### ISSUE TITLE
对网络图片添加水印时，部分图片含有红色蒙版

### ISSUE THREAD

**Issue by mwk719** [looly/hutool#1001]
### 版本情况

JDK版本：    Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
hutool版本： 4.5.13  最新版5.3.10未解决
本地：win10开发测试正常
服务器：CentOS Linux release 7.0.1406 存在问题

### 问题描述（包括截图）
1. 对网络图片添加水印时，部分图片含有红色蒙版

   - [原图](http://qn.minwk.top/img/1595232240113.jpg?w=800&h=800)
   - [红色蒙版图](https://haj.oss-cn-hangzhou.aliyuncs.com/t/shareImg/62e0e413a09d7c1a56461df1a7b51a8e.jpg)

2. 复现代码

```java
void pressImage(FilePath filePath, String pressUrl, Place place, Size srcSize, Size pressSize) {
		Image src = ImgUtil.scale(ImgUtil.read(FileUtil.file(filePath.getSrcPath())),
				srcSize.getWidth(), srcSize.getHeight());
		URL url = URLUtil.toUrlForHttp(pressUrl);
                // 怀疑是此处问题
		BufferedImage image = ImgUtil.read(url);
		Image press = ImgUtil.scale(image, pressSize.getWidth(), pressSize.getHeight());
		ImgUtil.pressImage(
				src,
				FileUtil.file(filePath.getOutPath()),
				//水印图片
				press,
				//x坐标修正值。 默认在中间，偏移量相对于中间偏移
				place.getX(),
				//y坐标修正值。 默认在中间，偏移量相对于中间偏移
				place.getY(),
				1f
		);
	}
```

**Comment by dahuoyzs** [comment]
JDK版本： Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
hutool版本： 5.3.10
本地：win10   不存在问题
服务器：CentOS  Linux VM_0_8_centos 3.10.0-514.26.2.el7.x86_64  不存在问题



### TestController.java

```java
@Slf4j
@RestController
public class TestController {

	@GetMapping("/testImg")
    public String testImg(){
        ImgUtil.read(new File("Sausages.jpg"));
        Image orgImage = ImgUtil.scale(ImgUtil.read(new File("Sausages.jpg")), 800, 800);
        Image logoImg = ImgUtil.scale(ImgUtil.read(new File("log.png")), 512, 512);
        Image image = ImgUtil.pressImage(orgImage, logoImg, 0, 0, 1f);
        ImgUtil.write(image,new File("SausagesHandler.jpg"));
        return "ok";
    }
}
```



### 服务器命令

```shell
[root@VM_0_8_centos testhutool]# ls
catalina.log  log.png  Sausages.jpg  testhutool.jar
[root@VM_0_8_centos testhutool]# curl 127.0.0.1:8080/testImg
ok[root@VM_0_8_centos testhutool]# ls
catalina.log  log.png  SausagesHandler.jpg  Sausages.jpg  testhutool.jar
[root@VM_0_8_centos testhutool]# cp SausagesHandler.jpg /home/bigfire/
[root@VM_0_8_centos testhutool]# uname
Linux
[root@VM_0_8_centos testhutool]# uname -a
Linux VM_0_8_centos 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@VM_0_8_centos testhutool]# java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
[root@VM_0_8_centos testhutool]# 

```



### Sausages.jpg

![Sausages](https://gitee.com/dahuoyzs/res/raw/master/img/aa.jpg)

### Log.png

![Log](https://gitee.com/dahuoyzs/res/raw/master/img/log.png)

### SausagesHandler.jpg

![SausagesHandler](https://gitee.com/dahuoyzs/res/raw/master/img/SausagesHandler.jpg)

**Comment by dahuoyzs** [comment]
会不会  是log图片要.png格式的？

**Comment by mwk719** [comment]
1. 我这边的log素材图就是.png格式
2. 很奇怪！用你发的代码和图片log生成的图片还是带有红色蒙版

![SausagesHandler](https://user-images.githubusercontent.com/34880212/89766837-6141cb80-db2b-11ea-897d-7c3220fcd696.jpg)

**Comment by mwk719** [comment]
> 会不会是log图片要.png格式的？
1. 我这边的log素材图就是.png格式
2. 很奇怪！用你发的代码和图片log生成的图片还是带有红色蒙版
![](http://qn.minwk.top/img/SausagesHandler.jpg)

**Comment by dahuoyzs** [comment]
这样的话，感觉和框架关系就不大了。。你有在不同版本的虚拟机里是过吗。你本地都可以了。那会不会是那个服务器上啥东西影响到了？这种问题的确难排查。

**Comment by mwk719** [comment]
> 这样的话，感觉和框架关系就不大了。。你有在不同版本的虚拟机里是过吗。你本地都可以了。那会不会是那个服务器上啥东西影响到了？这种问题的确难排查。

我们加了一段代码然后解决了这个问题
```java
private BufferedImage toBufferedImage(Image image) {
		if (image instanceof BufferedImage) {
			return (BufferedImage) image;
		}
		// This code ensures that all the pixels in the image are loaded
		image = new ImageIcon(image).getImage();
		BufferedImage bimage = null;
		GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
		try {
			int transparency = Transparency.OPAQUE;
			GraphicsDevice gs = ge.getDefaultScreenDevice();
			GraphicsConfiguration gc = gs.getDefaultConfiguration();
			bimage = gc.createCompatibleImage(image.getWidth(null),
					image.getHeight(null), transparency);
		} catch (HeadlessException e) {
			// The system does not have a screen
		}
		if (bimage == null) {
			// Create a buffered image using the default color model
			int type = BufferedImage.TYPE_INT_RGB;
			bimage = new BufferedImage(image.getWidth(null), image.getHeight(null), type);
		}
		// Copy image to buffered image
		Graphics2D g = bimage.createGraphics();

		// 增加透明度解决png透明图片会变黑的问题
		bimage = g.getDeviceConfiguration().createCompatibleImage(image.getWidth(null), image.getHeight(null), Transparency.TRANSLUCENT);
		g = bimage.createGraphics();

		// Paint the image onto the buffered image
		g.drawImage(image, 0, 0, null);
		g.dispose();
		image.flush();
		return bimage;
	}
```

**Comment by looly** [comment]
问题出在网络图片无法判断图片类型。

你图片是从网络上获取，获取下来是流而非文件，此时通过Img做变换Hutool就无法判断图片是png还是jpg，于是默认按照jpg处理（JPG使用RGB通道，PNG使用ARGB通道），通道不同，导致变色问题。

此类问题一般是在jpg上press一个png或者反之。

所以暂时无解，解决的办法一般是：

press对象通过调用`ImgUtil.toBufferedImage(img, imageType)` 指定下类型，即可避免此类问题。


--------------------------------------------

5.4.0会做小修改，pressImage方法会根据生成的图片类型做个转换，这样可以最大限度避免类似问题。

**Comment by mwk719** [comment]
> 问题出在网络图片无法判断图片类型。
> 
> 你图片是从网络上获取，获取下来是流而非文件，此时通过Img做变换Hutool就无法判断图片是png还是jpg，于是默认按照jpg处理（JPG使用RGB通道，PNG使用ARGB通道），通道不同，导致变色问题。
> 
> 此类问题一般是在jpg上press一个png或者反之。
> 
> 所以暂时无解，解决的办法一般是：
> 
> press对象通过调用`ImgUtil.toBufferedImage(img, imageType)` 指定下类型，即可避免此类问题。
> 
> 5.4.0会做小修改，pressImage方法会根据生成的图片类型做个转换，这样可以最大限度避免类似问题。

好的👍
