### ISSUE TITLE
老哥,这个并发量高的话会有严重问题呀,建议手动设置!

### ISSUE THREAD

**Issue by wl1092212424** [looly/hutool#1002]
/**
	 * 初始池大小
	 */
	private int corePoolSize;
	/**
	 * 最大池大小（允许同时执行的最大线程数）
	 */
	private int maxPoolSize = Integer.MAX_VALUE;
# 这个在并发量大的情况下会有很严重问题!

**Comment by looly** [comment]
你可以使用ExecutorBuilder自定义线程池。

**Comment by wl1092212424** [comment]
回复这么快的么?
