### ISSUE TITLE
HttpServerResponse 设置ContentType不生效

### ISSUE THREAD

**Issue by ooocici** [looly/hutool#1006]
### 版本情况

JDK版本：    openjdk_8_232
hutool版本： 5.3.10

### 问题描述（包括截图）

1. 复现代码

```java
HttpUtil.createServer(12345).addAction("/",(req,res)-> res.write("你瞅啥", ContentType.JSON.getValue()));
```

浏览器显示类容如下：
![image](https://user-images.githubusercontent.com/15642865/89484876-0ed27900-d7d2-11ea-95ad-e4801b6d6ed9.png)

Response Headers如下：
![image](https://user-images.githubusercontent.com/15642865/89484892-1c87fe80-d7d2-11ea-9eca-2cab21ac3bcc.png)

Response 内容如下：
![image](https://user-images.githubusercontent.com/15642865/89484919-2873c080-d7d2-11ea-9c90-1f1d0d895774.png)

**Comment by looly** [comment]
找到原因了，5.4.0修复此问题，感谢。

**Comment by ooocici** [comment]
> 找到原因了，5.4.0修复此问题，感谢。

什么原因捏。

**Comment by looly** [comment]
在调用setHeader方法调用前调用了sendResponse，因此头信息被忽略了。
