### ISSUE TITLE
在同一个文件流中通过ExcelReader获取多个sheet的数据时设置closeAfterRead无效

### ISSUE THREAD

**Issue by Charles2mx** [looly/hutool#1007]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9

```java
ExcelReader(InputStream bookStream, String sheetName, boolean closeAfterRead)
```
这里closeAfterRead设置为false，bookStream还是被apache 的poi关闭了。

**Comment by looly** [comment]
确实，WorkbookFactory.create方法读取流会自动关闭，没有注意。

5.4.0去除这个参数，感谢。
