### ISSUE TITLE
SpringUtil获取Bean异常，空指针

### ISSUE THREAD

**Issue by wuai1024** [looly/hutool#1010]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.3.10

### 问题描述（包括截图）

目前使用windows平台mvn package没问题，使用macOS mvn package就会出现这个空指针异常。

1. 复现代码

```java
private RedisUtil redisUtil = SpringUtil.getBean(RedisUtil.class);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

![image](https://user-images.githubusercontent.com/13379708/89773473-8be55180-db36-11ea-8f79-53fa614813b8.png)

**Comment by wuai1024** [comment]
系统：
1、windows 10 2004
2、macOS 10.15.6

jdk:
1、jdk11.0.8
2、jdk11.0.8

apache maven
1、3.6.3
2、3.6.3

除了系统，其他环境都一样

**Comment by wuai1024** [comment]
![image](https://user-images.githubusercontent.com/13379708/89845877-42d2e300-dbb2-11ea-9759-ab450f711671.png)

windows也用不了

**Comment by looly** [comment]
见文档：

https://hutool.cn/docs/#/extra/Spring/Spring%E5%B7%A5%E5%85%B7-SpringUtil

需要注册SpringUtil。

**Comment by wuai1024** [comment]
试过了，没用，springBoot启动的时候加上，或者在引用类上面加的，都为null

**Comment by wuai1024** [comment]
![image](https://user-images.githubusercontent.com/13379708/89862156-ef748b00-dbd9-11ea-9182-6ffa9444533d.png)

文档我看了，不是很详细，不知道具体加哪的

**Comment by looly** [comment]
加到配置的bean上。

可以百度下@Import注解

**Comment by wuai1024** [comment]
试过了的，2个注解我都试过了


你试下，在websocket中使用

**Comment by wuai1024** [comment]
![image](https://user-images.githubusercontent.com/13379708/89882056-df1fd880-dbf8-11ea-9cdc-33cc706e7467.png)

final和static 我也都试过了
