### ISSUE TITLE
需求: 希望增加MapUtil默认返回值

### ISSUE THREAD

**Issue by zhouhailin** [looly/hutool#1014]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.10（请确保最新尝试是否还有问题）

### 需求描述

希望新增 MapUtil.getStr(map, "key1", "defaultValue");

不知什么原因，没考虑该方法。

**Comment by looly** [comment]
5.4.0加入，感谢。之前有人提issue了。

你可以用MapUtil.createProxy(map).getStr完成。
