### ISSUE TITLE
需求:  StopWatch 的功能扩展

### ISSUE THREAD

**Issue by Henrich-Tong** [looly/hutool#1018]
1. 支持任意多个任务同时计时（线程安全）
2. 增加一个对外 api  `public void (String taskName, Runnable task)`
3. 合并名称相同的任务
4. 输出支持多种排序方式，比如：按任务总时长，按任务总次数，按任务平均时长等

感觉这种需求还是比较普遍的，尤其在做性能分析时更是不可避免。

**Comment by looly** [comment]
StopWatch来自于Spring框架，这些需求是否考虑提个pr？
