### ISSUE TITLE
获取本月第一天的方法

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#1019]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.10

### 问题描述（包括截图）

前端日期通过URL传递到后端，2020-07-02T00:00:00+08:00，通过DateUtil.parse方法转换成UTC格式，
![image](https://user-images.githubusercontent.com/14087655/90364382-ce5ae100-e096-11ea-8ffb-8361a3ed5109.png)
然后调用DateUtil.beginOfMonth，格式还是UTC，但是日期变成了2020-07-01 00:00:00，这样实际转成东八区的话是2020-07-01 08:00:00，正常如果是UTC的话是不是应该是2020-06-30 16:00:00？
![image](https://user-images.githubusercontent.com/14087655/90364734-2e518780-e097-11ea-8bd6-db6618c69e06.png)

1. 复现代码

Date month = DateUtil.beginOfMonth(date)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
DateUtil转换后为DateTime对象，这个对象本身附带一个时区对象。

任何日期计算和时区是不关联的，toString也是，因此所谓beginOfXXX，其实就是指定时区的开始事件，和时区无关。

要想体现时区，需要调用format方法格式化为UTC事件。
