### ISSUE TITLE
需求新增：StrUtil.firstIfNotNull

### ISSUE THREAD

**Issue by zhouhailin** [looly/hutool#1020]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

可以的话麻烦新增：
StrUtil.firstIfNotNull(String... strs)  
StrUtil.firstIfNotBlank(String... strs)
经常用到

**Comment by looly** [comment]
5.4.1增加方法：

StrUtil.firstNonNull
StrUtil.firstNonEmpty
StrUtil.firstNonBlank


当然，现有方法已经可以实现firstNonNull：

```java
ArrayUtil.firstNonNull
```
