### ISSUE TITLE
ZipUtil解压完可以不带目录吗？

### ISSUE THREAD

**Issue by jovi521** [looly/hutool#1022]
### 版本情况

JDK版本：    jdk1.8.0_261
hutool版本： 5.3.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
我打开我的zip明明没有目录，但是解压完之后会自动加一个目录，请问大神们可以去掉这个目录吗？
1. 复现代码

```java
File file = new File("D:\\Data\\radarPhasedArray\\00001\\20200628\\CR\\20200628_000103.00.010.001_R1.zip");
File unzip = ZipUtil.unzip(file);
System.out.println(unzip.getName() + " : " + unzip.length());
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可以使用`public static File unzip(ZipFile zipFile, File outFile)`自顶一下输出目录为当前目录。
