### ISSUE TITLE
CharUtil.isBlankChar 方法中空白字符不完善

### ISSUE THREAD

**Issue by lambert0529** [looly/hutool#1024]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
 CharUtil.isBlankChar 方法中空白字符不完善
1. 复现代码
![image](https://user-images.githubusercontent.com/23491308/90511299-d9913800-e18e-11ea-8656-3a8a266b524c.png)

这里缺少对ASCII码值160 的空格过滤,其编码为\u00A0
```
final char c1 = ' '; //db里的空格
final char c2 = ' '; //手动输入的空格
System.out.println((int)c1); //160
System.out.println((int)c2); //32
```

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/90611703-a8ba0d00-e239-11ea-9a74-586481ad43cb.png)

经过测试识别正常。

```java
Character.isWhitespace
```
方法已经包含这个字符的识别了。
