### ISSUE TITLE
文件跟随 Tailer 出现重复

### ISSUE THREAD

**Issue by happy888liu** [looly/hutool#1027]
### 版本情况

JDK版本：    jdk1.8
hutool版本：5.3.10

### 问题描述（包括截图）
使用Tailer实现文件跟随，发现部分内容会出现重复，图片中左边的数据之前已经出现过
图片左边为跟随的结果，右边为原文件内容
![image](https://user-images.githubusercontent.com/10581712/90777276-c5d00800-e32d-11ea-81ce-50c927902bec.png)
![image](https://user-images.githubusercontent.com/10581712/90777529-1fd0cd80-e32e-11ea-8d66-58ea8962c354.png)

**Comment by looly** [comment]
几个原因：

1、可能你的数据出现了删除的情况，或者清空重新写入
2、尝试构造时指定period增加检查延迟

**Comment by happy888liu** [comment]
谢谢，十分感谢
