### ISSUE TITLE
FTP示例代码错误

### ISSUE THREAD

**Issue by GGBOND1024** [looly/hutool#1028]
//匿名登录（无需帐号密码的FTP服务器）
Ftp ftp = new Ftp("172.0.0.1");
//进入远程目录
ftp.cd("/opt/upload");
//上传本地文件
ftp.upload("/opt/upload", FileUtil.file("e:/test.jpg"));
//下载远程文件
ftp.download("/opt/upload", "test.jpg", FileUtil.file("e:/test2.jpg"));

//关闭连接
ftp.close();

这里的目录不是根目录的需要去掉第一个/
ftp.cd("opt/upload");
ftp.upload("opt/upload", FileUtil.file("e:/test.jpg"));

**Comment by looly** [comment]
这只是个示例而已，路径并不重要。
