### ISSUE TITLE
建议db.setting增加数据连接池类型配置

### ISSUE THREAD

**Issue by lkhtest** [looly/hutool#1029]
### 版本情况

JDK版本：    jdk_8_231
hutool版本： 5.4.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

因为引入了 spring-data-jpa，在不排除HikariCP的情况下，无法使用Druid，为啥不在setting中增加一个type参数，可以手动指定数据池？

目前是否有别的方法可以手动指定数据池？

**Comment by looly** [comment]
可以调用DSFactory.setCurrentDSFactory自定义全局的数据库连接池工厂。
