### ISSUE TITLE
ReferenceUtil类软引用SoftReference错误写成弱引用WeakReference

### ISSUE THREAD

**Issue by McdullFei** [looly/hutool#103]
ReferenceUtil  47行
	public static <T> Reference<T> create(ReferenceType type, T referent, ReferenceQueue<T> queue) {
		switch (type) {
		case SOFT:
			return new WeakReference<>(referent);  // SoftReference
		case WEAK:
			return new WeakReference<>(referent);
		case PHANTOM:
			return new PhantomReference<T>(referent, queue);
		default:
			return null;
		}
	}

**Comment by looly** [comment]
pr已回复。十分感谢。
