### ISSUE TITLE
建议图片操作添加增加边框操作

### ISSUE THREAD

**Issue by oliverliu365** [looly/hutool#1033]
建议图片操作添加增加边框操作

**Comment by daidai21** [comment]
`hutool-captcha` 这个模块吗？ @Liuk2018

**Comment by looly** [comment]
并不是，是ImgUtil或者Img。

加边框理论上描边画线即可，但是我没仔细研究怎么弄，这个issue等等看。

**Comment by szmhbvrg** [comment]
> 并不是，是ImgUtil或者Img。
> 
> 加边框理论上描边画线即可，但是我没仔细研究怎么弄，这个issue等等看。

能否加一个SqlServer2008的分页dialect？

**Comment by looly** [comment]
5.4.1增加stroke方法：

```java
Img.from(FileUtil.file("test.png"))
	// 颜色，粗细
	.stroke(Color.BLACK, 2f)
	.write(FileUtil.file("stroke_result.png"));
```

如果你想自定义线条类型，可以自己构建`BasicStroke`对象，然后使用

```java
stroke(Color color, Stroke stroke)
```
