### ISSUE TITLE
字符串工具类的indexOf疑问

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#1038]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/14087655/91121733-10090e80-e6cb-11ea-8f1b-8c5f3a8f37d5.png)
indexOf的方法，如果是字符串，直接调用indexOf，这样如果字符串是空的话会报错，我看其它的都有判断是否为空，这是有其它的考虑所以不能判断是否为空吗？

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by HHHQiang** [comment]
你说的“字符串是空”，是null还是""（length 为0）的字符串？

**Comment by reixuemin** [comment]
> 你说的“字符串是空”，是null还是""（length 为0）的字符串？

null

**Comment by HHHQiang** [comment]
> > 你说的“字符串是空”，是null还是""（length 为0）的字符串？
> 
> null

这个确实很尴尬，毕竟null 空指针，返回-1好像也不太合理（滑稽

**Comment by reixuemin** [comment]
> > > 你说的“字符串是空”，是null还是""（length 为0）的字符串？
> > 
> > 
> > null
> 
> 这个确实很尴尬，毕竟null 空指针，返回-1好像也不太合理（滑稽

但是有其它的indexOf方法是有判断的，如果是null则返回-1

    public static int indexOf(CharSequence str, CharSequence searchStr, int fromIndex, boolean ignoreCase) {
        if (str != null && searchStr != null) {
            if (fromIndex < 0) {
                fromIndex = 0;
            }

            int endLimit = str.length() - searchStr.length() + 1;
            if (fromIndex > endLimit) {
                return -1;
            } else if (searchStr.length() == 0) {
                return fromIndex;
            } else if (!ignoreCase) {
                return str.toString().indexOf(searchStr.toString(), fromIndex);
            } else {
                for(int i = fromIndex; i < endLimit; ++i) {
                    if (isSubEquals(str, i, searchStr, 0, searchStr.length(), true)) {
                        return i;
                    }
                }

                return -1;
            }
        } else {
            return -1;
        }
    }

**Comment by HHHQiang** [comment]
> > > > 你说的“字符串是空”，是null还是""（length 为0）的字符串？
> > > 
> > > 
> > > null
> > 
> > 
> > 这个确实很尴尬，毕竟null 空指针，返回-1好像也不太合理（滑稽
> 
> 但是有其它的indexOf方法是有判断的，如果是null则返回-1
> 
> ```
> public static int indexOf(CharSequence str, CharSequence searchStr, int fromIndex, boolean ignoreCase) {
>     if (str != null && searchStr != null) {
>         if (fromIndex < 0) {
>             fromIndex = 0;
>         }
> 
>         int endLimit = str.length() - searchStr.length() + 1;
>         if (fromIndex > endLimit) {
>             return -1;
>         } else if (searchStr.length() == 0) {
>             return fromIndex;
>         } else if (!ignoreCase) {
>             return str.toString().indexOf(searchStr.toString(), fromIndex);
>         } else {
>             for(int i = fromIndex; i < endLimit; ++i) {
>                 if (isSubEquals(str, i, searchStr, 0, searchStr.length(), true)) {
>                     return i;
>                 }
>             }
> 
>             return -1;
>         }
>     } else {
>         return -1;
>     }
> }
> ```

hhhh 那估计就是这里忘了处理了，做个修复，然后提pr把 hhh

**Comment by daidai21** [comment]
> > > > > 你说的“字符串是空”，是null还是""（length 为0）的字符串？
> > > > 
> > > > 
> > > > null
> > > 
> > > 
> > > 这个确实很尴尬，毕竟null 空指针，返回-1好像也不太合理（滑稽
> > 
> > 
> > 但是有其它的indexOf方法是有判断的，如果是null则返回-1
> > ```
> > public static int indexOf(CharSequence str, CharSequence searchStr, int fromIndex, boolean ignoreCase) {
> >     if (str != null && searchStr != null) {
> >         if (fromIndex < 0) {
> >             fromIndex = 0;
> >         }
> > 
> >         int endLimit = str.length() - searchStr.length() + 1;
> >         if (fromIndex > endLimit) {
> >             return -1;
> >         } else if (searchStr.length() == 0) {
> >             return fromIndex;
> >         } else if (!ignoreCase) {
> >             return str.toString().indexOf(searchStr.toString(), fromIndex);
> >         } else {
> >             for(int i = fromIndex; i < endLimit; ++i) {
> >                 if (isSubEquals(str, i, searchStr, 0, searchStr.length(), true)) {
> >                     return i;
> >                 }
> >             }
> > 
> >             return -1;
> >         }
> >     } else {
> >         return -1;
> >     }
> > }
> > ```
> 
> hhhh 那估计就是这里忘了处理了，做个修复，然后提pr把 hhh

5.4.0版本中没有找到这个函数呀，全文搜索没搜到。。。

**Comment by reixuemin** [comment]
> > > > > > 你说的“字符串是空”，是null还是""（length 为0）的字符串？
> > > > > 
> > > > > 
> > > > > null
> > > > 
> > > > 
> > > > 这个确实很尴尬，毕竟null 空指针，返回-1好像也不太合理（滑稽
> > > 
> > > 
> > > 但是有其它的indexOf方法是有判断的，如果是null则返回-1
> > > ```
> > > public static int indexOf(CharSequence str, CharSequence searchStr, int fromIndex, boolean ignoreCase) {
> > >     if (str != null && searchStr != null) {
> > >         if (fromIndex < 0) {
> > >             fromIndex = 0;
> > >         }
> > > 
> > >         int endLimit = str.length() - searchStr.length() + 1;
> > >         if (fromIndex > endLimit) {
> > >             return -1;
> > >         } else if (searchStr.length() == 0) {
> > >             return fromIndex;
> > >         } else if (!ignoreCase) {
> > >             return str.toString().indexOf(searchStr.toString(), fromIndex);
> > >         } else {
> > >             for(int i = fromIndex; i < endLimit; ++i) {
> > >                 if (isSubEquals(str, i, searchStr, 0, searchStr.length(), true)) {
> > >                     return i;
> > >                 }
> > >             }
> > > 
> > >             return -1;
> > >         }
> > >     } else {
> > >         return -1;
> > >     }
> > > }
> > > ```
> > 
> > 
> > hhhh 那估计就是这里忘了处理了，做个修复，然后提pr把 hhh
> 
> 5.4.0版本中没有找到这个函数呀，全文搜索没搜到。。。

![image](https://user-images.githubusercontent.com/14087655/91382501-74a7a300-e85c-11ea-9ea6-bd93d5e71af6.png)
我看是hutool-all-5.4.0，难道idea有问题？

**Comment by looly** [comment]
嗯，这个其实是这样的:

传入null就不会按照String处理，直接调用StrUtil.indexOf判断，这里没做null的空指针判断。

5.4.1修复此问题，感谢。

> PS：你的IDEA可以考虑关联源码。
