### ISSUE TITLE
LomBok可以考虑试用下？！

### ISSUE THREAD

**Issue by daidai21** [looly/hutool#1039]
https://github.com/looly/hutool/blob/v5-master/hutool-system/src/main/java/cn/hutool/system/oshi/CpuInfo.java#L60-L114

```java
import lombok.Data;

@Data // 只需要加上这就好，就不需要写大量的getter和setter方法了
public class CpuInfo {

	/**
	 * cpu核心数
	 */
	private Integer cpuNum;

	/**
	 * CPU总的使用率
	 */
	private double toTal;

	/**
	 * CPU系统使用率
	 */
	private double sys;

	/**
	 * CPU用户使用率
	 */
	private double used;

	/**
	 * CPU当前等待率
	 */
	private double wait;

	/**
	 * CPU当前空闲率
	 */
	private double free;

	/**
	 * CPU型号信息
	 */
	private String cpuModel;

	public CpuInfo() {
	}

	public CpuInfo(Integer cpuNum, double toTal, double sys, double used, double wait, double free, String cpuModel) {
		this.cpuNum = cpuNum;
		this.toTal = toTal;
		this.sys = sys;
		this.used = used;
		this.wait = wait;
		this.free = free;
		this.cpuModel = cpuModel;
	}
}
```

**Comment by looly** [comment]
Lombok不适合在工具类或者框架中提供，你可以自行使用。

**Comment by caofanCPU** [comment]
> https://github.com/looly/hutool/blob/v5-master/hutool-system/src/main/java/cn/hutool/system/oshi/CpuInfo.java#L60-L114
> 
> ```java
> import lombok.Data;
> 
> @Data // 只需要加上这就好，就不需要写大量的getter和setter方法了
> public class CpuInfo {
> 
> 	/**
> 	 * cpu核心数
> 	 */
> 	private Integer cpuNum;
> 
> 	/**
> 	 * CPU总的使用率
> 	 */
> 	private double toTal;
> 
> 	/**
> 	 * CPU系统使用率
> 	 */
> 	private double sys;
> 
> 	/**
> 	 * CPU用户使用率
> 	 */
> 	private double used;
> 
> 	/**
> 	 * CPU当前等待率
> 	 */
> 	private double wait;
> 
> 	/**
> 	 * CPU当前空闲率
> 	 */
> 	private double free;
> 
> 	/**
> 	 * CPU型号信息
> 	 */
> 	private String cpuModel;
> 
> 	public CpuInfo() {
> 	}
> 
> 	public CpuInfo(Integer cpuNum, double toTal, double sys, double used, double wait, double free, String cpuModel) {
> 		this.cpuNum = cpuNum;
> 		this.toTal = toTal;
> 		this.sys = sys;
> 		this.used = used;
> 		this.wait = wait;
> 		this.free = free;
> 		this.cpuModel = cpuModel;
> 	}
> }
> ```

**工具也应该与时俱进**
来这里，lombok，springboot-starts都支持，把常见的中间件服务当工具进行封装

[**所见即所得**](https://github.com/caofanCPU)

让开发人员更专注于业务开发，这基本是共识
