### ISSUE TITLE
ExcelUtil问题建议

### ISSUE THREAD

**Issue by x270944070** [looly/hutool#1040]
今天用hutool工具的时候发现了一个问题。
```java
    ExcelWriter writer = new ExcelWriter();
    writer.setHeaderAlias(headerAlias);
    writer.write(dataList, true);
    writer.autoSizeColumnAll();
```
dataList是个List数据，但是由于对象里面的数据为Empty，导致空指针。原因在于最后一行`writer.autoSizeColumnAll()`。我们看下里面的代码：
__cn.hutool.poi.excel.ExcelBase#getColumnCount(int)__
```java
    	public int getColumnCount(int rowNum) {
		// getLastCellNum方法返回序号+1的值
		return this.sheet.getRow(rowNum).getLastCellNum();
	}
```
`this.sheet.getRow(rowNum)`为null

**Comment by daidai21** [comment]
这里`writer.autoSizeColumnAll();`调用了hutool中的
https://github.com/looly/hutool/blob/v5-master/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelWriter.java#L239
然后调用了`getColumnCount()`，也就是
https://github.com/looly/hutool/blob/v5-master/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelBase.java#L388
然后调用了
https://github.com/looly/hutool/blob/v5-master/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelBase.java#L402

测试代码：
```java
package poi;


/**
 * https://github.com/looly/hutool/issues/1040
  */


import cn.hutool.poi.excel.ExcelUtil;
import cn.hutool.poi.excel.ExcelWriter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;


public class issues1040 {
	public static void main(String[] args) {
		HashMap<String, String> headerAlias = new HashMap<String, String>();
		headerAlias.put("name", "姓名");
		headerAlias.put("age", "年龄");
		headerAlias.put("score", "分数");
		headerAlias.put("isPass", "是否通过");
		headerAlias.put("examDate", "考试时间");

		ExcelWriter writer = new ExcelWriter("./writeTest.xls");

		writer.setHeaderAlias(headerAlias);

		List<String> dataList = new ArrayList<String>();

		writer.write(dataList, true);

		writer.autoSizeColumnAll();
	}
}

```

应该在`public int getColumnCount(int rowNum) {`这个方法的开始先验证文件是否为空再开始计算获取`sheet.getRow(0);`
@x270944070 @looly

**Comment by daidai21** [comment]
这么搞没问题的话，我PR下？ @looly

**Comment by looly** [comment]
试下最新版本：

5.4.0

代码中https://github.com/looly/hutool/blob/v5-master/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelBase.java#L402

已经对null做了判空，sheet不可能为null。

**Comment by looly** [comment]
> 这么搞没问题的话，我PR下？ @looly

你的测试我使用最新版本测试没问题，文件是否为空不影响空指针，因为Writer创建后会自动创建一个sheet。

**Comment by x270944070** [comment]
嗯嗯看到了，升级版本就欧克

**Comment by x270944070** [comment]
> > 这么搞没问题的话，我PR下？ @looly
> 
> 你的测试我使用最新版本测试没问题，文件是否为空不影响空指针，因为Writer创建后会自动创建一个sheet。

嗯嗯看到了，升级版本就欧克
