### ISSUE TITLE
建议添加JWT TOKEN 工具类

### ISSUE THREAD

**Issue by Phukety** [looly/hutool#1041]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

项目集成JWT的时候，需要重复写很多工具类，希望能添加有关jwt的工具类

**Comment by looly** [comment]
这个考虑jjwt，或者欢迎贡献相关工具类。
