### ISSUE TITLE
StrUtil 中，可变参数导致的方法调用不明确

### ISSUE THREAD

**Issue by chendifan** [looly/hutool#1042]
JDK版本：    openjdk_11
hutool版本： 5.4.0

![20200827143451](https://user-images.githubusercontent.com/22953986/91400850-f60a3000-e872-11ea-8cef-689a7d75db19.png)

**Comment by looly** [comment]
这个在JDK8中不存在问题，高版本JDK可能有问题，5.4.1改为`wrapAllWithPairIfMissing`方法。
