### ISSUE TITLE
setFieldSeparator字段分隔符只能接收char类型的参数吗

### ISSUE THREAD

**Issue by rockbaby04** [looly/hutool#1043]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.3.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
往csv文件写数据的时候，有一个需求是字段的分隔符需要是多字符的，但是setFieldSeparator设置字段分隔符的方法只能接收char类型的参数，有什么办法可以解决吗

**Comment by looly** [comment]
这个没办法，按照CSV规范应该是逗号。
