### ISSUE TITLE
setFieldSeparator字段分隔符方法的接收参数为什么只能是char类型呢？

### ISSUE THREAD

**Issue by rockbaby04** [looly/hutool#1044]
### 问题描述（包括截图）

如果字段分隔符是多字符怎么处理呢？

**Comment by looly** [comment]
Hutool的CsvUtil参考了`FastCSV`项目，因此没有考虑多字符分割的情况。

而且CSV本身多字符分割也没有这样的规范吧？

Hutool不考虑多字符分割的情况。
