### ISSUE TITLE
 No pinyin jar found ! Please add one of it to your project !

### ISSUE THREAD

**Issue by a1265137718** [looly/hutool#1046]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

``` java
PinyinUtil.getFirstLetter()
```

2. 堆栈信息
java.lang.RuntimeException: cn.hutool.extra.template.TemplateException: No pinyin jar found ! Please add one of it to your project !
	at cn.hutool.core.lang.SimpleCache.get(SimpleCache.java:83)
	at cn.hutool.core.lang.Singleton.get(Singleton.java:53)
	at cn.hutool.extra.pinyin.engine.PinyinFactory.get(PinyinFactory.java:23)
	at cn.hutool.extra.pinyin.PinyinUtil.getEngine(PinyinUtil.java:21)
	at cn.hutool.extra.pinyin.PinyinUtil.getFirstLetter(PinyinUtil.java:62)

**Comment by SuperMaskv** [comment]
并不是一个bug，请仔细阅读文档，参考：
[https://www.hutool.cn/docs/#/extra/%E6%8B%BC%E9%9F%B3/%E6%8B%BC%E9%9F%B3%E5%B7%A5%E5%85%B7-PinyinUtil](url)

**Comment by SuperMaskv** [comment]
> ### 版本情况
> JDK版本： openjdk_8_201
> hutool版本： 5.4.0（请确保最新尝试是否还有问题）
> 
> ### 问题描述（包括截图）
> 1. 复现代码
> 
> ```java
> PinyinUtil.getFirstLetter()
> ```
> 
> 1. 堆栈信息
>    java.lang.RuntimeException: cn.hutool.extra.template.TemplateException: No pinyin jar found ! Please add one of it to your project !
>    at cn.hutool.core.lang.SimpleCache.get(SimpleCache.java:83)
>    at cn.hutool.core.lang.Singleton.get(Singleton.java:53)
>    at cn.hutool.extra.pinyin.engine.PinyinFactory.get(PinyinFactory.java:23)
>    at cn.hutool.extra.pinyin.PinyinUtil.getEngine(PinyinUtil.java:21)
>    at cn.hutool.extra.pinyin.PinyinUtil.getFirstLetter(PinyinUtil.java:62)

并不是一个bug，请仔细阅读文档，参考：
[https://www.hutool.cn/docs/#/extra/%E6%8B%BC%E9%9F%B3/%E6%8B%BC%E9%9F%B3%E5%B7%A5%E5%85%B7-PinyinUtil](url)
