### ISSUE TITLE
请问题一下ExcelWriter里面如何设置文字的对齐方式，现在默认是居中的，有些列是要求左对齐

### ISSUE THREAD

**Issue by xiaofuliang** [looly/hutool#1051]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

**Comment by looly** [comment]
使用`writer.getStyleSet().setAlign()`方法设置即可。

**Comment by xiaofuliang** [comment]
@looly 有独立设置每个列的对齐方式吗，这个是针对全部的对齐方式吧？设置后所有的都变了，现在是想某些列左对齐，有些居中对齐

**Comment by looly** [comment]
这个真没有，除非单独创建style
