### ISSUE TITLE
AES加密建议增加可选参数

### ISSUE THREAD

**Issue by xiaowuzimaxhub** [looly/hutool#1052]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.4.0

### 问题描述（包括截图）

AES加密建议增加可选参数,另外加密数据块使用多少位，还有偏移量没有说明。

```java
/** 默认的AES加密方式：AES/CBC/PKCS5Padding */
	AES("AES"), 
```

**Comment by looly** [comment]
偏移向量可以使用`setIv`方法设置。

块大小使用`cipher.getBlockSize()`方法获取。
