### ISSUE TITLE
ExcelUtil.read07BySax 读取未打开过的excel会读取不到内容

### ISSUE THREAD

**Issue by jason2015lxj** [looly/hutool#1056]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
String file = "test.xlsx";
  ExcelUtil.read07BySax(file, 0, new RowHandler() {
            @Override
            public void handle(int sheetIndex, long rowIndex, List<Object> list) {
                System.out.println("sheetIndex:" +sheetIndex+" rowIndex:" + rowIndex + " list.size:" + list.size());
                System.out.println(JSONObject.toJSONString(list));
            }
        });
如上代码，如果sheetIndex传-1则可以读取excel数据，但是如果只想读取第一个sheet，传sheetIndex为0，则如果改excel未曾打开过，就读取不到数据，如果编辑一下，然后再执行就可以读出来

**Comment by looly** [comment]
sax方式读取Excel并不是使用index，而是使用rid，程序生成的excel有可能这个rid不是0。

**Comment by jason2015lxj** [comment]
那么能否修改一下，不使用rid这种读取方式呢？因为要解析的excel不一定来源何处，有时就会出现这种问题，无法预估

**Comment by jason2015lxj** [comment]
XMLReader parser = this.fetchSheetParser(sst, (ISaxRowRead)rowRead);
            Iterator<InputStream> sheets = xssfReader.getSheetsData();
            int sheetIndex = 0;

            while(sheets.hasNext() && sheetIndex < params.getSheetNum()) {
                ++sheetIndex;
                InputStream sheet = (InputStream)sheets.next();
                InputSource sheetSource = new InputSource(sheet);
                parser.parse(sheetSource);
                sheet.close();
            }
如这种写法呢？

**Comment by looly** [comment]
之前想过，但是考虑到要兼容旧版本，如此改必然会造成sax读取兼容性问题。
