### ISSUE TITLE
SoapClient中怎么去添加请求头信息在参考文档中没看到描述

### ISSUE THREAD

**Issue by HackerStudy** [looly/hutool#1058]
![image](https://user-images.githubusercontent.com/37321393/92084687-590f4000-edfa-11ea-9aa6-527cf3da6a0a.png)

![image](https://user-images.githubusercontent.com/37321393/92084703-60364e00-edfa-11ea-8c8e-7a8ca3d5f1e6.png)

**Comment by looly** [comment]
调用setSOAPHeader方法。
