### ISSUE TITLE
JschUtil 执行shell命令无返回

### ISSUE THREAD

**Issue by hexw** [looly/hutool#1067]
### 版本情况

JDK版本：    jdk1.8.191
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JschUtil.execByShell 执行shell命令无返回
由于方法execByShell  中 立即读取InputStream in.available() 为0 跳过读取数据,InputStream 需要等待一会才有数据

1. 复现代码

```java
		Session session =  JschUtil.getSession("192.168.60.120", 22, "**", "**");
		String exereturn = JschUtil.execByShell(session, "df -h;\n exit \n", Charset.forName("UTF-8"));
		JschUtil.close(session);
		System.out.println("exereturn:"+exereturn);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
使用exec方法。

**Comment by NeverMore93** [comment]
> 使用exec方法。

execByShell 是用来做什么的？

**Comment by looly** [comment]
这个会读取环境变量。

**Comment by NeverMore93** [comment]
> 这个会读取环境变量。

这不make sense吧，如果这个方法只是exe的时候读取环境变量，但是在执行的时候也不应该报错或者没返回值啊

**Comment by looly** [comment]
> > 这个会读取环境变量。
> 
> 这不make sense吧，如果这个方法只是exe的时候读取环境变量，但是在执行的时候也不应该报错或者没返回值啊

确实，没注意到提问者的那句`InputStream in.available() 为0 跳过读取数据,InputStream 需要等待一会才有数据`

**Comment by looly** [comment]
问题出在错误的使用了`in.available()`导致的问题，5.5.3修复此问题，感谢。
