### ISSUE TITLE
关于Convert.toIntArray的疑问

### ISSUE THREAD

**Issue by GitHubXiaoSiyuan** [looly/hutool#1071]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

### 单纯的疑问

        String[] strings = {"1","2","3","4","5"};
        Integer[] array = Convert.toIntArray(strings);
toIntArray我以为是int数组，而不是Integer数组。（可能是个人理解的问题）
为什么不提供转换为int数组的方法？（单纯的好奇)

**Comment by GitHubXiaoSiyuan** [comment]
①toIntArray让我想到int[]，而不是Integer[]②为什么没有转换为int[]的方法

**Comment by looly** [comment]
```java
int[] intArray = Convert.convert(int[].class, b);
```

可以用这个。原始类型是单独转换的。

**Comment by looly** [comment]
名字这个问题确实是，但是优先考虑包装类型，原始类型最早并没考虑。
