### ISSUE TITLE
反序列化时处理下划线的逻辑导致另一个问题

### ISSUE THREAD

**Issue by ReiZ-X** [looly/hutool#1075]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Hutool在反序列化时，反射获取到的字段名，从jsonobject中查同名的数据，如果找不到：
![image](https://user-images.githubusercontent.com/38411172/92876680-f989e380-f43c-11ea-902d-852a1a36ebcd.png)
最终调用StrUtil的toSymbolCase，这个方法的处理，对于大写+数字的这种处理不友好。

正常的情况下，对于OrderNo这样的字段JSONUtil是不反序列化的，但是对于F2这种的字段又是反序列的。

PS：fastjson是都支持

1. 复现代码

 @org.junit.Test
    public void test() throws Exception {
       /* ObjA o = new ObjA();
        o.setF1("f1");
        o.setOrderNo("f2");
        String s = JSON.toJSONString(o);
        System.out.println(s);
        System.out.println(JSONUtil.toJsonStr(o));*/
//{"f1":"f1","orderNo":"f2"}
        String s = "{\"f1\":\"f1\",\"F2\":\"f2\",\"fac\":\"fac\"}";

        ObjA oa = JSON.parseObject(s, ObjA.class);
        System.out.println(oa);

        ObjA o2 = JSONUtil.toBean(s, ObjA.class);
        System.out.println(o2);

        System.out.println(StrUtil.toSymbolCase("F123", '_'));
        System.out.println(StrUtil.toSymbolCase("FAC", '_'));
        System.out.println(StrUtil.toSymbolCase("fac", '_'));
        System.out.println(StrUtil.toSymbolCase("facAbc", '_'));

    }

    @Data
    public static class ObjA {
        private String f1;
        private String F2;
        private String FAC;
    }

//输出
Test.ObjA(f1=f1, F2=f2, FAC=fac)
Test.ObjA(f1=f1, F2=f2, FAC=null)
f123
FAC
fac
fac_abc

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
在你例子中应该不是下划线的问题，二是大小写的问题：

例子中`fac`是小写，ObjA中定义的FAC为大写，因此为null。

你可以：

```java
String s = "{\"f1\":\"f1\",\"F2\":\"f2\",\"fac\":\"fac\"}";
ObjA o2 = JSONUtil.parseObj(s, JSONConfig.create().setIgnoreCase(true)).toBean(ObjA.class);
```

**Comment by ReiZ-X** [comment]
why fac can not be deserialized 

> 在你例子中应该不是下划线的问题，二是大小写的问题：
> 
> 例子中`fac`是小写，ObjA中定义的FAC为大写，因此为null。
> 
> 你可以：
> 
> ```java
> String s = "{\"f1\":\"f1\",\"F2\":\"f2\",\"fac\":\"fac\"}";
> ObjA o2 = JSONUtil.parseObj(s, JSONConfig.create().setIgnoreCase(true)).toBean(ObjA.class);
> ```

why fac can not be deserialized to FAC by default, but f2 can deserialized to F2。That's my question.

**Comment by looly** [comment]
原因和setXXX匹配有关：

json中找到`f2`字段，然后查找`setF2`方法，`F2`字段的setter方法刚好也是`setF2`，所以有值。

fac则不同，对应的setter方法是`setFac`，这个方法在bean中无，因此为null。

fastjson默认的匹配规则和hutool略有不同，因此结果有差别。

**Comment by looly** [comment]
我好像明白你的意思了……

你意思toUnderlineCase中转换弄巧成拙正好匹配到字段了……

**Comment by looly** [comment]
5.4.3修复此问题。

此问题的根源还在`StrUtil.toSymbolCase`，对于大写+数字转换错误导致的：

原来是：`H2` -> `h2`，5.4.3修复后为`H2` -> `H2`。

```java
final String jsonStr = "{\"f1\":\"f1\",\"f2\":\"f2\",\"fac\":\"fac\"}";
ObjA o2 = JSONUtil.toBean(jsonStr, ObjA.class);
Assert.assertNull(o2.getFAC());
Assert.assertNull(o2.getF2());
```

争取的应该是fac和f2都不匹配。

再次感谢你的issue。

> PS: 最新脑袋不灵光，理解问题有点儿慢，哈哈。
```
