### ISSUE TITLE
希望Console.log能支持“无模板，多变量输入”的模式

### ISSUE THREAD

**Issue by hifong45** [looly/hutool#1077]
参考js 中 console.log 实现结果，希望支持这样的模式：
Console.log("hello", "java", "!");
变量间自动用空格分隔即可，可以少写很多{}。

目前我自定义的方法： 判断第一个入参如果是 String，并且含有 {}，就说明是 模板。
代码参看如下：

`public static void line(Object obj0, Object... input) {
		if(input.length == 0) {
			Console.print(obj0);
			return;
		}
		
		// 如果第一个是字符串，并且包含{}，则直接给Console库
		if(obj0 instanceof String && ((String)obj0).indexOf("{}") > 0) {
			Console.print((String)obj0, input);
			return;
		}
		Console.print(obj0);
		Console.print(" {} ".repeat(input.length-1) + "{}", input);
	}
`

**Comment by looly** [comment]
5.4.3增加支持，感谢。
