### ISSUE TITLE
刚需: TimedCache(AbstractCache) 添加 public V get(K key, Func0<V> supplier, boolean isUpdateLastAccess) 方法

### ISSUE THREAD

**Issue by qaz4042** [looly/hutool#1080]
### 版本情况

JDK版本：    1.8.0_151
hutool版本： 5.4.2

1.缓存一般都会有时间(只是长短)
2.例如系统参数放缓存,希望能3分钟刷新一次,而不是等3分钟没人get的时候再去刷新
   public V get(K key, Func0<V> supplier) 使用上很简便还不用考虑太多并发因素,但不满足使用场景

**Comment by looly** [comment]
5.4.3增加此方法，感谢。

**Comment by qaz4042** [comment]
稳的
