### ISSUE TITLE
Aes 无法对小于16位字符串加密

### ISSUE THREAD

**Issue by fengsuiyuan** [looly/hutool#1081]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.2

### 问题描述（包括截图）
该问题之前说是已解决
之前问题地址 https://gitee.com/loolly/hutool/issues/I11YBS
Aes 加密报input is too short 在最新版本又出现了 之间作者说是盐iv导致的块大小问题。

**Comment by looly** [comment]
原问上也已回复：

短密钥需要BC库支持，引入即可：

```xml
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcprov-jdk15to18</artifactId>
	<version>1.66</version>
</dependency>
```
