### ISSUE TITLE
hutool log 打印null对象显示 {msg}异常问题

### ISSUE THREAD

**Issue by mccken** [looly/hutool#1084]
- 版本
>jdk： 1.8 
hutool： 5.4.2

- 基本描述
>log打印 null 对象，显示为 `{msg}`

![image](https://user-images.githubusercontent.com/26524164/93287182-71745700-f80b-11ea-8b23-1d7b1caa0f19.png)

**Comment by looly** [comment]
确认bug，5.4.3修复此问题，感谢。
