### ISSUE TITLE
Dict 类 of方法 有错误

### ISSUE THREAD

**Issue by MHXXX** [looly/hutool#1086]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

public static Dict of(Object... keysAndValues)   这个方法有误

1. 复现代码

按照描述应该将代码
```
if(i % 2 == 0){
				dict.put(key, keysAndValues[i]);
			} else{
				key = Convert.toStr(keysAndValues[i]);
			}
```
改为
```
if (i % 2 != 0)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.4.3修复此问题，感谢。

此issue与：https://gitee.com/loolly/hutool/issues/I1UUO5?from=project-issue 重复。
