### ISSUE TITLE
作者大大，希望能加个地区编码的工具类

### ISSUE THREAD

**Issue by zhouguangnuan** [looly/hutool#1087]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
地区编码指省市县的编码么？这个用字典即可，表可以去：

http://www.mca.gov.cn//article/sj/xzqh/2020/2020/20200908007001.html
