### ISSUE TITLE
cn.hutool.extra.mail.MailUtil#send(cn.hutool.extra.mail.MailAccount, java.util.Collection<java.lang.String>, java.lang.String, java.lang.String, boolean, java.io.File...)参数传了MailAccount 但是调用方法缺没有使用MailAccount这个参数而是从GlobalMailAccount.INSTANCE.getAccount()配置文件读，这个方法与预期的不符

### ISSUE THREAD

**Issue by jerzygao** [looly/hutool#1091]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
cn.hutool.extra.mail.MailUtil#send(cn.hutool.extra.mail.MailAccount, java.util.Collection<java.lang.String>, java.lang.String, java.lang.String, boolean, java.io.File...)参数传了MailAccount 但是调用方法缺没有使用MailAccount这个参数而是从GlobalMailAccount.INSTANCE.getAccount()配置文件读，这个方法与预期的不符
1. 复现代码

```java
 MailUtil.send(account, CollUtil.newArrayList("hutool@foxmail.com"), "测试", "邮件来自Hutool测试", false);
```

2. 堆栈信息
java.lang.NullPointerException
	at cn.hutool.extra.mail.Mail.<init>(Mail.java:84)
	at cn.hutool.extra.mail.Mail.create(Mail.java:57)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:194)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:128)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:158)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/93416281-0775b380-f8d8-11ea-9442-26f4aeefa61d.png)

最新版应该没这个问题了，请升级hutool
