### ISSUE TITLE
IdcardUtil重复性太高的问题

### ISSUE THREAD

**Issue by CloverAn** [looly/hutool#1092]
IdcardUtil目前解析出来的数据是完全分开的，即解析身份证-获得年龄，解析身份证-获得省份，解析身份证-获得生日，其中解析身份证的步骤过于重复。
意味着我要获取全部数据，必须要重复多次的进行解析。
建议在现有分开的基础上，增加一个返回含有全部数据的实体类的方法，可以通过get方法获取所需数据。

**Comment by looly** [comment]
解析过程本质上是对身份证每个段的解析，因此单独解析并不影响性能。

至于组合在一起，用个Bean包装下即可。

5.4.3加入包装方法，感谢。
