### ISSUE TITLE
日志设置TinyLog工厂的时候无法通过checkLogExist

### ISSUE THREAD

**Issue by colo1994** [looly/hutool#1094]
### 版本情况

JDK版本：    1.8.0_191
hutool版本： 5.4.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

LogFactory.setCurrentLogFactory(new TinyLogFactory());	

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

TinyLog出了2版本，但是现在代码里面检查的是org.pmw.tinylog.Logger.class，是1版本的路径。
官网除了1.3的兼容2.0的jar包，加入后可以找到这个类。但是在
Exception in thread "main" java.lang.NoSuchMethodError: org.pmw.tinylog.Logger.getLevel(Ljava/lang/String;)Lorg/pmw/tinylog/Level;
报错。

希望可以兼容2.0版本的TinyLog.

**Comment by looly** [comment]
5.4.3加入支持，感谢。
