### ISSUE TITLE
dbUtil是否支持ssl（代理）连接真正的数据库？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1095]

**Comment by looly** [comment]
不支持，也没有找到相关资料如何支持。貌似这个不应该是jdbc客户端来实现么？

**Comment by joey-happy** [comment]
我使用过这个：https://github.com/maniaclee/jumper 是能用的  看看您那里是否能够包装一个能实现的 并且简单的

**Comment by looly** [comment]
其实这个库就是做了端口转发，通过跳板机穿透。你按照文档获得相应的转换后的jdbc url即可。

**Comment by joey-happy** [comment]
嗯嗯 好吧 这样的话 我还得自己操作一下 主要是想方便操作api
