### ISSUE TITLE
	Setting能直接从字符串创建吗？

### ISSUE THREAD

**Issue by colo1994** [looly/hutool#1099]
### 版本情况

JDK版本：    1.8.0_191
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

	        String configINFO = config();
		File dbFile =	FileUtil.writeUtf8String(configINFO, "db2.setting");
		Setting dbSetting = new Setting("db2.setting");
		System.out.println(dbSetting);

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
Hutool的Setting非常好用，回不去了，不过我还没有找到从字符串直接生成Setting的办法，只能先从字符串创建一个文件，再读取这个文件生成Setting。
可以直接 Setting dbSetting = new Setting(configINFO ); 这样子生成吗？

**Comment by looly** [comment]
可以这样：

```java
Setting setting = new Setting();
setting.init(new StringResource(content), CharsetUtil.CHARSET_UTF_8, false);
```

5.4.4会增加一些新的构造方法，感谢。
