### ISSUE TITLE
调用 接口报错 RejectedExecutionException:cn.hutool.http.HttpException: Unexpected end of file from server

### ISSUE THREAD

**Issue by aslzl** [looly/hutool#1100]
![image](https://user-images.githubusercontent.com/13818316/93730050-8c730c80-fbf9-11ea-9edc-ba967d7aa2f4.png)

这样的接口用 hutool 怎么调用，我用这种方式调用，一直报错：
![image](https://user-images.githubusercontent.com/13818316/93730095-baf0e780-fbf9-11ea-8e26-93ffab072506.png)

![image](https://user-images.githubusercontent.com/13818316/93730116-cfcd7b00-fbf9-11ea-9e30-550cef0515ca.png)

**Comment by looly** [comment]
请使用body方法传入参数。具体见文档。
