### ISSUE TITLE
jSONNull == null返回false

### ISSUE THREAD

**Issue by brandonstack** [looly/hutool#1117]
### 版本情况

JDK版本：    jdk1.8.0_261
hutool版本： 5.4.0

### 问题描述（包括截图）

1. 复现代码

```java
// jsonNull为JSONNull类型
jsonNull == null (false)
jsonNull.equals(null) true
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/20850218/94139298-ff9bad80-fe9b-11ea-8c90-4157dbef37d0.png)

**Comment by totalo** [comment]
这里应该是故意这么设计的，他这里的jsonNull是字符串的“null”, 与js相对应，js中java的null 是undefind

**Comment by brandonstack** [comment]
但是这个不太符合Java的习惯，IDE也提示是冗余的。平时开发不经过测试，注意不到这个问题。
![image](https://user-images.githubusercontent.com/20850218/94216582-50e68400-ff12-11ea-80b0-3241c2b63d47.png)

**Comment by looly** [comment]
hutool的json库来自于json-lib库改造，最终把JSONNull这个对象保留了下来，便于与JS兼容。
