### ISSUE TITLE
HtmlUtil.unescape未处理&apos转义字符

### ISSUE THREAD

**Issue by 15036900300** [looly/hutool#1118]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String test = "真人版&quot;弥勒佛&quot;：&apos;&gt;&amp;在网络迅速走红，被富婆花高价请回家，现状如何";
System.out.println(HtmlUtil.unescape(test));
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
see https://github.com/looly/hutool/pull/1121
