### ISSUE TITLE
DateUtil.weekOfYear(date ) 有个 bug  

### ISSUE THREAD

**Issue by BigBroB** [looly/hutool#1120]
### 版本情况

JDK版本：    1.8
hutool版本： 5.4.2

### 问题描述
1. 复现代码

```
        DateTime time = DateUtil.parse("2018-12-31");
        int i = DateUtil.weekOfYear(time);
        System.out.println(i);
```
输出为 1 ，如果按照 2018 年当年的话 是不是应该为 53？

**Comment by looly** [comment]
![Uploading image.png…]()

**Comment by looly** [comment]
这是直接调用的`Calendar.get(Calendar.WEEK_OF_YEAR)`

**Comment by looly** [comment]
```
获得指定日期是所在年份的第几周<br>
此方法返回值与一周的第一天有关，比如：<br>
2016年1月3日为周日，如果一周的第一天为周日，那这天是第二周（返回2）<br>
如果一周的第一天为周一，那这天是第一周（返回1）<br>
跨年的那个星期得到的结果总是1
```

**Comment by Howie-mai** [comment]
DateUtil.weekOfYear(date) 这个方法只要是这周跨年了已经算是新的一年里了。

**Comment by ftdmao** [comment]
> DateUtil.weekOfYear(date) 这个方法只要是这周跨年了已经算是新的一年里了。

就算这周不跨年也认为是在新的一年里的。就比如2022年12月31日，是周六，它认为是第一周，而不是52周
