### ISSUE TITLE
字符串工具类StrUtil.splitToLong()返回类型错误

### ISSUE THREAD

**Issue by mahuandong** [looly/hutool#1124]
public static long[] splitToLong(CharSequence str, CharSequence separator) {
		return Convert.convert(long[].class, splitTrim(str, separator));
	}

**Comment by looly** [comment]
这个方法有啥问题么。返回类型错误是什么意思。

**Comment by mahuandong** [comment]
没看到两个方法的参数有区别，没有返回包装类型的方法吗

**Comment by looly** [comment]
splitToLong中的Long是驼峰命名大写的，返回long[]没有问题。
