### ISSUE TITLE
我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？

### ISSUE THREAD

**Issue by zhyit** [looly/hutool#1125]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

我想用httpUtil上传文件，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？

**Comment by looly** [comment]
见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0

**Comment by zhyit** [comment]
我知道这个，我这边用的springBoot，所以文件接收用的都是MultipartFile类型接收，如果用的官网的方法，我就要先生成文件，接着传递File，然后再删除文件，但是我不想生成文件后再去删除，而是想直接传流和文件名，请问有什么方法吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden Looly"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 上午9:28
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "ZYT"<871554023@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [looly/hutool] 我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？ (#1125)





 
见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0
 
&mdash;

**Comment by zhyit** [comment]
已找到解决方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden Looly"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 上午9:28
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "ZYT"<871554023@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [looly/hutool] 我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？ (#1125)





 
见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0
 
&mdash;

**Comment by lingyangcj** [comment]
> 已找到解决方法
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Golden Looly"<notifications@github.com&gt;; 发送时间: 2020年9月27日(星期天) 上午9:28 收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 抄送: "ZYT"<871554023@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [looly/hutool] 我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？ (#1125) 见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问如何解决的@zhyit

**Comment by zhyit** [comment]
> > 已找到解决方法
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Golden Looly"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年9月27日(星期天) 上午9:28 收件人: "looly/hutool"<[hutool@noreply.github.com](mailto:hutool@noreply.github.com)>; 抄送: "ZYT"<[871554023@qq.com](mailto:871554023@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [looly/hutool] 我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？ (#1125) 见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 请问如何解决的@zhyit

HttpResponse response = HttpRequest.post(server + "/save").form("file", bytes, filename).form(paramMap).execute();

**Comment by lingyangcj** [comment]
> > > 已找到解决方法
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "Golden Looly"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年9月27日(星期天) 上午9:28 收件人: "looly/hutool"<[hutool@noreply.github.com](mailto:hutool@noreply.github.com)>; 抄送: "ZYT"<[871554023@qq.com](mailto:871554023@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [looly/hutool] 我想用httpUtil上传文件到文件系统，但是文件系统接收使用的是MultipartFile这个文件类型，请问怎么弄？ (#1125) 见文档：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 请问如何解决的@zhyit
> 
> HttpResponse response = HttpRequest.post(server + "/save").form("file", bytes, filename).form(paramMap).execute();

非常感谢，解决了我当前的问题。比心~ @zhyit
