### ISSUE TITLE
log日志bug

### ISSUE THREAD

**Issue by wuai1024** [looly/hutool#1128]
### 版本情况

JDK版本：    11.0.8
hutool版本： 5.4.3

### 问题描述（包括截图）

目前我使用的日志框架是log4j2，日志根据info,warn,error 显示了绿色，黄色，红色三种不同的颜色。
以前使用的@Slf4j注解，每次idea升级后lombok都无法使用非常影响我们
故转而使用hutool-all的log，在版本5.4.1中还是好好的。我升级到最新的5.4.3中后就异常了

是否更改了日志实现方式？

1. 复现代码

```java
private static final Log log = LogFactory.get();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

有问题的图片（hutool-all 5.4.3）
![image](https://user-images.githubusercontent.com/13379708/94381695-c9e11800-016c-11eb-9463-855dc1fb0b58.png)

正常情况（hutool-all 5.4.1）
![image](https://user-images.githubusercontent.com/13379708/94381742-e715e680-016c-11eb-8415-8386d3f2e767.png)

**Comment by wuai1024** [comment]
目前我已经退回到5.4.1版本使用了。

这个版本中  log 日志显示正常， excel自动列宽适应正常

**Comment by looly** [comment]
看样子目测是日志配置文件没有读到，使用了默认的配置。

看下hutool log的日志是否识别到了你的log4j包，还有log4j2的配置文件是否正常。

log这块几乎没动，修改只有：

* 【log    】     增加TinyLog2支持（issue#1094@Github）
* 【log    】     修复打印null对象显示{msg}异常问题（issue#1084@Github）

**Comment by looly** [comment]
如果方便，麻烦提供下你的log4j2的配置文件，我这边测试。

**Comment by wuai1024** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE something>
<!--monitorInterval：Log4j能够自动检测修改配置 文件和重新配置本身，设置间隔秒数-->
<something status="WARN" monitorInterval="30">
    <!--先定义所有的appender-->
    <appenders>
        <!-- 这个会打印出所有的info及以下级别的信息，每次大小超过size，则这size大小的日志会自动存入按年份-月份建立的文件夹下面并进行压缩，作为存档 -->
        <RollingFile name="RollingFile" fileName="./logs/catalina.out" filePattern="./logs/%d{yyyy}/%d{MM}/catalina.%d{yyyy-MM-dd}.out">
            <!-- filePattern="${sys:catalina.home}/logs/$${date:yyyy-MM}/catalina.%d{yyyy-MM-dd}.%i.log"> -->
            <!--控制台只输出level及以上级别的信息（onMatch），其他的直接拒绝（onMismatch） -->
            <ThresholdFilter level="INFO" onMatch="ACCEPT" onMismatch="DENY"/>
            <PatternLayout charset="UTF-8" pattern="%highlight{[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%p] [%file:%line] - %m%n}"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="1"/>
                <SizeBasedTriggeringPolicy size="1000 GB"/>
            </Policies>
            <DefaultRolloverStrategy max="100"/>
        </RollingFile>
    </appenders>
    <!--然后定义logger，只有定义了logger并引入的appender，appender才会生效-->
    <loggers>
        <!--过滤掉spring和MyBatis的一些无用的DEBUG信息-->
        <logger name="org.springframework" level="INFO"/>
        <logger name="org.mybatis.spring.SqlSessionUtils" level="INFO"/>
        <logger name="org.apache.ibatis.logging.LogFactory" level="INFO"/>
        <logger name="org.mybatis.spring.transaction.SpringManagedTransaction" level="INFO"/>
        <logger name="io.undertow.security.impl.SecurityContextImpl" level="INFO"/>
        <logger name="com.alibaba.nacos.client.config.impl.ClientWorker" level="WARN"/>
        <AsyncRoot level="trace" includeLocation="true">
            <appender-ref ref="RollingFile"/>
        </AsyncRoot>
    </loggers>
</something>
```


在linux系统或者Mac中启动，就能看到彩色日志了

**Comment by wuai1024** [comment]
%highlight{} 主要是这个属性

**Comment by looly** [comment]
好的，测试后我回复此issue。

**Comment by wuai1024** [comment]
好的，有需要配合的，随时联系

**Comment by looly** [comment]
我这边测试必须添加`disableAnsi="false"`才可以高亮，不知道是不是log4j2版本的问题。

```
<PatternLayout charset="UTF-8" pattern="%highlight{[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%p] [%file:%line] - %m%n}" disableAnsi="false" />
```

**Comment by wuai1024** [comment]
你是把服务部署在linux上的吗？ windows无法看到的

**Comment by looly** [comment]
> 你是把服务部署在linux上的吗？ windows无法看到的

他用的IDEA输出的，环境没问题。

**Comment by wuai1024** [comment]
IDEA不行的，按我说的测试吧

**Comment by wuai1024** [comment]
打包出来，然后在centos上部署 运行，就能看到了

**Comment by looly** [comment]
具体可以看：https://issues.apache.org/jira/browse/LOG4J2-2342?jql=text%20~%20%22disableAnsi%22

log4j2从2.9.0开始需要明确指定是否高亮，我想你升级hutool同时也升级了log4j2的版本。

**Comment by wuai1024** [comment]
hutool-all 5.4.1版本是好的，log4j2的版本好久都没变动过了。

**Comment by looly** [comment]
> hutool-all 5.4.1版本是好的，log4j2的版本好久都没变动过了。

这就非常奇怪了，你加我说的这个配置试下，看行不行，如果行就是log4j2版本问题。

**Comment by wuai1024** [comment]
如果你没有服务器能测试使用，我可以给你提供。不要在idea上console看

**Comment by wuai1024** [comment]
你看我最上面2个截图，除了我变更了hutool版本，其他的没有做任何变动

5.4.1 和 5.4.3 这2个版本

**Comment by looly** [comment]
那就加我QQ：914104645发个测试包吧~~

**Comment by looly** [comment]
问题找到：

原因出在ClassLoader上，Hutool使用了JDK的SPI机制，即ServiceLoader，ServiceLoader默认的ClassLoader是SystemClassLoader，但是打成fat jar后的Spring项目ClassLoader变成LaunchedURLClassLoader，导致SPI中找到的类加载失败，最终被认定为这个class没有引入。

**Comment by wuai1024** [comment]
找到就好了，麻烦你找这么久了。坐等你发新版了

**Comment by looly** [comment]
不麻烦，还要感谢~~

发现和修复一个bug是十分珍贵的。
