### ISSUE TITLE
使用大批量ExcelUtil.readBySax()无法读取包含小数点的Excel列数据

### ISSUE THREAD

**Issue by GithubLinmingxing** [looly/hutool#113]
ExcelUtil.readBySax("aaa.xlsx", 0, createRowHandler());  使用的版本为：<poi-ooxml.version>3.17</poi-ooxml.version><hutool-all.version>4.0.12</hutool-all.version><xercesImpl.version>2.11.0</xercesImpl.version>

**Comment by looly** [comment]
单元测试正常。请提供样例Excel。
