### ISSUE TITLE
AES对应 CryptoJS，请调整为：padding: CryptoJS.pad.Pkcs7 示例

### ISSUE THREAD

**Issue by jredream** [looly/hutool#1135]
**_对于Java中AES的默认模式是：AES/ECB/PKCS5Padding，如果使用CryptoJS，请调整为：padding: CryptoJS.pad.Pkcs7_**

能够给出具体的示例？

或者 CryptoJS.pad.Pkcs7 具体对应hutool中的哪个类呢？

**Comment by looly** [comment]
也是使用字符串传：

new AES("AES/ECB/PKCS7Padding")

**Comment by zhangfulv** [comment]
cn.hutool.crypto.CryptoException: NoSuchAlgorithmException: Cannot find any provider supporting AES/ECB/PKCS7Padding

**Comment by looly** [comment]
需要BC库加入。

**Comment by zhangfulv** [comment]
这个我已经知道了，谢谢，但是又发现了默认AES aes = new AES(key.getbyte());  与需要设置的PKCS7Padding进行加密后的结果是一致的。

**Comment by looly** [comment]
貌似PCKS5个PCKS7差别不大，具体差异在哪儿我也不清楚哎。

**Comment by ThornHawd** [comment]
PCKS5与PCKS7是两种补码方式，虽然大多数情况下加密后结果一致，但是补码方式不同，依然会留下系统隐患。

**Comment by ThornHawd** [comment]
> 这个我已经知道了，谢谢，但是又发现了默认AES aes = new AES(key.getbyte()); 与需要设置的PKCS7Padding进行加密后的结果是一致的。

你这个BC库是在哪里加入的？

**Comment by zhangfulv** [comment]
加入maven依赖，<dependency>
        <groupId>org.bouncycastle</groupId>
         <artifactId>bcprov-jdk15on</artifactId>
         <version>1.68</version>
   </dependency>

**Comment by zhangfulv** [comment]
`加入maven依赖，<dependency>
        <groupId>org.bouncycastle</groupId>
         <artifactId>bcprov-jdk15on</artifactId>
         <version>1.68</version>
   </dependency>
`

**Comment by changhr2013** [comment]
> 貌似PCKS5个PCKS7差别不大，具体差异在哪儿我也不清楚哎。

PKCS5Padding 是 PKCS7Padding 的子集，可以理解 PKCS5Padding 是 PKCS7Padding 的一种特定 block 下的情况，JDK 的 PKCS5Padding 实现是依照 PKCS7Padding 的标准来实现的，所以 Java 中在构建 Cipher 的时候使用 PKCS5Padding 和 PKCS7Padding 没有区别。我看有好几个这种 issue，还是讲清楚好一些，或者更新一下说明文档。
