### ISSUE TITLE
JSONUtil.toJsonStr怎么把Long类型转成String

### ISSUE THREAD

**Issue by Fyee** [looly/hutool#1139]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JSONUtil.toJsonStr怎么把Long类型转成String
比如：
把
```json
{"id":123456}
```
转成
```json
{"id":"123456"}
```

**Comment by looly** [comment]
这个需要你put，重新覆盖值。
