### ISSUE TITLE
CronUtil 全局定时任务 数据操作报空指针

### ISSUE THREAD

**Issue by KOUymA** [looly/hutool#1142]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![微信图片_20200929181330](https://user-images.githubusercontent.com/72074577/94545989-dace7e00-027f-11eb-91a7-cf53a8e6b2cc.png)

只走数据库操作没问题，不含数据库操作的定时任务也没问题
但是通过定时任务查询数据库就报空指针

**Comment by totalo** [comment]
您好，可以提供一下代码嘛？ 我尝试了一下是ok的呀

**Comment by KOUymA** [comment]
dataList = wrongTopicMapper.selectByExample(new Example.Builder(WrongTopic.class)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .where(Sqls.custom()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .andEqualTo("forgettingLevel", 0)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .andEqualTo("source", TopicSource.KE_XIA)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .andLessThanOrEqualTo("completeTime", DateUtil.offsetDay(DateUtil.endOfDay(DateUtil.date()), -1)))
	.build());

报错的断点中间只有这段代码 而且单独运行是没问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "totalo"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 晚上8:29
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "黄旭铭"<316553954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [looly/hutool] CronUtil 全局定时任务 数据操作报空指针 (#1142)





 
您好，可以提供一下代码嘛？ 我尝试了一下是ok的呀

**Comment by KOUymA** [comment]
> 您好，可以提供一下代码嘛？ 我尝试了一下是ok的呀

![image](https://user-images.githubusercontent.com/72074577/94562693-399ff180-0298-11eb-844d-b7b7678359ac.png)
单独运行这个方法是没问题的

**Comment by looly** [comment]
> > 您好，可以提供一下代码嘛？ 我尝试了一下是ok的呀
> 
> ![image](https://user-images.githubusercontent.com/72074577/94562693-399ff180-0298-11eb-844d-b7b7678359ac.png)
> 单独运行这个方法是没问题的

当然空指针啊，你用的Spring项目吧？Spring中的bean依赖于IOC，hutool定时任务中是直接实例化反射掉调用的。
