### ISSUE TITLE
hutool-system中的工具类设计的方法都是非静态的，这个设计成静态方法会不会好一点?

### ISSUE THREAD

**Issue by echohlne** [looly/hutool#1154]
hutool-system中的类，都是一些对机器OS、系统属性的抽象，用起来非常麻烦，所有的方法都必须要先new 以后才能做查询，请教下这种不涉及内部变量状态变化的工具类是不是将方法改成static更好一点？

**Comment by looly** [comment]
这些类都是系统信息的包装啊，无需自己new，你使用SystemUtil即可。
