### ISSUE TITLE
关于JSON转对象BUG

### ISSUE THREAD

**Issue by clockworm** [looly/hutool#1161]
JSONUtil.toBean(json, beanClass) 这个方法有个BUG, 当JSON字符串属性为41070000.00 这样的大整形字符串或数字的情况下转成对象的属性会进行科学计算赋值为4.107E+7

**Comment by looly** [comment]
这个有啥问题吗？取决于你的bean中这个字段数字类型是啥。

**Comment by clockworm** [comment]
{
 "a": 41070000.00,
 "b": "41070000.00"
}
当Bean的a和b属性为String类型的时候会赋值为4.107E+7 
当Bean的a和b属性BigDecimal的时候会赋值为4.107E+7 
以上是错误的转换.
当使用阿里巴巴的fastJson或Gson做转换的时候,a和b属性在String或BigDecimal类型的时候赋值都为41070000.00 (正确)

**Comment by totalo** [comment]
能给个例子么？
我尝试了一下 正常啊
![image](https://user-images.githubusercontent.com/29777558/96332816-d0422000-1098-11eb-89dd-d8822a68fea3.png)
@clockworm

**Comment by clockworm** [comment]
![image](https://user-images.githubusercontent.com/12193979/96333144-cde0c580-109a-11eb-8bae-4af6f88b8484.png)

**Comment by clockworm** [comment]
使用版本组件为hutool-all  版本号为5.4.0 @looly

**Comment by totalo** [comment]
> 使用版本组件为hutool-all 版本号为5.4.0 @looly

debug 看了一下，dev分支修复了，下一个版本会更新。https://gitee.com/loolly/hutool/pulls/192/commits

**Comment by looly** [comment]
> > 使用版本组件为hutool-all 版本号为5.4.0 @looly
> 
> debug 看了一下，dev分支修复了，下一个版本会更新。https://gitee.com/loolly/hutool/pulls/192/commits

感谢帮忙回复~~
