### ISSUE TITLE
关于时区的问题

### ISSUE THREAD

**Issue by dq77** [looly/hutool#1165]
麻烦问一下，下面代码
String dateStr = "2017-03-01";
Date date = DateUtil.parse(dateStr);
字符串转时间这是按照哪个时区来转换的啊？文档没有写。

String formatDateTime = DateUtil.formatDateTime(date);
时间转字符串这个又是按照哪个时区来转的呢？文档依然没写。

**Comment by xyz327** [comment]
`DateUtil.parse` / `DateUtil.formatDateTime` 默认使用 TimeZone.getDefault();

这种没有指定的一般都会是用系统默认的嘛

要改变时区可以用 `DateUtil.parse(CharSequence dateStr, DateParser parser)` 通过 DateParser 指定时区
`DateParser dateParser = FastDateFormat.getInstance('yyyy-MM-dd', TimeZone.getDefault())`

**Comment by dq77** [comment]
感谢！
