### ISSUE TITLE
使用相关JSON工具类的时候遇到一些问题

### ISSUE THREAD

**Issue by chakid** [looly/hutool#1169]
### 版本情况

JDK版本：    java version "1.8.0_261"
hutool版本： 5.4.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
遇到的问题：

1. 复现代码

##### dangerPushList说明
```xml
{
    "content": [
        {
            "bedNo": "16",
            "criticalFlag": "1013396165",
            "criticalTime": "2020-10-17 13:10:39",
            "criticalTitle": "降钙素原检测",
            "dataAccount": "3524",
            "id": 1730,
            "isProcess": "0",
            "itemName": "降钙素原检测",
            "labReference": "0--0.05ng/mL",
            "labResult": "21.37",
            "name": "李延凤",
            "patientSno": "ZY00020001284986",
            "pushNumber": 1,
            "reportTime": "2020-10-17 13:10:57",
            "userDeptId": "X020",
            "userDeptName": "呼吸与危重症医学科",
            "userId": "58a40d7d50ada7a15c5f72fc",
            "userName": "陈琳"
        }
    ],
    "first": true,
    "last": false,
    "number": 0,
    "numberOfElements": 1,
    "pageable": {
        "offset": 0,
        "pageNumber": 0,
        "pageSize": 1,
        "paged": true,
        "sort": {
            "sorted": true,
            "unsorted": false
        },
        "unpaged": false
    },
    "size": 1,
    "sort": {
        "$ref": "$.pageable.sort"
    },
    "totalElements": 432,
    "totalPages": 432
}
```

```java
Page<DangerPush> dangerPushList = dangerPushRepository.findByReportTimeBetween(startTime, endTime, pageable);
JSONObject result= new JSONObject();
result.set("dangerPushList",dangerPushList); 

```
#### 问题1
我在使用hutool的时候，使用JSONObject类的时候去接收一些参数，然后返回前端的时候，在使用上面`result.set(String,Object)`的时候，Object我存的是Jpa分页之后的对象(`dangerPushList`)，这个时候，存到JSONObject之后，会只保留分页中的content信息，而其他比如‘pageable’相关的信息都被过滤掉了。
我将result打印出来，或者返回给前端的时候，就会只保留`dangerPushList`里面content的信息了。

#### 问题2
我在将`dangerPushList`这个对象转成json字符串的时候(使用的是`JSONUtil.toJsonStr(dangerPushList)`)，这个时候就会将分页信息给去掉，只保留了conten里面的信息（并且是数组形式）。

PS: 后面改成
```java
  com.alibaba.fastjson.JSONObject result = new com.alibaba.fastjson.JSONObject();
```
fastjson下面的JSONObject去接收的时候就会保留我整个对象的信息，
同时使用`JSON.toJSONString(dangerPushList)` (也是fastjson包下面的类)将`dangerPushList`转成json字符串的时候也会保留`dangerPushList`里面所有的信息（并且不是数组形式）。

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可否提供下bean结构。比如DangerPush。

**Comment by chakid** [comment]
@looly 好，已经QQ私发给你了，其实就是`dangerPushList` content里面那些信息

**Comment by looly** [comment]
问题出在Spring提供的Page接口。

Hutool解析对象的逻辑是：先解析集合接口，就跳过了，测试fastjson也是这个逻辑。

可能对Page对象做了特殊优化。

你可以实现`JSONSerializer`接口自定义下序列化规则，然后调用`JSONUtil.putSerializer`加入自定义规则即可。
