### ISSUE TITLE
JSONUtil.toBean 问题，如果对象中没有字段，就无法转换

### ISSUE THREAD

**Issue by chengqigang** [looly/hutool#1170]
![image](https://user-images.githubusercontent.com/29392211/96393819-db10c800-11f2-11eb-96ad-0da270188041.png)
用了JSONUtil.toBean(json, beanType, ignoreError)，但还是无法满足我的需求。这种希望返回的是个对象

**Comment by looly** [comment]
是滴，Hutool严格定义bean必须包含字段的。
