### ISSUE TITLE
hutool-http项目的文件下载能提供同步下载的方法吗

### ISSUE THREAD

**Issue by nicky1** [looly/hutool#1172]
### 版本情况 

JDK版本：    openjdk_8_201
hutool版本： 5.4.1

### 问题描述（包括截图）

1. 复现代码

```java
HttpUtil.requestDownloadFile
```

2.文件下载只提供了异步的方法，大部分业务场景都需要同步操作。

**Comment by xyz327** [comment]
不是很清楚你的问题。`HttpUtil.requestDownloadFile` 这是个私有方法。
下载文件应该使用 `HttpUtil.downloadXXX`相关方法才对呀

**Comment by looly** [comment]
调用writeBody后会自动转为同步的，异步是为了判断状态码。

**Comment by nicky1** [comment]
@xyz327 我们遇到的问题是
    1.调用 HttpUtil.downloadFile 方法，去下载zip包文件
    2.然后去调用  ZipUtil.unzip 解压刚下载到本地的 zip 包。
    3.这时线上jvm 就直接 crash了，找到log日志，报错的线程堆栈部分信息如下：
    `

Stack: [0x00007f01b697c000,0x00007f01b6a7d000],  sp=0x00007f01b6a7a460,  free space=1017kNative frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)C  [libzip.so+0x124e2]  newEntry+0x62C  [libzip.so+0x12b33]  ZIP_GetNextEntry+0x53J 22037  java.util.zip.ZipFile.getNextEntry(JI)J (0 bytes) @ 0x00007f032adaddf6 [0x00007f032adadd40+0xb6]J 26052 C2 java.util.zip.ZipFile$ZipEntryIterator.nextElement()Ljava/lang/Object; (5 bytes) @ 0x00007f032b92f1ec [0x00007f032b92f100+0xec]j  cn.hutool.core.util.ZipUtil.unzip(Ljava/util/zip/ZipFile;Ljava/io/File;)Ljava/io/File;+50J 26403 C1 cn.hutool.core.util.ZipUtil.unzip(Ljava/io/File;Ljava/io/File;Ljava/nio/charset/Charset;)Ljava/io/File; (31 bytes) @ 0x00007f032adcfc64 [0x00007f032adcfb20+0x144
--


`
   4. 我理解的这个download方法，executeAsync异步处理拿到 httpResponse，
      猜测是 2个线程，一个线上在写zip包，另一个解压的线程在读，
      导致的linux crash。

**Comment by xyz327** [comment]
@nicky1   我用下面测试是能正确解压文件的。不知道你们代码逻辑是怎样的。方便贴一下看看吗
```java
       @Test
	public void utlTest() {
		File file = new File("/Users/Downloads/test");
		File zipFile = new File(file, "demo.zip");
		HttpUtil.downloadFile("http://192.168.6.106:8000/demo.zip", file);
		ZipUtil.unzip(zipFile);
	}
```
