### ISSUE TITLE
升级版本包 5.3.5 -> 5.4.5,发现BeanUtil.copyProperties(),存在属性没有赋值的情况

### ISSUE THREAD

**Issue by yinzhiyuhot-126** [looly/hutool#1173]
### 版本情况

JDK版本：     java version "1.8.0_231"
hutool版本： 5.4.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
今次，升级版本包 5.3.5 -> 5.4.5,发现BeanUtil.copyProperties(),存在属性没有赋值的情况，我稍微看了一下源码，好像是新版本对方法有些优化调整，由于时间比较紧，没法细究，我抛出这个问题，
示例如下：
@Data
public class People implements Serializable {
    public transient String name;
}

@Data
public class BlackPeople extends People {
    private String name;
}

@Test
public void testGson() {
	BlackPeople blackPeople = new BlackPeople();
	blackPeople.setName("black");

	BlackPeople blackPeopleCopy = new BlackPeople();
	BeanUtil.copyProperties(blackPeople, blackPeopleCopy);
	Console.log(JSONUtil.toJsonStr(blackPeopleCopy)); 
}

**Comment by xyz327** [comment]
获取类字段时 如果父类存在同名字段，那就会使用父类的字段作为 copy 的字段，而由于你这个父类字段是 transient 的，copy 时默认会忽略掉transient的字段。。。
对于这种情况可以先通过`BeanUtil.copyProperties(source, dest, CopyOptions.create().setTransientSupport(false));`设置 CopyOptions 来不忽略 transient 字段

**Comment by yinzhiyuhot-126** [comment]
按我贴出的代码，并按照上述进行设置后，已经有值，但遇到新问题，即转json，并没有值
        Console.log(JSONUtil.toJsonStr(blackPeopleCopy));

**Comment by xyz327** [comment]
`JSONUtil.toJsonStr`没有值的原因和我上面说的原因一样。获取到了父类的 transient 字段而被忽略了.
`JSONUtil.parse(map, JSONConfig.create().setTransientSupport(false)).toJSONString(4);`  目前可以这样设置不跳过 transient 字段

**Comment by looly** [comment]
@xyz327 感谢排查意见，pr近期我检查后合并。

**Comment by looly** [comment]
see https://github.com/looly/hutool/pull/1175
