### ISSUE TITLE
The result of cn.hutool.core.date.chinese.GanZhi.cyclicalm(2020) may be incorrect

### ISSUE THREAD

**Issue by asdf913** [looly/hutool#1186]
### 版本情况

JDK版本：    jdk1.8.0_271
hutool版本： 5.4.6

### 问题描述（包括截图）

1. 复现代码

```java
System.out.println(cn.hutool.core.date.chinese.GanZhi.cyclicalm(2020));
```
print **甲辰**

According to [庚子 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%BA%9A%E5%AD%90),the result should be **庚子** 

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
看下注释，GanZhi.cyclicalm不能直接使用，你需要：

```java
final ChineseDate chineseDate = new ChineseDate(2020, 1, 1);
// 庚子
Console.log(chineseDate.getCyclical());
```

cyclicalm方法同时用于计算年、月、日的，所以这里传入的是offset。

5.4.7我会增加专门获取年的。感谢。

**Comment by asdf913** [comment]
Thanks you
