### ISSUE TITLE
希望添加一个常用的ExpressioUtil和RuleEngineUtil,最好是可以缓存对象的,缓存策略我根据情况替换!

### ISSUE THREAD

**Issue by independenter** [looly/hutool#1188]
## 执行一部分动态代码,来达到数据库控制业务逻辑的结果!
谢谢楼主!我也试着保持风格试一下

**Comment by looly** [comment]
查了下RuleEngine知道是啥了，Expression是啥？

**Comment by independenter** [comment]
表达式工具类,两个基本是类似的.

**Comment by independenter** [comment]
## 表达式工具类
一般是传入变量,获得boolean值
## 规则引擎工具类
执行一大段代码,可能还要import,执行java代码

**Comment by independenter** [comment]
> ## 表达式工具类
> 一般是传入变量,获得boolean值
> 
> ## 规则引擎工具类
> 执行一大段代码,可能还要import,执行java代码

**Comment by independenter** [comment]
> ## 表达式工具类
> 一般是传入变量,获得boolean值
> 
> ## 规则引擎工具类
> 执行一大段代码,可能还要import,执行java代码

**Comment by looly** [comment]
明白了，这个暂时不是很熟悉，暂不考虑。

欢迎提pr，封装第三方可以放在extra包中。

**Comment by independenter** [comment]
> 提pr

已经在写了,到时候麻烦检查,规范一下
