### ISSUE TITLE
生成连续日期需求

### ISSUE THREAD

**Issue by flzxss** [looly/hutool#119]
给定开始日期和结束日期字符串,如 开始日期:"2011-12-23" ,结束日期:"2012-03-01",补全中间的日期.形成List<String>存放生成的日期序列,该List包含开始日期和结束日期.

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/41412676-5b7c2ca2-7013-11e8-8a9e-a7958cf3a73c.png)

可以这么玩儿。4.1.0增加DateRange类。
