### ISSUE TITLE
ImgUtil.toBase64DataUri方法背景透明被转换成了黑色

### ISSUE THREAD

**Issue by yixiaco** [looly/hutool#1194]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.4.6

### 问题描述（包括截图）
背景透明被转换成了黑色
![image](https://user-images.githubusercontent.com/30982989/97540734-05d2fb80-19ff-11eb-866d-ef8f6ad542be.png)
正常效果
![image](https://user-images.githubusercontent.com/30982989/97540812-256a2400-19ff-11eb-8493-ff9167b57527.png)

1. 复现代码
```java
// 问题代码
ImgUtil.toBase64DataUri(image, "png")
// 正常效果代码
ByteArrayOutputStream stream = new ByteArrayOutputStream();
ImageIO.write(image, "png", stream)
```

**Comment by looly** [comment]
貌似找到了问题，你可以调用ImgUtil.write方法写出图片试下。

5.4.7修复此问题。

**Comment by looly** [comment]
没有复现问题。

请使用ImgUtil.write方法写出到文件试下。

如果不行请提供下变色的图片我测试，再打开issue。

**Comment by yixiaco** [comment]
[test.zip](https://github.com/looly/hutool/files/5457957/test.zip)
我试着保存到本地，然后再使用ImgUtil.toBase64,发现这时候是正常的，也就是说，在保存到本地之前，读取Image对象有问题导致背景变成了黑色。
我将这个过程保存在了test.zip中，里面能够复现我的异常问题，希望对你排查能有帮助。

**Comment by yixiaco** [comment]
文件的下载和图片的预览貌似需要代理。

**Comment by looly** [comment]
找到问题原因了。你原图处理后为`sun.awt.image.ToolkitImage`，使用hutool转换为BufferedImage的时候使用了默认的RGB模式导致的问题。

5.4.7修复此问题，感谢。
