### ISSUE TITLE
guava里边的Bytes.ensureCapacity，在hutool中有类似的函数吗

### ISSUE THREAD

**Issue by bigbeef** [looly/hutool#1196]
将byte数字填充成指定长度的数组
public static byte[] ensureCapacity(byte[] array, int minLength, int padding) ；

**Comment by looly** [comment]
这个方法使用JDK的`Arrays.copyOf`就行吧。

**Comment by bigbeef** [comment]
Arrays.copyOf不支持指定填充字节

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/97770911-9251fb00-1b72-11eb-9189-19eed3f94555.png)


看下源码，也没有填充哦，默认填充的0。其实就是扩容。
