### ISSUE TITLE
哪儿有傻瓜工使用hutool的demo？

### ISSUE THREAD

**Issue by linbren** [looly/hutool#1197]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
哪儿有傻瓜工使用hutool的demo？最好能全一点的。

1. 复现代码

 无
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可以看文档啊，写的很清楚：https://hutool.cn/
