### ISSUE TITLE
DateUtil中的current方法

### ISSUE THREAD

**Issue by fengshanbieyuan** [looly/hutool#1198]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在DateUtil中的current方法，使用了System.nanoTime()，这个方法并不是返回当前时间的时间戳，而是当前JVM的高精度时间，可能是从某个时间点开始计算的，可能是负数。
![image](https://user-images.githubusercontent.com/10769003/97961024-76a65900-1ded-11eb-9afc-a4f78e4859bf.png)
该api注释如下：
![image](https://user-images.githubusercontent.com/10769003/97961266-ed435680-1ded-11eb-87c4-efbb3cf38bde.png)
这个方法跟系统时钟无关，只能用于计算时间差

**Comment by looly** [comment]
确实，这块我疏漏了。

5.4.8去掉这个参数，感谢。
