### ISSUE TITLE
HttpUtil中Url不支持BasicAuth

### ISSUE THREAD

**Issue by changxinjie** [looly/hutool#1201]
期望 HttpUtil.get("http://chang:111222333@localhost:8444")能正常验证

**Comment by looly** [comment]
可以：HttpRequest.get("http://localhost:8444").basicAuth("chang", "111222333").execute().body();

**Comment by changxinjie** [comment]
> 可以：HttpRequest.get("[http://localhost:8444").basicAuth("chang](http://localhost:8444%22).basicAuth(%22chang)", "111222333").execute().body();

httpUtil.get() Url中应可以直接解析出auth信息.
