### ISSUE TITLE
希望可以把作者自己的，符合PR规则的formatter.xml放到项目中。

### ISSUE THREAD

**Issue by Lillls** [looly/hutool#1204]
希望可以把作者自己的，符合PR规则的formatter.xml放到项目中。

**Comment by Lillls** [comment]
提PR的人就不需要操心代码风格的问题了

**Comment by looly** [comment]
代码风格其实要求不高，就算不一致，我本地一键格式化即可。

提供`formatter.xml`反而增加pr的负担。
