### ISSUE TITLE
HexUtil.toHex(long value) 方法丢失字符

### ISSUE THREAD

**Issue by jiang4yu** [looly/hutool#1209]
### 版本情况

JDK版本：    Oracle_jdk1.8.0_192
hutool版本： 5.4.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
HexUtil.toHex(long value) 方法存在问题，会将丢掉首位为 “0”的字符；
例如：
 225825032 转16进制字符串 正确结果应为 0d75d108；
但 该方法得到的结果为：d75d108

1. 复现代码

```java
long value = 225825032L;
System.out.println(HexUtil.toHex(value));
```

**Comment by looly** [comment]
这个方法包装了`Long.toHexString(value)`

注释也很清楚：

```
This value is converted to a string of ASCII digits in hexadecimal (base&nbsp;16) with no extra leading {@code 0}s
```
