### ISSUE TITLE
poi模块-ExcelReader的read方法读取空单元格默认值问题

### ISSUE THREAD

**Issue by 1325886312** [looly/hutool#1213]
### 版本情况

JDK版本：    1.8.0_144
hutool版本： 5.4.7

### 问题描述（包括截图）
使用ExcelReader的read方法读取excel文件时，当遇到空单元格, 默认null 字符串作为默认值。尝试通过实现CellEditor 来设置空单元格的默认值时， debug发现，空值并没有进入 CellEditor 的相关处理逻辑，所以也不能实现自定义空单元的默认值，个人希望可以增加空单元格的自定义默认值操作. 感谢!

1. 测试截图
![微信图片_20201112200446](https://user-images.githubusercontent.com/9897264/98938283-9bec4300-2522-11eb-929e-f8da81852300.png)

2. 测试excel如附件所示
[test.xlsx](https://github.com/looly/hutool/files/5530488/test.xlsx)

**Comment by looly** [comment]
5.5.0修改null处理规则：

```java
final ExcelReader reader = ExcelUtil.getReader("null_cell_test.xlsx");
reader.setCellEditor((cell, value)-> ObjectUtil.defaultIfNull(value, "#"));
final List<List<Object>> read = reader.read();

// 对于任意一个单元格有值的情况下，之前的单元格值按照null处理
Assert.assertEquals(1, read.get(1).size());
Assert.assertEquals(2, read.get(2).size());
Assert.assertEquals(3, read.get(3).size());

Assert.assertEquals("#", read.get(2).get(0));
Assert.assertEquals("#", read.get(3).get(0));
Assert.assertEquals("#", read.get(3).get(1));
```

在测试Excel中，第二行只有第一个单元格有值，因此后边的单元格不会处理，只有单元格有值的情况下，之前的单元格值按照null处理。

**Comment by 1456132848** [comment]
为什么ExcelSaxReader没有setCellEditor方法？

**Comment by looly** [comment]
@1456132848 因为在sax模式下，没有完整的Cell对象，只能拿到固定标签。
