### ISSUE TITLE
http工具类自动重定向好像会导致cookie丢失

### ISSUE THREAD

**Issue by AnLiBoBo** [looly/hutool#1218]
### 版本情况

JDK版本：    
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

hutool版本： 所有版本都试过了

### 问题描述（包括截图）
目标web服务url  https://www.example.com/xxx
配置了nginx重定向 当以 http://example.com/xxx 请求时 会重定向到 https://www.example.com/xxx

然后携带了登录cookie的时候,请求会返回登录信息
这个时候 通过http://example.com/xxx 去请求,并且设置自动重定向 然后请求并没有返回登录信息过来
但是通过https://www.example.com/xxx 去请求,并且设置自动重定向 然后请求,这个时候就会返回登录信息过来

这个问题好像是jdk版本导致的,我本机调试是没有问题的, 下面是我本机的JDK版本信息
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

我尝试过其他请求库,还没有了解他们的底层用的是什么,但是他们的是可以正常访问的
```xml
<dependency>
            <groupId>net.dongliu</groupId>
            <artifactId>requests</artifactId>
            <version>5.0.8</version>
</dependency>
<dependency>
            <groupId>com.mashape.unirest</groupId>
            <artifactId>unirest-java</artifactId>
            <version>1.4.9</version>
</dependency>
```
1. 复现代码

```java
        cookie = "xxx";
        String result = HttpUtil.createGet("http://example.com/xxx")
                .setFollowRedirects(true)
                .cookie(cookie)
                .execute()
                .body();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
重定向后http改为了https，所以丢失。

hutool中的`GlobalCookieManager`使用URI区分网站Cookie，协议不同，因此Cookie域也不同。
