### ISSUE TITLE
json模块转换成JSON字符串.0小数点会被忽略，导致double类型变成int类型

### ISSUE THREAD

**Issue by lintingbin** [looly/hutool#1219]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
下面的代码的结果为：{"c":2}，但是实际结果应该是: {"c":2.0}。同样转换在fastjson上是没问题的。

1. 复现代码

```java
import cn.hutool.json.JSONUtil

Map<String, Object> map = new HashMap<>()
map.put("c", 2.0F)

JSONUtil.toJsonStr(map)
```

**Comment by looly** [comment]
这是有意而为之的，在`NumberUtil.toStr`中做了自动处理：

![image](https://user-images.githubusercontent.com/1432613/99240935-250fbc80-2838-11eb-9333-1275ada740ce.png)

原因如下：
1、带小数点的小数无论是Double还是Float，在parse解析的时候都可以自动转换
2、去除小数部分更加简短。

不知道这样处理你这里有什么问题么？

**Comment by lintingbin** [comment]
@looly 我这边遇到的问题是这样的。我们这边有一些数据需要异步写入数据库，所以会先把数据写入到kafka中，然后再从kafka读取数据写入到数据库中。有一个本来是double类型的数据，经过kafka再转回java的数据类型就会变成int的类型，这样就会导致写入数据库的时候报类型不匹配的错误。

**Comment by looly** [comment]
一般而言，kafka应该是序列化传输，然后反序列化，反序列化后依旧为JSON啊，入库不知道你如何入库的？按理说你的那个字段应该调用getDouble方法读取。而不是get方法。

**Comment by lintingbin** [comment]
我们存到kafka是使用json字符串，因为序列化的可读性不好。写入数据库的时候，写入方法会根据表的字段定义类型来做一个类型转化。

**Comment by looly** [comment]
我觉得应该在JSON字符串写入数据库这块逻辑下手。

尤其“根据表的字段定义类型来做一个类型转化”的逻辑中，应该做判断转换。

**Comment by lintingbin** [comment]
现在是有先做类型判断再处理。感觉这个问题应该算是一个取舍问题吧。fastjson选择了另一种方式。

**Comment by looly** [comment]
是啊，我觉得这是对数据格式的理解问题。JSONObject.getDouble("xxx")其实可以完成数字类型转换，输出格式上应该是没有限制才对。

**Comment by java8site** [comment]
> 这是有意而为之的，在`NumberUtil.toStr`中做了自动处理：
> 
> ![image](https://user-images.githubusercontent.com/1432613/99240935-250fbc80-2838-11eb-9333-1275ada740ce.png)
> 
> 原因如下： 1、带小数点的小数无论是Double还是Float，在parse解析的时候都可以自动转换 2、去除小数部分更加简短。
> 
> 不知道这样处理你这里有什么问题么？

给移动端发送数据时候，一会int，一会double, 移动端报错的。求个可配置的方法。
