### ISSUE TITLE
[bug] JSON parse missing some properties

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#122]
对象转化成 json 字符串的时候对象属性缺失
hutool 版本4.0.12

先看正确的，使用 jackson 转化 json 字符串的时候
![image](https://user-images.githubusercontent.com/10429917/41447600-9484ab98-701b-11e8-833d-c1668084a830.png)
结果：
![image](https://user-images.githubusercontent.com/10429917/41447612-a2c3a3f8-701b-11e8-9a89-ef4a09d545bc.png)

使用 hutool 的 JsonUtil#toJsonStr()
![image](https://user-images.githubusercontent.com/10429917/41447690-0d173e18-701c-11e8-8ae2-490fd65b6c01.png)
结果：
![image](https://user-images.githubusercontent.com/10429917/41447697-14752bc0-701c-11e8-85e4-74106b49ee28.png)

**Comment by xkcoding** [comment]
还有属性有些会被置空
先看正确的，使用 jackson 的时候
![image](https://user-images.githubusercontent.com/10429917/41447794-c12e4c66-701c-11e8-8d75-09f619714f7a.png)
结果：
![image](https://user-images.githubusercontent.com/10429917/41447787-b7f4370a-701c-11e8-9a12-d9240b6cac6d.png)

使用 hutool 的 JsonUtil#toJsonStr()的时候
![image](https://user-images.githubusercontent.com/10429917/41447967-adcece4c-701d-11e8-8f63-5ba52695615f.png)
结果：
![image](https://user-images.githubusercontent.com/10429917/41447971-b2449498-701d-11e8-9bcf-8c94af42e91d.png)

**Comment by xkcoding** [comment]
代码地址：https://github.com/xkcoding/security-demo.git

**Comment by looly** [comment]
经过测试，发现这个算是不是问题的问题。原因如下：

![image](https://user-images.githubusercontent.com/1432613/41509543-186d8d76-7288-11e8-942e-c580899c887c.png)

如图，getXXX方法并无属性，按照Bean规范，getXXX无属性的并非此Bean的Getter方法，Hutool会自动忽略。此处并无问题。

Hutool针对这里getXXX方法专门做了属性校验，因此在Bean中，如果你的属性无getXXX方法，不会读取属性，而只有getXXX方法，没有属性，也不会被读取。这种规则个人认为是没有错误的。欢迎探讨。

**Comment by xkcoding** [comment]
可不可以提供一个方法，可以把 getXXX 和属性一起变成 json字符串。毕竟 jackson 可以。
