### ISSUE TITLE
DateUtil.endOfDay 得到的时间保存到数据时会增加一秒

### ISSUE THREAD

**Issue by cnlinjie** [looly/hutool#1220]
### 版本情况

JDK版本：    openjdk_11.0.7
hutool版本： 5.5.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
```
DateUtil.endOfDay(date)
```
日期工具类 DateUtil 的方法 endOfDay(获取某天的结束时间)，得到的日期时间:23:59:59 ，保存到数据库(mysql)时，会增加一秒，变成次日的 00:00:00。
如：2020-11-10 23:59:59  保存到数据库时 会变成：2020-11-11 00:00:00 .

<img width="569" alt="WX20201116-143240@2x" src="https://user-images.githubusercontent.com/3601638/99219934-a0fa0c80-2818-11eb-9fe0-a03088d590c7.png">

<img width="230" alt="WX20201116-143349@2x" src="https://user-images.githubusercontent.com/3601638/99219997-c0913500-2818-11eb-836f-9d044ffd2869.png">

目前已知的问题是，因为MySQL数据库对于毫秒大于500的数据进行进位。
网络上的解决方案：
https://www.cnblogs.com/fswhq/p/mysql_1.html
代码如下：
```
public static Date getEndOfDay(Date date) {
        Calendar calendarEnd = Calendar.getInstance();
        calendarEnd.setTime(date);
        calendarEnd.set(Calendar.HOUR_OF_DAY, 23);
        calendarEnd.set(Calendar.MINUTE, 59);
        calendarEnd.set(Calendar.SECOND, 59);
        calendarEnd.set(Calendar.MILLISECOND, 0); // 这一句比较关键
        return calendarEnd.getTime();
    }
```

**Comment by cnlinjie** [comment]
<img width="566" alt="WX20201116-145353@2x" src="https://user-images.githubusercontent.com/3601638/99221470-968d4200-281b-11eb-9af4-de3ef02956b3.png">

临时解决方案，目前可行。

**Comment by looly** [comment]
确实是，但是endOf，如果毫秒为0就不是end了吧？所以面对数据库这种操作，只能手动修改毫秒为0。

**Comment by cnlinjie** [comment]
好像也有道理，哈哈哈哈哈哈哈哈~
