### ISSUE TITLE
CronTimer 容易死循环cpu100%

### ISSUE THREAD

**Issue by zhouchengfei** [looly/hutool#1224]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
matchSecond=true情况下,服务器稍微一卡 sleep就容易<0 导致死循环
1. 复现代码
final long timerUnit = this.scheduler.config.matchSecond ? TIMER_UNIT_SECOND : TIMER_UNIT_MINUTE;
		
		long thisTime = System.currentTimeMillis();
		long nextTime;
		long sleep;
		while(false == isStop){
			//下一时间计算是按照上一个执行点开始时间计算的
			//此处除以定时单位是为了清零单位以下部分，例如单位是分则秒和毫秒清零
			nextTime = ((thisTime / timerUnit) + 1) * timerUnit;
			sleep = nextTime - System.currentTimeMillis();
			if(isValidSleepMillis(sleep, timerUnit)){
				if (false == ThreadUtil.safeSleep(sleep)) {
					//等待直到下一个时间点，如果被中断直接退出Timer
					break;
				}
				//执行点，时间记录为执行开始的时间，而非结束时间
				thisTime = System.currentTimeMillis();
				spawnLauncher(thisTime);
			}else{
				log.error("死循环 sleep"+sleep+"timerUnit"+timerUnit);
			}
		}
		log.debug("Hutool-cron timer stopped.");

**Comment by looly** [comment]
这块逻辑确实有缺陷。5.5.2修复此问题，感谢！
