### ISSUE TITLE
树型工具在只有一个节点且节点不为父根点无法转换

### ISSUE THREAD

**Issue by pengdezhi** [looly/hutool#1226]
### 5.4.0

JDK版本：    openjdk_8_201
hutool版本：5.4.0

### TreeUtil.build时候，如果传入的list只有一个，且其不是根节点，则会返回空集合

1. 复现代码
List<Tree<E>> build(List<T> list, E parentId, TreeNodeConfig treeNodeConfig, NodeParser<T, E> nodeParser)
第77行

```java
for (Tree<E> node : treeList) {
	if (parentId.equals(node.getParentId())) {
	    finalTreeList.add(node);
	    innerBuild(treeList, node, 0, treeNodeConfig.getDeep());
	}		
 }
```

上面代码判断的时候，如果treeList只有一个，且其不是根节点，则不会进入判断。 finalTreeList将为空

**Comment by looly** [comment]
当然啊，只有一个节点这个节点，非根节点必须忽略啊。
