### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [looly/hutool#1230]
Hi all,
our bug scanner has reported a NPE bug.

A possible call chain may be [AbstractAsymmetricCrypto.java#L304](https://github.com/looly/hutool/blob/1858eea7e8c31a036ec84cc4483f5c1f630452bd/hutool-crypto/src/main/java/cn/hutool/crypto/asymmetric/AbstractAsymmetricCrypto.java#L304) => [BCD.java#L61](https://github.com/looly/hutool/blob/1858eea7e8c31a036ec84cc4483f5c1f630452bd/hutool-core/src/main/java/cn/hutool/core/codec/BCD.java#L61). Since the method [bytes()](https://github.com/looly/hutool/blob/1858eea7e8c31a036ec84cc4483f5c1f630452bd/hutool-core/src/main/java/cn/hutool/core/util/StrUtil.java#L2399) may return null at [AbstractAsymmetricCrypto.java#L304](https://github.com/looly/hutool/blob/1858eea7e8c31a036ec84cc4483f5c1f630452bd/hutool-crypto/src/main/java/cn/hutool/crypto/asymmetric/AbstractAsymmetricCrypto.java#L304), a NPE bug may take place at [BCD.java#L61](https://github.com/looly/hutool/blob/1858eea7e8c31a036ec84cc4483f5c1f630452bd/hutool-core/src/main/java/cn/hutool/core/codec/BCD.java#L61) when the variable `ascii` accesses its property `length`.

Thanks.

**Comment by looly** [comment]
5.5.1 add null check.
