### ISSUE TITLE
JSONUtil.toJsonStr()在数据量大的时候会内存溢出

### ISSUE THREAD

**Issue by if2018** [looly/hutool#1231]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

SONUtil.toJsonStr(picrecordList)

2. 堆栈信息
![1605750528(1)](https://user-images.githubusercontent.com/35320255/99610403-bc4d5d80-2a4c-11eb-840a-8eb010d7aa52.jpg)
![1605750609(1)](https://user-images.githubusercontent.com/35320255/99610420-c53e2f00-2a4c-11eb-8496-a0e09e9e369e.jpg)

3. 测试涉及到的文件（注意脱密）
测试用到的数据为300条数据库存入了二进制流的文件数据，每条200Kb的图片数据
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
数据量太大了，吧，转为字符串肯定大。

**Comment by looly** [comment]
试下jackson和Fastjson看行不行。
