### ISSUE TITLE
关于XmlUtil.toStr(xml,"GBK",true)方法格式化美化不完美问题

### ISSUE THREAD

**Issue by Trongdada** [looly/hutool#1232]
JDK版本： jdk1.8.0_221

hutool版本： 5.5.1

问题描述：
XmlUtil.toStr(xml,"GBK",true);这个格式化xml输出在设置了xml.setXmlStandalone(true)之后父节点开始节点出现了在第一行；
就是不够美化，不影响功能，第一次提交issues交给最爱的hutool，嘿嘿
[
![xml美化输出issues截图](https://user-images.githubusercontent.com/39590907/99614037-a2fbdf80-2a53-11eb-8470-d8ee3ec2a27a.jpg)
](url)

复现代码：

        Document xml = XmlUtil.createXml("NODES");
        xml.setXmlStandalone(true);

        NodeList parentNode = xml.getElementsByTagName("NODES");

        Element parent1Node = xml.createElement("NODE");

        Element node1 = xml.createElement("NODENAME");
        node1.setTextContent("走位");
        Element node2 = xml.createElement("STEP");
        node2.setTextContent("1");
        Element node3 = xml.createElement("STATE");
        node3.setTextContent("2");
        Element node4 = xml.createElement("TIMELIMIT");
        node4.setTextContent("");
        Element node5 = xml.createElement("STARTTIME");
        node5.setTextContent(LocalDateTimeFormatUtil.localDateTimeFormat(LocalDateTime.now()));
        Element node6 = xml.createElement("ENDTIME");
        node6.setTextContent(LocalDateTimeFormatUtil.localDateTimeFormat(LocalDateTime.now()));
        Element node7 = xml.createElement("ENDTIME");
        node7.setTextContent(LocalDateTimeFormatUtil.localDateTimeFormat(LocalDateTime.now()));

        parent1Node.appendChild(node1);
        parent1Node.appendChild(node2);
        parent1Node.appendChild(node3);
        parent1Node.appendChild(node4);
        parent1Node.appendChild(node5);
        parent1Node.appendChild(node6);
        parent1Node.appendChild(node7);

        parentNode.item(0).appendChild(parent1Node);

        String format = XmlUtil.toStr(xml,"GBK",true);
        System.out.println(format);

**Comment by CherryRum** [comment]
这个问题其实有解决办法，但是总感觉不是很好需要修改一下` XmlUtil.transform`这个方法，添加 `transformer.setOutputProperty(OutputKeys.DOCTYPE_PUBLIC, "yes");`，而且这个问题应该是陈年大坑貌似使用jdk1.5或者1.6不会出现这个问题，openjdk 曾经修复过这个问题，具体可参考[这个](https://bugs.openjdk.java.net/browse/JDK-7150637)

**Comment by CherryRum** [comment]
@looly 大佬您修改下，还是我提交个

1. `transformer.setOutputProperty(OutputKeys.DOCTYPE_PUBLIC, "yes");`
2. 参考openjdk实现
```
static final String ORACLE_IS_STANDALONE = "http://www.oracle.com/xml/is-standalone";
//catch IllegalArgumentException when running with previous releases
try {
    transformer.setOutputProperty(ORACLE_IS_STANDALONE, "yes");
} catch (IllegalArgumentException e) {
    //expected for previous releases
}
```
或者更简单点
```
try {
    transformer.setOutputProperty("http://www.oracle.com/xml/is-standalone", "yes");
} catch (IllegalArgumentException e) {
    // Might be thrown by JDK versions not implementing the workaround.
} 
```

**Comment by looly** [comment]
@CherryRum 太感谢啦，一直找不到解决办法。

稍后我合并测试~~

**Comment by looly** [comment]
see https://github.com/looly/hutool/pull/1234

**Comment by CherryRum** [comment]
@looly  好的测试样例我没敢上传，怕污染代码，您这边测试下，看看是否合并
