### ISSUE TITLE
自定义的sheet 总是自带一个默认的空sheet1 

### ISSUE THREAD

**Issue by Rekoe** [looly/hutool#1235]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9（请确保最新尝试是否还有问题）

### 问题描述

1. 复现代码

```java
ExcelWriter writer = ExcelUtil.getWriter("test.xlsx");
		writer.setSheet("Sheet2");
		writer.addHeaderAlias("tid", "订单号");
		List<NutMap> rows = Lists.newArrayList();
		rows.add(NutMap.NEW().setv("tid", "1000"));
		writer.write(rows, true);
		writer.close();
```
生成的xlsx文件中 总是多一个空白的sheet1 请问这个默认的sheet怎么不带呢？如果自定义了一个sheet后

**Comment by looly** [comment]
`public static ExcelWriter getWriter(File destFile, String sheetName)`

用这个指定sheet。
