### ISSUE TITLE
TimeInterval太弱鸡

### ISSUE THREAD

**Issue by maozexijr** [looly/hutool#1238]
TimeInterval 功能太弱鸡，建议入参追加个 name/key，用一个 timer 记录多组计时

**Comment by looly** [comment]
可以用`StopWatch`

**Comment by maozexijr** [comment]
`
public class TimerTool extends TimeInterval {

    Map<String, Long> timer;

    private TimerTool() {
        super();
        timer = new HashMap<>();
    }

    public static TimerTool getInstance(int key) {
        TimerTool tool = new TimerTool();
        tool.start(key);
        return tool;
    }

    private long start(int key) {
        long now = System.currentTimeMillis();

        if (timer.size() > 0) {
            timer.clear();
        }
        timer.put(String.valueOf(key), now);
        return now;
    }

    public long mark(int key) {
        long now = System.currentTimeMillis();

        timer.put(String.valueOf(key), now);
        return now;
    }

    public long append(int key, int next) {
        long now = System.currentTimeMillis();

        String name = String.valueOf(key);
        String then = String.valueOf(next);
        long interval = 0;
        if (timer.containsKey(name)) {
            interval = now - timer.get(name);
        }
        timer.put(then, now);
        return interval;
    }

    public long interval(int key) {
        long now = System.currentTimeMillis();

        String name = String.valueOf(key);
        if (timer.containsKey(name)) {
            return now - timer.get(name);
        } else {
            timer.put(name, now);
            return 0;
        }
    }

    public String prettyInterval(int key) {
        return DateUtil.formatBetween(interval(key));
    }
}
`


`
public class DateTool extends DateUtil {
    public static TimerTool timer(int key) {
        return TimerTool.getInstance(key);
    }
}
`


`
public class Test {

    public static void main(String[] args) throws InterruptedException {
        TimerTool timer = DateTool.timer(1);
        Thread.sleep(800);
        timer.mark(2);
        Thread.sleep(900);
        System.out.println(String.format("Timer 1 took %s ms", timer.interval(1)));
        Thread.sleep(1000);
        System.out.println(String.format("Timer 2 took %s ms", timer.append(2, 3)));
        Thread.sleep(1100);
        System.out.println(timer.prettyInterval(3));
    }

}
`

**Comment by maozexijr** [comment]
StopWatch 仍显鸡肋：①没法跨时间片区统计时间间隔，②多个时间片区不连续（stop().start('new')是两个步骤），③计时起始时间不复用，④用法繁琐不简洁，我写了一个不成熟的实现 @looly 

```
import cn.hutool.core.date.DateUtil;
import cn.hutool.core.date.TimeInterval;

import java.util.HashMap;
import java.util.Map;

public class TimerTool extends TimeInterval {

    Map<String, Long> timer;

    private TimerTool() {
        super();
        timer = new HashMap<>();
    }

    public static TimerTool getInstance(int key) {
        TimerTool tool = new TimerTool();
        tool.start(key);
        return tool;
    }

    private long start(int key) {
        long now = System.currentTimeMillis();

        if (timer.size() > 0) {
            timer.clear();
        }
        timer.put(String.valueOf(key), now);
        return now;
    }

    public long mark(int key) {
        long now = System.currentTimeMillis();

        timer.put(String.valueOf(key), now);
        return now;
    }

    public long append(int key, int next) {
        long now = System.currentTimeMillis();

        String name = String.valueOf(key);
        String then = String.valueOf(next);
        long interval = 0;
        if (timer.containsKey(name)) {
            interval = now - timer.get(name);
        }
        timer.put(then, now);
        return interval;
    }

    public long interval(int key) {
        long now = System.currentTimeMillis();

        String name = String.valueOf(key);
        if (timer.containsKey(name)) {
            return now - timer.get(name);
        } else {
            timer.put(name, now);
            return 0;
        }
    }

    public String prettyInterval(int key) {
        return DateUtil.formatBetween(interval(key));
    }

}

```

```

import cn.hutool.core.date.DateUtil;

public class DateTool extends DateUtil {

    public static TimerTool timer(int key) {
        return TimerTool.getInstance(key);
    }

}

```

```

public class Test {

    public static void main(String[] args) throws InterruptedException {
        TimerTool timer = DateTool.timer(1);
        Thread.sleep(800);
        timer.mark(2);
        Thread.sleep(900);
        System.out.println(String.format("Timer 1 took %s ms", timer.interval(1)));
        Thread.sleep(1000);
        System.out.println(String.format("Timer 2 took %s ms", timer.append(2, 3)));
        Thread.sleep(1100);
        System.out.println(timer.prettyInterval(3));
    }

}

```

**Comment by looly** [comment]
确实有这些问题。

稍晚处理，我想下如何改造现有类。

**Comment by looly** [comment]
5.5.2改造TimeInterval如下：

```java
final TimeInterval timer = new TimeInterval();
timer.start("1");
ThreadUtil.sleep(800);
timer.start("2");
ThreadUtil.sleep(900);


Console.log("Timer 1 took {} ms", timer.intervalMs("1"));
Console.log("Timer 2 took {} ms", timer.intervalMs("2"));
```

没有实现append方法，可以通过调用以下方法完成此功能：

```java
timer.intervalMs("2");
timer.start("3");
```
