### ISSUE TITLE
DateUnit.SECOND、DateField.SECOND、BetweenFormater.Level.SECOND 能统一到一个枚举类么？

### ISSUE THREAD

**Issue by maozexijr** [looly/hutool#1239]
DateUnit.SECOND、DateField.SECOND、BetweenFormater.Level.SECOND 能统一到一个枚举类么？

**Comment by looly** [comment]
意义不同。

DateUnit对应毫秒数
DateField对应Calendar
BetweenFormater.Level.SECOND对应格式化级别，没有周。

因此无法合并。

**Comment by maozexijr** [comment]
我晓得这三个枚举的应用场景的不同，但我想说的是这三个枚举都是在表达 秒 这个概念，调用者无需知道底层实现的不同，只要我想使用 秒 这个概念，有且仅有 某一个枚举类 可以使用，这才是最佳实现 @looly

**Comment by looly** [comment]
主要是field数量也不一样。

**Comment by maozexijr** [comment]
> 主要是field数量也不一样。

这。。确实是个问题。不过你可以暴露有限、足够的field，比如 年、月、日、时、分、秒、毫秒、季、周，常用的大约就这些
