### ISSUE TITLE
希望和postman可以无缝对接

### ISSUE THREAD

**Issue by wajncn** [looly/hutool#1242]
### 版本情况

JDK版本：    openjdk_8_201

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/37337912/99906772-e7b59e00-2d13-11eb-9476-e84bc07c7294.png)

在postman里面请求后 点击code 会出现在 okhttp 和 unirest  但是偏偏没有hutool-http.
所以建议开发者看下这个项目https://github.com/postmanlabs/postman-code-generators

**Comment by looly** [comment]
暂不考虑了，欢迎给这个项目提pr。
