### ISSUE TITLE
想请教一下SoapClient如何设置header

### ISSUE THREAD

**Issue by naimehao** [looly/hutool#1244]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
下面这是soapui中测试的内容
```xml

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://xxx.org/">
   <soap:Header>
      <tem:MySoapHeader>
         <!--Optional:-->
         <tem:UserName>xxxxxx</tem:UserName>
         <!--Optional:-->
         <tem:PassWord>xxxxxx</tem:PassWord>
      </tem:MySoapHeader>
   </soap:Header>
   <soap:Body>
      <tem:GetFzrxmxx>
         <!--Optional:-->
         <tem:ygbh>70204329</tem:ygbh>
      </tem:GetFzrxmxx>
   </soap:Body>
</soap:Envelope>

```

现在不知道怎么使用SoapClient来设置header中的用户名和密码
```java

public static void main(String[] args)
    {
        SoapClient client = SoapClient.create("http://xxx.xxx.xxx.xxx:8088/xxx/xxx.asmx");
        client.setMethod("tem:GetFzrxmxx","http://xxx.org/");
//请问如何设置头内的用户名与密码？

        client.setParam("ygbh", "70204329");
        String send = client.send();
        System.out.println(send);

    }

```
以上代码是可以正常执行并且得到返回的，只是因为没有设置用户名和密码，所以返回的内容提示了对应没有权限的信息。

**Comment by naimehao** [comment]
```java
public static void main(String[] args) throws SOAPException
    {
        SoapClient soapClient = SoapClient.create("http://xxx:8088/xxx/xxx.asmx")
                .setMethod("tem:GetFzrxmxx", "http://tempuri.org/");
        QName headerQName = new QName("http://xxx.org/", "MySoapHeader", "tem");
        QName userNameQName = new QName("http://xxx.org/", "UserName", "tem");
        QName passWordQName = new QName("http://xxx.org/", "PassWord", "tem");

        String userName = "xxx";
        String passWord = "xxx";

        SOAPHeaderElement soapHeaderElement = soapClient.addSOAPHeader(headerQName);
        soapHeaderElement.addChildElement(userNameQName).addTextNode(userName);
        soapHeaderElement.addChildElement(passWordQName).addTextNode(passWord);

        soapClient.setParam("ygbh", "70204329");

        String resultXml = soapClient.send();
//
    }
```

**Comment by lcnja** [comment]
> ### 版本情况
> JDK版本： openjdk_8_201
> hutool版本： 5.4.7（请确保最新尝试是否还有问题）
> 
> ### 问题描述（包括截图）
> 下面这是soapui中测试的内容
> 
> ```
> <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://xxx.org/">
>    <soap:Header>
>       <tem:MySoapHeader>
>          
>          <tem:UserName>xxxxxx</tem:UserName>
>          
>          <tem:PassWord>xxxxxx</tem:PassWord>
>       </tem:MySoapHeader>
>    </soap:Header>
>    <soap:Body>
>       <tem:GetFzrxmxx>
>          
>          <tem:ygbh>70204329</tem:ygbh>
>       </tem:GetFzrxmxx>
>    </soap:Body>
> </soap:Envelope>
> ```
> 
> 现在不知道怎么使用SoapClient来设置header中的用户名和密码
> 
> ```java
> public static void main(String[] args)
>     {
>         SoapClient client = SoapClient.create("http://xxx.xxx.xxx.xxx:8088/xxx/xxx.asmx");
>         client.setMethod("tem:GetFzrxmxx","http://xxx.org/");
> //请问如何设置头内的用户名与密码？
> 
>         client.setParam("ygbh", "70204329");
>         String send = client.send();
>         System.out.println(send);
> 
>     }
> ```
> 
> 以上代码是可以正常执行并且得到返回的，只是因为没有设置用户名和密码，所以返回的内容提示了对应没有权限的信息。

请问这个问题解决了吗?  @naimehao
