### ISSUE TITLE
hutool-all-5.4.0.jar

### ISSUE THREAD

**Issue by Leungheng** [looly/hutool#1245]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：hutool-all-5.4.0.jar（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
 static TimedCache<String, String> lockAppInfo = CacheUtil.newTimedCache(60000);

 // synchronized (lockAppInfo) {
//            String lockValueSource = lockAppInfo.get(roomno,false);
//            String lockValue = roomno + ":" + class_name + ":" + url;
//            if (StringUtils.isEmpty(lockValueSource)) {
//                lockAppInfo.put(roomno, lockValue);
//            } else {
//                //如果该房间号的值算出    来的值与锁里面的值相等证明是同一条数据返回
//                if (lockValueSource.equals(lockValue)) retu           lockAppInfo.put(roomno, lockValue, 10000);rn;
////
//            }
//        }
```
2.情况
 多线程情况下丢时时间失效。未对不同时间10000 的丢时进行测试目前是同一时间 300条线程下会出现丢时失效问题。

**Comment by looly** [comment]
我没太看懂你的意思。测试中丢时失效问题指？

**Comment by Leungheng** [comment]
在多线程情况下,dbug下看数据重复，并且到时间后数据没清除。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden Looly"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 中午1:40
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "亨亨"<604875700@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [looly/hutool] hutool-all-5.4.0.jar (#1245)





 
我没太看懂你的意思。测试中丢时失效问题指？

**Comment by looly** [comment]
1、关于数据没有清楚是因为需要调用`schedulePrune`方法启动定时任务，否则只有在get的时候清除。
2、数据重复指？
