### ISSUE TITLE
格式UTC日期失败了

### ISSUE THREAD

**Issue by aoyouxingkong** [looly/hutool#1249]
### 版本情况

JDK版本：   Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
hutool版本： 5.5.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

DateTime utcDateTime = DateUtil.parse("2020-11-24T09:39:21.799548092Z");
System.out.println("utcDateTime : " +utcDateTime);

2. 堆栈信息
Exception in thread "main" cn.hutool.core.date.DateException: No format fit for date String [2020-11-24T09:39:21.799548092Z] !
	at cn.hutool.core.date.DateUtil.parseUTC(DateUtil.java:841)
	at cn.hutool.core.date.DateUtil.parse(DateUtil.java:921)
	at com.seer.seerdemo.interceptor.Test.main(Test.java:51)
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by aoyouxingkong** [comment]
/**
     * UTC时间转化CST
     * @param utc
     * @return
     */
    public static String UTCtoCST(String utc){
        ZonedDateTime zdt  = ZonedDateTime.parse(utc);
        LocalDateTime localDateTime = zdt.toLocalDateTime();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(HOUR_PATTERN);
        return formatter.format(localDateTime.plusHours(8));
    }

**Comment by CherryRum** [comment]
那个首先说下您这个问题首先 `DateUtil.parse（yyyy-MM-dd'T'HH:mm:ss.SSS）`这个只能方法解析的规范就是这个，您的`YYYY-MM-DDTHH:mm:ss.sssssssssZ`精确纳秒并不适合这个方法。而且在Java语言中一般把ISO-8601这个规定SSS视为毫秒，所以你不可能达到1000毫秒，这样会使您的时间增加。

**Comment by looly** [comment]
是滴。貌似Java最高支持毫秒到999，没法支持到纳秒，所以这种格式没法解析，只能自行截取。
