### ISSUE TITLE
[建议] httpUtil body

### ISSUE THREAD

**Issue by changxinjie** [looly/hutool#125]
建议httpUtil get请求, 函数body() 参数放进请求体中, 而不是解析拼接在url后面, 类似 libcurl 的做法, 

虽然很少场景会用到, 但是个别场景只能这样做, 比如 ElasticSearch的validate api.

body函数本身就很语义化, 不用考虑新手错用的情况. 可以添加函数 params() 专门用于把参数拼接到url

**Comment by looly** [comment]
有道理。感谢意见。4.1.1做此逻辑。
