### ISSUE TITLE
有TOTP算法实现吗？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1257]
Google身份验证器Google Authenticator是谷歌推出的基于时间的一次性密码(Time-based One-time Password，简称TOTP)

**Comment by looly** [comment]
见：`cn.hutool.crypto.digest.opt.TOPT`

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/100415590-7f6e1000-30b7-11eb-90ac-3411b16f0f00.png)
名字起错了？应该是TOTP吧？？

**Comment by looly** [comment]
还真是。
