### ISSUE TITLE
ImgUtil.pressText本地正常，当放到服务器上时中文添加到图片上变成了乱码

### ISSUE THREAD

**Issue by MrWangYc** [looly/hutool#1258]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.1

### ImgUtil.pressText本地正常，当放到服务器上时中文添加到图片上变成了乱码

1. 复现代码

 Font addFont = new Font("Arial", Font.PLAIN, 14);
 Font addProFont = new Font("Arial", Font.BOLD, 14);
 int addX = -srcImgWidth / 2 + 56+address.length()*7;
 int addY = -srcImgHeight / 2 + 112;
 ImgUtil.pressText(imageFile, imageFile, address, Color.black, addProFont, addX , addY, 0.2f);
 ImgUtil.pressText(imageFile, imageFile, address, Color.white, addFont, addX+1, addY, 1);
//服务器版本
![image](https://sys.oss.rczfw.com/rc-eplus-system/2020/11/27/839d5dbac1284f34afc31322a5c7ab7e.jpg)
//本地版本
![image](https://sys.oss.rczfw.com/rc-eplus-system/2020/11/27/af6773276e8b45d58512bc2e202f5bea.jpg)

**Comment by looly** [comment]
服务器上没这个字体，装一下。
