### ISSUE TITLE
雪花算法id重复

### ISSUE THREAD

**Issue by zhangwangren** [looly/hutool#1260]
### 版本情况

JDK版本：    1.8
hutool版本： 5.5.1

### 问题描述（包括截图）
lambda表达式循环生成编号的时候，雪花算法id出现重复的情况
![image](https://user-images.githubusercontent.com/32890060/100428558-12ff0b00-30cf-11eb-9d74-2a77b953d7d8.png)
![image](https://user-images.githubusercontent.com/32890060/100428608-24481780-30cf-11eb-81bb-95df310773bf.png)
好像是 lastTimestamp 的问题，我自己在网上找的代码，把lastTimestamp设置为static好像就没问题。（有错勿喷~~~）

**Comment by looly** [comment]
使用IdUtil.getSnowflake

**Comment by zhangwangren** [comment]
谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午4:44
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"253911649"<253911649@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] 雪花算法id重复 (#1260)





 
使用IdUtil.getSnowflake
