### ISSUE TITLE
hutool-bom 问题

### ISSUE THREAD

**Issue by dong4j** [looly/hutool#1261]
一般的 bom 都是为了管理项目下所有模块的版本, 像 spring-framework-bom 一样, 我不想使用 hutool-all, 而是按照我的需求去添加具体的子模块, 我想使用 hutool-bom 去管理版本, 但是这样使用则不行:

```xml
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-bom</artifactId>
    <version>${hutool.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

能否将 hutool-bom 修改一下, 用以下这种方式:

```xml
<dependencyManagement>
    <dependency>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-core</artifactId>
        <version>${project.version}</version>
    </dependency>
    ...
</dependencyManagement>
```

这样我就不会在父模块中维护全部的子模块, 只需要使用 hutool-bom, 如果修改 hutool-bom 会影响其他用户, 也可添加 hutool-dependencies 来统一管理

**Comment by looly** [comment]
hutool的bom与其他框架略有不同，使用的是排除法：即默认是引入所有模块，通过排除去除不需要的模块。

**Comment by looly** [comment]
这个修改影响比较大。所以不考虑修改。

最简单的是引入hutool-all，体积并没有太大。
