### ISSUE TITLE
关于设计方案的请教

### ISSUE THREAD

**Issue by Shanchuanl** [looly/hutool#1262]
我在翻代码的时候有个问题没太看懂
BeanCopier 在执行拷贝方法的时候，为什么要在中间加一层ValueProvider，通过BeanValueProvider 调用Convert 类，若未设置自定义转换器，则会直接通过Convert 类调用默认转换器，为啥自定义要加ValueProvider，是出于哪些方面的考虑

**Comment by looly** [comment]
ValueProvider是为了提供一种抽象，即任何实现此接口的对象都可以转换为Bean，转换规则是可以自定义的。

在Hutool中BeanCopier承担了4种转换：

1. Bean 转 Bean
2. Bean 转 Map
3. Map  转 Bean
4. Map  转 Map

其中1和4的逻辑相似，都要解析目标bean的字段，为了去除重复代码，就定义了ValueProvider接口，这样可以共用目标bean的解析代码。
