### ISSUE TITLE
有生成这个ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();的工具类吗？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1264]

**Comment by looly** [comment]
见`cn.hutool.core.thread.ExecutorBuilder`

**Comment by joey-happy** [comment]
没发现newSingleThreadScheduledExecutor有这个

**Comment by joey-happy** [comment]
ScheduledExecutor

**Comment by looly** [comment]
`ThreadUtil.newSingleExecutor()`

![image](https://user-images.githubusercontent.com/1432613/100619872-adbe4a80-3358-11eb-8bd0-d57d7466b9f6.png)

**Comment by joey-happy** [comment]
ScheduledExecutor 我要的是这个 定时执行的executor
