### ISSUE TITLE
邮编正则表达式错误

### ISSUE THREAD

**Issue by Demon95** [looly/hutool#1274]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.1

### 问题描述 
`PatternPool.java` 中邮编的正则为 `public final static Pattern ZIP_CODE = Pattern.compile("[1-9]\\d{5}(?!\\d)");` 实际上，内蒙古自治区、山西省，河北省的邮编均以0开头。

[PatternPool.java](https://github.com/looly/hutool/blob/e2a7c06af95347d16db2adcb447859a638d11625/hutool-core/src/main/java/cn/hutool/core/lang/PatternPool.java)

[中华人民共和国境内地区邮政编码列表](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%A2%83%E5%86%85%E5%9C%B0%E5%8C%BA%E9%82%AE%E6%94%BF%E7%BC%96%E7%A0%81%E5%88%97%E8%A1%A8#%E8%8F%AF%E5%8C%97_0)

**Comment by looly** [comment]
5.5.2修复此问题，感谢。

新的正则为：`^(0[1-7]|1[0-356]|2[0-7]|3[0-6]|4[0-7]|5[0-7]|6[0-7]|7[0-5]|8[0-9]|9[0-8])\d{4}|99907[78]$`

新的正则兼容了港澳台地区邮编。
