### ISSUE TITLE
反馈bug，BeanUtil的bug

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#1276]
存在bug的方法 BeanUtil.copyProperties
描述：
如果source内某个属性为枚举类型，target同属性名对应的属性类型为数字则会报错
spring的BeanUtil.copyProperties不会报错，但是没有 copyProperties(Object source, Class<T> tClass)方法，需要先 new 再copy。
代码如下
`package xyz.booke.freebook.reader.test.utils;

import cn.hutool.core.bean.BeanUtil;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import org.junit.jupiter.api.Test;
import org.springframework.beans.BeanUtils;

public class HuToolTest {

    @AllArgsConstructor
    private enum UserGender {
        NONE(0, "none"),
        BOY(1, "boy"),
        GIRL(2, "girl");

        @Getter
        private Integer code;

        @Getter
        private String name;

        public static UserGender valueOf(int code) {
            for (UserGender gender : UserGender.values()) {
                if (gender.code == code) {
                    return gender;
                }
            }
            throw new IllegalArgumentException("UserGender not fond by code:" + code);
        }
    }

    @Data
    private static class AddUserRequest{
        private String name;
        private UserGender gender;
    }

    @Data
    private static class User{
        private String name;
        private Integer gender;
    }

    @Test
    public void huTool(){
        AddUserRequest addUserRequest = new AddUserRequest();
        {
            addUserRequest.setName("hu tool");
            addUserRequest.setGender(UserGender.BOY);
        }

        User user = BeanUtil.copyProperties(addUserRequest,User.class);
        System.out.println(user);
    }

    @Test
    public void spring(){
        AddUserRequest addUserRequest = new AddUserRequest();
        {
            addUserRequest.setName("spring");
            addUserRequest.setGender(UserGender.BOY);
        }

        User user = new User();
        {
            BeanUtils.copyProperties(addUserRequest,user);
            user.setGender(addUserRequest.gender.getCode());
        }
        System.out.println(user);
    }

}
`
![image](https://user-images.githubusercontent.com/34471928/100856738-c51b4600-34c6-11eb-9226-f40ee362fdf9.png)
在源码中发现没有判断枚举类型，直接将枚举对象转为了字符串，然后再用parseInt强行转换
final String valueStr = convertToStr(value);
return StrUtil.isBlank(valueStr) ? null : NumberUtil.parseInt(valueStr);

希望对枚举类型可以自动跳过转换
如：
source中字段a为枚举，target中a字段类型与source中a字段类型不一致则跳过转换

**Comment by looly** [comment]
请升级hutool到5.5.1（或者5.5.2），我记得新版本解决了这个问题，我这边新版测试正常，
