### ISSUE TITLE
关于台湾身份证的校验问题

### ISSUE THREAD

**Issue by lifesign** [looly/hutool#1277]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.4.5

### 问题描述（包括截图）

在使用 `cn.hutool.core.util.IdcardUtil#isValidCard` 方法时，传参有 830000 开头的身份证，校验失败，看了下代码是校验 city code 失败

![image](https://user-images.githubusercontent.com/2189610/100856760-cba9bd80-34c6-11eb-9814-8d4cff715523.png)

cityCode 在初始化的时候，并不存在 83
![image](https://user-images.githubusercontent.com/2189610/100856824-df552400-34c6-11eb-940f-99a4c5f5f28a.png)

我查阅了官方的一些文档，有一个比较坑的地方，虽然台湾是 710000，但是身份证是 830000

![image](https://user-images.githubusercontent.com/2189610/100857318-8639c000-34c7-11eb-9771-a048f865caa6.png)

《中华人民共和国行政区划代码 (8区)》
https://zh.m.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E4%BB%A3%E7%A0%81_(8%E5%8C%BA)

《港澳台居民居住证申领发放办法》
http://www.gov.cn/zhengce/content/2018-08/19/content_5314865.htm

**Comment by CherryRum** [comment]
的确台湾和行政区，规划不太一样，有空我提个pr,大佬有空审核下 @looly

**Comment by looly** [comment]
我把83也加上吧。

5.5.3加入。

**Comment by CherryRum** [comment]
嗯嗯 有改变了再说，本来想修复下身份证日期判断
