### ISSUE TITLE
http模块新增可扩展点

### ISSUE THREAD

**Issue by tanoak10** [looly/hutool#1279]
hutool-http 模块是否可以增加一下前置处理的，比如过滤器，用于增加日志记录的请求参数以及返回结果，类似
httpclient 中的
```
.addInterceptorFirst(new HttpClientRequestInterceptor())
.addInterceptorLast(new HttpClientRequestInterceptor())
```

**Comment by looly** [comment]
~~hutool的是通过统一准备好数据然后一次性发出的，HttpRequest本身就是个builder，因此意义不大。~~

5.7.16支持了~

**Comment by calmer-xu** [comment]
附议，请问统一加日志的场景当前有什么合适的解决方案么？

**Comment by looly** [comment]
@calmer-xu 5.7.16可以支持了：

```java
HttpUtil.createGet().addInterceptor();
```

**Comment by calmer-xu** [comment]
> @calmer-xu 5.7.16可以支持了：
> 
> ```java
> HttpUtil.createGet().addInterceptor();
> ```

收到，感谢
