### ISSUE TITLE
反馈bug，BeanUtil.copyProperties

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#1280]
描述：
如果source中a属性是枚举，target中a属性是非枚举，则会报错

使用spring的BeanUtils.copyProperties没问题，但是需要先new对象才能copy

代码如下

`import cn.hutool.core.bean.BeanUtil;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import org.junit.jupiter.api.Test;
import org.springframework.beans.BeanUtils;

public class HuToolTest {

    @AllArgsConstructor
    private enum UserGender {
        NONE(0, "none"),
        BOY(1, "boy"),
        GIRL(2, "girl");

        @Getter
        private Integer code;

        @Getter
        private String name;

        public static UserGender valueOf(int code) {
            for (UserGender gender : UserGender.values()) {
                if (gender.code == code) {
                    return gender;
                }
            }
            throw new IllegalArgumentException("UserGender not fond by code:" + code);
        }
    }

    @Data
    private static class AddUserRequest{
        private String name;
        private UserGender gender;
    }

    @Data
    private static class User{
        private String name;
        private Integer gender;
    }

    @Test
    public void huTool(){
        AddUserRequest addUserRequest = new AddUserRequest();
        {
            addUserRequest.setName("hu tool");
            addUserRequest.setGender(UserGender.BOY);
        }

        User user = BeanUtil.copyProperties(addUserRequest,User.class);
        System.out.println(user);
    }

    @Test
    public void spring(){
        AddUserRequest addUserRequest = new AddUserRequest();
        {
            addUserRequest.setName("spring");
            addUserRequest.setGender(UserGender.BOY);
        }

        User user = new User();
        {
            BeanUtils.copyProperties(addUserRequest,user);
            user.setGender(addUserRequest.gender.getCode());
        }
        System.out.println(user);
    }

}`

![image](https://user-images.githubusercontent.com/34471928/100954260-2c7cd880-354f-11eb-9c50-528a4af17cef.png)

查看源码发现并没有判断 source的类型，只判断了targetType

建议：如果source中a属性为枚举，target中a属性必须为source中a属性的类型，否则跳过改属性

**Comment by zhouxiaofu** [comment]
还有 source中的是Boolean,target中的是Integer应该也会出问题
出现这种问题主要是因为数据库中存枚举和布尔都是 tinyint类型的，dto是对应的枚举或者布尔值

**Comment by looly** [comment]
升级到最新试下，我记得这个提过了啊。

**Comment by looly** [comment]
见：https://github.com/looly/hutool/issues/1276
