### ISSUE TITLE
Excel readBySax方式读取自定义格式时问题

### ISSUE THREAD

**Issue by JarhomLiu** [looly/hutool#1283]
### 版本情况
最新版本：5.5.2

### 问题描述（包括截图）
用 readBySax方式读取xlsx文件时有下面这种情况：
![2020-12-04](https://user-images.githubusercontent.com/44824412/101109936-e5581b80-3612-11eb-805e-0894d2ef8c78.JPEG)
![2020-12-04-01](https://user-images.githubusercontent.com/44824412/101109966-f3a63780-3612-11eb-94dc-b65ee96a51eb.JPEG)
如图片所示，当我选择自定义格式的时候，红色框里的这几种日期格式是解析出数字的，并不是想要的日期。这个问题麻烦您看下。附件我也发一下。
[自定义日期格式.xlsx](https://github.com/looly/hutool/files/5640011/default.xlsx)

**Comment by looly** [comment]
好吧，严格来说是POI的bug，自定义日期格式中的格式index并不被识别，因此在`ExcelSaxUtil.isDateFormat`中加入：
```java
if (formatIndex == 28 || formatIndex == 31) {
	// 28 -> m月d日
	// 31 -> yyyy年m月d日
	return true;
}
```

参考：

https://blog.csdn.net/u014342130/article/details/50619503

5.5.3修复此问题，感谢。
