### ISSUE TITLE
CglibUtil copy报错

### ISSUE THREAD

**Issue by yiming33** [looly/hutool#1284]
### 版本情况

JDK版本：    jdk1.8.0_162
hutool版本： 5.5.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
最简单的复制，一直报错
java.lang.NoClassDefFoundError: net/sf/cglib/core/Converter

![image](https://user-images.githubusercontent.com/19584310/101135376-ab087180-3646-11eb-8427-ad37862ffd18.png)

![image](https://user-images.githubusercontent.com/19584310/101135387-b0fe5280-3646-11eb-8985-41ae272ec688.png)

![image](https://user-images.githubusercontent.com/19584310/101135496-d9864c80-3646-11eb-9a10-13c6f2105c26.png)

![image](https://user-images.githubusercontent.com/19584310/101135516-e014c400-3646-11eb-98e7-5dff74dadadf.png)

**Comment by 440981** [comment]
请问你是怎么解决的?我也出现了这个问题
