### ISSUE TITLE
希望BiMap能够扩展一下

### ISSUE THREAD

**Issue by cqyisbug** [looly/hutool#1288]
现在要求key value 都不能重复,能否实现一个key不能重复,但是value 可以重复的map
因为有些场景是一对多 的关系

**Comment by sky20086** [comment]
biMap是双向map，既可以根据key找value也可以根据value找key，你这要求value可以重复，根据value还怎么找key？
如果不需要根据value找key，为什么用bimap，直接hashmap不就可以了？

**Comment by sky20086** [comment]
biMap是双向map，既可以根据key找value也可以根据value找key，你这要求value可以重复，根据value还怎么找key？
如果不需要根据value找key，为什么用bimap，直接hashmap不就可以了？

**Comment by cqyisbug** [comment]
> biMap是双向map，既可以根据key找value也可以根据value找key，你这要求value可以重复，根据value还怎么找key？
> 如果不需要根据value找key，为什么用bimap，直接hashmap不就可以了？

k1-> v1 
k2-> v1

get(k1)  return v1
getKey(v1) return {k1,k2}

**Comment by looly** [comment]
可以用：TableMap
