### ISSUE TITLE
Excle输出bean,没法指定列的展示顺序

### ISSUE THREAD

**Issue by CodeZLei** [looly/hutool#129]
Excle输出bean,没法指定列的展示顺序,没有相应的方法提供

**Comment by CodeZLei** [comment]
Excle输出bean,没法指定列的展示顺序,没有响应的方法提供

**Comment by CodeZLei** [comment]
![image](https://user-images.githubusercontent.com/26864923/42429648-ddf0a714-836c-11e8-9cd4-b286bf19984d.png)
把定义列的展示顺序,把name放在第一列

**Comment by zhugunzi** [comment]
可以自己排序生成List<List<String>>然后导出

**Comment by CodeZLei** [comment]
我说的是在excel中列的排序展示,不是行的排序展示

**Comment by zhugunzi** [comment]
//导出转换
    //将List<Bean> 按自定义有序的headMap 顺序转换成 List<List<String>>
    public static List<List<Object>> convertExcelData(List<Object> list, Map headLinkedHashMap) {

        List<List<Object>> res = new ArrayList<List<Object>>();

        Iterator iterator = list.iterator();
        while (iterator.hasNext()) {

            Iterator keyIterator = headLinkedHashMap.keySet().iterator();
            Map map = BeanUtil.beanToMap(iterator.next());
            List row = new ArrayList();
            while (keyIterator.hasNext()) {
                Object key = keyIterator.next();
                row.add(map.get(key));
            }

            res.add(row);
        }
        res.add(0, new ArrayList(headLinkedHashMap.values()));

        return res;
    }

**Comment by zhugunzi** [comment]
headMap 中要放入的就是你自定义的列名 并且是有序的

**Comment by CodeZLei** [comment]
嗯,自己写的话指定没问题,我是希望在对应的jar里面添加相应的实现方法

**Comment by looly** [comment]
4.1.2将支持自定义顺序

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/42511684-2781adc4-8485-11e8-8e34-9f94f17e57ba.png)

**Comment by looly** [comment]
可以使用此方法自定义字段比较器，此比较器用于比较字段名的顺序。
