### ISSUE TITLE
对cn.hutool.cache.impl.CacheObj的isExpired()方法的小建议

### ISSUE THREAD

**Issue by fymenglovewxliu** [looly/hutool#1295]
### 版本情况

JDK版本： oraclejdk_1.8.0_271
hutool版本： 5.5.3-SNAPSHOT

### 问题描述（包括截图）
[问题描述](https://raw.githubusercontent.com/fymenglovewxliu/test/master/isExpired.png)
觉得cn.hutool.cache.impl.CacheObj的方法boolean isExpired()中的逻辑判断有点奇怪：
如果long型变量expiredTime因为溢出而变为了负数，那么isExpired()会返回false，我理解作者应该是认为此时ttl非常大，所以没有过期。
其实改成
return (System.currentTimeMillis() - this.lastAccess) > this.ttl;
会更好一些，采用“两时间之差”从而避免了long型溢出的问题，可能会更好理解一些。

**Comment by looly** [comment]
有道理啊，茅塞顿开，哈哈。感谢，5.5.3修改逻辑。
