### ISSUE TITLE
对于cn.hutool.core.lang.UUID的方法private UUID(byte[] data)的小建议

### ISSUE THREAD

**Issue by fymenglovewxliu** [looly/hutool#1296]
### 版本情况

JDK版本： oraclejdk_1.8.0_271
hutool版本： 5.5.3-SNAPSHOT

### 问题描述（包括截图）

[问题描述](https://raw.githubusercontent.com/fymenglovewxliu/test/master/uuid.png)

对于cn.hutool.core.lang.UUID的方法private UUID(byte[] data)，因为 i & 1 恒等于 i，所以 data[i] & 0xff 恒等于 data[i]。
因此建议把上图中两处 data[i] & 0xff 改为 data[i] ，这样可以避免一次位运算的计算量。

**Comment by zx-zy-zhu** [comment]
"因为 i & 1 恒等于 i，所以 data[i] & 0xff 恒等于 data[i]"，你再想想。。。

**Comment by fymenglovewxliu** [comment]
> "因为 i & 1 恒等于 i，所以 data[i] & 0xff 恒等于 data[i]"，你再想想。。。

你觉得问题在哪里呢？

**Comment by fymenglovewxliu** [comment]
> "因为 i & 1 恒等于 i，所以 data[i] & 0xff 恒等于 data[i]"，你再想想。。。

我知道我哪里错了!!!
在 data[i] & 0xff 时，java会将byte类型的data[i]提升为int类型，提升的规则是用byte的最高位填补int的高位3字节，
因此若data[i]的最高位是1的话，
例如data[i]为 10000001，
则data[i]会被提升为11111111 11111111 11111111 10000001，
与int类型的0xff（即00000000 00000000 00000000 11111111）按位与运算之后，
得到的结果是int类型，即00000000 00000000 00000000 1000001，
此时若再与data[i]进行相等比较，data[i]会再次被提升为int类型（即11111111 11111111 11111111 10000001），
而显然00000000 00000000 00000000 11111111与11111111 11111111 11111111 10000001不相等。

谢谢提醒，学到了！

**Comment by looly** [comment]
我也学习了，hutool的UUID是使用JDK的改造而来的。
