### ISSUE TITLE
使用csvutil时无法正确解析

### ISSUE THREAD

**Issue by jianlong-sun** [looly/hutool#1298]
### 版本情况

JDK版本：   jdk 1.8
hutool版本： 5.5.2

### 问题描述（包括截图）
csvutil 如下代码：读取到2135那一行 后面数据不再进行读取，无法获取整个csv列表。
1. 复现代码

```java
        CsvReader reader = CsvUtil.getReader();
//设置文件读取的分隔符
        reader.setFieldSeparator(',');
//根据特定的编码方式读取File的内容
        CsvData csvData = reader.read(resource.getFile(), StandardCharsets.UTF_8);
//读取文件中的所有的行数据
        List<CsvRow> rows = csvData.getRows();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
```
南浦大桥,2133
赵州桥,2134
",2135
赵,2136
州,2137
```

**Comment by winlans** [comment]
@jianlong-sun 
你这个是数据有问题,  或者你改下配置也行, 因为默认的TextDelimiter 是 `"` , 因此如果出现了`"` 那么就必须出现下一个`"`否则后面的都算一列, 可以用`reader.setTextDelimiter('"');`改成其他的, 例如用 反引号 但是要根据你的数据格式来

**Comment by jianlong-sun** [comment]
非常感谢解惑
