### ISSUE TITLE
邮件工具类配置文件存在问题

### ISSUE THREAD

**Issue by CodeLunatic** [looly/hutool#1301]
### 版本情况

JDK版本：    java version "14.0.2" 2020-07-14
hutool版本： 5.5.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

问题描述：邮件工具类使用配置文件，配置存在问题：

配置1：按照官方文档进行配置

```
from = cy@yi9.top
user = CY
pass = ...
host = smtp.yi9.top
```

发生认证失败的错误：

```
cn.hutool.extra.mail.MailException: AuthenticationFailedException: 526 Authentication failure[0]
```

打断点查看问题，发现此时登录所用的`user`为`cy`

配置2：交换`from`和`user`配置

```
from = cy
user = cy@yi9.top
pass = ...
host = smtp.yi9.top
```

发生语法错误的问题，猜疑是因为`from`不符合格式导致：

```
com.sun.mail.smtp.SMTPSendFailedException: 500 Error: bad syntax
```

配置3：正确的配置

```
from = cy@yi9.top
user = cy@yi9.top
pass = ...
host = smtp.yi9.top
```

此时可以正确的发送邮件

![image](https://user-images.githubusercontent.com/40259896/101592154-b8e43b00-3a28-11eb-9068-c0faf5dcbe09.png)

但是我想让收到邮件的`from`变为大写的`CY`，所以必须使用下面的配置

```
from = CY@yi9.top
user = CY@yi9.top
pass = ...
host = smtp.yi9.top
```

![image](https://user-images.githubusercontent.com/40259896/101592335-0b255c00-3a29-11eb-8f31-063041d33926.png)

但是这感觉并不符合`from`的用法，其他邮件工具中可以自定义`from`的格式，例如**配置2**中的那种配置

比如使用`OhMyEmail`：

```
    /**
     * smtp yi9
     *
     * @param debug enable debug
     */
    public static Properties SMTP_YI9(boolean debug) {
        Properties props = OhMyEmail.defaultConfig(debug);
        props.put("mail.smtp.host", "smtp.yi9.top");
        return props;
    }

    public static void main(String[] args) throws SendMailException {
        OhMyEmail.config(SMTP_YI9(true), "cy@yi9.top", "xs13934372635..");
        OhMyEmail.subject("主题").from("邮件来源").to("dnydict@163.com").text("测试内容").send();
    }
```

收到的邮件如下：

![image](https://user-images.githubusercontent.com/40259896/101594193-3bbac500-3a2c-11eb-8c6e-81efff0ecf5c.png)

配置4：理想中的状态，不用填写SMTP域名

```
from = CY
user = cy@yi9.top
pass = ...
```

但是此时出现错误：

```
cn.hutool.extra.mail.MailException: MessagingException: Unknown SMTP host: smtp.CY
```

**Comment by looly** [comment]
from是和账号关联的，你可以：

```
from == CY<cy@yi9.top>
```

具体参考`RFC-822`

![image](https://user-images.githubusercontent.com/1432613/101682973-49f5f900-3a9f-11eb-8270-286839a055e1.png)
