### ISSUE TITLE
readBySax 解析excel文件，解析出的数据为空

### ISSUE THREAD

**Issue by JarhomLiu** [looly/hutool#1303]
readBySax 解析excel文件，解析出的数据为空。
参数传 -1,0都不行。但是打开文件，啥都不改，直接保存就又有数据了。
麻烦看下是什么原因导致的，我们能用什么方法先规避一下

[456789.xlsx](https://github.com/looly/hutool/files/5678294/456789.xlsx)

**Comment by looly** [comment]
这个excel格式好奇怪：

```xml
<c r="C3" s="26" t="inlineStr">
    <is>
        <t>乔峰</t>
    </is>
</c>
```

标准的应该是：

```xml
<c r="C3" s="26" t="inlineStr">
    <v>乔峰</v>
</c>
```

没有找到相关的资料。

我考虑做个适配吧。

**Comment by looly** [comment]
确定为bug吧，5.5.3修复此问题，感谢。

考虑回退到5.4.7应该可以正常读取。

**Comment by JarhomLiu** [comment]
十分感谢
