### ISSUE TITLE
Excel读取出来的数据最后一列有丢失的单元格信息

### ISSUE THREAD

**Issue by xlhtc007** [looly/hutool#1319]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用ExcelReader读取Excel文件，最后一列的空单元格没有加入最终的结果集中，非最后一列的空单元格不会丢失。示例Excel见截图，期望标红部分的元素可以放入结果集中，这样结果是一个m*n的矩阵
1. 复现代码

```java
cn.hutool.poi.excel.ExcelReader#read()
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

![image](https://user-images.githubusercontent.com/570367/102465569-c59c0b00-4088-11eb-9e62-c9bc90341f4a.png)

**Comment by looly** [comment]
因为最后一列就没有值，或者单元格定义为空。

**Comment by xlhtc007** [comment]
> 因为最后一列就没有值，或者单元格定义为空。

没有值希望的是有元素，值可以是空的，其他列没有值结果集里面就有元素的，希望和其他列的处理保持一致

**Comment by looly** [comment]
这个取决于你的Excel中有没有创建这个单元格。

而且这行到底有多少单元格没法判定。

**Comment by xlhtc007** [comment]
> 这个取决于你的Excel中有没有创建这个单元格。
> 
> 而且这行到底有多少单元格没法判定。

帮忙评估一下：以首行的单元格数量作为基准，少于这个数量后面自动补上空值元素这种方案
在read()方法入参增加一个配置选项，默认还是现有处理模式，如果指定的话就自动补全结尾的空值元素
主要是现在的逻辑读出来的二维数组，子数组长度不一致，不是标准的矩阵形式

**Comment by looly** [comment]
有道理。我试下。先open。

**Comment by looly** [comment]
这个我就不封装了，考虑自行实现`SheetReader`或者`CellHandler`即可。

**Comment by xlhtc007** [comment]
> 这个我就不封装了，考虑自行实现`SheetReader`或者`CellHandler`即可。

咱们框架支持扩展是吧，具体实现哪个接口的哪个方法？

**Comment by Noooooooone** [comment]
5.8.5仍有此问题。当我通过ExcelUtil.getReader()方法读取的时候，最后一列的内容已经被丢弃，返回的结果不是标准矩阵格式。如果自定义支持把空值填充成功null或其他内容，需要如何实现

**Comment by looly** [comment]
@Noooooooone Excel中POI定义的cell分成两种情况，一是有单元格没有值，二是根本没有单元格，ExcelUtil.getReader是遵从原Excel表格读取的。

你说的这种情况很难对齐，举个例子，假如1000条数据，只有一条数据的长度是10，其他为9，那需要填充所有长度为9的单元格，这样很难做。

**Comment by Noooooooone** [comment]
可以以第一行为基准，第一行普遍是标题行。第一行的列为读取长度。小于此长度的补全，大于此长度的舍弃。

**Comment by looly** [comment]
@Noooooooone 补全好说，丢弃读取的值用户会疯掉的……

Hutool要兼顾各种用户，因此有了现在的读取方式。

**Comment by Noooooooone** [comment]
> @Noooooooone 补全好说，丢弃读取的值用户会疯掉的……
> 
> Hutool要兼顾各种用户，因此有了现在的读取方式。

主要现在补全也没有，导致返回的集合中长度不一样......

**Comment by zlsq** [comment]
为什么不以第一行（头行）为准呢，直接为null也行，但是不能直接丢失掉值呀

**Comment by looly** [comment]
@zlsq 不是丢掉值，而是Excel对应这个单元格就没有值。第一行为准这种规则是不准确的，因为第一行不一定是标题。万一第一行只有一个单元格有值，那后面行的数据都要丢掉么？

**Comment by Fankekeke** [comment]
![image](https://github.com/dromara/hutool/assets/42531874/f6e9fa9c-a01b-4322-bcec-4ba630b37d2e)
如果excel模板是由己方生成，更粗暴的方式可以在最后列加标识，read出来后再进行remove，这样就能取到完整的数据了

**Comment by looly** [comment]
@Fankekeke 那这样就把Excel读取复杂化了。而且Hutool确实没考虑过Excel模板的情况，考虑easyExcel等三方库？
