### ISSUE TITLE
对象拷贝时,不同类型的相同字段也可以进行拷贝

### ISSUE THREAD

**Issue by laokamo** [looly/hutool#1320]
### 版本情况

JDK版本：    oracle-jdk_8_201
hutool版本： 5.5.0

### 问题描述（包括截图）

对象拷贝时 字段名相同,字段类型不同也能拷贝

1. 复现代码

A{
  String position;
}

B{
  List<String> position;
}

BeanUtil.copyProperties(a, b);

**Comment by looly** [comment]
对啊，这个有啥问题额么？类型不同会自动调用Convert转换。
