### ISSUE TITLE
BeanUtil.copyProperties老是有各种问题

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#1327]
### 版本情况

JDK版本：    openjdk 1.8
hutool版本： 5.5.4
BeanUtil.copyProperties
如果A对象中有一个字段是Integer类型，B中同名字段的类型是枚举，则会报错枚举中有一个属性对应A中的那个字段
希望无法转换的字段不要报错

![image](https://user-images.githubusercontent.com/34471928/102840638-43239a80-443e-11eb-82de-eb91c2a265b8.png)

**Comment by zhouxiaofu** [comment]
有的类似的可以转，有的不行

**Comment by zhouxiaofu** [comment]
但是希望无法转换的字段不要报错

**Comment by looly** [comment]
转换规则为：数字转换为enum的序号对应的enum值。

你可以在CopyOption里设置是否忽略错误。
