### ISSUE TITLE
hutool Json 解析Json到实体类时，怎样使用别名？

### ISSUE THREAD

**Issue by nieyuan1980** [looly/hutool#1329]
### 版本情况

JDK版本：    jdk1.8.0_212
hutool版本：5.5.2

### 问题描述（包括截图）
1.Json串

{
  "errcode": 0,
  "errmsg": "ok",
  "department": [
    {
      "id": 2,
      "name": "广州研发中心",
      "name_en": "RDGZ",
      "parentid": 1,
      "order": 10
    },
    {
      "id": 3,
      "name": "邮箱产品部",
      "name_en": "mail",
      "parentid": 2,
      "order": 40
    }
  ]
}

2.实体类

/*
 * @Author: Administrator
 * @DateTime: 2020/12/7 16:05
 * @Description: 部门
 */
public class WeChat_Department implements Serializable {

    /*部门id*/
    private Long departmentId;

    /*部门名称*/
    private String name;

    /*英文名称
    此字段从2019年12月30日起，对新创建第三方应用不再返回，2020年6月30日起，对所有历史第三方应用不再返回该字段*/
    private String nameEn;

    /*父部门id
    根部门为 1*/
    private Long parentId;

    /* 在父部门中的次序值
      order值大的排序靠前。值范围是[0, 2^32)*/
    private Long order;
}

json里面的"id"对应实体类里面的是departmentId，这样就取不出来

**Comment by looly** [comment]
使用@Alias注解即可。

**Comment by nieyuan1980** [comment]
您好，请问，有具体文档可以参考吗？
@alias注解，是作用在实体类上面吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午4:34
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"缘来是渊"<nieyuan1980@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] hutool Json 解析Json到实体类时，怎样使用别名？ (#1329)





 
使用@alias注解即可。

**Comment by looly** [comment]
放在字段上即可：

```java
@Data
public static class BeanWithAlias {
	@Alias("name")
	private String value1;
	@Alias("age")
	private Integer value2;
}
```

**Comment by nieyuan1980** [comment]
可以了，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午4:43
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"缘来是渊"<nieyuan1980@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] hutool Json 解析Json到实体类时，怎样使用别名？ (#1329)





 
放在字段上即可：
 @Data public static class BeanWithAlias { 	@Alias("name") 	private String value1; 	@Alias("age") 	private Integer value2; }
