### ISSUE TITLE
CollUtil

### ISSUE THREAD

**Issue by yexuchen** [looly/hutool#133]
CollUtil.findOne 源码当中没有加对集合为空的判断，导致对集合行foreach遍历的时候会报空指针异常
![snipaste_2018-07-10_16-07-08](https://user-images.githubusercontent.com/21358074/42497428-ea95704a-845b-11e8-9c9f-866ff4d23569.png)

**Comment by yexuchen** [comment]
作者，不知道算不算bug，但是我觉得如果需要操作的集合为空，结果直接返回空会不会好点

**Comment by looly** [comment]
算bug。十分感谢。4.1.2修复此问题。
