### ISSUE TITLE
HttpUtil的POST请求传递单一参数时候会多余一个=号

### ISSUE THREAD

**Issue by dan47645** [looly/hutool#1331]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.5.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String post = HttpUtil.post(getUserRole,username);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
测试的时候传递的用户名是zzzz，可是接收的时候多了一个=号
![image](https://user-images.githubusercontent.com/28745921/102980532-ad256800-4542-11eb-8b0f-c8febd3dbde1.png)
![image](https://user-images.githubusercontent.com/28745921/102980563-bb738400-4542-11eb-87a1-ed730b97b824.png)

**Comment by looly** [comment]
需要自定义一下`ContentType`。

```java
HttpRequest.post("http://hutool.cn")
    .body("zzzz", ContentType.JSON.getValue())
    .execute().body();
```

具体见：https://blog.csdn.net/crazyamada/article/details/60876667
