### ISSUE TITLE
JSONArray.toList方法 如果I对象熟悉中存在枚举，反序列化枚举值不正确

### ISSUE THREAD

**Issue by MySelfBlank** [looly/hutool#1333]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JSONArray.toList方法 如果I对象熟悉中存在枚举，反序列化枚举值不正确
1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
枚举是自动处理的。

你json中的值是啥？如果是数字，是按照indexOf类似的方法处理的，如果是String，是匹配枚举的name的。

**Comment by MySelfBlank** [comment]
枚举中存的是key和Value
Json 中是Value 

对象属性中就枚举对象
转换的时候取到的枚举不是value对应的Key而是枚举里的第一个枚举值


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 晚上10:49
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"Blank丶White"<yzhzhiheng@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] JSONArray.toList方法 如果I对象熟悉中存在枚举，反序列化枚举值不正确 (#1333)





 
枚举是自动处理的。
 
你json中的值是啥？如果是数字，是按照indexOf类似的方法处理的，如果是String，是匹配枚举的name的。

**Comment by syzsh** [comment]
@MySelfBlank 枚举中是否存在静态方法, 如果有的话可以参考:
https://github.com/dromara/hutool/issues/2075#issue-1095932300
