### ISSUE TITLE
NumberConverter#toBigDecimal方法带千分位的字符串数据转换失败

### ISSUE THREAD

**Issue by jacky2048** [looly/hutool#1334]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
<img width="859" alt="图片" src="https://user-images.githubusercontent.com/21087169/102989633-e9f85b80-4550-11eb-9dbd-292496284311.png">
<img width="758" alt="图片" src="https://user-images.githubusercontent.com/21087169/102989787-2fb52400-4551-11eb-8e92-ccacbb9618e1.png">

1. 复现代码

```java
NumberConverter.toBigDecimal("1,234.55")
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
<img width="1005" alt="图片" src="https://user-images.githubusercontent.com/21087169/102989825-3e034000-4551-11eb-93b4-a5b0350e89fd.png">

比如报错的Excel文件，有问题的图片等。

4.解决方案
在convertToStr方法增加千分符的判断，存在千分符去掉

**Comment by looly** [comment]
5.5.5会在NumberUtil增加逻辑：

```java
try{
	number = NumberUtil.parseNumber(number).toString();
} catch (Exception ignore){
	// 忽略解析错误
}
```
