### ISSUE TITLE
引入hutool-all时，可以排除hutool-json吗?

### ISSUE THREAD

**Issue by duktig666** [looly/hutool#1338]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

引入`hutool-all`时，可以排除`hutool-json`吗?
没有单独引入的原因是只想排除json，剩下保留。项目中需要确定一种json的序列化方式，但是经常会误使用到hutool-json。（上次在gitee提了issues，得到回复目前hutool-json不能做redis的json序列化方式）。

使用如下方式并不能其效果
```
<!--    hutool的java开发工具包    -->
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>${hutool.version}</version>
    <exclusions>
        <exclusion>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-json</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by looly** [comment]
可以使用json-bom，然后在maven中排除不需要的模块。
