### ISSUE TITLE
在线文档中有错误

### ISSUE THREAD

**Issue by JackTheMico** [looly/hutool#1339]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在线文档中有错误

https://www.hutool.cn/docs/#/core/JavaBean/Bean工具-BeanUtil
![image](https://user-images.githubusercontent.com/19216598/103193755-622b9c00-4918-11eb-899a-0eac0f63f2e9.png)

如上图所示，是否应该为“不用知道”

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
最新修复文档,感谢
