### ISSUE TITLE
HtmlUtils新需求

### ISSUE THREAD

**Issue by WayneLee5991** [looly/hutool#1340]
### 版本情况

JDK版本：   jdk_8_251
hutool版本： 5.5.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
HtmlUtil，我想根据div的id或者class删除指定的标签及该标签下的所有内容，但是最新版的HtmlUtil只能根据tag删除，这样就会把所有的div都删除了

**Comment by looly** [comment]
HtmlUtil使用简单的正则来查找标签,更复杂的HTML标签操作考虑使用Jsoup.
