### ISSUE TITLE
HttpUtil.createServer创建简易web应用问题

### ISSUE THREAD

**Issue by huicrh** [looly/hutool#1341]
JDK版本：    jdk_1.8_202
hutool版本：5.5.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
HttpUtil.createServer(8888).setRoot("target/classes").start();

然后访问localhost:8888//test/index.html，正常加载Html文件，但是涉及到的js和css全都为ocstream的返回格式，前端样式全部失效。请问下有没有好的解决方案。

**Comment by looly** [comment]
应该是自动获取MimeType错误导致的.

5.5.6修复此问题,感谢.
