### ISSUE TITLE
SheetRidReader获取实际的rId好像有点问题

### ISSUE THREAD

**Issue by lengyueyidao** [looly/hutool#1342]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
SheetRidReader类
```java
final String ridStr = attributes.getValue(SHEET_ID_ATTR); // 这里应该取得是RID_ATTR吧？
```
另外直接取SheetId可能不准，在以下场景下可能对应不上：对excel添加一个sheet，然后删除第一个sheet，这个时候第一个sheet得sheetId为2，但是想要得结果应为1吧？

**Comment by looly** [comment]
确实,5.5.6修复此问题,感谢.

但是sheetId这个只能这么映射,没法按照index映射.

**Comment by lengyueyidao** [comment]
但这种场景是存在的，这个时候无法通过getRidBySheetIdBase0来准确定位到想要的sheet了。
通过在SheetRidReader中定义一个sheetIndex，然后在映射那边以这个sheetIndex为键，rid为值，映射之后进行累加。这种方式是否可行？

**Comment by lengyueyidao** [comment]
> 确实,5.5.6修复此问题,感谢.
> 
> 但是sheetId这个只能这么映射,没法按照index映射.

但这种场景是存在的，这个时候无法通过getRidBySheetIdBase0来准确定位到想要的sheet了。
通过在SheetRidReader中定义一个sheetIndex，然后在映射那边以这个sheetIndex为键，rid为值，映射之后进行累加。这种方式是否可行？

**Comment by looly** [comment]
5.5.7在`SheetRidReader`中增加`getRidByIndex`方法。
