### ISSUE TITLE
FR: 在 Android 下跳过加载 PathConverter 和 CharsetConverter

### ISSUE THREAD

**Issue by nekohasekai** [looly/hutool#1344]
https://github.com/looly/hutool/blob/ecfa245ad9b9bc1b573a6a3b33b31f0e9b27bf6e/hutool-core/src/main/java/cn/hutool/core/convert/ConverterRegistry.java#L439

android 8 以下没有 java nio (脱糖库也没有包括), 这导致 hutool-http 无法使用。

**Comment by looly** [comment]
这个……，hutool里用NIO的地方很多哎。
