### ISSUE TITLE
SheetDataSaxHandler类的sharedStringsTable属性始终为null

### ISSUE THREAD

**Issue by lengyueyidao** [looly/hutool#1345]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

SheetDataSaxHandler类的sharedStringsTable属性始终为null，需要在构造函数中将XSSFReader的getSharedStringsTable获取的SharedStringsTable对象传过去。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/103342983-dbb4bd00-4ac5-11eb-8a1e-c48f5baa1ac2.png)

在read的时候会初始化。
