### ISSUE TITLE
treeutils有点麻烦

### ISSUE THREAD

**Issue by czbabl** [looly/hutool#1346]
参数通过map来扩展，还要通过转换器来实现 ,set,get太多，而且比较麻烦。
比如菜单要树形，我写个menutreenode继承treenode从而实现扩展参数，
角色要树形，我定个roletreenode继承treenode从而实现角色的扩展参数。

**Comment by looly** [comment]
TreeUtil是为了兼容各种树形结构后妥协的结果。

你继承也可以，但是涉及太多数据结构，使用上会更加复杂。
