### ISSUE TITLE
身份证号码校验问题

### ISSUE THREAD

**Issue by fangzhengjin** [looly/hutool#1348]
其实身份证最后一位的X不是英文字母，它是罗马数字10，用英文字母应该是大写的X
但是目前校验都是转到小写去校验, 对于银行, 海关等来说, 使用小写X是无效的证件号码
如果一定要支持使用小写X进行校验, 能否加一个参数来进行强制大写匹配

**Comment by looly** [comment]
5.5.7增加一个重载，可选是否忽略大小写。

```java
boolean isValidCard18 = IdcardUtil.isValidCard18("xxxxxxxxx", false);
```
