### ISSUE TITLE
解压zip文件报错：java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by leisure1211** [looly/hutool#1349]
### 版本情况

JDK版本：    1.8.0_171
hutool版本： 5.5.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用ZipUtil的unzip方法 解压zip文件格式报错：java.util.zip.ZipException: error in opening zip file; 多次尝试后发现解压包里的文件名称太长导致，修改为短名称不会报错。

1. 复现代码

```java
ZipUtil.unzip(zipFile);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
[c_1344112734760931330_20201230104703032.zip](https://github.com/looly/hutool/files/5756168/c_1344112734760931330_20201230104703032.zip)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
没有找到原因，貌似是旧版jdk打包zip，新版本jdk不太兼容，和名字长度无关。你可以这样：

```java
final File unzip = ZipUtil.unzip(
		FileUtil.getInputStream(FileUtil.file("d:/test/c_1344112734760931330_20201230104703032.zip")),
		FileUtil.file("d:/test/aaa/"),
		CharsetUtil.CHARSET_UTF_8
);
```

使用流的方式可以解决这个问题。

**Comment by chenwu14** [comment]
我发现流也无法解决

**Comment by chenwu14** [comment]
虽然Hutool基于JDK提供了ZipUtil用于压缩或解压ZIP相关文件，但是对于7zip、tar等格式的压缩依旧无法处理，于是基于commons-compress做了进一步封装：CompressUtil。或者可以在ziputil说明一下，给个链接。另外直接改拓展名称的都不会成功解压，也可以在文档中备注警告

**Comment by looly** [comment]
@chenwu14 文档确实应该做一些说明
