### ISSUE TITLE
Hutool-Json 日期转换

### ISSUE THREAD

**Issue by nieyuan1980** [looly/hutool#1350]
### 版本情况

JDK版本：   jdk_8_201
hutool版本： 5.2.2

### 问题描述
1.前端json传来的一个日期是1605146009， 
2.数据库数据定义的是Date,1970/1/19 22:15:47
请问，这种情况下，实体类需要怎样处理？

    @Alias("createtime") 
    private Date createTime;

**Comment by nieyuan1980** [comment]
前端返回的Unix时间戳：1606547388

**Comment by looly** [comment]
这个需要手动处理。先用long接收，*1000后parse即可。

**Comment by nieyuan1980** [comment]
感谢您的回复，已经解决
