### ISSUE TITLE
ExcelWriter设置行高样式不生效

### ISSUE THREAD

**Issue by zynote** [looly/hutool#1357]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        writer.setColumnWidth(-1,20);
        writer.setRowHeight(-1,35);
```
宽度生效了，但是高度在有内容的区域没有生效，空白区域生效了....应该是写入的时候带了默认的样式，但是我找不到方法设置默认高度，尝试过  writer.setDefaultRowHeight()  是一样的结果。

**Comment by looly** [comment]
getStyle试下。

**Comment by zynote** [comment]
getStyle效果一样writer.setRowHeight(-1,35)不行，但是如果不是-1，而是独自设置 1，2，3得时候生效，我目前得做法是for循环setRowHeight
