### ISSUE TITLE
createServer创建简单SimpleServer的问题

### ISSUE THREAD

**Issue by huicrh** [looly/hutool#1358]
### 版本情况

JDK版本：    oracle_8
hutool版本： 5.5.6

### 问题描述（包括截图）

1.HttpUtil.createServer .addAction("/api/v1/clients", (req, res)->{
                    res.write("0");
                })
    想要返回一个字符串0，但是在实际返回response-header会出现Transfer-encoding →chunked。
                  实际应该想要的是content-length:1 。response-header好像有点问题。

    目前解决方法:改为.addHandler("/api/v1/clients",new ClientsHandler()) 后返回0，才是正常的返回头

2.是否考虑加入拦截器功能用于权限校验，比如对于RootAction或者所有需要的Handler，请求拦截用于处理url后的加密参数校验

**Comment by looly** [comment]
可否看下你的`ClientsHandler`是怎么写的？我对比下如何修正。貌似手动加头不行。

**Comment by huicrh** [comment]
> 可否看下你的`ClientsHandler`是怎么写的？我对比下如何修正。貌似手动加头不行。

        Headers responseHeaders = httpExchange.getResponseHeaders();
        responseHeaders.set("Content-Type", "application/json;charset=utf-8");
        String response = "0";
        OutputStream writer = null;
        try {
            httpExchange.sendResponseHeaders(HttpURLConnection.HTTP_OK, response.length());
            writer = httpExchange.getResponseBody();
            writer.write(response.getBytes());
            writer.flush();
        } catch (IOException e) {
            e.printStackTrace();
            HandlerUtil.ok(httpExchange);
            System.out.println("捕获异常IOException");
        } finally {
            try {
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

**Comment by looly** [comment]
明白问题所在了。

```java
httpExchange.sendResponseHeaders(HttpURLConnection.HTTP_OK, response.length());
```

这里hutool默认指定了0导致的。

**Comment by looly** [comment]
5.5.7修复此问题。

同时在此版本中加入addFilter方法。
