### ISSUE TITLE
身份证验证工具--香港身份证

### ISSUE THREAD

**Issue by allen-berry** [looly/hutool#136]
P835604(5)  一个香港的身份证 通过IdcardUtil.isValidCard()验证合法，然后获取性别，数组越界。是否在获取性别的时候，分别考虑下是哪个地方的身份证，而不是直接就取了第17位？，而且这个身份证再网上验证了几个工具，都是验证格式不正确。

**Comment by looly** [comment]
单独根据身份证号码无法得出香港身份证号码中的性别。所以下个版本我加了个异常。
