### ISSUE TITLE
类SymmetricAlgorithm中AES("AES")注释写错了吧？ 应该是/** 默认的AES加密方式：AES/ECB/PKCS5Padding */

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1360]
![image](https://user-images.githubusercontent.com/16012082/103724965-88d08d80-5010-11eb-8a0b-a14d0ea2cac5.png)
现在的注释是：/** 默认的AES加密方式：AES/CBC/PKCS5Padding */
期望的注释是：AES/ECB/PKCS5Padding

**Comment by looly** [comment]
5.5.7修改，感谢。
