### ISSUE TITLE
Maven 如何排除指定的 json module?

### ISSUE THREAD

**Issue by scruel** [looly/hutool#1361]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
由于 hutool-all 是多模块项目，对于子模块的引入并不是 maven 依赖形式。需求是目前用了大部分工具类，而因为项目了统一 json 处理模块，故想在导入级别上直接把 json 这个模块排除掉（当然可以把其他的 17 个模块一一导入，但这样显然不优雅），请问这种需求有办法达成吗？下面提供的配置无法达成目的。

1. 复现代码

```java
  <dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>${hutool.version}</version>
    <exclusions>
      <exclusion>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-json</artifactId>
      </exclusion>
    </exclusions>
  </dependency>
```

**Comment by looly** [comment]
使用hutool-bom，然后exclude即可。

**Comment by scruel** [comment]
Could not find artifact cn.hutool:hutool-bom:jar:5.5.6 in central (https://repo.maven.apache.org/maven2)
