### ISSUE TITLE
Convert.convert转换相同class对象，存在对象引用

### ISSUE THREAD

**Issue by kamitryant** [looly/hutool#1365]
### 版本情况

JDK版本：    openjdk_8_271
hutool版本： 5.5.7

### 问题描述（包括截图）
Convert.convert转换相同class对象，存在对象引用，对象进行修改同时会对所有引用对象进行修改

**Comment by looly** [comment]
Convert.convert本质上是类型转换，相同的类型肯定是不需要转换的（或者直接强制转换），他并不是复制。

所以这个所谓引用其实就是同一个对象。
