### ISSUE TITLE
RSA算法的AsymmetricAlgorithm枚举需要新增支持"RSA/ECB/NoPadding"

### ISSUE THREAD

**Issue by vivahu** [looly/hutool#1368]
### 版本情况
JDK版本：Oracle JDK 1.8.0_271
hutool版本：5.5.7

### 问题描述（包括截图）
目前 cn.hutool.crypto.asymmetric.AsymmetricAlgorithm 中提供的三种转换模式（Cipher Mode）中：
![image](https://user-images.githubusercontent.com/1997175/104158705-ddb53f00-5428-11eb-8b11-5a319b0952dc.png)

1. Oracle JDK不支持Modes为"None"
来源参考：[https://stackoverflow.com/questions/22102382/cant-find-rsa-none-nopadding-provider-in-jdk-1-8](https://stackoverflow.com/questions/22102382/cant-find-rsa-none-nopadding-provider-in-jdk-1-8)
```
/** RSA算法，此算法用了RSA/None/NoPadding */
RSA_None("RSA/None/NoPadding"); // Oracle JDK不支持
```

2. 需要新增目前缺少的常用转换模式（Cipher Mode）"RSA/ECB/NoPadding"
* Oracle JDK 8支持的转换模式（Cipher Mode）详见：[https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#cipherTable](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#cipherTable)
* Oracle JDK 7支持的转换模式（Cipher Mode）详见：[https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html#cipherTable](https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html#cipherTable)

**Comment by looly** [comment]
5.5.8增加，感谢~~

**Comment by vivahu** [comment]
> 5.5.8增加，感谢~~

棒～坐等使用新版～

**Comment by vivahu** [comment]
> 5.5.8增加，感谢~~

PS. 建议允许用户自行输入转换模式（Cipher Mode）字符串，hutool提供的枚举只作为常用的参考而已。这样扩展性更好一些。

**Comment by looly** [comment]
有的啊，RSA构造方法可以传入字符串。

**Comment by vivahu** [comment]
> 有的啊，RSA构造方法可以传入字符串。

我测了一下5.5.7版，使用 RSA(String rsaAlgorithm, PrivateKey privateKey, PublicKey publicKey) 构造方法，同一对公私钥，使用私钥加密同一段数据，与使用纯Java代码加密出来的结果不一样，而且纯Java加密出来的结果才是对的。

所以只给 AsymmetricAlgorithm 加个枚举值可能是不够的。

![image](https://user-images.githubusercontent.com/1997175/104906531-ca711900-59be-11eb-94ce-ea5d991c5665.png)

**Comment by looly** [comment]
看能否正常加密解密，如果可以就不影响。

hutool默认使用分段加密解密，可以设置block，不知道是不这里的问题。

**Comment by vivahu** [comment]
> 看能否正常加密解密，如果可以就不影响。
> 
> hutool默认使用分段加密解密，可以设置block，不知道是不这里的问题。

有可能，如有必要我可以通过telegram提供数据，配合测试。目前我先用纯Java的实现了。

**Comment by looly** [comment]
可以提供下测试的密钥，还有java实现的代码我这边可以测试。
