### ISSUE TITLE
【功能】封装统一的自定义返回信息(class R)

### ISSUE THREAD

**Issue by s2005lg** [looly/hutool#1370]
现在大多数项目中，在controller层，最终都会return 一个自定义的 R 作为统一返回信息，给到前端。如下图：
![image](https://user-images.githubusercontent.com/6127395/104418589-1b919f00-55b2-11eb-9d18-aefdea155d5e.png)
![image](https://user-images.githubusercontent.com/6127395/104418617-24827080-55b2-11eb-8b66-3f96c0fb1d0d.png)

是否可以封装一个统一的 class R，包含常见的错误信息，错误码等。避免每个项目都重复定义 class R

**Comment by celizi** [comment]
对的 ，再加个流程引擎和表单引擎，这样大部分项目都不需要重复引入了

**Comment by looly** [comment]
哈哈，这个不考虑封装。这个是业务相关的，每个系统工程对R的定义都不一样，字段名字也不一样。工具类不应该封装或强制用户使用特定格式。
