### ISSUE TITLE
Ftp工具类中exist方法存在问题

### ISSUE THREAD

**Issue by CodeLunatic** [looly/hutool#1371]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在`exist`方法中使用了`ls`方法，`ls`方法在目录不存在的情况下返回根目录中所有的文件。

如果根目录中存在`test`目录，那么假设文件夹`/123123`不存在，判断`/123123/test`文件夹的时候返回`true`，原因是`ls`返回的信息中存在`test`，而`test`在根目录中。

1. 复现代码

```java
public boolean exist(String path) {
    final String fileName = FileUtil.getName(path);
    final String dir = StrUtil.removeSuffix(path, fileName);
    final List<String> names = ls(dir);
    return containsIgnoreCase(names, fileName);
}
```

2. 堆栈信息

     无

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.5.8修复此问题：

问题在于cd方法没有检查是否进入这个目录成功与否，导致如果进入失败，会停留于初始目录。
