### ISSUE TITLE
QrCodeUtil.decode 二维码无法识别

### ISSUE THREAD

**Issue by WingGao** [looly/hutool#1372]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
QrCodeUtil.decode(qrFile)
```

2. 堆栈信息
```
NotFoundException: null
cn.hutool.extra.qrcode.QrCodeException: NotFoundException: null
	at cn.hutool.extra.qrcode.QrCodeUtil.decode(QrCodeUtil.java:324)
```
3. 测试涉及到的文件（注意脱密）

类似解决方案
https://www.cnblogs.com/huangzizhu/p/9360097.html

**Comment by looly** [comment]
设置下QrCode.setQrVersion试下。
