### ISSUE TITLE
URLUtil.encode方法部分字符串下无法encode

### ISSUE THREAD

**Issue by Mrzlr** [looly/hutool#1373]
### 版本情况

JDK版本：    8.0.242-zulu
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
System.out.println(URLUtil.encode("sendid=afbfd064&ver=8&sign=f6d9db11&mid=b2n3j1wbv5t54k5&pid=mn4dd7ds1c4adf1xas"));
```

2. 堆栈信息

3. [测试涉及到的文件（注意脱密）]
比](url)`如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
使用URLUtil.encodeAll
