### ISSUE TITLE
图片验证码流输出到页面验证码不变化

### ISSUE THREAD

**Issue by EmonLieu** [looly/hutool#1374]
### 版本情况

JDK版本：    oracle JDK1.7
java version "1.7.0"
Java(TM) SE Runtime Environment (build 1.7.0-b147)
Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)

hutool版本： 4.6.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
```
public String getCaptcha() throws IOException {
HttpServletResponse response=this.getResponse();
 LineCaptcha captcha = CaptchaUtil.createLineCaptcha(100, 50, 6, 220);
 captcha.write(response.getOutputStream());
//或者
 LineCaptcha captcha = CaptchaUtil.createLineCaptcha(100, 50, 6, 220);
 captcha.createCode();
 captcha.write(response.getOutputStream());
return null;
}
```
多次刷新时Struts2的ACTION每次输出到页面上的验证码都相同，很小几率会出现新的验证码 再刷新又会回到原来的验证码

spring+struts2 工程。

查看后发现是RandomUtil中使用的ThreadLocalRandom.current() 存在出现重复输出随机数的情况，改用Random后未出现重复，但是没有找到原因。怀疑是ThreadLocalRandom.current()不适用于多线程的情况。

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CodeLunatic** [comment]
访问验证码地址的时候是否添加了时间戳参数防止多次请求的地址相同？

**Comment by EmonLieu** [comment]
> 访问验证码地址的时候是否添加了时间戳参数防止多次请求的地址相同？

请求地址是相同的。 但是有个现象就是本地调试正常 服务器环境下会出现这个问题。

**Comment by EmonLieu** [comment]
> 访问验证码地址的时候是否添加了时间戳参数防止多次请求的地址相同？

是因为struts2 是多线程的原因么。

**Comment by CodeLunatic** [comment]
可以在地址后面加入时间戳，防止验证码请求的地址每次都相同，导致浏览器缓存问题引起的验证码图片不刷新，例如：
```javascript
`http://localhost:8080/getCaptcha?t=${Date.now()}`
```

**Comment by looly** [comment]
你可以在action中增加调试信息，看每次刷新是否执行了这个action。

很多时候是浏览器缓存。
