### ISSUE TITLE
加密报错

### ISSUE THREAD

**Issue by weilongshi** [looly/hutool#1378]
### 版本情况

JDK版本：    jdk_8_191
hutool版本： 5.4.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
  @Test
    public void encryptTest() {
        // 构建

        AES aes = new AES(Mode.CBC, Padding.PKCS5Padding,
                "1234567890123456".getBytes(), "1234567890123456".getBytes());
        String encryptHex = aes.encryptHex("123456");
       Assert.assertEquals("d637735ae9e21ba50cb686b74fab8d2c", encryptHex);
    }

```

2. 堆栈信息
java.lang.NoSuchMethodError: cn.hutool.core.lang.Assert.notBlank(Ljava/lang/CharSequence;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/CharSequence;

	at cn.hutool.crypto.KeyUtil.generateKey(KeyUtil.java:139)
	at cn.hutool.crypto.SecureUtil.generateKey(SecureUtil.java:96)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:155)
	at cn.hutool.crypto.symmetric.AES.<init>(AES.java:83)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
检查你的依赖，是不引入多个版本hutool导致的。看样子是包冲突了。
