### ISSUE TITLE
ExcelUtil.readBySax(inputStream, index, handler) 不支持InputStream？

### ISSUE THREAD

**Issue by liujun7570** [looly/hutool#138]
// 输入文件名  ok
ExcelUtil.readBySax("C:/Users/28149/Desktop/test.xlsx", 0, createRowHandler()); // ok

// 输入InputStream  error
ExcelUtil.readBySax(new FileInputStream("C:/Users/28149/Desktop/test.xlsx"), 0, createRowHandler()); // throw a POIException: NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file

// 输入BufferedInputStream  ok
查看源码后发现需要用BufferedInputStream包装一层才能正常使用
ExcelUtil.readBySax(new BufferedInputStream(new FileInputStream("C:/Users/28149/Desktop/test.xlsx")), 0, createRowHandler()); // ok

**Comment by looly** [comment]
请升级Hutool到新版（最新4.1.2），新版做了自动包装。
