### ISSUE TITLE
使用 HttpRequest 如何指定 form 类型

### ISSUE THREAD

**Issue by FormatToday** [looly/hutool#1390]
### 版本情况

JDK版本：    openjdk_8_275
hutool版本： 5.5.7

### 问题描述

使用 HttpRequest 如何指定form类型。具体说明如下：

在调用**azkaban**的时候，有个上传文件的接口，详见[这里](https://azkaban.readthedocs.io/en/latest/ajaxApi.html#upload-a-project-zip)，需要指定文件的类型为`application/zip` 或者 `application/x-zip-compressed`，但是请求的类型为`multipart/mixed`,请问这个怎么发送请求。

1. 复现代码

```java
HttpRequest
.post("http://ip:port/manager?ajax=upload")
.form("session.id", sessionId)
.form("project", projectName)
.form("file", zipFile) // 这里需要指定 application/x-zip-compressed
.contentType("multipart/mixed")
.execute().body();
```

2. 堆栈信息
无

3. 测试涉及到的文件
无，问题跟zip文件内容无关

**Comment by looly** [comment]
自定义文件名试下。
