### ISSUE TITLE
2020年后的2月闰月判断错误

### ISSUE THREAD

**Issue by jinjingmail** [looly/hutool#1395]
### 版本情况

JDK版本：    oracle jdk_8_217
hutool版本： 5.5.7（当前的最新版）

### 问题描述（包括截图）
2020年后的2月闰月判断错误，如下代码应该返回true，但是返回了false
Validator.isBirthday("2024-02-29")
Validator.isBirthday("2028-02-29")

1. 复现代码

```java
    public static void main(String[] args) {
        System.out.println(Validator.isBirthday("2020-02-29"));
        System.out.println(Validator.isBirthday("2024-02-29"));
        System.out.println(Validator.isBirthday("2028-02-29"));
    }
```

2. 堆栈信息
无

3. 测试涉及到的文件（注意脱密）
Validator.java
DateUtils.java
GregorianCalendar.java

**Comment by chaixuqing** [comment]
```
// 验证年
int thisYear = DateUtil.thisYear();
if (year < 1900 || year > thisYear) {
	return false;
}
```

**Comment by chaixuqing** [comment]
> ### 版本情况
> JDK版本： oracle jdk_8_217
> hutool版本： 5.5.7（当前的最新版）
> 
> ### 问题描述（包括截图）
> 2020年后的2月闰月判断错误，如下代码应该返回true，但是返回了false
> Validator.isBirthday("2024-02-29")
> Validator.isBirthday("2028-02-29")
> 
> 1. 复现代码
> 
> ```java
>     public static void main(String[] args) {
>         System.out.println(Validator.isBirthday("2020-02-29"));
>         System.out.println(Validator.isBirthday("2024-02-29"));
>         System.out.println(Validator.isBirthday("2028-02-29"));
>     }
> ```
> 
> 1. 堆栈信息
>    无
> 2. 测试涉及到的文件（注意脱密）
>    Validator.java
>    DateUtils.java
>    GregorianCalendar.java

因为测试的两个用例不是过去的年份，源代码如下：
```// 验证年
int thisYear = DateUtil.thisYear();
if (year < 1900 || year > thisYear) {
	return false;
} 
```

**Comment by looly** [comment]
未来出生的日期肯定是false。

Hutool约定未来出生的不可预知，因此判定出生日期是错误的。（我想科幻小说不会用这个工具吧……）

**Comment by jinjingmail** [comment]
强！细节考虑周到。
