### ISSUE TITLE
Ftp工具类ls和exist存在一些问题

### ISSUE THREAD

**Issue by CodeLunatic** [looly/hutool#1397]
### 版本情况

JDK版本：    
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. `Ftp` `ls`方法的异常信息不友好，仅使用了模板字符串，但并未使用方法进行赋值。

```java
if (StrUtil.isNotBlank(path)) {
	pwd = pwd();
	if(false == cd(path)){
		throw new FtpException("Change dir to [{}] error, maybe path not exist!");
	}
}
```

2.` Ftp`的`exist`方法返回值不友好，由于`ls`方法抛出一个异常，所以导致`exist`方法也会抛出一个异常，此处应该返回`false`，否则会造成程序出现无法启动。

```java
public boolean exist(String path) {
	final String fileName = FileUtil.getName(path);
	final String dir = StrUtil.removeSuffix(path, fileName);
	final List<String> names = ls(dir);
	return containsIgnoreCase(names, fileName);
}
```

**Comment by CodeLunatic** [comment]
Ftp中的部分方法在多线程多目录下不能正常的工作，猜测可能是因为多线程cd造成的，比如说upload，如果无法解决该问题推荐加上synchronized。

**Comment by looly** [comment]
>但并未使用方法进行赋值

这句啥意思？

**Comment by CodeLunatic** [comment]
> > 但并未使用方法进行赋值
> 
> 这句啥意思？

就是模板字符串没有给模板赋值

**Comment by looly** [comment]
模板异常、exist异常已解决，syn已加。

5.5.9修复。
