### ISSUE TITLE
查询星座的APi有问题

### ISSUE THREAD

**Issue by Live-or** [looly/hutool#1398]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Live-or** [comment]
结果不符合预期

**Comment by CherryRum** [comment]
老哥 代码呢

**Comment by Live-or** [comment]
我以为是反馈问题你们解决呢

**Comment by looly** [comment]
麻烦提供一个不符合预期的日期。

**Comment by Live-or** [comment]
10-28 这应该是天蝎座的，但是给出的结果确实射手座
