### ISSUE TITLE
ExcelReader 读取Sheet BUG？

### ISSUE THREAD

**Issue by aaronuu** [looly/hutool#140]
ExcelReader reader = ExcelUtil.getReader("file.xlsx", 0);

ExcelReader reader = ExcelUtil.getReader("file.xlsx");

这两行代码 第一行是指定 Sheet num读取，第二行我以为会默认合并所有sheet   能否增加一个可以合并所有sheet的方法？

**Comment by looly** [comment]
合并所有sheet读取是不现实的。因为：

1、合并后的数据行会出现混乱，因为每个sheet都可能有标题行
2、合并读取会增加复杂度

因此建议调用`reader.setSheet`切换sheet后读取。
