### ISSUE TITLE
是否考虑加入类似于FileUtil. prettyFileName(String)这样的方法

### ISSUE THREAD

**Issue by CodeLunatic** [looly/hutool#1401]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

描述：很多时候文件名为用户输入，或者爬虫的时候从网站上读取，但是读取到的内容中包含文件名中的特殊字符，所以需要工具来去掉这些不属于文件名的特殊字符，就像Windows创建文件的时候自动就进行了文件名处理一样。

**Comment by looly** [comment]
这里存在个问题：

某些特殊字符在Linux下是有效的，这个就无法很好的判断。

当然，hutool提供了对应方法：

```
FileUtil.cleanInvalid
```
