### ISSUE TITLE
【新特性】是否考虑新增类似 MapUtil.toCamelCaseMap(map) 这种下划线转驼峰格 为自定义格式转驼峰格接口

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#1402]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8

### 问题描述（包括截图）
最近在解析yml 格式文件中发现，springboot 体系中都是中划线 -  ， 如mybatis-plus 转换成 mybatisPlus 这种类型

然后用map注入bean中是没办法注入的，

> 工具提供的仅提供了下划线 _ 转驼峰格 

源码中CamelCaseMap 拓展了一个

```

	/**
	 * 将Key转为驼峰风格，如果key为字符串的话
	 * 
	 * @param key KEY
	 * @return 驼峰Key
	 */
	@Override
	protected Object customKey(Object key) {
		if (key instanceof CharSequence) {
			key = StrUtil.toCamelCase(key.toString());
		}
		return key;
	}

```

是否可以开放自定义键的接口注入方法，同时添加中划线 转 驼峰格 的StrUtil 方法 ， 或者 我来提供也行

**Comment by looly** [comment]
你可以直接继承使用`CustomKeyMap`，重写customKey方法即可。

**Comment by freshgeek** [comment]
两个确实都可以

但是用接口注入就不用重新继承，创建一个新的对象，再重写一堆的构造器，而只关注业务逻辑 customKey ，感觉这种应该也是工具类的更优选吧

**Comment by freshgeek** [comment]
好像存在一个小问题，转换驼峰格中，如果value 也是 map ， 这时是 不会将value map 中的key 递归转换驼峰格 @looly

**Comment by looly** [comment]
5.6.0增加FuncKeyMap。

递归问题不涉及，因为你put的时候如果不是CamelCaseMap，那没法转换。
