### ISSUE TITLE
ExcelWriter添加自定义头是否有问题

### ISSUE THREAD

**Issue by zhangyan1030** [looly/hutool#1403]
### 版本情况

JDK版本：    jdk_8_181
hutool版本： 5.5.8

### 问题描述（包括截图）

1. 复现代码

javaBean
![image](https://user-images.githubusercontent.com/54790977/106690410-b6f3be00-660c-11eb-96ba-3a6a8c214899.png)

![image](https://user-images.githubusercontent.com/54790977/106690459-cffc6f00-660c-11eb-95b3-f2dec7893627.png)

ExcelWriter.java 427行
rowMap = BeanUtil.beanToMap(rowBean, new TreeMap(this.getCachedAliasComparator()), false, false);
本意使用TreeMap中比较器功能，但是当javaBean的字段多余头字段，会出现treeMap需要初始化root节点(把多余字段初始化为root节点)

最后导致定义一列头信息，生成excel为两列信息
![image](https://user-images.githubusercontent.com/54790977/106690827-6e88d000-660d-11eb-86cc-dad7bc630885.png)

是否考虑初始把头信息加入map,赋值是查看是否有初始key,或者直接通过初始key，反射bean属性找到对应值

**Comment by looly** [comment]
试下setOnlyAlias

**Comment by zhangyan1030** [comment]
> 试下setOnlyAlias

用了setOnlyAlias这个方法也不行，本质上是treeMap的比较器方法导致的
![image](https://user-images.githubusercontent.com/54790977/106691734-fb805900-660e-11eb-95a0-e35cd01c16e2.png)
初次进入的shihou时候 treeMap的根节点为null 会忽视比较器~

**Comment by zhangyan1030** [comment]
1
