### ISSUE TITLE
FileUtil.file(URL url)方法出现URI scheme is not "file"

### ISSUE THREAD

**Issue by Secret-zero** [looly/hutool#1405]
### 版本情况

JDK版本：    jdk_8_0.221;
hutool版本： 5.5.8

### 问题描述（包括截图）

1. 复现代码

```java
URI uri = new URI("http://xxxx/xx.jpg");
File file = FileUtil.file(uri);
```
出现URI scheme is not "file";

**Comment by looly** [comment]
对啊，一个Http地址，你直接用File去初始化肯定报错。你想实现下载？可以用HttpUtil.downloadFile
