### ISSUE TITLE
JsonUtil有没有什么类似Jackson,fastjson中的注解表名解析json中的哪个属性?

### ISSUE THREAD

**Issue by trdmm** [looly/hutool#1406]
### 版本情况

JDK版本：    jdk_8_251
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

其他业务传输的json,属性名不符合驼峰式命名,类似下面这种:
```json
{
  "Time":1612352755697,
  "TerminalId":"101005100005",
  "Payload":"xxx"
}
```
如果Java实体类的属性名按 驼峰式命名,就是  `time`,`terminalId`,`payload`,但这样JsonUtil.toBean返回的结果各属性都是null.
只能Java类中只能`Time`,`TerminalId`,`Payload`命名...
所以想问下有没有Jackson中类似`@JsonProperty`这样的东西?

**Comment by CherryRum** [comment]
https://github.com/looly/hutool/issues/1329   这个吗

**Comment by CherryRum** [comment]
不知道 我理解是否正确

**Comment by looly** [comment]
试下Alias注解。

**Comment by trdmm** [comment]
> 不知道 我理解是否正确
就是这个,多谢 :P 👍 


> 试下Alias注解。
就是这个,多谢 💯
