### ISSUE TITLE
ListUtil类的方法sub(List<T> list, int start, int end, int step) 在step<=1和>1的情况下，返回的List在使用机制上是不一致的问题

### ISSUE THREAD

**Issue by fuyc224** [looly/hutool#1409]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7

### 问题描述（包括截图）
ListUtil类的方法public static <T> List<T> sub(List<T> list, int start, int end, int step) 
![ListUtil sub](https://user-images.githubusercontent.com/52287914/106867864-10411780-6709-11eb-9d4f-83cee7199a8a.jpg)

1. step<=1的时候，返回的list，是使用JDK自带的subList方法截取，而该方法返回的List由原列表支持，对其进行修改会影响到原list；
2.  step>1的时候，返回的list，是new了一个ArrayList，并从原list取值然后add到新list，对其修改，不会影响到原list了

**Comment by looly** [comment]
确实忽略了这块。

5.5.9修复此问题，将统一改为不影响原List。
