### ISSUE TITLE
ImageUtil.pressText图片有黑边的问题

### ISSUE THREAD

**Issue by cj506817364** [looly/hutool#141]
原图如下图所示
![ec4 vcp 3rfe44jjlm 7b](https://user-images.githubusercontent.com/33059555/43582462-1ae32b9e-968f-11e8-8d41-ba221d2bc3d2.png)

当我调用
ImageIO.write(image, "png", response.getOutputStream());
方法将图片响应懂啊浏览时图片没有黑边

但是当我调用
ImageUtil.pressText(inputStream,response.getOutputStream(),code, Color.RED,new Font("黑体",Font.BOLD,40),-45,180,1.0f);
方法将图片响应出去的时候,图片自带黑边,这时候的图片格式是jpg

我起初觉得是响应时所使用的图片格式有问题,于是找了下其他几种重载的方法,发现没有响应PNG的方式

于是我改用了如下方法
BufferedImage image = ImageUtil.pressText(ImageUtil.read(inputStream), code, Color.RED, new Font("黑体", Font.BOLD, 40), -45, 180, 1.0f);
ImageIO.write(image, "png", response.getOutputStream());

测试后发现响应的图片还是带有黑边的,难受

**Comment by looly** [comment]
4.1.5修复此问题。

**Comment by looly** [comment]
是由于`BufferedImage.TYPE_INT_RGB`导致透明通道失效问题。4.1.5修复此问题。换成了`BufferedImage.TYPE_INT_ARGB`
