### ISSUE TITLE
Hutool 工具 ExcelUtil.getReader读excel文件的问题

### ISSUE THREAD

**Issue by lzb-libra** [looly/hutool#1410]
您好
我当前使用的Hutool版本5.5.8
今天我使用了您的工具中ExcelUtil.getReader方法来读取一个Excel文件，当我执行main方法后出现了一个错误信息(Exception in thread "main" cn.hutool.core.exceptions.DependencyException: You need to add dependency of 'poi-ooxml' to your project, and version >= 4.1.2)， 我按着错误信息引入了 poi-ooxml 的 jar 包，版本是 5.0.0，然后我又重新执行了main方法，发现当前已经不会提示上一个错误了，但是又出现了新的错误信息(Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType)，我发现CellUtil 类的 getCellValue方法中调用了getCellTypeEnum方法，然后我到poi-ooxml查找该方法，发现并没有此方法，然后我将poi-ooxml的版本调整到4.1.2，找到了该方法，再次执行main方法发现可以正常执行了，回看4.1.2的poi-ooxml，发现getCellTypeEnum已经被标识为过时的方法。您看这个问题您是否可以处理一下。

Hello
I am currently using Hutool version 5.5.8
Today I used the ExcelUtil.getReader method of your tool to read an Excel file. When I executed the main method, an error message appeared (Exception in thread "main" cn.hutool.core.exceptions.DependencyException: You need to add dependency of'poi-ooxml' to your project, and version >= 4.1.2), I introduced the poi-ooxml jar package according to the error message, the version is 5.0.0, and then I re-executed the main method, It is found that the previous error is no longer prompted, but a new error message has appeared (Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache /poi/ss/usermodel/CellType), I found that the getCellTypeEnum method was called in the getCellValue method of the CellUtil class, and then I searched for this method in poi-ooxml and found that there is no such method, and then I adjusted the version of poi-ooxml to 4.1 .2. Found the method, execute the main method again and find that it can be executed normally. Looking back at the poi-ooxml of 4.1.2, it is found that getCellTypeEnum has been identified as an obsolete method. You see if you can deal with this problem.

**Comment by looly** [comment]
POI之前是为了向下兼容3.x，所以使用了过期方法。

预计在5.6.X中会修改所有弃用方法。

**Comment by looly** [comment]
推荐使用POI 4.1.2

**Comment by looly** [comment]
重复：https://gitee.com/loolly/hutool/issues/I35J6B

**Comment by lwl888** [comment]
5.6.6好像还没有修复此问题

**Comment by 8debug** [comment]
5.7.20好像还没有修复此问题

**Comment by looly** [comment]
@8debug 修复了啊，检查你项目里的POI版本是否新，或者是否多版本冲突。
