### ISSUE TITLE
setRowHeight()和setColumnWidth()函数无法设置行高和列宽

### ISSUE THREAD

**Issue by Manual-S** [looly/hutool#1414]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.5.8
poi-ooxml版本： 4.1.2

### 问题描述（包括截图）

1. 复现代码

```java
    @Test
    public void test04() {
        System.out.println("test04");
        /**
         * 代写入的数据
         */
        Map<String, Object> row1 = new LinkedHashMap<>();
        row1.put("姓名", "张三");
        row1.put("年龄", 23);
        row1.put("成绩", 88.32);
        row1.put("是否合格", true);
        row1.put("考试日期", DateUtil.date());

        Map<String, Object> row2 = new LinkedHashMap<>();
        row2.put("姓名", "李四");
        row2.put("年龄", 33);
        row2.put("成绩", 59.50);
        row2.put("是否合格", false);
        row2.put("考试日期", DateUtil.date());

        ArrayList<Map<String, Object>> rows = CollUtil.newArrayList(row1, row2);
        System.out.println(rows.size() + " " + rows.get(0).size());
        ExcelWriter writer = ExcelUtil.getWriter("writeTest.xlsx");
        //字体大小
        short fontSize = 12;
        configureWriteAttribute(writer,Font.COLOR_NORMAL,fontSize,"等线",false);
        writer.write(rows, true);
        writer.close();
    }

    public void configureWriteAttribute(ExcelWriter writer,short color, short fontSize, String fontName, boolean ignoreHead){
        System.out.println("public void ConfigureWriteAttribute(ExcelWriter writer)");
        /**
         *  设置字体
         */
        writer.getStyleSet().setFont(color,fontSize,fontName,ignoreHead);
        /**
         * 设置标题样式 这里考虑标题的颜色在函数的入参写好
         */
        StyleSet style = writer.getStyleSet();
        XSSFCellStyle headCellStyle = (XSSFCellStyle) style.getHeadCellStyle();
        byte[] rgb = new byte[]{(byte) 0, (byte) 181, (byte) 65};
        XSSFColor myColor = new XSSFColor(rgb, null);
        headCellStyle.setFillForegroundColor(myColor);
        
        //设置行高
        writer.setRowHeight(-1,50);
        //设置列宽
        writer.setColumnWidth(-1,50);
    }
```
设置后的结果
<img width="1062" alt="企业微信20210205-112712@2x" src="https://user-images.githubusercontent.com/38674587/106986076-8e52fc00-67a5-11eb-80ba-7a18c8f568d9.png">

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Manual-S** [comment]
表格是在wps中打开的

**Comment by looly** [comment]
应该是被单元格样式覆盖导致的。

**Comment by TianzhiZhou** [comment]
` Java   
        
            writer.setOnlyAlias(true);
            //writer.setDefaultRowHeight(25);
            // 合并单元格后的标题行，使用默认标题样式
            writer.merge(len-1, headTitle);
            writer.setRowHeight(0,40);
            writer.setRowHeight(1,30);
            //一次性写出内容，强制输出标题
            writer.write(dataList, true);
            for(int i=0;i<dataList.size();i++){
                writer.setRowHeight(i+2,25);
            }
            writer.getHeadCellStyle().setFillForegroundColor(IndexedColors.BRIGHT_GREEN1.getIndex());
            Font font = writer.createFont();
            font.setBold(true);
            font.setFontHeight((short)440);
            writer.getHeadCellStyle().setFont(font);`


我的代码，因为有一个总标题和每一列的属性名（不知道为什么hutool的headcell把两个都包括了）所以setrowheight了这两列的高度，然后再写出内容，然后再对每一行遍历设置高度（setDefaultRowHeight不知道为什么会把头两列也覆盖，找不到解决的办法）。下面再获取headcell设置背景颜色和字体（本来想设一个浅绿一个浅绿1的，不知道怎么设置），字体440等于excel中的22磅（除20）

**Comment by looly** [comment]
@TianzhiZhou 那就禁用hutool默认样式，然后自己写样式即可。
