### ISSUE TITLE
是否可以添加PBKDF2工具类

### ISSUE THREAD

**Issue by shoppWeb** [looly/hutool#1416]

**Comment by shoppWeb** [comment]
当前好多大厂密码都是用PBKDF2进行加密

**Comment by CherryRum** [comment]
https://tools.ietf.org/html/rfc6070  先做个标记 我看看我能看懂不能

**Comment by CherryRum** [comment]
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf

**Comment by CherryRum** [comment]
大概写了下 还是不如 bc库写的全  不如包装下bc库

**Comment by shoppWeb** [comment]
现在密码加密多采用pbkdf2迭代1000～1000w次的 方式，用了你的工具类库之后发现没有，所以给你提提意见看看能不能加进来。



---原始邮件---
发件人: "lin"<notifications@github.com&gt;
发送时间: 2021年2月12日(周五) 晚上9:50
收件人: "looly/hutool"<hutool@noreply.github.com&gt;;
抄送: "pikachu"<956875143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [looly/hutool] 是否可以添加PBKDF2工具类 (#1416)




 
大概写了下 还是不如 bc库写的全  不如包装下bc库

**Comment by CherryRum** [comment]
抱歉 这不是我的库 而且 说实话 很多地方不建议使用pbkdf2,有空的话我会提交个初稿

**Comment by looly** [comment]
5.6.0增加方法：

```java
SecureUtil.pbkdf2("123456".toCharArray(), RandomUtil.randomBytes(16));
```

**Comment by shoppWeb** [comment]
看了你的示例方法后，有些想法想说一下，不对之处还望指正。
我现在接触的项目对安全要求的都比较高，示例代码中使用的盐值 建议使用 SecureRandom生成

**Comment by CherryRum** [comment]
那样可能有性能问题吧&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pikachu"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 晚上8:08
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "1809040656"<1809040656@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [looly/hutool] 是否可以添加PBKDF2工具类 (#1416)





 
看了你的示例方法后，有些想法想说一下，不对之处还望指正。
 我现在接触的项目对安全要求的都比较高，示例代码中使用的盐值 建议使用 SecureRandom生成

**Comment by CherryRum** [comment]
对于您这个问题，假如安全要求高，建议使用Bcrypt（原因后面说），假如您因为系统改动过大，还使用PBKDF2，可以考虑加pepper，在不同的年代，迭代次数应该增加，以摩尔定律来说，18个月应该翻倍，而对于PBKDF2（这玩意.net用的多）建议使用HMAC-SHA-256，迭代次数至少推荐10000.
注意：
使用 bcrypt 慢哈希函数，服务器也可能承受压力吗？
**可以在客户端进行bcrypt 运算，服务端进项验证即可。**
pepper记得设置长一点

最后说一句 一般来说这样就很难破解了 但是注意好公司自己的人员保密

[参考文档](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html)
