### ISSUE TITLE
原本spring boot项目CronUtil.schedule正常使用的，切换成spring could后发现CronUtil.schedule失效了，其他功能正常

### ISSUE THREAD

**Issue by Simba9980** [looly/hutool#1417]
JDK版本：    1.8
hutool版本： 5.5.8

项目切换成spring could后发现定时器无法正常添加运行

项目pom
![image](https://user-images.githubusercontent.com/26837690/107341728-4fe97400-6afa-11eb-8886-3f4caac5a84e.png)

代码截图
![image](https://user-images.githubusercontent.com/26837690/107341826-70193300-6afa-11eb-9411-b72eb11f73d5.png)

**Comment by looly** [comment]
确认几个点：

1、方法调用位置在哪里，检查日志定时线程是否启动后被强行关闭了。
2、最好在系统初始化时候启动。
