### ISSUE TITLE
【新特性】英文文档

### ISSUE THREAD

**Issue by askask11** [looly/hutool#1418]
### 版本情况

JDK版本：    11.0.6
hutool版本： 5.5.2（请确保最新尝试是否还有问题）

能否翻译我们现存的文档增加英文文档？ 如果不能翻译javadoc也行至少网站上面的简介也做一个英文版，这样子更多人能认识 这个简洁好用的工具。

**Comment by CherryRum** [comment]
英语小垃圾 @looly

**Comment by looly** [comment]
我英语真的垃圾。

有英文版本的readme：https://github.com/looly/hutool/blob/v5-master/README-EN.md
