### ISSUE TITLE
Sm4算法和js有差异

### ISSUE THREAD

**Issue by zhfish** [looly/hutool#1427]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8

### 问题描述（包括截图）

主要体现在
```js
// JS的SM4实现
       this.GET_ULONG_BE = function (b, i) {
		return (b[i] & 0xff) << 24 | ((b[i + 1] & 0xff) << 16) | ((b[i + 2] & 0xff) << 8) | (b[i + 3] & 0xff) & 0xffffffff;
	}
```
```java
// JAVA的SM4实现
       // 用LONG，结果和js不同
	private long GET_ULONG_BE(byte[] b, int i)
	{
		long n = (b[i] & 0xff) << 24 | ((b[i + 1] & 0xff) << 16) | ((b[i + 2] & 0xff) << 8) | (b[i + 3] & 0xff) & 0xffffffffL;
		return n;
	}
        // 用INT，结果和js相同
	private long GET_ULONG_BE(byte[] b, int i)
	{
		int n = (b[i] & 0xff) << 24 | ((b[i + 1] & 0xff) << 16) | ((b[i + 2] & 0xff) << 8) | (b[i + 3] & 0xff) & 0xff;
		return n;
	}

```
这个方法里，js的long和java的long，在64位里的表现是不一致的，导致结果不太一样

解决方法:
把SM4从Bouncy Castle里拿出来
并且针对这个方法做个开关
毕竟就加密的一致性里说，c#的long和java的long肯定是一致的
所以应该根据不同的情况，选用long还是int

看有没有什么好建议，我可以提个pr

**Comment by looly** [comment]
SM4封装很浅，基本就是`Bouncy Castle`实现，不知道如何修改。是否是mode或者padding有区别导致的差异？

**Comment by zhfish** [comment]
> SM4封装很浅，基本就是`Bouncy Castle`实现，不知道如何修改。是否是mode或者padding有区别导致的差异？

说的很明白了，是不同语言，对64位总线的long解释不一样引起的，和mode和padding无关

**Comment by looly** [comment]
欢迎提供修改思路，关于long类型差异不是很理解。

**Comment by zhfish** [comment]
修改思路是把SM4从Bouncy Castle里提出来，直接用SM4源代码
用一个参数去决定用long或者int的GET_ULONG_BE方法
long的方式，可以和c#计算保持一致, int的方式，可以和js的计算保持一致

但是提出来之后，如何能优雅的保持api不变，这个没思路。用if else似乎有点蠢
再或者，给Bouncy Castle提一下这个问题。。
