### ISSUE TITLE
Cache类如何获取到缓存的key列表?

### ISSUE THREAD

**Issue by dahuoyzs** [looly/hutool#1429]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

AbstractCache.java
```java
	@Override
	public Iterator<V> iterator() {
		CacheObjIterator<K, V> copiedIterator = (CacheObjIterator<K, V>) this.cacheObjIterator();
		return new CacheValuesIterator<>(copiedIterator);
	}

	@Override
	public Iterator<CacheObj<K, V>> cacheObjIterator() {
		CopiedIter<CacheObj<K, V>> copiedIterator;
		final long stamp = lock.readLock();
		try {
			copiedIterator = CopiedIter.copyOf(this.cacheMap.values().iterator());
		} finally {
			lock.unlockRead(stamp);
		}
		return new CacheObjIterator<>(copiedIterator);
	}
```

这里迭代器只是迭代了values
可不可以迭代`protected Map<K, CacheObj<K, V>> cacheMap;`  这个Map.Entry呢？
或者重载一些方法？

或者有什么好的方法获取到key吗？

TimeCache可以初始化的时候自己放入一个Map
LRUCache目前还不知道如何获取缓存的keys

😥

**Comment by looly** [comment]
暂时没有实现。

5.5.9会在AbstractCache中加入keySet方法。


暂时你可以两种办法获取：

1. 用反射获取map后调用keySet
2. 继承XXXCache，访问map
