### ISSUE TITLE
无法直接从JSONObject构造另一个JSONObject

### ISSUE THREAD

**Issue by ghost** [looly/hutool#143]
JSONObject a = ... 

1.
需求 : 从一个JSONObject直接构造另一个JSONObject
JSONObject b = JSOMObject(a)
// 传入构造器 (JSONObject,String...)
结果 : b = {}
原因 无直接构造的构造器
2.
需求 从提供的构造器 (JSONObject,String...)构造另一个JSONObject
JSONObject b = JSONObject(a,a.keySet().toArray(new String[a.size()])
// 传入构造器 (Object,String[])
结果 : b = {}
原因:构造器(JSONObject,String...)不可达

**Comment by looly** [comment]
4.1.5修复，感谢。
