### ISSUE TITLE
Hutool-db 自定义配置文件方法报错，无该方法

### ISSUE THREAD

**Issue by FJiayang** [looly/hutool#1431]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

参照文档编写自定义配置文件加载，报错，无该方法。
是否该方法已经弃用？有其他的替代方案？

1. 复现代码

```java
//获取指定配置，第二个参数为分组，用于多数据源，无分组情况下传null
DataSource ds = DSFactory.get(setting, null);
```

![image](https://user-images.githubusercontent.com/23110725/108153981-21315600-7117-11eb-8269-d4ef4e6eaaa2.png)

尝试用create方法加载后再get，报警告
![image](https://user-images.githubusercontent.com/23110725/108154092-5178f480-7117-11eb-9459-7ea2e993ddce.png)

RedisDS相同方法依然有效

![image](https://user-images.githubusercontent.com/23110725/108154195-74a3a400-7117-11eb-9989-3848bdb5c16d.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
使用`DSFactory.create(setting).getDataSource(group)`

**Comment by looly** [comment]
文档稍后修改。
