### ISSUE TITLE
Setting文件如何读取其他yml文件的变量值

### ISSUE THREAD

**Issue by FJiayang** [looly/hutool#1432]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用数据库工具，配置db.setting文件，无法读取到其他文件的变量值

1. 复现代码

```
[blade]
url = ${blade.datasource.dev.url}
username = ${blade.datasource.dev.username}
password = ${blade.datasource.dev.password}

```

```java
DataSource dataSource = DSFactory.create(dbSetting).get(databaseName);
```

2. 堆栈信息

![image](https://user-images.githubusercontent.com/23110725/108205962-b9076200-7160-11eb-92eb-c2582cf64273.png)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
无法获取，这个和Spring不通，只能获取本文件中的变量。
