### ISSUE TITLE
为什么cn.hutool.core.util下面工具类没有私有构造函数，并且设计为final呢？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [looly/hutool#1435]
### 版本情况

工具类，没有实例变量的类，一般设计为私有并且final的，这样会使得封装性较好，如果客户端继承了你的类，那么util兼容性将会不好，

**Comment by looly** [comment]
其实也是考虑了继承的。

之前是有的，后来有用户提出需要继承工具类，为了：

1. 更好的使用别名，适应项目
2. 继承与项目工具类做到比较好的兼容，减少冗余。

**Comment by xiaozhiliaoo** [comment]
我理解用户要的是复用，而不是继承，继承是复用的方式之一，组合比继承好点，用户说继承就把权限打开了，用户继承你的类，某种情况会使你的类变得脆弱虽然，问题是你是静态方法，何来继承一说呢？

**Comment by looly** [comment]
道理如此。但是毕竟是工具，给用户最大的自由我觉得是没问题的。
