### ISSUE TITLE
希望操作流的工具在流读取完毕之后自动关闭

### ISSUE THREAD

**Issue by jiangqiang1996** [looly/hutool#1438]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

	IoUtil.readObj(InputStream in, Class<T> clazz) 方法没有关闭流，导致后面删不掉对应的文件。

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/108940976-39612200-768f-11eb-9611-58d64ba3b146.png)

**Comment by jiangqiang1996** [comment]
但是像输入流的操作，是可以明确知道是否读取完毕的。数据都读完了之后就没什么用了，而且像对象流这种东西，基本上就是一次读完就完了，所以个人觉得并没有什么影响吧？

**Comment by CherryRum** [comment]
单线程 肯定没事 多线程可能会有事 而且 提供了关闭操作  `IoUtil.close`


Java中还有个语法糖（jvm提供的）`{try}-with-resources`

```
private static void autoClosable() throws IOException {
		//jdk1.7版本流会自动关闭，实现了AutoClosable接口
		try(
				FileInputStream fis = new FileInputStream("xxx.txt");
				FileOutputStream fos = new FileOutputStream("hhh.txt");
				MyAutoClosable closable = new MyAutoClosable();
		){
			int len = -1;
			while((len=fis.read())!=-1) {
				fos.write(len);
			}
		}
	}
```

**Comment by looly** [comment]
此处in是用户传入，理应由用户自行关闭。
