### ISSUE TITLE
希望Excel，csv工具类读取文件时来增加批量回调的方法

### ISSUE THREAD

**Issue by xuzongmeng** [looly/hutool#1439]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.4.5
能否在在读取大文件的Excel时，方便增加批量回调的方法，比如1000行，2000行，这样数据库方便批量插入，以下是我CSV封装批量回调代码，execl批量回调封装
也类似，![微信截图_20210224173413](https://user-images.githubusercontent.com/16155051/108980676-e5722f80-76c6-11eb-8afd-c7e827ae0b67.png)
，虽然可以封装成批量回调形式，但是我大文件我只能用RowHandler ，得不到总行数，也就得不到最后结束的标志。我是希望大佬的工具类能增加批量回调方法。
![image](https://user-images.githubusercontent.com/16155051/108981249-84972700-76c7-11eb-8a5c-9220c8a2572f.png)

1. 复现代码

无
2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
可以自己实现RowHandler啊，然后累加行号，加逻辑判断即可。
