### ISSUE TITLE
ExcelWriter writer = ExcelUtil.getWriter();

### ISSUE THREAD

**Issue by dousp** [looly/hutool#144]
![7xj8566de j_0k bay6hi](https://user-images.githubusercontent.com/5936499/43708010-fd55e250-999b-11e8-8a44-701a85f67369.png)
这是缺是要哪个？我对比下代码pom引用的，我都引入了。

**Comment by looly** [comment]
需要引入poi-ooxml，这个库才能支持xlsx。

**Comment by looly** [comment]
还有确认没有引入两个版本的poi，可能会导致包冲突。

**Comment by dousp** [comment]
升级到4.1.5就没这问题了，今天测试了下
