### ISSUE TITLE
RuntimeUtil工具使用能保证同步执行吗？

### ISSUE THREAD

**Issue by robben009** [looly/hutool#1443]
1：RuntimeUtil.exec("mysql -uroot -p'***' -Dapolloconfigdb < /db.sql");

2：RuntimeUtil.exec("mysql -uroot -p'***' -Dapolloconfigdb < /db2.sql");

像上面两个执行sql文件的方法，能保证db.sql执行完成后，再执行db2.sql吗？会出现db.sql执行到一半,db2.sql就开始执行了（假如db.sql执行需要很久）

**Comment by looly** [comment]
这个不清楚，你得尝试。理论上你执行的命令是同步阻塞的就会同步执行。
