### ISSUE TITLE
StrUtils.format Sonar提示 Code Smell

### ISSUE THREAD

**Issue by jamestao83** [looly/hutool#1444]
### 版本情况

JDK版本：    1.8.0_241
hutool版本： 5.5.8
Sonar版本: Community Edition Version 8.6.1 

### 问题描述（包括截图）

StrUtils.format(CharSequence template, Object... params)

Sonar会提示 java:S3252"static" base class members should not be accessed via derived types

**Comment by looly** [comment]
只是代码建议而已吧。
