### ISSUE TITLE
setField 有问题

### ISSUE THREAD

**Issue by icy2003** [looly/hutool#145]
代码如下
DateUtil.date(1533784198)
            .setField(DateField.HOUR_OF_DAY, 12)
            .setField(DateField.MINUTE, 0)
            .setField(DateField.SECOND, 0)
            .setField(DateField.MILLISECOND, 0)
            .getTime()
当我把setField 去掉的时候，结果就是开始设置的时间戳，加上的时候，就变成下一年的了

**Comment by looly** [comment]
```java
DateTime dateTime = DateUtil.date(1533784198);
Console.log(dateTime);
dateTime
.setField(DateField.HOUR_OF_DAY, 12)
.setField(DateField.MINUTE, 0)
.setField(DateField.SECOND, 0)
.setField(DateField.MILLISECOND, 0);
Console.log(dateTime);
```

打印：

1970-01-19 02:03:04
1970-01-19 12:00:00

没有任何问题。

**Comment by looly** [comment]
补充说明一下：1533784198你这个时间明显是Unix时间戳，精确到了秒，想要获得正确时间需要自行*1000。

**Comment by icy2003** [comment]
![_20180810090832](https://user-images.githubusercontent.com/12480850/43933591-0512b0f2-9c7d-11e8-97f9-88503c99568d.png)
时间不对啊
如果是*1000，也就是DateUtil.date(1533784198000);eclipse会提示太长，不给过

**Comment by looly** [comment]
```java
DateUtil.date(1533784198000L);
```

**Comment by icy2003** [comment]
ok了……
