### ISSUE TITLE
TreeUtil 能否添加一个获取所有children 的List

### ISSUE THREAD

**Issue by lslvxy** [looly/hutool#1450]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Tree对象下有getChildren方法。

**Comment by lslvxy** [comment]
> Tree对象下有getChildren方法。

getChildren 只能获取当前节点的子节点,如果子节点还有嵌套的话那还是需要递归获取的.可否提供嵌套获取所有子节点

**Comment by looly** [comment]
树形结构获取所有递归子节点自己遍历把~~
