### ISSUE TITLE
HttpUtil的followRedirect时,中间head里有set-cookie没有跟过去

### ISSUE THREAD

**Issue by AnLiBoBo** [looly/hutool#1452]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.4.7

### 问题描述（包括截图）

1. 复现代码
https://www.domian.com/a 会set一个cookie,然后再重定向 https://www.domain.com/b
在b链接里需要用的a设置的cookie,但是followRedirect过去时,cookie没有跟过去

我记得hutool 里有个 HttpCookieManager
这个cookie管理器的执行原理是啥啊...

**Comment by looly** [comment]
升级到5.5.9尝试看是否丢失，新版本的hutool对cookie存储做了变动。
