### ISSUE TITLE
HttpRequest多文件上传时, 表单名称相同导致被覆盖.

### ISSUE THREAD

**Issue by syzsh** [looly/hutool#1453]
### 版本情况
5.3.2
JDK版本：    openjdk_8_201
hutool版本： 5.3.2

### 问题描述（包括截图）

httpRequest.form 添加文件时是用map存储的.
private Map<String, Resource> fileForm;

我请求的接口是用 File[] files 文件数组接收的
所以我的两个文件的name都是files导致被覆盖

请问有什么解决方案吗?

 复现代码

```java
@RequestMapping("/test")
public Object test(MultipartFile[] files) throws IOException {
    HttpRequest httpRequest = HttpRequest.post(URL).header(headerTokenKey, headerTokenValue);
    for (MultipartFile file : files) {
        httpRequest.form("files", file.getBytes(), file.getOriginalFilename());
    }
    return httpRequest.execute().body();
}
```

**Comment by looly** [comment]
使用`form(String name, File... files)`，或者使用`MultiFileResource`
