### ISSUE TITLE
ExcelUtils 读取xls文件报错

### ISSUE THREAD

**Issue by JarhomLiu** [looly/hutool#1454]
您好。在使用readBySax解析xls文件时会报以下的错：

Caused by: org.apache.poi.hssf.record.RecordInputStream$LeftoverDataException: Initialisation of record 0x208(RowRecord) left 14 bytes remaining still to be read.

文件打开，什么不做，保存后就可以了。
这个问题我在码云有和您提过，您当时回复我是因为文件有Bom头，用BomInputStream。然后我试了下都不行。
因为码云不能上传文件，我只有来github上传文件给您看看。
[测试数据.zip](https://github.com/looly/hutool/files/6068080/default.zip)

**Comment by looly** [comment]
搜了下，目测是Excel文件损坏，暂无解决办法。

**Comment by CherryRum** [comment]
把受保护的视图关掉再尝试一下
![image](https://user-images.githubusercontent.com/24296698/113414139-daf63480-93ee-11eb-8c82-dc7c8113aea3.png)
