### ISSUE TITLE
Excel导出列错误

### ISSUE THREAD

**Issue by LH040707** [looly/hutool#1458]
### 版本情况

JDK版本：    1.8
hutool版本： 5.5.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![微信截图_20210304114245](https://user-images.githubusercontent.com/24651895/109908211-d1d65280-7cde-11eb-95d9-9ddef0f9cc69.png)

![微信截图_20210304114431](https://user-images.githubusercontent.com/24651895/109908327-0c3fef80-7cdf-11eb-9107-1fb859133ca7.png)

设置标题中并没有设置Id列，导出的文件中却多出了Id列

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by taotao173** [comment]
我也遇到了这个问题，就是bean的第一个属性会被导出来

**Comment by LH040707** [comment]
> 我也遇到了这个问题，就是bean的第一个属性会被引入来
新增配置即可
writer.setOnlyAlias(true);//只导出设置类别名的列，其他字段都不要导出

**Comment by leimingchao666** [comment]
版本情况
JDK版本： 1.8
hutool版本： 5.7.0

writer.setOnlyAlias(true);//只导出设置类别名的列，其他字段都不要导出，好像失效了
没有设置别名的也导出来了
@PropIgnore
private Long userId;
最后这样解决了

**Comment by leimingchao666** [comment]
https://user-images.githubusercontent.com/25113897/220307614-8f03ebd3-ce19-4ade-991e-45176713aaf9.png

**Comment by leimingchao666** [comment]
https://user-images.githubusercontent.com/25113897/220308169-db334304-4f12-4e01-b821-30fb70071e35.png
https://user-images.githubusercontent.com/25113897/220308273-5cb72449-4441-4f1e-88ca-da1d9b0031b0.png

**Comment by leimingchao666** [comment]
最后这样解决了
https://user-images.githubusercontent.com/25113897/220309064-a8efbd58-c644-4e15-a2dc-a00277d6291a.png
