### ISSUE TITLE
CellUtil.getMergedRegionCell() 方法返回导致的空指针异常

### ISSUE THREAD

**Issue by ChambersChan** [looly/hutool#1462]
### 版本情况

hutool版本： 5.4.0

### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/32906036/110290969-564e0b80-8026-11eb-9fd5-49ae62b05797.png)
![image](https://user-images.githubusercontent.com/32906036/110291008-5f3edd00-8026-11eb-96c6-48d840bd4105.png)

线上日志发现该问题，缺少测试文件不好定位。

**Comment by qclucky7** [comment]
看了下更新日志应该是在5.4.5修复的这个问题,
没有具体issue, 倒数第三个

# 5.4.5 (2020-10-18)

### 新特性
* 【core   】     ConsoleTable代码优化（pr#190@Gitee）
* 【http   】     HttpRequest增加setProxy重载（pr#190@Gitee）
* 【core   】     XmlUtil.cleanComment（pr#191@Gitee）
* 【core   】     ArrayUtil.unWrap增加默认值（pr#1149@Github）
* 【core   】     ArrayUtil.indexOf修改double的equals判断（pr#1147@Github）
* 【core   】     优化StrUtil中部分参数校验以及逻辑处理（pr#1144@Github）
* 【core   】     简化CreditCode逻辑去除无用Character.toUpperCase（pr#1145@Github）
* 【core   】     NumberUtil增加generateRandomNumber重载，可自定义seed（issue#I1XTUT@Gitee）
* 【core   】     DataSizeUtil支持小数（pr#1158@Github）
* 【core   】     完善注释（pr#193@Gitee）
* 【core   】     优化Combination.countAll（pr#1159@Github）
* 【core   】     优化针对list的split方法（pr#194@Gitee）
* 【poi    】     ExcelWriter增加setRowStyle方法
* 【core   】     Assert增加函数接口（pr#1166@Github）
* 【core   】     新增AtomicIntegerArray、AtomicLongArray转换
* 【extra  】     PinyinUtil新增Bopomofo4j支持
* 【core   】     新增TemporalUtil工具类，新增时间相关方法

### Bug修复
* 【core   】     解决农历判断节日未判断大小月导致的问题（issue#I1XHSF@Gitee）
* 【core   】     解决ListUtil计算总量可能的int溢出问题（pr#1150@Github）
* 【json   】     解决JSON中转换为double小数精度丢失问题（pr#192@Gitee）
* 【core   】     修复CaseInsensitiveMap的remove等方法并没有忽略大小写的问题（pr#1163@Gitee）
* 【poi    】     修复合并单元格值读取错误的问题
* 【poi    】     修复NamedSql解析形如col::numeric出错问题（issue#I1YHBX@Gitee）
* 【core   】     修复计算相差天数导致的问题

**Comment by qclucky7** [comment]
![969DAF97-222B-499a-BBEE-B33CB4FB910F](https://user-images.githubusercontent.com/38759552/110307656-227ce100-803a-11eb-8d7c-c1b8cee3351c.png)
