### ISSUE TITLE
JsonUtil date 相关时间类型支持秒级时间戳配置

### ISSUE THREAD

**Issue by Teddy-Zhu** [looly/hutool#1464]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.9

### 问题描述（包括截图）

序列化或反序列化有时会遇到非常规时间格式， 例如 秒时间戳（目前貌似只支持毫秒）
可否增加该配置
感谢

2. 堆栈信息
3. 
暂无

3. 测试涉及到的文件（注意脱密）

暂无

**Comment by Teddy-Zhu** [comment]
#1350 注意到这个里面回复说先作为long 再转换， 感觉不太优雅，如果可以的话还是增加配置或者额外的主动注册convertor比较好一点

**Comment by looly** [comment]
暂时没有很好的解决办法，Hutool的json也不支持特定字段特定转换，只能是读出来后替换操作。
