### ISSUE TITLE
JSON工具类给getByPath方法添加默认值可好？

### ISSUE THREAD

**Issue by naimehao** [looly/hutool#1470]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
别的get方法都可以给默认值，但如果我要获取深层的某个值就要通过getByPath，就没法给默认值了，普通的get方法又不能写表达式。。。
![image](https://user-images.githubusercontent.com/50571342/110727464-4c125400-8256-11eb-8567-a920423d5747.png)

**Comment by looly** [comment]
5.6.0添加，感谢。
