### ISSUE TITLE
农历转国历

### ISSUE THREAD

**Issue by libra1010** [looly/hutool#1481]
看了源码其实是有这样的代码的
不太明白为什么不提供出来喃？
需要用到阴历这部分，大概率还是会有场景 阳历转阴历，阴历转阳历的需求吧？

**Comment by yu199195** [comment]
我觉得你有好的思路，可以提供pr出来

**Comment by CherryRum** [comment]
首先呢 农历 是临时确定的，**中国大陆现行的农历是由南京紫金山天文台历算室计算的，历算室还公布每年的24节气的具体时间（精确到分钟）、重要的天象（日月食等）时间、大行星运行轨道等信息。**

现行农历历法又叫做**紫金历**
`http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=E107EA4DE9725EDF819F33C60A44B296`

**Comment by CherryRum** [comment]
根据 南京紫金山天文台 发布的 大众万年历 只到2100（可能会进行修改），所以暂时没有完美的转换算法

**Comment by looly** [comment]
5.6.1增加`ChineseDate.getGregorianDate`

**Comment by CherryRum** [comment]
嗯嗯 注意2033事件

**Comment by looly** [comment]
@CherryRum 2033年有什么特别么？

**Comment by CherryRum** [comment]
https://zh.wikipedia.org/wiki/2033%E5%B9%B4%E5%95%8F%E9%A1%8C
大概就是 根据紫金历法应该是 闰十一月

**Comment by CherryRum** [comment]
https://www.hko.gov.hk/sc/gts/time/conversion.htm 具体参考这个 和紫金山 用的一样

**Comment by CherryRum** [comment]
还是您写的快 我刚写了一点 哈哈哈哈哈

**Comment by looly** [comment]
@CherryRum 2033暂时看不懂，不考虑了，有了好的方案再说吧。

**Comment by CherryRum** [comment]
@looly  等我最近面试完 看能不能提交个全面的  现在支持这种农历（中国 泰国 日本 等） 好的方案也就 time4j 看了下代码 太复杂了
根据 历法 和 部分天体算 都会有误差
