### ISSUE TITLE
ExcelWriter 如何设置斑马纹样式

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [looly/hutool#1488]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
ExcelWriter 如何设置斑马纹样式类似这种
![image](https://user-images.githubusercontent.com/16460207/111714104-eb090280-888b-11eb-92a5-3855ce4ba361.png)
具体颜色配置有没有详细说明

**Comment by looly** [comment]
用原生POI吧，Hutool对样式支持很弱。

**Comment by Jean-Jacques-Nuoan** [comment]
意思是，一次性写出write方法和样式设置不能一起生效么

**Comment by looly** [comment]
样式需要按照行单独创建，给行赋值样式。

**Comment by wang271724646** [comment]
试一下

**Comment by qclucky7** [comment]
试一下
CellStyle rowStyle = excelWriter.createRowStyle(1);
rowStyle.setFillBackgroundColor(IndexedColors.BLUE.getIndex());

**Comment by Jean-Jacques-Nuoan** [comment]
> 试一下
> CellStyle rowStyle = excelWriter.createRowStyle(1);
> rowStyle.setFillBackgroundColor(IndexedColors.BLUE.getIndex());

这个需要用excelWriter.setRowStyle()么，我看excelWriter.write方法默认用的styleset全局样式，我怀疑一次性导出的时候把之前设置的样式覆盖掉了

**Comment by qclucky7** [comment]
我本地试了试应该不太行
