### ISSUE TITLE
excel导出如何指定某个字段格式化

### ISSUE THREAD

**Issue by peterzhangnull** [looly/hutool#1491]
比如，0.09像格式化为9%

**Comment by looly** [comment]
只能传String。使用NumberUtil.decimalFormat格式化下。

**Comment by peterzhangnull** [comment]
查找api 文档解决了，通过修改对应cellStyle ；
`cellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("0.00%"));`
