### ISSUE TITLE
URLQuery解析get链接中的参数后无法修改

### ISSUE THREAD

**Issue by lin1993** [looly/hutool#1493]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8

### 问题描述（包括截图）
在使用URLQuery对get的参数进行解析，并重新封装的时候，发现里面是个不可变的map，这样我就无法对某个特定的参数进行操作。在对某个参数操作以后，无法覆盖之前的参数，因为不可变，所以整个处理就会非常麻烦。
不知道是否有代替的方法，或者，允许修改或者覆盖之前的参数。

**Comment by looly** [comment]
不太理解哪里用到不可变的Map了，默认使用TableMap：

![image](https://user-images.githubusercontent.com/1432613/113073148-2516c480-91fb-11eb-8c87-8130882adf97.png)

**Comment by qclucky7** [comment]
![BA5AD1A1-455E-42f0-AB6C-FF5E9428011F](https://user-images.githubusercontent.com/38759552/113074421-9eafb200-91fd-11eb-922b-df5f247bf707.png)
他应该说的是这里

**Comment by looly** [comment]
这个肯定不可变啊，想变更使用UrlQuery.add不就行了，默认覆盖的。
