### ISSUE TITLE
URLUtil.encode() URL编码后在网页上解码 +号会变成空格

### ISSUE THREAD

**Issue by SSFCHJJ** [looly/hutool#1499]
### 版本情况

JDK版本：    openjdk_8_275
hutool版本： 5.6.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        String data = "{\"result\":\"+\"}";
        String encode = URLUtil.encode(data);
        System.out.println("encode = " + encode); //%7B%22result%22:%22+%22%7D
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
![image](https://user-images.githubusercontent.com/36260193/113653606-c05edc80-96c8-11eb-94c6-63e8ae741106.png)

**Comment by looly** [comment]
使用`URLUtil.encodeAll`
