### ISSUE TITLE
FileNameUtil,FileTypeUtil未能正确识别url中的文件名,拓展名

### ISSUE THREAD

**Issue by awswt** [looly/hutool#1500]
### 版本情况
5.6.2
JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
未能识别出url中不带明显文件格式的文件,以下链接格式png,这是微信的图片地址
1. 复现代码
String uri = "http://mmbiz.qpic.cn/mmbiz/yqVAqoZvDibHzibqju4gK7q1d995WQ7BvCUomR2EJ7w3fiaA3b4shsmlcuKic7Ov6Vb9NCyyG8vRfBsnaBNVTIhrCw/0";
        System.out.println(FileNameUtil.mainName(uri));
        System.out.println(FileTypeUtil.getType(uri));
        System.out.println(FileNameUtil.extName(uri));
输出
0
null

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
必须不能识别啊，url中没有任何文件名信息。
