### ISSUE TITLE
HttpUtil 工具对URL 编码处理后, 导致无法正常请求

### ISSUE THREAD

**Issue by cnlinjie** [looly/hutool#1501]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.6.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

这是我使用抓包软件抓的请求图，

![image](https://user-images.githubusercontent.com/3601638/113990650-41ae9e80-9884-11eb-9583-d08dbcb6e501.png)

蓝色的是正常的请求，红色失败的是通过HttpUtil，被编码后的请求。

比如我请求：http://www.baidu.com/+86888888888

经过HttpUtil 处理后，会编码为：http://www.baidu.com/%2086888888888

如果有URL编码方面的处理，建议增加一个参数，默认是当前的处理模式，如果不需要编码的，则可手动设置，感谢。

1. 复现代码

```java
        String s = HttpUtil.get("http://www.baidu.com/+8618888888888");

```

2. 堆栈信息

编码前：
![image](https://user-images.githubusercontent.com/3601638/113990504-19bf3b00-9884-11eb-8d4c-2fcc44cc83e9.png)

编码后：
![image](https://user-images.githubusercontent.com/3601638/113990847-77ec1e00-9884-11eb-9a82-b44736b7015c.png)

**Comment by looly** [comment]
path中的+确实不应该编码，5.6.3修复此问题，感谢。

**Comment by ayang0422** [comment]
5.7.9中post还是会有对url编码，导致请求失败
<img width="875" alt="image" src="https://user-images.githubusercontent.com/43911138/177456401-df064cff-2a8a-4e02-8548-d5d8deee340e.png">
执行的时候，url被编码了，这个是有很大问题的
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/43911138/177456618-135a2b4d-7820-4369-a997-1c3172073a42.png">

**Comment by looly** [comment]
@ayang0422 尝试升级到5.8.4。
