### ISSUE TITLE
解析UTC格式时间字符串出错

### ISSUE THREAD

**Issue by matebase** [looly/hutool#1503]
### 版本情况

JDK版本：    oracle jdk_1.8.0_31
hutool版本： 5.6.2

### 问题描述（包括截图）

1.使用DateUtil.parse(CharSequence dateCharSequence) 无法解析UTC格式时间字符串（2021-03-30T12:56:51.53Z）
![image](https://user-images.githubusercontent.com/18496797/114174356-1652af00-996b-11eb-8609-73fb4c0ff3ab.png)

1. 复现代码
    public static void main(String[] args) {
        String utcTime="2021-03-30T12:56:51.53Z";
        DateTime parse = DateUtil.parse(utcTime);
        System.out.println(parse);
    }

```java

Exception in thread "main" cn.hutool.core.date.DateException: No format fit for date String [2021-03-30T12:56:51.53Z] !

```
2. 源码位置
DateUtil 816行
public static DateTime parseUTC(String utcString) {
		if (utcString == null) {
			return null;
		}
		int length = utcString.length();
		if (StrUtil.contains(utcString, 'Z')) {
			if (length == DatePattern.UTC_PATTERN.length() - 4) {
				// 格式类似：2018-09-13T05:34:31Z，-4表示减去4个单引号的长度
				return parse(utcString, DatePattern.UTC_FORMAT);
			} else if (length == DatePattern.UTC_MS_PATTERN.length() - 4) {
				// 格式类似：2018-09-13T05:34:31.999Z，-4表示减去4个单引号的长度
				return parse(utcString, DatePattern.UTC_MS_FORMAT);
			}
		} else {
			if (length == DatePattern.UTC_WITH_ZONE_OFFSET_PATTERN.length() + 2 || length == DatePattern.UTC_WITH_ZONE_OFFSET_PATTERN.length() + 3) {
				// 格式类似：2018-09-13T05:34:31+0800 或 2018-09-13T05:34:31+08:00
				return parse(utcString, DatePattern.UTC_WITH_ZONE_OFFSET_FORMAT);
			} else if (length == DatePattern.UTC_MS_WITH_ZONE_OFFSET_PATTERN.length() + 2 || length == DatePattern.UTC_MS_WITH_ZONE_OFFSET_PATTERN.length() + 3) {
				// 格式类似：2018-09-13T05:34:31.999+0800 或 2018-09-13T05:34:31.999+08:00
				return parse(utcString, DatePattern.UTC_MS_WITH_ZONE_OFFSET_FORMAT);
			} else if (length == DatePattern.UTC_SIMPLE_PATTERN.length() - 2) {
				// 格式类似：2018-09-13T05:34:31
				return parse(utcString, DatePattern.UTC_SIMPLE_FORMAT);
			} else if (StrUtil.contains(utcString, CharUtil.DOT)){
				// 可能为：  2021-03-17T06:31:33.99
				return parse(utcString, DatePattern.UTC_SIMPLE_MS_FORMAT);
			}
		}
		// 没有更多匹配的时间格式
		throw new DateException("No format fit for date String [{}] !", utcString);
	}

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
`.53`这里是两位数导致的，5.6.3修复此问题，感谢。
