### ISSUE TITLE
Http 工具类，308重定向处理不了

### ISSUE THREAD

**Issue by jiangjialiang918** [looly/hutool#1504]
### 版本情况

JDK版本：   jdk11
hutool版本： 5.2.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

HttpUtil和HttpRequest，308重定向处理不了，最后使用的jdk11的HttpClient

<html>
<head><title>308 Permanent Redirect</title></head>
<body bgcolor="white">
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>

**Comment by looly** [comment]
5.6.3加入支持，感谢~~
