### ISSUE TITLE
敏感信息处理方法

### ISSUE THREAD

**Issue by MrQiaoLei** [looly/hutool#1509]
能不能添加一个敏感信息脱敏的方法，例如手机号、身份证号等，传3个参数脱敏开始位数，结束位数和脱敏字符串。返回按要求脱敏后的数据

**Comment by looly** [comment]
有StrUtil.hide方法。

或者有封装好的：DesensitizedUtil

**Comment by linyongfu2013** [comment]
version 5.3.9 怎么没有 DesensitizedUtil 这个工具类了？

@looly

**Comment by looly** [comment]
升级到5.6.4
