### ISSUE TITLE
ExcelWriter.writer

### ISSUE THREAD

**Issue by c472672231** [looly/hutool#151]
write里面做分批处理了么？如果一次传送千万级别以上的数据能不能hold住。如果没有的话，建议处理一下。

**Comment by looly** [comment]
由于POI限制，这个量暂无办法处理。

**Comment by c472672231** [comment]
你可以封装一下处理多少条，然后线程停0.1秒，或者按量来处理嘛，当然我们可以在外面处理，但是能封装的话，封装一下。
