### ISSUE TITLE
ServletUtil.getMultipart 报错End of HTTP request stream reached

### ISSUE THREAD

**Issue by mml1988** [looly/hutool#1510]
### 版本情况

JDK版本：    1.8.0_181
hutool版本： 5.6.3

### 问题描述

1. 复现代码

```   @RequestMapping(value = "v2/upload", method = RequestMethod.POST)
    @ResponseBody
    public ResultDTO Upload(
            HttpServletRequest request
    ) {
        ResultDTO ret = null;

        try {
            MultipartFormData multipartFormData = ServletUtil.getMultipart(request);
            Object fileMap = multipartFormData.getFileMap();
```

2. 堆栈信息
```
Caused by: java.io.IOException: End of HTTP request stream reached
	at cn.hutool.core.net.multipart.MultipartRequestInputStream.readByte(MultipartRequestInputStream.java:33)
	at cn.hutool.core.net.multipart.MultipartRequestInputStream.readBoundary(MultipartRequestInputStream.java:69)
	at cn.hutool.core.net.multipart.MultipartFormData.parseRequestStream(MultipartFormData.java:61)
	at cn.hutool.extra.servlet.ServletUtil.getMultipart(ServletUtil.java:272)
```
3. 测试涉及到的文件
使用postman可以复现
![image](https://user-images.githubusercontent.com/26512798/114483135-6e730500-9c3a-11eb-8672-4157d8485dec.png)

抛出异常的位置
![image](https://user-images.githubusercontent.com/26512798/114483316-b6922780-9c3a-11eb-9754-f4d9d3416463.png)

请大佬帮忙确认，是否是我使用方法有问题？

**Comment by looly** [comment]
是不是在调用ServletUtil.getMultipart前调用了其他获取参数的方法？

**Comment by mml1988** [comment]
如上面问题复现代码所示，HttpServletRequest request在接口传入后，就直接传给了ServletUtil.getMultipart；这个方法在单元测试和文档里都没有

**Comment by looly** [comment]
还有不能用form-data，应该用x-www-form-urlencoded

**Comment by zhang141650** [comment]
> ### 版本情况
> JDK版本： 1.8.0_181 hutool版本： 5.6.3
> 
> ### 问题描述
> 1. 复现代码
> 
> ```
>     @ResponseBody
>     public ResultDTO Upload(
>             HttpServletRequest request
>     ) {
>         ResultDTO ret = null;
> 
>         try {
>             MultipartFormData multipartFormData = ServletUtil.getMultipart(request);
>             Object fileMap = multipartFormData.getFileMap();
> ```
> 
> 2. 堆栈信息
> 
> ```
> Caused by: java.io.IOException: End of HTTP request stream reached
> 	at cn.hutool.core.net.multipart.MultipartRequestInputStream.readByte(MultipartRequestInputStream.java:33)
> 	at cn.hutool.core.net.multipart.MultipartRequestInputStream.readBoundary(MultipartRequestInputStream.java:69)
> 	at cn.hutool.core.net.multipart.MultipartFormData.parseRequestStream(MultipartFormData.java:61)
> 	at cn.hutool.extra.servlet.ServletUtil.getMultipart(ServletUtil.java:272)
> ```
> 
> 3. 测试涉及到的文件
>    使用postman可以复现
>    ![image](https://user-images.githubusercontent.com/26512798/114483135-6e730500-9c3a-11eb-8672-4157d8485dec.png)
> 
> 抛出异常的位置 ![image](https://user-images.githubusercontent.com/26512798/114483316-b6922780-9c3a-11eb-9754-f4d9d3416463.png)
> 
> 请大佬帮忙确认，是否是我使用方法有问题？

请问现在解决了吗？碰到一样的问题了
