### ISSUE TITLE
增加一个字符串方法

### ISSUE THREAD

**Issue by yuxin5156** [looly/hutool#1511]
![image](https://user-images.githubusercontent.com/10668783/114495773-4347e000-9c51-11eb-9291-6c5d3398bd51.png)
**想增加一个更屌的方法，比如有一个变量我想在字符串中出现多次，我可以这样写**

```java
String template = "你到底{0}不{0}{1}，不{0}{1}的话，请直说！";
String str = StrUtil.format(template, "爱", "我"); //str -> 你到底爱不爱我，。。。
String str = StrUtil.format(template, "讨厌", "吃狗粮"); //str ->你到底讨不讨厌吃狗粮。。。
```

**Comment by looly** [comment]
可以使用`StrUtil.indexedFormat`
