### ISSUE TITLE
有html转png的工具类吗？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1513]

**Comment by looly** [comment]
没有。

**Comment by daidai21** [comment]
https://github.com/puppeteer/puppeteer

这个可以的，但是是ts，你找找java可能也有类似的吧

**Comment by joey-happy** [comment]
> https://github.com/puppeteer/puppeteer
> 
> 这个可以的，但是是ts，你找找java可能也有类似的吧

多谢 我看看有没有
