### ISSUE TITLE
ExcelWriter cn.hutool.poi.excel.ExcelWriter.merge(int firstRow, int lastRow, int firstColumn, int lastColumn, Object content, boolean isSetHeaderStyle) content无法设置合并单元格的内容

### ISSUE THREAD

**Issue by hzc313** [looly/hutool#1516]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/20276157/114689409-3fe35000-9d48-11eb-8681-23d3a1365e0e.png)
![image](https://user-images.githubusercontent.com/20276157/114689474-5093c600-9d48-11eb-9bfb-5ca1a72ff46d.png)
![image](https://user-images.githubusercontent.com/20276157/114689561-66a18680-9d48-11eb-8a82-30a1a6d1ca91.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个等等测试后回复。

**Comment by looly** [comment]
我这边测试没有问题，麻烦单独写个test试下，确认：

1. 是否合并后没有显示？

如果无法确定问题，麻烦把测试的test代码贴一下我好排查问题。

**Comment by lxldemon** [comment]
` public static void main(String[] args) {
        //通过工具类创建writer
        ExcelWriter writer = ExcelUtil.getWriter("d:/writeTest2123.xlsx");
        List<Map<String,Object>> list = initData();
        writer.addHeaderAlias("xmnf", "项目年份");//1

        //合并单元格后的标题行，使用默认标题样式
        writer.merge(7, "测试标题");
        writer.merge(3, 4, 0, 0, "9999", true);
        writer.write(list, true);
        writer.close();

    }

    private static List<Map<String, Object>> initData() {
        List<Map<String,Object>> list = new ArrayList<>();
        Map<String,Object> map = new HashMap<>();
        map.put("xmnf","2020");
        list.add(map);

        Map<String,Object> map1 = new HashMap<>();
        map1.put("xmnf","2020");
        list.add(map1);

        Map<String,Object> map2 = new HashMap<>();
        map2.put("xmnf","2019");
        list.add(map2);

        return list;
    }`
