### ISSUE TITLE
list拷贝是哪个类啊？没有找到

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1526]

**Comment by looly** [comment]
使用Convert.toList吧

**Comment by joey-happy** [comment]
好吧  
如果我使用 我第一个会想到BeanUtil这个工具 发现没有 我又去CollUtil去找 还是没找到
能否封装一下啊？

**Comment by joey-happy** [comment]
看了一下api 不满足我的要求 你这个中间借助了一个String去转换 我直接是一个List<A> 拷贝到 List<B> A对象与B对象中的属性完全相同

**Comment by looly** [comment]
这个拷贝涉及到浅拷贝和深拷贝的问题，浅拷贝即List中的Bean对象不复制，可以使用`ListUtil.toList`完成。

深拷贝涉及到Bean中的引用对象复制问题，可以考虑通过JSON转换。

**Comment by joey-happy** [comment]
public static <T> List<T> copyList(List<?> sourceList, Class<T> clazz) {
        return (List)sourceList.stream().map((source) -> {
            return copyProperties(source, clazz);
        }).collect(Collectors.toList());
    }

**Comment by joey-happy** [comment]
public static <T> List<T> copyList(List<?> sourceList, Class<T> clazz) {
        return (List)sourceList.stream().map((source) -> {
            return copyProperties(source, clazz);
        }).collect(Collectors.toList());
    }

public static <T> T copyProperties(Object source, Class<T> clazz) {
        T target = BeanUtils.instantiate(clazz);
        BeanUtils.copyProperties(source, target);
        Map<String, Field> sourceFieldMap = (Map)Arrays.asList(source.getClass().getDeclaredFields()).stream().filter((field) -> {
            return ValueEnum.class.isAssignableFrom(field.getType()) || field.getType() == Integer.TYPE || field.getType() == Integer.class;
        }).collect(Collectors.toMap(Field::getName, Function.identity()));
        List<Field> targetFieldList = (List)Arrays.asList(clazz.getDeclaredFields()).stream().filter((field) -> {
            if (ValueEnum.class.isAssignableFrom(field.getType())) {
                return sourceFieldMap.containsKey(field.getName()) && (((Field)sourceFieldMap.get(field.getName())).getType() == Integer.TYPE || ((Field)sourceFieldMap.get(field.getName())).getType() == Integer.class);
            } else if (field.getType() != Integer.TYPE && field.getType() != Integer.class) {
                return false;
            } else {
                return sourceFieldMap.containsKey(field.getName()) && ValueEnum.class.isAssignableFrom(((Field)sourceFieldMap.get(field.getName())).getType());
            }
        }).collect(Collectors.toList());
        targetFieldList.stream().forEach((field) -> {
            Field sourceField;
            if (ValueEnum.class.isAssignableFrom(field.getType())) {
                sourceField = (Field)sourceFieldMap.get(field.getName());
                ReflectionUtils.makeAccessible(sourceField);
                Integer valuex = (Integer)ReflectionUtils.getField(sourceField, source);
                ValueEnum valueEnum = (ValueEnum)getEnumValue(field.getType(), valuex);
                ReflectionUtils.makeAccessible(field);
                ReflectionUtils.setField(field, target, valueEnum);
            } else {
                sourceField = (Field)sourceFieldMap.get(field.getName());
                ReflectionUtils.makeAccessible(sourceField);
                int value = ((ValueEnum)ReflectionUtils.getField(sourceField, source)).getValue();
                ReflectionUtils.makeAccessible(field);
                ReflectionUtils.setField(field, target, value);
            }

        });
        return target;
    }

这是我们架构组自己写的代码实现

**Comment by joey-happy** [comment]
```java
    public static <T> List<T> copyList(List<?> sourceList, Class<T> clazz) {
        return (List)sourceList.stream().map((source) -> {
            return copyProperties(source, clazz);
        }).collect(Collectors.toList());
    }

public static <T> T copyProperties(Object source, Class<T> clazz) {
        T target = BeanUtils.instantiate(clazz);
        BeanUtils.copyProperties(source, target);
        Map<String, Field> sourceFieldMap = (Map)Arrays.asList(source.getClass().getDeclaredFields()).stream().filter((field) -> {
            return ValueEnum.class.isAssignableFrom(field.getType()) || field.getType() == Integer.TYPE || field.getType() == Integer.class;
        }).collect(Collectors.toMap(Field::getName, Function.identity()));
        List<Field> targetFieldList = (List)Arrays.asList(clazz.getDeclaredFields()).stream().filter((field) -> {
            if (ValueEnum.class.isAssignableFrom(field.getType())) {
                return sourceFieldMap.containsKey(field.getName()) && (((Field)sourceFieldMap.get(field.getName())).getType() == Integer.TYPE || ((Field)sourceFieldMap.get(field.getName())).getType() == Integer.class);
            } else if (field.getType() != Integer.TYPE && field.getType() != Integer.class) {
                return false;
            } else {
                return sourceFieldMap.containsKey(field.getName()) && ValueEnum.class.isAssignableFrom(((Field)sourceFieldMap.get(field.getName())).getType());
            }
        }).collect(Collectors.toList());
        targetFieldList.stream().forEach((field) -> {
            Field sourceField;
            if (ValueEnum.class.isAssignableFrom(field.getType())) {
                sourceField = (Field)sourceFieldMap.get(field.getName());
                ReflectionUtils.makeAccessible(sourceField);
                Integer valuex = (Integer)ReflectionUtils.getField(sourceField, source);
                ValueEnum valueEnum = (ValueEnum)getEnumValue(field.getType(), valuex);
                ReflectionUtils.makeAccessible(field);
                ReflectionUtils.setField(field, target, valueEnum);
            } else {
                sourceField = (Field)sourceFieldMap.get(field.getName());
                ReflectionUtils.makeAccessible(sourceField);
                int value = ((ValueEnum)ReflectionUtils.getField(sourceField, source)).getValue();
                ReflectionUtils.makeAccessible(field);
                ReflectionUtils.setField(field, target, value);
            }

        });
        return target;
    }
```

这是我们架构组自己写的代码实现

**Comment by looly** [comment]
5.6.4增加`BeanUtil.copyToList`

```java
return collection.stream().map((source)->{
	final T target = ReflectUtil.newInstanceIfPossible(targetType);
	copyProperties(source, target, copyOptions);
	return target;
}).collect(Collectors.toList());
```

这样可能更加直观。

**Comment by joey-happy** [comment]
非常给力
