### ISSUE TITLE
请问是否可以自动检测文本文件内容的字符集？

### ISSUE THREAD

**Issue by 8debug** [looly/hutool#1530]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.6.3

### 问题描述（包括截图）
请问是否可以自动检测文本文件内容的字符集？

**Comment by CherryRum** [comment]
https://code.google.com/archive/p/juniversalchardet/

**Comment by looly** [comment]
CharsetDetector.detect试下。
