### ISSUE TITLE
HttpUtil请求成功后json串部分不对

### ISSUE THREAD

**Issue by zynote** [looly/hutool#1531]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3（已尝试最新）

### 问题描述（包括截图）

1. 复现

正常返回，返回成功后，部分List中的item数据如图所示：
![image](https://user-images.githubusercontent.com/10859954/115664376-52770e00-a374-11eb-9ae8-d6aed1e0583d.png)
且同一个List里面，有的item数据是正常的：
![image](https://user-images.githubusercontent.com/10859954/115664601-a255d500-a374-11eb-99ef-b7e87f8b87dd.png)

如果用postman模拟，则数据都正常：（我用postman请求，参数一致）
![image](https://user-images.githubusercontent.com/10859954/115664470-733f6380-a374-11eb-9a34-e275afac3e16.png)

**Comment by looly** [comment]
检查下请求头是否一致，Hutool默认给了一部分headser，你自定义下Accept试下。
