### ISSUE TITLE
JSONUtil把某obj转换成json字符串时部分数据丢失未转换出来

### ISSUE THREAD

**Issue by ObamaX** [looly/hutool#1532]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JSONUtil.toJsonStr()把某个obj转换成json字符串时，部分数据未转换！
1. 复现代码
JSONUtil.toJsonStr(response);
2.打印信息
fastjson response{"clusters":{"fragment":true,"skipped":0,"successful":0,"total":0},"failedShards":0,"fragment":false,"hits":{"fragment":true,"hits":[{"fields":{},"fragment":false,"highlightFields":{},"id":"1001","matchedQueries":[],"primaryTerm":0,"rawSortValues":[],"score":1.0,"seqNo":-2,"sortValues":[],"sourceAsMap":{"sex":"男","name":"李四","age":28},"sourceAsString":"{\"name\":\"李四\",\"sex\":\"男\",\"age\":28}","sourceRef":{"fragment":true},"type":"_doc","version":-1}],"maxScore":1.0,"totalHits":{"relation":"EQUAL_TO","value":1}},"internalResponse":{"fragment":true,"numReducePhases":1},"numReducePhases":1,"profileResults":{},"shardFailures":[],"skippedShards":0,"successfulShards":1,"timedOut":false,"took":{"days":0,"daysFrac":1.0601851851851852E-5,"hours":0,"hoursFrac":2.5444444444444446E-4,"micros":916000,"microsFrac":916000.0,"millis":916,"millisFrac":916.0,"minutes":0,"minutesFrac":0.015266666666666666,"nanos":916000000,"seconds":0,"secondsFrac":0.916,"stringRep":"916ms"},"totalShards":1}
fastjson hits{"fragment":true,"hits":[{"fields":{},"fragment":false,"highlightFields":{},"id":"1001","matchedQueries":[],"primaryTerm":0,"rawSortValues":[],"score":1.0,"seqNo":-2,"sortValues":[],"sourceAsMap":{"sex":"男","name":"李四","age":28},"sourceAsString":"{\"name\":\"李四\",\"sex\":\"男\",\"age\":28}","sourceRef":{"fragment":true},"type":"_doc","version":-1}],"maxScore":1.0,"totalHits":{"relation":"EQUAL_TO","value":1}}
hutool response{"shardFailures":[],"successfulShards":1,"totalShards":1,"internalResponse":{"numReducePhases":1},"skippedShards":0,"clusters":{"skipped":0,"total":0,"successful":0}}
hutool hits[[]]

用fastjson就没有存在该问题，用hutool自带的jsonutil存在部分信息未转换出来

**Comment by looly** [comment]
请检查你未转换出来的bean：

1. 是否有getXXX方法
2. getXXX对应是否有XXX字段。
