### ISSUE TITLE
JSONUtil.isJson()校验结果不正确

### ISSUE THREAD

**Issue by risfeng** [looly/hutool#1533]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3

### 问题描述（包括截图）
输入Json字符串：{"最小日期":"2001-01-01","最大日期"} 调用JSONUtil.isJson()
1、预期结果：应该返回false（因为json字符串非法）
2、实际结果：返回了true

![image](https://user-images.githubusercontent.com/11593554/115991169-e9a0c780-a5f9-11eb-8ec8-2b3621bce2a1.png)

1. 复现代码

```java
public static void main(String[] args) {
        String json = "{\"最小日期\":\"2001-01-01\",\"最大日期\"}";
        boolean isJson = JSONUtil.isJson(json);
        System.out.println("这不是合法json，为什么返回true，isJson=" + isJson);
    }
// 输出结果：这不是合法json，为什么返回true，isJson=true
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
pr中已经解释过了。
