### ISSUE TITLE
文件类型判断不准确

### ISSUE THREAD

**Issue by crrtty** [looly/hutool#1546]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7

### 问题描述（包括截图）

1. 复现代码
doc文档类型会识别成xls
![image](https://user-images.githubusercontent.com/13958603/116518738-3a1e6a80-a903-11eb-84a3-99e204d34eaa.png)
![image](https://user-images.githubusercontent.com/13958603/116518954-7d78d900-a903-11eb-9697-cac10bfaab54.png)
![image](https://user-images.githubusercontent.com/13958603/116519036-93869980-a903-11eb-9ec0-34ed3d47882e.png)

xlsx文件会识别成zip，空的docx文件得到的type是null
![image](https://user-images.githubusercontent.com/13958603/116519331-f1b37c80-a903-11eb-864c-63c09eeb7933.png)
![image](https://user-images.githubusercontent.com/13958603/116519423-0bed5a80-a904-11eb-94ed-e99c4313fd81.png)

其它类型文件还没试

**Comment by Ltyro** [comment]
getType方法说明了：
 1、无法识别类型默认按照扩展名识别
2、xls、doc、msi头信息无法区分，按照扩展名区分
3、zip可能为docx、xlsx、pptx、jar、war、ofd头信息无法区分，按照扩展名区分

**Comment by looly** [comment]
是滴，尝试最新版本，使用扩展名辅助判断了。
