### ISSUE TITLE
MapUtil新增交集、并集、差集

### ISSUE THREAD

**Issue by lin-code-world** [looly/hutool#1547]
MapUtil可以新增交集、并集、差集

**Comment by daidai21** [comment]
https://github.com/dromara/hutool/pull/1556

这里PR了一个Set的，是不是可以写个模板计算集合的交并集？！

**Comment by looly** [comment]
交集并集差集都有啊，见：

CollUtil.intersection

CollUtil.union

CollUtil.disjunction

**Comment by looly** [comment]
Map的交集如何做？并级可以用：

`ListValueMap`

`SetValueMap`
