### ISSUE TITLE
Mongodb连接配置不生效

### ISSUE THREAD

**Issue by zcyoop** [looly/hutool#1548]
### 版本情况

JDK版本：    1.8
hutool版本： 5.6.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在配置文件中配置connectTimeout后不生效
1.个人猜测原因
MongoDS在138行分组会被默认设置为空
![image](https://user-images.githubusercontent.com/39327876/116528776-caae7800-a90e-11eb-908e-f2b1a05dffe2.png)
在MongoDS 340行中由于已经被设置为空了，所以在判断分组是否为空时又被加上了点，所以在后面设置参数时设置失败
![image](https://user-images.githubusercontent.com/39327876/116528951-fd587080-a90e-11eb-9ef4-264b2f8d901e.png)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
确实有这个问题，判断了null，没有判断""。

5.6.5修复此问题，感谢。
