### ISSUE TITLE
增加本地端口是否被占用？

### ISSUE THREAD

**Issue by angelyouyou** [looly/hutool#1549]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
这个一般写 shell吧

**Comment by angelyouyou** [comment]
@CherryRum 在程序中启动自己的服务需要检查是否被占用？
https://blog.csdn.net/weixin_26963033/article/details/114510861?utm_medium=distribute.wap_relevant.none-task-blog-baidujs_baidulandingword-11

**Comment by CherryRum** [comment]
一般来说程序最后都在服务器上跑着，服务器都是有自己规范的，很少会冲突

**Comment by angelyouyou** [comment]
> 一般来说程序最后都在服务器上跑着，服务器都是有自己规范的，很少会冲突

有些服务是用户后期指定端口号开启的，这时候需要告诉用户这个端口是否可用

**Comment by looly** [comment]
NetUtil.isUsableLocalPort
