### ISSUE TITLE
希望增强NetUtils的netCat的功能

### ISSUE THREAD

**Issue by angelyouyou** [looly/hutool#1562]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1.当前不支持UDP版本探测；
2.不支持结果确认；
3.不支持探测间隔，次数和超时时间的设置。
希望支持上述功能，增强可用性。

**Comment by looly** [comment]
此方法只是简单的模拟Linux下的`netcat`命令，关于增强功能暂时不考虑，考虑第三方库吧。
