### ISSUE TITLE
SystemClock是否存在内存问题

### ISSUE THREAD

**Issue by xiaoyu9720** [looly/hutool#1566]
### 版本情况

JDK版本：    1.8.0_211-b12
hutool版本： 5.1.2+

### 问题描述
 在查看线程资源占用情况时，发现System Clock内存占用超高，而且不断上涨。经过查阅源码SystemClock类的InstanceHolder创建SystemClock实例，将会每隔一毫秒执行now = System.currentTimeMillis()；理想情况下不存在内存的问题。猜想的情况是System.currentTimeMillis()不能在1ms内返回，导致同样的now = System.currentTimeMillis();代码进入任务队列，内存不断上涨

**Comment by looly** [comment]
是的，所以这个类只能用于对currentTimeMillis方法调用极为频繁的情况下，因为实际上如果单独调用currentTimeMillis可能每毫秒请求的次数更多。

**Comment by xiaoyu9720** [comment]
可否将SystemClock实例弄成懒加载，只要使用了hutool，现在就会启动线程

**Comment by looly** [comment]
时间这个东西如何懒加载？欢迎提供思路。

你每次去请求时间，什么情况下触发更新呢？

**Comment by xiaoyu9720** [comment]
public static final SystemClock INSTANCE = new SystemClock(1L);在类加载的时候就会创建实例，是否可以使用 public static final SystemClock INSTANCE =null;避免类加载的时候创建实例对象,在需要使用的时候再创建实例并启动线程。现在我了解到代码存在的问题是，只要我引用了hutool-core, SystemClock.InstanceHolder会new SystemClock(1L)；启动线程，其实我并不一定会调用SystemClock.currentTimeMillis(),SystemClock.now()这些方法，这是否这是资源的浪费。另外，由于我的电脑在性能可能不是很好，’System Clock ‘线程中 this.now = System.currentTimeMillis();的执行时间可能超过1ms,造成任务堆积，由此引发内存问题。SystemClock应该是为极端情况下准备的，不应该任何环境都使用吧。如有说得不对的请指正:)

**Comment by looly** [comment]
对的啊，但是引入hutool不会触发`SystemClock`的使用啊，只有你自行new之后才会启动。

怀疑是不是碰到版本bug了？麻烦升级到5.6.5最新试下。

**Comment by xiaoyu9720** [comment]
SystemClock在mybatisplus里面也存在，是mybatisplus搞得鬼，是我没仔细排查。问题已解决，谢谢
