### ISSUE TITLE
SoapClient不支持短连接

### ISSUE THREAD

**Issue by yanghuaibing1680** [looly/hutool#1567]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3
建议SoapClient将HttpRequest类的keepAlive扩展可设置，否则服务端不允许长连接的情况下就是这个问题
修改代码如下：

    /**
     * 默认长连接
     */
    private boolean keepAlive = true;

    /**
     * 设置是否长连接
     *
     * @param isKeepAlive是否
     * @return this
     */
    public SoapClient keepAlive(boolean isKeepAlive){
        this.keepAlive = isKeepAlive;
        return this;
    }

   /**
     * 发送请求，获取异步响应
     *
     * @return 响应对象
     */
    private HttpResponse sendForResponse() {
        return HttpRequest.post(this.url)//
                .setFollowRedirects(true)//
                .setConnectionTimeout(this.connectionTimeout)
                .setReadTimeout(this.readTimeout)
                .contentType(getXmlContentType())//
                .header(this.headers()).keepAlive(this.keepAlive)
                .body(getMsgStr(false))//
                .executeAsync();
    }

**Comment by looly** [comment]
你可以调用header方法自行添加：

```java
SoapClient client = SoapClient.create(url).header(Header.CONNECTION, "Close");
```
