### ISSUE TITLE
Setting的getByGroup希望增加默认值参数

### ISSUE THREAD

**Issue by anaer** [looly/hutool#1572]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.5

```
public <T> T getByGroup(String key, String group, T defaultValue){}
```

**Comment by looly** [comment]
可以使用`getStr(String key, String group, String defaultValue)`

**Comment by anaer** [comment]
主要是希望加个泛型, 根据defaultValue类型返回

**Comment by looly** [comment]
增加泛型没有任何意义吧？Setting的值基本都是String类型，最多转换为数字类型，泛型会让用户误以为可以支持Bean。
