### ISSUE TITLE
HttpUtil的https请求问题，报错connection reset

### ISSUE THREAD

**Issue by Murphy-Chang** [looly/hutool#1573]
### 版本情况

JDK版本：    jdk1.8.0_111
hutool版本： 5.3.5和5.6.5
httpclient版本：4.5.12

### 问题描述
对接第三方平台（.net开发，IIS直接部署的https，没有使用nginx）
postman和浏览器测试接口都正常
使用HttpUtil调用任何接口都是connection reset
起初认为是对方服务器没有做好TLSv1.2的解析，后来调查过后发现对方是支持的
然后使用httpclient调用，一切正常

1. 复现代码
* HttpUtil
```java
public static void main(String[] args) {
    Map<String, Object> body = new HashMap<>();
    body.put("param1", "xxx");
    body.put("param2", "xxx");
    String resultStr = HttpUtil
		    .createPost("https://www.xxx.com:9021/api/xxx")
		    .header("Content-Type", "application/json")
		    .body(JSONUtil.toJsonStr(body))
		    .execute()
		    .charset("utf-8")
		    .body();
    System.out.println(JSONUtil.toJsonPrettyStr(resultStr));
}
```

* httpclient
```java
public static void main(String[] args) {
    try {
        HttpPost httppost = new HttpPost("https://www.xxx.com:9021/api/xxx");
	httppost.addHeader("Content-type","application/json");

	Map<String, Object> body = new HashMap<>();
	body.put("param1", "xxx");
	body.put("param2", "xxx");
	StringEntity entity = new StringEntity(JSONUtil.toJsonStr(body));
	httppost.setEntity(entity);

	HttpClient httpclient = HttpClients.createDefault();
	HttpResponse resp = httpclient.execute(httppost);
	HttpEntity he = resp.getEntity();
	String respContent = EntityUtils.toString(he,"UTF-8");
	System.out.println(JSONUtil.toJsonPrettyStr(respContent));
    }catch (Exception e) {
	e.printStackTrace();
    }
}
```

2. 堆栈信息
添加```-Djavax.net.debug=ssl```参数后的日志
* HttpUtil
![image](https://user-images.githubusercontent.com/42343239/117932817-6ee2e680-b333-11eb-8ba0-7c5c14ef9096.png)

* httpclient
![image](https://user-images.githubusercontent.com/42343239/117936340-5379da80-b337-11eb-88d1-64b42744ed2b.png)

**Comment by looly** [comment]
怀疑是请求头的问题，hutool默认添加以下头：

![image](https://user-images.githubusercontent.com/1432613/118056736-07717900-b3bd-11eb-9154-973f50dfa5e4.png)


尝试清除或者覆盖这些头试下。

**Comment by Murphy-Chang** [comment]
还是一样的   HttpUtil在握手建立连接后，开始write数据就直接被服务器断开连接了，上面的截图中可以看到

**Comment by world66** [comment]
> 还是一样的 HttpUtil在握手建立连接后，开始write数据就直接被服务器断开连接了，上面的截图中可以看到

麻烦问下 这个解决了么 我也遇见同样的报错了

**Comment by looly** [comment]
> > 还是一样的 HttpUtil在握手建立连接后，开始write数据就直接被服务器断开连接了，上面的截图中可以看到
> 
> 麻烦问下 这个解决了么 我也遇见同样的报错了

一般是服务端没法接收你的参数。API公开么？我这边测试下。

PostMan可以访问么？

**Comment by Murphy-Chang** [comment]
> > 还是一样的 HttpUtil在握手建立连接后，开始write数据就直接被服务器断开连接了，上面的截图中可以看到
> 
> 麻烦问下 这个解决了么 我也遇见同样的报错了

我尝试了覆盖header参数依旧是不行的，postman可以调通，使用httpUtil调用其他https接口也是ok的，多半是服务端对头部参数的配置问题。我这边对接的是某个政府平台，具体的配置也没法获取，调试也比较困难，所以我是用httpclient代替的。如果你是自己公司开发的平台，最好开发服务端的人联调一下。

**Comment by world66** [comment]
可能跟系统环境也有关系 最终我用了httpClient
我在几个不同的系统环境上试了
我自己用的deepin 没问题
win10的两台电脑 一个有问题 一个没问题
不行的那台win10部署测试代码没问题 部署生产环境就有问题

**Comment by Murphy-Chang** [comment]
> 可能跟系统环境也有关系 最终我用了httpClient
> 我在几个不同的系统环境上试了
> 我自己用的deepin 没问题
> win10的两台电脑 一个有问题 一个没问题
> 不行的那台win10部署测试代码没问题 部署生产环境就有问题

2个环境的java版本都分别是多少能交流一下吗

**Comment by looly** [comment]
很是奇怪啊，按理说不应该有差别。

之前遇到问题是碰到JDK的一个bug，升级jdk8_update200以上最新就可以。

具体见：https://hutool.cn/docs/#/http/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by Murphy-Chang** [comment]
> 很是奇怪啊，按理说不应该有差别。
> 
> 之前遇到问题是碰到JDK的一个bug，升级jdk8_update200以上最新就可以。
> 
> 具体见：https://hutool.cn/docs/#/http/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

我好像找到问题了，对方服务器应该是开启了SNI。httpUtil发起的握手请求clientHello中并没有带server_name扩展字段信息 httpclient中带了，见下图，左边是HttpUtil，右边是httpclient。
![image](https://user-images.githubusercontent.com/42343239/119764003-302c5f00-bee3-11eb-8310-95f60665d06c.png)

然后我打断点调试，发现最后走到的socket都是sun.security.ssl.SSLSocketImpl，只是使用的构造器不同，如下图
![image](https://user-images.githubusercontent.com/42343239/119764597-4e468f00-bee4-11eb-830f-383a125396db.png)
可以看到httpclient调用的构造器中设置了一步
```this.serverNames = Utilities.addToSNIServerNameList(this.serverNames, this.host);```

ps:另外调试的时候还遇到了一个奇怪的问题，使用httpUtil调用有时候能通有时候不能通，可能是用httpclient调用之后socket缓存住了

**Comment by Murphy-Chang** [comment]
附个测试代码，对方服务器应该是多证书的

```
    public static void main(String[] args) throws Exception {
		Map<String, Object> body = new HashMap<>();
		body.put("param1", "xxx");
		body.put("param2", "xxx");
		String url = "https://www.xxx.com:9021/api/xxx";

		// httpclient
		HttpPost httppost = new HttpPost(url);
		httppost.addHeader("Content-type","application/json");
		StringEntity entity = new StringEntity(JSONUtil.toJsonStr(body));
		httppost.setEntity(entity);
		HttpClient httpclient = HttpClients.createDefault();
		HttpResponse resp = httpclient.execute(httppost);
		HttpEntity he = resp.getEntity();
		String respContent = EntityUtils.toString(he,"UTF-8");
		System.out.println(respContent);

		// httputil
		String resultStr = HttpUtil
				.createPost(url)
				.header("Content-Type", "application/json")
				.body(JSONUtil.toJsonStr(body))
				.execute()
				.charset("utf-8")
				.body();
		System.out.println(resultStr);
	}
```

**Comment by iceco1a** [comment]
> 附个测试代码，对方服务器应该是多证书的
请问一下目前你们是怎么解决这个问题的？换用了HttpClient？还是Hutool更新解决了这个问题？谢谢

**Comment by looly** [comment]
这个先保留，稍后看下。

**Comment by Murphy-Chang** [comment]
> > 附个测试代码，对方服务器应该是多证书的
> > 请问一下目前你们是怎么解决这个问题的？换用了HttpClient？还是Hutool更新解决了这个问题？谢谢

我是换用httpclient

**Comment by looly** [comment]
https://issues.apache.org/jira/browse/HTTPCLIENT-1119

貌似httpclient之前也遇到这个问题，先mark，稍后看。

**Comment by looly** [comment]
@Murphy-Chang 终于找到了，JDK的一个bug，已经在JDK8_141之后修复了，见：

https://www.oracle.com/java/technologies/javase/8u141-relnotes.html

> Earlier releases of JDK 8 Updates didn't always send the Server Name Indication (SNI) extension in the TLS ClientHello phase if a custom hostname verifier was used. This verifier is set via the setHostnameVerifier(HostnameVerifier v) method in HttpsURLConnection. The fix ensures the Server Name is now sent in the ClientHello body.

https://bugs.openjdk.java.net/browse/JDK-8144566

升级JDK试下吧。

**Comment by iceco1a** [comment]
> @Murphy-Chang 终于找到了，JDK的一个bug，已经在JDK8_141之后修复了，见：
> 
> https://www.oracle.com/java/technologies/javase/8u141-relnotes.html
> 
> > Earlier releases of JDK 8 Updates didn't always send the Server Name Indication (SNI) extension in the TLS ClientHello phase if a custom hostname verifier was used. This verifier is set via the setHostnameVerifier(HostnameVerifier v) method in HttpsURLConnection. The fix ensures the Server Name is now sent in the ClientHello body.
> 
> https://bugs.openjdk.java.net/browse/JDK-8144566
> 
> 升级JDK试下吧。

> JDK:1.8.0_201
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-bit Server VM (build 25.201-b09,mixed mode)

Linux:
Linux host-10-10-10-11 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Linux version 3.10.0-693.el7.x86_64 (mockbuild@x86-038.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jul 6 19:56:57 EDT 2017

Red Hat Enterprise Linux Server release 7.4 (Maipo)

在对接多个外部系统的时候，只遇到一个系统会出现这种情况，其余是正常的。java环境是高于141的，并且仅能在Linux下复现这个问题，windows下是正常的。

**Comment by Murphy-Chang** [comment]
@looly 升级到了1.8.0_201，好像是没这问题了

**Comment by guoguozhi** [comment]
open jdk 17似乎也有这个问题呢

**Comment by looly** [comment]
@guoguozhi 试下最新的update版本。

**Comment by lihengjie** [comment]
jdk17 也有这个问题。。。

**Comment by looly** [comment]
@guoguozhi @lihengjie 

看下这个https://bugs.openjdk.org/browse/JDK-8277307

貌似你们要升级到17.0.10以上试下。

**Comment by lihengjie** [comment]
> @guoguozhi @lihengjie
> 
> 看下这个https://bugs.openjdk.org/browse/JDK-8277307
> 
> 貌似你们要升级到17.0.10以上试下。

收到，我去下载试试看，感谢~~~

**Comment by yangkebiao** [comment]
我也遇到此类问题，在请求前设置System.setProperty("https.protocols", "TLSv1.2,TLSv1.1,SSLv3"); 就好了
