### ISSUE TITLE
rsa无法分片加解密 setDecryptBlockSize setEncryptBlockSize已设置

### ISSUE THREAD

**Issue by CallMeBatMan** [looly/hutool#1574]
jdk1.8
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>4.1.0</version>
</dependency>
-----------------
无法分片加解密
rsa.setDecryptBlockSize(Integer.MAX_VALUE);
rsa.setEncryptBlockSize(Integer.MAX_VALUE);
Exception in thread "main" cn.hutool.crypto.CryptoException: IllegalBlockSizeException: Data must not be longer than 117 bytes
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.encrypt(AsymmetricCrypto.java:226)
	at cn.hutool.crypto.asymmetric.RSA.encrypt(RSA.java:154)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.encrypt(AsymmetricCrypto.java:287)
	at cn.hutool.crypto.asymmetric.AsymmetricCrypto.encryptHex(AsymmetricCrypto.java:299)
-----------------
 public static void main(String[] args) {
        String publicKey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDb+tV4NSHvyIfJzuE2vKRtbFDC" +
                "9fcYyzw0O0iaWsAtxQGdfjUDiXnmCrsxItfp9jBsVCb1F3B27eKSSPoA+dGhXCW0" +
                "f+1BWgALFWvQk0y8crqcl3niSAlX5QusbPo4OkgJWA08us2ZpyLYeuEZYsCe1FSZ" +
                "NCFQSgQgmb4pEzgXVwIDAQAB";
        String privateKey = "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANv61Xg1Ie/Ih8nO" +
                "4Ta8pG1sUML19xjLPDQ7SJpawC3FAZ1+NQOJeeYKuzEi1+n2MGxUJvUXcHbt4pJI" +
                "+gD50aFcJbR/7UFaAAsVa9CTTLxyupyXeeJICVflC6xs+jg6SAlYDTy6zZmnIth6" +
                "4RliwJ7UVJk0IVBKBCCZvikTOBdXAgMBAAECgYAMefSDhdfv5pq0+nPRi+9zeVI3" +
                "TIYANP6sI7ShdIYz0lmeGhtdoP1166PkTIqcbWcfrcIr4nFxfVp9W4A6b/DQsBok" +
                "a6JSUUrn83hTOnJOZ+ogYhT55A4JPDofXiTNQX97bewMbxAbTlSzel6L4COelR3t" +
                "TkoyCorwv6rFbPZNQQJBAPmxKPIKc5S/LE6/G4CNjDJB5aqbV4oL9Wzhzr2XNm+O" +
                "Cj5dJHt9n5yBxSSdjV0qpPeSVh0IQapSEMWvJpCyRrcCQQDhiYPsvdKMn+XYFJaU" +
                "DZNp09AMqezQlyhSmm6TNMQPr6uq6FbYT3geDQMlo1UDn5GJzQvFPhZ+SyVX+6Zy" +
                "AxRhAkAe12omU3IpWl+/rk1YWKOLhaY3p45th8Kd21ptAqN/rfzH7TtXYZH4g/L0" +
                "7d0LN/w+dD3cwitSPWbC9DqAPvULAkEA25LB+W4k2fuiDWid4K4G4nTwjCOzBrDi" +
                "9Oic1nv8lTj17IIeaqGT083fTnlhfxGO45XY68Kyq2oFhU7ekQkmgQJBAI+n49w9" +
                "MZLpzZATbraVYRtV7nuKzq8x9KHxUV93RgYW8AgZgfiBQyRy46VB4fYAop4tKkW3" +
                "eufXuG1RqNKrO74=";
        String data = "因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，因此，";
        RSA rsa = SecureUtil.rsa(privateKey, publicKey);
        rsa.setDecryptBlockSize(Integer.MAX_VALUE);
        rsa.setEncryptBlockSize(Integer.MAX_VALUE);

        String encrypt = rsa.encryptHex(data, KeyType.PrivateKey);
        System.out.println(encrypt.length() + " 加密：" + encrypt);
        System.out.println("解密：" + rsa.decryptFromBcd(encrypt, KeyType.PublicKey));

    }

**Comment by looly** [comment]
你的版本呢太旧了，考虑升级到5.6.5

**Comment by CallMeBatMan** [comment]
> 你的版本呢太旧了，考虑升级到5.6.5

RSA的实例中应该要求：{ encryptBlockSize<=117，decryptBlockSize<=128 } 吧？
如果小于这个范围，我看到仅仅是write流时不同，那设置这两个属性的好处是什么呢？
设置小范围的maxBlockSize场景有哪些呢？

**Comment by looly** [comment]
新版本中这个block是自动获取的，应该不用手动设置。

手动设置用于特殊情况下，加密解密为了保持一致。
