### ISSUE TITLE
数据库查询List<Entity>返回有Clob，想要直接转成String有什么好的方法吗？

### ISSUE THREAD

**Issue by madizm** [looly/hutool#1577]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： hutool-all-5.6.3.jar

### 问题描述（包括截图）

自己重新写一个EntityListHandler感觉有些重复，期待更好的解决办法。

**Comment by looly** [comment]
直接entity.getStr()不就行了，toBean也会自动转换的。

**Comment by madizm** [comment]
就是不想循环List，对每个entity执行getStr()😥。
我想是否可以把cn.hutool.db.handler.HandleHelper#getColumnValue设置成protect的方法，允许用户继承覆盖

**Comment by looly** [comment]
看来你只能自己实现RsHandler接口了。
