### ISSUE TITLE
where 语句的 set 方法支持问题

### ISSUE THREAD

**Issue by icy2003** [looly/hutool#158]
假如有个查询是
where status>0 and status < 3
一开始我写的是

.set("status", ">0").set("status" , "< 3")

但是调试发现，后者把前者的条件覆盖了
希望对一个字段的多个条件可以得到支持

**Comment by c472672231** [comment]
文档上写了，暂时不支持字段多条件，你可以写sql试下，不要用entity的方法

**Comment by looly** [comment]
可以使用：

```
List<Entity> find = Db.use().findBy("user", 
	Condition.parse("status", "> 0"), 
	Condition.parse("status", "< 3")
);
```
