### ISSUE TITLE
建议FileUtil.isEmpty方法里面当文件不存在时返回true

### ISSUE THREAD

**Issue by Camio1945** [looly/hutool#1582]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.5

### 问题描述

如题：建议FileUtil.isEmpty方法里面当文件不存在时返回true，即判断一下file.exists()，文件不存在可以认为是空的。

**Comment by looly** [comment]
5.6.6修改这个逻辑，感谢。
