### ISSUE TITLE
FileTypeUtil.getType(）方法无法识别部分MP4格式文件

### ISSUE THREAD

**Issue by azhu949** [looly/hutool#1584]
### 版本情况

JDK版本：    jdk1.8.0_281
hutool版本： 5.6.5

### 问题描述
FileTypeUtil.getType(）方法无法识别文件头为0000001C66747970的MP4格式文件

1. 复现代码
            String fileHead = IoUtil.readHex28Upper(video.getInputStream());
            String type = FileTypeUtil.getType(video.getInputStream());

2. 堆栈信息
![image](https://user-images.githubusercontent.com/51523658/118749620-7739a500-b890-11eb-95b3-87723a09bc73.png)

3. 测试涉及到的文件（注意脱密）

https://user-images.githubusercontent.com/51523658/118749632-7ef94980-b890-11eb-8bf5-bcfdef5aa262.mp4

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/118836480-75a2c800-b8f6-11eb-8c44-dac11099fdbd.png)
这个视频是3gp的 不是mp4

**Comment by CherryRum** [comment]
细说一下吧，你传这个呢，的确也是mp4格式的
![image](https://user-images.githubusercontent.com/24296698/118837835-c36c0000-b8f7-11eb-8a62-67bb86166993.png)

```
00 00 00 1C 66 74 79 70 6D 70 34 32 00 00 00 01 ; ....ftypmp42....
69 73 6F 6D 6D 70 34 31 6D 70 34 32           ; mp41mp42isom

===================== 解析 =====================
00 00 00 1C: box长度28，包括这4个字节本身，即后面还有24个字节的box body;
66 74 79 70: ftyp, box type	
6D 70 34 32: mp42, major brand
00 00 00 01: 1,	Minor version
6D 70 34 31 6D 70 34 32 69 73 6F 6D: Compatible brands, isom (0X69736F6D),mp41 (0X6D703431), mp42 (0X6D703432),说明本文档遵从（或称兼容）mp41,mp42,isom三种协议。

可以自己进行判断，估计作者没考虑mp4的多种封装格式

**Comment by looly** [comment]
5.6.6加入。

你先可以putFileType方法把自定义类型放入。
