### ISSUE TITLE
List<T> 转成tree结构

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#1587]
看了您的tree相关方法如下：
/**
	 * 树构建
	 *
	 * @param <T>            转换的实体 为数据源里的对象类型
	 * @param <E>            ID类型
	 * @param list           源数据集合
	 * @param parentId       最顶层父id值 一般为 0 之类
	 * @param treeNodeConfig 配置
	 * @param nodeParser     转换器
	 * @return List
	 */
	public static <T, E> List<Tree<E>> build(List<T> list, E parentId, TreeNodeConfig treeNodeConfig, NodeParser<T, E> nodeParser) {
	}
期望的是：传进去的是一个对象list 期望返回的是排好序 并且是树形结构的对象list

**Comment by Pluto-Whong** [comment]
昨天刚提了这个相关的pr，然后就看到了你这个建议，坐等merge🤣

**Comment by joey-happy** [comment]
> 昨天刚提了这个相关的pr，然后就看到了你这个建议，坐等merge🤣

缘分啊 哈哈 这个需求还是挺普遍的 之前是自己写 也能实现 但是想起hutool来了 哈哈

**Comment by looly** [comment]
但是你需要定义：

1. 父Id的字段名称

**Comment by looly** [comment]
看到PR了，我不希望新建一个新的工具类，考虑方法加到TreeUtil。

**Comment by joey-happy** [comment]
> 但是你需要定义：
> 
> 1. 父Id的字段名称

构造树形结构用到的变量 可以实现你定义的接口获得 这样更灵活了

**Comment by joey-happy** [comment]
> 但是你需要定义：
> 
> 1. 父Id的字段名称

你可以定义一个接口 我们的实体类实现你的接口 然后复写你需要获得变量的方法 这样会更灵活

**Comment by joey-happy** [comment]
> 但是你需要定义：
> 
> 1. 父Id的字段名称

整个树形结构的关键 就是pid吧？你可以定义一个接口 我们的实体类实现你的接口 然后复写你需要获得变量的方法 这样会更灵活
