### ISSUE TITLE
关于 类 DateTime 和 Date 的问题

### ISSUE THREAD

**Issue by wh2887** [looly/hutool#1592]
在 Spring Data JPA 中传递 DateUtil 返回的结果作为参数，查询不到数据。
应该是日期格式的问题，请问有什么解决办法吗？
```java
findSomethingBy(Date startDate, Date endDate);
```
![DateUtil](https://user-images.githubusercontent.com/39092207/119108895-45bd0700-ba53-11eb-82e9-9156fe27460c.png)
![Date](https://user-images.githubusercontent.com/39092207/119108977-58cfd700-ba53-11eb-869c-b30400414fe0.png)

**Comment by linyuliu** [comment]
可以看下数据库吗

**Comment by wh2887** [comment]
> 可以看下数据库吗

已解决，是 JPA 写法的问题。自己坑自己。抱歉

![解决办法](https://user-images.githubusercontent.com/39092207/119122250-e7972080-ba60-11eb-8c62-ad23ea312f37.png)

**Comment by CherryRum** [comment]
没事，最近我的时间都用String 接的 数据库设计的太傻比了

**Comment by looly** [comment]
DateTime唯一覆盖的就是toString方法。
