### ISSUE TITLE
关于hutool-poi的乱码问题

### ISSUE THREAD

**Issue by yuyu414** [looly/hutool#1593]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.6.5

### 问题描述（包括截图）
使用了hutool-poi关于表格的导入导出，现在面临一个问题：我们的用户比较杂，他们电脑操作系统有的是win10、MacBook。然后他们的电脑的编码格式还不同，外加上有的使用微软的office、也有使用WPS。就导致了我们这边的导入导出乱码问题，主要是导入乱码的问题。
我看了源代码在解析表格的时候并没有关于表格的格式的处理。
希望得到的帮助：
1.可能是我没有找到，如果有希望帮我找一下Excelutil工具中获取表格文件编码格式的方法在哪里？
2.然后第一步完成之后，第二步需要按照编码读取。QQ群里小磊说的可以指定读取excel格式的方法出入参，但是很可惜 我也没找到这个方法，请告诉我在哪里？
 希望得到你们的帮助 谢谢~

**Comment by looly** [comment]
刚突然发现POI写出没有自定义编码的地方，Excel难道内部编码不是固定的？欢迎提供思路。

**Comment by yuyu414** [comment]
> 刚突然发现POI写出没有自定义编码的地方，Excel难道内部编码不是固定的？欢迎提供思路。
应该不是,创建excel的时候可以设置编码格式的。只不过使用的是默认，poi也有解析表格时候workSheet是可以设置解析的编码格式的

**Comment by looly** [comment]
我这边暂时没有找到相应的API。

**Comment by yuyu414** [comment]
> 我这边暂时没有找到相应的API。

好吧，那我只能周末学习一下官方的文档了，到时候在交流
