### ISSUE TITLE
URLUtil.normalize() 方法无效

### ISSUE THREAD

**Issue by libin-tech** [looly/hutool#1595]
### 版本情况

JDK版本：    java version "1.8.0_291"
hutool版本： 5.6.5

### 问题描述（包括截图）

1. 复现代码

```java
public static void main(String[] args) {
        String path = "https://repo1.maven.org/maven2//com/alibaba/fastjson/1.2.76/fastjson-1.2.76.jar";
        System.out.println("path：" + URLUtil.normalize(path));

        /**
         * hutool 官方例子
         */
        String url = "http://www.hutool.cn//aaa/bbb";
        // 结果为：http://www.hutool.cn/aaa/bbb
        String normalize = URLUtil.normalize(url);
        System.out.println("normalize：" + normalize);
    }
```

2. 控制台结果
path：https://repo1.maven.org/maven2//com/alibaba/fastjson/1.2.76/fastjson-1.2.76.jar
normalize：http://www.hutool.cn//aaa/bbb

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/38720407/119304169-73938d00-bc99-11eb-9bd3-aa9f491dba28.png)

**Comment by looly** [comment]
官网文档有问题。

hutool新版本对此规则做了修改：

按照之前逻辑。`//`是不规范的，但是按照URL规范，`//`是符合标准的，因此此处保留。

文档稍后修改。
