### ISSUE TITLE
IOS H5图片上传进过hutool工具类图片压缩后旋转90度

### ISSUE THREAD

**Issue by shuangpai** [looly/hutool#1598]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7

自带的有问题会旋转
Img.from(srcFile).scale(0.2f).write(destFile);

改成下边则不会旋转
 <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>0.4.8</version>
        </dependency>
Thumbnails.of(srcFile).scale(0.5f).toFile(destFile);

**Comment by shuangpai** [comment]
希望官方把这个问题解决了，就不需要引入其他包

**Comment by looly** [comment]
可能是个bug。

请升级到5.6.5试下。
