### ISSUE TITLE
CRC16 构造方法都是protected

### ISSUE THREAD

**Issue by hexw** [looly/hutool#1601]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
CRC16 构造方法都是protected ,无法初始化

1. 复现代码

new CRC16(new CRC16Modbus())

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.6.6修复此问题，感谢。
