### ISSUE TITLE
FileUtil对路径末尾有空格时处理出错

### ISSUE THREAD

**Issue by kpkym** [looly/hutool#1603]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
同样的路径，使用 FileUtil 时会修剪掉路径最后的空格。原因在于 FileUtil 的 normalize 方法使用了trim

1. 复现代码

```java
String dir = "/Desktop/test/abcd "; // 末尾有空格的文件夹
String path1 = FileUtil.getUserHomePath() + dir;
String path2 = "~" + dir;

System.out.println(new File(path1).exists()); // true
System.out.println(new File(path2).exists()); // false

new File(path1).listFiles(); // 正常
FileUtil.ls(path2); // 报错 找不到文件
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by kpkym** [comment]
第六行应该是
`System.out.println(FileUtil.file(path2).exists()); // false`

**Comment by looly** [comment]
5.6.7修复此问题，感谢。
