### ISSUE TITLE
[enhancement] 增强CollUtil功能

### ISSUE THREAD

**Issue by cqyisbug** [looly/hutool#1606]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6

希望添加以下方法
1. collectToList  
   收集集合中对象的某一属性为List
2. collectToSet
   收集集合中对象的某一属性为Set
3. collectToMap
   收集集合中对象的两个属性为map
4. groupBy
   按照对象的某一属性进行分组，返回Map<Key,List<T>>

我这边的话已经实现，不知道别人有没有这样的需求，如果能加到hutool中也是很好的

![1622176178019](https://user-images.githubusercontent.com/25382172/119929672-89ae8f80-bfb0-11eb-998d-bc37f7436c9b.jpg)

**Comment by weimo123** [comment]
这个很好呀

**Comment by CherryRum** [comment]
可以提交下 pr

**Comment by looly** [comment]
1. CollUtil.extract
2. 自行转一下set
3. CollUtil.toMap，用函数定义key和value，更加灵活
4. 同样可以用CollUtil.toMap，函数定义可以随意定制你的key和value
