### ISSUE TITLE
关于ssh这部分，有一个不一定会引起问题的坑，和作者说一下

### ISSUE THREAD

**Issue by reidzhou** [looly/hutool#1611]
我在项目里也用到了ssh，然后前段时间我模仿了你的代码在ssh模块里添加缓存池，也是用的WeakHashMap，然后测试环境就发生了OOM。
直接原因是堆里有大量的jsch的Session对象，没有被gc掉。
我看了代码，发现Session内部有一个类型为GlobalRequestReply的成员变量grr，它使用了当前线程作为成员变量，而且一般也是业务线程，所以只要当前线程不死，Session就不会被GC，然后WeakHashMap的key每次gc都会被回收，再次从缓冲池里获取session就会构建一个新Session，导致Session对象大量堆积。
![image](https://user-images.githubusercontent.com/34478469/120350535-a7258580-c331-11eb-926a-f95d9dd28e87.png)
考虑到Session的代码问题，我想到也许使用另外的线程来执行ssh的逻辑之后再关闭Session应该就可以被回收了，经过测试也确实是可以的。

所以关于ssh这部分，我大概有以下2点想法：
1. ssh的创建使用应当绑定额外线程，而不是当前的主要业务线程
2. 鉴于一个ssh session对应一个线程，而且session越多，所需要的线程越多，那么需要一个配置来限定session的数量上限

**Comment by looly** [comment]
嗯……新建线程确实不是很现实，没有研究过Jsch的源码，不知道这个全局线程有啥用。

Hutool新版本使用的是`new SimpleCache<>(new HashMap<>());`，使用了普通HashMap，然后手动关闭Session。

**Comment by looly** [comment]
欢迎提供更好的思路。

**Comment by reidzhou** [comment]
嗯，又再看了下，session的绑定线程只有一个地方有在操作
![image](https://user-images.githubusercontent.com/34478469/120413839-96a1f900-c38b-11eb-8e56-eb4fc4587b5a.png)
这个代码是在执行ssh -Q的操作的时候会触发，一般来说应用里也很难用到这个操作，所以好像也没有什么好担忧的地方。

GC部分也没有什么好办法，好在应用里的session一般也不会太多，也还能接受。
主要还是我对于WeakHashMap的理解太浅了。
