### ISSUE TITLE
我想加一套关于Class文件的Plus内容

### ISSUE THREAD

**Issue by gongxuanzhang** [looly/hutool#1612]
现在的Class不能获取注释内容。
我想加一套关于ClassPlus的内容 
代码已经实现，不知道hutool是否有意愿加相应工具， 如果有我可以提PR

**Comment by looly** [comment]
没看懂， Class编译后注释不是没了么？如何获取。

**Comment by gongxuanzhang** [comment]
https://github.com/dromara/hutool/issues/1612#issuecomment-852850229
原理是通过javadoc  可以获取javadoc注释，可以包装在如 class ClassPlus 中  
对于想魔改逆向工程的小伙伴很友好

**Comment by gongxuanzhang** [comment]
@looly 
可以参考此项目 
https://github.com/dnault/therapi-runtime-javadoc
