### ISSUE TITLE
SymmetricCrypto 增加 update 方法

### ISSUE THREAD

**Issue by xbkaishui** [looly/hutool#1613]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新

### 问题描述（包括截图）

1. SymmetricCrypto 增加 update 方法，用于生成rand 随机数，比如对于aes 算法中间过程可以当作随机数

**Comment by xbkaishui** [comment]
可以assign给我，我来改

**Comment by looly** [comment]
有什么思路么？欢迎提供pr
