### ISSUE TITLE
windows系统 访问共享目录路径文件出错

### ISSUE THREAD

**Issue by OwhCode** [looly/hutool#1614]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在使用hutool的其它工具的时候内部调用了FileUtil.normalize()方法。windows系统，参数是共享目录路径：“\\CCQ\....”。
但返回的格式为："\/CCQ/..."。
这样的格式无法访问到目标文件。
虽然注释中写了兼容Windows下的共享目录路径，但没用。

**Comment by looly** [comment]
FileUtil只能针对本地目录，不能针对共享目录，共享目录理论上是一种网络服务，Linux下叫Samba服务，因此不要用这个方法。
