### ISSUE TITLE
zip_slip漏洞

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [looly/hutool#162]
大家好,
奇虎360代码卫士团队在Hutool中发现了一个Zip_slip漏洞 . 详细信息如下：
![bsbcr75to x49xho fhah b](https://user-images.githubusercontent.com/39950310/45464038-50bb2780-b741-11e8-83e9-123e59e08081.png)
![image](https://user-images.githubusercontent.com/39950310/45464227-346bba80-b742-11e8-887c-e115396c6827.png)
可以看到并没有对zipEntry.getName()做任何校验就用于创建新的文件，如果恶意攻击者通过上传恶意zip文件（目录中带有../），可以覆盖项目中其他敏感文件或直接上传一句话木马。

                                                                                                                               奇虎360代码卫士团队

**Comment by looly** [comment]
4.1.12中修复此漏洞。十分感谢。
