### ISSUE TITLE
XXE漏洞

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [looly/hutool#163]
大家好：
奇虎360代码卫士团队发现Hutool团队中发现了XXE漏洞，详细信息如下：
![image](https://user-images.githubusercontent.com/39950310/45465336-4b60db80-b747-11e8-98da-b93dd5d4dc4d.png)
![image](https://user-images.githubusercontent.com/39950310/45465352-587dca80-b747-11e8-970f-5cee6ad24997.png)
可以看到程序解析xml没有做安全措施，如禁用外部实体等，会导致外部实体注入漏洞。

                                                                                                                                 奇虎360代码卫士团队

**Comment by looly** [comment]
感谢360团队指出的问题。此问题的解决在`createDocumentBuilder`方法中：

![image](https://user-images.githubusercontent.com/1432613/45466247-49008080-b74b-11e8-8e4c-01562c7b56b6.png)


其中`disableXXE`代码如下：

![image](https://user-images.githubusercontent.com/1432613/45466259-5fa6d780-b74b-11e8-9d03-5a1184c1d9c4.png)


参考：

[https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXP_DocumentBuilderFactory.2C_SAXParserFactory_and_DOM4J](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXP_DocumentBuilderFactory.2C_SAXParserFactory_and_DOM4J)

**Comment by QiAnXinCodeSafe** [comment]
是我疏忽了，这里确实不存在漏洞

**Comment by 360CodeSafe** [comment]
您好，我又看代码了disableXXE函数会返回一个安全的xml处理器，但是程序中并没有接收这个处理器啊。。。。
![default](https://user-images.githubusercontent.com/39950310/46660072-d4552080-cbe8-11e8-93e1-3607aa7beac9.png)
所以这里还是存在漏洞的
