### ISSUE TITLE
如何在Java程序中获取cron.setting定义的cron间隔？

### ISSUE THREAD

**Issue by angelyouyou** [looly/hutool#1635]
### 版本情况

JDK版本：    openjdk_8_271
hutool版本： 5.6.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在cron.setting定义如下的信息：
[com.xxx.detector.core.utils.monitor]
SystemMonitor.run = 0 */1 * * * ?

如何在Java程序中获取cron.setting定义的cron间隔，如1分钟还是2分钟？

1. 复现代码

NA

2. 堆栈信息
NA

3. 测试涉及到的文件（注意脱密）
NA

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
没法获得。

表达式是个复杂的任务时间定义，无法单独获得“间隔”。
