### ISSUE TITLE
建议Excel读取添加新的返回结构

### ISSUE THREAD

**Issue by spvycf** [looly/hutool#1638]
Excel读取-ExcelReader
此工具类是否可以添加一个返回列号的数据结构方法。
类似以下返回：
ExcelReader reader = ExcelUtil.getReader("d:/aaa.xlsx");
List<Map<Integer,Object>> readAll = reader.readAll();
Integer代表第几列。
因为业务中有些列标题千奇百怪。
此致，开源敬意！

**Comment by looly** [comment]
可以自行实现`CellHandler`完成。
