### ISSUE TITLE
转换bean的忽略字段大小写的问题

### ISSUE THREAD

**Issue by thinsstar** [looly/hutool#1641]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6

### 问题描述（包括截图）
所有涉及可以转换bean的方法,例如 json转bean 或 map转bean 或 xml转bean
当可设置忽略字段大小写时,只能忽略简单类型的字段,当字段也是bean或者是集合bean时,这时候大小写忽略就失效了

1. 复现代码

```java
public class User {
        private String name;
        private Level level;

        public static class Level {
                private String id;
                private String desc;
        }
}
```
```java
String json = "{"NAME":"NAME","LEVEL":{"ID":"ID","DESC":"DESC"}}"

User user = new BeanConverter<T>(User.class, CopyOptions.create().setIgnoreCase(true)).convert(json, null);
```

user对象的字段level里的字段全都为null

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
稍后测试。

**Comment by thinsstar** [comment]
BeanUtil.beanToMap
这个方法,bean里面字段也是bean的话,转化出来的map里面还是bean,应该都要转化成map吧

**Comment by looly** [comment]
BeanUtil没有多层转换，只能通过JSON方式转换。

json字符串转换只能是：

```java
JSONUtil.parseObj(jsonStr).toBean(xxxx);
```

BeanConverter无法解析JSON。

2是你的bean必须有getter和setter方法才能读取或者注入。

**Comment by thinsstar** [comment]
> BeanUtil没有多层转换，只能通过JSON方式转换。
> 
> json字符串转换只能是：
> 
> ```java
> JSONUtil.parseObj(jsonStr).toBean(xxxx);
> ```
> 
> BeanConverter无法解析JSON。
> 
> 2是你的bean必须有getter和setter方法才能读取或者注入。

复现代码使用了@Data,所以是有getter和setter的
但问题是json的转换不能忽略大小写呀,所以我才用了toBean里面的BeanConverter去转换
