### ISSUE TITLE
HttpRequest.httpVersion(HTTP_1_0),无法设置协议版本

### ISSUE THREAD

**Issue by tiancw829** [looly/hutool#1644]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.6.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
HttpRequest post = HttpUtil.createPost(this.url);
        HttpResponse resp = post.keepAlive(false)
                .httpVersion(HTTP_1_0)
                .method(Method.POST)
                .removeHeader(Header.ACCEPT_ENCODING)
                .removeHeader(Header.ACCEPT_LANGUAGE)
                .body(reqXML)
                .header(headers, true)
                .execute();
```

2. 堆栈信息
无报错
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
请求协议还是HTTP/1.1
![image](https://user-images.githubusercontent.com/45424930/121491857-eb3b1900-ca08-11eb-868f-fa8187fe197d.png)

**Comment by looly** [comment]
此方法用于关闭Keep-Aliave，无法修改请求的HTTP版本。
