### ISSUE TITLE
Ftp下载文件没有报错，也没有成功，调用方不知道是否下载成功

### ISSUE THREAD

**Issue by feitianmao2008** [looly/hutool#1646]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.9

### 问题描述
Ftp类下载文件的时候，即使下载失败了，也不会报错，调用方没有办法判断是否下载成功。如下图所示，箭头所指函数会返回boolean值的。

![image](https://user-images.githubusercontent.com/20870166/121621824-82eb4680-ca9f-11eb-9450-fd5ecc2df0ec.png)

**Comment by looly** [comment]
之前版本的cd命令有个bug，请升级到5.6.7尝试。

2. 考虑切换为主动模式尝试。
