### ISSUE TITLE
code qa

### ISSUE THREAD

**Issue by lnsane** [looly/hutool#1647]
https://github.com/dromara/hutool/blob/6ffc2cc29bdb49c40834bc01b35e6966e2c00b42/hutool-cache/src/main/java/cn/hutool/cache/impl/FIFOCache.java#L40

capacity  = 0  -> initialCapacity = 16
capacity  = 50  -> initialCapacity = 16
capacity  = 500  -> initialCapacity = 16
capacity  = 5000  -> initialCapacity = 39

why? 

Math.max(1 << 4, 3 >>> 7)  😵😵😵😵

**Comment by lnsane** [comment]
https://github.com/dromara/hutool/blob/6ffc2cc29bdb49c40834bc01b35e6966e2c00b42/hutool-cache/src/main/java/cn/hutool/cache/impl/FIFOCache.java#L43-L72

并发猛增，capacity 设置的不大的情况，就会读不到刚增加的数据 是这样的吗？😥😥😥😥😥😥

**Comment by looly** [comment]
这个初始大小设置确实不合理，5.7.0改为：

```java
cacheMap = new LinkedHashMap<>(capacity + 1, 1.0f, false);
```

关于并发猛增读取不到的情况，是不是加入太多超出capacity，导致被清理了？

**Comment by lnsane** [comment]
> 这个初始大小设置确实不合理，5.7.0改为：
> 
> ```java
> cacheMap = new LinkedHashMap<>(capacity + 1, 1.0f, false);
> ```
> 
> 关于并发猛增读取不到的情况，是不是加入太多超出capacity，导致被清理了？


感觉上这个地方有点不合理

https://github.com/dromara/hutool/blob/6ffc2cc29bdb49c40834bc01b35e6966e2c00b42/hutool-cache/src/main/java/cn/hutool/cache/impl/FIFOCache.java#L65-L70

并发高的情况下，很可能出现大量缓存失效的情况，但是把capacity设置0又显得太粗暴了。

**Comment by looly** [comment]
这个就要更高缓存策略了，比如使用LRUCache。
