### ISSUE TITLE
二维码生成异常

### ISSUE THREAD

**Issue by hl976440572** [looly/hutool#1648]
### 版本情况

JDK版本：   jdk1.8.0_221
hutool版本： 5.4.2

### 问题描述（包括截图）
批量生成 有时候会出现这种只有半张的二维码，另外一半是灰的。
![image](https://user-images.githubusercontent.com/29592294/122003491-c1596c00-cde5-11eb-8808-45015dc1b917.png)

1. 复现代码

```java
QrCodeUtil.generate( jsonObject.getStr("url"),
QrConfig.create().setImg(bg + File.separator + "logo.jpeg").setQrVersion(4).setWidth(2000).setHeight(2000),
FileUtil.file(file)
);
```

**Comment by nancheung** [comment]
是我吃过的那个马路边边吗

**Comment by looly** [comment]
升级到5.6.7试下，可能没有关闭流导致的？
