### ISSUE TITLE
HttpUtil不支持gzip

### ISSUE THREAD

**Issue by horizonzy** [looly/hutool#1649]
version: hutool-http:5.6.3

服务端开启了gzip压缩。当客户端设置请求头 **Accept-Encoding:gzip, deflate**时，对返回的response inputStream进行gzip转换时，提示inputStream的格式不是GZIP的格式。

用apache的httpclient没有该问题。

**Comment by looly** [comment]
检查下`Content-Encoding`头信息看是否是`gzip`，hutool根据这个头信息判断内容的类型。

如果是，麻烦贴下堆栈。

**Comment by looly** [comment]
而且`Accept-Encoding:gzip, deflate`是不需要手动设置的，自动识别的。

**Comment by horizonzy** [comment]
Ok, 我直接看数据是ok的，hutool自动帮忙解压了，牛皮。
