### ISSUE TITLE
core.io.FileUtil newerThan(File file,File reference)

### ISSUE THREAD

**Issue by Alvinyk** [looly/hutool#165]
原始实现为：
	public static boolean newerThan(File file, File reference) {
		if (null == file || false == reference.exists()) {
			return true;// 文件一定比一个不存在的文件新
		}
		return newerThan(file, reference.lastModified());
	}
我觉得应为：
	public static boolean newerThan(File file, File reference) {
		if (**_null == reference_** || false == reference.exists()) {
			return true;// 文件一定比一个不存在的文件新
		}
		return newerThan(file, reference.lastModified());
	}

**Comment by looly** [comment]
感谢意见，确认为bug，4.1.14修复此问题。

**Comment by Alvinyk** [comment]
感谢您的这个库，目前正在学习您的代码。
