### ISSUE TITLE
httprequest 通过账户密码代理请求https 返回407

### ISSUE THREAD

**Issue by carl-don-it** [looly/hutool#1650]
### 版本情况

JDK版本：   jdk1.8.0_271
hutool版本：5.5.7

### 问题描述（包括截图）

1. 复现代码

```java
//http没有问题
        HttpResponse execute = HttpRequest.get("http://www.gov.cn/")
                .setProxy(ProxyUtils.buildHttpProxy(ip, port))
                // .header("Proxy-Authorization", "Basic " + Base64Encoder.encode(ProxyUser+":"+ProxyPass))
                .basicProxyAuth(ProxyUser,ProxyPass)
                .execute();
//https有问题
        HttpResponse execute1 = HttpRequest.get("https://www.baidu.com/")
                .setProxy(ProxyUtils.buildHttpProxy(ip, port))
                // .header("Proxy-Authorization", "Basic " + Base64Encoder.encode(ProxyUser+":"+ProxyPass))
                .basicProxyAuth(ProxyUser,ProxyPass)
                .execute();
```

2. 堆栈信息
Exception in thread "main" cn.hutool.core.io.IORuntimeException: IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1164)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
	at com.dc.dmc.crawl.carl_don.ProxyTest.main(ProxyTest.java:49)
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2152)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1159)

**Comment by looly** [comment]
账号密码不对吧。

**Comment by carl-don-it** [comment]
http是对的

**Comment by looly** [comment]
试下这个方法：

https://www.jianshu.com/p/3278f96b6640

**Comment by carl-don-it** [comment]
已经用上了，不行

**Comment by carl-don-it** [comment]
已实现，property需要在调用htttpUrlConnection前设置

**Comment by looly** [comment]
好的~~

**Comment by Mr-LiuDC** [comment]
Oracle JDK 1.8

Hutool 5.7.21

我这边也遇到这个问题，确认账号密码正确。
HTTP正常，HTTPS就报 `Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"`。
```
@Test
public void testHttpRequestWithProxy() {
    System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
    String url = "https://api.ipify.org?format=json";
    String host = "";
    int port = 1111;
    String username = "";
    String password = "";
    HttpRequest httpRequest = new HttpRequest(url);
    httpRequest.setHttpProxy(host, port);
    httpRequest.basicProxyAuth(username, password);
    String body = httpRequest.execute().body();
    System.out.println(body);
}
```

**Comment by obiscr** [comment]
@Mr-LiuDC 请问这个问题解决了没？

**Comment by wjy000** [comment]
我也遇到这个问题, 问题并没有解决啊, 怎么就关闭了. 用户密码肯定正确, curl 测试正常, 用HttpUtil死活就是报407错误

**Comment by wjy000** [comment]
http链接没问题, 只有https会报这个错误

**Comment by looly** [comment]
@wjy000 嗯……不是每个问题都可以解决。关于代理验证问题，考虑到HttpUrlConnection对代理设置验证的局限性，Hutool也无能为力。

考虑更换HTTP Client。

**Comment by Mr-LiuDC** [comment]
@obiscr 我目前是这样处理的：
```
System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
Authenticator.setDefault(new Authenticator() {
    public PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(username, password.toCharArray());
    }
});

String url = "https://api.ipify.org/?format=json";
HttpResponse response = HttpUtil.createGet(url).setHttpProxy(host, port).execute();
Console.log(JSONUtil.toJsonPrettyStr(response.body()));
```

**Comment by obiscr** [comment]
@Mr-LiuDC 感谢，目前已经解决了。

**Comment by gaizi001** [comment]
> @obiscr 我目前是这样处理的：
> 
> ```
> System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
> Authenticator.setDefault(new Authenticator() {
>     public PasswordAuthentication getPasswordAuthentication() {
>         return new PasswordAuthentication(username, password.toCharArray());
>     }
> });
> 
> String url = "https://api.ipify.org/?format=json";
> HttpResponse response = HttpUtil.createGet(url).setHttpProxy(host, port).execute();
> Console.log(JSONUtil.toJsonPrettyStr(response.body()));
> ```

这个有效吗，我用了还是报错407
