### ISSUE TITLE
Db下的 query方法支持in吗?

### ISSUE THREAD

**Issue by hhiew** [looly/hutool#1652]
### 版本情况

JDK版本：    JDK1.8
hutool版本： 5.6.7

### 问题描述（包括截图）
query方法支持in吗?(有其他复杂的条件,使用entity不方便)
Db.use().queryOne("select * from hrmresource where ...其他复杂的条件 and id in (?)",new int[]{1,2,3});

**Comment by looly** [comment]
貌似不行，Hutool的处理方式是通过拼接完成:

```java
List<Entity> results = db.findAll(Entity.create("user")
				.set("id", new long[]{1, 2, 3}));
```

**Comment by looly** [comment]
5.7.1增加支持：

```java
List<Entity> results = db.query("select * from user where id in (:ids)",
				MapUtil.of("ids", new int[]{1, 2, 3}));
```
