### ISSUE TITLE
后续是否可以考虑对Phoenix的支持

### ISSUE THREAD

**Issue by GabrielXie** [looly/hutool#1656]
![image](https://user-images.githubusercontent.com/33001936/122151493-3e421f80-ce92-11eb-9264-2a121d38760a.png)

**Comment by GabrielXie** [comment]
![image](https://user-images.githubusercontent.com/33001936/122151983-17381d80-ce93-11eb-9ef6-68fc553d73ec.png)
我看到好像已经支持了

**Comment by GabrielXie** [comment]
我自己尝试了一下，已经支持了Driver，但是不支持其独特的语法，即**UPSERT INTO** 语法，会报如下异常
![image](https://user-images.githubusercontent.com/33001936/122178804-80cb2280-ceb9-11eb-92a1-fa9549626f2e.png)

**Comment by looly** [comment]
确实，没有针对此数据库做单独的方言。此issue保留，稍后我查下相关资料。

**Comment by GabrielXie** [comment]
phoenix基本语法里就插入和更新和mysql语法有区别，phoenix插入和更新语法都为**UPSERT INTO**
参考：
http://phoenix.apache.org/language/index.html#:~:text=upsert%20into%20test%20values('foo'%2C'bar'%2C3)%3Bupsert

![image](https://user-images.githubusercontent.com/33001936/122188298-69446780-cec2-11eb-906e-492e7f5ebbe1.png)

**Comment by looly** [comment]
5.7.2增加`PhoenixDialect`
