### ISSUE TITLE
工具类存在的问题hihi

### ISSUE THREAD

**Issue by whererose** [looly/hutool#1657]
hi非常感谢贡献出的工具类,在使用过程中发现如下的问题：

1.Month.of(Calendar.JANUARY).getLastDay(false);获取月份的最后一天；因每年的二月份比较特殊，有28天和29的区分，然而提供的方法名称无法区分是否获取的是当前年份月的最后一天。

2. Object result = converterRegistry.convert(String.class, ls); 类型转换问题；首先入参我指明了出参类型，但是接受参数类型仍然可以是非入参类型，是否进行强约束会更好一些。

**Comment by looly** [comment]
1. getLastDay的参数是否闰年已经区分了啊，闰年29天，非闰年28天。

2. 麻烦使用Convert.convert方法，指定了泛型。
