### ISSUE TITLE
POI模块，修改导致显示异常

### ISSUE THREAD

**Issue by sppan24** [looly/hutool#1659]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.7

### 问题描述（包括截图）

如果使用BigExcelWriter生成的Excel文件，再使用ExcelWriter对文件进行修改，会导致文件Excel格式单元格格式异常。

1. 复现代码

```java
// 生成文件
File file = new File("/Users/sppan/Desktop/tmp/100_.xlsx");
BigExcelWriter writer = ExcelUtil.getBigWriter(file);
writer.disableDefaultStyle();
List<List<String>> rows = Collections.singletonList(Arrays.asList("哈哈", "嘿嘿"));
writer.write(rows);
writer.flush();
writer.close();

// 修改文件
File file = new File("/Users/sppan/Desktop/tmp/100_.xlsx");
ExcelWriter writer = ExcelUtil.getWriter(file);
writer.disableDefaultStyle();
writer.writeCellValue(0, 0, "a");
writer.flush();
writer.close();
```

**Comment by sppan24** [comment]
xml中的内容：

![image](https://user-images.githubusercontent.com/15795173/122492242-fc42e600-d017-11eb-8382-be282a1148ad.png)

Excel显示情况：

![image](https://user-images.githubusercontent.com/15795173/122492374-37ddb000-d018-11eb-8cfe-32273ad43f75.png)

**Comment by looly** [comment]
可能时POI本身的bug，我找下看能解决不。

**Comment by looly** [comment]
5.7.2修复此问题，感谢。

原因其实在于POI，我猜可能算一个bug。

在使用BigWriter(SXSSF)模式写出数据时，单元格值为直接值，非引用值（is标签）。
而再使用ExcelWriter(XSSF)编辑时，会写出引用值，导致失效。

5.7.2采取比较极端的方法处理：先清空单元格值，再写出新的值。

```java
if(CellType.BLANK != cell.getCellType()){
	cell.setBlank();
}
```

**Comment by sppan24** [comment]
好的，为速度点赞

**Comment by Lemon-cxh** [comment]
> 

目前使用 BigWriter 导出数据时，因为 CellType 设置为空了，导致使用 ExcelUtil.readBySax 读取时，无法正确解析日期类型的单元格，解析出来变为天数数字了
