### ISSUE TITLE
[bug] StrUtil#toUnderlineCase  has no expect result

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#166]
1. sample code : 
```java
System.out.println(StrUtil.toUnderlineCase("isUPk"));
```
2. Expect result : `is_u_pk`
3. Run result : `is_UP_k`

**Comment by xkcoding** [comment]
PR #167 提示 CI 报错，重新提交 PR #168

**Comment by looly** [comment]
这块需要手动来了。针对UP缩写，专门做了这种识别。

**Comment by xkcoding** [comment]
但是 toUnderlineCase 这种需求，现在的好像是错误的，类似 `isUPk` 这种，转成下划线格式，正确的应该就是 `is_u_pk`

**Comment by looly** [comment]
之前我也是这么做得。但是is up k 和 is u pk 作为工具类如何能分清用户的意图？所以Hutool做得策略是isUPk把UP当作一个词。再举个例子：

isURL那你怎么办？因此特殊的转下划线考虑自行实现。

**Comment by xkcoding** [comment]
好吧。这个需求主要是应对数据库和 model 的转化，isURL 不算是标准的驼峰吧。。isUrl 才算，我只这么认为的 😄
