### ISSUE TITLE
TreeUtil ，在新版本中，最大递归深度未被控制

### ISSUE THREAD

**Issue by bingxue314159** [looly/hutool#1661]
### 版本情况

JDK版本：    jdk_8
hutool版本： 5.6.7

### 问题描述
TreeUtil，在V5.6.7、V5.7.1中，最大递归深度未被控制，生成的树会全量生成。在V5.6.3中则正常。

1. 复现代码

```java

    @Test
    public void testTree(){

        // 构建node列表
        List<TreeNode<String>> nodeList = CollUtil.newArrayList();
        for (int i = 0; i < 10; i++) {
            String id = i + "";
            String title = "第" + i + "级";
            String pid = null;
            if (i != 0) {
                pid = (i - 1 ) + "";
            }
            TreeNode td = new TreeNode<>(id, pid, title, id);
            nodeList.add(td);
        }


        //配置
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig();
        // 最大递归深度
        treeNodeConfig.setDeep(2);

        //转换器
        List<Tree<String>> treeNodes = TreeUtil.build(nodeList, null, treeNodeConfig,
                (treeNode, tree) -> {
                    tree.setId(treeNode.getId());
                    tree.setParentId(treeNode.getParentId());
                    tree.setWeight(treeNode.getWeight());
                    tree.setName(treeNode.getName());
                });

        String jsonStr = JSON.toJSONString(treeNodes);

        System.out.println("jsonStr = " + jsonStr);
    }
```

**Comment by looly** [comment]
5.7.2修复，感谢。

**Comment by bingxue314159** [comment]
> 5.7.2修复，感谢。

测试了下，V5.7.2版本跑出的结果和之前的不一样，V5.7.2的这个参数应该理解为：最大深度。V5.6.3版本的，应该理解为：最大递归次数。

`
    @Test
    public void testTree(){

        // 构建node列表
        List<TreeNode<String>> nodeList = CollUtil.newArrayList();
        for (int i = 0; i < 10; i++) {
            String id = i + "";
            String title = "第" + i + "级";
            String pid = null;
            if (i != 0) {
                pid = (i - 1 ) + "";
            }
            TreeNode td = new TreeNode<>(id, pid, title, id);
            nodeList.add(td);
        }


        //配置
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig();
        // 最大递归深度
        treeNodeConfig.setDeep(2);

        //转换器
        List<Tree<String>> treeNodes = TreeUtil.build(nodeList, null, treeNodeConfig,
                (treeNode, tree) -> {
                    tree.setId(treeNode.getId());
                    tree.setParentId(treeNode.getParentId());
                    tree.setWeight(treeNode.getWeight());
                    tree.setName(treeNode.getName());
                });

        String jsonStr = JSON.toJSONString(treeNodes);

        System.out.println("jsonStr = " + jsonStr);
    }
`


同样的代码，不同的结果：
V7.5.2
jsonStr = [{"id":"0","weight":"0","name":"第0级","children":[{"id":"1","parentId":"0","weight":"1","name":"第1级"}]}]

V5.6.3
jsonStr = [{"id":"0","weight":"0","name":"第0级","children":[{"id":"1","parentId":"0","weight":"1","name":"第1级","children":[{"id":"2","parentId":"1","weight":"2","name":"第2级"}]}]}]

**Comment by bingxue314159** [comment]
> 5.7.2修复，感谢。

测试了下，V5.7.2版本跑出的结果和之前的不一样，V5.7.2的这个参数应该理解为：最大深度。V5.6.3版本的，应该理解为：最大递归次数。

```java
    @Test
    public void testTree(){

        // 构建node列表
        List<TreeNode<String>> nodeList = CollUtil.newArrayList();
        for (int i = 0; i < 10; i++) {
            String id = i + "";
            String title = "第" + i + "级";
            String pid = null;
            if (i != 0) {
                pid = (i - 1 ) + "";
            }
            TreeNode td = new TreeNode<>(id, pid, title, id);
            nodeList.add(td);
        }


        //配置
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig();
        // 最大递归深度
        treeNodeConfig.setDeep(2);

        //转换器
        List<Tree<String>> treeNodes = TreeUtil.build(nodeList, null, treeNodeConfig,
                (treeNode, tree) -> {
                    tree.setId(treeNode.getId());
                    tree.setParentId(treeNode.getParentId());
                    tree.setWeight(treeNode.getWeight());
                    tree.setName(treeNode.getName());
                });

        String jsonStr = JSON.toJSONString(treeNodes);

        System.out.println("jsonStr = " + jsonStr);
    }
```


同样的代码，不同的结果：
V7.5.2
jsonStr = [{"id":"0","weight":"0","name":"第0级","children":[{"id":"1","parentId":"0","weight":"1","name":"第1级"}]}]

V5.6.3
jsonStr = [{"id":"0","weight":"0","name":"第0级","children":[{"id":"1","parentId":"0","weight":"1","name":"第1级","children":[{"id":"2","parentId":"1","weight":"2","name":"第2级"}]}]}]


后续版本应该以哪个为准？
