### ISSUE TITLE
hutool-db可以配合spring的@Transactional注解使用事务吗？

### ISSUE THREAD

**Issue by gamead** [looly/hutool#1667]
hutool-db可以配合spring的@Transactional注解使用事务吗？具体应该怎么配置呢？

**Comment by looly** [comment]
https://gitee.com/dromara/hutool/blob/v5-master/hutool-log/src/test/resources/logging.properties

https://gitee.com/dromara/hutool/tree/v5-master/hutool-log/src/test/resources

项目地址变更导致404了，稍后修复。

**Comment by gamead** [comment]
没看明白，能详细说说吗？@looly

**Comment by looly** [comment]
回复错了。Hutool不支持Spring的任何注解。
