### ISSUE TITLE
[功能建议]可以新加websocket客户端和简单服务端吗

### ISSUE THREAD

**Issue by nosiyBUGS** [looly/hutool#1669]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
websocket服务端需要与Tomcat之类的绑定使用，封装的意义不大。暂时不考虑。
