### ISSUE TITLE
BeanUtil.copy有bug

### ISSUE THREAD

**Issue by DrakenZeng** [looly/hutool#1674]
### 版本情况

JDK版本：   jdk1.8
hutool版本： 5.7.2

### 问题描述
beanutil数组类的json切割的时候，切割异常
导致转换失败

**Comment by linyuliu** [comment]
有例子吗

**Comment by DrakenZeng** [comment]
知道原因了
是我这边有个实体类有个list<Object>属性  拷贝的对象是String 
低版本是检测强制转换类型没有报错 ，高版本修复了 会报错没问题。
