### ISSUE TITLE
关于jwt加解密

### ISSUE THREAD

**Issue by chried** [looly/hutool#1677]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.7.2

### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/24580076/123362139-cb782900-d5a2-11eb-98e8-3f62269946f4.png)

拿到token，可以直接使用Base64.decodeStr()方法解密，都不需要密钥

**Comment by looly** [comment]
JWT本身就是明文传输的，密钥主要是用于验证信息是否被篡改而已。

见：http://www.ruanyifeng.com/blog/2018/07/json_web_token-tutorial.html
