### ISSUE TITLE
Excel 导出 设置行高无效

### ISSUE THREAD

**Issue by l745230** [looly/hutool#1678]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.2  
poi: 5.0.0

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/15940920/123362475-56f1ba00-d5a3-11eb-81c1-f7bf9518d6b5.png)

1. 复现代码

```java
        writer.setRowHeight(-1, 28);
        writer.setDefaultRowHeight(28);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

使用了两种方式设置都没有效果. 有数据的行高都是默认的.

**Comment by looly** [comment]
貌似是POI的问题……暂未找到合适的解决办法，欢迎提供思路。

**Comment by l745230** [comment]
@looly 尝试后发现在数据写入完成后,再对每一行设置行高,会生效.

![image](https://user-images.githubusercontent.com/15940920/123564397-eee1e480-d7eb-11eb-8eb6-fa889abb80be.png)
![image](https://user-images.githubusercontent.com/15940920/123564408-f5705c00-d7eb-11eb-8a34-4902aefee4f5.png)

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/123564431-0a4cef80-d7ec-11eb-860d-57ceff1f74b4.png)
