### ISSUE TITLE
DateUtil的问题

### ISSUE THREAD

**Issue by primejava** [looly/hutool#1680]
### 版本情况
hutool版本： 5.1.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        System.out.println(new Date());
        System.out.println(DateUtil.date());
        int result=DateUtil.compare(new Date(),DateUtil.date());
        System.out.println(result);
```
前两行代码注释与否，会影响result的值

**Comment by looly** [comment]
可能的原因：

DateUtil.date()构建需要传入timezone，第一次构建花的时间相对于new Date()比较长长，因此得出的时间会晚一点。

如果有前两行，部分方法被“预热”了，这个差异就几乎没有了。
