### ISSUE TITLE
excel使用别名时读取日期类型数据报错

### ISSUE THREAD

**Issue by lewis-wu** [looly/hutool#1682]
5.7.2版本，excel使用别名读取日期类型报错

        ExcelReader reader = ExcelUtil.getReader(excelStream, 0);
        reader.addHeaderAlias("生日", "birthday");
        List<EmployeeListDTO> emps = reader.read(1, 2, EmployeeListDTO.class);
excel表头如下
![image](https://user-images.githubusercontent.com/49868257/123544101-4187b600-d784-11eb-8241-0ee0d9ae29a3.png)

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/123549683-9505fe00-d79c-11eb-8a36-6414c7ea74d3.png)
并没有发现什么问题，请您检查时间格式，核实实体类

**Comment by looly** [comment]
麻烦提供下报错的excel和实体类、测试代码等。

**Comment by lewis-wu** [comment]
Poi读取工具类

package com.dustess.vhr.common.util;

import cn.hutool.core.io.IoUtil;
import cn.hutool.poi.excel.ExcelBase;
import cn.hutool.poi.excel.ExcelReader;
import cn.hutool.poi.excel.ExcelUtil;
import cn.hutool.poi.excel.ExcelWriter;
import com.dustess.vhr.client.dto.emp.EmployeeListDTO;

import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;

/**
 * @author Wu 
 * @version 1.0
 * @date 2021/6/26 19:31
 */
public class PoiUtil {

    public static void employee2Excel(List<EmployeeListDTO> emps, OutputStream out) {
        ExcelWriter writer = ExcelUtil.getWriter(true);
        writer.renameSheet(0,"员工表");
        addHeaderAliasForEmployee(writer);
        writer.merge(32, "员工基本信息",true);
        writer.write(emps, true);
        writer.flush(out,true);
        writer.close();
        IoUtil.close(out);
    }

    public static void employee2Excel(List<EmployeeListDTO> emps, File excelFile) {
        ExcelWriter writer = ExcelUtil.getWriter(excelFile);
        writer.renameSheet(0,"员工表");
        addHeaderAliasForEmployee(writer);
        writer.merge(32, "员工基本信息",true);
        writer.write(emps, true);
        writer.close();
    }

    public static List<EmployeeListDTO> excel2Emps(InputStream excelStream) {
        ExcelReader reader = ExcelUtil.getReader(excelStream, 0);
        addHeaderAliasForEmployee(reader);
        List<EmployeeListDTO> emps = reader.read(1, 2, EmployeeListDTO.class);
        reader.close();
        return emps;
    }

    public static List<EmployeeListDTO> excel2Emps(File excelFile) {
        ExcelReader reader = ExcelUtil.getReader(excelFile, 0);
        addHeaderAliasForEmployee(reader);
        List<EmployeeListDTO> emps = reader.read(1, 2, EmployeeListDTO.class);
        reader.close();
        return emps;
    }



    private static void addHeaderAliasForEmployee(ExcelBase<?> excelBase) {
        if(excelBase instanceof  ExcelWriter){
            ExcelWriter writer=(ExcelWriter) excelBase;
            writer.renameSheet(0,"员工表");
            writer.addHeaderAlias("id", "id");
            writer.addHeaderAlias("workId", "工号");
            writer.addHeaderAlias("name", "姓名");
            writer.addHeaderAlias("gender", "姓别");
            writer.addHeaderAlias("birthday", "生日");
            writer.addHeaderAlias("idCard", "身份证号");
            writer.addHeaderAlias("wedlock", "婚姻状况");
            writer.addHeaderAlias("nativePlace", "籍贯");
            writer.addHeaderAlias("email", "电子邮箱");
            writer.addHeaderAlias("phone", "手机号");
            writer.addHeaderAlias("address", "联系地址");
            writer.addHeaderAlias("tiptopDegree", "最高学历");
            writer.addHeaderAlias("specialty", "所学专业");
            writer.addHeaderAlias("school", "毕业院校");
            writer.addHeaderAlias("workAge", "工作年限");
            writer.addHeaderAlias("workState", "是否在职");
            writer.addHeaderAlias("engageForm", "聘用形式");
            writer.addHeaderAlias("beginDate", "入职日期");
            writer.addHeaderAlias("conversionTime", "转正时间");
            writer.addHeaderAlias("notWorkDate", "离职时间");
            writer.addHeaderAlias("contractTerm", "合同期限");
            writer.addHeaderAlias("beginContract", "合同起始时间");
            writer.addHeaderAlias("endContract", "合同终止时间");
            writer.addHeaderAlias("politicsName", "政治面貌");
            writer.addHeaderAlias("nationName", "民族");
            writer.addHeaderAlias("departmentName", "部门");
            writer.addHeaderAlias("jobLevelName", "职称");
            writer.addHeaderAlias("posName", "职位");

            writer.addHeaderAlias("departmentId", "部门id");
            writer.addHeaderAlias("jobLevelId", "职称id");
            writer.addHeaderAlias("posId", "职位id");
            writer.addHeaderAlias("politicId", "政治面貌id");
            writer.addHeaderAlias("nationId", "民族id");
        }

        if (excelBase instanceof ExcelReader) {
            ExcelReader reader =(ExcelReader) excelBase;
            reader.addHeaderAlias("id", "id");
            reader.addHeaderAlias("工号", "workId");
            reader.addHeaderAlias("姓名", "name");
            reader.addHeaderAlias("姓别", "gender");
            reader.addHeaderAlias("生日", "birthday");
            reader.addHeaderAlias("身份证号", "idCard");
            reader.addHeaderAlias("婚姻状况", "wedlock");
            reader.addHeaderAlias("籍贯", "nativePlace");
            reader.addHeaderAlias("电子邮箱", "email");
            reader.addHeaderAlias("手机号", "phone");
            reader.addHeaderAlias("联系地址", "address");
            reader.addHeaderAlias("最高学历", "tiptopDegree");
            reader.addHeaderAlias("所学专业", "specialty");
            reader.addHeaderAlias("毕业院校", "school");
            reader.addHeaderAlias("工作年限", "workAge");
            reader.addHeaderAlias("是否在职", "workState");
            reader.addHeaderAlias("聘用形式", "engageForm");
            reader.addHeaderAlias("入职日期", "beginDate");
            reader.addHeaderAlias("转正时间", "conversionTime");
            reader.addHeaderAlias("离职时间", "notWorkDate");
            reader.addHeaderAlias("合同期限", "contractTerm");
            reader.addHeaderAlias("合同起始时间", "beginContract");
            reader.addHeaderAlias("合同终止时间", "endContract");
            reader.addHeaderAlias("政治面貌", "politicsName");
            reader.addHeaderAlias("民族", "nationName");
            reader.addHeaderAlias("部门", "departmentName");
            reader.addHeaderAlias("职称", "jobLevelName");
            reader.addHeaderAlias("职位", "posName");

            reader.addHeaderAlias("部门id", "departmentId");
            reader.addHeaderAlias("职称id", "jobLevelId");
            reader.addHeaderAlias("职位id", "posId");
            reader.addHeaderAlias("政治面貌id", "politicId");
            reader.addHeaderAlias("民族id", "nationId");
        }

    }

    public static void main(String[] args) {
        List<EmployeeListDTO> emps = excel2Emps(new File("员工表.xlsx"));
        System.out.println(emps);
    }
}

实体类

package com.dustess.vhr.client.dto.emp;

import java.util.Date;

/**
 * @author Wu 
 * @version 1.0
 * @date 2021/6/20 21:40
 */
public class EmployeeListDTO {
    private Integer id;

    private String name;

    private String gender;

    private Date birthday;

    private String idCard;

    private String wedlock;

    private Integer nationId;

    private String nativePlace;

    private Integer politicId;

    private String email;

    private String phone;

    private String address;

    private Integer departmentId;

    private Integer jobLevelId;

    private Integer posId;

    private String engageForm;

    private String tiptopDegree;

    private String specialty;

    private String school;

    private Date beginDate;

    private String workState;

    private String workId;

    private Double contractTerm;

    private Date conversionTime;

    private Date notWorkDate;

    private Date beginContract;

    private Date endContract;

    private Integer workAge;

    private String politicsName;

    private String nationName;

    private String departmentName;

    private String jobLevelName;

    private String posName;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getWedlock() {
        return wedlock;
    }

    public void setWedlock(String wedlock) {
        this.wedlock = wedlock;
    }

    public Integer getNationId() {
        return nationId;
    }

    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    public String getNativePlace() {
        return nativePlace;
    }

    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    public Integer getPoliticId() {
        return politicId;
    }

    public void setPoliticId(Integer politicId) {
        this.politicId = politicId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Integer getJobLevelId() {
        return jobLevelId;
    }

    public void setJobLevelId(Integer jobLevelId) {
        this.jobLevelId = jobLevelId;
    }

    public Integer getPosId() {
        return posId;
    }

    public void setPosId(Integer posId) {
        this.posId = posId;
    }

    public String getEngageForm() {
        return engageForm;
    }

    public void setEngageForm(String engageForm) {
        this.engageForm = engageForm;
    }

    public String getTiptopDegree() {
        return tiptopDegree;
    }

    public void setTiptopDegree(String tiptopDegree) {
        this.tiptopDegree = tiptopDegree;
    }

    public String getSpecialty() {
        return specialty;
    }

    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public String getWorkState() {
        return workState;
    }

    public void setWorkState(String workState) {
        this.workState = workState;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public Double getContractTerm() {
        return contractTerm;
    }

    public void setContractTerm(Double contractTerm) {
        this.contractTerm = contractTerm;
    }

    public Date getConversionTime() {
        return conversionTime;
    }

    public void setConversionTime(Date conversionTime) {
        this.conversionTime = conversionTime;
    }

    public Date getNotWorkDate() {
        return notWorkDate;
    }

    public void setNotWorkDate(Date notWorkDate) {
        this.notWorkDate = notWorkDate;
    }

    public Date getBeginContract() {
        return beginContract;
    }

    public void setBeginContract(Date beginContract) {
        this.beginContract = beginContract;
    }

    public Date getEndContract() {
        return endContract;
    }

    public void setEndContract(Date endContract) {
        this.endContract = endContract;
    }

    public Integer getWorkAge() {
        return workAge;
    }

    public void setWorkAge(Integer workAge) {
        this.workAge = workAge;
    }

    public String getPoliticsName() {
        return politicsName;
    }

    public void setPoliticsName(String politicsName) {
        this.politicsName = politicsName;
    }

    public String getNationName() {
        return nationName;
    }

    public void setNationName(String nationName) {
        this.nationName = nationName;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getJobLevelName() {
        return jobLevelName;
    }

    public void setJobLevelName(String jobLevelName) {
        this.jobLevelName = jobLevelName;
    }

    public String getPosName() {
        return posName;
    }

    public void setPosName(String posName) {
        this.posName = posName;
    }
}

这个excel表的数据是假数据，不存在数据隐私的问题。
在不使用别名，即将日期列的标题行改为与实体类的属性名一致时，读取数据不报错。

**Comment by looly** [comment]
@lewis-wu 麻烦再提供下假数据的excel，可能是时间格式的问题。

**Comment by lewis-wu** [comment]
[员工表.xlsx](https://github.com/dromara/hutool/files/6780972/default.xlsx)




> @lewis-wu 麻烦再提供下假数据的excel，可能是时间格式的问题。

不好意思，我当时直接用邮件回复的，邮件中有这excel表附件，但github上却没有。我在这儿重新上传一份。

**Comment by CherryRum** [comment]
您好，您的生日格式是yyyy/m/d h:mm 可能需要转化一下格式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月8日(周四) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] excel使用别名时读取日期类型数据报错 (#1682)




 
员工表.xlsx
  
@lewis-wu 麻烦再提供下假数据的excel，可能是时间格式的问题。
  
不好意思，我当时直接用邮件回复的，邮件中有这excel表附件，但github上却没有。我在这儿重新上传一份。

**Comment by lewis-wu** [comment]
> 您好，您的生日格式是yyyy/m/d h:mm 可能需要转化一下格式
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月8日(周四) 上午10:14 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [dromara/hutool] excel使用别名时读取日期类型数据报错 (#1682) 员工表.xlsx @lewis-wu 麻烦再提供下假数据的excel，可能是时间格式的问题。 不好意思，我当时直接用邮件回复的，邮件中有这excel表附件，但github上却没有。我在这儿重新上传一份。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我这里不使用别名，将生日标题行的改为英文的“birthday"就能正常读取，我并没有做额外的格式转换。
![excel-birthday](https://user-images.githubusercontent.com/49868257/124863521-c75bfa80-dfe9-11eb-877a-5b01a012c318.png)
![emp-birthday](https://user-images.githubusercontent.com/49868257/124863533-cc20ae80-dfe9-11eb-81c3-c0390df09eb4.png)

**Comment by CherryRum** [comment]
抱歉，今天才有时间，大概看了下
1、你真的有点坑，这个并不是生日那个别名造成的
2、原因是你的，你的离职时间，在excel并不全，所以导致类型转换失败
![image](https://user-images.githubusercontent.com/24296698/125103565-0e8fdb80-e10f-11eb-8693-1b437a5858d8.png)

**Comment by looly** [comment]
@CherryRum 哈哈，真是有心了~~

**Comment by CherryRum** [comment]
> @CherryRum 哈哈，真是有心了~~

哈哈、事情要有头有尾呀

**Comment by lewis-wu** [comment]
非常感谢 @CherryRum
