### ISSUE TITLE
ExcelWriter是否可以增加一个清空数据的功能

### ISSUE THREAD

**Issue by rillzhang** [looly/hutool#1684]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
ExcelWriter是否可以增加一个清空数据的功能？如果对excel文件操作过，再写入，目前只能先删除文件再操作。是否可以增加一个清空的功能。
1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
清空不好使，推荐先判断文件是否存在，然后直接删除即可。
