### ISSUE TITLE
ExcelUtil.readBySax()读取1万行的excel时RowHandler的handle方法不执行

### ISSUE THREAD

**Issue by dustyou** [looly/hutool#1685]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
ExcelUtil.readBySax()读取从网上下载的excel文件时rowhandler的handle方法不执行
1. 复现代码
rowhandler的构造方法执行, 但handle方法不执行,
打开excel修改并保存后, 再次解析可执行handle方法;
```java
ExcelUtil.readBySax(file, 0, new CustomRowHandler(customObject));


@Override
    public void handle(int sheetIndex, long rowIndex, List<Object> rowList) {
        log.info("rowhandler");
        if (rowIndex == 0) {
            deal with header;
            return;
        }
        deal with body;
        }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by dustyou** [comment]
> excel文件5000行左右时handle方法正常执行, 文件达到1万行时

rowhandler

**Comment by dustyou** [comment]
把第二个参数改为-1后可正常读取
ExcelUtil.readBySax(file, -1, new CustomRowHandler(customObject));

**Comment by looly** [comment]
sax方式默认使用rid，很多生成的excel这个rid和index不一样，所以读不到。

考虑可以传字符串的sheet名称。
