### ISSUE TITLE
两个Bean属性互转同时用@Alias;  BeanUtil.toBean() 就不生效

### ISSUE THREAD

**Issue by tb-bear** [looly/hutool#1687]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/18545839/123745056-4793a900-d8e2-11eb-9ffc-28a1f33dfdc9.png)

###不生效的原因

两个实体类
SysUserFb
```
@Data
public class SysUserFb implements Serializable {

    private static final long serialVersionUID = 1L;

    @Alias("depart")
    private String depId;

    @Alias("orgId")
    private String customerId;
}
```

SysUser
```
@Data
public class SysUser implements Serializable {

    private static final long serialVersionUID = 1L;

    @Alias("depId")
    private Long depart;

    private Long orgId;
}
```

进行互转:
```
 SysUser sysUser = BeanUtil.toBean(sysUserFb, SysUser.class);
```
转换出来的结果并没有
SysUser中的depart 并没有赋值; 而 SysUser中的orgId却成功赋值了; 

这个功能挺实用; 但不能两个Bean同时写@Alias

**Comment by looly** [comment]
问题出在你的别名：

`SysUserFb`加上注解后`depId`变成`depart`了，SysUser的`depart`变成`depId`，然后Hutool从`SysUserFb`中找名字为`depId`的字段，找不到，自然是null。

还有补救办法，就是使用`CopyOptions`

```java
final CopyOptions copyOptions = CopyOptions.create().setFieldMapping(
	MapUtil.builder("depart", "depId").build()
);
BeanUtil.toBean(sysUserFb, SysUser.class, copyOptions);
```

**Comment by tb-bear** [comment]
### 首先感谢作者的及时回复； 

### 目前采用的解决方案
只在`SysUserFb` 中用`@Alias`;  这样转换的话就没问题； 
反过来转的话 一般都是查询后取值赋予其他变量； 
如果用`Copyptions`进行补救的话 就丢失了使用`@Alias`的便捷性；相当于两个地方（SysUserFb, CopyOptions ）都进行维护了

**Comment by looly** [comment]
是。但是别名不是真的别名，而是改了名字。

这个无法完全做到双名字兼容。
