### ISSUE TITLE
Could not initialize class cn.hutool.crypto.SmUtil

### ISSUE THREAD

**Issue by Jugol7** [looly/hutool#1689]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.7.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

 Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class cn.hutool.crypto.SmUtil

1. 复现代码

SmUtil.sm4().decrypt(data);

2. 堆栈信息

![image](https://user-images.githubusercontent.com/48045783/123761855-cb569100-d8f4-11eb-891e-8df184e4ef24.png)

**Comment by looly** [comment]
需要引入BC库的。具体见文档：https://hutool.cn/docs/#/crypto/%E5%9B%BD%E5%AF%86%E7%AE%97%E6%B3%95%E5%B7%A5%E5%85%B7-SmUtil

**Comment by linyuliu** [comment]
建议运行时检测下用户导入包的情况
貌似POI就检查了吧
