### ISSUE TITLE
Excel导出,设置列别名,如果数据源无别名对应字段,Excel不会导出此列

### ISSUE THREAD

**Issue by l745230** [looly/hutool#1690]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.2 

### 问题描述（包括截图）

1. 复现代码

```java
 Map<Object, Object> row1 = new LinkedHashMap<>();
        row1.put("name", "张三");
        row1.put("age", 33);
//        row1.put("email", "33@qq.com"); // 查询条件过滤后的数据源,刚好这几个用户的邮箱都未设置,邮箱无返回值

        Map<Object, Object> row2 = new LinkedHashMap<>();
        row2.put("name", "李四");
        row2.put("age", 44);
//        row2.put("email", "44@qq.com");

        List<Map<Object, Object>> rows = CollUtil.newArrayList(row1, row2);

        ExcelWriter writer = ExcelUtil.getWriter();

        writer.setOnlyAlias(true);

        writer.addHeaderAlias("name", "姓名");
        writer.addHeaderAlias("age", "年龄");
        writer.addHeaderAlias("email", "邮箱");

        writer.merge(3 - 1, "标题");

        writer.write(rows, true);

        response.setContentType("application/vnd.ms-excel;charset=utf-8");
        response.setHeader("Content-Disposition","attachment;filename=test.xls");
        ServletOutputStream out=response.getOutputStream();

        writer.flush(out, true);
        writer.close();
        IoUtil.close(out);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

![image](https://user-images.githubusercontent.com/15940920/123912917-31ecb500-d9b0-11eb-9d5f-a817071110ad.png)

正常导出都是3列.  但是测试反馈如果查询条件过滤出来的用户没有设置邮箱,  则导出会少了一列.  
还有就是3列的时候,值如果没取到的情况下,那个单元格默认的黑色边框也没有了,能不能未获取到值的情况下默认给个空字符串.
大佬,能优化下嘛.

**Comment by PisecesPeng** [comment]
@l745230  你好!
`ExcelWriter. write()`[注释说明](https://github.com/dromara/hutool/blob/e5e6500116d30d202f14f259da94dc6c17720463/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelWriter.java#L831)
我个人认为这不是一个问题, `this.headerAlias`仅记录名称的映射, 也许并不能作为`列`输出.
但如你所说, 这是个常见的场景 @looly .

**Comment by l745230** [comment]
@PisecesPeng 

 ```
Map<Object, Object> row1 = new LinkedHashMap<>();
        row1.put("name", "张三");
        row1.put("age", 33);
// 别名列如果第一行的值没取到,即使后面行有值也不会输出,这一列都不会生成
//        row1.put("email", "33@qq.com"); 

        Map<Object, Object> row2 = new LinkedHashMap<>();
        row2.put("name", "李四");
        row2.put("age", 44);
        row2.put("email", "44@qq.com");

```

昨天我以为是这一列都没值导致列头不会生成.   今天又试了了下,发现只要是第一行没值,及时后面行有值也不会输出.

**Comment by xlgo** [comment]
如果你设置成  null 会怎么样呢？ 
正常不会你这么玩吧！都是循环输出的。
人家说了 根据第一行，没数据就扔个 空串或者 null 。
约定优先
@l745230

**Comment by PisecesPeng** [comment]
> @PisecesPeng
> 昨天我以为是这一列都没值导致列头不会生成. 今天又试了了下,发现只要是第一行没值,及时后面行有值也不会输出.

没错, `ExcelWriter`类中包含了许多[isFirstRow校验](https://github.com/dromara/hutool/blob/e5e6500116d30d202f14f259da94dc6c17720463/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelWriter.java#L853)

**Comment by l745230** [comment]
@xlgo 数据源的接口是第三方提供的,不是标准的矩形阵列.  对方返回的json应该是配置了值为空,就过滤掉.

**Comment by xlgo** [comment]
@l745230 那就搞个java bean  。

**Comment by l745230** [comment]
> @l745230 那就搞个java bean 。

这并不是个很好的解决方案. 临时解决还行. 如果每个导出都要去写个javabean 并不现实.

而且在说来回,配置了HeaderAlias与OnlyAlias. 是可以作为列头的依据的.

依赖数据源第一行的值来处理列,应该是有优化的空间的.

如果数据源返回的列表是空的,一个列列都不生成了. 表格里就剩下自己定义的标题了. 这就与数据源是否标准矩形没有关系了.

我不知道你们是怎么用的,没有中文列头的需求还是说每个导出都写javabean(我还没去验证这个方案是否可行).

**Comment by xlgo** [comment]
map 才是不友好的。。。
或许，你换个  比如  exsyexcel  看看

**Comment by looly** [comment]
这么设计是优化写出。

举个例子，你有1000条数据，也就是一千个Map，如果我不按照第一行来写出列名，就需要遍历所有行来取字段的“并集”，这样效率非常低。

所以如果对标题和数据输出有要求，可以调用writeLine按照行写出。

**Comment by l745230** [comment]
@looly 

这中文列头的需求不是个非常常见的场景吗.
从目前的结果来看,
1.数据源为空,导出Excel连列头都不生成
2.按数据源第一行的Map来生成列,这个逻辑也是值得斟酌. 如果没有配置列头这么处理没问题. 但是都配置了HeaderAlias与OnlyAlias, 这列头取哪些字段都已经明确了,不需要``` 需要遍历所有行来取字段的“并集” ```.

相比于英文列头导出, 中文列头的导出才是主流用法吧?

另外有点没弄明白,这个github的issues提出的问题,是作者回复下就关掉的吗? 是为了关单子而关单子吗?  作为问题的提出者,我感觉我并没有疑问得到解决,莫名其妙的的单子就被关了.

PS:1.没找到writeLine这个方法. 2.如果标题跟数据都自己来输出了,何必多此一举调用hutool的poi,直接用Apache poi生成就行了.
本来是想用成熟的工具导出,减少自己写BUG, 结果调完了,发现踩了个坑,解决不了,换个工具. 体验很差.

![image](https://user-images.githubusercontent.com/15940920/124205892-ce2fcc80-db14-11eb-89a6-27aae93dcb0a.png)
一个老用户想说,勿忘初心.

**Comment by looly** [comment]
@l745230

1. 按照首行识别原则，数据为空，表头不打印没问题。
2. 这是对数据写出方式理解的不同而已。我们最早设想的别名类似于字典表，它是兼容多种bean结构的，贸然的写出所有头信息，改变了这种“字典”性质的作用。onlyAlias只是针对没有配置别名的情况。具体举个例子：

```java
user{
     String name;
     int      age;
     String gende;
}

user2{
    String name;
    int      age;
    String address;
}
```

写出两个用户信息到Excel，我们定义name、age、gender、address，如果全字段写出标题，那和实际的bean非常不符，hutool设想的场景是我只需配一套alias，即可兼容`user`和`user2`。

这样还有个好处是，却字段了可以新建一个Bean把缺的字段补上，但是全部写出，你就要重新写一遍alias来减少字段。

再者，这个逻辑已经持续多个版本，为了考虑到向下兼容，也不会做变更。

PS1：这个确实是我回复错了，是writeRow方法，单独写出行。

3. 关于issue的关闭问题，和开发者的习惯有关。我的习惯是：一般问答类问题我认为解释清楚了就关闭了，如果你不明白可以再打开这个issue或者新建一个issue，个人不太喜欢在一个issue下讨论一大堆东西，这会让搜索到这个issue想寻找答案的用户很苦恼（用户耐心有限），如果想详细讨论，可以加Hutool的QQ群找我私聊讨论。

有这个习惯的另一个原因是，很多用户提完issue后就找不到了，你回复他并不会回来回复你，及时关闭也是避免这种无效issue的方式，希望理解。

说实话，Hutool对POI的封装相对比较简单，只是从数据层面，你会发现一旦涉及合并单元格或者样式问题，非常难用，远不如原生POI方便。

**Comment by l745230** [comment]
```
/**
     * 列头对应关系 [字段,别名]
     */
    private Map<String, String> headMap = new LinkedHashMap<>();

/**
     * 写入Excel数据
     *
     * @param writer
     * @param list       数据源
     * @param fileName   文件名
     */
    private void writeExcel(ExcelWriter writer, List<Map<String, Object>> list, String fileName) {
        // 写入标题
        writer.merge(this.headMap.size() - 1, fileName);

        // 写入列头
        List headList = new ArrayList();
        this.headMap.forEach((key, value) -> headList.add(value));

        writer.writeHeadRow(headList);

        // 写入数据
        int rowIndex = 1;
        int colIndex;
        for (Map<String, Object> map : list) {
            rowIndex++;
            colIndex = -1;

            for (String headKey : headMap.keySet()) {
                colIndex++;

                Object value = map.get(headKey);
                writer.writeCellValue(colIndex, rowIndex, value);
            }
        }
    }
```

自行解析输出单元格内容.   前人栽树后人乘凉.
