### ISSUE TITLE
版本： 5.7.3    然后代码使用了：   EqualsBuilder  发现出错

### ISSUE THREAD

**Issue by perfect5085** [looly/hutool#1692]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

EqualsBuilder

![image](https://user-images.githubusercontent.com/865936/124105068-6f773e00-da95-11eb-8906-71a5acd5571e.png)

设置完之后，没有直接 return，还会继续执行： ArrayUtil.equals....
这里是比较数组，肯定要报错。

**Comment by looly** [comment]
已合并：https://github.com/dromara/hutool/pull/1694
