### ISSUE TITLE
数据库工具在Flink中使用时出现的异常

### ISSUE THREAD

**Issue by GabrielXie** [looly/hutool#1693]
首先Hutool添加的这个数据库工具对于非Spring项目来说非常友好，个人认为很不错，但是在结合大数据组件Flink使用的过程中，发现了一些问题，不知道是我使用问题还是hutool本身的问题，在尝试多种方案后仍然无果，望作者和大佬们能够提供一些帮助。

。。。。。。。

**Comment by GabrielXie** [comment]
是我的问题

**Comment by looly** [comment]
哈哈，可以把问题以及解决问题思路放上来，大家一起分享。

**Comment by GabrielXie** [comment]
Flink 中如果使用hutool的工具类需要把数据源的定义作为类对象定义 (最好封装进单独的工具类)，而不能在map/filter等算子中去定义，flink在启动时会根据并行度启动多个算子，可能还有flink自己的关闭开启机制会影响hutool中对数据源连接的开启关闭，导致连接数过多。

异常截图

![124142897-394db480-dabd-11eb-8ae4-979b6903d6a1](https://user-images.githubusercontent.com/33001936/124160573-fa285f00-dace-11eb-90c6-6c4de11506f0.png)

正确的做法：
```
类 {
 statis 数据源定义

env初始化
source 算子 {

}
transform 算子 {
  // 数据源的使用
}

sink 算子 {
  // 数据源的使用

}
```

错误的做法：
```
类 {

env初始化
source 算子 {
}

transform 算子 {
   // 数据源定义
  // 数据源的使用
}

sink 算子 {
   // 数据源定义
  // 数据源的使用

}
```

大概就是这么个意思
