### ISSUE TITLE
图片编辑功能，图片切割后，留有黑边

### ISSUE THREAD

**Issue by lichaoliu** [looly/hutool#1695]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.3
### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/20872105/124408985-02f08d80-dd7a-11eb-8488-18c4e8f2cdf2.png)
![image](https://user-images.githubusercontent.com/20872105/124409012-13086d00-dd7a-11eb-92b7-b74c6a3b1079.png)

1. 复现代码
`        Img.from(FileUtil.file("C:\\Users\\rrc\\Desktop\\c.jpg"))
                .cut(0, 0, 21)//
                .write(FileUtil.file("C:\\Users\\rrc\\Desktop\\d.jpg"));`

**Comment by looly** [comment]
切割圆形后生成图片格式为jpg，是不透明的，因此背景色 默认给成了黑色。你可以：

1. 将输出格式定为png

**Comment by lichaoliu** [comment]
jpg本身不支持透明？
用png确实好了

**Comment by lichaoliu** [comment]
`Img.from(new URL("http://team.zqcf718.com/qdicon.png?e=1912408283&token=Lix9HHSQrTTVYqLG3aaUvJPNB3uBoz9GtxCqMS5G:0HpmID8xJNR1Tt9Z_Snse19WRUU=")).scale(50, 50).write(FileUtil.file("C:\\Users\\rrc\\Desktop\\ccc.png"));`
为啥压缩图片又出现黑边了。这次用的是png

**Comment by looly** [comment]
![ccc](https://user-images.githubusercontent.com/1432613/124800135-e164f100-df87-11eb-84b2-379df23e7b9a.png)

我测试为啥没有黑边呢？确实是透明的啊。

**Comment by lichaoliu** [comment]
![ccc](https://user-images.githubusercontent.com/20872105/124850895-0e3ef580-dfd4-11eb-9690-0135583d067c.png)
执行上面代码，图片这样。不透明啊。

**Comment by lichaoliu** [comment]
> ![ccc](https://user-images.githubusercontent.com/1432613/124800135-e164f100-df87-11eb-84b2-379df23e7b9a.png)
> 
> 我测试为啥没有黑边呢？确实是透明的啊。
![ccc](https://user-images.githubusercontent.com/20872105/124851019-4b0aec80-dfd4-11eb-9211-beb3da330e8d.png)
执行上面代码，图片这样，不透明啊

**Comment by lichaoliu** [comment]
> ![ccc](https://user-images.githubusercontent.com/1432613/124800135-e164f100-df87-11eb-84b2-379df23e7b9a.png)
> 
> 我测试为啥没有黑边呢？确实是透明的啊。

![ccc](https://user-images.githubusercontent.com/20872105/124851058-5f4ee980-dfd4-11eb-8de4-223ec587c8d5.png)
执行上面代码，图片这样，不透明啊

**Comment by lichaoliu** [comment]
![ccc](https://user-images.githubusercontent.com/20872105/124851110-7b528b00-dfd4-11eb-90bc-b4a215191055.png)

**Comment by lichaoliu** [comment]
![ccc](https://user-images.githubusercontent.com/20872105/124851165-945b3c00-dfd4-11eb-81b8-0cdb3e2cd616.png)
执行完这样，不透明啊

> ![ccc](https://user-images.githubusercontent.com/1432613/124800135-e164f100-df87-11eb-84b2-379df23e7b9a.png)
> 
> 我测试为啥没有黑边呢？确实是透明的啊。

**Comment by looly** [comment]
@lichaoliu 咱俩结果不一致，检查下hutool版本问题。
