### ISSUE TITLE
hutool-poi 合并单元格填充content不起作用

### ISSUE THREAD

**Issue by lxldemon** [looly/hutool#1696]
ExcelWriter writer = ExcelUtil.getWriter();
 writer.merge(index, index + temps.size() - 1, 0, 0, "**9999**", true);

**9999 导出后无法再excel 单元格出现**
<dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.3.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-schemas</artifactId>
            <version>4.1.2</version>
        </dependency>

**Comment by lxldemon** [comment]
<dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.3.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-schemas</artifactId>
            <version>4.1.2</version>
        </dependency>

**Comment by lxldemon** [comment]
`public class HutoolPoiTest {

    public static void main(String[] args) {
        //通过工具类创建writer
        ExcelWriter writer = ExcelUtil.getWriter("d:/writeTest2123.xlsx");
        List<Map<String,Object>> list = initData();
        writer.addHeaderAlias("xmnf", "项目年份");//1

        //合并单元格后的标题行，使用默认标题样式
        writer.merge(7, "测试标题");
        writer.merge(3, 4, 0, 0, "9999", true);
        writer.write(list, true);
        writer.close();

    }

    private static List<Map<String, Object>> initData() {
        List<Map<String,Object>> list = new ArrayList<>();
        Map<String,Object> map = new HashMap<>();
        map.put("xmnf","2020");
        list.add(map);

        Map<String,Object> map1 = new HashMap<>();
        map1.put("xmnf","2020");
        list.add(map1);

        Map<String,Object> map2 = new HashMap<>();
        map2.put("xmnf","2019");
        list.add(map2);

        return list;
    }
}`

**Comment by looly** [comment]
貌似是POI中引用值造成的问题，怀疑是POI的bug，暂时可以这么解决：

```java
List<Map<String,Object>> list = new ArrayList<>();
Map<String,Object> map = new HashMap<>();
map.put("xmnf","2021");
list.add(map);

Map<String,Object> map1 = new HashMap<>();
map1.put("xmnf",new XSSFRichTextString("9999"));
list.add(map1);

Map<String,Object> map2 = new HashMap<>();
map2.put("xmnf","2019");
list.add(map2);

//通过工具类创建writer
FileUtil.del("d:/test/writeTest2123.xlsx");
ExcelWriter writer = ExcelUtil.getWriter("d:/test/writeTest2123.xlsx");
writer.addHeaderAlias("xmnf", "项目年份");//1

//合并单元格后的标题行，使用默认标题样式
writer.merge(7, "测试标题");
writer.merge(3, 4, 0, 0, new XSSFRichTextString("9999"), true);
writer.write(list, true);
writer.close();
```
