### ISSUE TITLE
添加sm2 加密与js互相转换示例

### ISSUE THREAD

**Issue by luanxuechao** [looly/hutool#1698]
你好，我在做hutool里sm2加密和nodeJS互相转换加解密，遇到许多问题，后来解决了，现在添加了一个代码示例，可以加到readme里吗？
这是代码repo:
https://github.com/luanxuechao/hutool-js-sm2-demo

**Comment by linyuliu** [comment]
大概看了下 你遇见的问题是der编码和sm2不同规范的问题

https://github.com/dromara/hutool/issues/1388

**Comment by luanxuechao** [comment]
对的，我也是参考了那个PR来做的，后面发现问题在，所以提供了一个完整示例让大家参考，看issue太慢了

**Comment by CherryRum** [comment]
遇见问题第一下应该找下 规范看看，sm2就是个ecc加密的一种实现方式，定义了一堆（一条椭圆曲线，qs分量等等）

**Comment by looly** [comment]
@luanxuechao 可以升级hutool到5.7.3试下哦，那个issue之后我对几种密钥格式做了兼容：

私钥：可以使用PKCS#8、D值或PKCS#1规范

公钥：可以使用X509、Q值或PKCS#1规范
