### ISSUE TITLE
Props替代Properties提示不可序列化异常

### ISSUE THREAD

**Issue by jiangjialiang918** [looly/hutool#1701]
### 5.2.0

JDK版本：    openjdk_8_291
hutool版本： 5.2.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/22257945/124726487-63312c00-df40-11eb-9bfb-b3dbf579665b.png)

1. 复现代码

```java
Props props = new Props("test.properties");
FlinkKafkaConsumer<EventTracking> consumer = new FlinkKafkaConsumer<>("event_tracking", new EventDeserializationSchema(),kafkaProps);
DataStream<EventTracking> stringDataStream = env.addSource(consumer).name("kafkaEventTracking");
```

![WX20210707-163205](https://user-images.githubusercontent.com/22257945/124727159-097d3180-df41-11eb-8c6e-bf769adf836c.png)

**Comment by looly** [comment]
5.7.4修复此问题，Charset对象没有实现序列化接口，添加transient关键字。
