### ISSUE TITLE
关于标准化路径的疑问

### ISSUE THREAD

**Issue by NoErla** [looly/hutool#1703]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.4

### 问题描述（包括截图）
```java
String path = "../a/b.csv";
CsvReader reader = CsvUtil.getReader();
reader.read(ResourceUtil.getUtf8Reader(path), C.class);
//ResourceUtil.getUtf8Reader()会调用FileUtil.normalize把路径处理成a/b.csv导致无法正确识别文件
```

**Comment by looly** [comment]
确实是个问题，原因是normalize无法处理上级路径导致的，举个例子：

`a/../b`处理后是`b`，`..`抵消了上级目录`a`，但是`..`出现在路径开头，就无法抵消了，也把`..`丢失了。

5.7.5修复此问题，会保留开头的`..`。

暂时的解决办法是尽量避免开头使用`../`的路径。

ResourceUtil默认读取classpath路径，你使用`../`就是跳出classpath了，此时考虑使用File或者绝对路径。
