### ISSUE TITLE
文档示例有问题

### ISSUE THREAD

**Issue by cocobolor** [looly/hutool#1707]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

此处文档示例写错了,出来的效果不是图示效果,这个size应该拿内部的map的size.
![QQ图片20210713153028](https://user-images.githubusercontent.com/29691396/125410221-46d53980-e3ef-11eb-8eb0-a04aa7dbe3dc.png)

**Comment by looly** [comment]
确实，稍后修正，感谢。
