### ISSUE TITLE
HttpUtil 不能正常获取响应头

### ISSUE THREAD

**Issue by chenxuebing2** [looly/hutool#1709]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

 spring-boot项目启动后，使用HttpUtil 访问接口，前十次可正常获取到响应头里面的Set-Cookie，第十一次之后响应依然正常，但无法获取到响应头中的Set-Cookie

1. 复现代码
![image](https://user-images.githubusercontent.com/17702812/125444402-311b3ec5-a642-437c-8ed6-c4d1578d9a4c.png)

**Comment by looly** [comment]
第一次请求后，会记录Cookie，然后后续请求附带Cookie，因此服务端就不再发送Cookie了。你可以请求时disableCookie方法关闭Cookie记录。
