### ISSUE TITLE
`RegexPool`能否增加BASE64字符串的格式校验正则？

### ISSUE THREAD

**Issue by wangliang181230** [looly/hutool#1710]
如题

**Comment by looly** [comment]
5.7.5增加：

Base64.isBase64方法。

**Comment by wangliang181230** [comment]
好的，谢谢，静待发布。

**Comment by wangliang181230** [comment]
@looly v5.7.5
Base64.isBase64方法，校验的不是很严格啊，如长度必须是4的倍数，“=”（等于号）只会出现在字符串末尾两位等等。

**Comment by wangliang181230** [comment]
@looly 另外，Base64字符集似乎有些问题？
![图片](https://user-images.githubusercontent.com/1527893/126130980-6e9b7c6a-974d-4bee-837b-b3ecc32d5d39.png)

**Comment by looly** [comment]
先回答问题吧：

1. '-'和'_'是URL安全的Base64使用的字符，所以此处需要加入。

2. 没检查长度是因为Base64.encode的时候是可选是否补充‘=’的，不补充情况下貌似不是4的倍数。

3. -2是表示'='所在位置的值，表示padding。

**Comment by wangliang181230** [comment]
> 
> 
> 先回答问题吧：
> 
>     1. '-'和'_'是URL安全的Base64使用的字符，所以此处需要加入。
> 
>     2. 没检查长度是因为Base64.encode的时候是可选是否补充‘=’的，不补充情况下貌似不是4的倍数。
> 
>     3. -2是表示'='所在位置的值，表示padding。

哦，明白了。

那实际上，只需要再添加:
1. 末尾存在‘=’时，长度必须为4的倍数。
2. '='必须连续出现在末尾，且最多两个。
是吧？

**Comment by looly** [comment]
是滴。isBase64我是从apache commons中copy过来的，确实没判断末尾=。

**Comment by wangliang181230** [comment]
> 
> 
> 是滴。isBase64我是从apache commons中copy过来的，确实没判断末尾=。

好的。
那下个版本是否再添加一个严格校验位数和'='的方法呢？如果末尾存在'='的话

**Comment by looly** [comment]
4的倍数这个暂时不加了，原因是：

根据apache commons的逻辑，空白符也算在内了（例如换行符），这样4的倍数统计就会出错

我先补充一下等号的吧。

**Comment by wangliang181230** [comment]
好的。

**Comment by wangliang181230** [comment]
https://gitee.com/easyj-projects/easyj/blob/develop/core/src/main/java/icu/easyj/core/util/Base64Utils.java
我自己写了个Base64Utils，在判断String类型的数据时，直接判断字符，似乎性能更高一些。

对应的测试类：
https://gitee.com/easyj-projects/easyj/blob/develop/core/src/test/java/icu/easyj/core/util/Base64UtilsTest.java

```
Base64UtilsTest.testIsBase64():
cost  easyj: 19099600
cost hutool: 33779500
```

**Comment by wangliang181230** [comment]
额，似乎在java 11中，性能又不一样了。
![图片](https://user-images.githubusercontent.com/1527893/126251896-f85f7d39-97eb-4024-a263-0520010090dc.png)
