### ISSUE TITLE
SystemUtil.getUserInfo()获取的Name后面带/斜杠

### ISSUE THREAD

**Issue by OAFROG** [looly/hutool#1711]
用版本5.5.9获取的系统当前登录用户的名字是没问题的。
但是升级到5.7.4后获取的用户名后面都带一个斜杠 /

System：macos 10.14.6
jdk：1.8

**Comment by linyuliu** [comment]
5.6.4之后统一末尾使用'/'
SystemUtil.getUserInfo()中所有平台路径统一末尾加/（issue#I3NM39@Gitee）
[https://gitee.com/dromara/hutool/issues/I3NM39](url)

**Comment by looly** [comment]
> 5.6.4之后统一末尾使用'/'
> SystemUtil.getUserInfo()中所有平台路径统一末尾加/（issue#I3NM39@Gitee）
> [https://gitee.com/dromara/hutool/issues/I3NM39](url)

Good job!

**Comment by dianbaiyizhong** [comment]
所以呢？为什么再加个斜杠
