### ISSUE TITLE
CronPattern文档注释在vscode中显示有问题

### ISSUE THREAD

**Issue by anaer** [looly/hutool#1712]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
vscode中, CronPattern文档注释显示有问题, strong标签有的正常, 有的显示成**了, 试了下, \</strong\>标签后 带个空格, 可以正常显示.

1. 复现代码
![image](https://user-images.githubusercontent.com/4637100/125757672-8f7fba97-b56a-4d99-82d5-1e4a436ecb86.png)

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
嗯……这并不算问题，或者这是VSCode插件的bug吧。

5.7.5我加个空格吧……
