### ISSUE TITLE
关于 ip 地址获取错误问题

### ISSUE THREAD

**Issue by grallcd** [looly/hutool#1717]
JDK版本：    jdk1.8.0_221
hutool版本： 5.7.5

问题：调用 hutool-core 中的 NetUtil.getLocalhostStr() 方法获取本机 ip 地址返回的一直是回环地址 127.0.0.1，发现该方法由 issue#428 提供的，不知道在 Windows 下是否是正确，如下，实际上是应该返回 10.0.3.114 的，却返回了 127.0.0.1:
```java
@Test
public void testIp(){
	LinkedHashSet<String> ipList = NetUtil.localIps();
	// [ 10.0.3.114, 127.0.0.1...]

	InetAddress localhost = NetUtil.getLocalhost();
        // xxx-MacBook-Pro.local/127.0.0.1

	String localhostStr = NetUtil.getLocalhostStr();
        // 127.0.0.1	
}
```

修改如下，发现主要区别就是 getLocalhost() 方法中，isSiteLocalAddress() 的判断这里,如果是否的话，是不会返回本地地址的。
```java
public static String getLocalInetAddressStr() {
	return getLocalInetAddress().getHostAddress();
}

public static InetAddress getLocalInetAddress() {
		InetAddress candidateAddress = null;
		Enumeration<NetworkInterface> enums;
		try {
			enums = NetworkInterface.getNetworkInterfaces();
			while (enums.hasMoreElements()) {
				NetworkInterface networkInterface = enums.nextElement();
				for (Enumeration<InetAddress> addressEnums = networkInterface.getInetAddresses(); addressEnums.hasMoreElements(); ) {
					InetAddress inetAddress = addressEnums.nextElement();
					// 排除回环地址
					if (inetAddress.isLoopbackAddress()) {
						continue;
					}
					// 如果是本地网站地址，则返回
					if (inetAddress.isSiteLocalAddress()) {
						return inetAddress;
					}
					// 若不是，则记录下候选
					if (candidateAddress == null) {
						candidateAddress = inetAddress;
					}
				}
			}
			// 最终没找到本地网站地址，则返回候选方案
			return candidateAddress == null ? InetAddress.getLocalHost() : candidateAddress;
		} catch (Exception e) {
			throw new UtilException("Get InetAddress error!");
		}
	}
```

**Comment by looly** [comment]
不对啊，你确定使用的是5.x版本么？

![image](https://user-images.githubusercontent.com/1432613/126496375-f2251696-4170-4319-8974-95bccfe8cf18.png)

**Comment by grallcd** [comment]
![WechatIMG24](https://user-images.githubusercontent.com/54536224/126578982-c1f8a25d-c5e6-4abe-9e04-c52cbbfbea79.jpeg)

<img width="844" alt="image" src="https://user-images.githubusercontent.com/54536224/126579050-a35c8e4f-bd64-4229-92c4-11284f839c0d.png">


确定版本是最新版的，你可以直接 debug 跑一下，你会发现该方法最后走的都是 flag2 那里，而 InetAddress.getLocalHost() 方法在 linux 和 Windows 下是有区别的，linux 下只会获取到 127.0.0.1,根本不适合在生产环境使用。

**Comment by looly** [comment]
看到你两个地址：
10.0.3.114, 127.0.0.1，这两个地址都被识别为site local address，导致执行到了flag2部分，flag2部分是JDK本身提供的方法。

这样的逻辑来自于：https://github.com/dromara/hutool/issues/428

PS：127.0.0.1在内网地址存在情况下确实不应该返回，这块我加端逻辑修改下优先级吧。

5.7.6修改，感谢。
