### ISSUE TITLE
没有找到UUID

### ISSUE THREAD

**Issue by Chen-kaiyuan** [looly/hutool#1718]
### 版本情况

JDK版本：    jdk 1.8.0_291
hutool版本： 5.7.5

### 问题描述（包括截图）

1. 复现代码

```java
public String getUUID(){ return RandomUtil.randomUUID}
```
![image](https://user-images.githubusercontent.com/17740259/126583652-6777ce54-4e7b-45cf-9fef-aeb97ff17eb3.png)
![image](https://user-images.githubusercontent.com/17740259/126583687-dde55ebf-c842-4a22-a414-e7363d9e8b68.png)

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
无
在官方文档上看到可支持UUID
但是，在使用的时候没有找到方法，
在代码中，也没有看到
https://github.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/util/RandomUtil.java

**Comment by anaer** [comment]
IdUtil.fastUUID()

**Comment by Chen-kaiyuan** [comment]
> IdUtil.fastUUID()

Thanks♪(･ω･)ﾉ
