### ISSUE TITLE
hutool-db文档和新版本好像都对不上了

### ISSUE THREAD

**Issue by luo201227** [looly/hutool#172]
最近在使用hutool-db模块的自定义配置文件创建数据源时发现已经和文档上的方式已经不同了，文档大佬们是不是考虑更新一下？另外：使用DSFactory创建出来的数据源后，可以直接使用Db.use()执行相关SQL语句吗？

**Comment by looly** [comment]
1、文档部分哪里对不上麻烦截个图~~我也会再排查一遍。
2、Db.use()可以直接使用DataSource

![image](https://user-images.githubusercontent.com/1432613/46447384-13800d80-c7b4-11e8-824f-9b07456f8e2e.png)
