### ISSUE TITLE
FileTypeUtil判断bmp文件类型的问题

### ISSUE THREAD

**Issue by letcodeff** [looly/hutool#1720]
FileTypeUtil判断bmp文件类型时，为什么不是只要是424d开头的都判定为bmp文件？
是不是只要FILE_TYPE_MAP.put("424d", "bmp"); 这样就好了？

**Comment by looly** [comment]
magic header增加长度是为了减少误判，可以考虑增加自定义头。

```java
FileTypeUtil.putFileType
```
