### ISSUE TITLE
Convert.chineseToNumber()有BUG 处理十到二十的结果全是个位数

### ISSUE THREAD

**Issue by wssy001** [looly/hutool#1726]
### 版本情况

JDK版本：    openjdk "11.0.11"
hutool版本： 5.7.5
### 问题描述（包括截图）
数字转换（汉字转阿拉伯数字）处理 十一，十二之类的会有BUG
![QQ截图20210726131053](https://user-images.githubusercontent.com/22979223/126936326-9f308235-592f-428c-95c2-25ff58251b5e.png)

1. 复现代码

```java
int a = Convert.chineseToNumber("十一");
```

**Comment by looly** [comment]
确认bug。

按照正常逻辑：
```java
// 11
int a = Convert.chineseToNumber("一十一");
```

5.7.6增加逻辑修复这个bug，同时支持”百二“为”120“，”千二“为“1200”这类简称。
