### ISSUE TITLE
JSONObject处理 "null" 字符串的坑

### ISSUE THREAD

**Issue by ZYHPRO** [looly/hutool#1728]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
下面代码中的json，在进行载入解析后，通过跟中提示，会显示 "null", 但是通过 bodyjson.toString() 输出来，却是 null ,现在已经确认是 json解析库的问题，我现在已经换成了 fastjosn,同样的 json串载入解析，一切正常

1. 复现代码
  JSONObject bodyjson =  JSONUtil.parseObj({
            "device_model": null,
            "device_status_date": null,
            "imsi": null,
            "act_date": "2021-07-23T06:23:26.000+00:00"})

**Comment by ZYHPRO** [comment]
第一次使用 hutool ，掉到 null 处理的坑里面，发现了就提交一下，完善上

**Comment by looly** [comment]
不带包装的null解析后是JSONNull对象，toString后是"null"，但是这个特殊对象默认输出JSON字符串还是null；

你可以试下：

```java
// class cn.hutool.json.JSONNull
bodyjson.get("device_model").getClass()
```

在Hutool中，JSONNull是个特殊的对象，他用于标识用户提供了key，但是值是null的情况。

如果你想忽略这个null，可以：

```java
JSONObject bodyjson = JSONUtil.parseObj("{\n" +
				"            \"device_model\": null,\n" +
				"            \"device_status_date\": null,\n" +
				"            \"imsi\": null,\n" +
				"            \"act_date\": \"2021-07-23T06:23:26.000+00:00\"}", true, true);
```

后两个Boolean参数分别代表忽略null和有序。

**Comment by looly** [comment]
此处我也发现了一个改进点：

```java
JSONObject bodyjson = JSONUtil.parseObj("{\n" +
				"            \"device_model\": null,\n" +
				"            \"device_status_date\": null,\n" +
				"            \"imsi\": null,\n" +
				"            \"act_date\": \"2021-07-23T06:23:26.000+00:00\"}");
bodyjson.getConfig().setIgnoreNullValue(true);
Console.log(bodyjson.toString());
```

在以前版本中无法去除null的字段，在5.7.6中改进这里可以二次设置去除null值的字段。
