### ISSUE TITLE
文档中的错字

### ISSUE THREAD

**Issue by YoungTakhin** [looly/hutool#1734]
### 版本情况

hutool版本： 5.7.6

### 问题描述（包括截图）

参考文档文档中 ***RobotUtl增加getDelay、getRobot方法***，其中***RobotUtl***是否漏写了一个字母”i“？

**Comment by looly** [comment]
文档中没找到，貌似这个工具类没写文档，请问哪里看到的？

**Comment by anaer** [comment]
指的CHNAGELOG.md吧
![image](https://user-images.githubusercontent.com/4637100/127584549-7f4e6ac7-f936-4b89-bd3e-f701cf1209a1.png)

**Comment by looly** [comment]
哈哈，明白了，谢谢。

**Comment by YoungTakhin** [comment]
是的，就是这里
