### ISSUE TITLE
connectionTimeout和timeout设置

### ISSUE THREAD

**Issue by niujianya** [looly/hutool#1738]
HttpGlobalConfig必须设置timeout和connectionTimeout一样，分开设置不可以吗？

> 
	/**
	 * 默认连接超时
	 */
	private int connectionTimeout = HttpGlobalConfig.timeout;
	/**
	 * 默认读取超时
	 */
	private int readTimeout = HttpGlobalConfig.timeout;

**Comment by looly** [comment]
这样设置是为了简单。

你可以在HttpRequest对象中手动调用`setConnectionTimeout`和`setReadTimeout`放啊分别自定义。

**Comment by niujianya** [comment]
config是全局配置吧，用httpRequest.set的话那是不是每次request的时候都得set？
@looly
