### ISSUE TITLE
金额大写问题

### ISSUE THREAD

**Issue by wangyiqing1991** [looly/hutool#1739]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当金额为亿元整的时候有问题
![image](https://user-images.githubusercontent.com/88300962/127800199-c11f9b6b-8bf5-40f7-8314-d0594e981e1e.png)
![image](https://user-images.githubusercontent.com/88300962/127800211-dd561997-63fd-4c05-b0e2-a368b1e29288.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by wangyiqing1991** [comment]
不应该是两亿零元整而应该是两亿元整

**Comment by looly** [comment]
5.7.7修复此问题，感谢。
