### ISSUE TITLE
使用GET方式请求https接口 通过请求体body传参 自动变成POST方式

### ISSUE THREAD

**Issue by dingsuo** [looly/hutool#1740]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
定义的是get请求，在真实发送时已经转变成了post请求
现象：
如果是正常GET请求，则返回缺少AccessToken参数提示
如果是POST请求，则会返回“404 page not found”，目前推测是转换成了POST请求

```java
Console.log(HttpRequest.get("https://ad.oceanengine.com/open_api/2/advertiser/info/").body("{\"advertiser_ids\":[1690657248243790,1696557412560013,1696829196924936]}").execute().body());
    
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
原因来自于`HttpsUrlConnection`，当`setDoOutput(true)`时，默认将所有GET请求转换为POST请求，导致某些严格的服务端出现404问题。

此问题只出现在https请求中，解决办法暂时未找到，此issue保留。

**Comment by xyz327** [comment]
最好还是 GET 请求不要带 request body

**Comment by looly** [comment]
> 最好还是 GET 请求不要带 request body

Rest请求无论GET还是其他，都需要带Body，这个绕不过的。

**Comment by looly** [comment]
找到了问题线索：

`sun.net.www.protocol.http.HttpURLConnection`在`getOutputStream0`方法中很自作多情的”帮助用户“把GET请求换成了POST请求。

![image](https://user-images.githubusercontent.com/1432613/128958120-d3104530-e7d6-440a-9f7d-b7a077e9f832.png)

**Comment by looly** [comment]
这个问题除了重新实现HttpUrlConnection外没有别的办法了，考虑更换HttpClient吧。

**Comment by zhyusgethup** [comment]
get请求带body 太不按照http协议的规范了吧
