### ISSUE TITLE
使用JSONUtil对象转字符串时，Long类型的字段前端会丢失精度

### ISSUE THREAD

**Issue by xiaoke1301** [looly/hutool#1744]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.7.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

可不可以加一下自定义类型转换，可以自定义配置将Long类型转换为字符串类型

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Long本身有长度限制吧，太长会溢出。考虑使用BigDecimal

**Comment by xiaoke1301** [comment]
> ### 版本情况
> JDK版本： jdk1.8
> hutool版本： 5.7.6（请确保最新尝试是否还有问题）
> 
> ### 问题描述（包括截图）
> 1. 复现代码
> 
> 可不可以加一下自定义类型转换，可以自定义配置将Long类型转换为字符串类型
> 

不好意思哈，可能是没有描述清楚，比如后台返回的json格式：{id:1349625084474417153}，但是前端拿到的是{id:1349625084474417100}，这个long类型的id精度丢失了，所以想在对象转json时long类型能转成字符串类型：{id:'1349625084474417153'}，这样前端拿到的是字符串，就不会有数字精度问题了

**Comment by xiaoke1301** [comment]
> Long本身有长度限制吧，太长会溢出。考虑使用BigDecimal

不好意思哈，可能是没有描述清楚，比如后台返回的json格式：{id:1349625084474417153}，但是前端拿到的是{id:1349625084474417100}，这个long类型的id精度丢失了，所以想在对象转json时long类型能转成字符串类型：{id:'1349625084474417153'}，这样前端拿到的是字符串，就不会有数字精度问题了

**Comment by looly** [comment]
那你只能set("id", "1349625084474417153")
