### ISSUE TITLE
BeanPath 获取值没有按照 java bean 规范设置，只是直接设定到字段上，没有同 get set 方法设置

### ISSUE THREAD

**Issue by vivlanwong** [looly/hutool#1745]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/6279503/128288137-bda5593f-9415-442d-8cef-f7cb6313554a.png">

**Comment by looly** [comment]
BeanPath本质上是字段操作，所以就直接赋值或读取字段了。
