### ISSUE TITLE
使用ExcelUtil 生成Excel文件时，使用getHeadCellStyle设置第一行单元格样式，不生效

### ISSUE THREAD

**Issue by Chen-kaiyuan** [looly/hutool#1746]
### 版本情况

JDK版本：   java version "1.8.0_291"
hutool版本： 5.7.5（请确保最新尝试是否还有问题）
相关依赖：
poi-ooxml v5.0.0
xercesImpl v2.12.1

### 问题描述（包括截图）
使用ExcelUtil 生成Excel文件时，使用getHeadCellStyle设置第一行单元格样式，不生效
1. 复现代码

```java
// 设置单元格为黄色
        CellStyle cellStyle1 = style.getHeadCellStyle();
        cellStyle1.setFillForegroundColor(IndexedColors.YELLOW1.index);
        cellStyle1.setFillPattern(FillPatternType.SOLID_FOREGROUND);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可以啊：

```java
final ExcelWriter writer = ExcelUtil.getWriter("d:/test/headerStyle.xlsx");
writer.writeHeadRow(ListUtil.of("姓名", "性别", "年龄"));
final CellStyle headCellStyle = writer.getStyleSet().getHeadCellStyle();
headCellStyle.setFillForegroundColor(IndexedColors.YELLOW1.index);
headCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

writer.close();
```

![image](https://user-images.githubusercontent.com/1432613/128595792-c3bfeff0-208d-476f-8abd-e5f5da9b0a8b.png)

**Comment by Chen-kaiyuan** [comment]
还是不行，
这个是我的代码，我把这个封装成了一个方法，
```java
 public static String writeExcel(String FilePath, String caseName, List<List<String>> list){
        // 预设格式
        List<String> row1 = CollUtil.newArrayList("KEY","TYPE","PARAMS","VERIFY");
        List<String> row2 = CollUtil.newArrayList("CaseName",caseName,"","");
        List<String> row3 = CollUtil.newArrayList("CaseRun","TRUE","","");
        List<List<String>> rows = CollUtil.newArrayList(row1,row2,row3);
        // 设置生成的文件名
        String name =FilePath+"_"+DateUtil.format(DateUtil.parse(DateUtil.date().toString()),"yyyyMMddHHmmss")+".xlsx" ;
        // 新建文件
        ExcelWriter writer = ExcelUtil.getWriter(name,caseName);
        // 设置样式为左对齐
        StyleSet style = writer.getStyleSet();
        CellStyle cellStyle = style.getCellStyle();
        cellStyle.setAlignment(HorizontalAlignment.LEFT);
        // 设置单元格为黄色
        CellStyle headCellStyle = writer.getStyleSet().getHeadCellStyle();
        headCellStyle.setFillForegroundColor(IndexedColors.YELLOW1.index);
        headCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        // 设置列宽 55（前4列）
        writer.setColumnWidth(0,55);
        writer.setColumnWidth(1,55);
        writer.setColumnWidth(2,55);
        writer.setColumnWidth(3,55);
        // 写入预设
        writer.write(rows);
        // 写入数据
        writer.write(list);
        // 关闭文件
        writer.close();

        return name;
    }
```

**Comment by Chen-kaiyuan** [comment]
谢谢，不好意思，我自己的锅
我写标题的时候，没有用writer.writeHeadRow
感谢您的回答，谢谢啦。
Thanks♪(･ω･)ﾉ

**Comment by Kylelkh** [comment]
这里还有一个问题，用了writer.writeHeadRow，接着使用writer.write(data)，生成的excel只有header并没有data
@looly

**Comment by looly** [comment]
@Kylelkh 如果你的data是map，那会写数据，与headerRow没关系。如果是List应该可以直接写出。

如果无法解决，麻烦重新开一个issue，提供下测试代码。

**Comment by Kylelkh** [comment]
@looly 
### 测试代码


    @Data
    class TestData {
      private String id;
      private String version;
    }

    List<TestData> data = new ArrayList<>();
    for (int i = 1; i <= 10; i++) {
      TestData testData = new TestData();
      testData.setId(UUID.randomUUID().toString());
      testData.setVersion("" + i);
      data.add(testData);
    }

    ExcelWriter writer = ExcelUtil.getWriter("d:/testHeaderStyle.xlsx");
    writer.writeHeadRow(ListUtil.of("UUID", "Version"));
    final CellStyle headCellStyle = writer.getStyleSet().getHeadCellStyle();
    headCellStyle.setFillForegroundColor(IndexedColors.YELLOW1.index);
    headCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

    writer.write(data, false);

    writer.close();
  



### 生成效果

![Image](https://github.com/user-attachments/assets/6ecd9eb6-a527-452d-9bfc-4f91e2380a4f)
