### ISSUE TITLE
发送邮件附件为中文

### ISSUE THREAD

**Issue by jwkuaile** [looly/hutool#1747]
请问，发送邮件附件带有中文，收到的邮件附件显示为“未命名.bin”，删除中文名称采用纯数字的显示就正常的；
使用方法：
cn.hutool.extra.mail.MailUtil.send(String to, String cc, String bcc, String subject, String content, boolean isHtml, File... files)

多谢！！！

**Comment by looly** [comment]
使用Mail对象构建设置下编码：

MailAccount.setCharset
