### ISSUE TITLE
希望BeanUtil.copytoList能支持null值判断

### ISSUE THREAD

**Issue by LoveofRedMoon** [looly/hutool#1754]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

可能导致NPE

1. 复现代码

```java
List<String> list = null;
BeanUtil.copytoList(list, XXX.class);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/128872566-5fcd3e40-2875-434b-a8c2-04e3aac9cb1c.png)


chuan'ru传入CopyOptions即可。

**Comment by LoveofRedMoon** [comment]
@looly 是指第一个参数collection = null时, 在collection.stream()的时候就直接NPE了
```java
List<JSONObject> list = null;
BeanUtil.copyToList(list, JSONObject.class, new CopyOptions().ignoreNullValue().ignoreError());
```
