### ISSUE TITLE
CharSequenceUtil 注释问题

### ISSUE THREAD

**Issue by anaer** [looly/hutool#1756]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.7

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/4637100/128833882-002e6c84-b7fb-4677-b21c-c1433849ea8d.png)

DesensitizedUtil 脱敏工具类 类名不带s
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.7.8修复注释，感谢。
