### ISSUE TITLE
ImgUtil.compress 只支持jpg,麻烦抛个异常,容易死循环

### ISSUE THREAD

**Issue by zhouchengfei** [looly/hutool#1758]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
把图片压缩到500K以下

String oldFile = newfilePathName;
  while (true){
      //只支持jpg
      String new2 = savePath + IdUtil.fastSimpleUUID() + ".png";
      ImgUtil.compress(FileUtil.file(oldFile),FileUtil.file(new2),0.9F);
      log.info("压缩图片"+FileUtil.size(FileUtil.file(new2)));
      oldFile = new2;
      if(FileUtil.checkFileSize(FileUtil.file(new2),500,"K")){
          break;
      }
  }

**Comment by looly** [comment]
请在循环外自行判断下文件类型呗，如果写在循环内部或者compress方法中，会每次循环判断。

你也可以判断后自行转换为jpg。
