### ISSUE TITLE
Hutool 5.7.7 引用poi 5.0.0 又遇到了NoSuchMethodError

### ISSUE THREAD

**Issue by lifedever** [looly/hutool#1759]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用ExcelUtil读取xlsx并写出，报错：
```java
NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellType hutool
```

这个问题什么时候能彻底解决一下？

**Comment by lifedever** [comment]
已经退回5.6.7，用poi 5.0.0没有问题
![image](https://user-images.githubusercontent.com/3143306/128996715-bb8fda64-c036-44e3-b934-30ca725d472b.png)

**Comment by looly** [comment]
我检查了，4.1.2和5.0.0都没有问题，考虑：

1. 是否引入多版本的POI导致冲突了？
2. 是否引入多版本的hutool冲突了？

看了下找不到的方法：

旧版本的POI中是没有`Cell.getCellType`的，只有`getCellTypeEnum`，而Hutool中调用的是getCellType方法，大概率是你的POI版本太低导致的（或者项目中存在旧版本POI）

hutool-5.6.x可以使用是因为兼容了POI-3.x。
