### ISSUE TITLE
使用ExcelUtil如何设置某一列的类型，比如设置为字符串

### ISSUE THREAD

**Issue by ideaviewes** [looly/hutool#1762]
### 版本情况

JDK版本：    1.8.0_301
hutool版本： 5.5.2
### 问题描述（包括截图）
使用ExcelUtil如何设置某一列的类型，比如设置为字符串，具体问题是，导出身份证号的时候，变成了科学计数法的数字

1. 复现代码

![image](https://user-images.githubusercontent.com/5431843/129338322-4a2d5738-4d8e-4b12-b7ec-e8a64cdbc982.png)

**Comment by looly** [comment]
没办法，只能为这一列单元格单独创建样式，然后CellUtil.setCellValue
