### ISSUE TITLE
httprequest工具问题

### ISSUE THREAD

**Issue by ccxyChuzhong** [looly/hutool#1763]
### 版本情况

JDK版本：    Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
hutool版本：5.7.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

华为的一个restful接口 是post请求 url上边带get请求参数  
因为Java post请求会将url格式化  所以请求不到
![image](https://user-images.githubusercontent.com/55871409/129440969-1ef148fd-95ad-49f2-a4c0-8a6c392ff757.png)
![image](https://user-images.githubusercontent.com/55871409/129440997-57123ef9-61c2-413c-8194-e62b49e4912e.png)

**Comment by looly** [comment]
你可以HttpRequest.post("xxxxx?xxx=aa&xx=b").form()

应该是URL中的参数和body中的参数互不影响。
