### ISSUE TITLE
hutool 不支持 安卓5.0版本怎么解决呢

### ISSUE THREAD

**Issue by bravelionet** [looly/hutool#1773]
出现以下错误 : 
   #main(1) java.lang.NoClassDefFoundErrorcn.hutool.core.lang.-SSLambda$Assert$vGIX034NIFTO1yOx8lxOPOo7hou 

图片 : 
![image](https://user-images.githubusercontent.com/48754924/130014642-4c5dfa13-e589-4417-8b85-76147383d731.png)

**Comment by looly** [comment]
可能是因为Android5上的JDK（jre）版本太低了吧，目测是不支持jdk8的lambda表达式。
