### ISSUE TITLE
Could make sense create samples (may be in English) in various sub project?

### ISSUE THREAD

**Issue by antimoroma** [looly/hutool#1777]
I take a look at the hutool-json test code and found some interesting and useful functions, may be to accelerate the adoption of this and another sub projects I/we can create some samples (in my case in English in a PR) to facilitate  new adopters.
My English is not perfect at all , but is better than my Chinese :)

Just an idea :)

**Comment by looly** [comment]
Sorry sir, my English is pool so we can not comment and code in English, you can translate by Google to help it. Hutool code is free, so you can do anything you want.
