### ISSUE TITLE
生成Excel数据不全

### ISSUE THREAD

**Issue by sonj2u** [looly/hutool#1778]
### 版本情况

JDK版本：    OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
hutool版本： 5.7.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
行转列，数据用map包装，头标题是它们的字段set集合，固定字段分配了固定的key命名，其余json内的以colmun(0,1,2.....) 命名对应，使用hutool生成excel出现了第一个数据列map如果不存在key好像就停止的现象。

- 数据
![image](https://user-images.githubusercontent.com/30248358/130320430-07546651-9344-4b45-9905-b7266a01fa78.png)

- 使用hutool编码实现
![image](https://user-images.githubusercontent.com/30248358/130320405-76e17306-3227-4583-ba3a-6916581633da.png)

- 使用poi编码实现
![image](https://user-images.githubusercontent.com/30248358/130320451-cafc3103-56a0-4023-a8b3-439396e4a765.png)

1. 复现代码

```java
public void writeFormDataToFile(File file, Map<String, String> headerMap,
		List<?> formData) {
	try (ExcelWriter writer = ExcelUtil.getWriter(true)) {
		writer.setDestFile(file);
		Set<Map.Entry<String, String>> entries = headerMap.entrySet();
		for (Map.Entry<String, String> headerEntry : entries) {
			String name = headerEntry.getKey();
			String alias = headerEntry.getValue();
			writer.addHeaderAlias(name, alias);
		}
		List<Object> collList = CollUtil.newArrayList();
		collList.addAll(formData);
		writer.write(collList);
		writer.flush();
	}
}
```

2. 堆栈信息
无异常
3. 测试涉及到的文件（注意脱密）
无
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
是的，标题按照第一行数据写出，后续数据都是以第一行为准的。考虑将第一行数据补充完整。
