### ISSUE TITLE
hutool-db对于返回值大小写bug

### ISSUE THREAD

**Issue by zheng-zy** [looly/hutool#1782]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
Db.use(ds).query(strSql);

2. 堆栈信息
![image](https://user-images.githubusercontent.com/13825054/130502999-9635ba38-92ae-474b-b9bf-15e67cfe065e.png)
sql字段：SELECT CompanyCode,UpdateDate,COUNT(0)Num FROM kdw_tbl_test WHERE companycode=''

3. 测试涉及到的文件（注意脱密）
sql字段CompanyCode,UpdateDate,Num，返回字段变成companycode,updatedate,num，返回会修改我字段大小写，需要区分大小写，怎么处理？

**Comment by looly** [comment]
你可以尝试：

```java
GlobalDbConfig.setCaseInsensitive(false);
```

**Comment by zheng-zy** [comment]
可以 感谢
