### ISSUE TITLE
cn.hutool.core.bean.BeanUtil#mapToBean时setter的参数类型和属性类型不一致会报错

### ISSUE THREAD

**Issue by chenfeiwu** [looly/hutool#1784]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

执行setter赋值的时候获取的类型可以根据setter参数类型来吗，而不是通过属性的类型来转换，
有些场景下我们会在setter方法中自定义转换逻辑的

**Comment by looly** [comment]
Hutool做了这块的限制，setter和参数必须对应。

考虑使用Apache commons没有限制。
