### ISSUE TITLE
希望CsvUtil支持多字符做字段分隔符和文本分隔符比如 ~#

### ISSUE THREAD

**Issue by Kiriter** [looly/hutool#1788]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![image](https://user-images.githubusercontent.com/5117675/130884828-a514d653-ca2a-4e0a-9346-ed0fe65dafa8.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个不打算支持。
