### ISSUE TITLE
您好 使用Excel导出时在打包后无法加载模板内容

### ISSUE THREAD

**Issue by wlsDDD** [looly/hutool#1790]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.9 

### 问题描述（包括截图）

1. 打包前 导出
![image](https://user-images.githubusercontent.com/51633561/130766520-4ea55eb2-90e0-4448-8c60-bafffb423628.png)

2.打成jar包后 导出
![image](https://user-images.githubusercontent.com/51633561/130766778-c1b6ca72-0ff7-446e-b2ac-f94aec025e24.png)

**Comment by looly** [comment]
导出后Excel文件会被打包在jar中，此时须使用流的方式配合ResourceUtil读取。
