### ISSUE TITLE
httprequest设置超时后仍然无限阻塞

### ISSUE THREAD

**Issue by carl-don-it** [looly/hutool#1795]
### 版本情况

JDK版本：    jdk1.8.0_271
hutool版本： 5.5.7

### 问题描述（包括截图）
httpRequest设置超时后仍然无限阻塞，最近频繁出现。使用了代理。开了6条线程，线程栈不相同。
1. 复现代码

```java
Authenticator.setDefault(new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(ProxyUser, ProxyPass.toCharArray());
            }
        });
 HttpRequest request = HttpRequest.get(url)
                // .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36")
                .cookie("")
                .setProxy(ProxyUtils.buildHttpProxy(proxy))
                .setConnectionTimeout(5000)
                .setReadTimeout(60000);
```

2. 堆栈信息
  堆栈跟踪: 
  java.net.SocketInputStream.socketRead0(Native Method)
  java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
  java.net.SocketInputStream.read(SocketInputStream.java:171)
  java.net.SocketInputStream.read(SocketInputStream.java:141)
  sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
  sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:458)
  sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:242)
  sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:180)
  sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
  sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1279)
  sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1188)
  sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
     - 已锁定 sun.security.ssl.TransportContext@4af9a1f
  sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
  sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
  sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
  cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
  cn.hutool.http.HttpRequest.send(HttpRequest.java:1159)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
  com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
  com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:449)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
  com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
  java.util.concurrent.FutureTask.run(FutureTask.java)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
  
  
  堆栈跟踪: 
  java.net.SocketInputStream.socketRead0(Native Method)
  java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
  java.net.SocketInputStream.read(SocketInputStream.java:171)
  java.net.SocketInputStream.read(SocketInputStream.java:141)
  java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
  java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
  java.io.BufferedInputStream.read(BufferedInputStream.java:345)
     - 已锁定 java.io.BufferedInputStream@29fcab63
  sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
  sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
  sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2061)
     - 已锁定 sun.net.www.protocol.https.DelegateHttpsURLConnection@7be894c3
  sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
  sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
  cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
  cn.hutool.http.HttpRequest.send(HttpRequest.java:1159)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
  com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
  com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:449)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
  com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
  java.util.concurrent.FutureTask.run(FutureTask.java)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
  
  堆栈跟踪: 
  java.net.SocketInputStream.socketRead0(Native Method)
  java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
  java.net.SocketInputStream.read(SocketInputStream.java:171)
  java.net.SocketInputStream.read(SocketInputStream.java:141)
  sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
  sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:458)
  sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:242)
  sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:180)
  sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
  sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1282)
  sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1249)
     - 已锁定 sun.security.ssl.SSLSocketImpl@8282229
  sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:75)
  sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:915)
     - 已锁定 sun.security.ssl.SSLSocketImpl$AppInputStream@7de5e463
  java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
  java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
  java.io.BufferedInputStream.read(BufferedInputStream.java:345)
     - 已锁定 java.io.BufferedInputStream@5c746988
  sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
  sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
     - 已锁定 sun.net.www.http.ChunkedInputStream@600ce421
  java.io.FilterInputStream.read(FilterInputStream.java:133)
  sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
  java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
  java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
  java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
  cn.hutool.http.HttpInputStream.read(HttpInputStream.java:40)
  java.io.InputStream.read(InputStream.java:101)
  cn.hutool.core.io.IoUtil.copy(IoUtil.java:158)
  cn.hutool.core.io.IoUtil.copy(IoUtil.java:132)
  cn.hutool.core.io.IoUtil.copy(IoUtil.java:119)
  cn.hutool.http.HttpResponse.readBody(HttpResponse.java:451)
  cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:479)
  cn.hutool.http.HttpResponse.init(HttpResponse.java:434)
  cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:379)
  cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:976)
  cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
  com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
  com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:477)
  com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
  com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
  java.util.concurrent.FutureTask.run(FutureTask.java)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)

堆栈跟踪: 
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:171)
java.net.SocketInputStream.read(SocketInputStream.java:141)
sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1279)
sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1188)
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
   - 已锁定 sun.security.ssl.TransportContext@27937af5
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
cn.hutool.http.HttpRequest.send(HttpRequest.java:1159)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:449)
com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
java.util.concurrent.FutureTask.run(FutureTask.java)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

堆栈跟踪: 
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:171)
java.net.SocketInputStream.read(SocketInputStream.java:141)
sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:458)
sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:242)
sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:180)
sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1282)
sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1249)
   - 已锁定 sun.security.ssl.SSLSocketImpl@6dd4e185
sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:75)
sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:915)
   - 已锁定 sun.security.ssl.SSLSocketImpl$AppInputStream@eb9bb06
java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
java.io.BufferedInputStream.read(BufferedInputStream.java:345)
   - 已锁定 java.io.BufferedInputStream@2431521
sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
   - 已锁定 sun.net.www.http.ChunkedInputStream@34d368f6
java.io.FilterInputStream.read(FilterInputStream.java:133)
sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
cn.hutool.http.HttpInputStream.read(HttpInputStream.java:40)
java.io.InputStream.read(InputStream.java:101)
cn.hutool.core.io.IoUtil.copy(IoUtil.java:158)
cn.hutool.core.io.IoUtil.copy(IoUtil.java:132)
cn.hutool.core.io.IoUtil.copy(IoUtil.java:119)
cn.hutool.http.HttpResponse.readBody(HttpResponse.java:451)
cn.hutool.http.HttpResponse.forceSync(HttpResponse.java:479)
cn.hutool.http.HttpResponse.init(HttpResponse.java:434)
cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:379)
cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:976)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:477)
com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
java.util.concurrent.FutureTask.run(FutureTask.java)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

堆栈跟踪: 
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:171)
java.net.SocketInputStream.read(SocketInputStream.java:141)
java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
java.io.BufferedInputStream.read(BufferedInputStream.java:345)
   - 已锁定 java.io.BufferedInputStream@7ec16f20
sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2061)
   - 已锁定 sun.net.www.protocol.https.DelegateHttpsURLConnection@3de38a75
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
cn.hutool.http.HttpRequest.send(HttpRequest.java:1159)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:969)
cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
com.dc.common.util.httputil.HttpUtil.executeAndRetry(HttpUtil.java:132)
com.dc.dmc.crawl.crawler.jd.AbstractJDCrawler.get(AbstractJDCrawler.java:83)
com.dc.dmc.crawl.crawler.jd.JDCrawler.dealOneSort(JDCrawler.java:449)
com.dc.dmc.crawl.crawler.jd.JDCrawler.lambda$basic$6(JDCrawler.java:201)
com.dc.dmc.crawl.crawler.jd.JDCrawler$$Lambda$418/730533521.run(Unknown Source)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
java.util.concurrent.FutureTask.run(FutureTask.java)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by looly** [comment]
暂时不确定是否为代理导致的超时，HttpUrlConnection提供的超时选项只有这连个。

**Comment by carl-don-it** [comment]
这怎么解决啊

**Comment by looly** [comment]
这个暂时无法复现找不到原因，考虑：

去掉代理直接访问试下看超时是否有效。

**Comment by carl-don-it** [comment]
去掉代理没问题

**Comment by carl-don-it** [comment]
找到了一些相关文章，https://blog.csdn.net/u010916254/article/details/88915534

**Comment by looly** [comment]
感谢回答，我一直没有找到原因，原来是JDK的坑……

**Comment by carl-don-it** [comment]
能改一下吗

**Comment by looly** [comment]
HttpUrlConnection没法自定义soTimeout，因此这个问题没法解决。只能升级JDK了。
