### ISSUE TITLE
希望Validator可以结合JSR 380使用

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#1798]
希望Validator可以结合JSR 380使用
1. ValidateException和StatefulException希望能继承javax.validation.ValidationException
2. 希望能够有注解或其他结合JSR 380的形式进行使用

**Comment by looly** [comment]
1. `javax.validation.ValidationException`并不在JDK默认提供的包的范围内，需要单独引入`jakarta.validation-api`
可以用extra模块的`ValidationUtil`
