### ISSUE TITLE
HttpRequest调用kafka的put接口失败

### ISSUE THREAD

**Issue by gaoxs1985** [looly/hutool#1799]
### 版本情况

JDK版本：    1.8.0_191
hutool版本： 5.7.9

### 问题描述（包括截图）

```java
HttpRequest.put("http://10.0.1.180:8083/connectors/" + connectName + "/pause").execute().body()
```

在通过HttpRequest调用kafka的put接口时返回异常
```java
{"error_code":415,"message":"HTTP 415 Unsupported Media Type"}
```

但通过postman调用同样接口没问题

可以协助解决一下吗?

**Comment by looly** [comment]
应该是Content-Type类型导致的，尝试自定义添加`header(Header.CONTENT_TYPE, "application/json")`试下。
