### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by walden1993** [looly/hutool#180]
CompareUtil类内存溢出异常：
      使用Excel工具类导出的时候。进行bean排序发生。麻烦看看。

	public static <T> int compare(T o1, T o2, boolean isNullGreater) {
		if (o1 == o2) {
			return 0;
		} else if (null == o1) {// null 排在后面
			return isNullGreater ? 1 : -1;
		} else if (null == o2) {
			return isNullGreater ? -1 : 1;
		}
		
		if(o1 instanceof Comparable && o2 instanceof Comparable) {
			//如果bean可比较，直接比较bean（这里会进入无限循环比较）
			return compare((Comparable<?>)o1, (Comparable<?>)o2, isNullGreater);
		}
		
		if(o1.equals(o2)) {
			return 0;
		}
		
		int result = Integer.compare(o1.hashCode(), o2.hashCode());
		if(0 == result) {
			result = compare(o1.toString(), o2.toString());
		}
		
		return result;
	}

**Comment by looly** [comment]
4.1.18解决此问题。十分感谢。
