### ISSUE TITLE
FileUtil.del("");会删掉classes文件夹

### ISSUE THREAD

**Issue by ShubaoYang** [looly/hutool#1802]
### 版本情况

JDK版本：    1.8.0_181
hutool版本： 5.7.9/5.7.10

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/41741864/131316628-4e3fb884-5262-45da-bdce-ccf1e3bb973e.png)
![image](https://user-images.githubusercontent.com/41741864/131316656-d077a3a0-c605-4d9b-a56f-93dca7deb4bc.png)

1. 复现代码

```java
import cn.hutool.core.io.FileUtil;


public class Demo {
    public static void main(String[] args){
        FileUtil.del("");
    }
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by ShubaoYang** [comment]
在删除文件之前没有判断文件路径是否为空，这是我写法上有问题。但是直接删掉classes文件夹就不好了。还好在测试环境上发现了问题，如果生产环境，后果不堪设想，后怕

**Comment by looly** [comment]
确实是这样的，Hutool定义传入""表示相对路径的classpath的根路径，所以会清空classpath。

如果你传入new File("")，那清空的就是你的整个项目目录了。

**Comment by ShubaoYang** [comment]
这样做风险会不会太高了呢？
