### ISSUE TITLE
带注释的json字符串转换报错

### ISSUE THREAD

**Issue by shenyeting** [looly/hutool#1806]
### 版本情况

hutool版本： 5.7.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
json字符串中带注释时，使用JSONUtil.parse()转换时会报错。
之前用的fastjson不会报错
![image](https://user-images.githubusercontent.com/25581502/131654033-01d99dfb-eae1-43b1-b98c-12fa39501337.png)

**Comment by looly** [comment]
hutool不支持JSON中这类注释。
