### ISSUE TITLE
Json解析

### ISSUE THREAD

**Issue by zs1973** [looly/hutool#1809]
### 版本情况

JDK版本：    java version "11.0.10" 2021-01-19 LTS
hutool版本： 5.7.11
json解析失败：
json:  {
"code":200,
"errMsg":"ok"
}

如果定义的数据modol类有一个data字段，但是后台返回的数据只有如上两个字段，请问怎么处理这种情况呢？

**Comment by looly** [comment]
没听懂，model类中有多余data字段，会默认不赋值啊。
