### ISSUE TITLE
二维码在工具类之外生成失败

### ISSUE THREAD

**Issue by HWYWL** [looly/hutool#181]
在本地我的应用中直接使用二维码在工具类生成二维码失败，
[Error:(47, 19) java: 无法访问com.google.zxing.BarcodeFormat 找不到com.google](url)
需要在本地引入“com.google.zxing”包才能正常使用。

**Comment by looly** [comment]
是滴。Hutool的二维码工具类需要依赖zxing库，文档中有说明。这没问题。
