### ISSUE TITLE
TimedCache 是否考虑增加获取过期时间的接口？

### ISSUE THREAD

**Issue by ruanych** [looly/hutool#1810]
对于基于过期时间的缓存策略，有一个需求是获取某个 key 在缓存中的 剩余过期时间。

目前 hutool 中的缓存工具类 `cn.hutool.cache.impl.TimedCache ` 并没有获取缓存过期时间的方法，是否考虑以某种形式增加这种功能？

**Comment by looly** [comment]
不考虑单独加方法了，你可以：

继承`TimedCache`，然后加个方法访问`cacheMap`，get出来`CacheObj`，反射获取相应字段。

虽然比较麻烦，但是考虑到缓存的健壮性，不建议访问修改CacheObj。
