### ISSUE TITLE
cn.hutool.core.collection.ListUtil#split 升级5.7.11后使用异常

### ISSUE THREAD

**Issue by xllove-moon** [looly/hutool#1812]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
从5.6.x低版本升级上来的，原来无论原始list是多长 ListUtil.split都没有问题，现在如果list的长度小于size就会报错

2. 堆栈信息
问题行
java.lang.ArithmeticException: / by zero
at cn.hutool.core.collection.Partition.size(Partition.java:44) ~[hutool-all-5.7.11.jar:?]

在这个类里 cn.hutool.core.collection.Partition
```
	public int size() {
		// 此处采用动态计算，以应对list变化
		final int total = list.size();
		int length = total / size;
		if(total % length > 0){
			length += 1;
		}
		return length;
	}
```
当total/size=0的时候问题就出现了，total % 0 报错

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/issues/I48Q0P

5.7.12修复此问题。
