### ISSUE TITLE
多个请求如何共用header

### ISSUE THREAD

**Issue by monyuan** [looly/hutool#1813]
`
String result2 = HttpRequest.post(url)
    .header(Header.USER_AGENT, "Hutool http")//头信息，多个头信息多次调用此方法即可
    .form(paramMap)//表单内容
    .timeout(20000)//超时，毫秒
    .execute().body();
Console.log(result2);
`
如何定义一个全局header，然后.header引用。

刚转java两天，不太懂，求指导

**Comment by looly** [comment]
可以用`GlobalHeaders.INSTANCE.header()`添加全局头信息。

**Comment by monyuan** [comment]
@looly 谢谢，请问GlobalHeaders.INSTANCE.header()是作用于整个项目，还是当前的方法里。如果想作用于当前域，如何操作

**Comment by looly** [comment]
> @looly 谢谢，请问GlobalHeaders.INSTANCE.header()是作用于整个项目，还是当前的方法里。如果想作用于当前域，如何操作

是整个项目，没有作用域。作用域没办法的。
