### ISSUE TITLE
这个UUID存在的意义？

### ISSUE THREAD

**Issue by lnsane** [looly/hutool#1816]
https://github.com/dromara/hutool/blob/c36f9f55db1c271966863c1dd397a9f29678e837/hutool-core/src/main/java/cn/hutool/core/lang/UUID.java#L43

为什么不使用 java.util.UUID ?

**Comment by looly** [comment]
> 此类拷贝自java.util.UUID，用于生成不带-的UUID字符串

两个原因：

1. 提供toString方法，可选是否有`-`，JDK原生UUID如果需要转换，必须使用`String.replace`方法去掉`-`，重写后在生成时就不加入`-`，性能更好。

2. 提供`fastUUID`方法，使用`ThreadLocalRandom`生成伪随机数，相比`SecureRandom`提供更好的性能。

**Comment by lnsane** [comment]
> > 此类拷贝自java.util.UUID，用于生成不带-的UUID字符串
> 
> 两个原因：
> 
> 1. 提供toString方法，可选是否有`-`，JDK原生UUID如果需要转换，必须使用`String.replace`方法去掉`-`，重写后在生成时就不加入`-`，性能更好。
> 2. 提供`fastUUID`方法，使用`ThreadLocalRandom`生成伪随机数，相比`SecureRandom`提供更好的性能。

如你所说，那为什么不把 ThreadLocalRandom.current() 当成默认生成的Random？

**Comment by looly** [comment]
> > > 此类拷贝自java.util.UUID，用于生成不带-的UUID字符串
> > 
> > 
> > 两个原因：
> > 
> > 1. 提供toString方法，可选是否有`-`，JDK原生UUID如果需要转换，必须使用`String.replace`方法去掉`-`，重写后在生成时就不加入`-`，性能更好。
> > 2. 提供`fastUUID`方法，使用`ThreadLocalRandom`生成伪随机数，相比`SecureRandom`提供更好的性能。
> 
> 如你所说，那为什么不把 ThreadLocalRandom.current() 当成默认生成的Random？

` ThreadLocalRandom.current()`虽然速度快，但是生成的随机数有重复率比较高的问题，因此只适合对重复性要求不高的场景。
