### ISSUE TITLE
Jackson  JSONNull的问题

### ISSUE THREAD

**Issue by SYanalyser** [looly/hutool#1820]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.4

### 问题描述（包括截图）
Jackson不能序列化JSONNull，是否能在hutool做适配？
当然我这边也是扩展了Jackson让它适配JSONNull，是否能有更好的方案？
现解决方案如下：
```java
SimpleModule simpleModule = new SimpleModule();
        simpleModule.addSerializer(JSONNull.class, new JsonSerializer<JSONNull>() {
            @Override
            public void serialize(JSONNull jsonNull, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
                jsonGenerator.writeNull();
            }
        });
        simpleModule.addDeserializer(JSONNull.class, new JsonDeserializer<JSONNull>() {
            @Override
            public JSONNull deserialize(JsonParser jsonParser, DeserializationContext deserializationContext){
                return null;
            }
        });
ObjectMapper objectMapper = new ObjectMapper().registerModule(simpleModule);
```

1. 复现代码

测试代码

```java
@GetMapping("testJson")
@ResponseBody
public JSONObject testJson() {
        String json = "{ \n" +
                " \"request\": \"method\",\n" +
                " \"content\": {\n" +
                " \"device_path\": \"31f4287d-e902-3b21-b592-6b7e3c88d07f",\n" +
                " \"params\": {\n" +
                " \"start_time\": 1616351962,\n" +
                " \"end_time\": 1616355562,\n" +
                " \"video_quality\": 1,\n" +
                " \"speed\": 1,\n" +
                " \"tz_delta\": null \n" +
                " }\n" +
                " }\n" +
                "}";

     return JSONUtil.parseObj(json);
    }

```

2. 堆栈信息
 ERROR [c.w.p.e.GlobalExceptionHandler] - org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class cn.hutool.json.JSONNull]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class cn.hutool.json.JSONNull and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: cn.hutool.json.JSONObject["content"]->cn.hutool.json.JSONObject["params"]->cn.hutool.json.JSONObject["data"])
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:460)
at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Hutool-json早期根据json-lib改造而来，因此保留了JSONNUll，不建议jackson和hutool同时使用，这个暂时没有更好的办法。
