### ISSUE TITLE
关于 BitStatusUtil 工具类的一点问题

### ISSUE THREAD

**Issue by starxg** [looly/hutool#1824]
### 版本情况

hutool版本： 5.6.6+

### 问题描述（包括截图）
我发现这个工具类 （[BitStatusUtil](https://github.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/math/BitStatusUtil.java) ）和我之前写的工具类高度相似，可以说一模一样。[https://blog.starxg.com/2020/11/bit-status/](https://blog.starxg.com/2020/11/bit-status/)

博客之前迁移过一次，但commit日期依然早于此 [PR](https://github.com/dromara/hutool/pull/1600)

![CE0A9108-6E81-4EB2-8660-B5F5051F8D49](https://user-images.githubusercontent.com/34997494/133021045-729a6d50-6b88-4380-bb21-0c26d2d3d59a.png)

希望在后续版本中在 [author](https://github.com/dromara/hutool/blob/5.6.6/hutool-core/src/main/java/cn/hutool/core/math/BitStatusUtil.java#L7) 处加上 `huangxingguang`。

谢谢！

**Comment by looly** [comment]
不好意思，这个是用户提交上来的PR，我会在工具中注明出处及Author。

如果涉及侵权会在下个版本删除。

**Comment by looly** [comment]
5.7.13注释增加说明并添加作者。
