### ISSUE TITLE
日期工具类中有判断一个字符串为合法日期时间格式的方法吗

### ISSUE THREAD

**Issue by zuccyingjie** [looly/hutool#1827]
比如我传入一个字符串“2021-09-15 00:00:00"
返回true

**Comment by shiyishiaa** [comment]
1. public static LocalDateTime parse(CharSequence text, DateTimeFormatter formatter);然后在判断一下？
2. RegexPool.BIRTHDAY;搭配着时间写一个正则

**Comment by shiyishiaa** [comment]
还有个FastDateParser
