### ISSUE TITLE
在OpenJDK14.0.2中使用BeanUtil.toBean方法导致JVM崩溃

### ISSUE THREAD

**Issue by KwonJiYongYG** [looly/hutool#1828]
### 版本情况

JDK版本：    openjdk_14.0.2
hutool版本： 5.5.1

### 问题描述（包括截图）

1. 复现代码
![image](https://user-images.githubusercontent.com/48173172/133586330-2530d7ad-51b6-4cf6-a0c7-3431847a0fae.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

![image](https://user-images.githubusercontent.com/48173172/133585901-e4e1175b-f211-4b33-a3d7-35bdeb404f65.png)

**Comment by looly** [comment]
这个问题暂时找不到原因，尝试使用Spring的BeanUtils试下。

Hutool通过反射调用相关方法注入，如果换Spring的工具出现，则可能是jdk的bug。

尝试升级JDK到最新update版本试下。

**Comment by rexlin600** [comment]
这个问题有后续结论吗 @looly

**Comment by hanb102400** [comment]
此错误并非个例，我jdk11的版本也遇到了，频繁调用JsonUtil.toJsonStr()方法最终调入反射的invoke中，然后报出Crash in G1ParCopyClosure，导致整个JVM进程异常崩溃，属于严重问题了，并且随机出现比较难定位。 @looly

**Comment by hanb102400** [comment]
怀疑是invoke方法调用了错误的内存地址，看使用了WeakConcurrentMap，这个弱引用在内存占用满时，多个线程执行invoke会有并发问题吗，会不会有可能出现弱引用被回收，但是其他线程调用到已经回收的弱引用导致内存错误？不懂jvm，说错勿怪。@looly

**Comment by looly** [comment]
@shawnxt 嗯……其实我也不懂JVM，而且我怀疑是JVM本身的bug，在工具层没法找到问题。看后续JDK更新吧。

**Comment by 1435646097** [comment]
JDK17中也遇到了这种问题，还很难复习，只能暂时先不要用copyProperties这个方法
