### ISSUE TITLE
从4.6.10升级5.7.12后跑不起来

### ISSUE THREAD

**Issue by cnbeiyu** [looly/hutool#1829]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.12</version>
        </dependency>

2. 堆栈信息
![Uploading image.png…]()
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method cn.hutool.core.lang.Assert.notEmpty(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; but it does not exist. Its class, cn.hutool.core.lang.Assert, is available from the following locations:

    jar:file:/Users//.m2/repository/cn/hutool/hutool-all/5.7.12/hutool-all-5.7.12.jar!/cn/hutool/core/lang/Assert.class

It was loaded from the following location:

    file:/Users/wenzhuo/.m2/repository/cn/hutool/hutool-all/5.7.12/hutool-all-5.7.12.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of cn.hutool.core.lang.Assert

**Comment by looly** [comment]
4.x和5.x的API很多变更了，升级后需要手动解决报错，然后重新编译项目。
