### ISSUE TITLE
URLUtil是否可以增加一个将URL长链接转换为短链接的功能

### ISSUE THREAD

**Issue by zhuyouzhufu** [looly/hutool#1830]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.12

### 功能增加建议
URLUtil是否可以增加一个将URL长链接转换为短连接的功能。因为以前有些功能涉及到此功能个人觉得URLUtil工具类可以增加一些辅助的功能。
如：https://sina.lt/

**Comment by zhuyouzhufu** [comment]
说一个业务场景：如发短信一个长链接动不动就是几百个字符长度，用短链接处理后就会好很多。

**Comment by qingkediguo** [comment]
这个肯定是需要保存或者处理长链接短连接的映射关系的。不可能通过这种工具类进行处理的啊

**Comment by looly** [comment]
这个不行，需要借助第三方短链接生成接口完成。
