### ISSUE TITLE
collUtil.subtract方法浅拷贝，会改变collection1的值，建议优化

### ISSUE THREAD

**Issue by xieshanwu1** [looly/hutool#1835]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.7（最新版没有修改）

### 问题描述（包括截图）

1. 见标题
  个人觉得apache-commons-collections4中的实现更好些

**Comment by looly** [comment]
你升级到5.7.13

这个方法不会改变啊：

```java
Collection<T> result = ObjectUtil.clone(coll1);
```

**Comment by xieshanwu1** [comment]
我的测试代码
cn.hutool.json.JSONArray list1 = new cn.hutool.json.JSONArray();
        list1.add("a");
        list1.add("b");
        list1.add("c");
        cn.hutool.json.JSONArray list2 = new cn.hutool.json.JSONArray();
        list2.add("b");
        list2.add("c");
        list2.add("d");
        // 不改变list1
        Collection<Object> subtract1 = org.apache.commons.collections4.CollectionUtils.subtract(list1, list2);
        System.out.println(list1); // ["a","b","c"]
        System.out.println(list2); // ["b","c","d"]
        System.out.println(subtract1); // ["a"]
        // 改变list1
        Collection<Object> subtract = cn.hutool.core.collection.CollUtil.subtract(list1, list2);
        System.out.println(list1); // ["a"]
        System.out.println(list2); // ["b","c","d"]
        System.out.println(subtract); // ["a"]
