### ISSUE TITLE
请问spring cloud分布式下WatchMonitor如何实现文件监听锁，一个文件只能被某一个服务监听？

### ISSUE THREAD

**Issue by 852675742** [looly/hutool#1838]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.5.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

请问spring cloud分布式下WatchMonitor如何实现文件监听锁，一个文件只能被某一个服务监听？

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个没有考虑。

你可以被监听文件旁边创建一个xxx.lock文件，等监听结束删除这个文件，启动监听检查下是否存在这个文件。
