### ISSUE TITLE
CSV 注释不是协议标准，为何默认强制要使用注释符特性

### ISSUE THREAD

**Issue by jalr4ever** [looly/hutool#1842]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

如题，似乎到现在也没找到 RPC 协议标准，为何 CsvConfig#commentCharacter 这种特性必须使用，这种在我理解为是增强性的行为不该是默认不启用么？

**Comment by looly** [comment]
这个有什么问题么？

你的意思是默认不支持注释么？这个配置只是定义了默认的注释符号，即默认注释格式，不喜欢可以自定义的。

**Comment by looly** [comment]
根据[rfc4180](https://datatracker.ietf.org/doc/html/rfc4180)确实没有定义注释，这个是根据FastCSV实现新增的。

按照 https://stackoverflow.com/questions/1961006/can-a-csv-file-have-a-comment 的说法，这个由应用层限制或制定。

**Comment by jalr4ever** [comment]
> 这个有什么问题么？
> 
> 你的意思是默认不支持注释么？这个配置只是定义了默认的注释符号，即默认注释格式，不喜欢可以自定义的。

1、是的，既然不是协议标准，注释符作为一种 enhance 功能存在，那么就应该给出一个配置项去选择开启或者不开启，并且默认不开启

2、问题在于你们的 CSVReader 强制要求用户使用这种非协议标准的特性了，可以参考 CsvParser#readLine() 中解析的代码。

**Comment by jalr4ever** [comment]
我们现在由于在工程中会涉及到大量的 Csv 处理，csv 行的确有可能包含的第一个字符就是注释符，于是处理就被略过的，注释符的确可能就是用户的数据，于是我们只能换一个 csv 处理库了...

建议对注释的特性重新考虑设计一下

**Comment by looly** [comment]
如果不想读取注释，可以考虑在CsvConfig里，设置注释符为不常用字符。

**Comment by looly** [comment]
5.7.14增加CsvConfig.disableComment方法，可以关闭注释解析。
