### ISSUE TITLE
TreeBuilder 能否考虑为根节点填充属性

### ISSUE THREAD

**Issue by John-Chan** [looly/hutool#1848]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.9

### 问题描述（包括截图）
我用的5.7.9，看了最新版(5.7.13)源码应该也是一样。当前的设计，即使将根节点的信息append到TreeBuilder里面，它也不用上，导致build出来的根节点只有ID而没有名称等业务信息。

**Comment by looly** [comment]
TreeUtil.buildSingle之后自行添加属性即可。

**Comment by John-Chan** [comment]
理是这么个理，不过我认为有改进的空间，比如build()方法也不应该抛运行时异常，感谢大佬回复~

**Comment by looly** [comment]
> 理是这么个理，不过我认为有改进的空间，比如build()方法也不应该抛运行时异常，感谢大佬回复~

不抛运行时异常是指？欢迎提供思路。

**Comment by John-Chan** [comment]
build方法，从使用者的角度来说，我把数据交给你，你把build出来的结果(tree)给我，不允许重复调用我觉得设计不合理，使用方重复调用这个方法并不会造成什么副作用，因为内部已经记录了是否已经build，所以说，build方法在已经build的状态下直接返回root就好。另外，TreeBuilder 当前的设计思路是一次性构建，然后缓存结果，缓存不就是为了重复读取吗。

对于append方法，在已经build的状态下抛异常我觉得合理，因为原始数据已经清空，属于不可恢复错误，程序员应该为此负责。

大佬看看我的理解有没有问题？

**Comment by looly** [comment]
确实是这样。

5.7.14会增加一些方法，填充根节点数据。
