### ISSUE TITLE
NetUtil的getLocalhostStr方法获取CentOS的IP地址时经常获取到127.0.0.1

### ISSUE THREAD

**Issue by Sawyerlsy** [looly/hutool#1854]
### 版本情况

JDK版本：   1.8.0_144
hutool版本： 5.7.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
1. 在CentOS中通过NetUtil.getLocalhostStr方法获取本机ip地址时，获取到的是127.0.0.1
2. 经测试NetUtil.getLocalhostStr实际调用的是InetAddress.getLocalHost()，本质上是查询Linux机器的/etc/hosts文件，而CentOS中/etc/hosts文件 localhost对应的是127.0.0.1
![image](https://user-images.githubusercontent.com/48912613/135015925-86770e78-0ce7-4c4f-942d-72421d8ba990.png)

![image](https://user-images.githubusercontent.com/48912613/135015836-a1bf4f56-ee58-4ec7-9fdd-9bb5a2e6cc8a.png)

**Comment by looly** [comment]
前面的逻辑筛选去掉了内网等数据。

如果结果不满足你的要求，只能调用localAddressList方法，自行筛选获取。
