### ISSUE TITLE
jsonArray.put(0,1)bug 

### ISSUE THREAD

**Issue by StudentXXd** [looly/hutool#1858]
### 版本情况

JDK版本：    jdk1.8.0_92
hutool版本： 5.6.6至最新版

### 问题描述（包括截图）
![0PF`I % IUD{ DXBJWV@P72](https://user-images.githubusercontent.com/49467166/135188847-a0a733ff-d960-4ea8-9a6e-5902587252b9.png)
![~IP_1`UIJ@$23NC7{K)4NX2](https://user-images.githubusercontent.com/49467166/135188804-95101750-14d4-4e5d-82ce-ac1b10f1f81c.png
![Q`Q)M9%@0}%)YDAN0~A~8UJ](https://user-images.githubusercontent.com/49467166/135188865-a845dad1-839a-47a9-9482-f77554242dbb.png)
)
仔细看了版本提交记录，在5.6.6版本修复JSONArray.put方法不能覆盖值的问题后出现该问题，5.7.0更新记录并没有修复改数组越界问题，到最新版该问题还一直存在

**Comment by StudentXXd** [comment]
![~IP_1`UIJ@$23NC7{K)4NX2](https://user-images.githubusercontent.com/49467166/135189039-d23f9f09-51a3-4a97-aad5-4027ad51cc3e.png)

**Comment by StudentXXd** [comment]
![Q`Q)M9%@0}%)YDAN0~A~8UJ](https://user-images.githubusercontent.com/49467166/135189087-cb73c37f-4b29-4a74-8ccb-6f28d2d3161c.png)

**Comment by StudentXXd** [comment]
![0PF`I % IUD{ DXBJWV@P72](https://user-images.githubusercontent.com/49467166/135189140-6ae2572b-38c2-4f6d-840c-7d7097439c22.png)

**Comment by looly** [comment]
判断问题，确认bug，感谢。

5.7.14修复。
