### ISSUE TITLE
建议HttpUtil的downloadFile方法可以传入自定义HttpRequest

### ISSUE THREAD

**Issue by ponyjoy** [looly/hutool#187]
HttpUtil的downloadFile系列方法，无法自定义Cookie或其他头信息，希望能加入一个版本的方法传入自定义HttpRequest。因此有些下载场景是需要带入认证信息的。

**Comment by ponyjoy** [comment]
另外有个疑惑。用HttpUtil模拟登录，然后将获得的cookie填入另一个请求，第2个请求问题认证不了，相当于没有登录。但是第2个请求如果用从浏览器获得的cookie填入就可以使用。请问如果保留cookie

**Comment by looly** [comment]
HttpUtil.download本质也是HttpRequest请求的一个快捷操作，你可以：

```
HttpResponse response = HttpRequest.get(url).timeout(timeout).executeAsync();
response.writeBody(file);
```

按照如上请求即可。

**Comment by looly** [comment]
在4.1.19中Cookie是默认记录的，请升级Hutool版本呢尝试。
