### ISSUE TITLE
BeanSheetReader 读取较大 excel 文件(6w 行)时，创建了过多重复 CopyOptions 对象 

### ISSUE THREAD

**Issue by WillfordZhan** [looly/hutool#1875]
## 版本情况

JDK版本：    openjdk_15.0.1
hutool版本： 5.7.13

### 问题原因
BeanSheetReader read() 方法会使用 `BeanUtil.toBeanIgnoreError()` 和 `BeanUtil.copyProperties()`  两个方法

`BeanUtil.toBeanIgnoreError()` 和 `BeanUtil.copyProperties()` 方法每次调用都会新建一个 CopyOptions 对象，导致在读取多行 excel 文件时，会生成大量重复的 CopyOptions 对象

`BeanUtil.copyProperties()`
```java
	public static void copyProperties(Object source, Object target, CopyOptions copyOptions) {
		BeanCopier.create(source, target, ObjectUtil.defaultIfNull(copyOptions, CopyOptions.create())).copy();
	}
``` 

`BeanUtil.toBeanIgnoreError()`
```java
	public static <T> T toBeanIgnoreError(Object source, Class<T> clazz) {
		return toBean(source, clazz, CopyOptions.create().setIgnoreError(true));
	}
```

CopyOptions 生成对象数量
![现状](https://tva1.sinaimg.cn/large/008i3skNgy1gv5r9psyy6j60xz0phq8x02.jpg)

### 建议💡 和疑问❓
建议：对两个方法分别引入两个静态常量，减少方法大量调用时 CopyOptions 对象的创建
```java
	private static final CopyOptions ignoreOption = CopyOptions.create().setIgnoreError(true);
	public static <T> T toBeanIgnoreError(Object source, Class<T> clazz) {
		return toBean(source, clazz, CopyOptions.create().setIgnoreError(true));
	}

	private static final CopyOptions defaultOption = CopyOptions.create();
	public static void copyProperties(Object source, Object target, CopyOptions copyOptions) {
		BeanCopier.create(source, target, ObjectUtil.defaultIfNull(copyOptions, defaultOption)).copy();
	}
```
疑问：如果可以引入的话，不知道这两个常量应该放在哪个类中

### 复现流程
1. 将 ”bbb.xlsx“ 放置在 POI 模块 test resource `hutool-poi/src/test/resources` 目录下
2. 定位到 POI 模块测试代码路径 `hutool-poi/src/test/java/cn/hutool/poi/excel/ExcelReadTest.java`
3. 将该 excelReadToBeanListTest 方法内容修改为如下内容后，运行
```java
	@Test
	public void excelReadToBeanListTest() {
//		ExcelReader reader = ExcelUtil.getReader(ResourceUtil.getStream("aaa.xlsx"));
		ExcelReader reader = ExcelUtil.getReader(ResourceUtil.getStream("bbb.xlsx"));
		reader.addHeaderAlias("姓名", "name");
		reader.addHeaderAlias("年龄", "age");
		reader.addHeaderAlias("性别", "gender");
		reader.addHeaderAlias("鞋码", "shoeSize");

		List<Person> all = reader.readAll(Person.class);
		Assert.assertEquals("张三", all.get(0).getName());
		Assert.assertEquals("男", all.get(0).getGender());
		Assert.assertEquals(Integer.valueOf(11), all.get(0).getAge());
		Assert.assertEquals(new BigDecimal("41.5"), all.get(0).getShoeSize());
	}
```

### 内存占用信息
> 使用 BeanSheetReader 读取 bbb.xlsx (60007 行 Person 数据) ，以下为运行时 JProfiler 的截图

1. 现状
![现状](https://tva1.sinaimg.cn/large/008i3skNgy1gv5r9psyy6j60xz0phq8x02.jpg)
2. 给其中一个方法引入常量
![给其中一个方法引入常量](https://tva1.sinaimg.cn/large/008i3skNgy1gv5r9oqld7j60xc0p0di902.jpg)
3.两个方法使用静态常量后
![两个方法使用静态常量后](https://tva1.sinaimg.cn/large/008i3skNgy1gv5r9p6vsyj60xc0p0jt102.jpg)

### 测试涉及到的文件
bbb.xlsx
https://github.com/WillfordZhan/hutool/raw/v5-dev/hutool-poi/src/test/resources/bbb.xlsx

**Comment by looly** [comment]
感谢意见。应该是读取Excel列表式，转换Bean导致多次创建CopyOptions导致的，问题出在：

https://github.com/dromara/hutool/blob/aa9b82705767b28331ade836bb9a0cd54da04852/hutool-poi/src/main/java/cn/hutool/poi/excel/reader/BeanSheetReader.java#L45

此处改为：

```java
final CopyOptions copyOptions = CopyOptions.create().setIgnoreError(true);
for (Map<String, Object> map : mapList) {
	beanList.add(BeanUtil.toBean(map, this.beanClass, copyOptions));
}
```

5.7.14修改这块逻辑，感谢。
