### ISSUE TITLE
CollUtil.isEqualList 2个NULL集合的判断错误

### ISSUE THREAD

**Issue by zpj1151495891** [looly/hutool#1885]
Version 5.7.14  

  @Test
    public void test(){

        List list1 = null;
        List list2 = null;

        log.info("{}",CollUtil.isEqualList(list1,list2));   false
        log.info("{}", ListUtils.isEqualList(list1,list2));   true
    }

取自 Apache-Commons-Collections4 的方法 调换了第一个判断与第二个判断的顺序，所以出现对于2个NULL 集合的结果 不同

**Comment by CherryRum** [comment]
已提交修复https://github.com/dromara/hutool/pull/1887

**Comment by looly** [comment]
5.7.15修复，感谢。
