### ISSUE TITLE
报错无效的密文cn.hutool.crypto.CryptoException: InvalidCipherTextException: invalid cipher text

### ISSUE THREAD

**Issue by trxrjgc** [looly/hutool#1890]
cn.hutool.crypto.CryptoException: InvalidCipherTextException: invalid cipher text
        byte[] d = SmUtil.sm2().getD();
        byte[] q = SmUtil.sm2().getQ(false);
        String privateKey = HexUtil.encodeHexStr(d);
        String publicKey = HexUtil.encodeHexStr(q);
        System.out.println("私钥：" + privateKey);
        System.out.println("公钥：" + publicKey);
        SM2 sm2 = SmUtil.sm2(privateKey, publicKey);
        String cipher = sm2.encryptHex("111111", KeyType.PublicKey);
        String plaintext = sm2.decryptStr(cipher, KeyType.PrivateKey);
        System.out.println(plaintext);
报错无效的密文是什么原因啊？

**Comment by looly** [comment]
你的d和q值不是成对存在的，每次调用`SmUtil.sm2()`会生成不同的随机密钥对。

正确使用应该是：

```java
final SM2 sm2 = SmUtil.sm2();
byte[] d = sm2.getD();
byte[] q = sm2.getQ(false);
String privateKey = HexUtil.encodeHexStr(d);
String publicKey = HexUtil.encodeHexStr(q);
Console.log("私钥：" + privateKey);
Console.log("公钥：" + publicKey);

SM2 sm22 = SmUtil.sm2(privateKey, publicKey);
String cipher = sm22.encryptHex("111111", KeyType.PublicKey);
String plaintext = sm22.decryptStr(cipher, KeyType.PrivateKey);
Console.log(plaintext);
```
