### ISSUE TITLE
创建验证码底色和验证码颜色一致，导致看不清楚

### ISSUE THREAD

**Issue by hatricks** [looly/hutool#1899]
jdk版本:1.8
hutool版本:5.5.7

LineCaptcha lineCaptcha = cn.hutool.captcha.CaptchaUtil.createLineCaptcha(125, 42, 4, 12);
lineCaptcha.setFont(new Font(Font.SANS_SERIF, Font.BOLD, (int) (42 * 0.75)));
lineCaptcha.setGenerator(new RandomGenerator(BASE_CHAR + BASE_NUMBER, 4));
lineCaptcha.setTextAlpha(1f);

lineCaptcha.getCode();

获取到验证码和底色颜色一致，看不清楚（因为使用的是随机颜色所以偶尔会有颜色一致的问题）

是否可以做到   在生成验证码的时候将验证码颜色跟底色区分开

**Comment by looly** [comment]
这个没法区分，不过偶尔一个颜色冲突让用户重新刷新即可。要么就要自行实现随机颜色方法，避开背景色。
