### ISSUE TITLE
请教一下，springboot 引入hutool 和 poi 进行excel批量读取，项目启动报错：NoClassDefFoundError

### ISSUE THREAD

**Issue by zhangchao6018** [looly/hutool#1901]
我引入的依赖版本：
<artifactId>hutool-all</artifactId>： <version>5.7.14</version>
 <artifactId>poi-ooxml</artifactId>： <version>4.1.2</version>

通过降低hutool版本、排除pio的comons工具的依赖，结果仍然也一样

求大神解答

![image](https://user-images.githubusercontent.com/44044963/137718913-06ebef1e-aed1-48e2-9ab7-a4400888088d.png)

**Comment by zhangchao6018** [comment]
这个是依赖图：
![image](https://user-images.githubusercontent.com/44044963/137719554-a71931fb-491d-4e4a-94c4-45b54e469f62.png)

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/137730044-fe1793e6-aebf-4439-8c11-cc5a3302a9de.png)

**Comment by looly** [comment]
@CherryRum 其实是做了4.1.2兼容的。

@zhangchao6018 看报错是Hutool的某个类没找到，你要检查是否引入多个版本Hutool导致包冲突了。

**Comment by zhangchao6018** [comment]
> @CherryRum 其实是做了4.1.2兼容的。
> 
> @zhangchao6018 看报错是Hutool的某个类没找到，你要检查是否引入多个版本Hutool导致包冲突了。

是的  和其他引入的一个依赖有依赖冲突 已解决
