### ISSUE TITLE
url带特殊字符被转义

### ISSUE THREAD

**Issue by jsyhj1234** [looly/hutool#1904]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
url为 https://invoice.maycur.com/2b27a802-8423-4d41-86f5-63a6b259f61e.xlsx?download/2b27a802-8423-4d41-86f5-63a6b259f61e.xlsx&e=1630491088&token=cQAoIFQK1rR3_2NgfDcJu5zzTgZjGBUD-Ghot7mv%3AMzjWITFm0ixwhK8k4J6FbYmgGSk%3D&attname=HH40%E5%87%BA%E5%B7%AE%E8%AE%A1%E5%88%92.xlsx
这个链接现在是已经失效了，主要原因是download后面的/被转义成%2F，链接就变成https://invoice.maycur.com/2b27a802-8423-4d41-86f5-63a6b259f61e.xlsx?download%2F2b27a802-8423-4d41-86f5-63a6b259f61e.xlsx&e=1630491088&token=cQAoIFQK1rR3_2NgfDcJu5zzTgZjGBUD-Ghot7mv%3AMzjWITFm0ixwhK8k4J6FbYmgGSk%3D&attname=HH40%E5%87%BA%E5%B7%AE%E8%AE%A1%E5%88%92.xlsx。

**Comment by looly** [comment]
5.7.15修复此问题，是因为Hutool的QueryBuilder没有遵照`RFC3986`导致的。
