### ISSUE TITLE
使用ziputil 工具类打包到out流里时 多文件只有一个文件被打包进去 其余文件失踪

### ISSUE THREAD

**Issue by z69426** [looly/hutool#1907]
### 版本情况

JDK版本：    oracle 11.0.12
hutool版本： 5.7.14（请确保最新尝试是否还有问题）
ZipUtil.zip 打包文件后 zip包里只有一个文件 
### 问题描述（包括截图）
我这边上传不了图片 不好意思 
1. 复现代码
数组 srcFileNames和srcFiles 确定有值 
直接获取 response.getOutputStream() 返回前端
ZipUtil.zip(response.getOutputStream(), srcFileNames, srcFiles);

或者
BufferedOutputStream bos = new BufferedOutputStream(response.getOutputStream());
ZipOutputStream out = new ZipOutputStream(bos);
ZipUtil.zip(out , srcFileNames, srcFiles);
这样也没用 压缩包里还是只有一个文件

**Comment by z69426** [comment]
找到原因了 同名文件参与打包后 zip只会打包一个同名文件到zip
例如
1.txt
2.txt
3.txt
1.txt
zip 只会打包 1.txt

**Comment by looly** [comment]
2和3也会丢失么？

**Comment by z69426** [comment]
会的 最后只有1.txt 进入打包 如果所有文件名不一样的话就没有任何问题  希望可以在手册或者文档中添加说明 不知道这算bug还是特性

**Comment by z69426** [comment]
因为我是的参数out 是respones 打包后直接返回前端的 可能会出现的问题是 
在出现同名文件之前都是正常打包 出现同名文件后 他把之前的zip替换掉了 直接把文件单独打包然后跳出返回前台
只是猜测 可能打包到本地没有这种问题 我这边暂时没有条件测试

**Comment by looly** [comment]
经过测试：出现重复文件会抛出：

```java
cn.hutool.core.io.IORuntimeException: ZipException: duplicate entry: a.txt
...
Caused by: java.util.zip.ZipException: duplicate entry: a.txt
```

所以你检查下是否遇到重复文件，抛出异常你没有捕获？
