### ISSUE TITLE
关于Hutool中StopWatch的意见

### ISSUE THREAD

**Issue by LiZhenye** [looly/hutool#1910]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.6

### 问题描述（包括截图）

关于打印最后统计报告（stopWatch.prettyPrint()方法），可否提供时间单位选项，目前默认的纳秒可读性太差了

![image](https://user-images.githubusercontent.com/19367446/138548653-e81d07e1-6770-48c0-bae8-f5cbddd71439.png)

**Comment by looly** [comment]
5.7.16增加prettyPrint重载，支持传入时间单位。
