### ISSUE TITLE
合并单元格为日期时，导出单元格数据为数字

### ISSUE THREAD

**Issue by Brother-Dragon** [looly/hutool#1911]
### 版本情况

JDK版本：    1.8.0_131
hutool版本： 5.7.15

### 问题描述（包括截图）
如果合并的单元格类型为日期时，设置单元格值会将其转换为数字。
![Snipaste_2021-10-25_15-59-46](https://user-images.githubusercontent.com/76202082/138657327-4811a1fa-1f28-4df0-adb5-9f32afe2baa7.png)
复现代码

![Snipaste_2021-10-25_16-00-02](https://user-images.githubusercontent.com/76202082/138657383-08047e68-0cff-4e5c-85fa-26348d8c99ff.png)

**Comment by CherryRum** [comment]
@looly  确实是bug 应该是 5.6.4->5.6.5 引入的 ，今天业务写的有点自闭，git 历史看的不清楚，有空再看 

不知道是 5.65 是不是这段
![image](https://user-images.githubusercontent.com/24296698/138908733-37e5de0c-d7a3-4b12-923e-ea8119366319.png)
你看下 老哥

**Comment by looly** [comment]
确实是个bug，新版本中没有引用styleSet中的日期格式导致的。

5.7.16修复此问题，感谢。

**Comment by CherryRum** [comment]
> 确实是个bug，新版本中没有引用styleSet中的日期格式导致的。
> 
> 5.7.16修复此问题，感谢。

老哥 我想问下，Excel读取成为实体类时候，怎么使用注解设置生成的变量的格式 
比如时间yyyy-mm-dd
