### ISSUE TITLE
EmojiUtil个别字符不能处理

### ISSUE THREAD

**Issue by zzb980881** [looly/hutool#1919]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.6.5

### 问题描述（包括截图）
EmojiUtil不能处理方框的字符，见下图
![图片](https://user-images.githubusercontent.com/1118228/139216969-157aaa0e-a9dd-401a-9382-69b37585d354.png)

**Comment by looly** [comment]
升级最新版本的Hutool和`emoji-java`试下，此方法依赖于emoji-java

**Comment by zzb980881** [comment]
emoji-java版本是5.1.1，这个应该是emoji-java的bug，我用它的com.vdurmont.emoji.EmojiParser.removeAllEmojis这个方法也是这个问题，但我觉得既然集成到整个框架里，应该想办法修复

**Comment by looly** [comment]
@zzb980881 何不向他提个issue？：https://github.com/vdurmont/emoji-java
