### ISSUE TITLE
Map 中 有null 值  怎么在转json时把null 转为空串

### ISSUE THREAD

**Issue by blackkeai** [looly/hutool#1921]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

需要把map 中的 null 值在转为json 字符串的时候转为空串。
![82895F7302DBBFD6A5737F21295E5002](https://user-images.githubusercontent.com/7159046/139372060-27b192f8-3a93-4924-8fd2-5ac08f0399fe.jpg)

**Comment by prince052** [comment]
遇到了同样的问题，使用BeanUtil.beanToMap(object,true,true)  时无法忽略空值

**Comment by looly** [comment]
> 遇到了同样的问题，使用BeanUtil.beanToMap(object,true,true) 时无法忽略空值

BeanUtil是有效的啊，你是忽略null还是也要转换为""？

**Comment by looly** [comment]
5.7.16修改toJSONString方法：

```java
JSONObject json1 = JSONUtil.createObj(JSONConfig.create().setOrder(true).setIgnoreNullValue(false))
		.set("a", null)
		.set("b", "value2");

final String s = json1.toJSONString(0, (pair) -> {
	pair.setValue(ObjectUtil.defaultIfNull(pair.getValue(), StrUtil.EMPTY));
	return true;
});
```
