### ISSUE TITLE
Setting store方法持久化问题

### ISSUE THREAD

**Issue by dnslin** [looly/hutool#1923]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：最新

### 问题描述（包括截图）

1. 复现代码

        Setting setting = new Setting("data.setting");
        setting.setByGroup("clientId","client","88888888").store("src/main/resources/data.setting");
        String clientId = setting.getByGroup("clientId", "client");
        System.out.println("clientId==>"+clientId);

store是持久化到内存？ 如果编译器重启或者环境重启 这个持久化就失效了
能不能改为持久化到硬盘

**Comment by looly** [comment]
store方法你应该用绝对路径吧？

`src/main/resources/data.setting`实际写出是：`%classpath%/src/main/resources/data.setting`，正确的方式是store到：

```java
setting.setByGroup("clientId","client","88888888").store("data.setting");
```

当然，前提是你没有打成jar包形式。
