### ISSUE TITLE
在使用json字符串转java bean方法时能否给字段取别名？

### ISSUE THREAD

**Issue by LovelyLM** [looly/hutool#1925]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.1

### 问题描述（包括截图）

使用
![image](https://user-images.githubusercontent.com/46336155/139772592-efd13168-abd3-4983-a7d0-1762d08414d2.png)
此方法时是否可以给java类属性取别名？

**Comment by looly** [comment]
使用`@Alias`注解。

**Comment by LovelyLM** [comment]
🆗 感谢回复

**Comment by kazetyan** [comment]
> 使用`@Alias`注解。

建议加点注释或者文档中说明一下,不翻issue根本找不到这个注解

**Comment by looly** [comment]
@kazetyan 后续补充文档，感谢意见。
