### ISSUE TITLE
发送邮件无法使用代理

### ISSUE THREAD

**Issue by Peter-Zhoutuanjie** [looly/hutool#1927]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
发送邮件无法使用代理，接口是否有地方设置邮箱代理呢？大部门公司服务器都是没有外网的

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个还得依赖于`javax.mail`本身的能力：见：https://community.oracle.com/tech/developers/discussion/1589188/javamail-send-a-mail-through-a-proxy-server-answer-and-with-gmail-ssl

可以在自定义的`MailAccount.setCustomProperty`方法中添加代理相关配置。
