### ISSUE TITLE
cn.hutool.core.text.CharSequenceUtil#maxLength 逻辑问题

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#1930]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/20513615/140005188-d4989af2-f195-4ce1-8680-7f36eb23f0b7.png)

**Comment by freshgeek** [comment]
感觉这里不能根据length 去截取，而需要根据场景不同去设置，有些设备下...的字符并不是1个字符长度

**Comment by freshgeek** [comment]
只是建议，大佬决定

**Comment by looly** [comment]
你的意思是根据具体编码后的bytes截取么？这个就不是字符串的功能了，就应该用Stream或者Channel来完成了。

**Comment by c-der** [comment]
@looly 这里好像没考虑到在末尾加"..."
```
System.out.println(StrUtil.maxLength("0123456789", 5));
// 01234...
System.out.println(StrUtil.maxLength("0123456789", 5- 3));
// 01...
```
