### ISSUE TITLE
为什么UrlQuery不转义部分特殊符号呢？

### ISSUE THREAD

**Issue by starxg** [looly/hutool#1931]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
System.out.println(UrlQuery.of(":", StandardCharsets.UTF_8).build(StandardCharsets.UTF_8));
```
得到结果是: `:`

**5.7.14是没有这个问题的**

**Comment by starxg** [comment]
**5.7.14**
```java
System.out.println(UrlQuery.of("+",StandardCharsets.UTF_8).build(StandardCharsets.UTF_8));
System.out.println(UrlQuery.of(ImmutableMap.of("a","+")).build(StandardCharsets.UTF_8));
```
响应:
```text
%20
a=%2B
```

**5.7.15**
```java
System.out.println(UrlQuery.of("+",StandardCharsets.UTF_8).build(StandardCharsets.UTF_8));
System.out.println(UrlQuery.of(ImmutableMap.of("a","+")).build(StandardCharsets.UTF_8));
```
响应:
```text
%20
a=+
```


5.7.15 没有转换 `+` ，这是HTTP最新的标准吗？还是BUG引起的呢？

**Comment by looly** [comment]
见：https://datatracker.ietf.org/doc/html/rfc3986#section-3.4

```
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="

pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

query       = *( pchar / "/" / "?" )
```

**Comment by looly** [comment]
关于`+`的问题我得再查下，这个是不转义的，理论上服务端`%2B`和`+`都可以解析才对。

**Comment by starxg** [comment]
Springboot 版本: 2.2.2.RELEASE
JDK: 1.8

```java
@RestController
public class DemoController {

    @PostMapping("/demo/test")
    public Object test(String str) {
        return str;
    }
}
```

测试代码
```java
public class DemoTest {
    @Test
    public void test1() {
        Assert.assertEquals("abc+123", HttpUtil.createPost("http://localhost:7171/connector/demo/test")
                .form(ImmutableMap.of("str", "abc+123")).execute().body());
    }
}
```
**5.7.15**
```text
org.junit.ComparisonFailure: 
Expected :abc+123
Actual   :abc 123
```

**5.7.14**
测试通过

**Comment by looly** [comment]
@starxg 确实是Hutool的问题，我错误的理解了`RFC 3986`和`application/x-www-form-urlencoded`之间的关系。

关于+问题的说明见：https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

**Comment by starxg** [comment]
经过测试，当 `Content-Type` 为 `application/x-www-form-urlencoded` 或 `application/json` 时 `;:@&=+$,/?#[]` 字符也需要转义。

![1](https://user-images.githubusercontent.com/34997494/140615662-c217e967-4202-4370-83da-114593ca6b1a.png)
----
![2](https://user-images.githubusercontent.com/34997494/140615666-dd0522d2-c22d-4e5f-ab88-bfcc9634f9c6.png)

但[目前](https://github.com/dromara/hutool/tree/065c6d61c890980e4f6669d371ac1cd098731ecf)仅转义了部分字符。

![3](https://user-images.githubusercontent.com/34997494/140615675-232e1dc0-a21d-4586-a32d-cdb0216d1918.png)

测试代码：#1937

**Comment by looly** [comment]
@starxg `application/x-www-form-urlencoded`编码还是很混乱的，我测试Spring boot对于":"“@”等字符无论编码与否都可以识别。

看你的测试应该是浏览器默认都做了编码。

以防万一，Hutool在5.7.16中修改都编码这些字符吧。

---------------------------------------------------------------------------------------------------------------------------------------

5.7.16修改总结下来就是：

- 对于URL中的query参数（如GET请求 http://hutool.cn/aaa?a=b&c=d ），遵循`RFC3986`规范。
- 对于`application/x-www-form-urlencoded`按照 https://url.spec.whatwg.org/#urlencoded-serializing 遵循，具体为除了字母,数字,"-", "_", ".", "*"外，都进行编码，空格编码为`+`，`+`编码为`%2B`。

- 对于`application/json`等其他类型数据，默认不做编码，由用户自行编码，这个不变。
