### ISSUE TITLE
HttpUtil POST请求，根据请求 body 判断 ContentType 类型的分支缺失

### ISSUE THREAD

**Issue by AgeFades** [looly/hutool#1933]
### 版本情况

JDK版本：    openjdk_8_211
hutool版本： 5.5.7

### 问题描述（包括截图）
1. HttpUtil 发送 POST 请求时，默认 ContentType 为 application/json
2. 场景传入 body 为 String 类型的加密信息字符串、需要 POST 请求 ContextType 为 text/plain
3. 期望 HttpUtil 能根据请求 body 判断 ContentType 类型
4. RestTemplate.postForObject() 可以满足上述场景，可以作为参考

**Comment by looly** [comment]
看了下Spring的实现，比较复杂，Hutool还是简单粗暴：

body方法通过传入Content判断Content-Type，但是默认只能识别包括JSON和XML，`text/plain`需要你手动传入第二个参数了。
