### ISSUE TITLE
Set-Cookie 不完整

### ISSUE THREAD

**Issue by Gump0422** [looly/hutool#1936]
请求响应头中的"Set-Cookie" 不完整
HttpUtil.createGet 

![image](https://user-images.githubusercontent.com/68499299/140457800-c5746887-466e-4d3b-94c9-0b0d0368821d.png)

postman:
![image](https://user-images.githubusercontent.com/68499299/140457856-0c9a4cb7-57ca-4a83-818f-a397bce8d0d2.png)

**Comment by Gump0422** [comment]
It seems the " URLConnection" issue

**Comment by looly** [comment]
Hutool借助CookieManager完成Cookie解析。

我猜问题出在`URLConnection.getHeaderFields`，你可以手动打印下。目测同名的header会被合并为List，不过没有值，是否因为cookie格式问题导致解析失败？

可否方便提供测试的网址，我这边确认下。

我先暂时关闭issue，有后续再打开。

**Comment by Gump0422** [comment]
> Hutool借助CookieManager完成Cookie解析。
> 
> 我猜问题出在`URLConnection.getHeaderFields`，你可以手动打印下。目测同名的header会被合并为List，不过没有值，是否因为cookie格式问题导致解析失败？
> 
> 可否方便提供测试的网址，我这边确认下。
> 
> 我先暂时关闭issue，有后续再打开。

Hi, 谢谢你的回复
我debug后看到确实是 ```URLConnection.getHeaderFields```本身拿到的set-cookie就有缺失，但具体原因是什么暂时还没得到结果
