### ISSUE TITLE
Hutool.printAllUtils()

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#1939]
### 版本情况

JDK版本：    

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Hutool.printAllUtils();
```

2. 堆栈信息
无

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/26990889/140680402-9c3c39dd-59b5-4b7d-b060-b9ebb4d79f97.png)

打印的样式是不是有点问题？

**Comment by looly** [comment]
样式没问题啊，是不是你字体导致的？
