### ISSUE TITLE
SmUtil报错提示缺少GMNamedCurves文件

### ISSUE THREAD

**Issue by liao10108180** [looly/hutool#1941]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
我依赖了最新 1.56 的bouncycastle了，里面没有这个文件，请问我需要依赖哪个版本的呢？
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/asn1/gm/GMNamedCurves;
        at cn.hutool.crypto.SmUtil.<clinit>(SmUtil.java:54)
        at cn.hutool.crypto.SmUtil.sm4(SmUtil.java:189)

1. 复现代码

```java
SmUtil.sm4().encryptHex(data);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
implementation'cn.hutool:hutool-all:5.7.16'
implementation 'org.bouncycastle:bcprov-jdk15on:1.56'

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
请使用`bcprov-jdk15on`

```xml
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.69</version>
</dependency>
```
或者`bcprov-jdk15to18`
```xml
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15to18</artifactId>
    <version>1.69</version>
</dependency>
```
