### ISSUE TITLE
5.7.16 JSONUtil 转换错误

### ISSUE THREAD

**Issue by 120011676** [looly/hutool#1945]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
{"userId":["1"],"password":["e165421110ba03099a1c0393373c5b43"]}
转换内容对象不正确
应该如下
{"userId":"1","password":"e165421110ba03099a1c0393373c5b43"}

1. 复现代码

```java
System.out.println(JSONUtil.createObj()
                .append("userId", "1")
                .append("password", DigestUtil.md5Hex("233"))
                .toString());
```

2. 堆栈信息
{"userId":["1"],"password":["e165421110ba03099a1c0393373c5b43"]}

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by anaer** [comment]
看注释, append就是加的JSONArray,  可以换set方法
