### ISSUE TITLE
Assert.assertEquals(); 函数 在 5.7.16 版本 Assert 类 中 没有找到

### ISSUE THREAD

**Issue by feng-dan** [looly/hutool#1954]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Assert.assertEquals(); 函数 在 5.7.16 版本中 没有找到

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这是Junit里的方法，Hutool没有。

**Comment by feng-dan** [comment]
好的，谢谢
