### ISSUE TITLE
DB下query()方法如何返回List<Integer>结果 ?

### ISSUE THREAD

**Issue by dyxcloud** [looly/hutool#1957]
### 版本情况

JDK版本：    java8
hutool版本： 5.7.16

### 问题描述

1. 复现代码

```java
List<Integer> ids = Db.use().query("select id from physicaldevice where purchase_date < curdate() or end_of_warranty < curdate()", Integer.class);
```

2. 问题

期待返回值: [4], 实际执行sql的查询结果是这个值

实际返回值: [0]

debug发现是进入`HandleHelper#handleRow()`以普通bean的方式进行实例化的

想知道如果想要查询`List<Integer>`结果, 应该如何调用?

**Comment by looly** [comment]
那你要自己实现`RowHandler`了~
