### ISSUE TITLE
android NoClassDefFoundError

### ISSUE THREAD

**Issue by 594238813** [looly/hutool#1960]
### 版本情况

JDK版本：     
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在 安卓 6.0 设备 ，Readmi Note 4 上出现的问题
 
1. 复现代码

```
     SM2 sm2 = SmUtil.sm2(null,SM2_Key);

      ...   = sm2.encryptHex(POST_DATA,KeyType.PublicKey);
```

java.lang.NoClassDefFoundError: Failed resolution of: Lcn/hutool/core/lang/-$$Lambda$Assert$eSa13geDXfUFtcOuHoGzKFFBDCo;
	at cn.hutool.core.lang.Assert.notNull(Assert.java:216)
	at cn.hutool.crypto.asymmetric.SM2.getCipherParameters(SM2.java:547)
	at cn.hutool.crypto.asymmetric.SM2.encrypt(SM2.java:221)
	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor$-CC.$default$encrypt(AsymmetricEncryptor.java:92)
	at cn.hutool.crypto.asymmetric.AbstractAsymmetricCrypto.encrypt(AbstractAsymmetricCrypto.java)
	at cn.hutool.crypto.asymmetric.AsymmetricEncryptor$-CC.$default$encryptHex(AsymmetricEncryptor.java:104)
	at cn.hutool.crypto.asymmetric.AbstractAsymmetricCrypto.encryptHex(AbstractAsymmetricCrypto.java)

**Comment by looly** [comment]
安卓没有测试，目测是`java.util.function.Supplier`找不到，确认下android 6.0对应支持jdk1.8的类的。

**Comment by juicelover** [comment]
### vivo oppo Huawei 出现同样问题 Android 5.1 5.11 6.0  6.0.1 
版本：implementation 'cn.hutool:hutool-all:5.7.12'
更新最新版 5.8.0 依旧不行
降低版本  5.4.4  正常使用

5.1  5.1.1
cn.hutool.core.lang.-$$Lambda$Assert$eSa13geDXfUFtcOuHoGzKFFBDCo

6.0 
Didn't find class "cn.hutool.core.text.-$$Lambda$eyjfHrW56d90MXqb3v7q6gu39HI" on path: DexPathList[[zip file "/data/app/com.wzh.sjsst.activity-2/base.apk", dex file "null", dex file "null", dex file "null", dex file "null"],nativeLibraryDirectories=[/data/app/com.wzh.sjsst.activity-2/lib/arm64, /data/app/com.wzh.sjsst.activity-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]

6.0.1
Didn't find class "cn.hutool.core.lang.-$$Lambda$Assert$eSa13geDXfUFtcOuHoGzKFFBDCo" on path: DexPathList[[zip file "/data/app/com.wzh.sjsst.activity-2/base.apk", dex file "null", dex file "null", dex file "null", dex file "null"],nativeLibraryDirectories=[/data/app/com.wzh.sjsst.activity-2/lib/arm64, /data/app/com.wzh.sjsst.activity-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]

**Comment by looly** [comment]
@juicelover 同理。目测应该是你们安卓的JDK版本太低的问题。请确认是否兼容JDK8。

**Comment by juicelover** [comment]
项目已经设置了
`
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
`
