### ISSUE TITLE
cn.hutool.core.lang.Assert（v5.4.3）isTrue和isFalse的用法疑问

### ISSUE THREAD

**Issue by chengzhezhijian** [looly/hutool#1964]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/6291019/142960835-d20ff29f-a94a-4f3b-a6f9-f8eab716e7ef.png)

1. 复现代码

```java
Console.log("报错了");
```
cn.hutool.core.lang.Assert类中
isTrue的用法我认为应该是expression=true触发抛出异常，符合常理
isFalse的用法注释提示是expression=true触发抛出异常，但是代码却是expression=false才触发异常

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个对应Junit的`Assert.assertTrue`

逻辑没问题。
