### ISSUE TITLE
如何只读取表头不读取数据

### ISSUE THREAD

**Issue by qianzzbatt** [looly/hutool#1966]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
貌似只能根据行来读取
```java
ExcelReader reader = ExcelUtil.getReader(file);
List<Object> header = reader.readRow(0);
```
