### ISSUE TITLE
StrUtil.sub("123456789", -1, -6)=345678,通过负索引获取数据永远无法获得最后一个字符

### ISSUE THREAD

**Issue by folochina** [looly/hutool#1967]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
StrUtil.sub("123456789", -1, -6)
StrUtil.subWithLength("123456789", -1, 6)
![image](https://user-images.githubusercontent.com/11660951/143401861-e6fe5dae-a42e-4c5e-b855-703bb8b44f3f.png)
![image](https://user-images.githubusercontent.com/11660951/143402008-62679c43-dfae-46c5-9699-0951b6cb8d6d.png)
通过负索引获取数据永远无法获得最后一个字符
-1时缺少最后一位字符，为0时则从最前面获取

1. 复现代码
```java
System.out.println(StrUtil.sub("123456789", -1, -6));
System.out.println(StrUtil.subWithLength("123456789", -1, 6));
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
对的，有意这么设计的。

理论上 开始位置表示`0`，结果位置既是`length`，也是`-0`，可惜`-0`和`0`表示一个意思，导致无法取得最后一个字符。

因此这里老老实实用`str.length()`吧。

**Comment by folochina** [comment]
嗯，我已改用subSufByLength尾部截取

**Comment by baoerzhang** [comment]
> 

那就在文档里说清楚啊，还洋洋得意地说【-1表示最后一个字符（这个思想来自于[Python](https://www.python.org/)，如果学过[Python](https://www.python.org/)的应该会很喜欢的）】，真是坑人

**Comment by looly** [comment]
@baoerzhang 我想你对截取和索引的理解有误。

-1表示最后一个字符没错，python中获取最后一个字符可以是`str[-1]`。

```java
String[] a = {"a", "b", "c"};
final Object o = ArrayUtil.get(a, -1);
```

`-1表示最后一个字符`这句话本身没有错误，只不过StrUtil.sub遵循了JDK的包含模式：

>the ending index, exclusive.

也就是说end对应的字符是不包含的，因此使用`-1`无法截取到。同样你可以运行Python代码试下：

```python
a = "abcde"
print(a[0:-1])
```

最后一个字符也是取不到的。

文档这块我做个说明吧，可能写的不够详细。
