### ISSUE TITLE
test fail : NegativeArraySizeException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1974]
unit test failed for method range
![image](https://user-images.githubusercontent.com/44200574/143555890-c8554e5e-6097-4e64-912d-6d97e9bbfa32.png)
![image](https://user-images.githubusercontent.com/44200574/143556705-edacc957-e1c9-4514-87ee-8b14e5ed707b.png)

This is a special case.
0 - Integer.MIN_VALUE = Integer.MIN_VALUE ,so the length < 0 in code

**Comment by looly** [comment]
事实上使用`Integer.MIN_VALUE`之后总长度已经超过`Integer.MAX_VALUE`，无论如何也会报错的。

这块抛出异常是对的。
