### ISSUE TITLE
test fail: throw StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1975]
JDK：    openjdk_8_201
hutool： 5.7.16

for method normalizeParams
![image](https://user-images.githubusercontent.com/44200574/143558732-e3397e88-cee8-43f1-8544-41ae901fa8dc.png)
 we generate unit test case:
![image](https://user-images.githubusercontent.com/44200574/143558837-89abdc3f-9e5e-4b06-a5bf-5df0c4db8246.png)
the reason is you throw exception in method StrBuilder.charAt. But you don't catch or throw again in method normalizeParams.
We think you should catch or throw, not do nothing for the soundness.

**Comment by looly** [comment]
5.7.17修复此问题，增加了一个判空。
