### ISSUE TITLE
Rest请求中，GET请求附带body导致GET请求被强制转换为POST

### ISSUE THREAD

**Issue by yangzcp** [looly/hutool#1976]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
HttpRequest request = HttpUtil.createRequest(xx)
request.body(xxxx);
request.execute();
```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
https://github.com/dromara/hutool/issues/1740

**Comment by looly** [comment]
这个确实没办法。只能更换HttpClient了~~

**Comment by soulCoke** [comment]
hutool 底层http 请求这块有考虑更换  httpClient 吗？httpUtils用的很爽，因为这一个瑕疵换了好可惜

**Comment by looly** [comment]
@soulCoke Hutool大部分基于JDK封装的，这个JDK导致的问题也无法通过魔改完成。封装第三方在考虑中。

**Comment by sunupo** [comment]
5.8.26 是不是已经修复了。 现在 httprequest.get请求附带body，GET请求无法被强制转换为POST
