### ISSUE TITLE
test fail: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1978]
JDK版本：    openjdk_8_201
hutool版本： 5.7.16

 对方法 `ThreadUtil.getStackTraceElement` 生成的单元测试失败了

![image](https://user-images.githubusercontent.com/44200574/143798419-6773ee64-7dcd-495e-b84a-070b6304b9f1.png)

![image](https://user-images.githubusercontent.com/44200574/143797312-44c008ea-13ea-4e1e-8451-739054523ce5.png)

如果参数值 i<0, 且 i+= stackTrace.length; i < 0, 就会出错
总之，在调用stackTrace[i]时 应判断i和  stackTrace.length 的关系；
否则，是否告知使用者参数i的范围？

**Comment by looly** [comment]
这个告知我觉得也是没有意义的，因为你不知道堆栈到底实际有多长。

举个例子，你这里传入一个很大的数字会报错，但是在实际环境中，如果堆栈特别长，就不会报错。

此处抛出这个异常是没有问题的。
