### ISSUE TITLE
test fail : throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1980]
JDK版本：    openjdk_8_201
hutool版本： 5.7.16

测试用例失败
![image](https://user-images.githubusercontent.com/44200574/143799543-a17ef304-2c5e-4b33-b261-015d063eef3d.png)

![image](https://user-images.githubusercontent.com/44200574/143799583-46f0209c-3d63-4755-9b44-17890e7b6b4b.png)

这是public static 方法，因此也许您应该告知函数参数应满足的要求，或者要在函数体内考虑参数所有可能的情况

**Comment by looly** [comment]
Hash算法本身是一种很特别的数字计算方式，这里如果增加校验，那会消耗很多的性能，毕竟hash算法调用频率非常高。

此处抛出异常是没有问题的。
