### ISSUE TITLE
test fail: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1981]
JDK版本：    openjdk_8_201
hutool版本： 5.7.16

![image](https://user-images.githubusercontent.com/44200574/143800209-55a6200a-f66c-4dbb-b438-b347dc7b5deb.png)

![image](https://user-images.githubusercontent.com/44200574/143800437-ffd963cb-220f-4566-bd95-a4fb7d229747.png)
在调用`System.arraycopy(value, srcBegin, dst, dstBegin, srcEnd - srcBegin);` 之前，是否需要判断5个参数要满足的关系？否则，很容易导致异常发生。

**Comment by looly** [comment]
这块抛出异常没有问题，可以看下JDK的`AbstractStringBuilder`，getChars方法也没有判断。

**Comment by suoyi123wang** [comment]
您好，我去查了一下最新的jdk AbstractStringBuilder的getChars方法：
![image](https://user-images.githubusercontent.com/44200574/144033562-6ee22153-43bc-40cb-add5-dc8ba2f496ee.png)

它检查了参数需要满足的关系。若不满足，将会抛出异常。

**Comment by looly** [comment]
@suoyi123wang 看来还是我的JDK比较旧。

这块暂时不变了，后续我觉得StrBuilder考虑要弃用了，JDK的StringBuilder更新之后基本完善了，无需自己实现了。
