### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [looly/hutool#1982]
JDK版本：    openjdk_8_201
hutool版本： 5.7.16

单元测试用例失败
![image](https://user-images.githubusercontent.com/44200574/143800981-f5630182-88cb-4cc0-8e9e-27b29b5a7dde.png)

![image](https://user-images.githubusercontent.com/44200574/143801018-24566f53-3aab-439a-8ab2-b0f5cd8be524.png)

**Comment by looly** [comment]
嗯……这个方法不应该为public，5.7.17改为private~~

因为调用这个方法前已经判断是否是固定的几个算术运算符。
