### ISSUE TITLE
url后面信息丢失

### ISSUE THREAD

**Issue by SeriousMa** [looly/hutool#1989]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16

### 问题描述
url 后面信息 imageMogr2/thumbnail/x800/format/jpg 丢失

1. 复现代码

```java
 HttpRequest httpRequest = HttpRequest.get("http://ci.xiaohongshu.com/spectrum/c136c98aa2047babe25b994a26ffa7b492bd8058?imageMogr2/thumbnail/x800/format/jpg");
        HttpResponse execute = httpRequest.execute();
```

2. 堆栈信息
![image](https://user-images.githubusercontent.com/464213/144169139-62db868b-de1b-4fc4-95a4-09e24647bea9.png)

**Comment by looly** [comment]
确实，这个query部分太特殊了，被当作url的一部分了。

5.7.17修复此问题，感谢。
