### ISSUE TITLE
RuntmeUtil 中存在挂起的风险

### ISSUE THREAD

**Issue by 284970624** [looly/hutool#199]
下面的方法中，只读取了正常的Inputstream信息，实际上应该同时要读取getErrorStream()，否则某些操作系统的输入流缓存大小有限制，一旦缓存满了会导致进程会挂起

/**
	 * 获取命令执行结果，获取后销毁进程
	 * 
	 * @param process {@link Process} 进程
	 * @param charset 编码
	 * @return 命令执行结果列表
	 * @since 3.1.2
	 */
	public static String getResult(Process process, Charset charset) {
		InputStream in = null;
		try {
			in = process.getInputStream();
			return IoUtil.read(in, charset);
		} finally {
			IoUtil.close(in);
			destroy(process);
		}
	}

**Comment by looly** [comment]
在RuntimeUtil中，默认设置了：

```
process = new ProcessBuilder(cmds).redirectErrorStream(true).start();
```

其中`redirectErrorStream`设置为true后，error部分的流数据会转发到普通流中，因此不必处理。

**Comment by looly** [comment]
4.1.21会增加getErrorResult，用于用户自定义获取结果使用。
