### ISSUE TITLE
http自动编码导致请求404

### ISSUE THREAD

**Issue by parkerisme** [looly/hutool#1990]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

Http的url会被编码，比如特殊字符:，url为：http://xxx:xxx1/sfsf。xxx:xxx1中间的:被编码，导致无法正常请求。能不能把是否编码参数放开？让自己选择是否编码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
升级5.7.16改进了编码。
