### ISSUE TITLE
同一条命令，JschUtil.execByShell 一直处于阻塞状态，JschUtil.exec没问题。

### ISSUE THREAD

**Issue by iamxiaojianzheng** [looly/hutool#1991]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.13（请确保最新尝试是否还有问题）

JschUtil.exec(session, "echo $JAVA_HOME", StandardCharsets.UTF_8); // 没问题

JschUtil.execByShell (session, "echo $JAVA_HOME", StandardCharsets.UTF_8); // 一直阻塞没有返回

**Comment by looly** [comment]
第二方法默认使用`ChannelShell`执行，可能是交互式环境造成的，你可以查阅JSCH相关资料。
