### ISSUE TITLE
apk文件解析MimeType出错

### ISSUE THREAD

**Issue by bloomL** [looly/hutool#1993]
### 版本情况

JDK版本：    openjdk11
hutool版本： 5.5.4 、5.7.2

### 问题描述（包括截图）

1. 复现代码

```java
String url = null;
HttpRequest request = HttpRequest.post(url);
request.form("apkFile", new File("F:/Project/1638436519181056152_base_1638436504624.apk"));
try {
    request.execute().body();
}catch (Exception e){
    e.printStackTrace();
}
```

2. 堆栈信息
在**5.5.4**的版本下，通过getMimeType()能获取**默认MimeType**；
然而在**5.7.2**版本下，通过getMimeType()出现**IO异常**
![image](https://user-images.githubusercontent.com/43021146/144551367-003cc7da-8584-4e6f-8c3b-e70afeb19897.png)

**Comment by looly** [comment]
我这里返回null。

升级5.7.16试下。
