### ISSUE TITLE
hutool 国密算法长度不符合规范

### ISSUE THREAD

**Issue by keenorchen** [looly/hutool#1994]
### 版本情况
JDK版本：    openjdk_8_201
hutool版本： 5.7.16

### 问题描述（包括截图）
根据国密规范，SM2公钥长度64字节，私钥长度32字节，但是使用hutool的库，算出来的公私钥长度都不对！

![image](https://user-images.githubusercontent.com/12131613/144556797-e9650c55-0550-4e4b-87d4-7d24dd5f1d7e.png)

不知道什么原因

**Comment by CherryRum** [comment]
请提供代码

**Comment by keenorchen** [comment]
代码就是你们官方文档提供的，如下：

2. 使用自定义密钥对加密或解密
String text = "我是一段测试aaaa";

KeyPair pair = SecureUtil.generateKeyPair("SM2");
byte[] privateKey = pair.getPrivate().getEncoded();
byte[] publicKey = pair.getPublic().getEncoded();

**Comment by CherryRum** [comment]
首先 哪两个并不是sm2算法的公钥和私钥（某种意义上也算），但是不是您理解的，`SM2公钥`长度`64字节`，`私钥`长度`32字节`

sm2算法其实是ecc加密的一种实现，选择了一种自己的椭圆曲线和其他的实现
```java
//生成了一个符合 PKCS#8规范私钥
byte[] privateKey = pair.getPrivate().getEncoded();
//生成了一个符合 X509规范的公钥
byte[] publicKey = pair.getPublic().getEncoded();
```


而您说的应该是
```java
public class testSM {
	public static void main(String[] args) {
		SM2 sm2 = SmUtil.sm2();
		byte[] d = sm2.getD();
		byte[] q = sm2.getQ(false);
		String privateKey = HexUtil.encodeHexStr(d);
		String publicKey = HexUtil.encodeHexStr(q);
		Console.log(MessageFormat.format("私钥：{0} len:{1}", privateKey, privateKey.length()));
		Console.log(MessageFormat.format("公钥：{0} len:{1}", publicKey, publicKey.length()));

	}
}
```
结果是
```
私钥：6bb09db6d9a21427be11d9073b35c324622a505bd3ba8f18bc90cc9fe8a23609 len:64
公钥：04c91d59235852ee2e3947cb6db1c2cf88bf0e38004199f0d6d823a98e05d84ab82b37bdd8ef80edcae6c70f78a522b087bef5948cfc2877528b0ccd045d616e24 len:130

```

是不是想问为啥公钥是`65字节`因为`SM2`非压缩公钥格式字节串长度为65字节,前缀0x04区分未压缩公钥

**Comment by keenorchen** [comment]
SM2的来历，前缀04我也是知道的，只是hutool生成的公私钥长度跟其他大多工具类都不一样，一般的都是标准的32位私钥

**Comment by CherryRum** [comment]
那我看您看的也不是hex编码的呀，既然不是，怎么会有不统一的情况呢，hutool包装的是bc库，大部分都是基于bc库ecc生成的，上面代码应该没什么问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月6日(周一) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] hutool 国密算法长度不符合规范 (Issue #1994)




 
SM2的来历，前缀04我也是知道的，只是hutool生成的公私钥长度跟其他大多工具类都不一样，一般的都是标准的32位私钥
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
@keenorchen https://github.com/dromara/hutool/issues/2001 看下这个issue是不是这个问题？

**Comment by keenorchen** [comment]
一个字节对应两个hex编码字符，国密标准规定了私钥是32个字节，自然也就是64个hex字符。公钥本质是一个点的x、y的值，因此是64个字节（去掉04这个字节），是私钥的两倍长度。我同时也用了github上其他的加密库，也都是国密标准，也就是D、Q的值。

**Comment by CherryRum** [comment]
所以，我给您的代码的确是32字节的呀。您有什么不一样的吗？


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月6日 14:12:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] hutool 国密算法长度不符合规范 (Issue #1994)




 
一个字节对应两个hex编码字符，国密标准规定了私钥是32个字节，自然也就是64个hex字符。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by keenorchen** [comment]
getPrivate()和getPublic() 却是PKCS#8和X.509格式的公私钥，我不太懂这种格式，只是不明白hutool这样子做的目的，有点反常规，也不通用，毕竟我们一般用的是国密标准（32位私钥和64位公钥）的公私钥对。

**Comment by CherryRum** [comment]
这个是标准给定的，而您说的32位和64位是大众传播导致的误区，因为sm2(商密算法)，其实不能算一种单独的算法，他属于ecc(椭圆曲线加密)，而这个加密算法有很多标准，sm2 工具可以直接指定公钥和私钥，按照您说的32字节和64字节，hutool封装了多个方式来获取公钥和私钥(其中您使用的就是bc库获取的一种)，其实，不论什么格式，您要理解的是，sm2的私钥其实就是一个很大的整数，然后把这个整数变成hex编码，就是sm算法中提到的32字节，具体的要参考国标。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月6日(周一) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] hutool 国密算法长度不符合规范 (Issue #1994)




 
getPrivate()和getPublic() 却是PKCS#8和X.509格式的公私钥，我不太懂这种格式，只是不明白hutool这样子做太反常了，毕竟我们一般用的是国密标准（32位私钥和64位公钥）的公私钥对。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by keenorchen** [comment]
在国密官网阅读了国标，详见http://www.gmbz.org.cn/main/viewfile/2018011001400692565.html。其中明确提到公私钥长度，而并非大众传播的误区。SM2算法就是设计了一条ECC命名曲线，具体标准见：
![image](https://user-images.githubusercontent.com/12131613/144802132-eec1a638-cf94-46a6-ad98-9cde6bb6a686.png)
![image](https://user-images.githubusercontent.com/12131613/144802156-d00ab735-21e5-4361-b9ef-c122ae83fc2d.png)
标准里面提到的256位，换算下来就是64位字节。

**Comment by keenorchen** [comment]
而且第三方在线加密，给的同样是符合标准的公私钥，例如：https://i.goto327.top/CryptTools/SM2.aspx   
![image](https://user-images.githubusercontent.com/12131613/144802436-3639cbdf-7085-46a3-bd0f-409db14c185d.png)
因此：`        SM2 sm2 = SmUtil.sm2();
        byte[] encodedPk = sm2.getPrivateKey().getEncoded();
`  算出的私钥，应该是32位的字节，而不应该是91个字节的ECC PKCS 格式

**Comment by CherryRum** [comment]
话说 您还是没理解咱们讨论的不一样吗？
假如您想获取sm2的公钥和私钥,调用如下的d和q就算出来了
```java
byte[] d = sm2.getD();
		byte[] q = sm2.getQ(false);
		String privateKey = HexUtil.encodeHexStr(d);
		String publicKey = HexUtil.encodeHexStr(q);
```

而对于某些硬件加密需要对接，可能才要获取ecc椭圆加密的算法的公钥还有私钥，这样才需要使用继承父类得到的方法，一方面sm2就是依赖椭圆曲线加密产生的算法，ecc自身也有自己的公钥和私钥。

您的意思是`.getPrivateKey().getEncoded();`不要继承父类ecc之类的问题吗？ 
还是使用中出现的其他问题？

**Comment by CherryRum** [comment]
话说是我没说清楚 还是您没运行我提供的代码

**Comment by CherryRum** [comment]
其他工具 只给您提供sm2 的公钥和私钥可能有其中抉择，比较简单，但是国密对接是一个很坑过程，有的使用硬件加密（der编码的公钥），有的使用软加密就是咱们说的，还有的奇奇怪怪的对接，所以一个工具不能和所有人保持一样的，大部分人没能力实现一遍这个算法(近世代数和数论太难了)，bc库是一个很权威的加密库在`java`和`c#`方法

**Comment by CherryRum** [comment]
> 私钥：6bb09db6d9a21427be11d9073b35c324622a505bd3ba8f18bc90cc9fe8a23609 len:64
> 公钥：04c91d59235852ee2e3947cb6db1c2cf88bf0e38004199f0d6d823a98e05d84ab82b37bdd8ef80edcae6c70f78a522b087bef5948cfc2877528b0ccd045d616e24 len:130

32字节私钥和64字节公钥

**Comment by keenorchen** [comment]
我运行了你给的代码，
`        byte[] encodedPk = sm2.getD();
        String sk = HexUtil.encodeHexStr(encodedPk);
        byte[] encodedSk = sm2.getQ(false);
        String pk = HexUtil.encodeHexStr(encodedSk);
`
只是 hutool 官方文档并没有给出上面这种实际开发中用的最多的形式，因此我默认使用了` getPrivateKey().getEncoded();  ` 以至于造成了很大的困惑，我虽然懂一些基础的ECC RSA知识，但是对于 PKCS DER X509 之类的就不懂了。

因此，我还是希望hutool能采用常规API，避免造成困惑。
另外，也建议把 ` sm2.getD();    sm2.getQ(false);`  补充到官网文档中，不然很容易疑惑。

**Comment by CherryRum** [comment]
等我最近病假休息好，我把这部分补充下。

**Comment by changhr2013** [comment]
PKCS#8，指代的是 Private-Key Information Syntax Specification Version 1.2，参考 [RFC-5208](https://www.rfc-editor.org/rfc/rfc5208)，即 私钥信息语法标准，是一种国际标准，规定了私钥的打包语法规范。

X.509，一般指代的是  Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile，参考 [RFC 3280](https://www.ietf.org/rfc/rfc3280.txt)，规定了公钥基础设施规范。

这两类都是国际标准化组织定义的标准，目前 Java 和 Bouncy Castle 的默认实现都是以这两种标准为准。

具体可以查看 JDK 的 `java.security.Key` 接口说明。

在 `String getFormat()` 上有这么一段描述：

> Returns the name of the primary encoding format of this key, or null if this key does not support encoding. The primary encoding format is named in terms of the appropriate ASN.1 data format, if an ASN.1 specification for this key exists. For example, the name of the ASN.1 data format for **public keys is SubjectPublicKeyInfo, as defined by the X.509 standard**; in this case, the returned format is "X.509". Similarly, the name of the ASN.1 data format for **private keys is PrivateKeyInfo, as defined by the PKCS#8 standard**; in this case, the returned format is "PKCS#8".

Hutool 目前是对 JCE 和 Bouncy Castle 的薄封装，因此对于 SM2 算法的 Key 实现是依赖于 BC 的 `BCECPrivateKey` 和 `BCECPublicKey`，这两个类的 `getFormat()` 默认实现就是 `PKCS#8` 和 `X.509`。你调用的 `getEncoded()` 方法实际上是透传到这两个 Key 实现类的方法，因此编码都是遵循的国际通行标准。

SM2 算法从 ECC 算法衍生而来，因此公私钥选取方式是跟 ECC 一致的，国际通行标准旨在屏蔽算法之间的差异，因此 SM2 做国际化时，理论上也会遵循现有的国际通行编码标准。

当然，在一些算法确认的系统中，使用原始编码能减少一些密钥传输和存储的开销，这就是系统设计的话题了。

编码与密钥并不冲突，你可以把 32 个字节的裸字节称之为 PrivateKey，在经过 PKCS#8 编码后，它还是可以称之为 PrivateKey，只是在你将一个 `PKCS#8` Key 和一个裸字节 Key 传递给其他人时，PKCS#8 中已经包含了密钥的算法、参数等一系列信息，具有自描述能力，而裸字节 Key，你还需要将自己使用的算法、参数等一系列信息作为附加项传递给对方，这就是标准化的作用。

**Comment by CherryRum** [comment]
。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月31日(周四) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] hutool 国密算法长度不符合规范 (Issue #1994)




 
PKCS#8，指代的是 Private-Key Information Syntax Specification Version 1.2，参考 RFC-5208，即 私钥信息语法标准，是一种国际标准，规定了私钥的打包语法规范。
 
X.509，一般指代的是  Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile，参考 RFC 3280，规定了公钥基础设施规范。
 
这两类都是国际标准化组织定义的标准，目前 Java 和 Bouncy Castle 的默认实现都是以这两种标准为准。
 
具体可以查看 JDK 的 java.security.Key 接口说明。
 
在 String getFormat() 上有这么一段描述：
  
Returns the name of the primary encoding format of this key, or null if this key does not support encoding. The primary encoding format is named in terms of the appropriate ASN.1 data format, if an ASN.1 specification for this key exists. For example, the name of the ASN.1 data format for public keys is SubjectPublicKeyInfo, as defined by the X.509 standard; in this case, the returned format is "X.509". Similarly, the name of the ASN.1 data format for private keys is PrivateKeyInfo, as defined by the PKCS #8 standard; in this case, the returned format is "PKCS#8".
  
Hutool 目前是对 JCE 和 Bouncy Castle 的薄封装，因此对于 SM2 算法的 Key 实现是依赖于 BC 的 BCECPrivateKey 和 BCECPublicKey，这两个类的 getFormat() 默认实现就是 PKCS#8 和 X.509。你调用的 getEncoded() 方法实际上是透传到这两个 Key 实现类的方法，因此编码都是遵循的国际通行标准。
 
SM2 算法从 ECC 算法衍生而来，因此公私钥选取方式是跟 ECC 一致的，国际通行标准旨在屏蔽算法之间的差异，因此 SM2 做国际化时，理论上也会遵循现有的国际通行编码标准。
 
当然，在一些算法确认的系统中，使用原始编码能减少一些密钥传输和存储的开销，这就是系统设计的话题了。
 
编码与密钥并不冲突，你可以把 32 个字节的裸字节称之为 PrivateKey，在经过 PKCS#8 编码后，它还是可以称之为 PrivateKey，只是在你将一个 PKCS#8 Key 和一个裸字节 Key 传递给其他人时，PKCS#8 中已经包含了密钥的算法、参数等一系列信息，具有自描述能力，而裸字节 Key，你还需要将自己使用的算法、参数等一系列信息作为附加项传递给对方，这就是标准化的作用。
