### ISSUE TITLE
CellUtil.setCellValue(Cell cell, Object value, CellStyle style)未设置值

### ISSUE THREAD

**Issue by Silas-Zhu** [looly/hutool#1995]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
当style为空时，不会设置value的值，也不会去默认的样式，与描述不符， 是从https://github.com/dromara/hutool/commit/b5145a0bac9a572ca4678752b7114dded7d0429e#diff-7aac6cc7b9f01041909ec8a1983fa0eaefe4c8413f3d5bfb33d76a8c6b7305ec这个版本开始的

```java
	/**
	 * 设置单元格值<br>
	 * 根据传入的styleSet自动匹配样式<br>
	 * 当为头部样式时默认赋值头部样式，但是头部中如果有数字、日期等类型，将按照数字、日期样式设置
	 *
	 * @param cell  单元格
	 * @param value 值
	 * @param style 自定义样式，null表示无样式
	 */
	public static void setCellValue(Cell cell, Object value, CellStyle style) {
		setCellValue(cell, (CellSetter) cell1 -> {
			if (null != style) {
				cell1.setCellStyle(style);
				setCellValue(cell, value);
			}
		});
	}
```

**Comment by looly** [comment]
这是个bug，样式不应该影响值的设置。

5.6.17修复，感谢。
