### ISSUE TITLE
StrUtil.toUnderlineCase的问题

### ISSUE THREAD

**Issue by naimehao** [looly/hutool#1997]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public class A
{
    public static void main(String[] args)
    {
        String s = StrUtil.toUnderlineCase("XGH_ID");
        System.out.println(s);//XGH_I_d
    }
}
```

在5.4.7版本中，是这样的：
```java
public class A
{
    public static void main(String[] args)
    {
        String s = StrUtil.toUnderlineCase("XGH_ID");
        System.out.println(s);//XGH_ID
    }
}
```

这样的改动已经会影响到原有的业务，其实我也不想更新jar包的😂，只是json那边有个bug是后面版本才修复的。
请问这个改动是出于什么考虑呢？感觉不太合理😂

***

翻了一下更新记录
找到了这个：
https://gitee.com/dromara/hutool/issues/I40CGS

**Comment by looly** [comment]
此方法的本意是驼峰转下划线，如果你本身就是下划线，会导致结果不是预期的。

这块建议手动完成。
