### ISSUE TITLE
pinyinUtils问题求解

### ISSUE THREAD

**Issue by shallwetalkge** [looly/hutool#2003]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.7

### 问题描述（包括截图）
K8S环境下拼音包报[Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com.github.promeg.pinyinhelper.Pinyin] with root cause java.lang.ClassNotFoundException: com.github.promeg.pinyinhelper.Pinyin
1. 复现代码

```java
PinyinUtil.getFirstLetter(value,"");
```
```pom.xml
        <dependency>
            <groupId>com.github.stuxuhai</groupId>
            <artifactId>jpinyin</artifactId>
            <version>1.1.8</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.7</version>
        </dependency>

```
2. 堆栈信息
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/github/promeg/pinyinhelper/Pinyin] with root cause java.lang.NoClassDefFoundError: com/github/promeg/pinyinhelper/Pinyin
	at cn.hutool.extra.pinyin.engine.tinypinyin.TinyPinyinEngine.getPinyin(TinyPinyinEngine.java:53) ~[hutool-all-5.7.7.jar!/:?]
	at cn.hutool.extra.pinyin.PinyinEngine.getFirstLetter(PinyinEngine.java:52) ~[hutool-all-5.7.7.jar!/:?]
	at cn.hutool.extra.pinyin.PinyinUtil.getFirstLetter(PinyinUtil.java:73) ~[hutool-all-5.7.7.jar!/:?]

**Comment by looly** [comment]
因为PinyinUtil只是一个门面，因此需要引入任意一个第三方的拼音库，见：https://hutool.cn/docs/#/extra/%E6%8B%BC%E9%9F%B3/%E6%8B%BC%E9%9F%B3%E5%B7%A5%E5%85%B7-PinyinUtil

**Comment by shibor** [comment]
我应经收到你的邮件！

**Comment by qyx-git** [comment]
感谢您的来信,您的邮件已被我成功接收.

**Comment by dnslin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by shallwetalkge** [comment]
详细已经在issues中说明，已经引入，仍然会报错，在k8s中部署会引发错误，本地启动没有错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] pinyinUtils问题求解 (Issue #2003)





 
因为PinyinUtil只是一个门面，因此需要引入任意一个第三方的拼音库，见：https://hutool.cn/docs/#/extra/%E6%8B%BC%E9%9F%B3/%E6%8B%BC%E9%9F%B3%E5%B7%A5%E5%85%B7-PinyinUtil
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shallwetalkge** [comment]
文档列举的三个库都已经尝试过，同样本地不报错，部署上K8后就会报这样的错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] pinyinUtils问题求解 (Issue #2003)





 
因为PinyinUtil只是一个门面，因此需要引入任意一个第三方的拼音库，见：https://hutool.cn/docs/#/extra/%E6%8B%BC%E9%9F%B3/%E6%8B%BC%E9%9F%B3%E5%B7%A5%E5%85%B7-PinyinUtil
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
@shallwetalkge 是不K8虚拟环境中JDK版本问题（如JDK版本太高，导致第三方库的模块没有加载导致）。

**Comment by shallwetalkge** [comment]
您好，经验证，k8环境使用容器为adoptopenJDK，java版本为8，在经过ServiceLoaderUtil.loadFirstAvailable的时候，空构造函数会导致catch不到异常，今晚下了最新代码准备修复，发现该问题已经被修复，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] pinyinUtils问题求解 (Issue #2003)





 
@shallwetalkge 是不K8虚拟环境中JDK版本问题（如JDK版本太高，导致第三方库的模块没有加载导致）。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
