### ISSUE TITLE
请教一下，如何使用HttpUtil上传文件二进制，在body中

### ISSUE THREAD

**Issue by seepine** [looly/hutool#2007]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

这是我通过httpClient上传
```java
HttpRequestBase baseReq = new HttpPut(url);
((HttpEntityEnclosingRequest) baseReq)
        .setEntity(new ByteArrayEntity(outputStream.toByteArray()));
```

当我使用hutool的http，虽然body有接收byte[]的方法，但是好像不支持文件
```java
HttpUtil.createRequest(url)
            .body(outputStream.toByteArray())
```

**Comment by looly** [comment]
二进制流的发送取决于你服务端如何接收，可能的接收方式：

1. multipart模式，使用文件上传方式即可，见：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0

2. bytes经过转义（如转为hex或者base64）服务端解析，此时使用body即可。

**Comment by seepine** [comment]
> 二进制流的发送取决于你服务端如何接收，可能的接收方式：
> 
> 1. multipart模式，使用文件上传方式即可，见：https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil?id=%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0
> 2. bytes经过转义（如转为hex或者base64）服务端解析，此时使用body即可。

我是想问...........
这是我通过httpClient上传
```
HttpRequestBase baseReq = new HttpPut(url);
((HttpEntityEnclosingRequest) baseReq)
        .setEntity(new ByteArrayEntity(outputStream.toByteArray()));
```

当我使用hutool的http，应该如何写，我使用如下代码，文件无法上传
```
HttpUtil.createRequest(url)
            .body(outputStream.toByteArray())
```

**Comment by looly** [comment]
@seepine 如果是这样确实使用body方法应该是可以的。你有没有设置content-type？

方便的化提供下URL我这边测试。

**Comment by seepine** [comment]
> @seepine 如果是这样确实使用body方法应该是可以的。你有没有设置content-type？
> 
> 方便的化提供下URL我这边测试。

请稍等明天给你，文件接口等数据都在公司

**Comment by looly** [comment]
@seepine 我记得你在QQ群里，QQ私聊发我即可。

**Comment by looly** [comment]
讨论结果：
URL中其实问题出在其中的%2B，你们的URL转义了，这个应该是+，hutool做了反转义（因为+是无需转义的）

可以：
```java
final HttpRequest request = new HttpRequest(UrlBuilder.ofHttpWithoutEncode(url));
request.body(xxx.getBytes());
```
