### ISSUE TITLE
Could not connect to SMTP host: smtp-mail.outlook.com, port: 587, response: -1

### ISSUE THREAD

**Issue by liangxp** [looly/hutool#2008]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.7.16

### 问题描述（包括截图）

1. 复现代码

```java
MailAccount account = new MailAccount();
            account.setHost("smtp-mail.outlook.com");
            account.setPort(587);
            account.setFrom("xxx@outlook.com");
            account.setPass("pass");
            account.setSslEnable("false");
            account.setAuth(true);
            MailSSLSocketFactory sf = new MailSSLSocketFactory();
            sf.setTrustAllHosts(true);
            account.setCustomProperty("mail.smtp.ssl.socketFactory", sf);
            account.setDebug(true);
            account.setStarttlsEnable(true);
            String result = Mail.create(account)
                    .setTos(to)
                    .setTitle(subject)
                    .setContent(content)
                    .setHtml(true)
                    .send();
```

2. 堆栈信息
cn.hutool.extra.mail.MailException: MessagingException: Could not connect to SMTP host: smtp-mail.outlook.com, port: 587, response: -1
	at cn.hutool.extra.mail.Mail.send(Mail.java:398)
	at cn.com.xxx.identity.common.utils.SendMailUtil.sendHtml(SendMailUtil.java:52)
	at cn.com.xxx.identity.web.controller.system.SysMessageController.sendTestMsg(SysMessageController.java:75)
	
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你确定你的host是对的么？

我查阅是：smtp.office365.com

麻烦检查后重试。

**Comment by liangxp** [comment]
> 你确定你的host是对的么？
> 
> 我查阅是：smtp.office365.com
> 
> 麻烦检查后重试。

确认哦，因为这个配置使用其他发邮件工具都可以正常发送哦
