### ISSUE TITLE
JSONUtil.toJsonStr()方法问题

### ISSUE THREAD

**Issue by sunnyyuu** [looly/hutool#2010]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.14

### 问题描述
JSONUtil.toJsonStr()方法，当对象属性为BigDecimal类型且值为零时(BigDecimal.ZERO)，对其设置小数位数格式（例如四舍五入保留2位小数），转换成Json字符串后将其值直接变为0，而不是0.00。这在某些场景下（如财务会计、金融银行业等）接口要求非常严格，必须按照其规定的格式输出，能否麻烦优化下，谢谢！

1. 复现代码
obj.setXXX(BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP));
System.out.println(JSONUtil.toJsonStr(obj);

**Comment by sunnyyuu** [comment]
fastjson是正常的

**Comment by looly** [comment]
你可以自定义`JSONConfig.create().setStripTrailingZeros(false)`即可。

**Comment by HoldEvan** [comment]
> 

这样设置后，BigDecimal类型的小数点后面只有1个0啊

**Comment by looly** [comment]
@java-lyf 那就没有别的办法了。
