### ISSUE TITLE
LineReadWatcher#onModify方法中对文件变化判断问题

### ISSUE THREAD

**Issue by hyh2437124907git** [looly/hutool#2013]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当监听的目标文件被清空时，currentLength为0，导致错误的认为文件没有变化

比如报错的Excel文件，有问题的图片等。
![image](https://user-images.githubusercontent.com/72654526/145664618-2b74d464-cd78-4046-9935-7443af98b494.png)

**Comment by looly** [comment]
有道理，内容清空应该调用seek方法让指针归零。

5.7.18改为：

![image](https://user-images.githubusercontent.com/1432613/145697479-45262c08-fb5e-458c-9cd8-3ad27fa4ced8.png)
