### ISSUE TITLE
日志报：cn.hutool.setting.SettingLoader  Load setting file [classpath:system.setting]

### ISSUE THREAD

**Issue by jenemy8023** [looly/hutool#2014]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用了hutool的log工具和sql工具。
log使用log4j2，用单例访问
sql用的HikariCP 
日志里一直报：
2021-12-11 16:37:53.109 [JavaFX Application Thread] DEBUG cn.hutool.setting.SettingLoader - Load setting file [classpath:system.setting]
感觉每次报这个，日志都会停顿一下。这个是正常的么？ 会影响性能么？

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这是个debug日志，表示读取了这个配置文件，至于停顿跟这个无关吧，一般这个日志会在初始化时候打印，停顿应该是你初始化耗费了比较长的时间。
