### ISSUE TITLE
hutool-log依赖的log4j-core版本为2.12.1，是否有安全漏洞？

### ISSUE THREAD

**Issue by calvinGithub** [looly/hutool#2015]
![image](https://user-images.githubusercontent.com/38104214/145670633-dc5e1cf2-c413-4add-aae8-ddf1f5295408.png)
![image](https://user-images.githubusercontent.com/38104214/145670692-dfd41c13-c52a-44a1-bef7-b58d1b437227.png)

**Comment by CherryRum** [comment]
特别说明: 最近log4j2爆大漏洞，所以针对hutool作下说明。Hutool-log采用门面模式输出日志，类似slf4j但是更加优雅，既hutool会自动查找你引入的jar来判断转发到的日志库，也就是说如果你的项目中有log4j2的jar，肯定中招，升级log4j2的版本即可，没有就不影响，因为hutool会转发到其他日志库，如果找不到日志库会转发到System.out.println

作者的回复

**Comment by ParkFeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by looly** [comment]
你看依赖是`optional`的，只是编译使用到了，如果你不单独引用log4j2的话hutool不会关联引入的。
