### ISSUE TITLE
JSONObject 初始化大小值 未被使用.

### ISSUE THREAD

**Issue by moxiaobin** [looly/hutool#2016]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.7.17最新版本

### 问题描述
创建 `JSONObject` 对象时, 指定 **初始化大小** 参数 `capacity` 在 `config.isIgnoreCase() == false` 情况下 未被使用. 

![image](https://user-images.githubusercontent.com/26433204/145717086-39b0421a-ce60-4518-bac9-d94475bf9992.png)

**Comment by looly** [comment]
5.7.18修复此问题，感谢。
