### ISSUE TITLE
ExcelWriter写出Map数据并自定义key别名时，导出列丢失问题

### ISSUE THREAD

**Issue by pangyuQ** [looly/hutool#2017]
### 版本情况

JDK版本：    openjdk_15
hutool版本： 5.X.X（最新版5.7.17仍有问题）

### 问题描述（包括截图）
ExcelWriter写出Map数据并自定义key别名时，导出数据之前会将Map的key转为自定义的别名，并将Map的key作为表头导出，这会导致重复的别名合并，导出的数据丢失重复别名的列。

源码实现代码：
cn.hutool.poi.excel.ExcelWriter#writeRow(java.util.Map<?,?>, boolean)
```java
Map<?, ?> aliasMap = this.aliasMap(rowMap);
if (isWriteKeyAsHead) {
    this.writeHeadRow(aliasMap.keySet());
}
```

建议：
这里定义的别名不应该做处理，应该遍历设置的别名。
目前已经通过cn.hutool.poi.excel.ExcelWriter#write(java.lang.Iterable<?>)导出行对象避免遇到该问题。

1. 复现代码

```java
@Test
public void t() {
	ExcelWriter writer = new ExcelWriter("/home/测试.xls");
	writer.addHeaderAlias("index1", "题目1");
	writer.addHeaderAlias("index2", "问题1");
	writer.addHeaderAlias("index3", "题目2");
	writer.addHeaderAlias("index4", "问题1");

        // 导出只有三列表头，重复的 问题1 会丢失一个
	writer.write(
		List.of(
			Map.of("index1", "1", "index2", "1.1", "index3", "2", "index4", "2.1"),
			Map.of("index1", "1", "index2", "1.1", "index3", "2", "index4", "2.1")
		),
		true
	);
	writer.close();
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
如果别名后的标题重复，确实会有这个问题。

但是暂时无法解决此问题，写出map是根据别名后的标题行定位列填充的，如果标题重复，就无很好的定位。

欢迎提供好的思路。

**Comment by pangyuQ** [comment]
> 如果别名后的标题重复，确实会有这个问题。
> 
> 但是暂时无法解决此问题，写出map是根据别名后的标题行定位列填充的，如果标题重复，就无很好的定位。
> 
> 欢迎提供好的思路。

写出map不应该根据别名后的标题行定位列填充，应该根据原始值进行填充，我认为别名只是用于展示的，不能作为唯一列

**Comment by looly** [comment]
@pycrab 用户提供的数据很有可能是别名后的键值对怎么办……这块处理会因为重复问题变得复杂化……

**Comment by pangyuQ** [comment]
> @pycrab 用户提供的数据很有可能是别名后的键值对怎么办……这块处理会因为重复问题变得复杂化……

哦哦，那建议增加一个重写方法，分别兼容这两种可能性，并给出方法注释避免这些情况，这样比较完整:smile:

**Comment by suochuanlin** [comment]
作者打算修复一下吗？

**Comment by codesverve** [comment]
这个问题有修复后的版本吗？因为标题是用户输入的，并不能保证不会重复，导出后丢失列是比较不合理的

**Comment by looly** [comment]
不考虑修复。

如果有重复头，考虑自行一行一行写出。

**Comment by codesverve** [comment]
这一步转为按别名作为键的map不是必须的，最终目的是为了按顺序写出行。存储标题的数据headerAlias是有序的LinkedHashMap类型，按顺序写出values即可，数据行也一样只需要按照headerAlias.keys的顺序写出即可保证有序

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/145cf779-d154-4094-a13f-c13d7b47b229">
