### ISSUE TITLE
DateTime类型中的cdate是空的，导致通用mapper的方法生成的sql没有‘’号

### ISSUE THREAD

**Issue by LZLLZ001** [looly/hutool#2018]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/42398065/145816967-c0d18083-6f73-4d46-bcc8-308bedfbd3a7.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个是java.util.Date中的属性。

![image](https://user-images.githubusercontent.com/1432613/145820842-6832ebe8-4ed3-40dd-a351-f5f64e60fa6d.png)
