### ISSUE TITLE
ExcelWriter中数据类型为bean的write方法存在bug

### ISSUE THREAD

**Issue by Squirrel1024** [looly/hutool#2021]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
 问题条件：

- 通过Bean来写入数据
- Bean的部分字段设置了别名

出现的问题：

- 出现且仅出现一个未设置别名的属性列
- 出现的属性列的值非Bean中对应属性的值，被其他未设置别名的属性列所覆盖了

![test](https://user-images.githubusercontent.com/38368160/145947814-d1256828-63a1-4d77-b964-46b39ff11335.png)

问题可能是对象转treemap时，treemap的[别名的默认比较器IndexedComparator](https://github.com/dromara/hutool/blob/ddb8aad9d1364ba9bb7b42b3f7b9166eaeccd6a3/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelWriter.java#L957)导致的：有多个[不存在别名的属性order值同为-1](https://github.com/dromara/hutool/blob/ddb8aad9d1364ba9bb7b42b3f7b9166eaeccd6a3/hutool-core/src/main/java/cn/hutool/core/comparator/IndexedComparator.java#L58-L64)，在treemap中无法比较。
1. 复现代码
```java
    public void HutoolTest(HttpServletResponse response) throws IOException {
        ArrayList<JSONObject> hutoolTestEntities = new ArrayList<>();
        // 填充对象
        JSONObject jsonObject1 = new JSONObject(true);
        jsonObject1.put("statDate","12-03");
        jsonObject1.put("testCode","testCode");
        jsonObject1.put("testName","testCode");
        jsonObject1.put("testArea",null);
        jsonObject1.put("testCompany",null);
        jsonObject1.put("createTime","123");
        hutoolTestEntities.add(jsonObject1);
        BigExcelWriter writer= (BigExcelWriter) ExcelUtil.getBigWriter();
        //自定义标题别名
        writer.addHeaderAlias("statDate", "日期");
        writer.addHeaderAlias("testCode", "测试码");
        writer.addHeaderAlias("testName", "测试名");
        writer.addHeaderAlias("testArea", "测试地区");
        // 构建结果集
        writer.write(hutoolTestEntities,true);
        String fileName = "测试";
        // 设置响应报文头
        response.setContentType("application/vnd.ms-excel;charset=utf-8");
        //设置Http响应头告诉浏览器下载这个附件
        response.setHeader("Content-Disposition", "attachment;filename=" + URLEncoder.encode(fileName, "UTF-8") + ".xls");
        // 流输出
        ServletOutputStream outputStream = response.getOutputStream();
        writer.flush(outputStream);
        writer.close();
    }
```

**Comment by looly** [comment]
没看懂，是多出来了未设置别名的列？如果是可以通过`setOnlyAlias`去掉。

`被其他未设置别名的属性列所覆盖了`没看懂。

如果有补充麻烦重新打开issue。

**Comment by Squirrel1024** [comment]
以问题中的例子来说
1、希望 多出来未设置别名的列“testCompany”和“createTime”列，但只多出来一个“testCompany”列，“createTime”列消失了。
2、“testCompany”列的值不是我期望的null，实际变成了“createTime”列的“123”
