### ISSUE TITLE
IoUtil.copy中Buffer不再自动Flush

### ISSUE THREAD

**Issue by zhaomoran** [looly/hutool#2022]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.17（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用的outStream在不同大小的buffer写入下有着较大的差别，在hutool 5.5.2的版本我们通过设置buffer大小来权衡刷新的及时性和吞吐量。升级至5.7.17后，发现该buffer满后不在刷新，而是一直将整个inStream的数据写完再执行flush，虽然我们的outStream会自动刷新，但是在性能方面不再理想。

1. 复现代码

```java
IoUtil.copy(inStream, outStream, 1024 *  8)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
嗯，如果按照这个需求的话，确实缺少自定义。

这个稍后处理。

**Comment by looly** [comment]
5.7.18你可以：

```java
new StreamCopier(bufferSize, -1, null).setFlushEveryBuffer(true).copy(in, out);
```
