### ISSUE TITLE
LocalDateTimeUtil和DateUtil时间偏移的建议

### ISSUE THREAD

**Issue by farawayll** [looly/hutool#2025]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.17(最新版)

### 问题描述（包括截图）
LocalDateTime = "yyyy-MM-01 00:00:0";
LocalDateTimeUtil.endOfDay(time)后, 时间是yyyy-MM-01 23:59:59.999

问题:  存入mysql数据库datetime字段 mysql会四舍五入变成yyyy-MM-02 00:00:00
建议:  endOfDay()增加重载方法 > LocalDateTimeUtil.endOfDay(time, "")

**Comment by looly** [comment]
你可以使用`DateUtil.ceiling(DateUtil.date(), DateField.DAY_OF_MONTH, true)`。

5.7.18增加：

```java
final LocalDateTime localDateTime = LocalDateTimeUtil.parse("2020-01-23T12:23:56");

// 2020-01-23T23:59:59
LocalDateTimeUtil.endOfDay(localDateTime, true);
```
