### ISSUE TITLE
关于代码兼容性的建议

### ISSUE THREAD

**Issue by hzdjulytech** [looly/hutool#2027]
hutool 的使用已经越来越广了 代码兼容性问题需要得到重视，并不是所有情况下都能取修改使用代码 
兼容性问题会成为版本升级的大坑
当我们需要升级jar版本时  
对于第三方进入的代码中 hutooll使用情况时无法完全把控的 
hutool作为工具包一旦出现api兼容性会影响多出代码
比如 String[] arr= StrUtil.split(str, separator); 返回值改成list类型就需要同时调整所有使用了此方法的地方这是十分困难的

**Comment by looly** [comment]
是的，这个方法的修改是不得已为之，因为split方法有的返回数组，有的返回List，很多人提issue返回这种不统一的困惑。

接下来5.7.x之后会基本保持API不动。
