### ISSUE TITLE
日期工具类DateUtil中月份差值计算有误

### ISSUE THREAD

**Issue by yhmoling** [looly/hutool#2029]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.7.4

### 问题描述（包括截图）

1. 复现代码

```java
 Date begin = DateUtil.parseDate("2021-12-21");
        Date end = DateUtil.parseDate("2022-1-24");
        System.out.println( DateUtil.betweenMonth(begin,end,true));
```

2. 堆栈信息
  此时预期结果为2，实际输出结果为1

**Comment by kunhour** [comment]
我觉得1 是对的

**Comment by I-KevinZhan** [comment]
1是ok的，应该算是对api的理解不同

**Comment by qclucky7** [comment]
这个看自己怎么处理吧, 相同月份返回是0

**Comment by looly** [comment]
12月和1月相差难道不是1个月？

举个例子，你12月1日出生，我1月1日出生，我们出生相差1个月，没错吧。

**Comment by yhmoling** [comment]
那就应该是注释的问题，看注释我一直以为不足月的时候会补到月




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月21日(星期二) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] 日期工具类DateUtil中月份差值计算有误 (Issue #2029)





 
1是ok的，应该算是对api的理解不同
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
@yhmoling 你可能理解有误，第三个参数是重置的，也就是`2021-12-21`会被重置为`2021-12-01`
