### ISSUE TITLE
JSONObject 无法对接口bean进行json解析

### ISSUE THREAD

**Issue by sakka6868** [looly/hutool#2032]
### 版本情况

JDK版本：    openjdk version "1.8.0_41"
hutool版本： 5.7.17

### JSONObject 无法对接口bean进行json解析
![image](https://user-images.githubusercontent.com/23228684/147025538-01c2ec71-9246-40e3-bc6b-a8c7568baf4f.png)
![image](https://user-images.githubusercontent.com/23228684/147025701-a0d12325-39c5-4686-bf78-15fe7fee5a54.png)
![image](https://user-images.githubusercontent.com/23228684/147025717-afa77c41-9f79-49b4-98ed-92fa349b7ce2.png)

**Comment by looly** [comment]
你的User实现类中没有字段。例如getId应该有id字段才可以。

严重怀疑你的User实现类是动态代理对象。
