### ISSUE TITLE
配置文件为UTF-8 with DOM时 无法获取分组

### ISSUE THREAD

**Issue by CHENGPUYUAN** [looly/hutool#2037]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.17（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

文件为UTF-8 with DOM时 无法获取分组
(只有第一行是分组时会出现)
1. 复现代码

```java
 Setting setting = new Setting(filepath, CharsetUtil.CHARSET_UTF_8, true);
        assert setting.getGroups().contains("demo");
        assert setting.containsKey("demo", "name");

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

[[demo].txt](https://github.com/dromara/hutool/files/7773960/demo.txt)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
确实没法自动识别bom形式文件，考虑借助`BOMInputStream`完成读取。
