### ISSUE TITLE
CharSequenceUtil.replace方法不支持增补字符

### ISSUE THREAD

**Issue by micuncang** [looly/hutool#2039]
### 版本情况

JDK版本：    1.8.0_292
hutool版本： 5.7.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/3069117/147388586-1e3093ff-0d83-42fa-b305-12197bd5ee39.png)

1. 复现代码

```java
    public static void main(String[] args) {
        String text = "\uD853\uDC09秀秀";
        System.out.println(text);
        System.out.println(DesensitizedUtil.chineseName(text));
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
PR已合并~~感谢。
