### ISSUE TITLE
JSONUtil.toBean时候，BigDecimal属性字段损失精度(算是损失，位数不一致，小数不是零的话没有问题)，比如：12.00-->12.0

### ISSUE THREAD

**Issue by napoleon02** [looly/hutool#205]
public static void main(String[] args) {
        String str="{\"amount\":12.00,\"salary\":0}";
        TestBean testBean1 = JSONUtil.toBean(str, TestBean.class);
        TestBean testBean2 = JSONObject.parseObject(str, TestBean.class);

        System.out.println(testBean1);
        //打印TestBean{amount=12.0, salary=0, name='null'}
        System.out.println(testBean2);
        //打印TestBean{amount=12.00, salary=0, name='null'}
    }

**Comment by looly** [comment]
精度问题并非丢失，而是在BigDecimal转Double的时候自动操作。要想保留精度，此处请使用String。

Bigdecimal转String才有精度一说。
