### ISSUE TITLE
DateUtil.parseLocalDateTime("2021-1-22 00:00:00","yyyy-MM-dd HH:mm:ss") 月份为一位转换问题

### ISSUE THREAD

**Issue by zjf2671** [looly/hutool#2051]
### 版本情况

JDK版本：   jdk11
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
DateUtil.parseLocalDateTime("2021-1-22 00:00:00","yyyy-MM-dd HH:mm:ss")
如果时间月份是一位的情况下，报错
1. 复现代码
DateUtil.parseLocalDateTime("2021-1-22 00:00:00","yyyy-MM-dd HH:mm:ss")

```java
Console.log("报错了");
```

2. 堆栈信息
![image](https://user-images.githubusercontent.com/25733810/147652698-a7c4cb83-1ffb-4581-a6e3-965cd182f678.png)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by zjf2671** [comment]
DateUtil.parseLocalDateTime("2021-11-2 00:00:00","yyyy-MM-dd HH:mm:ss") 天个位数也有问题

**Comment by CherryRum** [comment]
建议还是标准字符串
```java
2021-01-22 00:00:00
```
或者
```java
val localDateTime = DateUtil.parseLocalDateTime("2021-1-22 00:00:00", "yyyy-M-dd HH:mm:ss");
System.out.println(localDateTime);
val s = DateUtil.formatLocalDateTime(localDateTime);
System.out.println(s);


2021-01-22T00:00
2021-01-22 00:00:00
```

**Comment by zjf2671** [comment]
建议把DateUtil.parseLocalDateTime("2021-1-22 00:00:00"）优化成同DateUtil.parse("2021-1-22 00:00:00")类似，这个方法就会正常解析。

**Comment by looly** [comment]
@zjf2671 你的格式本身有问题：`"yyyy-MM-dd HH:mm:ss"`，这个格式定义了两位，提供的字符串是一位，肯定有问题啊。

你可以直接采用自动识别转换方式：

```java
DateUtil.parse("2021-1-22 00:00:00");
```

如果想转为LocalDateTime，那：

```java
DateUtil.parse("2021-1-22 00:00:00").toLocalDateTime();
```
