### ISSUE TITLE
Cron 跨年后结果为null

### ISSUE THREAD

**Issue by wangxin05** [looly/hutool#2052]
String patter = "0 30 20 * * WED";
Date matchDate = CronPatternUtil.nextDateAfter(new CronPattern(patter),new Date(),true);

matchDate 为null。

版本：5.7.17

**Comment by wangxin05** [comment]
猜测是因为时间跨年导致
比如：

异常时：
String patter = "0 30 20 * * WED";
Date matchDates = CronPatternUtil.nextDateAfter(new CronPattern(patter),DateUtil.parseDateTime("2021-12-28 00:00:00"),true);

正常时：
String patter = "0 30 20 * * WED";
Date matchDates = CronPatternUtil.nextDateAfter(new CronPattern(patter),DateUtil.parseDateTime("2022-01-01 00:00:00"),true);

**Comment by looly** [comment]
这个方法的实现原理就是走秒，非常耗费性能。所以去掉了跨年，这个注释有说明。

![image](https://user-images.githubusercontent.com/1432613/147841753-f3e9fa1d-487f-485b-a7f6-d41754d5eecc.png)

**Comment by looly** [comment]
你可以手动调用`CronPatternUtil.matchedDates`方法自定义范围。

**Comment by wangxin05** [comment]
> 这个方法的实现原理就是走秒，非常耗费性能。所以去掉了跨年，这个注释有说明。
> 
> ![image](https://user-images.githubusercontent.com/1432613/147841753-f3e9fa1d-487f-485b-a7f6-d41754d5eecc.png)

确实很慢，即使是加上时间限制后，依然非常慢，以这个表达式为例：0 0 0 25 12 ?，使用最近一年时间范围计算后，得10s才能计算完成，这个有什么好的优化建议吗？

**Comment by looly** [comment]
@wangxin05 匹配这块还真的是想不到，除非解析表达式来比对完成。欢迎提供好的思路。
