### ISSUE TITLE
jsonobject转xml问题

### ISSUE THREAD

**Issue by zhbdesign** [looly/hutool#2058]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
jsonobject转xml问题
1. 复现代码

如果有list，xml会变成&lt,&gt

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可否提供测试样例？

**Comment by looly** [comment]
@zhbdesign JSONObject中的值一般是JSONArray，我的测试是这样的：

```java
final JSONObject obj = JSONUtil.createObj();
obj.set("key1", "v1")
	.set("key2", ListUtil.of("a", "b", "c"));

final String xmlStr = JSONUtil.toXmlStr(obj);
```

结果是：

```xml
<key1>v1</key1><key2>a</key2><key2>b</key2><key2>c</key2>
```

**Comment by looly** [comment]
有啥问题可以再打开此issue，并麻烦提供测试样例。
