### ISSUE TITLE
cn.hutool.core.io   FileUtil. touch(String path) 生成windows共享文件失败。

### ISSUE THREAD

**Issue by MLIceRedTea** [looly/hutool#2059]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1.cn.hutool.core.io   FileUtil 的这个方法不支持windows共享目录里生成文件  路径类似：\\192.168.248.128\file\test.txt ， touch(String path) 不会认为他是一个共享路径，原本设计是不是要touch(File file) 才可以在windows共享目录里创建文件。
	public static File touch(String path) throws IORuntimeException {
		if (path == null) {
			return null;
		}
		return touch(file(path));
	}

2.问题片段：
        a处： normalize(String path) 认为path.startsWith("\\\\") 是共享路径，那就应该是绝对路径。
	b处： 为什么 isAbsolutePath(String path) 认为‘/’	开头的才是绝对路径。不应该是 ‘\’ 吗。

a.//兼容Windows下的共享目录路径（原始路径如果以\\开头，则保留这种路径）
		if (path.startsWith("\\\\")) {
			pathToUse = "\\" + pathToUse;
		}

b.	public static boolean isAbsolutePath(String path) {
		if (StrUtil.isEmpty(path)) {
			return false;
		}

		// 给定的路径已经是绝对路径了
		return StrUtil.C_SLASH == path.charAt(0) || path.matches("^[a-zA-Z]:([/\\\\].*)?");
	}

**Comment by looly** [comment]
FileUtil是不支持Windows共享目录的，本质上这个共享目录走的Samba协议，使用专门的网络库解决吧。

使用`/`是为了保持多平台的统一性，你可以试下，在win下Java使用`/`也是可以的。
