### ISSUE TITLE
文档勘误-CSV文件处理工具-CsvUtil

### ISSUE THREAD

**Issue by alaahong** [looly/hutool#2061]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

文档勘误
https://www.hutool.cn/docs/#/core/%E6%96%87%E6%9C%AC%E6%93%8D%E4%BD%9C/CSV%E6%96%87%E4%BB%B6%E5%A4%84%E7%90%86%E5%B7%A5%E5%85%B7-CsvUtil
在线文档中有这么一句，本身描述有误，未找到文档源码处修改，故提交issue
`注意 CSV文件本身为一种简单文本格式，有编码区分。Excel读取CSV文件中含有中文时时必须为GBK编码（Windows平台下），否则会出现乱码。`

用excel打开csv想要无乱码，GBK并非必要条件，如果UTF-8的文件增加了BOM头就没有问题。
这个是excel的问题，不是csv文件的问题。
![image](https://user-images.githubusercontent.com/3264250/147895731-628d8969-46dd-4eed-8cc6-0cb37a82d37c.png)

附样例文件
[BOM.csv](https://github.com/dromara/hutool/files/7800149/BOM.csv)
![image](https://user-images.githubusercontent.com/3264250/147895909-cbde4ad5-e5ba-4605-9662-99756c7db615.png)

[non-BOM.csv](https://github.com/dromara/hutool/files/7800150/non-BOM.csv)
![image](https://user-images.githubusercontent.com/3264250/147895942-8fa181f3-7f7e-421e-b2a0-a1e80900f7ba.png)

**Comment by CherryRum** [comment]
如果没记错,utf-8不带bom确实是对的,规范上只有UTF16，UTF32应该携带BOM,在 UTF-8 文件中放置 BOM 主要是微软的臭习惯

**Comment by alaahong** [comment]
> 如果没记错,utf-8不带bom确实是对的,规范上只有UTF16，UTF32应该携带BOM,在 UTF-8 文件中放置 BOM 主要是微软的臭习惯

虽然我做项目，为了保障兼容性，也是都按照非BOM存储代码的，但是微软用BOM是符合UTF-8规范的，详见https://www.rfc-editor.org/rfc/rfc3629#section-6
回到正题，这个issue的初衷是文档的表述错误，Excel读取包含中文的CSV无乱码，并不一定要GBK编码。而且GBK的兼容性还是不如UTF-8好，增加一种带BOM的选择给UTF-8比较普适。

**Comment by CherryRum** [comment]
我的建议 bom的话还是存成utf16le 吧 这样跨平台没什么问题,Windows也能打开,貌似这个问题有人反馈给微软,这些人就是不修

**Comment by CherryRum** [comment]
嗯,确实应该修改下描述,但是我记得wps修复了这个问题,office还没有

**Comment by looly** [comment]
确实，这块文档应该详细说明下。

说实话bom头不想碰，坑太多了。

先保留issue，改了文档我再关闭。

**Comment by looly** [comment]
文档已修改，稍后更新。
