### ISSUE TITLE
最新版本format方法格式化时间报错，年末的最后一周，2021-12-26 至2021-12-31会出错

### ISSUE THREAD

**Issue by ducp123** [looly/hutool#2062]
### 版本情况

JDK版本：    jdk1.81.8.0_181
hutool版本： 5.7.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

最新版本format方法格式化时间报错，年末的最后一周，2021-12-26 至2021-12-31会出错
1. 复现代码

```java
System.out.println("xxxxx = " + DateUtil.date());
System.out.println("xxxxx = " + DateUtil.format(DateUtil.date(), "YYYY-MM-dd HH:mm:ss"));

System.out.println("xxxxx = " + new Date());
System.out.println("xxxxx = " + DateUtil.format(new Date(), "YYYY-MM-dd HH:mm:ss"));
```
xxxxx1 = 2021-12-26 11:29:28
xxxxx2 = 2022-12-26 11:29:28
xxxxx3 = Sun Dec 26 11:29:28 CST 2021
xxxxx4 = 2022-12-26 11:29:28

**Comment by CherryRum** [comment]
您的问题是对于**格式理解**有问题
`Week year`意思是当天所在的周属于的年份，一周从周日开始，周六结束，只要本周跨年，那么这周就算入下一年,所以出现您的问题,您应当使用`yyyy-MM-dd HH:mm:ss` 

`https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns`
