### ISSUE TITLE
在 `Java11` 及 `Java17` 中，`Issue644Test` 测试不通过

### ISSUE THREAD

**Issue by wangliang181230** [looly/hutool#2069]
在 `Java11` 及 `Java17` 中，`Issue644Test` 测试不通过：
```
Error:  Failures: 
Error:    Issue644Test.toBeanTest:28 expected: <2022-01-05T15:29:01.316208> but was: <2022-01-05T15:29:01.316>
```

**Comment by looly** [comment]
这个测试对比的是LocalDateTime对象啊，为何结果是字符串？
![image](https://user-images.githubusercontent.com/1432613/148200675-5c0e6f85-6005-44a8-909d-93d7fa24ddee.png)

hutool使用JDK8编译，还是建议使用JDK8吧。

**Comment by wangliang181230** [comment]
> 这个测试对比的是LocalDateTime对象啊，为何结果是字符串？ ![image](https://user-images.githubusercontent.com/1432613/148200675-5c0e6f85-6005-44a8-909d-93d7fa24ddee.png)
> 
> hutool使用JDK8编译，还是建议使用JDK8吧。

是对象啊，你看那个结果对比左右是尖括号。
JDK11及以上版本，LocalDateTime是含纳秒，不只毫秒。

**Comment by looly** [comment]
额……JDK11+估计是提高了LocalDateTime的精度了，我改下这块的test吧，把格式化后的字符串作为测试结果。

感谢。
