### ISSUE TITLE
建议给BeanUtil增加list的转换

### ISSUE THREAD

**Issue by 63734996** [looly/hutool#207]
经常用到把List Bean转成List Map，建议增加，参考代码如下：

public final class BeanUtilExt {
	
    /**
     * 把存放Bean的List转换到存放Map的List
     * @param list
     * @return
     */
    public static List<Map> listBean2listMap(List list){
        List<Map> rs = new ArrayList<Map>(list.size());
        for(Object obj:list){
            if(obj instanceof Map){
                rs.add((Map)obj);
            }
            else {
            	rs.add(BeanUtil.beanToMap(obj));
            }
        }
        return rs;
    }
    
    /**
     * 把存放Map的List转换到存放Bean的List
     * @param list
     * @return
     */
    public static <T> List<T> listMap2listBean(List<Map> list, Class<T> c){
        List<T> rs = new ArrayList<T>(list.size());
        for(Map obj:list){
            rs.add(BeanUtil.mapToBean(obj, c, true));
        }
        return rs;
    }
}

**Comment by looly** [comment]
考虑使用Convert.toList

**Comment by looly** [comment]
考虑使用Convert.toList

**Comment by mr-mihu** [comment]
> 考虑使用Convert.toList

List<Map<String, Object>> dataRow = Convert.convert(new TypeReference<List<Map<String, Object>>>() {}, dataList)
