### ISSUE TITLE
BeanUtil.beanToMap(xx, true, true)使用转换为下划线模式customerNickV2类型的字段转换错误

### ISSUE THREAD

**Issue by wuzhidexiaolang** [looly/hutool#2070]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.3

### 问题描述
BeanUtil.beanToMap(xx, true, true),使用转换为下划线模式， 输入的字段为customerNickV2， 输出的字段为customer_nick_V2,
这种类型的输出在别的gson包里是customer_nick_v2
![image](https://user-images.githubusercontent.com/33483160/148201239-daf94042-bbd2-401f-9b45-22a5edc9fce8.png)

1. 复现代码
@Data
public class Person {
    private Integer num;

    private String name;

    private String customerNickV2;
}

 public static void main(String[] args) {
        Person p = new Person();
        p.setCustomerNickV2("我是name");
        Map<String, Object> stringObjectMap = BeanUtil.beanToMap(p, true, true);
        System.out.println(stringObjectMap);

    }
```java
Console.log("{customer_nick_V2=我是name}");
```

**Comment by looly** [comment]
5.7.19修复此问题，感谢。
