### ISSUE TITLE
单元测试 `SM2Test.dLengthTest` 中 `SM2.getDHex()` 偶尔会报错

### ISSUE THREAD

**Issue by wangliang181230** [looly/hutool#2072]
`SM2.getDHex()` 问题：
```
Error:  Failures: 
Error:    SM2Test.dLengthTest:318 expected: <64> but was: <62>
```

**Comment by CherryRum** [comment]
抱歉上次忘记这个事情了
https://github.com/dromara/hutool/issues/2001
https://github.com/dromara/hutool/pull/2073

**Comment by wangliang181230** [comment]
> 抱歉上次忘记这个事情了 #2001 #2073

好的。

**Comment by wangliang181230** [comment]
@CherryRum  
另一个方法也报错了。`sm2.getD().length` 偶尔是 `31`。 能否再帮忙看一下？

```
Error:  Failures: 
Error:    SM2Test.dLengthTest:319 expected: <32> but was: <31>
```

**Comment by wangliang181230** [comment]
@looly 麻烦重启一下issue吧。

**Comment by CherryRum** [comment]
@wangliang181230 
这个问题,是归根结底是jdk 中 `bigint`的问题,现在应该使用getDHex(),我不是很建议手动控制bigint生成的`byte[]`的符号,由于jdk使用最低高位代表符号为,而直接把`bigint`转为`byte[]`就会有33位的问题,而使用BC提供的'asUnsignedByteArray'就会有31位的问题了.丢失了前导`0`,这个我考虑下,和作者在商量下是否返回给用户,现在你们可以使用
`getDBigInteger()`直接获取私钥`大正整数`进行需要的操作.而不需要获取一个私钥的无符号`byte数组`

**Comment by changhr2013** [comment]
这，刚去看了下我封装的库为啥没出问题😂发现了当时写的这段
```java
    /**
     * 将 BigInteger 转换为定长的字节数组
     *
     * @param rOrS BigInteger
     * @return byte[] 定长的字节数组，长度为 32(RS_LEN)
     */
    private static byte[] bigIntToFixedLengthBytes(BigInteger rOrS) {
        // for sm2p256v1, n is 00fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d54123,
        // n and s are the result of mod n, so they should be less than n and have length < 32.
        byte[] rs = rOrS.toByteArray();
        if (rs.length == RS_LEN) {
            return rs;
        } else if (rs.length == RS_LEN + 1 && rs[0] == 0) {
            return Arrays.copyOfRange(rs, 1, RS_LEN + 1);
        } else if (rs.length < RS_LEN) {
            byte[] result = new byte[RS_LEN];
            Arrays.fill(result, (byte) 0);
            System.arraycopy(rs, 0, result, RS_LEN - rs.length, rs.length);
            return result;
        } else {
            throw new RuntimeException("error rs: " + Hex.toHexString(rs));
        }
    }
```

**Comment by wangliang181230** [comment]
> 这，刚去看了下我封装的库为啥没出问题😂发现了当时写的这段
> 
> ```java
>     /**
>      * 将 BigInteger 转换为定长的字节数组
>      *
>      * @param rOrS BigInteger
>      * @return byte[] 定长的字节数组，长度为 32(RS_LEN)
>      */
>     private static byte[] bigIntToFixedLengthBytes(BigInteger rOrS) {
>         // for sm2p256v1, n is 00fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d54123,
>         // n and s are the result of mod n, so they should be less than n and have length < 32.
>         byte[] rs = rOrS.toByteArray();
>         if (rs.length == RS_LEN) {
>             return rs;
>         } else if (rs.length == RS_LEN + 1 && rs[0] == 0) {
>             return Arrays.copyOfRange(rs, 1, RS_LEN + 1);
>         } else if (rs.length < RS_LEN) {
>             byte[] result = new byte[RS_LEN];
>             Arrays.fill(result, (byte) 0);
>             System.arraycopy(rs, 0, result, RS_LEN - rs.length, rs.length);
>             return result;
>         } else {
>             throw new RuntimeException("error rs: " + Hex.toHexString(rs));
>         }
>     }
> ```

你可以写个测试用例，从MIN到MAX，所有值测一遍。哈哈。

**Comment by CherryRum** [comment]
你真的是狠人



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月28日(周五) 下午2:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] 单元测试 `SM2Test.dLengthTest` 中 `SM2.getDHex()` 偶尔会报错 (Issue #2072)




  
这，刚去看了下我封装的库为啥没出问题😂发现了当时写的这段
     /**      * 将 BigInteger 转换为定长的字节数组      *      * @param rOrS BigInteger      * @return byte[] 定长的字节数组，长度为 32(RS_LEN)      */     private static byte[] bigIntToFixedLengthBytes(BigInteger rOrS) {         // for sm2p256v1, n is 00fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d54123,         // n and s are the result of mod n, so they should be less than n and have length < 32.         byte[] rs = rOrS.toByteArray();         if (rs.length == RS_LEN) {             return rs;         } else if (rs.length == RS_LEN + 1 &amp;&amp; rs[0] == 0) {             return Arrays.copyOfRange(rs, 1, RS_LEN + 1);         } else if (rs.length < RS_LEN) {             byte[] result = new byte[RS_LEN];             Arrays.fill(result, (byte) 0);             System.arraycopy(rs, 0, result, RS_LEN - rs.length, rs.length);             return result;         } else {             throw new RuntimeException("error rs: " + Hex.toHexString(rs));         }     }
  
你可以写个测试用例，从MIN到MAX，所有值测一遍。哈哈。

**Comment by changhr2013** [comment]
生产环境用好久了，应该是没啥问题，记得当时是做加密机的大佬说这个长度记得处理一下😂

**Comment by CherryRum** [comment]
对的，用c语言写就没啥事，这玩意就是java一直不加无符号数，导致的，bc库也做了处理.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月28日(周五) 下午2:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] 单元测试 `SM2Test.dLengthTest` 中 `SM2.getDHex()` 偶尔会报错 (Issue #2072)




 
生产环境用好久了，应该是没啥问题，记得当时是做加密机的大佬说这个长度记得处理一下😂

**Comment by wangliang181230** [comment]
是啊，JAVA为什么一直不加无符号数呢，第一位好浪费啊。

**Comment by CherryRum** [comment]
是的呀，为了简单，搞得做加密的有点难受
