### ISSUE TITLE
反序列化JSON时, 当字段类型为枚举且枚举类存在静态方法时, 反序列化结果与预期不符.

### ISSUE THREAD

**Issue by syzsh** [looly/hutool#2075]
### 版本情况

JDK版本：    adopt-openjdk-1.8.0_282
hutool版本： ‎5.7.18（当前为最新版本）

### 问题描述（包括截图）

反序列化JSON时, 当字段类型为枚举, 且当这个枚举存在参数类型为String的静态方法, 方法有默认返回值时, 反序列会优先调用静态方法, 而不执行枚举的valueOf方法, 解析到的枚举值不符合预期.

代码如下:
cn.hutool.core.convert.impl.EnumConverter#tryConvertEnum (94~102 行)

![image](https://user-images.githubusercontent.com/7196606/148483123-bbd681c8-ea56-4b86-a7d7-46e5582fd7c9.png)

1. 复现代码

```java

import cn.hutool.json.JSONUtil;
import java.util.stream.Stream;

public class EnumConvertTest {

    public static void main(String[] args) {
        User user = new User("张三", Gender.MALE);

        String json = JSONUtil.toJsonStr(user);
        System.out.println(json); // {"gender":"MALE","name":"张三"}

        user = JSONUtil.toBean(json, User.class);

        System.out.println(user.getGender()); // OTHER
        System.out.println(Gender.valueOf("MALE")); // MALE
    }
}

class User {
    private String name;
    private Gender gender;

    public User(String name, Gender gender) {
        this.name = name;
        this.gender = gender;
    }

    public String getName() {
        return name;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }
}

enum Gender {
    MALE("M", "男"),
    FEMALE("F", "女"),
    OTHER("O", "其它"),
    ;
    String code;
    String desc;

    Gender(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public static Gender getByCode(String code) {
        return Stream.of(values()).filter(it -> it.code.equals(code)).findFirst().orElse(OTHER);
    }
}
```

**Comment by looly** [comment]
这是一个策略问题。

hutool认为用户定义的策略大于系统默认方法的策略，所以这块应该没问题。

你这种特殊情况只能修改getByCode方法，兼容传入的是code还是name或者自定义一个`EnumConverter`覆盖hutool默认即可。

方法在`ConverterRegistry.putCustom`

**Comment by syzsh** [comment]
你提到的解决方案, 前提是用户要在使用前知道有这个默认策略, 否则会导致莫名其妙的问题.
这个默认策略导致反序列化行为与其它主流JSON序列化框架均不一致, 文档中也未看到相关提示.
而且枚举中定义一个getByCode的静态方法是很常见的场景. 第三方类库无法修改源码, 自定义转换器对静态工具类来说也很不方便.
是否可以考虑把这种扩展行为的策略当作可选操作呢?

**Comment by looly** [comment]
@SYZ1421 这个策略也是很多用户提的PR和issue，每个人对枚举的使用都不一样，自己定义`EnumConverter`是最好的办法~

**Comment by syzsh** [comment]
@looly 好的, 感谢.

**Comment by looly** [comment]
文档也要说明：https://hutool.cn/docs/#/core/%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2-ConverterRegistry?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e8%bd%ac%e6%8d%a2

**Comment by SYZ1421** [comment]
@looly 

感谢耐心回复, 我指的文档中没有说明, 并不是说没有转换器相关文档.
我意思是在使用JSONUtil这个工具类的时候, 并不知道转换枚举会有这个默认策略.

我生产项目中, 静态工具一般用FastJSON, Spring默认的Jackson, 我喜欢用Hutool, 所以在写脚本的时候就优先使用了Hutool的, 切换类库的时候, 会默认序列化结果与其它类库一致, 都没有打开文档看, 猜着名字大概也是JSONUtil之类, 所以就直接用了.

我搜了下issue, 看到了类似的问题, 但是提问者没有描述的很清楚, 不确定:
https://github.com/dromara/hutool/issues/1333#issue-773648472

**Comment by baymax55** [comment]
我也遇到了这个问题,当存在静态方法时这里返回null:
![image](https://user-images.githubusercontent.com/35788491/185589241-4fdaad07-8d63-41d6-9aac-d0c7364d54f3.png)

**Comment by xy9860** [comment]
这个顺序非常不符合直观逻辑,建议先使用valueOf再try 或者增加JsonUtil.tryToBean方法
