### ISSUE TITLE
Velocity模板引擎无法加载模板文件

### ISSUE THREAD

**Issue by mokself** [looly/hutool#2078]
### 版本情况

JDK版本：    jdk1.8.0_211
hutool版本： 5.7.14
Velocity版本：1.7

### 问题描述
Velocity模板引擎无法加载模板文件。
不知道是不是maven分模块的原因，hutool在最外层引入的

1. 复现代码
```java
TemplateEngine engine = TemplateUtil.createEngine(new TemplateConfig("templates", TemplateConfig.ResourceMode.CLASSPATH));
Template template = engine.getTemplate("templates/entity.vm");
```

2. 堆栈信息
严重: ResourceManager : unable to find resource '/templates/entity.vm' in any resource loader.
Exception in thread "main" org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource '/templates/entity.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
	at cn.hutool.extra.template.engine.velocity.VelocityEngine.getTemplate(VelocityEngine.java:99)
	at com.msr.PlanImportStart.generateJavaFile(PlanImportStart.java:71)
	at com.msr.PlanImportStart.main(PlanImportStart.java:65)

**Comment by looly** [comment]
你确认下你的模板文件确实在classpath中，具体去target目录下找一下，是不编译后没有拷贝出去。

有问题再打开issue。

**Comment by mokself** [comment]
怎么可能犯这么低级的错误



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] Velocity模板引擎无法加载模板文件 (Issue #2078)





 
你确认下你的模板文件确实在classpath中，具体去target目录下找一下，是不编译后没有拷贝出去。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
刚发现你的代码问题，修改如下：

```java
emplateEngine engine = TemplateUtil.createEngine(new TemplateConfig("templates", TemplateConfig.ResourceMode.CLASSPATH));
Template template = engine.getTemplate("entity.vm");
```

new TemplateConfig的时候已经指定了`templates`目录，getTemplate无需再指定目录前缀。你试下。

**Comment by mokself** [comment]
你试过吗，没有用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] Velocity模板引擎无法加载模板文件 (Issue #2078)





 
刚发现你的代码问题，修改如下：
 emplateEngine engine = TemplateUtil.createEngine(new TemplateConfig("templates", TemplateConfig.ResourceMode.CLASSPATH)); Template template = engine.getTemplate("entity.vm");
 
new TemplateConfig的时候已经指定了templates目录，getTemplate无需再指定目录前缀。你试下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/148866709-82c94c5a-2920-4102-ad93-ab01e9f871ba.png)

见截图。

**Comment by mokself** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] Velocity模板引擎无法加载模板文件 (Issue #2078)





 

 
见截图。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pierswu** [comment]
我用Velocity1.7遇到的问题和你一样。但是我升级到2.3就可以了。

**Comment by looly** [comment]
@pierswu 嗯，正解。估计是旧版本velocity不兼容导致的。
