### ISSUE TITLE
RegexPool中汉字正则并不能完全覆盖汉字范围

### ISSUE THREAD

**Issue by micuncang** [looly/hutool#2080]
### 版本情况

JDK版本：    1.8.0_292
hutool版本： 5.7.19（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
System.out.println(Validator.hasChinese("㐓㐘"));
```
参考资料：
- 维基百科关于汉字Unicode范围描述
![image](https://user-images.githubusercontent.com/3069117/148559490-a5fc3a8b-c9d1-48e0-8211-974a976b9f13.png)

- Surrogate Pair计算工具，用两个UTF16编码来表示一个字符，方便计算新正则边界
http://www.russellcottrell.com/greek/utilities/SurrogatePairCalculator.htm

**Comment by looly** [comment]
已合并PR，感谢。
