### ISSUE TITLE
hashutil 希望增加Ketama hash实现

### ISSUE THREAD

**Issue by herouu** [looly/hutool#2084]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
搜了一下，这个是一致性hash算法吧。

找了个简单实现，5.7.20新增加KetamaHash，你可以看下。

**Comment by herouu** [comment]
给力
