### ISSUE TITLE
SystemUtil.getHostInfo().getAddress()获取ip不对

### ISSUE THREAD

**Issue by imapach** [looly/hutool#2085]
本机装有docker时，会获取docker的IP

**Comment by looly** [comment]
这个方法本质上调用`NetUtil.getLocalhost()`，逻辑是：

1. 查找所有网卡地址，必须非回路（loopback）地址、非局域网地址（siteLocal）、IPv4地址
2. 如果无满足要求的地址，调用 {@link InetAddress#getLocalHost()} 获取地址

docker环境理应获取docker下的地址吧？如果想获取主机地址，使用`NetUtil.localAddressList`

**Comment by imapach** [comment]
> root@KitDevVps:~# ip addr
> 1: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
>     link/ether 02:42:8c:85:1a:f3 brd ff:ff:ff:ff:ff:ff
>     inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::42:8cff:fe85:1af3/64 scope link 
>        valid_lft forever preferred_lft forever
> 2: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 3: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
>     inet xxx.xxx.xxx.xxx/23 brd xxx.xxx.xxx.xxx scope global dynamic ens3
>        valid_lft 55158sec preferred_lft 55158sec
>     inet6 xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope global dynamic mngtmpaddr noprefixroute 
>        valid_lft 2591896sec preferred_lft 604696sec
>     inet6 xxxx::xxxx:xxxx:xxxx:xxxx/64 scope link 
>        valid_lft forever preferred_lft forever
> 4: ens7: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff


我linux本机安装了docker，然后网卡里会有个docker0，本机下使用SystemUtil.getHostInfo().getAddress()方法获取的ip是docker0网卡的地址172.17.0.1。

@looly
