### ISSUE TITLE
CaseInsensitiveMap's behavior is inconsistent between v5.0.7 and v5.7.18 in Java Stream API

### ISSUE THREAD

**Issue by logsin37** [looly/hutool#2086]
### 版本情况

JDK版本：    openjdk_11.0.3.7
hutool版本： 5.0.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
package org.xxx.xxx;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import cn.hutool.core.lang.Console;
import cn.hutool.core.lang.Pair;
import cn.hutool.core.map.CaseInsensitiveMap;

public class xxxMainClass{


    public static void main(String[] args) {

        Pair<String, String> b = new Pair<>("a", "value");
        Pair<String, String> a = new Pair<>("A", "value");
        final List<Pair<String, String>> pairs = Arrays.asList(a, b);
        final Map<String, String> map = pairs.stream().collect(Collectors.toMap(Pair::getKey, Pair::getValue, (A, B) -> A, CaseInsensitiveMap::new));
        Console.log(map);
    }
}

```

this code print `{a=value}` at v5.0.7 but `{a=value, A=value}` at v5.7.18

### core cause

Collectors.toMap method will call `java.util.Map#merge` to accumulate each value in stream source, and CaseInsensitiveMap's  parent class `MapWrapper` override this method  and not call `cn.hutool.core.map.CustomKeyMap#customKey` fucntion to change key case and got wrong result

![image](https://user-images.githubusercontent.com/19299794/148736901-8f1f0830-d6bd-4452-90d8-5c46d0d6453a.png)

**Comment by looly** [comment]
Thanks, we will fix overide default method at `CustomKeyMap`。

5.7.20 fix it.

**Comment by CherryRum** [comment]
速度够快

**Comment by logsin37** [comment]
thanks
