### ISSUE TITLE
[feature] MetaUtil.getTableMeta() 方法返回的 Table 对象 建议新增 comment 属性

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#209]
新需求请求：MetaUtil.getTableMeta() 方法返回的 Table 对象 建议新增 comment 属性

实现：可通过 `rs.getString("REMARKS")` 获取表注释，前提 jdbcUrl 末尾需要添加 `useInformationSchema=true`

不清楚加到hutool的何处，希望小磊可以添加在合适位置，感谢感谢！

**Comment by looly** [comment]
`MetaUtil.getTableMeta().get(列名称).getComment()`

4.2.2会增加`getColumn`方法，更加明确获取列。

**Comment by xkcoding** [comment]
...并非获取列的注释，而是希望获取表注释
