### ISSUE TITLE
JSONUtil如何序列化LocalDate LocalDateTime jdk1.8 时间

### ISSUE THREAD

**Issue by newbirdking** [looly/hutool#2090]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

        JSONConfig config = new JSONConfig().setIgnoreNullValue(false);//.setDateFormat(DatePattern.NORM_DATE_PATTERN);
        String s1 = JSONUtil.toJsonStr(JSONUtil.parse(d, config));
        LocalDate localDate1 = JSONUtil.toBean(s1, LocalDate.class);
        System.out.println(s1 + "==" + localDate1);
```java
Console.log("报错了");
```
![image](https://user-images.githubusercontent.com/5317586/149076239-c41a2cd7-700c-4907-a80d-e19698831d7d.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
LocalDate 同理
```java
	public static void main(String[] args) {
		LocalDateTime localDateTime = DateTime.now().toLocalDateTime();
		String format = LocalDateTimeUtil.format(localDateTime, DateTimeFormatter.ISO_DATE_TIME);
		LocalDateTime local = LocalDateTimeUtil.parse(format);
		System.out.println(format+"---"+format.getClass());
		System.out.println(local+"---"+local.getClass());
	}

//2022-01-12T15:12:46.827---class java.lang.String
//2022-01-12T15:12:46.827---class java.time.LocalDateTime
```

**Comment by newbirdking** [comment]
我的意思是,如果有个对象User中存在 LocalDateTime;我如何用JSONUtil转json;然后还原对象User.
**JSONUtil**工具可以处理jdk1.8的时间吗?

我用Gson是可以转换的,只不过,需要一些配置.而JSONUtil直接报错.
 public static void main(String[] args) {
        LocalDate d = LocalDate.now();
        Gson gson = new Gson();
        String s = gson.toJson(d);
        LocalDate localDate = gson.fromJson(s, LocalDate.class);
        System.out.println(s + "==" + localDate);
        JSONConfig config = new JSONConfig().setIgnoreNullValue(false);//.setDateFormat(DatePattern.NORM_DATE_PATTERN);
        String s1 = JSONUtil.toJsonStr(JSONUtil.parse(d, config));
        LocalDate localDate1 = JSONUtil.toBean(s1, LocalDate.class);
        System.out.println(s1 + "==" + localDate1);
    }

**Comment by CherryRum** [comment]
貌似配置中并没有这个配置,所以可能需要您自定义序列化设置,手动转了

**Comment by looly** [comment]
如果你的LocalDate在Bean中是没有问题的，LocalDate会被转换为时间戳：

```java
@Data
	public static class Test{
		private LocalDate localDate;
	}
```

```java
final Test test = new Test();
test.setLocalDate(LocalDate.now());
// {"localDate":1642176000000}
JSONObject json = JSONUtil.parseObj(test);
```

**Comment by looly** [comment]
这个算是bug吧，LocalDate的Month这个enum，实现了`TemporalAccessor`接口导致的问题。

5.7.20修复，感谢。

**Comment by newbirdking** [comment]
JDK版本： openjdk_8_201
hutool版本： 5.7.21（请确保最新尝试是否还有问题）
已用最新版本测试
![QBKKN((KEO)THYYEKZN{FA3](https://user-images.githubusercontent.com/5317586/154385572-5a656763-d719-4068-8626-cecda629d4d2.png)
如下方法测试:仍然报错,解析不了.
public static void main(String[] args) {
LocalDate d = LocalDate.now();
Gson gson = new Gson();
String s = gson.toJson(d);
LocalDate localDate = gson.fromJson(s, LocalDate.class);
System.out.println(s + "==" + localDate);
JSONConfig config = new JSONConfig().setIgnoreNullValue(false);//.setDateFormat(DatePattern.NORM_DATE_PATTERN);
String s1 = JSONUtil.toJsonStr(JSONUtil.parse(d, config));
LocalDate localDate1 = JSONUtil.toBean(s1, LocalDate.class);
System.out.println(s1 + "==" + localDate1);
}
![image](https://user-images.githubusercontent.com/5317586/154385748-898bcef9-f4b5-47bf-a4ab-518ab4d9d8e2.png)

**Comment by looly** [comment]
@newbirdking LocalDate无法直接转换为JSONObject，在Bean中它被转换为时间戳。

如果想实现转换，自行实现TemporalAccessorSerializer接口，然后调用`GlobalSerializeMapping.put`加入即可。

5.7.22增加默认的实现：

```java
package cn.hutool.json.serialize;

import cn.hutool.json.JSON;
import cn.hutool.json.JSONException;
import cn.hutool.json.JSONObject;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.TemporalAccessor;

/**
 * {@link TemporalAccessor}的JSON自定义序列化实现
 *
 * @author looly
 * @since 5.7.22
 */
public class TemporalAccessorSerializer implements JSONObjectSerializer<TemporalAccessor>, JSONDeserializer<TemporalAccessor> {

	private static final String YEAR_KEY = "year";
	private static final String MONTH_KEY = "month";
	private static final String DAY_KEY = "day";
	private static final String HOUR_KEY = "hour";
	private static final String MINUTE_KEY = "minute";
	private static final String SECOND_KEY = "second";
	private static final String NANO_KEY = "nano";

	private final Class<? extends TemporalAccessor> temporalAccessorClass;

	public TemporalAccessorSerializer(Class<? extends TemporalAccessor> temporalAccessorClass) {
		this.temporalAccessorClass = temporalAccessorClass;
	}

	@Override
	public void serialize(JSONObject json, TemporalAccessor bean) {
		if (bean instanceof LocalDate) {
			final LocalDate localDate = (LocalDate) bean;
			json.set(YEAR_KEY, localDate.getYear());
			json.set(MONTH_KEY, localDate.getMonthValue());
			json.set(DAY_KEY, localDate.getDayOfMonth());
		} else if (bean instanceof LocalDateTime) {
			final LocalDateTime localDateTime = (LocalDateTime) bean;
			json.set(YEAR_KEY, localDateTime.getYear());
			json.set(MONTH_KEY, localDateTime.getMonthValue());
			json.set(DAY_KEY, localDateTime.getDayOfMonth());
			json.set(HOUR_KEY, localDateTime.getHour());
			json.set(MINUTE_KEY, localDateTime.getMinute());
			json.set(SECOND_KEY, localDateTime.getSecond());
			json.set(NANO_KEY, localDateTime.getNano());
		} else {
			throw new JSONException("Unsupported type to JSON: {}", bean.getClass().getName());
		}
	}

	@Override
	public TemporalAccessor deserialize(JSON json) {
		final JSONObject jsonObject = (JSONObject) json;
		if (LocalDate.class.equals(this.temporalAccessorClass)) {
			return LocalDate.of(jsonObject.getInt(YEAR_KEY), jsonObject.getInt(MONTH_KEY), jsonObject.getInt(DAY_KEY));
		} else if (LocalDateTime.class.equals(this.temporalAccessorClass)) {
			return LocalDateTime.of(jsonObject.getInt(YEAR_KEY), jsonObject.getInt(MONTH_KEY), jsonObject.getInt(DAY_KEY),
					jsonObject.getInt(HOUR_KEY), jsonObject.getInt(MINUTE_KEY), jsonObject.getInt(SECOND_KEY), jsonObject.getInt(NANO_KEY));
		}

		throw new JSONException("Unsupported type from JSON: {}", this.temporalAccessorClass);
	}
}
```
