### ISSUE TITLE
HttpUtil.get()获取到的响应不完整

### ISSUE THREAD

**Issue by xtanyu** [looly/hutool#2091]
### 版本情况

JDK版本：    1.8
hutool版本： 5.7.8

### 问题描述
HttpUtil调用腾讯地图API时返回的JSON只有一半

返回结果如下
![image](https://user-images.githubusercontent.com/50282105/149091732-89dd34fc-17a4-47eb-aadc-f97c02a1e201.png)
1. 复现代码

```java
        String url = StrUtil.format("https://apis.map.qq.com/ws/geocoder/v1/?location={},{}&key={}", lat, lng, commonProperties.getTxMapKey());
        url = HttpUtil.encodeParams(url, Charsets.UTF_8);
        String body = HttpUtil.get(url);
        System.out.println(body);
```

**Comment by looly** [comment]
可能遇到bug了，麻烦升级到5.7.19试下。
