### ISSUE TITLE
HttpUtil无法识别chunk不完整下的异常

### ISSUE THREAD

**Issue by zhaomoran** [looly/hutool#2092]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.19（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在Http协议中，对于`Transfer-Encoding: Chunked`在正常情况下末尾会写入一个Length为0的的chunk标识完整结束。
可参考这个DEMO：https://gist.github.com/mwisnicki/6df71b2b5f7712306fca27bf34c24e94
我已经按照修复springboot实现正常末尾为0的chunk，异常无该chunk，以此来区分正常和异常结束的流。

在使用HttpUtil调用该接口进行测试时
1. 复现代码
```java
  // 末尾有0chunk，正常输出
  println(HttpRequest.get("http://localhost:8080/servlet/success").execute().body())

  // 末尾无0chunk，依然正常输出
  println(HttpRequest.get("http://localhost:8080/servlet/error").execute().body())
```
经过排查发现，发现在`HttpResponse`中忽略了EOF的异常，这里是有什么特殊的意义么？
```java
    private static long copyBody(InputStream in, OutputStream out, long contentLength, StreamProgress streamProgress) {
		if (null == out) {
			throw new NullPointerException("[out] is null!");
		}

		long copyLength = -1;
		try {
			copyLength = IoUtil.copy(in, out, IoUtil.DEFAULT_BUFFER_SIZE, contentLength, streamProgress);
		} catch (IORuntimeException e) {
			//noinspection StatementWithEmptyBody
			if (e.getCause() instanceof EOFException || StrUtil.containsIgnoreCase(e.getMessage(), "Premature EOF")) {
				// 忽略读取HTTP流中的EOF错误
			} else {
				throw e;
			}
		}
		return copyLength;
	}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by zhaomoran** [comment]
目前我已经使用下面的代码来处理，依然还是反馈给你确认是否需要对Chunked模式下做EOF的特殊处理
```
val response = HttpRequest.get("http://localhost:8080/servlet/error").executeAsync()
println(new String(IoUtil.readBytes(response.bodyStream())))
```

**Comment by looly** [comment]
这个是修复之前用户提的issue，如果服务端返回数据并不规范，会导致EOF异常，于是加了“容错”。

这块我考虑下，看是否需要修改。

**Comment by sppan24** [comment]
我还遇到使用PUT方法上传文件的时候，和之前版本(5.7.14)不一样，导致接收方校验出错，目前暂时还没时间去分析是哪里有问题。同样的代码5.7.14正确 5.7.16不正确。

**Comment by looly** [comment]
@sppan24 上传文件没有变动啊。你升级到5.7.19试下看是否还有问题。

**Comment by looly** [comment]
折中一下：

在`HttpGlobalConfig`中添加了全局开关：`setIgnoreEOFError`，默认是忽略，如果希望得到这个异常，置为false即可。

5.7.20增加，感谢。
