### ISSUE TITLE
SQLserver 不支持 DateUtil.parse 转换后的时间,在mapper文件中?

### ISSUE THREAD

**Issue by newbirdking** [looly/hutool#2095]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用了DateUtil.parse方法到mapper中查询#{ksj},出来的结果 2020-08-31 00:00:00  
而直接new Date()   ,结果: '2022-01-13 00:00:00'
最终结果语句就有问题:
SELECT a.*    FROM t_cx a    WHERE  a.f_ksj >= 2020-08-31 00:00:00     and a.f_jsj >= '2022-01-13 00:00:00'   

如实就有问题了.

1. 复现代码
 DateTime startTime = DateUtil.parse(timeList.get(1), DatePattern.NORM_DATE_PATTERN);
 Test t = new Test();
 t.setksj(startTime);
t.setjsj(new Date());

mapper 如下:
  <if test="dto.ksj != null">
            and a.f_ksj >= #{dto.ksj }
        </if>
        <if test="dto.jsj!= null">
            and a.f_jsj >= #{dto.jsj }
        </if>

```java
### SQL:     SELECT a.*    FROM t_cx a    WHERE  a.f_ksj >= 2020-08-31 00:00:00     and a.f_jsj >= '2022-01-13 00:00:00'     
### Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 从字符串转换日期和/或时间时，转换失败。
; uncategorized SQLException; SQL state [S0001]; error code [241]; 从字符串转换日期和/或时间时，转换失败。; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 从字符串转换日期和/或时间时，转换失败。]
Creating a new SqlSession
```
![image](https://user-images.githubusercontent.com/5317586/149295517-b6518f35-d640-4181-9182-19583b338730.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你这个原始日期格式和你的DatePattern.NORM_DATE_PATTERN不匹配导致的吧，检查下`timeList.get(1)`这个值是啥。

我又看了下问题，你的意思是使用new Date是带单引号，但是使用DateUtil.parse是不带单引号是吧？

你是用的什么数据库框架，myBatis么？可能是框架判断类型识别Date但是不识别DateTime造成的。

你可以：

```java
startTime.toJdkDate();
```

转换成JDK的Date对象。

**Comment by newbirdking** [comment]
转换之后,进行验证,确实可以.感谢,大佬.
