### ISSUE TITLE
请支持单位换算能力

### ISSUE THREAD

**Issue by ruei0325** [looly/hutool#2097]
可以增加一个单位换算能力吗？
1. 长度单位互转 cm/m/英寸等常见单位互转
2. 重量单位互转 g/kg/t/lb等常见单位互转

**Comment by looly** [comment]
这个不考虑，不就是*1000和/1000？

**Comment by ruei0325** [comment]
写代码不就是CRUD？

**Comment by looly** [comment]
没错，不过这个封装我个人觉得意义不大，你可以自己搞一个enum
