### ISSUE TITLE
WordUtil是否可以增加导出富文本的方法

### ISSUE THREAD

**Issue by parson1** [looly/hutool#2104]
是否可以增加功能，富文本编辑的带html标签的字符串，导出为真正的word（不是带html标签的word），目前还没有比较成熟的此类工具。某些富文本编辑器如tinymce的导出功能都是收费的，所以此功能应该还是比较受欢迎的。

**Comment by looly** [comment]
这个实现不了，富文本的内容千奇百怪，做word转换还做不到。
