### ISSUE TITLE
CBC/PKCS7Padding

### ISSUE THREAD

**Issue by dwxbc** [looly/hutool#2108]
用hutools进行AES加解密，需要使用CBC/PKCS7Padding
在Padding枚举下没有看到有PKCS7Padding，是不支持吗？

**Comment by looly** [comment]
需要引入BC库才支持，然后算法直接传字符串。

文档有说明，见：https://hutool.cn/docs/#/crypto/%E5%AF%B9%E7%A7%B0%E5%8A%A0%E5%AF%86-SymmetricCrypto
