### ISSUE TITLE
[QA] 可以扩展下表达式相关的功能么？ 类似spel

### ISSUE THREAD

**Issue by daidai21** [looly/hutool#2109]

**Comment by CherryRum** [comment]
参考下`cn.hutool.extra.expression.engine.spel`这个包
![image](https://user-images.githubusercontent.com/24296698/150349578-8177b9a0-7ce7-48a9-bc33-a29ebec723c4.png)

**Comment by looly** [comment]
Hutool封装了表达式引擎，可以兼容多种引擎。
