### ISSUE TITLE
实体类新加字段并热部署，BeanUtil.copyProperties无法拷贝新字段

### ISSUE THREAD

**Issue by kydxone** [looly/hutool#2115]
### 版本情况

JDK版本：    oracle-jdk_8_251
hutool版本： 5.5.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
实体类新加字段，并用jrebel热部署，BeanUtil.copyProperties无法拷贝新字段
1. 复现代码

```java
 List<WarehouseStockRecordVo> list = boDataSet.getData().stream().map(m -> {
                    WarehouseStockRecordVo vo = new WarehouseStockRecordVo();
                    BeanUtil.copyProperties(m, vo);//这里换成spring BeanUtils同名方法可以用
                    return vo;
                }
        ).collect(Collectors.toList());
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/18263593/150905733-3a42dfdf-ce4c-4be0-bdd5-6626ff661190.png)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可能是Bean缓存造成的问题。

5.7.21增加`BeanDescCache.INSTANCE.clear()`方法，可以试下清除缓存重新获取后是否可以。
