### ISSUE TITLE
CPU使用率获取不准确？

### ISSUE THREAD

**Issue by vickllny** [looly/hutool#2116]
### 版本情况

JDK版本：    openjdk_8_301
<img width="941" alt="16431003106982" src="https://user-images.githubusercontent.com/31479141/150942820-d3296885-0204-4296-b4b9-117542807adf.png">

hutool版本： 5.7.20

### 问题描述（包括截图）

1. 复现代码

```java

CpuInfo cpuInfo = OshiUtil.getCpuInfo();
double usage = cpuInfo.getUsed();
logger.debug("cpuUsage: {}", usage );
```
 得到的usage 总是比任务管理器里面的CPU使用率少5%-15% 左右。我是写了一个while(true) 执行的

**Comment by looly** [comment]
这块确实有问题，getUsed应该是getUser()，这个使用率是用户使用率，总的使用率应该包括用户使用率+系统使用率。

5.7.21此方法改为getUser + getSys。

你可以暂时使用：

```java
100 - cpuInfo.getFree()
```
