### ISSUE TITLE
有没有根据指定端口关闭进程的方法？

### ISSUE THREAD

**Issue by fendo8888** [looly/hutool#2124]
java 关闭指定端口 兼容windows和linux这种，https://www.zjh336.cn/?id=2055 这里引入了jPowerShell，感觉一个简单的功能，单独引入一个jar包，有点多余，不知道hutoll里有没有简单的方法

**Comment by looly** [comment]
没有此封装。

端口、进程等都是系统调用，涉及到权限问题，可以使用RuntimeUtil.exec执行系统命令。
