### ISSUE TITLE
官方文档的描述问题

### ISSUE THREAD

**Issue by jdAction** [looly/hutool#2125]
[[超时-TimedCache](https://www.hutool.cn/docs/#/cache/TimedCache?id=%e8%b6%85%e6%97%b6-timedcache)
](https://www.hutool.cn/docs/#/cache/TimedCache)

//启动定时任务，每5毫秒秒检查一次过期
timedCache.schedulePrune(5);

此行描述应该为：启动定时任务，每5毫秒清理一次过期条目，注释此行首次启动仍会清理过期条目

**Comment by jdAction** [comment]
注释此行首次启动仍会清理4毫秒内的过期条目

**Comment by looly** [comment]
最近修改，感谢。
