### ISSUE TITLE
敏感词过滤跟预期不符合

### ISSUE THREAD

**Issue by decadenceqi** [looly/hutool#2126]
### 版本情况

JDK版本：    openjdk version "11.0.10" 2021-01-19
hutool版本： 5.7.20

### 问题描述（包括截图）

初始化敏感词：习、习近、习近平
输入：习近平在干什么
输出：**平在干什么
期望：***在干什么

1. 复现代码
![image](https://user-images.githubusercontent.com/6396992/152750364-56736cb7-0ace-469c-9ad8-4e661bb70768.png)

**Comment by looly** [comment]
5.7.21修复此问题，感谢。

这个是匹配密集规则问题导致的。
