### ISSUE TITLE
StrUtil增加非空相等判断

### ISSUE THREAD

**Issue by ThomasLiuSeu** [looly/hutool#2127]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.20

### 问题描述（包括截图）
StrUtil比较能不能增加一个非空比较，比如String A, String B，仅当A和B 都不为 null或者 ""， 且A == B时返回true

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息
null
3. 测试涉及到的文件（注意脱密）
null
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个自行实现吧。

Hutool提供了`StrUtil.equals`。
