### ISSUE TITLE
如何拿到 http 请求里每一次重定向的返回headers

### ISSUE THREAD

**Issue by amosnothing** [looly/hutool#2129]
目前有一个小小的问题：
某个接口请求，我用了 jmeter & postman & 其他  java http 工具调用返回的都是正常的，但是 hutool-http 有问题

如果hutool-http请求不开启重定向， 确实可以拿到返回的 status code = 302，但是一旦开启了重定向则 status code = 400

之所以提这个问题，是想像下面这样，拿到每次的响应头信息

![image](https://user-images.githubusercontent.com/24653016/153161176-da9c6375-65fe-4911-b6e3-ce6fd1ce1865.png)

**Comment by looly** [comment]
确实无法拿到每次请求头和响应头。

是否使用最新版本Hutool？怀疑是重定向后的URL被转义导致的。

我先关闭issue，有问题再打开。

**Comment by amosnothing** [comment]
我用最新版本试过了 @looly 一样的有问题

**Comment by looly** [comment]
@amosnothing URL地址是否公开？我这边测试下。

**Comment by amosnothing** [comment]
@looly  
请求 URL：https://front-service.shoplinestg.com/uc/customers/check
请求 Method: Post
content-type: applications/json
body: `{
  "email": "32328423741@qq.com",
  "mobile_phone": "18620888981",
  "mobile_phone_country_calling_code": "86",
  "id": "",
  "country_code": "cn"
}`

**Comment by looly** [comment]
@amosnothing 已删。我这边测试。

**Comment by amosnothing** [comment]
@looly Hello ，作者大大，有结果了吗？

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/154409601-d1bcf893-b1c0-476c-a6db-38a4ed1a2b64.png)

经过测试，多次f返回302，最终指向登录页面了。
