### ISSUE TITLE
如何设计一个工具类？

### ISSUE THREAD

**Issue by xmt1139057136** [looly/hutool#213]
看看这篇文章：[http://www.xttblog.com/?p=3485](http://www.xttblog.com/?p=3485)

方法优先于对象
自动识别优于用户定义
便捷性与灵活性并存
适配与兼容
可选依赖原则
无侵入原则

**Comment by looly** [comment]
https://hutool.cn/docs/#/Hutool%E7%9A%84%E6%9C%8B%E5%8F%8B%E4%BB%AC

![image](https://user-images.githubusercontent.com/1432613/49500546-e6cb9d80-f8ab-11e8-9300-c951c1a106b9.png)

**Comment by xmt1139057136** [comment]
???

**Comment by looly** [comment]
那你的issue的意思是？

**Comment by xmt1139057136** [comment]
我的意思是，你的工具类，没有 final class ，也没有 abstract class 是有什么原因吗？

**Comment by looly** [comment]
final原来是有的，但是有用户提issue说需要继承工具类使用，因此就去掉了。

abstract个人认为没啥意义，就是避免new了这个工具。
