### ISSUE TITLE
CsvUtil这个工具类怎么自定义分隔符呢？

### ISSUE THREAD

**Issue by liufei4552** [looly/hutool#2135]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.20（请确保最新尝试是否还有问题）

### CsvUtil这个工具类怎么自定义分隔符呢？
![image](https://user-images.githubusercontent.com/26732771/153525849-911d343f-0fa5-4eca-ab50-cbad98e9e7f2.png)
![image](https://user-images.githubusercontent.com/26732771/153525917-f6e49a95-3e34-4ca9-9f50-7566eccdf057.png)
![image](https://user-images.githubusercontent.com/26732771/153525935-4760b091-02ad-4eb4-a52f-cba5c5cd55b4.png)
谢谢解惑

**Comment by xyz327** [comment]
```
CsvReadConfig csvReadConfig = new CsvReadConfig();
csvReadConfig.setFieldSeparator("|");
CsvReader csvReader = CsvUtil.getReader(file, csvReadConfig);
```

**Comment by liufei4552** [comment]
> ```
> CsvReadConfig csvReadConfig = new CsvReadConfig();
> csvReadConfig.setFieldSeparator("|");
> CsvReader csvReader = CsvUtil.getReader(file, csvReadConfig);
> ```

**Comment by liufei4552** [comment]
@xyz327，谢谢
