### ISSUE TITLE
cn.hutool.core.map.MapUtil  如果map是null 返回的不是默认值而是null

### ISSUE THREAD

**Issue by xu-zhipeng** [looly/hutool#2136]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public static <T> T get(Map<?, ?> map, Object key, TypeReference<T> type, T defaultValue) {
        return null == map ? null : Convert.convert(type, map.get(key), defaultValue);
 }
```

2. 如果map是null 返回的不是默认值而是null
用工具类的初衷就是少掉重复的判空转换这些代码，但是这个我又得再判一次空，感觉不太舒适（个人觉得）

**Comment by xyz327** [comment]
https://github.com/dromara/hutool/commit/e7a5295460470923255d3726ec1039582425bb35
这个已经改了

**Comment by pinkedidi** [comment]
你好，邮件已经收到，我会在24小时内回复给你

**Comment by looly** [comment]
请升级到最新版本Hutool。

**Comment by xu-zhipeng** [comment]
> 请升级到最新版本Hutool。

好的，谢谢，我也看到了
