### ISSUE TITLE
JSONUtil将对象转换成字符串丢失属性

### ISSUE THREAD

**Issue by guanqing7011** [looly/hutool#2143]
### 版本情况

JDK版本：    jdk1.8.0_152
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当无get方法或get方法名称与字段不一致时无法获取字段值

1. 复现代码

```java
@Builder
public class Person {

    private String name;
    private String mobile;
    private String birthday;

    public String getName() {
        return name;
    }

    public String getPhone() {
        return mobile;
    }
}
```

```java
 @Test
    public void test20() {
        Person person = Person.builder().name("zhangsan").mobile("111111111").birthday("19981111").build();
        log.info("huTool json = {}",JSONUtil.toJsonStr(person));
        //  封装的gsonUtil
        log.info("gson = {}",JsonUtil.toJson(person));
        log.info("fastjson ={}", JSON.toJSONString(person));
    }
```

2. 堆栈信息
11:22:10.983 [main] INFO com.junjie.demo.SomeTest - huTool json = {"name":"zhangsan"}
11:22:11.055 [main] INFO com.junjie.demo.SomeTest - gson = {"name":"zhangsan","mobile":"111111111","birthday":"19981111"}
11:22:11.146 [main] INFO com.junjie.demo.SomeTest - fastjson ={"name":"zhangsan","phone":"111111111"}

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Hutool对Bean的检查更为严格，你这个Bean中字段名字是`mobile`，getter方法却是`getPhone`，显然是不一致的，导致这个字段被忽略。

**Comment by guanqing7011** [comment]
不过没有`getter`方法的字段同样会被忽略，不过fastjson也有这个问题，gson却不会，这是设计成这样的是吗

**Comment by looly** [comment]
@guan-qing-mai-mai 是的，策略问题。Hutool的策略是没有getter方法字段忽略，但是如果这个字段是public，也可要读的。
