### ISSUE TITLE
VelocityEngine模板生成新文件乱码，版本4.2.1

### ISSUE THREAD

**Issue by zjw2011** [looly/hutool#215]
cn.hutool.extra.template.engine.velocity.VelocityEngine的类中
```
 @Override
	public Template getTemplate(String resource) {
 		return VelocityTemplate.wrap(engine.getTemplate(resource));
	}
```

由于 engine.getTemplate(resource) 没有指定编码，默认是ISO-8859-1，假如文件是UTF-8格式的，并且有汉字的，那么获取的文件中汉字是乱码，建议进行优化

**Comment by looly** [comment]
4.3.0修复此问题。感谢。
