### ISSUE TITLE
为什么hutool的国密四算法，key是16位的小写字母和数字混杂，我查到的SM4Util全都是32位字母数字混杂？

### ISSUE THREAD

**Issue by AbelKeithsun** [looly/hutool#2150]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个是BC库默认的密钥长度，可以自定义生成的随机密钥长度：

```java
KeyUtil.generateKey("sm4", 256).getEncoded();
```

关于字母数字混杂你看到的是Hex格式的密钥吧。
