### ISSUE TITLE
有没有去除字符串中所有空白字符的方法

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2151]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
有没有去除字符串中所有空白字符的方法
比如：
    private String removeBlank(String s) {
        return Objects.isNull(s) ? null
                : s.replaceAll("\n", "")
                        .replaceAll(" ", "")
                        .replaceAll("\t", "");
    }

**Comment by CherryRum** [comment]
貌似没有只有一个去除所有空白字符的
包含`\t \n`

**Comment by looly** [comment]
StrUtil.cleanBlank
