### ISSUE TITLE
是否考虑新增base58的编码呢?

### ISSUE THREAD

**Issue by xiguazhiPrince** [looly/hutool#2154]
如题

**Comment by CherryRum** [comment]
这玩意不是比特币用的吗？
@looly  需要吗？我可以加上去

**Comment by looly** [comment]
@CherryRum 现在由Base64、Base32、Base62，可以加入Base58。

我其实在想搞个类似commons-codec那样的`BaseNCodec`，最好复用代码。

你先加上吧，后续我再整理。

参考这个不错：https://github.com/chrylis/base58-codec/blob/develop/src/main/java/com/chrylis/codec/base58/Base58Codec.java

**Comment by CherryRum** [comment]
> @CherryRum 现在由Base64、Base32、Base62，可以加入Base58。
> 
> 我其实在想搞个类似commons-codec那样的`BaseNCodec`，最好复用代码。
> 
> 你先加上吧，后续我再整理。
> 
> 参考这个不错：https://github.com/chrylis/base58-codec/blob/develop/src/main/java/com/chrylis/codec/base58/Base58Codec.java

嗯 下午提

**Comment by changhr2013** [comment]
他实际的想法是不是更想要 base58check 😂

**Comment by CherryRum** [comment]
应该是的，那个实现挺麻烦的

**Comment by CherryRum** [comment]
由于实现的话，肯定要有规范，所以我看下是否需要，提供增加版本号的 base58check
https://rosettacode.org/wiki/Talk:Base58Check_encoding

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/2162
