### ISSUE TITLE
join的实用性的问题

### ISSUE THREAD

**Issue by huangrenxi** [looly/hutool#2156]
hutool的StrUtil.join没有可以在组合的前后加上连接符号的方法吗,还是要自己拼接？
比如我希望的是  ;1;2;3;
实际拼接出来的是  1;2;3

**Comment by changhr2013** [comment]
这种需求感觉直接外面套一层
```java
String format = String.format(";%s;", StrUtil.join(";", 1, 2, 3));
```
就可以了吧 😂，扩展 join 反而会引入复杂性。

**Comment by huangrenxi** [comment]
我举个例子 比如说连接符是引用自一个全局变量GlobalConfig.STR_DELIMITER那么你的代码就需要这样写
String format = String.format(GlobalConfig.STR_DELIMITER+"%s"+GlobalConfig.STR_DELIMITER, StrUtil.join(GlobalConfig.STR_DELIMITER, 1, 2, 3));

**Comment by looly** [comment]
可以使用`StrJoiner`：

```java
// [1,2,3]
StrJoiner append = StrJoiner.of(",", "[", "]")
				.append("1")
				.append("2")
				.append("3");
```
