### ISSUE TITLE
压缩两个文件 ，压缩包里面只有一个文件

### ISSUE THREAD

**Issue by xiaowei127** [looly/hutool#2159]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
压缩两个文件 ，压缩包里面只有一个文件

1. 复现代码

```java
    public static void main(String[] args) {
        File[] dd={FileUtil.file("F:\\sbimg\\qrcode\\邓伟532128199707273378.jpg")
                ,FileUtil.file("F:\\sbimg\\qrcode\\隆谨蔚430522199607208091.jpg")};

        ZipUtil.zip(FileUtil.file("F:\\zipFile\\test.zip"),false,dd);
    }
```
[test.zip](https://github.com/dromara/hutool/files/8122152/test.zip)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我这边测试没有问题啊。

请确认文件是否存在。

```java
File[] dd={FileUtil.file("d:\\test\\qr_a.jpg")
		,FileUtil.file("d:\\test\\qr_b.jpg")};

ZipUtil.zip(FileUtil.file("d:\\test\\qr.zip"),false,dd);
```

![image](https://user-images.githubusercontent.com/1432613/155592664-f3c9155b-96b7-435f-83e7-537c2f66c3e4.png)
