### ISSUE TITLE
在header中的未配置的字段也会被导出

### ISSUE THREAD

**Issue by laihg** [looly/hutool#2161]
### 版本情况

JDK版本：   1.8
hutool版本： 5.5.9

### 问题描述（包括截图）
1. 在header中未配置的字段(只需展示name，age)，excel导出时会带上其他字段。 往targetMap.put()时，是否考虑仅存在于headerAlias中的字段才能放入？
![image](https://user-images.githubusercontent.com/13795944/155523412-14d48f19-a5d4-4e9c-b589-f2321641a577.png)
3. IndexedComparator.compare()方法对两个值进行比较，getOrder()对未查询到的字段返回-1，两个参数都会-1，则compare()返回0，在调用TreeMap.put()方法时，等于0会被重新赋值。
![image](https://user-images.githubusercontent.com/13795944/155524018-018d8eb7-3871-41ca-ae33-2374e3cd0abb.png)

排查思路：
1. 复现代码
 public static void main(String[] args) throws FileNotFoundException {
        List<Student> students = new ArrayList<>();
        Student student1 = new Student(20, "20220224201", "张三", "班级名称11");
        Student student2 = new Student(23, "20220224202", "李思", "班级名称22");
        Student student3 = new Student(24, "20220224204", "王武", "班级名称33");
        students.add(student1);
        students.add(student2);
        students.add(student3);

        ExcelWriter writer = ExcelUtil.getWriter();
        writer.addHeaderAlias("name", "学生名称");
        writer.addHeaderAlias("age", "年龄");
        writer.setDefaultRowHeight(25);
        writer.setColumnWidth(-1, 25);
        writer.write(students, true);
        CellStyle headCellStyle = writer.getStyleSet().getHeadCellStyle();
        headCellStyle.setFillForegroundColor(IndexedColors.SKY_BLUE.getIndex());
        try( BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream("D:\\Work\\ProjectRecord\\1.xlsx"))) {
            writer.flush(out, true);
        } catch (Exception e) {
            log.error("data export failure", e);
        }
        finally {
            writer.close();
        }
    }

2. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
见：https://hutool.cn/docs/#/poi/Excel%E7%94%9F%E6%88%90-ExcelWriter?id=_4-%e8%87%aa%e5%ae%9a%e4%b9%89bean%e7%9a%84key%e5%88%ab%e5%90%8d%ef%bc%88%e6%8e%92%e5%ba%8f%e6%a0%87%e9%a2%98%ef%bc%89

使用`setOnlyAlias`
