### ISSUE TITLE
HttpUtil.downloadBytes 方法下载文件一直返回500状态

### ISSUE THREAD

**Issue by xionglei123** [looly/hutool#2164]
![1646027147262_5ADD11B5-5F4F-4883-81D5-69C8915EFAFD](https://user-images.githubusercontent.com/35485243/155933675-09d65d9d-df8d-491e-85b4-86c9c8581f54.png)

在访问文件服务时下载一直500，而后改用httpclient 就可以了

**Comment by looly** [comment]
提示验证失败，请检查：

1. Hutool是否为最新版本
2. URL中是否有验证字符串，被转义了。

方便的话QQ私聊给下URL我测试。
