### ISSUE TITLE
ListUtil.split 切分字符串错误

### ISSUE THREAD

**Issue by xzh0315** [looly/hutool#2169]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
个别情况下使用ListUtil.split 切分list 返回数量不正常，缺少部分数据。
1. 复现代码

```java
lic void testCollUtil() {
        List<List<Object>> objects = new ArrayList<>();
        for (int i = 0; i < 2264; i++) {
            List<Object> objects1 = new ArrayList<>();
            objects1.add(i);
            objects.add(objects1);
        }
        System.out.println(objects.size());
        List<List<List<Object>>> split = ListUtil.split(objects, 500);
//split.size  应该为5，但是目前返回结果为4，
        System.out.println(split.size());
```
分析原因应该为：cn.hutool.core.collection.Partition  中 total % length 这样取值有问题。希望尽快修复下。
2. 堆栈信息 

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xzh0315** [comment]
cn.hutool.core.collection.Partition 44#
 if(total % (length*size) > 0)
应该可以解决

**Comment by looly** [comment]
这是个bug，但是在新版本中已经修复了，请升级Hutool到5.7.22试下。
