### ISSUE TITLE
这个方法好坑，日过是DateTime 返回的是引用，日过是date 返回的是新对象，我用一个结果接受返回值，期望是新对象

### ISSUE THREAD

**Issue by xiaowan1993** [looly/hutool#217]
/**
	 * {@link Date}类型时间转为{@link DateTime}
	 * 
	 * @param date Long类型Date（Unix时间戳）
	 * @return 时间对象
	 * @since 3.0.7
	 */
	public static DateTime date(Date date) {
		if (date instanceof DateTime) {
			return (DateTime) date;
		}
		return new DateTime(date);
	}

这个方法好坑，日过是DateTime 返回的是引用，日过是date 返回的是新对象，我用一个结果接受返回值，期望是新对象，因为我还要使用原有对象，但是有时候返回新对象，有时候返回原有对象，让系统出现莫名其妙的bug  我现在 只敢这样使用了，DateUtil.date(new Date(date.getTime))  代码很不友好

**Comment by xiaowan1993** [comment]
如果是引用的话 方法最好不要给返回值，新对象才给返回值，这样更好理解

**Comment by looly** [comment]
此方法本质是类型转换，4.3.1会增加`dateNew`方法。感谢。
