### ISSUE TITLE
DFA支持检查英文单词吗

### ISSUE THREAD

**Issue by liunancun** [looly/hutool#2174]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
WordTree tree = new WordTree();
tree.addWord("a");

String text = "my apple";

System.out.println(tree.matchAll(text));
```

2. 执行结果
[a]

针对英文来说，应该是整个单词匹配才算敏感词，现在测试的结果是按字母匹配了

**Comment by looly** [comment]
DFA模块没有分词功能，因此`addWord`中你必须键入完整的单词，即：

```java
WordTree tree = new WordTree();
tree.addWord("apple");
```

**Comment by liunancun** [comment]
@looly 
那比如puss和pussycat这种有包含关系的单词呢
如果addWord录入的是puss，判断的时候会把pussycat也判断成违规
我们是想用这个功能来检测是否录入品牌词
