### ISSUE TITLE
关于strbuilder性能问题

### ISSUE THREAD

**Issue by k297512373** [looly/hutool#2177]
关于strbuilder
我使用stringbuilder的setLength(0)的方式来清空stringbuilder
发现效率比strbulider的reset方法效率高一倍
![image](https://user-images.githubusercontent.com/46101972/156740057-142b1a63-18e6-40a3-803f-04ab399bf8d3.png)
![image](https://user-images.githubusercontent.com/46101972/156740123-6419e8c4-a72e-4ecb-91e7-48922a76941c.png)

**Comment by changhr2013** [comment]
底层都是给位置指针赋了一下值，基本没什么区别，同样的代码我的第二段要更快点。
```java
public static void main(String[] args) {

    long start = Instant.now().toEpochMilli();
    StringBuilder builder1 = new StringBuilder();
    for (int i = 0; i < 1000000; i++) {
        builder1.append("test");
        builder1.setLength(0);
    }
    System.out.println(Instant.now().toEpochMilli() - start);

    long start2 = Instant.now().toEpochMilli();
    StrBuilder builder2 = StrBuilder.create();
    for (int i = 0; i < 1000000; i++) {
        builder2.append("test");
        builder2.reset();
    }
    System.out.println(Instant.now().toEpochMilli() - start2);
}
```

```text
14
10
```

**Comment by looly** [comment]
是滴。其实JDK8的StringBuilder更快，因为某些方法使用了String的内部属性，这些属性对于Hutool不可见。

StrBuilder是4.x引入，是为JDK7服务的产物，因为JDK7没有setLength这个方法。

6.x会移除StrBuilder这个类。
