### ISSUE TITLE
是否考虑增加Guava的Table数据结构

### ISSUE THREAD

**Issue by ruansheng8** [looly/hutool#2179]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X

### 问题描述（包括截图）

Guava 提供的Table 这种二维表数据结构在工作上还是比较常用的，是否有考虑封装一个

![image](https://user-images.githubusercontent.com/24709538/156919033-5d128fbe-f995-4eb4-b266-3a0586cf2c80.png)

**Comment by CherryRum** [comment]
貌似这玩意有点难=-=

**Comment by looly** [comment]
确实应该有的……稍后处理。

**Comment by looly** [comment]
@CherryRum 其实就是包装成`Map<Pair<R, C>, V>`

**Comment by CherryRum** [comment]
> @CherryRum 其实就是包装成`Map<Pair<R, C>, V>`

有pair那就还好

**Comment by ruansheng8** [comment]
> @CherryRum 其实就是包装成`Map<Pair<R, C>, V>`

Map<Pair<R, C>, V> 根据行或者列查询可能就不方便了，用 Map<R, Map<C, V>> 这种结构应该会好一点

**Comment by looly** [comment]
说实话，我低估了这个的实现难度。

Guava的实现方式非常多，最多使用的是`HashBasedTable`，结构是`Map<R, Map<C, V>>`，Hutool对应实现了`RowKeyTable`，其他实现暂时没有添加，后续慢慢加吧。、

HashBasedTable的实现难点在于效率，要想实现高效的使用，就要重新实现`columnMap`等方法，各种继承抽象后包装实现。

5.7.23加入这个类。

不过相比Guava，有些方法名字做了修改，如`column()`方法我改为`getColumn()`，我想这个方法更加舒服。

```java
final Table<Integer, Integer, Integer> table = new RowKeyTable<>();
table.put(1, 2, 3);
table.put(1, 6, 4);

Assert.assertEquals(new Integer(3), table.get(1, 2));
Assert.assertNull(table.get(1, 3));

//判断row和column确定的二维点是否存在
Assert.assertTrue(table.contains(1, 2));
Assert.assertFalse(table.contains(1, 3));

//判断列
Assert.assertTrue(table.containsColumn(2));
Assert.assertFalse(table.containsColumn(3));

// 判断行
Assert.assertTrue(table.containsRow(1));
Assert.assertFalse(table.containsRow(2));


// 获取列
Map<Integer, Integer> column = table.getColumn(6);
Assert.assertEquals(1, column.size());
Assert.assertEquals(new Integer(4), column.get(1));
```
