### ISSUE TITLE
图形验证码工具类死循环

### ISSUE THREAD

**Issue by boasad** [looly/hutool#2186]
### 版本情况

JDK版本：    JDK1.8
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
![image](https://user-images.githubusercontent.com/64964182/157887658-120287c0-dc7a-46a2-b7b3-494d38119731.png)
在序列化LineCaptcha到redis时会死循环,具体异常如下
![image](https://user-images.githubusercontent.com/64964182/157888121-68d3526c-d300-4a2e-84c1-aed89784ba8d.png)
在更 改为lc.getCode()之后，问题解除

**Comment by xiejiaxing163** [comment]
unsubscribe
















在 2022-03-11 21:37:59，"boasad" ***@***.***> 写道：

版本情况

JDK版本： JDK1.8
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

问题描述（包括截图）
复现代码

在序列化LineCaptcha到redis时会死循环,具体异常如下

在更 改为lc.getCode()之后，问题解除

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by looly** [comment]
LineCaptcha对象不要考虑序列化……
