### ISSUE TITLE
httputil 302

### ISSUE THREAD

**Issue by spiritn** [looly/hutool#2187]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
http get请求设置禁止重定向无效。注意没有code,data等字段，响应内容为：
{
    "versioninfo": {
        "appurl": "https://net/mobile/app/ce_monitor-2_0.jar",
        "currentVersion": 2,
        "isUpdated": false,
        "md5": "b91bd32b4e47e70b9392d706173a1994",
        "updateTitle": "需升级至新版",
        "versionname": "版本2"
    }
}
但是用hutool的HttpUtils发送请求，返回302 Moved.设置setFollowRedirects(false)也无效。
    <html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
debug从httpConnection copy url直接复制到浏览器也返回正常。
感觉问题出在hutool自动进行重定向？
1. 复现代码
HttpRequest.get(XXX).form(XXX)..setFollowRedirects(false)

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）
实际URL不方便发，私聊可发

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
自动重定向关闭导致的问题，调用`HttpRequest.setFollowRedirects(true)`即可。
