### ISSUE TITLE
HttpRequest重定向重复拼接参数

### ISSUE THREAD

**Issue by spiritn** [looly/hutool#2189]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22

### 问题描述（包括截图）

1. 复现代码
代码为：
http get请求，有7个拼接参数
```
HttpRequest httpRequest = HttpRequest.get(ddDomain + checkUpdateUrl).formStr(paramMap).setFollowRedirects(true);
HttpResponse httpResponse = httpRequest.execute();
```
这里设置setFollowRedirects(true)是因为需要自动重定向，不然返回302，#2187
问题：重定向之后会再次去拼接paraMap发出请求，造成错误，下面有debug信息

3. 堆栈信息
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/40299015/158095436-b849f364-aa53-468f-8373-3fb9766ef9a7.png">

**Comment by looly** [comment]
这块没有注意。

5.7.23修复此问题，修改后，非rest请求在重定向时，忽略参数。
