### ISSUE TITLE
国密加密测试案例报错

### ISSUE THREAD

**Issue by zdrott** [looly/hutool#2193]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/44641350/158302653-715753c3-f51c-4372-86ec-cee2db4e566c.png)
![image](https://user-images.githubusercontent.com/44641350/158302670-7cbb69fa-742b-4f65-b4ba-0b99ed72a2d7.png)
![image](https://user-images.githubusercontent.com/44641350/158302756-81c12b0e-8fea-46a7-888b-7c8acc0989e7.png)

1. 复现代码

```java
Console.log("报错了");
public class HutoolsTest {


    public static void main(String[] args) {

        SM2 sm2 = SmUtil.sm2();

        String content = "1111Hanley.";

        String sign = sm2.signHex(HexUtil.encodeHexStr(content));

        // true
        boolean verify = sm2.verifyHex(HexUtil.encodeHexStr(content), sign);
        System.out.println(verify);
    }
}


   <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.7.22</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15to18</artifactId>
            <version>1.69</version>
        </dependency>

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
检查是否引入多个版本的BC库导致包冲突了？

**Comment by zdrott** [comment]
多谢，是jar包冲突，一部分我通过lib引入了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] 国密加密测试案例报错 (Issue #2193)





 
检查是否引入多个版本的BC库导致包冲突了？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
