### ISSUE TITLE
mapToBean 定义映射字段对应关系不生效

### ISSUE THREAD

**Issue by StephonDNG** [looly/hutool#2196]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.13（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
mapToBean 定义映射字段对应关系不生效
1. 复现代码

```java
       String data = "......xmldata";
        Map<String,String> fieldMap = new HashMap<>();
        fieldMap.put("request","Request");
        fieldMap.put("package","packageItem");

        final Map<String, Object> map = XmlUtil.xmlToMap(XmlUtil.readXML(data));
        if (null != map && map.size() == 1) {

            if (map.containsKey("request")) {
                // 只有key和bean的名称匹配时才做单一对象转换
                Request request = BeanUtil.toBean(map.get("request"), Request.class, CopyOptions.create().setFieldMapping(fieldMap));
                System.out.println(JSONUtil.toJsonStr(request));
            }
        }

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by StephonDNG** [comment]
```             // 遍历目标bean的所有属性
		BeanUtil.descForEach(actualEditable, (prop)->{
			if(false == prop.isWritable(this.copyOptions.isTransientSupport())){
				// 字段不可写，跳过之
				return;
			}
			// 检查属性名
			String fieldName = prop.getFieldName();
			if (CollUtil.contains(ignoreSet, fieldName)) {
				// 目标属性值被忽略或值提供者无此key时跳过
				return;
			}

			// 对key做映射，映射后为null的忽略之
			// 这里 copyOptions.editFieldName() 不能少，否则导致 CopyOptions setFieldNameEditor 失效
			final String providerKey = copyOptions.editFieldName(copyOptions.getMappedFieldName(fieldName, true));
			if(null == providerKey){
				return;
			}
			if (false == valueProvider.containsKey(providerKey)) {
				// 无对应值可提供
				return;
			}

			// 获取目标字段真实类型
			final Type fieldType = TypeUtil.getActualType(this.destType ,prop.getFieldType());

			// 获取属性值
			Object value = valueProvider.value(providerKey, fieldType);
			if(null != copyOptions.propertiesFilter && false == copyOptions.propertiesFilter.test(prop.getField(), value)) {
				return;
			}

			if ((null == value && copyOptions.ignoreNullValue) || bean == value) {
				// 当允许跳过空时，跳过
				// 值不能为bean本身，防止循环引用
				return;
			}

			prop.setValue(bean, value, copyOptions.ignoreNullValue, copyOptions.ignoreError);
		});```

**Comment by looly** [comment]
当然不生效了啊

```java
fieldMap.put("request","Request");

Request request = BeanUtil.toBean(map.get("request"), Request.class, CopyOptions.create().setFieldMapping(fieldMap));
```

这句话中你只是将request映射为Request，但是你没用到`Request`这个名字啊，你这里应该是字段映射才对。

**Comment by StephonDNG** [comment]
> 当然不生效了啊
> 
> ```java
> fieldMap.put("request","Request");
> 
> Request request = BeanUtil.toBean(map.get("request"), Request.class, CopyOptions.create().setFieldMapping(fieldMap));
> ```
> 
> 这句话中你只是将request映射为Request，但是你没用到`Request`这个名字啊，你这里应该是字段映射才对。

不是的，这个字段当然是不生效的，另外一个字段不生效，在循环的过程中到映射的字段CopyOptions会丢失

**Comment by StephonDNG** [comment]
另外，mapToBean外层没有提供传递CopyOptions的方法好像（旧的已经弃用），所以我只能拿一层toBean

原始结构是 `<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><request><deliveryOrder><deliveryOrderCode>xx</deliveryOrderCode><deliveryOrderId>xxx</deliveryOrderId><warehouseCode>xxxxxx</warehouseCode><orderType>xxxx</orderType><outBizCode>xxxx-xx-xx</outBizCode><operatorName>xxxx</operatorName><operateTime>2022-03-15 17:49:09</operateTime><status>DELIVERED</status><invoices/></deliveryOrder><packages><package><logisticsCode>YTO</logisticsCode><expressCode>xxxxxx</expressCode><packageCode>xxxxx-1</packageCode><length>0.0</length><width>0.0</width><height>0.0</height><theoreticalWeight>0.0</theoreticalWeight><weight>1.52</weight><volume>0.0</volume><packageMaterialList><packageMaterial><type>xx-xxx-xx</type></packageMaterial></packageMaterialList><items><item><itemCode>xxxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxx</itemCode><quantity>1</quantity></item></items></package><package><logisticsCode>YTO</logisticsCode><expressCode>xxxx</expressCode><packageCode>xxx-xx</packageCode><length>0.0</length><width>0.0</width><height>0.0</height><theoreticalWeight>0.0</theoreticalWeight><weight>2.97</weight><volume>0.0</volume><packageMaterialList><packageMaterial><type>xx-xx-xx</type></packageMaterial></packageMaterialList><items><item><itemCode>xxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxx</itemCode><quantity>1</quantity></item><item><itemCode>xxxx</itemCode><quantity>1</quantity></item></items></package></packages><orderLines><orderLine><orderLineNo>1</orderLineNo><itemCode>xxx</itemCode><ownerCode>xxx</ownerCode><actualQty>2</actualQty><batchs><batch><inventoryType>ZP</inventoryType><actualQty>2</actualQty></batch></batchs></orderLine><orderLine><orderLineNo>2</orderLineNo><itemCode>xxxxx</itemCode><ownerCode>xxx</ownerCode><actualQty>2</actualQty><batchs><batch><inventoryType>ZP</inventoryType><actualQty>2</actualQty></batch></batchs></orderLine><orderLine><orderLineNo>3</orderLineNo><itemCode>xxxx</itemCode><ownerCode>xxxx</ownerCode><actualQty>2</actualQty><batchs><batch><inventoryType>ZP</inventoryType><actualQty>2</actualQty></batch></batchs></orderLine><orderLine><orderLineNo>4</orderLineNo><itemCode>xxxx</itemCode><ownerCode>BL8755</ownerCode><actualQty>2</actualQty><batchs><batch><inventoryType>ZP</inventoryType><actualQty>2</actualQty></batch></batchs></orderLine></orderLines></request>`

取packages 里面的 list<Package> 由于package是java中关键字所以需要映射一个新的属性名

**Comment by StephonDNG** [comment]
final Map<String, Object> mapd = XmlUtil.xmlToMap(XmlUtil.readXML(data));

        Map<String,String> mapping = new HashMap<>();
        mapping.put("request","Request");
        mapping.put("Request","request");
        mapping.put("package","packageItem");
        mapping.put("packageItem","package");

        Request request = BeanUtil.mapToBean(mapd,Request.class,false, CopyOptions.create().setFieldMapping(mapping));
        System.out.println(JSONUtil.toJsonStr(request));

@looly

**Comment by looly** [comment]
@DongJigong 说实话我还是没看懂你的问题在哪里。

我理解的是你想把一个多层的XML转换为Bean对象，但是很遗憾BeanUtil.mapToBean只能实现单层转换，下一层不会转换，建议使用JSON模块完成此功能，具体可以借助JSONDeserializer。

欢迎交流你的解决方案。
