### ISSUE TITLE
提供一个集合去重的方法,看是否有幸能被收录

### ISSUE THREAD

**Issue by kirning** [looly/hutool#2198]
### 版本情况

JDK版本：    openjdk_8_201

### 问题描述（包括截图）

提供一个集合去重的方法，我没有找到对应的，所以自己写了一个。看是否有幸能被收录
```java
    private <T, V> List<T> removeDuplicate(Collection<T> list, Function<T.V> callback) {
        Set<V> temp = new HashSet<>(list.size());
        List<T> resultList = new ArrayList<>();
        for (T item : list) {
            if (temp.add(callback.apply(item))) {
                resultList.add(item)
            }
        }
        return resultList;
    }
```

**Comment by xyz327** [comment]
`CollectionUtil.distinct()` 集合去重可以用这个。而且你这个 去重里面的 callback 啥意思？ 转换？

**Comment by shenshaoming** [comment]
> 

他那个callback意思是按照那个apply出来的值去重(唯一键)。

**Comment by shenshaoming** [comment]
> `CollectionUtil.distinct()` 集合去重可以用这个。而且你这个 去重里面的 callback 啥意思？ 转换？

他那个callback意思是按照那个apply出来的值去重(唯一键)。

**Comment by xyz327** [comment]
> > `CollectionUtil.distinct()` 集合去重可以用这个。而且你这个 去重里面的 callback 啥意思？ 转换？
> 
> 他那个callback意思是按照那个apply出来的值去重(唯一键)。

原来如此。那他这个意思不按equals去重.  也可能会有一定的业务场景

**Comment by looly** [comment]
@kirning @shenshaoming 那这个需求完全可以使用5.7.23新增的`UniqueKeySet`完成去重。

**Comment by kirning** [comment]
好的哈，期待5.7.23新版本
