### ISSUE TITLE
MetaUtil.getTableMeta 查询表元数据，返回的数据类型问题

### ISSUE THREAD

**Issue by ethanxlau** [looly/hutool#2201]
### 版本情况

JDK版本：    java version "1.8.0_181"
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
通过调用MetaUtil工具类查询oracle表元数据。
源表 TIMESTAMP 类型的字段，
调用MetaUtil#getTableMeta方法返回的Column对象的typeName属性不应带精度，因为精度已经在digit属性中指明了。
如图：typeName=TIMESTAMP(3)
期望的结果：typeName=TIMESTAMP

<img width="1272" alt="2" src="https://user-images.githubusercontent.com/6408198/158791579-7c3bd1b1-00d0-4ca9-8953-b9b30d092e02.png">

1. 复现代码

```java
cn.hutool.db.meta.MetaUtil#getTableMeta(javax.sql.DataSource, java.lang.String)
```

oracle表结构：
```
CREATE TABLE "yf_test_etl"
(
    "id"           NUMBER(10, 0) NOT NULL ENABLE,
    "f_int"        NUMBER(10, 0),
    "f_varchar"    VARCHAR2(50),
    "f_tinyint"    NUMBER(4, 0),
    "f_smallint"   NUMBER(5, 0),
    "f_mediumint"  NUMBER(7, 0),
    "f_bigint"     NUMBER(19, 0),
    "f_float"      NUMBER(6, 3),
    "f_double"     NUMBER(20, 4),
    "f_decimal"    NUMBER(20, 5),
    "f_date"       VARCHAR2(16) DEFAULT '2020-01-01',
    "f_time"       VARCHAR2(16),
    "f_datetime"   TIMESTAMP(0),
    "f_year"       VARCHAR2(100),
    "f_timestamp"  TIMESTAMP(0),
    "f_char"       CHAR(1),
    "F_TIMESTAMP2" TIMESTAMP(2),
    "F_TIMESTAMP3" TIMESTAMP(3),
    PRIMARY KEY ("id")
)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
底层调用的`ResultSet#.getString("TYPE_NAME")`，因此是驱动返回的。

这块5.7.23做个处理：

```
typeName = ReUtil.delLast("\\(\\d+\\)", typeName);
```

感谢意见。
