### ISSUE TITLE
The part /xl/worksheets/sheet1.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller

### ISSUE THREAD

**Issue by J-Orange-Sun** [looly/hutool#2209]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
偶发性出现如下异常

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/79563279/159227790-98f7051a-96c7-4139-acd5-5f5f1fc8334b.png">

1. 复现代码
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/79563279/159227938-5ca383d5-1589-48ca-8a41-6c0cef83f500.png">

```java
Console.log("报错了");
```

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不太好确定问题，看样子是保存时XML无法写入。

升级下POI版本尝试吧。
