### ISSUE TITLE
【BUG】JSONUtil.toJsonStr 忽略空值 BUG

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#221]
![image](https://user-images.githubusercontent.com/10429917/49788766-2ccda900-fd65-11e8-89be-afe8db38ebfc.png)

data这一属性值为null 
使用`JSONObject(Object source, boolean ignoreNullValue)` 这个构造方法，JSONObject 构造出来的是这样的：
![image](https://user-images.githubusercontent.com/10429917/49789000-cd23cd80-fd65-11e8-851c-f22ec8f3b35a.png)

但是使用 JSONUtil.toJsonStr 转成 String 的时候，是有问题的。
![image](https://user-images.githubusercontent.com/10429917/49789057-f8a6b800-fd65-11e8-9821-2edca5cbcd2f.png)

**Comment by looly** [comment]
4.3.1修复此问题，感谢。

**Comment by jokersunny** [comment]
问题重现了，请问怎么处理

![企业微信截图_16463253865562](https://user-images.githubusercontent.com/23479171/156609286-58ca3125-ec38-4b40-a25c-4d0eb07d1cc1.png)

![image](https://user-images.githubusercontent.com/23479171/156609329-bf6fb1ee-bb0b-451b-80af-eba77e3a86de.png)

**Comment by jokersunny** [comment]
5.63 重现，请问怎么处理
![image](https://user-images.githubusercontent.com/23479171/156609469-02f31d51-1fe6-468b-ad10-f4a9d9f326c6.png)


![image](https://user-images.githubusercontent.com/23479171/156609498-607914c1-2d06-400b-91c3-ab77e96d8170.png)

**Comment by looly** [comment]
@jokersunny 最新的是5.7.22，升级试下。

**Comment by wwyynnn** [comment]
Hi @looly ，这个 bug 到目前位置还没有修复，最新版本 5.8.5 下进行测试， JSONUtil.toJsonStr() 方法仍然会过滤掉 value为 null 的值。举例如下：
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/29294095/186066140-1553aea6-c7d3-4d0f-ae47-a16e92cf0e68.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/29294095/186066185-bc77ef98-096c-423f-af71-37b5d27620b6.png">
请问，JSONUtil工具自身不支持对 null 值的保留？是否可以像 
public static JSONArray parseArray(Object arrayOrCollection, boolean ignoreNullValue)  方法一样，给出一个带有开关，允许配置是否忽略 null 值的 toJsonStr() 方法？
