### ISSUE TITLE
探讨：ExcelUtil作者的实现（使用）思想

### ISSUE THREAD

**Issue by 120011676** [looly/hutool#2214]
探讨：ExcelUtil作者的实现（使用）思想

增加、修复缺陷的时候看了下作者的Excel实现源码，理解到的是作者希望实现一个实时可读、可写的简便工具类，👍🏻，好用；
发现实时可读写只有在Excel是文件（File对象或String文件地址）才支持，还没用应用到其他方式；
想着扩展一下，发现是存着文件对象转换读写的，在InputStream情况下不好扩展；想着核心方法只提供一种Workbook操作实现，其他方法在上面扩展。只对Workbook做读写转换保存、引用返回，感觉可能要大修下。
探讨。（不知道写哪儿，所以写这里了，有不便望谅解，qq：120011676）

**Comment by looly** [comment]
你可以看下POI的`WorkbookFactory.create`方法，针对流和文件实现方式不同。

流读出来是不可编辑的，编辑了也没有意义，你也写不出到流中去。所以针对你说的InputStream扩展如何扩展？使用临时文件？

你也可以看下`ExcelBase`，本质上是对`Sheet`的封装。

**Comment by 120011676** [comment]
@looly  👍🏻，URL Excel 读了（业务判断是否需要修改）保存，2个文件sha1是否一样

**Comment by looly** [comment]
@120011676 没看懂你的意思 。我理解你的意思是读取时检查文件是否变更？那这个和流有啥关系？

**Comment by 120011676** [comment]
@looly  写代码实现这样的业务是否代码简洁、便利，能否实现，实现后的下载文件sha1（没修改文件内容）与下载源的文件sha1是否一致
