### ISSUE TITLE
使用hutool的http工具后，如何统一处理Request和Response

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2217]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22

### 问题描述（包括截图）

使用hutool的http工具，一般都会有统一处理Request和Response的需求，比如：
1. 打印请求、响应日志
2. 在请求中添加统一的参数或头，如：MDC的trace_id
3. 统一加密请求参数、解密响应参数

现在只知道可以这样，每次都要写一些重复的代码，及其繁琐也不容易维护

```java
    HttpRequest httpRequest = HttpUtil.createGet("www.baidu.com");
    httpRequest.addInterceptor(request -> log.info("http请求开始, {}", request));
    HttpResponse httpResponse = httpRequest.execute();
    log.info("http请求结束, {}", httpResponse);
```

请问如何统一统一处理Request和Response，不用每次调用都重复编码

建议：
1. addInterceptor方法不要返回void，否则打断了链式编码
2. Interceptor有两个抽象方法，这样可以统一处理request和response
```java
public abstract class HttpInterceptor {

    /**
     * 在请求之前执行
     *
     * @param httpRequest http请求
     */
    abstract void before(HttpBase<?> httpRequest);

    /**
     * 在响应之后执行
     *
     * @param httpResponse http响应
     */
    abstract void after(HttpBase<?> httpResponse);

}
```
3. 类似与GlobalHeaders一样，可以配置全局(默认)的Interceptor chain，在每次执行方法时都默认调用

**Comment by looly** [comment]
5.8.0修改：

1. `HttpRequest.addInterceptor`增加this返回值
2. 增加GlobalInterceptor，只针对请求前
3. HttpResponse不添加任何拦截器，因为此对象内容不可写，考虑获取响应对象后自行转换处理。

**Comment by ljynfo** [comment]
> 5.8.0修改：
> 
> 1. `HttpRequest.addInterceptor`增加this返回值
> 2. 增加GlobalInterceptor，只针对请求前
> 3. HttpResponse不添加任何拦截器，因为此对象内容不可写，考虑获取响应对象后自行转换处理。

@looly 请问没用办法想对httpRequest一样去对HttpResponse做统一处理吗？比如：统一打印日志，或者类似AOP那样
调用外部系统，百分百是需要关心日志的，没法统一处理只能每次手动写也太麻烦了
或者在process方法加上返回值

建议：
```java

@FunctionalInterface
public interface HttpInterceptor {

	/**
	 * 处理请求
	 *
	 * @param request 请求
	 * @return {@link HttpResponse}
	 */
	HttpResponse process(HttpRequest request);

```

@looly okhttp3里的Interceptor就是这样的
![image](https://user-images.githubusercontent.com/42232422/160312795-b65d6e7c-dfce-4032-a3ed-aff07c511a1d.png)



@looly apache的http工具包里也有对HttpResponse的统一处理
![image](https://user-images.githubusercontent.com/42232422/160313348-f0f8cbdb-cf4a-42e6-bcf7-353c2c8e27fa.png)
![image](https://user-images.githubusercontent.com/42232422/160313368-2018029a-aeb2-4a95-9819-bede82a0ca32.png)


说明这个是一个真实的需求，请务必考虑

**Comment by looly** [comment]
5.8.0.M2
增加GlobalInterceptor.addRequestInterceptor、GlobalInterceptor.addResponseInterceptor

**Comment by anaer** [comment]
HttpRequest 不提供获取body的方法吗?

**Comment by looly** [comment]
body()方法是获取body，不过并不是发送的body。

**Comment by anaer** [comment]
@looly HttpRequest的toString方法, 只打印了body参数, 没有打印form表单参数,
想自定义下输出格式, HttpRequest又只提供了form()方法获取表单数据, 没有获取body参数的方法😓

**Comment by looly** [comment]
@anaer 确实没有，因为最终生成报文是HttpUrlConnection来完成的，因此Hutool没法拿到实际发送的报文。

**Comment by anjia0532** [comment]
是否考虑增加 GlobalInterceptor.addExceptionInterceptor?
场景：
现在请求前有addRequestInterceptor,然后执行send（真实请求），如果send报错（比如超时），就直接throw了，不走addResponseInterceptor了。
比如需要全局打印请求和响应参数，或者执行耗时，或者用sentinel处理异常时，针对超时等异常场景，目前无法兜住。

**Comment by EFGL** [comment]
能否增加一个便捷方法
`HttpUtils.addGlobalHeaders()`
