### ISSUE TITLE
cn.hutool.poi.excel.ExcelWriter#writeImg适用性较差

### ISSUE THREAD

**Issue by QiuSoft** [looly/hutool#2218]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.18

### 问题描述（包括截图）
excel写图片方法只能传File作为资源, http(s)等协议的网络资源不支持包装成FIle，存在局限性
建议重载方法支持 byte[], Resouce
![image](https://user-images.githubusercontent.com/49966947/160081901-28a63246-a73a-4de0-aca0-12d7fdabe781.png)

**Comment by looly** [comment]
5.8.0 ExcelWriter增加重载：

```java
public ExcelWriter writeImg(byte[] pictureData, int imgType, int dx1, int dy1, int dx2,
								int dy2, int col1, int row1, int col2, int row2) {
```
