### ISSUE TITLE
LineCaptcha.createCode() 第一次生成很慢

### ISSUE THREAD

**Issue by hi-asan** [looly/hutool#2219]
### 版本情况

JDK版本：    java version "1.8.0_144"
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

LineCaptcha.createCode() 第一次生成很慢

1. 复现代码

<img width="828" alt="image" src="https://user-images.githubusercontent.com/12293038/160219952-476d7f28-47d9-4a1d-a5bc-fd40add1c4eb.png">
<img width="181" alt="image" src="https://user-images.githubusercontent.com/12293038/160220002-ad43d5ea-bdbf-423e-9be8-fdca71bff222.png">

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
因为第一次调用需要生成随机字符串，是否由于第一次调用随机数种子生成消耗了时间。
