### ISSUE TITLE
IdcardUtil#getCityCodeByIdCard获取城市code少了一位

### ISSUE THREAD

**Issue by stefanxfy** [looly/hutool#2224]
IdcardUtil#getCityCodeByIdCard获取城市code少了一位

![image](https://user-images.githubusercontent.com/32997428/160348430-0459f273-aeb2-4b35-9a6d-09be2cb984ed.png)
![image](https://user-images.githubusercontent.com/32997428/160348634-2cbd51d9-1c47-4778-826a-840705143f12.png)
第1、2位数字表示：所在省份的代码
第3、4位数字表示：所在城市的代码
第5、6位数字表示：所在区县的代码

应该是idcard.substring(0, 6)吧

**Comment by looly** [comment]
这块确实有问题，不过并不是获取0，6，而是0，4，因为是获取的市级别编码。

**Comment by stefanxfy** [comment]
OK，感谢
