### ISSUE TITLE
GET参数有+号会变成空格

### ISSUE THREAD

**Issue by amosnothing** [looly/hutool#2226]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
    @Test
    public void test6()  {
        String url = "https://postman-echo.com/get";
        final Map<String, Object> map = new HashMap<>();
        map.put("aaa", "application+1@qqq.com");
        HttpResponse response =HttpUtil.createGet(url).form(map).execute();
        System.out.println(response.body());
    }
```

**Comment by amosnothing** [comment]
{"args":{"aaa":"application 1@qqq.com"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6242e44c-58b5f74e435f6a29282a3a9f","accept":"text/html,application/json,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Hutool","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.8"},"url":"https://postman-echo.com/get?aaa=application+1@qqq.com"}

**Comment by looly** [comment]
因为form方法调用后会拼接在url后，你看请求的`url":"https://postman-echo.com/get?aaa=application+1@qqq.com"`这段中+没有转义，可能postman对url中的参数做了反转义，+转为空格了。

根据RFC3986规范，URL参数值中`+`是安全字符，无需转义，因此此处没问题。如果你有问题，可以在客户端上手动转义此字符。

**Comment by amosnothing** [comment]
> 因为form方法调用后会拼接在url后，你看请求的`url":"https://postman-echo.com/get?aaa=application+1@qqq.com"`这段中+没有转义，可能postman对url中的参数做了反转义，+转为空格了。
> 
> 根据RFC3986规范，URL参数值中`+`是安全字符，无需转义，因此此处没问题。如果你有问题，可以在客户端上手动转义此字符。

比对了一下 postman 跟 httputil
![image](https://user-images.githubusercontent.com/24653016/160725344-fbea569a-1825-4c02-89c3-c874c8690c31.png)

![image](https://user-images.githubusercontent.com/24653016/160725373-61165794-1427-4d40-b218-45c025c0b328.png)

**Comment by amosnothing** [comment]
q请问一下，这个 url 编码为何有的可以转，+号怎么始终是空格呢 ？

![image](https://user-images.githubusercontent.com/24653016/160725940-7c355063-4641-4537-b927-affaff1583c3.png)
![image](https://user-images.githubusercontent.com/24653016/160725985-3ff79d05-b518-4a17-ad3b-2246ad6ea7da.png)

**Comment by juesuchen** [comment]
在5.7.16版本，我请求HttpUtil.get("https://xxx.com/list_cdr_all?Signature=nU%2BmcBgr7nMavxUfzEyHI6RVt9U%3D")，发现里面构造UrlBuilder的UrlQuery时，会把参数decode解释放到query这个map中，
如：Signature = nU+mcBgr7nMavxUfzEyHI6RVt9U=
然后再发送时，cn.hutool.http.HttpRequest#initConnection会调用UrlBuilder.toURL(this.urlHandler)生成请求的url，最终会调用到cn.hutool.core.net.url.UrlQuery#build(java.nio.charset.Charset)方法，此方法不会转义+号，如上面所说它是安全字符，但是不转义成%2B，+号会视为空格，那这种情况，我要如何处理？

**Comment by amosnothing** [comment]
我是先把 url 编码，再调用 `new HttpRequest(UrlBuilder.ofHttpWithoutEncode(Uri))`

**Comment by juesuchen** [comment]
> 我是先把 url 编码，再调用 `new HttpRequest(UrlBuilder.ofHttpWithoutEncode(Uri))`
改成这样是可以了，不过总感觉原来 的方式工具类处理的是有问题的，我转义传入，它确定不转义发出

new HttpRequest(UrlBuilder.ofHttpWithoutEncode(url)).form(params).execute().body();

**Comment by amosnothing** [comment]
没什么问题，加号在 URL 里面就是为了代替空格的

**Comment by looly** [comment]
@juesuchen 那个版本有这个bug，升级5.8.4就可以了。
