### ISSUE TITLE
httputil

### ISSUE THREAD

**Issue by nuo010** [looly/hutool#2229]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

post发送请求 body 对象能不能吧map自动转json
还得在套上一层才可以 JSON.toJSONString(postparam)

**Comment by looly** [comment]
这里是任意字符串，要根据你的实际需要传入对应格式的字符串。

如果你需要Map转为XML怎么办？所以这种自动转换不现实。

**Comment by nuo010** [comment]
不是老哥你没懂我的意思
这是我接收方的接口
![](http://qiniu.elel.fun/20220331151842.png)
这是我发送方的接口 我先直接穿map 对象 就可以在内部自动转换json字符串 不是要在外边在套上一层json解析
![](http://qiniu.elel.fun/20220331151945.png)

**Comment by nuo010** [comment]
![](http://qiniu.elel.fun/20220331152130.png)

**Comment by looly** [comment]
说的意思一样，这个参数格式可能是：

1. JSON
2. XML
3. 类似于a=1&b=2这种UrlEncoded

因此如果传入Map就直接转JSON不合适吧？

**Comment by nuo010** [comment]
好的吧

**Comment by nuo010** [comment]
我感觉现在都是json了吧 xml 和 a=1&b=2 这种都是老项目在用了  新项目用的很少了 都是json ....

**Comment by looly** [comment]
@nuo010 新旧与否不重要，重要的是兼容性要好。就像PostMan，你可以看下。
