### ISSUE TITLE
IoUtil.readBytes无法读取固定长度

### ISSUE THREAD

**Issue by zhaomoran** [looly/hutool#2230]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.19（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
此处的IoUtil.readBytes，在非FileInputStream情况下（例如网络流），并不会真实读取到固定的length，是否应该使用while循环读取直到固定长度或者到结尾。目前方法和InputStream.readByte是一致的。或者考虑增加readFully。

```java
/**
	 * 读取指定长度的byte数组，不关闭流
	 *
	 * @param in     {@link InputStream}，为null返回null
	 * @param length 长度，小于等于0返回空byte数组
	 * @return bytes
	 * @throws IORuntimeException IO异常
	 */
public static byte[] readBytes(InputStream in, int length) throws IORuntimeException {
		if (null == in) {
			return null;
		}
		if (length <= 0) {
			return new byte[0];
		}

		byte[] b = new byte[length];
		int readLength;
		try {
			readLength = in.read(b);
		} catch (IOException e) {
			throw new IORuntimeException(e);
		}
		if (readLength > 0 && readLength < length) {
			byte[] b2 = new byte[readLength];
			System.arraycopy(b, 0, b2, 0, readLength);
			return b2;
		} else {
			return b;
		}
	}
```

**Comment by looly** [comment]
你可以看下最新版本的源码，此处做了判定：

见：https://gitee.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/io/IoUtil.java#L474

**Comment by zhaomoran** [comment]
是的，研究了源码，在https://gitee.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/io/IoUtil.java#L474 此处是可以进行完整读取的，在下面这段里读取到固定的length无法对网络流生效，因为其是按照块来传输。
https://gitee.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/io/IoUtil.java#L506

**Comment by looly** [comment]
@zhaomoran 这个方法确实有问题。5.8.0修复，感谢！

**Comment by vxinv** [comment]
@zhaomoran 查看写的是：  Note that while some implementations of {@code InputStream} will
     * return the total number of bytes in the stream, many will not.  It is
     * never correct to use the return value of this method to allocate
     * a buffer intended to hold all data in this stream.
但是 这样写行吗，available是否真的返回文件的大小？
