### ISSUE TITLE
ListUtil部分方法命名问题

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2235]
希望新增 ListUtil.Lists.newArrayList() 与 newLinkedList() 命名的方法，
比 ListUtil.list(false) 和 ListUtil.list(true) 敲起来更快，也更符合方法语义

**Comment by looly** [comment]
这个和命名风格有关系，有人喜欢newXXX，有人喜欢createXXX，Hutool暂时这块比较混乱，看6.x可否做到统一。

现阶段，个人认为list方法比较简单。
