### ISSUE TITLE
FileTypeUtil.getType(inputStream)读取文件名后，原有流就不完整了

### ISSUE THREAD

**Issue by kannayshu** [looly/hutool#2237]
Stream只能read一次，FileTypeUtil.getType(inputStream)读取文件名后，这个文件本身就少了一部分，再用该文件流去执行操作，就有问题。
建议：
1、修复；
2、指出这个问题，免得踩坑

**Comment by looly** [comment]
5.8.0.M3会在注释中说明：

![image](https://user-images.githubusercontent.com/1432613/161376727-49a166b6-a129-4669-ac2c-dcf0b64f92f6.png)
