### ISSUE TITLE
cn.hutool.poi.excel.ExcelWriter#getDisposition返回错误

### ISSUE THREAD

**Issue by bluef1ash** [looly/hutool#2239]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新版本

### 问题描述（包括截图）

1. 复现代码

返回文件名

```
=_1649254123953.xlsx_; filename_=UTF-8''1649254123953.xlsx
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个头很奇怪……

5.8.0.M3修复此问题，感谢。

**Comment by bluef1ash** [comment]
5.8.3版本返回文件名
`=_1657616856883.xlsx_`
