### ISSUE TITLE
请求nginx 转发地址图片资源返回403

### ISSUE THREAD

**Issue by lxf-lxf** [looly/hutool#2242]
### 版本情况

JDK版本：    zulu-jdk8-302
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
hutool HttpUtil 和 httpRequest 请求获取不到图片源,okhttp可以
没报错，地址好像是重定向的，返回403 提示.
![image](https://user-images.githubusercontent.com/61101384/162350492-581691ca-f5c9-42b8-9292-941f5604b383.png)
postman 也请求返回正常
![7809DEF70A6F063BA2EB36AC34FD96DF](https://user-images.githubusercontent.com/61101384/162350503-250dbf07-a3a3-49d8-a22f-0e041bf173b4.jpg)
![image](https://user-images.githubusercontent.com/61101384/162350519-c50a4ba6-35aa-4fe5-8405-d87c1381de72.png)

**Comment by lxf-lxf** [comment]
更新最新版本 无问题

**Comment by lxf-lxf** [comment]
升到最新版本5.7.21 okhttp如果先请求，再用httpRequest请求就返回正常。

**Comment by looly** [comment]
URL链接有提供么？

**Comment by lxf-lxf** [comment]
> URL链接有提供么？

https://p26-sign.douyinpic.com/tos-cn-i-0813/199f538e06c547a3b0093079d5bad950~noop.webp?x-expires=1651946400&x-signature=kGIGAUmhwW0pJ1jXd6ajWid7yOY%3D&from=4257465056&s=PackSourceEnum_DOUYIN_REFLOW&se=false&biz_tag=aweme_images&l=20220408024617010210068018330E720C

**Comment by looly** [comment]
@lxf-lxf 我这里请求没有问题：

```java
String url = "https://p26-sign.douyinpic.com/tos-cn-i-0813/199f538e06c547a3b0093079d5bad950~noop.webp?x-expires=1651946400&x-signature=kGIGAUmhwW0pJ1jXd6ajWid7yOY%3D&from=4257465056&s=PackSourceEnum_DOUYIN_REFLOW&se=false&biz_tag=aweme_images&l=20220408024617010210068018330E720C";
final String s = HttpUtil.get(url);
Console.log(s);
```

麻烦升级到5.8.0.M2试下。

**Comment by lxf-lxf** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/61101384/162450452-b274b8c0-07ff-44c6-bdc8-6300d9f6b935.png">
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/61101384/162450574-5ffdc5ed-5558-4862-a74c-5cd7af82b40f.png">
还是403 @looly

**Comment by looly** [comment]
@lxf-lxf 你不会被屏蔽了吧？

**Comment by lxf-lxf** [comment]
> @lxf-lxf 你不会被屏蔽了吧？

没有啊
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/61101384/162451695-f3b24932-e899-4d2c-af61-6fdfbeb3dbcc.png">
