### ISSUE TITLE
HttpRequest of(String url, Charset charset) charset 为null时，仍然对url进行了编码导致错误

### ISSUE THREAD

**Issue by renlm** [looly/hutool#2243]
### 版本情况

JDK版本：    openjdk_8_231
hutool版本： 5.8.0.M2

### 问题描述（包括截图）

1. 复现代码
场景1：
```java
// 调用接口（注意：使用手动编码方式）
// url = HttpUtil.encodeParams(url, StandardCharsets.UTF_8);
// https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=+8616512884988
HttpRequest request = HttpRequest.of("https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=%2B8616512884988", null).method(Method.GET);
```
![image](https://user-images.githubusercontent.com/38641421/162363833-8d6357d7-4f17-4db5-b803-30d6938cd8b9.png)
如上图，获取华为虚拟号，接口要求手机号码必须是标准的+86格式并且要对+号编码，设置chartset为空，却再次将+号编码后的%2B又做了一次转换；
场景2：
```java
// 调用接口（注意：使用手动编码方式）
// url = HttpUtil.encodeParams(url, StandardCharsets.UTF_8);
// https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=+8616512884988
HttpRequest request = HttpRequest.of("https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=+8616512884988").method(Method.GET);
```
![image](https://user-images.githubusercontent.com/38641421/162364258-8e057507-db7d-4cc7-bca7-7a1c47ddad43.png)
直接使用参数未编码的url，+号未编码
场景3：
```java
// 调用接口（注意：使用手动编码方式）
// url = HttpUtil.encodeParams(url, StandardCharsets.UTF_8);
// https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=+8616512884988
HttpRequest request = HttpRequest.of("https://rtcpns.cn-north-1.myhuaweicloud.com:443/rest/provision/caas/privatenumber/v1.0?privateNum=+8616512884988", CharsetUtil.UTF_8).method(Method.GET);
```
![image](https://user-images.githubusercontent.com/38641421/162364555-deb22f2e-ee37-419c-a439-8a93b2c68eab.png)
设置charset = CharsetUtil.UTF_8，请求链接仍然未处理+号

### 是我使用的方式不对么？如果才能让请求参数privateNum=%2B8616512884988正确的传递过去？

5.7.22是没问题的，HttpUtil.encodeParams(url, StandardCharsets.UTF_8); 对url进行编码可以转换+号
升级到5.8.0.M1，HttpUtil.encodeParams(url, StandardCharsets.UTF_8); 无法对url参数中的+号编码，我改成单独对privateNum参数使用 URLEncoder.encode(privateNum, StandardCharsets.UTF_8.displayName()) 转换编码
升级到5.8.0.M2，使用各种方式均不行，如上三个场景。

**Comment by looly** [comment]
啊，这个编码真是让人头疼，稍后我好好看看。

**Comment by omegod** [comment]
看起来是 debug 模式下调用了某个初始化方法导致了 UrlBuilder 中的 charset 被赋值。不在 debug 模式下如：
![image](https://user-images.githubusercontent.com/22209885/162402444-6b5505bc-56d1-4b98-9324-ba794c769bb4.png)
使用 debug 预览后
![image](https://user-images.githubusercontent.com/22209885/162402542-f27cf60f-dae9-47f6-bee9-dad3d7bdae3e.png)
![image](https://user-images.githubusercontent.com/22209885/162402583-f059f7c5-1e5f-434f-8298-0f76bd1ee9b9.png)

**Comment by looly** [comment]
这个事情我解释下。

根据RFC3986规范，+属于安全字符，可以出现在URL中，因此场景2和场景3未编码是没问题的。

你提供的URL特殊要求在，服务端强制要求+必须编码为`%2B`，这就导致了场景1中被重复编码了。

那Hutool必须考虑几种情况：

1. 用户提供的URL是编码过的，此时不应该重复编码
2. 用户提供的URL是非编码过的，比如有汉字，此时需要按照规范编码
3. 用户提供的URL混杂了编码后的内容和未编码的内容，比如`https://hutool.cn/req?a=你好&b=%2B是`，这种最为麻烦，需要做到：已经编码的保持现状，未编码的进行编码。

第三种情况带来个问题就是`%`的处理，用户传入一个`%`，我无法区分这个是编码后的字符还是未编码的字符，就引起了场景1中的问题，Hutool把这个字符当作未编码字符又编码了一遍。

5.8.0.M3会修改此处的逻辑：

用户传入的带有`%`的字符串统一按照已经编码后处理，除非用户在of的时候指定了编码，做了解码。

感谢如此详细的描述问题，后续有问题请随时反馈。
