### ISSUE TITLE
有没有判断一个文件是否是图片的工具类啊？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2250]

**Comment by joey-happy** [comment]
FileTypeUtil这个工具类能获取到文件类型 我想要的是一个方法 类似isImage(File file) 或者 isImage(InputStream in) 来判断是否是图片 能提供一下这个方法吗？

**Comment by looly** [comment]
这个没有，而且图片类型众多，无法提供一个通用的方法。

**Comment by joey-happy** [comment]
https://blog.csdn.net/dgqvhtlwq472235338/article/details/101415101

spring boot ImageIO这个类好像可以
//检查是否是图片
BufferedImage bi = ImageIO.read(file.getInputStream());
if(bi == null){ 
    return JsonResVo.buildErrorResult(ErrorEnum.ERROR_DEFAULT.getErrorCode(), "上传的文件不是图片");    
}

**Comment by looly** [comment]
那你还不如直接读呢。

**Comment by joey-happy** [comment]
那我怎么判断呢？ 格式太多了
