### ISSUE TITLE
ByteUtil.ByteUtil 漏了一个if判断

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#2252]
ByteUtil.ByteUtil 漏了对Byte的判断，由于我传的Number 4种整数类型都可能，所以遇到Byte的时候就出问题了

下面的截图是最新版本的代码

我的版本是 5.7.22

![image](https://user-images.githubusercontent.com/34471928/163125256-7d366326-63a7-4057-a8ce-9521665b6d0a.png)

**Comment by looly** [comment]
5.8.0.M3解决，感谢。
