### ISSUE TITLE
有没有封装好的随机生成 4 位纯数字验证码的方法

### ISSUE THREAD

**Issue by samho2008** [looly/hutool#2254]
目前可以使用 `RandomUtil.randomInt(1000,10000)` 来获取 4 位纯数字验证码，有没有进一步封装好的？这个需求在验证码上挺常见的。

![image](https://user-images.githubusercontent.com/92196261/163272410-9c5511a2-ae7c-4f5e-83d0-6102754cc09a.png)

**Comment by looly** [comment]
```java
RandomUtil.randomString("0123456789", 4);
```
