### ISSUE TITLE
StrUtil工具类，firstNon系列方法不是静态方法

### ISSUE THREAD

**Issue by 1511pzz** [looly/hutool#2257]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0.M3

### 问题描述（包括截图）

1.  StrUtil工具类，firstNon系列方法不是静态方法
![微信截图_20220416170934](https://user-images.githubusercontent.com/30923775/163669226-7440b314-1a6f-4edb-be59-dec59bd3def4.png)

**Comment by looly** [comment]
啊，忘记加了。

5.8.0.M4修复，感谢！
