### ISSUE TITLE
HttpRequest 的报文日志

### ISSUE THREAD

**Issue by alice9nine** [looly/hutool#2258]
##### 能不能增加报文打印    用习惯了httpClient的工具请求的报文很详细例如
- 14:51:20.478 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /mpay/buy_goods_m HTTP/1.1
14:51:20.478 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
14:51:20.479 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
14:51:20.481 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> GET /mpay/buy_goods_m HTTP/1.1
14:51:20.481 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: ysdktest.qq.com
14:51:20.481 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
14:51:20.481 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.11 (Java/1.8.0_181)
14:51:20.481 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
14:51:20.481 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "GET /mpay/buy_goods_m HTTP/1.1[\r][\n]"
14:51:20.481 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: ysdktest.qq.com[\r][\n]"
14:51:20.481 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
14:51:20.481 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.11 (Java/1.8.0_181)[\r][\n]"
14:51:20.482 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
14:51:20.482 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Mon, 18 Apr 2022 06:51:20 GMT[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 55[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
14:51:20.548 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"msg":"client request's app is not existed","ret":-2}[\n]"
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Mon, 18 Apr 2022 06:51:20 GMT
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 55
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
14:51:20.553 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Content-Type-Options: nosniff
14:51:20.559 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely

**Comment by looly** [comment]
构建HttpRequest之后可以直接调用toString，就是报文内容。
