### ISSUE TITLE
AioServer#setIoAction#doAction函数里面的ByteBuffer数据太长被截断

### ISSUE THREAD

**Issue by mdddj** [looly/hutool#2259]
作者你好

我在使用socket来和客户端传输大量的字符串数据(长度是未知的)
如果字符串太长会被截断,请问有什么办法可以解决这个问题吗?

<img width="781" alt="image" src="https://user-images.githubusercontent.com/29020213/163950076-92bebf42-62dc-4930-864b-37882193cc74.png">

数据被截断,导致我的json转model解析失败
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/29020213/163950177-3c15daa3-0751-480b-b523-875c3e65f8b0.png">

**Comment by looly** [comment]
这是粘包了，自行通过头长度等方式处理粘包问题把。
