### ISSUE TITLE
文件类型判断-FileTypeUtil不能识别war包

### ISSUE THREAD

**Issue by jaredhu** [looly/hutool#226]
文件类型判断-FileTypeUtil不能识别war包，返回的结果是zip包

**Comment by tall-nuts** [comment]
FileTypeUtil不应该以扩展名来判断文件类型，应该以MIME来去做大部分的常用文件处理。

**Comment by looly** [comment]
Hutool的类型判断是根据Magic Header来判断的，war本身是zip包，因此识别为zip。无法更进一步判断。
