### ISSUE TITLE
ObjectUtil.defaultIfBlank("abc", null);调用这个方法提示 有两个方法相匹配

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2260]
![image](https://user-images.githubusercontent.com/16012082/163951783-a40007a4-8e6c-43f4-95f0-d02d9456397b.png)

**Comment by joey-happy** [comment]
导致没有办法使用

**Comment by joey-happy** [comment]
StrUtil.blankToDefault("abc", null); 这个方法 如果是空串 我就让它变成null 但是看你的源码 第二个参数不能传null 满足不了我这个需求了 有啥好办法吗？

**Comment by anaer** [comment]
StrUtil.trimToNull?

**Comment by t-aest** [comment]
那个版本啊

**Comment by looly** [comment]
@anaer 正解。

**Comment by looly** [comment]
3.x版本就有了，你可以：

![image](https://user-images.githubusercontent.com/1432613/163991217-bdaa0520-545a-48b0-9390-30329c9c2798.png)
