### ISSUE TITLE
Springboot部署后FileUtil.getAbsolutePath打印的是Jar中的BOOT-INF路径

### ISSUE THREAD

**Issue by MarcusMjk** [looly/hutool#2261]
### 版本情况

JDK版本：    jdk-8u271-windows-x64
hutool版本： 5.7.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
项目为Springboot项目（2.6.6），在IDEA中正常运行，能够打印出target中该文件的路径，但是在Springboot打成Jar包后，发现打印出来的路径带有“E:\\xxx-0.0.1-SNAPSHOT.jar!\BOOT-INF\classes!\conf\text.txt”，使得我外置的conf\text.txt无效

1. 复现代码

```java
System.out.println("===========================================");
System.out.println("下面是text.txt的绝对路径");
System.out.println(FileUtil.getAbsolutePath("conf/text.txt"));
System.out.println("===========================================");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
[text.txt](https://github.com/dromara/hutool/files/8518044/text.txt)

运行截图：
IDEA中运行： 
![image](https://user-images.githubusercontent.com/21231382/164143642-f791586f-0c9e-43cd-b861-7c0bf5584ff8.png)

打成部署包后运行的截图：
![image](https://user-images.githubusercontent.com/21231382/164144732-e21de485-6432-44ed-84e7-94bc85534d10.png)

想问下这种方式能识别出来并自动改成启动时指定的classPath的路径吗？

目前我的处理：将`-classpath .` 改为 `-Xbootclasspath/a:./` 解决了目前的需求，是否只有这种方式才能解决springboot打包后的绝对路径的问题呢？

**Comment by looly** [comment]
这个获取绝对路径是依赖于classpath的获取，如果有多个相同的相对路径存在，获取顺序应该是取决于你的-cp参数后跟着的参数。

这个暂时没有好的办法，欢迎提供好的解决方案。

**Comment by modyuan** [comment]
大坑……我用FileUtil.writeUtf8String("123","out.txt")写输出文件，期待是在当前工作目录输出 ，结果却是在工作目录下leak-migrate-1.0.jar!\BOOT-INF\classes!目录下输出。😓

**Comment by looly** [comment]
@modyuan 在web项目中，工作目录是不可控的，因此默认Hutool的相对路径都是相对classpath。

**Comment by modyuan** [comment]
> [@modyuan](https://github.com/modyuan) 在web项目中，工作目录是不可控的，因此默认Hutool的相对路径都是相对classpath。

1. 你不能假定我的使用场景一定是web，也可能是我在做工具类
2. FileUtil.writeUtf8String方法注释上没有提到会根据classpath，我会认为他和Java标准库的FileOutputStream行为类似，应该是根据工作目录才对。
