### ISSUE TITLE
有没有字符串+数字这种排序规则 举例：foo foo1 room11 room100 room2 期望排序后:foo foo1 room2 room11 room100

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2263]
原文地址：https://cloud.tencent.com/developer/ask/194669
![image](https://user-images.githubusercontent.com/16012082/164198923-b0098aff-0ae0-4eac-8cd1-f49f5725e67e.png)

**Comment by joey-happy** [comment]
类似于这种解决方案：https://developer.aliyun.com/article/444597

**Comment by looly** [comment]
没有，考虑自行封装Comparator
