### ISSUE TITLE
替换所有正则匹配的文本

### ISSUE THREAD

**Issue by guodong8988** [looly/hutool#2264]
cn.hutool.core.util.ReUtil#replaceAll(java.lang.CharSequence, java.util.regex.Pattern, cn.hutool.core.lang.func.Func1<java.util.regex.Matcher,java.lang.String>) 
有示例吗？

**Comment by guodong8988** [comment]
替换所有正则匹配的文本

**Comment by looly** [comment]
见：http://hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E6%AD%A3%E5%88%99%E5%B7%A5%E5%85%B7-ReUtil?id=reutilreplaceall
