### ISSUE TITLE
postman中的raw类型数据如何创建

### ISSUE THREAD

**Issue by savaza** [looly/hutool#2265]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.1

### 问题描述（包括截图）
请问在Postman中的raw类型JSON数据在HttpRequest中如何创建？
![image](https://user-images.githubusercontent.com/36786253/164241094-e44daaf3-ceaf-416d-a5e3-f9267ebed894.png)

**Comment by looly** [comment]
使用body方法即可，见：http://hutool.cn/docs/#/http/Http%E8%AF%B7%E6%B1%82-HttpRequest?id=restful%e8%af%b7%e6%b1%82
