### ISSUE TITLE
ExcelFileUtil .isXlsx 判断不准确

### ISSUE THREAD

**Issue by funyule** [looly/hutool#2266]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.3

### 问题描述（包括截图）
使用junit单元测试
```java
File file = new File("IamDocx.docx");
Assert.assertTure(ExcelFileUtil.isXlsx(new FileInputStream(file));
```
测试通过

注：docx文档使用wps创作

补充一个实际场景截图：
![image](https://user-images.githubusercontent.com/12372048/164352609-0812eb3d-6b61-45df-8381-f04244d2e67e.png)

**Comment by looly** [comment]
这个方法只是使用magic header辅助判断，因为xlsx本质上是zip包，因此无法正确判断，考虑借助扩展名辅助判断。
