### ISSUE TITLE
空检查属性获取-Opt 文档建议

### ISSUE THREAD

**Issue by tuess** [looly/hutool#2267]
一个小小的文档建议
文档链接：https://hutool.cn/docs/#/core/JavaBean/%E7%A9%BA%E6%A3%80%E6%9F%A5%E5%B1%9E%E6%80%A7%E8%8E%B7%E5%8F%96-Opt

此处文档中的第一段代码中改成了```Opt```，但是后面的代码都还是用的```OptionalBean```，它已经在5.7.12版本弃用了，所以建议文档也更正一下，谢谢

**Comment by looly** [comment]
OK，感谢，这个文档稍后修复。
