### ISSUE TITLE
[bug]hutool版本更新之后，JSONUtil.toBean()方法无法 ignoreError了

### ISSUE THREAD

**Issue by xkcoding** [looly/hutool#227]
从4.1.19更新到4.3.1 JSONUtil.toBean方法不能忽略错误了。

**Comment by looly** [comment]
新版中toBean默认规则改为不忽略错误。如果想忽略错误，请使用：

```
JSONConverter.jsonConvert
```

为了方便，4.3.2中的JSONObject对象会添加toBean重载，支持可选是否忽略错误。

感谢。
