### ISSUE TITLE
希望增加win11操作系统的识别

### ISSUE THREAD

**Issue by lizhen789** [looly/hutool#2270]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/35031472/164705989-0361f5ef-9d8e-4681-909d-c8599e29ed31.png)

希望增加win11操作系统识别

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I546PY
