### ISSUE TITLE
FileUtil.copyContent不能将jar里的文件复制到文件系统指定目录。

### ISSUE THREAD

**Issue by mostcool** [looly/hutool#2273]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
FileUtil.copyContent(FileUtil.file("./templates/frontend/files/"), FileUtil.file(outputDir), true);
```

2. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Jar、Zip中的文件无法使用`FileUtil`完成，可以使用`ZipUtil`完成操作。

**Comment by mostcool** [comment]
> ZipUtil

先解压，再操作？

**Comment by mostcool** [comment]
> Jar、Zip中的文件无法使用`FileUtil`完成，可以使用`ZipUtil`完成操作。

先解压，再复制？

**Comment by looly** [comment]
直接解压到目标目录即可。
