### ISSUE TITLE
FileTypeUtil.getType识别WPS-xlsx为jar格式[BUG?]

### ISSUE THREAD

**Issue by Leo-GH** [looly/hutool#2275]
### 版本情况

JDK版本：    oracle jdk_8_201
hutool版本： 5.7.5 or 5.8.0.M2 都有尝试
WPS Office版本：3.9.4 for mac

### 问题描述（包括截图）
- 上传WPS创建的xlsx文件，或者是WPS编辑并保存过的xlsx文件，使用FileTypeUtil.getType(file.getInputStream())都会识别为jar文件
- 使用微软Office Excel创建/编辑的 xlsx文件，上传被正确识别为zip（正确）

1. 复现代码

```java
String type = FileTypeUtil.getType(file.getInputStream());
```

2. 堆栈信息

读取到的前几位字节：

WPS：504B03040A0000000000874EE2400000000000000000000000000900

Office：504B030414000600080000002100A453C5CF4E010000080400001300

按照Map内的顺序，会先比对jar1，然后jar2，然后zip
jar1: FILE_TYPE_MAP.put("504B03040a0000000000", "jar"); 
jar2: FILE_TYPE_MAP.put("504B0304140008000800", "jar");
zip: FILE_TYPE_MAP.put("504B0304", "zip");

经过测试，WPS的前几位字节，会优先被jar1（504B03040a0000000000）匹配到，所以被识别为jar

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/issues/I4MH9O
