### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#2277]
### 版本情况

JDK版本：    openjdk_8_291
hutool版本： 5.8.0.M3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

调用https的接口，在浏览器能访问，用代码就报错了
![image](https://user-images.githubusercontent.com/14087655/165042432-1da344a3-4715-45b4-959c-8ee2378598d3.png)

我看了下官网，里面有这个错误的处理方式，但是我也试过了，还是不行，我的jdk是291的，想问下有什么其它的解决方案吗？
![image](https://user-images.githubusercontent.com/14087655/165042749-82a1dc69-1dd3-4a66-89f8-4e625363dfdd.png)

1. 复现代码

HttpUtil.get("https://xxxxxxxx");

**Comment by looly** [comment]
尝试添加全局的属性：

```java
System.setProperty("https.protocols", "TLSv1.2,TLSv1.1,SSLv3");
```

如果不行麻烦提供下你的请求链接我这边测试。

到时再打开issue。

**Comment by reixuemin** [comment]
> 尝试添加全局的属性：
> 
> ```java
> System.setProperty("https.protocols", "TLSv1.2,TLSv1.1,SSLv3");
> ```
> 
> 如果不行麻烦提供下你的请求链接我这边测试。
> 
> 到时再打开issue。

刚才发现了个现象，目前我调用的是我通过nginx转发的，比如

地址A（nginx->地址B）
地址B（实际地址）
目前用HttpUtil.get(地址B）是没问题的，HttpUtil.get(地址A)就报错，但是浏览器直接访问地址A没问题

这种情况是工具问题还是nginx的设置问题？

**Comment by looly** [comment]
这个我这边也不好说……

如果找到原因欢迎此issue下分享。

**Comment by xiaoqiqiya** [comment]
我也出现这种问题了

**Comment by jq94666** [comment]
java17遇到这种问题了，这里是连接：https://www.wuhu.gov.cn/ @looly
