### ISSUE TITLE
大佬, 能加一个获取网络上传和下载速度的工具类吗?

### ISSUE THREAD

**Issue by TOP-LH** [looly/hutool#2278]
提个意见
大佬, 能加一个获取网络上传和下载速度的工具类吗?

**Comment by looly** [comment]
这个没法加吧？你要获取系统信息？

考虑Oshi库看是否可以实时获取网卡信息。

**Comment by TOP-LH** [comment]
> 这个没法加吧？你要获取系统信息？
> 
> 考虑Oshi库看是否可以实时获取网卡信息。

类似于这种大佬, 我认为您可以优化一下他的代码
https://www.cnblogs.com/myfrank/p/15618373.html

**Comment by looly** [comment]
@lihao0324 这个属于调用系统命令吧，系统兼容性很差，容易出错，风险也高（很容易被注入）。不考虑。

**Comment by TOP-LH** [comment]
> @lihao0324 这个属于调用系统命令吧，系统兼容性很差，容易出错，风险也高（很容易被注入）。不考虑。

好的, 有大佬这句话我这个需求就可以不接了, 我也感觉这个需求怪怪的
