### ISSUE TITLE
AnnotationUtil.getAnnotationValue为何getMethodOfObj是用的annotationEle而不是annotationType

### ISSUE THREAD

**Issue by dreamingo88** [looly/hutool#228]
不是特别理解这个地方的做法，到底是想获取什么？

比如我一个注解@A(x="",y="")，我想获取的是y。
如果是想获取注解中的属性的值，应该用annotationType而不是annotationEle吧？

**Comment by looly** [comment]
注释很清楚：

```
{@link AnnotatedElement}，可以是Class、Method、Field、Constructor、ReflectPermission
```

也就说说是获取类、方法、字段等上面的注解，annotationType指注解类型，是你获取的注解是什么类型。

**Comment by dreamingo88** [comment]
> 注释很清楚：
> 
> ```
> {@link AnnotatedElement}，可以是Class、Method、Field、Constructor、ReflectPermission
> ```
> 也就说说是获取类、方法、字段等上面的注解，annotationType指注解类型，是你获取的注解是什么类型。

这个我自然知道。我说的是AnnotationUtil的96行和100行，
final Method method = ReflectUtil.getMethodOfObj(annotationEle, propertyName);
return ReflectUtil.invoke(annotationEle, method);
这两个地方为什么用annotationEle？
比如我一个注解@A(x="",y="")，我想获取属性y。
调用这个方法得到的是Null。

**Comment by looly** [comment]
4.4.5修复此问题。感谢。
