### ISSUE TITLE
有没有直接把http请求的结果直接转成java对象的方法吗？例如：httpUtil.xxxx.execute().body(User.class)

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2280]
原请求：String result = HttpUtil.createPost("api.uhaozu.com/goods/description/1120448506")
				.charset(CharsetUtil.UTF_8)
				.execute().body();
有直接把返回值json直接转成java对象的方法吗？
例如：		String result = HttpUtil.createPost("api.uhaozu.com/goods/description/1120448506")
				.charset(CharsetUtil.UTF_8)
				.execute().body(User.class);

**Comment by looly** [comment]
body方法返回的是字符串，如果你确定是JSON字符串，可以使用`JSONUtil.toBean`完成转换。
