### ISSUE TITLE
集合工具类比较差集问题

### ISSUE THREAD

**Issue by hogger0** [looly/hutool#2282]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

        List<Integer> db = List.of(2001,2011,1000);

        List<Integer> page = List.of(2001,2011,2031,2041);

        System.out.println("比较差集" + CollUtil.subtract(db, page));

执行报错，不能这么玩么？？

![image](https://user-images.githubusercontent.com/6472032/165252036-3e249986-159d-4255-a23c-b58fe026a23a.png)

**Comment by seedscoder** [comment]
Arrays.asList returns a mutable list while the list returned by List.of is [immutable](https://docs.oracle.com/javase/9/docs/api/java/util/List.html#immutable):

**Comment by CherryRum** [comment]
你建立的list其实只是array下面的一个内部类，不是正常的List

**Comment by meredith233** [comment]
List.of() 可替换为 CollUtil.newArrayList() 来解决这个问题
