### ISSUE TITLE
Assert无法触发idea静态语句非空检查

### ISSUE THREAD

**Issue by iDayMonthYear** [looly/hutool#2287]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）
能不能提供个类似 spring 断言的简单判断方法

### 问题描述（包括截图）
<img width="493" alt="image" src="https://user-images.githubusercontent.com/4516585/165460396-d7dfefd2-fe7f-42cb-bc81-2c6f4c38f146.png">

1. 复现代码

```java
spirng 使用的是简单语句做判断，所以 idea 能静态检查

public static void isTrue(boolean expression, String message) {
  if (!expression) {
    throw new IllegalArgumentException(message);
  }
}

hutool assert 使用的是一个函数调用所以无法触发idea静态语句检查了。
public static void isTrue(boolean expression, String errorMsgTemplate, Object... params) throws IllegalArgumentException {
    isTrue(expression, () -> new IllegalArgumentException(StrUtil.format(errorMsgTemplate, params)));
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
代码复用导致的，IDEA貌似只检测一层。

**Comment by looly** [comment]
见：https://github.com/dromara/hutool/issues/2028
