### ISSUE TITLE
数字工具bug

### ISSUE THREAD

**Issue by ronaldoWang** [looly/hutool#229]
NumberUtil.isInteger()
这个方法，传入浮点数，返回true
public static boolean isInteger(String s) {
        try {
            parseInt(s);
            return true;
        } catch (NumberFormatException var2) {
            return false;
        }
    }
public static int parseInt(String number) throws NumberFormatException {
        if (StrUtil.isBlank(number)) {
            return 0;
        } else {
            number = StrUtil.subBefore(number, '.', false);
            if (StrUtil.isEmpty(number)) {
                return 0;
            } else if (StrUtil.startWithIgnoreCase(number, "0x")) {
                return Integer.parseInt(number.substring(2), 16);
            } else {
                return number.startsWith("0") && number.length() > 1 ? Integer.parseInt(number.substring(1), 8) : Integer.parseInt(number);
            }
        }
    }

**Comment by looly** [comment]
感谢。4.3.2修复此问题。
