### ISSUE TITLE
HttpUtil封装的方法没有调用close方法

### ISSUE THREAD

**Issue by 411937647** [looly/hutool#2301]
### 版本情况

JDK版本：    JDK 1.8.0_131
hutool版本： 5.7.9

### 问题描述（包括截图）

通常我是这样调用的（直接使用HttpUtil的封装方法）

![图片](https://user-images.githubusercontent.com/21364503/167101991-6a76c127-5918-47ce-9956-ffd8058f6f3e.png)
![图片](https://user-images.githubusercontent.com/21364503/167102617-97bc7dc7-3ed7-4524-9007-1213b9f82ffb.png)

但最近IDEA扫描爆出了这个警告，我才发现HttpResponse继承了Closeable, 并且方法体内有释放IO的内容，但HttpUtil封装的方法没有调用close方法，是否能够修复一下

**Comment by looly** [comment]
这个没有问题。

调用execute方法的时候，会自动读取响应内容，然后关闭流。

这里HttpResponse实现Closeable接口的原因是，有个executeAsync方法，是不读取响应流的，而是要持有流，等用户需要时读取。

**Comment by Delete94** [comment]
关闭流的代码在哪里，可以截个图吗，没找到

**Comment by looly** [comment]
@Delete94 

![image](https://github.com/dromara/hutool/assets/1432613/68f07261-47de-4bae-b968-827b121282a2)


见：HttpResponse.forceSync();
