### ISSUE TITLE
使用MailUtil发送邮件时报错com.sun.mail.handlers.text_html cannot be cast to javax.activation.DataContentHandler

### ISSUE THREAD

**Issue by NiuXiaoGuang** [looly/hutool#2302]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.0

### 问题描述（包括截图）
使用MailUtil发送邮件时报错com.sun.mail.handlers.text_html cannot be cast to javax.activation.DataContentHandler
详情见下图
<img width="958" alt="截屏2022-05-07 02 49 06" src="https://user-images.githubusercontent.com/30843465/167199827-fda6c3e6-a4df-4b31-acf5-6cdb858fa30d.png">
<img width="403" alt="截屏2022-05-07 02 49 47" src="https://user-images.githubusercontent.com/30843465/167199907-a3420a8b-1ceb-44b6-8ea9-067872dd9637.png">
<img width="966" alt="截屏2022-05-07 02 50 22" src="https://user-images.githubusercontent.com/30843465/167200095-e6b59cde-d2c2-46e5-b126-3a2bacf57abb.png">

<img width="440" alt="截屏2022-05-07 02 52 01" src="https://user-images.githubusercontent.com/30843465/167200190-ce8fc1c2-96bb-4271-b7fe-b6915fcba640.png">

1. 复现代码

```java
 private void test() throws GeneralSecurityException {
        MailAccount account = new MailAccount();
        account.setHost("smtp.aliyun.com");
        account.setPort(465);
        account.setAuth(true);
        MailSSLSocketFactory sf = new MailSSLSocketFactory();
        sf.setTrustAllHosts(true);
        account.setCustomProperty("mail.smtp.ssl.socketFactory",sf);
        account.setFrom("****@aliyun.com");
        account.setUser("*****@aliyun.com");
        account.setPass("****");

        MailUtil.send(account, CollUtil.newArrayList("*****@qq.com"), "测试",
                "邮件来自Hutool测试", true);
    }
```

**Comment by looly** [comment]
考虑是不是有包冲突问题。

如果无法排除问题，麻烦加我QQ，私聊发下我demo项目，然后再打开此issue。
