### ISSUE TITLE
cn.hutool.core.bean.BeanUtil#beanToMap(java.lang.Object, java.lang.String...)属性参数properties设置null报错

### ISSUE THREAD

**Issue by houcong0901** [looly/hutool#2303]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
cn.hutool.core.bean.BeanUtil#beanToMap(java.lang.Object, java.lang.String...)

2、场景1:
Map<String, Object> map = BeanUtil.beanToMap(stu, null);
报错（java.lang.NullPointerException）

3、场景2:
Map<String, Object> map = BeanUtil.beanToMap(stu, "");
按照注解说明，null或空表示拷贝所有值，此方法并没有实现

**Comment by looly** [comment]
失误了。

5.8.1修复此问题，感谢！
