### ISSUE TITLE
StrUtil缺少与方法endWithAnyIgnoreCase对称的方法startWithAnyIgnoreCase

### ISSUE THREAD

**Issue by jiasxin** [looly/hutool#2312]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/82010424/167407950-3a064567-2948-4c1c-aacb-0ba7378a2c02.png)

1. 复现代码

```java
//StrUtil缺少与方法endWithAnyIgnoreCase对称的方法startWithAnyIgnoreCase
//
if (StrUtil.startWithAnyIgnoreCase(str, "Normal.")) { 
        return false;
}
```

**Comment by looly** [comment]
5.8.1增加，感谢。
