### ISSUE TITLE
MetaUtil.getTableMeta 解析表结构字段长度，int类型长度为什么会少1

### ISSUE THREAD

**Issue by mengsm** [looly/hutool#2315]
MetaUtil.getTableMeta 解析表结构字段长度，int类型长度为什么会少1
比如是20，查询出来是19

**Comment by looly** [comment]
直接调用的这个：
![image](https://user-images.githubusercontent.com/1432613/167603441-fef3c505-2886-456e-bec9-dd454b9459de.png)


麻烦检查下是否是驱动的bug？

**Comment by looly** [comment]
如果无法找到原因，麻烦提供下数据库类型和驱动版本。
