### ISSUE TITLE
QrCodeUtil 二维码边距不能为 0

### ISSUE THREAD

**Issue by sunbeams001** [looly/hutool#2316]
考虑增加自定义边距的配置吗？
目前使用 EncodeHintType.MARGIN 的边距配置不能真正实现 0 边距，应该还是有很多人需要的

大概流程是：
1. 生成 BitMatrix 后进行裁剪，只取包含有效码点的部分
2. 然后在四周加入自定义padding
3. 最后缩放整体图像使得大小匹配宽高

如果需要也可以提供 PR

**Comment by looly** [comment]
你升级zxing到3.5.0，可以传入margin为0。

**Comment by sunbeams001** [comment]
感谢回复，zxing 3.5.0 确实有效
但是还不是准确的 0，有固定的一小段白边，应该是为了扫码识别效果

看个人需要吧，要求严格大概还是要自己裁一下

**Comment by looly** [comment]
@sunbeams001 嗯，这块还是由使用者自行完成吧。
