### ISSUE TITLE
HttpRequest 请求几十次接口后报错连接超时，但是在被请求端通过POSTMAN测试并无此问题

### ISSUE THREAD

**Issue by Jazts** [looly/hutool#2317]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.2

### 问题描述（包括截图）
HttpRequest 请求几十次接口后报错连接超时，但是在被请求端通过POSTMAN测试并无此问题
![image](https://user-images.githubusercontent.com/53136628/167576088-805b7f29-cb8a-4692-b11f-3572276a35a1.png)
![image](https://user-images.githubusercontent.com/53136628/167576129-1333d76b-542a-4ff6-bd50-2be909029529.png)

1. 复现代码

```java
HttpRequest.post(url).timeout(3000).body(JSONUtil.toJsonStr(params), "application/json").execute();
```

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
无
比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你的timeout设置太短了吧？这个超时相当于只有3秒。
