### ISSUE TITLE
请问一下HttpRequest使用executeAsync还是会同步等待。

### ISSUE THREAD

**Issue by 418545106** [looly/hutool#2319]
### 版本情况

JDK版本：    corretto-11(11.0.11)
hutool版本： 5.8.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
```
HttpRequest.post("http://192.168.2.88:5050").body(JSONObject.toJSONString(hardMessage)).executeAsync();
```
使用HttpRequest的post异步调用后，另一个应用打了断点后，本应用也无法继续执行下去

**Comment by looly** [comment]
这个异步的意思是不等待响应直接返回。请求时还需等待。
