### ISSUE TITLE
MapUtil的of方法，在传入2个Pair的时候没有调用到public static <K, V> Map<K, V> of(Pair<K, V>... pairs)方法

### ISSUE THREAD

**Issue by Z-feiyao** [looly/hutool#2322]
### 版本情况

JDK版本：    openjdk_8_332
hutool版本： 5.8.0（请确保最新尝试是否还有问题）

### MapUtil的of方法，在传入2个Pair的时候没有调用到public static <K, V> Map<K, V> of(Pair<K, V>... pairs)方法
![image](https://user-images.githubusercontent.com/78218958/167865735-ffb58428-bab5-4286-9d99-1f2247a38d56.png)

1. 复现代码
```java
    @Test
    public void test(){
        log.info("一个 Pair 正常:\t\n" + MapUtil.of(Pair.of("first", 1)));

        log.info("两个 Pair 无法正常解析:\t\n" + MapUtil.of(Pair.of("first", 1), Pair.of("second", 1)));

        log.info("三个 Pair 正常:\t\n" + MapUtil.of(Pair.of("first", 1), Pair.of("second", 1), Pair.of("three", 3)));
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
从5.8.0开始，为了解决这种歧义，增加了`ofEntries`，不再支持Pair，你传入`Map.Entry`对象即可。

可以通过MapUtil.entry方法创建。

```java
Map<String, Integer> map = MapUtil.ofEntries(
    MapUtil.entry("a", 1), 
    MapUtil.entry("b", 2)
);
```
