### ISSUE TITLE
IoUtil#readBytes(InputStream in, int length) 方法导致后续上传文件损坏

### ISSUE THREAD

**Issue by looooooow** [looly/hutool#2326]
### 版本情况

JDK版本：    oracle jdk_8_201
hutool版本： 5.7.17

### 问题描述（包括截图）
在文件上传时，调用 FileTypeUtil.getType方法来获取文件类型，如果传入的是InputStream,该方法内部会调用IoUtil#readBytes(InputStream in, int length)方法读取前28个字节，导致后续使用InputStream流上传文件会造成文件损坏。
1. 复现代码

```java
MultipartFile file....
InputStream in = file.getInputStream();
String fileType = FileTypeUtil.getType();
// check file type 
.....

// upload 
....
 PutObjectArgs args =
          PutObjectArgs.builder().object(randomFilename).bucket(config.getBucket()).stream(
                  in, in.available(), -1)
              .contentType(contentType)
              .build();
MinioClient client = this.getClient().putObjects(args);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
对的，所以此处应该使用`BufferedInputStream`，先mark一下，获取后调用reset即可。
