### ISSUE TITLE
NumberUtil工具类问题

### ISSUE THREAD

**Issue by yuzixuan0722** [looly/hutool#2328]
NumberUtil工具的isNumber()和parseNumber()两个方法对number的格式是不是应该保持一致，0xffff的十六进制数对于isNumber方法处理后的结果是true，但是parseNumber方法转化成0了。

```java
System.out.println(NumberUtil.isNumber("0x00000001"));
System.out.println(NumberUtil.parseNumber("0xffff"));
```

结果是

```
true
0
```

**Comment by looly** [comment]
5.8.1增加补充支持，你可以暂时使用`NumberUtil.parseLong`完成。
