### ISSUE TITLE
使用httputil类调用第三方api时，如果第三方的编码多了分号，就会报编码异常

### ISSUE THREAD

**Issue by wantosleep** [looly/hutool#233]
[使用httputil类调用第三方api时，如果第三方的编码多了分号，就会报编码异常
![111](https://user-images.githubusercontent.com/18753715/50534946-0db18280-0b7f-11e9-9e0b-93c85531270b.jpg)
![222](https://user-images.githubusercontent.com/18753715/50534947-0f7b4600-0b7f-11e9-910b-d599d4f590fd.jpg)

**Comment by looly** [comment]
新版修复了此问题，请升级到4.3.2
