### ISSUE TITLE
UserAgentUtil 无法识别 部分ipod touch ua的OS信息

### ISSUE THREAD

**Issue by wolfoot** [looly/hutool#2330]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0

### 问题描述（包括截图）

UserAgentUtil 无法识别 此ua的OS信息:
Mozilla/5.0 (iPod touch; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by looly** [comment]
啊，这是多老的UA啊，ipod可以上网么？这个设备不考虑了。

**Comment by wolfoot** [comment]
Ipod touch 7 2019年出来的产品，这个不老吧，还有ipod不能上网???

**Comment by wolfoot** [comment]
> 啊，这是多老的UA啊，ipod可以上网么？这个设备不考虑了。

Ipod touch 7 2019年出来的产品，这个不老吧，还有ipod不能上网???

**Comment by xyz327** [comment]
https://github.com/dromara/hutool/blob/a0c65de743f895a1b78445a03071c4d647e0f4cb/hutool-http/src/main/java/cn/hutool/http/useragent/OS.java#L63-L65

自己增加相应的解析呗
