### ISSUE TITLE
JSONUtil无法解析record类（java16 特性）

### ISSUE THREAD

**Issue by anci3ntr0ck** [looly/hutool#2335]
### 版本情况

JDK版本：    openjdk_17.0.1
hutool版本： 5.8.0

### 问题描述（包括截图）

1. 复现代码

```java
public record Response(int code, String msg, Object data) {

    public static String RespJsonStr(int code, String msg, Object data) {
        return JSONUtil.toJsonStr(new Response(code, msg, data));
    }

}
```
函数的输出结果总为空“{}”
可能是由于record类编译后直接使用字段名作为get方法名，导致无法识别？
![image](https://user-images.githubusercontent.com/55662947/168721147-e86b4b24-119a-46a4-aa2b-17078d3f6bba.png)

将类改为普通类，使用getXXX作为方法名后可以正常使用
![image](https://user-images.githubusercontent.com/55662947/168721456-681a8792-8793-492e-b0f3-7650640eb7b3.png)

**Comment by zhouxiaofu** [comment]
用别的json工具估计也不行吧？

**Comment by looly** [comment]
这个record类并不符合标准的Bean格式规范。

你可以使用`GlobalSerializeMapping.put(Record.class, JSONObjectSerializer)`方法，全局创建自定义的对象序列化规则。
