### ISSUE TITLE
5.8.0.M3里程碑版本怎么没有说明

### ISSUE THREAD

**Issue by JoeyBling** [looly/hutool#2336]
### 版本情况

JDK版本：    OracleJDK_1.8.0_251
hutool版本： 5.8.0.M3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
**&emsp;&emsp;[5.8.0.M3](https://mvnrepository.com/artifact/cn.hutool/hutool-bom/5.8.0.M3)里程碑版本怎么没有说明**

**Comment by JoeyBling** [comment]
> [tag](https://github.com/dromara/hutool/tags)标签没看到，在[CHANGELOG.md](https://github.com/dromara/hutool/blob/a0c65de743f895a1b78445a03071c4d647e0f4cb/CHANGELOG.md)找到了。[5.8.0.M3 (2022-04-14)](https://github.com/dromara/hutool/blob/v5-master/CHANGELOG.md#580m3-2022-04-14)

**Comment by looly** [comment]
是滴。~~
