### ISSUE TITLE
SqlUtil.buildLikeValue不会对内容进行转义

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#2337]
SqlUtil.buildLikeValue 不会对 内容中的 % _ \  转义

System.out.println(SqlUtil.buildLikeValue("%", LikeType.Contains,false));
打印: %%%
预期打印：%\\%%

可以参考[https://stackoverflow.com/questions/45276410/escape-mysql-strings-in-java-without-prepared-statements](https://stackoverflow.com/questions/45276410/escape-mysql-strings-in-java-without-prepared-statements)

**Comment by zhouxiaofu** [comment]
我觉得应该新增一个 转mysql字符串的方法
官方转义字符表
[https://dev.mysql.com/doc/refman/5.7/en/string-literals.html](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html)

**Comment by looly** [comment]
考虑到不同数据库的兼容性，此方法并没有加入转义的内容。

用户需要根据实际数据库的类型，自行完成转义。
