### ISSUE TITLE
有没有比较两个数据库中表的不同及相同表中字段不同的方法？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2338]
背景：项目迭代很快 dev环境的sql执行了 但是test环境的忘记执行了
所以 需要这么一个方法
例如：DbDiff diff  = DbUtil.dff(Datasource d1, Datasource d2);
diff中包含了差异信息

**Comment by CherryRum** [comment]
这个需求不符合工具类的定义了，
这个需求很大的，语义分析，语法分析，不同库，很多麻烦的问题
暂时加不了

**Comment by joey-happy** [comment]
> 这个需求不符合工具类的定义了， 这个需求很大的，语义分析，语法分析，不同库，很多麻烦的问题 暂时加不了

https://github.com/oracle614/sagacity-db-diversity
