### ISSUE TITLE
BeanUtil空指针问题

### ISSUE THREAD

**Issue by wuyanzu-9527** [looly/hutool#2339]
### 版本情况
hutool版本： 5.8.0

### 问题描述
BeanUtil.copyProperties(); 
5.7.17之前当source为null时会返回一个空的target(非null),5.8.0直接抛出空指针异常,如果是作者
有意而为的话希望能在方法上注明source为null时将抛出空指针异常
1. 复现代码

```java
final Map<String, PropDesc> sourcePropDescMap = BeanUtil.getBeanDesc(source.getClass()).getPropMap(copyOptions.ignoreCase);
```
source.getClass()  若source为null会空指针

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I58CJ3
