### ISSUE TITLE
ArrayUtil.isEmpty功能是否存在问题

### ISSUE THREAD

**Issue by JJput** [looly/hutool#2342]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（已确保最新还有问题）

### 问题描述（包括截图）
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/32796639/169438942-051b22a2-67dd-48cb-ab41-a36b12343e2a.png">
isEmpty判断已实例化的List对象，但size==0却返回fasle
翻看了源码如下：
<img width="591" alt="image" src="https://user-images.githubusercontent.com/32796639/169439084-5f824415-c1bb-4e21-b722-f6ac75f3dbf9.png">
其中有`return 0 == Array.getLength(array);`，也就是`if (isArray(array))`并无生效，您这里判断的数组只指java系统数组`[]`是么?并不泛指List等对象。能否支持？

**Comment by looly** [comment]
对的。ArrayUtil只是判断数组，列表有`CollUtil.isEmpty。

如果你不想区分数组还是列表，也可以使用`ObjectUtil.isEmpty`

**Comment by JJput** [comment]
好的，谢谢
