### ISSUE TITLE
zip压缩问题~

### ISSUE THREAD

**Issue by CodeMan-cmd** [looly/hutool#2344]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.5.6</version>
        </dependency>

### 问题描述（包括截图）
**通过下列代码测试发现压缩指定的zip的文件夹下，报错不能是目录~按照官方文档上的代码和描述并且没有有效果**
Exception in thread "main" cn.hutool.core.exceptions.UtilException: Zip file [E:\demo_file\zip] must not be a directory !

1. 复现代码

```java
    private static final String FILE_PATH = "E:\\demo_file\\file";
    private static final String ZIP_TARGET_PATH = "E:\\demo_file\\zip";
        ZipUtil.zip(FILE_PATH,
                ZIP_TARGET_PATH + "\\");
```

2. 堆栈信息
![image](https://user-images.githubusercontent.com/52879329/169694635-cc67cf96-49b5-41f4-bfaf-2cb55c47087b.png)

**Comment by looly** [comment]
按照报错信息，应该是你的`E:\\demo_file\\zip`这个路径已经存在且为目录，这个路径必须是文件，你可以指定为：


```
E:\\demo_file\\zip\\xxx.zip
```

**Comment by CodeMan-cmd** [comment]
&nbsp;
你们这个描述变化了，当时说的是将aaa下的所有文件目录打包到bbb下的aaa.zip 文件目
建议：官方文档尽量不要描述太多无用，或者是错误的表达~我这是算踩坑了哈哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] zip压缩问题~ (Issue #2344)





 
按照报错信息，应该是你的E:\\demo_file\\zip这个路径已经存在且为目录，这个路径必须是文件，你可以指定为：
 E:\\demo_file\\zip\\xxx.zip

**Comment by looly** [comment]
@CodeMan-cmd 看下：https://hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E5%8E%8B%E7%BC%A9%E5%B7%A5%E5%85%B7-ZipUtil?id=zip

文档有写第二个参数必须是文件的哦。
