### ISSUE TITLE
ImgUtil.scale缩放1亿像素照片时耗时过长

### ISSUE THREAD

**Issue by tastypinenut** [looly/hutool#2345]
### 版本情况

JDK版本：    jdk1.7
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
ImgUtil.scale缩放1亿像素照片时耗时过长，以下附件中的10000x7500像素照片需要3秒多才能缩放完成，12032x9024像素甚至需要11秒才能完成缩放

1. 复现代码

```java
    public static void main(String[] args) {
        long startTime = System.currentTimeMillis();
        ImgUtil.scale(
                FileUtil.file("xrk.jpg"),
                FileUtil.file("xrk2.jpg"),
                0.08f // 10000x7500 缩放到 800x600
        );
        System.out.println("time = " + (System.currentTimeMillis() - startTime));
   }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
链接: https://pan.baidu.com/s/17Rdcbzua9_gRropG1eHUtw 提取码: zm7a

**Comment by looly** [comment]
嗯……建议放弃吧。Hutool封装的是JDK中awt相关类，处理过程应该是先全部加载内存，再做处理。

建议找专业的图像处理库。
