### ISSUE TITLE
关于XmlUtil.mapToXml方法询问

### ISSUE THREAD

**Issue by gaoxs1985** [looly/hutool#2346]
### 版本情况

JDK版本：    openjdk_8_322
hutool版本： 5.7.22

### 描述

XmlUtil.mapToXml方法，如果Map参数位空map时，生成的xml为
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<log/>
```
可以通过什么方式生成为
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<log>
</log>
```
还是XmlUtil.mapToXml方法只能生成第一种结构？

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I592R0
