### ISSUE TITLE
重启服务后偶先patch无法执行

### ISSUE THREAD

**Issue by RoyXiBoy** [looly/hutool#2347]
### 版本情况

JDK版本：    1.8.0_161
hutool版本： 5.7.5（已确认最新版本无修改）

### 问题描述（包括截图）
调用patch方法报 
cn.hutool.http.HttpException: Invalid HTTP method: PATCH 

1. 复现代码
偶现，无法准确复现

2. 堆栈信息
![TLCufEnEKs](https://user-images.githubusercontent.com/22719855/170199273-795c1083-e300-4091-a37d-131b1f51f064.jpg)

经过验证目前定位的是 反射抛出异常导致，如上图所示

与正常情况下对比，目前仅能得到下面的结果：
![image](https://user-images.githubusercontent.com/22719855/170199751-4d073352-2423-44a6-ad8d-650f4a07fd9c.png)

下面是：HttpGlobalConfig 第一次调setFieldValue的参数情况 
异常请求参数：
![mnC7KsZC0O](https://user-images.githubusercontent.com/22719855/170199482-7ec12e27-7d18-4965-91bf-0e61eb1c8959.jpg)
正常请求参数：
![hbfpGF6Y1D](https://user-images.githubusercontent.com/22719855/170199950-7c641cf3-6128-4a14-907b-b9312984756e.jpg)

**Comment by RoyXiBoy** [comment]
![image](https://user-images.githubusercontent.com/22719855/170201118-7a9efddc-64b1-46b0-8d8a-054eb9cec1e5.png)
传错了 这个才是第一次异常

**Comment by looly** [comment]
因为HttpUrlConnection本身不支持patch方法，Hutool使用注入方式修改原类中的参数来支持这一方法，可能存在偶尔注入失败的问题。但是现在无法确定注入失败的原因。

考虑HttpClient比较稳妥。
