### ISSUE TITLE
Singleton.get ConcurrentHashMap.transfer 死循环

### ISSUE THREAD

**Issue by zhouchengfei** [looly/hutool#2349]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
https://blog.csdn.net/xiaochao_bos/article/details/103789991

Singleton.get(一个类),刚好那个类的单例方法也用了Singleton.get 就出现上面文章的问题

[root@wshang-02 ~]# jstack 2315|grep 90c -A 30
"main" #1 prio=5 os_prio=0 tid=0x00007f09f0008800 nid=0x90c runnable [0x00007f09f6561000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap.java:2497)
	at java.util.concurrent.ConcurrentHashMap.addCount(ConcurrentHashMap.java:2288)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1720)
	at cn.hutool.core.lang.Singleton.get(Singleton.java:55)
	at cn.hutool.core.lang.Singleton.get(Singleton.java:39)
	at com.****ServiceImpl.getInstance(WxMessageServiceImpl.java:23)

**Comment by looly** [comment]
嗯，我看文章了，请问有好的解决方案么?

**Comment by looly** [comment]
更详细的介绍：https://blog.csdn.net/g6U8W7p06dCO99fQ3/article/details/106846139

**Comment by looly** [comment]
5.8.2修复此问题。

采用Dubbo类似方式完成修复。

```java
Object value = POOL.get(key);
if(null == value){
	POOL.putIfAbsent(key, supplier.callWithRuntimeException());
	value = POOL.get(key);
}
return (T) value;
```

**Comment by Vinke2** [comment]
> ```java
> Object value = POOL.get(key);
> ```

这个高并发下不能保证计算函数只执行一次啊

**Comment by looly** [comment]
@wenkang-du 你是指get只执行一次么？确实不能保证，所以叫避开bug的替代方案。但是可以保证put只执行一次。

**Comment by Vinke2** [comment]
> ```java
> supplier.callWithRuntimeException()
> ```

我指的是这个方法,因为此方法可能是一个耗时操作,高并发执行多次会带来性能问题

**Comment by looly** [comment]
@zhouchengfei 明白你说的了。实际使用中确实存在多次调用问题，要不说只是一种绕过bug的方法，这个在JDK8下没有办法解决。欢迎提供更好的思路。

**Comment by Vinke2** [comment]
暂时只想到双重检查锁的办法,不知道是否合适

**Comment by looly** [comment]
@wenkang-du 那你要对ConcurrentHashMap全部方法加读写锁，还不如直接使用HashMap加锁快。所以遇到supplier比较耗费时间，就用`Collctions.synchronizedMap(new HashMap())`就行。

**Comment by hoxiansen** [comment]
能不能再加一个Map<K, Object> lockMap，用来存放每个key的锁，然后用这个锁来做double-check

**Comment by looly** [comment]
@hoxiansen ConcurrentHashMap已经有锁了，因此加key锁没有意义。

**Comment by hoxiansen** [comment]
@looly 感谢回复。我的意思是加锁来保证 `supplier.callWithRuntimeException()` 这行最多只执行一次，当在这个方法特别消耗资源的情况下为每个key加个double-check还是有意义的吧。
