### ISSUE TITLE
BigExcelWriter创建新的sheet的时候, 会报参数异常，下标越界

### ISSUE THREAD

**Issue by ONI-MIKO** [looly/hutool#235]
poi版本3.17
hutool版本4.4.0
代码如下
AtomicLong totalHouseNum = new AtomicLong(0L);
        // 通过工具类创建writer
        BigExcelWriter writer = ExcelUtil.getBigWriter(filePath);
        //自定义标题别名
        writer.addHeaderAlias("cityName", "城市名称");
        writer.addHeaderAlias("blockId", "小区id");
        writer.addHeaderAlias("orgName", "小区名称");
        writer.addHeaderAlias("buildingId", "楼栋id");
        writer.addHeaderAlias("buildingName", "楼栋名称");
        writer.addHeaderAlias("appbuilding", "楼栋编码");
        writer.addHeaderAlias("appunit", "单元编码");
        writer.addHeaderAlias("apphouse", "房间号");
        // 合并单元格后的标题行，使用默认标题样式
        writer.merge(7, "思源房间信息");
        blocks.stream().map(block -> {
            List<HouseDTO> rows = JDBCUtils.queryForList(SQL_queryHouseByBlockId, HouseDTO.class, block.getBlockId());
            System.out.println(String.format("小区:%s查询到的房间数量:%s", block.getBlockId(), rows.size()));
            return rows;
        }).forEach(rows -> {
            if (rows.isEmpty()) {
                return;
            }
            List<HouseExcelDTO> resultList = new ArrayList<>();
            for (HouseDTO house : rows) {
                resultList.add(copy(house));
                resultList.add(copy(house));
                resultList.add(copy(house));
                resultList.add(copy(house));
                resultList.add(copy(house));
                resultList.add(copy(house));
                resultList.add(copy(house));
            }
            totalHouseNum.addAndGet(resultList.size());
            int rowNum = writer.getSheet().getLastRowNum();
            if (rowNum + resultList.size() > 1048576) {
                // 新建sheet
                writer.setSheet(writer.getSheetCount());
            }
            // 一次性写出内容，使用默认样式
            writer.write(resultList);
        });
        System.out.println(String.format("总房间数量:%s", totalHouseNum.get()));
        // 关闭writer，释放内存
        writer.close();

 writer.setSheet(writer.getSheetCount());这里报错了
![default](https://user-images.githubusercontent.com/21209857/50670847-0a981580-1009-11e9-9a3c-6e2f2d5ac43c.png)
![default](https://user-images.githubusercontent.com/21209857/50670862-26032080-1009-11e9-9312-af8f95a17ad3.png)
这一行直接报错了，没有走后面的创建逻辑

**Comment by looly** [comment]
看报错是数据大于最大行数。

**Comment by ONI-MIKO** [comment]
> 
> 
> 看报错是数据大于最大行数。

我图片发错了，，，这个是刚开始报的错，后面我自己做判断，超过最大行就新建一个sheet，然后新建的时候报错了

**Comment by ONI-MIKO** [comment]
> 
> 
> 看报错是数据大于最大行数。

![default](https://user-images.githubusercontent.com/21209857/50672082-dc1e3880-1010-11e9-8cb5-00b86767e898.png)

**Comment by looly** [comment]
4.4.1修复此问题。感谢。
