### ISSUE TITLE
用了CollUtil.isNotEmpty()，idea依然给出可能产生空指针异常警告

### ISSUE THREAD

**Issue by wwplash** [looly/hutool#2351]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
用了CollUtil.isNotEmpty()，idea依然给出可能产生空指针异常警告

1. 复现代码

```java
public static void main(String[] args) {
        List<Object> list = getList();
        if(CollUtil.isNotEmpty(list)){
            for (Object o : list) {
                System.out.println(o);
            }
        }

    }

    public static List<Object> getList(){
        return null;
    }

```
<img width="570" alt="error" src="https://user-images.githubusercontent.com/49054005/170625287-5185ba33-a5db-47b3-9a84-b3c13ddc830b.png">

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

4.建议
建议底层改成 !Empty(collection)

**Comment by CherryRum** [comment]
这个是idea提示问题，不能为了去兼容他没扫描出来，就修改底层
