### ISSUE TITLE
使用工具类 ExcelUtil.getBigWriter 异常有可能被吞掉，导致无法定位问题。

### ISSUE THREAD

**Issue by daiyun169** [looly/hutool#2354]
### 版本情况

JDK版本：    java version "11.0.10" 2021-01-19 LTS
hutool版本： 5.6.3（请确保最新尝试是否还有问题）
poi-ooxml: 5.2.2

### 问题描述（包括截图）

1. 复现代码

```java
    try {

      ExcelWriter bigWriter = ExcelUtil.getBigWriter();

      BigExcelWriter bigExcelWriter = new BigExcelWriter();

    } catch (Throwable e) {

      log.error("出错啦", e);

      return ResultVo.fail();

    }
```

2. 堆栈信息

Caused by: java.lang.NullPointerException: null
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:377)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:322)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 88 common frames omitted

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

环境说明下：
1、我们测试环境一切正常
2、阿里云ECS 运行代码由于使用的是工具类创建  ExcelUtil.getBigWriter() 异常被吞。

**Comment by daiyun169** [comment]
![image](https://user-images.githubusercontent.com/19162724/170688790-04ea31b3-5aa1-4b8a-a3dd-6a7d69b31437.png)

**Comment by looly** [comment]
很奇怪的问题。

Hutool的BigWriter创建只是简单将异常包装为运行时异常，没有吞掉啊。

这个不太好复现，而且ERROR级别也是直接打印的啊。

麻烦补充问题，再打开issue。

**Comment by daiyun169** [comment]
@looly 你好，这个问题是运行环境的问题。没有特定的字体库

`
		try {
			return new BigExcelWriter();
		} catch (NoClassDefFoundError e) {
			throw new DependencyException(ObjectUtil.defaultIfNull(e.getCause(), e), PoiChecker.NO_POI_ERROR_MSG);
		}
`
这个捕获的异常不够，如果不是 NoClassDefFoundError 异常 就会吞掉异常 比如 上面的 
java.lang.InternalError: java.lang.reflect.InvocationTargetException

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/170895740-5bd90d08-f373-4850-9254-77f23c3b2305.png)


你可以看到，Hutool只是针对`NoClassDefFoundError`单独处理了而已，这么做的目的是当发现POI的相关类找不到的时候，提醒开发者需要引入jar，而其他异常，如字体找不到之类的，并不在提醒范围内，直接抛出原始异常了，并没有吞掉。

**Comment by daiyun169** [comment]
> ![image](https://user-images.githubusercontent.com/1432613/170895740-5bd90d08-f373-4850-9254-77f23c3b2305.png)
> 
> 你可以看到，Hutool只是针对`NoClassDefFoundError`单独处理了而已，这么做的目的是当发现POI的相关类找不到的时候，提醒开发者需要引入jar，而其他异常，如字体找不到之类的，并不在提醒范围内，直接抛出原始异常了，并没有吞掉。

是的，是我看错了。

**Comment by daiyun169** [comment]
> > ![image](https://user-images.githubusercontent.com/1432613/170895740-5bd90d08-f373-4850-9254-77f23c3b2305.png)
> > 你可以看到，Hutool只是针对`NoClassDefFoundError`单独处理了而已，这么做的目的是当发现POI的相关类找不到的时候，提醒开发者需要引入jar，而其他异常，如字体找不到之类的，并不在提醒范围内，直接抛出原始异常了，并没有吞掉。
> 
> 是的，是我看错了。

我的程序里面捕获的是 Exception 所以我错误的以为是异常被吞了。
实际上程序运行 ExcelUtil.getBigWriter 是报错了 InternalError ，而我自己没有捕获到。

**Comment by daiyun169** [comment]
问题已经解决。经过排查，发现是 阿里云 ECS centos 镜像缺少字体。

`yum install fontconfig`
`fc-cache --force`

重启服务即可
