### ISSUE TITLE
NumberUtil空字符串判断数字返回true

### ISSUE THREAD

**Issue by initchen** [looly/hutool#2356]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
boolean isLong = NumberUtil.isLong("");
System.out.println(isLong); // true
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

从5.7.22升级到5.8.2之后，我看源码NumberUtil加入了null检查，但是好像把空字符串一起忽略了，导致表现不太一致。
```java
public static boolean isLong(String s) {
	if(StrUtil.isNotBlank(s)) {
		try {
			Long.parseLong(s);
		} catch (NumberFormatException e) {
			return false;
		}
	}
	return true;
}
```

**Comment by CherryRum** [comment]
确实是bug，下个版本修复

**Comment by looly** [comment]
我晕，失误了…… 5.8.3修复此问题，感谢！
