### ISSUE TITLE
网络框架有问题

### ISSUE THREAD

**Issue by xmhwws** [looly/hutool#2358]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.8.1

### 问题描述（包括截图）

url鉴权，hutool有点问题
比如url = http://账号:密码@域名.com
一个get请求，用浏览器可以正常访问，获取返回数据
但hutool的网络框架访问一直401错误

一个大佬看了下，说网络框架有问题，让我把请求改为这样：
url = http://域名.com
添加请求头 Authorization = Basic base64(账号:密码)
用hutool的网络框架访问，就可以正常获取数据

请作者大大排查下，hutool的网络框架是否对一些情况没处理好，有没有其他问题了

**Comment by CherryRum** [comment]
参照这个，应该是没有实现这个规范，需要手动实现以下
https://docs.oracle.com/javase/6/docs/technotes/guides/net/http-auth.html
