### ISSUE TITLE
JSONUtil.toBean方法没办法把类路径字符串解析成Class对象

### ISSUE THREAD

**Issue by hhf296095496** [looly/hutool#2359]
### 版本情况

JDK版本：    openjdk_11
hutool版本： 5.8.2（会报错），5.4.0（会解析成null，不会报错）

### 问题描述（包括截图）
我想把含有Class<?>类型的属性的对象解析成json格式的字符串，然后再解析回来成对象
解析成字符串没问题，但是再解析回来成对象的话，用5.8.2版本会报错，用5.4.0会把Class<?>属性的值解析成null，但不会报错

1. 复现代码

```java

//这是一个自定义对象
RpcRequestMessage message = new RpcRequestMessage(1,    //int类型
        "222", //字符串类型
        "123", //字符串类型
        HelloService.class,  //Class<?>类型
        new Class[]{HelloService.class}, //Class<?>数组类型
        args  //字符串数组类型
);
System.out.println("message = " + message); 
JSON parse = JSONUtil.parse(message);
String s = parse.toString();
System.out.println("s = " + s);

RpcRequestMessage toBean = JSONUtil.toBean(parse, new TypeReference<RpcRequestMessage>() {}, false);
System.out.println("bean = " + toBean);


```

2. 堆栈信息
这是用5.8.2版本打印的：
**message** = RpcRequestMessage(super=Message(sequenceId=1, messageType=101), interfaceName=222, methodName=123, **returnType**=interface com.hhf.nio.netty.rpc.service.HelloService, **parameterTypes**=[interface com.hhf.nio.netty.rpc.service.HelloService], parameterValue=[])

**s** = {"interfaceName":"222","methodName":"123","**returnType**":"interface com.hhf.nio.netty.rpc.service.HelloService","**parameterTypes**":["interface com.hhf.nio.netty.rpc.service.HelloService"],"parameterValue":[],"sequenceId":1,"messageType":101}

**Exception** in thread "main" cn.hutool.core.convert.ConvertException: Can not Converter from [java.lang.String] to [java.lang.Class<?>]

这是用5.4.0版本打印的：
**message** = RpcRequestMessage(super=Message(sequenceId=1, messageType=101), interfaceName=222, methodName=123, **returnType**=interface com.hhf.nio.netty.rpc.service.HelloService, **parameterTypes**=[interface com.hhf.nio.netty.rpc.service.HelloService], parameterValue=[])

**s** = {"**parameterTypes**":["interface com.hhf.nio.netty.rpc.service.HelloService"],"methodName":"123","parameterValue":[],"sequenceId":1,"messageType":101,"interfaceName":"222","**returnType**":"interface com.hhf.nio.netty.rpc.service.HelloService"}

**bean** = RpcRequestMessage(super=Message(sequenceId=1, messageType=101), interfaceName=222, methodName=123, **returnType**=null, **parameterTypes**=null, parameterValue=[])
上面信息中的returnType和parameterTypes是Class<?>和Class<?>[]类型，都没有解析回去

4. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
没法完成自动解析。

类名称解析为类的风险较大（如反序列化漏洞），如果需要，请自行实现`JSONDeserializer`

```java
GlobalSerializeMapping.put
```
