### ISSUE TITLE
Your project looly/hutool is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [looly/hutool#236]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  commons-logging commons-logging (hutool-log/pom.xml)
  version: 1.2

  Jira issues:
  BufferedReader is not closed properly
  affectsVersions:1.1.1;1.2
  https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-163?filter=allopenissues

  2  org.apache.logging.log4j log4j-core (hutool-log/pom.xml)
  version: 2.10.0

  Jira issues:
  Curly braces in parameters are treated as placeholders
  affectsVersions:2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2032?filter=allopenissues
  Remove Log4J API dependency on Management APIs
  affectsVersions:2.9.1;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2126?filter=allopenissues
  Log4j2 throws NoClassDefFoundError in Java 9
  affectsVersions:2.10.0;2.11.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2129?filter=allopenissues
  ThreadContext map is cleared => entries are only available for one log event
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2158?filter=allopenissues
  Objects held in SortedArrayStringMap cannot be filtered during serialization
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2163?filter=allopenissues
  NullPointerException at org.apache.logging.log4j.util.Activator.loadProvider(Activator.java:81) in log4j 2.10.0
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2182?filter=allopenissues
  MarkerFilter onMismatch invalid attribute in .properties
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2202?filter=allopenissues
  Configuration builder classes should look for "onMismatch"; not "onMisMatch".
  affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2219?filter=allopenissues
  Empty Automatic-Module-Name Header
  affectsVersions:2.10.0;2.11.0;3.0.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2254?filter=allopenissues
  ConcurrentModificationException from org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:71)
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2276?filter=allopenissues
  Allow SystemPropertiesPropertySource to run with a SecurityManager that rejects system property access
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2279?filter=allopenissues
  ParserConfigurationException when using Log4j with oracle.xml.jaxp.JXDocumentBuilderFactory
  affectsVersions:2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2283?filter=allopenissues
  Log4j 2.10+not working with SLF4J 1.8 in OSGI environment
  affectsVersions:2.10.0;2.11.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2305?filter=allopenissues
  fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
  affectsVersions:2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.9.1;2.10.0;2.11.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues
  NullPointerException when closing never used RollingRandomAccessFileAppender
  affectsVersions:2.10.0;2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2418?filter=allopenissues

  3  ch.qos.logback logback-classic (hutool-log/pom.xml)
  version: 1.2.3

  Jira issues:
  missing log files and log entries when using SizeAndTimeBasedRollingPolicy 
  affectsVersions:1.2.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1361?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by looly** [comment]
Thanks for your issue.

1. The newest version of `commons-logging` is `1.2`，and Hutool dependency for it is optional.

2. We have update `log4j-core` to `2.11.1`

3. The newest version of `logback-classic` is `1.2.3`，and Hutool dependency for it is optional.
