### ISSUE TITLE
能否增加一些AnsiColor的alias

### ISSUE THREAD

**Issue by yzqdev** [looly/hutool#2367]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

当前有`Console.log`,`Console.error`等等控制台打印的封装,跟js控制台的console很像,请问能否像js控制台一样打印颜色文字
就像这样
```java
Console.green("this is green text")
Console.purple("this is purple")
```
下面是js控制台的打印颜色字体封装,在打印很多变量时很好区分
![image](https://user-images.githubusercontent.com/20037151/172110113-ea0c70fe-13ac-4612-909f-a7e291e8b446.png)

 ```js
class Log {
  purple(text) {
    console.log("%c" + text, "color:purple");
  }
  green(text) {
    console.log("%c" + text, "color:green");
  }
}
```

**Comment by looly** [comment]
Hutool提供了ConsoleColorLog，以及`AnsiEncoder.encode`可以配合完成彩色输出。

暂不考虑单独封装。
