### ISSUE TITLE
邮件工具能否适配 jakarta.mail

### ISSUE THREAD

**Issue by LemonGo97** [looly/hutool#2368]
### 版本情况

JDK版本：    zulujdk_8_332
hutool版本： 5.8.2

### 问题描述

邮件工具适配问题

`javax.mail` 从18年就转到  `jakarta.mail` 了，能否对新的包名进行一下适配

**Comment by looly** [comment]
hutool 6.x做全面适配，直接抛弃javax.mail，你可以先下载自行编译。
