### ISSUE TITLE
byte[]数组转换成json字符串bug合集

### ISSUE THREAD

**Issue by hdwang123** [looly/hutool#2369]
### 版本情况

JDK版本：    jdk-8u271-windows-x64.exe
hutool版本： 5.8.2

### 问题描述（包括截图）
1.byte[]转成json字符串直接报错了（A JSONArray text must start with '[' at 3 [character 2 line 2]）
2.List<FileInfo{byte[]}、Map<String,FileInfo{byte[]}> 这种的反序列化回来为null
3.FileInfo{byte[]} 这种反序列化回来直接报错 （Unparseable number: "MDAx"）这个是：issues/2365

1. 复现代码

```
JSONUtil.toJsonStr(new byte[]{ 10, 11});

```

2. 堆栈信息
3. Exception in thread "main" cn.hutool.json.JSONException: A JSONArray text must start with '[' at 3 [character 2 line 2]
	at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:396)
	at cn.hutool.json.JSONParser.parseTo(JSONParser.java:102)
	at cn.hutool.json.ObjectMapper.mapFromTokener(ObjectMapper.java:242)
	at cn.hutool.json.ObjectMapper.map(ObjectMapper.java:148)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:168)
	at cn.hutool.json.JSONArray.<init>(JSONArray.java:147)
	at cn.hutool.json.JSONUtil.parseArray(JSONUtil.java:175)
	at cn.hutool.json.JSONUtil.parse(JSONUtil.java:234)
	at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:373)
	at cn.hutool.json.JSONUtil.toJsonStr(JSONUtil.java:355)
	at com.hdwang.test.ObjectConvertTest.main(ObjectConvertTest.java:67)

4. 测试涉及到的文件（注意脱密）

**Comment by hdwang123** [comment]
这些是好的：
JSONUtil.toJsonStr(new Byte[]{ 10, 11});
JSONUtil.toBean("[10, 11]", byte[].class, false);
JSONUtil.toBean("[10, 11]", Byte[].class, false);

**Comment by CherryRum** [comment]
您的复现代码，可否贴一下呢

**Comment by hdwang123** [comment]
[001.txt](https://github.com/dromara/hutool/files/8857966/001.txt)

@Data
public class FileInfo {

    private String fileName;

    private byte[] fileBytes;

}

测试代码：

File src = new File("D:/test/001.txt");
        byte[] fileBytes = FileUtil.readBytes(src);
        FileInfo fileInfo = new FileInfo();
        fileInfo.setFileBytes(fileBytes);
        fileInfo.setFileName(src.getName());
        String fileInfoStr = JSONUtil.toJsonStr(fileInfo);
      fileInfo = JSONUtil.toBean(fileInfoStr,FileInfo.class,false); //Unparseable number: "MDAx"

List<FileInfo> fileInfos = new ArrayList<>();
        fileInfos.add(fileInfo);
        fileInfoStr = JSONUtil.toJsonStr(fileInfos);
        fileInfos =  JSONUtil.toBean(fileInfoStr, new TypeReference<List<FileInfo>>() {
        }, false); //这种的反序列化回来byte[]为null
        System.out.println(fileInfos);

        Map<String,FileInfo> fileInfoMap = new HashMap<>();
        fileInfoMap.put("file1", fileInfo);
        String fileInfoMapStr = JSONUtil.toJsonStr(fileInfoMap);
        fileInfoMap =  JSONUtil.toBean(fileInfoMapStr, new TypeReference<Map<String,FileInfo>>() {
        }, false);  //这种的反序列化回来byte[]为null
        System.out.println(fileInfoMap);


        String bytesStr = JSONUtil.toJsonStr(new Byte[]{ 10, 11});
        String bytesStr = JSONUtil.toJsonStr(new byte[]{ 10, 11}); //A JSONArray text must start with '[' at 3 [character 2 line 2]
        bytes = JSONUtil.toBean("[10, 11]", byte[].class, false);
        Byte[] bytes1 = JSONUtil.toBean("[10, 11]", Byte[].class, false);
        System.out.println(bytes);

**Comment by hdwang123** [comment]
看我下方评论

**Comment by hdwang123** [comment]
> 您的复现代码，可否贴一下呢

看我下方评论

**Comment by looly** [comment]
5.8.3解决此问题。

此问题的原因是，构建JSONArray时，byte[]被识别为JSON字符串的二进制流形式，因此报错。

下个版本会做两项兼容。
