### ISSUE TITLE
StopWatch  prettyPrint()方法打印能否增加一个运行时间为毫秒的

### ISSUE THREAD

**Issue by jisl1024** [looly/hutool#2374]
StopWatch目前使用的用来统计报表用时，这个时间一般都较长，直接打印纳秒实在太大了，很难一眼看出，每次都要增加一个毫秒打印
log.info("通行日报结束用时:{}ms,{}",stopWatch.getTotalTimeMillis(),stopWatch.prettyPrint());
running time = 505786014 ns

如果是数据库查询，一般我们关注ms级别的时间。

**Comment by looly** [comment]
prettyPrint有一个重载方法可以自定义时长单位啊：

```java
stopWatch.prettyPrint(TimeUnit.MILLISECONDS);
```
