### ISSUE TITLE
JSONUtil工具bug

### ISSUE THREAD

**Issue by DaLanWang6** [looly/hutool#2380]
### 版本情况

JDK版本：    openjdk_1.8.0_221
hutool版本： 5.8.3（请确保最新尝试是否还有问题）

### 问题描述
  不是json格式的字符串，使用JSONUtil竟然可以转成json，本例中自动去除了逗号，转成了json

1. 复现代码
                 String s = "{\"k\":\"v\",}";//{"k":"v",} 多个逗号
		JSONObject jsonObject = JSONUtil.parseObj(s);
		System.out.println(jsonObject); //输出 {"k","v"}

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/173734008-ddad4f82-1183-47c8-ac86-40bdeaddce62.png)

这块专门增加了简单的容错处理，所以是正常的。

**Comment by DaLanWang6** [comment]
作为工具，这里加了“容错”是恰当的吗 json格式的正确性是否应该交给使用方把控呢 我发现这个问题是这样的场景，我想判断一个字符串是否为json格式。



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2022年6月15日(周三) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] JSONUtil工具bug (Issue #2380)




 

 
这块专门增加了简单的容错处理，所以是正常的。

**Comment by CherryRum** [comment]
这个由我来回复您吧，
json这个叫做```Trailing commas```
在es规范中（js语法）是允许的，但是在json中又不允许，但是又在json之后的扩展中，又被修改为允许了，所以诞生了很多库，要不报错，要不容错，这是个选择罢了

**Comment by DaLanWang6** [comment]
明白了，感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月15日(周三) 下午4:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] JSONUtil工具bug (Issue #2380)




 
这个由我来回复您吧，
 json这个叫做Trailing commas
 在es规范中（js语法）是允许的，但是在json中又不允许，但是又在json之后的扩展中，又被修改为允许了，所以诞生了很多库，要不报错，要不容错，这是个选择罢了

**Comment by looly** [comment]
@CherryRum 你这个真的是专业啊。 学习了。这个我加到注释中吧。
