### ISSUE TITLE
cn.hutool.http.HttpException: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by sheldon-lu** [looly/hutool#2383]
hutool-all：5.7.22
偶发性出现：cn.hutool.http.HttpException: Invalid HTTP method: PATCH 这是什么问题？

**Comment by sheldon-lu** [comment]
HttpResponse response = HttpRequest.patch(url + StrUtil.format(URI, "xxxx"))
                    .headerMap(headers, true)
                    .body(body)
                    .execute();

![image](https://user-images.githubusercontent.com/31846425/173973754-1b3bcecf-5bc1-430a-9a8d-cba73c1e6008.png)

**Comment by looly** [comment]
这个偶发性问题暂时没有找到原因和解决方案。

考虑使用HttpClient代替吧~~
