### ISSUE TITLE
ReUtil转义: 转义只添加了一个反斜杠, java

### ISSUE THREAD

**Issue by touch-feel** [looly/hutool#2385]
### 版本情况

JDK版本：    corretto-11
hutool版本： 5.8.4.1.M1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/73594022/173987264-9dd0ac07-ec97-4401-93ae-6f39872b66b2.png)

builder.append('\\'); 执行一次后,   builder只添加了一个反斜杠, java正则表达式需要两个反斜杠

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
麻烦说的详细点儿，没看懂。

**Comment by looly** [comment]
不对吧，转义符是一个反斜杠吧，怎么会两个反斜杠？

```java
String str = "a[bbbc";
String re = "[";
final String s = ReUtil.get(ReUtil.escape(re), str, 0);
Assert.assertEquals("[", s);
```

**Comment by touch-feel** [comment]
https://www.runoob.com/java/java-regular-expressions.html

![image](https://user-images.githubusercontent.com/73594022/173989125-02ad5ea6-122e-47d2-b01d-7cb3c2e36de8.png)

**Comment by touch-feel** [comment]
而且只用一个反斜杠转义,   match时会抛异常: java.util.regex.PatternSyntaxException
![image](https://user-images.githubusercontent.com/73594022/173989252-f4dfcfbb-bfd3-46d2-813c-1a6ad0c5c95d.png)

**Comment by touch-feel** [comment]
先吃饭去了

**Comment by looly** [comment]
@touch-feel 对啊，在Java中，字符串中的特殊字符本身就需要转义，所以`String a = "\\"`其实就是表示`\`。

你给的测试有问题，isMatch是全匹配，当然无法匹配了！

```java
String context = "{prefix}_";
String regex = "{prefix}_";
final boolean b = ReUtil.isMatch(ReUtil.escape(regex), context);
Assert.assertTrue(b);
```

**Comment by VampireAchao** [comment]
👍

**Comment by touch-feel** [comment]
是我菜了, 一时没绕过来
