### ISSUE TITLE
JSONUtil.toJsonStr怎么配置把mongo的ObjectId自动转String

### ISSUE THREAD

**Issue by c44cc** [looly/hutool#2387]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述
问题：JSONUtil.toJsonStr怎么配置把mongo的ObjectId自动转String
寻找的办法：
![@~NB`TA8MY HAGMJF0_U8(E](https://user-images.githubusercontent.com/34033955/174206284-81ab3c33-f755-4c86-a231-e104f64b008f.png)
使用这种办法有个问题，所有的属性我都得set一遍，而且我也不想指定为User，只要是包含ObjectId的都转为字符串就行

**Comment by c44cc** [comment]
![XH`Y8XX 1O~0QR5MYVHT)KH](https://user-images.githubusercontent.com/34033955/174206516-f2a98193-beb7-46e8-9fd2-bdee94a713fc.png)
Jackson这样配了转的时候就可以自动转

**Comment by looly** [comment]
嗯……5.x暂无办法解决，只能实现JSONString接口来完成。不过貌似ObjectId你动不了是吧……

**Comment by looly** [comment]
在6.0.0中可以设置全局的自定义对象写出：

```java
GlobalValueWriterMapping.put(CustomSubBean.class, (JSONValueWriter<CustomSubBean>) (writer, value) -> {
	writer.writeRaw(String.valueOf(value.getId()));
});
```
