### ISSUE TITLE
hutool邮件工具不支持S/MIME加密签名邮件，希望可以增加此功能。

### ISSUE THREAD

**Issue by 404area** [looly/hutool#2397]
建议：

hutool邮件工具不支持S/MIME加密签名发送，希望可以通过配置文件直接配置证书位置，即可发送或接收S/MIME加密签名的邮件。

**Comment by looly** [comment]
暂时没有找到方案，欢迎提供思路。

你也可以参考：https://github.com/simple-java-mail/java-utils-mail-smime 完成。
