### ISSUE TITLE
从5.7.22升级到5.8.2后导出Excel出错

### ISSUE THREAD

**Issue by Aexistence** [looly/hutool#2398]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

导出Excel文件格式混乱

1. 使用cn.hutool.poi.excel.ExcelWriter#write(java.lang.Iterable<?>)方法写入List<JSONObject>类型集合时出现问题
2. 通过debug发现cn.hutool.poi.excel.ExcelWriter#writeRow(java.lang.Object, boolean)方法中的第一行if判断结果和之前有变化导致代码进入了1016行调用了cn.hutool.poi.excel.ExcelWriter#writeRow(java.lang.Iterable<?>)方法
3. 该bug使导出文件时无法通过别名集合headerAlias写入数据、最终给Excel写入了 （X -> Y） 形式的无序且未过滤的数据
4. 经过检查发现是新版中JSONObject通过MapWrapper<String, Object>类实现了Iterable<Map.Entry<K, V>>接口导致的该问题

**Comment by Aexistence** [comment]
用5.7.22版和5.8.3版分别执行后，查看导出的Excel文件。

麻烦提供下测试用例。就是如何写出数据会触发bug？

―

**Comment by looly** [comment]
仔细看了下，确实有这个问题。

优先按照Iterable写出了，5.8.8修复。感谢！
