### ISSUE TITLE
大量的http请求会导致内存溢出

### ISSUE THREAD

**Issue by Edinjohn** [looly/hutool#2401]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.8

### 问题描述

1. 复现代码
//url是同一个域名且同一个接口
String result = new HttpRequest(url)
      .method(Method.POST)
      .header("Content-Type", "application/json")
      .header("zjgxfwxt-time", timeStamp)
      .body(“xxxxx”)
      .timeout(1000)
      .execute().body();
定时任务每个整点请求5千次

2.现象
运行2-3天后，原本占用300MB的程序（只跑这个任务），内存占用扩大到15GB。
win server，natestat -ano看到非常多 established状态的请求

3. 定位问题
换用okhttp
+ 原本 timeout(1000) 每100个请求里会失败2-3个。connect time out，换了之后稳定不会出现超时，甚至timeout时间缩短到 100ms都很稳定
+ 原本执行时间久了内存占用非常大，换了之后稳定运行了2周了。

4. 问题推测
是否hutool内的http没有复用http请求，每次都重新握手？ okhttp则实现了复用。
希望hutool也能优化底层实现，增强工具的性能和稳定性。

**Comment by looly** [comment]
因为Hutool基于HttpUrlComnnecion封装，没有连接池，可能请求太多会造成响应内容太多堆积问题。

这个考虑更换HttpClient或者OkHttp。
