### ISSUE TITLE
命令行工具需求

### ISSUE THREAD

**Issue by lizhen1412** [looly/hutool#2407]
需求:
分类:
远程执行命令
需求描述:
如果知道其他机器账号密码或者秘钥，可以远程执行其他机器上的命令。

**Comment by FULaBUla** [comment]
jschutil，hutool已经提供了，需要引入第三方依赖

**Comment by lizhen1412** [comment]
> jcshutil，hutool已经提供了，需要引入第三方依赖

我看hutools 官方文档没有，使用方法可以维护下吗？或者给个教程
https://hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7-RuntimeUtil

我们好像维护不了官方文档。

**Comment by looly** [comment]
文档源码在这里：https://gitee.com/loolly_admin/hutool-site

**Comment by FULaBUla** [comment]
> 

不好意思拼错了，是 `jschutil` @lizhen1412

**Comment by lizhen1412** [comment]
> 

https://hutool.cn/docs/#/extra/Jsch%E5%B0%81%E8%A3%85/Jsch%E5%B7%A5%E5%85%B7-JschUtil

只有账号密码的方式，其实我觉得秘钥方式也是刚需吧！

**Comment by lizhen1412** [comment]
> > 
> 
> https://hutool.cn/docs/#/extra/Jsch%E5%B0%81%E8%A3%85/Jsch%E5%B7%A5%E5%85%B7-JschUtil
> 
> 只有账号密码的方式，其实我觉得秘钥方式也是刚需吧！

我好像理解你的意思了，这其实就是个第三方的库，其实我个人是想引入我们hutools-all这个包其他的什么都不引入了。

**Comment by looly** [comment]
@lizhen1412 哈哈，ssh客户端hutool没有能力自己封装的，Jsch虽然老，但是应用比较广泛，hutool只是包装了一下。有提供证书参数的。

**Comment by lizhen1412** [comment]
> 

好像 ganymed-ssh2 用的比较多吧！支持两种策略，我们可不可以把他加去呀！或者拆分出一个模块来，这样用着更舒服一点是真的，我就不喜欢引一堆东西。

**Comment by lizhen1412** [comment]
> > 
> 
> 好像 ganymed-ssh2 用的比较多吧！支持两种策略，我们可不可以把他加去呀！或者拆分出一个模块来，这样用着更舒服一点是真的，我就不喜欢引一堆东西。

主要是ssh 和密码都支持，但是封装的都不是很好是真的，像java 这块真没啥特别好用的库

**Comment by looly** [comment]
@lizhen1412 见：GanymedUtil

**Comment by lizhen1412** [comment]
> 

好像没搜到。

**Comment by looly** [comment]
@lizhen1412 更新Hutool。

![image](https://user-images.githubusercontent.com/1432613/176653786-6376a7b0-92ea-43b1-b65d-83b27dd9a494.png)

**Comment by lizhen1412** [comment]
> @lizhen1412 更新Hutool。
> 
> ![image](https://user-images.githubusercontent.com/1432613/176653786-6376a7b0-92ea-43b1-b65d-83b27dd9a494.png)

好的，谢谢您，不过不支持秘钥有点遗憾，不过问题也不大，我看您有个有个ip + port 的api  其实本地认证好问题也不大，这样吧！大佬我先用，有好的思路我在跟您探讨或者提一个pull request
<img width="818" alt="image" src="https://user-images.githubusercontent.com/29331541/176656072-b954f3fa-692c-4fdd-a040-5ce8dc8c15fe.png">
