### ISSUE TITLE
邮件发送api 附件名称中多了一个空格 如何解决？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2413]
邮件发送api 附件名称中多了一个空格 这个知道怎么解决吗？

**Comment by joey-happy** [comment]
mailAccount.setEncodefilename(true);
这个设置成true时 附件名称：受试者纳入报 告_2022-06-28.xlsx 正确的是：受试者纳入报告_2022-06-28.xlsx （报告中间没有用空格）

mailAccount.setEncodefilename(false);
这个设置成false时 附件名称：受试者纳入报告_2022-06-28.xlsx 正确 d但是点击下载附件之后 下载后的文件名称乱码

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/176148327-65618cda-eaeb-440d-bf02-c7b75e6c5261.png)

mailAccount.setEncodefilename(true);
此属性设置成true（默认也是true） 测试了腾讯企业邮箱 qq邮箱 网易邮箱 新浪邮箱 阿里云企业邮箱 只有腾讯企业邮箱和qq邮箱有附件名称展示多空格的问题  其他邮箱附件名称展示都正确
嗨 我是真服了 哈哈

**Comment by looly** [comment]
啊，这个可能和邮件服务端的解析有关系……

setEncodefilename是转义文件命名，难道你的文件名中有特殊字符？

如果能找到解决方案，欢迎提供。
