### ISSUE TITLE
jre17的jar包运行报错

### ISSUE THREAD

**Issue by zzy-life** [looly/hutool#2420]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
打包成jar后运行就会出错
![image](https://user-images.githubusercontent.com/68179477/176630661-c2ebfae4-7396-40b2-9c07-6bcbd44fb8eb.png)

1. 复现代码

```java
sourceDir = D:\java\project\studycountry
fileFilter 是指定文件后缀java yml
 List<File> fileList = FileUtil.loopFiles(sourceDir, fileFilter);

```
![image](https://user-images.githubusercontent.com/68179477/176626957-6a3e38cf-3d39-4206-af4f-f33c982eb919.png)

**Comment by zzy-life** [comment]
不好意思 是我自己写错了

**Comment by zzy-life** [comment]
好吧还是有这个问题

**Comment by zzy-life** [comment]
发现问题在于jre无法运行  jdk可以  不过我要构建exe应该用jre

**Comment by zzy-life** [comment]
我用jdk打包了

**Comment by looly** [comment]
看样子是缺了`java.sql.xxx`

参考：https://www.cnblogs.com/Hakurei-Reimu-Zh/p/14921100.html

**Comment by zzy-life** [comment]
> 看样子是缺了`java.sql.xxx`
> 
> 参考：https://www.cnblogs.com/Hakurei-Reimu-Zh/p/14921100.html

解决了 感谢
