### ISSUE TITLE
BeanUtil.beanToMap之后，再执行BeanUtil.mapToBean无法解析回来enum

### ISSUE THREAD

**Issue by folochina** [looly/hutool#2423]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/11660951/176827865-9e94c7dd-6de0-4de6-8ed7-30ad9fcb6550.png)

1. 复现代码
![image](https://user-images.githubusercontent.com/11660951/176827900-3a0d42aa-c999-4873-a09a-a68bac97702e.png)
![image](https://user-images.githubusercontent.com/11660951/176827930-2d44a26d-1725-47f1-b346-b3e32d3ceba0.png)
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by folochina** [comment]
升级到5.8.4依然存在该问题

**Comment by looly** [comment]
针对Enum枚举，Hutool在转为字符串（JSON）时，默认调用toString方法，但是回转时可能就无法返回，需要你的enum提供一个方法，参数是String，返回值是enum才可以正常转换。
