### ISSUE TITLE
从ReflectUtil.getMethods取出的Method无法获取到方法注解

### ISSUE THREAD

**Issue by xi-nan** [looly/hutool#2424]
### 版本情况

JDK版本：    jdk1.8.0_221
hutool版本： 5.8.4
SpringBoot版本： 2.5.5

### 问题描述（包括截图）
ReflectUtil.getMethods(beanClass) 在SpringBoot中只返回了EnhancerBySpringCGLIB代理对象中的方法，无法获取到方法上的注解
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/16499394/176886253-a0b51bf7-57fd-4bd3-80cb-08204df1d3d3.png">

1. 复现代码
<img width="983" alt="image" src="https://user-images.githubusercontent.com/16499394/176886434-483e9e5e-784b-4b0b-a088-20f30d4cbb90.png">

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by VampireAchao** [comment]
:trollface:

**Comment by looly** [comment]
代理对象肯定是获取不到对应注解的，这个AnnotationUtil封装并未考虑到代理对象的情况。

你可以使用Spring的工具类：`AnnotatedElementUtils.findMergedAnnotation()`

**Comment by looly** [comment]
同时尝试使用这个看可以获取否：https://gitee.com/dromara/hutool/pulls/678
