### ISSUE TITLE
TimeInterval和GroupTimeInterval写得太烂了

### ISSUE THREAD

**Issue by maozexijr** [looly/hutool#2429]
在时间线上分别打了多个锚点：A、B、C ...

取时间差时 总是当前时间 - A、B、C （不可否认这是一种使用场景）

如果想获取 AB之间、BC之间、AC之间的时间差，我竟然要自己算 ..

试问我为啥不 自己System.currentTimeMillis() ？？？

**Comment by maozexijr** [comment]
另外

不想在多个方法中互传时间锚点（这和业务无关），我就想计算同一线程下的多个执行步骤之间的时间差。。

**Comment by wushuaiping** [comment]
哥们，我觉得提建议可以，没必要人身攻击啊

**Comment by looly** [comment]
确实写得很烂，不过考虑到兼容性一直没有去掉。

Hutool同时提供了`StopWatch`，我想这个应该满足你的需要（此工具来自Spring）

**Comment by looly** [comment]
Hutool-6.x改造中会去除`TimeInterval`和`GroupTimeInterval`，并可能强化StopWatch。

**Comment by maozexijr** [comment]
> 哥们，我觉得提建议可以，没必要人身攻击啊

对于我昨天的行为深表歉意

昨天翻源码，实在没忍住。。小情绪爆炸

见贤思齐、三省吾身，阿门~
