### ISSUE TITLE
db工具类，query方法报错不能执行update 的sql语句

### ISSUE THREAD

**Issue by xiaoyaodev** [looly/hutool#243]
![atw5hvdxix5bc 7 cz4j](https://user-images.githubusercontent.com/19989280/51070035-91866700-1675-11e9-94f3-f04dfd0a76a4.png)
![0kymv4odz5n1amm nwp 79f](https://user-images.githubusercontent.com/19989280/51070036-94815780-1675-11e9-9989-af517a17d675.png)

**Comment by looly** [comment]
文档已修正，感谢。
