### ISSUE TITLE
请问是否考虑过增加IpUtil这种工具类？

### ISSUE THREAD

**Issue by wushuaiping** [looly/hutool#2431]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
不是bug，是功能建议，比如在IpUtil中增加获取用户真实IP、判断IP是否为IPv4还是IPv6、判断是内网地址还是外网地址等等。。

**Comment by looly** [comment]
见Ipv4Util

**Comment by w-sf** [comment]
> 见Ipv4Util

@looly 大佬，只能IPV4判断是内网还是外网么，能否加个IPV6的判断

**Comment by looly** [comment]
@w-sf 见6.x的Ipv6Util

**Comment by w-sf** [comment]
> @w-sf 见6.x的Ipv6Util

@looly 我在v6-dev分支里找到了Ipv6Util，但里面没有内网判断。。是还没推送么

**Comment by looly** [comment]
@w-sf ipv6貌似没有严格的内网地址概念，只有：

- 链路本地地址（Link-Local Addresses）：以 fe80::/10 开头。
- 站点本地地址（Site-Local Addresses）：以 fec0::/10 开头，但已被废弃，不推荐使用。
- 唯一本地地址（Unique Local Addresses）：以 fc00::/7 开头

这些都在`Inet6Address`对象中有对应方法。
