### ISSUE TITLE
请求StrMatcher类功能增强

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2436]
cn.hutool.core.text.StrMatcher类请求功能增强

```java
pattern: ${name}-${age}-${gender}-${country}-${province}-${city}-${status}
text:    "小明-19-男-中国-河南-郑州-已婚"
result:  {name=小明, age=19, gender=男, country=中国, province=河南, city=郑州, status=已婚}
```

1. 变量的标识符（"${"、"}"）可以支持替换，因为结合Spring容器使用时Spring会去找这个变量（如：(name)-(age)-(gender)-(country)-(province)-(city)-(status)）
2. 增加方法能获取占位符的所有变量（结果：[name, age, gender, country, province, city, status]
3. 增加是否完全匹配方法，用来判断 pattern 和 text 是否匹配

**Comment by duhanmin** [comment]
参考这个单元测试
cn.hutool.core.text.StrMatcherTest

**Comment by looly** [comment]
这个未来会增强，见：https://github.com/dromara/hutool/issues/1940

**Comment by eoc2015** [comment]
催催更
