### ISSUE TITLE
JOSN @Alias 能否支持多个别名？

### ISSUE THREAD

**Issue by jiffei** [looly/hutool#2438]
JOSN @Alias 能否支持多个别名？

**Comment by jiffei** [comment]
或者直接兼容@JsonAlias

**Comment by looly** [comment]
不支持。多个别名意味着双向转换时无法确定使用哪个别名。

举个例子 ，如果bean中属性名为name，设置别名后是newName1, newName2，那bean转json无法确定使用哪个别名。

**Comment by jiffei** [comment]
可以参考@JsonAlias，多个别名时，bean转json时使用属性名而不是别名。

**Comment by jiffei** [comment]
> 不支持。多个别名意味着双向转换时无法确定使用哪个别名。
> 
> 举个例子 ，如果bean中属性名为name，设置别名后是newName1, newName2，那bean转json无法确定使用哪个别名。

别名只用来json转bean，bean转json用属性名，或者另外定义注解（此注解不支持多个）
jackson 就是这么做的，使用@JsonAlias控制json转bean，使用@JsonProperty控制bean转json

**Comment by looly** [comment]
@jiffei Hutool希望使用最少的注解解决更多的问题，这个不考虑。
