### ISSUE TITLE
Partition 除0异常

### ISSUE THREAD

**Issue by fanthos** [looly/hutool#2439]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

hutool-core/src/main/java/cn/hutool/core/collection/Partition.java#L29

当使用空列表初始化时，获取大小（`size()`）会提示除0异常。

**Comment by duhanmin** [comment]
* 传入空list,将会给排除错误造成困难,不如直接抛异常
* 如果size传入0,依旧会报除0异常

**Comment by fanthos** [comment]
按照之前的代码，list 的内容是可变的，没有数据应该符合使用条件
size 不应该传入0，可用 Assert 作校验

**Comment by looly** [comment]
我加了一个assert校验。

**Comment by looly** [comment]
见：https://github.com/dromara/hutool/pull/2441

**Comment by fanthos** [comment]
当list是0的时候是不是不报错，但是size是0更好

**Comment by looly** [comment]
@fanthos 如果用户提供翻页，那当index越界不报错，很有可能造成死循环。

**Comment by fanthos** [comment]
是说size()返回0不报错，但是get(i)报错可以
