### ISSUE TITLE
#2239 BUG未修复

### ISSUE THREAD

**Issue by bluef1ash** [looly/hutool#2440]
#2239 bug未修复，版本5.8.4返回文件名 `=_1657616856883.xlsx_`

**Comment by looly** [comment]
麻烦提供下你的文件名，可以看下测试，如果文件名正常，这个生成的也是正常的。

![image](https://user-images.githubusercontent.com/1432613/179339370-eafd424a-efeb-4124-b967-049508ea4230.png)

**Comment by bluef1ash** [comment]
> 麻烦提供下你的文件名，可以看下测试，如果文件名正常，这个生成的也是正常的。
> 
> ![image](https://user-images.githubusercontent.com/1432613/179339370-eafd424a-efeb-4124-b967-049508ea4230.png)

![image](https://user-images.githubusercontent.com/6230265/179360642-5f07a736-0f5e-4c9e-8044-e8c5e077d553.png)

![image](https://user-images.githubusercontent.com/6230265/179360654-198a4b0a-7f03-4b15-8c3c-1b7fc617e977.png)

![image](https://user-images.githubusercontent.com/6230265/179360658-256eda4f-0466-4369-8891-2c92a6f11a87.png)

**Comment by looly** [comment]
嗯……貌似这是浏览器问题！

见：https://blog.csdn.net/qq_41732963/article/details/122211939

你可以生成后手动去除下双引号试下，或者按照：https://blog.csdn.net/weixin_49051190/article/details/109717823 处理。
