### ISSUE TITLE
有没有获取jvm相关内存信息的工具？获取到新生代内存 老年代内存 yonggc和fullgc次数的工具类

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2444]
参考：https://github.com/toomanyopenfiles/jmxmon

**Comment by duhanmin** [comment]
@joey-happy 参考 ManagementFactory用法

**Comment by CherryRum** [comment]
java语言层次上不太可能，您这种都是agent来实现的。

**Comment by joey-happy** [comment]
> java语言层次上不太可能，您这种都是agent来实现的。

ManagerMXBean 这些都能实现 不需要agent

**Comment by joey-happy** [comment]
> ManagementFactory

还得我自己写啊 我期望的是hutool工具类直接封装

**Comment by CherryRum** [comment]
> > java语言层次上不太可能，您这种都是agent来实现的。
> 
> ManagerMXBean 这些都能实现 不需要agent

没记错，这玩意不同虚拟机都不一样，您是打算咋区分gc算法之类的呢

**Comment by joey-happy** [comment]
> > > java语言层次上不太可能，您这种都是agent来实现的。
> > 
> > 
> > ManagerMXBean 这些都能实现 不需要agent
> 
> 没记错，这玩意不同虚拟机都不一样，您是打算咋区分gc算法之类的呢

看我发的那个连接 我期望的就是能达到他的效果 open-falcon就是用这种方式采集相关数据的 
具体神马gc算法 我不关心

**Comment by CherryRum** [comment]
建议您使用哪个库，5.+版本不会新增功能了，您可以提交自己的pr到6.0上，多谢

**Comment by joey-happy** [comment]
> 建议您使用哪个库，5.+版本不会新增功能了，您可以提交自己的pr到6.0上，多谢

东西太多了 哈哈 不支持就算了

**Comment by CherryRum** [comment]
首先，这玩意不能影响你的代码业务功能，所以不建议在工具库这种业务常用中插入日志监控，这玩意应该是系统中插件存在的记录上传的一种监测工具。比如美团mycat之类的。

**Comment by joey-happy** [comment]
> 首先，这玩意不能影响你的代码业务功能，所以不建议在工具库这种业务常用中插入日志监控，这玩意应该是系统中插件存在的记录上传的一种监测工具。比如美团mycat之类的。

明白你的意思 好多都是agent这种  或者prometheus这种 这个只是工具类而已 你可以提供 但是用不用就是我们的事情了
