### ISSUE TITLE
数据库操作，sql 日志

### ISSUE THREAD

**Issue by gee1k** [looly/hutool#245]
数据库操作，sql 日志

showSql  已经开启用的logback

**Comment by gee1k** [comment]
多表关联 分页查询是不是必须使用sql语句呀？

**Comment by looly** [comment]
多表关联只能用SQL，SQL也是最方便的。

**Comment by looly** [comment]
SQL打印日志请把配置放在分组外边，否则无法识别。

具体日志级别请配置logback

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/51220796-a6af0e80-1971-11e9-9cb7-56552eb5ee70.png)

我的配置是这样的。手动通过 LogFactory 记录日志是可以的

**Comment by gee1k** [comment]
不好意思，是我的问题。 logback  日志 package 配置的问题
