### ISSUE TITLE
URLEncodeUtil.encode 符号"+"不会被编码

### ISSUE THREAD

**Issue by wushuaiping** [looly/hutool#2453]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

返回错误的编码结果代码：
```java
public static void main(String[] args) {
        String encode = URLEncodeUtil.encode("Galaxy S22+", StandardCharsets.UTF_8);
        System.out.println(encode);
    }
```
运行后的结果
```
Galaxy%20S22+
```

返回正确的编码结果代码：
URLEncoder是java.net包下的工具
```java
public static void main(String[] args) {
        String encode = URLEncoder.encode("Galaxy S22+", StandardCharsets.UTF_8);
        System.out.println(encode);
    }
```
运行后的结果
```
Galaxy+S22%2B
```

**Comment by duhanmin** [comment]
https://www.rfc-editor.org/rfc/rfc3986.txt

**Comment by looly** [comment]
URLEncodeUtil.encode默认遵循RFC3986规范，编码URL，因此不会编码+。

你可以使用`encodeAll`

**Comment by daohuosuo** [comment]
> URLEncodeUtil.encode默认遵循RFC3986规范，编码URL，因此不会编码+。
> 
> 你可以使用`encodeAll`

encodeAll直接把链接转成不能访问了  :/全被转义了
