### ISSUE TITLE
TemplateUtil 加载不了模板

### ISSUE THREAD

**Issue by hight-lig** [looly/hutool#2454]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/56749939/179205417-747de496-6165-4ac4-bd1a-04bb56d5222b.png)

1. 复现代码
TemplateEngine engine = TemplateUtil.createEngine(new TemplateConfig());
加载模板失败 找不到模板引擎

**Comment by looly** [comment]
这不已经显示加载了FreemarkerEngine？

**Comment by looly** [comment]
有问题再打开此issue。

**Comment by hight-lig** [comment]
解决了 是我的freemaker 版本太低了
