### ISSUE TITLE
请求头被强制修改为hutool

### ISSUE THREAD

**Issue by savior-only** [looly/hutool#2458]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
我的代码
.header(Header.CONTENT_TYPE, "multipart/form-data; boundary=--------------------------921378126371623762173617")

实际请求用burp抓包被改为
boundary=--------------------hutool

**Comment by looly** [comment]
multipart的boundary是自动生成的，你可以全局自定义：

```java
HttpGlobalConfig.setBoundary("--------------------------921378126371623762173617")
```
