### ISSUE TITLE
URLUtil.normalize(url) 标准化不会处理//问题

### ISSUE THREAD

**Issue by Thornchg** [looly/hutool#2462]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

URLUtil.normalize(url) 标准化不会处理//问题

1. 复现代码

```java
        String url = "http://www.hutool.cn//aaa/bbb";
        System.out.println(URLUtil.normalize(url)); // http://www.hutool.cn//aaa/bbb
```

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/179953519-5fed6cd6-aa12-415e-8266-d4e39ffd4900.png)


这个双斜杠替换是可选的，你可以使用这个方法。

具体为啥不替换，见：https://gitee.com/dromara/hutool/issues/I25MZL

**Comment by Thornchg** [comment]
好的。可以了。不过官网文档上建议也修改下 @looly

**Comment by looly** [comment]
@Thornchg 谢谢。官网文档近期会改版。
