### ISSUE TITLE
日志的文档问题

### ISSUE THREAD

**Issue by phper08** [looly/hutool#2466]
文档地址

https://www.hutool.cn/docs/#/log/%E6%A6%82%E8%BF%B0?id=%e5%b7%b2%e6%9c%89%e9%97%a8%e9%9d%a2%e5%ad%98%e5%9c%a8%e9%97%ae%e9%a2%98

![image](https://user-images.githubusercontent.com/13127645/180147937-3916ab69-7807-446b-9818-c134e162bc7c.png)

这里的 

"很多时候我们为了在类中加日志不得不写一行，而且还要去手动改XXX这个类名"

```java
private static final Logger log = LoggerFactory.getLogger(XXX.class);
```

可以改为
```java
private static final Logger log = LoggerFactory.getLogger(getClass());
```

并不需要手动修改类名

**Comment by looly** [comment]
getClass难道不是对象方法？你`private static final`如何使用对象方法？

**Comment by phper08** [comment]
写错了，应该是

```java
private final Logger log = LoggerFactory.getLogger(getClass());
```

**Comment by looly** [comment]
@phper08 可以这么写。不过你这样每次对象创建都要动态查找一次Logger，性能可不高啊。
