### ISSUE TITLE
远程读取Excel模板,写入后导出丢失原来的信息

### ISSUE THREAD

**Issue by 1996-gjq** [looly/hutool#2467]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4

### 问题描述（包括截图）
在远程放置了一个excel模板,ExcelUtil从流中获取writer,在进行编辑,原来模板中的数据没有了,只剩下新写入的数据.
模板文件:
![image](https://user-images.githubusercontent.com/40714507/180171520-b612dc5c-edec-446e-9471-a39bad140a76.png)
操作后导出的文件
![image](https://user-images.githubusercontent.com/40714507/180171302-a4b8b8b2-5770-4ded-aefd-65a2c1f167cf.png)

1. 复现代码

```java
//从oss获取模板文件
    IConfig config = aliOssUtil.getConfig();
    OSSObject object = oss.getObject(config.getBucketName(), "template/template3.xls");
    InputStream stream = object.getObjectContent();
    ExcelReader reader = ExcelUtil.getReader(stream);
    ExcelWriter writer = reader.getWriter();
    .......
    writer.writeCellValue("B1", "报告生成时间：" + DateUtil.now());
    //写出到HttpServletResponse
    writer.flush(outputStream, true);
```

**Comment by looly** [comment]
Hutool不支持模板读取的。或者考虑写出到一个临时文件试下。
