### ISSUE TITLE
sftp报错问题

### ISSUE THREAD

**Issue by xiaozhangxiaozhangchifanyonggang** [looly/hutool#2468]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.5.7

### 问题描述:sftp先查询文件目录是否存在，然后在新增或其他操作就报错

1. 复现代码
![image](https://user-images.githubusercontent.com/57582459/180190092-c9635d10-59c3-4d7c-b6c4-55003ed87850.png)
![image](https://user-images.githubusercontent.com/57582459/180190144-8bf48f6e-9415-468c-9f7a-8de7f1cf7d65.png)

```java
final boolean exist = preprocessSftp.exist(path);
        if (preprocessSftp.mkdir(path)) {
}
```

**Comment by looly** [comment]
看下cause by，是不是目录美哟权限？

有问题再打开issue。
