### ISSUE TITLE
希望在Db中新增可以使用sql的page方法

### ISSUE THREAD

**Issue by tskynn** [looly/hutool#247]
例：
page(int currPage,int pageSize,String select,String sql,Object... params)
page(1,10,""select *","from xxx ?????",params);

【成都】sky

**Comment by looly** [comment]
考虑到SQL中子语句较多，无法判断分页语句添加的合适位置，因此不考虑封装。欢迎提供意见。

**Comment by qzmer1104** [comment]
> 考虑到SQL中子语句较多，无法判断分页语句添加的合适位置，因此不考虑封装。欢迎提供意见。

这个我觉得可以参考 PageHelper的添加分页的拦截器。

**Comment by looly** [comment]
暂时先打开此issue。我需要看下pageHelper是否为伪分页。

**Comment by qhsword** [comment]
可以直接接入 [sqlhelper](https://github.com/fangjinuo/sqlhelper)

**Comment by cciloveyou** [comment]
AbstractDb中能增加批量更新方法吗？

**Comment by looly** [comment]
> AbstractDb中能增加批量更新方法吗？

executeBatch方法就可以啊，你可以传insert或者update语句。

**Comment by cciloveyou** [comment]
> > AbstractDb中能增加批量更新方法吗？
> 
> executeBatch方法就可以啊，你可以传insert或者update语句。

但是我这边是JsonArray直接转成的List Entity，批量更新entity的方法更方便，或者有没有转换Entity为sql（insert或update）的方法呢？是否能提供insertOrUpdateBatch(Entity entity)方法呢？

**Comment by looly** [comment]
有道理

**Comment by looly** [comment]
> > > AbstractDb中能增加批量更新方法吗？
> > 
> > 
> > executeBatch方法就可以啊，你可以传insert或者update语句。
> 
> 但是我这边是JsonArray直接转成的List Entity，批量更新entity的方法更方便，或者有没有转换Entity为sql（insert或update）的方法呢？是否能提供insertOrUpdateBatch(Entity entity)方法呢？

我觉得批量更新的意义不大，且存在很多问题，这个暂时不考虑了。

**Comment by dahuoyzs** [comment]
分页这个东西的确有点尴尬，公司项目中用到了MybatisPlus 的Ipage类和 PagHelper两种分页，
但是Ipage里的分页字段是currentPage和pageSize，而PageHelper里却是pageNum和pageSize两个字段。
于是公司的大佬就封装了一封，想把MybatisPlus 的分页Ipage和 PagHelper的参数统一 一下。于是就又多了一个PageUtil这个类。
那么PageUtil这个类就又要 必须依赖MybatisPlus 和PagHelper  了

**Comment by looly** [comment]
好吧，还是半夜脑袋灵光一点儿，通宵终于搞定了，5.5.3加入：

```java
String sql = "select * from user";
List<Entity> page0 = Db.use().page(sql, Page.of(0, 3));
```
