### ISSUE TITLE
hutool-http 有打算支持 GraphQL 吗?

### ISSUE THREAD

**Issue by amosnothing** [looly/hutool#2470]

**Comment by CherryRum** [comment]
5.+不会了
可能6.+有

**Comment by looly** [comment]
@CherryRum GraphQL支持JDBC么，不支持的话看有没有工具化的必要，比如Kafka之类的，貌似没有封装的意义。

**Comment by CherryRum** [comment]
也是呀

**Comment by amosnothing** [comment]
各位大大下午好，现在的 hutool-http 也是可以调用 GraphQL。

只是参数还需要特殊处理一下，比如在 postman 发起请求的时候，body 填写是：
`query{
  product(id:"123") {
    id
    title     
    handle
}}`
。但在 hutool 发起请求的时候，只需要把上面的 body 作为 Map 的value，key = "query" , 然后把 Map 转成字符串整个传给 body 即可正常调用。

**Comment by CherryRum** [comment]
> 各位大大下午好，现在的 hutool-http 也是可以调用 GraphQL。
> 
> 只是参数还需要特殊处理一下，比如在 postman 发起请求的时候，body 填写是： `query{ product(id:"123") { id title handle }}` 。但在 hutool 发起请求的时候，只需要把上面的 body 作为 Map 的value，key = "query" , 然后把 Map 转成字符串整个传给 body 即可正常调用。

这样就太不优雅了

**Comment by duhanmin** [comment]
> @CherryRum GraphQL支持JDBC么，不支持的话看有没有工具化的必要，比如Kafka之类的，貌似没有封装的意义。

@looly kafka之类可以通过Presto/Trino去封装,支持jdbc

**Comment by looly** [comment]
讨论结果，暂不考虑。
