### ISSUE TITLE
Dromara 友情链接申请

### ISSUE THREAD

**Issue by tomsun28** [looly/hutool#2472]
磊哥，申请一个 Dromara HertzBeat 友情链接 🙏 

https://hertzbeat.com/

![hertzbeat_logo](https://user-images.githubusercontent.com/24788200/180413536-ec35a3ef-7236-4bc1-ba0d-33b468843f77.png)

**Comment by looly** [comment]
Dromara的项目我都会统一加友情链接的，稍晚一些哈~~

**Comment by tomsun28** [comment]
好的好的～～
