### ISSUE TITLE
csv导出纯数字订单号变科学计数法

### ISSUE THREAD

**Issue by kiritokun07** [looly/hutool#2477]
### 版本情况

JDK版本：   1.8 11
hutool版本： 5.8.4

### 问题描述

需要导出的list数据包含一个很长的订单号`2022072512345928259`（数据已脱敏）

```java
try (CsvWriter writer = CsvUtil.getWriter(xxx, CharsetUtil.CHARSET_GBK)) {
    writer.writeBeans(dataList);
}
```
打开csv，订单号变成科学计数法，且后4位变成0

easyexcel有注解`@NumberFormat`，不知道hutool有没有类似注解

只能暂且先这么处理了：
```
public String getOrderNo() {
    return "`" + orderNo;
}
```

**Comment by kiritokun07** [comment]
另外推荐`CsvWriter.writeBeans(Iterable<?> beans)`方法将`map = BeanUtil.beanToMap(bean);`移到`if (isFirst)`下一行

**Comment by kiritokun07** [comment]
这个问题是csv读取软件（office wps）的问题，按txt打开订单号是没有问题的

**Comment by CherryRum** [comment]
好的，那先关闭这个issues，您有问题随时打开

**Comment by kiritokun07** [comment]
还有一个问题，CsvReader读csv时（用`read(Reader reader, Class<T> clazz)`），如果碰到很长的纯数字，读取的String和写一样变成科学计数法应该怎么处理

**Comment by kiritokun07** [comment]
> 还有一个问题，CsvReader读csv时（用`read(Reader reader, Class<T> clazz)`），如果碰到很长的纯数字，读取的String和写一样变成科学计数法应该怎么处理
class里有这么个属性
```
@Alias("示例值")
private String example;
```

**Comment by ZZemptypoint** [comment]
> 还有一个问题，CsvReader读csv时（用`read(Reader reader, Class<T> clazz)`），如果碰到很长的纯数字，读取的String和写一样变成科学计数法应该怎么处理

无法复现你的问题, 请提供更多测试代码和csv文件

**Comment by kiritokun07** [comment]
我今天测了一下，没有复现出来，等下次出现时我再提个测试代码

**Comment by doublez-ten** [comment]
> 还有一个问题，CsvReader读csv时（用`read(Reader reader, Class<T> clazz)`），如果碰到很长的纯数字，读取的String和写一样变成科学计数法应该怎么处理

超过15位的数字的文本，在写入时，文本前面加`\t`
