### ISSUE TITLE
db.page分页查询结果没有页码和总数相关信息

### ISSUE THREAD

**Issue by nivalsoul** [looly/hutool#2478]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
PageResult<Entity> userinfo = db.page(Entity.create("userinfo"), new Page(0, 10));
```
我使用这段代码分页查询表的数据，返回的结果只有查询的list，并没有PageResult对象里面的page、pageSize、total等字段的信息。

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
是没有值么？

**Comment by nivalsoul** [comment]
> 

连字段都没有呢，你可以试下，谢谢！

**Comment by duhanmin** [comment]
我没有复现出来

**Comment by looly** [comment]
@nivalsoul 你连接的什么数据库呢？考虑是否数据库限制无法返回meta信息。

麻烦补充以下信息后打开issue：

1. 使用的数据库
2. 看下返回结果对象和日志，看是否meta信息获取错误，如数据库不支持获取。
