### ISSUE TITLE
【DB】模块别名问题

### ISSUE THREAD

**Issue by zj-dreamly** [looly/hutool#2480]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新版

是不是对表的别名和列的别名还不支持，我需要在 SQLbuilder#select 方法自行去构造，from 现在好像是只能设置表名，如果说要支持子查询的话，是不是还不行

**Comment by looly** [comment]
你指的是Bean中的别名么？你可以使用@Alias注解。
