### ISSUE TITLE
JSONUtil.toBean后丢失小数位

### ISSUE THREAD

**Issue by isinry** [looly/hutool#2481]
![image](https://user-images.githubusercontent.com/27894034/180909063-31f15e11-7873-4a8e-80af-690b06632d22.png)
==========
将json转换为bean后，其中的BIgDecimal值小数两位为0的情况下会丢失位数只保留一位

**Comment by duhanmin** [comment]
@isinry 没复现出
![image](https://user-images.githubusercontent.com/28647031/180911158-9013cca2-660c-4814-91d3-9147a48ddf5b.png)

**Comment by looly** [comment]
tobean之后数字会转换为BigDecimal对象，这个对象本身没有小数位数一说的，二十根据你toString后规定的，你可以设置格式，想保留几位都行。
