### ISSUE TITLE
ReUtil正则匹配卡死问题

### ISSUE THREAD

**Issue by sinbh** [looly/hutool#2482]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4

### 问题描述

1. 复现代码

```java
public static void main(String[] args) {
        List<String> list = FileUtil.readLines("D:\\msg.txt", "utf-8");
        String reg = "<img.*?data-src=\"(.*?)\".*?data-type=\"(.*?)\".*?>";
       //此处会一直等待下去
        List<String> imgList = ReUtil.findAll(reg, list.get(0), 1);
        System.out.println(imgList);
    }
```

这是一篇微信公众号文章的文本内容,内容里由于没有带data-type的图片,应该是匹配不到才对,但结果是会卡死,cpu上升,无运行结果.

文件:
[msg.txt](https://github.com/dromara/hutool/files/9186285/msg.txt)

**Comment by CherryRum** [comment]
请您搜索下`Catastrophic Backtracking`,您的正则应该发生了灾难性回溯
