### ISSUE TITLE
要是setting文件有idea的插件就好了

### ISSUE THREAD

**Issue by zhyusgethup** [looly/hutool#2487]
要是setting文件有idea的插件就好了

**Comment by duhanmin** [comment]
参考下
![Uploading image.png…]()

**Comment by duhanmin** [comment]
参考下
![image](https://user-images.githubusercontent.com/28647031/181522244-0cba5bbe-285a-4c9d-8457-7039dbc968b7.png)

**Comment by zhyusgethup** [comment]
就这样吧 谢谢

**Comment by looly** [comment]
其实setting本质和ini文件类似。
