### ISSUE TITLE
HexUtil工具类中decodeHex方法解析异常，出现乱码

### ISSUE THREAD

**Issue by AlanFin** [looly/hutool#2490]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.4

### 问题描述

1. 复现代码
```java
    //测试代码
public static void main(String[] args) {
        String hex = "7b202277696669223a205b202254502d4c"
            + "494e4b5f313032222c20225869616f6d695f38373"
            + "337222c2022636e65646765626f78222c2022e88a"
            + "99e89389e585b4e79b9b222c202250686f656e697"
            + "8222c20225869616f6d695f46314636222c2022e5"
            + "b08fe69fb3e9babbe5b086e5aea4222c2022d1eeb"
            + "ae3222c2022e68891e698afe58c85e5ad90222c20"
            + "224368696e614e65742d57447752222c20224d455"
            + "2435552595f46313238222c20224d455243555259"
            + "5f31313031222c20224161222c20224368696e614"
            + "e65742d6d72586b222c20225044434e222c202258"
            + "69616f6d695f326262626222205d207d";
        String decodedStr = HexUtil.decodeHexStr(hex);
        System.out.println(decodedStr);
}
//控制台输出
{ "wifi": [ "TP-LINK_102", "Xiaomi_8737", "cnedgebox", "芙蓉兴盛", "Phoenix", "Xiaomi_F1F6", "小柳麻将室", "���", "我是包子", "ChinaNet-WDwR", "MERCURY_F128", "MERCURY_1101", "Aa", "ChinaNet-mrXk", "PDCN", "Xiaomi_2bbbb" ] }
```
2. 问题
出现乱码现象，实际在网站上的结果是，以下结果是通过https://www.bejson.com/convert/ox2str/ 在线网站转译的结果
{ "wifi": [ "TP-LINK_102", "Xiaomi_8737", "cnedgebox", "芙蓉兴盛", "Phoenix", "Xiaomi_F1F6", "小柳麻将室", "Ѯ젢我是包子", "ChinaNet-WDwR", "MERCURY_F128", "MERCURY_1101", "Aa", "ChinaNet-mrXk", "PDCN", "Xiaomi_2bbbb" ] }
3. 图片展示
代码解析：
![image](https://user-images.githubusercontent.com/49778121/181455264-b2f74fa2-821d-4f92-be4e-994e631da15f.png)
网站解析：
![image](https://user-images.githubusercontent.com/49778121/181454914-323ed093-3daf-495b-9e8e-706f5d6bf2f4.png)

**Comment by duhanmin** [comment]
@AlanFin 提供下正确字符串

**Comment by looly** [comment]
我不知道你的hex字符串如何得出的，你可以试下。

通过你给的网站解码后的字符串，再编码为hex，和你提供的hex不同，所以怀疑是你的hex有问题。而这个在线工具可能做了一些容错。

欢迎讨论，有需要再打开issue。

**Comment by AlanFin** [comment]
16进制：
7b202277696669223a205b202254502d4c494e4b5f313032222c20225869616f6d695f38373337222c2022636e65646765626f78222c2022e88a99e89389e585b4e79b9b222c202250686f656e6978222c20225869616f6d695f46314636222c2022e5b08fe69fb3e9babbe5b086e5aea4222c2022d1eebae3222c2022e68891e698afe58c85e5ad90222c20224368696e614e65742d57447752222c20224d4552435552595f46313238222c20224d4552435552595f31313031222c20224161222c20224368696e614e65742d6d72586b222c20225044434e222c20225869616f6d695f326262626222205d207d
字符串：
{ "wifi": [ "TP-LINK_102", "Xiaomi_8737", "cnedgebox", "芙蓉兴盛", "Phoenix", "Xiaomi_F1F6", "小柳麻将室", "Ѯ젢我是包子", "ChinaNet-WDwR", "MERCURY_F128", "MERCURY_1101", "Aa", "ChinaNet-mrXk", "PDCN", "Xiaomi_2bbbb" ] }

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] HexUtil工具类中decodeHex方法解析异常，出现乱码 (Issue #2490)





 
@AlanFin 提供下正确字符串
