### ISSUE TITLE
字符串中包含<0x01> 导出到excel会变成？号

### ISSUE THREAD

**Issue by zhongliangjian** [looly/hutool#2494]
示例字符串：zYdsfsUnW23eb23423(空格部分就是0x01)
导出到excel后会变成zYdsfsU?nW23eb23423

**Comment by zhongliangjian** [comment]
![image](https://user-images.githubusercontent.com/11154633/181735174-2bf7053d-1ee8-43ff-a43e-00367a9e68aa.png)

**Comment by zhongliangjian** [comment]
![image](https://user-images.githubusercontent.com/11154633/181735357-1fb3c823-93a0-4cbe-a7e6-c3b6d0481073.png)

**Comment by looly** [comment]
这是个不可见字符啊，出来肯定是？

**Comment by zhongliangjian** [comment]
但是格式已经变了，重excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会

**Comment by zhongliangjian** [comment]
> 这是个不可见字符啊，出来肯定是？


但是格式已经变了，重excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会

**Comment by zhongliangjian** [comment]
> > 这是个不可见字符啊，出来肯定是？
> 
> 但是格式已经变了，重excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会

虽然不能正常显示出来，但是<0x01>格式按道理应该不会直接被去掉了

**Comment by zhongliangjian** [comment]
从excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会,现在是导出到excel，这个<0x01>字符丢失了 @looly
