### ISSUE TITLE
PNG压缩成JPG后，透明背景会被转成黑色

### ISSUE THREAD

**Issue by hiqiuyi** [looly/hutool#2497]
### 版本情况
JDK版本：    openjdk version "11.0.9.1" 2020-11-04
hutool版本： 5.8.5.M1

### 问题描述（包括截图）
1. 复现代码
![image](https://user-images.githubusercontent.com/28918611/182102870-be21177c-fc75-4a13-8c7b-22e7bea4489f.png)

将PNG图片转JPG图片时，PNG透明的背景会被转成黑色，如截图：
![lQLPJxaMyIDa5KDNAT7NAuGwItGD9l1rnlUC57m8PwCJAA_737_318](https://user-images.githubusercontent.com/28918611/182103206-912e35b5-40f6-4936-9c42-6667a6930201.png)

想到的两个方案：
方案1：
![image](https://user-images.githubusercontent.com/28918611/182103883-f0455d6a-63e7-48e7-a436-b44d8f170120.png)

方案2：
![image](https://user-images.githubusercontent.com/28918611/182104224-1de6c237-b218-4774-af39-74cc026aae50.png)

**Comment by looly** [comment]
jpg是必须要有背景色的，默认黑色。你可以自定义背景色为白色。
