### ISSUE TITLE
Hutool v5.7.18 的 HttpRequest 被发现忽略所有 TLS/SSL 证书验证。

### ISSUE THREAD

**Issue by ZhouYixun** [looly/hutool#2498]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5 hutool-http（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
> Hutool v5.7.18 的 HttpRequest 被发现忽略所有 TLS/SSL 证书验证。

sonatype扫描时报这个，问下是什么原因以及可以修复的吗？

**Comment by looly** [comment]
这个是有意这么设置的。

有用户提出某些网站的SSL信息有误，导致客户端请求报错，因此修改此规则。

作为Http客户端，不辨别服务端有效性和正确性。

如果需要验证，请自行调用setSSLSocketFactory完成验证。

**Comment by ZhouYixun** [comment]
感谢回复
