### ISSUE TITLE
从excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会,现在是导出到excel，这个<0x01>字符丢失了 @looly

### ISSUE THREAD

**Issue by zhongliangjian** [looly/hutool#2499]
从excel中复制出来<0x01>已经变成了？号字符。导出到csv文件就不会,现在是导出到excel，这个<0x01>字符丢失了 @looly

_Originally posted by @zhongliangjian in https://github.com/dromara/hutool/issues/2494#issuecomment-1200588666_

**Comment by looly** [comment]
CSV是纯文本肯定是保留的。

至于POI导出为何丢失，我也没有找到具体原因（难道写出时过滤了？）

你可以用原生POI试下。

**Comment by zhongliangjian** [comment]
> CSV是纯文本肯定是保留的。
> 
> 至于POI导出为何丢失，我也没有找到具体原因（难道写出时过滤了？）
> 
> 你可以用原生POI试下。

我试了原生poi的和easyexcel都是会丢失
