### ISSUE TITLE
setting中有没有密码加密功能

### ISSUE THREAD

**Issue by penguin290** [looly/hutool#25]
如果没有的话可不可以只能加关键信息加密功能

**Comment by looly** [comment]
配置文件中对民问密码加密这个问题还没有思考过。可否提供思路？比如使用base64？

**Comment by penguin290** [comment]
我是咸鱼，这个真的没有思路。这个想法我是在NutzWK中看到的，但是他那里是用durid的生成加密密码及公钥后自己放到配置文件里，我觉得完全可以在第一次加载时读取配置文件pwd的值加密并做出标记，根据标记来判断是否是已加密的密码。我接触的东西很少，只是一点不成熟的建议

**Comment by looly** [comment]
恩。这块我会暂时保留。我想想怎么整。如果有其它思路欢迎提供。

**Comment by zxniuniu** [comment]
考虑使用jasypt加密，解密？感觉在SpringBoot中很方便，直接引用，密码采用：ENC(加密后的密码即可)，非常方便，不知道Hutool中能否提供呢，感觉密码不加密不安全啊。

**Comment by looly** [comment]
那密码保存在哪里呢？

**Comment by justinyx** [comment]
Jasypt 是一个 Java 库，它允许应用程序开发者轻松地添加基本的加密功能到他们的项目中。使用 Jasypt 进行加密通常涉及对敏感数据进行加密处理，以保护这些信息不被未授权访问。

关于密码（通常指用于加密解密过程中的密钥或口令）的保存途径，有几种常见的方法：

环境变量：
密码可以存储在环境变量中，这样可以避免直接在代码或者配置文件中硬编码密码。
应用程序启动时从环境变量加载密码。
配置文件：
在一些情况下，可能会将密码存储在一个外部的配置文件中，并且这个文件不在版本控制系统中。
需要确保配置文件的安全性，例如通过操作系统权限来限制对文件的访问。
密钥管理系统 (KMS)：
使用第三方的服务如 AWS KMS, Google Cloud KMS 或 Azure Key Vault 来管理密码。
这些服务提供了安全的密码管理解决方案，并且通常具有良好的 API 支持。
手动输入：
在某些场景下，可以让用户在应用启动或者需要的时候手动输入密码。
这种方式适合于那些不需要频繁使用密码的应用程序。
数据库：
将密码存储在数据库中，但是这种方式需要对密码进行额外的保护措施，比如使用更强大的加密算法来保护存储在数据库中的密码。
硬件安全模块 (HSM)：
对于极其敏感的数据，可能需要使用 HSM 来存储密码，这种设备提供了一个物理上隔离的环境来处理加密事务。
