### ISSUE TITLE
SM2秘钥对使用的曲线为prime256v1

### ISSUE THREAD

**Issue by Gsealy** [looly/hutool#250]
您好，
SM2秘钥对使用的曲线不是`sm2p256v1`
pull request：#249

**Comment by looly** [comment]
已接收。感谢。

**Comment by k4n5ha0** [comment]
sm2p256v1 请问是否有对应的javascript加密代码，小弟我不太懂js。。。自己捣鼓到现在没有折腾出来。。。。

**Comment by Gsealy** [comment]
@chaojidachanmao
js我也不懂，但是有几个网站您可以看看
[JavaScript实现SM2算法加解密](http://www.jonllen.com/jonllen/js/178.aspx)
[JS版SM2国密算法的签名验证](http://www.jonllen.com/jonllen/js/175.aspx)
[SM2签名验签网址](http://www.jonllen.com/upload/jonllen/case/jsrsasign-master/sample-sm2.html)
您可以直接下他的js研究下

**Comment by k4n5ha0** [comment]
> @chaojidachanmao
> js我也不懂，但是有几个网站您可以看看
> [JavaScript实现SM2算法加解密](http://www.jonllen.com/jonllen/js/178.aspx)
> [JS版SM2国密算法的签名验证](http://www.jonllen.com/jonllen/js/175.aspx)
> [SM2签名验签网址](http://www.jonllen.com/upload/jonllen/case/jsrsasign-master/sample-sm2.html)
> 您可以直接下他的js研究下

这个地址我其实早就试过了，这个作者做的算法是有问题的，js自己加解密都很不稳定

**Comment by Gsealy** [comment]
抱歉哈，那我就不懂了，要是您有找到了也请@我下
要是换个思路做网页的控件呢？

**Comment by k4n5ha0** [comment]
我们公司确实也做不出来，找遍了网上实现的js，如果没有配套的js加解密，就很尴尬了
