### ISSUE TITLE
[建议] 可以维护一下excel 模块的文档嘛

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#2505]
[建议] 可以维护一下excel 模块的文档嘛
拿excel 读举例，一些设置别名方式没有介绍不知道有没有
![image](https://user-images.githubusercontent.com/20513615/182512984-c0d633e2-91c2-4aaa-ad18-e7b30a86b3ed.png)

**Comment by freshgeek** [comment]
https://hutool.cn/docs/#/poi/Excel%E8%AF%BB%E5%8F%96-ExcelReader

**Comment by looly** [comment]
新的文档在计划了：https://gitee.com/dromara/hutool/issues/I5CYN4
