### ISSUE TITLE
字符串解析成XML再传JSON时,遇到<![CDATA[问题

### ISSUE THREAD

**Issue by banyouu** [looly/hutool#2507]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.12

### 问题描述（包括截图）
一条XML数据

`	<MsgInfo>
		<Msg>
			<![CDATA[<msg><body><row action="select"><DIET>低盐饮食[嘱托]]><![CDATA[]</DIET></row></body></msg>]]>
		</Msg>
		<Msg>
			<![CDATA[<msg><body><row action="select"><DIET>流质饮食</DIET></row></body></msg>]]>
		</Msg>
	</MsgInfo>`

使用JSONObject jsonObject = JSONUtil.xmlToJson(s1);会解析成两条数据

![1659498357832](https://user-images.githubusercontent.com/38764151/182520079-a0e88168-9d83-4252-984c-153c49822ab7.png)

**Comment by looly** [comment]
这么解析没有问题啊，你XML格式化后：

```xml
<MsgInfo>
    <Msg>
        <![CDATA[<msg><body><row action="select"><DIET>低盐饮食[嘱托]]>
        <![CDATA[]</DIET></row></body></msg>]]>
    </Msg>
    <Msg>
        <![CDATA[<msg><body><row action="select"><DIET>流质饮食</DIET></row></body></msg>]]>
    </Msg>
</MsgInfo>
```

CDATA包裹的内容，第一个是：

```
<msg><body><row action="select"><DIET>低盐饮食[嘱托
```

第二个是：

```
]</DIET></row></body></msg>
```

因为都是取`<![CDATA[`和`]]>`之间的内容啊。
