### ISSUE TITLE
有没有解析url功能，想去除http url的后缀参数等信息，只保留url的主体

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#2509]
有没有解析url功能，想去除http url的后缀参数等信息，只保留url的主体
例如：https://blog.csdn.net/m0_47419053/article/details/126119390?app_version=5.7.0&code=app_1562916241&csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22126119390%22%2C%22source%22%3A%22m0_47419053%22%7D&ctrtid=2jVQy&uLinkId=usr1mkqgl919blen&utm_source=app
我只想要：
https://blog.csdn.net/m0_47419053/article/details/126119390

**Comment by freshgeek** [comment]
现有的方法也可以拼接出来，但是每次拼接都要重写，而且可能存在分隔符不一样，存在端口，IP 各种情况容易出错，所以我觉得应该是hutool的初衷

**Comment by freshgeek** [comment]
如果有的话，麻烦给个使用说明

**Comment by freshgeek** [comment]
如果没有我可以提供PR

**Comment by anaer** [comment]
直接根据问号位置截子串？

**Comment by freshgeek** [comment]
> 直接根据问号位置截子串？

也是一种方案，也是可以的，能把这个能力收拢到工具中规范化最好

**Comment by duhanmin** [comment]
参考UrlBuilder,可以拿到scheme/host/port/path/query/fragment

**Comment by duhanmin** [comment]
```java
	@Test
	public void isHttpTest(){
		UrlBuilder s = UrlBuilder.of("http://www.baidu.com/s?wd=hutool", CharsetUtil.CHARSET_UTF_8);
		System.out.println(s.getPath());
		System.out.println(s.getScheme());
		System.out.println(s.getHost());
		System.out.println(s.getPort());
		System.out.println(s.getQuery());
	}
```
