### ISSUE TITLE
请求在cn.hutool.http.HttpRequest中添加一个可以获取httpConnection的方法，或者能够对httpConnection进行差异性配置的方法

### ISSUE THREAD

**Issue by FansinZhao** [looly/hutool#251]
cn.hutool.http.HttpRequest中有一个私有的成员变量

   /** 连接对象 */
   private HttpConnection httpConnection

对于HttpConnection的配置是固定方式，连接超时和读取超时

	/**
	 * 设置连接和读取的超时时间
	 * 
	 * @param timeout 超时时间
	 * @return this
	 */
	public HttpConnection setConnectionAndReadTimeout(int timeout) {
		setConnectTimeout(timeout);
		setReadTimeout(timeout);

		return this;
	}

对于连接超时和读取超时无法单独设置。

希望将cn.hutool.http.HttpRequest的httpConnection开放出来，方便进行差异化配置。

**Comment by looly** [comment]
4.4.2增加此方法
