### ISSUE TITLE
【建议】新增银行卡号真伪校验

### ISSUE THREAD

**Issue by samho2008** [looly/hutool#2510]
LUHN规则说明：
如何判断一个银行卡号是否是真实有效的，还是胡乱编造的呢。

银联卡号Luhn校验规则：16位银行卡号（19位通用）

1.将未带校验位的 15（或18）位卡号从右依次编号 1 到 15（18），位于奇数位号上的数字乘以 2

2.将奇位乘积的个十位全部相加，再加上所有偶数位上的数字

3.将加法和加上校验位能被 10 整除

> 参考来源：[http://www.yinhangkahao.com/zhenjiayinhangka.html](http://www.yinhangkahao.com/zhenjiayinhangka.html)

**Comment by samho2008** [comment]
代码参考：[https://wenku.baidu.com/view/612b1355f142336c1eb91a37f111f18583d00c78.html](https://wenku.baidu.com/view/612b1355f142336c1eb91a37f111f18583d00c78.html)

**Comment by samho2008** [comment]
校验规则：https://blog.csdn.net/liyongzhi1992/article/details/82773993

**Comment by samho2008** [comment]
前端校验规则：https://www.cnblogs.com/zxd66666/p/13427095.html

**Comment by hb0730** [comment]
行业标准: JR/T 0008—2000
link: https://hbba.sacinfo.org.cn/attachment/onlineRead/dbcbceac0c2d234ff1132cc1989378dd412d03612769d38e7074e4744461c75f

**Comment by samho2008** [comment]
> 行业标准: JR/T 0008—2000 link: https://hbba.sacinfo.org.cn/attachment/onlineRead/dbcbceac0c2d234ff1132cc1989378dd412d03612769d38e7074e4744461c75f

感谢提供思路

**Comment by CherryRum** [comment]
考虑过，但是有些不支持，你又不能说是错的

**Comment by CherryRum** [comment]
https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?cardNo=XXX&cardBinCheck=true
建议使用这个查吧

**Comment by CherryRum** [comment]
这个就过不了Luhn
https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?_input_charset=utf-8&cardNo=6214832018989180&cardBinCheck=true

部分江苏银行 交通银行 中国工商部分的借记卡  等等等一堆奇葩

**Comment by samho2008** [comment]
> 考虑过，但是有些不支持，你又不能说是错的

是的，卡的类型太多了，有的不按照标准来，这个时候虽然卡是存在的，但是会识别成错的

**Comment by samho2008** [comment]
> https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?cardNo=XXX&cardBinCheck=true 建议使用这个查吧

感谢提供 API，我也看了下银联那边的 API，还是得靠这种 API 去调用验证稳妥一点。

**Comment by samho2008** [comment]
> 这个就过不了Luhn https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?_input_charset=utf-8&cardNo=6214832018989180&cardBinCheck=true
> 
> 部分江苏银行 交通银行 中国工商部分的借记卡 等等等一堆奇葩

哎，不统一真的麻烦

**Comment by looly** [comment]
嗯，那我关闭issue了。

**Comment by yangliu0109** [comment]
> > 考虑过，但是有些不支持，你又不能说是错的
> 
> 是的，卡的类型太多了，有的不按照标准来，这个时候虽然卡是存在的，但是会识别成错的

sssssssss
