### ISSUE TITLE
CSV文件比较大的时候CsvUtil进行解析，会不会出现内存溢出呢

### ISSUE THREAD

**Issue by Holinc19** [looly/hutool#2512]
### 版本情况

JDK版本：    opnjdk_8_201
hutool版本： 5.8.5

### 问题描述
CSV文件比较大的时候进行解析，会不会出现内存溢出呢

**Comment by looly** [comment]
如果你调用read()方法返回CsvData，肯定内存会爆。你可以使用`read(final CsvRowHandler rowHandler)`，通过CsvRowHandler按行处理即可。

**Comment by GankGintama** [comment]
你好 我使用CsvRowHandler还是出现了内存溢出的情况，版本是5.4.0
![image](https://user-images.githubusercontent.com/33503325/206138228-004cc0d7-0637-4d85-bf44-8788f529aac2.png)

**Comment by looly** [comment]
@GankGintama 当然了，你写出到StringBuilder，还是存在内存中，你要写出文件啊。

**Comment by looly** [comment]
见：https://github.com/dromara/hutool/issues/2783
