### ISSUE TITLE
hutool-db 操作sqlite，表字段有点号

### ISSUE THREAD

**Issue by wmq95** [looly/hutool#2514]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21

### 问题描述（包括截图）

1. 复现代码
 Db.use(sqLiteDataSource).insert(Entity.create("XXX").set(EscapeUtil.escape("WTUR.Other.Rg.S.WTName"), "value"));

执行的sql
 INSERT INTO [tendata] ([WTUR].[Other.Rg.S.WTName]) VALUES (?)
字段第一个点号被加上了[]

**Comment by looly** [comment]
确实有这个问题，稍后处理。

**Comment by looly** [comment]
严格来说这并不是问题，而是你的字段命名不应该带点。

举个例子，如果你多表关联查询，使用别名的时候就需要 `select b.WTUR.Other.Rg.S.WTName from XXX b`这样，很容易造成歧义。

如果你没法修改表字段，则给你的解决方案是：

```java
Db.use(sqLiteDataSource).setWrapper((Wrapper) null).insert(Entity.create("XXX").set(EscapeUtil.escape("WTUR.Other.Rg.S.WTName"), "value"));
```

也就是把字段、表名的自动wrap关闭，这样就要求你的表名称不能和系统关键字重合。
