### ISSUE TITLE
RandomUtil#randomString 入参length为负数时报错

### ISSUE THREAD

**Issue by Jack724** [looly/hutool#2515]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

cn.hutool.core.util.RandomUtil#randomString 入参length为负数时报错

源码

![image](https://user-images.githubusercontent.com/34974966/183012166-7322eea9-ad69-4525-a45f-7731c3674bef.png)

552行构造 StringBuilder 报错，554-556行设置length最小值没有意义

### 复现代码

```java
  cn.hutool.core.util.RandomUtil.randomString("123", -1)
```

**Comment by looly** [comment]
5.8.6修复此处，感谢。
