### ISSUE TITLE
网络请求工具类上传文件问题

### ISSUE THREAD

**Issue by MrYZhou** [looly/hutool#2516]
java 8
hutool5.7.22
我按照示例

```java
HashMap<String, Object> paramMap = new HashMap<>();
paramMap.put("file", FileUtil.file("D:\\face.jpg"));
paramMap.put("path",path );
```

就是有一个参数是文件，一个参数是额外的一些信息。上传失败了。

但是我使用apache的包：org.apache.httpcomponents:httpclient:4.5.12 (httpclient-4.5.12.jar)
操作就可以成功上传。核心代码如下

```java
 CloseableHttpClient httpclient = HttpClientBuilder.create().build();
        try {
            HttpPost httpPost = new HttpPost(url);
            FileBody file = new FileBody(fileData);
            MultipartEntityBuilder builder = MultipartEntityBuilder.create().addPart("file", file).setMode(HttpMultipartMode.BROWSER_COMPATIBLE);
            if (StringUtil.isNotBlank(filePath)) {
                builder.addTextBody("filePath", filePath, ContentType.create(ContentType.TEXT_PLAIN.getMimeType(), Charset.forName("UTF-8")));
            }
            HttpEntity reqEntity = builder.setCharset(Charset.forName("UTF-8")).build();
            httpPost.setEntity(reqEntity);
            HttpResponse response = httpclient.execute(httpPost);
```

我看到这种有些区别的是有个apache定义的filebody对象，而hutool的FileUtil.file("D:\\face.jpg")是返回 file 对象。

由于这个是第三方的api.我没办法知道对面接口怎么写的，但是明确的是对方是jsp的服务。我推测是不是用request接收导致有些不是
兼容的。现在很困扰。

**Comment by looly** [comment]
忙猜是HttpMultipartMode.BROWSER_COMPATIBLE这里模式问题。

**Comment by MrYZhou** [comment]
看了enum值，他说的意思是：browser-compatible mode, i.e. only write Content-Disposition; use content charset
这个工具类我觉得封装的非常好用，百分99.9不会出错。就这次这个出了问题，导致现在用hutool都有点心里负担，担心出错。

**Comment by looly** [comment]
@MrYZhou 我查阅下相关资料。

你的链接公开么？

**Comment by MrYZhou** [comment]
什么链接？

**Comment by looly** [comment]
就是上传的链接，我好测试。

**Comment by MrYZhou** [comment]
http://47.95.222.153:19090/fcscloud/file/upload
这个看了就删除了吧。

**Comment by MrYZhou** [comment]
我补充下，我这个记错了，对面是微服务的。但是不知道怎么接手的这个。hutool传不成功

**Comment by MrYZhou** [comment]
http://39.106.90.191:18080/uploadFile.do 这个接口，上面那个不是，看样子这个又是jsp的样子

**Comment by looly** [comment]
因为没有服务端的API，因此我这边无法测试。

看样子是multipart的模式兼容性问题导致的。

如果方便，可以抓包看下Http body的区别，再打开issue。这个暂时无法处理。
