### ISSUE TITLE
关于格式化日期字符串的建议

### ISSUE THREAD

**Issue by zichen1019** [looly/hutool#2517]
### 版本情况

JDK版本：    openjdk 1.8.0_162
hutool版本： 5.8.3

### 问题描述（包括截图）

1. 复现代码

```java
public static DateTime format(String dateStr) {
        return DateUtil.parseDateTime(dateStr);
    }

    public static void main(String[] args) {
        System.out.println(format("2022\"年\"1\"月\"1\"日\" 20:01:02"));
    }
```

2. 堆栈信息
![image](https://user-images.githubusercontent.com/18498131/183059388-d05a88dc-4f53-4a7e-80a0-4514e9bf088f.png)

3. 建议
只需在格式化之前将多余字符进行移除。
哦对，处理之前应该判断下是否为空，懒得写了，手动补充个注释吧。
```java
/**
     * 对日期进行格式化，继承自hutool的{@link DateUtil#parseDate(CharSequence)}{@link DateUtil#parseDateTime(CharSequence)}
     *
     * @param dateString   日期或时间字符串
     * @return  日期
     */
    public static DateTime parse(String dateString) {
        dateString = ReUtil.delAll("[^0-9年月日/.-: ]", dateString);
        if (dateString.length() > 10) {
            return DateUtil.parseDateTime(dateString);
        }
        return DateUtil.parseDate(dateString);
    }

    /**
     * 对日期进行格式化，继承自hutool的{@link DateUtil#parseDate(CharSequence)}
     * 
     * @param dateString   日期或时间字符串
     * @return  日期
     */
    public static DateTime parseDate(String dateString) {
        dateString = ReUtil.delAll("[^0-9年月日/.-: ]", dateString);
        return DateUtil.parseDate(dateString);
    }

    /**
     * 对日期时间进行格式化，继承自hutool的{@link DateUtil#parseDateTime(CharSequence)}
     *
     * @param dateString   日期或时间字符串
     * @return  日期时间
     */
    public static DateTime parseDateTime(String dateString) {
        dateString = ReUtil.delAll("[^0-9年月日/.-: ]", dateString);
        return DateUtil.parseDateTime(dateString);
    }

    public static void main(String[] args) {
        System.out.println(parse("2022\"年\"1\"月\"1\"日\""));
        System.out.println(parse("2022\"年\"1\"月\"1\"日\" 20:01:02"));
    }
```

**Comment by looly** [comment]
特殊字符需要手动去掉的。

你可以直接使用`DateUtil.parse`解析啊，不用手动判断。

**Comment by zichen1019** [comment]
> 特殊字符需要手动删除的。
> 
> 你可以使用`DateUtil.parse`解析啊，不用直接判断。

我提这个建议的意思就是希望DateUtil.parse等在解析前将多余字符删除，主要是这一句代码`dateString = ReUtil.delAll("[^0-9年月日/.-: ]", dateString);`，然后借此减少格式化失败的问题。

**Comment by looly** [comment]
@zichen1019 去掉肯定不对。

你可以看下`DateUtil.normalize`自动做了转换。`DateUtil.parse`方法是调用了这个方法的。

你提供的日期的问题在于有双引号，是不被处理的。

![image](https://user-images.githubusercontent.com/1432613/183245017-dc4a5742-f1f9-41dd-8b54-8099fa64dead.png)

**Comment by zichen1019** [comment]
> @zichen1019 去掉肯定不对。

不是说去掉“年月日”等之类的字符，是想将除正常在日期里面会出现的“多余字符”去掉。单纯个人想法。

**Comment by looly** [comment]
@zichen1019 我理解你的意思了，就是只保留日期需要的字符是吧。这种需求很容易误伤。

就说你这个正则，`2022-02-02T08:00:00`就会误伤去掉T，还有月的英文缩写。如`Tue Jun 4 16:25:15 +0800 2019`

**Comment by zichen1019** [comment]
> @zichen1019 我理解你的意思了，就是只保留日期需要的字符是吧。这种需求很容易误伤。
> 
> 就说你这个正则，`2022-02-02T08:00:00`就会误伤去掉T，还有月的英文缩写。如`Tue Jun 4 16:25:15 +0800 2019`

我写的那个只是举个例子，你可以将通过你的解析方式将可以处理的字符罗列一下，然后将多余的字符都移除掉。
我提的建议重点是思路，不是代码。 抱歉，没有从一开始就表述清楚。
