### ISSUE TITLE
RandomUtil.weightRandom() 使用无法获得预期结果

### ISSUE THREAD

**Issue by geshijie123** [looly/hutool#252]
**RandomUtil.weightRandom()  对多个权重为0的数组，会出现问题**

`package com.demo.cardjilv;

import cn.hutool.core.lang.WeightRandom;
import cn.hutool.core.util.RandomUtil;

public class RandomTest {

    public static void main(String[] args) {
//        int[] nums={1,1,1,1};
//        getCardNum(nums);
        int[] nums1={0,1,0,1};
        getCardNum(nums1);
    }
    private static void getCardNum(int[] num){

        WeightRandom.WeightObj[] ll= new WeightRandom.WeightObj[num.length];
        for (int i = 0; i < num.length; i++) {
            WeightRandom.WeightObj<String> a1=new WeightRandom.WeightObj<>(i+"卡",num[i]);
            ll[i]=a1;
        }
        WeightRandom stringWeightRandom = RandomUtil.weightRandom(ll);
        int i=0;
        int a11=0;
        int a22=0;
        int a33=0;
        int a44=0;
        while(i<100000){
            String next = (String)stringWeightRandom.next();
            if(next.equals("0卡")){
                a11++;
            }
            if(next.equals("1卡")){
                a22++;
            }
            if(next.equals("2卡")){
                a33++;
            }
            if(next.equals("3卡")){
                a44++;
            }
            i++;
        }

        System.out.println(a11);
        System.out.println(a22);
        System.out.println(a33);
        System.out.println(a44);
        System.out.println("-------");
    }
}
`
运行期望结果
0
50000
0
50000
-----

实际结果
0
0
50000+-
50000+-

**Comment by looly** [comment]
4.4.2修复此问题。
