### ISSUE TITLE
Q：上传下载时候带上请求头

### ISSUE THREAD

**Issue by qiuyueovo** [looly/hutool#2522]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.5

### 问题描述（包括截图）
使用hutool能否在上传下载时候带上请求头呢

**Comment by qiuyueovo** [comment]
目前我是直接使用HttpRequest，上传下载文件的。似乎是可行的

**Comment by looly** [comment]
可以使用HttpRequest构建请求。
