### ISSUE TITLE
有没有这样的工具类，xxx(str, wordLength, fillStr),这个方法的大意是:给定字符str，在str的每间隔wordLength的位置添加字符fillStr

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#2523]
xxx(str, wordLength, fillStr),这个方法的大意是:给定字符str，在str的每间隔wordLength的位置添加字符fillStr

例子:xxx("abcdefg", 3, "\rn") 返回的结果是"abc\rndef\rng"

**Comment by andglf** [comment]
这个估计是没有，不过可以通过这个方法实现：
`ArrayUtil.join(StrUtil.split("abcdefg", 3), "\r\n")`

**Comment by joey-happy** [comment]
> 这个估计是没有，不过可以通过这个方法实现： `ArrayUtil.join(StrUtil.split("abcdefg", 3), "\r\n")`

非常感谢您的回答
