### ISSUE TITLE
《hutool参考文档》RAS案例缺少标点符号

### ISSUE THREAD

**Issue by Bistutu** [looly/hutool#2525]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 《hutool参考文档》RAS案例缺少标点符号
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/91378285/183829254-76469a78-4b2b-4df3-828f-1aaa4bb42b0b.png">

**Comment by looly** [comment]
近期修改文档，感谢。
