### ISSUE TITLE
5.1.0版本之后数据库查询方法返回的字段会把驼峰命名的改成小写

### ISSUE THREAD

**Issue by Zyanbo** [looly/hutool#2526]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.1.0以后到最新版本

### 问题描述（包括截图）

数据库查询方法返回的字段会把驼峰命名的改成小写

![image](https://user-images.githubusercontent.com/20349639/183886226-b63b5af8-1a92-48d3-b5d8-eaa01eb53528.png)
![image](https://user-images.githubusercontent.com/20349639/183886980-da9ec10b-5511-4a2e-8bed-8cd14519e581.png)

**Comment by looly** [comment]
这是忽略大小写导致的。可以调用`DbUtil.setCaseInsensitiveGlobal(false)`关闭即可。
