### ISSUE TITLE
JSONUtil.toJsonStr(Object obj) 缺少非空判断，容易引发nullpointexception

### ISSUE THREAD

**Issue by xiehong0114** [looly/hutool#253]
/**
	 * 转换为JSON字符串
	 * 
	 * @param obj 被转为JSON的对象
	 * @return JSON字符串
	 */
	public static String toJsonStr(Object obj) {
		if (obj instanceof String) {
			return (String) obj;
		}
		return toJsonStr(parse(obj));
	}

obj  为null

**Comment by looly** [comment]
4.4.2增加检查。感谢。
