### ISSUE TITLE
模板引擎封装-TemplateUtil是否支持Thymeleaf的Java8TimeDialect

### ISSUE THREAD

**Issue by liunancun** [looly/hutool#2530]
Thymeleaf引擎默认不支持JDK8时间格式化，需要额外引入thymeleaf-extras-java8time

参考：
https://github.com/thymeleaf/thymeleaf-extras-java8time

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.addDialect(new Java8TimeDialect());

使用TemplateUtil不支持此定制，是否可以考虑支持

**Comment by looly** [comment]
从5.8.7开始，可以：

```java
final TemplateEngine engine = TemplateUtil.createEngine();
if(engine instanceof ThymeleafEngine){
	final org.thymeleaf.TemplateEngine rawEngine = ((ThymeleafEngine) engine).getRawEngine();
	rawEngine.addDialect(new Java8TimeDialect());
}
```
