### ISSUE TITLE
Request编码问题

### ISSUE THREAD

**Issue by kings1990** [looly/hutool#2531]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 问题描述（包括截图）

1. 复现代码
```
这个地址http://localhost:8081/base/test1原样返回传入的str


Map<String,String> map = new HashMap<>();
        map.put("str","+123");
        
        String queryParam = Joiner.on("&")
                .useForNull("")
                .withKeyValueSeparator("=")
                .join(map);//返回str=+123
        
        HttpRequest request = HttpUtil.createGet("http://localhost:8081/base/test1");
        request.setUrl("http://localhost:8081/base/test1" + "?" + queryParam);
        HttpResponse execute = request.execute();
        System.out.println(execute.body());
```

几个问题如果执行了*request.setUrl*,不管str传+123还是%2B123响应都会把+号干掉

换个方式写
```
Map<String,String> map = new HashMap<>();
        map.put("str","+123");

        String queryParam = Joiner.on("&")
                .useForNull("")
                .withKeyValueSeparator("=")
                .join(map);//返回str=+123
        
        HttpRequest request = HttpUtil.createGet("http://localhost:8081/base/test1?"+queryParam);
        HttpResponse execute = request.execute();
        System.out.println(execute.body());
```
这样子会把+去掉，只有str传%2B123才能在响应中返回+123

**Comment by looly** [comment]
嗯……我为啥测试都可以正常：

1. 使用setUrl：

![image](https://user-images.githubusercontent.com/1432613/190882874-801c0d2f-b6b3-4612-ab9e-2973111b3449.png)

2. 直接createGet：

![image](https://user-images.githubusercontent.com/1432613/190882886-093dac11-3261-458e-85db-b1e784e1555a.png)

我用的是Hutool的SimpleServer。你的测试服务端用的tomcat么？

**Comment by looly** [comment]
Hutool的HttpRequest中的URL编码解码由`UrlBuilder`完成，规则如下；

```java
// 根据RFC3986规范，在URL中，"+"是安全字符，所以不会解码也不会编码
UrlBuilder builder = UrlBuilder.ofHttp("https://hutool.cn/a=+");
Assert.assertEquals("https://hutool.cn/a=+", builder.toString());

// 由于+为安全字符无需编码，ofHttp方法会把%2B解码为+，但是编码的时候不会编码
builder = UrlBuilder.ofHttp("https://hutool.cn/a=%2B");
Assert.assertEquals("https://hutool.cn/a=+", builder.toString());

// 如果你不想解码%2B，则charset传null表示不做解码，编码时候也被忽略
builder = UrlBuilder.ofHttp("https://hutool.cn/a=%2B", null);
Assert.assertEquals("https://hutool.cn/a=%2B", builder.toString());
```

用户传入URL字符串的时候，要考虑三种情况：

1. URL没有编码，需要编码
2. URL已经编码，不需要编码
3. URL中混杂着已经编码和没有编码的字符，那未编码的需要编码，编码后的需要保留

`URLBuilder`处理的方式是：

1.  `UrlBuilder.of`方法将已经编码的全部还原
2.  `UrlBuilder.build`方法将还原的和未编码的全部编码

通过这两个步骤，即可处理以上三种情况。

但是问题来了：如果用户需要将不需要编码的字符强制编码该如何（如上例子中提到的`%2B`），`%2B`本身是`+`的编码形式，但是URL中不需要编码，`UrlBuilder`会”自作聪明“的将`%2B`还原为`+`，这就与用户的需求不一致了。

这个时候只能将`charset`参数强制置为`null`来关闭自动解码编码行为，这样输入和输出就是原样行为。
