### ISSUE TITLE
能否提供一套关于假期的接口

### ISSUE THREAD

**Issue by askdpe** [looly/hutool#2532]
你好，我发现很多工具都没有对假期的维护，每次都需要自己来实现一些功能，希望hutool团队能够帮忙封装一下
下面是我的小想法
提供方法让用户自己维护两个列表
//假期
 List<String> holiday =new ArrayList<>();
//调休的日期
List<String> extraWorkDay =new ArrayList<>();
然后根据这些日期增加一些对假期的操作，比如当月实际工作天数，当前日期是否放假等

**Comment by CherryRum** [comment]
其实，你有这俩列表的话，后面的都不是很难的。用户可能很难去找当前的假期。
这个需求，可能会在6.0上新增，看到时候实现方法吧。

**Comment by looly** [comment]
这个不考虑了，需要自行封装维护假期管理。
