### ISSUE TITLE
hutool ExcelWriter 导出图片

### ISSUE THREAD

**Issue by dajitui** [looly/hutool#2534]
### 问题描述（包括截图）

我需要实现ExcelWriter 导出excel 嵌入图片的需求，发现ExcelWriter里面没有方法可以实现这个功能，只能另外处理这个逻辑，希望工具可以实现这个功能。
```
Drawing<?> drawingPatriarch = sheet.createDrawingPatriarch();
```

**Comment by looly** [comment]
这块没有封装，暂不考虑，考虑使用POI原生方法。
