### ISSUE TITLE
是否可以提供XML压缩工具方法

### ISSUE THREAD

**Issue by liunancun** [looly/hutool#2535]
压缩前：

<users>

	<user>
		<name>zhangsan</name>
		<age>18</age>
	</user>
	<user>
		<name>lisi</name>
		<age>20</age>
	</user>
</users>

压缩后：
`<users><user><name>zhangsan</name><age>18</age></user><user><name>lisi</name><age>20</age></user></users>`

**Comment by looly** [comment]
XmlUtil.toStr(XmlUtil.(parseXml));
