### ISSUE TITLE
TreeUtil.build 

### ISSUE THREAD

**Issue by QinHongZhe** [looly/hutool#2538]
### 版本情况

JDK版本：    jdk11.0.13
hutool版本： 5.8.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

此方法泛型传入Object 不能正确构建树

![image](https://user-images.githubusercontent.com/25653313/184787759-486c0c19-9b2f-40e7-99af-5cc4187d0bff.png)

1. 复现代码

```java
package com.gientech.ivics.rest.dept.controller;

import cn.hutool.core.date.DateUtil;
import cn.hutool.core.lang.tree.Tree;
import cn.hutool.core.lang.tree.TreeNodeConfig;
import cn.hutool.core.lang.tree.TreeUtil;

import java.util.ArrayList;
import java.util.List;

public class TestMain {

    public static void main(String[] args) {
        Test test1 = new Test();
        test1.setId(1);
        test1.setParentId(0);
        test1.setName("1");
        Test test2 = new Test();
        test2.setId(2);
        test2.setParentId(1);
        test2.setName("1");

        List<Test> list = new ArrayList<>();

        list.add(test1);
        list.add(test2);
        // 配置
        TreeNodeConfig treeNodeConfig = new TreeNodeConfig();
        // 自定义属性名 都要默认值的
        treeNodeConfig.setIdKey("id");
        treeNodeConfig.setDeep(Integer.MAX_VALUE);
        treeNodeConfig.setParentIdKey("parentId");

        // 转换器
        List<Tree<Object>> treeNodes = TreeUtil.build(list, "0",
                treeNodeConfig,
                (treeNode, tree) -> {
                    tree.setId(treeNode.getId());
                    tree.setParentId(treeNode.getParentId());
                });
        System.out.println(treeNodes);
    }
}


package com.gientech.ivics.rest.dept.controller;

public class Test {

    private long id;

    private long parentId;

    private String name;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getParentId() {
        return parentId;
    }

    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by duhanmin** [comment]
Test 中node为long, rootId类型不对,用0L

**Comment by QinHongZhe** [comment]
![image](https://user-images.githubusercontent.com/25653313/184795119-fa57c4eb-6910-4947-9ff2-77d19f3db2de.png)
![image](https://user-images.githubusercontent.com/25653313/184795131-a65c3aae-4c31-44b9-91f8-75a11eb4cd04.png)

已经改为 0L  并且赋值的时候也该成了 L  但是，还是build 出来是 null

**Comment by duhanmin** [comment]
> ![image](https://user-images.githubusercontent.com/25653313/184795119-fa57c4eb-6910-4947-9ff2-77d19f3db2de.png) ![image](https://user-images.githubusercontent.com/25653313/184795131-a65c3aae-4c31-44b9-91f8-75a11eb4cd04.png)
> 
> 已经改为 0L 并且赋值的时候也该成了 L 但是，还是build 出来是 null

```
		List<Tree<Object>> treeNodes = TreeUtil.build(list, 0L,
				treeNodeConfig,
				(treeNode, tree) -> {
					tree.setId(treeNode.getId());
					tree.setParentId(treeNode.getParentId());
					tree.setName(treeNode.getName());
					tree.setWeight(null);
				});
```

![image](https://user-images.githubusercontent.com/28647031/184796247-d1482c0a-1994-4153-93c3-9be595bcf0f2.png)

**Comment by QinHongZhe** [comment]
已成功构建出树结构，感谢。  但是，还是提一个小建议： 把类型校验加上，抛出个异常也行，要不真的是不知道为啥。

**Comment by duhanmin** [comment]
已经增加校验
```
			if (!rootId.getClass().equals(node.getId().getClass())) {
				throw new IllegalArgumentException("rootId type is node.getId().getClass()!");
			}
```

**Comment by baymax55** [comment]
> 已经增加校验
> 
> ```
> 			if (!rootId.getClass().equals(node.getId().getClass())) {
> 				throw new IllegalArgumentException("rootId type is node.getId().getClass()!");
> 			}
> ```

相似的问题, 在TreeBuilder中的构建树,遇到该参数校验失败:

可以帮忙分析下为什么string类型的id自动转为long了吗,
![image](https://github.com/dromara/hutool/assets/35788491/0612fa88-63ca-4581-8a3b-18c3c26b76d3)

**Comment by baymax55** [comment]
> > 已经增加校验
> > ```
> > 			if (!rootId.getClass().equals(node.getId().getClass())) {
> > 				throw new IllegalArgumentException("rootId type is node.getId().getClass()!");
> > 			}
> > ```
> 
> 相似的问题, 在TreeBuilder中的构建树,遇到该参数校验失败:
> 
> 可以帮忙分析下为什么string类型的id自动转为long了吗, ![image](https://user-images.githubusercontent.com/35788491/280585074-0612fa88-63ca-4581-8a3b-18c3c26b76d3.png)

@duhanmin @QinHongZhe @looly
