### ISSUE TITLE
采用hutool的JSONUtil对Boolean转换时，无法出来正确的结果

### ISSUE THREAD

**Issue by littlebeesvr** [looly/hutool#2544]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
采用hutool的JSONUtil对Boolean转换时，无法出来正确的结果

1. 复现代码

```java
    public static void main(String[] args) {
        Boolean bool = true;
        // hutool
        System.out.println(JSONUtil.toJsonStr(bool));
        // jackson
        System.out.println(JsonUtils.stringify(bool));
    }

运行结果：
{}
true
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
当然啦， 你一个boolean只是一个值，并不符合json规范。

类似fastjson会返回对应字符串值。
