### ISSUE TITLE
CharsetDetector 将UTF-8的文件识别为UTF-16BE

### ISSUE THREAD

**Issue by KOUymA** [looly/hutool#2547]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 问题描述（包括截图）

1. 复现代码
![image](https://user-images.githubusercontent.com/72074577/185350188-62698673-4f51-4a0b-bc3a-464a473c00ac.png)

通过CharsetDetector 识别txt文件的字符集来判断是否需要转换，所以识别错误导致后续转换出现乱码

3. 测试涉及到的文件（注意脱密）
[名著导读.txt](https://github.com/dromara/hutool/files/9371903/default.txt)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
CharsetDetector根据读取的bytes使用`CharsetDecoder`报错与否来判断编码，可能有错误这个难免。

建议不要依赖于这个判断编码。

这段文字稍后测试判断，可能是头部的字符问题。

**Comment by KOUymA** [comment]
> CharsetDetector根据读取的bytes使用`CharsetDecoder`报错与否来判断编码，可能有错误这个难免。
> 
> 建议不要依赖于这个判断编码。
> 
> 这段文字稍后测试判断，可能是头部的字符问题。

好的谢谢 想问下判断编码有什么可靠的方法吗？

**Comment by CherryRum** [comment]
> 

可靠如果代表100%，那现在来说不太可能的。

**Comment by looly** [comment]
@KOUymA 可以试下universalchardet库，也不是100%。

**Comment by looly** [comment]
@KOUymA  经过测试，是你读取的bytes数太少的原因，可以：

```java
final Charset detect = CharsetDetector.detect(IoUtil.DEFAULT_LARGE_BUFFER_SIZE, ResourceUtil.getStream("d:/test/default.txt"));
```

这样比较准确。

**Comment by looly** [comment]
从5.8.8开始，读取较多的bytes避免识别出错。
