### ISSUE TITLE
建议添加 LambdaExceptionUtil 

### ISSUE THREAD

**Issue by zhfkt** [looly/hutool#2549]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Feature request：

建议添加 LambdaExceptionUtil （源代码在 https://gist.github.com/jomoespe/ea5c21722b693c09c38bf6286226cd92 ） ，可以将 Lambda 中的CheckedException rethrow出来。相关问题在 https://stackoverflow.com/a/27644392/1237832 

我看到有个CheckedUtil - https://apidoc.gitee.com/dromara/hutool/cn/hutool/core/exceptions/CheckedUtil.html ，但是看起来好像没有rethrow函数，并且LambdaExceptionUtil 在调用unchecked的时候好像更加简洁，不用额外调用CheckedUtil 中的call函数得到结果。

**Comment by Createsequence** [comment]
大概看了一下，`LambdaExceptionUtil`  和 `CheckedUtil`  的功能是一样的，都是为了避免 `unchecked` 而不得不强制 `try-catch`，它们的区别主要在于：

`LambdaExceptionUtil` 的 `rethrow` 返回是 `JDK` 自带的函数式接口：

~~~java
public static <T, E extends Exception> Consumer<T> rethrowConsumer(Consumer_WithExceptions<T, E> consumer) {
    return t -> {
        try { consumer.accept(t); }
        catch (Exception exception) { throwAsUnchecked(exception); }
    };
}
~~~

而 `CheckedUtil`  返回是是 `Hutool` 提供的函数式接口：

~~~java
public static <R> Func0Rt<R> uncheck(final Func0<R> expression) {
    return uncheck(expression, RuntimeException::new);
}
~~~

所以导致了在 `Stream` 这种方法参数是 `JDK` 函数式接口的场景下，无法直接用类似 `map(CheckedUtil.uncheck(doSomething))` 的方法完成调用。

关于这点的话，大概有两种思路：

- 直接为`CheckedUtil`  补充返回 `JDK` 函数式接口的静态方法；
- 为返回的 `Hutool` 自定义函数式接口补充一个转成 `JDK` 函数默认方法，那样就可以写成类似 `map(CheckedUtils.uncheck(xxx).toJava())` 的样式；

我个人比较倾向于后者，毕竟前者需要调整API，不过具体怎么样还是得看作者的想法。

**Comment by looly** [comment]
这个工具现在这个状态的原因是，5.x中定义的函数不能很好的和jdk8提供的函数相契合导致的，6.x会重新规划函数，此issue暂时保留。

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/pulls/800

**Comment by zhfkt** [comment]
> 大概看了一下，`LambdaExceptionUtil` 和 `CheckedUtil` 的功能是一样的，都是为了避免 `unchecked` 而不得不强制 `try-catch`，它们的区别主要在于：
> 
> `LambdaExceptionUtil` 的 `rethrow` 返回是 `JDK` 自带的函数式接口：
> 
> ```java
> public static <T, E extends Exception> Consumer<T> rethrowConsumer(Consumer_WithExceptions<T, E> consumer) {
>     return t -> {
>         try { consumer.accept(t); }
>         catch (Exception exception) { throwAsUnchecked(exception); }
>     };
> }
> ```
> 
> 而 `CheckedUtil` 返回是是 `Hutool` 提供的函数式接口：
> 
> ```java
> public static <R> Func0Rt<R> uncheck(final Func0<R> expression) {
>     return uncheck(expression, RuntimeException::new);
> }
> ```
> 
> 所以导致了在 `Stream` 这种方法参数是 `JDK` 函数式接口的场景下，无法直接用类似 `map(CheckedUtil.uncheck(doSomething))` 的方法完成调用。
> 
> 关于这点的话，大概有两种思路：
> 
> * 直接为`CheckedUtil`  补充返回 `JDK` 函数式接口的静态方法；
> * 为返回的 `Hutool` 自定义函数式接口补充一个转成 `JDK` 函数默认方法，那样就可以写成类似 `map(CheckedUtils.uncheck(xxx).toJava())` 的样式；
> 
> 我个人比较倾向于后者，毕竟前者需要调整API，不过具体怎么样还是得看作者的想法。

不确定是否800pull支持了原生jdk lamdba的包裹异常，至少从pull的注释上来看是还没有支持
