### ISSUE TITLE
CharSequenceUtil中containsOnly存在问题

### ISSUE THREAD

**Issue by zclai163** [looly/hutool#2551]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
········/**
	 * 检查指定字符串中是否只包含给定的字符
	 *
	 * @param str       字符串
	 * @param testChars 检查的字符
	 * @return 字符串含有非检查的字符，返回false
	 * @since 4.4.1
	 */
	public static boolean containsOnly(CharSequence str, char... testChars) {
		if (false == isEmpty(str)) {
			int len = str.length();
			for (int i = 0; i < len; i++) {
				if (false == ArrayUtil.contains(testChars, str.charAt(i))) {
					return false;
				}
			}
		}
		return true;
	}
·······public static void main(String[] args) {
                 // 输出 true
                 // 给定字符串为空时，依旧返回包含给定字符
		System.out.println(containsOnly(null,'a'));
	}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Pacifica-Git** [comment]
拙见：这个方法的语义应该是判断给定字符序列 str 是否只包含给定字符数组 testChars 中的字符，如果是则返回 true，否则返回 false。那么存在一个逻辑上的问题就是您提到的这个问题，不含任何内容的空字符串，不管是 null 还是 ""，是否可以认为其只包含 testChars 中的字符，它不含任何字符，换个角度看，它也不包含任何不存在在 testChars 中的字符，那么从这个角度看，是符合方法的语义的，所以才返回了 true。与其说整个方法是在判断 str 中是否包含 testChars 中的字符，倒不如说是在于判断 str 中是否不包含 testChars 中的字符，如果确实不包含，就返回 true，剩下的不管 str 中包含什么字符甚至为空都不影响，因为那不是方法的重点。若有错误请指出

**Comment by Createsequence** [comment]
> 拙见：这个方法的语义应该是判断给定字符序列 str 是否只包含给定字符数组 testChars 中的字符，如果是则返回 true，否则返回 false。那么存在一个逻辑上的问题就是您提到的这个问题，不含任何内容的空字符串，不管是 null 还是 ""，是否可以认为其只包含 testChars 中的字符，它不含任何字符，换个角度看，它也不包含任何不存在在 testChars 中的字符，那么从这个角度看，是符合方法的语义的，所以才返回了 true。与其说整个方法是在判断 str 中是否包含 testChars 中的字符，倒不如说是在于判断 str 中是否不包含 testChars 中的字符，如果确实不包含，就返回 true，剩下的不管 str 中包含什么字符甚至为空都不影响，因为那不是方法的重点。若有错误请指出

空字符串我觉得这个方法的判断是没什么问题的，但是涉及到 `null` 的情况感觉就会有点歧义：

- `str` 是 `null`，`testChars` 也是 `null`，目前直接返回 `true`；
- `str` 是 `null`，`testChars` 不是 `null`，目前直接返回 `true`；
- `str` 不是 `null`，`testChars` 是 `null`，目前直接返回 `false`；

实际上所有涉及到 `A 在一组 B 中是否存在` 的方法都会有面临这种情况，语义问题暂时不谈，个人觉得，涉及到这种情况的方法是不是都需要额外补充注释，说明一下这三种情况下的返回值？

**Comment by looly** [comment]
针对null和''的问题确实存在理解歧义，这里我补充下注释。
