### ISSUE TITLE
JSON反序列化时，引用字段类型的自定义JsonDeserializer无效

### ISSUE THREAD

**Issue by kongxiangxin** [looly/hutool#2555]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.5

### 问题描述（包括截图）
为某个类型指定了自定义Serializer和Deserializer，如果该类型作为其他类型的字段，则自定义Deserializer的逻辑不会被调用，自定义Serializer的逻辑会被调用两次。

1. 复现代码

```java
@Data
public class MyType extends BaseObjectX {
    private String address;
}
@Data
public class SimpleObj {
    private MyType myType;
}
@Test
public void test() {
    JSONUtil.putSerializer(MyType.class, new MySerializer (););
    JSONUtil.putDeserializer(MyType.class, new MyDeserializer());
    SimpleObj simpleObj = new SimpleObj();
     MyType child = new MyType();
     simpleObj.setMyType(child);
    //MySerializer会被调用两次
     String json = JSONUtil.toJsonStr(simpleObj);

    //MyDeserializer不会被调用
     SimpleObj simpleObj2 = JSONUtil.toBean(json, SimpleObj.class);
    ...     
}
```

**Comment by looly** [comment]
确认bug。

5.8.6修复此问题！感谢！

**Comment by zhangqinghua2015** [comment]
看到5.8.6之前新增了BeanConverterForJSON这个类，然后又删除了，但是是为什么呢？
但是ConverterRegistry 中这段代码还在，项目在用到JSONUtil.toList()方法时，会每次都去加载BeanConverterForJSON，实际上并不会加载到，有性能问题，会导致应用线程都阻塞在类加载这里

![1671260063084](https://user-images.githubusercontent.com/15626167/208229706-91ecbbf2-f93c-425c-a2b0-c8ee0e351004.png)

![1671259994421](https://user-images.githubusercontent.com/15626167/208229650-d2fd5061-2343-4a1d-87e7-beeaa0590baa.png)

![1671259917029](https://user-images.githubusercontent.com/15626167/208229632-120c888d-e740-4795-98fe-8ea2b66fb26d.png)

**Comment by looly** [comment]
@zhangqinghua2015 这个稍后我看下会在：https://github.com/dromara/hutool/issues/2812 回复你。
