### ISSUE TITLE
5.6.4tag缺失问题

### ISSUE THREAD

**Issue by CChengjie** [looly/hutool#2556]
我们发现了5.6.4版本在maven中发布了，但是github中并没有相应的tag; 
1) 请问tag缺失的原因是什么？（发现有相关版本发布的commit message）
    a、该版本存在代码问题，如存在漏洞、兼容性问题、界面方面问题等。
    b、该版本出现功能性问题，如功能规划不合理、基础功能不能使用等。
    c、忘记打tag
    d、不在意或者嫌操作麻烦
    e、其他原因，_

2） 针对该问题，我们提出了一个方法，能够找到version 可能对应的真实commit， 以帮助开发者快速定位问题代码，完成漏洞修复。  以下是我们方法给出的可能的真实commits，请您帮忙确认下是否包含了真实的commit，如果不是，应该是哪一个？

['b14bbffa32c166a42685957b8e1d0e4fce7e0d0b', 'fda3fa2e61f03eea77917d83e26dd002e54669e6', '4f634c384d26d83e1083eef8b138c5c4d320520d']

**Comment by looly** [comment]
不是每个版本都打tag的，打tag这个习惯在最新的几个版本中才有。

**Comment by CChengjie** [comment]
> 

好的！非常感谢您的回复
