### ISSUE TITLE
JSONUtil.toJsonStr() 忽略空值null 异常

### ISSUE THREAD

**Issue by wwyynnn** [looly/hutool#2557]
### 版本情况

JDK版本：    openjdk 1.8.0_302
hutool版本： 5.8.5

### 问题描述（包括截图）
Hi @looly ，JSONUtil.toJsonStr() 方法在面对 value 为 null 的字段时会自动过滤处理，不在 string 中展示，最新版本 5.8.5 下进行测试。举例如下：
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/29294095/186066140-1553aea6-c7d3-4d0f-ae47-a16e92cf0e68.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/29294095/186066185-bc77ef98-096c-423f-af71-37b5d27620b6.png">

请问
- JSONUtil.toJsonStr() 方法不支持对 null 值的保留吗？
- 是否可以像 `public static JSONArray parseArray(Object arrayOrCollection, boolean ignoreNullValue) ` 方法一样，给出一个带有开关，允许配置是否忽略 null 值的 toJsonStr() 方法？

### 复现代码

```java
class Entity{
        private Long id;
        private String applyNo;
        private String sourceSystem;
        private String projectCode;
    }
@Test
    public void testHutoolJsonUitl(){

        Entity e1 = new Entity();
        e1.setApplyNo("an1");
        e1.setProjectCode("pc1");
        System.out.println(e1); // 输出为 testString.Entity(id=null, applyNo=an1, sourceSystem=null, projectCode=pc1)

        // 当 hutool 版本为 5.8.5
        System.out.println("hutool version = 5.8.5 -------------------------------------");
        System.out.println(JSONUtil.toJsonStr(e1)); // 输出结果为：  {"projectCode":"pc1","applyNo":"an1"}
    }
```

**Comment by duhanmin** [comment]
![image](https://user-images.githubusercontent.com/28647031/186086942-f823d0f1-e0e2-41a8-afe0-aa65bc773352.png)

**Comment by wwyynnn** [comment]
> 
想请教下 JSONConfig 中 ignoreNullValue 默认设置为 true 的考量是什么？完全展现输入结果（null 也展示）比较合理吧？
<img width="737" alt="image" src="https://user-images.githubusercontent.com/29294095/186365569-e77d9ec6-8564-424b-948b-a1c2476bfcc0.png">

**Comment by wwyynnn** [comment]
> ![图片](https://user-images.githubusercontent.com/28647031/186086942-f823d0f1-e0e2-41a8-afe0-aa65bc773352.png)

**Comment by wwyynnn** [comment]
> ![图片](https://user-images.githubusercontent.com/28647031/186086942-f823d0f1-e0e2-41a8-afe0-aa65bc773352.png)

想请教下 JSONConfig 中的 ignoreNullValue 默认设置为 true 的考量展示是什么输入结果（null 也）比较合理吧？
<img width="733" alt="image" src="https://user-images.githubusercontent.com/29294095/186365996-7a76a491-19e5-4381-a404-2515e18e166a.png">

**Comment by looly** [comment]
@wwyynnn 长度考虑。考虑大部分情况下null的字段没有意义，而且占用长度。在API调用时，减少请求体和响应体的体积。
