### ISSUE TITLE
mysql-connector 8.0.18+mybatis+cn.hutool.core.date.DateTime 兼容性问题

### ISSUE THREAD

**Issue by hcxxiaomo** [looly/hutool#2558]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8
mybatis版本：3.2.7
mysql版本：5.7
mysql-connector版本： 8.0.18

### 问题描述（包括截图）

1. 复现代码

```java
TaskExample taskExample = new TaskExample();
taskExample.createCriteria().andCreateTimeGreaterThan(cn.hutool.core.date.DateUtil.yesterday());
taskMapper.selectByExample(taskExample);
```
dba抓到的慢sql，耗时7、8秒左右

3. 测试涉及到的文件
![微信图片_20220823233147](https://user-images.githubusercontent.com/4076523/186202003-fc3e09e3-21e2-4c88-b996-c82fecd7aa7a.jpg)

后面改成 java.util.Date()，sql就恢复了，耗时10ms左右

**Comment by looly** [comment]
DateTime只是重写了toString方法而已。

如果碰到兼容性问题，可以调用`toJdkDate`方法转换为jdk的date。
