### ISSUE TITLE
FileUtil.getAbsolutePath导致的歧义

### ISSUE THREAD

**Issue by baichangda** [looly/hutool#2559]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.5

### 问题描述（包括截图）

1. 复现代码

FileUtil.writeUtf8Lines(Arrays.asList("1","2"),"a.txt");
太容易产生歧义了
明明是准备写入在项目根目录下面、结果看源代码才知道、写入到了classpath
如下图是 FileUtil.getAbsolutePath方法导致的

![image](https://user-images.githubusercontent.com/24662536/186323016-eaf37980-12f4-4df9-9c63-14fb6cbf77fe.png)

**Comment by duhanmin** [comment]
写项目目录应该是用相对路径写 String path = FileUtil.getAbsolutePath("./");

**Comment by baichangda** [comment]
> 写项目目录应该是用相对路径写 String path = FileUtil.getAbsolutePath("./");
FileUtil.getAbsolutePath("a.txt")和FileUtil.getAbsolutePath("./a.txt") 没有区别、两者都是相对路径写法

![image](https://user-images.githubusercontent.com/24662536/186364567-f50e5d7f-2de9-4eb9-97fe-e2557565a44e.png)

**Comment by duhanmin** [comment]
idea里相对于你代码路径,服务器上是相对于jar路径

**Comment by duhanmin** [comment]
这样写
![image](https://user-images.githubusercontent.com/28647031/186370291-ae859953-8916-41dc-acb5-bf581c41d41c.png)

**Comment by looly** [comment]
hutool的相对绝对路径概念都是基于`classpath`的，这个和JDK有所不同。

因为在web项目中，项目目录这个概念很难找到对应的文件，尤其打包成jar之后。所以封装了相对classpath路径。

如果想找相对项目的路径，可以使用new File.
