### ISSUE TITLE
5.8.0+ json转换bean对多层嵌套的对象，解析不出来

### ISSUE THREAD

**Issue by IvesQing** [looly/hutool#2561]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 问题描述（包括截图）
使用xml转化json，然后再转成bean对象 ，从5.8.0+开始测试，发现多层嵌套的json解析有误，第二层的解析不出来（但是5.7.2可以）
![image](https://user-images.githubusercontent.com/26543986/186373631-027c75f9-02b3-4150-879f-b574704ef436.png)
![image](https://user-images.githubusercontent.com/26543986/186374002-22cd6ecb-9b5e-4d2f-8595-873b07297132.png)

1. 复现代码
```java
   String resu =
            "{\"svg\":{\"version\":1.1,\"id\":\"图层_1\",\"xmlns\":\"http://www.w3.org/2000/svg\",\"xmlns:xlink\":\"http://www.w3.org/1999/xlink\",\"x\":\"0px\",\"y\":\"0px\",\"viewBox\":\"0 0 8000 3000\",\"enable-background\":\"new 0 0 8000 3000\",\"xml:space\":\"preserve\",\"data-version\":1,\"g\":{\"id\":\"g0\",\"transform\":\"matrix(1, 0, 0, 1, 1000, 1500)\",\"data-area\":\"A\",\"data-pt\":\"C\",\"text\":{\"id\":\"总箱数\",\"transform\":\"matrix(0.65519 0 0 1 237.98067 16.95963)\",\"font-family\":\"'Arial-BoldMT','Arial Bold'\",\"font-size\":\"79.51235px\",\"data-fill\":\"0:0:0:100\",\"content\":210}}}}";
 SVGRootVO rootVO = JSONUtil.toBean(object1, SVGRootVO.class); 
```

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
麻烦提供下SVGRootVO结构我测试。

**Comment by looly** [comment]
请升级到5.8.6尝试，如果不行请提供`SVGRootVO`后再打开此issue。
