### ISSUE TITLE
单测能搞一搞么，很多UT执行不通过啊

### ISSUE THREAD

**Issue by jamesMuWB** [looly/hutool#2562]
如题

**Comment by CherryRum** [comment]
很多是指？

**Comment by CherryRum** [comment]
11和17因为模块化，和jdk删除了部分模块

**Comment by jamesMuWB** [comment]
hutool 5.8.5，MacOS intellj ideal  JDK1.8_102
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/102423/186562720-afb0d12a-6130-4b7b-9d8b-dce15cc9211c.png">

**Comment by CherryRum** [comment]
晚上我去看下faild的，ignored 的很多是需要自己建立环境的。

**Comment by jamesMuWB** [comment]
> 



> 晚上我去看下faild的，ignored 的很多是需要自己建立环境的。

需要自建环境的部分可以在readme里做个说明么，作为使用者，本地跑跑单测，覆盖率高的话，用起来也放心一些 😓

**Comment by VampireAchao** [comment]
收到！感谢反馈

**Comment by CherryRum** [comment]
> > 
> 
> > 晚上我去看下faild的，ignored 的很多是需要自己建立环境的。
> 
> 需要自建环境的部分可以在readme里做个说明么，作为使用者，本地跑跑单测，覆盖率高的话，用起来也放心一些 😓

我在windows下测试全部跑过了，mac下还没尝试

**Comment by looly** [comment]
没有mac，麻烦把测试失败的方法列一下~~

**Comment by looly** [comment]
@jamesMuWB 提交后麻烦重新开一下issue。
