### ISSUE TITLE
验证码在vertx框架中运行会弹出框架的Launcher窗口

### ISSUE THREAD

**Issue by 9iks** [looly/hutool#2563]
### 版本情况

JDK版本：    Corretto-11.0.15.9.1
hutool版本： 5.8.5（请确保最新尝试是否还有问题）
vertx版本：  4.3.3

### 问题描述（包括截图）

1. 复现代码

```java
LineCaptcha captcha = CaptchaUtil.createLineCaptcha(width, height);
captcha.write("a.png");
```

```bash
java -jar -Xmx1024M -Xms256M api-1.0.0-fat.jar --server.port=8080 
```
在vertx中，会弹出框架的Launcher窗口
<img width="92" alt="Launcher" src="https://user-images.githubusercontent.com/19774885/186572259-00333014-87ac-4b55-984b-ee3f6d099610.png">

**Comment by looly** [comment]
CaptchaUtil没有窗口相关方法，麻烦检查下你的代码。
