### ISSUE TITLE
 JSONUtil.toBean("{}", A.class),空json字符串转空bean报错

### ISSUE THREAD

**Issue by chengqigang** [looly/hutool#2564]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/29392211/186590178-3a560c93-b10f-41ca-8104-062f2a42b6a1.png)

1. 复现代码

```java
@Getter
@Setter
public class A implements Serializable {
  private static final long serialVersionUID = -5282562537774493119L;

  public static void main(String[] args) {
    String x = "{}";
    System.out.println(JSONUtil.toJsonStr(new A()));
    A a = JSONUtil.toBean(x, A.class);
  }
}
```

**Comment by 13906568663** [comment]
实力类 没有get set方法 是有问题的

**Comment by 13906568663** [comment]
它没法进行实例化操作

**Comment by 13906568663** [comment]
![image](https://user-images.githubusercontent.com/38032667/186614447-a4e81ff2-b523-42cb-a531-6901489eb72f.png)
源码里hasSetter方法

**Comment by looly** [comment]
原因确实如@13906568663 所说，没法判定为是一个bean，所以没法调用toBean转换。

可以使用`JSONConfig.setIgnoreError`避免此错误。

**Comment by looly** [comment]
5.8.30变更：

空对象转bean返回默认实例，而非null。
