### ISSUE TITLE
请问如何设置全局的日志等级？

### ISSUE THREAD

**Issue by glight2000** [looly/hutool#2565]
private static final Log log = LogFactory.get();
log.debug("无法输出日志");
log.info("可以输出日志");

请问如何设置全局的日志等级为ALL或者INFO呢。

**Comment by duhanmin** [comment]
通过日志框架配置

**Comment by VampireAchao** [comment]
Hutool-Log采用门面模式输出日志，类似slf4j但是更加优雅，既hutool会自动查找你引入的jar来判断转发到的日志库，也就是说如果你的项目中引入得有日志框架，则修改对应使用的日志框架等级即可。
如果未引入任何日志库，则检查ClassPath下的logging.properties，存在则使用JdkLogFactory，使用`java.util.logging.Logger.getLogger`或者`java.util.logging.Logger.getAnonymousLogger`获取到的`java.util.logging.Logger`包含`setLevel`方法也许是个方案
```java
import java.util.logging.Level;
import java.util.logging.Logger;

// ...
Logger.getLogger(name).setLevel(Level.ALL);
```

否则使用`ConsoleLogFactory`，即默认会转发到`System.out.println` 🍻 
使用`cn.hutool.log.dialect.console.ConsoleLog#setLevel`试试

```java
import cn.hutool.log.dialect.console.ConsoleLog;

// ...
ConsoleLog.setLevel(Level.ALL);
```

参考：[疑惑解答](https://www.hutool.cn/docs/#/log/%E7%96%91%E6%83%91%E8%A7%A3%E7%AD%94)

> Hutool默认会使用JDK Logging做为其日志实现。出现这句话的意思是你没有在你的ClassPath下放logging.properties（JDK Logging的配置文件），系统默认默认读取JDK目录下的默认配置文件。你可以考虑在ClassPath下放一个logging.properties（就是src/main/resources）下。

配置文件模板见：https://gitee.com/dromara/hutool/blob/v5-master/hutool-log/src/test/resources/logging.properties

其它日志框架的配置文件模板见：https://gitee.com/dromara/hutool/tree/v5-master/hutool-log/src/test/resources

注意 在新版的Hutool中会自动检测logging.properties存在与否，如果不存在这个配置文件，将跳过JDK-Logging从而使用Console-log（命令行打印日志）


欢迎补充
