### ISSUE TITLE
JschSessionPool默认池管理缓存建议更换

### ISSUE THREAD

**Issue by molagaz** [looly/hutool#2568]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.7.5

### 问题描述（包括截图）

1. 背景
目前使用了JschUtil.getSession方式获取session会话；
跟踪代码后可知，最终JschSessionPool托管了session会话的缓存，但是目前默认的cache使用的是hutool内的SimpleCache;
执行机与目标机之间可能存在较为复杂的网络，这会导致cache中的session实际上可能早已失效；
最终导致我在调用exec执行命令时，出现下述问题；

2. 堆栈信息
cn.hutool.extra.ssh.JschRuntimeException: JSchException: channel is not opened.
        at cn.hutool.extra.ssh.JschUtil.exec(JschUtil.java:439)
        at cn.hutool.extra.ssh.JschUtil.exec(JschUtil.java:407)
        at com.xxxxx.build.task.AutoDeployTask.run(AutoDeployTask.java:107)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

3.最后
  如果想保持session的复用，期望能够替换默认的cache实现或者补充一些会话有效性的校验；
  或者无需cache

**Comment by looly** [comment]
作为替代，可以使用`JschUtil.createSession`自行管理Session。

在5.8.x中，SimpleCache增加了验证sesion有效性的函数:

![image](https://user-images.githubusercontent.com/1432613/186852932-9c35b5a3-8588-45b6-8deb-742f922cf6d3.png)


看是否可以避免一些问题。

**Comment by molagaz** [comment]
> 作为替代，可以使用`JschUtil.createSession`自行管理Session。
> 
> 在5.8.x中，SimpleCache增加了验证sesion有效性的函数:
> 
> ![image](https://user-images.githubusercontent.com/1432613/186852932-9c35b5a3-8588-45b6-8deb-742f922cf6d3.png)
> 
> 看是否可以避免一些问题。


自行管理ok
另外补充一下，实际上造成channel is not opened的代码跟踪后发现是检查的receipent标识，不确定5.8.x升级后isConnneted是否有效

**Comment by looly** [comment]
@molagaz 其实我也不得而知，只是单纯信任Jsch库提供的这些方法有效。

**Comment by proluoo** [comment]
> > 作为替代，可以使用`JschUtil.createSession`自行管理Session。
> > 在5.8.x中，SimpleCache增加了验证sesion有效性的函数:
> > ![image](https://user-images.githubusercontent.com/1432613/186852932-9c35b5a3-8588-45b6-8deb-742f922cf6d3.png)
> > 看是否可以避免一些问题。
> 
> 自行管理ok 另外补充一下，实际上造成channel is not opened的代码跟踪后发现是检查的receipent标识，不确定5.8.x升级后isConnneted是否有效

无效

**Comment by looly** [comment]
@proluoo jsch库的源码没有仔细看，不知道有没有其它办法判断连接有效性。欢迎提供思路。
