### ISSUE TITLE
HttpResponse中getCookieStr 缺少

### ISSUE THREAD

**Issue by zzc2001** [looly/hutool#2569]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
getCookieStr返回的不完整只获取一个，但实际是返回多个。
![image](https://user-images.githubusercontent.com/55677078/187055881-3f5533f4-6441-44ef-aff5-ce025d0d7c97.png)

![image](https://user-images.githubusercontent.com/55677078/187055860-248ba425-44cb-4b2a-a687-0a8311b33c31.png)

1. 复现代码
`HttpRequest.get("https://www.baidu.com").execute().getCookieStr()`

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个方法简单调用了`Set-Cookie`头信息。

如果不完整，考虑：

1. 多次调用时，前几次的cookie已经存入本地，因此第二次调用不再返回其他cookie。
2. 服务端返回只有这几个cookie值

如果没有解决，麻烦补充后再打开issue。
