### ISSUE TITLE
Hutool提供了专门的`Money`类用于货币处理:

### ISSUE THREAD

**Issue by Flappybay** [looly/hutool#2570]
有两个疑问，
疑问1： 分转元，这个传参方式有点复杂吧，还要把元和分拆开才行，按照你这个参数看，我都已经知道值了为什么还要调你的这个方法呢，不是多此一举吗，为什么不能直接传分返回元呢，比如：123456 ——>1234.56？
疑问2： 转元的时候为什么是doublerValue(), double不是容易丢失精度吗？
Hutool提供了专门的`Money`类用于货币处理:

```java
// 元转分
final Money money = new Money("1234.56");
money.getCent();

// 分转元
final Money money = new Money(1234, 56);
money.getAmount().doubleValue();
```

_Originally posted by @looly in https://github.com/dromara/hutool/issues/1796#issuecomment-908021011_

**Comment by handy-git** [comment]
1. 你可以使用
// 元转分
MathUtil.yuanToCent(1234.56)
// 分转元
MathUtil.centToYuan(123456);
2. 是BigDecimal转的double
