### ISSUE TITLE
Ftp及Sftp中exist方法在判断分割符结尾路径时存在问题

### ISSUE THREAD

**Issue by yebukong** [looly/hutool#2575]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在Ftp及Sftp中，cn.hutool.extra.ftp.AbstractFtp#exist方法判断逻辑为使用ls遍历父目录文件是否包含当前文件

```java
public boolean exist(String path) {
    // getName获取名称时会忽略结尾路径分割符
    final String fileName = FileUtil.getName(path);
    // 如果path包含分割符，父目录路径将截取失败
    final String dir = StrUtil.removeSuffix(path, fileName);
    final List<String> names;
    try {
	names = ls(dir);
    } catch (FtpException ignore) {
	return false;
    }
    return containsIgnoreCase(names, fileName);
}
```
其中如果 path以文件分割符结尾 ，FileUtil.getName将会获取除最后分割符外的文件名，导致后续StrUtil.removeSuffix方法无法正常删除后缀，从而判断失败。

1. 复现代码

![image](https://user-images.githubusercontent.com/26626551/187591644-c4c650f6-6463-4275-b28c-6b557eff19d5.png)

#2574  为我提交的修复PR，同时还修复了cn.hutool.extra.ftp.AbstractFtp#isDir方法会导致pwd目录修改的问题

具体逻辑为先使用 isDir方法验证是否为有效目录，如果为"true"表示：当前path一定存在，否则使用原判断逻辑。
注意 ： 新逻辑的加入改变了一些特殊path的返回值

|  exp         |Ftp(旧)| Sftp(旧)| 新    |
|  ------------| ----  | ----   | ---- |
| exist(null)| false | 异常    | false |
| exist("")    | false | 异常    | false |
| exist(".")   | false | 异常    | true |
| exist("..")  | false | 异常    | true |
| exist("/")   | false | false  | true |

```java
public boolean exist(String path) {
	if (StrUtil.isBlank(path)) {
		return false;
	}
	// 目录验证
	if (isDir(path)) {
		return true;
	}
        // 分割符结尾，path指目录，肯定不存在
	if (CharUtil.isFileSeparator(path.charAt(path.length() - 1))) {
		return false;
	}
        // "." , ".." 结尾，path指目录，肯定不存在
	final String fileName = FileUtil.getName(path);
	if (".".equals(fileName) || "..".equals(fileName)) {
		return false;
	}
	// 文件验证
	final String dir = StrUtil.emptyToDefault(StrUtil.removeSuffix(path, fileName), ".");
	final List<String> names;
	try {
		names = ls(dir);
	} catch (FtpException ignore) {
		return false;
	}
	return containsIgnoreCase(names, fileName);
}
```

**Comment by looly** [comment]
感谢PR~~
