### ISSUE TITLE
类型丢失问题

### ISSUE THREAD

**Issue by jiangqiang1996** [looly/hutool#2581]
### 版本情况

JDK版本：    JDK17
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

JWT模块：Long类型作为其中一个负载生成token时，如果Long类型的数值比较小，会丢失类型。
现象：解析token之后Long变成Integer类型，导致强转失败。因为他包装类不能自动提升类型，数据较大时测试正常，数值较小时会出现异常。可能导致隐患。

**Comment by looly** [comment]
可否提供个测试用例我测试下。

**Comment by jiangqiang1996** [comment]
![image](https://user-images.githubusercontent.com/44720422/188249620-e4bda676-8995-4ed8-9d1f-0ff6720cf123.png)

     Map<String, Object> map = new HashMap<>();
        map.put("test1", 1);
        map.put("test2", 2L);
        JWTSigner jwtSigner = JWTSignerUtil.createSigner(AlgorithmUtil.getAlgorithm("HS256"), Base64.getDecoder().decode("abcdefghijklmn"));
        String sign = JWT.create().addPayloads(map).sign(jwtSigner);
        Object test1 = JWT.create().parse(sign).getPayload().getClaim("test1");
        Object test2 = JWT.of(sign).getPayload().getClaim("test2");
        System.out.println(test1);
        System.out.println(test2);

**Comment by jiangqiang1996** [comment]
下面两个都是integer类型，开发人员放进去到long，取出来一般都强转long，但是因为包装类型改变，导致强转报错。

**Comment by looly** [comment]
你可以试下：当你的`test2`足够大的时候，会变成Long：

```java
final Map<String, Object> map = new HashMap<>();
map.put("test2", 22222222222222L);
final JWTSigner jwtSigner = JWTSignerUtil.createSigner(AlgorithmUtil.getAlgorithm("HS256"), Base64.getDecoder().decode("abcdefghijklmn"));
final String sign = JWT.of().addPayloads(map).sign(jwtSigner);
final Object test2 = JWT.of(sign).getPayload().getClaim("test2");
Console.log(test2.getClass());
```

这是JSON解析的时候处理的见：

![image](https://user-images.githubusercontent.com/1432613/188316458-40d963ec-1669-48dc-af3a-9c80ae73b7dc.png)

也就是说你在生成JSON字符串的时候无法保留是Long还是Integer，在解析时，是按照数字大小自动判断Long还是Integer的。

最好的办法是`((Number)value).longValue()`
