### ISSUE TITLE
数据导出成excel,默认精度保留两位？我我查到的数据有的是4位小数，只给我显示2位有办法解决吗？

### ISSUE THREAD

**Issue by chenjunshi8** [looly/hutool#2586]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/84824386/188125104-8826e710-95bf-4c28-9656-ad9a0bc46efc.png)

**Comment by looly** [comment]
已回复，见：https://gitee.com/dromara/hutool/issues/I5PI5C
