### ISSUE TITLE
【讨论】是否应该添加一个自定义http连接池或者封装一个成熟的http连接到hutool中

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#2587]
最近用到http连接池，发现hutool的工具中使用的是直接创建http连接的方式，这对于一个star 23.8k的项目而言，是不太合理的

同时，在文档中没有特殊标明，这个做法的危害，直接在生产中使用是极易出现问题的 
- [http://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil](http://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil)
- #2401 

并且在多个issue中有提到添加：
- #2102
- #1167
- #1005
- #289 (这个估计大佬没有看清楚问题)

最后呼应一下hutool宗旨：

![image](https://user-images.githubusercontent.com/20513615/188248050-4358b261-a653-4c10-8f92-5f97d3e73284.png)

**Comment by VampireAchao** [comment]
😢

**Comment by looly** [comment]
严格来说，这是JDK的HttpUrlConnection存在的问题，Hutool在封装这个的时候尽最大努力避开一些问题和bug，但是毕竟不是自己实现的Http协议，无法完成类似连接池等功能，也不能保证溢出问题。

还有个办法是封装HttpClient或者OKhttp，这个暂时没有在计划之列，希望理解。
