### ISSUE TITLE
文件类型判断方法改进建议

### ISSUE THREAD

**Issue by newmann** [looly/hutool#259]
现在的判断方法是根据文件头的字节内容判断，存在很大的误差，比如docx认为是个zip文件等等，还不如直接用File的probeContentType判断准确。
疑问：
1、为什么采用现在的处理方式？
2、有没有其他更好的识别方式？

**Comment by sunsulei** [comment]
根据文件头已经是最准确的判断方式了

**Comment by looly** [comment]
FileTypeUtil只是一个辅助类型判断，主要用于判断上传的图片类型。

根据头信息判断是最准确的，也是不容易被篡改的。扩展名判断你可以自行实现。
