### ISSUE TITLE
生成的验证码与文档描述不一致

### ISSUE THREAD

**Issue by uliian** [looly/hutool#2590]
### 版本情况

JDK版本：    Amazon Corretto 11.0.8
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
验证码文档中 [验证码部分](https://hutool.cn/docs/#/captcha/%E6%A6%82%E8%BF%B0)
![16113807_sICp](https://user-images.githubusercontent.com/3947701/188303586-b56cfc7a-58ed-4a3f-a042-f5827432644d.png)

展现出来的验证码字符间有重叠，这对增加OCR识别难度有很大帮助，但是新版生成的验证码，既无扭曲，更无重叠，使得OCR变得极其容易，希望能够实现出文档中那样效果的验证码

1. 复现代码

```java
	@Test
	@Ignore
	public void lineCaptchaTest3() {
		// 定义图形验证码的长和宽
		LineCaptcha lineCaptcha = CaptchaUtil.createLineCaptcha(200, 70, 4, 15);
		lineCaptcha.setBackground(Color.yellow);
		lineCaptcha.write("D://tellow.png");
	}
```

现在的验证码：
![tellow](https://user-images.githubusercontent.com/3947701/188303569-6e3623e2-ef35-4ee8-ae89-2c42c471fdad.png)

**Comment by looly** [comment]
这块做了些许变更，你可以使用ShearCaptcha。

关于重叠，可以减少宽高，然后增大字体。

**Comment by uliian** [comment]
没参数修改字体啊
cn/hutool/core/img/GraphicsUtil.java:114
```java
int charWidth = width / len;
```

**Comment by looly** [comment]
setFont可以~~
