### ISSUE TITLE
我来提意见

### ISSUE THREAD

**Issue by Liang-Dongxing** [looly/hutool#2592]
可以有 html转图片，html转word，html转pdf，word转pdf，word转图片，pdf转图片 这些功能吗？

**Comment by looly** [comment]
PDF相关功能都没有。考虑其他第三方库吧~~

HTML转图片、word都不现实，因为要配合css保持样式，这些坑很多。不考虑。

**Comment by Liang-Dongxing** [comment]
java借助python能实现吗

**Comment by looly** [comment]
那就比较麻烦了，python有现成实现么？

**Comment by VampireAchao** [comment]
pdf可以参考：https://gitee.com/dromara/x-easypdf
