### ISSUE TITLE
读取大的excel文件怎么获取总行数

### ISSUE THREAD

**Issue by xhrwp** [looly/hutool#2593]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xhrwp** [comment]
测试100w行的excel 
ExcelReader reader = ExcelUtil.getReader(file);
System.out.println(reader.getPhysicalRowCount());
获取行数直接内存溢出了。sax包下面没有找到获取大文件行数的方法

**Comment by looly** [comment]
Sax方式是按照流的方式读取的，类似于Iterator，无法获取总行数。
