### ISSUE TITLE
jwt公钥签名报错

### ISSUE THREAD

**Issue by ghost** [looly/hutool#2597]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.5

### 问题描述（包括截图）
在生成jwt的token时，使用公钥签名出现报错`InvalidKeyException: Key must not be null`，使用私钥签名时可以正常解析的，建议下一个版本能够支持公钥签名

复现代码
```java
public static String token2() {
        // 算法ID，定义在AlgorithmUtil类型的map集合中
        String id = "rs256";
        // 生成密钥对
        KeyPair rsa256 = KeyUtil.generateKeyPair(AlgorithmUtil.getAlgorithm(id));
        JWTSigner signer = JWTSignerUtil.createSigner(id, rsa256.getPublic());
        return JWT.create()
                .setPayload("sub", "1234567890")
                .setSigner(signer)
                .sign();
}
```

![image](https://user-images.githubusercontent.com/97662228/188896606-ae5f43c0-9358-4f97-90ca-39546ac7b80b.png)

**Comment by looly** [comment]
公钥还能签名？只有私钥才能签名吧。

![image](https://user-images.githubusercontent.com/1432613/188909473-d627041f-0836-449e-8319-99aea013739d.png)
