### ISSUE TITLE
hutool-db 无法处理 表名 或者 表字段带空格问题

### ISSUE THREAD

**Issue by machengjun220** [looly/hutool#2598]
###  字段名或者表名如果带空格，会被忽略不处理。。。
具体截图如下
![1662602850847](https://user-images.githubusercontent.com/40233531/189018448-3d04b7ee-67ed-4e71-ab63-9eb8ddb21370.jpg)

**Comment by looly** [comment]
这是为了兼容值是表达式或者函数的情况。

如果你的表名带空格，考虑自行添加引号。

**Comment by machengjun220** [comment]
> 这是为了兼容值是表达式或者函数的情况。
> 
> 如果你的表名带空格，考虑自行添加引号。

但是我觉得这里的话，如果我写的是自定义sql查询，自定义sql 完全可以自行添加引号，因为既然写sql，用户本身必然是懂的，但是如果只是用户简单的指定某些字段查询一张表，那我只能根据数据源为字段或者表名 增加相应的包装符，要是你们这个方法有个类型切换就好了，如果不是自定义sql的话，都会根据数据源自动给我加上，避免我们自己加
