### ISSUE TITLE
BooleanUtil.orOfWrap()方法，是否可以增加 null判断

### ISSUE THREAD

**Issue by Cmc0** [looly/hutool#2599]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
	/**
	 * 对Boolean数组取或
	 *
	 * <pre>
	 *   BooleanUtil.or(Boolean.TRUE, Boolean.TRUE)                  = Boolean.TRUE
	 *   BooleanUtil.or(Boolean.FALSE, Boolean.FALSE)                = Boolean.FALSE
	 *   BooleanUtil.or(Boolean.TRUE, Boolean.FALSE)                 = Boolean.TRUE
	 *   BooleanUtil.or(Boolean.TRUE, Boolean.TRUE, Boolean.TRUE)    = Boolean.TRUE
	 *   BooleanUtil.or(Boolean.FALSE, Boolean.FALSE, Boolean.TRUE)  = Boolean.TRUE
	 *   BooleanUtil.or(Boolean.TRUE, Boolean.FALSE, Boolean.TRUE)   = Boolean.TRUE
	 *   BooleanUtil.or(Boolean.FALSE, Boolean.FALSE, Boolean.FALSE) = Boolean.FALSE
	 * </pre>
	 *
	 * @param array {@code Boolean}数组
	 * @return 取或为真返回{@code true}
	 */
	public static Boolean orOfWrap(Boolean... array) {
		if (ArrayUtil.isEmpty(array)) {
			throw new IllegalArgumentException("The Array must not be empty !");
		}
		final boolean[] primitive = Convert.convert(boolean[].class, array);
		return or(primitive);
	}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
```java
// 就是这句话，是否可以增加一个 null判断
final boolean[] primitive = Convert.convert(boolean[].class, array);
```

比如报错的Excel文件，有问题的图片等。

**Comment by Cmc0** [comment]
如果是 null，就返回 false

**Comment by looly** [comment]
不建议。null本身定义为false或者true都不合适，这种默认行为可能导致结果意外。自行判定吧。

**Comment by Cmc0** [comment]
> 不建议。null本身定义为false或者true都不合适，这种默认行为可能导致结果意外。自行判定吧。

### 我觉得可以加，我的观点如下：
1. 这个方法入参是封装的 Boolean类型，那么，我每个都要判断是否为 null吗？不然的话会报错，那我每个都判断是否为 null了，那我再调这个方法就有点多余了呀。
2. 从这个方法的含义来说，只要有一个为 true，就返回 true，那么 null是不是不为 true，所以 null就可以不管呀，而不是直接就报错了，就类似下面的代码，为 null，则表示是 false。
```java
	 * <pre>
	 *   BooleanUtil.isTrue(Boolean.TRUE)  = true
	 *   BooleanUtil.isTrue(Boolean.FALSE) = false
	 *   BooleanUtil.isTrue(null)          = false
	 * </pre>
```

```java
// 这句代码 array里面有为 null的元素的话，则会报错。
final boolean[] primitive = Convert.convert(boolean[].class, array);
```
### 综上所述：加一个 null判断，不会影响最终结果的，但是会提升代码的可用性。

**Comment by Cmc0** [comment]
就是这个方法的含义就是，有一个为 true即可，为 null，为 false，都不影响最终的结果的。

**Comment by looly** [comment]
@Cmc0 你可以试下，`BooleanUtil.isTrue(null) `和`BooleanUtil.isFalse(null) `返回的都是false。

这个规则我坚持自己的意见，修改后用户的代码会变成火葬场。

**Comment by Cmc0** [comment]
> @Cmc0 你可以试下，`BooleanUtil.isTrue(null) `和`BooleanUtil.isFalse(null) `返回的都是false。
> 
> 这个规则我坚持自己的意见，修改后用户的代码会变成火葬场。

不会啊，现在传入 null，就直接报错了

**Comment by Cmc0** [comment]
> > @Cmc0 你可以试下，`BooleanUtil.isTrue(null) `和`BooleanUtil.isFalse(null) `返回的都是false。
> > 这个规则我坚持自己的意见，修改后用户的代码会变成火葬场。
> 
> 不会啊，现在传入 null，就直接报错了

我现在用，BooleanUtil.orOfWrap方法，都是要确保每个值，不为 null才行，不然就直接报错了

**Comment by Cmc0** [comment]
那不为 null我要确保，只有给为 null的值，赋值为 false，因为只能传 true或者false嘛，和这里加一个 null表示为 false，没啥区别呀

**Comment by Cmc0** [comment]
> @Cmc0 你可以试下，`BooleanUtil.isTrue(null) `和`BooleanUtil.isFalse(null) `返回的都是false。
> 
> 这个规则我坚持自己的意见，修改后用户的代码会变成火葬场。

那不为 null我要确保，只有给为 null的值，赋值为 false了，因为只能传 true或者false嘛，和这里加一个 null表示为 false，没啥区别呀

**Comment by looly** [comment]
@Cmc0 我想了下，这块确实需要改下。

本身效率也不高，而且or的话null和false貌似都没影响。感谢意见。
