### ISSUE TITLE
hutool-db 包 cn.hutool.db.dialect.impl  下的 OracleDialect 包装符号问题

### ISSUE THREAD

**Issue by machengjun220** [looly/hutool#2605]
这个OracleDialect 的包装符为啥要去掉，这导致字段如果有中文 或者 关键字 ,sql 查询会报错，还有一个
就是目前HiveDialect 为啥没有啊，谢谢~
![image](https://user-images.githubusercontent.com/40233531/189829057-1be5fde4-3857-4989-971b-54068c089c0f.png)

**Comment by looly** [comment]
去掉的原因是Oracle的语句更为复杂，并且加上引号就不忽略大小写了，不符合使用SQL的习惯。

HiveDialect有什么特别需要设置的么？直接默认使用AnsiSqlDialect。

我先关闭issue，如果有异议欢迎讨论并再打开issue。
