### ISSUE TITLE
db 模块，根据jdbc url自动获取 driverClassName的一个bug (hive2不能自动识别)

### ISSUE THREAD

**Issue by machengjun220** [looly/hutool#2606]
只能识别hive，而且你识别开头是hive的，都用这个驱动DRIVER_HIVE，这样hive2就不对了，hive2 (jdbc:hive2://172.30.6.156:10000/default)  没有识别啊，是不是漏了，这个应该简单吧，只要匹配开头是
jdbc:hive2:   就可以了。麻烦看下，谢谢~
![image](https://user-images.githubusercontent.com/40233531/189846948-feee15f3-2e2d-4ed7-92d8-a61e735ca6ec.png)

**Comment by looly** [comment]
5.8.7修复此问题，感谢。

**Comment by Chris-playground** [comment]
5.7.19 虽然写了 Hive2 的驱动名, 但是没有引用, 一直报这个错, Mark 一下, 给后来的小伙伴踩坑
```java
Failed to load driver class org.apache.hadoop.hive.jdbc.HiveDriver in either of HikariConfig class loader or Thread context classloader
```
![image](https://user-images.githubusercontent.com/48941586/198430918-bb950207-1770-4654-9bd3-213d1487c618.png)
