### ISSUE TITLE
5.8.6 FTP工具类表现异常

### ISSUE THREAD

**Issue by liuyx2021** [looly/hutool#2608]
### 版本情况

JDK版本：jdk1.8
hutool版本： 5.8.6

### 问题描述（包括截图）
  FTP 工具类中的  upload、download、recursiveDownloadFolder 等方法皆表现异常，具体表现为： 
  upload 方法返回值为true提示上传文件成功，但远程FTP服务器未找到指定文件，实际未上传成功。
  download 方法成功执行未报异常，但仅会在本地指定目录生成同名文件，文件内容为空，实际未下载成功。
  recursiveDownloadFolder  递归下载方法，成功执行未报异常，但未在本地生成对应的目录及文件，实际未下载成功。
  当将版本降低至 5.8.5 时，上述功能恢复正常

1. 复现代码
public void downloadFile(String sourcePath,String fileName,String targetPath){
	Ftp ftpClient = FtpUtils.getFtpClient(null);
	File file = FileUtil.file(targetPath);
	boolean exists = file.exists();
	if (!exists){
		file.mkdirs();
	}
	//下载
	ftpClient.download(sourcePath,fileName,FileUtil.file(targetPath));
	//关闭连接
	boolean closeFtpClient = FtpUtils.closeFtpClient(ftpClient);

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I5R2DE
