### ISSUE TITLE
chineseMoneyToNumber不显示角分

### ISSUE THREAD

**Issue by chenjianguang1124** [looly/hutool#2611]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.6
### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/51688036/190191356-4a37230f-626c-4e92-9408-a5e00c0ef23d.png)

**Comment by looly** [comment]
最终结果是`BigDecimal`，你可以使用NumberUtil.decimalFormat输出希望的数字格式：

```java
final BigDecimal value = Convert.chineseMoneyToNumber("陆万柒仟伍佰伍拾柒元");

// 67,557.00
Console.log(NumberUtil.decimalFormatMoney(value.doubleValue()));
```

**Comment by chenjianguang1124** [comment]
![image](https://user-images.githubusercontent.com/51688036/190394938-dace7c87-694a-4f39-86f4-203a2b40572d.png)
还是没有角和分

**Comment by chenjianguang1124** [comment]
> 最终结果是`BigDecimal`，你可以使用NumberUtil.decimalFormat输出希望的数字格式：
> 
> ```java
> final BigDecimal value = Convert.chineseMoneyToNumber("陆万柒仟伍佰伍拾柒元");
> 
> // 67,557.00
> Console.log(NumberUtil.decimalFormatMoney(value.doubleValue()));
> ```

还是没有角和分

**Comment by looly** [comment]
sorry，之前没有理解和看清你的问题，确实是bug，这是由于BigDecimal设置精度问题造成的。5.8.7修复~~

感谢。
