### ISSUE TITLE
请教 FileUtil.loopFiles 这个方法用法

### ISSUE THREAD

**Issue by Arther1228** [looly/hutool#2615]
### 版本情况

JDK版本：    oracle jdk 1.8.0_171-b11
hutool版本： 5.7.22

### 问题描述（包括截图）

1. 复现代码

```java
List<File> files = FileUtil.loopFiles(new File(path), maxDepth, File::delete);
```

2.问题描述
我在使用FileUtil这个工具类的时候，使用了loopFiles这个方法，具体方法是：

public static List<File> loopFiles(File file, int maxDepth, FileFilter fileFilter) {
		return loopFiles(file.toPath(), maxDepth, fileFilter);
	}

能不能请教下，为什么使用File::delete这种形式也能成功删除目录中的文件呢，按照我的理解只有实现了FileFilter 类才能作为参数吧？

**Comment by CherryRum** [comment]
假如对方法引用不太了解的话，可以当做匿名类来看

![image](https://user-images.githubusercontent.com/24296698/191052723-99f05032-f910-4add-aa05-27dad63def49.png)

**Comment by VampireAchao** [comment]
https://www.hutool.cn/docs/#/core/JavaBean/%E7%A9%BA%E6%A3%80%E6%9F%A5%E5%B1%9E%E6%80%A7%E8%8E%B7%E5%8F%96-Opt?id=%e5%ad%a6%e4%b9%a0%ef%bc%9a
