### ISSUE TITLE
IdcardUtil地级市和区县名称

### ISSUE THREAD

**Issue by yangwenliang123** [looly/hutool#2622]
IdcardUtil目前只显示到省份，何时计划支持地级市和区县名称呢

**Comment by looly** [comment]
不考虑。考虑自行使用字典表。

![image](https://user-images.githubusercontent.com/1432613/191400240-782a0aa0-fa9a-425a-9110-43cd52f80a3d.png)


原因如下：

1. 区县名称等可能每年变动，为了这个修改升级hutool没有意义且繁琐
2. 名称太多了会增加hutool体积。
