### ISSUE TITLE
对象里面包含枚举，转换的时候有可能出现枚举转换错误，有时成功有时出错

### ISSUE THREAD

**Issue by Simba9980** [looly/hutool#2624]
### 版本情况

JDK版本：    jdk_8_201
hutool版本： 5.8.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
json转换报错
![image](https://user-images.githubusercontent.com/26837690/191693717-db1afdb0-20c2-4883-a693-c9be0674a1e0.png)
1. 复现代码
![image](https://user-images.githubusercontent.com/26837690/191693793-b580ea7f-d67c-4def-a5b9-0693f9ce1520.png)
![image](https://user-images.githubusercontent.com/26837690/191693903-d4a9091f-d56e-49d4-b20b-3a37aeec6d53.png)
![image](https://user-images.githubusercontent.com/26837690/191694103-94c15383-f1c9-49f1-8ed2-c62f8550ac7d.png)
如果没报错，请尝试多运行几次，我也不知道为啥，反正·····有时候报错有时候正常，还没啥规律
2. 堆栈信息
![image](https://user-images.githubusercontent.com/26837690/191693717-db1afdb0-20c2-4883-a693-c9be0674a1e0.png)

**Comment by looly** [comment]
你可以在Enum中定义一个static方法，参数是String，结果是Platform，转换器会自动调用。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/191695539-67bd3645-4351-4976-b63d-a946a12958ed.png)

**Comment by Simba9980** [comment]
每一个都需要这样定义吗？

**Comment by Simba9980** [comment]
静态的 parse方法？还是可以随意一个方法名，我这边这个枚举里面其实有几个静态方法···

**Comment by looly** [comment]
满足`参数是String，结果是Platform`就会被扫描到并调用。我猜测可能有时候扫描到了错误的方法名称导致报错。

**Comment by Simba9980** [comment]
这就尴尬了，原本的枚举上面有一些静态方法，参数String，结果是当前枚举对象的，难怪有时候报错，有时候又正常

**Comment by looly** [comment]
@Simba9980 当时设计是为了兼容更多的Enum转换。你定义一个方法，参数String，返回enum，那我就认为你这个方法有可能是将string转换为enum的。
