### ISSUE TITLE
ReflectUtil 反射方法中桥接问题？bug?

### ISSUE THREAD

**Issue by dashabizzz** [looly/hutool#2625]
### 版本情况

JDK版本：    jdk1.8.0_161
hutool版本： 5.8.7

### 问题描述（包括截图）
5.7.x版本中 
ReflectUtil#getMethod(Class<?> clazz, boolean ignoreCase, String methodName, Class<?>... paramTypes)
false == method.isBridge()方法判断为true 可以反射调用方法
5.8.7版本中 
false == method.isBridge()方法判断为false 无法反射调用方法
1. 复现代码

![image](https://user-images.githubusercontent.com/3240232/191727013-e631f62d-da54-4061-836f-351d2f43e36b.png)

2.异常日志
调用方法
ReflectUtil.invoke(target, "andEqualTo", o);
cn.hutool.core.exceptions.UtilException: No such method: [andEqualTo] from [class tk.mybatis.mapper.entity.Example$Criteria]
	at cn.hutool.core.util.ReflectUtil.invoke(ReflectUtil.java:1091)

**Comment by looly** [comment]
应该不是isBridge判断的问题，这个知识判断是否是`由编译器生成的方法`。

编译器生成的方法不应该被获取。

**Comment by dashabizzz** [comment]
> 应该不是isBridge判断的问题，这个知识判断是否是`由编译器生成的方法`。
> 
> 编译器生成的方法不应该被获取。

恩恩 我的意思是这个调用原生方法 确实不应该
但是是否是因为getMethons(clazz);方法中 获取方法更新所致

**Comment by dashabizzz** [comment]
@looly 
恩恩 我的意思是这个调用原生方法判断桥接，确实不应该
但是是否是因为getMethons(clazz);方法中 获取方法更新所致
新版本 获取方法采用自定义弱引用WeakConcurrentMap造成
![image](https://user-images.githubusercontent.com/3240232/191879441-d151d9d7-352a-47ae-a1df-166da3ddffd3.png)
![image](https://user-images.githubusercontent.com/3240232/191879451-dd62dbff-6892-4870-9865-bd9e6662fdec.png)

**Comment by looly** [comment]
@dashabizzz 确实是isBridge的问题。 内部类继承时方法会变成Bridge。

```java
public static class A{

	public static class C extends B{

	}

	protected static class B{
		public B getThis(){
			return this;
		}
	}
}
```

```java
final Method[] methods = ReflectUtil.getMethods(A.C.class);
for (final Method method : methods) {
	if("getThis".equals(method.getName())){
		// true
		Console.log("{}", method.isBridge());
	}
}
```

我猜测内部类继承时会动态生成类和方法导致变成`Bridge`方法。这确实是个bug。

5.8.8修复此问题。感谢！

**Comment by scruel** [comment]
可喜可贺，终于修复了

> That's a feature x)

**Comment by dashabizzz** [comment]
@looly 然后麻烦看下基于此还有问题 
大概描述为 内部类abstract类A 内部类继承abstract类 B extend A
然后方法获取是两套方法，但是存储是按value存储 会变成一套，5.7.x版本没有这个问题
getMethodsDirectly(Class<?> beanClass, boolean withSupers, boolean withMethodFromObject)
![image](https://user-images.githubusercontent.com/3240232/191943387-f67927dd-c580-49ba-927d-c62c6974c496.png)
![image](https://user-images.githubusercontent.com/3240232/191943298-f3ab9b1c-1108-464c-af2d-a453f3abe395.png)
是设计如此么 
感谢

**Comment by Createsequence** [comment]
> @looly 然后麻烦看下基于此还有问题 大概描述为 内部类abstract类A 内部类继承abstract类 B extend A

关于继承了内部类以后反射获取多个同名方法的问题，可以参考 https://stackoverflow.com/questions/24106486/why-does-the-java-compiler-add-visibility-bridge-methods-for-public-methods-defi

就是当这种内部类互相继承的时候，编译器编译完以后会自动给子类补上父类中方法对应的桥接方法，也就是说，假如父类有一个方法 A，而子类没有，等到编译的时候子类会自动生成一个桥接方法 A。

你这个情况跟题主说的问题应该是一个原因造成的，修复以后你这个问题应该也会解决。

**Comment by dashabizzz** [comment]
@Createsequence 恩恩 我理解是 因为按值作为key存储，当这种情况时，debug显示值其实相同，所以不会存储，这块是不是也算是有些问题 因为不知道后续改法 此处会不会有隐患 因为本质上我理解父类不是桥接方法
![image](https://user-images.githubusercontent.com/3240232/191945001-39f2240a-6b67-4543-897f-29a01726f92c.png)
