### ISSUE TITLE
不应该改为Function

### ISSUE THREAD

**Issue by youtiaoguagua** [looly/hutool#2626]
不应该改为Function

_Originally posted by @VampireAchao in https://github.com/dromara/hutool/issues/2603#issuecomment-1254728492_

我觉得最好也不用function，直接在注释中注明可能造成的问题算了，之后也好排查，但是idea会推荐你改成::写法😂，不知道有没有更好的方法。

**Comment by looly** [comment]
@youtiaoguagua 修改后同时提供了function和Supplier
