### ISSUE TITLE
JakartaServletUtil.getClientIP 与 ServletUtil.getClientIP功能是否重复了?

### ISSUE THREAD

**Issue by selierlin** [looly/hutool#2633]
JakartaServletUtil.getClientIP 与 ServletUtil.getClientIP功能是否重复了?

**Comment by looly** [comment]
是重复了，但是原因是servlet的包改变导致的。

旧的Servlet使用的包是`javax.servlet`，新的规范中servlet给了Jakarta，导致包名变成了`jakarta.servlet`，不得已封装了两个工具类以应对不同版本的Servlet（具体你可以了解下Tomcat不同版本实现了不同的servlet接口）。
