### ISSUE TITLE
加密算法不支持PKCS7Padding

### ISSUE THREAD

**Issue by LoopOuroboros** [looly/hutool#2634]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
希望支持AES/CBC/PKCS7Padding

**Comment by changhr2013** [comment]
PKCS5Padding 实际上是 PKCS7Padding 的子集，PKCS5Padding 标准定义了块大小为 8 个字节，PKCS7Padding 的块大小可以是 1-255 之间任意个字节。
JDK 实现的 PKCS5Padding 实际上是按照 PKCS7Padding 去实现的，所以在 AES 算法的模式下，JDK 会根据 AES 的块大小 16 byte 按照 PKCS7Padding 方式去填充。
因此，当我们使用 JCE 初始化 Cipher 时

```java
Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
```

实际上我们得到的 cipher 内部加/解密时会按照 PKCS7Padding 的方式去填充。
因此 Java 的 PKCS5Padding 是可以跟其他语言的 PKCS7Padding 互通的，没必要单独去做这方面的实现。

**Comment by CherryRum** [comment]
> 

太快了 老哥

**Comment by changhr2013** [comment]
哈哈哈，以前写的，直接粘贴过来的😸

**Comment by LoopOuroboros** [comment]
那有没有静态方法可以抹平PKCS5Padding和PKCS7Padding的差别？

**Comment by CherryRum** [comment]
您如果引入了 bc库也可以参考这样 
https://hutool.cn/docs/#/crypto/%E5%AF%B9%E7%A7%B0%E5%8A%A0%E5%AF%86-SymmetricCrypto

**Comment by changhr2013** [comment]
使用 BC provider，支持传入 PKCS7Padding

**Comment by LoopOuroboros** [comment]
好吧，还是要引入BC库
