### ISSUE TITLE
java.lang.ClassNotFoundException: java.sql.SQLException

### ISSUE THREAD

**Issue by vanezkw** [looly/hutool#2635]
hutool版本： 5.8.8
使用FileUtil.ls()，报错：java.lang.ClassNotFoundException: java.sql.SQLException

**Comment by duhanmin** [comment]
I can't repeat the mistake

**Comment by looly** [comment]
检查你的IDE环境。

1. FileUtil不会使用这个类
2. 这个类是JDK的类，不应该找不到。
