### ISSUE TITLE
动态设置和获取Setting文件时会报inotify watches异常

### ISSUE THREAD

**Issue by laoxiaokang** [looly/hutool#2637]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![cfe5c63297caea3a0d2f45cb9f42520](https://user-images.githubusercontent.com/45983816/192962776-d21dcc03-4f1d-440f-a8e4-523cd895b98b.jpg)

**Comment by looly** [comment]
看报错是打开了太多文件。

参考看：http://www.longant.cn/index.php/zh-hans/node/1109

调整下最大句柄数试下。
