### ISSUE TITLE
HttpUtil.createGet命令导致HttpGlobalConfig中的MaxRedirectCount失效

### ISSUE THREAD

**Issue by fatcarter** [looly/hutool#2638]
### 版本情况

JDK版本：    8
hutool版本： 5.8.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
// HttpUtil中
public static HttpRequest createGet(String url, boolean isFollowRedirects) {
return HttpRequest.get(url).setFollowRedirects(isFollowRedirects);
}
// HttpRequest类中
public HttpRequest setFollowRedirects(boolean isFollowRedirects) {
    return setMaxRedirectCount(isFollowRedirects ? 2 : 0); // 这里将重定向次数写死为2 
}
```

如果302次数超过2次会抛出302异常，完全不管你HttpGlobalConfig类中的maxRedirectCount的值是多少

**Comment by fatcarter** [comment]
关于302重定向这里，sendRedirectIfPossible方法调用UrlBuilder.ofHttpWithoutEncode的时候，有可能拿到的location头是一个没有域名的path，不知道这个是http的规范允许的不，反正浏览器是可以正常解析的，但是UrlBuilder.ofHttpWithoutEncode会在path前面加上http://前缀，导致遇到类似的请求时重定向会失败

**Comment by fatcarter** [comment]
这个url
https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe

**Comment by looly** [comment]
PR中已回复~~
