### ISSUE TITLE
.tar.gz等压缩文件的主文件名

### ISSUE THREAD

**Issue by humphreygao** [looly/hutool#2642]
### 版本情况

JDK版本：    openjdk_8_341
hutool版本： 5.8.8

### 问题描述
.tar.gz压缩文件主文件名，应该包含".tar"吗？

1. 复现代码

```java
FileUtil.mainName("abc.tar.gz");
FileUtil.extName("abc.tar.gz")
```
输出结果为
```
abc.tar
tar.gz
```

**Comment by looly** [comment]
5.8.9修复此问题，感谢。

mainName没有判断多级扩展名的情况。

**Comment by humphreygao** [comment]
好哒
