### ISSUE TITLE
httprequest patch请求方式偶发性报错 Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by 274574162** [looly/hutool#2643]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
HttpRequest.patch(dsUrl + "/datasources/" + id + "/" + projectId)
                    .auth(authorization)
                    .contentType(ContentType.APPLICATION_FORM_URLENCODED.getMimeType())
                    .execute().body();
```

2. 堆栈信息
Invalid HTTP method: PATCH
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个在5.8.8中做了一些“补救”措施，看是否有效。麻烦升级到最新。

如果不行就只能换HttpClient了。

**Comment by lianyiwuming** [comment]
> 这个在5.8.8中做了一些“补救”措施，看是否有效。麻烦升级到最新。
> 
> 如果不行就只能换HttpClient了。

v5-master 分支上，走HttpRequest.patch 方法。追踪代码到  cn.hutool.http.HttpConnection#setMethod  ，这里面有对patch方法的支持。  但这个位置应该是写错了。  @looly 
![image](https://user-images.githubusercontent.com/23331492/194791872-e0f830c1-7665-4dcb-9391-4c86a4685883.png)

**Comment by looly** [comment]
@lianyiwuming 这个有啥问题么？

**Comment by lianyiwuming** [comment]
> @lianyiwuming 这个有啥问题么？

这个patch的判断应该是在 上个  if 块儿的外面
![image](https://user-images.githubusercontent.com/23331492/196162244-cfbabbb8-32fa-45a1-acea-78ed9e101f3a.png)

**Comment by looly** [comment]
@lianyiwuming 在里面应该没有问题。前一个判断是判定了多个请求类型，然后针对多个类型中的一个做处理。

**Comment by lianyiwuming** [comment]
@looly   抱歉，我看错了

**Comment by looly** [comment]
@lianyiwuming 那patch无效的问题还有复现么？

**Comment by KevinXie2021** [comment]
@lianyiwuming @looly 最新版本还有出现这问题吗？我用的低版本偶尔也会出现这个问题

**Comment by looly** [comment]
@KevinXie2021 你可以试下，最新版本做了一点点修改：就是当全局修改patch请求无效的时候，请求前再修改一次。

**Comment by KevinXie2021** [comment]
@looly 嗯，已经用最新版本了，我再观察观察，多谢
