### ISSUE TITLE
考不考虑新加一个gis专业模块？

### ISSUE THREAD

**Issue by Arjen10** [looly/hutool#2644]
在地理信息系统中有很多常用的地信专业方法，例如：
1、空间分析，相交、包含、缓冲等等
2、投影转换：投影坐标，空间坐标互相转换等等
3、矢量、栅格裁切等等
4、求最大外接矩形等等
5、前后端GeoJSON、WKT序列化和反序列等等

不知道项目维护团队是什么想法

**Comment by looly** [comment]
不考虑，没有相关专业知识，考虑寻找专业的实现库。

**Comment by Arjen10** [comment]
> 不考虑，没有相关专业知识，考虑寻找专业的实现库。

emmm，我应该这样问，接不接受一个地理信息工具库

**Comment by looly** [comment]
@Arjen10 我想你是不是要找的是类似这个：https://github.com/geotools/geotools

**Comment by looly** [comment]
@Arjen10 如果自己有维护，建议单独开源哦~~

**Comment by Arjen10** [comment]
> @Arjen10 我想你是不是要找的是类似这个：https://github.com/geotools/geotools

我们工作中经常用到geotools，我的意思是可以把我们用到的，合并进hutools

**Comment by Arjen10** [comment]
> @Arjen10 如果自己有维护，建议单独开源哦~~

了解了，感谢
