### ISSUE TITLE
JSONUtil判断是否是JSON数据有bug

### ISSUE THREAD

**Issue by zhangbao4830** [looly/hutool#2646]
JSONUtil工具类判断是否是JSON数据的时候，如果是"{\"zhangsan\"}"的字符串也会判断为JSON数据~~~~

**Comment by CherryRum** [comment]
https://github.com/dromara/hutool/issues/955  
这个只是为了区分xml之类的简单做个判断吗没有解析语法树

**Comment by CherryRum** [comment]
#https://github.com/dromara/hutool/issues/955
