### ISSUE TITLE
LRUCache移除事件监听失效

### ISSUE THREAD

**Issue by miracle-tree** [looly/hutool#2647]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8

### 问题描述
最近在看Cache模块代码，LRUCache因使用LinkedHashMap进行LRU实现，对象移除存在无法触发监听器移除事件回调现象

1. 复现代码

```java
         LRUCache<String, Integer> cache = CacheUtil.newLRUCache(3);

        cache.setListener((key, value) -> Log.get().info("Start remove k-v, key:{}, value:{}", key, value));

        for (int i = 0; i < 10; i++) {
            cache.put(StrUtil.format("key-{}", i), i);
        }
```

**Comment by CherryRum** [comment]
```java
 LRUCache<String, Integer> cache = CacheUtil.newLRUCache(3,1);  
```
调用错了吧

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/195042988-da050c55-f3b1-42a1-8e2c-0c94be1b760b.png)

**Comment by miracle-tree** [comment]
> ```java
>  LRUCache<String, Integer> cache = CacheUtil.newLRUCache(3,1);  
> ```
> 
> 调用错了吧

不设置超时情况

**Comment by miracle-tree** [comment]
> ```java
>  LRUCache<String, Integer> cache = CacheUtil.newLRUCache(3,1);  
> ```
> 
> 调用错了吧

非超时原因下的删除事件无法监听到

**Comment by looly** [comment]
这里的listener监听只监听队列自动清理的情况，主要实现在`pruneCache`方法，主要是：

1. 如果队列满了清理
2. 如果超时自动清理

问题中我猜测你指用户手动删除的无法监听到，是因为手动删除操作本身并不是缓存自身行为，不会监听。

补充：

嗯……好像满了后确实监听不到……

**Comment by looly** [comment]
确认问题。

5.8.9解决在队列满时监听不到的问题。
