### ISSUE TITLE
建议  BeanUtil.copyToList 貌似性能有点慢

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#2649]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
我在一个长度为50的循环里面调用BeanUtil.copyToList复制数据，貌似有点慢，需要18秒

![image](https://user-images.githubusercontent.com/14087655/195014107-2716c422-418e-4666-8fc4-d75845eea86d.png)
![image](https://user-images.githubusercontent.com/14087655/195014152-67e1235c-5779-48d5-8009-c84543e61ebb.png)

convertor是调用的dozer-core组件，有没有考虑过借鉴一下或者整合？

**Comment by looly** [comment]
麻烦提供下测试代码，我看啥原因这么慢。按理说比较慢，但是差距这么大肯定有问题。

**Comment by looly** [comment]
不知道我的结构是否和你一致：

```java
@Data
static class View1{
	private String a;
	private String b;
	private List<View2> viewList = new ArrayList<>();
}

@Data
static class View2{
	private String a;
	private String b;
	private List<View2> viewList = new ArrayList<>();
}
```

```java
final List<View1> view1List = new ArrayList<>();
for (int i = 0; i < 200; i++) {
	final View1 view1 = new View1();
	view1.setA(String.valueOf(i));
	view1.setB(String.valueOf(i));
	for (int j = 0; j < 2; j++) {
		final View2 view2 = new View2();
		view1.setA(String.valueOf(i));
		view1.setB(String.valueOf(i));
		view1.getViewList().add(view2);
	}
	view1List.add(view1);
}

final StopWatch stopWatch = new StopWatch();
stopWatch.start();
BeanUtil.copyToList(view1List, View2.class);
stopWatch.stop();
Console.log(stopWatch.getTotalTimeSeconds());
```

结果：

![image](https://user-images.githubusercontent.com/1432613/195127778-8a4f5906-5256-4f06-b05d-fd47176a1e4d.png)

**Comment by looly** [comment]
我先关闭issue，如有补充麻烦重新打开issue。

**Comment by reixuemin** [comment]
最后还少了一个循环，我是循环调用BeanUtil.copyToList，调用50次

**Comment by reixuemin** [comment]
> 我先关闭issue，如有补充麻烦重新打开issue。

最后还少了一个循环，我是循环调用BeanUtil.copyToList，调用50次

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/195567312-957d1df9-8037-4e83-ac5b-1b9742379afe.png)

@reixuemin 时间也不对啊。麻烦提供下你的测试用例代码。

**Comment by reixuemin** [comment]
> ![image](https://user-images.githubusercontent.com/1432613/195567312-957d1df9-8037-4e83-ac5b-1b9742379afe.png)
> 
> @reixuemin 时间也不对啊。麻烦提供下你的测试用例代码。

好神奇，我今天第一次跑还是16秒，我是没有加final的，后来改成你这种写法之后就0.06秒，我再改回来也还是0.几秒了

先这样吧，我之后找到问题了再跟你说
