### ISSUE TITLE
根据环境获取setting配置文件

### ISSUE THREAD

**Issue by bxstar** [looly/hutool#265]
通过Setting setting = new Profile().setProfile("dev").getSetting("config.setting");
获取配置文件失败，查看代码发现cn.hutool.setting.profile.Profile#fixNameForProfile
return StrUtil.format("{}/{}", actralProfile);，漏掉一个参数name

**Comment by looly** [comment]
4.4.4修复此问题。感谢。

**Comment by ltylty** [comment]
可以在启动是设置全局profile吗？  实现类似spring boot中类似的效果。

**Comment by ltylty** [comment]
看了下源码，发现GlobalProfile这个类，但是设置之后并不起作用。
继续看DSFactory的源码，找到了办法。在程序启动时执行下面语句就可以指定db.setting的profile。
`Setting setting = new Profile("test").getSetting("db.setting");
        DSFactory.setCurrentDSFactory(DSFactory.create(setting));`

**Comment by ltylty** [comment]
贴上完整代码
```
@Component
public class StartUpConfig implements ApplicationRunner {

    @Autowired
    private Environment environment;

    @Override
    public void run(ApplicationArguments args) {
        // 配置hutool中db.setting 的profile
        String[] activeProfiles = environment.getActiveProfiles();
        if(ArrayUtil.isNotEmpty(activeProfiles)) {
            String profile = StrUtil.format("config-{}", activeProfiles[0]);
            Setting setting = new Profile(profile).getSetting("db.setting");
            DSFactory.setCurrentDSFactory(DSFactory.create(setting));
        }
    }
}
```
