### ISSUE TITLE
文件工具的MailAccount问题

### ISSUE THREAD

**Issue by a349130579** [looly/hutool#2650]
### 版本情况

JDK版本：    openjdk_8_111
hutool版本： 5.8.0

### 问题描述（包括截图）
![输入图片说明](https://foruda.gitee.com/images/1665471383550087231/7d355b76_11458763.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1665471145058765191/3472385f_11458763.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1665471212491471501/a19cb867_11458763.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1665471692183011110/d61d26ff_11458763.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1665471784569917643/ede8b362_11458763.png "屏幕截图")
![输入图片说明](https://foruda.gitee.com/images/1665471801438153284/6e1b5634_11458763.png "屏幕截图")
![image](https://user-images.githubusercontent.com/115529424/195021034-6c7412e4-427b-4a95-a510-d8fa3b1f25df.png)

在使用@Bean和@ConfigurationProperties 给MailAccount类注入属性时遇到的问题， **在本地启动的MailAccount可以正常注入配置文件的属性值** ，在服务器上部署相同的代码后，该类获取的属性值一直为null，最后找到的办法是手动创建了一个bean MailProperties继承MailAccount，MailProperties就能正常读取配置文件。经过反复的debug发现，本地在初始化MailAccount类，读取配置文件进行属性绑定时，能读取到配置文件属性，而服务器在启动，初始化MailAccount的时候，没有读取到配置文件，而在执行MailProperties却能正常注入。这就导致如果使用MailUtil.send的时候，一直报空指针错误。个人尝试了很多方法，没有发现MailAccount类无法注入的具体原因，希望作者不吝赐教，谢谢。
1. 复现代码

```
@Slf4j
@Configuration
@PropertySource(value={"classpath:mail-${spring.profiles.active}.properties"}, encoding = "utf-8")
public class MailConfig {

    @Bean
    @ConfigurationProperties(prefix = "mail")
    public MailProperties mailProperties() {
        return new MailProperties();
    }

    @Bean
    @ConfigurationProperties(prefix = "mail")
    public MailAccount mailAccount() {
        return new MailAccount();
    }

    @PostConstruct
    public void init() {
        log.info("mail account:{}", mailAccount());
        log.info("mail mailProperties:{}", mailProperties());
    }
}


@Data
public class MailProperties extends MailAccount {

    private String title;

    private String content;

}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个我这边也很难复现，考虑：

1. 如果本都和服务端不一致，则考虑配置文件路径问题（如服务端是否在jar包中）
2. 考虑classloader是否一致。

有问题补充再打开此issue。

**Comment by a349130579** [comment]
> 这个我这边也很难复现，考虑：
> 
> 1. 如果本都和服务端不一致，则考虑配置文件路径问题（如服务端是否在jar包中）
> 2. 考虑classloader是否一致。
> 
> 有问题补充再打开此issue。

感谢回复，1经过尝试是在jar中的，配置文件也在。2的方向，答主的意思是看类加载器是ext还是app嘛?

**Comment by looly** [comment]
@a349130579 我也只是猜测而已。如果在jar中，看spring读取配置文件的读取机制了。

**Comment by a349130579** [comment]
> @a349130579 我也只是猜测而已。如果在jar中，看spring读取配置文件的读取机制了。
好的，感谢。这个方向我在尝试一下。
