### ISSUE TITLE
使用HttpUtil登录网站后自动回填cookie问题

### ISSUE THREAD

**Issue by icocooo** [looly/hutool#2658]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用账号登录网页后无法保持登录状态去访问其他页面，开始我以为是访问不带cookie导致的，而去获取Request中的cookie再去访问的使用调用cookie方法就能够以登录状态去访问，后来通过抓包发现自动填充cookie和调用cookie()方法所发送的cookie不同，前者不能保持登录状态，后者可以
![图片](https://user-images.githubusercontent.com/107689720/195988881-c8519c0f-a7ce-40d3-a15a-ec8a1ec730d6.png)
![图片](https://user-images.githubusercontent.com/107689720/195988896-b99260ca-3fda-464a-952b-8ddff397abca.png)

1. 复现代码
  HttpRequest.get("https://www.baidu.com/").execute();

  List<HttpCookie> cookies = GlobalCookieManager.getCookieManager().getCookieStore().getCookies();
  HttpRequest.get("https://www.baidu.com/").cookie(cookies).execute();

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/197345577-027adbec-3e6d-4b51-b4fe-245345f952c3.png)

第一次请求后会生成BIDUPSID和BAIDUID，请求时附带这些信息。

不知道你说的自动回填问题是啥？

我先关闭issue，如需讨论再次打开即可。
