### ISSUE TITLE
ObjUtil建议增加方法

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2659]
ObjUtil建议增加方法
ObjUtil.allNotNull(Object ... args);
ObjUtil.anyNotNull(Object ... args);
ObjUtil.allNull(Object ... args);
ObjUtil.anyNull(Object ... args);

**Comment by wangfanlan** [comment]
有hasNull方法就够了

**Comment by looly** [comment]
见：
1. ArrayUtil.isAllNotNull
2. 
3. ArrayUtil.isAllNull
4. ArrayUtil.hasNull

第二个会在6.x中增加`hasNonNull`方法，你可以暂时使用`false == isAllNull`
