### ISSUE TITLE
自定义邮件发件人别名

### ISSUE THREAD

**Issue by qiuyueovo** [looly/hutool#2662]
### 版本情况

JDK版本：    jdk 8
hutool版本： 5.8.8 

### 问题描述（包括截图）

1. 复现代码

```java
        MailAccount account = new MailAccount();
        account.setHost("smtp.163.com");
        account.setPort(465);
        account.setAuth(true);
        account.setFrom("aqiuyue00@163.com");
        account.setPass("xxxxxxxxx");
        account.setStarttlsEnable(true);
        account.setSslEnable(true);
        account.setDebug(true);
        account.setUser("qiuyue");
```

问题：
如果要自定义别名如何做呢，设置了setUser后会报权限错误，是否可以自定义邮件发件人别名而不是必须是邮箱前缀

**Comment by looly** [comment]
`别名<xxx@hutool.cn>`

**Comment by qiuyueovo** [comment]
account.setFrom("aqiuyue00@163.com");
        account.setPass("xxxxxxxx");
        account.setStarttlsEnable(true);
        account.setSslEnable(true);
        account.setDebug(true);
        account.setUser("qiuyue@163.com");

仍然会报错
cn.hutool.extra.mail.MailException: AuthenticationFailedException: 535 Error: authentication failed
不设置setUser不会。我想自定义别名

**Comment by looly** [comment]
@qiuyueovo 你的user和from要一致，你可以：

```java
account.setFrom("小红<aqiuyue00@163.com>");
```
