### ISSUE TITLE
邮件自定义别名

### ISSUE THREAD

**Issue by qiuyueovo** [looly/hutool#2666]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.8

### 问题描述（包括截图）

1. 复现代码

```java
    account.setFrom("aqiuyue00@163.com");
    account.setPass("xxxxxxxx");
    account.setStarttlsEnable(true);
    account.setSslEnable(true);
    account.setDebug(true);
    account.setUser("qiuyue@163.com");
仍然会报错
cn.hutool.extra.mail.MailException: AuthenticationFailedException: 535 Error: authentication failed
不设置setUser不会。我想自定义别名
```

**Comment by qiuyueovo** [comment]
如果是用原生的话，这样是可以的   
     MimeMessage message = new MimeMessage(session);
        // 2.From:发件人（昵称有广告嫌疑，避免被邮件服务器误认为是滥发广告以至返回失败，请修改昵称）
        message.setFrom(new InternetAddress(sendMail, "xxxxx有限公司", "UTF-8"));

**Comment by looly** [comment]
见：https://github.com/dromara/hutool/issues/2662
