### ISSUE TITLE
UserAgent.getOs() 不支持Windows11

### ISSUE THREAD

**Issue by xcloading** [looly/hutool#2669]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8

**Comment by CherryRum** [comment]
您说反了，是Windows11 不支持UserAgent  

```Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47```

他都没给版本号，所以没办法知道是 Windows11

**Comment by CherryRum** [comment]
想要区分的话建议使用这个  https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11
