### ISSUE TITLE
Entity 能不能实现 IS NOT NULL 这种语句

### ISSUE THREAD

**Issue by gee1k** [looly/hutool#267]
Entity 能不能实现 IS NOT NULL 这种语句

**Comment by gee1k** [comment]
还是说只能 是  key = value

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/51962850-7badda00-249c-11e9-95d1-2ba14489f68e.png)

![image](https://user-images.githubusercontent.com/12059800/51962856-823c5180-249c-11e9-9593-3fa4c4117793.png)

![image](https://user-images.githubusercontent.com/12059800/51962866-8a948c80-249c-11e9-905b-52596904754b.png)

**Comment by gee1k** [comment]
Like 是可以实现的   但 IS NOT NULL 缺直接变成了 =

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/51962948-cfb8be80-249c-11e9-93d5-1c6ce199d0db.png)

![image](https://user-images.githubusercontent.com/12059800/51962954-d6dfcc80-249c-11e9-9d40-a8aabf434291.png)


这样写可以。这是不是算是一个 bug

**Comment by looly** [comment]
4.4.4增加支持。感谢。
