### ISSUE TITLE
远程下载带有Https的URL文件会报错

### ISSUE THREAD

**Issue by uu-xixi** [looly/hutool#2670]
### 版本情况

JDK版本：    openjdk_11.0.15
hutool版本： 5.8.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用HttpUtil.downloadFile方法远程下载带有Https的URL文件会报错

1. 复现代码
String url  = "https:// xxxx.xxxx.xxxx";
HttpUtil.downloadFile(url, new File(xxxx));
```java
异常信息：PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by duhanmin** [comment]
参考下:
```
String url= "https://www.baidu.com/img/flexible/logo/pc/result.png";
HttpRequest.get(url).setSSLProtocol("TLSv1.2").executeAsync().writeBody("/Users/duhanmin/Desktop/result.png"
```

**Comment by uu-xixi** [comment]
> 参考下:
> 
> ```
> String url= "https://www.baidu.com/img/flexible/logo/pc/result.png";
> HttpRequest.get(url).setSSLProtocol("TLSv1.2").executeAsync().writeBody("/Users/duhanmin/Desktop/result.png"
> ```

感谢大佬~
