### ISSUE TITLE
关于传递数组参数时，key和value都相同的情况

### ISSUE THREAD

**Issue by samCooker** [looly/hutool#2671]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public static void main(String[] args) {
        HttpRequest request = HttpRequest.post("http://xxx");
        request.form("keys","01");
        request.form("keys","02");
        request.form("keys","03");
        request.form("keys","01");
        request.form("keys","01");
        request.setConnectionTimeout(20000)
                .setReadTimeout(30000)
                .header(Header.CONTENT_TYPE, ContentType.APPLICATION_FORM_URLENCODED.toString())
                .execute().body();
    }
```
如图所示，debug时，后面两个参数没有传递。不知道是不是还需要设置什么？
![15AE9B54-B25D-4162-9CD4-0B028A45FFAF](https://user-images.githubusercontent.com/13888063/196855599-0f94d99a-9996-470a-8baa-1bbc5fe14909.png)

**Comment by samCooker** [comment]
图没有截完整
![C6C040DC-05E6-415C-A5B2-8447E40A269A](https://user-images.githubusercontent.com/13888063/196856153-de9c6f31-71a9-414c-b46c-fe2c64def3b8.png)

**Comment by Milesians** [comment]
使用案例重现了一下，发现是由于在TableMap#entrySet() 中，返回值是一个LinkedHashSet，而Entry的equals方法判定当key和value都相等时为true，导致重复的entry丢掉了，本人比较小白，关注下后续会如何修改

**Comment by looly** [comment]
这个是TableMap的bug，5.8.9修复，感谢！！

见：https://gitee.com/dromara/hutool/issues/I5WMST
