### ISSUE TITLE
gitBigWriter导出之后write会报错

### ISSUE THREAD

**Issue by Javac0** [looly/hutool#2674]
![1666414192649](https://user-images.githubusercontent.com/31591084/197320418-d57ef066-de5c-4faa-ad53-2540cb7f6b26.jpg)

**Comment by Javac0** [comment]
报错代码
List<?> row1 = CollUtil.newArrayList("aa", "bb", "cc", "dd", DateUtil.date(), 3.22676575765);
        List<?> row2 = CollUtil.newArrayList("aa1", "bb1", "cc1", "dd1", DateUtil.date(), 250.7676);
        List<?> row3 = CollUtil.newArrayList("aa2", "bb2", "cc2", "dd2", DateUtil.date(), 0.111);
        List<?> row4 = CollUtil.newArrayList("aa3", "bb3", "cc3", "dd3", DateUtil.date(), 35);
        List<?> row5 = CollUtil.newArrayList("aa4", "bb4", "cc4", "dd4", DateUtil.date(), 28.00);

        List<List<?>> rows = CollUtil.newArrayList(row1, row2, row3, row4, row5);

        BigExcelWriter writer= ExcelUtil.getBigWriter("d:/xxx.xlsx","sheet1");
// 一次性写出内容，使用默认样式
        writer.write(rows);
// 关闭writer，释放内存
        writer.close();

//存在空单元格(输入文字后，在单元格内删除了字符)，不为null的单元格，使用getBigWriter
导出之后write出现 Attempting to write a row[0] in the range [0,4] that is already written to disk.

**Comment by looly** [comment]
BigWriter构造的时候设置下最大窗口即可。
