### ISSUE TITLE
HmacAlgorithm.HmacSHA1 无key构造会填充随机key

### ISSUE THREAD

**Issue by BennyTian** [looly/hutool#2685]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22/5.8.9

### 问题描述（包括截图）

1. 复现代码

```java

String body = "helloworld" ;
HMac mac = new HMac(HmacAlgorithm.HmacSHA1);
String result = mac.digestHex(body.getBytes(StandardCharsets.UTF_8));

```
采用 new HMac(HmacAlgorithm.HmacSHA1); 单参数构建的时候,result每次结果都不同,

采用  new HMac(HmacAlgorithm.HmacSHA1,key); 则正常

**Comment by CherryRum** [comment]
![image](https://user-images.githubusercontent.com/24296698/198167205-ab0b4edd-06fa-4b43-9b97-5bdfb8d56569.png)
