### ISSUE TITLE
Db.use()有没有${}可以替换字段和表名

### ISSUE THREAD

**Issue by Chris-playground** [looly/hutool#2689]
`Db.use()` 模块有没有 `${}` 的占位符可以替换select的字段, 比如
```java
Db.use("impala").query("select ${columnName} from ${dbName}.${tableName} limit 2", "tyre_barcode", "dw", "dw_wms_vw_bi_tyre_barcode");
```

**Comment by fenglex** [comment]
兄弟写python习惯了吧，java一般会用'?'做这样的操作
比如
Db.use().query("select * from user where age < ?", 3);

**Comment by Chris-playground** [comment]
> 兄弟写python习惯了吧，java一般会用'?'做这样的操作 比如 Db.use().query("select * from user where age < ?", 3);

其实我主要是想做字段名的替换, 这里的 `?` 其实就对应 mbp 里的 `#{}`, mbp 里的 `${}` 可以替换字段名和表名啥的, 不知道`Db.use()` 里有没有类似的操作

**Comment by fenglex** [comment]
> 那的确不行，可以考虑使用[StrFormatter]结合做，因为参数和字段表名处理是不同的逻辑，可能还要考虑各个数据库对于保留词的处理情况，是很麻烦的，那么这整个sql就不如直接使用StrFormatter，是一个？主要是能达到预编译的效果，如果整个作为字符串处理好像就失去了意义吧，还不如结合StrFormatter表名字段名使用Str工具，字段使用'？'进行预编译

**Comment by Createsequence** [comment]
楼上说的有道理，不过这种自定义的占位符确实也有对应的使用场景，不仅局限于sql，v6也许会加上，实际上已经有对应的pr了

**Comment by Chris-playground** [comment]
嗯, 现在做的是使用 `StrUtil.format()` 提前处理好 SQL, 然后直接执行, 应该也只能这样了吧

**Comment by looly** [comment]
有兴趣可以看下：`NamedSql`。

![image](https://user-images.githubusercontent.com/1432613/199533621-cd6a040b-824c-46fb-a47a-6db1db4d99e6.png)
