### ISSUE TITLE
URLUtil.normalize不能将//转为/

### ISSUE THREAD

**Issue by matcha007** [looly/hutool#2693]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.6.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

```java
        String url = "http://www.hutool.cn//aaa/bbb";
        // 结果为：http://www.hutool.cn/aaa/bbb
        String normalize = URLUtil.normalize(url);
        url = "http://www.hutool.cn//aaa/\\bbb?a=1&b=2";
        // 结果为：http://www.hutool.cn/aaa/bbb?a=1&b=2
        normalize = URLUtil.normalize(url);
```
[https://www.bookstack.cn/read/hutool-5.6.0-zh/0d2d3c5e924b5f1c.md](url)
抄的这上面的代码，但是结果和上面的描述不一样。我的结果是
http://www.hutool.cn//aaa/bbb
http://www.hutool.cn//aaa//bbb?a=1&b=2
如上，结果中的//仍然存在

**Comment by matcha007** [comment]
看了源代码，需要这样写才行：URLUtil.normalize(url, false, true);

**Comment by looly** [comment]
@matcha007 是滴。因为有些URL中`//`是合法字符，尤其在路径中。
