### ISSUE TITLE
FieldsComparator排序时，被FuncComparator类的compare方法中对象排序冲突

### ISSUE THREAD

**Issue by mabin37562060** [looly/hutool#2695]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.9

### 问题描述（包括截图）
多字段排序，无效 FieldsComparator

**Comment by looly** [comment]
可否提供下样例代码？没看懂啥意思。

**Comment by looly** [comment]
我先关闭issue，麻烦进一步补充后再打开。
