### ISSUE TITLE
Db.use().get()查询oracle11g的DATE(7)类型，获取到的Entity内值为"2022-10-20T01:36:00.000+0000"字符串

### ISSUE THREAD

**Issue by diaomina** [looly/hutool#2699]
Db.use().get()查询oracle11g的DATE(7)类型，获取到的Entity内值为"2022-10-20T01:36:00.000+0000"字符串

理论上应该是"2022-10-20 09:36:00"字符串

**Comment by diaomina** [comment]
查询出来的类型不是DATE
![image](https://user-images.githubusercontent.com/40923075/199149391-a01d6322-8ce0-4db8-9d9d-ea79babf86e5.png)

**Comment by diaomina** [comment]
![image](https://user-images.githubusercontent.com/40923075/199149549-b43844ca-4754-418c-9246-348aa097e758.png)

**Comment by fenglex** [comment]
我感觉是你理解的有问题，我看到你的entity中的APPLY_DATE类型是timestamp，和你的数据库中的日期类型对应的，他后面肯定会有秒后面的精度相关的数据的，就像你new Date()，出来的时间他肯定会带有毫秒的信息的。在这Date(7),后面的这个7应该是精度相关的，和格式并没有什么关系吧，你想要格式需要你进行转换

**Comment by diaomina** [comment]
ok
