### ISSUE TITLE
建议: 增加敏感词,

### ISSUE THREAD

**Issue by leblog** [looly/hutool#2701]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Createsequence** [comment]
是指敏感词库吗？如果是的话感觉不太合适让一个第三方库提供：

- 这个东西很难做到通用性，不同场景里面的敏感词范围很可能不一样，具体可能需要由公司自己的业务决定；
- 这玩意也很难保证时效性，毕竟敏感词的范围也会随着时间变化；

**Comment by CherryRum** [comment]
词库建议自己准备然后使用，`SensitiveUtil`初始化
