### ISSUE TITLE
poi写excel头内容写入到列值里

### ISSUE THREAD

**Issue by guangshuowang** [looly/hutool#2703]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.5（请确保最新尝试是否还有问题）
我看了版本升级记录，没有关于我这个问题的修复
### 问题描述（包括截图）
表头存在，但是数据里没有设置对应列的值，有的时候会空 有的时候就像下面这样，把表头赋值在列值中
1. 复现代码
String path = "D:/home/download/temp/workbench" + File.separator + "111.xlsx";
		BigExcelWriter writer = ExcelUtil.getBigWriter(path);
		writer.renameSheet(0, "Sheet0");

		writer.setSheet("Sheet0");
		HashSet<String> headSet = new HashSet<>();
		headSet.addAll(Arrays.asList("A","B","C","D","E"));
		List<Map<String, String>> datas = new ArrayList<>();
		boolean head = true;
		for (int i = 0; i < 10; i++) {
			Map<String, String> mapAll = new HashMap<>();
			Map<String, String> map = new HashMap<>();
			headSet.remove("D");
			for (String s : headSet) {
				map.put(s, "h" + i);
			}
			mapAll.putAll(map);
			mapAll.put("E", "aaa");
			datas.add(mapAll);
			headSet.add("D");
		
			writer.setCurrentRow(i);
			writer.write(datas, head);
			datas.clear();
		}
		for (int i = 10; i < 20; i++) {
			Map<String, String> map = new HashMap<>();
			for (String s : headSet) {
				map.put(s, "h" + i);
			}
			datas.add(map);
			
			writer.setCurrentRow(i);
			writer.write(datas, head);
			datas.clear();
		}
		writer.close();
```java
第二个问题，
复现代码：

```

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
麻烦升级Hutool到最新试下。
