### ISSUE TITLE
验证码如果是四则运算，则如何获得他的运算结果

### ISSUE THREAD

**Issue by hardyfan** [looly/hutool#2708]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

验证码选择四则运算之后，getCode获得的是一个运算表达式（例如：86-34=），我们想要把这个计算的结果保存在session中，然后在后续提交登陆时再去做验证用户输入的验证码是否匹配。
怎么做？

**Comment by looly** [comment]
现在只支持在MathGenerator.verify中完成验证，你可以拿出其中代码获取值。
