### ISSUE TITLE
注解工具AnnotationUtil方法getAnnotationValue调用取值为null

### ISSUE THREAD

**Issue by crazyliuzc** [looly/hutool#271]
同 #228  问题，尝试getAnnotation和getAnnotationValueMap方法可以获取，查看源代码发现写法不一样，
问题代码出现在以下，method为null，ReflectUtil.invoke第一个参数应该是上文获取到的annotation
`final Method method = ReflectUtil.getMethodOfObj(annotationEle, propertyName);`
`if (null == method) {`
	`return null;`
`}`
`return ReflectUtil.invoke(annotationEle, method)`

希望路神的单元测试可以覆盖的所有工具方法，方便测试，也方便菜鸟上手。

**Comment by looly** [comment]
感谢。属于手误，之前的issue没看懂。这回懂了。

4.4.5修复此问题。

顺便：新春快乐~~

**Comment by crazyliuzc** [comment]
新春快乐
