### ISSUE TITLE
使用DbUtil无法保存clob类型数据

### ISSUE THREAD

**Issue by diaomina** [looly/hutool#2711]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.21

### 问题描述（包括截图）
使用DbUtil无法保存clob类型数据。

步骤为：
1、将字符串转为clob
value = new SerialClob(String.valueOf(value).toCharArray());
2、设置到Entity
entity.set(name, value);
3、保存
count = session.update(entity, entityWhere);

![image](https://user-images.githubusercontent.com/40923075/200099235-1b3658bf-21bc-440d-a3dd-f085f0c3a4e0.png)

**Comment by diaomina** [comment]
补充一下数据库版本：
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by diaomina** [comment]
<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>21.1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
            <version>21.1.0.0</version>
        </dependency>

**Comment by looly** [comment]
entity.set(name, value)中的value为何不直接传Clob？这样试下。

**Comment by diaomina** [comment]
试了下entity.set(name, value)中value不可为Clob类型，传入Stirng可以

**Comment by looly** [comment]
@diaomina 麻烦升级Hutool到最新版本试下。
