### ISSUE TITLE
[type: new feature] locate the QR code

### ISSUE THREAD

**Issue by loongs-zhang** [looly/hutool#2714]
Why ?
On the one hand, in order to cut out the QR code and then recognize it, so as to improve the accuracy of QR code recognition; 
On the other hand, it can meet other requirements, such as replacing QR codes.

How ?
My company has implemented it based on `javacv` and runs well in the production environment, so I plan to implement it based on [javacv](https://github.com/bytedeco/javacv)

Other import information
The `model` is needed for localization. I plan to `package the model in jar` and `extract it at runtime`. 
`javacv` is internally integrated with many platform implementations, because the underlying layer is `JNI`, I plan to cut the introduction of `javacv`, leaving only `linux-x86_64`, which means you can't use it on `windows/macos`.

Any suggestions ?

**Comment by looly** [comment]
sorry, Hutool`s QrcodeUtil base the Google Zxing, not plan  to supoort the jni
