### ISSUE TITLE
csv读取文件，映射实体方式无法读取第一列数据

### ISSUE THREAD

**Issue by wangwen1024** [looly/hutool#2715]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.8.9（已是最新）

### 问题描述（包括截图）

1. 复现代码

```java
CsvReader reader = CsvUtil.getReader();
List<CsvVo> rows = reader.read(ResourceUtil.getUtf8Reader("C:\\Users\\11722\\Desktop\\alice.csv"), CsvVo.class);
System.out.println(rows);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/11722/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/11722/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

age | income
-- | --
30 | 80000
30 | 70000

</body>

</html>

比如报错的Excel文件，有问题的图片等。

**Comment by wangwen1024** [comment]
![)VUR`B3FI0WOC ~4Z)94XRQ](https://user-images.githubusercontent.com/72856573/200167077-02f1317d-ad6d-4521-a563-440246f26f32.png)
源码debug 追踪到是copyProperties 的时候 复制掉了

cn.hutool.core.bean.BeanUtil  这个类的toBean(Object source, Supplier<T> targetSupplier, CopyOptions options)方法

**Comment by looly** [comment]
麻烦提供下测试的Excel文件和CsvVo的结构。

**Comment by wangwen1024** [comment]
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CsvVo {
    /**
     * 年龄
     */
    @Alias("age")
    private String age;

    /**
     * 收入
     */
    @Alias("income")
    private String income;

    /**
     * 性别
     */
    @Alias("sex")
    private String sex;

    /**
     * 学历
     */
    @Alias("education")
    private String education;

    /**
     * 国籍
     */
    @Alias("nationality")
    private String nationality;

    /**
     * 电话
     */
    @Alias("telephone")
    private String telephone;
}

> 麻烦提供下测试的Excel文件和CsvVo的结构。

**Comment by wangwen1024** [comment]
[alice.csv](https://github.com/dromara/hutool/files/9947367/alice.csv)

**Comment by wangwen1024** [comment]
> 麻烦提供下测试的Excel文件和CsvVo的结构。

`@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CsvVo {
    /**
     * 年龄
     */
    @Alias("age")
    private String age;

    /**
     * 收入
     */
    @Alias("income")
    private String income;

    /**
     * 性别
     */
    @Alias("sex")
    private String sex;

    /**
     * 学历
     */
    @Alias("education")
    private String education;

    /**
     * 国籍
     */
    @Alias("nationality")
    private String nationality;

    /**
     * 电话
     */
    @Alias("telephone")
    private String telephone;
}`

**Comment by wangwen1024** [comment]
```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CsvVo {
    /**
     * 年龄
     */
    @Alias("age")
    private String age;

    /**
     * 收入
     */
    @Alias("income")
    private String income;

    /**
     * 性别
     */
    @Alias("sex")
    private String sex;

    /**
     * 学历
     */
    @Alias("education")
    private String education;

    /**
     * 国籍
     */
    @Alias("nationality")
    private String nationality;

    /**
     * 电话
     */
    @Alias("telephone")
    private String telephone;
}
```

**Comment by looly** [comment]
嗯……并不是Hutool的问题，而是你的文件有问题。

你的文件是带BOM头的，所以读出来标题的age这个名字前加了一些bom头的东西，都出来就有问题了。

可以这样读就行了：

```java
final CsvReader reader = CsvUtil.getReader();
final List<CsvVo> rows = reader.read(new BomReader(ResourceUtil.getStream("d:/test/alice.csv")), CsvVo.class);
```

**Comment by wangwen1024** [comment]
好的。感谢 解决了
