### ISSUE TITLE
【建议】建议新增 QQ 和微信号的正则表达式

### ISSUE THREAD

**Issue by samho2008** [looly/hutool#2726]
【建议】建议新增 QQ 和微信号的正则表达式

**Comment by CherryRum** [comment]
qq号建议自己写吧，今年不是还出了qid自己设置

微信号 是这个 https://kf.qq.com/touch/wxappfaq/120813euEJVf141212Vfi6fA.html?ivk_sa=1024320u
`^[a-zA-Z][-_a-zA-Z\d]{5,19}$`随手一写应该是这样的

**Comment by looly** [comment]
不考虑，尤其微信号，可以自定义的，定义正则没意义。
