### ISSUE TITLE
mongo链接时如何设置访问用户和密码？

### ISSUE THREAD

**Issue by hardyfan** [looly/hutool#2729]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用Mongo需要配置文件，但是配置文件里没有设置用户和密码的地方。无法连接上服务器。

**Comment by looly** [comment]
只需：

```
user = test1
pass = password
database = test

[master]
host = 127.0.0.1:27017

[slave]
host = 127.0.0.1:27018
```

**Comment by hardyfan** [comment]
感谢，不过我 database = test链接不上，后来修改成 database = admin 后链接上。

**Comment by looly** [comment]
@hardyfan 当然拉，数据库名称是你MongoDB中定义的名称。
