### ISSUE TITLE
UrlBuilder获取query参数，如果path有#，则获取不到query参数

### ISSUE THREAD

**Issue by zhouxiaofu** [looly/hutool#2732]
### 版本情况

JDK版本：    Oracle OpenJDK 1.8.0_333
hutool版本： 

```xml
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>5.8.9</version>
</dependency>
```

### 问题描述（包括截图）

UrlBuilder获取query参数，如果path有#，则获取不到query参数

前端hash模式url的path上会有#

```java
import cn.hutool.core.net.url.UrlBuilder;
import cn.hutool.core.util.StrUtil;
import org.junit.jupiter.api.Test;

public class UrlTest {
    @Test
    public void getQuery() {
        UrlBuilder urlBuilder1 = UrlBuilder.of("http://127.0.0.1/#/user/page?pageNum=1&pageSize=10");
        UrlBuilder urlBuilder2 = UrlBuilder.of("http://127.0.0.1/user/page?pageNum=1&pageSize=10");

        System.out.println(StrUtil.format("pageNum: {}, pageSize: {}", urlBuilder1.getQuery().get("pageNum"),
            urlBuilder1.getQuery().get("pageSize")));

        System.out.println(StrUtil.format("pageNum: {}, pageSize: {}", urlBuilder2.getQuery().get("pageNum"),
            urlBuilder2.getQuery().get("pageSize")));
    }
}
```

打印结果：
> urlBuilder1, pageNum: null, pageSize: null
> urlBuilder2, pageNum: 1, pageSize: 10

**Comment by zhouxiaofu** [comment]
前端hash模式url的path上会有#

**Comment by ZZemptypoint** [comment]
这个是java.net.URL解析的问题, 它认为`#`后面是`reference`链接

**Comment by zhouxiaofu** [comment]
找到原因了 [https://stackoverflow.com/questions/36604037/not-able-to-parse-query-parameters-with-url](https://stackoverflow.com/questions/36604037/not-able-to-parse-query-parameters-with-url)

需要先对path进行urlEncode处理

**Comment by zhouxiaofu** [comment]
找到原因了 [https://stackoverflow.com/questions/36604037/not-able-to-parse-query-parameters-with-url](https://stackoverflow.com/questions/36604037/not-able-to-parse-query-parameters-with-url)

需要先对path进行urlEncode处理
