### ISSUE TITLE
分词工具ik引擎版本比较老，建议替换一下

### ISSUE THREAD

**Issue by Furinai** [looly/hutool#2733]
我基于最新版ik插件改的一个https://github.com/Linter-cn/ik-analyzer

**Comment by looly** [comment]
几个问题。

我看你的实现了，包名没变，直接引入即可识别。

你可以看到引入的旧版本的scope是optional的，因此不影响（只是影响test结果而已）

我尝试引入你的包，依赖的lucence是`9.4.0`版本，这个版本没法在jdk8下编译。所以这块暂时不动。

**Comment by Furinai** [comment]
> 

我这边用的jdk11，确实没考虑jdk8，等有空看看哪个版本lucene合适
