### ISSUE TITLE
JSONUtil.toList 时间丢失了

### ISSUE THREAD

**Issue by stoneLee81** [looly/hutool#2737]
![image](https://user-images.githubusercontent.com/18001708/202216620-18fefa6d-6ef9-4297-81f6-b3f6f9d9cfa1.png)
![image](https://user-images.githubusercontent.com/18001708/202216684-1f1e73ce-f627-4d30-bbae-d390ceee204c.png)

使用gson转是有的

**Comment by looly** [comment]
只有这个一个字段为空还是全部字段？是否提供了setter方法？

麻烦提供下测试代码后打开issue。

**Comment by stoneLee81** [comment]
> 
测试对象：
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TestDTO implements Serializable {
    private Date followupTime;
}

测试代码
List<TestDTO> tttt = JSONUtil.toList(GsonUtil.toJson(Lists.newArrayList(TestDTO.builder()
                .followupTime(DateUtil.parseDate("2021-08-03 16:44:00"))
                .build())), TestDTO.class);

``
输出结果
![image](https://user-images.githubusercontent.com/18001708/202341562-6ec2f86c-4fff-4e2c-9e3e-5d9630f5ae30.png)

只要是时间都会空

**Comment by stoneLee81** [comment]
@looly

**Comment by stoneLee81** [comment]
我知道怎么回事了，我用的gson来获取的jsonstr,然后用的hutool转的，当我使用JSONUtil.toJsonStr就可以出结果了，但是都是标准的jsonstr,为什么输出的结果却不一样呢？

**Comment by stoneLee81** [comment]
日期的格式不太一样，gson/hutool jsonutil转出导致的

**Comment by ZZemptypoint** [comment]
你打印一下两个工具类转出来的json字符串

**Comment by stoneLee81** [comment]
gson的 [{"followupTime":"Aug 3, 2021 4:44:00 PM"}]
jsonutil的[{"followupTime":1627980240000}]

**Comment by ZZemptypoint** [comment]
有点离谱

**Comment by looly** [comment]
@stoneLee81 GSON生成的time类型是ISO格式的，Hutool默认只支持时间戳。你这种情况需要在JSONConfig中setDateFormat。

PS：建议不要多个JSON库混用。
