### ISSUE TITLE
 ImageUtil.rotate方法bug

### ISSUE THREAD

**Issue by colorall** [looly/hutool#274]
ImageUtil.rotate 旋转后会少一个像素，如，1024*768 变成 1023*768

**Comment by looly** [comment]
测试后并未发现此问题。我这边测试90、180。

麻烦提供测试图片和旋转角度。

**Comment by colorall** [comment]
> 测试后并未发现此问题。我这边测试90、180。
> 
> 麻烦提供测试图片和旋转角度。

现在我测试也没有重现，抱歉给你添麻烦了

**Comment by looly** [comment]
不麻烦。欢迎随时提问题或者提bug。
