### ISSUE TITLE
Find a OutOfMemoryError which may lead to dos in hutool-json

### ISSUE THREAD

**Issue by BIngDiAn-s** [looly/hutool#2747]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

``` 
public static void main(String[] args)  {

String a="{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{'a':1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}:1}";
JSONObject jsonObject=new JSONObject(a);

    }
```

2. 堆栈信息
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/32029400/202851698-e13bf298-8a57-4622-9fa9-00fc3286c998.png">

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
和你提的：https://github.com/dromara/hutool/issues/2746 这个类似，合并issue。

**Comment by duhbbx** [comment]
还有这种json？

**Comment by ZZemptypoint** [comment]
@duhbbx 
当然, 它不是有效的json, 但是hutool并没有识别到它的非法, 而是抛了OOM错误, 所以它确实算是一个问题.
