### ISSUE TITLE
FileTypeUtil.getType 不能获取文件类型 文件是jpg类型

### ISSUE THREAD

**Issue by colorall** [looly/hutool#275]
FileTypeUtil.getType(InputStream)
判断文件类型准确性问题，文件是jpg类型，文件头如下：
FFD8FFDB0043000D090A0B0A110D0B150B1D0E0D0F13201513121213
![2332573_2 null](https://user-images.githubusercontent.com/5858032/53064805-13cf3a00-3504-11e9-9b74-dddca04454c6.jpg)

**Comment by looly** [comment]
4.5.0修复此问题。
