### ISSUE TITLE
Alias只会替换对象的第一层级，多层级子级不会替换

### ISSUE THREAD

**Issue by bijialin** [looly/hutool#2754]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4
### 问题描述（包括截图）

1. 复现代码

```java
  @Data
  class Package {
   
    @Alias("版本")
    private String version;

    @Alias("签名对象")
    private SignedObject signedObject;

  }

  @Data
  class SignedObject {

    @Alias("包类型")
    private String packageType;

    @Alias("包描述")
    private String packageDescription;
}
```

使用@Alias进行maptoBean复制，或者从beantomap时，只会对第一层级进行alias替换，多层级不会进行替换

**Comment by ZZemptypoint** [comment]
`BeanUtil.beanToMap()`只会把bean转为单层Map, 你想要多层Map, 要使用`JSONUtil.parseObj()`, JSONObject也是Map的子类, `@Alias` 也会生效
