### ISSUE TITLE
URLUtil.normalize(url) 方法无法正确去除URL中的斜杠

### ISSUE THREAD

**Issue by happyjustyn** [looly/hutool#2757]
### 版本情况

JDK版本：    oracle jdk 1.8.0_91
hutool版本： 5.8.9

### 问题描述（包括截图）

`URLUtil.normalize(url)`和`URLUtil.normalize(url, false)`方法不能正确标准化URL, 具体表现为不能正确去除URL中的斜杠

1. 复现代码

```java
public static void main(String[] args) {
    String url = "http://www.hutool.cn//aaa///bbb\\ggg";
    System.out.println(URLUtil.normalize(url));
}
```
![image](https://user-images.githubusercontent.com/35069723/203782495-7d130ba1-0d5d-4755-96c4-8f2c7034cb01.png)

输出结果:
```
http://www.hutool.cn//aaa///bbb/ggg
```
![image](https://user-images.githubusercontent.com/35069723/203782585-3cb40065-f82b-424a-9a62-bc8f5f57d9b6.png)

**Comment by CherryRum** [comment]
尝试如下方法
```java
System.out.println(URLUtil.normalize(url,false,true));
```

**Comment by happyjustyn** [comment]
> 

谢谢, 这种方式确实可以, 但还是希望改进下最简单的调用方式

**Comment by looly** [comment]
@happyjustyn 双斜杠未处理是有意为之，很多URL双斜杠是合法的，简单处理为单斜杠URL反而会报错。

**Comment by happyjustyn** [comment]
> @happyjustyn 双斜杠未处理是有意为之，很多URL双斜杠是合法的，简单处理为单斜杠URL反而会报错。

我懂了, 感谢回复

**Comment by CherryRum** [comment]
擦，我以为我回复了。🤣



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2022年11月24日(周四) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [dromara/hutool] URLUtil.normalize(url) 方法无法正确去除URL中的斜杠 (Issue #2757)




 
@happyjustyn 双斜杠未处理是有意为之，很多URL双斜杠是合法的，简单处理为单斜杠URL反而会报错。
