### ISSUE TITLE
sftp.cd方法 方法注释和实际效果不符

### ISSUE THREAD

**Issue by lydygg** [looly/hutool#2758]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.1 - 最新版本（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

Hutool在4.4.2版本中该方法如下
![image](https://user-images.githubusercontent.com/44763569/203890129-e1144abc-118d-4e8c-a622-d9caca3ab75f.png)
最近我们更新了5.7.1版本，发现该方法出现严重的使用问题，如图：
![image](https://user-images.githubusercontent.com/44763569/203890430-001cf89e-3b66-4db6-a339-e8348a777d2c.png)
方法注释说明：打开指定目录，如果指定路径非目录或不存在返回false
但是实际上方法如果不返回true，就会报错。但是直到最新版本此方法的方法注释都没有更改。

**Comment by looly** [comment]
5.8.11修改注释，感谢。
