### ISSUE TITLE
JSONUtil.formatJsonStr针对时间的处理破坏了原有的格式

### ISSUE THREAD

**Issue by winterallen** [looly/hutool#2763]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
升级到5.8.10之后JSONUtil.formatJsonStr针对时间的处理破坏了原有的格式，例如：`updateTime:2022-11-27 19:09:09.409`
格式化完之后`updateTime: 2022-11-27 19: 09: 09.409`，小时和分钟后面的":"加了空格，无法通过`yyyy-MM-dd HH:mm:ss.SSS`校验失败
1. 复现代码

```java
String str = "updateTime:2022-11-27 19:09:09.409";
JSONUtil.formatJsonStr(str);
```

**Comment by looly** [comment]
你是如何使用的？自定义了日期格式么？可否提供测试用例。

**Comment by lzwcyd** [comment]
你都不是json格式，为啥要这样调用呢？
String str = "{\"updateTime\":\"2022-11-27 19:09:09.409\"}";
JSONUtil.formatJsonStr(str);
这样输出的格式就没问题啊

**Comment by lzwcyd** [comment]
你都不是json格式，为啥要这样调用呢？
String str = "{\"updateTime\":\"2022-11-27 19:09:09.409\"}";
JSONUtil.formatJsonStr(str);
这样输出的格式就没问题啊

**Comment by looly** [comment]
@lzwcyd 原来是这样，我都搞蒙圈了，哈哈。
