### ISSUE TITLE
使用时的JDK版本问题

### ISSUE THREAD

**Issue by a852203465** [looly/hutool#2764]
### 版本情况

JDK版本：    jdk1.8.0_321
hutool版本： 5.8.10

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/33900410/204416862-1982ad21-7883-4585-906b-8ea36b16a09f.png)
1. 复现代码
从5.7.22升级到5.8.10时发现引用javax.* 已变为引用jakarta.*， 请麻烦在README中说明下大版本的最低JDK版本要求

**Comment by BingChunMoLi** [comment]
导入jakarta.validation-api 3.0.0以上版本呢
```xml
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>3.0.0</version>
</dependency>
```
validation-api 与jdk版本无关属于外部依赖，看下有没有兼容性问题

**Comment by a852203465** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/hutool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/hutool] 使用时的JDK版本问题 (Issue #2764)





 
导入jakarta.validation-api 3.0.0以上版本呢
 <dependency&gt;     <groupId&gt;jakarta.validation</groupId&gt;     <artifactId&gt;jakarta.validation-api</artifactId&gt;     <version&gt;3.0.0</version&gt; </dependency&gt;
 
validation-api 与jdk版本无关属于外部依赖，看下有没有兼容性问题
