### ISSUE TITLE
ImgUtil.read部分图片读取有误，相比原图旋转了90度

### ISSUE THREAD

**Issue by huangjianven** [looly/hutool#2765]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10

### 问题描述（包括截图）

1. 复现代码

```java
    public static void main(String[] args) {
        File file = FileUtil.file("C:\\Users\\Administrator\\Desktop\\61.jpg");
        BufferedImage read = ImgUtil.read(file);
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
原图片的分辨率为：4624 x 2600，ImgUtil.read(file)之后，图片的分辨率为2600 x 4624，图片躺平了，相比原图旋转了90度，用手机竖屏拍摄的图片可以重现
原图：
![61](https://user-images.githubusercontent.com/42291031/204691690-715c29d9-793a-4b29-ab1d-191a741438bb.jpg)
识别后的信息：
![image](https://user-images.githubusercontent.com/42291031/204691917-3b3bd214-2bb8-4907-8ebf-021d606c972a.png)

**Comment by ZZemptypoint** [comment]
不是旋转, 只是宽和高互换了, 你的图片有问题, 使用windows的画图打开 直接另存为jpg后, hutool读取新图就是正常的竖图, 说明工具类没问题.
hutool底层使用的是javax的ImageIO, 它从你的图中读到的宽高就是互换的, 从新图中读到的是正常的.

**Comment by looly** [comment]
之前有人提过类似问题，是图片中没有方向信息导致的。

**Comment by looly** [comment]
sorry这个issue处理了半年之久。

在用户的努力下，v6版本添加了图片元信息读取工具，可以识别图片的旋转角度，具体可以参考：

https://github.com/dromara/hutool/issues/2923

解决方案是：

```java
final File file = FileUtil.file("d:/test/204691690-715c29d9-793a-4b29-ab1d-191a741438bb.jpg");
final int orientation = ImgMetaUtil.getOrientation(file);
Img.from(file)
		.rotate(orientation)
		.write(FileUtil.file("d:/test/aaa.jpg"));
```
