### ISSUE TITLE
ListUtil.filter方法找不到

### ISSUE THREAD

**Issue by dzdzdzd123** [looly/hutool#2766]
请问文档中写道的ListUtil.filter方法在哪里可以找到？是不是还没添加？[ListUtil.java](https://gitee.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/collection/ListUtil.java)中没有找到这个方法！

文档地址：https://hutool.cn/docs/#/core/%E9%9B%86%E5%90%88%E7%B1%BB/%E5%88%97%E8%A1%A8%E5%B7%A5%E5%85%B7-ListUtil?id=%e8%bf%87%e6%bb%a4%e5%88%97%e8%a1%a8

**Comment by Createsequence** [comment]
用的已经是最新版本了吗？

**Comment by ZZemptypoint** [comment]
抱歉, 文档有点过时了, 更通用的filter方法在CollUtil中

**Comment by dzdzdzd123** [comment]
> 抱歉, 文档有点过时了, 更通用的filter方法在CollUtil中

嗯嗯 那就对了  感谢

**Comment by looly** [comment]
近期更新文档，感谢。
