### ISSUE TITLE
json序列化时，is开头的非boolean字段会变成null

### ISSUE THREAD

**Issue by geosmart** [looly/hutool#2768]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10

### 问题描述（包括截图）

1. 复现代码

```java
    class Pojo {
        var id: String? = null
        var isOk: Int? = null
    }

    @Test
    fun serialTest() {
        val pojo = Pojo().apply {
            id = "a"
            isOk = 1
        }
        val deSerialPojo = JSONUtil.toBean(JSONUtil.toJsonStr(pojo), Pojo::class.java)
        assertEquals(pojo.id, deSerialPojo.id)
        assertEquals(pojo.isOk, deSerialPojo.isOk)
    }

```

2. 堆栈信息
```
java.lang.AssertionError: 
Expected :1
Actual   :null
```

**Comment by looly** [comment]
看了下你使用的是Kotlin，我反编译了下，isOK生成的setter代码是：`setOk`，这个方法因该是`setIsOk`才对。

所以Hutool不识别。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/204784904-706f4868-5e6a-4b8a-a3df-0560f291b520.png)
![image](https://user-images.githubusercontent.com/1432613/204784935-9285e13a-dec8-4bde-9e9b-3568eb28d7ff.png)

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/204789297-eb5c96a6-f701-437d-9433-8e8672a90360.png)

**Comment by syzsh** [comment]
我也遇到了这个问题, 也可以通过如下方式解决:
```java
@get:JvmName("getIsXXX")
@set:JvmName("setIsXXX")
var isXXX:String? = null,
```
