### ISSUE TITLE
pressImage 添加图片水印 网络url无法读取

### ISSUE THREAD

**Issue by yisirman** [looly/hutool#2771]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.9

### 问题描述（包括截图）
当ImgUtil.read(FileUtil.file('xxxxx')) 其中的图片是网络url时，会报错 Can't read input file! 
跟踪代码发现好像文件读取权限问题？
当文件是本地绝对路径时，不会出现该问题

1. 复现代码

```java
ImgUtil.pressImage(
    FileUtil.file("d:/picTest/1.jpg"), 
    FileUtil.file("d:/picTest/dest.jpg"), 
    ImgUtil.read(FileUtil.file("d:/picTest/1432613.jpg")), //水印图片
    0, //x坐标修正值。 默认在中间，偏移量相对于中间偏移
    0, //y坐标修正值。 默认在中间，偏移量相对于中间偏移
    0.1f
);
```

**Comment by ZZemptypoint** [comment]
网络url呢? 是谁能访问的网络图片吗?

**Comment by yisirman** [comment]
> 网络url呢? 是谁能访问的网络图片吗?

是的，随便一张网络图
比如：https://img-blog.csdnimg.cn/20210714225920519.png

**Comment by yisirman** [comment]
已解决，网络URL请使用
ImgUtil.read(new URL("xxxx");
