### ISSUE TITLE
HttpUtil下载大文件问题

### ISSUE THREAD

**Issue by zhangpeibisha** [looly/hutool#2772]
private static HttpResponse requestDownload(String url, int timeout) {
		Assert.notBlank(url, "[url] is blank !");

		final HttpResponse response = HttpUtil.createGet(url, true)
				.timeout(timeout)
				.executeAsync();

		if (response.isOk()) {
			return response;
		}

		throw new HttpException("Server response error with status code: [{}]", response.getStatus());
	}

该方法原理是先将文件下载到内存然后再写入，该方法在下载小文件没问题，但是在下载大文件时，特别是集中下载大文件时会出现内存不够用的情况，从而导致服务崩溃。

**Comment by 928001955** [comment]
有FileUtil.downloadFile方法吧

**Comment by looly** [comment]
仔细看下executeAsync这个方法，叫做async就是请求后不读取响应体内容，通过获取流来完成读取。
