### ISSUE TITLE
CacheUtil 获取空值判断 CacheObj 不为空但是内部值object为空的情况应该不走缓存

### ISSUE THREAD

**Issue by cyao2q** [looly/hutool#2773]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![1669967085605](https://user-images.githubusercontent.com/10820724/205242645-50ac90e7-6e47-4f58-87fc-7b50c50f2b21.jpg)

```java
Console.log("报错了");

这种场景应该重新调用实际方法的 但是这个null判断不包含CacheObj里面的object是否为空

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by ZZemptypoint** [comment]
你的意思是缓存中key存在， 但是它关联的value是null， 这个时候你希望它使用supplier.get()的值去替换缓存的value？

**Comment by cyao2q** [comment]
> 你的意思是缓存中key存在， 但是它关联的value是null， 这个时候你希望它使用supplier.get()的值去替换缓存的value？

是的，我目前是覆盖了源码使用 判断null=co.getObj()

**Comment by ZZemptypoint** [comment]
这个使用逻辑是不合理的, 没有哪个缓存会这样设计, 如果一定要这样用确实只能覆盖源码

**Comment by cyao2q** [comment]
> 这个使用逻辑是不合理的, 没有哪个缓存会这样设计, 如果一定要这样用确实只能覆盖源码

源码第一行V v = get(key, isUpdateLastAccess);获取的就是CacheObj对象属性obj的值
所以代码走到了下一行但是仅仅判断了null == co || co.isExpired() 如果不判断 co.getValue()又何必走到第一个if语句里面 
看我截图 当 key =间谍过家家 对应的CacheObj不为空 （但是属性obj为空的情况） 会每次走到
if (null == v && null != supplier) {
但是并没有去调用 v = supplier.call(); 

所以 我认为 代码 应该是这样的 
```
if (null == co || co.isExpired() || null == co.getValue()) {
                    try {
                        v = supplier.call();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                    put(key, v, this.timeout);
                } else {
                    v = co.get(isUpdateLastAccess);
                }
```

**Comment by cyao2q** [comment]
当然只是个人建议，看您是否有出于其他的考虑

**Comment by ZZemptypoint** [comment]
哦哦, 你是想要Map.computeIfAbsent()的效果, 它确实会在value为null时直接用新值替换

**Comment by zhrgithub** [comment]
不接受你的建议发自我的 iPhone在 2022年12月3日，15:47，Sky ***@***.***> 写道：﻿
当然只是个人建议，看您是否有出于其他的考虑

**Comment by looly** [comment]
@cyao2q 当value为null的时候，此时值虽然是null，但是这个值是实际存在的，不会穿透缓存而执行`supplier`。

在第一重判断中返回null有两种情况：

1. 值不存在，此时会进入双重检查，执行`supplier`，这个没问题。
2. 值存在但是为null，此时进入双重检查，检查发现值是存在的，跳过返回null。

其实你的疑问在于，为何不在第一次就判断CacheObj而是判断value？

这主要是为了代码复用。

你可以看到AbstractCache有两个子类，分别使用ReentrantLock和StampLock实现锁，因此此处为了复用get方法，采取这种策略。

理论上只是多了一次判断，并不会穿透。

**Comment by cyao2q** [comment]
那可以考虑加一个 类似Map.computeIfAbsent()的方法 因为值虽然是null 对某些场景是没有意义的

**Comment by ZZemptypoint** [comment]
> 那可以考虑加一个 类似Map.computeIfAbsent()的方法 因为值虽然是null 对某些场景是没有意义的

@looly 是的, 我也感觉可以加, jdk的`Map.computeIfAbsent()`就会在value为null时直接用新值替换, 不论key存不存在

**Comment by looly** [comment]
@ZZemptypoint 那就pr to v6吧~~

**Comment by ZZemptypoint** [comment]
> @ZZemptypoint 那就pr to v6吧~~

ok
