### ISSUE TITLE
关于HttpRequest对象问题

### ISSUE THREAD

**Issue by lyxlucky** [looly/hutool#2775]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

HttpRequest对象服务器上请求无输出，本地机器无问题，线上环境有问题
关键代码：
location为经纬度 示例值：28.18644,112.952042
服务器配置为2核2g

1. 复现代码

```
public static final String GET_ADDRESS_URL = "https://api.xxxxxx.com/api/location/?location=";
String address = UnicodeUtil.toString(HttpRequest.get(XiaoBeiConstant.GET_ADDRESS_URL + location)
                 .execute()
                 .body());
```

2. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
尝试在服务端使用curl请求试下看是否可达。

怀疑网络问题。

**Comment by looly** [comment]
修改了你的问题，把API地址隐藏了。下次提issue注意隐私保护。

**Comment by looly** [comment]
如果没有解决，再打开issue补充信息吧。如服务端的curl信息。

**Comment by lyxlucky** [comment]
![image](https://user-images.githubusercontent.com/59909125/205826522-a642b236-6941-425d-846f-6f9a7343298e.png)
服务端curl请求
网络无问题

**Comment by looly** [comment]
@lyxlucky 不太好复现你的问题。尝试自定义下`User-Agent`看是否可以。
