### ISSUE TITLE
时间轮对于任务取消的支持

### ISSUE THREAD

**Issue by joelzzhang** [looly/hutool#2776]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
hutool里面提供的时间轮算法中，如何取消已加入时间轮的任务，让它不会被执行呢
1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
哪个类？

**Comment by looly** [comment]
这个暂时不支持移除任务。
