### ISSUE TITLE
RedisDS 连接池问题

### ISSUE THREAD

**Issue by matrixd2** [looly/hutool#2778]
### 版本情况

JDK版本：    openjdk_1.8.0_345
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

jedis 连接意外中断，RedisDS 类里边JedisPool成员属性为私有访问且没有提供相应的方法将jedis归还到Jedis连接池

https://github.com/dromara/hutool/blob/v5-master/hutool-db/src/main/java/cn/hutool/db/nosql/redis/RedisDS.java

![image](https://user-images.githubusercontent.com/15178537/205926937-fe12f64f-8fb8-4aa2-913f-e0fb1ca3dfe2.png)

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
调用Jedis对象的close方法即可。

**Comment by matrixd2** [comment]
> 调用Jedis对象的close方法即可。

通过静态方法create创建的RedisDS实例，调用方法`getStr` 和 `setStr` 这两个实例方法并没有返回jedis对象这种怎么处理呢？
