### ISSUE TITLE
RedisDS.java 存在指令操作后，无法释放 jredis 资源的问题

### ISSUE THREAD

**Issue by roamdy** [looly/hutool#2779]
![image](https://user-images.githubusercontent.com/15623964/206068373-ecf12de5-5574-46e7-877f-d812305c72c0.png)

**Comment by cyao2q** [comment]
```
try (Jedis jedis = getJedis()) 
```
这种写法就会自动调用jedis.close();啊

**Comment by roamdy** [comment]
> 

感谢回复
