### ISSUE TITLE
ClassPathResource使用的问题

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#278]
`          ClassPathResource resource = new ClassPathResource(fileName);
           Path keyPath = Paths.get(resource.getAbsolutePath());
           keyBytes = Files.readAllBytes(keyPath);`

通过ClassPathResource来读取项目classpath文件的信息，然后resource.getAbsolutePath()获取到绝对路径进行读取操作。正常在tomcat部署项目的情况下，没有任何问题。

但是使用springboot开发项目，产物为jar，然后放到服务器上，在运行的时候，jar包中的路径，就无法读取到，路径是这样的：/opt/v70/api/buyer/buyer-api-7.0.0.jar!/BOOT-INF/classes!/aes.key

请问这种情况使用hutool是否有解决方案

**Comment by looly** [comment]
在jar情况下这个类不能这么用需要getStream获取文件的数据流然后处理。jar中的路径无法直接读取

**Comment by gpqhl0071** [comment]
> 在jar情况下这个类不能这么用需要getStream获取文件的数据流然后处理。jar中的路径无法直接读取

我目前改用这种方式：
InputStream is = PathUtil.class.getResourceAsStream("/aes.key");

**Comment by looly** [comment]
一样的，ClassPathResource.getStream也是封装的这个。

**Comment by gpqhl0071** [comment]
> 一样的，ClassPathResource.getStream也是封装的这个。

已解决，非常感谢。

**Comment by xkcoding** [comment]
感谢！
