### ISSUE TITLE
[文档]Lambda单词错误

### ISSUE THREAD

**Issue by YonChun** [looly/hutool#2781]
### 版本情况

hutool版本： 5.8.10

### 问题描述
单词拼写错误
复现：
对象工具-ObjectUtil
[错误链接](https://hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E5%AF%B9%E8%B1%A1%E5%B7%A5%E5%85%B7-ObjectUtil?id=%e6%96%b9%e6%b3%95)

<img width="743" alt="image" src="https://user-images.githubusercontent.com/27072445/206103954-150eca6e-6360-4475-8726-70d039a4912f.png">

**Comment by ZZemptypoint** [comment]
感谢指正

**Comment by looly** [comment]
稍后修复。
