### ISSUE TITLE
希望适配springboot3

### ISSUE THREAD

**Issue by falcon-jin** [looly/hutool#2782]
希望适配springboot3比如ServletUtil

**Comment by vnobo** [comment]
这要升级最低jdk为 17,很多API 就不能用了

**Comment by ZZemptypoint** [comment]
> 希望适配springboot3比如ServletUtil

请看这个issue [目前有计划考虑支持 SpringBoot 3 吗？](https://gitee.com/dromara/hutool/issues/I633IX#note_14710646_link)
