### ISSUE TITLE
使用CsvRowHandler读取平均3g多的csv文件，也出现了Java内存溢出异常

### ISSUE THREAD

**Issue by GankGintama** [looly/hutool#2783]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.4.0

1. 截图

![image](https://user-images.githubusercontent.com/33503325/206138490-84e424f7-fd82-419c-8bf4-67526ef89841.png)

**Comment by GankGintama** [comment]
5.8.10的版本也有这种情况

**Comment by GankGintama** [comment]
在CsvParser.java 新增一句代码 ，验证并解决了这个问题 麻烦大佬看下这样子 是否可行
![image](https://user-images.githubusercontent.com/33503325/206413084-6e0d9749-97c6-473b-8201-eba2196b2fab.png)

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/206438469-0fdd748f-80f6-4348-8780-6132efbc79c4.png)

经过测试，并没有出现溢出的情况啊，你的使用方法是否有问题？

**Comment by looly** [comment]
如果还有问题，麻烦附上测试代码并打开此issue，我这边继续测试。

**Comment by GankGintama** [comment]
因为我们的csv文档没有贵方 发现csv文档有特殊符号 ‘“文本’ CsvParser就一直读取 导致内存溢出  我想问下 这个工具默认是不是把”当作转义字符处理呢

**Comment by looly** [comment]
@GankGintama 有可能。双引号默认包装一个大文本（如一个字段中有换行符的情况），但是如果这个双引号不是成对出现的，就会出现一直读一个字段的问题，那确实会溢出。

如果不想处理双引号，可以`CsvConfig.setTextDelimiter`方法自定义一个其他字符即可。
