### ISSUE TITLE
关于RedisDS类中的的pool重复创建的问题

### ISSUE THREAD

**Issue by ctrl-cli** [looly/hutool#279]
您好，请问下：
文档中说每次只需要调用下面即可：
`Jedis jedis = RedisDS.create().getJedis();`

比如我都：
try(Jedis jedis = RedisDS.create().getJedis()){

}
如果在代码证每次需要调用redis都执行这个代码不就是相当于每次都创建一个新的pool吗？

谢谢！还是有其他的调用方法？

比如需要单例类Singleton来包装下RedisDS的实例呢。

**Comment by looly** [comment]
RedisDS最好单例使用，可以使用Singleton.get单例获取。
