### ISSUE TITLE
HttpRequest请求日志

### ISSUE THREAD

**Issue by j4vvy** [looly/hutool#2791]
如何查看HttpRequest的请求日志

**Comment by looly** [comment]
没办法查看。

Hutool封装的HttpUrlConnection，没有提供日志监听。

**Comment by j4vvy** [comment]
作者你好，HttpRequest/HttpResponse 的 toString() 方法不就能查看吗？自己写的都忘记了。^_^

**Comment by looly** [comment]
@hou-nevermore 这个方法只是打印你设置的请求参数，实际的请求报文是看不到的。
