### ISSUE TITLE
NamedSql 的in问题

### ISSUE THREAD

**Issue by zyzyzy523** [looly/hutool#2792]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

如果查询是select * from user where id IN (:ids)；
这样的话 namedSql得到的参数不正确，因为 NamedSql中 replaceVar方法只对小写的in做了操作

![image](https://user-images.githubusercontent.com/48322364/206676826-713cab27-0c7a-437b-89e3-aa02cbf5e5b9.png)

**Comment by looly** [comment]
感谢，5.8.11修复此问题。

**Comment by zyzyzy523** [comment]
> 感谢，5.8.11修复此问题。

感谢，建议这里的IN对集合类型的参数进行适配

**Comment by looly** [comment]
@zyzyzy523 集合支持在v6版本中支持。
