### ISSUE TITLE
cn.hutool.core.convert.Convert.chineseMoneyToNumber()整数部分int越界

### ISSUE THREAD

**Issue by imarkofu** [looly/hutool#2793]
### 版本情况
5.8.10

### 问题描述（包括截图）

1. 复现代码

```java
cn.hutool.core.convert.Convert.chineseMoneyToNumber()
整数部分会有int越界问题
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
确实存在可能越界问题。

考虑不要使用这个方法处理超大金额。

此问题可能会在v6版本中解决，感谢。
