### ISSUE TITLE
Hutool-db模块使用问题

### ISSUE THREAD

**Issue by artillerymans** [looly/hutool#2794]
### 版本情况

JDK版本：    openjdk_11
hutool版本： last_version（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
背景：最近在看Compose for DeskTop这块的，我不是很明白Db模块是怎么用的，我按照文档集成到项目后创建数据库直接报错，有没有从0构建的那种demo参考一下， 我之前一直搞移动端的 不是很懂这个配置

1. 复现代码

```java
Console.log("报错了");

![image](https://user-images.githubusercontent.com/16060581/206685138-608a65d3-e419-4169-8664-efdf3ad913c0.png)

![image](https://user-images.githubusercontent.com/16060581/206685167-263eb31d-2a60-4f2f-ad07-8db52f7be02c.png)

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by artillerymans** [comment]
![image](https://user-images.githubusercontent.com/16060581/206685259-703a857c-a28f-45ef-ad39-e2adda246b74.png)

**Comment by artillerymans** [comment]
![image](https://user-images.githubusercontent.com/16060581/206685305-8715dddf-e06b-47fd-a583-967528b8a8b5.png)

**Comment by looly** [comment]
见文档：https://hutool.cn/docs/#/db/%E6%A6%82%E8%BF%B0
