### ISSUE TITLE
FileUtil.getMimeType无法获取常用的word、excel文件类型

### ISSUE THREAD

**Issue by zhangdp** [looly/hutool#2795]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

System.out.println(FileUtil.getMimeType("a.docx"));
System.out.println(FileUtil.getMimeType("a.doc"));
System.out.println(FileUtil.getMimeType("a.xls"));
System.out.println(FileUtil.getMimeType("a.xlsx"));
System.out.println(FileUtil.getMimeType("a.ppt"));
System.out.println(FileUtil.getMimeType("a.pptx"));

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/26567414/206957325-4b4a8f46-4242-4f57-a7df-aa452f77c2d3.png">

FileUtil.getMimeType无法获取常见的word、excel、ppt文件类型，是否是因为本机没有装office软件才识别不出来？是的话不都是部署运行在linux系统下的要如何解决？只能改代码手动加上类型了吗？

**Comment by ZZemptypoint** [comment]
5.8.10中无法复现你的问题, 请先排查一下文件是否正常.
hutool底层使用的是java.net.URLConnection来判断文件类型, 并没有依赖office相关组件:
```java
String contentType = URLConnection.getFileNameMap().getContentTypeFor(filePath);
```

**Comment by zhangdp** [comment]
> 5.8.10中无法复现你的问题, 请先排查一下文件是否正常. hutool底层使用的是java.net.URLConnection来判断文件类型, 并没有依赖office相关组件:
> 
> ```java
> String contentType = URLConnection.getFileNameMap().getContentTypeFor(filePath);
> ```

你可以试下在mac环境下运行的结果，同样代码在win环境是有值的，但是在mac环境下运行结果却为null，所以我才问是不是需要先在系统安装office软件。也不是文件是否正常的问题，是构造的文件名而已，就算传参真实文件路径也是null

**Comment by looly** [comment]
@zhangdp 可能是JDK版本问题。没有提供对应的类型。

麻烦打印下：`URLConnection.getFileNameMap()`

**Comment by looly** [comment]
我猜可能openJDK预制的getFileNameMap中没有这些个类型，考虑自行做个补充判断吧。
