### ISSUE TITLE
验证码及其不灵活，部分字母还会超出边界

### ISSUE THREAD

**Issue by guoping007** [looly/hutool#280]
默认的几个验证码居然不能设置生成器，默认生成器o和0，1和l及其难识别，想去掉只能自己拷贝代码写，g这种字符还经常出现看不到下半截的情况。

**Comment by looly** [comment]
1和I的问题来自于字体，请自定义字体。

超出边界问题尝试新版本，最近我也会做更多测试。

**Comment by guoping007** [comment]
最主要的问题，使用默认的验证码无法指定生成器
