### ISSUE TITLE
节日

### ISSUE THREAD

**Issue by cn-src** [looly/hutool#2800]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
能支持常规的节日么，比如：端午，中秋，春节等等。
是节日，不是放假。

**Comment by ZZemptypoint** [comment]
你试试`ChineseDate.getFestivals()` 和 `LunarFestival.getFestivals()`能不能满足你的需要
