### ISSUE TITLE
适配jakarta.servlet-api

### ISSUE THREAD

**Issue by dfengwei** [looly/hutool#2802]
### 版本情况

JDK版本：openjdk-17.0.5.0.8-2
tomcat版本：10.0.27
springframework版本：6.0.2
hutool版本：5.8.10

### 问题描述

springframework6和tomcat10已经将javax.servlet-api更改为jakarta.servlet-api，ServletUtil是否可做相应的适配？

**Comment by ZZemptypoint** [comment]
请看这个issue [目前有计划考虑支持 SpringBoot 3 吗？](https://gitee.com/dromara/hutool/issues/I633IX#note_14710646_link)
