### ISSUE TITLE
JSONUtil.toJsonStr() 传参为整数类型

### ISSUE THREAD

**Issue by kk1234kk4321** [looly/hutool#2803]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![截图](https://user-images.githubusercontent.com/11435815/207269634-fa0b98ad-d94b-4899-923d-9efc0283fd10.png)

1. 复现代码

JSONUtil.toJsonStr(1);

输出结果为"{}"

**Comment by ZZemptypoint** [comment]
你期望它返回什么?

**Comment by looly** [comment]
你可能想像FastJSON一样返回原值。但是事实上返回原值是错误的，结果非JSON类型吗，会导致错误。
