### ISSUE TITLE
RuntimeUtil.execForStr 在linux下执行命令不成功

### ISSUE THREAD

**Issue by jezzhu** [looly/hutool#2809]
### 版本情况

JDK版本：    jdk1.8.0
hutool版本： 5.7.22
系统环境： centos7.6

### 问题描述（包括截图）
RuntimeUtil.execForStr(exePath + cmdArgs);  执行命令过程莫名无法执行
如图下所示
![image](https://user-images.githubusercontent.com/13492095/207749216-ddecde27-e178-4de9-a529-30b6b5b8b706.png)

而手动执行命令就可以正常执行
![image](https://user-images.githubusercontent.com/13492095/207750514-2e78ba1d-1eda-4ef6-bfaa-e1b474283d7e.png)

后来采用java 原始的Runtime 也能正常执行得到wav文件
```
try {
	Runtime.getRuntime().exec(exePath + cmdArgs);
}catch (Exception e){
	log.error("执行命令失败",e);
	needRetry =false;
}
```

其中 exePath + cmdArgs 就是 第二张图选中的命令 也是 /tmp/jave/ffmpeg-amd64-3.3.1 -ar 16000 -ac 2 -f s16le -y -i /home/audio/xxxxx.pcm  -ar 8000 -ac 2  /home/audio/xxxx.wav

另外，在windows环境下RuntimeUtil.execForStr(exePath + cmdArgs);  是可以正常执行的

**Comment by looly** [comment]
execForStr传入一个参数数组，尝试将各个参数分开传入试下：

```java
RuntimeUtil.execForStr("/tmp/jave/ffmpeg-amd64-3.3.1", "-ar", ....)
```

hutool默认对参数做了分割，可能这个分割规则并不适合这个命令……只能用原生方式了。
