### ISSUE TITLE
QrCodeUtil生成带LOGO的二维码很丑,希望能给LOGO加上白边

### ISSUE THREAD

**Issue by cj506817364** [looly/hutool#281]
对比下面两张图可以看出,微信生成的二维码有添加白边,十分美观
我使用QrCodeUtil生成的二维码
<img width="456" alt="3df7f0c28e27b46469891f63760a62d7" src="https://user-images.githubusercontent.com/33059555/53717128-28abb600-3e92-11e9-98e1-55a91aa98bd1.png">
 
下面是微信生成的二维码
![460fc95e1010a3a7ab23990a56db0a84](https://user-images.githubusercontent.com/33059555/53717169-3e20e000-3e92-11e9-8a04-db7345132e11.png)

**Comment by looly** [comment]
描边和圆角Hutool暂时都没有封装，这个我需要找下，暂缓。

**Comment by looly** [comment]
4.5.3做了圆角处理，描边暂时做不了。欢迎提供思路。
