### ISSUE TITLE
excel工具bug，超过一百行数据会导致单元格无法自适应宽度

### ISSUE THREAD

**Issue by qq420100523** [looly/hutool#2810]
### 版本情况

JDK版本：    openjdk_1.8.0_292
hutool版本： 5.8.10（最新版本）

### 问题描述（包括截图）

1. 复现代码

```java
	@Test
	public void excelWriterAutoSizeColumnAllTest() {
		String filePath = "/Users/zengzw/Downloads/test.xlsx";
		List<Map<String, Object>> list = new ArrayList<>();
//		int size = 99;
		int size = 100;
		for (int i = 0; i < size; i++) {
			HashMap<String, Object> map = new HashMap<>();
			map.put("test", "tttttttttttttttttttttttttttttt");
			list.add(map);
		}
		BigExcelWriter bigWriter = ExcelUtil.getBigWriter(filePath);
		bigWriter.write(list);
		// 超过一百行数据，autoSizeColumnAll()将会失效
		bigWriter.autoSizeColumnAll();
		bigWriter.flush();
		bigWriter.close();
	}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
bigWriter.write(list); -> SXSSFSheet.createRow() -> SXSSFSheet.flushRows()
BigExcelWriter.autoSizeColumnAll() -> ExcelBase.getColumnCount()
因为SXSSFSheet类的属性private int _randomAccessWindowSize = 100;当数据write满一百后会flush firstRow，导致ExcelBase.getColumnCount()返回-1

**Comment by looly** [comment]
BigExcelWriter有窗口大小，因此只对窗口中的数据有效。要么不用这个，要么调整增加窗口大小。
