### ISSUE TITLE
缺少矩阵运算相关方法

### ISSUE THREAD

**Issue by warmbraw2002** [looly/hutool#2813]
### 版本情况

JDK版本：    openjdk-16 16.0.2
hutool版本： 5.8.10

### 问题描述（包括截图）

在项目中缺少矩阵运算相关的方法，例如矩阵的加、减、乘、除、转置、求逆等等

**Comment by CherryRum** [comment]
这个暂时没什么好的想法，6.0可能会加

**Comment by looly** [comment]
回复见：https://github.com/dromara/hutool/pull/2814
