### ISSUE TITLE
db.Insert()在ojdbc6中不可用

### ISSUE THREAD

**Issue by jackhb1999** [looly/hutool#2815]
### 版本情况

JDK版本：    openjdk_8_201
jdbc: ojdbc6-11.2.0
hutool版本： 5.7.14

### 问题描述

1. 复现代码

```java
use. Insert(entity);
```
无法添加，报数组越界。可在文档提示ojdbc7可用。

**Comment by jackhb1999** [comment]
SqlBuilder builder = new SqlBuilder();
SqlBuilder insert = builder.insert(entity);
String s = insert.toString();
Object[] paramValueArray = insert.getParamValueArray();
use. Execute(s,paramValueArray);

我尝试绕开

**Comment by jackhb1999** [comment]
`
/**
 * @author jack
 * @date 2022/12/20 9:31
 * @description: ojdbc6 有问题 db.insert() 不能用
 */
public class InsertUtil {

    public void insert(Entity entity) throws SQLException {
        Db db = HutoolDbConfig.getDb();
        SqlBuilder builder = new SqlBuilder();
        SqlBuilder insert = builder.insert(entity);
        String str = insert.toString();
        List<Object> paramValues = insert.getParamValues();
        String[] strings = Convert.toStrArray(paramValues);
        String replaceStr = StrUtil.replace(str, "?", "'{}'");
        String formatStr = StrUtil.format(replaceStr, strings);
        db.execute(formatStr);
    }
}
`
虽然这样局限更大，但先跑着

**Comment by jackhb1999** [comment]
/**
     * 返回 PageResult 的列表及相关翻页信息
     * @param result PageResult实例
     * @return
     */
    public static Map resultMap(PageResult result) {
        HashMap pageMap = new HashMap();
        if(result != null) {
            pageMap.put("list", toKeyMapList(result));
            // 页码
            pageMap.put("pageNumber", result.getPage());
            // 一页多少内容
            pageMap.put("pageSize", result.getPageSize());
            // 总条  (第一页 PageResult,getTotal() 条目小于pageSize的不准确)
            if(result.getPage() == 0 && result.size() < result.getPageSize()){
                pageMap.put("total", result.size());
            }else {
                pageMap.put("total", result.getTotal());
            }
        }
        return pageMap;
    }




result.getTotal() 不准确

**Comment by looly** [comment]
@jackhb1999 麻烦提供下完整堆栈看下哪里的问题。

盲猜你传入了数组类的参数，但是驱动不支持这个类型的参数。

补充后打开此issue。
