### ISSUE TITLE
参考文档的jedis版本建议修正

### ISSUE THREAD

**Issue by boronga** [looly/hutool#2819]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
RedisDS.create().del("1");
```

2. 堆栈信息
java.lang.NoSuchMethodError: redis.clients.jedis.Jedis.del([Ljava/lang/String;)J

3. 来源
https://hutool.cn/docs/#/db/NoSQL/Redis%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B0%81%E8%A3%85-RedisDS

4. 建议
修改页面. jedis版本修改为4.2.3

**Comment by looly** [comment]
感谢意见。此处文档近期修正。

PS： v6版本Jedis相关会删掉。
