### ISSUE TITLE
验证码能否加入加减乘除的验证码？

### ISSUE THREAD

**Issue by david1025** [looly/hutool#282]

**Comment by looly** [comment]
4.5.1增加支持。

```java
// 定义图形验证码的长和宽
LineCaptcha lineCaptcha = CaptchaUtil.createLineCaptcha(200, 100);
lineCaptcha.setGenerator(new MathGenerator());
lineCaptcha.write("e:/code.png");
```

**Comment by david1025** [comment]
> 4.5.1增加支持。
> 
> ```java
> // 定义图形验证码的长和宽
> LineCaptcha lineCaptcha = CaptchaUtil.createLineCaptcha(200, 100);
> lineCaptcha.setGenerator(new MathGenerator());
> lineCaptcha.write("e:/code.png");
> ```

老哥，4.5.1啥时候发布？
