### ISSUE TITLE
使用FileTypeUtil判断wav后缀的录音文件类型，没有匹配到

### ISSUE THREAD

**Issue by yanjingfan** [looly/hutool#2821]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.3.10

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/37790182/208848715-6d72ba09-791b-4701-9a3a-bc932a49957c.png)

经过测试，不同的wav文件，文件流头部16进制字符串格式为
```txt
52494646xxxxxxxx57415645666D74201200000006000100401F0000
```
中间的8个x都不同，下面FileTypeUtil类中fileTypeMap这么写，应该是不对的
```java
fileTypeMap.put("52494646e27807005741", "wav"); // Wave (wav)
```

3. 测试涉及到的文件，下面的测试文件下载有效期：`2022:12:18 16:11:53`
[http://120.24.173.36:9000/sinvie/sinvie-steward/server/2022/1215/20221221145616271.wav](http://120.24.173.36:9000/sinvie/sinvie-steward/server/2022/1215/20221221145616271.wav)

**Comment by CherryRum** [comment]
嗯确实有问题，第5-8为File size

**Comment by CherryRum** [comment]
2023年前优化下这个类
