### ISSUE TITLE
ExcelUtil读取服务器共享盘文件，碰见双斜杠始终自动转义成单斜杠

### ISSUE THREAD

**Issue by Hy961919621** [looly/hutool#2829]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
读取//172.18.18.121服务器上的excel文件，路径会变成 
 `\172.18.18.121\c\C8Export\beiliaozhongxin\STNAViewer_beiliaozhongxin_HSE.xlsx`
而不是我想要的
` \\172.18.18.121\c\C8Export\beiliaozhongxin\STNAViewer_beiliaozhongxin_HSE.xlsx`
（ip地址前面应该是双斜杆）导致读取报错，不太清楚要怎么解决这个问题。
![image](https://user-images.githubusercontent.com/58396951/209609465-d6eba216-5bd6-423c-ae4c-0537e5270a8f.png)
![image](https://user-images.githubusercontent.com/58396951/209609489-84e487ab-df24-4cbe-ac75-cd13f78b4851.png)

1. 复现代码

```java

ExcelReader reader = ExcelUtil.getReader("//172.18.18.121/c/C8Export/beiliaozhongxin/STNAViewer_beiliaozhongxin_HSE.xlsx");
// ExcelReader reader = ExcelUtil.getReader("E://STNAViewer_beiliaozhongxin_HSE.xlsx");
List<List<Object>> read = reader.read();
System.out.println(read);

```

**Comment by ZZemptypoint** [comment]
问题描述中的两个路径为什么是一样的?

**Comment by Hy961919621** [comment]
问题描述中的双斜杆被转为单斜杆

**Comment by ZZemptypoint** [comment]
ok, 帮你修改了描述

**Comment by Hy961919621** [comment]
> ok, 帮你修改了描述

谢谢

**Comment by Hy961919621** [comment]
试过`\\\\`和各种字符串拼接，还是读取不到正确的路径，读取本地盘文件没有问题

**Comment by ZZemptypoint** [comment]
经过询问, ExcelUtil不支持从url中读取文件流

**Comment by Hy961919621** [comment]
> 经过询问, ExcelUtil不支持从url中读取文件流

那我如要读取这个路径，应该可以怎么样操作，用FileUtil先把File读取出来，然后读取这个File吗

**Comment by CherryRum** [comment]
> > 经过询问, ExcelUtil不支持从url中读取文件流
> 
> 那我如要读取这个路径，应该可以怎么样操作，用FileUtil先把File读取出来，然后读取这个File吗

您使用是``` SMB协议```
需要先读出来文件信息，之后和本地文件没有区别,读取方法多种，请注意自己的路径不能有空格

```java

public static void main(String[] args) throws MalformedURLException, URISyntaxException {
		//file 协议 \\192.168.1.26\编程资源-pdf文档\LeetCode
		URL url = new URL("file://192.168.1.26/编程资源-pdf文档/LeetCode");
		File file = Paths.get(url.toURI()).toFile();
		System.out.println(Arrays.toString(file.list()));
	}
```
![image](https://user-images.githubusercontent.com/24296698/209610809-4c1c4a52-bdb6-43db-b490-2e685fcf9375.png)

**Comment by Hy961919621** [comment]
感谢！这个方法可以

**Comment by Hy961919621** [comment]
> > > 经过询问, ExcelUtil不支持从url中读取文件流
> > 
> > 
> > 那我如要读取这个路径，应该可以怎么样操作，用FileUtil先把File读取出来，然后读取这个File吗
> 
> 您使用是` SMB协议` 需要先读出来文件信息，之后和本地文件没有区别,读取方法多种，请注意自己的路径不能有空格
> 
> ```java
> public static void main(String[] args) throws MalformedURLException, URISyntaxException {
> 		//file 协议 \\192.168.1.26\编程资源-pdf文档\LeetCode
> 		URL url = new URL("file://192.168.1.26/编程资源-pdf文档/LeetCode");
> 		File file = Paths.get(url.toURI()).toFile();
> 		System.out.println(Arrays.toString(file.list()));
> 	}
> ```
> 
> ![image](https://user-images.githubusercontent.com/24296698/209610809-4c1c4a52-bdb6-43db-b490-2e685fcf9375.png)

感谢！这个方法可以

**Comment by CherryRum** [comment]
使用如下也行,注意此处三个`/`
```java
File file1 = FileUtil.file(URLUtil.toURI("file:///192.168.1.26/编程资源-pdf文档/LeetCode"));
		System.out.println(file1);
```
