### ISSUE TITLE
请问ThreadUtil.execute() 和 ThreadUtil.excAsync()的区别是什么？

### ISSUE THREAD

**Issue by VanMesure** [looly/hutool#283]
官方文档介绍一个是在公共线程池执行线程，一个是执行异步线程， 我有点看不明白呢，能不能稍微说明一下，非常感谢（＾∀＾●）ﾉｼ

**Comment by looly** [comment]
前者是放到线程池中执行，后者是直接新建一个线程。

Callable参数是支持回调的，返回Future对象，用于想获取线程执行结果的环境。
