### ISSUE TITLE
使用DateUtil.parse()方法，五分钟都没有执行完毕

### ISSUE THREAD

**Issue by vxinv** [looly/hutool#2830]
### 版本情况

JDK版本：    openjdk_8_232
hutool版本： 5.7.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
调试代码的时候，使用DateUtil.parse()方法，五分钟都没有执行完毕，发现堆栈太深

1. 复现代码

```java
DateUtil.parse(“2022-10-14”)
```

2. 堆栈信息
![af68a29d9758a791f90faa25f41bd68](https://user-images.githubusercontent.com/31587597/209648598-837e1da3-7d39-40e0-9902-9d1beb14a097.jpg)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个方法应该是没有问题的，请：

1. 升级hutool到最新尝试
2. 麻烦贴下你的batch代码，我这边测试。

补充内容后再打开此issue。
