### ISSUE TITLE
数字转人民币大写问题

### ISSUE THREAD

**Issue by 13051856722** [looly/hutool#2833]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.10

### 问题描述（包括截图）

复现代码

```java
String s = Convert.numberToChinese(1205623, true);
System.out.println(s);
```

 问题描述：显示的人民币大写：不应该有“零”
代码错误结果：壹佰贰拾万零伍仟陆佰贰拾叁
期望正确结果：壹佰贰拾万伍仟陆佰贰拾叁

**Comment by ZZemptypoint** [comment]
从我查到的资料来看，这个零可写可不写，有些在线工具是写了， 有些又没有，特别的是Excel是没写，但是它们不够权威。或许你可以提供更专业的资料来证明这是不合规的。
[人民币大写在线转换工具](https://tool.gaodun.com/rmb.html)

>三、阿拉伯数字小写金额数字中有“0”时，中文大写应按照汉语语言规律、金额数字构成和防止涂改的要求进行书写。举例如下： 1、阿拉伯数字中间有“0”时，中文大写要写“零”字，如￥1409.50应写成人民币壹仟肆佰零玖元伍角； 2、阿拉伯数字中间连续有几个“0”时、中文大写金额中间可以只写一个“零”字，如￥6007.14应写成人民币陆仟零柒元壹角肆分。 3、阿拉伯金额数字万位和元位是“0”，或者数字中间连续有几个“0”，万位、元位也是“0”但千位、角位不是“0”时，中文大写金额中可以只写一个零字，也可以不写“零”字，如￥1680.32应写成人民币壹仟陆佰捌拾元零叁角贰分，或者写成人民币壹仟陆佰捌拾元叁角贰分。又如￥107000.53应写成人民币壹拾万柒仟元零伍角叁分，或者写成人民币壹拾万零柒仟元伍角叁分。 4、阿拉伯金额数字角位是“0”而分位不是“0”时，中文大写金额“元”后面应写“零”字，如￥16409.02应写成人民币壹万陆仟肆佰零玖元零贰分，又如￥325.04应写成人民币叁佰贰拾伍元零肆分。

**Comment by CherryRum** [comment]
@ZZemptypoint @13051856722 
这两个都可以
出自中国人民银行规定
银行、单位和个人填写的各种票据和结算凭证是办理支付结算和现金收付的重要依据，直接关系到支付结算的准确、及时和安全。票据和结算凭证是银行、单位和个人凭以记载帐务的会计凭证，是记载经济业务和明确经济责任的一种书面证书。因此，填写票据和结算凭证，必须做到标准化、规范化，要要素齐全、数字正确、字迹清晰、不错漏、不潦草，防止涂改。

 一、中文大写金额数字应用正楷或行书填写，如壹（壹）、贰（贰）、叁（叁）、肆（肆）、伍（伍）、陆（陆）、柒、捌、玖、拾、佰、仟、万（万）、亿、元、角、分、零、整（正）等字样。不得用一、二（两）、三、四、五、六、七、八、九、十、念、毛、另（或0）填写，不得自造简化字。如果金额数字书写中使用繁体字，如贰、陆、亿、万、圆的，也应受理。

 二、中文大写金额数字到“元”为止的，在“元”之后，应写“整”（或“正”）字，在“角”之后可以不写“整”（或“正”）字。大写金额数字有“分”的，“分”后面不写“整”（或“正”）字。

 三、中文大写金额数字前应标明“人民币”字样，大写金额数字有“分”的，“分”后面不写“整”（或“正”）字。

 四、中文大写金额数字前应标明“人民币”字样，大写金额数字应紧接“人民币”字样填写，不得留有空白。大写金额数字前未印“人民币”字样的，应加填“人民币”三字。在票据和结算凭证大写金额栏内不得预印固定的“仟、佰、拾、万、仟、佰、拾、元、角、分”字样。

 五、阿拉伯小写金额数字中有“0”时，中文大写应按照汉语语言规律、金额数字构成和防止涂改的要求进行书写。举例如下：
  （一）阿拉伯数字中间有“0”时，中文大写金额要写“零”字。如￥1，409．50，应写成人民币壹仟肆佰零玖元伍角。
  （二）阿位伯数字中间连续几个“0”时，中文大写金额中间可以只写一个“零”字。如￥6，007．14，应写成人民币陆仟零柒元壹角肆分。
  （三）阿拉伯金额数字万位或元位是“0”，或者数字中间连续有几个“0”，万位、元位也是“0”，但千位、角位不是“0”时，中文大写金额中可以只写一个零字，也可以不写“零”字。如￥1，680．32，应写成人民币壹仟陆佰捌拾元零叁角贰分，或者写成人民币壹仟陆佰捌拾元叁角贰分；又如￥107，000．53，应写成人民币壹拾万柒仟元零伍角叁分，或者写成人民币壹拾万零柒仟元伍角叁分。
  （四）阿拉伯金额数字角位是“0”，而分位不是“0”时，中文大写金额“元”后面应写“零”字。如￥16，409．02，应写成人民币壹万陆仟肆佰零玖元零贰分；又如￥325．04，应写成人民币叁佰贰拾伍元零肆分。

 五、阿拉伯小写金额数字前面，均应填写人民币符号“￥”（或草写：￥）。阿拉伯小写金额数字要认真填写，不得连写分辩不清。

 六、票据的出票日期必须使用中文大写。为防止变造票据的出票日期，在填写月、日时，月为壹、贰和壹拾的，日为壹至玖和壹拾、贰拾和叁拾的，应在其前加“零”；日为拾壹至拾玖的，应在其前面加“壹”。如1月15日，应写成零壹月壹拾伍日。再如10月20日，应写成零壹拾月零贰拾日。
[中国人民银行关于印发《支付结算办法》的通知](http://tradeinservices.mofcom.gov.cn/article/zhengce/flfg/201710/1277.html)

**Comment by looly** [comment]
@CherryRum 真人维基百科名不虚传。
