### ISSUE TITLE
SpringUtil.getBean 处于非 Spring 环境下应当抛出一个合适的异常

### ISSUE THREAD

**Issue by cn-src** [looly/hutool#2835]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当处于非 Spring 环境下，SpringUtil.getBean 抛出了空指针异常，应当处理下换成一个合适的异常类型（顺带增加一个判断是否处于 Spring 环境的方法？）

**Comment by cn-src** [comment]
我的代码是在一个需要兼容有无 Spring 环境的场景，也就是说不一定初始化了 SpringUtil。
目前是通过捕获空指针异常处理，但是这个异常类型不合适。
```java
final Environment env;
try {
    env = SpringUtil.getBean(Environment.class);
}
catch (NullPointerException e) {
    log.warn("Can not get spring bean Environment", e);
    return;
}
```

**Comment by looly** [comment]
无Spring环境应该抛出classNotFound异常，而非空指针。

空指针的情况可能是你有引入Spring的jar，但是没有使用Spring环境。

我觉得这样抛出NP异常没有问题。

**Comment by cn-src** [comment]
但是 NP 并不是主动抛出的，而是这里引起的：

```java
public static ListableBeanFactory getBeanFactory() {
		return null == beanFactory ? applicationContext : beanFactory;
	}
```
如果不是 hutool 主动抛出，那么应该就由 spring 默认抛出 NoSuchBeanDefinitionException。

**Comment by looly** [comment]
总之未获取到beanFactory，应该就是环境问题。按照你的方法try一下即可。

**Comment by cn-src** [comment]
> 总之未获取到beanFactory，应该就是环境问题。按照你的方法try一下即可。

是这样没错，但我应该明确捕获一个因【Spring 环境问题】或着 【Bean 不存在】而引起的异常，而不是捕获一个因【beanFactory 或 applicationContext】不存在导致的空指针异常，或者更宽泛的去捕获更大范围的 Exception 异常，对吧？

**Comment by cn-src** [comment]
如果后续这块的代码进行了变更，我捕获的 NullPointerException 到底是因为什么呢？是【Spring 环境问题】或着 【Bean 不存在】？还是这个代码有更深层次引发的 NullPointerException ？这个逻辑会不会走向一个未知的错误？毕竟我能做的也就到捕获 NullPointerException 这个层级了，我没办法去细分这个 NullPointerException 是因为 【beanFactory 或 applicationContext】没有导致的，还是别的原因，毕竟这个异常太常见了。

**Comment by looly** [comment]
@cn-src 嗯，确实有道理。给用户一个不确定的异常会让用户非常困惑。

5.8.16会修改此处，当出现null时抛出一个UtilException。
