### ISSUE TITLE
树结构工具-TreeUtil 下个版本可以自定义 bean类型吗

### ISSUE THREAD

**Issue by bangzhu-simple** [looly/hutool#2837]
目前[树结构工具-TreeUtil 生成树时，将树的额外参数放在 TreeNode 的extra 中，	
private Map<String, Object> extra;

下个版本 是否可以将  extra 定义成一个泛型  bean类型

**Comment by looly** [comment]
6.x增加了`BeanTree`，看是否满足你的要求。

至于extra，你增加的字段值类型肯定不一样，使用泛型限定了类型不合适吧。
