### ISSUE TITLE
MailUtil发送vue的动态html失败

### ISSUE THREAD

**Issue by luoysuan** [looly/hutool#2838]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8

### 问题描述
使用MailUtil发送vue的动态html失败

1. 复现代码
1.1发送代码
![image](https://user-images.githubusercontent.com/51365362/210521257-56918e2f-87d7-45d5-ade8-3039f4466f58.png)

1.2效果
![image](https://user-images.githubusercontent.com/51365362/210521379-9d1049bb-0206-49ea-83ec-36326a801d5d.png)

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）
用来发送的html文件
[test.zip](https://github.com/dromara/hutool/files/10342767/test.zip)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
检查邮件接收方的安全规则，是不是不允许有JS？
