### ISSUE TITLE
合并单元格后，自动换行样式没有生效，需要双击单元格才显示换行

### ISSUE THREAD

**Issue by Xuchongbin** [looly/hutool#2839]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

双击前
![image](https://user-images.githubusercontent.com/48149886/210680264-23a2594b-cd70-4efd-911e-1e5439bef5bc.png)

双击后
![image](https://user-images.githubusercontent.com/48149886/210680298-ae6ba107-e7e2-4d1b-aff4-95d509218330.png)

1. 复现代码

```java
CellStyle cellStyle = writer.getCellStyle();
cellStyle.setWrapText(true);
writer.merge(row, row, 0, 1, evnet, cellStyle);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可能生效了，只是单元格不够大，你需要调整单元格高度。

**Comment by Xuchongbin** [comment]
要怎么实现自动适应行高呢

**Comment by looly** [comment]
貌似不行。试下autoSizeColumn。

**Comment by Xuchongbin** [comment]
这个是列宽，不是行高吧。没合并的单元格设置自动换行是可以自动调整行高的，合并的单元格就不行。有没有其他的思路可以实现呢

**Comment by looly** [comment]
@Xuchongbin 那就可能没有了，考虑POI原生方法。
