### ISSUE TITLE
没有判断字符串有多少个字节的方法.

### ISSUE THREAD

**Issue by tang1998bjt** [looly/hutool#284]
有时候要判断当前字符串是否能存进数据库.比如varchar2(128);
这个时候如果用length判断字符串,有汉字还是会报错的.

**Comment by tang1998bjt** [comment]
我还有一个厚颜无耻的请求....就是sub能按照字节来截取

**Comment by looly** [comment]
4.5.2添加`StrUtil.byteLength`。

关于sub，推荐字符串getBytes后，调用`ArrayUtil.sub`即可（4.5.2可用）。
