### ISSUE TITLE
读取excel到mapBUG

### ISSUE THREAD

**Issue by caoxingsheng** [looly/hutool#2840]
### 版本情况

JDK版本：    JDK11
hutool版本： 5.7.18和5.8.11

### 问题描述（包括截图）
读取表头为空的时候，有时能读取到map中的key没有值，有时候读取到又有值

1. 复现代码

```java

情况1：
    @Test
    public void readTest() {
        ExcelReader reader = ExcelUtil.getReader("c:/列名为空.xlsx");
        List<Map<String, Object>> excelDataList = reader.readAll();
        System.out.println(excelDataList);
    }



----------------------------------------------------------------------

情况2：
    @Test
    public void readTest() {
        ExcelReader reader = ExcelUtil.getReader("c:/sss.xlsx");
        List<Map<String, Object>> excelDataList = reader.readAll();
        System.out.println(excelDataList);
    }


```

2. 截图
情况1：
D列为空，读取到map中的key为空
![image](https://user-images.githubusercontent.com/27294643/210935842-63144fae-4369-4a73-ac71-3668e0a02ddf.png)
![image](https://user-images.githubusercontent.com/27294643/210935889-3f1dbdfc-2255-403b-a7b8-0d2bd7c64393.png)

情况2：
D列和E列没有表头，读取出来map中有key值，为'D'和‘E’
![image](https://user-images.githubusercontent.com/27294643/210935398-1341f26b-aeec-4571-bd1b-4b11ed69e21b.png)
![image](https://user-images.githubusercontent.com/27294643/210935476-cbb7234f-ebdf-461d-bcbd-22156b0e52df.png)

**Comment by looly** [comment]
第一种情况，是D1单元格这个单元格是存在的，值为""。

第二种情况，D1单元格没创建，即D1 == null，此时默认读取D作为列名。

**Comment by caoxingsheng** [comment]
有没有方法读取出来的结果，不设置默认列名的，比如说第二种情况，读取出来的结果为   =33, =44

**Comment by caoxingsheng** [comment]
> 
有没有方法读取出来的结果，不设置默认列名的，比如说第二种情况，读取出来的结果为   =33, =44

**Comment by looly** [comment]
@caoxingsheng 这个没有，你要手动去处理结果了。
