### ISSUE TITLE
javax to jakarta

### ISSUE THREAD

**Issue by yuluo-yx** [looly/hutool#2842]
我在spring-boot 3.01 版本中使用了hutool库，使用过程发现了一些问题：
spring-boot中的java已经换成了jakarta。但是hutool中的servletutil还是javax版本。在使用过程中出现了问题。

![image](https://user-images.githubusercontent.com/77964041/211187912-27bef766-e6ee-4eb6-9670-dc0ff4eb2046.png)

pom.xml信息如下：
```xml
       <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.11</version>
        </dependency>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.1</version>
        <relativePath/>
    </parent>
```

**Comment by ZZemptypoint** [comment]
hutool中提供了`JakartaServletUtil`, 你需要手动替换. 
详情请看这个issue [目前有计划考虑支持 SpringBoot 3 吗？](https://gitee.com/dromara/hutool/issues/I633IX#note_14710646_link)

**Comment by yuluo-yx** [comment]
> hutool中提供了`JakartaServletUtil`, 你需要手动替换. 详情请看这个issue [目前有计划考虑支持 SpringBoot 3 吗？](https://gitee.com/dromara/hutool/issues/I633IX#note_14710646_link)

非常感谢，解决了我的问题！
我对hutool非常感兴趣，我可以加入你们的开源组织吗？或者我可以为此项目做些什么？

**Comment by ZZemptypoint** [comment]
> 非常感谢，解决了我的问题！ 我对hutool非常感兴趣，我可以加入你们的开源组织吗？或者我可以为此项目做些什么？

非常欢迎! 加入我们需要先做出一些贡献, 比如参与issue的解决, 或者提交pr, 比如添加新的功能, 修复bug, 完善和优化已有功能等等.

**Comment by yuluo-yx** [comment]
> > 非常感谢，解决了我的问题！ 我对hutool非常感兴趣，我可以加入你们的开源组织吗？或者我可以为此项目做些什么？
> 
> 非常欢迎! 加入我们需要先做出一些贡献, 比如参与issue的解决, 或者提交pr, 比如添加新的功能, 修复bug, 完善和优化已有功能等等.

好的
