### ISSUE TITLE
HttpUtil的post方法设置超时时间为等待对应时间后才执行调用

### ISSUE THREAD

**Issue by qintao0203** [looly/hutool#2844]
### 版本情况

JDK版本：    oracle jdk 1.8.0_192-b12
hutool版本： 5.5.2

### 问题描述（包括截图）
设置超时时间后，每次调用接口没有超时，2s多返回，总耗时在设置15s超时时间后17s才返回。更改超时时间后比如改成十秒，总耗时会在12秒左右返回
1. 复现代码

```java
HttpUtil.post("", jsonstr,15000);
```

2. 堆栈信息
使用阿里巴巴工具查看耗时如下
`---ts=2023-01-07 17:24:10;thread_name=http-nio-9032-exec-10;id=48;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@a4ca3f6
    `---[15015.260184ms] cn.hutool.http.HttpRequest:sendFormUrlEncoded()
        +---[0.00% 0.005676ms ] cn.hutool.http.HttpRequest:header() 
        +---[0.00% 0.002534ms ] cn.hutool.core.util.StrUtil:isBlank() 
        +---[0.00% 0.004685ms ] cn.hutool.core.util.ArrayUtil:isNotEmpty() 
        +---[100.00% 15015.139376ms ] cn.hutool.http.HttpConnection:getOutputStream() 
        `---[0.00% 0.012123ms ] cn.hutool.core.io.IoUtil:write() 

`---ts=2023-01-07 17:24:10;thread_name=http-nio-9032-exec-10;id=48;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@a4ca3f6
    `---[15015.749659ms] cn.hutool.http.HttpRequest:send()
        +---[0.00% 0.002378ms ] cn.hutool.http.Method:equals() 
        +---[0.00% 0.013188ms ] cn.hutool.http.HttpRequest:isMultipart() 
        `---[100.00% 15015.7134ms ] cn.hutool.http.HttpRequest:sendFormUrlEncoded() 

`---ts=2023-01-07 17:24:10;thread_name=http-nio-9032-exec-10;id=48;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@a4ca3f6
    `---[17136.716425ms] cn.hutool.http.HttpRequest:execute()
        `---[100.00% 17136.703641ms ] cn.hutool.http.HttpRequest:execute()
            `---[100.00% 17136.659753ms ] cn.hutool.http.HttpRequest:execute()
                +---[0.00% 0.00479ms ] cn.hutool.http.HttpRequest:urlWithParamIfGet() 
                +---[0.00% 0.204237ms ] cn.hutool.http.HttpRequest:initConnection() 
                +---[87.62% 15015.886357ms ] cn.hutool.http.HttpRequest:send() 
                +---[0.00% 0.00359ms ] cn.hutool.http.HttpRequest:sendRedirectIfPossible() 
                +---[0.00% 0.003799ms ] cn.hutool.http.HttpRequest:isIgnoreResponseBody() 
                `---[12.37% 2120.394395ms ] cn.hutool.http.HttpResponse:<init>()

**Comment by looly** [comment]
这个超时是调用了`URLConnection.setConnectTimeout`和`UrlConnection.setReadTimeout`。

这个在Hutool中无法控制。

**Comment by qintao0203** [comment]
您好，我在源码中也看到调用设置连接超时和读取超时的设置了，同一个项目里面也有使用这个方法的，差别就是有没有设置超时时间和数据传递和返回的不同，设置超时时间的接口请求的是json数据返回的是xml数据，其他接口都是json数据，会跟这个有关系吗？或者您有别的排查思路帮助定位问题吗？

**Comment by qintao0203** [comment]
破案了，项目里面配置了代理，代理服务器访问不同，导致超时了

**Comment by looly** [comment]
@qintao0203 哈哈，这个我确实没有想到，学习了。
