### ISSUE TITLE
FileUtil的rename(File file, String newName, boolean isOverride)方法在newName与原文件夹名称一样时，文件夹会被删除

### ISSUE THREAD

**Issue by Camio1945** [looly/hutool#2845]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
FileUtil.rename(new File("D:\\a" ), "a", false);
```
其中 `a` 是一个文件夹，其下不管还有没有文件，上面的代码都会把整个 `a` 文件夹删除。仅文件夹有这个问题，文件没有问题。
（不是故意找个不可能出现的场景抬杠哈，是真实开发里面确实遇到这种情况了，比如把某个包名 `com.github` 改成 `com.gitee` 时，先把 github 重命名成 gitee 没有问题，后面递归把 com 重命名为 com 时整个文件夹被删除了）

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by ZZemptypoint** [comment]
确实是bug,.
```java
FileUtil.rename(new File("D:\\a" ), "a", false);
```
在底层调用中, 会把目标文件的路径解析为"D:\\a"(`路径前缀来自源文件`), 显然这是一个目录, 所以在`PathUtil.move(src, target, isOverride)`方法中, 当target为目录时, 会直接把src当做文件(`bug就在这里`), 提取文件名拼接到target路径里, target就变成了"D:\\a\\a", 于是目录重命名变成了把a目录移动到自己的子目录中, 移动失败, 开始走跨分区移动的逻辑, 就把源目录给删掉了

![图片](https://user-images.githubusercontent.com/28431269/211445334-e261da75-3df8-4172-a83c-8a5a70655e8a.png)

暂时的替代方法:
1. 重命名前先判断是否是同一个文件, 或者是否文件路径完全相同, 相同则不重命名;
2. 如果你非要重命名目录为原名称, 那就只能使用一个临时目录作为中转: 对任意文件都先把`D:\\x`先重命名为`D:\\y`, 然后在重命名为`D:\\x`

**Comment by looly** [comment]
@ZZemptypoint 看来得加个判断逻辑了。

**Comment by looly** [comment]
5.8.12修复此问题，感谢！

**Comment by LeonemZhang** [comment]
我也遇到这个问题了，hutool版本，新的if case没有解决这个问题
![image](https://user-images.githubusercontent.com/50519058/229009649-54d07f5d-e1ac-4c20-914e-95eeb93564d9.png)

![image](https://user-images.githubusercontent.com/50519058/229008630-c0bc72a0-cf56-4eb4-96c2-daf7598ebe9e.png)
![image](https://user-images.githubusercontent.com/50519058/229008663-5879e00e-9e93-4a8e-8d24-00189b75d695.png)
target.resolve之前就应该判断源和目标是否相同，不然resolve会把src的名字拼到target的后面
![image](https://user-images.githubusercontent.com/50519058/229008955-ac9b4d2d-2d0c-4567-80a2-51b6a663118a.png)
导致会把/test移动到/test/test下。我的环境调试时又会稳定报错
![image](https://user-images.githubusercontent.com/50519058/229009157-b4851673-0577-4f60-b8fe-acff38a2dfdf.png)
非调试的情况也会报错，但是没有抛
![image](https://user-images.githubusercontent.com/50519058/229009259-68f706c3-1469-4d41-a1bd-6dda88f95008.png)
然后就会调用下面删除/test，源目录就被删了
![image](https://user-images.githubusercontent.com/50519058/229009347-10dbe7a3-e844-4f7c-949a-787289b16fc6.png)
