### ISSUE TITLE
CollUtil.union 如果两个coll都是null的话会有空指针问题

### ISSUE THREAD

**Issue by jinqiangx** [looly/hutool#2849]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.15

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/122419627/211705953-7d855180-4a0d-4adf-9a61-18d6021cca64.png)

1. 复现代码

```java
String str = null;
JobDetailSettingsDTO jobDetailSettingsDTO = JSONUtil.toBean(str, JobDetailSettingsDTO.class);
Collection<Object> unionFields = CollUtil.union(jobDetailSettingsDTO.getInfoEnableFields(),
                jobDetailSettingsDTO.getHeaderEnableFields());
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by ZZemptypoint** [comment]
这个问题已修复, 请使用新版本

**Comment by jinqiangx** [comment]
👌🏻
