### ISSUE TITLE
ReUtil.escape存在转义bug

### ISSUE THREAD

**Issue by izerok** [looly/hutool#2850]
### 版本情况

JDK版本：    JDK_8
hutool版本： 5.8.11

### 问题描述

1. 复现代码

```java
System.out.println(ReUtil.escape("我有个$符号{}"));
我有个\$符号\{\}
```

3. 测试涉及到的文件
涉及文件:
ReUtil.java

涉及代码:
cn.hutool.core.util.ReUtil#escape(java.lang.CharSequence)
ReUtil.java:983
``` java
if (RE_KEYS.contains(current)) {
	builder.append('\\');
}
此处append应为"\\\\"

```

**Comment by CherryRum** [comment]
https://github.com/dromara/hutool/issues/2385 
看下这个问题

**Comment by izerok** [comment]
> #2385 看下这个问题

我看了上述问题, 明白了正则转义工具的定义
我描述的观点应该是 工具包可以添加 消除正则表达式 比如说
```code 
*  ->  \\* 
```
面向文字的处理方法
