### ISSUE TITLE
线程级别缓存的支持

### ISSUE THREAD

**Issue by herouu** [looly/hutool#2851]
### 问题描述（包括截图）
想问下有没有基于threadlocal实现的线程级缓存工具

类似于如下的功能
https://juejin.cn/post/6974258796382126117

**Comment by looly** [comment]
还真没研究过，保留issue，后续学习~~

**Comment by peigen** [comment]
threadlocal这玩意已经足够简单了吧，还需要再次封装，会不会有点过犹不及

**Comment by looly** [comment]
确实是，使用threadlocal最简单。
