### ISSUE TITLE
Cannot resolve symbol 'Season'

### ISSUE THREAD

**Issue by BNTang** [looly/hutool#2852]
### 版本情况

JDK版本：JDK 8
hutool版本： 5.8.11

### 问题描述（包括截图）

1. 复现代码

```java
Season season = dateTime.seasonEnum();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

![image](https://user-images.githubusercontent.com/78400939/211844523-0d9fb41e-b88d-47e1-9f0a-09545334be90.png)

**Comment by looly** [comment]
5.8.x修改了这个方法名称，改为了：`quarterEnum`
