### ISSUE TITLE
使用httputil通过代理发送请求，代理访问不同自动进行直连访问

### ISSUE THREAD

**Issue by qintao0203** [looly/hutool#2853]
### 版本情况

JDK版本：    oracle_8
hutool版本： 5.5.2

### 问题描述（包括截图）
之前的问题是这个 #2844
现在发现是因为项目里面配置了代理，而代理是以前的老配置没有修改，服务器之间不同，但是存在的疑问问题是，现在连接代理超时了，而项目里面没看到报错，并且接口调用还成功了，就很困惑，HttpUtil工具类会自动重试吗？
1. 复现代码
System.setProperty("proxySet", "true");
System.setProperty("http.proxyHost", "proxy.example.com");
System.setProperty("http.proxyPort", "8080");
System.setProperty("https.proxyHost", "proxy.example.com");
System.setProperty("https.proxyPort", "8080");
HttpUtil.post("url","json",10000);

**Comment by looly** [comment]
这个并不是Hutool的机制，严重怀疑是JDK的HttpUrlConnection实现自己的机制，我没具体研究过，考虑看下JDK源码？

**Comment by qintao0203** [comment]
打断点跟了一下代码，发现确实有重试的机制，走代理连接超时之后，重试的时候就不加代理创建新的httpclient了
![image](https://user-images.githubusercontent.com/29176158/212829610-85860c04-3eb8-440b-b648-21926eba1efc.png)

**Comment by qintao0203** [comment]
通过启动程序命令参数 -Dsun.net.http.retryPost=false
或代码设置 System.setProperty(“sun.net.http.retryPost”, “false”)可以禁止重试
