### ISSUE TITLE
添加数字常量

### ISSUE THREAD

**Issue by zhouyongshen** [looly/hutool#286]
@looly  你好，能不能添加一些数字类的常量来避免在代码中使用魔法值 
例如：
![image](https://user-images.githubusercontent.com/26317312/54023930-397d6400-41d1-11e9-8d35-084ce14eb7a1.png)

**Comment by looly** [comment]
数字常量请自行定义，暂未接到相关需要的需求。

**Comment by fengdh23** [comment]
这个需求，我觉得挺好的。

**Comment by looly** [comment]
不考虑，徒增jar的体积。
