### ISSUE TITLE
[Feature] 添加用于stream中的distinctByKey

### ISSUE THREAD

**Issue by zhfkt** [looly/hutool#2860]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

Stream提供的distinct()方法只能去除重复的对象，无法根据指定的对象属性进行去重；可以添加实用方法distinctByKey进行去重，代码很短：

```java
public static <T> Predicate<T> distinctByKey(Function<? super T, ?> keyExtractor) {
    Set<Object> seen = ConcurrentHashMap.newKeySet();
    return t -> seen.add(keyExtractor.apply(t));
}
```
用于

```java
persons.stream().filter(distinctByKey(Person::getName))
```

参考链接：

1. https://stackoverflow.com/questions/23699371/java-8-distinct-by-property
2. https://stackoverflow.com/questions/27870136/java-lambda-stream-distinct-on-arbitrary-key
3. https://www.cnblogs.com/zwh0910/p/15877284.html

**Comment by looly** [comment]
这个在6.x的`EasyStream`中有提供。

`EasyStream.of(list).parallel().distinct(String::valueOf).toList();`
