### ISSUE TITLE
数组、集合的zip方法

### ISSUE THREAD

**Issue by li-fcb1899** [looly/hutool#2867]
### 版本情况

JDK版本：    jdk19
hutool版本： 5.8.11

### 问题描述
![屏幕截图_20230123_100542](https://user-images.githubusercontent.com/65374839/213954736-ee8bb1d6-fdd6-4e3d-aed7-f07781c61d84.png)

对于ArrayUtil.zip和CollUtil.zip方法，既然定义了Tuple，难道不应该返回Tuple[]和List<Tuple>，怎么能返回Map呢？

**Comment by yanjingfan** [comment]
> 其他的先不说，你的代码字母看起来好费劲，年轻人有个性是好的，我着实看了半天

**Comment by looly** [comment]
@li-fcb1899 是为了便于操作。在Java中返回一个tuple的List意义不大，没有操作性。
