### ISSUE TITLE
5.8.11 版本 Snowflake 方法缺失

### ISSUE THREAD

**Issue by hello-gitboy** [looly/hutool#2870]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![微信截图_20230129150416](https://user-images.githubusercontent.com/49771801/215310688-7b342d02-8360-460b-ba30-baedbc91c1ac.png)
这个方法没有了吗

**Comment by Freud-Ju** [comment]
这个方法是在IdUtil工具类下面的
cn.hutool.core.util.IdUtil#getSnowflakeNextIdStr

在Snowflake中使用的是
cn.hutool.core.lang.Snowflake#nextIdStr

**Comment by zhaojunliing** [comment]
//简单使用
long id = IdUtil.getSnowflakeNextId();
String id = snowflake.getSnowflakeNextIdStr();

文档错误了

**Comment by hello-gitboy** [comment]
> //简单使用 long id = IdUtil.getSnowflakeNextId(); String id = snowflake.getSnowflakeNextIdStr();
> 
> 文档错误了

是的

**Comment by looly** [comment]
是的，后续修复文档。
