### ISSUE TITLE
计算一年中的第几周和预期不符

### ISSUE THREAD

**Issue by zhangyinyuan** [looly/hutool#2871]
### 版本情况

JDK版本：    Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
hutool版本： hutool-all-5.1.4.jar

### 问题描述（包括截图）

1. 复现代码

```java
System.out.println(cn.hutool.core.date.DateUtil.weekOfYear(new SimpleDateFormat("yyyy-MM-dd").parse("2022-12-29")));
```
期望值: 53
实际值: 1
在线验证工具 https://www.ttnongli.com/jinri/week_2022-12-9.html

**Comment by Freud-Ju** [comment]
注意看方法的说明。跨年的周返回的总是1.

![image](https://user-images.githubusercontent.com/31378712/215437014-6a39fa7a-1696-400e-9659-2c572d8850dc.png)
