### ISSUE TITLE
Springboot3 中无法使用ServletUtil方法

### ISSUE THREAD

**Issue by chenjy1991** [looly/hutool#2872]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.11

### 问题描述（包括截图）

1. 复现代码

```java
import jakarta.servlet.http.HttpServletRequest;
HttpServletRequest request;
ServletUtil.getClientIP(request);
```
ServletUtil方法中使用的是`javax.servlet.http.HttpServletRequest`
Springboot3中替换为`jakarta.servlet.http.HttpServletRequest`

**Comment by Freud-Ju** [comment]
这个是jdk版本的问题，目前hutool应该不支持jdk17吧。springboot3也有jdk版本限制。目前hutool都是基于jdk1.8

**Comment by BingChunMoLi** [comment]
请使用JakartaServletUtil.

**Comment by chenjy1991** [comment]
> 请使用JakartaServletUtil.

谢谢
