### ISSUE TITLE
Ipv4Util.isInnerIP 内网IP判断

### ISSUE THREAD

**Issue by zhouchengfei** [looly/hutool#2873]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
似乎少了
192.0.0.0  ==> 192.0.0.255
搭建的k8s会有这个内网地址
资料:http://ip.yqie.com/192/0/

**Comment by BingChunMoLi** [comment]
192.168.0.0是IANA保留地址并非局域网地址
