### ISSUE TITLE
StrFormatter#format方法可能与预期不符

### ISSUE THREAD

**Issue by Freud-Ju** [looly/hutool#2875]
### 版本情况

JDK版本：    openjdk_8_121
hutool版本： 5.8.11

### 问题描述（包括截图）
问题方法：cn.hutool.core.text.StrFormatter#format(java.lang.CharSequence, java.util.Map<?,?>, boolean)
要显式的设置Map里的参数为null才能达到预期效果

1. 复现代码

```java
		final String template = "你好，我是{name}，我的电话是：{phone}";
		final String result3 = StrUtil.format(template, Dict.create().set("name", "张三"),true);
		final String result4 = StrUtil.format(template, Dict.create().set("name", "张三"),false);
		System.out.println(result3);
		System.out.println(result4);
		Assert.assertNotEquals(result3, result4);



		final String result5 = StrUtil.format(template, Dict.create().set("name", "张三").set("phone",null),true);
		final String result6 = StrUtil.format(template, Dict.create().set("name", "张三").set("phone",null),false);
		System.out.println(result5);
		System.out.println(result6);
		Assert.assertNotEquals(result5, result6);
```

2. 输出图片
![111](https://user-images.githubusercontent.com/31378712/215631228-6ffb3bc4-f822-48c0-ab78-40af0a0bad9d.png)

**Comment by Freud-Ju** [comment]
我已经在v5-dev中新增了cn.hutool.core.text.StrTemplate#format(java.lang.CharSequence, java.util.Map<?,?>, boolean)解决了这个问题。

**Comment by looly** [comment]
PR中已经说明。

合并issue到：https://github.com/dromara/hutool/issues/1940
