### ISSUE TITLE
Convert.toBigDecimal/NumberUtil.toBigDecimal方法中，传参435.sdf，返回信息不为null而为错误值435

### ISSUE THREAD

**Issue by JarLiOne** [looly/hutool#2878]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： hutool-all-5.8.11.jar 

### 问题描述（包括截图）
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/103226883/216542249-b37462d1-9375-4986-a6c1-6c521801f6b4.png">
1. 复现代码
  Console.log("Convert.toBigDecimal(\"345.sdf\") = " +  Convert.toBigDecimal("345.sdf"));
        Console.log("NumberUtil.toBigDecimal(\"345.sdf\")" +  NumberUtil.toBigDecimal("345.sdf"));
 
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个方法是包装了` java.text.NumberFormat`，你可以试下，两个结果一致：

```java
NumberUtil.toBigDecimal("345.sdf");

NumberFormat.getInstance().parse("345.sdf")
```

我觉得作为工具类，理应与JDK中的方法结果保持一致。
