### ISSUE TITLE
ImgUtil是否能新增按目标 图片大小进行压缩

### ISSUE THREAD

**Issue by wangdazhong001** [looly/hutool#2880]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
部分硬件图片进行对接的适合，硬件对图片大小有要求，比如部分只支持200k，则要求对原始图片进行压缩
1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
做不到。考虑其他图片库。
