### ISSUE TITLE
能增加几个下载  InputStream 的方法吗

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#2886]
### 版本情况

JDK版本：    openjdk11.0.18
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

有时候下载网络上的资源，并不需要下载到具体的文件，只需要一个流就好了，现在貌似没看到相关的方法，
HttpDownloader 以及相关联的 HttpUtil 里，都没有看到下载 Stream 的方法

**Comment by winlans** [comment]
@liaozan 这个不就是吗？
```java
/**
* 下载远程文件
*
* @param url        请求的url
* @param out        将下载内容写到输出流中 {@link OutputStream}
* @param isCloseOut 是否关闭输出流
* @return 文件大小
*/
public static long download(String url, OutputStream out, boolean isCloseOut) {
	return download(url, out, isCloseOut, null);
}
```

**Comment by refeccd** [comment]
@winlans 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/26990889/217742785-6df0d0b0-453b-4597-8201-e9559c9d8a45.png">

业务中有些场景是从网络上下载文件，然后传到 oss，免去中间文件存储的步骤，oss 需要 InputStream，所以希望增加 inputStream 相关的方法

**Comment by refeccd** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/26990889/217744781-6bf4e6e2-851c-4880-93c8-58d19b4c9476.png">

**Comment by looly** [comment]
```java
final HttpResponse response = HttpUtil.createGet(url, true)
				.timeout(timeout)
				.executeAsync();
```

因为涉及到关闭流的问题，所以没有单独封装。

**Comment by zhangdp** [comment]
同问，也是业务要求需要下载成InputStream，目前用executeAsync方式返回response.bodyStream()，InputStream用完会手动关闭，但是HttpResponse感觉也应该进行手动关闭，要怎么处理呢这里

**Comment by looly** [comment]
@zhangdp 一样的。response关闭本质上是关闭stream。

**Comment by zhangdp** [comment]
> @zhangdp 一样的。response关闭本质上是关闭stream。

意思是关闭了InputStream就不需要再手动关闭HttpResponse吗
