### ISSUE TITLE
对毫秒位个数不定的日期字符串有统一的方法转换吗？

### ISSUE THREAD

**Issue by lylyxxg** [looly/hutool#2887]
如下日期字符串
2023-02-07T00:02:16.123+08:00
2023-02-07T00:02:16.1234+08:00
2023-02-07T00:02:16.12345+08:00
对于以上的字符串，请问大佬有统一的方法转换成date类型吗

**Comment by lylyxxg** [comment]
上面的可以用DateUtil.parseUTC进行统一转换，但转换后的时间不一样，后两个日期字符串转换后秒会增加，怎样可以不让秒位增加？

**Comment by winlans** [comment]
@lylyxxg 你这个时间是有问题的， 秒后面的是毫秒呢，还是纳秒呢，如果是毫秒不可能超过999，如果是纳秒那就得自定义了。
因为秒会增加这是个bug

**Comment by lylyxxg** [comment]
是的，想要的结果是不让秒增加，小数点后大于3位的话转换让自动舍弃3位后的数；如果需要更精确，走自定义format转换；
秒会增加的版本用的5.7.18，不让秒增加的bug有版本修复吗，
如果已修复，是哪个版本；未修复的话，有版本计划吗

**Comment by winlans** [comment]
@lylyxxg 这个是最新版的bug， 修复只能等待下个版本了， 现在你只能自己兼容了。

**Comment by looly** [comment]
这个并不算是bug，而是默认的parseUTC方法并不支持3位以上的毫秒，支持格式：
![image](https://user-images.githubusercontent.com/1432613/217811053-be2a8e71-b3fe-4934-9448-7335b0bf44fa.png)


考虑parse方法传入自定义格式即可。
