### ISSUE TITLE
关于ExcelUtil使用多个sheet时，能否直接产生

### ISSUE THREAD

**Issue by tmichael1028** [looly/hutool#2888]
ExcelUtil使用多个sheet时候，比如我有一个Map,Map中放的是  (sheet名，具体数据)，
现在遍历Map，每一个sheet名生成一个sheet，但总会出现一个默认的sheet1，我现在的方案是

```java
for (Map.Entry<sheet名, 具体数据> entry : resultMap.entrySet()) {

                System.out.println("Key = " + entry.getKey() + ", Value = " + entry.getValue());

                if (0 == i) {
                    bigWriter.renameSheet(entry.getKey());
                } else {
                    bigWriter.setSheet(entry.getKey());
                }

                i++;
            }
```

总会需要判断第0个，然后重命名，产生的Excel才是没有sheet1的结果

有方法直接遍历，不用判断，然后最终结果产生的Excel是没有sheet1的表格呢？

**Comment by looly** [comment]
这个没有。

![image](https://user-images.githubusercontent.com/1432613/217811703-154bb401-9891-4a1b-be8f-780458c2f462.png)

使用这个方法指定第一个sheet名称即可。
