### ISSUE TITLE
BeanUtil.copyProperties(new Source, Target.class) , Source 是 record 类，生成的Target对象字段全为null

### ISSUE THREAD

**Issue by Thomas2077** [looly/hutool#2895]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
<img width="807" alt="image" src="https://user-images.githubusercontent.com/20399536/218261913-530bb196-1d15-4707-9218-d596db5b1475.png">

1. 复现代码

```java
// 源类
public record Source(
  String name
){}
@Data
public class Target{
    public String name;
}
// 生成的Target对象字段全为null
Target target = BeanUtil.copyProperties(new Source("Tom"), Target.class)
```

**Comment by looly** [comment]
record 类事实上并没有被直接支持，因为jdk8中没有相关修饰符。
