### ISSUE TITLE
URLQuery编码

### ISSUE THREAD

**Issue by wzglgo** [looly/hutool#2898]
build方法里value值编码用的valueCoder.encode，无法对冒号进行编码

**Comment by looly** [comment]
可以看下RFC3986规范，`:`在value中是不需要编码的。

**Comment by wzglgo** [comment]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/95947852/218978794-e8ad7959-25ef-4da8-81d6-3dd86b613552.png">
有些平台似乎不支持不转译的 :

**Comment by looly** [comment]
你可以看下：https://www.ietf.org/rfc/rfc3986.html#section-3.3

这个方法不知道转义哪个部分。
