### ISSUE TITLE
Excel导出bean对象时，如果bean的字段上存在hutools的Alias注解，此时再为excel的列设置别名标题会无法导出数据

### ISSUE THREAD

**Issue by Kuidaxia** [looly/hutool#2899]
### 版本情况

JDK版本：    jdk1.8.0_321
hutool版本： 5.8.12

### 问题描述
使用工具包的过程中，我发现使用hutool的@Alias，注解在需要导出的bean的字段上可以直接给excel中的标题设置别名，所以我就在想能否通过字段上是否有此注解来控制是否导出某个字段，结果是不行的。
![image](https://user-images.githubusercontent.com/39208351/218708357-aa8acb55-0ef4-4d9b-b50d-addfbbed9cca.png)
![image](https://user-images.githubusercontent.com/39208351/218708493-94ab393b-1386-4f09-9812-90c0c3acbd2d.png)
![image](https://user-images.githubusercontent.com/39208351/218708608-c52bf9c2-fbc5-4f96-817f-245a43b83a79.png)

因此还是需要手动的通过addHeaderAlias方法为ExcelWriter设置列标题，结果生成的excel中便没有数据了。
![image](https://user-images.githubusercontent.com/39208351/218709555-ca2ab371-09f5-4113-b0b5-800614409c69.png)

通过反射取注解值的方式，可以看到已经设置成功别名
![image](https://user-images.githubusercontent.com/39208351/218710018-02aeca88-d040-48fc-8cac-64614d66db2d.png)

生成结果没有数据
![image](https://user-images.githubusercontent.com/39208351/218710185-a820f8ec-4114-4816-839e-c9ec71ef37bc.png)

经过调试，我发现hutool应该用@alias还做了其他事导致了这个问题（具体干啥了我没看到），所用我通过自定义注解解决了这个问题。所以是否可以改进一下，能通过@Alias注解是否标注在字段上来控制字段是否导出

**Comment by winlans** [comment]
@Kuidaxia  这个好像是你理解错了， excel导出的headerAlias和`@Alias`并没有什么关系， `@Alias`只是用在BeanUtil中用来做bean之间转换时候用的。这里的onlyAlias是说，只有你配置的headerAlias中的属性将被导出。
ps: 为什么用了`@Alias`会导致导出数据消失，是因为你修改了Bean的属性名导致的意外。

**Comment by Kuidaxia** [comment]
按道理来讲，@Alias确实不应该和excel导出中的设置别名扯上关系。
但是我意外发现，可以通个这个注解为导出excel设置别名，请看上面的前三张图，我只在Bean上面用注解设置了别名，下面的excel导出代码中我并没有写任何别名相关的代码，但是导出的excel中标记了@Alias的属性确实被别名替换掉了，这说明是可以通过@Alias注解为excel导出时设置别名（PS：为什么会这样我没找到原因）。
那么我的想法是，既然可以通过@Alias为excel设置别名，那么是否可以通过判断bean字段上的@Alias注解存在与否来决定该字段是否导出呢。现在是不行的，从第一个导出结果可以看到，如果没有注解，那么就以原字段名作为excel的列名。
这时我就只能自己手动的为excel设置别名并为onlyAlias属性设置为true.
所以当Bean上存在@Alias注解并同时手动的为excel设置别名就会导致导不出数据,你说的修改了bean的属性名,但是我没有修改过

**Comment by winlans** [comment]
@Kuidaxia [文档这里](https://www.hutool.cn/docs/#/core/JavaBean/Bean%E5%B7%A5%E5%85%B7-BeanUtil?id=%e4%bb%80%e4%b9%88%e6%98%afbean)写的还是很清楚的，告诉你@Alias是用来做什么。至于为什么你使用它导出Excel的时候生效了[这里是关键](https://github.com/dromara/hutool/blob/77e42315a7526a603569b5fc5e9b567688db33ef/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelWriter.java#L1347-L1360),详细的你可以断点去一点点看。这的确是某种巧合😂

**Comment by looly** [comment]
嗯，`@Alias`和手动使用`addHeaderAlias`确实有兼容性问题，这个问题可能会在6.x中解决，我来解释下。

Bean中设置`@Alias`时，`setOnlyAlias`是无效的，这个参数只和`addHeaderAlias`配合使用，原因是注解是Bean内部的操作，而addHeaderAlias是Writer的操作，不互通。

因此你可以把Bean中的注解去掉，完全使用`addHeaderAlias`配合`setOnlyAlias`完成写出。
![image](https://user-images.githubusercontent.com/1432613/219014677-036eda5f-94be-44ce-a8e0-cc15d2109e68.png)


当然，如果你的Bean中注解不想去掉，你可以设置一个同名的`addHeaderAlias`即可。

![image](https://user-images.githubusercontent.com/1432613/219014941-576c412c-45d9-436b-9c62-d64152688fc3.png)
