### ISSUE TITLE
HttpResponse的getCookieStr方法返回的Cookie不完整

### ISSUE THREAD

**Issue by Jarvan-wong** [looly/hutool#290]
目前返回的是 headerList(“Cookie”).get(0) ,  获取的是response  set的第一条cookie的内容，希望获取所有的Cookie， 
`List<HttpCookie> cookies = response.getCookies();
StringBuffer cookie = new StringBuffer();
		
for(HttpCookie cook:cookies){			
    cookie.append(cook.getName()+"="+cook.getValue()+";");		
}
`

**Comment by looly** [comment]
请升级到Hutool的最新版本，有`getCookies`方法。
