### ISSUE TITLE
NamingCase.toUnderlineCase 转换大小写错误

### ISSUE THREAD

**Issue by coolbeevip** [looly/hutool#2900]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12

### 问题描述（包括截图）

我期望 `aBCd` 转换为 `a_b_cd` ，但是转换为了 `a_B_cd`
```java
  @Test
  public void toUnderlineCaseTest2() {
    String camel = "aBCd";
    String under = "a_b_cd";
    assertThat(NamingCase.toUnderlineCase(camel), Matchers.is(under));
    assertThat(NamingCase.toCamelCase(under), Matchers.is(camel));
  }
```

失败信息

```shell
java.lang.AssertionError: 
Expected: is "a_b_cd"
     but: was "a_B_cd"
Expected :a_b_cd
Actual   :a_B_cd
```

我想代码错误应该出现在这里

https://github.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/text/NamingCase.java#L93

判断条件中应该加上 Character.isUpperCase(nextChar)

**Comment by looly** [comment]
这个其实取决于如何理解这个单词。aBCd可以理解为a_BC_d，BC是个专有名词，也可以理解为a_b_cd，理解b为一个普通单词。

Hutool这里将BC中的B理解为一个专有名词，因此没有转为小写。

如果你有类似需求，建议自行转换呗。

**Comment by coolbeevip** [comment]
如果能提供一个专于名词定义的 API 就更完善一些

**Comment by looly** [comment]
@coolbeevip 嗯，这个暂时没有考虑那么多情况。我找找有没有什么好的解决方案。
