### ISSUE TITLE
请实现cn.hutool.poi.excel.cell.NullCell ToString的方法

### ISSUE THREAD

**Issue by HaxiTang** [looly/hutool#2906]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

 reader.setCellEditor((cell, value) -> {
                return cell.toString();
            });
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个类实现toString的意义是啥？debug？

**Comment by HaxiTang** [comment]
Cell toString时会调用原Cell的toString方法转为字符串，NullCell没有实现ToString将会返回ClassName对象名，虽然value值传递过来null，但是这并不优雅，其实本意为了读取Excel所有值为String

**Comment by looly** [comment]
但是这个实现返回什么都不合适。

1. 如果返回null、或者“”都不对，你觉得应该返回什么内容呢？
