### ISSUE TITLE
java.lang.NoSuchFieldError: SM4CMAC

### ISSUE THREAD

**Issue by MrQiaoLei** [looly/hutool#2910]
### 版本情况

JDK版本：    17
hutool版本：  5.7.11

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/17661940/219618754-02a86067-4fe9-438f-baf2-d87edd124517.png)
![image](https://user-images.githubusercontent.com/17661940/219618806-a4e0d0da-73a6-4bbe-8fdc-a107ab6bc796.png)
![image](https://user-images.githubusercontent.com/17661940/219618852-1de3c7d9-8592-411d-8047-fbbabc44f501.png)
![image](https://user-images.githubusercontent.com/17661940/219618896-81aad2ec-f414-409e-87a6-be864e54af23.png)

**Comment by DINGDANGMAOUP** [comment]
_**（已解决）**_好兄弟，啥意思，怎么解决的，咋关闭了

**Comment by MrQiaoLei** [comment]
版本不一致导致的，用的hutool工具包要使用同一个版本的，不同版本可能会报错发自我的手机-------- 原始邮件 --------发件人： kuroneko ***@***.***>日期： 2023年2月23日周四 下午1:26收件人： dromara/hutool ***@***.***>抄送： MrQiaoLei ***@***.***>, State change ***@***.***>主    题： Re: [dromara/hutool] java.lang.NoSuchFieldError: SM4CMAC (Issue #2910)

好兄弟，啥意思，怎么解决的，咋关闭了

**Comment by looly** [comment]
@DINGDANGMAOUP 加BC库依赖即可。

https://hutool.cn/docs/#/crypto/%E5%9B%BD%E5%AF%86%E7%AE%97%E6%B3%95%E5%B7%A5%E5%85%B7-SmUtil?id=%e5%bc%95%e5%85%a5bouncy-castle%e4%be%9d%e8%b5%96
