### ISSUE TITLE
cn.hutool.http.HttpRequest 如何保持sessions会话？

### ISSUE THREAD

**Issue by PlexPt** [looly/hutool#2913]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Hutool基于HttpUrlConnection封装，无法保持Session。

**Comment by PlexPt** [comment]
有什么推荐的吗

**Comment by looly** [comment]
HttpClient

**Comment by PlexPt** [comment]
支持 "Content-Type: text/event-stream" 的请求吗

**Comment by looly** [comment]
@PlexPt try it.

**Comment by PlexPt** [comment]
不支持，会阻塞
