### ISSUE TITLE
移除log4j后  有什么办法可以解决 Log4j2Log 和 Log4j2LogFactory

### ISSUE THREAD

**Issue by renxinyujava** [looly/hutool#2915]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我没看懂你的意思。既然已经移除了log4j2，那这两个类就不会调用了，无需管他。
