### ISSUE TITLE
ImgUtil.scale会在某些图片压缩之后自动旋转90度

### ISSUE THREAD

**Issue by wangdazhong001** [looly/hutool#2923]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.0.M3

##ImgUtil.scale会在某些图片压缩之后自动旋转90度  有没有解决方案

**Comment by wangdazhong001** [comment]
已经找到解决办法，亲测可行
https://blog.csdn.net/yuyu1067/article/details/116333935

**Comment by looly** [comment]
打开issue先mark一下，看是否可以封装一层。

**Comment by wangdazhong001** [comment]
好的
















在 2023-02-24 16:13:16，"Golden Looly" ***@***.***> 写道：

打开issue先mark一下，看是否可以封装一层。

**Comment by looly** [comment]
可以看下：https://github.com/dromara/hutool/issues/2765

在v6版本中增加`ImgMetaUtil`，为了解耦第三方库，因此读取角度信息解耦，由用户手动旋转。

```java
final File file = FileUtil.file("d:/test/204691690-715c29d9-793a-4b29-ab1d-191a741438bb.jpg");
final int orientation = ImgMetaUtil.getOrientation(file);
Img.from(file)
		.rotate(orientation)
		.write(FileUtil.file("d:/test/aaa.jpg"));
```
