### ISSUE TITLE
JSONUtil.toList() 会对元素自动排序，怎么解决？

### ISSUE THREAD

**Issue by pzzzzzzzzzzz** [looly/hutool#2924]
### 版本情况

JDK版本：    openjdk version "11.0.15" 
hutool版本： 5.6.2

### 问题描述

```java
String idsJsonString = "[1174,137,1172,210,1173,627,628]";
List<Integer> idList = JSONUtil.toList(idsJsonString,Integer.class);
```

转换后：输出 是按照 id 的大小顺序自动排序的。这样不能满足当前使用条件，是否可以不排序？就按照原样输出。

**Comment by looly** [comment]
在旧版本中可能是bug，新版本没有这个问题。请升级到5.8.12。

![image](https://user-images.githubusercontent.com/1432613/221127245-b93b4b7e-dbe0-4c2f-b232-2b4ce14f576c.png)
