### ISSUE TITLE
RandomUtil.randomInt(10,10)方法是否应该支持两值相等

### ISSUE THREAD

**Issue by dianbaiyizhong** [looly/hutool#2928]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.8.11

### 问题描述

1. 复现代码

```java
RandomUtil.randomInt(10,10);
```

2. 堆栈信息
java.lang.IllegalArgumentException: bound must be greater than origin

	at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:379)
	at cn.hutool.core.util.RandomUtil.randomInt(RandomUtil.java:184)

3. apache common lang中的RandomUtils.nextInt是支持两值相等的，这样会对使用更友好，是否能支持呢

**Comment by code142857** [comment]
@dianbaiyizhong 如果你想要10位那就使用`RandomUtil.randomInt(10);`就行吧

**Comment by dianbaiyizhong** [comment]
@auto-generated 不一样的，RandomUtil.randomInt(10)是从0-10生成10位数，而RandomUtil.randomInt(10，10)是只会生成10.。在特定的场景中是能帮助到开发人员的。。例如RandomUtil.randomInt(a，b),a++,b--对吧。

**Comment by looly** [comment]
这个范围按照JDK的范围保持一致：

![image](https://user-images.githubusercontent.com/1432613/221855045-aa876603-9673-4dd5-a155-0856f1a5608c.png)
