### ISSUE TITLE
文档中提到的SecureUtil.simpleUUID无法找到

### ISSUE THREAD

**Issue by by123456by** [looly/hutool#2938]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
https://hutool.cn/docs/#/crypto/%E5%8A%A0%E5%AF%86%E8%A7%A3%E5%AF%86%E5%B7%A5%E5%85%B7-SecureUtil?id=uuid
文档中提到的SecureUtil.simpleUUID无法找到

**Comment by looly** [comment]
换在IdUtil中了。

**Comment by looly** [comment]
最近更新文档。
