### ISSUE TITLE
DateUtil.calendar(date) 得到Calendar对象，其中时分秒变成：00:00:00了

### ISSUE THREAD

**Issue by LelandACM** [looly/hutool#2944]
### 版本情况

JDK版本：    1.8.0.331
hutool版本： 5.8.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/19402747/222646481-9bbe778e-b56b-4c29-80d1-5280afa6de06.png)

1. 复现代码

```java
        Date date = DateUtil.date();
        Calendar c = DateUtil.Calendar(date);
       c 的时分秒自动丢失变成：0时0分0秒了,日期是正确的。
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/222694151-e5788b63-7b3b-4a54-9032-20290547463c.png)

经过测试并没有丢失。

我看你代码中`ce`变量日期是正常的，但是cdate对象丢失了时间，你这个cdate如何得出的？怀疑你ce转cdate时候用错了方法。

**Comment by LelandACM** [comment]
@looly 谢谢你，找到了问题所在
