### ISSUE TITLE
StrUtil.removeAny(CharSequence str, CharSequence... strsToRemove) 方法错误

### ISSUE THREAD

**Issue by zw18** [looly/hutool#2945]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

**以下代码错误，只会根据最后一个参数做置空处理，未循环使用result**

1. 复现代码
/**
	 * 移除字符串中所有给定字符串，当某个字符串出现多次，则全部移除<br>
	 * 例：removeAny("aa-bb-cc-dd", "a", "b") =》 --cc-dd
	 *
	 * @param str         字符串
	 * @param strsToRemove 被移除的字符串
	 * @return 移除后的字符串
	 * @since 5.3.8
	 */
	public static String removeAny(CharSequence str, CharSequence... strsToRemove) {
		String result = str(str);
		if (isNotEmpty(str)) {
			for (CharSequence strToRemove : strsToRemove) {
				result = removeAll(str, strToRemove);
			}
		}
		return result;
	}

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你用的版本太旧了，可能触发了bug，最新版本没有问题：

![image](https://user-images.githubusercontent.com/1432613/222693498-31b75e43-69c7-419b-9bf0-ed7df06d6d1f.png)
