### ISSUE TITLE
pr出错

### ISSUE THREAD

**Issue by wangruipeng-wrp** [looly/hutool#2946]
你好，我想要提交一个pr，在这个pr中需要创建一个新的 module：hutool-web，但是我在 idea 中创建新 module 时 git 会创建一个新的仓库，导致我无法将代码合并到 v5-dev 中，我想请问一下这是不是你有做了什么设置，还是我自己对 git 的操作失误？

**Comment by looly** [comment]
我这边没有设置。

检查下你的IDE配置。

还有之前有pr，hutool-web不考虑的，欢迎讨论。
