### ISSUE TITLE
FileUtil的使用疑惑 rename 报错 

### ISSUE THREAD

**Issue by artillerymans** [looly/hutool#2947]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/16060581/222891235-a49114c1-ba49-4444-9639-7e6f50bba44b.png)

这段代码有问题吗？不是很明白这个用法，文件确认本地有

![image](https://user-images.githubusercontent.com/16060581/222891297-f81317a5-2567-4089-aa9d-8673bd2003f1.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by lensferno** [comment]
升级至5.8.13可解决

5.8.12在判断重命名后的文件是否为同一文件时的处理有点问题，可见#2894
