### ISSUE TITLE
ExpressionUtil Expression Injection Vulnerability

### ISSUE THREAD

**Issue by SoLikeDog** [looly/hutool#2950]
Hello, I found an expression injection vulnerability. In ExpressionUtil, parameters are not verified before untrusted data is passed in, resulting in arbitrary code execution.

Vulnerability trigger analysis:

In `ExpressionUtil.class`:

```java
 public static ExpressionEngine getEngine() {
 //an interface `ExpressionEngine` is returned here.
        return ExpressionFactory.get();
    }

    public static Object eval(String expression, Map<String, Object> context) {
    //so getEngine().eval actually is the eval method of ExpressionEngine.
        return getEngine().eval(expression, context);
    }
```

The implementation class of `ExpressionEngine` is `MvelEngine`,

```java
public Object eval(String expression, Map<String, Object> context) {
        return MVEL.eval(expression, context);
    }
```

In the `eval` method, `MVEL` is used to execute regular expressions,after untrusted data is passed into the `eval` method,the expression injection vulnerability will be triggered.

For more information about this vulnerability, see:https://github.com/SoLikeDog/Hutool-Expression-injection

Kind regards

**Comment by looly** [comment]
Hutool`s ExpressionUtil is just a facecade of expression engines, so can not check all untrusted data, user must check it before use.

its just like log4j has a Vulnerability and slf4j can not do any thing.
