### ISSUE TITLE
5.8.14版本 hutool-all Automatic-Module-Name 是不是不太正确

### ISSUE THREAD

**Issue by lWoHvYe** [looly/hutool#2952]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.14

### 问题描述（包括截图）

1. 新版本 hutool-all的 Automatic-Module-Name的问题

5.8.12及之前应该是Auto module，所以module name是 hutool-all
5.8.13添加了 Automatic-Module-Name 属性，变成了 cn.hutool
5.8.14变成了 cn.hutool.aop ，这个是不是不太正确

附图
![截屏2023-03-07 上午7 57 04](https://user-images.githubusercontent.com/39266195/223283768-5dd71cde-0abb-4073-9c10-499b032dc3c5.png)

**Comment by looly** [comment]
我检查下~

**Comment by CherryRum** [comment]
@lWoHvYe 是的。谢谢大佬提醒，写错了，下个版本修复

**Comment by unknowIfGuestInDream** [comment]
5.8.14 hutool-core, hutool-log等模块的 Automatic-Module-Name 也是 cn.hutool.aop

**Comment by CherryRum** [comment]
@unknowIfGuestInDream 嗯找到问题了

**Comment by unknowIfGuestInDream** [comment]
另外，我使用的JDK版本是17，项目中使用了模块化，在5.8.12时使用的module name是 hutool-xxx。
在dependabot 提交的pr中出现模块找不到的编译错误，但在Release notes或者Changelog中未找到模块名变更的说明，是否考虑完善下相关说明？

**Comment by looly** [comment]
5.8.15修复此问题。

**Comment by CherryRum** [comment]
> 另外，我使用的JDK版本是17，项目中使用了模块化，在5.8.12时使用的module name是 hutool-xxx。 在dependabot 提交的pr中出现模块找不到的编译错误，但在Release notes或者Changelog中未找到模块名变更的说明，是否考虑完善下相关说明？

由之前Auto module `hutool-xxx`
这个变更为`cn.hutool.xxx` 
`module name`规范内不让试用`-`
具体您可以看pom文件下面加了个属性

**Comment by unknowIfGuestInDream** [comment]
> > 另外，我使用的JDK版本是17，项目中使用了模块化，在5.8.12时使用的module name是 hutool-xxx。 在dependabot 提交的pr中出现模块找不到的编译错误，但在Release notes或者Changelog中未找到模块名变更的说明，是否考虑完善下相关说明？
> 
> 由之前Auto module `hutool-xxx` 这个变更为`cn.hutool.xxx` `module name`规范内不让试用`-` 具体您可以看pom文件下面加了个属性

是的，我明白您的意思，我的想法是是否需要在Release中告知用户 module name 由 `hutool-xxx` -> `cn.hutool.xxx`，因为对使用模块化的用户来说需要修改他们的`module-info.java`文件，如果能在Release中看到这个改动会让用户更直接得获取这个变更。

因为我是在提升版本后发现模块未找到错误后才发现模块名变更的事请，所以才提出这个请求。

**Comment by looly** [comment]
@unknowIfGuestInDream 有道理。这个我加下。
