### ISSUE TITLE
JSONUtil.parseObj 在值为超大数字时会自动变成字符串

### ISSUE THREAD

**Issue by java-yzy-noob** [looly/hutool#2953]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.10

### 问题描述（包括截图）
JSONUtil.parseObj 在值为超大数字时会自动变成字符串
![image](https://user-images.githubusercontent.com/39071118/223312114-5063d9d5-dd8c-4fea-a795-e96f418f642a.png)

1. 复现代码

```
    public static void main(String[] args) {

        String a = "{\"a\": 114793903847679990000000000000000000000}";
        JSONObject jsonObject = JSONUtil.parseObj(a, JSONConfig.create());
        System.out.println(jsonObject);
    }

```

**Comment by java-yzy-noob** [comment]
不清楚是不是JSONConfig需要配置的问题, 没找到相关配置 和 相关问题

**Comment by CherryRum** [comment]
这个值已经超过long的表达精度了吧,所以可能解析过程自动转为字符串了

**Comment by java-yzy-noob** [comment]
> 这个值已经超过long的表达精度了吧,所以可能解析过程自动转为字符串了

没超过double, 我觉得优先转double 或者bigDecimal 合理一些

**Comment by looly** [comment]
@java-yzy-noob 默认都是转BigDecimal的，但是显示成JSON字符串是用字符串表示。

**Comment by java-yzy-noob** [comment]
> @java-yzy-noob 默认都是转BigDecimal的，但是显示成JSON字符串是用字符串表示。

![image](https://user-images.githubusercontent.com/39071118/223596235-f53c6e38-eb23-45ba-966a-9d2ab682f3a9.png)
但是我这边看是变成了String

**Comment by looly** [comment]
@java-yzy-noob 对啊，超出long的精度了，因此使用String表示了。

**Comment by java-yzy-noob** [comment]
> @java-yzy-noob 对啊，超出long的精度了，因此使用String表示了。
这个情况下用double 或者 bigDecimal  表示会不会更好一些. 目前我这边使用的时候先读再写, 数字类型就变字符串了

**Comment by java-yzy-noob** [comment]
> @java-yzy-noob 对啊，超出long的精度了，因此使用String表示了。
我试了fastjson2读写不会加这个引号

**Comment by looly** [comment]
@java-yzy-noob 首先JSON你不但需要考虑到Java环境，还要考虑到JS环境。如果超出精度的数字不使用字符串表示，在JS中将丢失精度， 这可是大问题，见：https://github.com/dromara/hutool/issues/1744

你可以自己在控制台中试试：

![image](https://user-images.githubusercontent.com/1432613/224025842-4a0af081-9147-4113-8796-ef77445e2797.png)

**Comment by java-yzy-noob** [comment]
@looly  能不能在JSONConfig里加一个配置, 就是数字超出long时的处理方式, 这样也可以按需选择

**Comment by looly** [comment]
@java-yzy-noob 考虑试下FastJSON之类的库看是否有解决方案。
