### ISSUE TITLE
JWTUtil 无法获取到指定的 payload 字段

### ISSUE THREAD

**Issue by oswayne** [looly/hutool#2958]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.14

### 问题描述（包括截图）

1. 复现代码

```java
// 无法获取到指定的 payloads 字段，已经确认该字段已经存在
JWTUtil.parseToken(jwt).getPayloads().getLong("id")
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xiaoso456** [comment]
你的 payload 是不是类似这样？
```json
{
  "id": 123
}
```
jwt 中数值是代表时间戳，如要要用getLong方法转化为数值，数值应该用字符串，如下

```json
{
  "id": "123"
}
```

**Comment by looly** [comment]
bug，见：https://gitee.com/dromara/hutool/issues/I6L2LO
