### ISSUE TITLE
有sql 注入风险

### ISSUE THREAD

**Issue by jaydenchau** [looly/hutool#2959]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11

SQL Inection vulnerability in Dromara hutool v5.8.11 allows attacker to execute arbitrary code via the aviator template engine.

**Comment by CherryRum** [comment]
Hutool本身只是表达式引擎的门面，具体实现有漏洞，Hutool也没办法来修补和操控。

只能看实现库是否能解决。不能解决更换引擎
