### ISSUE TITLE
weekOfYear 不准确

### ISSUE THREAD

**Issue by he0xff** [looly/hutool#296]
2019-12-30, 2019-12-31 通过weekOfYear 获取得到的是1，这个可否解释一下？谢谢（时区是：东八区）

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/54350123-9cff0a00-4687-11e9-9686-35fa7eeff9b2.png)

这里`2019-12-30, 2019-12-31`所在周跨年了，始终返回1。

这是遵循Calendar对象的结果值。

见：

https://blog.csdn.net/first773/article/details/51479621

**Comment by he0xff** [comment]
好的，十分感谢
