### ISSUE TITLE
开启自动重定向之后，重定向过程中产生的cookie丢失

### ISSUE THREAD

**Issue by wxyun2** [looly/hutool#2960]
### 版本情况

JDK版本：    
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
hutool版本： 5.8.14

### 问题描述（包括截图）
1、使用HttpRequest.setCookieManager(cookieManager); 设置了全局cookie
2、调用httpRequest.setMaxRedirectCount(20) 设置了最大重试次数20次
3、在重定向过程中会产生cookie，经过调试hutool代码发现 cn.hutool.http.HttpRequest#doExecute 方法中sendRedirectIfPossible 使用了递归进行处理自动重定向。但是其中cookie的设置在 跟中之后发现如下方法中
![image](https://user-images.githubusercontent.com/12785684/223656488-dfdd8014-57e8-4e1b-af67-b50ebe7de5ab.png)
![image](https://user-images.githubusercontent.com/12785684/223656552-86d6ed4e-a569-4cff-9180-be9797b40fe2.png)
![image](https://user-images.githubusercontent.com/12785684/223656584-03fb3e2c-81ab-4fd6-970b-9d4cef782435.png)
![image](https://user-images.githubusercontent.com/12785684/223656641-11cabdeb-bc0f-4535-9ff5-2b4222876e76.png)

4、在sendRedirectIfPossible 中递归调用了doExecute 方法，按照这种方式处理，会导致在重定向过程之中只会保留最后一次的cookie，多次重定向写入的cookie就会产生丢失
![image](https://user-images.githubusercontent.com/12785684/223656869-580e646a-e6f0-4e36-b6ac-fab6feb3c3e4.png)

### 目前研究出有如下几种处理方案：
第一种处理方案：修改hutool源码（不建议），在重定向之前调用cn.hutool.http.cookie.GlobalCookieManager#store写入cookie即可
![image](https://user-images.githubusercontent.com/12785684/223658666-8fe18399-a82c-47dc-b780-35ec70d7fe3e.png)

第二种处理方案：解决hutool提供的拦截器进行处理
```java
 httpRequest.addRequestInterceptor(httpObj -> {
            HttpConnection requestConnection = httpRequest.getConnection();
            try {
                //判断请求是否已经进行了，在第二次重定向执行之前进行存储cookie
                if(requestConnection!=null && requestConnection.responseCode() > 0){
                    GlobalCookieManager.store(requestConnection);
                }
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
```

建议hutool官方增加自动重定向是否携带cookie配置进行修复

**Comment by looly** [comment]
嗯，PR为何关闭了？

**Comment by looly** [comment]
感谢，PR已合并。
