### ISSUE TITLE
Calculator.conversion() 表达式计算有问题

### ISSUE THREAD

**Issue by yellowgg** [looly/hutool#2964]
### 版本情况

JDK版本：    openjdk_8_342
hutool版本： 5.7.22（经测试,最新版5.8.15依然存在）

### 问题描述（包括截图）
1. 使用表达式计算工具计算 (11+2)12 这条式子的时候, 计算结果为12.
2. 理论上来说,要么是返回结果13*12=156,要么是报错(其实一般来说是报错,别的计算引擎也是报错的)

1. 复现代码

```java
  public static void main(String[] args) {
        double calcValue = Calculator.conversion("(11+2)12");
        System.out.println(calcValue);
    }
```
运行结果
<img width="466" alt="image" src="https://user-images.githubusercontent.com/27286340/223973577-c1d3c00b-1739-4d3b-87ef-f7e5604a2afc.png">

**Comment by looly** [comment]
5.8.16调整代码。

调整方式按照省略乘法方式：

```
// 当结果集中有多个数字时，可能是省略*，类似(1+2)3
return NumberUtil.mul(resultStack.toArray(new String[0])).doubleValue();
```
