### ISSUE TITLE
URLUtil.encode(url)编码时，不支持带+的字符串

### ISSUE THREAD

**Issue by vathesee** [looly/hutool#2968]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String url = "demo1副本（）+# .mp4";
String result= URLUtil.encode(url);
```
result = demo1%E5%89%AF%E6%9C%AC%EF%BC%88%EF%BC%89+%23%20.mp4

2. 结果分析
得到的字符串中，"+"未编码，导致去访问的时候，浏览器无法解析

**Comment by looly** [comment]
HttpUtil会自动编码需要的字符，请升级到最新版本hutool尝试。

如果想编码+，使用encodeAll方法。

**Comment by vathesee** [comment]
已经解决了，谢谢。还有一个api,  URLUtil.encodeQuery(url)。
