### ISSUE TITLE
官网参考手册描述错误

### ISSUE THREAD

**Issue by xxxxbxxxxx** [looly/hutool#2971]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： docs

### 问题描述（包括截图）

![image](https://user-images.githubusercontent.com/18393907/224244254-fb17a37e-87ea-496b-8592-008e7b1cd153.png)

[https://hutool.cn/docs/#/core/%E7%BA%BF%E7%A8%8B%E5%92%8C%E5%B9%B6%E5%8F%91/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BA%BF%E7%A8%8B%E6%B1%A0-ExecutorBuilder](https://hutool.cn/docs/#/core/%E7%BA%BF%E7%A8%8B%E5%92%8C%E5%B9%B6%E5%8F%91/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BA%BF%E7%A8%8B%E6%B1%A0-ExecutorBuilder)

**Comment by looly** [comment]
感谢，近期修复文档。
