### ISSUE TITLE
Tailer stop 方法未关闭RandomAccessFile 随机访问流 导致磁盘空间不释放

### ISSUE THREAD

**Issue by wlngo** [looly/hutool#2972]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

cn.hutool.core.io.file.Tailer 类名
Tailer stop 方法 未关闭RandomAccessFile的资源  导致磁盘空间不释放

![image](https://user-images.githubusercontent.com/85060647/224246933-48877c05-25b4-40b0-9b4a-337ea0d1b955.png)

1. 复现代码 ![image](https://user-images.githubusercontent.com/85060647/224247415-3bd16cce-7054-4dd9-9940-51b995ee74eb.png)

2 .Linux  查询命令 lsof  path |grep delete

**Comment by looly** [comment]
更新到最新版本，修复了这个问题：

![image](https://user-images.githubusercontent.com/1432613/224335048-7aa2b10d-9c0a-42c2-aa96-39d43e716472.png)

![image](https://user-images.githubusercontent.com/1432613/224335185-e6afe265-9532-47c4-9b84-fef48cea1859.png)

**Comment by wlngo** [comment]
已收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden ***@***.***&gt;; 
发送时间: 2023年3月10日(星期五) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/hutool] Tailer stop 方法未关闭RandomAccessFile 随机访问流 导致磁盘空间不释放 (Issue #2972)





 
更新到最新版本，修复了这个问题：
