### ISSUE TITLE
能不能支持收邮件啊，比如获取邮件title，内容，时间等的封装方法。如果不通用，可以针对邮箱封装，比如qq邮箱，163邮箱，gmail邮箱等

### ISSUE THREAD

**Issue by PandaSkying** [looly/hutool#2973]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
暂时没有封装，只有发件封装。

**Comment by MagicDev001** [comment]
请问发送邮件之后，可以拿到邮件的UID或者其他能够用来对邮件排重的参数吗？我需要按照时间范围同步邮件到本地，根据哪个参数可以对邮件排重呀？

**Comment by looly** [comment]
send方法调用后，返回`message-id`
