### ISSUE TITLE
针对于Alias注解的建议

### ISSUE THREAD

**Issue by jdAction** [looly/hutool#2978]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12

### 问题描述（包括截图）
Alias在转换的时候其解析的key只能是一层解析转换，能否增加多层解析？
下图是目前使用的情况
![image](https://user-images.githubusercontent.com/87454525/224635396-e53d7122-d3ba-49e6-bbe1-3cb48883c47d.png)
能否增加多层解析，如下图所示
![image](https://user-images.githubusercontent.com/87454525/224635619-bd88139c-d860-4648-b853-0666330b9e39.png)
解析的代码思路
![image](https://user-images.githubusercontent.com/87454525/224635848-c5472756-2d1a-4220-ba0d-c815d22f8772.png)
![image](https://user-images.githubusercontent.com/87454525/224635942-d0009d07-ef59-4e6e-8b5b-f3e790bf3089.png)

**Comment by looly** [comment]
多层解析需要通过JSON完成。

**Comment by jdAction** [comment]
直接通过注解帮忙把这个事做了不可行吗

**Comment by looly** [comment]
不行。bean操作是非递归的。所以无法完成。
