### ISSUE TITLE
HttpRequest在spring boot @Async异步执行登录多账户切换操作后出现cookie混乱

### ISSUE THREAD

**Issue by Andy5972** [looly/hutool#298]
HttpRequest在spring boot @Async异步执行登录多账户切换操作后出现cookie混乱
CPID_3=24260813;LOGINAID=3;LOGINUID=25576542;错误cookies
CPID_3=27246492;LOGINAID=3;LOGINUID=24260813;错误cookies 
正确cookies值 CPID_3=LOGINUID 
操作过程是模拟登录 多账户 采用@Async异步操作登录方法，登录多次切换后出现cookies混乱

**Comment by Andy5972** [comment]
4.5.1最新版本

**Comment by looly** [comment]
不知道@async是用在客户端还是服务端？如果是客户端不建议使用，HttpRequest并不能单例使用。

Hutool的Cookie使用JDK自带的CookieManager管理，且多线程是分别管理的。看是否是这个导致的？

**Comment by Andy5972** [comment]
我看了代码 HttpRequest是不是可以加个clearcookies的 方法
对于线程池下 ThreaLocal的使用情况 可以手动清理cookies
这样就不会造成 线程池重用 造成 ThreadLocal 存储cookies造成的错乱
不知道 理解的对不对
@looly

**Comment by looly** [comment]
有个closeCookie方法

**Comment by Andy5972** [comment]
closeCookie是禁用cookie了  
测试添加clearcookies后 未出现 cookie混乱， 在存在线程池调用HttpRequest 多账户cookie可以 参考
功能需求是爬虫项目 维护多账户 cookie
/**
	 * 清理cookies
	 * @return
	 */
	public static boolean clearCookies(){
		return cookieManager.getCookieStore().removeAll();
	}

**Comment by Andy5972** [comment]
其实考虑到ThreadLocalCookieStore对cookie的维护 如果多账户 情况 意义不大 肯定是会清理cookie保持http环境清洁。不知道 理解对不对。
