### ISSUE TITLE
关于Dateutil中获得指定日期区间内的年份和季节方法的问题

### ISSUE THREAD

**Issue by jzdayz** [looly/hutool#2982]
### 版本情况

JDK版本：    openjdk 1.8.0_362
hutool版本： 5.7.3(最新的5.8.15也试过)

### 问题描述（包括截图）

1. 复现代码

我观察到方法注释为：获得指定日期区间内的年份和季节
理论上来讲，这两段代码获取的结果应该是一致的才对。

```java
Console.log(DateUtil.yearAndQuarter(DateUtil.parse("2022-09-01"), DateUtil.parse("2023-08-31")));
Console.log(DateUtil.yearAndQuarter(DateUtil.parse("2022-07-01"), DateUtil.parse("2023-08-31")));
```
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/35563513/224927373-305002a3-dc4a-4bc2-a656-551c54cea2cb.png">

**Comment by looly** [comment]
这里跟计算方式有关：

这个方法遍历时间段内的季度列表，但是循环方式是：

** 在初始日期的基础上，每次增加三个月 **

这种规则导致两个日期段获得的结果列表不一致。

**Comment by looly** [comment]
v6版本中会删除这个方法。
