### ISSUE TITLE
使用Db.query或page方法查询数据时，使用 in 查询 and上其它条件无法查出数据

### ISSUE THREAD

**Issue by fnyhD** [looly/hutool#2986]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.3

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/72966095/225233095-1ca83cb8-a2bf-4d89-8c39-627fe0f3c94e.png)
ids为String[]
使用Db.query或page方法查询数据时 使用in条件再and上其它条件无法查出数据（条数为0），将in 换成 = 条件可以正常查询，或者只使用in 条件时或单独使用其它条件时可以正常查询满足条件数据
![image](https://user-images.githubusercontent.com/72966095/225232785-17f0a869-c2d5-4ae7-8046-d733dc80e578.png)
在控制台可以正常查询出满足条件数据

**Comment by looly** [comment]
麻烦设置下showSql = true，打印下生成的SQL语句，可能是String被转换为了不同类型。

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/225247221-94712fc9-51c2-4e1a-b314-76b49c299d70.png)

![image](https://user-images.githubusercontent.com/1432613/225247100-762aafd7-c3e6-4c4c-ad41-93be7709207d.png)

**Comment by fnyhD** [comment]
![image](https://user-images.githubusercontent.com/72966095/225249455-9c672836-9137-4463-ac35-62e3f35ce616.png)
你好，这是打印的sql

**Comment by fnyhD** [comment]
![image](https://user-images.githubusercontent.com/72966095/225249763-e96becb8-1f1a-4dbd-a952-babab2a6c899.png)

**Comment by fnyhD** [comment]
单独使用in时，参数是MapUtil.of("ids", ids)里面的元素，in再and其它条件 in的参数是MapUtil.of("ids", ids)的地址 导致查不出来数据
sql执行情况:
单独使用in：
![image](https://user-images.githubusercontent.com/72966095/225254141-52c86ad0-6959-43e3-8488-3f00246c55f5.png)
in and 其它条件：
![image](https://user-images.githubusercontent.com/72966095/225255415-16e6ed55-3ff8-4d80-9b61-68b8ca34db1a.png)

**Comment by looly** [comment]
变量参数和？不能混用，建议所有参数都用变量名代替：

![image](https://user-images.githubusercontent.com/1432613/225694554-ce4ab779-3b34-496f-8205-ce60c3fb9bff.png)
