### ISSUE TITLE
ThreadUtil使用咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#2988]
咨询个事情，假如项目中有很多地方调用了ThreadUtil.execute  execAsync 等方法，现在想自定义线程池了，是不是这些方法都要改成我自己的线程池.execute，还有其它方法吗？

**Comment by looly** [comment]
当然。你需要自己使用`ExecutorBuilder`创建一个自定义线程池，然后替换对应的方法。

默认使用的是`GlobalThreadPool`
