### ISSUE TITLE
ExcelWriter.merge指定行列合并单元格有内容不会自动跳到下一行

### ISSUE THREAD

**Issue by Road-Work** [looly/hutool#2994]
### 版本情况

JDK版本：    java version "1.8.0_201"
hutool版本： 5.6.5（确认最新5.8.15还存在）

### 问题描述（包括截图）

ExcelWriter merge(int firstRow, int lastRow, int firstColumn, int lastColumn, Object content, boolean isSetHeaderStyle)方法content != null 不会自动跳到下一行

文档上是写的有内容会自动跳到下一行
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/48465812/226097389-fab5b035-5205-4c0b-b2fd-78e50e5c252a.png">
源码没有看到跳到下一行的代码
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/48465812/226097458-9713ec5a-310c-45ca-b6c0-914f97006b67.png">
相似的方法有跳到下一行的代码
<img width="937" alt="image" src="https://user-images.githubusercontent.com/48465812/226097543-794fd4b7-7ec7-49f3-9edc-7d9c1268fb8c.png">

**Comment by looly** [comment]
注释问题，已修正。

第二个方法会将值写出到下一行，是因为使用了**当前行**的概念，下一行是没东西的。

但是第一个方法制定了行号，下一行可能有内容，覆盖则会有问题。
