### ISSUE TITLE
TimedCache，没有获取 key什么时候过期的方法

### ISSUE THREAD

**Issue by Cmc0** [looly/hutool#2996]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.14（请确保最新尝试是否还有问题）

**Comment by Cmc0** [comment]
加几行代码就可以解决了，这个问题 🙏🙏

**Comment by looly** [comment]
你可以继承`TimedCache`，复写getWithoutLock方法。

通过调用`getWithoutLock(key).getExpiredTime()`读取。
