### ISSUE TITLE
HttpInterceptor拦截器增强

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#2998]
cn.hutool.http.HttpInterceptor#process方法是否可以改成 Response proceed(Request request)  或 增加请求上下文，
类似于okhttp okhttp3.Interceptor.Chain#proceed 或 org.apache.http.HttpResponseInterceptor#process

现在有需要给所有的http请求做监控打点，目前hutool的请求、响应拦截器是分开的 且 没有请求上下文，没有想到解决方法

**Comment by looly** [comment]
sorry，由于设计问题（可能为设计缺陷），在5.x中无法实现增加context。

6.x考虑增加。

**Comment by ljynfo** [comment]
@looly 请问6.x的版本计划是啥呀，啥时候release

**Comment by looly** [comment]
@ljynfo 还有几个大块问题没有解决，尤其Htttp这块做了大的改动，结束后发布。
