### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class cn.hutool.extra.qrcode.QrCodeUtil

### ISSUE THREAD

**Issue by qingquaner** [looly/hutool#3001]
### 版本情况

JDK版本：    1.8
<dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-all</artifactId>
      <version>5.8.14</version>
  </dependency>
<dependency>
    <groupId>com.google.zxing</groupId>
    <artifactId>core</artifactId>
    <version>3.5.1</version>
</dependency>
![image](https://user-images.githubusercontent.com/20200473/226502903-e2f70a84-83e3-4f8a-a7fe-7be929f96e5d.png)

**Comment by looly** [comment]
检查版本冲突，是否引入多个版本的Hutool了。
