### ISSUE TITLE
去除ExcelPicUtil中的Assert调用，改为抛出异常

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [looly/hutool#3003]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.15

### 问题描述（包括截图）
https://github.com/dromara/hutool/blame/9b81e5502daabe21ff7f71bcb420662c7d1c3b90/hutool-poi/src/main/java/cn/hutool/poi/excel/ExcelPicUtil.java#L42

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这不就是抛出异常么？
