### ISSUE TITLE
WatchUtil createModify maxDepth传递后没有使用

### ISSUE THREAD

**Issue by yanchengfei** [looly/hutool#3005]
JDK版本：    openjdk_8_201
hutool版本： 5.8.15（请确保最新尝试是否还有问题）

/**
* 创建并初始化监听，监听修改事件
*
* @param file 被监听文件
* @param maxDepth 当监听目录时，监听目录的最大深度，当设置值为1（或小于1）时，表示不递归监听子目录
* @param watcher {@link Watcher}
* @return {@link WatchMonitor}
* @since 4.5.2
*/
public static WatchMonitor createModify(File file, int maxDepth, Watcher watcher) {
return createModify(file.toPath(), 0, watcher);
}

**Comment by looly** [comment]
5.8.16修复此问题，感谢！

**Comment by yanchengfei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
