### ISSUE TITLE
props.toBean 数组字段未赋值

### ISSUE THREAD

**Issue by ijxinyu** [looly/hutool#3008]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.15

### 问题描述（包括截图）

 从properties获取属性并赋值给Bean。
1.test
![image](https://user-images.githubusercontent.com/11799914/227126680-10287a34-253b-4383-906e-c9278c0d5318.png)
2.properties
![image](https://user-images.githubusercontent.com/11799914/227126970-9835c070-85eb-4b37-911c-119c7ce34cf2.png)
3.bean
![image](https://user-images.githubusercontent.com/11799914/227127046-d9f06822-f704-4ec5-a1b3-88ecf49d01b5.png)
4.result
![image](https://user-images.githubusercontent.com/11799914/227127123-c6726dab-9024-4e0b-9e3c-28256c8f0466.png)

**Comment by looly** [comment]
确实无法注入。

原因是注入数组产生新的数组，导致值丢失。

5.8.16修复此问题，感谢！
