### ISSUE TITLE
Sftp和JschUtil是否可以增加proxy的配置

### ISSUE THREAD

**Issue by xingguang2013** [looly/hutool#301]
cn.hutool.extra.ssh.Sftp和cn.hutool.extra.ssh.JschUtil发现没有proxy配置，是否可以增加，查了资料，应该是在`com.jcraft.jsch.Session#setProxy`

**Comment by looly** [comment]
4.5.2可以这么用：

Sftp构造方法支持传入Session对象，而Session对象可以通过openSession获取，要想使用代理，则：

```
Session session = JschUtil.createSession(host, port, user, pass);
session.setProxy(proxy);
JschUtil.createSftp(session);
```

**Comment by xingguang2013** [comment]
`cn.hutool.extra.ssh.JschUtil#openSession`方法中已经调用了`com.jcraft.jsch.Session#connect()`方法，也就是已经创建了连接，后面再设置proxy，已经无效了

**Comment by looly** [comment]
4.5.2增加`createSession`方法，感谢。
