### ISSUE TITLE
希望优化MurmurHash中hash32，可以选择是返回int还是long

### ISSUE THREAD

**Issue by wnhyang** [looly/hutool#3010]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
MurmurHash.hash32("xxxxxx")
```
因为java没有无符号数的原因，我希望从hash32拿到的是准确的int（无符号的），但现在是不满足的，所以希望能优化这个返回可以有long可选

**Comment by looly** [comment]
我没太懂你的意思？32位不用int表示么？

麻烦补充后再打开issue。
