### ISSUE TITLE
CsvWriter 存在DDE攻击风险

### ISSUE THREAD

**Issue by li-keguo** [looly/hutool#3014]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述
CsvWriter 存在DDE攻击风险

1. 复现代码

```java
		//指定路径和编码
		CsvWriter writer = CsvUtil.getWriter("D:\\tmp\\testWrite.csv", CharsetUtil.CHARSET_UTF_8);
		//按行写出
		writer.write(
				new String[] {"a1", "b1", "=12+23"},
				new String[] {"a2", "b2", "c2"},
				new String[] {"a3", "b3", "c3"}
		);
``` 

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

![image](https://user-images.githubusercontent.com/33576070/227455505-748e874c-1b57-4614-9541-8a48b7fdb846.png)

**Comment by looly** [comment]
这个漏洞不应该是写CSV来防护吧？应该是解析器来防护吧？

就好比我写出到文件一个`rm -rf *`，那这也算漏洞？

**Comment by li-keguo** [comment]
Hi @looly ,我认同你说的应该在解析的时候防护，我也并不认为这是一个漏洞或者bug。

在实际场景中导出的文件极有可能被用户使用execl等工具打开，这些人可能并不具备网络安全的相关知识，这使得DDE有机可乘。

hutool是一个工具，能否在写入的时候提供safeWitter的实现，在写入的时候对潜在的攻击字符串进行转义和清洗，当然这必然会导致写入效率的低下。我们可以在文档中予以说明。提供用户可选空间，我找了很多工具都没有类似的实现。

**Comment by looly** [comment]
@li-keguo 嗯，我也查了相关资料和其他库的实现，只能“帮助”用户添加一些特殊符号（如`）来避免公式解析。

虽然对excel是友好的，但是可能对于其它CSV工具就是不兼容了。

找到了类似文章：https://blog.csdn.net/weixin_41924764/article/details/108665746

**Comment by LiuTianyou** [comment]
你好 @looly ：Csvwriter 是否考虑增加这个特性，如果是的话我想贡献这部分代码

**Comment by looly** [comment]
@LiuTianyou 麻烦提交到v6-dev分支，感谢~

**Comment by looly** [comment]
关联PR：https://github.com/dromara/hutool/pull/3016
