### ISSUE TITLE
使用雪花ID生成主键，出现了20位的雪花ID，正常的雪花ID都是19位的

### ISSUE THREAD

**Issue by xinwangji** [looly/hutool#3015]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用雪花ID生成主键，出现了20位的雪花ID，正常的雪花ID都是19位的
![image](https://user-images.githubusercontent.com/26083013/227682086-0da42f5c-e19a-4f79-82f2-6ba07f1c87b7.png)

![image](https://user-images.githubusercontent.com/26083013/227682134-349c0438-66a8-4080-84a2-5ac89bdb8763.png)

1. 复现代码

```java
    public void add(AddMessageAnnouncementDTO dto) {
        MessageAnnouncementPO po = new MessageAnnouncementPO();
        BeanUtils.copyProperties(dto, po);
        po.setId(IdUtil.getSnowflake().nextId());
        setCreator(po, AuthUserContextUtils.getUserByToken());
        messageAnnouncementMapper.insert(po);
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by BingChunMoLi** [comment]
雪花算法 如果带符号位，是20位第一位恒定0，表示正数。19位为简化写法

**Comment by CherryRum** [comment]
正常情况下，不会出现负数，您看下您的系统时间是什么时候
