### ISSUE TITLE
解压缩失败Zip bomb attack detected

### ISSUE THREAD

**Issue by airujingye** [looly/hutool#3018]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用最新版后，解压zip文件时提示Zip bomb attack detected。之前使用5.5.2版本没有这个问题。

1. 复现代码
//压缩文件的代码是
ZipUtil.zip(exportDir, Charset.forName("UTF-8"));

// 解压代码
unzipDir = ZipUtil.unzip(modelFile.getInputStream(), tempDir, Charset.forName("UTF-8"));
```java
Console.log("报错了");
```
// 报错信息
cn.hutool.core.exceptions.UtilException: Zip bomb attack detected, invalid sizes: compressed -1, uncompressed -1, name cy_user_process.png
	at cn.hutool.core.compress.ZipReader.checkZipBomb(ZipReader.java:247)
	at cn.hutool.core.compress.ZipReader.readFromStream(ZipReader.java:224)
	at cn.hutool.core.compress.ZipReader.read(ZipReader.java:188)
	at cn.hutool.core.compress.ZipReader.readTo(ZipReader.java:148)
	at cn.hutool.core.compress.ZipReader.readTo(ZipReader.java:135)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:665)
	at cn.hutool.core.util.ZipUtil.unzip(ZipUtil.java:650)
3. 堆栈信息
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/15830628/227833089-c94862cc-8a0f-4f10-baa8-70a730dfd8fd.png">

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
新版本中增加了Zip bomb漏洞安全检查。

![image](https://user-images.githubusercontent.com/1432613/227893379-d2216903-9414-4e7b-9c50-507562856bf1.png)

看报错是你的`name cy_user_process.png`文件压缩后大小没有读到。

麻烦提供下测试的文件，之后再打开此issue。

**Comment by airujingye** [comment]
> 新版本中增加了Zip bomb漏洞安全检查。
> 
> ![image](https://user-images.githubusercontent.com/1432613/227893379-d2216903-9414-4e7b-9c50-507562856bf1.png)
> 
> 看报错是你的`name cy_user_process.png`文件压缩后大小没有读到。
> 
> 麻烦提供下测试的文件，之后再打开此issue。

[导出导入测试.zip](https://github.com/dromara/hutool/files/11077384/default.zip)
这个压缩文件是用hutool代码压缩的，如果手动解压后再压缩，最后用代码执行解压就没这个问题ZipUtil.unzip()

**Comment by looly** [comment]
@airujingye 

![image](https://user-images.githubusercontent.com/1432613/227924684-8c38c88b-6b31-4709-b165-53c14f37e743.png)

![image](https://user-images.githubusercontent.com/1432613/227924803-8e858ff8-7a1f-4a1c-a960-54eac766d34a.png)

经过测试，使用文件方式可以正常读取元信息，但是使用流不行。

保留此issue稍后处理。

**Comment by looly** [comment]
5.8.17修复此问题，感谢~

**Comment by werfei** [comment]
5.8.17依然存在这个问题

**Comment by looly** [comment]
@werfei 更新最新试下。

**Comment by chuzhongzai** [comment]
版本情况
JDK版本： openjdk-17.0.5
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

问题描述（包括截图）
刚刚好遇到压缩一百倍的情况，导致zip bomb错误。能否给一个检测炸弹的开关或者提供改倍数的函数？这个是自己两个服务器之间传文件的场景，也许还有其他不需要检测炸弹的场景？
![image](https://github.com/dromara/hutool/assets/36190484/2622f312-00fc-4a14-9fb8-af371cf9c2cc)


[test.zip](https://github.com/dromara/hutool/files/12092367/test.zip)

**Comment by looly** [comment]
@A-Pupils-form-china 这里确实是个极端的例子。

5.8.21在`ZipReader`中增加`setMaxSizeDiff`方法来自定义这个参数。

**Comment by makewheels** [comment]
> @A-Pupils-form-china 这里确实是个极端的例子。
> 
> 5.8.21在`ZipReader`中增加`setMaxSizeDiff`方法来自定义这个参数。

请问下，如何使用setMaxSizeDiff方法呢？在调用ZipUtil.unzip的时候，里面是new的ZipReader

![Image](https://github.com/user-attachments/assets/ca332ff4-caa6-4f04-8944-96d9627361cf)

**Comment by looly** [comment]
@makewheels 自行构建`ZipReader`，然后设置。
