### ISSUE TITLE
wps创建的doc文件后缀识别为xls

### ISSUE THREAD

**Issue by laoxilaoxi** [looly/hutool#3024]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.15

### 问题描述

1. 复现代码

```java
        FileInputStream fileInputStream = new FileInputStream("/Users/laoxi/Desktop/321.doc");
        String x = FileTypeUtil.getType(fileInputStream,true);
        System.out.println(x);
```
输出结果为：xls

321.doc文件是通过wps创建的doc文件。测试office创建的doc文件无此问题。

**Comment by looly** [comment]
麻烦提供下生成的doc文件我看下magic number。

**Comment by laoxilaoxi** [comment]
[TEST_WPS_DOC.docx](https://github.com/dromara/hutool/files/11095806/TEST_WPS_DOC.docx)
文件后缀原本是.doc的，因为github不支持上传.doc文件，所以将后缀修改为.docx。这个文件原本名称为TEST_WPS_DOC.doc

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/228422568-051ebca5-58ae-40dc-9f6d-3e9967e3d4dc.png)

我这边测试正常。
这个功能在新版本中做了较大变动，麻烦升级到5.8.16尝试。

**Comment by looly** [comment]
查阅相关资料，确实是xls和doc两个文件的magic number是一样的。

**Comment by CherryRum** [comment]
@laoxilaoxi  这个是我写的，因为规范问题，我参考的文件魔术
![image](https://user-images.githubusercontent.com/24296698/228432812-64f4b3c6-6f44-4502-a597-bf56564ff271.png)

正常的doc文件 0x200 后面应该是 `[512 (0x200) byte offset]
EC A5 C1 00`
如下
![image](https://user-images.githubusercontent.com/24296698/228433163-db56ae18-c619-4caf-bd20-564c6dbde9db.png)
wps 保存过的
![11861680066586_ pic](https://user-images.githubusercontent.com/24296698/228433329-be387dd8-6585-4d30-982b-6d4d7d01b7ee.jpg)

所以这个问题属于`wps` 不讲道理，插入了自己的文件头，而且不提供文档
