### ISSUE TITLE
Numberutile error 

### ISSUE THREAD

**Issue by yu5056561661** [looly/hutool#3027]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
System.out.println(NumberUtil.add("1.00","0.00"));
在本地计算是正确的1，但是在客户德语电脑上计算出来 居然是100， 4.5几的版本是正常的，最新版也是错误的
![image](https://user-images.githubusercontent.com/75231131/228502467-bdd1a885-71c1-45b8-af20-bf0cb1d18445.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I6REMW
