### ISSUE TITLE
ExcelUtil工具类合并单元格超过100行会出错

### ISSUE THREAD

**Issue by Suzzt** [looly/hutool#3028]
### 版本情况

JDK版本：    任何版本
hutool版本： 5.8.16
poi版本
` <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-schemas</artifactId>
            <version>4.0.0</version>
        </dependency>`

### 问题描述（包括截图）
合并单元格100行以上会直接报错。但是感觉是poi能力有问题，但是我觉得hutool应该也要兼容这一块内容

1. 复现代码

```java
public static void main(String[] args) {
    //合并101行就会直接报一层
    ExcelUtil.getBigWriter("/data/test.xlsx").merge(0, 101, 0, 0, "111111", false).flush();
}
```
2.报错
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/27397567/228723182-98f2107c-e164-40cb-a23a-8dad926442cb.png">

**Comment by looly** [comment]
使用`getWriter`，不要使用BigWriter。

bigwriter在内存中有个窗口大小的概念，也就是默认只在内存中保留的行数，这个默认值是100，因此你合并101会报错。

你也可以自己增加这个窗口大小。

![image](https://user-images.githubusercontent.com/1432613/228873013-9121342f-2e45-4108-8379-8a4830ef1195.png)
