### ISSUE TITLE
优化PathMover.move()的异常捕捉和处理

### ISSUE THREAD

**Issue by LeonemZhang** [looly/hutool#3033]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.14

### 问题描述（包括截图）
优化PathMover.move()的异常捕捉和处理
![image](https://user-images.githubusercontent.com/50519058/229017220-d60e1e39-d5e5-4d05-b696-2db92daeee77.png)
如果是跨分区移动导致的移动失败才应该调用`walkMove(src, target, options);` 和`PathUtil.del(src);`
有很多其他类型的错误应该直接抛异常，比如文件被占用，文件无权限访问
![image](https://user-images.githubusercontent.com/50519058/229017183-f377f629-86c2-44de-bd36-9b30c3573373.png)

**Comment by looly** [comment]
你看这里捕获的是`IOException`，你说的无权限这类异常直接抛出了。

**Comment by LeonemZhang** [comment]
![image](https://user-images.githubusercontent.com/50519058/229397682-2059213e-fc50-4418-9268-e40ab2e781f9.png)
![image](https://user-images.githubusercontent.com/50519058/229397590-bc666896-0362-445f-aeb3-0489190b0dcd.png)

![image](https://user-images.githubusercontent.com/50519058/229397709-ff57d7da-8a8e-4966-ae5c-13c60ecc8383.png)


> 你看这里捕获的是`IOException`，你说的无权限这类异常直接抛出了。

**Comment by LeonemZhang** [comment]
> ![image](https://user-images.githubusercontent.com/50519058/229397682-2059213e-fc50-4418-9268-e40ab2e781f9.png) ![image](https://user-images.githubusercontent.com/50519058/229397590-bc666896-0362-445f-aeb3-0489190b0dcd.png)
> 
> ![image](https://user-images.githubusercontent.com/50519058/229397709-ff57d7da-8a8e-4966-ae5c-13c60ecc8383.png)
> 
> > 你看这里捕获的是`IOException`，你说的无权限这类异常直接抛出了。

我调试的时候遇到好几个FileSystemException，它是IOException的子类，被捕获了可是没有被抛出啊

**Comment by looly** [comment]
其他异常我是无法区分是否是跨分区移动导致的，所以没有捕获。

**Comment by LeonemZhang** [comment]
> 其他异常我是无法区分是否是跨分区移动导致的，所以没有捕获。

我觉得大多数情况下至少不能走到`PathUtil.del()`的case中

**Comment by looly** [comment]
对啊，walkMove执行失败肯定不能执行到PathUtil.del。

但是减少异常捕获的种类，会增加walkMove的执行。
