### ISSUE TITLE
FileUtil.move() 把父目录移到子目录会无限递归创建目录

### ISSUE THREAD

**Issue by LeonemZhang** [looly/hutool#3034]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.14

### 问题描述（包括截图）

1. 复现代码
`PathUtil.rename()`把父目录移到子目录会无限递归创建目录
![image](https://user-images.githubusercontent.com/50519058/229032459-8d2ad2e9-137f-44dc-84ba-e581bd3abef3.png)

**Comment by LeonemZhang** [comment]
![image](https://user-images.githubusercontent.com/50519058/229035914-bef9ae93-2698-4c5c-b48e-39b6f4fb2ce5.png)
![image](https://user-images.githubusercontent.com/50519058/229035945-1f57bb5b-94f4-4921-b531-b70a6bed3fed.png)
![image](https://user-images.githubusercontent.com/50519058/229036052-2a680712-2d46-4645-a6b0-08135e7d34f5.png)
这里每resolve一次，就多一层目录
![image](https://user-images.githubusercontent.com/50519058/229036371-f35bd70c-6b20-4b41-8132-915d5cc4fc28.png)

**Comment by looly** [comment]
这个在上次修改中一并解决。
