### ISSUE TITLE
LRUCache 内存溢出

### ISSUE THREAD

**Issue by yangWwww** [looly/hutool#3040]
### 版本情况

JDK版本：    1.8.0_321
hutool版本： 5.4.7

### 问题描述（包括截图）
使用以下工具类并创建了一个LRU缓存,程序运行了一段时间后fullgc频繁发生,分析dump获取到以下信息:
![Image_20230403160852](https://user-images.githubusercontent.com/26993300/229449932-89a80faa-101e-4c76-b7cd-c17d30289147.png)

![Image_20230403160901](https://user-images.githubusercontent.com/26993300/229449958-c908456f-6a42-4953-be27-a65cb1f0ce5f.png)

![Image_20230403161005](https://user-images.githubusercontent.com/26993300/229450094-d195f144-0e64-4682-9014-f547332238a0.png)

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@Slf4j
public class WorkOrderCommonParamterUtile {

    public WorkOrderCommonParamterUtile() {
    }
    private static LRUCache<String,WorkOrderCommonParamter> workOrderCommonParamterMap=new LRUCache<String,WorkOrderCommonParamter>(3);
    int setCacheCapcity=0;

    public static WorkOrderCommonParamter getWorkOrderCommonParamterByModelId(String modelId){
        if(workOrderCommonParamterMap.get(modelId) == null){
            workOrderCommonParamterMap.put(modelId,new WorkOrderCommonParamter());
        }
        return (WorkOrderCommonParamter) workOrderCommonParamterMap.get(modelId);
    }

}

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I6SL89
