### ISSUE TITLE
StrUtil.fillAfter

### ISSUE THREAD

**Issue by charles-xuchao** [looly/hutool#3046]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
StrUtil.fillAfter(tar,sour,length)
```

这个拼接的字符只能是字符串，限制使用范围了。
字符串的指定长度拼接使用的更高些，希望可以支持字符串的拼接了

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
没看懂你的意思。这个只是“填充”字符串而已。

麻烦补充后再打开issue。
