### ISSUE TITLE
分组计时ID不会被清除

### ISSUE THREAD

**Issue by QuarkYah** [looly/hutool#3047]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16

### 问题描述（包括截图）
分组ID存储到分组Map中，在计时结束后分组ID不会被清除，请问是设计如此吗

1. 复现代码

```java
TimeInterval timeInterval = new TimeInterval();
while (true) {
    String timeId = IdUtil.getSnowflakeNextIdStr();
    timeInterval.start(timeId);
    long ms = timeInterval.intervalMs(timeId);
    System.out.println(ms);
}
```

2. 堆栈信息
无

3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
带清除的请使用`StopWatch`。

事实上TimeInterval并不会清除ID，保留ID也是为了用户可以多次调用intervalXX方法。

如果想清除，可以手动调用`clear`方法。
