### ISSUE TITLE
Excel导出javaBean中有BigDecimal类型精度流失

### ISSUE THREAD

**Issue by yangfeng20** [looly/hutool#3048]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.10

### 问题描述
![image](https://user-images.githubusercontent.com/83114564/230573967-973c92e2-6582-4028-a0e7-ec8a4a4e68ae.png)
![image](https://user-images.githubusercontent.com/83114564/230574034-788f4bd9-ec05-4671-ab2a-ddb35fb397e9.png)
excel导出实体bean对象，bigDecimal类型的数据精度流失。

1. 复现代码

        List<xxxxx> excelExportList = xxxx;
        ExcelWriter excelWriter = ExcelUtil.getWriter(true);
        excelWriter.write(excelExportList, true);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        excelWriter.flush(outputStream);
        excelWriter.close();

**Comment by GengMS** [comment]
这个问题可以通过ExcelWriter.setStyleSet 方法 设置自定义单元格样式解决， 可以自定义数字单元格的小数精度保留位数。

**Comment by GengMS** [comment]
添加 数字单元格精度据单元格实际数值自动适配新特性；https://github.com/dromara/hutool/pull/3050；
用这个新特性也可以，目前还未合并到仓库

**Comment by yangfeng20** [comment]
好的啊，但是这个其实它本身就是Bigdecimal类型，后面能根据类型决定精度吗
