### ISSUE TITLE
重大bug，fastjson2升级到2.0.27后Hutool工具的Dict字段接收不到数据了

### ISSUE THREAD

**Issue by yuxicun** [looly/hutool#3049]
重大bug，fastjson2升级到2.0.27后Hutool工具的Dict字段接收不到数据了

**Comment by CherryRum** [comment]
能提供一个测试样例吗

**Comment by yuxicun** [comment]
https://github.com/alibaba/fastjson2/issues/1338   问题参照这里,目前尚不知道到底是hutool的问题还是fastjson的问题  .如果我降低fastjson2到2.0.26版本,对Dict支持正常,但是用hutool的JSONUtil.Parse转换json字串报错

**Comment by yuxicun** [comment]
![image](https://user-images.githubusercontent.com/18489852/230748452-1cca68f0-2480-4efd-ba7d-f8a042fd5588.png)
![image](https://user-images.githubusercontent.com/18489852/230748521-cdeef44b-d047-43e9-8237-ab5b698b90c2.png)

![image](https://user-images.githubusercontent.com/18489852/230748513-a07950b3-93cb-4b51-a817-6fab9115d90e.png)

**Comment by yuxicun** [comment]
@Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        TimeZone.setDefault(TimeZone.getTimeZone("GMT+8"));
        Locale.setDefault(Locale.CHINA);

        //移除默认的jackson2适配器
        for (int i = converters.size() - 1; i > -1; i--) {
            if ((converters.get(i) instanceof MappingJackson2HttpMessageConverter)) {
                converters.remove(i);
            }
        }
        FastJsonHttpMessageConverter fastJsonConverter = new FastJsonHttpMessageConverter();

        //创建fastjson配置
        FastJsonConfig fastJsonConfig = new FastJsonConfig();
        fastJsonConfig.setDateFormat("yyyy-MM-dd HH:mm:ss");// 设置默认日期格式
        fastJsonConfig.setCharset(StandardCharsets.UTF_8);

        // 设置过滤器,存在异常
//        fastJsonConfig.setSerializeFilters((ValueFilter) (object, name, value) -> {
//            if (value instanceof LocalDateTime) {
//                ;
//            }
////            log.info("{}", object, name, value);
////            return object;
//        });

        fastJsonConfig.setWriterFeatures(
                //大范围数超出js整数,输出字符串格式
                JSONWriter.Feature.BrowserCompatible,
                //Long转string丢失精度问题
                JSONWriter.Feature.WriteLongAsString,
                // 保留map空的字段
                JSONWriter.Feature.WriteMapNullValue,
                //将List类型的null转成[]
                JSONWriter.Feature.WriteNullListAsEmpty,
                //将Boolean类型的null转成false
                JSONWriter.Feature.WriteNullBooleanAsFalse,
                //将Number类型的null转成0
                JSONWriter.Feature.WriteNullNumberAsZero,
                //日期格式转换
                JSONWriter.Feature.PrettyFormat,
                //将空置输出为缺省值，Number类型的null都输出为0，String类型的null输出为""，数组和Collection类型的输出为[]
                JSONWriter.Feature.NullAsDefaultValue);
        fastJsonConverter.setFastJsonConfig(fastJsonConfig);
        fastJsonConverter.setDefaultCharset(StandardCharsets.UTF_8);
        fastJsonConverter.setSupportedMediaTypes(Collections.singletonList(MediaType.APPLICATION_JSON));

        converters.add(0, fastJsonConverter);
    }

**Comment by looly** [comment]
@yuxicun 温大已经回复了，他那边的问题，你测试下fastjson2的snapshot版本。

我先关闭issue了。
