### ISSUE TITLE
simhash多线程的问题

### ISSUE THREAD

**Issue by gaoxjin** [looly/hutool#305]
https://github.com/looly/hutool/blob/v4-master/hutool-core/src/main/java/cn/hutool/core/text/Simhash.java
算法实现来自：https://github.com/xlturing/Simhash4J
/** 按照分段存储simhash，查找更快速 */
`private List<Map<String, List<Long>>> storage;`
其中`List<Long>`在多线程情况下equals和store时存在线程安全问题。
建议store方法中
`final List<Long> ls = new ArrayList<Long>();`
改为
`final Queue<Long> queue= new ConcurrentLinkedQueue<>();`

**Comment by looly** [comment]
ConcurrentLinkedQueue不能根本性解决问题，4.5.3添加读写锁。感谢。
