### ISSUE TITLE
没有属性的对象转json字符串抛异常:Unsupported type[xxxx] to JSONObject!

### ISSUE THREAD

**Issue by sosojustdo** [looly/hutool#3051]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16

### 问题描述（包括截图）
一个没有属性的静态内部类，使用lombok builder注解构建对象实例后，转json字符串抛异常，使用版本回滚到5.8.3不报错，正常使用。
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/3364336/230919194-ec7b1399-e0be-427b-816d-8b3ec719ecd6.png">

1. 复现代码

```java
public class Test {

@Value
@Builder
@AllArgsConstructor
public static class OutputData {

}

public static void main(String[] args){
OutputData outputData = OutputData.builder().build();
String json = JSONUtil.toJsonStr(outputData));
}

}

```

**Comment by dengniSLM** [comment]
查了一下，该问题是json包下的ObjectMapper在序列化对象时，经过最后一层判断`BeanUtil.isReadableBean(source.getClass())`的Bean判断方法修改导致的，BeanUtil在[修复BeanUtil.hasGetter没有跳过getClass方法的问题](https://github.com/dromara/hutool/commit/a3f48ccb2937a6f75aefac1de1ca267828ac90a5)这次提交中把原getClass方法给屏蔽了，导致当一个bean class没有属性时，BeanUtil就会判断不是一个Bean对象，从而json序列化失败，但我觉得一个空属性的class在json序列化后不应该为`{}`吗？
望回复~

**Comment by sosojustdo** [comment]
> 

一个空属性的class在json序列化后理论上就应该为{}。目前在5.8.16版本是直接抛异常了，导致项目中许多地方使用JSONUtil.toJsonStr(空属性对象)报错，临时解决先回滚版本了。但是希望作者在新版本中考虑兼容空属性class转json字符串.

**Comment by looly** [comment]
暂时可以：

```java
String json = JSONUtil.toJsonStr(outputData), JSONConfig.create().setIgnoreError(true));
```

5.8.17修复此问题。
