### ISSUE TITLE
是否可以在HttpUtil类中添加downloadFile可以设置请求头的重载方法

### ISSUE THREAD

**Issue by hncdyj123** [looly/hutool#3053]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16

### 问题描述（包括截图）

1. 复现代码
```java
long fileSize = HttpUtil.downloadFile(ts.getUri(), FileUtil.file(tsAbsolutePath), streamProgress);
 log.info("<<<请求下载:uri=<{}>,第<{}>块,文件大小:{}<<<.", ts.getUri(), ts.getIndex(), fileSize);
```
--------------------------------------------------------------------------------------------------------------
```java
HttpDownloader类
private static HttpResponse requestDownload(String url, int timeout) {
		Assert.notBlank(url, "[url] is blank !");

		final HttpResponse response = HttpUtil.createGet(url, true)
				.timeout(timeout)
				.executeAsync();

		if (response.isOk()) {
			return response;
		}

		throw new HttpException("Server response error with status code: [{}]", response.getStatus());
	}
```
2.能否加个SetRequestHeader请求头的重载方法，一般在下载CDN上缓存的东西，不加请求头会报403错误
![image](https://user-images.githubusercontent.com/15844006/231046147-02d66078-7488-48f6-9843-5be99a29741c.png)

**Comment by looly** [comment]
考虑使用`GlobalHeaders.INSTANCE.header()`方法定义全局头信息。
