### ISSUE TITLE
考虑支持webdav服务吗，我看extra有sftp支持

### ISSUE THREAD

**Issue by lunasaw** [looly/hutool#3054]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不考虑支持。

HttpClient可以搞定。
