### ISSUE TITLE
CollUtil.reverseNew的异常

### ISSUE THREAD

**Issue by seavers** [looly/hutool#3056]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
CollUtil.reverseNew(List.of("7", "9", "8"))
```

2. 堆栈信息
会报错：java.lang.UnsupportedOperationException

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

很多时候Stream返回的toList，都是 unmodifiableList ，这个时候再 reverseNew 就报错了

**Comment by looly** [comment]
5.8.18修复此问题，感谢~~
