### ISSUE TITLE
AbstractCache的setListener方法描述不清晰

### ISSUE THREAD

**Issue by quanueilun** [looly/hutool#3061]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
setListener函数名不能直观理解listener的作用，实际上时onRemove中使用的，建议函数名改成setRemoveListener

![图片](https://user-images.githubusercontent.com/38317429/232205653-5367e9e9-23a0-44f2-b9f6-e1188b65974c.png)

![图片](https://user-images.githubusercontent.com/38317429/232205685-eeedbd5b-3cdf-4793-86ae-fbe8f356407b.png)

**Comment by looly** [comment]
嗯，原计划是这个接口完成多个行为的监听的，暂时只实现了onRemove而已。

这个在6.x中可能做变动。感谢。
