### ISSUE TITLE
5.8.17会自动将junit.jar打入包中

### ISSUE THREAD

**Issue by dph5199278** [looly/hutool#3062]
### 版本情况

hutool版本： 5.8.17

### 问题描述（包括截图）

只要引入5.8.17版本，打包就会多出junit等包，虽然大部分没多大影响，不过我这里引入junit会与我们项目的包起冲突

5.8.17打包后
![image](https://user-images.githubusercontent.com/5254255/232275243-ab3a1dff-5e26-4b44-a3e1-11f18072e769.png)

5.8.16打包后
![image](https://user-images.githubusercontent.com/5254255/232275314-0dbc5335-2a5f-465f-9540-9a5fe488614f.png)

这是框架后期都需要引入junit才能使用了吗？

**Comment by dph5199278** [comment]
这边初步的排查：
在v5分支上
![image](https://user-images.githubusercontent.com/5254255/232278342-7e8f403e-6f42-4d80-9d38-debd646b556a.png)
在v6分支上
![image](https://user-images.githubusercontent.com/5254255/232278392-ff318e22-f853-45f2-badd-15a77dda0d8f.png)

看来junit-jupiter-engine的引入只是为了测试，5.8.18版本是否考虑加上
```
<scope>test</scope>
```

:)

**Comment by looly** [comment]
啊啊啊，纯属失误！！！

5.8.18修复此问题！！！

这就修改提交。
