### ISSUE TITLE
NumberUtil的equals方法咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#3066]
想咨询个事情，现在NumberUtil.equals里有  long long 和 Number  Number

假如我有个是Integer，一个是int，这种判断就会提示“对equals的引用不明确“

这种情况应该很常见的吧，判断是否等于0或者等于1来判断数据是否正确等等，难道要转换吗？

public class View { Integer  a;}

NumberUtil.equals(view.getA(), 0)  难道要改成   NumberUtil.equals(view.getA(), Convert.toInt(0))

![image](https://user-images.githubusercontent.com/14087655/232522403-5ae1afed-7aea-4781-9700-6ae90b8a73f8.png)

**Comment by looly** [comment]
嗯……最早了是为了简化原始类型的判断，避免不必要的拆装箱操作，现在看来确实容易引起歧义……

暂时看你只能自行拆箱或装箱判断。

6.0.0删除掉无用方法~~
