### ISSUE TITLE
HttpRequest#toString输出form参数问题

### ISSUE THREAD

**Issue by zzzj1233** [looly/hutool#3072]
> 请求前请求的form参数都会转换为body方式，即a=1&b=2这种形式。因此没有必要打印。

可是这有两个前提诶
1. 必须是GET请求
2. 必须在调用execute()方法后

如果我在请求前打印httpRequest，这样form里的参数就无法在日志中提现

场景1. 使用POST请求
![image](https://user-images.githubusercontent.com/44407821/227901781-ef2b1bfe-3401-42be-afc7-f4059b0c891e.png)

场景2. 调用execute前
![image](https://user-images.githubusercontent.com/44407821/227902024-df97c06a-c4fb-4727-a36c-b8288455973f.png)

版本：5.8.16

_Originally posted by @zzzj1233 in https://github.com/dromara/hutool/issues/3020#issuecomment-1484813078_

**Comment by looly** [comment]
确实存在这个问题。

5.8.19优化这块的打印。

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/commit/b0d528e27b565ddce678cbf4d5deba66a8d2dbad
