### ISSUE TITLE
HexUtil.isHexNumber 不同版本结果有差异，没有明确说明

### ISSUE THREAD

**Issue by hotspring-zwb** [looly/hutool#3073]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.10

### 问题描述（包括截图）
5.8.10 版本以及之前版本判断 HexUtil.isHexNumber("0") 结果为 false, 5.8.11 及以后的版本 判断为 true, 这个逻辑不能随便改吧，如果改了，之前的代码里用这个做判断的，以前的项目代码就出bug了

1. 复现代码

```java
HexUtil.isHexNumber("0");
HexUtil.isHexNumber("002c");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
严格来说是bug修复了。

见：https://gitee.com/dromara/hutool/issues/I62H7K

https://github.com/dromara/hutool/commit/4e06f0261072ddc72b235427b0bd8d96c6aa865d
