### ISSUE TITLE
HttpRequest.body参数问题

### ISSUE THREAD

**Issue by kings1990** [looly/hutool#3074]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12

### 问题描述（包括截图）

代码如下，接收参数的时候**多了一个等号**

1. 复现代码

```java
HttpRequest request = HttpUtil.createPost("http://localhost:8081/book/test3");
request.body("aaa");
request.execute();
```

2.服务端
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/8969637/233274042-d7a5ffa4-b325-4d42-87c7-cc99cd71a941.png">

**Comment by looly** [comment]
我测试发出的确实只有`aaa`。

客户端没有问题。

你可以看下：https://blog.csdn.net/Crazyamada/article/details/60876667

默认请求是`x-www-form-urlencoded`可能理解成了form表单，你可以：

```java
HttpUtil.createPost("http://localhost:8888/body")
			.contentType(ContentType.JSON.getValue())
			.body("aaa")
			.execute();
```
