### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by randolph555** [looly/hutool#3075]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
<img width="714" alt="image" src="https://user-images.githubusercontent.com/22696026/233293804-fce8c58b-bfb1-4f48-a58d-a43e2627bfae.png">

1. 复现代码

```java
HttpResponse response = HttpUtil.createPost(CHAT_COMPLETIONS)
                .header("Authorization", BEARER + " " + appKey)
                .body(dto, "application/json")
                .setConnectionTimeout(1000)
                .setReadTimeout(12000)
                .execute();
```

2. 堆栈信息
<img width="714" alt="image" src="https://user-images.githubusercontent.com/22696026/233293804-fce8c58b-bfb1-4f48-a58d-a43e2627bfae.png">
3. 测试涉及到的文件（注意脱密）

在本地环境运行正常，部署到香港服务器出现这个问题.

换成okhttp本地和香港服务器都正常.

**Comment by randolph555** [comment]
尝试加入System.setProperty("https.protocols", "TLSv1.2,TLSv1.1,SSLv3");
无法解决。

补充jdk版本：java version "1.8.0_121"

**Comment by looly** [comment]
我遇到的也只是JDK版本和这个配置问题。

https://hutool.cn/docs/#/http/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

方便的话提供下请求的URL我这边测试再打开此issue。

**Comment by randolph555** [comment]
> 我遇到的也只是JDK版本和这个配置问题。
> 
> https://hutool.cn/docs/#/http/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
> 
> 方便的话提供下请求的URL我这边测试再打开此issue。

https://api.openai.com/v1/chat/completions

**Comment by looly** [comment]
sorry……我的网络环境不允许测试这个链接。

考虑更换HttpClient或者Okhttp吧。
