### ISSUE TITLE
关于Http无法解析Response的br压缩

### ISSUE THREAD

**Issue by live-in-a-dream** [looly/hutool#3076]
版本5.7.20并没有实现对于br压缩的解压。

HttpInputStream的类中并没有br的解压处理，用户也无法自定义处理类

	/**
	 * 初始化流
	 *
	 * @param response 响应对象
	 */
	private void init(HttpResponse response) {
		try {
			this.in = (response.status < HttpStatus.HTTP_BAD_REQUEST) ? response.httpConnection.getInputStream() : response.httpConnection.getErrorStream();
		} catch (IOException e) {
			if (false == (e instanceof FileNotFoundException)) {
				throw new HttpException(e);
			}
			// 服务器无返回内容，忽略之
		}

		// 在一些情况下，返回的流为null，此时提供状态码说明
		if (null == this.in) {
			this.in = new ByteArrayInputStream(StrUtil.format("Error request, response status: {}", response.status).getBytes());
			return;
		}

		if (response.isGzip() && false == (response.in instanceof GZIPInputStream)) {
			// Accept-Encoding: gzip
			try {
				this.in = new GZIPInputStream(this.in);
			} catch (IOException e) {
				// 在类似于Head等方法中无body返回，此时GZIPInputStream构造会出现错误，在此忽略此错误读取普通数据
				// ignore
			}
		} else if (response.isDeflate() && false == (this.in instanceof InflaterInputStream)) {
			// Accept-Encoding: defalte
			this.in = new InflaterInputStream(this.in, new Inflater(true));
		}
	}

**Comment by live-in-a-dream** [comment]
使用org.brotli.dec包进行解压
BrotliInputStream brotliInputStream = new BrotliInputStream(this.in);

**Comment by live-in-a-dream** [comment]
建议这里使用用户自定义处理方式，比较灵活

**Comment by looly** [comment]
嗯。这块5.x不做修改了。

在6.x中增加`GlobalCompressStreamRegister`，可以调用register方法注册自定义的压缩算法流。

不过在实际网站中，服务端支持多个压缩方式，你请求时不指定br即可。

```java
GlobalCompressStreamRegister.INSTANCE.register("br", BrotliInputStream.class);

final Response s = Request.of("https://xxxxx")
				.header(HeaderName.ACCEPT_ENCODING, "br")
				.send();
		Console.log(s.body());
```
