### ISSUE TITLE
官网参考手册描述错误

### ISSUE THREAD

**Issue by apzr** [looly/hutool#3083]
### 问题描述（包括截图）
https://www.hutool.cn/docs/#/Hutool%E7%9A%84%E6%9C%8B%E5%8F%8B%E4%BB%AC
![is](https://user-images.githubusercontent.com/4961561/234526137-5b085e7d-7233-4964-87c4-8f95668dfaf2.jpg)

**Comment by looly** [comment]
ok,后续修正。
