### ISSUE TITLE
相关类库不兼容JDK17（建议可以迭代一个兼容最新jdk的版本）

### ISSUE THREAD

**Issue by cunzhiwang** [looly/hutool#3085]
### 版本情况

JDK版本：    openjdk_17_2
hutool版本： 5.8.16

Eclipse基金会在2017年取得了Java EE的授权，随后启动了一个名为Eclipse Jakarta EE的项目，以此为基础扩展Java EE。因此，Java EE项目在Eclipse基金会的管理下，转变为了Jakarta EE，因此相关涉及java包名的类，会不兼容。
![image](https://user-images.githubusercontent.com/57314096/235080180-c08831a1-f9cf-4c73-9885-3dc40519d15f.png)

1. 复现代码

```java
public static void writeToJson(HttpServletResponse response, Object object) {
        String content = JSONUtil.toJsonStr(object);
        ServletUtil.write(response, content, MediaType.APPLICATION_JSON_UTF8_VALUE);
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
使用：JakartaServletUtil
