### ISSUE TITLE
在线文档  文档内容丢失

### ISSUE THREAD

**Issue by penghuizhang** [looly/hutool#3089]
### 版本情况
https://hutool.cn/docs/#/ 

![image](https://user-images.githubusercontent.com/17181083/236749833-263d804d-2e4f-4e39-b835-b7998e7bee6b.png)

![image](https://user-images.githubusercontent.com/17181083/236749965-f07f852f-c3a3-47fa-8e38-f0f9106164e0.png)

不止一个页面出现文档未找到情况

**Comment by is-myke** [comment]
+1

**Comment by xuekangli** [comment]
没人来修复一下吗

**Comment by ajun233** [comment]
+1

**Comment by NGbetrue** [comment]
+1

**Comment by zhengxin1993** [comment]
+1

**Comment by looly** [comment]
已修复。
