### ISSUE TITLE
0 如格式化成 0.00

### ISSUE THREAD

**Issue by sunhai1988** [looly/hutool#309]
如何使用   NumberUtil  将0 如格式化成 0.00 
现在格式化成的.00

**Comment by looly** [comment]
NumberUtil.decimalFormat("0.00")

**Comment by sunhai1988** [comment]
String s = NumberUtil.decimalFormat(",###.00", 0);  ---- > .00

直接用0.00  没有 没三个数字加一个逗号

**Comment by sunhai1988** [comment]
String s = NumberUtil.decimalFormat(",##0.00", 0); 这样就可以了

**Comment by looly** [comment]
好吧，这也是封装的jdk的
