### ISSUE TITLE
对List<Long>使用BeanUtil.copyToList,会出现结果为0的集合

### ISSUE THREAD

**Issue by iflamma** [looly/hutool#3091]
### 版本情况

JDK版本：    java 11.0.14
hutool版本： 5.8.11

### 问题描述（包括截图）
对List<Long>使用BeanUtil.copyToList(Collection<?> collection, Class<T> targetType),会出现结果为0的集合
![图片](https://user-images.githubusercontent.com/34542199/237009221-bdb0e30b-86a0-4786-940a-c2ceab55f5bd.png)

1. 复现代码
```java
    @Test
    void testQALC(){
        List<Ddd>  list = Arrays.asList(new Ddd(){{setId(1L);}},new Ddd(){{setId(2L);}});
        List<Long> l1 = Arrays.asList(1L,2L);

        System.out.println("OBJ="+BeanUtil.copyToList(list,Ddd.class));
        System.out.println("LONG="+BeanUtil.copyToList(l1,Long.class));
    }

    @Data
    public class Ddd {
        private Long id;
    }
```

**Comment by jiandanfeng** [comment]
这是因为Long类中的属性value是不可读的，没有getter，也不是public修饰，所以复制不了

**Comment by looly** [comment]
事实上，Long并不属于Bean。

BeanUtil没有封装普通值的拷贝。

按照bug算吧。

5.8.19和6.0.0.M4修复此问题。感谢~~
