### ISSUE TITLE
fix:BeanUtil.getBeanDesc set方法赋值错误

### ISSUE THREAD

**Issue by wulangcode** [looly/hutool#3096]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： latest version

### 问题描述（包括截图）

1. 复现代码

```java
public static class User {
  private Boolean lastPage;
  private Boolean isLastPage;

  public Boolean getLastPage() {
    return this.lastPage;
  }

  public void setLastPage(final Boolean lastPage) {
    this.lastPage = lastPage;
  }

  public Boolean getIsLastPage() {
    return this.isLastPage;
  }

  public void setIsLastPage(final Boolean isLastPage) {
    this.isLastPage = isLastPage;
  }
}
```

```java
@Test
public void propDescOfBooleanTest3() {
  BeanDesc desc = BeanUtil.getBeanDesc(User.class);

  Assert.assertEquals("setLastPage", desc.getSetter("lastPage").getName());
  Assert.assertEquals("setIsLastPage", desc.getSetter("isLastPage").getName());
}
```
<img width="1216" alt="image" src="https://github.com/dromara/hutool/assets/48200100/4e930673-648b-4d7c-98b1-b2ebc1d5df05">
<img width="806" alt="image" src="https://github.com/dromara/hutool/assets/48200100/be356851-7012-45b9-afc9-ff3d943d9b7e">
<img width="800" alt="image" src="https://github.com/dromara/hutool/assets/48200100/6660c8b3-6e02-46e7-91fc-0f835b6eefdb">

`cn.hutool.core.bean.PropDesc#setter` 中的属性依赖于 `ReflectUtil.getMethods(this.beanClass, ReflectUtil::isGetterOrSetterIgnoreCase)` 返回方法的顺序，而每次返回的顺序又是无序的，所以每次赋值的情况都不固定，造成使用`cn.hutool.core.bean.BeanUtil#copyProperties(java.lang.Object, java.lang.Class<T>, java.lang.String...)`时，时而能拷贝数据，时而拷贝不上数据。

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
@wulangcode 我理解你的意思了，问题出在`isMatchSetter`方法中：

![image](https://github.com/dromara/hutool/assets/1432613/05ce3966-4acb-40fa-9de7-16200d324414)


就是无论是`lastPage`还是`isLastPage`，都是优先查找`setLastPage`的，这里存在歧义。

暂时保留这个issue，PR已经打开，我研究下逻辑关系后再处理。

感谢。

**Comment by aozeyu** [comment]
<img width="1280" alt="截屏2023-05-19 09 50 06" src="https://github.com/dromara/hutool/assets/55688386/c0e94465-8c85-4380-a2cf-65521a164bd5">
@looly  这个问题是不是已经修复了呢，感觉没有报错呢😂

**Comment by wulangcode** [comment]
> <img alt="截屏2023-05-19 09 50 06" width="1280" src="https://user-images.githubusercontent.com/55688386/239416343-c0e94465-8c85-4380-a2cf-65521a164bd5.png"> @looly 这个问题是不是已经修复了呢，感觉没有报错呢😂


多运行几遍，存在一定概率

**Comment by aozeyu** [comment]
@wulangcode 这样啊😂，我就跑了一遍，那这个是偶现，我再多试试

**Comment by aozeyu** [comment]
@wulangcode yes,确实复现了

**Comment by aozeyu** [comment]
![Uploading 截屏2023-05-19 09.59.59.png…]()
@wulangcode @looly yes,确实复现了

**Comment by aozeyu** [comment]
<img width="1280" alt="截屏2023-05-19 10 01 10" src="https://github.com/dromara/hutool/assets/55688386/04ab7c52-9bd7-4002-9105-ef4d7c4e3bad">

@wulangcode 确实复现了

**Comment by aozeyu** [comment]
@looly

**Comment by looly** [comment]
@wulangcode 考虑到兼容性问题，5.x不做修改。

在6.0.0.M4开始，修改匹配规则为：

字段为isName，优先查找`setIsName`方法，找不到的情况下，去找`setName`

具体见：https://github.com/dromara/hutool/commit/18784f37dd221d41a8ff172d66aff91015385acb
