### ISSUE TITLE
RSA解密使用decryptStr返回的字符串长度有问题

### ISSUE THREAD

**Issue by xXiaoYu** [looly/hutool#3098]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.18

### 问题描述（包括截图）
RSA解密使用decryptStr返回的字符串再加密文比较少的情况也会返回固定128字节的字符串，需要去除空字符串'\u0000' 0
![image](https://github.com/dromara/hutool/assets/16264607/831fdaa6-045a-486e-b745-b7d429fde61b)
![image](https://github.com/dromara/hutool/assets/16264607/f2c32049-9d21-4be2-8488-ca7a71a480bf)

![image](https://github.com/dromara/hutool/assets/16264607/4590c741-c18c-495e-b31c-c26290973f50)

**Comment by ZZemptypoint** [comment]
无法复现你的问题, 请排查一下`RSAUtils.generateKey()`生成的结果, 它的公钥和私钥可能不是base64的字符串. 
我使用的测试用例如下:
```java
                final String text = "{key:ddd}";
		final RSA rsa = new RSA();
		
		// 公钥加密
		final RSA encryptRsa = new RSA(AsymmetricAlgorithm.RSA_ECB.getValue(), null, rsa.getPublicKeyBase64());
		final String encryptStr = encryptRsa.encryptBase64(text, KeyType.PublicKey);

		// 私钥解密
		final RSA decryptRsa = new RSA(AsymmetricAlgorithm.RSA_ECB.getValue(), rsa.getPrivateKeyBase64(), null);
		final String decryptStr = decryptRsa.decryptStr(encryptStr, KeyType.PrivateKey);

		Assert.assertEquals(text, decryptStr);
```

**Comment by xXiaoYu** [comment]
![image](https://github.com/dromara/hutool/assets/16264607/230d40d2-69a5-424b-be09-267d17f83b9b)
我运行了你提供的代码，确实会复现。
你确定你用的jdk是1.8的。我用的jdk是jdk-8u371-windows-x64，今天刚刚从官网下载的，这个问题应该是跟jdk的解密返回的字节数组有关系。我看源码解密返回的字节数组固定是128或者256固定倍数大小

**Comment by ZZemptypoint** [comment]
不应该啊, 我也是jdk1.8. 请排查一下代码中使用到的`RSA`对象所属的`hutool`版本

**Comment by xXiaoYu** [comment]
![image](https://github.com/dromara/hutool/assets/16264607/4c3cb8d3-6b49-4039-8d4a-c481e384c57c)

**Comment by ZZemptypoint** [comment]
![图片](https://github.com/dromara/hutool/assets/28431269/54fb6fc1-4c83-45a8-882f-8fd1e28d1a25)

**Comment by xXiaoYu** [comment]
![image](https://github.com/dromara/hutool/assets/16264607/b45b917f-61ce-42bd-8fd2-b8fc2b480c2c)

**Comment by ZZemptypoint** [comment]
oracle的最新版似乎是jdk-8u361, 你的真的是371吗?
https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html

**Comment by ZZemptypoint** [comment]
我的测试代码在`jdk1.8.0_361`中依然是运行成功的
![图片](https://github.com/dromara/hutool/assets/28431269/cd3c9a60-a942-4ecf-a1c0-3cf80977e2e3)

**Comment by xXiaoYu** [comment]
你的hutool版本是多少的？

**Comment by xXiaoYu** [comment]
我用原生的解密返回的字节也有问题
![image](https://github.com/dromara/hutool/assets/16264607/da057b47-17a5-43c8-819c-52199c93845d)

        final RSA rsa = new RSA();
        final String text = "{key:ddd}";
        final RSA encryptRsa = new RSA(AsymmetricAlgorithm.RSA_ECB.getValue(), null, rsa.getPublicKeyBase64());
        final String str = encryptRsa.encryptBase64(text, KeyType.PublicKey);

        String decodeStr = null;
        try {
            //64位解码加密后的字符串
            byte[] inputByte = Base64.getDecoder().decode(str);
            byte[] privateCode = Base64.getDecoder().decode(rsa.getPrivateKeyBase64());
            PKCS8EncodedKeySpec pkcs8EncodedKeySpec = new PKCS8EncodedKeySpec(privateCode);
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            RSAPrivateKey rsaPrivateKey = (RSAPrivateKey) keyFactory.generatePrivate(pkcs8EncodedKeySpec);
            Cipher cipher = Cipher.getInstance(AsymmetricAlgorithm.RSA_ECB.getValue());
            cipher.init(Cipher.DECRYPT_MODE, rsaPrivateKey);
            byte[] result = cipher.doFinal(inputByte);
            // Base64编码
            decodeStr = new String(result);
            Assert.assertEquals(text, decodeStr);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("公钥加密失败");
        }

**Comment by xXiaoYu** [comment]
我看看是我的jdk哪里有问题，我刚刚又去下载了一个jdk1.8.0_361也是有该问题

**Comment by ZZemptypoint** [comment]
哦哦, 我是在hutool源码的test包中测试的, 我新建项目后引入`hutool 5.8.18`确实有这个问题, 可以通过引入`bouncycastle`来解决:
```
         <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15to18</artifactId>
            <version>1.72</version>
        </dependency>
```

**Comment by xXiaoYu** [comment]
jdk原生的返回的数组字节，需要处理一下去掉多余的空字节。hutool包可以处理一下，使用bouncycastle包，应该是不用原生jdk的加解密算法。
ok我没问题了

**Comment by ZZemptypoint** [comment]
没错

**Comment by changhr2013** [comment]
@looly 我感觉应该是原生 RSA 解密封装的 block 长度有问题，有时间可以一起看看，先 mark 一下。

**Comment by changhr2013** [comment]
@looly @xXiaoYu @ZZemptypoint 
我跟了一下 SUN 原生和 BouncyCastle 的 RSA 算法实现，最终得到的结论是：**两种实现对解密结果 BigInteger 转换到字节数组的实现不一致**。

在不引入 BouncyCastle 库时，JCE 默认会使用 `sun.security.rsa.RSACore` 进行 RSA 运算，而引入 BouncyCastle 后，JCE 默认会优先使用 `org.bouncycastle.crypto.engines.RSABlindedEngine` 进行 RSA 运算。

我们都知道，RSA 运算实际上是大数的质因数分解问题，因此在 RSA 私钥解密运算后得到的实际上是一个 BigInteger，要想得到原有的明文字节数组，一般会将 `BigInteger` 转换为 `byte[]`，再进一步把 `byte[]` 编码为字符串消息。

不同的是，`RSACore` 和 `RSABlindedEngine` 在将 `BigInteger` 转换为 `byte[]` 时采取了不同的转换策略。

`RSACore` 使用的方法是（只展示关键代码）：

```java
return toByteArray(m, getByteLength(n));
```

```java
/**
 * Return the encoding of this BigInteger that is exactly len bytes long.
 * Prefix/strip off leading 0x00 bytes if necessary.
 * Precondition: bi must fit into len bytes
 */
private static byte[] toByteArray(BigInteger bi, int len) {
    ...
    byte[] t = new byte[len];
    ...
    return t;
}
```

其中 n 指的是 RSA 的模数，它的比特长度实际上就是我们所说的 RSA1024、RSA2048 后面跟的数字，`RSACore` 输出的解密结果的长度，会与 n 的字节长度对齐，`Biginteger` 的有效位长度不够的话会在高位补零。

而 `RSABlindedEngine` 采用的方法是（只展示关键代码）：

```java
return core.convertOutput(result);
```

```java
public byte[] convertOutput(BigInteger result) {
    byte[] output = result.toByteArray();
    ...
    rv = new byte[output.length];
    ...
    return rv;
}
```

`RSABlindedEngine` 直接将 `Biginteger` 的有效位转换为了 `byte[]`，并不关心整体的模长。

因此就会出现上述的情况，在使用原生 JCE 的 RSA 解密时，解密结果有效位因为不足 n 的模长，就会在高位填充 0 直到长度与 n 的模长对齐；而使用 BouncyCastle 之后，解密结果就只会输出有效位。

举个栗子🌰：

假如一个 RSA 运算的 n 模长为 64，一个解密消息结果是 `[31, 32, 33]`。

那么使用 `RSACore` 得到的结果就是：

```js
[0, 0, 0, 0, 0, 31, 32, 33]
```

因为要对齐 64 的模长，需要在前面补充 5 个 `0x00` 字节

而使用 `RSABlindedEngine` 得到的结果就是：

```js
[31, 32, 33]
```

一些个人的碎碎念：按 RFC 的标准来讲，在 `NoPadding` 的情况下，我觉得 SUN 的实现应该更加标准一些。😄

**Comment by looly** [comment]
@changhr2013 感谢你给我这个小白答疑解惑。😁

Hutool作为工具类，只是简单封装了API，还真没有深入去看BC库和sun的源码。

按照你的解释，考虑可以为BC库提个issue哦~~

**Comment by Createsequence** [comment]
> @looly @xXiaoYu @ZZemptypoint 我跟了一下 SUN 原生和 BouncyCastle 的 RSA 算法实现，最终得到的结论是：**两种实现对解密结果 BigInteger 转换到字节数组的实现不一致**。
> 
> 在不引入 BouncyCastle 库时，JCE 默认会使用 `sun.security.rsa.RSACore` 进行 RSA 运算，而引入 BouncyCastle 后，JCE 默认会优先使用 `org.bouncycastle.crypto.engines.RSABlindedEngine` 进行 RSA 运算。
> 
> 我们都知道，RSA 运算实际上是大数的质因数分解问题，因此在 RSA 私钥解密运算后得到的实际上是一个 BigInteger，要想得到原有的明文字节数组，一般会将 `BigInteger` 转换为 `byte[]`，再进一步把 `byte[]` 编码为字符串消息。
> 
> 不同的是，`RSACore` 和 `RSABlindedEngine` 在将 `BigInteger` 转换为 `byte[]` 时采取了不同的转换策略。
> 
> `RSACore` 使用的方法是（只展示关键代码）：
> 
> ```java
> return toByteArray(m, getByteLength(n));
> ```
> 
> ```java
> /**
>  * Return the encoding of this BigInteger that is exactly len bytes long.
>  * Prefix/strip off leading 0x00 bytes if necessary.
>  * Precondition: bi must fit into len bytes
>  */
> private static byte[] toByteArray(BigInteger bi, int len) {
>     ...
>     byte[] t = new byte[len];
>     ...
>     return t;
> }
> ```
> 
> 其中 n 指的是 RSA 的模数，它的比特长度实际上就是我们所说的 RSA1024、RSA2048 后面跟的数字，`RSACore` 输出的解密结果的长度，会与 n 的字节长度对齐，`Biginteger` 的有效位长度不够的话会在高位补零。
> 
> 而 `RSABlindedEngine` 采用的方法是（只展示关键代码）：
> 
> ```java
> return core.convertOutput(result);
> ```
> 
> ```java
> public byte[] convertOutput(BigInteger result) {
>     byte[] output = result.toByteArray();
>     ...
>     rv = new byte[output.length];
>     ...
>     return rv;
> }
> ```
> 
> `RSABlindedEngine` 直接将 `Biginteger` 的有效位转换为了 `byte[]`，并不关心整体的模长。
> 
> 因此就会出现上述的情况，在使用原生 JCE 的 RSA 解密时，解密结果有效位因为不足 n 的模长，就会在高位填充 0 直到长度与 n 的模长对齐；而使用 BouncyCastle 之后，解密结果就只会输出有效位。
> 
> 举个栗子🌰：
> 
> 假如一个 RSA 运算的 n 模长为 64，一个解密消息结果是 `[31, 32, 33]`。
> 
> 那么使用 `RSACore` 得到的结果就是：
> 
> ```js
> [0, 0, 0, 0, 0, 31, 32, 33]
> ```
> 
> 因为要对齐 64 的模长，需要在前面补充 5 个 `0x00` 字节
> 
> 而使用 `RSABlindedEngine` 得到的结果就是：
> 
> ```js
> [31, 32, 33]
> ```
> 
> 一些个人的碎碎念：按 RFC 的标准来讲，在 `NoPadding` 的情况下，我觉得 SUN 的实现应该更加标准一些。😄

非常通俗易懂的回答，小白的我看完感觉忽然开朗，专门登录给你点个赞 :)
