### ISSUE TITLE
ZipReader可能存在bug，请作者大佬确认下哦

### ISSUE THREAD

**Issue by dujiecn** [looly/hutool#3099]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
<img width="1034" alt="image" src="https://github.com/dromara/hutool/assets/10645118/7c378464-b004-4ab8-833a-65cddb256bbb">

cn.hutool.core.compress.ZipReader#get，这段代码里面会抛出throw new IOException("mark/reset not supported");
1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.19
6.0.0.M4

修复。感谢！
