### ISSUE TITLE
> `String.toLowerCase`和`String.toUpperCase`已经满足所有要求了，而且性能更好。

### ISSUE THREAD

**Issue by KwokRoot** [looly/hutool#3101]
> `String.toLowerCase`和`String.toUpperCase`已经满足所有要求了，而且性能更好。

1.String.toLowerCase和String.toUpperCase 使用之前需要判空。
2.String.toLowerCase 和 String.toUpperCase  底层我看了看源码基本也是 CharSequence 遍历方式实现的。
3.apache-langs包StringUtils也有此方法，多了步判空，可参考。

_Originally posted by @KwokRoot in https://github.com/dromara/hutool/issues/3100#issuecomment-1546924905_

**Comment by looly** [comment]
就是因为只是多了一步判空，我觉得很没有必要……

**Comment by KwokRoot** [comment]
> 就是因为只是多了一步判空，我觉得很没有必要……

ok
