### ISSUE TITLE
System.out.println(Convert.toLong("0.a"));输出结果为0而不是null这是不合理的

### ISSUE THREAD

**Issue by lizihang4869** [looly/hutool#3105]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这里解析的最终调用是`java.text.NumberFormat`：

```java
NumberFormat format = NumberFormat.getInstance();
format.parse("0.a");
```

得到的结果确实为`0`。

查阅了下资料，`NumberFormat`是一个较为宽泛的数字解析，这里保留JDK的这个规则。

**Comment by lizihang4869** [comment]
虽然你调用底层是那个，不过对于这个方法来说我想转换成long类型的但是你将这个转换成了long这个不是很合理，是不是要考虑一下优化底层



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2023年5月16日(周二) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] System.out.println(Convert.toLong("0.a"));输出结果为0而不是null这是不合理的 (Issue #3105)




 
这里解析的最终调用是java.text.NumberFormat：
 NumberFormat format = NumberFormat.getInstance(); format.parse("0.a");
 
得到的结果确实为0。
 
查阅了下资料，NumberFormat是一个较为宽泛的数字解析，这里保留JDK的这个规则。

**Comment by looly** [comment]
@lizihang4869 整个Converter的原则是**尽最大努力**转换数字，包括一些科学计数法、简易表示法等，这些都需要依赖于`NumberFormat`。

如果你对的转换有特殊要求，考虑使用`Long.parseLong`完成~~

**Comment by lizihang4869** [comment]
明白了，感谢



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2023年5月16日(周二) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] System.out.println(Convert.toLong("0.a"));输出结果为0而不是null这是不合理的 (Issue #3105)




 
@lizihang4869 整个Converter的原则是尽最大努力转换数字，包括一些科学计数法、简易表示法等，这些都需要依赖于NumberFormat。
 
如果你对的转换有特殊要求，考虑使用Long.parseLong完成~~
