### ISSUE TITLE
MailUtil发送邮件注意事项

### ISSUE THREAD

**Issue by MrRohwei** [looly/hutool#3107]
使用MailUtil时在mail.setting中按官网添加参数
![image](https://github.com/dromara/hutool/assets/35440977/571e3eb0-4a83-4fc4-a9e9-0a50f96eaf4d)
一定要注意，这个`user`参数不能乱填，我看备注是默认是邮箱前缀，还以为可以随意填写。发了半天发不出去。这个user只能要不就是邮箱前缀，比如：123123@qq.com就填123123或者123123@qq.com，其他的不行

**Comment by looly** [comment]
是滴。这个user在不同邮箱服务中是不一样的，Hutool只是提供了一种默认值而已。

一般网易之类的user都是邮箱前缀，QQ邮箱使用完整邮箱作为user。

**Comment by looly** [comment]
可以看下：https://gitee.com/dromara/hutool/issues/I4FYVY

**Comment by MrRohwei** [comment]
> 可以看下：https://gitee.com/dromara/hutool/issues/I4FYVY

好的，谢谢回复
