### ISSUE TITLE
使用HttpUtil.downloadFile下载大文件时，当下载1G后自动停止

### ISSUE THREAD

**Issue by Rebuilding127** [looly/hutool#3108]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.18

### 问题描述（包括截图）

使用`HttpUtil.downloadFile`及`HttpUtil.download`下载网络文件，当下载1GB后自动停止了，并未下载完成。

使用IDM等下载软件下载是可以完整下载的。

**Comment by looly** [comment]
是否考虑网络问题？或者链接被断开？

**Comment by Rebuilding127** [comment]
发现问题了，是nginx配置导致的。
