### ISSUE TITLE
ReflectUtil中CONSTRUCTORS_CACHE、FIELDS_CACHE、METHODS_CACHE设计问题

### ISSUE THREAD

**Issue by Warren-W** [looly/hutool#3117]
利用WeakHashMap来自动回收，但是这三个cache中的vlue中含有对应key class的强引用，导致无法自动回收，同时fullgc时元空间无法释放。BeanDescCache中的bdCache也有这个问题。

**Comment by looly** [comment]
在`ReferenceConcurrentMap`中使用了`WeakKey`作为key，这样就避免了强引用的问题。

如果还有讨论，请再打开此issue。

**Comment by Warren-W** [comment]
参考weakhashmap的注释或者参考com.sun.beans.finder.MethodFinder中cache实现，value也应该被指定为weak
 * <p> <strong>Implementation note:</strong> The value objects in a
 * <tt>WeakHashMap</tt> are held by ordinary strong references.  Thus care
 * should be taken to ensure that value objects do not strongly refer to their
 * own keys, either directly or indirectly, since that will prevent the keys
 * from being discarded.  Note that a value object may refer indirectly to its
 * key via the <tt>WeakHashMap</tt> itself; that is, a value object may
 * strongly refer to some other key object whose associated value object, in
 * turn, strongly refers to the key of the first value object.  If the values
 * in the map do not rely on the map holding strong references to them, one way
 * to deal with this is to wrap values themselves within
 * <tt>WeakReferences</tt> before
 * inserting, as in: <tt>m.put(key, new WeakReference(value))</tt>,
 * and then unwrapping upon each <tt>get</tt>.

**Comment by looly** [comment]
@Warren-W 你不应该参考`WeakHashMap`，而应该看`jdk.management.resource.internal.WeakKeyConcurrentHashMap`。

可以看下这段：

![image](https://github.com/dromara/hutool/assets/1432613/9fc5f11b-709f-463d-a68d-0a33ded94112)

![image](https://github.com/dromara/hutool/assets/1432613/bfd208c6-baed-4d00-ab86-40911981c141)

![image](https://github.com/dromara/hutool/assets/1432613/c5c463b0-8392-489f-8109-bc2d7b580ed9)

道理一样，为了解决key和value强关联的问题，可以通过`new WeakReference(value)`，也可以通过`new WeakReference(key)`
来达到目的。
