### ISSUE TITLE
Excel导入包含空列把Excel自带的字母填充进来了

### ISSUE THREAD

**Issue by teacherblitz** [looly/hutool#3118]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        InputStream inputStream = file.getInputStream();
        ExcelReader excelReader = ExcelUtil.getReader(inputStream);

        // 忽略表头，直接从第三行开始读取
        List<List<Object>> list = excelReader.read(2);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
导入的Excel：
![image](https://github.com/dromara/hutool/assets/54267617/6464bcdb-f3b7-447f-a137-303f52261217)
使用复现代码读取后的内容
![image](https://github.com/dromara/hutool/assets/54267617/9b5fd79b-049c-4411-8bf4-ce5c2e5706ec)

**Comment by looly** [comment]
是。为了解决空列无key的情况，默认使用Excel的列号来表示key。

**Comment by teacherblitz** [comment]
[bug.xlsx](https://github.com/dromara/hutool/files/11539212/bug.xlsx)
excel内容，B列无值，读取第一行数据A=1，B本来是null，但是读取出来时B

**Comment by looly** [comment]
按照你的代码：

```java
 List<List<Object>> list = excelReader.read(2);
```

读取没有问题：

![image](https://github.com/dromara/hutool/assets/1432613/927d3c21-2567-4b4e-95b2-d4994b6c8305)

但是合并单元格的情况，不要使用Bean或map读取，读取后空的标题行默认会用Excel格式的标题序号表示。

**Comment by teacherblitz** [comment]
``` java
File file = new File("C:\\Users\\朱老师\\Desktop\\bug.xlsx");
        ExcelReader excelReader = ExcelUtil.getReader(file);

        // 忽略表头，直接从第三行开始读取
        List<List<Object>> list = excelReader.read(2);
        for (List<Object> obj: list) {
            Console.log(obj);
        }
```
[bug.xlsx](https://github.com/dromara/hutool/files/11540044/bug.xlsx)
结果：
![微信图片_20230523135739](https://github.com/dromara/hutool/assets/54267617/a4b2c895-5ed1-47f1-9b5b-ded3af693635)

**Comment by 1746631764** [comment]
怎么关闭了，有同样的问题，怎么解决
