### ISSUE TITLE
是。为了解决空列无key的情况，默认使用Excel的列号来表示key。

### ISSUE THREAD

**Issue by teacherblitz** [looly/hutool#3119]
是。为了解决空列无key的情况，默认使用Excel的列号来表示key。

_Originally posted by @looly in https://github.com/dromara/hutool/issues/3118#issuecomment-1558428868_

[bug.xlsx](https://github.com/dromara/hutool/files/11539212/bug.xlsx)
excel内容，B列无值，读取第一行数据A=1，B本来是null，但是读取出来时B

**Comment by looly** [comment]
@teacherblitz 不必新开issue，原issue讨论即可：

https://github.com/dromara/hutool/issues/3118
