### ISSUE TITLE
Excel导入问题，在线等急

### ISSUE THREAD

**Issue by teacherblitz** [looly/hutool#3120]
``` java
File file = new File("C:\\Users\\朱老师\\Desktop\\bug.xlsx");
ExcelReader excelReader = ExcelUtil.getReader(file);

 // 忽略表头，直接从第三行开始读取
        List<List<Object>> list = excelReader.read(2);
        for (List<Object> obj: list) {
            Console.log(obj);
        }
```

[bug.xlsx](https://github.com/dromara/hutool/files/11540044/bug.xlsx)

结果：

![微信图片_20230523135739](https://github.com/dromara/hutool/assets/54267617/a4b2c895-5ed1-47f1-9b5b-ded3af693635)

**Comment by handy-git** [comment]
图片看不了，请补充完整下

**Comment by teacherblitz** [comment]
![微信图片_20230523135739](https://github.com/dromara/hutool/assets/54267617/4c3dbade-ad1e-4a44-ae3b-835f10627fab)

**Comment by teacherblitz** [comment]
#3118

**Comment by teacherblitz** [comment]
已补充发自我的iPhone------------------ 原始邮件 ------------------发件人: handy  ***@***.***>发送时间: 2023年5月23日 14:56收件人: dromara/hutool ***@***.***>抄送: 朱老师 ***@***.***>, Author ***@***.***>主题: 回复：[dromara/hutool] Excel导入问题，在线等急 (Issue #3120)
图片看不了，请补充完整下

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dromara/hutool/issues/3120#issuecomment-1558644728",
"url": "https://github.com/dromara/hutool/issues/3120#issuecomment-1558644728",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by looly** [comment]
@teacherblitz 可能是旧版本bug。

麻烦更新到最新版本Hutool尝试。

讨论问题可以在同一个issue中讨论，如果没有解决再打开issue即可，无需重复添加新的issue。

**Comment by looly** [comment]
@teacherblitz issue太慢的话，可以加QQ群私聊: 715292493

**Comment by looly** [comment]
reader.read(2, Integer.MAX_VALUE, false);

用这个方法读取即可。

原因是aliasFirstLine这个参数，默认把你读取的第一行作为标题行了，这个可能不合理，下个版本修改。

考虑到兼容问题，6.0.0.M4开始修改此处规则。
