### ISSUE TITLE
https 过期了，如何设置不能请求

### ISSUE THREAD

**Issue by iCloudys** [looly/hutool#3123]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
如果https证书无效了，我该如何设置不能请求成功。就是需要验证证书信息是否可用
1. 复现代码

```java
HttpRequest request = HttpUtil.createGet("https://api.zhonghaoweilai.com/ac/captcha/getCaptcha",true);

HttpResponse execute = request.execute();
        
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
HttpRequest.setSSLSocketFactory

设置自定义即可。
