### ISSUE TITLE
OshiUtil获取CPU序列号和命令行获取的不一致

### ISSUE THREAD

**Issue by ustcck** [looly/hutool#3126]
### 版本情况

JDK版本：    OpenJDK_17.0.7_7
hutool版本： 5.8.12（请确保最新尝试是否还有问题）
服务器OS：Ubuntu 22.04.2 LTS

### 问题描述（包括截图）

1. 复现代码

```java
            // 当前服务器CPU序列号
            CentralProcessor processor = OshiUtil.getProcessor();
            String cpuSerial = processor.getProcessorIdentifier().getProcessorID();
```

![a7c3d189e545d30d5acf427bdc9c832](https://github.com/dromara/hutool/assets/16115192/71e54b13-3220-4bbb-a2a0-dfa0b5e2628a)

OshiUtil获取的结果是BFEBFBFF00500657，命令行获取的结果是BFEBFBFF00050657。

**Comment by ustcck** [comment]
dmidecode -t processor | grep 'ID' | awk -F ':' '{print $2}' | head -n 1

**Comment by looly** [comment]
这个问题我觉得你应该提给Oshi库：https://github.com/oshi/oshi

或者更新Oshi版本试下。
