### ISSUE TITLE
HttpRequest重定向问题

### ISSUE THREAD

**Issue by ryumiyax** [looly/hutool#3129]
HttpRequest在重定向Location: "//path.to.website/something" 的时候会重定向到 http:////path.to.website/something

**Comment by ryumiyax** [comment]
而且重定向在没有协议的时候不是应该默认使用重定向源网站的协议嘛,这里把https也置为http了

**Comment by ryumiyax** [comment]
参考 
cn.hutool.core.net.url.UrlBuilder.ofHttp(UrlBuilder.java:107)
cn.hutool.http.HttpRequest.setUrl(HttpRequest.java:315)
cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1197)

**Comment by ryumiyax** [comment]
而且重定向不走过滤器，我甚至没办法改它:(

**Comment by ryumiyax** [comment]
用python的requests或者posman都能正常重定向到https://path.to.website/something

**Comment by jsfu** [comment]
正常情况下如果不带协议，应该是想跳相对路径吧

**Comment by looly** [comment]
见：https://gitee.com/dromara/hutool/issues/I5TPSY

最新版本已经修复此问题，请升级Hutool尝试。不行的话麻烦提供URL并打开此issue，我这边测试。

![image](https://github.com/dromara/hutool/assets/1432613/53410a6f-e6fd-4bcd-a80d-7c61763043ba)
