### ISSUE TITLE
建议：会不会引入类似 faker.js 的功能？

### ISSUE THREAD

**Issue by gMan1990** [looly/hutool#3138]
.

**Comment by looly** [comment]
貌似是个类似测试数据生成的东西。没有考虑加入，可以用：
https://github.com/DiUS/java-faker

**Comment by gMan1990** [comment]
@looly 但这个不太中文友好。

还有个 fork https://github.com/datafaker-net/datafaker

其它语言 see https://fakerjs.dev/guide/

**Comment by looly** [comment]
啊~~那我没得办法了，翻译吧，哈哈。

**Comment by gMan1990** [comment]
@looly 1. `不太中文友好` 是指，比如 随机大陆身份证，随机国内手机号

2. 随机中文名，前面说的lib 里面有

3. 还有什么 随机中文昵称，好像没看到
