### ISSUE TITLE
升级版本后xml转json再转bean失败

### ISSUE THREAD

**Issue by TuWei1992** [looly/hutool#3139]
### 版本情况

JDK版本：    openjdk_8_201
升级后版本： 5.8.19 
原版本: 5.7.8 

### 问题描述

1. 使用Xml.toBean将xml文本转为的JSONObject对象
2. 调用jsonObject.toBean转为bean失败
3. 复现代码
```xml
<r>
  // 这里其实是个数组 
  <c>
     <s>1</s>
     <p>str</p>
  </c>
</r>
```
转换后的json
```json
{
  // 这里识别为了对象
  "c": {

   }
}
```

对应的bean为

```java
@Data
class C {
  String s;
  String p;
}

@Data
class R {
  List<C> c;
}
```

4.  原因: ConverterRegistry 把R.c 这个属性识别为列表, 使用CollectionConverter进行转换, 内部不是把c这个节点当做整体对象, 而是将c当做数组, 内部的每个键值对都解析为了map对象, 所以无法将r.c节点转为 new ArrayList().add(new C()) 这种形式,  *但是5.7.8版本是ok的*

**Comment by looly** [comment]
确认bug，你暂时可以：

```java
final R r = XmlUtil.xmlToBean(XmlUtil.parseXml(xml), R.class);
```

问题出在新版本JSONObject实现了Iterable接口导致逻辑错误，5.8.20修复此问题！

6.0.0-M4同步修复此问题。

**Comment by looly** [comment]
这块可能存在bug，暂时保留issue。
