### ISSUE TITLE
SM2加解密密文排序问题

### ISSUE THREAD

**Issue by Gsealy** [looly/hutool#314]
看到您补充了密文拼接模式

https://github.com/looly/hutool/blob/75f9a529906432585cd31f6a331c8a8dee799633/hutool-crypto/src/main/java/cn/hutool/crypto/asymmetric/SM2Engine.java#L85

因为BC是按照英文的SM2草案做的，当时用的老版本就是mode里面的C1C2C3，但是在现行国标中，修改为了C1C3C2拼接模式，主要是因为C2是一个可变长的比特串，所以后来改到了后面，但是英文版就没有改过来。

所以推荐缺省按照C1C3C2拼接模式，遵循现阶段的国标（GB/T 32918.4-2016）

现行[SM2公钥加密算法](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=370AF152CB5CA4A377EB4D1B21DECAE0)

具体描述：
![image](https://user-images.githubusercontent.com/26080361/55405877-90d2e200-558d-11e9-9120-623424164fff.png)

**Comment by looly** [comment]
我添加了可以自定义拼接模式，但是还得考虑之前的算法可能有用户在项目中已经使用，贸然修改容易造成项目突然报错。所以默认还是旧的。

**Comment by looly** [comment]
c1c3c2模式我给bc库提issue了，希望bc库可以官方支持，到时就不用这么麻烦了。

**Comment by Gsealy** [comment]
但是因为现在最新的SM2英文版也还是用的老模式，所以没有相应的文件支撑。不知道BC接不接受这个issue

**Comment by looly** [comment]
恩。所以暂时等待。
