### ISSUE TITLE
TimeCache put((K key, V object, long timeout) 自定义超时时间失效

### ISSUE THREAD

**Issue by iszhangsc** [looly/hutool#3141]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.8.19

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/41824454/d610076e-b0e5-4869-aa82-fca7f640e7d7)

两次请求时间没有超过我定义的7000000 ms，却走了匿名函数内的方法，请问以下这是怎么一回事？

1. 以下是复现代码

```java
@Slf4j
@RestController
@RequestMapping("/wechat")
public class WechatAccessTokenController {

    @Resource
    private ObjectMapper objectMapper;
    @Resource
    private RestTemplate restTemplate;

    private static final String URL = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s";

    private static final TimedCache<String, String> timedCache = CacheUtil.newTimedCache(TimeUnit.SECONDS.toMillis(10));

    @GetMapping("/getAccessToken")
    public String getAccessToken(@RequestParam String appid, @RequestParam String secret) {
        return getString(appid, secret);
    }

    private String getString(String appid, String secret) {
        return timedCache.get(appid, () -> {
            log.info("缓存中没有该appid:{}对应的accessToken,将尝试调用微信获取", appid);
            String url = String.format(URL, appid, secret);
            String accessToken = restTemplate.getForObject(url, String.class);
            JsonNode jsonNode = objectMapper.readValue(accessToken, JsonNode.class);
            JsonNode expiresIn = jsonNode.get("expires_in");
            if (expiresIn.isNull()) {
                log.error("获取微信AccessToken异常:{}", accessToken);
                return accessToken;
            }
            long timeout = TimeUnit.SECONDS.toMillis(expiresIn.asInt() - 200);
            log.info("缓存：{} ms, appId对应的accessToken:{}", timeout, accessToken);
            timedCache.put(appid, accessToken, timeout);
            return accessToken;
        });
    }

}
```

**Comment by looly** [comment]
@iszhangsc 你lambda中的逻辑有问题。

![image](https://github.com/dromara/hutool/assets/1432613/fc2eb318-2879-4bb4-b9d7-67cc0e87ca1e)

get方法处理的时候，已经有put操作了，因此在lambda中不必再调用put了，这个函数只需生成并返回value即可。

你在lambda中调用put，因为非原子性，可能会导致并发问题，从而多次put。

**Comment by CherryRum** [comment]
> @iszhangsc 你lambda中的逻辑有问题。
> 
> ![image](https://user-images.githubusercontent.com/1432613/245068845-fc2eb318-2879-4bb4-b9d7-67cc0e87ca1e.png)
> 
> get方法处理的时候，已经有put操作了，因此在lambda中不必再调用put了，这个函数只需生成并返回value即可。
> 
> 你在lambda中调用put，因为非原子性，可能会导致并发问题，从而多次put。

我都没看出来

**Comment by iszhangsc** [comment]
> @iszhangsc 你lambda中的逻辑有问题。
> 
> ![image](https://user-images.githubusercontent.com/1432613/245068845-fc2eb318-2879-4bb4-b9d7-67cc0e87ca1e.png)
> 
> get方法处理的时候，已经有put操作了，因此在lambda中不必再调用put了，这个函数只需生成并返回value即可。
> 
> 你在lambda中调用put，因为非原子性，可能会导致并发问题，从而多次put。

按照源码来看，这个超时时间是没法再进行控制的了对吧
