### ISSUE TITLE
springboot3中hutool中引用的javax包报错怎么办

### ISSUE THREAD

**Issue by TenXLL** [looly/hutool#3143]
### 版本情况

JDK版本：    jdk20
hutool版本： 5.8.19（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
如果使用ServletUtil，改为使用JarkartaServletUtil即可。

如果使用其它工具，使用Hutool-3.0.0.M3。
