### ISSUE TITLE
QrCodeUtil生成的二维码，怎么改留白的宽度

### ISSUE THREAD

**Issue by stoneLee81** [looly/hutool#3144]
设置高，宽是85的二维码，输出后，发现二维码留白太多了，怎么让留白变少，让二维码填满整个输出的图片。

**Comment by looly** [comment]
QrConfig.setMargin

见：https://doc.hutool.cn/pages/QrCodeUtil/#%E7%94%9F%E6%88%90svg%E7%9F%A2%E9%87%8F%E5%9B%BE%E4%BA%8C%E7%BB%B4%E7%A0%81-since-5-8-6

**Comment by stoneLee81** [comment]
测试的代码
QrCodeUtil.generate("https://www.baidu.com", QrConfig.create().setWidth(85).setHeight(85), new File("地址"));
setMargin是让留白更多吧，我希望留白少，让二维码能填满整个图片 @looly

**Comment by looly** [comment]
你可以设置setMargin(0)

**Comment by stoneLee81** [comment]
好像是参数中字符会影响二维码的生成，第一个图是有大幅的留白，设置了margin = 0也是的，但第二幅图留白基本正常
QrCodeUtil.generate("https://www.baidu.com/h5/monitorfile/index.html?sadfsfasdfsafsafasfasfsafasfasdfsafdsafsfasfafsfaasfsdfsfsafasfa", QrConfig.create().setWidth(85).setHeight(85).setMargin(0), new File("地址"));

QrCodeUtil.generate("https://www.baidu.com/h5/monitorfile/index.html?sadfsfasdfsafsafasfasfsafasfasdf", QrConfig.create().setWidth(85).setHeight(85).setMargin(0), new File("地址"));
@looly

**Comment by looly** [comment]
@stoneLee81 看你打开了新的issue，我会在：https://github.com/dromara/hutool/issues/3146 处理回复。
