### ISSUE TITLE
HttpUtil.decodeParamMap方法对于参数中有多个同名参数的问题

### ISSUE THREAD

**Issue by leoxchang** [looly/hutool#3145]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

对于openFeigh调用的get接口，如果用@SpringQueryMap修饰的参数，如果参数用有数组，生成的url是这样的：
oms/course/course-banner/cgb/test-list?evalStatus=2&evalIds=158&evalIds=159&pageSize=2&buyType=1&pageNum=1
其中evallids在参数中定义的是一个数组，在controller层是可以正常解析成数组的，但是HttpUtil.decodeParamMap解析的Map只包含了最后一个参数，例子中的159，原来的版本4.3.2中返回的是第一个参数，即158；这个地方是不是可以改成返回158,169的形式？返回所有的数据

**Comment by CherryRum** [comment]
尝试一下代码
```Java
UrlQuery parse =  UrlQuery.of("oms/course/course-banner/cgb/test-list?evalStatus=2&evalIds=158&evalIds=159&pageSize=2&buyType=1&pageNum=1", Charset.defaultCharset(), true);
Map<CharSequence, List<CharSequence>> collect = parse.getQueryMap().entrySet().stream().collect(Collectors.groupingBy(Map.Entry::getKey, Collectors.mapping(Map.Entry::getValue, Collectors.toList())));
System.out.println(collect);
```

**Comment by leoxchang** [comment]
> 尝试一下代码
> 
> ```java
> UrlQuery parse =  UrlQuery.of("oms/course/course-banner/cgb/test-list?evalStatus=2&evalIds=158&evalIds=159&pageSize=2&buyType=1&pageNum=1", Charset.defaultCharset(), true);
> Map<CharSequence, List<CharSequence>> collect = parse.getQueryMap().entrySet().stream().collect(Collectors.groupingBy(Map.Entry::getKey, Collectors.mapping(Map.Entry::getValue, Collectors.toList())));
> System.out.println(collect);
> ```

HttpUtil本身有一个方法public static Map<String, List<String>> decodeParams(String paramsStr, String charset) ，返回的Map<String, List<String>> ，但不是想要的，只能自己再加工一下了,返回Map<String,String>,其实就是decodeParamMap方法会丢参数

**Comment by CherryRum** [comment]
你说的我都知道
不是会丢参数，有些是需要覆盖，有些是需要List, Map中那个默认覆盖了

**Comment by leoxchang** [comment]
> 你说的我都知道 不是会丢参数，有些是需要覆盖，有些是需要List, Map中那个默认覆盖了
嗯，这个地方确实无法判断是否应该覆盖，还是合成list，得看接收参数是咋样的

**Comment by leoxchang** [comment]
嗯，这个地方确实无法判断是否应该覆盖，还是合成list，得看接收参数是咋样的

**Comment by looly** [comment]
@leoxchang 个性化需求确实无法满足，你只能：

当参数唯一时，使用`decodeParamMap`，参数不唯一时使用`decodeParams`
