### ISSUE TITLE
QrCodeUtil生成的二维码留白的问题

### ISSUE THREAD

**Issue by stoneLee81** [looly/hutool#3146]
setMargin(0)并不能解决留白的问题，测试的content的参数不一样，width,height不一样时，输出的二维码留白会有很大的不同。
测试代码

```java
QrCodeUtil.generate("https://www.baidu.com/h5/monitorfile/index.html?sadfsfasdfsafsafasfasfsafasfasdfsafdsafsfasfafsfaasfsdfsfsafasfa", QrConfig.create().setWidth(85).setHeight(85).setMargin(0), new File("地址"));
```

<img width="106" alt="image" src="https://github.com/dromara/hutool/assets/18001708/cc6c1263-461c-4c83-a344-1989ed39356a">

```java
QrCodeUtil.generate("https://www.baidu.com/h5/monitorfile/index.html?sadfsfasdfsafsafasfasfsafasfasdf", QrConfig.create().setWidth(85).setHeight(85).setMargin(0), new File("地址"));
```

<img width="103" alt="image" src="https://github.com/dromara/hutool/assets/18001708/48896bed-d0cf-4a0b-8220-976901744d28">

**Comment by looly** [comment]
我试了下，确实存在这个问题，但是这个Hutool没法解决，貌似是zxing的问题，不过你可以把宽高设置的大一些，可能是宽高太小，内容太多导致的。

**Comment by stoneLee81** [comment]
> 我试了下，确实存在这个问题，但是这个Hutool没法解决，貌似是zxing的问题，不过你可以把宽高设置的大一些，可能是宽高太小，内容太多导致的。

拿到BitMatrix后，重新调整BitMatrix的高宽，可以修复白边的问题

**Comment by looly** [comment]
@stoneLee81 那还不是调整宽高？宽高加大了？
