### ISSUE TITLE
http请求乱码

### ISSUE THREAD

**Issue by kiwiflydream** [looly/hutool#315]
同 #258 

你设置的默认请求没有指定 utf-8，导致乱码

![image](https://user-images.githubusercontent.com/13311001/55450661-78e97580-5602-11e9-8ec0-62ba623339d2.png)

**Comment by looly** [comment]
请求中这个参数中设置编码无意义吧。

**Comment by kiwiflydream** [comment]
> 请求中这个参数中设置编码无意义吧。



路大，这个肯定有问题的，我们升级了新版，用户反馈我们给他们的请求没有编码头，导致他们出现乱码，对比了代码发现，以前版本的 httprequest 没有设置默认请求头，后面你是通过下面的方法判空然后设置的请求头，
![image](https://user-images.githubusercontent.com/13311001/55604837-67d86a00-57a4-11e9-83dc-d11d6adaa004.png)
后来不知道 httprequest 什么时候加入了全局默认的请求头，然后还没有加编码。然后上面的那个判断就完全没有用了，因为不可能为空了，上面的方法你加了编码，设置全局的时候又没加编码

**Comment by looly** [comment]
明白了。不过按照http规范，这个content-type在响应头中读取有意义，很少有服务器读取这个头信息。4.5.4我会修复这个问题。感谢
