### ISSUE TITLE
Base64中的isBase64方法，随便输入一个英文字符串，就会返回true

### ISSUE THREAD

**Issue by MarioWang0708** [looly/hutool#3151]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Base64中的isBase64方法，随便输入一个英文字符串，就会返回true。
例如：Base64.isBase64("bfsfglafuaw")的返回结果就是true

**Comment by looly** [comment]
这个方法只是简单校验Base64格式，用于区分Hex等，因此它不能作为验证Base64的有效性。

在6.0.0中，此方法更名为：

```
isTypeBase64
```
