### ISSUE TITLE
RowUtil

### ISSUE THREAD

**Issue by 553531284** [looly/hutool#3153]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![image](https://github.com/dromara/hutool/assets/26433083/94849a68-219c-4077-aba1-f553c7a496e5)

**Comment by looly** [comment]
确认bug。

5.8.20修复此问题！感谢~~
