### ISSUE TITLE
使用ZipWriter工具类创建一个空的，还是有大小

### ISSUE THREAD

**Issue by zuikushaoshao** [looly/hutool#3156]
### 版本情况

JDK版本：    java1.8.0_241
hutool版本：5.8.0.M3

### 问题描述（包括截图）
使用ZipWriter工具类创建一个空的，还是有大小,大小为22kb
![image](https://github.com/dromara/hutool/assets/39935147/6c314195-afda-4bc5-b39f-98634862fb82)

1. 复现代码

```java
ZipWriter of = ZipWriter.of(new File("D:\\my-computer\\Desktop\\aa.zip"), CharsetUtil.defaultCharset());
        of.close();
```

**Comment by zuikushaoshao** [comment]
希望能出一个判断空的,并且解决创建空zip，是0字节。
目前我自己解决方案是如下代码:
```
ZipFile isZipFile = ZipUtil.toZipFile(new File(zipFilePath), CharsetUtil.defaultCharset());
            if (isZipFile.size() == 0) {
              
            }
```

**Comment by looly** [comment]
Zip文件本身有一些meta信息，size肯定不是0。

判空只能自行遍历，看是否有entry。
