### ISSUE TITLE
升级到5.8.19后把mp4文件判定成m4a类

### ISSUE THREAD

**Issue by aijoo2012** [looly/hutool#3160]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.8.19

### 问题描述（包括截图）

1. 复现代码

```java
 String uploadFileType = FileTypeUtil.getType(inputStream);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
测试文件地址：http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
错误信息：
将mp4文件判断成了m4a导致上传失败

**Comment by aijoo2012** [comment]
看错了。是M4V。没问题

**Comment by CherryRum** [comment]
<img width="583" alt="image" src="https://github.com/dromara/hutool/assets/24296698/90077a6c-b757-4a2f-ae74-f9d8ace93c83">
确实是M4V

**Comment by aijoo2012** [comment]
公众号：凯哥Java(kaigejava)个人博客：www.kaigejava.com

**Comment by CherryRum** [comment]
你差点给我整不自信了
