### ISSUE TITLE
MapUtil工具使用filter方法问题

### ISSUE THREAD

**Issue by Dxdzy86** [looly/hutool#3162]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.8.20

### 问题描述（包括截图）
MapUtil工具的filter方法，我看描述是“过滤Map保留指定键值对，如果键不存在跳过”。我指定了需要过滤保留的key，但是该filter方法的执行结果还是初始的Map值。并且MapUtil的getAny方法也是这个情况。

1. 复现代码

```java
Map<String, Object> map = new HashMap<String, Object>() {{
            put("a", "1");
            put("b", "2");
            put("c", "3");
        }};
        Map<String, Object> filtered = MapUtil.filter(map, "a", "b");
        Console.log(filtered.toString());
```
![image](https://github.com/dromara/hutool/assets/32768934/82d0bbe2-f5e1-4ef1-a074-2371f2644687)

**Comment by looly** [comment]
5.8.21
6.0.0-M5

修复此问题，感谢~~

**Comment by CherryRum** [comment]
# 问题概述

在处理Java中的Map时，使用"{{}}"进行初始化可能会导致一些未预期的问题，主要是因为这种双大括号初始化（`double-brace initialization`）实际上创建了`Map`的**匿名子类**。这种做法可能会导致`getClass()`方法返回不是我们期望的`Map`类（如`HashMap或LinkedHashMap`），而是一个特定的匿名子类。

另一个相关问题是EnumMap的实例化问题。因为EnumMap的构造函数需要一个Enum类型的Class对象，这使得我们不能像其他Map一样使用默认构造函数创建它的实例。

# 解决方案

为了解决这个问题，我们需要在创建新的Map实例时更加小心。在我们的`newInstanceIfPossible`方法中，我们需要检查`map.getClass()`是否返回的是一个匿名类或成员类。如果是，我们需要使用`getSuperclass()`方法来找到它的直接超类，这将会是我们期望的Map类。这样我们就可以使用这个类来创建新的Map实例。

或者我们发现初始化的内部类不为空(empty),手动清空，但是这样我们会丢失原类型。

```java
Class<?> aClass = map.getClass();
if (aClass.isAnonymousClass() || aClass.isMemberClass()) {
    aClass = aClass.getSuperclass();
}
Map<K, V> map2 = newInstanceIfPossible(aClass);

或者 一般不会有多个情况

while (aClass.getName().contains("$")) {
            aClass = aClass.getSuperclass();
         }
```

另外，由于`EnumMap`的特殊性，如果我们不能确定要用于创建`EnumMap`的`Enum`类，我们可能需要避免实例化`EnumMap`，或者提供一个专门用于`EnumMap`的方法，并在该方法中需要明确提供`Enum`类型，所以这个情况暂时不考虑。
一个小建议，**使用双大括号初始化**通常不是一个好的实践，除非你有特定的理由要这么做。在其他情况下，使用普通的构造函数来初始化你的Map可能是更好的选择。
具体参考 
https://jesperdj.com/2016/07/19/dont-use-the-double-brace-initialization-trick/
