### ISSUE TITLE
SensitiveUtil工具类，如果敏感词的最后一位是StopChar，将不起效果

### ISSUE THREAD

**Issue by nothingbj** [looly/hutool#3164]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

敏感词是：

 (禁看)

代码是
`List<String> list1 = FileUtil.readLines("C:\\Users\\Downloads\\625.txt", "UTF-8");`
        `SensitiveUtil.init(list1);`
        `List<FoundWord> d = SensitiveUtil.getFoundAllSensitive("(禁看)");`
        `System.out.println(JSONObject.toJSONString(d));`

2. 堆栈信息

WordTree是
![image](https://github.com/dromara/hutool/assets/7500295/1c20c1ce-46ac-422f-8e84-984ca11dbd3f)
endCharacterSet是 ")"
![image](https://github.com/dromara/hutool/assets/7500295/a96943b9-26e0-4994-b90e-8df43a8146fb)

match的时候，159行这里，判断最后一个字“看”不是endCharacterSet“)”，没有进到这个if，foundWords没有add进去
![image](https://github.com/dromara/hutool/assets/7500295/5d5f5b2e-d713-45a0-8080-a592c1618313)

![image](https://github.com/dromara/hutool/assets/7500295/c49c697e-3d2a-443c-b8f4-037555d1e774)

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
首先StopChar是用于跳过正文中的特殊字符的，你的关键词中不应该有stopChar。

**Comment by nothingbj** [comment]
> 首先StopChar是用于跳过正文中的特殊字符的，你的关键词中不应该有stopChar。

收到，谢谢了
