### ISSUE TITLE
jedis连接失败

### ISSUE THREAD

**Issue by changxinjie** [looly/hutool#3166]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
final Jedis jedis = RedisDS.create().getJedis();
```

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/9565184/7c8c9a04-8687-4a6a-b773-5b551bd77270)

3. 测试涉及到的文件（注意脱密）
![image](https://github.com/dromara/hutool/assets/9565184/a28430e0-93cd-4057-9098-4ce089f60acd)

比如报错的Excel文件，有问题的图片等。

**Comment by changxinjie** [comment]
'redis.clients:jedis:4.4.3'

**Comment by looly** [comment]
使用原生Jedis连接试下，应该是密码部分没有读取到。
