### ISSUE TITLE
ExecutorService.newExecutor(10) 的无限创建线程池问题

### ISSUE THREAD

**Issue by dianbaiyizhong** [looly/hutool#3167]
我说下我的理解，这个方法一般会让入门开发者认为是“创建一个拥有一次性只能执行10个任务的线程池”，因为这个场景在工作中经常用到。然而最近被这个方法坑一了下。。
例如我设置了参数为10，也就是ExecutorService.newExecutor(10) ，当任务队列超过一定数量，例如超过1024+10 = 1035.。。。。此时会多创建一个线程池来执行第二份任务，这个实在是让人意想不到。。具体测试代码如下

```java
    public static void main(String[] args) {
        ExecutorService executorService = ThreadUtil.newExecutor(10);

        for (int i = 0; i < 1035; i++) {
            int finalI = i;
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    System.out.println(finalI);
                    ThreadUtil.sleep(50000);
                }
            });
        }
    }
```

理论上应该打印10行，但是超过1024的那份任务会再生成一个新的线程池去运行，一共打印了11行。。。如果任务数量继续增加，录入成千上万，会生成几十个线程池。。

**Comment by looly** [comment]
是这么设计的。

如果有自定义需求，考虑使用`ExecutorBuilder`自定义构建线程池。

**Comment by dianbaiyizhong** [comment]
@looly 不知道能否赐教一下，这样设计的初衷是什么呢。。。ExecutorService.newExecutor(10)作为最简单的线程池初始化，为何默认要埋一个1024队列的值在这里。。不如不埋他，让用户自定义去设置自己的1024

**Comment by looly** [comment]
@dianbaiyizhong 你可以看下JDK的`Executors.newFixedThreadPool`，默认创建的LinkedBlockingQueue初始大小为`Integer.MAX_VALUE`。

Hutool此处给一个较小的值以满足常会需求。至于1024这个值的意义，只能说预估的……

**Comment by dianbaiyizhong** [comment]
@looly 我不是说1024这个值的问题。。我直接说下我的建议就是：干脆ThreadUtil.newExecutor应该直接等效于jdk的ThreadUtil.newExecutor就可以了。。。。。我觉得这个才是最常用的场景。。。
而你现在设置的1024，可不是什么善哉。。。并非超过1024就拒绝了，而是一旦超过1024，剩余的部分会继续起一个新的线程池来运行，这个更坑。至少我认为你们这个方法的说明文档里得标注一下。。
之所以提这个建议是，日常开发中创建线程池第一时间也是想到用hutool的ThreadUtil直接印出来创建，我感觉newFixedThreadPool应该是最常用的才对。你推荐我用Executors.newFixedThreadPool，这个我肯定已经用了，因为线上被这个1024搞到内存溢出了都。。我就是提个建议，交流交流。。hutool不是提供简单工具类么

**Comment by Createsequence** [comment]
> @looly 我不是说1024这个值的问题。。我直接说下我的建议就是：干脆ThreadUtil.newExecutor应该直接等效于jdk的ThreadUtil.newExecutor就可以了。。。。。我觉得这个才是最常用的场景。。。 而你现在设置的1024，可不是什么善哉。。。并非超过1024就拒绝了，而是一旦超过1024，剩余的部分会继续起一个新的线程池来运行，这个更坑。至少我认为你们这个方法的说明文档里得标注一下。。 之所以提这个建议是，日常开发中创建线程池第一时间也是想到用hutool的ThreadUtil直接印出来创建，我感觉newFixedThreadPool应该是最常用的才对。你推荐我用Executors.newFixedThreadPool，这个我肯定已经用了，因为线上被这个1024搞到内存溢出了都。。我就是提个建议，交流交流。。hutool不是提供简单工具类么

同意，感觉楼上说的有道理，默认的 `newExecutor` 等效于 `newFixedThreadPool` 比起现在的实现要更符合直觉

**Comment by looly** [comment]
@dianbaiyizhong 我又重新捋了一下。

默认的：
core = 10
max = 无限
queue = 1024

那这样的规则就是：新进的线程，首先使用core线程执行，多余的放入queue，queue满了之后，继续创建线程，直到达到max。

这个规则确实有问题，真正执行的时候queue的作用无法或很难体现出来。

考虑到兼容性问题，5.x不做修改，6.x此处创建线程按照JDK规则修改，感谢~。
