### ISSUE TITLE
FileUtil.ls

### ISSUE THREAD

**Issue by xm0625** [looly/hutool#3172]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.5.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
FileUtil.ls("./pair");
```

2. 环境信息
IDEA目录接口
-pair
-src
--com
----xm
------a.java

在a的main方法中调用的FileUtil.ls("./pair")，使用IDEA的debug功能运行main方法，此时报pair不是目录，debug发现内部new File之后路径在/target/pair下，
而同样的位置使用(new File("./pair")).isDirectory()为true，new File("./pair")可以正确找到目录，说明workDir是对的，在IDEA项目根目录

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xm0625** [comment]
感觉是getAbsolutePath导致的问题

**Comment by looly** [comment]
@xm0625 使用FileUtil传入相对路径，默认相对的是classpath路径，因此出现你说的这个问题。

你这种情况可以直接使用：

```java
File file = new File(xxxx);
ile.listFiles();
```

**Comment by xm0625** [comment]
嗯嗯。。。已经用listFiles((FileFilter) FileFilterUtils.directoryFileFilter());解决了
