### ISSUE TITLE
【功能支持】最大公约数、最小公倍数入参支持多个

### ISSUE THREAD

**Issue by ljynfo** [looly/hutool#3173]
最大公约数、最小公倍数方法入参目前只支持2个，请求可以支持多个，类似

    public static int multiple(int m, int n, int ... nums) {
    }

**Comment by looly** [comment]
嗯……不考虑。考虑多次调用吧。

**Comment by ljynfo** [comment]
> 嗯……不考虑。考虑多次调用吧。

为啥不考虑啊，这个应该是一个常用的需求吧，现在基本找不到什么工具有类似多个入参的方法，还是希望考虑支持一下
