### ISSUE TITLE
`java.math.BigDecimal#valueOf(double) 也得注意`

### ISSUE THREAD

**Issue by gMan1990** [looly/hutool#3175]
https://github.com/dromara/hutool/blob/45879c3f7a395fa1344727437625aa6262d47346/hutool-core/src/main/java/cn/hutool/core/util/NumberUtil.java#L25

```java
System.out.println(BigDecimal.valueOf(0.1d));
System.out.println(BigDecimal.valueOf(0.1f));
System.out.println(new BigDecimal(0.1d));
System.out.println(new BigDecimal(0.1f));
```

```text
0.1
0.10000000149011612
0.1000000000000000055511151231257827021181583404541015625
0.100000001490116119384765625
```

**Comment by CherryRum** [comment]
注释中写明了
<img width="969" alt="CleanShot 2023-06-28 at 08 47 21@2x" src="https://github.com/dromara/hutool/assets/24296698/1241d67c-e56b-466c-91bd-33d412c16c69">

**Comment by gMan1990** [comment]
@CherryRum 注释里是1个方法，我提的issue还有valueOf方法

**Comment by CherryRum** [comment]
原因是一样的，valueOf重载的其实就是new 
double试用的 ieee754肯定是没法表示出来的

**Comment by gMan1990** [comment]
@CherryRum `BigDecimal.valueOf(0.1d)` 走的是 String 模式，结果是对的。但 `BigDecimal.valueOf(0.1f)` 是另外的问题引起的精度
