### ISSUE TITLE
感觉可以使用 `@Deprecated` 和 `@deprecated`

### ISSUE THREAD

**Issue by gMan1990** [looly/hutool#3177]
https://github.com/dromara/hutool/blob/050f312c564699a17b4c52c121bbe787e8e37fbd/hutool-core/src/main/java/cn/hutool/core/net/URLEncodeUtil.java#L11

```java
/**
 * URL编码工具
 *
 * @author looly
 * @since 5.7.13
 * @deprecated 在6.x中移除此工具（无法很好区分URL编码和www-form编码）
 */
@Deprecated
public class URLEncodeUtil {
```

**Comment by CherryRum** [comment]
没办法，由于很多东西，不移除没人维护的话，`@Deprecated`一般代表会有新的替代，移除的原因是没法进行很好的维护，或者由于外部原因（某些其他库的bug）然后这边无法解决，一些cve漏洞

**Comment by looly** [comment]
@gMan1990 在5.x中这个类 依旧需要使用，而且没有替代，只有6.x才会移除，因此只能加个注释。
