### ISSUE TITLE
官网文档的“IO流相关”概述中的描述有问题

### ISSUE THREAD

**Issue by ajiakes** [looly/hutool#3178]
网址：https://www.hutool.cn/docs/#/core/IO/%E6%A6%82%E8%BF%B0
位置：
       IO流相关-概述-由来
问题：
      由来下面的描述中说 “而如果想读写字节流，还需要Reader和Writer的各种实现类”，这里应该是字符流，还望改正
截图：
![1687933818885](https://github.com/dromara/hutool/assets/55873415/a979840c-f365-44bd-ae89-3d15ded163e4)

**Comment by handy-git** [comment]
InputStream 是一个抽象类，用于读取字节流。它是 Java I/O 库中用来从数据源（如文件、网络连接等）读取原始字节数据的基类。它提供了一系列方法来读取字节流，如 read() 方法用于读取单个字节，read(byte[] buffer) 方法用于读取字节数组等。

与之对应的是字符流，由 Reader 和 Writer 类及其子类构成。它们是高级别的 I/O 类，用于读写字符数据而不是字节。字符流提供了更高级的操作，能够直接读写字符并进行字符编码转换等。

所以，如果需要操作字符数据，推荐使用字符流（Reader 和 Writer），如果需要操作字节数据，使用字节流（InputStream 和 OutputStream）更合适。

**Comment by handy-git** [comment]
确实应该是字符流

**Comment by looly** [comment]
OK，后续修改文档描述。
