### ISSUE TITLE
创建2个sheet时，第二个sheet header会使用第一个sheet header的排序规则

### ISSUE THREAD

**Issue by heyaping388** [looly/hutool#318]
调用clearHeaderAlias()未清空 第一个sheet的比较器， 所以(null == aliasComparator) 不成立 ，getInitedAliasComparator()返回的 还是第一个sheet的比较器  
![8C)LHEDQ X6FQ@UI`6738NQ](https://user-images.githubusercontent.com/25815555/55708862-90b56500-5a19-11e9-9701-bb10c53b33ec.png)

**Comment by looly** [comment]
4.5.5修复此问题，感谢。
