### ISSUE TITLE
Hutool-dfa最新版预期结果和文档不一致

### ISSUE THREAD

**Issue by cyao2q** [looly/hutool#3180]
![image](https://github.com/dromara/hutool/assets/10820724/91143d55-72ac-42a2-a5d1-b4daf47d38f9)

我测到的5.7.21之后所有版本都不正常 实际输出
```
[大, 土豆, 刚出锅]
```

5.7.20旧版本可以
![image](https://github.com/dromara/hutool/assets/10820724/d5a8d83c-6d56-405a-ac86-ae8d24760359)

5.7.21修复BUG后出问题
![image](https://github.com/dromara/hutool/assets/10820724/6541dc88-d079-4161-aff7-0588e12a53c8)

**Comment by looly** [comment]
嗯，看来文档要修改了。近期修改文档。感谢。

**Comment by cyao2q** [comment]
现在的版本是 第一种参数和第三种参数结果完全一致了 是想要的吗
![image](https://github.com/dromara/hutool/assets/10820724/d7a9bb01-0c46-4b31-902e-ad061781f244)
