### ISSUE TITLE
分钟不是00的utc时间是解析不了吗

### ISSUE THREAD

**Issue by minatoyukina** [looly/hutool#3181]
比如`2023-05-17T06:10:00-04:30`。5.8.18版本

**Comment by looly** [comment]
`2023-05-17T06:10:00-04:30`

你这个很明显不是时间吧，而是一个时间段吧。肯定没法解析。

**Comment by looly** [comment]
我猜测`-04:30`是个时区标识是吧？时区表示不能包含分钟的。

**Comment by minatoyukina** [comment]
不是有半时区甚至quarter吗

**Comment by looly** [comment]
@minatoyukina 这块还真是不了解。你看使用SimpleDateFormat或者LocalDateTime可以解析不。
