### ISSUE TITLE
继续探讨关于RandomUtil.randomInt(min,max)问题

### ISSUE THREAD

**Issue by dianbaiyizhong** [looly/hutool#3182]
既然是参考了jdk的逻辑，走的是不允许两个参数值相等，可否新增一个类似区间开关的功能，例如类似于guava的随机生成Range类
```java
        Range<Integer> range = Range.closedOpen(20, 20);
```
除此之外还有openClosed，close，和open方法。。。可以让调用者设置范围区间的开关。

另外我想提醒的是。commons-lang的ramdon是允许两值相等的。我认为两值相等不抛异常更常用。

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/4a2c3c07-4a8e-46c4-9375-411a786ca6cf)

commons也是开闭区间。

**Comment by looly** [comment]
5.8.21 6.0.0-M5增加可选是否包含边界的重载：

https://github.com/dromara/hutool/commit/77e455d98b0dd62b7f7b6027137217b9bff94b09

**Comment by dianbaiyizhong** [comment]
@looly 哎呦不错哦

**Comment by ichenfeng** [comment]
![image](https://github.com/dromara/hutool/assets/2437125/55a2be94-2791-4e3b-a10d-df59f1585330)
这个实现有问题吧？ @looly
