### ISSUE TITLE
关乎hutool.db目前不支持hint的一点问题

### ISSUE THREAD

**Issue by sakuraacc** [looly/hutool#3183]
作者你好，我们目前的项目用到db查询数据库的时候需要用到hint来优化，目前没有发现支持这个功能，我们的想法是提供这点的代码push上来，或者有什么解决的好方法，期待回复，谢谢

**Comment by looly** [comment]
这个hint我不太了解，可否详细描述下使用方式？我记得有个issue我已经回复了，hint貌似是Oracle的独有特性，没办法支持。

补充后再打开此issue。

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I7HKOY
