### ISSUE TITLE
TableMap中isEmpty方法报错

### ISSUE THREAD

**Issue by liangleiA** [looly/hutool#3185]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.1.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
TableMap中isEmpty方法使用ArrayUtil.isEmpty判空, ArrayUtil.isEmpty接收的应该是数组,而这里使用了List,导致报错     Object to provide is not a Array !1034 

1. 复现代码

```java
		UrlBuilder urlBuilder = UrlBuilder.ofHttp("http://dmp/flow/L001/code?s=A11");
		CharSequence s = urlBuilder.getQuery().get("s");
		System.out.println(s);
```

2. 堆栈信息

**Comment by looly** [comment]
@liangleiA 我想是你遇到bug了。最新版本没有这个问题。

![image](https://github.com/dromara/hutool/assets/1432613/49a96d2b-b135-4942-a92f-fbb70ed70e74)
