### ISSUE TITLE
InternUtil问题

### ISSUE THREAD

**Issue by bigprincipalkk** [looly/hutool#3186]
### 问题描述（包括截图）
1.背景
开发一个基础组件给业务使用，这个组件会不停的更新信息，其中的一部分字符串会保存在内存，其中有很多重复的字符串，并且及时ygc不掉，会比较快的进入老年代，看到了hutool提供的interner，所以效仿这部分代码做了实现。其中省略了purgeStaleKeys这部分代码，并且WeakKey的构造方法使用的是父类不包含引用队列的构造方法，其他关键代码均保持一致。
<img width="542" alt="image" src="https://github.com/dromara/hutool/assets/45305238/d5d1e0eb-9f72-4acb-b6c4-8468eb21c3c1">
2.使用方式
当组件产生大量字符串时，及时的使用intern将这产生的这部分池化起来，这样新增的重复的一部分String由于失去了强引用，在ygc就会被清除掉。结果证明，内存减少了许多。
3.问题
当数据量过大时，产生了CPU热点现象，热点主要出现在ReferenceConcurrentMap的findNodeTree上，起初以为是equals方法没有写对，导致红黑树较高，但是比较并且自测没有发现问题，并且从堆内存快照来看，整个堆中的String有50w个，但是Weakey对象产生了200w+个。
我的理解：
WeakConcurrentMap的key是WeakKey对象，本质上就是String对象的一个弱引用，value存放的就是WeakRefrence对象，也是指向String，如果不加purgeStaleKeys主动清除被回收的对象，那Node指向的key和val都被清除了，Node一直不会被释放导致的问题？

**Comment by looly** [comment]
这个问题对我来说太难了，超出了我的能力。

@CherryRum 靠你了~~

**Comment by Createsequence** [comment]
我尝试理解一下。

首先：
1、你参考 hutool 的代码实现了一个 `ReferenceConcurrentMap`，其中，键使用 `WeakKey` ，值使用 `WeakRefrence`（我可以理解是 `Map<Reference<K>, Reference<V>>` 这样的结构吗？）；
2、在你的版本中， `WeakKey` 的父类构造中没有传入因此队列，因此键被回收的时候不会进入队列；
3、由于没有队列，因此无法且不用 `purgeStaleKeys` 方法主动的移除被回收的键对应的值；

然后，在数据量较大的情况下，出现了 CPU 热点，它主要位于 `ConcurrentMap`  的 `findTreeNode` 方法，同时你注意到堆中存活的 `Weakey` 和 `String` 数量差距较大。

最后，你怀疑问题是因为即使作为弱引用对象键值都被回收了，但是 `Node` 实例依然没有被回收，导致槽中的树过高？

**Comment by bigprincipalkk** [comment]
@Createsequence 对，您总结的非常好，我现在就是这个疑问。
1. 对于1提到的Map<Reference<K>, Reference<V>>我看源码本质上就是这样实现的对吧，其中key是WeakKey对象，WeakKey继承的WeakRefrence，cn.hutool.core.lang.intern.WeakInterner#cache在声明时指定了value是WeakReference<T>。
2. 由于这个组件的试错成本较大，比较难让业务去试用观察效果，自己在线下又复现不出问题，所以想先请教下这块是否会存在这个问题。    
3. 其他会导致树高的问题只想到equals，但是测试是没有问题的。 
4. 还有比较疑惑的一点就是为啥有那么多的WeakKey对象产生，从dump中看很多都套了多层next。


最后，感谢大佬的解答，我现在是个小菜鸡，确实遇到了这个问题，可能某些方面在表述上有问题，希望大佬们不吝赐教，我多多学习。

**Comment by CherryRum** [comment]
@bigprincipalkk   是否有分析的dump的截图呢

**Comment by bigprincipalkk** [comment]
@CherryRum 有的
<img width="1775" alt="image" src="https://github.com/dromara/hutool/assets/45305238/d7d4d980-640c-4414-b8b2-bbe8e2279100">
<img width="673" alt="image" src="https://github.com/dromara/hutool/assets/45305238/b87f018b-921c-4e61-8bae-8551817186f4">
<img width="742" alt="image" src="https://github.com/dromara/hutool/assets/45305238/612814b5-650a-4c88-8504-db445e90ba21">
<img width="624" alt="image" src="https://github.com/dromara/hutool/assets/45305238/1853cf2f-eb3f-4d99-9c4f-9ddcb7e82ef6">


您看看还需要哪些

**Comment by Createsequence** [comment]
> @Createsequence 对，您总结的非常好，我现在就是这个疑问。
>
> 1. 对于1提到的Map<Reference, Reference>我看源码本质上就是这样实现的对吧，其中key是WeakKey对象，WeakKey继承的WeakRefrence，cn.hutool.core.lang.intern.WeakInterner#cache在声明时指定了value是WeakReference。
> 2. 由于这个组件的试错成本较大，比较难让业务去试用观察效果，自己在线下又复现不出问题，所以想先请教下这块是否会存在这个问题。
> 3. 其他会导致树高的问题只想到equals，但是测试是没有问题的。
> 4. 还有比较疑惑的一点就是为啥有那么多的WeakKey对象产生，从dump中看很多都套了多层next。
>
> 最后，感谢大佬的解答，我现在是个小菜鸡，确实遇到了这个问题，可能某些方面在表述上有问题，希望大佬们不吝赐教，我多多学习。

首先，Hutool 的 `WeakConcurrentMap` 的实际上并没有包装值，而只包装了键，因此它不是 `Map<Reference<K>, Reference<V>>` 的结构，而是 `Map<Reference<K>, V>`。

我去看了其他库中 `WeakConcurrentMap` 的实现：

- Spring 的 `ConcurrentReferenceHashMap` 和 JDK 的 `WeakHashMap` 直接将 `Entry` 包装为弱引用对象，并且在必要的时候也会主动调用 `restructureIfNecessary` 清空无效键值；
- Guava 的 `MapMaker` 如果将键值都指定为弱引用对象，则将会直接将 `Entry` 包装为弱引用对象，但是在 `MapMakerInternalMap` 中同样会调用 `preWriteCleanup` 清空无效键值；
- Hutool 的 `WeakConcurrentMap` 与 JDK 的 `WeakKeyConcurrentHashMap` 都将键包装为弱引用对象，并且在每次操作前都会清空无效的键值；

也就是说：

- `WeakKey` 数量问题：键值分别分别指的是 `Reference<K>` （`WeakKey`）和 `Reference<V>`，真正被回收的是两个引用中的对象，也就是你说的大字符串对象，我猜测，由于没有主动地清空无效的键值对，因此实际上不管是 `WeakKey` 本身还是 `Reference` 都是没有被回收的，所以堆中才会出现 `WeakKey` 与 `String` 数量不成正比的情况，如果这个猜想成立，我觉得你可以验证一下包装值的 `Reference` 对象数量是否与 `WeakKey` 大致相同；

- 热点问题：基于上述的推断，我猜测即使键值都被回收的，但是由于没有主动的清理，所以 `Entry` 依然没有被回收，并且 `Entry` 依然保持着与 `WeakKey` 的 `Reference` ——注意，不是缓存的大字符串——的强引用，这个问题的直接表现就是槽中的树节点越来越高，`WeakKey` 的数量也越来越多；

如果上述推论成立，那么你的理解应该是正确的，这个问题本质上与键值是否为弱引用对象无关，而是垃圾清理这一步不能省略。

**Comment by bigprincipalkk** [comment]
@Createsequence 
辛苦解答，您说的我明白了。
那我先在线下用目前不主动清除的代码，模拟下让WeakKey指向的String失去强引用，然后主动触发gc，再去观察内存中关联的Entry的表现，以及与加上主动清除的对比，这样应该可以得出结论。

**Comment by bigprincipalkk** [comment]
@looly @CherryRum @Createsequence 

- 我按照上面说的方式测试了下，发现确实是没有主动清除，导致entry没有被释放的原因导致，并且Entry对WeakKey保持着强引用，导致之前被释放掉的String对应的WeakKey释放不了，下面是测试代码以及相关的内存截图。
<img width="881" alt="image" src="https://github.com/dromara/hutool/assets/45305238/7cbd7a22-915a-43cf-949f-035a0de6e346">

**不加主动释放的情况**：

<img width="751" alt="image" src="https://github.com/dromara/hutool/assets/45305238/3b5cbfe9-204a-4f59-b3ab-4637915bb37e">

<img width="664" alt="image" src="https://github.com/dromara/hutool/assets/45305238/45c48554-adac-408f-ad5d-bed4ddf9dbe5">

**加主动释放的情况**：

<img width="767" alt="image" src="https://github.com/dromara/hutool/assets/45305238/d108cb82-8b49-451b-a6b1-6b4455847b08">
<img width="693" alt="image" src="https://github.com/dromara/hutool/assets/45305238/289b0f34-1a52-4720-9686-6087b4b95d54">

- 这块当初开发的时候觉得jvm会在合适的时机会把对应的失效的key以及node回收掉，没考虑到中间的强引用。这块后续深入思考并调整一下。

**_最后，感谢各位大佬的解答，祝一切顺利。_**

**Comment by Createsequence** [comment]
> @looly @CherryRum @Createsequence
> 
> * 我按照上面说的方式测试了下，发现确实是没有主动清除，导致entry没有被释放的原因导致，并且Entry对WeakKey保持着强引用，导致之前被释放掉的String对应的WeakKey释放不了，下面是测试代码以及相关的内存截图。
> 
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/45305238/250787599-7cbd7a22-915a-43cf-949f-035a0de6e346.png">
> **不加主动释放的情况**：
> 
> <img alt="image" width="751" src="https://user-images.githubusercontent.com/45305238/250789211-3b5cbfe9-204a-4f59-b3ab-4637915bb37e.png"> <img alt="image" width="664" src="https://user-images.githubusercontent.com/45305238/250788269-45c48554-adac-408f-ad5d-bed4ddf9dbe5.png">
> **加主动释放的情况**：
> 
> <img alt="image" width="767" src="https://user-images.githubusercontent.com/45305238/250788485-d108cb82-8b49-451b-a6b1-6b4455847b08.png"> <img alt="image" width="693" src="https://user-images.githubusercontent.com/45305238/250788578-289b0f34-1a52-4720-9686-6087b4b95d54.png">
> * 这块当初开发的时候觉得jvm会在合适的时机会把对应的失效的key以及node回收掉，没考虑到中间的强引用。这块后续深入思考并调整一下。
> 
> **_最后，感谢各位大佬的解答，祝一切顺利。_**

很高兴能够帮助你解决这个问题，也祝你一切顺利。如果暂时没有的疑问了，你可以先关闭该 issues。

**Comment by looly** [comment]
哈哈，感谢各位大佬的讨论，小白的我默默学习。
