### ISSUE TITLE
动态变化的sheet页名称，ExcelReader报错No Sheet provided

### ISSUE THREAD

**Issue by YuLoving** [looly/hutool#3189]
ExcelReader(File bookFile, String sheetName)这个方法中如果sheetName不存在就会报错No Sheet provided。目前我这边是直接catch这个异常且判断异常信息是否是No Sheet provided。如果是则跳过。虽然我业务逻辑上catch了。但是如果hutool后续版本中修改了异常类型或者异常信息。那么我这边的处理还是失效了。所以我的想法是能不能加一个入参 或者新增一个方法来兼容sheetName不存在的清空。比如不存在时直接返回null也可以。

**Comment by looly** [comment]
嗯……这个异常类型不会修改。

还有你可以根据sheetIndex选：

![image](https://github.com/dromara/hutool/assets/1432613/6ad93e0c-2634-4c6a-a2d6-8cfcfee686de)

**Comment by YuLoving** [comment]
恩恩 只要异常类型和报错信息（No Sheet provided.）不变就可以。sheetIndex这个方式不适用我当下业务.正因为sheetName是动态的且sheet的顺序也是动态的  后续逻辑又需要基于sheetName来执行不同的处理逻辑。但是sheetIndex我无法识别归属于哪个name 所以不好处理对应业务
