### ISSUE TITLE
NumberUtil可能有bug

### ISSUE THREAD

**Issue by 89333367** [looly/hutool#3190]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.20</version>
        </dependency>

### 问题描述（包括截图）

1. 复现代码

![image](https://github.com/dromara/hutool/assets/20157752/c28c4de0-87d3-4dba-b0a1-12277d45512f)

感觉这个不应该是true

**Comment by looly** [comment]
e是科学计数法，d结尾表示double，所以没问题。
