### ISSUE TITLE
现在版本的Sm2不能用私钥加密、公钥解密了

### ISSUE THREAD

**Issue by ybbwk** [looly/hutool#3191]
### 版本情况

JDK版本：    jdk_17
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
最新版的国密Sm2不支持使用私钥加密、公钥解密，原来是支持的。不知为何？是国密的规范要求么？
![图片](https://github.com/dromara/hutool/assets/522288/c3b94ce6-228a-4026-9074-30bbe2f0288a)
encrypt和decrypt方法的入参keyType还有什么意义？

**Comment by looly** [comment]
SM2一直是公钥加密，私钥解密，没有提供私钥加密功能。

![image](https://github.com/dromara/hutool/assets/1432613/9feba631-8663-4e4d-94c0-a7a447d73769)

encrypt和decrypt方法的入参keyType是为了兼容`AbstractAsymmetricCrypto`通用接口而实现的，同时提供了无KeyType方法：

![image](https://github.com/dromara/hutool/assets/1432613/59daf7a0-b3d3-4424-b7aa-4ab6a43547df)

**Comment by CherryRum** [comment]
SM2是一种基于椭圆曲线密码学（Elliptic Curve Cryptography，ECC）的密码算法。在SM2中，私钥用于签名操作，而公钥用于验证签名。因此，SM2算法不支持使用私钥加密和公钥解密的操作。
换句话说，你这个场景叫做验证签名（验签），而不是加密和解密
私钥用于生成数字签名，以确保数据的完整性和身份验证。发送方使用私钥对数据进行签名，接收方使用发送方的公钥验证签名，以确保数据的来源和完整性。
