### ISSUE TITLE
创建rowHandler时，List<Object> cellList列顺序发生了变化

### ISSUE THREAD

**Issue by bosen365** [looly/hutool#3194]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.18（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
创建列处理时，列的顺序发生了变化，导致导入的数据错位
public void handle(int sheetIndex, long rowIndex, List<Object> cellList)

其中cellList顺序错乱，导致导入到库中的数据错位

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
没看懂你的问题。cellList为何会顺序错乱，你意思是读取出来的顺序和表格中的实际顺序不一致？

麻烦补充下你的测试用例代码，上传测试的excel我这边测试。

补充后再打开此issue。
