### ISSUE TITLE
设置上传文件属性

### ISSUE THREAD

**Issue by savior-only** [looly/hutool#3195]
https://github.com/dromara/hutool/issues/3158
关于这个问题

POST /test HTTP/1.1
Content-Type: multipart/form-data; boundary=A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT
User-Agent: Java/1.8.0_345
Host: 
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Content-Length: 219
Connection: close

--A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT
Content-Disposition: form-data; name="upload"; filename="1.jsp"
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

123
--A9-oH6XdEkeyrNu4cNSk-ppZB059oDDT--

5.8.20修改此处逻辑，调用body方法也可以使用multipart方式。
我需要一个示例代码实现设置
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

麻烦给一下，谢谢🙏

**Comment by looly** [comment]
直接调用：

HttpRequest.post(url)
.header(xxx)
.body(xxx)
