### ISSUE TITLE
httprequest gzip 返回时，数据返回不全

### ISSUE THREAD

**Issue by AVAL-NIX** [looly/hutool#3197]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

python tornado 框架， 设定返回值为gzip压缩,  java端接收到半截， postman接收正常
<img width="1345" alt="image" src="https://github.com/dromara/hutool/assets/30321646/91fe974f-6ed0-46cf-bbee-5382b37dbe45">

```
    def response(self, data):
          self.set_header("Content-Encoding", "gzip")
          self.write(gzip.compress(data.encode("utf-8")))
```

```java
String result = httpRequest.execute().body();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这之前是个旧版本的bug，按理说新新版本不存在这个问题。

先保留issue，我稍后测试。

**Comment by looly** [comment]
经过测试，并没有发现有丢失内容的现象，麻烦确认下hutool版本，或提供下你测试的数据内容。

我测试内容如下：

```python
#!/usr/bin/env python
# -*- coding:utf-8 -*-

import tornado.web
import tornado.ioloop
import gzip
 
class IndexHandler(tornado.web.RequestHandler):
 
    def get(self, *args, **kwargs):
        self.set_header("Content-Encoding", "gzip")
        self.write(gzip.compress("""这里我使用后了很长的字符串""".encode("utf-8")))
 
application = tornado.web.Application([
    (r'/index',IndexHandler),
])
 
if __name__ == "__main__":
    application.listen(8080)
    tornado.ioloop.IOLoop.instance().start()
```

Hutool代码如下：

```java
final String s = HttpUtil.get("http://localhost:8080/index");
Console.log(s);
```

**Comment by looly** [comment]
如果问题还有复现，麻烦补充测试用例后再打开此issue。

**Comment by AVAL-NIX** [comment]
我现在重试后确实没有这个问题，可能之前 5.7.8 升级到5.8.20的时候maven没刷新，我也没有观察maven依赖树。也忘记maven clean了。 
给开发组填麻烦了

**Comment by looly** [comment]
@AVAL-NIX 哈哈，你这个issue让我学了一上午tornado

**Comment by AVAL-NIX** [comment]
辛苦了， 我没贴测试数据跟测试代码是因为公司数据比较敏感。 只能贴半截 。 我应该用心点写个demo的。  第一次贴issue，不太熟练。
