### ISSUE TITLE
新版本jwt.getPayload取值时发现原本Integer类型的ID被变成了NumberWithFormat。导致取值出现强转失败

### ISSUE THREAD

**Issue by YuLoving** [looly/hutool#3199]
5.8.20版本：![image](https://github.com/dromara/hutool/assets/45093487/8f98cc49-dab1-4ff9-8ba3-b0a9938e58e8)
5.7.17版本： ![image](https://github.com/dromara/hutool/assets/45093487/ad1f609b-aba3-461d-a193-b2f56820fb64)
发现原本的Integer类型的loginId被初始化为了NumberWithFormat,导致后续int loginId = (int) jwt.getPayload(JwtUtils.LOGIN_ID) 取值强转失败了
![image](https://github.com/dromara/hutool/assets/45093487/0510fe82-9c67-4694-8fc8-f6575ce273e6)
![image](https://github.com/dromara/hutool/assets/45093487/defd8656-b1e6-40c0-ad00-17dc3bc2d8a4)

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/884b9f0d-8221-4546-8b07-b5e9389a43fc)

`NumberWithFormat`继承自`Number`，主要是考虑数字如果超出长度会在int和long之间变化，因此统一采用Number接收。

你可以调用`intValue`获取值。
