### ISSUE TITLE
HttpUtil 应该更全面一点

### ISSUE THREAD

**Issue by Muyv** [looly/hutool#32]
如果能够支持其他 http 方法会更好，另外没有 postString 功能，这个很常用

**Comment by looly** [comment]
1、你可以使用HttpRequest.xxx来创建其它方法的http请求。
2、postString是指请求体全部是字符串？类似于Rest请求？请用HttpRequest对象中的body方法

**Comment by Muyv** [comment]
@looly 
1. 最后是用 HttpRequest.post(url).body(body).execute().body() 来做的
2. 由于很多 Rest 接口都接受 RequestBody 这种方式的请求，比如直接传个字符串或 JSON 结构的字符串，这种接口很常用，所以我的意思是把这种方式在 HttpUtil 里封装一遍，API 路径会短一些

**Comment by looly** [comment]
恩。其实我考虑过针对Rest请求做一个RestUtil，后来并未完成。感谢你的提议。后续版本会考虑加入支持~

**Comment by Muyv** [comment]
nice
