### ISSUE TITLE
Is any idea with List<A> copy to List<B> 

### ISSUE THREAD

**Issue by oldmee** [looly/hutool#3202]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. which method can I do for that like List<A> copy to List<B> ?

**Comment by Createsequence** [comment]
~~~java
// version >= 5.5.2
List<B> listB = CollStreamUtil.toList(listA, a -> BeanUtil.copyProperties(a, new B()));
// version >= 5.6.5
List<B> listB = BeanUtil.copyToList(listA, B.class);
~~~

**Comment by oldmee** [comment]
I know,I need to update my hutool version

**Comment by oldmee** [comment]
> ~~~java
> 
> // version >= 5.5.2
> 
> List<B> listB = CollStreamUtil.toList(listA, a -> BeanUtil.copyProperties(a, new B()));
> 
> // version >= 5.6.5
> 
> List<B> listB = BeanUtil.copyToList(listA, B.class);
> 
> ~~~

I know,I need to update my hutool version
