### ISSUE TITLE
不明白版本5.8.16版本移除BeanUtil.beanToMap(newObj);这个方法的意义在哪？

### ISSUE THREAD

**Issue by swit1983** [looly/hutool#3206]
### 版本情况

JDK版本：    jdk11
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/6257620/3eb01d4e-1768-4d8b-879f-7427a152a5ae)
hutool版本： 5.8.15
![image](https://github.com/dromara/hutool/assets/6257620/34031c96-5679-44f6-8f7a-8e076f1826e2)

不知道为何升级后原来的BeanUtil.beanToMap(newObj)方法报错，找不到此方法。线上包解压出来
![image](https://github.com/dromara/hutool/assets/6257620/67df82eb-4a22-4284-9940-ea4a15b73734)

**Comment by VampireAchao** [comment]
当前版本`5.8.20`
是有这个方法的
![image](https://github.com/dromara/hutool/assets/52746628/25ee7f44-8c5c-4ff1-b77b-48247debca2c)

**Comment by swit1983** [comment]
5.8.16  也有你标记的方法，但是就是报找不到这个方法，重新发布才行，实在太奇怪了
