### ISSUE TITLE
新版本CsvWriter类中相关isAppend追加失效

### ISSUE THREAD

**Issue by YuLoving** [looly/hutool#3207]
最新版本：使用CsvWriter(File file, Charset charset, boolean isAppend)方法追加数据时 发现直接填充到了原本的最后一行 如图
![image](https://github.com/dromara/hutool/assets/45093487/33f388f2-cb29-495c-8576-4f0ea255b329)

红色标记的为 初始数据最后一行。橘色标记的为后续要追加的列表数据。发现直接填充到了初始数据的最后一行
5.7.17版本：
![image](https://github.com/dromara/hutool/assets/45093487/f3574c99-5862-4f21-a05b-9189f89b12c2)
老版本 则没有问题 完全在下一行进行数据的追加填充

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/65cd5701-c6b2-4101-a8c2-9d5b6e42769d)

修改见：https://gitee.com/dromara/hutool/pulls/1010/files

这块默认的，就算isAppend为true，第一次写出都是按照首行对待。首航不加换行符的。

此处存在一个争议点：

情况1：如果源文件末尾有换行符，追加时增加换行符是有问题的。
情况2：如果源文件末尾没有换行符，就是你提问这种情况。

因此考虑兼容两者行为，默认写出首行是不加换行符的。你可以手动调用`writeLine()`方法写出一个空行。
