### ISSUE TITLE
hutool  http工具不支持流式数据返回吗

### ISSUE THREAD

**Issue by wujixialan** [looly/hutool#3208]
hutool  http工具不支持响应式数据返回吗

ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
        WebClient client = WebClient.builder().clientConnector(connector).build();

        Future<Flux<String>> future = ThreadUtil.execAsync(() -> {
            log.info("--------------------------");
            return client.post()
                    .uri(config.getCompletions())
                    .header("Content-Type", "application/json")
                
                    .bodyValue(args)
                    .retrieve()
                    .bodyToFlux(String.class);

例如 spring webflux 这种的吗，流式响应

**Comment by looly** [comment]
HttpRequest可以完成，最后使用`writeTo`方法。
