### ISSUE TITLE
DesensitizedUtil 脱敏工具类中方法 bankCard 脱敏银行卡方法有BUG

### ISSUE THREAD

**Issue by sunny0130** [looly/hutool#3209]
### 版本情况

JDK版本：    Oracle OpenJDK 1.8.0_291
hutool版本： 5.8.20

### 问题描述（包括截图）

在使用` cn.hutool.core.util.DesensitizedUtil `类中的` bankCard `方法时发现有bug
按方法的描述，如果脱敏前的卡号是`1234 2222 3333 4444 6789` ，
那期望脱敏后的结果应该是：`1234 **** **** **** 6789`，
实际输出结果为：`1234 **** **** **** **** 6789`，多了一组 "****"

1. 复现代码

```java
	public static void main(String[] args) {
		String str = "1234 2222 3333 4444 6789";
		System.out.println("脱敏前的数据："+str);
		System.out.println("脱敏后的数据："+bankCard(str));
	}
```

<img width="570" alt="image" src="https://github.com/dromara/hutool/assets/49335596/a36ed863-97f3-4e96-905d-4ffe5915cb93">

2. 个人建议
查看方法源码发现，拿注释中的20位卡号举例，保留前后4位数字中间脱敏，中间应该是 3组“****”，一共12个 “*”，加上4个空格，一共24位，
而作者此处`midLength = length - 8`，midLength = 24-8 = 16，则后续for循环的次数也为16次，而每次都会加上一个“*”，则一共有4组“****”，16个“*”，比预期多出一组，这便是问题的由来。（我发现这个方法作者没有写测试方法，不然应该能发现，所以自测还是很重的，哈哈！）我后面会提交修复的代码，希望有所帮助！
<img width="1175" alt="image" src="https://github.com/dromara/hutool/assets/49335596/88cd2b96-51e8-448c-8f48-05741370a1e5">

**Comment by CherryRum** [comment]
嗯确实有点不规范，这个我最近重构下吧，之前我记得中国人民银行发过建议
1.要注意有核心卡（民生的有9位数的卡号）
http://www.pbc.gov.cn/chubanwu/114566/114579/4356052/4356327/2021100915453743772.pdf

**Comment by sunny0130** [comment]
其实卡号长度很多的话，例如将来有的银行推出8位以内的卡号，我的想法是，按4位一组分隔，大于8位的展示前后4位和最后1-4位，比如：1234 2222 3 --> 1234 **** 3;

**Comment by sunny0130** [comment]
其实如果卡号长度很多，也没有统一规范的话，将来有的银行是不是会可能推出8位以内的卡号？ 所以我的想法是：
1. 按4位一组分隔，大于8位的展示前后4位和最后1-4位，比如：1234 2222 3 --> 1234 **** 3；
2. 4-8位的展示前后各一位，比如：1234 --> 1**4; 1234 5 --> 1*** 5，最低也有两位数的替换，考虑到很多重试限制的，这样也不太容易试出来；
3. 如果小于3位就不处理了，替换一位的话，被试出来的几率就很大了，或者这种直接就全部替换。

**Comment by CherryRum** [comment]
不会的虽然银行卡规范比较乱，但是还是有部分规则的（上面的链接倒数几页有部分推荐规范的）

**Comment by looly** [comment]
@dazer007

**Comment by looly** [comment]
已合并PR~~
