### ISSUE TITLE
能否将 `Log log = LogFactory.get();` 使用类似lombok  @Slf4j注解替代？

### ISSUE THREAD

**Issue by geekxingyun** [looly/hutool#3211]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.2

### 问题描述（包括截图）

如下所示示例：

```java
Log log = LogFactory.get();

log.debug("This is {} log", Level.DEBUG);
log.info("This is {} log", Level.INFO);
log.warn("This is {} log", Level.WARN);

Exception e = new Exception("test Exception");
log.error(e, "This is {} log", Level.ERROR);
```
我们知道，使用hultool 日志门面的一个好处是：

不需要每个日志执行前都加this.isWarnEnabled() 类似代码判断

  if (this.isWarnEnabled()) {
            this.logger.warn(StrUtil.format(format, arguments));
 }

虽然这很好，但是能否将 `Log log = LogFactory.get();` 使用类似lombok  @Slf4j注解替代？

Log log = LogFactory.get();  还是对系统侵入性太大，能否优化下类似lombok 那样使用一个注解生成这种模板代码？

**Comment by looly** [comment]
Hutool没法搞字节码生成，因此这种侵入性注解没法实现。

**Comment by geekxingyun** [comment]
为什么没办法实现呢？
我看了下lombok 的实现，如果使用了@Slf4j 注解，那么生成的编译字节码则是变成了
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Test{
      private static final Logger log = LoggerFactory.getLogger(Test.class);

     public static void main(){
          log.info("test message");
      }
 }
```
不是只需要private static final Logger log = LoggerFactory.getLogger(Test.class); 替换成
Log log = LogFactory.get(); 不就行了？
