### ISSUE TITLE
使用HttpUtil.post发送post请求，如果body中都是放的字符串的话，出现/被自动转义

### ISSUE THREAD

**Issue by javasopp** [looly/hutool#3212]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
String resultString = HttpUtil.post(url, encodeString, 6000);
```
上述的url自定义本地的url，encodeString是加密字符串，其中包含有/，另一端使用以下代码接收
```java
    @PostMapping("/auth")
    public void auth(@RequestBody String encodeString) {
          // 此处打印这个字符串的时候，就会出现，/自动转义成了%2F，但是如果使用接口工具来测试，就不会被自动转义。
    }
```

**Comment by luxx-lq** [comment]
你可以换成图片中的写法
![image](https://github.com/dromara/hutool/assets/58515565/8a7556ef-9c4b-4f32-8c2d-b196fc510eb1)
如果不想修改，我找到了下源码
![image](https://github.com/dromara/hutool/assets/58515565/dc2747fb-9d25-4376-b523-67049ed2e249)
你可以在项目中添加下面的路径把源码复制一份，然后改掉代码
![image](https://github.com/dromara/hutool/assets/58515565/fb3504b7-ba76-4879-ada7-93ccc12717d6)
this.httpConnection.header(Header.CONTENT_TYPE, ContentType.TEXT_PLAIN.toString(this.charset), true);
但我不建议你这么做

**Comment by looly** [comment]
@luxx-lq 正解。使用正确的content-type可以避免不必要的编码。

**Comment by javasopp** [comment]
多谢。
