### ISSUE TITLE
EmojiUtil.containsEmoji() 存在未定义的方法

### ISSUE THREAD

**Issue by gaizi001** [looly/hutool#3216]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20

### 问题描述（包括截图）
EmojiUtil.containsEmoji("这是一个表情")
中的EmojiManager.containsEmoji(str)方法不存在，
![image](https://github.com/dromara/hutool/assets/124646899/6c6d0f13-e624-44d7-b374-4fecd9bc2c93)

1. 复现代码
maven项目，已导入依赖
<dependency>
            <groupId>com.vdurmont</groupId>
            <artifactId>emoji-java</artifactId>
            <version>4.0.0</version>
        </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>5.8.20</version>
            </dependency>

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/124646899/d40eabbd-b77e-4b08-877c-d075efb4d420)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
emoji-java使用5.1.1
