### ISSUE TITLE
建议ListUtil添加一个可重叠分段方法，对集合按照指定的每段长度和每段的可重叠长度分段，每一个段为单独的集合，返回这个集合的列表

### ISSUE THREAD

**Issue by zhoujin7** [looly/hutool#3219]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20

### 问题描述
可重叠分段，对集合按照指定的每段长度和每段的可重叠长度分段，每一个段为单独的集合，返回这个集合的列表<br>
指定的每段长度必须大于每段的可重叠长度，否则则抛出IllegalArgumentException。

<p>例：</p>
<pre>
    ListUtil.overlapPartition(null, 2, 0);	// []
    ListUtil.overlapPartition(Arrays.asList(1, 2, 3, 4, 5), 2, 0);	// [[1, 2], [3, 4], [5]]
    ListUtil.overlapPartition(Arrays.asList(1, 2, 3, 4, 5), 2, 1);	// [[1, 2], [2, 3], [3, 4], [4, 5]]
    ListUtil.overlapPartition(Arrays.asList(1, 2, 3, 4, 5), 3, 2);	// [[1, 2, 3], [2, 3, 4], [3, 4, 5]]
    ListUtil.overlapPartition(Arrays.asList(1, 2, 3, 4, 5), 6, 1);	// [[1, 2, 3, 4, 5]]
</pre>

**Comment by zhoujin7** [comment]
请问pr现在是提交到v5-dev还是v6-dev?

**Comment by looly** [comment]
PR已回复。
