### ISSUE TITLE
建议：对于别名Alias注解能否用在Bean拷贝、Bean转Map等时，可以手动指定是否启用

### ISSUE THREAD

**Issue by CodeHui001** [looly/hutool#3221]
在实际项目中，Bean字段名五花八门的，如果可以手动指定是否启用，一个Bean相当于有了两套属性名，分别对应两个Bean

**Comment by looly** [comment]
嗯……这个注解牵涉的地方比较多，改起来影响较大。不考虑。

**Comment by mr-mihu** [comment]
强烈建议增加这个功能，json和bean会有影响，系统内拷贝和对三方输出json字段不一定一致

**Comment by looly** [comment]
@mr-mihu 我看在6.x中是否分开这个注解。
