### ISSUE TITLE
建议：常量DRIVER_CLICK_HOUSE可否更新为最新ClassName

### ISSUE THREAD

**Issue by hanwei1980** [looly/hutool#3224]
如题：clickhouse的驱动名称已经修改为com.clickhouse.jdbc.ClickHouseDriver，在建立SimpleDataSource的时候，如果不指定driver会报Get jdbc driver [] error!

**Comment by looly** [comment]
考虑到向前兼容性，因此这块没有变更。

6.x已经变更：

![image](https://github.com/dromara/hutool/assets/1432613/88bc3fa9-9916-474d-95c8-04bef620ad85)


5.8.21修改此处。
