### ISSUE TITLE
HttpRequest无法兼容双斜杠路径

### ISSUE THREAD

**Issue by dianbaiyizhong** [looly/hutool#3229]
版本 5.8.20

1. 复现代码

```java
        HttpRequest post = HttpUtil.createPost("http://localhost:2408/user//register");

```

url必须要这么写http://localhost:2408/user/register。不能这么写http://localhost:2408/user//register。。否则就会报404.。我觉得兼容书双斜杠挺好的

**Comment by looly** [comment]
双斜杠不能简单处理为单斜杠。

在某些URL中。`//`是有特殊意义的，是独立的路径。
