### ISSUE TITLE
感觉 hutool 可以加入一个 批量处理队列 工具类

### ISSUE THREAD

**Issue by thousmile** [looly/hutool#3234]
这种 批量队列 挺常用，目前暂未发现有可用的第三方库。
类似于[ Elasticsearch 中 BulkProcessor 。](https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.17/java-docs-bulk-processor.html) 但不能通用

**Comment by looly** [comment]
我想这个不应该由工具支撑，而由特定数据框架支撑哦~~
