### ISSUE TITLE
增加响应浏览器文件下载功能

### ISSUE THREAD

**Issue by FULaBUla** [looly/hutool#3237]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

能否封装一个将服务器文件通过浏览器进行下载的实现

像这个链接里写的方法：https://blog.csdn.net/sfhappy23/article/details/116119240?utm_source=miniapp_weixin

**Comment by looly** [comment]
不太懂你的意思。你要客户端还是服务端：

客户端使用HttpDownloader

服务端使用`SimpleServer`

**Comment by FULaBUla** [comment]
> 不太懂你的意思。你要客户端还是服务端：
> 
> 客户端使用HttpDownloader
> 
> 服务端使用`SimpleServer`

都不是，我是作为 web 服务端，响应浏览器的文件下载请求，响应下载的地方没有封装，有参考的代码就是我上面发的链接里的，希望能把那个实现做个封装

**Comment by looly** [comment]
@FULaBUla 
Hutool 不参与任意框架的绑定，也没有Spring这些封装。

如果你直接使用Servlet，则使用`ServletUtil.write`即可：

![image](https://github.com/dromara/hutool/assets/1432613/28f6df63-45e1-4110-a9a5-d0b6ea20c08e)
