### ISSUE TITLE
文件监听

### ISSUE THREAD

**Issue by wzxkk** [looly/hutool#3239]
文件监听多次重复触发，没达到效果

**Comment by wzxkk** [comment]
![image](https://github.com/dromara/hutool/assets/22493253/7af6f660-d704-4dbc-a646-0e7e620bea67)

**Comment by looly** [comment]
确实存在这个问题，但是这是JDK监听机制造成的。

你可以使用`DelayWatcher`增加一些延迟来 规避这个问题。
