### ISSUE TITLE
V6,httputil 会使用的httpclient4 会出现400错误，切换到okhttp/jdk都没有问题了

### ISSUE THREAD

**Issue by VirensCn** [looly/hutool#3240]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 6.0.0.M5

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可否提供请求测试链接？

**Comment by VirensCn** [comment]
使用httpclient4   
![image](https://github.com/dromara/hutool/assets/9736815/c8a152da-cf9f-4453-8bb1-c2a3bc9b512c)

使用okhttp
![image](https://github.com/dromara/hutool/assets/9736815/7d88c6b0-abd8-4b3a-bbd2-dbe614907d8f)

使用JDK
![image](https://github.com/dromara/hutool/assets/9736815/514117c4-2c71-46fb-a899-cbf7d1be2e49)


依赖（httpclient部分）
![image](https://github.com/dromara/hutool/assets/9736815/55957e8a-258f-409a-aab6-73e7f4045c38)

**Comment by VirensCn** [comment]
这个请求地址是onenet私有化地址。

这就很奇怪，测试发现，如果认证参数错了返回值就会是200，，参数都正确的时候就会出现400。。如果请求其他的接口也是正常的。

目前就只能先将这个项目的httpclient禁用掉。。

**Comment by looly** [comment]
@VirensCn 嗯……确实很奇怪，因为私有地址我这边没法测试复现。

有时间麻烦单独使用原生的HttpClient4测试下看是否会出现400，如果不出现，贴下代码，我这边对比差异。

暂时我先关闭issue，测试后再打开此issue。~~

**Comment by VirensCn** [comment]
经过测试，使用原生的httpclient就会不会出现这个错误:请求结果(符合预期), httpclient部分实现代码

![image](https://github.com/dromara/hutool/assets/9736815/936583ce-02c4-484c-9c2e-208346866152)

```java
		try {
			// 构建请求URL建造器----------------------------------------------------------------------
			UrlBuilder urlBuilder = UrlBuilder.of(server + request.url());
			request.reqForm().forEach(urlBuilder::addQuery);

			//      1、创建HttpClient对象
			CloseableHttpClient httpClient = HttpClients.createDefault();

			//      2、创建请求方式的实例
			HttpRequestBase httpPost;

			if (Method.POST.equals(request.method())) {
				httpPost = new HttpPost();
			} else {
				httpPost = new HttpGet();
			}

			httpPost.setURI(urlBuilder.toURI());

			httpPost.setHeader(HeaderName.CONTENT_TYPE.getValue(), ContentType.APPLICATION_JSON.getMimeType());
			httpPost.setHeader(HeaderName.AUTHORIZATION.getValue(), Assert.isEmpty(auth));
			request.reqHeader().forEach((k, v) -> {
				httpPost.setHeader(k, v);
			});

			//      3、添加请求参数(设置请求和传输超时时间)
			httpPost.setConfig(RequestConfig.custom().setSocketTimeout(60000).setConnectTimeout(60000).build());

			if (request != null && httpPost instanceof HttpPost hp) {
				hp.setEntity(new StringEntity(request.reqBodyStr()));
			}

			//      4、发送Http请求
			HttpResponse response = httpClient.execute(httpPost);

			//      5、获取返回的内容
			String results = null;

			int statusCode = response.getStatusLine().getStatusCode();

			if (200 == statusCode) {
				results = EntityUtils.toString(response.getEntity());
			} else {
				logger.info("请求第三方接口出现错误，状态码为:{}", statusCode);
				return null;
			}

			//      6、释放资源
			httpPost.abort();

			// 并判定响应结果-------------------------------------------------------------------------
			JSONObject result = JSON.parseObject(results);
			if (result == null || result.isEmpty()) {
				throw new APIException("响应为空");
			}

			return request.toResponse(result);
		} catch (Exception e) {
		}
```

**Comment by VirensCn** [comment]
如果采用hutool里面的httpclient 请求`https://gh.yubue.cn/https://github.com/espressif/arduino-esp32/releases/download/2.0.11/package_esp32_dev_index.json` (github加速连接任意地址都会出现这个错误)这个地址，也会出现报错.

响应结果如下：
```
cfworker error:
TypeError: Request with a GET or HEAD method cannot have a body.
    at proxy (worker.js:154:23)
    at httpHandler (worker.js:144:12)
    at fetchHandler (worker.js:87:16)
    at worker.js:58:17
```
![image](https://github.com/dromara/hutool/assets/9736815/3671d861-b81d-4419-9f2b-041a3490544c)

如果是使用原生的httpclient 就不会出现问题
![image](https://github.com/dromara/hutool/assets/9736815/5dd56f25-d590-414e-8c32-2b6126678652)

**Comment by VirensCn** [comment]
如果使用okhttp进行请求会出现乱码: 还是上面那个地址

![image](https://github.com/dromara/hutool/assets/9736815/db2b4595-3c30-4263-94c9-24dfa8b42c88)


httpclient也会默认开启keepAlive，用来扒数据的时候很容易被拦截。需要手动关闭keepAlive。。
只有使用JDK的才是最稳的

**Comment by looly** [comment]
@VirensCn 十分感谢提供的公开链接，问题出在这里：

![image](https://github.com/dromara/hutool/assets/1432613/a15b2c23-43d3-4c6c-8aae-48c4f0d1257e)

如果没有请求体，body为null，就不应该构建请求体，这里有问题。

6.0.0-M6修复此问题，等发布或者下载源码编译尝试！
