### ISSUE TITLE
通过ImgUtil.toBase64转换图片得到的Base64字符串相对于其他方式更长, 转换时间也更长

### ISSUE THREAD

**Issue by zoooooway** [looly/hutool#3244]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20

### 问题描述
如下代码，测试图片的大小是2.04MB，第一种方式是使用commons-io进行转换，速度很快而且结果字符串长度正常，第二种方式使用`ImgUtil.toBase64`进行转换，速度很慢而且结果大了十倍。

1. 复现代码

```java
String img = "H:\\temp\\test\\1.png";
byte[] fileContent = FileUtils.readFileToByteArray(new File(img));
String encodedString = Base64.getEncoder().encodeToString(fileContent);
System.out.println(encodedString.length()); // 2867180

String base64 = ImgUtil.toBase64(ImgUtil.read(img), ImgUtil.IMAGE_TYPE_PNG);
System.out.println(base64.length());  // 33966140
```
稍微debug后发现问题在读取图片转换为字节数组这里，这时候转换出的数组就已经很大了。将图片转换为字节数组再进行Base64编码后，字符串长度正常： 
```java
String img = "H:\\temp\\test\\1.png";
String encode = Base64.encode(FileUtil.readBytes(img));
System.out.println(encode.length()); // 2867180
```
希望能修改一下`ImgUtil.toBase64`这个方法，或是在方法上给出相关说明。

**Comment by looly** [comment]
这两个方法有本质区别。

既然你想把文件内容转换为Base64，就应该使用`Base64.encode(FileUtil.readBytes(img));`，这是不区分任何文件格式的。

ImgUtil则是转换Image对象，这其中涉及到了一些可能的转换，如png转jpg，自动添加背景颜色等。应用功能不同。

**Comment by zoooooway** [comment]
@looly  了解了，但还是希望方法上能给出一些相关提示，不然可能会像我一样，因为是进行图片文件的转换，自然而然的就使用ImgUtil类下的相关方法了

> 这两个方法有本质区别。
> 
> 既然你想把文件内容转换为Base64，就应该使用`Base64.encode(FileUtil.readBytes(img));`，这是不区分任何文件格式的。
> 
> ImgUtil则是转换Image对象，这其中涉及到了一些可能的转换，如png转jpg，自动添加背景颜色等。应用功能不同。

**Comment by looly** [comment]
后续做一些注释补充
