### ISSUE TITLE
SqlUtil.formatSql 格式化的sql换行异常

### ISSUE THREAD

**Issue by LeonemZhang** [looly/hutool#3246]
### 版本情况

JDK版本：    oracle jdk_8_281
hutool版本： 5.8.17.M1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![image](https://github.com/dromara/hutool/assets/50519058/d7d69853-2455-43f1-b8ef-24e8f34bfcef)

![image](https://github.com/dromara/hutool/assets/50519058/2ccfa00b-7ee8-42bc-bcb5-d1ec1dde7b16)

![image](https://github.com/dromara/hutool/assets/50519058/727f7f3a-2722-4e26-9761-8b215f71f5f1)
没有处理反引号，导致关键字与对象名判断错误

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/3247
