### ISSUE TITLE
parseUTC 这个方法无法格式化负时区（半小时的）

### ISSUE THREAD

**Issue by pigzhuzhu55** [looly/hutool#3248]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20

### 问题描述（包括截图）
https://github.com/dromara/hutool/blob/v5-master/hutool-core/src/main/java/cn/hutool/core/date/DateUtil.java

这个类的这个方法

public static DateTime parseUTC(String utcString) {

的这行代码

else if(ReUtil.contains("-\\d{2}:?00", utcString)){

无法格式化，负的半小时的时区

比如
2023-08-04T06:17:47-03:30

1. 复现代码

```java
DateUtil.parseUTC("")
```

**Comment by looly** [comment]
半小时的时区符合规范么？现在只支持整时区的……

**Comment by pigzhuzhu55** [comment]
没办法，公司QA提的bug，有  -3：30  的；+03:30：伊朗标准时间。等

**Comment by looly** [comment]
@pigzhuzhu55 这类特殊情况，考虑自行构建DataFormatter对象了。
