### ISSUE TITLE
增加响应浏览器的文件下载请求的实现封装

### ISSUE THREAD

**Issue by FULaBUla** [looly/hutool#3249]
希望仿照像这个链接里写的方法：https://blog.csdn.net/sfhappy23/article/details/116119240  做一个封装
目前，我作为 web 服务端，响应浏览器的文件下载请求，响应下载的地方没有封装，需要自己写把文件放到 response 的返回流中，有参考的代码就是我上面发的链接里的，希望能把那个实现做个封装

相关 #3237

**Comment by looly** [comment]
重复：https://github.com/dromara/hutool/issues/3237
