### ISSUE TITLE
剪贴板的监听已经测试,效果很棒,推荐加入更友好的使用方式

### ISSUE THREAD

**Issue by z231485** [looly/hutool#325]
如
ClipboardUtil.Strlistener(String str)  return str  
ClipboardUtil.Strlistener(Image img) return image
让用户可以只关心对监听数据的处理, 而无需了解 Transferable的使用
另外
考虑下有没有必要加入
1. 可选择为守护线程
2. 默认为非阻塞式
一般这个监听方法都是用在gui层面, 阻塞会造成界面卡死, 
而非守护线程模式下. 退出gui界面时, 此监听方法仍在运作

**Comment by looly** [comment]
可选sync参数是非阻塞的。

ClipboardMonitor实现了Runnable接口，可以直接线程运行。
