### ISSUE TITLE
JSON转字符串精度丢失

### ISSUE THREAD

**Issue by AmuseBoy** [looly/hutool#3250]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.2

### 问题描述（包括截图）

1. 复现代码
        A a = new A();
        a.setRedInvoicePrice(new BigDecimal("0.00"));
        System.out.println(JSON.toJSONString(a));
        System.out.println(JSONUtil.toJsonStr(a));

{"redInvoicePrice":0.00}
{"redInvoicePrice":0}

**Comment by AmuseBoy** [comment]
fastjson 的正常

**Comment by looly** [comment]
见：JSONConfig.setStripTrailingZeros
