### ISSUE TITLE
Hutool API文档说明优化建议

### ISSUE THREAD

**Issue by lzb-libra** [looly/hutool#3251]
您好，我是重度hutool的使用者，会经常结合参考文档+api文档的方式查询使用，希望在api文明中增加一个小小的建议，就是每个工具类里的每个方法加一个该方法时那个版本引入的显示。谢谢

**Comment by looly** [comment]
一般会有`@Since`

**Comment by lzb-libra** [comment]
我后来找到了这个标识，但是我有一点不明白的是listUtil下有个partition这个方法，看`@since`是5.4.5版本加上的，但是我项目引入hutool-all的5.4.6版本，我在使用listUtil竟然找不到该方法。
![QQ截图20230807184128](https://github.com/dromara/hutool/assets/63389341/52060490-4893-46d3-8290-eeefbfa3f3bc)
![QQ截图20230807184058](https://github.com/dromara/hutool/assets/63389341/40530481-6fbc-4db9-a46f-03b76fba48de)
![QQ截图20230807184221](https://github.com/dromara/hutool/assets/63389341/e1d1156d-cab2-4791-901d-0985cde5e817)
