### ISSUE TITLE
无法正确识别Smb网络存储的路径

### ISSUE THREAD

**Issue by loprx** [looly/hutool#3253]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码
似乎不兼容这种Smb的地址，我在使用ZipUtil时发现会把Smb地址解析为相对路径，测试过后发现FileUtil也是有问题的
可否对文件操作做个兼容呢~
```java
// 使用Hutool
System.out.println(FileUtil.exist("\\\\10.1.72.29\\1689171669748826112.zip"));

// 使用Jdk1.8提供的java.nio.file包
System.out.println(Files.exists(Paths.get("\\\\10.1.72.29\\1689171669748826112.zip")));
```
执行结果
```
false
true
```
2. 堆栈信息
无

3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
是滴。不支持smb格式。

原因是File中会调用`normalize`方法，转换`\`为`/`，因此不支持。

考虑JDK原生方法。

5.8.22修正这块逻辑，smb格式不做处理。

**Comment by loprx** [comment]
好的，感谢~
