### ISSUE TITLE
TreeUtil构建树时 当子节点和父节点id相同时 会丢失分支

### ISSUE THREAD

**Issue by deep12398** [looly/hutool#3254]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
当杭州市的id和浙江省的id相同时  会导致浙江省节点及子树都打印不出来
![image](https://github.com/dromara/hutool/assets/45665890/7736e828-74e3-4e0f-88a4-6e73c387de6b)

源码中map.put时进行了去重
![image](https://github.com/dromara/hutool/assets/45665890/f161b6a2-a927-471a-b022-29e0bc885ed2)

1. 复现代码

```java
public static void main(String[] args) {
        List<TreeNode<Integer>> nodeList = CollUtil.newArrayList();

        //省市区的树形结构
        nodeList.add(new TreeNode<>(1, 0, "浙江省", 0));
        nodeList.add(new TreeNode<>(1, 1, "杭州市", 0));
        nodeList.add(new TreeNode<>(111, 11, "余杭区", 0));
        nodeList.add(new TreeNode<>(112, 11, "西湖区", 0));
        nodeList.add(new TreeNode<>(113, 11, "拱墅区", 0));
        nodeList.add(new TreeNode<>(2, 0, "山东省", 0));
        nodeList.add(new TreeNode<>(22, 2, "泰安市", 0));
        nodeList.add(new TreeNode<>(222, 22, "泰山区", 0));
        Tree<Integer> tree = cn.hutool.core.lang.tree.TreeUtil.buildSingle(nodeList);

        System.out.println(tree.toString());
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by Createsequence** [comment]
我觉得这是合理的，节点的 id 应该是全局唯一的，如果一个父节点的 ID 实际上对应了多个父节点，那么岂不是变成图了？

如果你希望构建由多个树构成的森林，那么可以考虑使用 `ForestMap`，否则建议还是提供一个公共的根节点，把它们合并为一颗树。

**Comment by deep12398** [comment]
> 我觉得这是合理的，节点的 id 应该是全局唯一的，如果一个父节点的 ID 实际上对应了多个父节点，那么岂不是变成图了？
> 明白了  如果在示例中 有一个节点的parent_id为1 就不是一棵树了 
> 如果你希望构建由多个树构成的森林，那么可以考虑使用 `ForestMap`，否则建议还是提供一个公共的根节点，把它们合并为一课树。
