### ISSUE TITLE
有没有一个方法 我传一个实体类参数 就可以生成insert update delete等sql语句的？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#3255]
有没有一个方法 我传一个实体类参数 就可以生成insert update delete等sql语句的？

要的是完整的可执行的sql语句

**Comment by joey-happy** [comment]
直接实体类中的具体字段值也都填充好了

**Comment by looly** [comment]
这个没有。不过你可以借助ActiveEntity完成。
