### ISSUE TITLE
mail.setting中的参数能否支持从配置文件中读取？

### ISSUE THREAD

**Issue by FHICDI** [looly/hutool#3257]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.17（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
场景：测试环境和生产环境发短信的邮箱不应该是同一个。

1. 复现代码
![image](https://github.com/dromara/hutool/assets/50192332/acd86758-17be-455e-98d5-64546f535d13)

![image](https://github.com/dromara/hutool/assets/50192332/2e92505f-1f73-406b-a0c8-53da7a262086)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不支持，除非你自行构建Setting对象，可以从Spring中读取。
