### ISSUE TITLE
Request默认请求头优化

### ISSUE THREAD

**Issue by kings1990** [looly/hutool#3258]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
HttpUtil.createRequest创建Request对象的时候会塞入一些默认请求头，最终会在代码GlobalHeaders.putDefault中放入一个头Header.ACCEPT_LANGUAGE。这个头放入不合理应该去除，因为用户可能会使用这个头搞点国际化的逻辑。而且Postman默认请求头里面也没用放入这个。

![image](https://github.com/dromara/hutool/assets/8969637/5ac1798e-88b0-4ce8-99c0-914e81c2b736)

**Comment by looly** [comment]
5.8.22 6.0.0-M6 去除这个默认头
