### ISSUE TITLE
sm2解密有千分之几的错误，报异常java.lang.IllegalArgumentException: Invalid point coordinates

### ISSUE THREAD

**Issue by pym15970914014** [looly/hutool#3262]
### 版本情况
```xml
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-crypto</artifactId>
    <version>5.8.10</version>
</dependency>
```

模式：后端生成秘钥对，公钥给前端进行加密，后端解密
前端使用的js库是https://github.com/JuneAndGreen/sm-crypto
加密模式是前端也是 C1C3C2

在测试时发现
解密会出现千分之4左右的错误率，异常信息

###生成密钥对
```java
SM2 sm2 = SmUtil.sm2();
sm2.usePlainEncoding();
// 生成私钥D
String privateKeyD = HexUtil.encodeHexStr(BCUtil.encodeECPrivateKey(sm2.getPrivateKey()));
log.info("私钥D: {}", privateKeyD);

// 生成公钥Q，以q值做为js端的加密公钥
String publicKeyQ = HexUtil.encodeHexStr(((BCECPublicKey) sm2.getPublicKey()).getQ().getEncoded(false));
log.info("公钥Q: {}", publicKeyQ);
```

###解密
```java
SmUtil.sm2(privateKey, null)
                .decryptStr(data, KeyType.PrivateKey)
```

###异常信息
```java
java.lang.IllegalArgumentException: Invalid point coordinates
	at org.bouncycastle.math.ec.ECCurve.validatePoint(ECCurve.java:125)
	at org.bouncycastle.math.ec.ECCurve.decodePoint(ECCurve.java:420)
	at org.bouncycastle.crypto.engines.SM2Engine.decrypt(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.processBlock(Unknown Source)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:299)
	at cn.hutool.crypto.asymmetric.SM2.decrypt(SM2.java:282)
```

按照其他博客信息，比如公钥和密文前面加04  私钥面前加00也都未解决，求大佬解惑

**Comment by looly** [comment]
sorry……这个我真解决不了，Hutool封装的BC库的SM2算法，无法确定这个概率问题出在哪里……

**Comment by CherryRum** [comment]
这个你最好给个复现的 公钥和私钥，不然没法查证的，
这个报错就是告诉你，你的密钥的两个坐标点，不在sm2的椭圆曲线上

**Comment by pym15970914014** [comment]
解决了，直接密文前面加04，不加判断，全部密文都加04，测试了100W数据解密全部正常

**Comment by CherryRum** [comment]
嗯呢，那就是某些密文没封装标识，不太科学呀
![CleanShot 2023-08-17 at 18 25 34@2x](https://github.com/dromara/hutool/assets/24296698/75915a50-969f-4f62-ae99-fea7a132e801)
https://www.cnblogs.com/lylhqy/p/15693757.html 具体可以看看这个

**Comment by dingjs** [comment]
这个问题原因是：
1. [sm-crypto](https://github.com/JuneAndGreen/sm-crypto) 这个框架生成的是不带04前缀的; 而 `bc` 解密时会需要04前缀，参见`org.bouncycastle.math.ec.ECPoint`
2. 你原来的处理是判断有没有04前缀，有就不加，没有就加，有有4‰出错的概率。原因猜测是有时候密文生成的前两位刚就好是04，你就没加前缀，导致把密文的04被误识别为前缀04，这个在你的用例里刚好是4‰ 。

问题核心是 `sm-crypto` 和 hutool 用到的 `bc` 对于公钥是否压缩（带04前缀）的处理方式不一样。至于谁是合理的，需要再看一下sm2相关规范，凭经验判断 hutool 使用的 bc 是合理的。

**Comment by looly** [comment]
关联参考：https://github.com/JuneAndGreen/sm-crypto/issues/72

**Comment by dingjs** [comment]
再啰嗦一句，sm2加密后返回的是16制串，每个char都是0-9，a-f 这16个中的一个，两个char是16*16 = 256， 出现04的概率就是1/256,刚好4‰

**Comment by studeyang** [comment]
@dingjs 感谢水哥解惑，技术道路早已充满你的足迹😊

**Comment by dingjs** [comment]
> [@dingjs](https://github.com/dingjs) 感谢水哥解惑，技术道路早已充满你的足迹😊

有用就行，互相交流，人人为我，我为人人。
感谢hutool
