### ISSUE TITLE
DateUtil.parse("13时30分20秒")报错

### ISSUE THREAD

**Issue by Lishuoyy** [looly/hutool#3263]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码
String dateStr = "13时30分20秒";
Date date = DateUtil.parse(dateStr);
System.out.println(date);

2. 堆栈信息
Exception in thread "main" cn.hutool.core.date.DateException: No format fit for date String [13时30分20] !
at cn.hutool.core.date.DateUtil.parse(DateUtil.java:1027)
at test.main(test.java:19)

**Comment by Lishuoyy** [comment]
String dateStr = "13时30分20秒";
Date date = DateUtil.parse(dateStr,"HH时mm分ss秒");
System.out.println(date);
还有，上面这行代码输出年份为什么是1970-01-01 13:30:20

**Comment by ZZemptypoint** [comment]
:sweat_smile: 
第一段代码异常信息很明确，你这个格式不是hutool默认支持的时间格式，所以需要你传入自定义格式。
第二段代码，是因为你并没指明年月日，所以jdk的`DateFormat.parse()`自动给了默认的起始日期：
```
DateFormat is an abstract class for date/time formatting subclasses which formats and parses dates or time in a language-independent manner. The date/time formatting subclass, such as SimpleDateFormat, allows for formatting (i.e., date → text), parsing (text → date), and normalization. The date is represented as a Date object or as the milliseconds since January 1, 1970, 00:00:00 GMT.
```
