### ISSUE TITLE
使用了HttpRequest的executeAsync，返回的HttpResponse的isAsync仍然是false

### ISSUE THREAD

**Issue by GingerNg** [looly/hutool#3264]
### 版本情况

JDK版本：    openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
hutool版本： 5.8.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.http.HttpException;
import cn.hutool.http.HttpRequest;
import cn.hutool.http.HttpResponse;

public class HttpRequestDemo {
    public static void main(String[] args) {
        String url = "http://localhost:8081";
        HttpResponse response = HttpRequest.get(url).executeAsync();
        if (false == response.isOk()) {
        throw new HttpException("Server response error with status code: [{}]", response.getStatus());
        }else{
            System.out.println(response.body());
        }
    }
}
```

2. 堆栈信息: 无

3. 测试涉及到的文件（注意脱密）
<img width="1174" alt="image" src="https://github.com/dromara/hutool/assets/13898738/8a3b8fd6-c80b-4c6b-b948-bb92fc6636a1">

**Comment by looly** [comment]
当调用body方法时，需要同步拉取响应内容，自然就变成false了。

你可以把response.body()去掉试下。

**Comment by GingerNg** [comment]
截图是断点打到11行的情况，那时候还没有执行response.body()
