### ISSUE TITLE
关于MailUtil的使用

### ISSUE THREAD

**Issue by jwf1173** [looly/hutool#327]
MailUtil在设置了account账号信息后，当在网页动态调整账号信息时，发送邮件却还是用的原来的配置，必须重启服务器才会重新生效，账号信息是从数据库获取的
![image](https://user-images.githubusercontent.com/31645649/56179408-38ddb600-6038-11e9-9184-46d3dd2439f7.png)
![image](https://user-images.githubusercontent.com/31645649/56179568-bef9fc80-6038-11e9-83f2-684c0d0dde96.png)

**Comment by looly** [comment]
是动态构建的MailAccount么？如果是，每次调用send的时候，需要指定新的MailAccount。

**Comment by DengSinkiang** [comment]
请问怎么解决的

**Comment by DengSinkiang** [comment]
> 是动态构建的MailAccount么？如果是，每次调用send的时候，需要指定新的MailAccount。

请问怎么解决，同样遇到这个问题

**Comment by DengSinkiang** [comment]
> 是动态构建的MailAccount么？如果是，每次调用send的时候，需要指定新的MailAccount。



> MailUtil在设置了account账号信息后，当在网页动态调整账号信息时，发送邮件却还是用的原来的配置，必须重启服务器才会重新生效，账号信息是从数据库获取的
> ![image](https://user-images.githubusercontent.com/31645649/56179408-38ddb600-6038-11e9-9184-46d3dd2439f7.png)
> ![image](https://user-images.githubusercontent.com/31645649/56179568-bef9fc80-6038-11e9-83f2-684c0d0dde96.png)

你是怎么解决的
