### ISSUE TITLE
slf4j在1.6.0以后已经支持打印参数化的异常日志

### ISSUE THREAD

**Issue by yu2014ol** [looly/hutool#3270]
即
```java
String s = "Hello world";
try {
  Integer i = Integer.valueOf(s);
} catch (NumberFormatException e) {
  logger.error("Failed to format {}", s, e);
}
````
需要把异常作为最后一个参数
官方FAQ：https://www.slf4j.org/faq.html#paramException

**Comment by looly** [comment]
嗯……这个不影响任何使用吧？这个和Hutool有啥关系么？

**Comment by looly** [comment]
Hutool为了减少异常对象和可变长参数的区分，保持异常对象在前，我觉更加合理。

**Comment by yu2014ol** [comment]
> 

嗯嗯，不影响使用，不过因为日志类库的文档里有提到slf4j不支持打印参数化的异常日志，所以就提醒一下，文档可以看情况要不要更新一下

**Comment by looly** [comment]
@yu2014ol 哈哈，谢谢提醒，这个需要更新下。
