### ISSUE TITLE
JSONUtils 无法解析record类

### ISSUE THREAD

**Issue by 0xiaoyu** [looly/hutool#3271]
### 版本情况

JDK版本：    openjdk_17
hutool版本：5.8.15

**Comment by CherryRum** [comment]
暂时5.x不会考虑解决这个问题，
原因在于，jdk8想要实现这jdk14的关键词绕不开字节码(ASM)
可以先考虑这个使用已有的其他开源库

**Comment by looly** [comment]
6.x支持。可以先用6.0.0-M5

**Comment by 0xiaoyu** [comment]
好的

**Comment by 0xiaoyu** [comment]
谢谢
