### ISSUE TITLE
jsonConvert  json2bean 忽略异常后返回null

### ISSUE THREAD

**Issue by geshijie123** [looly/hutool#3274]
### 版本情况

JDK版本：    openjdk_1.8.0_301 
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码

```
import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;

class LarkCoreHrServiceTest {
    public static void main(String[] args) {
        JSONObject entries = new JSONObject("{\n" +
                "    \n" +
                "    \"age\": 36,\n" +
                "    \"gender\": {\n" +
                "        \"display\": [\n" +
                "            {\n" +
                "                \"lang\": \"zh-CN\",\n" +
                "                \"value\": \"男\"\n" +
                "            },\n" +
                "            {\n" +
                "                \"lang\": \"en-US\",\n" +
                "                \"value\": \"Male\"\n" +
                "            }\n" +
                "        ],\n" +
                "        \"enum_name\": \"male\"\n" +
                "    },\n" +
                "    \"id\": \"123123123\"\n" +
                "}");
        //已配置忽略异常
        LarkCoreHrPersonal larkCoreHrPersonal = JSONUtil.toBean(entries, LarkCoreHrPersonal.class,true);
        // 5.8.5版本正常可以转换部分字段，  5.8.16  5.8.21 版本无法正常忽略枚举转换异常 造成对象返回为null
        System.out.println("报错了");
        System.out.println(larkCoreHrPersonal==null);
    }
}

@Data
@NoArgsConstructor
@AllArgsConstructor
 class LarkCoreHrPersonal {
    private String id;
    private String age="";
    private Gender gender;
}

@Getter
 enum Gender {
    male("male","Male","男"),
    female("female","Female","女"),
    other("other","Other","其他");
    private JSONArray display;
    private  String enum_name;
    private Gender(String enum_name,String en_Us,String zh_CN){
        this.enum_name=enum_name;
        this.display=new JSONArray("[{\"lang\": \"en-US\",\"value\": \""+en_Us+"\"},{\"lang\": \"zh-CN\",\"value\": \""+zh_CN+"\"}]");
    }
}
```

2. 堆栈信息
暂无

5.8.5 与 5.8.21 执行结果不同
![image](https://github.com/dromara/hutool/assets/35256516/b0db4990-2552-40b8-a470-fc2dcbdbedf2)
![image](https://github.com/dromara/hutool/assets/35256516/eae3d9b9-d595-45bd-8518-dc0c1b85656a)

期望可以正常转换部分字段，不是忽略异常然返回null

**Comment by ZZemptypoint** [comment]
确实是bug，你可以暂时先使用`entries.toString()`来绕过这个bug。
```java
        //已配置忽略异常
        LarkCoreHrPersonal larkCoreHrPersonal = JSONUtil.toBean(entries.toString(), LarkCoreHrPersonal.class, true);
```

**Comment by looly** [comment]
@ZZemptypoint 可以找到bug点么？来个PR？

**Comment by lzwcyd** [comment]
cn.hutool.json.JSONUtil#toBean(java.lang.String, java.lang.reflect.Type, boolean)与cn.hutool.json.JSONUtil#toBean(cn.hutool.json.JSON, java.lang.reflect.Type, boolean)
在构造json的时候存在差异，构造出来的json对象的JSONConfig存在差异
前者
![image](https://github.com/dromara/hutool/assets/56526731/6a3b9302-6367-4e02-977c-29cb44a4e0a4)
后者
![image](https://github.com/dromara/hutool/assets/56526731/4271fed8-fb98-4d4a-bad9-5dcf1cce822c)

后者在执行
cn.hutool.core.convert.impl.BeanConverter#convertInternal的第90行BeanCopier.create(value, ReflectUtil.newInstanceIfPossible(this.beanClass), this.beanType, this.copyOptions).copy()会报错

**Comment by lzwcyd** [comment]
> cn.hutool.json.JSONUtil#toBean(java.lang.String, java.lang.reflect.Type, boolean)与cn.hutool.json.JSONUtil#toBean(cn.hutool.json.JSON, java.lang.reflect.Type, boolean) 在构造json的时候存在差异，构造出来的json对象的JSONConfig存在差异 前者 ![image](https://user-images.githubusercontent.com/56526731/263975387-6a3b9302-6367-4e02-977c-29cb44a4e0a4.png) 后者 ![image](https://user-images.githubusercontent.com/56526731/263975410-4271fed8-fb98-4d4a-bad9-5dcf1cce822c.png)
> 
> 后者在执行 cn.hutool.core.convert.impl.BeanConverter#convertInternal的第90行BeanCopier.create(value, ReflectUtil.newInstanceIfPossible(this.beanClass), this.beanType, this.copyOptions).copy()会报错

刚刚的回复是不准确的，

cn.hutool.core.bean.copier.CopyOptions#converter
第89行，反射调用的时候丢失了ignoreError，导致报错

![image](https://github.com/dromara/hutool/assets/56526731/3b5571ea-30f7-4a09-b95e-4e3e4b9939a4)

稍后我提一个PR

**Comment by looly** [comment]
事实上这个是5.x参数混乱造成的。

你可以：

```java
final JSONObject entries = new JSONObject("{\n" +
			"    \n" +
			"    \"age\": 36,\n" +
			"    \"gender\": \"\",\n" +
			"    \"id\": \"123123123\"\n" +
			"}", JSONConfig.create().setIgnoreError(true));
```

**Comment by lzwcyd** [comment]
我个人觉得还是工具类里面将ignoreError在转换的过程中漏掉导致的，你下面已经传入ignoreError，传入两次是不合理的 ---- 回复的原邮件 ----发件人Golden ***@***.***>发送日期2023年08月30日 22:51 ***@***.***> ***@***.***>***@***.***>主题Re: [dromara/hutool] jsonConvert  json2bean 忽略异常后返回null (Issue #3274)
事实上这个是5.x参数混乱造成的。
你可以：
final JSONObject entries = new JSONObject("{\n" +
			"    \n" +
			"    \"age\": 36,\n" +
			"    \"gender\": \"\",\n" +
			"    \"id\": \"123123123\"\n" +
			"}", JSONConfig.create().setIgnoreError(true));

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dromara/hutool/issues/3274#issuecomment-1699333284",
"url": "https://github.com/dromara/hutool/issues/3274#issuecomment-1699333284",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lzwcyd** [comment]
> JSONUtil.to



如果是这样做的话，这第三个参数就没有意义啊，既然靠设置json本身的属性就没有必要再传入ignoreError，而且这个是一个工具类的方法，传入了ignoreError但是会存在概率转换成为null值，让人觉得有点奇怪，不符合预期
cn.hutool.json.JSONUtil#toBean(cn.hutool.json.JSON, java.lang.reflect.Type, boolean)

**Comment by looly** [comment]
@lzwcyd 所以说这个是5.x的设计缺陷。6.x会彻底修复。
