### ISSUE TITLE
HttpUtil.post(url, params)当params中有List集合时会引发bug

### ISSUE THREAD

**Issue by lvgitt** [looly/hutool#328]
对参数值为list的情况，直接把参数值转成了如图这种格式
![image](https://user-images.githubusercontent.com/44693144/56253831-aea55880-60f0-11e9-9140-f46de441690c.png)

我不清楚正确的是要转为标准[{"key1","val1"}]格式还是["{key1=val1}"]格式
总之似乎是少了一对"[]"

测试demo
![image](https://user-images.githubusercontent.com/44693144/56253843-c250bf00-60f0-11e9-93cf-262334579c56.png)

`public static void main(String[] args) {
        HashMap<String, Object> params = new HashMap<>();
        params.put("key1","val1");

        ArrayList<Map<String, Object>> listParam = new ArrayList<>();

        HashMap<String, Object> inListMap1 = new HashMap<>();
        inListMap1.put("listKey1","listVal1");
        listParam.add(inListMap1);

        params.put("list",listParam);

        HttpUtil.post("www.baidu.com",params);

    }`

**Comment by lvgitt** [comment]
参照
<dependency>
	<groupId>com.taobao.top</groupId>
	<artifactId>taobao-sdk</artifactId>
	<version>2.0.3</version>
</dependency>
中WebUtils.doPost(url, params,"UTF-8",50000, 120000,headerMap);方法

**Comment by looly** [comment]
此处你应该调用List本身的toString方法，而非join。

**Comment by lvgitt** [comment]
第一张图是hutool工具类中的源码，我这边只能从外层改，直接把List转成String，再调用post方法

**Comment by looly** [comment]
我明白了。这个是默认行为。

考虑自己手动把List转为String传参吧。
