### ISSUE TITLE
Validator 类可以提供更丰富些的校验么?

### ISSUE THREAD

**Issue by mrxlh** [looly/hutool#3280]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
可以参照这个项目
https://github.com/validatorjs/validator.js/tree/master
提供更丰富的校验么？
比如 基于ipv4 段的校验 等

**Comment by looly** [comment]
可以考虑。我先看下。

**Comment by l7810** [comment]
![image](https://github.com/dromara/hutool/assets/12392453/7928d58f-f77f-4ce0-b68f-243818ea19b6)

如下图示例：
`
/**
     * 检查指定值是否非.<br/>
     * 抛出 RuntimeException 类型异常.
     * @param value            待校验的参数.
     * @param runtimeException 检查不满足条件抛出的运行期异常.
     * @param <T>              被检查的对象类型.
     * @return 检查过后的值.
     */
    public static <T> T validateNotNull(T value, RuntimeException runtimeException) {
        if (isNull(value)) {
            throw runtimeException;
        }
        return value;
    }

    /**
     * 检查指定值是否非.<br/>
     * 抛出 自定义类型的异常.
     * @param value             待校验的值.
     * @param exceptionSupplier 检查不满足条件抛出的运行期异常.
     * @param <T>               待校验的参数.
     * @param <X>               Throwable的子类型.
     * @return 检查过后的值.
     * @throws X Throwable的子类.
     */
    public static <T, X extends Throwable> T validateNotNull(T value, Supplier<? extends X> exceptionSupplier) throws X {
        if (isNull(value)) {
            throw exceptionSupplier.get();
        }
        return value;
    }
`
此类中，其他方法，诸如validateNotEmpty，同样增加类似方法，
这样， Validator 类会变得更加通用，封装度也更高，实用性更强。

**Comment by looly** [comment]
@mrxlh 看了参考中的方法，大部分校验都可以通过正则完成，因此不考虑再封装。
