### ISSUE TITLE
StrUtil.toCamelCase 字符串转驼峰原有的大写转成小写了

### ISSUE THREAD

**Issue by Cooperter** [looly/hutool#3281]
### 版本情况

JDK版本：    Oracle 1.8.0_321
hutool版本： 5.8.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
如果字符串中有驼峰格式，转换时会把大写的字母转成小写

1. 复现代码

```java
System.out.println(StrUtil.toCamelCase("tabs_customReport"));

输出 TabsCustomreport
```

**Comment by winlans** [comment]
这个就是代码的默认行为， 如果你想达到你想要的效果，可以用这个`NamingCase.toCamelCase("tabs_customReport", '_', false);`
