### ISSUE TITLE
NumberUtil.equals(long, long)对equals的引用不明确

### ISSUE THREAD

**Issue by luger1990** [looly/hutool#3282]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.21（目前的最新版）

### 问题描述（包括截图）

1. 复现代码

```java
Long a = 1L;
System.out.println(NumberUtil.equals(a, 1L));
```

这段代码编译的时候提示：
cn.hutool.core.util.NumberUtil 中的方法 equals(long,long) 和 cn.hutool.core.util.NumberUtil 中的方法 equals(java.lang.Number,java.lang.Number) 都匹配

**Comment by looly** [comment]
@luger1990 确实存在此类问题，所以在6.x中彻底解决这类歧义方法。
