### ISSUE TITLE
 fillColumns 方法没有判断 column 为空的情况直接空指针

### ISSUE THREAD

**Issue by bestK** [looly/hutool#3284]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新版

### 问题描述（包括截图）

fillColumns 方法没有判断 column 为空的情况直接空指针

![image](https://github.com/dromara/hutool/assets/14979305/092b4c39-8ddb-462e-b7a2-1d7f9c73a821)

1. 复现代码

```java
 ConsoleTable t = ConsoleTable.create();
  t.addHeader("姓名", "年龄");
  t.addBody("张三", "15");
  t.addBody("李四", "29");
  t.addBody("王二麻子", null); //👈这里
  t.print();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.22修复，感谢。
