### ISSUE TITLE
有没有截取视频第一帧为图片的方法？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#3287]
有没有截取视频第一帧为图片的方法？

**Comment by CherryRum** [comment]
我理解您的需求，对于提取首帧的任务，我建议您使用`FFmpeg`。与`Hutool`不同，`FFmpeg`提供了视频流解码功能。另外，您还需要区分`P帧`、`B帧`和`I帧`。

其次这个建议您使用点播服务自动完成
