### ISSUE TITLE
CollectionUtil.split()存在歧义结果

### ISSUE THREAD

**Issue by Zcr-907** [looly/hutool#3292]
### 版本情况

JDK版本：    openjdk_8_218
hutool版本： 4.5.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        List<Object> emptyList = Collections.emptyList();
        List<List<Object>> split = CollectionUtil.split(emptyList, 1);
        // split.size()==1,当对一个空集合进行split时，split.size()不应该等于0吗？
        System.out.println(split.size());
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你的版本太旧了，更新到5.8.21此处bug或者逻辑已经修改：

![image](https://github.com/dromara/hutool/assets/1432613/30b459d9-9fbb-450b-8694-d9e5f1e6fdbc)
