### ISSUE TITLE
ReUtil 匹配数字字符串范围 寻求帮助

### ISSUE THREAD

**Issue by artillerymans** [looly/hutool#3295]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
场景 输入框内 限制输入的数字大小范围限制  假设 7-776 亦或者其他的数字范围
根据3个参数 minStr maxStr valueStr 判断valueStr是否在minStr与maxStr范围内

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
ReUtil没法匹配数字范围，只能先转为数字，然后判断。
