### ISSUE TITLE
JSONUtil 性能瓶颈

### ISSUE THREAD

**Issue by kuaile1993** [looly/hutool#3297]
### 版本情况

JDK版本：   jdk8
hutool版本： 5.4.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JSONUtil 有同步代码块，有重大的性能瓶颈，开发喜欢用JSONUtil  打印日志，写在拦截器里，一个很简单的代码，导致cpu100%，GC 异常，一个看起来不可能存在问题的代码出问题了。
![image](https://github.com/dromara/hutool/assets/52553619/4962cfac-b40d-4988-9ef7-d6722f32035c)
![image](https://github.com/dromara/hutool/assets/52553619/5b7fbb08-bd14-4add-80cf-6cdca5edbaea)

删除此段代码后业务正常
![image](https://github.com/dromara/hutool/assets/52553619/f1e2afea-6f24-43b0-8148-356265659b68)

**Comment by looly** [comment]
嗯，此段来自于json-lib。

貌似确实没有什么必要。

不过我在想，`synchronized (sw.getBuffer())`中的锁来自于sw.getBuffer()，所有人调用此方法的锁对象都是不一样的，应该是不冲突的，不知道为何会导致CPU使用率很高。

盲猜同步块检查锁的逻辑占用了大量CPU资源，这块5.8.22修改，感谢。
