### ISSUE TITLE
Python实现结果集不同

### ISSUE THREAD

**Issue by xiangchao886** [looly/hutool#3298]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

hutool 包的加解密的实现方式，参照着源码，想用python做出实现，但在同一文本，秘钥(16-bit)，IV(8-bit)情况下，得到的结果集始终与java的不一致，Crypto.Cipher 的DES、DES3试过还是不行

**Comment by looly** [comment]
哪个加密解密？

检查Mode和Padding是否一致。
