### ISSUE TITLE
HttpRequest.get(url).form(params).execute().body(); 方法传参有误

### ISSUE THREAD

**Issue by lvgitt** [looly/hutool#3306]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 复现代码

```java
@AllArgsConstructor
@NoArgsConstructor
@Builder
@lombok.Data
public class TencentFiltering {
    /**
     * 过滤字段
     */
    private String field;
    /**
     * 操作符
     */
    private String operator;
    /**
     * 字段取值
     */
    private String[] values;
}

@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
@lombok.Data
public class TencentPageQueryReq {
    /**
     * 推广帐号 id，有操作权限的帐号 id，包括代理商和广告主帐号 id
     */
    private Long accountId;
    /**
     * 过滤条件，若此字段不传，或传空则视为无限制条件
     */
    private List<TencentFiltering> filtering;
    /**
     * 搜索页码，默认值：1
     */
    private Integer page;
    /**
     * 一页显示的数据条数，默认值：10
     */
    private Integer pageSize;
}
// 实际报错代码 start
Map<String, Object> params = BeanUtil.beanToMap(tencentPageQueryReq, true, true);
// url 随便填也能浮现问题
// 请debug到cn.hutool.http.HttpRequest#urlWithParamIfGet方法，发现最后拼接的地址是“https://api.e.qq.com/v1.3/conversions/get?access_token=f4fd445dcadbdbe048f4244b0dae&nonce=5de1xyik70l6ama3okzkrao9dvid9spy&timestamp=1694592747&account_id=31657200&
// filtering=TencentFiltering(field=conversion_name, operator=CONTAINS, values=[啊啊啊啊])&page=1&page_size=10 ”

        String res = HttpRequest.get(url)
                .form(params).execute().body();
// 实际报错代码end
```
2. 堆栈信息
通过以上代码进行get请求时，发现get请求中的filtering参数值把对象的toString结果传过去了，实际上的filtering值应为[{"field":"conversion_name","operator":"CONTAINS","values":["啊啊啊啊"]}]

**Comment by lvgitt** [comment]
![image](https://github.com/dromara/hutool/assets/44693144/dcbbeb6b-779e-46f9-844f-3f503617cd38)
![image](https://github.com/dromara/hutool/assets/44693144/80412b58-0530-47ef-aef1-18a77c45bebc)
同样的数据，经过JSON转化后和经过form后的结果不一样

**Comment by lvgitt** [comment]
![image](https://github.com/dromara/hutool/assets/44693144/ea4e1848-9040-43e9-8b8d-6f1bb8c34725)
这一行List对象转化有问题

**Comment by lvgitt** [comment]
![image](https://github.com/dromara/hutool/assets/44693144/51b53120-9c7d-4726-8d7d-349f4e9415df)

`
String str = "[{\"field\":\"conversion_name\",\"operator\":\"CONTAINS\",\"values\":[\"啊啊啊啊\"]}]";
		List<TencentFiltering> tencentFilterings = JSON.parseArray(str, TencentFiltering.class);

		Object value = tencentFilterings;
		System.out.println(CollUtil.join((Iterable) value, ","));
		// TencentFiltering(field=conversion_name, operator=CONTAINS, values=[啊啊啊啊])
`

**Comment by lvgitt** [comment]
在cn.hutool.http.HttpRequest#form(java.lang.String, java.lang.Object)：228行代码上面添加如下两行代码或可解决问题：
List<JSONObject> list = Convert.toList(JSONObject.class, value);
		Object value = list;

**Comment by looly** [comment]
@lvgitt 当然了。Hutool的http模块不会自动转换你的JSON对象，需要你手动调用JSONUil.toString完成。

Object对象转JSON只是你的业务要求是JSON，那如果服务端要求传XML咋办？Hutool不可能帮助用户选择格式，只能默认调用toString。

**Comment by lvgitt** [comment]
![image](https://github.com/dromara/hutool/assets/44693144/8df456a6-6e2c-4bb8-8c9e-7c01425615b2)
我传进去JSONArray,转成toString后不应该是[{}]结构吗？怎么变成{}了？
