### ISSUE TITLE
CollUtil#join(java.lang.Iterable<T>, java.lang.CharSequence) 转换JSON数组对象时格式错误，导致丢失中括号

### ISSUE THREAD

**Issue by lvgitt** [looly/hutool#3307]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22

### 问题描述
![image](https://github.com/dromara/hutool/assets/44693144/4d7aa241-235c-41d3-88ff-2f96dbb25047)
我传进去JSONArray,转成toString后不应该是[{}]结构吗？怎么变成{}了？

1. 复现代码

```java
  Map map1 = JSON.parseObject("{\"account_id\":31657200,\"filtering\":[{\"field\":\"conversion_name\",\"operator\":\"CONTAINS\",\"values\":\"啊啊啊啊\"}],\"page\":1,\"page_size\":10}", Map.class);
        String res = HttpRequest.get(url)
                .form(map1).execute().body();
```

**Comment by looly** [comment]
@lvgitt 可以看逻辑。filtering的值是个JSONArray，经过CollUtil.join之后就是{}, {}这种形式。

此处传入JSON不应该使用form方法，这个方法只是处理简单键值对，值并不是简单调用toString，而是集合拼接方式，请自行处理值。
