### ISSUE TITLE
CglibUtil.copy()报错，本地OracleJDK没问题，服务器OpenJDK报错

### ISSUE THREAD

**Issue by luckbyte** [looly/hutool#3311]
### 版本情况

JDK版本：openjdk version "1.8.0_312"
hutool版本： 5.8.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![image](https://github.com/dromara/hutool/assets/28799116/c14081f5-8d09-4eee-84c0-36a5d318189d)

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/28799116/da8acd20-c84d-413d-b94f-b657ae256155)

**Comment by looly** [comment]
cglib不兼容JDK高版本（可能JDK9+？）

考虑使用Spring-cglib。

**Comment by luckbyte** [comment]
![image](https://github.com/dromara/hutool/assets/28799116/2c56a21c-6f8c-4837-92de-791c96108d1c)
那这个版本应该是多少?
我使用的JDK是1.8

**Comment by looly** [comment]
@darrenxyue 哪个也没用。cglib现在只支持到jdk8，如果服务端高于这个版本就有问题。

**Comment by luckbyte** [comment]
@looly 服务器和本地都是用的**jdk1.8**,只是本地用的**Oracle JDK**, **服务器用的 openjdk version "1.8.0_312"**

**Comment by looly** [comment]
那不应该啊，检查是否引入多个版本的cglib了。

**Comment by luckbyte** [comment]
> 那不应该啊，检查是否引入多个版本的cglib了。

没有，我本地去掉自己引入的cglib后就不能用了，说明没有引入其他版本的cglib
