### ISSUE TITLE
CglibUtil.copy()报错，JDK1.8，使用spring-cglib报错：java.lang.NoClassDefFoundError: net/sf/cglib/beans/BeanCopier

### ISSUE THREAD

**Issue by luckbyte** [looly/hutool#3312]
### 版本情况

JDK版本：openjdk version "1.8.0_312"
hutool版本： 5.8.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

![image](https://github.com/dromara/hutool/assets/28799116/c14081f5-8d09-4eee-84c0-36a5d318189d)

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/28799116/da8acd20-c84d-413d-b94f-b657ae256155)

**Comment by luckbyte** [comment]
![image](https://github.com/dromara/hutool/assets/28799116/c739f153-ef50-4582-9b3e-e25b7ab2a832)
官网上这里的版本应该是多少？

**Comment by looly** [comment]
Hutool不支持Spring-cglib库，只有6.x才改用这个库。

我意思是你用它，就不要用Hutool封装的方法了。直接使用cglib原生库方法即可。
