### ISSUE TITLE
请教一下，如何使用HttpUtil上传文件二进制，在body中

### ISSUE THREAD

**Issue by Mengleijin** [looly/hutool#3313]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22（请确保最新尝试是否还有问题）

### 问题描述
postman调用截图
![image](https://github.com/dromara/hutool/assets/28032070/e92f0a06-6337-43c6-989e-61abd0812fdc)

请问：如果使用HttpUtil应该如何实现？

**Comment by looly** [comment]
调用body方法。

![image](https://github.com/dromara/hutool/assets/1432613/edc323a9-3e8d-4330-b8ad-83d60c40bcc0)

**Comment by Mengleijin** [comment]
@looly 多谢，昨天也是这么写的发现没有成功，最后发现不是这一块代码的问题~
