### ISSUE TITLE
HttpRequest 如何调用请求方法是GET，参数是List的接口

### ISSUE THREAD

**Issue by 10veU** [looly/hutool#3317]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用HttpRequest如何调用下面的接口
1. 复现代码
```java
@GetMapping(value="/test")
public String test(@RequestBody List<String> ids){
    System.out.println(ids.toString);
}
```

**Comment by looly** [comment]
HttpRequest.get().setRest(true).body("[a,b,c,d]")
