### ISSUE TITLE
文档丢失

### ISSUE THREAD

**Issue by lhDream** [looly/hutool#3319]
大量文档都丢了
![image](https://github.com/dromara/hutool/assets/41568266/8320325f-1093-4d80-bdcb-686f7635ed12)
![image](https://github.com/dromara/hutool/assets/41568266/590afbab-15f5-422a-a4e6-aa837e737771)

**Comment by looly** [comment]
https://doc.hutool.cn/pages/MailUtil/

**Comment by looly** [comment]
https://hutool.cn/docs/#/extra/%E9%82%AE%E4%BB%B6%E5%B7%A5%E5%85%B7-MailUtil

sorry，之前迁移的时候乱码了。
