### ISSUE TITLE
Validator.isCitizenId() 低版本误判

### ISSUE THREAD

**Issue by workxie** [looly/hutool#3320]
### 版本情况
hutool-all(5.3.2)
hutool-core(5.8.18),

#### 需要用到core包里面Validator.isCitizenId()方法，
hutool-all中的判断会出现误判，特殊企业信用代码，全数字的
如果项目中同时引用了这两个，优先使用高版本的吗

**Comment by looly** [comment]
并不是。多版本同时存在会造成版本冲突，问题很难排查。

建议统一版本。
