### ISSUE TITLE
hu，可以增加httpRequest解析吗？

### ISSUE THREAD

**Issue by windpoiuytr** [looly/hutool#3321]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
GET www.baidu.com HTTP/1.1
Host: www.baidu.com
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
sec-ch-ua-mobile: ?0

可以增加http请求报文解析吗？虽然我可以循环split，但我需要一个更高效的方法，或者在SDK内新增此方法能够更方便的调用。

**Comment by looly** [comment]
嗯……应该是没有split那么简单。这个没有实现，考虑第三方库。
