### ISSUE TITLE
Shift-JIS编码特殊字符写入CSV被写成问号

### ISSUE THREAD

**Issue by yymjku18** [looly/hutool#3323]
### 版本情况

JDK版本：    jdk1.8.0_351
hutool版本： 5.7.10

### 问题描述（包括截图）
做日语报表，用Shift-JIS格式写入CSV数据，一些特殊符号被写成问号
1. 复现代码

```java
        // 指定 CSV 文件路径
        String filePath = "output.csv";
        // 创建 CsvWriter 并指定 Shift-JIS 字符编码
        CsvWriter csvWriter = new CsvWriter(filePath, Charset.forName("Shift-JIS"), true);
        // 创建包含特殊字符的数据行
        String specialData = "特殊字符：※☆㈱";
        String[] rowData = {specialData};
        char[] charArray = specialData.toCharArray();
        // 写入数据行
        csvWriter.write(rowData);
        // 关闭 CsvWriter
        csvWriter.close();
        System.out.println("CSV 文件已成功写入。");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
[output.csv](https://github.com/dromara/hutool/files/12826434/output.csv)
![image](https://github.com/dromara/hutool/assets/77368194/6f71bf39-3db5-47c4-9df0-0a14db33593d)

**Comment by ZZemptypoint** [comment]
这个特殊字符似乎不在`Shift-JIS`字符集中，我换成`GBK`都能正常输出到文件中。
[shift_jis码表](https://uic.jp/charset/show/shift_jis/)

**Comment by looly** [comment]
这个字符集可能缺失部分字符，导致乱码，就像GB2312确实部分字一样。

**Comment by yymjku18** [comment]
@looly @ZZemptypoint 
非常感谢各位帮助，该问题与hutool无关。
经过查阅日本计算机发展史，shift-jis也有很多版本，㈱不存在于ShiftJIS基础版本而是存在于一些扩展版本里，
将字符集改为Windows-31J(Shift-JIS的一个扩展版本)问题得到解决。
