### ISSUE TITLE
RuntimeUtil 执行 exec 单命令不能识别linux shell中的管道“|”符号。

### ISSUE THREAD

**Issue by admin233** [looly/hutool#3325]
### 版本情况

JDK版本：    openjdk_8_271
hutool版本： 5.8.X (所有版本)

### 问题描述（包括截图）

Hutool封装了JDK的Process类，用于执行命令行命令（在Windows下是cmd，在Linux下是shell命令）。

命令行工具-RuntimeUtil

RuntimeUtil 执行 exec 单命令不能识别linux shell中的管道“|”符号。目前依靠多命令执行包含管道的组合命令。
替代方案:RuntimeUtil.execForStr("/bin/sh","-c","top -b -n1 | head -n57");希望不用此方法执行包含管道的单条linux shell.

1. 复现代码

```java
RuntimeUtil.execForStr("top -b -n1 | head -n57");
```

2. 堆栈信息
报错,无法识别 "|" 符号

5. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
嗯……这个貌似是JDK内部实现机制的问题。

Hutool无法判定用户传入的命令执行的环境，因此，具体是调用cmd、还是shell还是sh，都是不确定的，需要用户自定义。

考虑试下：

```java
RuntimeUtil.execForStr("/bin/sh -c top -b -n1 | head -n57");
```
