### ISSUE TITLE
中文文档错别字偏多

### ISSUE THREAD

**Issue by MrFeng1993** [looly/hutool#3328]
### 问题描述
查看hutool-http相关官方中文文档的时候，才看了一眼就发现两处错别字。要不我加入维护？
![image](https://github.com/dromara/hutool/assets/33375434/d19affa7-7fd1-48fe-bf28-3d63c011cc06)

**Comment by VampireAchao** [comment]
很需要！可以提交pr到https://gitee.com/loolly_admin/hutool-site
