### ISSUE TITLE
有没有快速获得HttpServletReqeust的方法

### ISSUE THREAD

**Issue by xxyz30** [looly/hutool#3333]
springboot框架，方法没有传入`HttpServletReqeust`

想在方法内部拿到request对象，但代码太长

例如 https://www.jianshu.com/p/6e32e89b64ce

能否添加至`SpringUtil`或者`SpringMvcUtil`之类的地方？

**Comment by looly** [comment]
Spring MVC没有封装工具。考虑自行封装哦。
