### ISSUE TITLE
httprequest访问带gzip的接口会无响应

### ISSUE THREAD

**Issue by H-TWINKLE** [looly/hutool#3336]
debug成功拿到了响应，但是在inputstream.read时候刚开始能够while拿到数据，然后就卡死拿不到数据了

开发环境决定无法贴图

**Comment by H-TWINKLE** [comment]
如果请求接口拿到的响应body小，不会卡死，会正常返回，当body体量变大就会卡死

**Comment by looly** [comment]
卡死是会一直卡死么？

怀疑是：

1. 文件太大，压缩解压过程较长

尝试：

使用HttpClient看是否出问题。

后续结果请再打开此issue。
