### ISSUE TITLE
希望扩展MapUtil

### ISSUE THREAD

**Issue by 2406450951** [looly/hutool#3340]
### 版本情况

JDK版本：    openjdk_8_203
hutool版本：5.18.22

>  演示代码

目前。Oracle查询结果列名默认为大写。但是根据我这边研发规范，接口响应结果应为小写+驼峰。
```
public static void main(String[] args) {
Map<String, Object> map = new HashMap<>();
map.put("ID","1");
map.put("NAME","2");
map.put("STU_ID","3");
Map<String, Object> map1 = MapUtil.toCamelCaseMap(map);

System.out.println(map1.toString());
//{stuId=3, ID=1, NAME=2}
}
```

**MapUtil希望重载toCamelCaseMap方法，增加是否将Key转为小写或大写。**
或MapUtil增加将String类型Key转小写或大写方法，
例如：
```
public static void main(String[] args) {
Map<String, Object> map1 = new HashMap<>();
map1.put("ID","1");
map1.put("NAME","2");
map1.put("STU_ID","3");
Map<String, Object> map2 = new HashMap<>();
map1.forEach((k,v)->{
map2.put(k.toLowerCase(),v);
});
Map<String, Object> mapData = MapUtil.toCamelCaseMap(map2);
System.out.println(mapData.toString());
//{stuId=3, name=2, id=1}
}
```

**Comment by looly** [comment]
这里的逻辑问题出在`StrUtil.toCamelCase`方法。

其中有个参数`otherCharToLower`。

现有版本中这个参数只判断了带有连接符的字符串，只对带有连接符的字符串做了处理。

为了考虑兼容性，这块不做修改，考虑自行重写`CamelCaseMap`。


6.0.0-M8修改此处逻辑，逻辑如下：

当otherCharToLower为true时：

1. 如果给定字符串全部为大写，转换为小写，如NAME转为name。
2. 如果给定字符串大小写混合，认定为字符串已经是驼峰模式，只小写首字母，如TableName转换为tableName。
