### ISSUE TITLE
能不能增加阿拉伯数字转为中文大写的工具类啊

### ISSUE THREAD

**Issue by ancienter** [looly/hutool#3342]
### 需求建议

能不能增加阿拉伯数字转为中文大写的工具类啊

**Comment by looly** [comment]
https://doc.hutool.cn/pages/Convert/#%E6%95%B0%E5%AD%97%E8%BD%AC%E6%8D%A2

**Comment by JTongChen** [comment]
请问？为什么小数只能保留两位呢

**Comment by JTongChen** [comment]
> https://doc.hutool.cn/pages/Convert/#%E6%95%B0%E5%AD%97%E8%BD%AC%E6%8D%A2

请问为什么小数只能保留两位呢

**Comment by looly** [comment]
@JTongChen 这个主要用于金额转换，保留到分。
