### ISSUE TITLE
使用JDK 17, linux部署项目，加密报错

### ISSUE THREAD

**Issue by ANGLIOK** [looly/hutool#3345]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

直接部署出现的异常是：
User java.lang.SecurityException: JCE cannot authenticate the provider BC

然后我看Issues， 配置 Java.security 和 引入 bcprov-jdkxx-xxx.jar 到 jre/lib/ext  都试了。一样没有效果

后来 我看到有人评论 使用 SecureUtil.disableBouncyCastle(); 关闭BC

关闭后的异常 Caused by: java.security.NoSuchAlgorithmException: SM4 KeyGenerator not available

请教这个有什么办法能解决吗

**Comment by CherryRum** [comment]
建议您更换`OpenJDK`
原因在于`OracleJDK`验证了加密签名，而打包的过程破坏了验证BC库的签名。
