### ISSUE TITLE
ImgUtil的sliceByRowsAndCols切割透明背景的png似乎无论如何不能保持背景透明

### ISSUE THREAD

**Issue by crazysvn** [looly/hutool#3347]
### 版本情况

JDK版本：    javaSE-1.8
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
ImgUtil的sliceByRowsAndCols切割透明背景的png似乎无论如何不能保持背景透明

**Comment by looly** [comment]
5.8.23
6.0.0-M8

修复此问题，感谢~~
