### ISSUE TITLE
中文日期格式化问题

### ISSUE THREAD

**Issue by airclear** [looly/hutool#3348]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.x 5.8.x 都有

### 问题描述（包括截图）

1. 复现代码

```java
String formatChineseDate = DateUtil.formatChineseDate(new Date(), true, false);
Console.log(formatChineseDate);
```
2. 输出： 二〇二三年`一十`月二十三日   期望：二〇二三年十月二十三日

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/875ea743-a0c7-43a0-a8d3-55538e65041d)

请升级到5.8.23测试。
