### ISSUE TITLE
hutool-all5.8.6 版本在使用BeanUtil.toBean性能很差

### ISSUE THREAD

**Issue by zhaofei1193** [looly/hutool#3351]
通过对比hutool-all5.8.6 版本和hutool-all5.7.22 版本的BeanUtil.toBean，发现hutool-all5.8.6的性能很差，请问需要升级到哪个版本能解决？

**Comment by looly** [comment]
这块应该是一直没变，都是使用反射方式。

尝试升级到5.8.22试下看是否改善。

**Comment by ZZemptypoint** [comment]
可以考虑使用`CglibUtil`封装的方法。
