### ISSUE TITLE
RegexPool.EMAIL 邮箱正则不支持大写？

### ISSUE THREAD

**Issue by jansse-zhao** [looly/hutool#3352]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
RegexPool.EMAIL 邮箱正则不支持大写？后端接收到的email还需要转小写在校验吗？

1. 复现代码

```java
Zdd@163.com @Validated校验异常
```

**Comment by looly** [comment]
见PatternPool

![image](https://github.com/dromara/hutool/assets/1432613/4525040f-4c7a-4730-ab60-be274c1c2128)
