### ISSUE TITLE
cn.hutool.core.io.FileUtil#loopFiles(java.lang.String) 方法对于入参 path 为软链接时无法获取指定连接下的文件。

### ISSUE THREAD

**Issue by OnceNever** [looly/hutool#3353]
### 版本情况

JDK版本：    openjdk_8_311
hutool版本： 5.8.22

### 问题描述（包括截图）
最新版本hutool使用loopFiles方法，对于入参path为软链接时无法获取到预期路径下的文件。

1. 复现代码
![image](https://github.com/dromara/hutool/assets/57511377/32647003-035a-4276-b74e-6a74aee13c28)

2. 输出日志
![image](https://github.com/dromara/hutool/assets/57511377/febbdbbe-8866-44cd-a069-41220134a16c)

**Comment by looly** [comment]
默认不追踪软链的。

考虑加个重载方法。

**Comment by looly** [comment]
5.8.23
6.0.0-M8

增加重载：

![image](https://github.com/dromara/hutool/assets/1432613/e2d13fc5-c1fe-486e-ae30-8e135ed97c5b)
