### ISSUE TITLE
使用请教: 文件名 name.txt 如何移除里面的非法字符？

### ISSUE THREAD

**Issue by gMan1990** [looly/hutool#3354]
有哪个方法里写了吗?

比如 我命名 `aa:bb.txt` 总是不行的吧，得移除`:` 变为 `aabb.txt`

**Comment by ZZemptypoint** [comment]
这是windows文件系统的限制，有些符号是不可以出现在文件名里的。

![1698221891035](https://github.com/dromara/hutool/assets/28431269/3d5d16af-a961-4bb8-abdd-7c8d04f5f894)

**Comment by looly** [comment]
考虑正则去除吧。
