### ISSUE TITLE
布隆过滤器如何使用

### ISSUE THREAD

**Issue by liu-xinhui** [looly/hutool#3356]
### 版本情况
5.8.22

看文档，不知道如何确定m值。我如果想实现10w数据，错误率为0.01，m值填多少合适呢？
```
BitMapBloomFilter filter = new BitMapBloomFilter(10);
```

**Comment by CherryRum** [comment]
$$m=- \frac {n \ln {p}} {(\ln {2})^2}$$
预估的数据量`n`
错误率`p`
所以如下
<img width="538" alt="image" src="https://github.com/dromara/hutool/assets/24296698/9e410aff-ee7d-48ab-b5fa-b28642f30714">

**Comment by gujunhui** [comment]
请问版本用的是5.8.8，用958506，会报错Caused by: java.lang.NegativeArraySizeException: -1289486336
