### ISSUE TITLE
文件监听WatchMonitor新建文件夹在新建文件新建的文件将不会被监听到

### ISSUE THREAD

**Issue by 1999LP** [looly/hutool#3357]
### 版本情况

JDK版本：    openjdk_1.8_201
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
文件监听-WatchMonitor

WatchMonitor.createAll(file, new SimpleWatcher(){
	@Override
	public void onModify(WatchEvent<?> event, Path currentPath) {
		Console.log("EVENT modify");
	}
}).setMaxDepth(3).start();

原有文件夹下新建文件会监听到没问题，如果新建文件夹在新建文件 新建的文件将不会被监听到

**Comment by ZZemptypoint** [comment]
确实是有这个问题。
`hutool`是封装和扩展了`jdk`提供的文件监听组件，`jdk`原生的文件监听只支持`1层`文件夹的监听。
要实现这个功能，需要`Watcher`持有`WatchMonitor`，这是不太合理的。

如果你需要实现这个功能，可以考虑这样写：

```java
        WatchMonitor monitor = WatchMonitor.createAll(file, null);
        Watcher watcher = new SimpleWatcher() {
            @Override
            public void onCreate(WatchEvent<?> event, Path currentPath) {
                Object obj = event.context();
                if (obj instanceof Path) {
                    Path p = (Path) obj;
                    final File newfile = new File(currentPath.toString() + "/" + p);
                    if (FileUtil.isDirectory(newfile)) {
                        // 给新的目录注册监听
                        monitor.registerPath(newfile.toPath(), 2);
                    }
                }
                Console.log("创建：{}-> {}", currentPath, obj);
            }
        };
        monitor.setWatcher(watcher);

        monitor.setMaxDepth(3);
        monitor.start();
```

**Comment by looly** [comment]
@ZZemptypoint 只能给你个NB

**Comment by zhengwangwang** [comment]
@ZZemptypoint 如果目录不停的创建子目录，同时也会删除一些子目录，比如hls直播流的存储目录是按照小时拆分目录的，不停的创建新的存储目录，也会删除一些过早的目录，这样不停的注册路径监控，被删除掉的子目录没有回收watchKey，而且代码中用到了private final Map<WatchKey, Path> watchKeyPathMap = new HashMap<>();缓存WatchKey和path， 这样没有回收机制岂不是内存泄露了，watchKeyPathMap会不停变大。

**Comment by 357656763** [comment]
@zhengwangwang @1999LP 大佬们你们是怎么解决的
