### ISSUE TITLE
Failing tests in hutool-core

### ISSUE THREAD

**Issue by yesh385** [looly/hutool#3359]
### Version status

JDK version: 1.8.0_202

### Problem description

Tests fail in hutool-core module

1. Copy code
```
mvn -pl hutool-core test
```
<img width="1440" alt="Screenshot 2023-10-28 at 1 17 03 PM" src="https://github.com/dromara/hutool/assets/112648152/ec39d633-649a-4cdb-900e-a3ac9641e034">

2. Stack information

Failed tests:   parseCSTTest(cn.hutool.core.date.DateUtilTest): expected:<2009-09-16 11:26:23> but was:<2009-09-16 12:26:23>
  formatAndParseCustomTest(cn.hutool.core.date.DateUtilTest): expected:<1488[2976]00> but was:<1488[3480]00>
  formatBetweenTest(cn.hutool.core.date.DateUtilTest): expected:<31天[1小时]21分> but was:<31天[]21分>
  dateTest2(cn.hutool.core.date.DateUtilTest): expected:<1969-12-1[5 0]0:00:00> but was:<1969-12-1[4 1]0:00:00>
  formatHttpDateTest(cn.hutool.core.date.DateUtilTest): expected:<[Wed, 02 Jan 2019 1]4:32:01 GMT> but was:<[Thu, 03 Jan 2019 0]4:32:01 GMT>
  toInstantTest(cn.hutool.core.date.DateUtilTest): expected:<2017-05-06T[00]:30:00Z> but was:<2017-05-06T[13]:30:00Z>
  betweenTest(cn.hutool.core.date.DateUtilTest): expected:<745> but was:<744>
  formatAndParseCustomTest2(cn.hutool.core.date.DateUtilTest): expected:<1488[2976]00000> but was:<1488[3480]00000>
  betweenDayTest(cn.hutool.core.date.DateUtilTest): expected:<1480> but was:<1479>
  getChineseMonthTest(cn.hutool.core.date.ChineseDateTest): expected:<2020-08-0[4] 00:00:00> but was:<2020-08-0[3] 00:00:00>
  getGregorianDateTest(cn.hutool.core.date.ChineseDateTest): expected:<1998-06-2[4] 00:00:00> but was:<1998-06-2[3] 00:00:00>
  getCyclicalYMDTest2(cn.hutool.core.date.GanzhiTest): expected:<壬申年癸丑月[丁亥]日> but was:<壬申年癸丑月[丙戌]日>
  parseUTCTest(cn.hutool.core.date.Issue2981Test): expected:<1546272000000> but was:<1546322400000>
  formatCustomTest(cn.hutool.core.date.TemporalAccessorUtilTest): expected:<16246[368]00> but was:<16246[836]00>
  chineseDateTest(cn.hutool.core.date.chinese.IssueI5YB1ATest): expected:<2023-05-2[6] 00:00:00> but was:<2023-05-2[5] 00:00:00>
  getTermByChineseDateTest(cn.hutool.core.date.chinese.SolarTermsTest): expected:<[清明]> but was:<[]>
  toStringTest2(cn.hutool.core.date.DateTimeTest): expected:<2017-01-05T12:34:23[+08]00> but was:<2017-01-05T12:34:23[-06]00>
  getMimeTypeTest(cn.hutool.core.io.FileUtilTest): expected:<application/msword> but was:<null>
  issue3179Test(cn.hutool.core.io.file.PathUtilTest): expected:<image/jpeg> but was:<null>
  toDateFromIntTest(cn.hutool.core.convert.DateConvertTest): expected:<[Mon Dec 15 0]0:00:00 CST 1969> but was:<[Sun Dec 14 1]0:00:00 CST 1969>
  toOffsetDateTimeTest(cn.hutool.core.convert.TemporalAccessorConverterTest): expected:<2019-02-18T00:00[+08]:00> but was:<2019-02-18T00:00[-06]:00>
  toZonedDateTimeTest(cn.hutool.core.convert.TemporalAccessorConverterTest): expected:<2019-02-18T00:00[+08]:00> but was:<2019-02-18T00:00[-06]:00>
  toOffsetTimeTest(cn.hutool.core.convert.TemporalAccessorConverterTest): expected:<00:00[+08]:00> but was:<00:00[-06]:00>

Tests in error: 
  getConcurrencyTest(cn.hutool.core.lang.SimpleCacheTest): unable to create new native thread
  getTest(cn.hutool.core.lang.SingletonTest): unable to create new native thread
  reentrantTest(cn.hutool.core.lang.SingletonTest): unable to create new native thread
  getConcurrencyTest(cn.hutool.core.map.WeakConcurrentMapTest): unable to create new native thread
  executeExceptionTest(cn.hutool.core.thread.SyncFinisherTest): unable to create new native thread
  executeExceptionTest2(cn.hutool.core.thread.SyncFinisherTest): unable to create new native thread

Tests run: 1622, Failures: 23, Errors: 6, Skipped: 151

**Comment by looly** [comment]
DateUtil test must be set local to +08：00，you can set `export TZ=Asia/Shanghai`

getConcurrencyTest you can set `ulimit -u`
