### ISSUE TITLE
为什么CglibUtil.copy(Object source, Class<T> targetClass) source为空的时候不选择返回targetClass空对象而是直接报错呢

### ISSUE THREAD

**Issue by 752391183** [looly/hutool#3360]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.20（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/58898440/c45c6bf3-3b2f-43c9-95de-286ac2e1276d)

1. 复现代码

```java
A a = xxx.getInfo();
 CglibUtil.copy(a ,B.class)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
因为source为null有歧义性：

1. 用户可能忽略null
2. 用户可能想清空目标字段。

基于这种二义性，报错是最好的选择。
