### ISSUE TITLE
ClassUtil#scanPackage未正确关闭文件流

### ISSUE THREAD

**Issue by WongJiYong** [looly/hutool#3361]
`ClassUtil#scanPackage*`内部实现上，使用了JarFile但是未关闭，导致文件一只被占用

[ClassScanner#scanJar](https://github.com/dromara/hutool/blob/20f0c720c457efccde2bcfdd683b06a6ddcdd270/hutool-core/src/main/java/cn/hutool/core/lang/ClassScanner.java#L363C16-L363C16)

源码如下，应该scanJar后关闭JarFile。

![image](https://github.com/dromara/hutool/assets/26293590/1b54495c-6926-4db3-9ac9-6af527b82b11)

**Comment by looly** [comment]
5.8.23
6.0.0-M8 修复此问题~~

感谢~
