### ISSUE TITLE
 ZipUtil.get不解压直接获取压缩包中的内容返回结果为空

### ISSUE THREAD

**Issue by 184005306** [looly/hutool#3366]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22

### 问题描述（包括截图）

1. 复现代码

```java
    InputStream inputStream  = ZipUtil.get(new File("D:\\ftpdownload\\datafile\\bak\\20886412237549700156_20231030.csv.zip"), 
   CharsetUtil.CHARSET_UTF_8,"D:\\ftpdownload\\datafile\\bak\\20886412237549700156_20231030.csv.zip");
   System.out.println(inputStream);

```
  返回结果为空

3. 堆栈信息
无
4. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/895d579b-e9c6-4c11-b0f4-86c415a85ec3)


你参数传错了吧。第二个参数是压缩包中的相对路径，如`aaa/bbb.jpg`
