### ISSUE TITLE
ExcelReader.readAll()解析excel数据值，针对数值类型会出现失真

### ISSUE THREAD

**Issue by YuLoving** [looly/hutool#3367]
版本：5.7.22
代码：
![image](https://github.com/dromara/hutool/assets/45093487/86cae016-004e-4e25-b830-9424cf2de0af)
实际效果：
![image](https://github.com/dromara/hutool/assets/45093487/d37c9a94-a036-4e43-9ab5-804a7d3d7800)
postman调用解析结果 会出现部分数据失真
![image](https://github.com/dromara/hutool/assets/45093487/d619c419-9ccb-4234-bf17-56541097651e)
![image](https://github.com/dromara/hutool/assets/45093487/fffdea80-972c-4854-90f6-f777d1608cf8)

**Comment by looly** [comment]
这不是失真，而是读取后的数字显示类型。

读取Excel时，如果数字比较大或者比较特殊，会使用`BigDecimal`读取，你转JSON的时候自动调用了这个对象的toString，肯定就出现了科学计数法。

**Comment by YuLoving** [comment]
![image](https://github.com/dromara/hutool/assets/45093487/20998205-e590-4892-a178-cadf85afa2bf)
还没有到转json那一步吧，readAll()读取的结果中已经是科学计数法了
