### ISSUE TITLE
考虑设置cn.hutool.db.meta.Column.digit字段为原始类型

### ISSUE THREAD

**Issue by Xinmudotmoe** [looly/hutool#3370]
### 版本情况
hutool版本： 5.8.22
### 问题描述（包括截图）

1. 复现代码
```java
import cn.hutool.db.meta.Column;
Column column=/* 可能来自任何地方 只要没有设置过digit的值 */new Column();
column.getDigit(); // java.lang.NullPointerException
```
相关代码部分

https://github.com/dromara/hutool/blob/20f0c720c457efccde2bcfdd683b06a6ddcdd270/hutool-db/src/main/java/cn/hutool/db/meta/Column.java#L41
https://github.com/dromara/hutool/blob/20f0c720c457efccde2bcfdd683b06a6ddcdd270/hutool-db/src/main/java/cn/hutool/db/meta/Column.java#L126-L131
https://github.com/dromara/hutool/blob/20f0c720c457efccde2bcfdd683b06a6ddcdd270/hutool-db/src/main/java/cn/hutool/db/meta/Column.java#L261-L263
在161行 get时，进行了拆箱操作。而digit只有在128行执行成功后才可能设置为非空。
这使得执行get时，大概率出现空指针异常。

**Comment by looly** [comment]
此处确实有问题。

应该把getDigit返回值设置为Integer

5.8.23 6.0.0-M8 修复此问题。
