### ISSUE TITLE
FileUtil.getType，要是把docx改成doc然后进行格式判断，返回的格式为zip

### ISSUE THREAD

**Issue by kaixuanliang** [looly/hutool#3372]

**Comment by maoSting** [comment]
https://hutool.cn/docs/#/core/IO/%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B%E5%88%A4%E6%96%AD-FileTypeUtil?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e7%b1%bb%e5%9e%8b

注意 xlsx、docx本质上是各种XML打包为zip的结果，因此会被识别为zip格式。

文档有说明

**Comment by CherryRum** [comment]
补充一点，docx和doc是两个格式
`docx`是包含 [XML](https://en.wikipedia.org/wiki/XML) 和其他数据文件的 [ZIP 文件](https://en.wikipedia.org/wiki/ZIP_(file_format))
`doc`复合的二进制文件，旧版本office喜欢使用。
修改后缀不能改变文件本质。
