### ISSUE TITLE
Flaky tests detected in `hutool-core`

### ISSUE THREAD

**Issue by yesh385** [looly/hutool#3373]
### Version status

JDK version: 1.8.0_202

### Problem description

There are flaky tests in `cn.hutool.core.annotation.AnnotationUtilTest` which have been identified by using an open-source research tool named [NonDex](https://github.com/TestingResearchIllinois/NonDex) which is responsible for finding and diagnosing non-deterministic runtime exceptions in Java programs. Some of these flaky tests are: `getAnnotationValueTest`, `scanMetaAnnotationTest`, `getCombinationAnnotationsWithClassTest`, `getAnnotationSyncAlias`.

1. Copy code
```
mvn -pl hutool-core edu.illinois:nondex-maven-plugin:2.1.1:nondex
```
2. Stack information

<img width="1440" alt="Screenshot 2023-11-05 at 1 08 21 PM" src="https://github.com/dromara/hutool/assets/112648152/71b7de3c-b4b0-40bb-b3bb-436970a487d9">

Kindly let me know if you need fixes for these tests. 

Thank you.

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/3368

**Comment by yesh385** [comment]
Hello, I had created this [#3368](https://github.com/dromara/hutool/pull/3368) PR which fixed 6 flaky tests. It was however closed. Kindly let me know if the fix is valid or provide any suggestions/feedback. 

Thank you

**Comment by Createsequence** [comment]
Let me try to understand what you mean: 

Due to the mechanism of JDK, when getting the annotation list through the `getAnnotatioins` or `getDeclaredAnnotations` method of `AnnotatedElement`, the annotation order in the array cannot be guaranteed to be always consistent, so when trying to assert the annotations in the array through a fixed subscript in the test case, it is possible that this problem will fail?

**Comment by yesh385** [comment]
Yes, that's correct. If a test case relies on a specific order of annotations returned by the `getAnnotations` or `getDeclaredAnnotations` methods of `AnnotatedElement`, it may encounter issues due to the under-determined nature of the Java API. The order in which annotations are returned in the array is not guaranteed by the Java specification, which means it can vary between different Java runtime environments.

**Comment by Createsequence** [comment]
> Yes, that's correct. If a test case relies on a specific order of annotations returned by the `getAnnotations` or `getDeclaredAnnotations` methods of `AnnotatedElement`, it may encounter issues due to the under-determined nature of the Java API. The order in which annotations are returned in the array is not guaranteed by the Java specification, which means it can vary between different Java runtime environments.

I think I should understand what you mean. 

However, modifying the source code in order to ensure the accuracy of the test is not a very reasonable means. we should avoid this problem by directly modifying the test case itself.

**Comment by yesh385** [comment]
Thank you for your feedback. Let me check if there is a way to modify only the test and not the source code.
Thank you

**Comment by Createsequence** [comment]
> Thank you for your feedback. Let me check if there is a way to modify only the test and not the source code. Thank you

If there are no other questions, we will close this PR. 

But if you have any new ideas, please continue to give feedback!

**Comment by yesh385** [comment]
Thank you for your feedback. Based on your feedback, I have updated my PR to fix the flaky tests. I have removed my changes from the source code and modified only the tests. Kindly let me know if the fixes look good and if you have any feedback or suggestions regarding the same. 

Thank you
