### ISSUE TITLE
Lambda定义的可序列化接口 Func接口能否继承Function

### ISSUE THREAD

**Issue by You51You** [looly/hutool#3381]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：  最新版本

### 问题描述（包括截图）

1. 复现代码

@FunctionalInterface
public interface Func<P, R> extends Serializable {

2. 改造下
@FunctionalInterface
public interface Func<P, R> extends Function<P，R>, Serializable 

3、可以考虑使用 LambdaMetafactory 实现代替反射

**Comment by looly** [comment]
这个是历史遗留导致的，为了兼容性就没做继承。

6.x中这块做了彻底的重构：

![image](https://github.com/dromara/hutool/assets/1432613/a2b4b857-97c2-4df2-8b81-1200631f1221)


关于LambdaMetafactory，见：LambdaFactory

**Comment by You51You** [comment]
这是来自QQ邮箱的自动回复邮件。你好，现不在手机电脑前，无法亲自回复你的邮件。我将在拿起手机那一刻，思考清楚快速给您回复。还请见谅。祝工作顺利，生活开心！！！
