### ISSUE TITLE
CompressUtil 是否能新增带密码解压和压缩

### ISSUE THREAD

**Issue by DOOB-B** [looly/hutool#3385]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
commons-compress 带有密码的API我并未找到，暂时不考虑封装，你可以直接使用commons-compress完成。或者更换zip4j
