### ISSUE TITLE
always add type to JWT header, it's necessary?

### ISSUE THREAD

**Issue by ZhangTianCi** [looly/hutool#3386]
https://github.com/dromara/hutool/blob/4852c4790470a3ca312966e6c70cb263571a231f/hutool-jwt/src/main/java/cn/hutool/jwt/JWT.java#L314-L322

在这里强制添加type是否有必要性？我在接入一个服务时由于这个问题无法使用JwtUtil。

**Comment by looly** [comment]
这是JWT规范要求吧。

见：https://jwt.io/introduction

![image](https://github.com/dromara/hutool/assets/1432613/60790e1c-79c1-4a6a-b316-5a42b6bd36e2)

**Comment by ZhangTianCi** [comment]
[标准](https://datatracker.ietf.org/doc/html/rfc7519#section-5.1)中说这是可选的，并不强制要求。
你提到的[jwt.io](https://jwt.io/introduction)中的截图，我觉得只是举的一个例子。
因为在实际对接中（AppleMusicApi）遇到了问题，所以还是建议去掉。

<img width="742" alt="image" src="https://github.com/dromara/hutool/assets/10275488/2a987a87-6841-4b5d-9303-5986531c8140">

**Comment by looly** [comment]
@ZhangTianCi 有道理。

为了兼容性，5.8.24增加一个重载方法：

![image](https://github.com/dromara/hutool/assets/1432613/456eaa3a-3b6c-46b5-984b-6408da5c4484)
