### ISSUE TITLE
CglibUtil，cglib包在jdk17的情况下无法使用

### ISSUE THREAD

**Issue by DOOB-B** [looly/hutool#3388]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
希望能重构一个spring修正后cglib实现SpringCglibUtil

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by DOOB-B** [comment]
https://github.com/cglib/cglib/issues/191

**Comment by looly** [comment]
cglib库没有兼容。

hutool6.x不再封装cglib相关工具，改为Spring内置的cglib，你可以试试
