### ISSUE TITLE
cn.hutool.extra.ssh.JschUtil

### ISSUE THREAD

**Issue by Jasonandy** [looly/hutool#339]
![image](https://user-images.githubusercontent.com/12879147/56487219-10a8f800-650d-11e9-99b1-176758de2a97.png)

![image](https://user-images.githubusercontent.com/12879147/56487273-3b934c00-650d-11e9-914f-3c1a4778e1c3.png)

提前connect有问题 再次connect的时候 就无数据返回？

**Comment by looly** [comment]
4.5.7修复此问题。感谢。
