### ISSUE TITLE
能否提供avro序列化及反序列化工具

### ISSUE THREAD

**Issue by weicheng-07** [looly/hutool#3394]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
能否提供类似ObjectMapper这种能将 avro格式的数据反序列化为java对象的工具类

**Comment by looly** [comment]
此类序列化涉及到跨语言，考虑专门的序列化库。
