### ISSUE TITLE
希望SqlBuilder在构建Insert Sql的时候可以选择是否使用参数占位符

### ISSUE THREAD

**Issue by kirning** [looly/hutool#3396]
### 版本情况
这是一个需求，不是bug

JDK版本：    openjdk_8_201
hutool版本： 5.8.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

希望SqlBuilder在构建Insert Sql的时候可以选择不适用 ？替代参数，有时候需要导出数据为insert语句到文件，如果是？的话，不好存储参数
![image](https://github.com/dromara/hutool/assets/7327933/f38eff60-c5c6-4498-8a81-742abb919b7f)

**Comment by looly** [comment]
那就没法避免SQL注入了啊，一旦提供这个方法，漏洞报告会铺天盖地……

考虑自行封装。
