### ISSUE TITLE
HttpUtil的post/get方法无法设置timeout，默认不超时

### ISSUE THREAD

**Issue by chenbing8512** [looly/hutool#34]
见标题

**Comment by liiuzhenzhou11** [comment]
是啊  不超时，有时候程序卡死

**Comment by looly** [comment]
HttpRequest.get(url).timeout(10000).execute().body()

HttpRequest.post(url).timeout(10000).execute().body()

**Comment by iteming** [comment]
设置了，然而根本无效，4.5.6

**Comment by mg0324** [comment]
我也遇到了，设置了超时，但是一直不超时，把线程独占了

**Comment by mg0324** [comment]
版本5.4.3

**Comment by ImSingee** [comment]
版本 5.5.4 在 Linux 环境下遇到了超时无效的问题

**Comment by looly** [comment]
此方法本质上是设置：
```java
HttpURLConnection urlCon = (HttpURLConnection)url.openConnection();
urlCon.setConnectTimeout();
urlCon.setReadTimeout(); 
```

具体为啥无效暂时无法测试也未找到原因。欢迎提供思路。

**Comment by ImSingee** [comment]
@looly 确实很奇怪，我在 Mac 上是可以正常超时的，jar 包放在 Linux（CentOS 8.2.2004）运行就不行

**Comment by lystrosaurus** [comment]
5..8.26 还有这个问题，比较迷茫了，代码看着是设置了超时的

**Comment by looly** [comment]
@lystrosaurus 我想可能是JDK中的设置失效了，暂时找不到原因。

考虑使用HttpClient吧

**Comment by lystrosaurus** [comment]
> @lystrosaurus 我想可能是JDK中的设置失效了，暂时找不到原因。
> 
> 考虑使用HttpClient吧

收到

**Comment by lifesign** [comment]
> 5..8.26 还有这个问题，比较迷茫了，代码看着是设置了超时的

请问这个问题还存在吗？
