### ISSUE TITLE
JschUtil的问题

### ISSUE THREAD

**Issue by MrChocol** [looly/hutool#340]
请问下，为什么JschUtil.exec(session, "nohup java -jar demo.jar 1>demo.log 2>demo.error.log &", null);这个命令在服务器上不起作用呢，但是JschUtil.exec(session, " java -version", null)虽然起作用，但是返回的结果为空字符串但是日志却打出来了

**Comment by looly** [comment]
这个问题还真没法解决。nohup之后进程没出现？还有考虑环境变量问题。

**Comment by looly** [comment]
这个方法只是简单包装了JDK的Runtime，具体请search。
