### ISSUE TITLE
URLEncodeUtil 未对“+”进行编码

### ISSUE THREAD

**Issue by StarkHy** [looly/hutool#3400]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23

### 问题描述

1. 复现代码

```java
        System.out.println(URLEncoder.encode("A++")); // java.net.URLEncoder 结果：A%2B%2B
        System.out.println(URLEncodeUtil.encode("A++")); // cn.hutool.core.net.URLEncodeUtil 结果：A++
```

request参数值中如果有 “+” 传递到后端之后会变成 “ ” 空白字符，需要和Java官方的encode方法一样转换成 “%2B”

**Comment by looly** [comment]
默认的encode方法按照RFC3986规范编码，并不编码`+`。

你可以使用`URLEncodeUtil.encodeAll`

**Comment by zzlAllen** [comment]
1 1
