### ISSUE TITLE
ListUtil工具中不存在filter方法

### ISSUE THREAD

**Issue by qinrui4054** [looly/hutool#3402]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![10881700804289_ pic](https://github.com/dromara/hutool/assets/39306789/72c99074-d4ea-424c-b136-e505eee8424c)

ListUtil 工具中不存在filter方法
![10871700804237_ pic](https://github.com/dromara/hutool/assets/39306789/5683effe-993d-4dee-8e8f-57120f8c329d)

**Comment by looly** [comment]
文档没有跟上代码。

见：

CollUtil.filter
