### ISSUE TITLE
关于工具类名称的一个个人小建议

### ISSUE THREAD

**Issue by hunny** [looly/hutool#3406]
首先，作为一名普通的网友，非常感谢你们为开源做出的贡献，工具是非常好的一个工具，想法也非常好，每个项目中可能都会重复Ctrl + V这些相同的代码。
以下是我的个人一些个人愚见，欢迎讨论，不喜勿喷哈：
既然已经定义为一个工具了，那么所有工具名称定义后的`Util`是否可以换成`s`，例如：`CacheUtil` -> `Caches`，这样使用更加简洁。
这个想法是参考JDK的java.util.Objects，它本身提供的就是Objects工具，例如：Objects.nonNull，还有Arrays等。

**Comment by Createsequence** [comment]
其实之前也有人反应过命名相关的问题，类似的还有为什么要叫 “XXXUtils” 而不是 “XXXUtil”。

关于工具类的命名，hutool 的主要考虑是：
- 工具类名相对其他的库需要具备一定的区分度，避免与其他常用的工具类库重复，比如 Guava 或者 java.util 包，hutool 也做不到百分百满足所有需求，与其他库一并使用的情况并不少见；
- 历史原因，早期的命名规则就是如此，因此后面开发的其他工具类需要保持与前面一致的命名风格，而一口气修改所有 API 显然也不现实；

实际上，“XXXs” 与 “XXXUtil”  都算是业内常见的命名方式？老前辈 apache-commons 也尝试过两种命名风格，哪一种更好其实算是一个见仁见智的问题，个人认为，命名只要做到全局风格统一，并且有辨识度即可。

**Comment by looly** [comment]
确实，命名规范这是习惯问题。

我个人觉得XXXUtil兼具简洁和辨识度。

举个例子，你说加后缀s的工具，很多单词的复数可不是加s，而是加es，这个会导致明显的语法错误。二是加s很多单词很难辨别，比如OpenGaussUtil，如果你用s后缀就会变成OpenGausss，是不是很奇怪？
