### ISSUE TITLE
查询结果有同名字段时，只输出一个

### ISSUE THREAD

**Issue by sunpauliz** [looly/hutool#3407]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
查询结果有同名字段时，只输出一个

1. 复现代码

```java
        Db db = DbUtil.use();
        List<Entity> dataList = db.query("select * from tb_test a, tb_test b");
        System.out.println(JSONUtil.toJsonStr(dataList));
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Entity对象会转换数据库结构为类似Map结构，这时会导致相同key被覆盖。你在使用大部分ORM时也会存在这个问题。

因此：

1. 考虑使用别名
2. 自定义`RsHandler`完成处理。
