### ISSUE TITLE
FileMagicNumber.getMagicNumbe判断错误；doc文件错误被认为是xls文件

### ISSUE THREAD

**Issue by jdzgd** [looly/hutool#3408]
### 版本情况

JDK版本：    openjdk_20
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
doc文件错误被认为是xls文件

1. 复现代码

```java
            byte[] bytes = StreamUtils.copyToByteArray(fileData.getInputStream());
            String mimeType = FileMagicNumber.getMagicNumber(bytes).getMimeType();
```

2. 堆栈信息
无

3. 测试涉及到的文件（注意脱密）
<img width="1541" alt="image" src="https://github.com/dromara/hutool/assets/29347418/3b5925af-8c01-43fb-bec1-e20f19783d40">

<img width="835" alt="image" src="https://github.com/dromara/hutool/assets/29347418/a59341fa-5b46-4b07-821c-5e32233e5076">

由于文件涉密暂不能提供，但已确认是doc文件且被word打开

**Comment by looly** [comment]
如果文件经过WPS编辑，会导致magic number错误。

考虑扩展名辅助识别。

**Comment by CherryRum** [comment]
https://github.com/dromara/hutool/issues/3573
