### ISSUE TITLE
"StrUtil.format()"  输出不符

### ISSUE THREAD

**Issue by touch-feel** [looly/hutool#3409]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/73594022/3eb5f61e-b0b9-4775-9cd0-95f26bdb0b59)

1. 复现代码

```java
    @Test
    public void test() {
        String format = StrUtil.format("{}\\{}", "D:\\a\\b", "c\\d");
        System.out.println(format);
    }
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by wcxgit** [comment]
把 {} 前面的 \\ 去掉就可以了
<img width="639" alt="图片" src="https://github.com/dromara/hutool/assets/24238373/86cb87eb-0af0-4095-b866-bbea087c107a">
