### ISSUE TITLE
ExcelUtil读取文件第一行会读取出额外的数据

### ISSUE THREAD

**Issue by Git594** [looly/hutool#3411]
### 版本情况

JDK版本：    openjdk_8_181
hutool版本： 5.8.23（目前最新版）
apache poi版本：5.2.5

### 问题描述（包括截图）
使用ExcelUtil从第二行读取后面的数据，第一行数据中的空数据会被列号填充
![image](https://github.com/dromara/hutool/assets/20329258/fc3d3f75-ea81-43ba-b627-db39649f03ca)
1. 复现代码
```java annotate 
import cn.hutool.poi.excel.ExcelReader;
import cn.hutool.poi.excel.ExcelUtil;

import java.util.List;

public class Main {

    public static void main(String[] args) {
        ExcelReader reader = ExcelUtil.getReader("C:\\Users\\Administrator\\Desktop\\test.xls");
        List<List<Object>> excelData = reader.read(1);
        for (List<Object> row : excelData) {
            System.out.println(row);
        }
    }
}
```
2. 堆栈信息
没有报错，只是数据有误

3. 测试涉及到的文件（注意脱密）
[test.xls](https://github.com/dromara/hutool/files/13527177/test.xls)

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/d1f27775-71bb-476c-bedd-71a88cb2cf1b)

改为：

```java
List<List<Object>> excelData = reader.read(1, Integer.MAX_VALUE, false);
```

即可。
