### ISSUE TITLE
BUG: 请问`NumberWordFormatter`中转换阿拉伯数字为英文时没有考虑四舍五入是否为 BUG ?

### ISSUE THREAD

**Issue by zflovecoding** [looly/hutool#3412]
### 版本情况

JDK版本：    openjdk_17.0.4
hutool版本： 5.8.23

### 问题描述
你好，我想请教下这是否是一个bug，还是这基于某些独特的考虑。在`cn.hutool.core.convert` 包下的`NumberWordFormatter`这个类中的`format`方法中，转换阿拉伯数字为英文时没有考虑四舍五入的情况，如果考虑该情况的话，那么当前方式的`transTwo`方法只截取字符串前两位存在问题，且考虑四舍五入时当需要进位到整数位时这种以`.`分割字符串的方式也存在问题。期待您的回复。

**Comment by looly** [comment]
这个不算bug，只能说没有考虑到四舍五入的问题。

本意上这个时金额数字的转换，因此只支持到分，超过的不计算在内，因此考虑在使用前自行做转换。

可能是类本身名称有歧义，因此会在6.x中修改名称。

5.x我会补充注释说明。

**Comment by looly** [comment]
这个类6.x可能做改进。

**Comment by zflovecoding** [comment]
> 这个不算bug，只能说没有考虑到四舍五入的问题。
> 
> 本意上这个时金额数字的转换，因此只支持到分，超过的不计算在内，因此考虑在使用前自行做转换。
> 
> 可能是类本身名称有歧义，因此会在6.x中修改名称。
> 
> 5.x我会补充注释说明。
> 
> 

好的，感谢您的回复，期待 hutool 新版本的发布，同时希望有机会可以为6.x贡献一份力量~
