### ISSUE TITLE
XmlUtil中删除了readObjectFromXml方法，无法读取通过保留的writeObjectAsXml方法写入的内容

### ISSUE THREAD

**Issue by fangxinsheng** [looly/hutool#3414]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

这个问题比较简单，代码就不贴了吧。

自从版本5.8.11以后由于反序列化漏洞，XmlUtil中删除了readObjectFromXml方法，但却保留了writeObjectAsXml方法。那么通过writeObjectAsXml方法写入的xml文件内容，就无法读取。
那么，很多历史代码中，只要使用了这对读写方法进行业务操作时，就必然大量报错。
因为这2个方法，实际上调用的是JDK自带的xmlDecode和xmlEncode，xml与bean的互转是遵循一定的格式要求的，他们必须是成对出现。
这样就造成只能写不能读的后果，请大佬完善工具类提供读取方法。

**Comment by looly** [comment]
这块漏洞我这边没有能力修复，因此做了删除处理。

如果必须使用，可以找下旧版本代码，或者直接使用JDK方式读取，毕竟只是一个简单包装而已。

**Comment by fangxinsheng** [comment]
OK👌🏻

---- 回复的原邮件 ----
| 发件人 | Golden ***@***.***> |
| 发送日期 | 2023年12月05日 12:06 |
| 收件人 | dromara/hutool ***@***.***> |
| 抄送人 | fxs ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dromara/hutool] XmlUtil中删除了readObjectFromXml方法，无法读取通过保留的writeObjectAsXml方法写入的内容 (Issue #3414) |

这块漏洞我这边没有能力修复，因此做了删除处理。

如果必须使用，可以找下旧版本代码，或者直接使用JDK方式读取，毕竟只是一个简单包装而已。
