### ISSUE TITLE
文件拓展名获取有差异

### ISSUE THREAD

**Issue by TinChi0818** [looly/hutool#3416]
### 版本情况

JDK版本：    java8
hutool版本： 5.8.23

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/33739928/4a083835-58d8-4fab-a358-92649a8789e2)
![image](https://github.com/dromara/hutool/assets/33739928/6822c433-250e-42b1-b6ed-3e3664aa3309)
![image](https://github.com/dromara/hutool/assets/33739928/db99ae39-ca2a-42c1-8408-64511cb644e4)

1. 复现代码

```java
    public static File convert(MultipartFile multipartFile) throws IOException {
        File file = new File(Objects.requireNonNull(multipartFile.getOriginalFilename()));
        FileUtil.writeBytes(multipartFile.getBytes(), file);
        return file;
    }

    public static File convert2(MultipartFile multipartFile) throws IOException {
        File file = new File(Objects.requireNonNull(multipartFile.getOriginalFilename()));
        try (InputStream in = multipartFile.getInputStream()) {
            IoUtil.copy(in, FileUtil.getOutputStream(file));
        }
        return file;
    }

String extension = FileUtil.getType(newFile);
```

**Comment by TinChi0818** [comment]
视频文件
https://github.com/dromara/hutool/assets/33739928/f799ef53-6424-4ee8-8926-8a9e63ed60ca

**Comment by CherryRum** [comment]
<img width="885" alt="image" src="https://github.com/dromara/hutool/assets/24296698/8cae925d-4ab0-490f-8fed-991bc7735651">
https://www.garykessler.net/library/file_sigs.html

<img width="772" alt="image" src="https://github.com/dromara/hutool/assets/24296698/42787bfe-5643-40ce-880e-50552c2d2505">

我再看看这个到底归到哪个比较合适，虽然mp4确实有很多后缀

**Comment by looly** [comment]
@TinChi0818 @CherryRum 我想这两种格式是一种格式，只是m4v是苹果的标准。
