### ISSUE TITLE
在使用calculate方法时无法完成计算

### ISSUE THREAD

**Issue by Zlase0820** [looly/hutool#3417]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

我们基于Hutool的计算模块开发了一个类似计算器的功能，但是当我们发现入参过大时就会出现死循环，最终导致程序崩溃；
如果可以我们希望能增加一个限定计算的范围或者当超出计算能力时抛出异常；谢谢

1. 复现代码
    public void main {
            Calculator calculator = new Calculator();
            double result2 = calculator.calculate("5+12*(3+5)/7"); // demo可以正常计算
            System.out.println(result2);
            double result1 = calculator.calculate("3333333E3333333333333-3333");
            System.out.println(result1);
            double result = calculator.calculate("3333333E3333333333333-3333!F\u0003\u0003E-\u0003\u0003FF");
    }

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Hutool提供的简单表达式计算智能计算简单的数学公式，不能提供超大数字计算。

考虑使用专门的表达式库~~
