### ISSUE TITLE
hutool-all的matchStart偶尔失效的情况

### ISSUE THREAD

**Issue by Zlase0820** [looly/hutool#3418]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在使用hutool-all的5.8.23版本时，使用combine会出现死循环长时间无响应，最终程序终止，具体的例子如下：

1. 复现代码

    public void main {
            String tempString1 = "********************************************+*";
            String tempString2 = "***********************";
            AntPathMatcher antPathMatcher = new AntPathMatcher();
            String result = antPathMatcher.combine(tempString1, tempString2);
            System.out.println(result);
    }

    public void main {
            String tempString1 = "************************************:*******************************";
            String tempString2 = "**************************ZZZZZZZZ";
            AntPathMatcher antPathMatcher = new AntPathMatcher();
            String result = antPathMatcher.combine(tempString1, tempString2);
            System.out.println(result);
    }

3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Zlase0820** [comment]
类似的问题还有 extractUriTemplateVariables 方法，偶尔也会出现类似的问题
public void main() {
            String tempString1 = "**********************\u02AA*********";
            String tempString2 = "****************";
            AntPathMatcher antPathMatcher = new AntPathMatcher();
            Map<String, String> result = antPathMatcher.extractUriTemplateVariables(tempString1, tempString2);
 }

**Comment by looly** [comment]
@Zlase0820 `AntPathMatcher` copy自Spring，你可以试下，估计Spring也有类似问题~~

这块暂时无能力修改，考虑给Spring提issue~~~
