### ISSUE TITLE
FileTypeUtil 文件类型判断，当 InputStream 读取内容为空的时候，抛出异常

### ISSUE THREAD

**Issue by charlesLeeLee** [looly/hutool#3419]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23

### 问题描述（包括截图）
文件中不包含任何内容的时候（或者说 InputStream 读取不到任何数据的时候），FileTypeUtil.getType 方法会抛出异常

1. 复现代码
    public static void main(String[] args) {
        // 指向文件
        File file = new File("C:\\Users\\48658\\Desktop\\问题文件.png");
        //  readAllBytes 读取到的内容是空的（这是正常情况，因为文件内容本身就是空的）
        byte[] readAllBytes =  cn.hutool.core.io.FileUtil.readBytes(file);
        // InputStream不为null, 但是读取不到任何数据的时候.
        // String fileType = FileTypeUtil.getType(new ByteArrayInputStream(readAllBytes),null, true);
        // 使用下面这一行也行
        String fileType = FileTypeUtil.getType(new ByteArrayInputStream(new byte[]{}),null, true);
        System.out.println(fileType);
    }

**Comment by CherryRum** [comment]
@looly  这种我们是不是不用替用户拦截比较好

**Comment by charlesLeeLee** [comment]
> @looly 这种我们是不是不用替用户拦截比较好

我觉得返回 null 要好一些

**Comment by looly** [comment]
5.8.24 6.0.0增加空判断。
