### ISSUE TITLE
mapUtil中of方法 案例错误

### ISSUE THREAD

**Issue by 543391073** [looly/hutool#342]
mapUtil.of(Object[] array)  方法注释中的案例错误

MapUtil.of(new String[][] {{
	      {"RED", "#FF0000"},
	     {"GREEN", "#00FF00"},
	     {"BLUE", "#0000FF"}});

修改为

MapUtil.of(new String[][] {
	      {"RED", "#FF0000"},
	     {"GREEN", "#00FF00"},
	     {"BLUE", "#0000FF"}});

文档也有同样的错误
https://hutool.cn/docs/#/core/Map%E5%B7%A5%E5%85%B7/Map%E5%B7%A5%E5%85%B7-MapUtil

**Comment by looly** [comment]
已修正，感谢。
