### ISSUE TITLE
URLEncode.encode() 方法 没有对加号等号字符"+","="进行encode 

### ISSUE THREAD

**Issue by hhy1007** [looly/hutool#3420]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
URLEncode.encode() 方法 没有对加号等号字符"+","="进行encode 
例如: Sh1GJ24cvil9trfhMw3xQaj2S+Xnsam7i6AG0dGygTs= 
URLEncode.encode()->                   输出Sh1GJ24cvil9trfhMw3xQaj2S+Xnsam7i6AG0dGygTs= 
使用ava.net.URLEncoder.encode->输出Sh1GJ24cvil9trfhMw3xQaj2S%2BXnsam7i6AG0dGygTs%3D
1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
使用`encodeAll`方法。
