### ISSUE TITLE
FileTypeUtil 对于 `ppt` 和 `pptx` 类型判断错误

### ISSUE THREAD

**Issue by Magma3085** [looly/hutool#3429]
[演示文稿11.pptx](https://github.com/dromara/hutool/files/13667790/11.pptx)
ppt 格式的上传不了 我放到了这里 https://cowtransfer.com/s/f7c11a18c7ae46 

### 版本情况

JDK版本：    openjdk_17.0.8
hutool版本： 5.8.23

### 问题描述（包括截图）
上传` pptx` 返回 `zip`
上传` ppt` 返回 `null`

1. 复现代码

```java
type = FileTypeUtil.getType(context.getFile().getInputStream());
log.info("type:{}", type);
```
返回
```java
type:null
```

**Comment by looly** [comment]
pptx本质上就是zip。

ppt识别有概率，某些wps修改过的ppt格式，修改了magic header，导致无法识别。
