### ISSUE TITLE
HtmlUtil 过滤 XSS 攻击标签白名单没有 p 标签

### ISSUE THREAD

**Issue by lwQin** [looly/hutool#3433]
### 版本情况

JDK版本：    OpenJDK Temurin-17.0.9+9
hutool版本： 5.8.23

### 问题描述（包括截图）
使用 HtmlUtil 中的 filter 方法过滤 XSS 攻击把正常的 p 标签也给过滤了

<img width="574" alt="image" src="https://github.com/dromara/hutool/assets/11586662/405d11ac-8551-4b32-9156-c65fc92d3b54">

**Comment by looly** [comment]
P标签肯定也要过滤啊，原因见：

https://www.freebuf.com/articles/web/340080.html

![Uploading image.png…]()

**Comment by lwQin** [comment]
直接过滤整个 p 标签也太粗暴了吧，富文本编辑器很多都使用了 p 标签做换行元素，至少保留在空属性的这个白名单列表里吧
https://github.com/dromara/hutool/blob/ac89627f3098818bb9e157aedf3285ee40167272/hutool-http/src/main/java/cn/hutool/http/HTMLFilter.java#L135C2-L135C2
<img width="625" alt="image" src="https://github.com/dromara/hutool/assets/11586662/7d1cad55-7aa0-438c-baab-2f267da74356">

**Comment by looly** [comment]
@lwQin 你说的有道理啊，这里可以去除属性。

5.8.24 6.0.0-M9修复此问题，感谢。
