### ISSUE TITLE
cn.hutool.core.lang.Singleton单例创建问题（v5.8.2&v5.8.23）

### ISSUE THREAD

**Issue by codeblackhole1024** [looly/hutool#3435]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.2

### 问题描述（包括截图）
虽然Singleton.get实现了单例类创建的问题，但在创建过程中，会存在对象被重复new的情况。
5.6.6版本是通过双检锁实现的，不会重复new。
版本升级了却出现了问题。

1. 复现代码

```java
 public static void main(String[] args) {
        String key = "123";
        ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(10, 10, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>());
        for (int i = 0; i < 100; i++) {
            threadPoolExecutor.execute(() -> {
                Singleton.get(key, () -> {
                    System.out.println(key);
                    return "123";
                });
            });
        }

    }
```

**Comment by codeblackhole1024** [comment]
5.8.2是通过ConcurrentHashMap实现的，虽然线程安全，却暴露了重复new对象的问题

**Comment by looly** [comment]
尝试升级到5.8.23，使用了computeIfAbsent方法应该没有重复创建问题。

**Comment by codeblackhole1024** [comment]
> 尝试升级到5.8.23，使用了computeIfAbsent方法应该没有重复创建问题。

我用的是jdk1.8，调用的是computeIfAbsentForJdk8，多线程情况下，因为没有加锁，map.get(key)会有多个线程返回null，mappingFunction.apply(key)还是存在多次执行的情况，所以问题仍然存在。
