### ISSUE TITLE
TinyPinyinEngine问题咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#3437]
### 版本情况

JDK版本：    1.8.0_391
hutool版本： 5.8.23

### 问题描述（包括截图）

1. 复现代码
PinyinUtil.getFirstLetter(null, "")

我看TinyPinyinEngine.getPinyin 是直接.toLowerCase()的，如果str是null，就会报错

我想的是既然是工具类封装，就是为了方便，是不是判断一下null会好点？

**Comment by looly** [comment]
5.8.24修复此问题。
