### ISSUE TITLE
> 尝试升级到5.8.23，使用了computeIfAbsent方法应该没有重复创建问题。

### ISSUE THREAD

**Issue by codeblackhole1024** [looly/hutool#3439]
> 尝试升级到5.8.23，使用了computeIfAbsent方法应该没有重复创建问题。

我用的是jdk1.8，调用的是computeIfAbsentForJdk8，多线程情况下，因为没有加锁，map.get(key)会有多个线程返回null，mappingFunction.apply(key)还是存在多次执行的情况，所以问题仍然存在。

_Originally posted by @lichriszhang in https://github.com/dromara/hutool/issues/3435#issuecomment-1863759061_

**Comment by codeblackhole1024** [comment]
针对jdk8的处理，虽然方法名是computeIfAbsent，但内部调用还是putIfAbsent

**Comment by looly** [comment]
@lichriszhang sorry，我这边测试没有切换JDK导致的。

为了解决恶心的`JDK-8161372`死循环问题，不得不改造这个方法。

确实改造后由于非原子可能造成对象重复创建的问题。

不过我觉得这个重复创建并不影响最终单例对象的唯一性。

可以看下`MapUtil.computeIfAbsentForJdk8`方法：

![image](https://github.com/dromara/hutool/assets/1432613/3fb39b0b-bb08-4e24-9e0c-d8d0599df94c)

步骤1中创建了对象，步骤2会重复判断，判断有值后会抛弃创建的对象。

也就是说，为了解决这个bug并照顾到性能问题，退而求其次选择了这个方案。

JDK9+无此问题。
