### ISSUE TITLE
FileTypeUtil getType 方法 校验excel xls后缀文件 传入inputstrem 后 返回null

### ISSUE THREAD

**Issue by luojianjun** [looly/hutool#3440]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.23（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

String filePath = "C:\\Users\\ccb\\Desktop\\test.xls";
        File file = new File(filePath);
        try {
            System.out.println(FileTypeUtil.getType(new FileInputStream(file)));
        } catch (IORuntimeException | FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

控制台 打印 null

**Comment by looly** [comment]
重复：https://gitee.com/dromara/hutool/issues/I8Q22I
