### ISSUE TITLE
csv处理文本中有双引号问题

### ISSUE THREAD

**Issue by duanfan07** [looly/hutool#3446]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.5.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
csvWriter.writeLine("\"[123]\"" )；
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。
csv文件  为 """[123]"""

**Comment by looly** [comment]
因为文本中有分隔符，需要使用""包装，""表示转义。

**Comment by duanfan07** [comment]
> 因为文本中有分隔符，需要使用""包装，""表示转义。

不想有转义字符，只想原版输出，怎么做才可以

**Comment by looly** [comment]
那你可以调用CsvWriteConfig.setTextDelimiter设置为其他字符。
