### ISSUE TITLE
JDK17 Unable to make final void java.lang.Throwable.setCause(java.lang.Throwable) accessible: module java.base does not "opens java.lang" to unnamed module

### ISSUE THREAD

**Issue by sosojustdo** [looly/hutool#3447]
### 版本情况

JDK版本：    openjdk_jdk17
hutool版本： 5.8.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java

```

2. 堆栈信息
<img width="1418" alt="企业微信截图_4e496ed2-9f7f-492d-9a93-78b16fa19378" src="https://github.com/dromara/hutool/assets/3364336/468e2dda-86a4-4780-9e0c-89003e4fdfd3">

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by sosojustdo** [comment]
网上搜寻一圈在java启动参数加上--add-opens java.base/java.lang=ALL-UNNAMED  --add-opens java.base/java.util=ALL-UNNAMED  --add-opens java.base/sun.util=ALL-UNNAMED，但是这似乎是根据jdk包名在做处理，生产环境仅仅靠出现问题，再去排除包名，已经来不及..

**Comment by looly** [comment]
@sosojustdo JDK9+对反射做了严格限制，这个暂时没办法解决，只能通过JVM参数方式。
