### ISSUE TITLE
分词器报错

### ISSUE THREAD

**Issue by clbDream** [looly/hutool#3448]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://github.com/dromara/hutool/assets/28987014/bc0621e1-d27f-4844-a2c4-97bb489790ef)
![image](https://github.com/dromara/hutool/assets/28987014/25972c08-5439-4602-93ce-acdefbecbabc)

比如报错的Excel文件，有问题的图片等。

**Comment by zhrgithub** [comment]
哦哦发自我的 iPhone在 2023年12月28日，15:29，常利兵 ***@***.***> 写道：﻿
版本情况
JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）
问题描述（包括截图）

复现代码

Console.log("报错了");


堆栈信息


测试涉及到的文件（注意脱密）
image.png (view on web)
image.png (view on web)


比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
是不是版本问题。

试下：

```java
		<dependency>
			<groupId>com.hankcs</groupId>
			<artifactId>hanlp</artifactId>
			<version>portable-1.8.4</version>
			<optional>true</optional>
		</dependency>
```
