### ISSUE TITLE
RandomUtil.randomInt,RandomUtil.randomLong range problem

### ISSUE THREAD

**Issue by holmebin** [looly/hutool#3449]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
RandomUtil.randomInt  RandomUtil.randomLong 代码中
if (includeMax) {
            --max;
}
--max逻辑上更取不到，应该改为++
RandomUtil.randomInt(1,2,true,true);
会导致java.lang.IllegalArgumentException: bound must be greater than origin
1. 复现代码

```java
RandomUtil.randomInt(1,2,true,true);
RandomUtil.randomLong(1,2,true,true);

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
PR已合并，感谢。
