### ISSUE TITLE
fillBeanWithMap方法的isToCamelCase无效

### ISSUE THREAD

**Issue by ChungChyi** [looly/hutool#3452]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.21（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
isToCamelCase设置为false，仍然会转换成驼峰。
![截图33](https://github.com/dromara/hutool/assets/76236177/32a69b71-6c14-471e-9f14-692650a054ae)

1. 复现代码

```java
public class BeanUtilExample {
    public static void main(String[] args) throws InstantiationException, IllegalAccessException {
        Map<String, Object> properties = new HashMap<>();
        properties.put("name", "JohnDoe");
        properties.put("user_age", 25);
        User user = BeanUtil.fillBeanWithMap(properties, User.class.newInstance(), false, false);
        System.out.println(user);

        properties.put("max_memory", 1024);
        properties.put("vpc_name", "name");
        DcsRedisProperties dcsRedisProperties = BeanUtil.fillBeanWithMap(properties, DcsRedisProperties.class.newInstance(), false, false);
        System.out.println(dcsRedisProperties);
    }
}
```

```java
@Data
public class User {
    private String name;

    private int userAge;

    @Override
    public String toString() {
        return "User{" +
            "name='" + name + '\'' +
            ", userAge=" + userAge +
            '}';
    }
}
```

```java
@Data
public class DcsRedisProperties {

    private Integer maxMemory;

    private String vpc_name;
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
确实存在这个问题。

问题的根源在于适配JSON自动转换时参数无法传递的问题，属于设计缺陷。

5.x 会deprecate掉这个方法，6.x删除此方法。

同时，在`CopyOptions`中增加`setAutoTransCamelCase`方法，可选是否转换为驼峰。

**Comment by llm163520** [comment]
当输出类型为MAP时，setAutoTransCamelCase无效；不会转换为驼峰；示例如下：
BeanUtil.toBean(map, Map.class, new CopyOptions());
成功示例：
BeanUtil.toBean(MapUtil.toCamelCaseMap(item), Map.class, new CopyOptions());
同时新的版本与原来的版本（5.8.26）不兼容，不会转换驼峰：
BeanUtil.mapToBean(map, Map.class, true, new CopyOptions());
