### ISSUE TITLE
NamingCase.toKebabCase()方法返回值与预期不符

### ISSUE THREAD

**Issue by izayoiyurin** [looly/hutool#3457]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.24（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
使用转短横线的toKebabCase方法，测试结果与注释提供的结果不符。

![image](https://github.com/dromara/hutool/assets/72809930/34189206-0cbf-4420-a17c-ce59a9795835)

1. 复现代码

```java
public class HutoolTest {
    public static void main(String[] args) {
        //  HelloWorld=》hello-world
        //  Hello_World=》hello-world
        //  HelloWorld_test=》hello-world-test
        System.out.println(NamingCase.toKebabCase("HelloWorld"));
        System.out.println(NamingCase.toKebabCase("Hello_World"));
        System.out.println(NamingCase.toKebabCase("HelloWorld_test"));
    }
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个方法只针对驼峰转换连接线模式，并不能转换其它连接线。
