### ISSUE TITLE
qrcodeUtil 能否新加一个在二维码上增加文字的方法 现在只有加logo

### ISSUE THREAD

**Issue by gaizi001** [looly/hutool#3459]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
加文字考虑使用ImgUtil吧。

**Comment by qiuyueovo** [comment]
还是期待能有一个方法可以加文字的
