### ISSUE TITLE
HttpRequest上传大文件，size超过Integer.max问题

### ISSUE THREAD

**Issue by waveBoom** [looly/hutool#3462]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.24（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
HttpRequest req =
                HttpRequest.put("xxxxx");
req.body(FileUtil.readBytes(file))
```
如上,当file的字节大小大于Integer的情况下，因为数组溢出了，会报错，这点正常
为了解决上述问题，我更新hutool到最新版本，使用了如下方法
```java
HttpRequest req =
                HttpRequest.put("xxxxx");
FileResource resource = new FileResource(file);
req.body(resource);
```
然后发现这个方法最终也会进行 数据流的copy，然后使用到了ByteArrayOutputStream.java导致出现了同样问题
报错信息如下
<img width="638" alt="image" src="https://github.com/dromara/hutool/assets/46739345/d4b1ba9b-ed42-4899-b672-bed222b13885">

请问，针对大文件进行http put请求上传，有什么好的方式吗

**Comment by looly** [comment]
FileUtil.readBytes(file)如果超过Integer.max肯定不行啊。

看堆栈应该是sun的实现使用了ByteArrayOutputStream。

考虑使用HttpClient吧，这个解决不了。

**Comment by c-der** [comment]
> FileUtil.readBytes(file)如果超过Integer.max肯定不行啊。
> 
> 看堆栈应该是sun的实现使用了ByteArrayOutputStream。
> 
> 考虑使用HttpClient吧，这个解决不了。

是否可以在 HttpRequest 中增加设置 HttpURLConnection#fixedContentLengthLong  的方法 @looly 
![image](https://github.com/user-attachments/assets/0f6505ef-2298-4327-a209-36d49786f7f1)

**Comment by looly** [comment]
@aishang1993 自定义body长度可以：

```java
request.getConnection().getHttpURLConnection().setFixedLengthStreamingMode(file.size());
```

5.8.33增加快捷方法。

**Comment by c-der** [comment]
@looly request需要在execute时才会初始化connection，坐等 5.8.33 😄

**Comment by looly** [comment]
@aishang1993 啊，忽略了……

5.8.33在`HttpRequest`中增加`setFixedContentLength`方法。
