### ISSUE TITLE
NumberUtil.roundStr； Out-of-bounds Write vulnerability with High severity found

### ISSUE THREAD

**Issue by liu-xinhui** [looly/hutool#3463]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.24（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
NumberUtil.roundStr(transaction.getAmount().getPayerTotal() / 100d, 2, RoundingMode.UP)
```
<img width="1113" alt="image" src="https://github.com/dromara/hutool/assets/7698511/eb640411-9c1b-48b7-994f-e0e7a3b823f7">

**Comment by Taogang00** [comment]
复议：

**Comment by Taogang00** [comment]
复议：
![image](https://github.com/dromara/hutool/assets/19925601/61c5ae62-668f-4b30-98d8-8b87c42d0604)

**Comment by CherryRum** [comment]
https://github.com/github/advisory-database/pull/3268
https://github.com/advisories/GHSA-m5hf-m3r2-xq53

**Comment by looly** [comment]
关联issue：https://github.com/dromara/hutool/issues/3423

sorry各位，这个问题在5.8.25修复。
