### ISSUE TITLE
求助，有没有（或者能不能提供）这样的功能：我想用 ConcurrencyTester 底层的 CountDownLatch 功能来保证所有的线程是同时开始执行的，但是我并不是只有一种类型的任务，不同的线程有可能执行的是不同的任务。

### ISSUE THREAD

**Issue by Camio1945** [looly/hutool#3465]
### 版本情况

hutool版本： 5.8.22

### 问题描述

比如我现在想测试缓存一致性的问题，假设一共有 N 个线程，其中 A 个线程执行更新数据库的操作，B 个线程执行删除数据库的操作，剩下的 N - A - B 个线程执行查询数据库的操作，使用 ConcurrencyTester 能实现吗？

**Comment by looly** [comment]
可以看下`SyncFinisher`，通过`addWorker`方法增加不同的任务。
