### ISSUE TITLE
前端是鸿蒙，使用鸿蒙的sm2加密出来的数据是Uint8Array整型数组，在后台这边使用hutool这边应该怎么解析呢？

### ISSUE THREAD

**Issue by yuntongzhong** [looly/hutool#3466]
我这边尝试将整形数组转成byte数组，再通过SmUtil生成SM2对象去解密，但是解不了。报错：Invalid point encoding 0x30，根据报错信息找到在私钥前加00、密文前加04、公钥前加04的方法，但是无用。
```java
ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
for (int i = 0; i < cipherArray.length; i++) {
            byteArrayOutputStream.write(cipherArray[i]);
        }
byte[] cipherByte = byteArrayOutputStream.toByteArray();

String priKey = "008243528309d275cf2ac66345950c24e2931cde64fc046330d88b490c2890d56b";
SM2 sm2Pri = SmUtil.sm2(priKey, null);
String result2 = sm2Pri.decryptStr(HexUtil.encodeHexStr(cipherByte), KeyType.PrivateKey);
```
请问这种数据如何解密呢？
鸿蒙arkTS这边使用SM2加密后的数据：
48,115,2,33,0,231,134,157,79,154,202,65,233,196,109,168,8,183,186,198,225,95,138,82,15,213,239,148,1,202,58,97,72,143,196,121,158,2,33,0,222,186,166,97,220,49,23,221,171,9,252,72,92,79,114,155,39,225,75,245,7,232,252,229,138,26,242,52,165,49,242,155,4,32,8,39,87,2,26,208,148,88,150,64,28,230,73,45,36,18,116,169,23,89,47,104,209,192,99,57,100,1,111,75,197,181,4,9,113,220,29,39,240,112,47,118,61

私钥：008243528309d275cf2ac66345950c24e2931cde64fc046330d88b490c2890d56b
原数据：abc123456

**Comment by CherryRum** [comment]
arkTS您这边的代码是怎么写的呢，不应该是js那一套吗？

**Comment by yuntongzhong** [comment]
> arkTS你的代码是怎么写的呢，不应该是js那一套吗？
鸿蒙的arkTS只是用了TS那一套的语法，但是js/ts那些现有的库却是不能直接用的。鸿蒙这边自己做了一套原生的加密算法库框架，sm2这块里面的私钥公钥，加密后的数据和解密后的数据全是Uint8Array整型数组。

**Comment by yuntongzhong** [comment]
而且使用鸿蒙这边的convertKey方法生成秘钥对时也有些问题，只能使用ASN.1序列化后的秘钥数据构造。
以下是华为这边的回复：
当前系统版本的指定生成密钥的API为convertKey，其中SM2密钥生成的参数只支持封装并ASN.1序列化后的数据（公钥91字节，私钥51字节)，而很多开发者使用的密钥数据是未封装序列化过的原始裸数据（公钥64字节，私钥32字节)，所以导致convertKey生成密钥对象失败。

目前可以使用下面这种方式生成的公钥，可以在鸿蒙那边正常构造秘钥对象，然后正常加密，加密后的数据不知道如何使用hutool工具解密。
 byte[] publicKey = ((BCECPublicKey) keyPair.getPublic()).getQ().getEncoded(false);

私钥的话，暂时不知道如何生成可以给鸿蒙这边使用的格式，鸿蒙这边要求的是私钥51字节，封装并ASN.1序列化后的数据

**Comment by CherryRum** [comment]
我这边没找到鸿蒙api文档，您是否有文档可以提供

**Comment by yuntongzhong** [comment]
> 我这边没找到鸿蒙api文档，您是否有文档可以提供

鸿蒙这边的sm2秘钥对象生成文档：
https://docs.openharmony.cn/pages/v4.0/zh-cn/application-dev/security/cryptoFramework-guidelines.md/#%E6%A0%B9%E6%8D%AEsm2%E5%AF%86%E9%92%A5%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%95%B0%E6%8D%AE%E7%94%9F%E6%88%90%E5%AF%86%E9%92%A5%E5%AF%B9

鸿蒙这边的sm2加解密文档：
https://docs.openharmony.cn/pages/v4.0/zh-cn/application-dev/security/cryptoFramework-guidelines.md/#sm2%E5%8A%A0%E8%A7%A3%E5%AF%86%E5%BC%80%E5%8F%91%E6%AD%A5%E9%AA%A4

**Comment by yuntongzhong** [comment]
> 而且使用鸿蒙这边的convertKey方法生成秘钥对时也有些问题，只能使用ASN.1序列化后的秘钥数据构造。 以下是华为这边的回复： 当前系统版本的指定生成密钥的API为convertKey，其中SM2密钥生成的参数只支持封装并ASN.1序列化后的数据（公钥91字节，私钥51字节)，而很多开发者使用的密钥数据是未封装序列化过的原始裸数据（公钥64字节，私钥32字节)，所以导致convertKey生成密钥对象失败。
> 
> 目前可以使用下面这种方式生成的公钥，可以在鸿蒙那边正常构造秘钥对象，然后正常加密，加密后的数据不知道如何使用hutool工具解密。 byte[] publicKey = ((BCECPublicKey) keyPair.getPublic()).getQ().getEncoded(false);
> 
> 私钥的话，暂时不知道如何生成可以给鸿蒙这边使用的格式，鸿蒙这边要求的是私钥51字节，封装并ASN.1序列化后的数据

秘钥的话我后面又尝试了下，在鸿蒙这边随机生成公钥私钥数据，然后在java这边使用int数组保存，再将其转成byte数组，使用SmUtil.sm2(priKeyByte, pubKeyByte)方式是可以正式构造SM2对象，然后在java这边加签验签也都可以。**现在的问题就是鸿蒙这边加密后的数据不知道如何使用hutool工具解密，使用hutool工具加密的数据不知道如何在鸿蒙这边解密。**

**Comment by changhr2013** [comment]
密文加了 DER 编码，处理下密文，解一下 DER 编码后再去解密就行了。

```java
/**
 * SM2 标准曲线
 */
private static final X9ECParameters X9_EC_PARAMETERS = GMNamedCurves.getByName("sm2p256v1");

/**
 * 解码 ASN1 编码的密文
 *
 * @param asn1Cipher DER 编码的密文
 * @return 原始密文
 */
public static byte[] decodeAsn1Cipher(byte[] asn1Cipher, SM2Engine.Mode mode) {
    ASN1Sequence sequence;
    try {
        sequence = (ASN1Sequence) DERSequence.fromByteArray(asn1Cipher);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    BigInteger x = ASN1Integer.getInstance(sequence.getObjectAt(0)).getPositiveValue();
    BigInteger y = ASN1Integer.getInstance(sequence.getObjectAt(1)).getPositiveValue();
    byte[] c1 = X9_EC_PARAMETERS.getCurve().validatePoint(x, y).getEncoded(false);

    byte[] c2, c3;
    if (mode == SM2Engine.Mode.C1C3C2) {
        c3 = ((ASN1OctetString) sequence.getObjectAt(2)).getOctets();
        c2 = ((ASN1OctetString) sequence.getObjectAt(3)).getOctets();
    } else {
        c2 = ((ASN1OctetString) sequence.getObjectAt(2)).getOctets();
        c3 = ((ASN1OctetString) sequence.getObjectAt(3)).getOctets();
    }

    byte[] plainCipher = new byte[c1.length + c2.length + c3.length];
    System.arraycopy(c1, 0, plainCipher, 0, c1.length);
    if (mode == SM2Engine.Mode.C1C3C2) {
        System.arraycopy(c3, 0, plainCipher, c1.length, c3.length);
        System.arraycopy(c2, 0, plainCipher, c1.length + c3.length, c2.length);
    } else {
        System.arraycopy(c2, 0, plainCipher, c1.length, c2.length);
        System.arraycopy(c3, 0, plainCipher, c1.length + c2.length, c3.length);
    }
    return plainCipher;
}
```

你上面提供的密文转换为 `Hex` 编码为：

```txt
3073022100e7869d4f9aca41e9c46da808b7bac6e15f8a520fd5ef9401ca3a61488fc4799e022100debaa661dc3117ddab09fc485c4f729b27e14bf507e8fce58a1af234a531f29b0420082757021ad0945896401ce6492d241274a917592f68d1c0633964016f4bc5b5040971dc1d27f0702f763d
```

你一看 `30` 开头的，基本就是 `ASN1` 的 `Sequence` 标志了，密文解 `ASN1` 后得到的原始密文 `Hex` 编码为：

```txt
04e7869d4f9aca41e9c46da808b7bac6e15f8a520fd5ef9401ca3a61488fc4799edebaa661dc3117ddab09fc485c4f729b27e14bf507e8fce58a1af234a531f29b082757021ad0945896401ce6492d241274a917592f68d1c0633964016f4bc5b571dc1d27f0702f763d
```

然后私钥你也没必要加 `00`，你这个私钥已经是 `32` 个字节了：

```txt
8243528309d275cf2ac66345950c24e2931cde64fc046330d88b490c2890d56b
```

最后使用 `SM2` 的 `C1C3C2` 标准解密就可以了。

**Comment by changhr2013** [comment]
华为这个格式应该是参照了 GMT 0009-2012 《SM2 密码算法使用规范》中的规定，可以参照 7.2 小节的描述：
![image](https://github.com/dromara/hutool/assets/8073367/7b2c44b4-e518-4098-a13e-907618693a22)

**Comment by changhr2013** [comment]
顺便补一下编码的方法，凑个对儿 😂

```java
/**
 * 为原始密文添加 ASN1 编码
 *
 * @param plainCipher 原始密文
 * @return ASN1 编码的格式的密文
 */
public static byte[] encodeAsn1Cipher(byte[] plainCipher, SM2Engine.Mode mode) {
    // sm2p256v1 的这个固定 65。可以看 GMNamedCurves、ECCurve 代码
    final int c1Len = (X9_EC_PARAMETERS.getCurve().getFieldSize() + 7) / 8 * 2 + 1;
    byte[] c1 = new byte[c1Len];
    System.arraycopy(plainCipher, 0, c1, 0, c1Len);

    BigInteger x = X9_EC_PARAMETERS.getCurve().decodePoint(c1).getXCoord().toBigInteger();
    BigInteger y = X9_EC_PARAMETERS.getCurve().decodePoint(c1).getYCoord().toBigInteger();

    // 长度为 new SM3Digest().getDigestSize()
    final int c3Len = 32;
    byte[] c3 = new byte[c3Len];

    final int c2Len = plainCipher.length - c1Len - c3Len;
    byte[] c2 = new byte[c2Len];

    ASN1EncodableVector v = new ASN1EncodableVector();
    v.add(new ASN1Integer(x));
    v.add(new ASN1Integer(y));

    if (mode == SM2Engine.Mode.C1C3C2) {
        System.arraycopy(plainCipher, c1.length, c3, 0, c3Len);
        System.arraycopy(plainCipher, c1Len + c3Len, c2, 0, c2Len);
        v.add(new DEROctetString(c3));
        v.add(new DEROctetString(c2));
    } else {
        System.arraycopy(plainCipher, plainCipher.length - c3Len, c3, 0, c3Len);
        System.arraycopy(plainCipher, c1Len, c2, 0, c2Len);
        v.add(new DEROctetString(c2));
        v.add(new DEROctetString(c3));
    }
    try {
        return new DERSequence(v).getEncoded(ASN1Encoding.DER);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

**Comment by yuntongzhong** [comment]
> 密文加了DER编码，处理下密文，解DER编码然后去解密就行了。
> 
> ```java
> /**
>  * SM2 标准曲线
>  */
> private static final X9ECParameters X9_EC_PARAMETERS = GMNamedCurves.getByName("sm2p256v1");
> 
> /**
>  * 解码 ASN1 编码的密文
>  *
>  * @param asn1Cipher DER 编码的密文
>  * @return 原始密文
>  */
> public static byte[] decodeAsn1Cipher(byte[] asn1Cipher, SM2Engine.Mode mode) {
>     ASN1Sequence sequence;
>     try {
>         sequence = (ASN1Sequence) DERSequence.fromByteArray(asn1Cipher);
>     } catch (IOException e) {
>         throw new RuntimeException(e);
>     }
>     BigInteger x = ASN1Integer.getInstance(sequence.getObjectAt(0)).getPositiveValue();
>     BigInteger y = ASN1Integer.getInstance(sequence.getObjectAt(1)).getPositiveValue();
>     byte[] c1 = X9_EC_PARAMETERS.getCurve().validatePoint(x, y).getEncoded(false);
> 
>     byte[] c2, c3;
>     if (mode == SM2Engine.Mode.C1C3C2) {
>         c3 = ((ASN1OctetString) sequence.getObjectAt(2)).getOctets();
>         c2 = ((ASN1OctetString) sequence.getObjectAt(3)).getOctets();
>     } else {
>         c2 = ((ASN1OctetString) sequence.getObjectAt(2)).getOctets();
>         c3 = ((ASN1OctetString) sequence.getObjectAt(3)).getOctets();
>     }
> 
>     byte[] plainCipher = new byte[c1.length + c2.length + c3.length];
>     System.arraycopy(c1, 0, plainCipher, 0, c1.length);
>     if (mode == SM2Engine.Mode.C1C3C2) {
>         System.arraycopy(c3, 0, plainCipher, c1.length, c3.length);
>         System.arraycopy(c2, 0, plainCipher, c1.length + c3.length, c2.length);
>     } else {
>         System.arraycopy(c2, 0, plainCipher, c1.length, c2.length);
>         System.arraycopy(c3, 0, plainCipher, c1.length + c2.length, c3.length);
>     }
>     return plainCipher;
> }
> ```
> 
> 你提供了上面的密文转换为`Hex`编码为：
> 
> ```
> 3073022100e7869d4f9aca41e9c46da808b7bac6e15f8a520fd5ef9401ca3a61488fc4799e022100debaa661dc3117ddab09fc485c4f729b27e14bf507e8fce58a1af234a531f29b0420082757021ad0945896401ce6492d241274a917592f68d1c0633964016f4bc5b5040971dc1d27f0702f763d
> ```
> 
> 你看的`30`开头，基本就是`ASN1`标志`Sequence`了，密文解开`ASN1`后得到的原始密文`Hex`编码为：
> 
> ```
> 04e7869d4f9aca41e9c46da808b7bac6e15f8a520fd5ef9401ca3a61488fc4799edebaa661dc3117ddab09fc485c4f729b27e14bf507e8fce58a1af234a531f29b082757021ad0945896401ce6492d241274a917592f68d1c0633964016f4bc5b571dc1d27f0702f763d
> ```
> 
> 然后私钥你也不需要加`00`，你这个私钥已经有`32`好几个字节了：
> 
> ```
> 8243528309d275cf2ac66345950c24e2931cde64fc046330d88b490c2890d56b
> ```
> 
> 最后使用`SM2`的`C1C3C2`标准解密就可以了。

按照这个方式成功解密了，感谢大佬解答~
