### ISSUE TITLE
缓存没用 ，我把代码给你看看

### ISSUE THREAD

**Issue by zokzy** [looly/hutool#347]
```java
import cn.hutool.cache.CacheUtil;
import cn.hutool.cache.impl.TimedCache;

public class CacheLocalUtil {

    private static final TimedCache<String, String> timedCache = CacheUtil.newTimedCache(7200*1000);

    private  CacheLocalUtil(){
        timedCache.schedulePrune(7200*1000);
    }

    private static class  CacheLocalUtilInstance{

        private static final CacheLocalUtil instance=new CacheLocalUtil();
    }

    public static CacheLocalUtil getInstance(){
        return CacheLocalUtilInstance.instance;
    }

    public void  put(String k ,String v,long time){
        timedCache.put(k,v,time);
    };


    public String get(String k){
        String s = timedCache.get(k, false);
        return s;
    }

}
```

**Comment by looly** [comment]
没用是指什么？过期的没有清理么？

**Comment by zokzy** [comment]
> 没用是指什么？过期的没有清理么？

### 不是定期没清理，就是获取不到，我put进去之后，获取不到，我调试了好久了，我把调试信息给你截图你看下

![企业微信截图_15571069418763](https://user-images.githubusercontent.com/34909038/57203511-45c04a80-6fe3-11e9-9e35-fe5e3373c409.png)

> 从图上是可以看到，我缓存里面是有数据的，key也是正确的，你看我debug到下一步之后，看下面那个图

### 你看我点击下一步之后
> 数据没了，并且我获取到的是null

![企业微信截图_155710701722](https://user-images.githubusercontent.com/34909038/57203530-7c966080-6fe3-11e9-9154-5b46cd986d83.png)

**Comment by zokzy** [comment]
你有直接的联系方式吗，之前跟你说。这样回复太慢了。不然我可能赶不上项目进度了

**Comment by gpqhl0071** [comment]
`  public void  put(String k ,String v,long time){
    timedCache.put(k,v,time);
  };`

put的时候有超时的参数，是不是设置时间太短，超时，数据被移除了。

**Comment by zokzy** [comment]
> ` public void put(String k ,String v,long time){ timedCache.put(k,v,time); };`
> 
> put的时候有超时的参数，是不是设置时间太短，超时，数据被移除了。

我设置的是
```java
 CacheLocalUtil.getInstance().put("template"+t.getId(), JSONUtil.toJsonPrettyStr(t),Long.MAX_VALUE);
```

**Comment by looly** [comment]
914104645 我的QQ，加我私聊

**Comment by looly** [comment]
我先测试下

**Comment by zokzy** [comment]
> 914104645

要验证 ，需要
![image](https://user-images.githubusercontent.com/34909038/57204000-0d227000-6fe7-11e9-9535-06f414220d2e.png)

**Comment by gpqhl0071** [comment]
> ```java
> Long.MAX_VALUE
> ```
Long.MAX_VALUE 你这个用法不对。我估计可能是 long的长度太长，越界了 。

**Comment by gpqhl0071** [comment]
`java
package com.example.demo;

import cn.hutool.cache.CacheUtil;
import cn.hutool.cache.impl.TimedCache;

import java.util.concurrent.TimeUnit;

import ch.qos.logback.core.util.TimeUtil;

/**
 * @author gao peng
 * @date 2019/5/6 10:02
 */
public class CacheLocalUtil {
  private static final TimedCache<String, String> timedCache = CacheUtil.newTimedCache(7200*1000);

  private  CacheLocalUtil(){
    timedCache.schedulePrune(7200*1000);
  }

  private static class  CacheLocalUtilInstance{

    private static final CacheLocalUtil instance=new CacheLocalUtil();
  }

  public static CacheLocalUtil getInstance(){
    return CacheLocalUtilInstance.instance;
  }

  public void  put(String k ,String v,long time){
    timedCache.put(k,v,time);
  };


  public String get(String k){
    String s = timedCache.get(k, false);
    return s;
  }

  public static void main(String[] args) throws Exception{
    CacheLocalUtil c = CacheLocalUtilInstance.instance;
    c.put("test","hello", 1000);
    System.out.println("get test = " + c.get("test"));

    c.put("Long.MAX_VALUE","testTimeOut hello", Long.MAX_VALUE);
    System.out.println("Long.MAX_VALUE result = "+ c.get("testTimeOut"));
  }

}

`

**Comment by gpqhl0071** [comment]
![](http://ww1.sinaimg.cn/large/9b13c8fdly1g2re0ibraqj21350h8q4b.jpg)

**Comment by gpqhl0071** [comment]
cn.hutool.cache.impl.CacheObj isExpired()方法，在get的时候，判断key是否失效时候，你使用Long.MAX_VALUE,已经是long的极限值，在进行加法运算，此处会存在问题，所以导致你的key 在此处失效了。

**Comment by looly** [comment]
> cn.hutool.cache.impl.CacheObj isExpired()方法，在get的时候，判断key是否失效时候，你使用Long.MAX_VALUE,已经是long的极限值，在进行加法运算，此处会存在问题，所以导致你的key 在此处失效了。

确实是越界失效了。

4.5.8修复此问题，感谢参与讨论的大家。

**Comment by looly** [comment]
4.5.8修复此问题，感谢参与讨论的大家。
