### ISSUE TITLE
Convert.toInt得到的结果不正确

### ISSUE THREAD

**Issue by xiao-le-ge** [looly/hutool#3470]
### 版本情况

JDK版本：    1.8.0_362
hutool版本： 5.8.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
最新版5.8.25返回结果也是1
Convert.toInt("01-03");
得到的结果为1，应该报错才对

1. 复现代码

```java
Convert.toInt("01-03")
```

2. 堆栈信息
不报错

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by xiao-le-ge** [comment]
看了下实现，原来是用的NumberFormat转的

**Comment by looly** [comment]
@xiao-le-ge 是，为了兼容一些特殊的数字格式，因此使用了`NumberFormat`。
