### ISSUE TITLE
Setting.autoLoad 中 WatchMonitor监听回调问题

### ISSUE THREAD

**Issue by MindFollowing** [looly/hutool#3473]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.25（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Setting.autoLoad = true时的实现仍由WatchMonitor实现，因此会出现多次调用回调函数情况。但autoload，无法使用DelayWatcher。不能像
#190 这样解决。

1. 复现代码
        this.setting.autoLoad(true,(success)->{
        });

2. 堆栈信息
无

**Comment by looly** [comment]
确实。

因为考虑到Setting加载并不是一个耗费性能的操作，因此多次调用并不影响配置文件的加载，所以没有使用DelayWatcher。
