### ISSUE TITLE
excel导入日期相关问题

### ISSUE THREAD

**Issue by ilikeyuyuan** [looly/hutool#3474]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
我要导入Excel，某一列是都是日期字符串（2024/1/1）这样类型的，我想要读取的时候是纯字符串，而不是自动转换成日期
![image](https://github.com/dromara/hutool/assets/34668457/0542aa25-2482-4948-9cf8-c56cf1ae6b5f)
我在接收excel的类中指明该字段为String，excel字段值是2024/1/1，但是获取到的字符串却是 2024/1/1 00:00:00，我只想要它是我在excel上写什么就是什么，请问改哪个地方可以避免它自动转换吗？
![image](https://github.com/dromara/hutool/assets/34668457/c9a12924-24ba-413c-80cf-69f424b2d4de)

**Comment by looly** [comment]
默认的，Hutool是按照单元格类型读取数据的，即`cell.getCellType();`

如果你想自定义读取单元格，请使用:

`ExcelReader.setCellEditor`

**Comment by ilikeyuyuan** [comment]
![image](https://github.com/dromara/hutool/assets/34668457/cb267d45-6a72-4dcc-a1df-5afd598ba2c7)
你的意思是说写一个CellEditor来处理吗，是像我这样特殊处理？可是如果这么写的话，每个单元格都需要多走这一小段代码，是否显得很傻，还是有什么其他的做法呢？我不想按照单元格类型读取数据，我试了取消宽容模式也不行

**Comment by looly** [comment]
@ilikeyuyuan 你也可以通过cell获取行号和列号，然后处理指定的单元格。
