### ISSUE TITLE
RSA 解密的时候出现了乱码

### ISSUE THREAD

**Issue by pdxgg** [looly/hutool#3478]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.3.8

### 问题描述（包括截图）
 业务中使用到了 RSA  公钥加密私钥解密的姿势，在调用解密接口的时候 偶发的出现解密异常，解密出来的结果中夹杂着乱码。
 并且其中所使用的 私钥和密文都是相同的

<img width="843" alt="hutollRSA-1" src="https://github.com/dromara/hutool/assets/54301419/2c28d6ae-f694-4505-9aa8-24b0b3ad7f8c">

<img width="595" alt="hutoolbut_rsa-2" src="https://github.com/dromara/hutool/assets/54301419/2210f972-9252-48b3-9dc3-dc5e5745003e">

1. 复现代码

```java


import cn.hutool.core.codec.Base64;
import cn.hutool.core.date.DatePattern;
import cn.hutool.core.date.DateUtil;
import cn.hutool.core.util.CharsetUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.crypto.asymmetric.KeyType;
import cn.hutool.crypto.asymmetric.RSA;

 public static void main(String[] args) {
        String pr = "";

        String token = "";

        String s = decryptByPriKey(pr, token);

        log.info("---DEBUG--解密后：{}",s);
    }

    /**
     * 私钥解密
     * @param priKey
     * @return
     */
    public static String decryptByPriKey(String priKey,String encryptTxt){
        try {
            RSA rsa = new RSA("RSA",priKey, null);
            return new String(rsa.decrypt(Base64.decode(encryptTxt), KeyType.PrivateKey), CharsetUtil.CHARSET_UTF_8);
        }catch (Exception e){
            log.error("私钥解密失败：error:{} 密文：{}",e.getMessage(),encryptTxt);
        }
        return null;
    }

```

如有需要可以提供公钥、私钥、密文

**Comment by looly** [comment]
@pdxgg 不同平台实现的padding不同，尝试指定padding和mode试下。

没有解决麻烦提供测试的密钥和密文，再打开此issue。

**Comment by changhr2013** [comment]
在加密时使用了填充方式（`PKCS#1 V1.5` 或 `OAEP`），解密时如果算法传入的是 `RSA`，`hutool` 会默认使用 `NoPadding` 方式去解密。

解密出来原文前面的乱码，实际上是加密时的填充数据，因为你解密传给解密算法的是 `NoPadding` 方式，所以算法在运算时会认为前面的填充数据也是原文的一部分，从而会不做 **Padding 移除操作** 直接返回。

要解决也简单，你在解密初始化 RSA 实例时，根据你加密时使用的算法填充方式来初始化，一般来讲，主流的方式会使用 `PKCS#1 V1.5`，即：

```java
new RSA("RSA/ECB/PKCS1Padding", priKey, null);
```

**Comment by pdxgg** [comment]
！！原来是这样，十分感谢 @changhr2013  。步骤出现在了生成密钥的时候没有指定Padding 

<img width="590" alt="RSA-2" src="https://github.com/dromara/hutool/assets/54301419/6e476733-c6fe-4f04-9bd4-10cba4da97fa">

修改之后在 公钥加密和私钥解密的时候也指定RSA就没问题了 🌹🌹🌹
