### ISSUE TITLE
希望增加一个好的socket工具类

### ISSUE THREAD

**Issue by z231485** [looly/hutool#348]
因为socket经常会用到, 所以希望能有一个封装完善的socket工具类
能实现基本功能即可, 不用太多优化
我自己封装的已经测试可用, 
但我技术不够, 如果有更好的实现方式. 劳烦优化
我的实现方式, 放在附件了
可在GitHub回复或者@hutool2群  2297643478
[socket.zip](https://github.com/looly/hutool/files/3145774/socket.zip)

**Comment by looly** [comment]
感谢。Hutool新版本专门提供了socket模块，你可以看下。
