### ISSUE TITLE
DateException: No format fit for date String

### ISSUE THREAD

**Issue by qingsongxi** [looly/hutool#3483]
高版本hutool项目中，有缺陷。
异常版本号: 5.8.18  对比低版本号为: 4.5.10
报错信息: cn.hutool.core.date.DateException: No format fit for date String [2024-01-04T03:08Z] 
报错代码: 

    public static void main(String[] args) {
        String time = "2024-01-04T03:08Z";
        HashMap<String, String> hashMap = new HashMap<String, String>() {
            {
                put("date", time);
            }
        };
        String jsonString = JSONObject.toJSONString(hashMap);
        Dto bean = JSONUtil.toBean(jsonString, Dto.class);
        System.out.println(bean);
    }

    @Data
    public static class Dto{
        private OffsetDateTime date;
    }

使用低版本时，没有这个问题，排查了一下，原因是 高版本在执行JSONUtil.toBean时，有调用DateUtil.parse方法，里面的DateUtil.parseUTF方法报错了。

对于字符串 2024-01-04T03:08Z 来说，不管是高版本还是低版本，执行DateUtil.parse都会报错。

问题在于，高版本的JSONUtil.toBean，当有时间字段时，会调用DateUtil.parse方法，低版本则不会。高版本执行时，就出现了上述的异常。

**Comment by CherryRum** [comment]
`2024-01-04T03:08Z`这个格式，是哪个规范的呀

**Comment by looly** [comment]
这个是非标准日期格式。
考虑自定义日期格式：

```java
JSONConfig.setDateFormat
```

**Comment by qingsongxi** [comment]
> 这是非标准日期格式。 考虑自定义日期格式：
> 
> ```java
> JSONConfig.setDateFormat
> ```

对于使用而言，在低版本可以正常使用，高版本会出现问题。 这一块不太兼容呢，就导致历史代码无法直接升hutool包依赖版本号

**Comment by looly** [comment]
@qingsongxi 严格来说，低版本的可以使用，只是不报错解析而已，其实解析出来的结果是错误的。
