### ISSUE TITLE
`Hutool.getAllUtils()` 获取不到 Base64 等工具类

### ISSUE THREAD

**Issue by fanthos** [looly/hutool#3484]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.8.25

### 问题描述（包括截图）

`Hutool.getAllUtils()` 获取不到 Base64 等工具类。

比如给工具类加上一个Util注解，或者写一个`cn.hutool.core.codec.CodecUtil.Base64`来指向Base64就可以解决这个问题

1. 复现代码

```java
cn.hutool.Hutool#printAllUtils
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
哈哈，感谢意见。

不过Hutool这个类属于`玩具类`，你可以看下逻辑，只是列出了所有XXXUtil，并没有其它复杂工具类。

**Comment by fanthos** [comment]
对，看过逻辑了。代码结构比较简单，不过目前好像没办法区分哪些是工具类和普通类。

**Comment by looly** [comment]
@fanthos XXXUtil是复杂工具类的快捷入口，以这个为主。

复杂工具类主要是提供了更多灵活的方法，避免工具类方法参数太多。
