### ISSUE TITLE
ChineseDate 农历日期中添加个方法为法定节假日（传统节日中包含信息过多，想要取得一个简化版）

### ISSUE THREAD

**Issue by zhangxiaokun12** [looly/hutool#3486]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
节日封装在：`LunarFestival`，基本覆盖了农历的节日。
