### ISSUE TITLE
Converter2  接口 是否需要 

### ISSUE THREAD

**Issue by HbnKing** [looly/hutool#3487]
Converter2<S, T> 
 
 当前 Converter  接口 将 source  固定为 Object  类 

是否 考虑新增 这种灵活一些 的 converter2

**Comment by VampireAchao** [comment]
不建议Converter2作为命名

**Comment by looly** [comment]
Converter接口只定义了目标类型，而源类型的判断可能并不简单是根据类型转换。

转换过程中，源对象的类型和表示形式均不相同，而如果想区分源对象类型，使用`instanceOf`更加合理，这样也减少了Converer的查找。
