### ISSUE TITLE
TemplateEngine模板无法解析${paymentInfo.userService.operator}层级对象

### ISSUE THREAD

**Issue by huzhan0404** [looly/hutool#3488]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
问题1: 外部传入的是Map<String, Object> context对象, 对象进入框架内部后被强转成了Map<String, String>
导致报错 NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar)

问题2:引入了freemark的jar包,而且也指定了freemark模板,但是本地idea运行,代码走入到了BeetlEngine引擎类里面去了.

**Comment by looly** [comment]
使用最新版本Hutool：

```java
final TemplateConfig config = new TemplateConfig("templates", TemplateConfig.ResourceMode.CLASSPATH);
config.setCustomEngine(FreemarkerEngine.class);

final TemplateEngine engine = TemplateUtil.createEngine(config);
Template template = engine.getTemplate("issue3488.ftl");

String result = template.render(Dict.create().set("paymentInfo", paymentInfo));
```

你可以试下。
