### ISSUE TITLE
json bean处理字段序列化忽略

### ISSUE THREAD

**Issue by walkwolf** [looly/hutool#3490]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
是否可可以支持在 `bean` 到 `json` 字符串的序列化和反序列化时候的 **个性化** 字段定义？
目前一旦字段设置了`@PropIgnore`，则序列化反序列化，该字段都不参与

1. fastjson支持的定义，支持定义序列化、反序列化的支持

```java
    @JSONField(serialize = false)
    public String name;
```

**Comment by looly** [comment]
你可以使用`JSONUtil.putSerializer`自定义序列化。
