### ISSUE TITLE
SM2算法同样的公钥使用不同的构造方法，加密结果不一致

### ISSUE THREAD

**Issue by xdewx** [looly/hutool#3491]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.12（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java

KeyPair pair=SecureUtil.generateKeyPair("SM2");
SM2 obj1=SmUtil.sm2(pair.getPrivate(),pair.getPublic());
String plaintext="hello";
byte[] encoded1=obj1.encrypt(plaintext.getBytes(),KeyType.PublicKey);
// 这里使用不同的方式是为了还原服务方和用户方的情况
SM2 obj2=SmUtil.sm2(null,pair.getPublic().getEncoded());
byte[] encoded2=obj2.encrypt(plaintext.getBytes(),KeyType.PublicKey);

// 为什么这里不一样？？
Assert.isTrue(Arrays.equals(encoded1,encoded2));
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
首先,不太理解为啥您要使用，不同的构造，
您的问题在于，有没有一种可能`sm2`加密是包含盐值计算的，所以你每次的加密字符串都不一样的。

**Comment by xdewx** [comment]
> 首先,不太理解为啥您要使用，不同的构造， 您的问题在于，有没有一种可能`sm2`加密是包含盐值计算的，所以你每次的加密字符串都不一样的。

你说的对，我查到非对称加密算法一般都有随机数。但是我想实现对输入的每次加密都相同，有样例可参考吗

**Comment by CherryRum** [comment]
1.你这需求，我怎么理解都是对称加密
2.可以非对称加密，那就找一个可以固定填充的（padding），或者删除填充，但是会降低安全
```python
# e, n代表公钥
e = xxxx
n = xxxxxxxxxxx

m = b'123456'
m = int.from_bytes(m, 'big')
c = pow(m, e, n)
#不带任何填充，随机数
c = c.to_bytes((c.bit_length() + 7) // 8, 'big')
# 密文c发送给服务器
send(c)
```
所以这个`RSA`属于`歪门邪道`的实现,可能需要你自己实现一个

**Comment by changhr2013** [comment]
哈哈，这其实是一个很有意思的问题，我看看能不能试着把这个问题讲清楚。

`SM2` 算法非对称的本质其实是椭圆曲线上的点乘运算，你并不需要理解点乘运算的原理，你只需要记住几个简单的前置概念：

1. 这个点乘运算的特点是做点乘运算容易，逆向做除法运算却十分困难。
2. 椭圆曲线有一个基点 `G`，你可以把它作为一个常量，假如私钥是 `D`，那么将私钥 `D` 与基点 `G` 点乘得到的值就是公钥，我们将公钥记作 `Q`，因此有 `D * G = Q`。（基于上面的第一条，我们可以用私钥很容易算出公钥，公钥却很难反推出私钥）
3. `SM2` 加密运算中的随机特性，本质上是在运算中随机又生成了一个私钥参与到了运算过程中，因此如果我们将这个随机生成的私钥固定，那么 `SM2` 算法的结果就失去了随机特性。

好的，那现在我们把几个概念列出来看看：

```txt
D：用户私钥
Q = D * G：用户公钥
k：随机私钥
c1 = k * G：随机私钥对应的公钥
G：基点，看做常量
```

`SM2` 算法中对数据进行加密和解密的处理本质上就是异或操作，异或操作的特点是什么呢？

没错，**重复异或两次可以相互抵消**：

```txt
A xor B = C
C xor B = A
A xor B xor B = A
```

好的，了解了这些，让我们用两个简单的公式模拟 `SM2` 加密和解密的核心过程：

```txt
// 公钥加密（用 Q 加密）
// 使用随机私钥与用户公钥点乘得到 kDG
k * Q = k * DG = kDG

// 使用 kdG 衍生的结果与原文异或得到密文 c2
kdf(kDG) xor data = c2

// 私钥解密（用 D 解密）
// 使用随机公钥与用户私钥点乘得到 kDG
c1 * D = kG * D = kDG

// 使用 kdG 衍生的结果与密文 c2 再次异或得到原文
kdf(kDG) xor c2 = data
```

加密过程对原文 `data` 异或了一次得到了密文 `c2`，解密过程对 `c2` 继续异或一次得到原文 `data`。

所以如果我们把参与异或的 `kDG` 固定之后，异或的结果 `c2` 就同样会固定。

那 `kDG` 的随机性来源于哪里呢？`D` 是我们使用的私钥，`G` 是常量，他们都不会变化，`k` 作为随机私钥，是加密过程中随机生成的，它是**随机性的最终来源**。如果我们提前生成一个 `k`，将 `k` 固定后做加解密运算，那么 `SM2` 加密结果也就会被随之固定。

-------------------------------

将 `k` 固定会来带一些算法**性能上的提升**，因为不再需要去生成椭圆曲线上的随机公私钥了。

但是将 `k` 固定也会带来**显著的坏处！显著的坏处！显著的坏处！（重要的事情说三遍）**（PS：GPT总结的 😂）：

1. 安全性降低：最大的缺点是安全性显著降低。C1 的随机性是保证每次加密结果都是独一无二的关键因素之一，固定 C1 会使得加密算法容易受到重放攻击和其他相关密码分析攻击。

2. 丧失前向安全性：如果攻击者某天破解了某个固定 C1 对应的私钥，那么所有使用该 C1 加密的信息都会立即暴露。而在 C1 每次随机的情况下，即便某个密钥被破解，也只会影响到少数几条信息。

3. 违背设计原则：SM2 加密算法的设计原则之一就是确保加密的随机性和唯一性，固定 C1 相当于违背了这一设计原则，降低了算法本身的安全保障。

所以 

> 想实现对输入的每次加密都相同。

这个需求理论上可以实现，但是不建议这样做。

另外，hutool 只封装了算法的使用，如果你需要更改算法流程，需要去更改 `BouncyCastle` 库的 `SM2Engine` 代码：

```java
private byte[] encrypt(byte[] in, int inOff, int inLen)
    throws InvalidCipherTextException
{
...
    byte[] c1;
    ECPoint kPB;
    do
    {
        BigInteger k = nextK();

        ECPoint c1P = multiplier.multiply(ecParams.getG(), k).normalize();

        c1 = c1P.getEncoded(false);

        kPB = ((ECPublicKeyParameters)ecKey).getQ().multiply(k).normalize();

        kdf(digest, kPB, c2);
    }
    while (notEncrypted(c2, in, inOff));
...
}
```

将上面代码中的 `nextK()` 结果固定就可以了。

🍺

**Comment by looly** [comment]
@changhr2013 专业选手，哈哈，敬佩~~

**Comment by xdewx** [comment]
> 哈哈，这其实是一个很有意思的问题，我看看能不能试着把这个问题讲清楚。
> 
> `SM2` 算法非对称的本质其实是椭圆曲线上的点乘运算，你并不需要理解点乘运算的原理，你只需要记住几个简单的前置概念：
> 
>     1. 这个点乘运算的特点是做点乘运算容易，逆向做除法运算却十分困难。
> 
>     2. 椭圆曲线有一个基点 `G`，你可以把它作为一个常量，假如私钥是 `D`，那么将私钥 `D` 与基点 `G` 点乘得到的值就是公钥，我们将公钥记作 `Q`，因此有 `D * G = Q`。（基于上面的第一条，我们可以用私钥很容易算出公钥，公钥却很难反推出私钥）
> 
>     3. `SM2` 加密运算中的随机特性，本质上是在运算中随机又生成了一个私钥参与到了运算过程中，因此如果我们将这个随机生成的私钥固定，那么 `SM2` 算法的结果就失去了随机特性。
> 
> 
> 好的，那现在我们把几个概念列出来看看：
> 
> ```
> D：用户私钥
> Q = D * G：用户公钥
> k：随机私钥
> c1 = k * G：随机私钥对应的公钥
> G：基点，看做常量
> ```
> 
> `SM2` 算法中对数据进行加密和解密的处理本质上就是异或操作，异或操作的特点是什么呢？
> 
> 没错，**重复异或两次可以相互抵消**：
> 
> ```
> A xor B = C
> C xor B = A
> A xor B xor B = A
> ```
> 
> 好的，了解了这些，让我们用两个简单的公式模拟 `SM2` 加密和解密的核心过程：
> 
> ```
> // 公钥加密（用 Q 加密）
> // 使用随机私钥与用户公钥点乘得到 kDG
> k * Q = k * DG = kDG
> 
> // 使用 kdG 衍生的结果与原文异或得到密文 c2
> kdf(kDG) xor data = c2
> 
> // 私钥解密（用 D 解密）
> // 使用随机公钥与用户私钥点乘得到 kDG
> c1 * D = kG * D = kDG
> 
> // 使用 kdG 衍生的结果与密文 c2 再次异或得到原文
> kdf(kDG) xor c2 = data
> ```
> 
> 加密过程对原文 `data` 异或了一次得到了密文 `c2`，解密过程对 `c2` 继续异或一次得到原文 `data`。
> 
> 所以如果我们把参与异或的 `kDG` 固定之后，异或的结果 `c2` 就同样会固定。
> 
> 那 `kDG` 的随机性来源于哪里呢？`D` 是我们使用的私钥，`G` 是常量，他们都不会变化，`k` 作为随机私钥，是加密过程中随机生成的，它是**随机性的最终来源**。如果我们提前生成一个 `k`，将 `k` 固定后做加解密运算，那么 `SM2` 加密结果也就会被随之固定。
> 
> 将 `k` 固定会来带一些算法**性能上的提升**，因为不再需要去生成椭圆曲线上的随机公私钥了。
> 
> 但是将 `k` 固定也会带来**显著的坏处！显著的坏处！显著的坏处！（重要的事情说三遍）**（PS：GPT总结的 😂）：
> 
>     1. 安全性降低：最大的缺点是安全性显著降低。C1 的随机性是保证每次加密结果都是独一无二的关键因素之一，固定 C1 会使得加密算法容易受到重放攻击和其他相关密码分析攻击。
> 
>     2. 丧失前向安全性：如果攻击者某天破解了某个固定 C1 对应的私钥，那么所有使用该 C1 加密的信息都会立即暴露。而在 C1 每次随机的情况下，即便某个密钥被破解，也只会影响到少数几条信息。
> 
>     3. 违背设计原则：SM2 加密算法的设计原则之一就是确保加密的随机性和唯一性，固定 C1 相当于违背了这一设计原则，降低了算法本身的安全保障。
> 
> 
> 所以
> 
> > 想实现对输入的每次加密都相同。
> 
> 这个需求理论上可以实现，但是不建议这样做。
> 
> 另外，hutool 只封装了算法的使用，如果你需要更改算法流程，需要去更改 `BouncyCastle` 库的 `SM2Engine` 代码：
> 
> ```java
> private byte[] encrypt(byte[] in, int inOff, int inLen)
>     throws InvalidCipherTextException
> {
> ...
>     byte[] c1;
>     ECPoint kPB;
>     do
>     {
>         BigInteger k = nextK();
> 
>         ECPoint c1P = multiplier.multiply(ecParams.getG(), k).normalize();
> 
>         c1 = c1P.getEncoded(false);
> 
>         kPB = ((ECPublicKeyParameters)ecKey).getQ().multiply(k).normalize();
> 
>         kdf(digest, kPB, c2);
>     }
>     while (notEncrypted(c2, in, inOff));
> ...
> }
> ```
> 
> 将上面代码中的 `nextK()` 结果固定就可以了。
> 
> 🍺

厉害,多谢
