### ISSUE TITLE
fillBeanWithMap方法的isToCamelCase无效 #3452延续

### ISSUE THREAD

**Issue by llm163520** [looly/hutool#3497]
当输出类型为MAP时，setAutoTransCamelCase无效；不会转换为驼峰；示例如下：
BeanUtil.toBean(map, Map.class, new CopyOptions());
成功示例：
BeanUtil.toBean(MapUtil.toCamelCaseMap(item), Map.class, new CopyOptions());
同时新的版本与原来的版本（5.8.26）不兼容，不会转换驼峰：
BeanUtil.mapToBean(map, Map.class, true, new CopyOptions());

**Comment by llm163520** [comment]
#3497

**Comment by looly** [comment]
`autoTransCamelCase`只用于解决Bean和Map转换中的匹配问题而设置，并不是一个强制参数，因此叫做`autoTransCamelCase`，而不是叫做`transCamelCase`。

这个`auto`的意思是：

1. 当map转bean时，如果map中是下划线等非驼峰模式，自动匹配对应的驼峰字段，避免出现字段不拷贝问题。
2. 当bean转bean时，由于字段命名不规范，使用了非驼峰方式，增加兼容性

但是bean转Map和map转map时，没有使用这个参数，是因为没有匹配的必要，转map不存在无法匹配到的问题，因此此参数无效。

如果你需要强制转换为驼峰方式，可以使用：

```java
final Map<String, String> aB = MapUtil.builder("a_b", "1").build();

// {aB=1}
final Map<?, ?> bean = BeanUtil.toBean(aB, Map.class, CopyOptions.create().setFieldNameEditor(StrUtil::toCamelCase));
```
