### ISSUE TITLE
希望HttpUtil类增加一个downloadBytes()方法可以新增一个超时配置

### ISSUE THREAD

**Issue by hanpijun-buhanpi** [looly/hutool#3499]
虽然目前可以通过downloadFile方法进行先下载再读取，但此方式多了一步IO，过于麻烦且耗时；且使用get方法时，会返回字符串null，无法通过此方式来变相转成bytes；所以希望丰富一下downloadBytes方法，至少新增一个超时配置

**Comment by looly** [comment]
对于自定义的请求，考虑直接使用`HttpUtil.createGet`:

```java
HttpUtil.createGet("https://hutool.cn")
  .timeout(1000)
  .execute()
  .bodyBytes();
```
