### ISSUE TITLE
请问怎么在maven下载hutool的源码

### ISSUE THREAD

**Issue by z231485** [looly/hutool#350]
有些方法我已经提供给hutool了.但是有些自用的方法没必要提交, 大家都用不到
所以想在hutool的基础上做一些扩展,加入些自己的功能
 已经找到方法带hutool打成一个jar包
但是注释没有了. 所以有没有办法下载源码包, 用maven下载, 比较好更新
我想在扩展之后依然可以看得到注释

**Comment by looly** [comment]
maven是自动下载源码包的，你可以在ide中设置。

**Comment by z231485** [comment]
不行的, 我已经设置下载源码了.但是打包完是没有注释的

**Comment by z231485** [comment]
必须直接下载源码包

**Comment by looly** [comment]
那就本地m2_repo里找到对应包，有源码。还不行就在这里下载    https://repo1.maven.org/maven2/cn/hutool/hutool-all/4.5.8/
