### ISSUE TITLE
参考文档”Excel生成-ExcelWriter“中效果图无法加载

### ISSUE THREAD

**Issue by Simon-0128** [looly/hutool#3500]
RT:
![image](https://github.com/dromara/hutool/assets/53385143/fe591e51-7345-4061-89e4-2d3e412d27b1)
![image](https://github.com/dromara/hutool/assets/53385143/e86b2fc4-66ca-484d-8e97-3ec6e7fa00ca)
![image](https://github.com/dromara/hutool/assets/53385143/e2ed6861-a30b-46b4-b6e4-353eef501a19)

**Comment by looly** [comment]
嗯，图片使用了开源中国的，没有替换，最近替换，感谢~~
