### ISSUE TITLE
DateUtil parse 方法时间多了几天

### ISSUE THREAD

**Issue by wuwu955** [looly/hutool#3509]
### 版本情况

JDK版本：    openjdk_8_321
hutool版本： 5.8.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
   DateTime endTime = DateUtil.parse("2024-04-30 59:59:20");
   System.out.println(endTime.toDateStr());
```

2. 堆栈信息
<img width="1110" alt="image" src="https://github.com/dromara/hutool/assets/26872462/5eb889df-d567-41f5-a036-483207088e78">

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by VampireAchao** [comment]
59点？？？一天是59个小时？？？这不对吧，没记错是24小时？

**Comment by CherryRum** [comment]
https://gitee.com/dromara/hutool/issues/I92MFE#note_25123989

**Comment by CherryRum** [comment]
### `java.time.LocalDate` 和 `ResolverStyle`

`java.time`包提供的日期时间API从Java 8开始引入，旨在解决旧`java.util.Date`类的一些设计问题。在这个新API中，`DateTimeFormatter`类用于格式化和解析日期时间对象，它支持通过`ResolverStyle`枚举来指定解析日期和时间时的策略。

`ResolverStyle`有三个选项：

- **`STRICT`**: 要求输入严格匹配日期时间格式器的格式。
- **`SMART`**: 对于某些不明确的情况，提供一种更智能的解析方式，例如，将非闰年的2月29日自动调整为2月28日。
- **`LENIENT`**: 解析过程非常宽松，几乎所有的日期和时间都会被尝试解析，无论它们是否有意义。

示例代码：

```java
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;

public class LocalDateExample {
    public static void main(String[] args) {
        String dateString = "2024-02-29";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("uuuu-MM-dd")
                                                       .withResolverStyle(ResolverStyle.STRICT);
        LocalDate date = LocalDate.parse(dateString, formatter);
        System.out.println(date);
    }
}
```

### `java.util.Date` 和 `setLenient(boolean lenient)`

在`java.util.Date`中，日期时间的解析通常依赖于`SimpleDateFormat`类，该类提供了`setLenient(boolean lenient)`方法来控制解析的宽松性。

- 当`setLenient`设置为`true`时（默认值），解析器会宽松解析输入的日期字符串，允许一些逻辑上不严密的日期，例如将"February 29, 2023"解析为"March 1, 2023"。
- 当`setLenient`设置为`false`时，解析器会严格根据`SimpleDateFormat`的模式来解析日期字符串，不允许日期溢出或其他逻辑错误，否则会抛出`ParseException`。

示例代码：

```java
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class DateExample {
    public static void main(String[] args) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // 设置为严格解析模式
        try {
            Date date = sdf.parse("2024-02-29");
            System.out.println(date);
        } catch (ParseException e) {
            System.out.println("解析异常: " + e.getMessage());
        }
    }
}
```

**Comment by looly** [comment]
可以通过设置:

```java
System.setProperty(SystemPropsUtil.HUTOOL_DATE_LENIENT, "false");
```

关闭全局宽松模式。
