### ISSUE TITLE
抛异常NoSuchAlgorithmException: no such algorithm: SHA256withRSA for provider BC

### ISSUE THREAD

**Issue by bingxue314159** [looly/hutool#3512]
### 版本情况

JDK版本：    JDK8
hutool版本：5.8.26

### 问题描述（包括截图）
抛异常NoSuchAlgorithmException: no such algorithm: SHA256withRSA for provider BC

#### 5.8.25是正常的，微信JS支付的签名，刚好用到了这个方法，直接导致生产事故，人都麻了。

1. 复现代码

```java
SecureUtil.sign(SignAlgorithm.SHA256withRSA);//
```

**Comment by looly** [comment]
测试并无报错。请确认你的BC库是否为最新版本：

```java
<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk18on</artifactId>
			<version>1.77</version>
		</dependency>
``
