### ISSUE TITLE
抛异常NoSuchAlgorithmException: no such algorithm: SHA256withRSA for provider BC

### ISSUE THREAD

**Issue by bingxue314159** [looly/hutool#3513]
### 版本情况

JDK版本：    JDK8
hutool版本： 5.8.26
### 问题描述（包括截图）

1. 复现代码

```java
SecureUtil.sign(SignAlgorithm.SHA256withRSA);//
```

#### 错误应该发生在此次提交（7c22ba0a）。
![1122](https://github.com/dromara/hutool/assets/10768058/d270308f-3b0d-4a03-9f35-d6b6f8e4ee2c)

```java
	public static Provider createBouncyCastleProvider() {
		Provider provider = Security.getProvider(org.bouncycastle.jce.provider.BouncyCastleProvider.PROVIDER_NAME);
		if (provider == null) {
                        //main方法时，可进入此方法。
                        //在我的项目中，此方法进入不了。导致Alg.Alias.Signature.SHA256WithRSA -> SHA256WITHRSA 未加载。
			provider = new org.bouncycastle.jce.provider.BouncyCastleProvider();
			// issue#2631@Github
			SecureUtil.addProvider(provider);
		}
		return provider;
	}
```

![444444](https://github.com/dromara/hutool/assets/10768058/71e7f6ab-ec5e-417c-a682-6a562b1f6a14)

**Comment by looly** [comment]
无法进入，说明`Security.getProvider(org.bouncycastle.jce.provider.BouncyCastleProvider.PROVIDER_NAME);`已经执行成功，在别处加载了BC库。

所以检查传递依赖，是否引入多个bc版本导致的问题。

如有补充再打开此issue。

**Comment by changhr2013** [comment]
两个问题：
1. 是否位于 Android 环境下？
2. 打印一下那个不为空的已经被加载的 BC 库版本号，看看加载到的是个什么版本的 BC 算法提供商：

```java
System.out.println(Security.getProvider(BouncyCastleProvider.PROVIDER_NAME).getVersion());
```
