### ISSUE TITLE
API文档中有writeCol这个方法，我调用的包中找不到，想问下是为什么？

### ISSUE THREAD

**Issue by TonyWang972** [looly/hutool#3514]
版本5.8.26，API文档中有writeCol这个方法，我调用的包中找不到，想问下是为什么？
![image](https://github.com/dromara/hutool/assets/55622087/36ab11b2-05f0-466c-825f-f8c1e7cc3e96)
![image](https://github.com/dromara/hutool/assets/55622087/57f32001-3b2d-41e8-b3ab-06b4b86ca6c8)

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/1b41a67f-372f-4f80-91f3-73d27a0063e1)

请检查hutool版本。
