### ISSUE TITLE
为什么不建议大家使用hutool

### ISSUE THREAD

**Issue by LouisGuo** [looly/hutool#3515]
4.1.14版本升级到5.7.12

1. PinyinUtil依赖了第三番SPI的jar包
2. ClassScanner名称改了
3. PageUtil起始页从1改成了0

最离谱的是这个3， 软件工程是这么干的吗？ 类名不变，方法签名不变，业务含义变了！！！！！！

靠我们在生产踩坑发现问题？

离谱不离谱？

**Comment by looly** [comment]
@LouisGuo 作为早期Hutool用户，对于hutool的支持表示感谢，不过任何库都有一个迭代升级的过程，这个过程中每个修改都是各种用户加入应用于不同场景的后的结果。

4.1.14是2018年的版本，至今已经6年了，这6年的迭代和修改远远多于你列举的这些，且迭代版本众多。

关于你的问题，我逐个回答下：

1. 4.x和5.x版本的变更，决定了很多API不兼容是正常的。
2. PinyinUtil开始使用unicode顺序排序，后来发现很多字的拼音获取不准，不得不选择封装第三方
3. ClassScanner类名称没变更，可能是包名变更了，这个是重新整理的结果
4. PageUtil增加了setFirstPageNo，可以自定义第一页的页码，使用0为默认也是遵循大部分数据库、List等下标。

任何一个代码库和框架不是一开始就是完美的，软件工程也一样，没有银弹，我们都是在不断变化中学习成长的。

PS：Hutool 6.x会有更大的变更，包名也会变更为新的。

**Comment by CherryRum** [comment]
当你决定将软件从版本`4.1.14`升级到`5.7.12`，跨越了`六年`的开发历程时，作为开发者，你承担了确保理解所有相关变更的责任。开源项目并不意味着没有成本，特别是在投入时间和努力方面。我们提供了详细的`变更日志`，目的正是为了帮助避免这类升级问题。忽略这些资源，然后将责任推给项目维护者，不仅不公平，而且明显误解了开源社区的共识。

拿滴滴之前遇到的`Kubernetes（k8s`）升级案例作为例子，这一重大事件强调了技术堆栈升级和变更管理的重要性。没有适当的预防措施和充分的准备，即使是最先进的系统也可能遇到意想不到的问题。我想知道，是什么给了你这样的勇气，去质疑这种做法，尤其是当大型开源项目如Spring Boot在主版本号变更时，都遵循了相似的策略。我们所有人都期望软件项目的迁移和升级能够顺利，但这确实需要双方的努力。特别是在跨越多个版本进行升级的情况下，细读文档是用户的基本责任。我们的团队已经竭尽全力确保所有必要的信息都被记录和共享。如果这些准备工作还不足以引导你进行适当的升级，那么挑战可能源自于超出软件本身的其他因素，比如负责升级的人。

我们非常欢迎和鼓励建设性的反馈，并期待用户能展示出基本的责任感和独立解决问题的能力。软件开发和维护本质上是一个互助合作的过程，而不仅仅是项目维护团队的单方面付出。记住，维护一个开源项目需要大量的时间和精力投入，这基于对技术社区的热爱和希望贡献。但理解一点很重要：我们不是在这里为你个人未能采取的行动承担责任。

**Comment by VampireAchao** [comment]
非常抱歉，我们吸取教训，计划6.x出一个从5.x到6.x的升级指南，再次感谢宝贵意见

**Comment by lonecloud** [comment]
同样遇到了这个问题，最近升级到5.8.20 还好提前发现了这个问题，不然就是大坑，直接干上生产了，更新日志上也没有写

**Comment by looly** [comment]
@lonecloud 不建议跨大版本升级。
