### ISSUE TITLE
系统属性调用

### ISSUE THREAD

**Issue by zhongziqiang** [looly/hutool#352]
运行时信息，包括内存总大小、已用大小、可用大小等
此方法SystemUtil.getRuntimeInfo();
我的是win10系统,在获取出来的数据,我是8G的内存,但是获取出来的数据为以下
Max Memory:    1.76 GB
Total Memory:     134.5 MB
Free Memory:     108.4 MB
Usable Memory:     1.74 GB

**Comment by looly** [comment]
此方法获得的是JVM运行时使用的内存
