### ISSUE TITLE
国密SM2为什么只能用公钥加密？

### ISSUE THREAD

**Issue by liugejava** [looly/hutool#3521]
### 版本情况

JDK版本：    oraclejdk_8_201
hutool版本： 5.3.8（最新版仍然有问题）

### 问题描述（包括截图）

1. 复现代码

```java
	/**
	 * 加密，SM2非对称加密的结果由C1,C2,C3三部分组成，其中：
	 *
	 * <pre>
	 * C1 生成随机数的计算出的椭圆曲线点
	 * C2 密文数据
	 * C3 SM3的摘要值
	 * </pre>
	 *
	 * @param data    被加密的bytes
	 * @param keyType 私钥或公钥 {@link KeyType}
	 * @return 加密后的bytes
	 * @throws CryptoException 包括InvalidKeyException和InvalidCipherTextException的包装异常
	 */
	@Override
	public byte[] encrypt(byte[] data, KeyType keyType) throws CryptoException {
		if (KeyType.PublicKey != keyType) {
			throw new IllegalArgumentException("Encrypt is only support by public key");
		}
		return encrypt(data, new ParametersWithRandom(getCipherParameters(keyType)));
	}
```

这里使用国密SM2加密，为什么只能用公钥加密，非对称加密可以私钥加密、公钥解密的啊，这样方法的参数 @param keyType 私钥或公钥 {@link KeyType}还有什么意义呢？

**Comment by changhr2013** [comment]
这个问题看起来简单，实际上得讲算法的数学原理了 😂 我目前还没有信心能把这个给零基础的同学讲明白……

如果你要一个偏数学回答，那就是：

RSA 算法是基于**大素数的乘积分解难题**设计的，在模 N（N=p*q） 下，选取了两个互为乘法逆元的指数 d 和 e 作为公钥和私钥，**公钥与私钥数学性质相同**。（加解密的过程直接利用了乘法逆元和欧拉定理的性质。）

而 SM2 算法是基于**椭圆曲线离散对数难题**设计的，公钥是通过私钥（一个随机选取的数）与椭圆曲线上的一个基点进行标量乘运算得到的，**公钥和私钥数学性质不同**。（加解密的过程实际上是利用了点乘的结合律和异或的性质，过程与 RSA 完全不同。）

所以 RSA 算法可以公私钥互换使用，SM2 却只能公钥加密私钥解密。

PS：等我什么时候能够整理出更通俗的数学原理描述后，再来更新下吧 😂。

**Comment by liugejava** [comment]
> 这个问题看起来简单，实际上得讲算法的数学原理了 😂 我目前还没有信心能把这个给零基础的同学讲明白……
> 
> 如果你要一个偏数学回答，那就是：
> 
> RSA 算法是基于**大素数的乘积分解难题**设计的，在模 N（N=p*q） 下，选取了两个互为乘法逆元的指数 d 和 e 作为公钥和私钥，**公钥与私钥数学性质相同**。（加解密的过程直接利用了乘法逆元和欧拉定理的性质。）
> 
> 而 SM2 算法是基于**椭圆曲线离散对数难题**设计的，公钥是通过私钥（一个随机选取的数）与椭圆曲线上的一个基点进行标量乘运算得到的，**公钥和私钥数学性质不同**。（加解密的过程实际上是利用了点乘的结合律和异或的性质，过程与 RSA 完全不同。）
> 
> 所以 RSA 算法可以公私钥互换使用，SM2 却只能公钥加密私钥解密。
> 
> PS：等我什么时候能够整理出更通俗的数学原理描述后，再来更新下吧 😂。

明白了，感谢。建议把这个方法是实现改为，抛出该方法不支持调用的异常。

**Comment by CherryRum** [comment]
@liugejava 
---
 昨天写了很多没有保存。
 大概给你说一下,严格意义上在密码学领域其实没有`公钥加密`，`非对称加密可以私钥加密、公钥解密`的这种说法。
 之所以您可能有点疑惑，罪魁祸首应该是`RSA`这个巧合.
在讨论国密SM2或任何非对称加密系统时，我们通常区分两个主要操作：加密和签名。这两种操作都利用了一对密钥——公钥和私钥，但它们服务于不同的目的。

### 非对称加密和签名的数学描述
对于消息\( m \)，公钥\( PK \)和私钥\( SK \)，非对称加密和签名过程可以数学表示如下：

- **加密过程**：\( c = E_{PK}(m) \) 其中\( c \)是密文，\( E \)是加密函数。
- **解密过程**：\( m = D_{SK}(c) \) 其中\( D \)是解密函数。

对于数字签名，过程是：
- **签名过程**：\( \sigma = S_{SK}(m) \) 其中\( \sigma \)是签名，\( S \)是签名函数。
- **验证过程**：\( \text{verify} = V_{PK}(m, \sigma) \) 其中\( V \)是验证函数，如果签名有效，则\( \text{verify} \)为真。
###  SM2 加密过程与签名过程流程图
此处引用的第一版的流程图，现有有效的应该是加密顺序应该是`C1C3C2`
<img width="597" alt="image" src="https://github.com/dromara/hutool/assets/24296698/0b408cec-304e-4407-90ff-be91b6578eec">
<img width="677" alt="image" src="https://github.com/dromara/hutool/assets/24296698/910433a3-355c-40b4-b76d-21db750148cf">
<img width="572" alt="image" src="https://github.com/dromara/hutool/assets/24296698/f2104bbf-59f3-4e51-9293-772bd8741767">
<img width="553" alt="image" src="https://github.com/dromara/hutool/assets/24296698/8fde0af5-4fbe-4c3e-929e-7ef376bf4cad">

### 为何通常使用公钥加密而非私钥加密
非对称加密中通常使用公钥进行加密，是因为这样可以确保只有对应的私钥持有者能解密和访问消息。这对于保护信息的安全至关重要。如果使用私钥加密，任何知道公钥的人（即公众）都能解密信息，这会破坏加密的目的。

### 数字签名的目的
数字签名使用私钥生成，用于验证消息的来源和完整性。签名确保了发送者的身份和消息的未被篡改，提供了不可否认性（术语应该是`不可抵赖`）。在RSA的上下文中，虽然签名过程数学上与加密相反，但实际上它们服务于完全不同的目的，并且对安全性的要求也不同。
---
### 结论
在非对称加密的实践中，使用私钥加密和公钥解密的概念主要限于数字签名领域，而不是通用加密通信。RSA的例子说明了这两个过程在数学上的相似性（相同的），但在应用中，它们是为了不同的安全目标和原则而设计的。数字签名主要用于验证身份和消息的完整性，而加密则用于保护信息的隐私。

**Comment by noear** [comment]
太牛了！！！
