### ISSUE TITLE
HttpRequest在设置body后会清除form数据

### ISSUE THREAD

**Issue by vincent98019** [looly/hutool#3523]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.8.16

### 问题描述

![image](https://github.com/dromara/hutool/assets/56062233/eb2acfda-255e-45ee-9114-f3fac69ff80f)

当我发起一个请求，既设置了form的数据，又设置了body的数据，另一个数据会被置为null，看了源码是刻意置为null，并且浏览了文档与其他方法，并没有找到一个有效的解决方案

**Comment by CherryRum** [comment]
试试手动把`form`参数编码到`url`

**Comment by looly** [comment]
因为无论是body还是form，本质上都是消息体，两者不能共存。
