### ISSUE TITLE
环境变量动态替换配置文件内容

### ISSUE THREAD

**Issue by Mr-LiuDC** [looly/hutool#3524]
### 版本情况

JDK版本：    JDK 1.8
hutool版本： 5.8.26

### 问题描述（包括截图）

目前config路径下的settings或者properties文件没法通过环境变量动态替换，希望可以增加这个特性。

**Comment by looly** [comment]
你可以通过`DSFactory.create(dbSetting).getDataSource(dbSourceName)`来自定义Setting的位置。
```java
final Setting dbSetting = new Setting("config/db.setting");
final DataSource dataSource = DSFactory.create(dbSetting).getDataSource("");
```

**Comment by Mr-LiuDC** [comment]
> 你可以通过`DSFactory.create(dbSetting).getDataSource(dbSourceName)`来自定义Setting的位置。
> 
> ```java
> final Setting dbSetting = new Setting("config/db.setting");
> final DataSource dataSource = DSFactory.create(dbSetting).getDataSource("");
> ```

这个用法还是不够灵活，配置固定写死在配置文件了。如果同时还支持环境变量覆盖配置的话就可以一次打包，可以在任何地方执行，只需修改环境变量或者命令行参数而不用修改配置文件。

**Comment by looly** [comment]
要想灵活又简便，这个其实很难做到。

使用环境变量的问题在于太隐蔽了。例如你项目中自定义了环境变量，这个变量是个全局值，一旦协作人员修改了这个值，别人不知道哪里修改了，很难排查问题。
