### ISSUE TITLE
使用Lombok的@Accessors(chain = true)之后, 无法copy

### ISSUE THREAD

**Issue by songhanlin** [looly/hutool#3525]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.26（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
@Data
@Accessors(chain = true)
 class SampleBean {
    private String value;
}
@Data
@Accessors(chain = true)
 class OtherSampleBean {
    private String value;
}

SampleBean bean1 = new SampleBean();
bean1.setValue("Hello world");

OtherSampleBean otherBean = new OtherSampleBean();

CglibUtil.copy(bean1, otherBean);

System.out.println(otherBean.getValue()); // 为空
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
<img width="887" alt="image" src="https://github.com/dromara/hutool/assets/22296845/e68f5496-7a70-4002-97a9-ce96e4935595">

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个是Cglib和Lombok的兼容问题，Cglib的拷贝不支持返回this的setter方法，因此不能识别。

考虑使用BeanUtil.copyProperties.
