### ISSUE TITLE
QrCodeUtil toSVG生成的图片比toImage生成的图片要粗

### ISSUE THREAD

**Issue by s1084796293** [looly/hutool#3528]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://github.com/dromara/hutool/assets/17758223/2a172895-42c0-467c-abe2-a70632bdb038)

**Comment by looly** [comment]
这个暂时没有办法，欢迎提供思路。
