### ISSUE TITLE
使用ExcelReader读取Excel文件，列内容长度特别长导致读取的值不完整

### ISSUE THREAD

**Issue by Mengleijin** [looly/hutool#3529]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.26（已确保最新尝试还有问题）

### 问题描述
    你好，想问一下使用ExcelReader读取Excel文件，列内容长度特别长导致读取的值不完整，这是Hutool工具做了限制？还是自定义对象定义的字段（用的String）有长度限制？

1. 复现代码

```java
        File file = FileUtil.file("xxx.xlsx");
        ExcelReader reader = ExcelUtil.getReader(file);
        List<MyObject> objectList = reader.readAll(MyObject.class);
```

**Comment by looly** [comment]
Excel对单元格的内容长度有限制。

**Comment by Mengleijin** [comment]
@looly 在Excel中内容是完整的，通过hutool读到的是不完整的
