### ISSUE TITLE
导出excel，通过注解设置别名后，setOnlyAlias=true不起作用

### ISSUE THREAD

**Issue by littleeyes** [looly/hutool#3531]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

<img width="420" alt="image" src="https://github.com/dromara/hutool/assets/12539960/45cb85b5-a4a2-49ae-b1cb-6b5836213db1">
<img width="150" alt="image" src="https://github.com/dromara/hutool/assets/12539960/65405710-4aa9-4d15-a321-ff31eb8a9d1f">
<img width="555" alt="image" src="https://github.com/dromara/hutool/assets/12539960/ace776ef-7b9e-4438-b20b-8cc91a32e2d0">
设置只写出加了别名的字段，但是实际依然全部字段都导出了

**Comment by gg1229505432** [comment]
ApiModelProperty 这个注解是这个吗? :  <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.6.8</version>

**Comment by littleeyes** [comment]
> ApiModelProperty 这个注解是这个吗? : io.swagger swagger-annotations 1.6.8

是的

**Comment by gg1229505432** [comment]
Bean中设置@Alias时，setOnlyAlias是无效的，这个参数只和addHeaderAlias配合使用，原因是注解是Bean内部的操作，而addHeaderAlias是Writer的操作，不互通。

**Comment by gg1229505432** [comment]
你可以下载hutool源码, 在这里查看示例: hutool-poi/src/test/java/cn/hutool/poi/excel/Issue2899Test.java

**Comment by gg1229505432** [comment]
<img width="1031" alt="image" src="https://github.com/dromara/hutool/assets/87351268/8fd03710-6074-49ef-ac53-2eec9a52c1b8">
