### ISSUE TITLE
CaseInsensitiveMap大小写问题，取不到值

### ISSUE THREAD

**Issue by heaxo** [looly/hutool#3532]
### 版本情况

JDK版本：    jdk11.0.16
hutool版本： [5.X.X](cn.hutool:hutool-all:5.7.9)（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
            Map<String, GqgWmsSteelPlateInfo> wmsMap = gqgWmsSteelPlateInfos.stream()
                    .collect(Collectors.toMap(wms -> wms.getToolStockPrdRef(),wms -> wms,
                            (old, cur) -> old.setLotAttr08((old.getLotAttr08() == null ? 0
                                    : old.getLotAttr08()) + (cur.getLotAttr08() == null ? 0 : cur.getLotAttr08())
                            ), CaseInsensitiveMap::new));
1. 复现代码
取值的时候转为小写了，
![1712055914916](https://github.com/dromara/hutool/assets/72446584/85596f54-ec10-4389-9541-58949d229e3b)
但是存的是大小的key
我看了一下put的时候确实转小写了，但是merge并没有转为小写
![1712055751255](https://github.com/dromara/hutool/assets/72446584/83fc0560-9065-4f16-962e-2aa440d13049)
取值的时候也是大写
![1712055936911](https://github.com/dromara/hutool/assets/72446584/6d178ff2-044e-492a-aba9-30877b6cbb77)
zui'z最终取值结果为null
![1712055998812](https://github.com/dromara/hutool/assets/72446584/647001b4-8c05-49d4-be31-ccaa643558a0)

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by heaxo** [comment]
implementation 'cn.hutool:hutool-all:5.7.9'

**Comment by gg1229505432** [comment]
你代码的最后一行 CaseInsensitiveMap::new, 这个方法Map是: 忽略大小写的Map<br>. 对KEY忽略大小写，get("Value")和get("value")获得的值相同，put进入的值也会被覆盖. 
所以会put, get出问题

**Comment by heaxo** [comment]
@gg1229505432 这个是正常的吗
![1712467984006](https://github.com/dromara/hutool/assets/72446584/70c1b372-cadf-464f-a1d1-f11cbf0dac23)

**Comment by gg1229505432** [comment]
你最初的问题是大小写出现问题，CaseInsensitiveMap这个还是Map本来就是忽略大小写的，所有的大写都会变成小写

**Comment by heaxo** [comment]
@gg1229505432 所以不是我这么用的对吧

**Comment by gg1229505432** [comment]
哈哈哈 是的 你用错了. 切记 不要用字符敏感的 Map ~
