### ISSUE TITLE
关于验证码的问题

### ISSUE THREAD

**Issue by YellowML** [looly/hutool#3534]
### 版本情况

JDK版本：    1.8
hutool版本： 5.8.11

### 问题描述（包括截图）

核心的生成验证码的代码就这一句，剩下的都是设置返回值类型，取响应流之类的无关代码

```java
ShearCaptcha captcha = CaptchaUtil.createShearCaptcha(200, 100, 4, 4);
```

最右边的验证码经常出现部分字符跑出边界的问题，我不知道是不是我设置的问题，或者有没有解决的方法

**Comment by gg1229505432** [comment]
已经在修复了, 默认的字体大小是 height*0.75, 如果onwer合并我代码的情况下, 你就可以在最新的代码里面设置字体大小了, 推荐是0.50f - 0.65f
https://github.com/dromara/hutool/pull/3533

**Comment by looly** [comment]
5.8.28并入修改。
