### ISSUE TITLE
HttpUtil工具get、post请求有没有关闭释放资源？

### ISSUE THREAD

**Issue by Delete94** [looly/hutool#3538]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.7.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

想问一下，HttpUtil工具get、post请求有没有关闭释放资源，看源码没有看到
![image](https://github.com/dromara/hutool/assets/49228381/18855f80-1d26-4573-9ff5-61faab312c93)

**Comment by HwwwwwLemon** [comment]
<img width="761" alt="image" src="https://github.com/dromara/hutool/assets/47653238/e4944f2d-ab8a-4914-b8c7-45a821cb112d">
<img width="1143" alt="image" src="https://github.com/dromara/hutool/assets/47653238/d1b8dfa3-4281-42ea-a186-108b7f37ca3b">

HttpBase#bodyBytes，最后调用IoUtil#read读取流后有close

**Comment by HwwwwwLemon** [comment]
同步请求会调用 HttpResponse#forceSync，在该方法里面关闭的，异步请求的需要手动关

**Comment by Hwwwww-dev** [comment]
同步请求会调用 HttpResponse#forceSync，异步需手动关闭。见[HttpResponse何时close?](https://gitee.com/dromara/hutool/issues/I7DNPG)
