### ISSUE TITLE
BeanUtil.beanToMap不能正常解析List

### ISSUE THREAD

**Issue by zhourui9797** [looly/hutool#3539]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
1，BeanUtil.beanToMap不能正常解析List
2，如图调用BeanUtil.beanToMap（）方法，并使用驼峰转下划线：
![Snipaste_2024-04-09_11-47-56](https://github.com/dromara/hutool/assets/34817337/0e4116c1-241b-4a77-b180-8952451ab980)
3，但转换的结果里面list的key的驼峰依然存在并没有转成下划线

**Comment by zhourui9797** [comment]
> ### 版本情况
> JDK版本： openjdk_8_201 hutool版本： 5.8.22（请确保最新尝试是否还有问题）
> 
> ### 问题描述（包括截图）
> 1，BeanUtil.beanToMap不能正常解析List 2，如图： ![Snipaste_2024-04-09_11-47-56](https://private-user-images.githubusercontent.com/34817337/320715230-0e4116c1-241b-4a77-b180-8952451ab980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzQ3OTIsIm5iZiI6MTcxMjYzNDQ5MiwicGF0aCI6Ii8zNDgxNzMzNy8zMjA3MTUyMzAtMGU0MTE2YzEtMjQxYi00YTc3LWIxODAtODk1MjQ1MWFiOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAzNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMWY0Mjg0MDAyYWY2YTI2YzBiYWZhZDQyZWNjZGEzNTk0NjVjZDI5MDU2ZWU5OWE3OWI3YmMxNWRmNmYwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XtPztUnOcPiq6SJBAyX9uvn-BWTUXRBCuknsTZHnGTQ)

**Comment by zhourui9797** [comment]
求解决

**Comment by CherryRum** [comment]
麻烦您提供下最小复现的样例

**Comment by looly** [comment]
beanToMap是浅复制或转换，因此子对象并不转换。
