### ISSUE TITLE
升级5.8.16后，JSON解析会有报错，影响了老代码写法

### ISSUE THREAD

**Issue by qierkang** [looly/hutool#3540]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
升级5.8.16 针对项目以前老的代码JSON 会有报错。对这样的 json 转换 是否可以按照老版本做兼容
JSONUtil.toJsonStr()
代码截图：
<img width="1125" alt="image" src="https://github.com/dromara/hutool/assets/17940151/c8589312-5c35-494a-a1ca-818876ea0cb8">

<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>5.8.16</version>
</dependency>

1. 复现代码

```java
public static void main(String[] args) {
        Long userId=10101010L;
        log.info("queryUserRightsAndVipLevel 调用成功，req:[{}]", JSONUtil.toJsonStr(userId));
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
尝试升级到5.8.27，会返回`{}`
