### ISSUE TITLE
JSON字符串包含特殊字符的转义问题

### ISSUE THREAD

**Issue by Yiuman** [looly/hutool#3544]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.27

### 问题描述（包括截图）

1. 复现代码

```java
String serviceDataJsonStr = "{"serviceId":"io.autoflow.plugin.regex.RegexService","parameters":{"regex":"((https?|ftp|gopher|telnet|file):((//)|(\\\\))+[\w\d:#@%/;$()~_?\+-=\\\.&]*)","content":"$.inputData.hgIkDW8F[0].raw","method":"findAll"}}"
//这里报错
ServiceData serviceData = JSONUtil.toBean(serviceDataJsonStr, ServiceData.class);

//字符串使用JSONUtil.quote(serviceDataJsonStr)转义后再转对象依然报错
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
<img width="891" alt="image" src="https://github.com/dromara/hutool/assets/23078024/cbf8e4ec-98c0-482e-8c19-b2753e0be576">

<img width="910" alt="image" src="https://github.com/dromara/hutool/assets/23078024/8dd192f5-f523-43a1-a3b1-88d40e34159a">

**Comment by 2-tong** [comment]
![image](https://github.com/dromara/hutool/assets/22452555/0a1b6c4e-ebbe-4ed3-8242-8e06693a1f2b)

JSON格式是错的。建议先JSONUtil.toJsonStr()看看格式正确的json是什么样子的。

**Comment by Yiuman** [comment]
这个字符串就是JSONUtil.toJsonStr()序列化对象出来的

**Comment by Yiuman** [comment]
阿知道了 经过某框架 转了两次
