### ISSUE TITLE
YamlUtil.dump写入文件之后第一行会有个!!xxxx这个东西，怎么去掉？

### ISSUE THREAD

**Issue by mayu3952678** [looly/hutool#3545]
```java
YamlUtil.dump(prometheusConfig, fileWriter);
```

![image](https://github.com/dromara/hutool/assets/59637162/6ce9b044-27b7-48d2-96f6-52cba6764b97)

**Comment by looly** [comment]
我想你Bean中是否存在一个子对象？

具体看下Yaml语法，`!!`表示一个强制对象类型。
