### ISSUE TITLE
JSONUtil.toList导致内存泄漏

### ISSUE THREAD

**Issue by 1316151417** [looly/hutool#3547]
### 版本情况

hutool版本： 5.8.10

### 问题描述（包括截图）
RSS内存监控，会随着时间一直增加，像是内存泄漏，将hutool的JSONUtil.toList改为jackson后重新压测，就没问题了。
hutool的压测RSS监控：
![image](https://github.com/dromara/hutool/assets/30792405/fd2b3467-62e4-4439-ac0a-913a6e3dcb49)
jackson的压测RSS监控：
<img width="780" alt="image" src="https://github.com/dromara/hutool/assets/30792405/6061fae0-9e81-437c-8447-2babff6a30b1">

**Comment by looly** [comment]
可能的问题是：

1. 在toList转换时，如果element为bean，涉及到bean拷贝，因此内存使用肯定上升

2. 在bean拷贝时，会缓存bean的描述信息，可能导致缓存内容没有释放

方便的话提供下测试代码和监测方式（是否可以看下USS的变化？）

补充后打开此issue。
