### ISSUE TITLE
关于MailUtil的使用

### ISSUE THREAD

**Issue by DengSinkiang** [looly/hutool#355]
第一次发送成功之后，无论怎么修改配置都能发送成功，如果重启服务器，配置就会生效。
![image](https://user-images.githubusercontent.com/40330921/57498704-8e437500-730f-11e9-91e2-6c35e00318e8.png)

**Comment by DengSinkiang** [comment]
![image](https://user-images.githubusercontent.com/40330921/57498693-7e2b9580-730f-11e9-88ad-b666278c0713.png)

**Comment by looly** [comment]
检查emailConfig，修改配置文件需要重新读取配置文件。
