### ISSUE TITLE
RuntimeUtil.exeForstr 执行psexe 获取不到日志

### ISSUE THREAD

**Issue by wlf2r** [looly/hutool#3554]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.0.m4

RuntimeUtil.exeForstr(cmd);

psexec 执行ping 获取不到日志
 
cmd 手动执行可以

**Comment by looly** [comment]
ping命令是个交互命令，因此exeForStr无返回或卡死。使用`exec`试下。

**Comment by wlf2r** [comment]
只能取到一行内容
