### ISSUE TITLE
TreeUtil扩展

### ISSUE THREAD

**Issue by dujiecn** [looly/hutool#3555]
<img width="717" alt="image" src="https://github.com/dromara/hutool/assets/10645118/2bcb364a-f2f0-4ff1-a321-e56d3109f348">
这个树的工具类，是否可以提供一个方法，该方法支持传入一个Tree对象和一个集合，目的是把这个集合数据正确挂在到Tree对象中

**Comment by looly** [comment]
可以自定义`NodeParser`
