### ISSUE TITLE
[Hutool-Captcha] 无法生成透明背景的验证码

### ISSUE THREAD

**Issue by Whitroom** [looly/hutool#3558]
### 版本情况

JDK版本：    openjdk 17.0.9 dragonwell
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
package com.example;

import java.awt.Color;

import cn.hutool.captcha.CircleCaptcha;
import cn.hutool.captcha.generator.MathGenerator;

public class Main {
    public static void main(String[] args) {
        MathGenerator mathGenerator = new MathGenerator(1);
        CircleCaptcha circleCaptcha = new CircleCaptcha(130, 25, 0, 0);
        circleCaptcha.setGenerator(mathGenerator);
        circleCaptcha.setBackground(new Color(255, 255, 255, 0));
        circleCaptcha.write("./captcha.png");
    }
}
```
2. 输出图片
![captcha](https://github.com/dromara/hutool/assets/56566522/82c6dc36-e9bd-499a-93e8-b8adfc5c3fb3)
3. 我们需要的效果
![captcha](https://github.com/dromara/hutool/assets/56566522/d5ffb4fe-123b-47ad-8e83-8fc1ce4219bc)
4. 可选的解决方案
在阅读源码的时候，发现`CircleCaptcha`类的`createImage`函数中创建了`BufferedImage`对象，并设定了`BufferedImage.TYPE_INT_RGB`，改成`BufferedImage.TYPE_INT_ARGB`就可以实现了(59行)。

其他类型的验证码也有一样的问题，有机会的话可以顺便改下😄。

**Comment by looly** [comment]
感谢。

5.8.28修改此处逻辑。

新逻辑是，当设置背景为`null`时，则背透明。
