### ISSUE TITLE
请问一下HttpUtil executeAsync方式是否需要手动关闭

### ISSUE THREAD

**Issue by zhangdp** [looly/hutool#3559]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
请问一下我写了一个方法传入url，通过http异步请求，返回响应的输入流，调用此方法的代码用完InputStream后会手动关闭，那么是否还需要关闭HttpResponse？如果要的话要在哪关闭？

1. 复现代码

```java
public InputStream download(String url) {
        HttpResponse response = HttpRequest.get(url)
                .addHeaders(createHeaders())
                .setConnectionTimeout(timeout)
                .setReadTimeout(readTimeout)
                .executeAsync();
        if (!response.isOk()) {
            throw new RuntimeException("http request fail: [" + response.getStatus() + "]" + response.body());
        }
        return response.bodyStream();
}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
需要。executeAsync打开了响应流，需要调用close方法。

**Comment by zhangdp** [comment]
> 需要。executeAsync打开了响应流，需要调用close方法。

对于调用方来说拿到的是InputStream，但是HttpResponse这个对象是方法内部的变量如何在流读完之后调用HttpResponse.close()？

**Comment by looly** [comment]
@zhangdp 
![image](https://github.com/dromara/hutool/assets/1432613/5b6ddc03-47d7-4de1-9f5a-730d4c886206)
