### ISSUE TITLE
HttpUtil.toParams bug

### ISSUE THREAD

**Issue by SeriousMa** [looly/hutool#356]
![image](https://user-images.githubusercontent.com/464213/57515735-e6956980-7345-11e9-83f8-5dd736f1288b.png)
如果valueStr是个url并且带参数 URLUtil.encodeQuery会识别为域名参数来处理
valueStr=http://xxx.baidu.com?1=1&2=2

结果 http%3A%2F%2Fwww.baidu.com%3F1=1&2=2

&符号没有转义

**Comment by looly** [comment]
4.5.10修复此问题，感谢。

**Comment by SeriousMa** [comment]
什么时候release呢?

**Comment by SeriousMa** [comment]
@looly 什么时候release呢?
