### ISSUE TITLE
xml转jsonobject，xml标签中的字符串&amp;被转成了&

### ISSUE THREAD

**Issue by winnie-33** [looly/hutool#3560]
### 版本情况

JDK版本：    openjdk_8_401
hutool版本： 5.8.27

### 问题描述
xml转jsonobject，xml标签中的字符串&amp;被转成了&，可以做配置不要转吗?
![image](https://github.com/dromara/hutool/assets/21211414/4d0a3c01-f809-4878-90f7-dfea889e01f9)

代码这样写的
```java
String inPara= "<ROOT><ID>002317479934367853</ID><CONTENT>asdfadf&amp;21sdgzxv&amp;aasfasf</CONTENT></ROOT>";
        cn.hutool.json.JSONObject jsonObject2 = XML.toJSONObject(inPara, true);
```
第二个参数传true的原因是希望数字不要被转成数字型，需要全部都是字符串型

**Comment by winnie-33** [comment]
String inPara= "<ROOT><ID>002317479934367853</ID><CONTENT>asdfadf&amp;21sdgzxv&amp;aasfasf</CONTENT></ROOT>";
        cn.hutool.json.JSONObject jsonObject2 = XML.toJSONObject(inPara, true);

**Comment by looly** [comment]
这个转换是没问题的。

我简化你的XML：

```xml
<CONTENT>&amp;</CONTENT>
```

因为`&`是保留字符，因此在XML中需要转义，变成`&amp;`，这样在解析时会被反解析为`&`。

你如果想显示原本的内容`&amp;`，那你的内容必须为：

```xml
<CONTENT>&amp;amp;</CONTENT>
```

或者使用`CDATA`方式表示原始字符串：

```java
<![CDATA[&amp;]]>
```

在你的例子中为：

```java
String inPara= "<ROOT><ID>002317479934367853</ID><CONTENT><![CDATA[asdfadf&amp;21sdgzxv&amp;aasfasf]]></CONTENT></ROOT>";
JSONObject json = XML.toJSONObject(inPara, true);
```
