### ISSUE TITLE
isAM()无法正确识别centOS系统的时间

### ISSUE THREAD

**Issue by weiyin-lu** [looly/hutool#3564]
### 版本情况

JDK版本：    openjdk-17-jdk-alpine（docker镜像）
hutool版本：5.8.16

### 问题描述（包括截图）
在部署环境下，isAM()和isPM()无法正确识别centOS7.9系统的时间
1. 代码片段
```java
        if (DateUtil.date().isAM()) {
            // 执行某些操作
        } else {
            // 执行另一些操作
        }
```
2. 问题描述
在开发环境下此问题无法复现，部署到centOS 7.9下，该方法无法得出正确结果。
我通过区分上下午来分别进行不同的业务行为，但在部署后发现，在下午执行了上午的业务。
服务器上的本地时间正常，推测可能是hwclock获取到的时间是12小时制，date()只得到时分秒信息，直接通过24小时制判断上下午。

**Comment by looly** [comment]
@weiyin-lu 我猜可能是时区出了问题。你服务端的时区不对，导致小时有偏移，造成AM判断错误。

尝试在服务端打印时区（locale），或者使用Calendar检查当前时间的时区。

**Comment by weiyin-lu** [comment]
> @weiyin-lu 我猜可能是时区出了问题。你服务端的时区不对，导致小时有偏移，造成AM判断错误。
> 
> 尝试在服务端打印时区（locale），或者使用Calendar检查当前时间的时区。

感谢，确实是时区问题，我已解决。
使用docker部署没声明时区，用了默认的UTC，在docker里声明时区或者使用Calendar都可解决此问题。
