### ISSUE TITLE
JDK21 环境下 ClassUtil.scanPackage 失效

### ISSUE THREAD

**Issue by RedCarl** [looly/hutool#3565]
### 版本情况

JDK版本：    jdk21
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        Set<Class<?>> mapperClasses = ClassUtil.scanPackage("co.ooci.database.mapper");
        System.out.println(mapperClasses.size());
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
JDK21为多模块项目，扫描失败的原因可能为：

1. 不在一个模块中或打包后剔除掉了`co.ooci.database.mapper`这个包。
2. 两个模块ClassLoader不同，尝试自定义ClassLoader。
