### ISSUE TITLE
DateUtil在使用graalvm打包native之后，会有时区问题

### ISSUE THREAD

**Issue by seepine** [looly/hutool#3566]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

在linux环境上海时区，代码也设置了默认时区 `TimeZone.setDefault(TimeZone.getTimeZone("Asia/Shanghai"));`
DateUtil.date能够获取正确当前时间，转字符串后，会重复增加时区

```java
    System.out.println("DateUtil.date " + DateUtil.date());
    System.out.println("DateUtil.now " + DateUtil.now());

    var date = DateUtil.parse("2024-04-30 00:02:05");
    var startTime = DateUtil.beginOfDay(date).toStringDefaultTimeZone();
    var endTime = DateUtil.endOfDay(date).toStringDefaultTimeZone();
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://github.com/dromara/hutool/assets/93666053/9223694c-b4b4-4604-a415-b52554b877ec)

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我本地使用`GraalVM`确实没有复现，猜测：

1. DateUtil.now()使用缓存中的format，你修改了defaultTimeZone，但是缓存中未修改。

因此尝试手动设置下DateTime的timezone试下。

```java
 var date = DateUtil.parse("2024-04-30 00:02:05")
date.setTimeZone(TimeZone.getTimeZone("Asia/Shanghai"));
date.toString();
```

**Comment by seepine** [comment]
> 我本地使用`GraalVM`确实没有复现，猜测：
> 
> 1. DateUtil.now()使用缓存中的format，你修改了defaultTimeZone，但是缓存中未修改。
> 
> 因此尝试手动设置下DateTime的timezone试下。
> 
> ```java
>  var date = DateUtil.parse("2024-04-30 00:02:05")
> date.setTimeZone(TimeZone.getTimeZone("Asia/Shanghai"));
> date.toString();
> ```

使用quarkus打包graalvm，新建个干净的quarkus项目试试
