### ISSUE TITLE
为什么 Action 报错不打印异常堆栈

### ISSUE THREAD

**Issue by Mr-LiuDC** [looly/hutool#3568]
### 版本情况

JDK版本：    JDK 1.8
hutool版本： 5.8.26

### 问题描述
我用`SimpleServer`来实现简单的HTTP请求处理，为什么Action中报错了没打印任何堆栈异常信息？

1. 复现代码

```java
public class DemoAction implements Action {

    private final Log log = Log.get();

    @Override
    public void doAction(HttpServerRequest request, HttpServerResponse response) {
        int random = RandomUtil.randomInt(9);
        if (random % 2 == 0) {
            String msg = "Random number is even.";
            log.info(msg);
            response.write(msg);
        } else {
            String msg = "Random number is odd.";
            log.error(msg);
            throw new RuntimeException(msg);
        }
    }
}
```

<img width="1061" alt="1714826763594" src="https://github.com/dromara/hutool/assets/18117854/45a010a8-2a50-40b3-8eec-95c227bf8cd5">

**Comment by looly** [comment]
Hutool的log使用第三方Log框架，并根据引入包自动识别。

请检查第三方日志配置的info和error是否打开。

**Comment by Mr-LiuDC** [comment]
> Hutool的log使用第三方Log框架，并根据引入包自动识别。
> 
> 请检查第三方日志配置的info和error是否打开。

我截图里面是能够正常打印各个级别的日志，我问的是为什么没有异常堆栈信息，throw 的异常或者其他未捕获的未知异常都没有打印异常堆栈信息。

**Comment by looly** [comment]
@Mr-LiuDC sorry，理解错了。

要打印堆栈，需要传入Exception对象：

```java
log.error(e, msg);
```

**Comment by Mr-LiuDC** [comment]
你说的传入 Exception 对象是没问题的，下面这行没有打印堆栈是什么问题呢？

throw new RuntimeException(msg);

**Comment by Mr-LiuDC** [comment]
我举个例子，我在 Action 里面用 DBUtil 进行数据库的读写操作，当报了异常，如果没有手动进行 catch 异常并手动打印异常，控制台居然没有打印任何异常信息。

**Comment by looly** [comment]
@Mr-LiuDC  终于明白你的意思了。

在Action中抛出异常是会被`吃掉`的。

这个原因是` com. sun. net. httpserver`中`HttpHandler`的创建处理机制并不抛出异常，此时需要你自定义`com.sun.net.httpserver.Filter`或`cn.hutool.http.server.filter.HttpFilter`

```java
/**
 * 异常处理过滤器
 *
 * @author looly
 */
public abstract class ExceptionFilter implements HttpFilter {

	@Override
	public void doFilter(final HttpServerRequest req, final HttpServerResponse res, final Filter.Chain chain) {
		try {
			chain.doFilter(req.getHttpExchange());
		} catch (final Throwable e) {
			afterException(req, res, e);
		}
	}

	/**
	 * 异常之后的处理逻辑
	 *
	 * @param req {@link HttpServerRequest}
	 * @param res {@link HttpServerResponse}
	 * @param e   异常
	 */
	public abstract void afterException(final HttpServerRequest req, final HttpServerResponse res, final Throwable e);
}
```

**Comment by looly** [comment]
这块6.x做的比较完善，5.8.8会增加`ExceptionFilter`和`DefaultExceptionFilter`。

这样有了异常会打印在页面中：

```java
public class ExceptionServerTest {
	public static void main(final String[] args) {
		HttpUtil.createServer(8888)
			.addFilter(new DefaultExceptionFilter())
			.addAction("/", (req, res) -> {
				throw new RuntimeException("Test Exception");
			})
			.start();
	}
}
```

![image](https://github.com/dromara/hutool/assets/1432613/a254e412-a7c9-442a-a458-2e119608235c)

**Comment by Mr-LiuDC** [comment]
@looly  非常感谢你的耐心解答。
