### ISSUE TITLE
请问有没有时间相互转换的工具？

### ISSUE THREAD

**Issue by lihaojiee** [looly/hutool#3572]
类似这种，可以转成任意时间单位，支持浮点数
![微信截图_20240506195629](https://github.com/dromara/hutool/assets/111339446/66242972-51fa-43a6-bd8d-61f7a99d3449)

**Comment by CherryRum** [comment]
没有支持浮点数的

**Comment by lihaojiee** [comment]
支持整数的是哪个？

**Comment by looly** [comment]
这个没有转换。

不过可以试下：`DateUtil.formatBetween`
