### ISSUE TITLE
FileTypeUtil 在分析 DOCX，PPTX，XLSX 文件类型时, 会被 ZIP 逻辑处理掉，不能被DOCX，PPTX，XLSX的match方法处理

### ISSUE THREAD

**Issue by cikecool** [looly/hutool#3573]
### 版本情况

JDK版本：    oracle jdk1.8.0_121
hutool版本：5.8.27（请确保最新尝试是否还有问题）

### 问题描述

1. FileTypeUtil 在分析 DOCX，PPTX，XLSX 文件类型时, 会被 ZIP 逻辑处理掉，不能被DOCX，PPTX，XLSX的match方法处理
2. DOCX，PPTX，XLSX 这个里面的 match 方法也无法正常识别 micro office 2010 创建的 DOCX，PPTX，XLSX

#### 相关代码和截图
1. 复现代码

```java
    public static void main(String[] args) {
        FileTypeUtil.getTypeByPath("d:\\123.xlsx");
        FileTypeUtil.getTypeByPath("d:\\123.pptx");
        FileTypeUtil.getTypeByPath("d:\\123.docx");
    }
```

![image](https://github.com/dromara/hutool/assets/33712457/a0d69383-63cd-414e-b1bf-dea48199e1e9)

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/dde3ed86-b699-446d-a2db-0bc5d3ef4016)

这块逻辑是这样的：

先发现是zip，则继续判断是否为office格式：

![image](https://github.com/dromara/hutool/assets/1432613/eee2bd3c-c49b-4c56-8e3b-5de093f19a46)

但是也会存在判断不准确的问题，这是文件本身的问题。考虑使用扩展名辅助判断。

**Comment by CherryRum** [comment]
还有一个问题，由于office文件的标识很容易被破坏，隐藏的也比较深（没有在前几十字节），所以建议您尝试下
<img width="1747" alt="image" src="https://github.com/dromara/hutool/assets/24296698/3baccce9-cdbb-418b-a997-9271439a3d83">
```java
 String typeByPath = FileTypeUtil.getType((FileUtil.getInputStream("/Users/lin/code/mine/java/hutool_test/src/main/java/org/example/sql/新建 Microsoft Word 文档.docx")),true);
```
本地测试应该没有问题，注意不要使用wps修改，这个我也没办法，他会写很多自己的信息到文件信息里面。
