### ISSUE TITLE
VelocityEngine 模板引擎找不到文件

### ISSUE THREAD

**Issue by 1164141376** [looly/hutool#3574]
VelocityEngine这个类
注释的这一行导致Velocity1.7老版本不可用，希望能够兼容老版本Velocity因为很多项目还是用的这个版本

				// 新版Velocity弃用
//			ve.setProperty("file.resource.loader.class", "org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
			ve.setProperty("resource.loader.file.class", "org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
				break;

版本：<dependency>
	<groupId>cn.hutool</groupId>
	<artifactId>hutool-extra</artifactId>
	<version>5.8.15</version>
</dependency>

**Comment by looly** [comment]
没办法，velocity新老版本冲突，Hutool封装没办法做到都兼容。
