### ISSUE TITLE
利用 JSR-305 元注释向支持 JSR-305 的常用工具指示 Java 中的可为空性

### ISSUE THREAD

**Issue by knightdreams6** [looly/hutool#3575]
![1715157847142](https://github.com/dromara/hutool/assets/34333488/b5005738-b283-4a3b-a47b-17081c1ec921)

**Comment by knightdreams6** [comment]
![image](https://github.com/dromara/hutool/assets/34333488/63e9e5c0-50cd-4754-b2dd-ee2a6445cae6)

**Comment by Createsequence** [comment]
一个非常有建设性的想法，在此之前也有人提过类似的建议。

不过，如果我们要这么做，那么就需要为核心模块额外的引入 checkframework、findbug 或者其他额外的第三方依赖库，这不符合 Hutool 非扩展模块对外部库零依赖的坚持。
