### ISSUE TITLE
关于@Alias注解的一些使用建议

### ISSUE THREAD

**Issue by funzj** [looly/hutool#3578]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在Excel导出设置别名时候与Bean属性复制 两个场景同时遇到, 原本使用 @Alias 是为了导出能设置中文名, 但属性复制的时候是为了避免导出一些无用字段, 想把字段复制到一个单独的BO 或者 VO的时候（字段名不变），就会因为 @Alias注解在这两个场景同时生效，导致的被复制出来的VO或者BO字段值都为null。
因为导出的场景基本字段都是中文，属性复制基本都是英文，所以建议还是在导出的时候用其他注解代替 @Alias 注解

1. 复现代码

```java
        List<ScriptExportVO> vos = BeanUtil.copyToList(list, ScriptExportVO.class);
        writer.setDefaultRowHeight(15);
        writer.write(vos);
        // 自适应列宽, 在write方法后调用生效
        writer.autoSizeColumnAll();
        Field[] fields = ReflectUtil.getFields(ScriptExportVO.class);
        for (int i = 0, fieldsLength = fields.length; i < fieldsLength; i++) {
            int columnWidth = writer.getSheet().getColumnWidth(i);
            writer.getSheet().setColumnWidth(i, columnWidth + 10);
        }
```

**Comment by looly** [comment]
@funzj 建议：

1. bean不添加设置中文的注解
2. 在ExcelWriter中使用`addHeaderAlias`方法添加导出别名。
