### ISSUE TITLE
db.settings 多数据源的时候 showSql 等配置不生效

### ISSUE THREAD

**Issue by gee1k** [looly/hutool#358]
db.settings 多数据源的时候 showSql 等配置不生效

**Comment by gee1k** [comment]
![image](https://user-images.githubusercontent.com/12059800/57566860-b8765f00-7403-11e9-805f-cd78669299fe.png)

**Comment by looly** [comment]
首先请升级Hutool到最近版本（当前4.5.9），其次showSql是个全局配置，应放在最开头，不应在任何分组下。请检查。

**Comment by gee1k** [comment]
那么 hikaricp 连接池配置项呢，是属于全局配置放在开头还是每个分组加一个

**Comment by looly** [comment]
这个是都可以识别的。
