### ISSUE TITLE
BeanUtil.setProperty 希望表达式可以支持list直接设置值

### ISSUE THREAD

**Issue by NieWeiChao** [looly/hutool#3580]
### 版本情况

JDK版本：    Oraclejdk1.8.0_401-b10
hutool版本： 5.8.X10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
请求实现新特性
BeanUtil.setProperty 希望可以支持list直接设置值，用下图这种方式，设置值会报空指针异常
![image](https://github.com/dromara/hutool/assets/18160403/3fbf06ad-421d-4541-aa94-f0fac7333c67)

1. 复现代码

- 对象中有list集合，然后list集合中的对象还有list集合，希望可以通过表达式一步到位，设置某个具体的字段值

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/18160403/40fa7979-d250-4d8e-8fbd-5ca1dbe8536b)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
可以考虑使用BeanPath。

**Comment by NieWeiChao** [comment]
> 可以考虑使用BeanPath。

大佬，beanpath如何使用能支持我这个场景，尝试了一下没实现效果

**Comment by NieWeiChao** [comment]
reopened

**Comment by looly** [comment]
@NieWeiChao 

```java
BeanPath.create([1].name).set(list, value);
```
