### ISSUE TITLE
DateUtil.format能否支持增加参数Locale 格式化成其他语言

### ISSUE THREAD

**Issue by a24211317** [looly/hutool#3585]
#437 问题跟这个类似 在format方法中应该是使用的默认Locale，能否支持参数设置
![image](https://github.com/dromara/hutool/assets/49759199/206e2d00-e457-4844-86a8-129ff028454a)

**Comment by looly** [comment]
可以使用：

![image](https://github.com/dromara/hutool/assets/1432613/c78b48af-fc79-4c2a-ad93-64371296da85)


即：

```java
DateUtil.format(xxx, DateUtil.newSimpleFormat(pattern, locale, timeZone));
```
