### ISSUE TITLE
关于ListUtil#setOrPadding的安全检查

### ISSUE THREAD

**Issue by Alleninggx** [looly/hutool#3586]
今天我在使用过程ListUtil:ListUtil#setOrPadding遇到了这个安全检验，翻看了一下，是由[#3286](https://github.com/dromara/hutool/issues/3286) issue提到后增加一个安全检验。

这里提出一下我的看法，我觉得hutool作为一个工具类，这些长度控制，限制了它作为工具的本质。
上诉issue中提到的问题，其实是应该程序员在编码过程中就应该注意规避的，而不是从工具上规避这个问题（或者说不能由工具给他兜底检查），工具加上这个检查，异常还是照样抛出，问题的根本没有解决。

如果加上这个检验，我不得不一开始就初始化这个数组，这就没这个工具本身的意义了。

附上工具截图
![image](https://github.com/dromara/hutool/assets/40049392/c421b12d-f81e-47f7-bcac-37e12e3a08e0)

**Comment by looly** [comment]
最然事实上是这样的，但是用户不合理的使用工具，如果这个参数是通过web方式传入，很容易造成OOM。

这种情况会被认定并上报为漏洞的，毕竟任何造成OOM的参数异常都应该被避免。

很多时候为了所谓安全，需要限定用户的很多行为，如果你的逻辑中无此隐患，考虑自行copy出来然后去掉检查代码。

**Comment by looly** [comment]
不过我考虑加个重载，可选是否检查这个参数。

5.8.28修改。

![image](https://github.com/dromara/hutool/assets/1432613/d2e5846c-0ad1-4ec9-90fc-47b0e6065974)
