### ISSUE TITLE
BooleanUtil.andOfWrap针对null取与结果与预期不符

### ISSUE THREAD

**Issue by nameizzz** [looly/hutool#3587]
### 版本情况

JDK版本：    1.8.0_45
hutool版本： 5.8.25

`BooleanUtil.andOfWrap(Boolean... array)`方法对`null`值处理有问题
![image](https://github.com/dromara/hutool/assets/43141910/718a42de-08c8-4a55-9554-5b45bcb55453)

1. 复现代码

```java
public static void main(String[] args) {
        Boolean boolean1 = true;
        Boolean boolean2 = null;
        Boolean result = BooleanUtil.andOfWrap(boolean1, boolean2);
        System.out.println(result);
    }
```
![image](https://github.com/dromara/hutool/assets/43141910/764c3cd4-d2e5-4197-9271-a81ffb9082c5)

此处使用`383`行`isFalse()`来跳出循环，当参数为`null`时，`isFalse()`返回`false`，无法跳出循环。
是否应更换为`!isTrue()`来跳出循环，还是`BooleanUtil.andOfWrap(Boolean... array)`就是这样设计的？
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.28修复此问题，感谢。
