### ISSUE TITLE
JSONObject.toBean为null问题

### ISSUE THREAD

**Issue by lsw1589034474** [looly/hutool#3588]
### 版本情况

JDK版本：    1.9
hutool版本： 5.8.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
JSONObject.toBean转都想为null,list循环转就没问题，只有一个对象得时候转就为null
![U E_0 6AA8~7(%)%B9_QB4](https://github.com/dromara/hutool/assets/54879658/a823125f-71c0-459f-823b-dd5b3387f47c)
![S44(ZIG) S)~W@2G2{KPK)9](https://github.com/dromara/hutool/assets/54879658/a039e4b2-9e3f-46e1-a5d8-a81dd1e9f3de)
![image](https://github.com/dromara/hutool/assets/54879658/ae439bfe-826d-464a-8e40-bc3a278a88ad)
![image](https://github.com/dromara/hutool/assets/54879658/e7beddfc-e699-4839-b9fb-d3fe1af6b83d)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
给一段测试的json

**Comment by lsw1589034474** [comment]
先将<Response><PK_Type><Name>GET_DATA_ACK</Name><Code>402</Code></PK_Type><Info><FsuId>51112643809002</FsuId><FsuCode>51112643809002</FsuCode><Values><DeviceList><Device Id="51112640709001" Code="51112640709001"><TSemaphore Type="3" Id="0407102001" MeasuredVal="30.29" SetupVal="" Status="0"/></Device></DeviceList></Values><Result>1</Result></Info></Response>通过XML.toJSONObject转为jsonobject

**Comment by looly** [comment]
@lsw1589034474 经过测试没有复现问题：

```java
String json = "{id: 1, code: 1122, tSemaphores: [{type: 1, status: 12}]}";
AttrData attrData = JSONUtil.toBean(json, AttrData.class);
Console.log(attrData);
```

看你的截图`tsemaphores`这个全用的小写，而非驼峰，应该是问题出在这里，那你需要使用`JSONConfig.create().setIgnoreCase(true)`:

```java
String json = "{id: 1, code: 1122, tsemaphores: [{type: 1, status: 12}]}";
AttrData attrData = JSONUtil.toBean(json, JSONConfig.create().setIgnoreCase(true), AttrData.class);
```
