### ISSUE TITLE
cn.hutool.http.HttpUtil#post(java.lang.String, java.lang.String) 这个方法按文档的标准参数调用报异常

### ISSUE THREAD

**Issue by songpaopao** [looly/hutool#3592]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
cn.hutool.http.IssueI7WZEOTest#postTest

{
    "code": 201,
    "msg": "解析失败"
}
```
![image](https://github.com/dromara/hutool/assets/41714029/354070e2-1c68-410a-be44-cf6f8bb1590b)

2. 堆栈信息
```
cn.hutool.http.HttpRequest#body(java.lang.String, java.lang.String)
原因在于这个方法在标准参数的时候 无法正确解析到content type
```

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这个远程接口失效或变更了。

我把test加ignore吧。

**Comment by songpaopao** [comment]
我想说明的是 
cn.hutool.http.HttpRequest#body(java.lang.String, java.lang.String)
原因在于这个方法在标准参数的时候 无法正确解析到content type
理论上按照文档是要塞一个的

**Comment by songpaopao** [comment]
![image](https://github.com/dromara/hutool/assets/41714029/6ee34a41-2e11-4d1e-a213-c39ba94f6ef2)
ho红框中的方法是进不去的

**Comment by looly** [comment]
对啊，当传入的是a=1&b=2这种时，是www-form-urlencode形式，这个非JSON也非XML，也可以不传，则默认是这个格式。

**Comment by songpaopao** [comment]
没问题 我理解错了  我想成form表单了  我的
