### ISSUE TITLE
需求请求：LocalDateTimeUtil.endOfDay重载一个接收LocalDate的方法

### ISSUE THREAD

**Issue by LeonemZhang** [looly/hutool#3594]
现在LocalDateTimeUtil.endOfDay只能接收LocalDateTime

希望可以重载一个接收LocalDate的方法

**Comment by looly** [comment]
LocalDate本身没有时间，也没有endOfDay的概念吧。

**Comment by LeonemZhang** [comment]
怎么没有呢？jdk提供了atStartOfDay
![image](https://github.com/dromara/hutool/assets/50519058/d1c02c25-b105-4996-95c4-e10c9236a45f)

但是没有提供endOfDay,只不过要获取一天的结束要写成：
![image](https://github.com/dromara/hutool/assets/50519058/6b8ba889-b7ad-4e88-9e0e-743ce9bfe78a)

**Comment by LeonemZhang** [comment]
贵项目的issue关的也太快了吧，多交流交流再关未尝不可吧

**Comment by looly** [comment]
@LeonemZhang 我明白了，你要参数是LocalDate，返回值还是LocalDateTime。

5.8.28增加重载。
