### ISSUE TITLE
贵团队有支持JPMS的计划吗？

### ISSUE THREAD

**Issue by lk101** [looly/hutool#3597]
### 版本情况

JDK版本：    openjdk_azul-21.0.3
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

使用jlink进行打包时，提示无法处理自动模块。

贵团队有支持Jigraw(JPMS)的计划吗？

**Comment by looly** [comment]
现在为了兼容JDK8，使用自动模块。

6.x中做了自动模块的兼容，你可以试下。

正式抛弃jdk8需要等到7.x了。
