### ISSUE TITLE
NumberUtil.pow(3,-2)  指数不能为负数

### ISSUE THREAD

**Issue by lilanlong** [looly/hutool#3598]
### 版本情况

JDK版本：    jdk1.8.0_131
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![image](https://github.com/dromara/hutool/assets/18063071/f62ca18c-a040-48b8-b62f-642576182398)

**Comment by looly** [comment]
此方法调用了`BigDecimal#pow`，可以看到注释是不支持负数指数的。

![image](https://github.com/dromara/hutool/assets/1432613/720f8bd0-cd65-45d6-a301-e5eb252b0435)

**Comment by lilanlong** [comment]
这个看到了，那这样会造成NumberUtil.pow无法正常使用

**Comment by looly** [comment]
@lilanlong 5.8.28增加负数支持。
