### ISSUE TITLE
关于 ArrayUtil.java 中  join(T[] array, CharSequence conjunction) 方法的逻辑

### ISSUE THREAD

**Issue by Yixiaohan** [looly/hutool#36]
https://github.com/looly/hutool/blob/c147a449bb0ff859d4d7a319d50fcb57e177d119/hutool-core/src/main/java/com/xiaoleilu/hutool/util/ArrayUtil.java#L1433

https://github.com/looly/hutool/blob/c147a449bb0ff859d4d7a319d50fcb57e177d119/hutool-core/src/main/java/com/xiaoleilu/hutool/util/ArrayUtil.java#L1435

感觉 L1433、L1435 逻辑有问题

**Comment by looly** [comment]
这么写应该是没有问题吧？有何逻辑问题？
