### ISSUE TITLE
【question】请问一下hutool有直接读取并返回X509Certificate的方法吗？

### ISSUE THREAD

**Issue by BestQwerty** [looly/hutool#3602]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.4

### 问题描述（包括截图）
cn.hutool.crypto.KeyUtil.readCertificate：
![image](https://github.com/dromara/hutool/assets/44726454/7d631b22-eecb-4145-909e-5d288876b4c7)

 Certificate certificate = KeyUtil.readX509Certificate(new ByteArrayInputStream(ConvertTool.base64ToByte(cert)));
返回的是Certificate类，请问一下有直接返回X509Certificate的吗？看了文档未找到相关的方法。

**Comment by BestQwerty** [comment]
请问一下密码证书相关的工具类有吗?文档未找到

**Comment by changhr2013** [comment]
`X509Certificate` 是很上层的一个抽象类，直接强转就可以。
