### ISSUE TITLE
ListUtil 需要一个【元素移动】的方法

### ISSUE THREAD

**Issue by LouisLiu00** [looly/hutool#3603]
### 任务需求：
将一个 List 集合中的一个指定元素移动到指定的下标，而不是元素交换。

### 举例：
```
List<String> list = new ArrayList(){{
  add("A");
  add("B");
  add("C");
  add("D");
}};

ListUtil.moveTo(list, "B", list.size() - 1);
```
### 结果：
原：["A", "B", "C", "D"]
现：["A", "C", "D", "B"]

### 附加：
1. 如果是对象集合，可以根据对象的某一个属性进行匹配；
2. 如果有重复元素，可以只匹配第一次出现的；
3. 若考虑不周，可以持续交流！

**Comment by looly** [comment]
5.8.29增加move方法。
