### ISSUE TITLE
[程序崩溃]JDK11 + HuTool5.7.5 偶发程序崩溃问题

### ISSUE THREAD

**Issue by rexlin600** [looly/hutool#3609]
### 版本情况

JDK版本：    JDK 11.0.2
hutool版本： 5.7.5

### 问题描述（包括截图）

1. 复现代码

```java
// 简单的对象拷贝
BeanUtil.copyProperties(socialInsurancePlanVo,MultiInsurancePlanVo.class)
```

场景：大批量的数据查询，大对象拷贝

2. 堆栈信息
<img width="1671" alt="image" src="https://github.com/dromara/hutool/assets/23032549/93155b49-6a10-4793-8817-64348347c271">

**Comment by looly** [comment]
类似于：https://github.com/dromara/hutool/issues/1828

@rexlin600 我猜测是：

1. 大量拷贝导致堆或栈满了。

考虑：
1. 最新版本改为使用`MethodHandle`方式触发反射，看是有改观
2. 使用Spring或Commons的BeanUtils.copyProperties拷贝Bean对象
3. 使用CglibUtil拷贝bean对象

后续有补充再打开此issue。
