### ISSUE TITLE
希望给 ImgUtil.convert 图片类型转换添加 webp 转换支持

### ISSUE THREAD

**Issue by xiaoACE6716** [looly/hutool#3610]
如题，请问开发者们是否有想法添加 webp 转 png、jpg等方法

**Comment by changhr2013** [comment]
这是要转 ChatGPT 输出的图片吗😂，可以看看 JavaCV，我感觉这种专业性太强的特殊领域功能，hutool 放进来应该也不太好维护。

**Comment by looly** [comment]
考虑一些第三方库吧，如：https://github.com/sejda-pdf/webp-imageio
