### ISSUE TITLE
希望加个银行卡校验算法Luhn

### ISSUE THREAD

**Issue by kiritokun07** [looly/hutool#3611]
在线银行卡合法性校验工具
https://uutool.cn/bank-card-validate/
https://uutool.cn/bank-card-batch/

**Comment by kiritokun07** [comment]
Java银行卡校验
https://blog.csdn.net/PioneerOneLi/article/details/107487886

**Comment by looly** [comment]
@kiritokun07 

见：https://github.com/dromara/hutool/issues/2510

部分江苏银行 交通银行 中国工商部分的借记卡等都不符合这个规范，没法封装，封装了会被一顿怼。
