### ISSUE TITLE
文档注释有误

### ISSUE THREAD

**Issue by Vec9527** [looly/hutool#3612]
### 版本情况
hutool版本：5.8.28

### 问题描述（包括截图）

1. cn.hutool.cache.Cache的V get(K key, boolean isUpdateLastAccess, Func0<V> supplier);方法注释有误, 即'调用此方法时，会检查上次调用时间，如果与当前时间差值大于超时时间返回{@code null}，否则返回值。', 应改为'调用此方法时，会检查上次调用时间，如果与当前时间差值大于超时时间返回Func0回调产生的对象，否则返回值。'.  其他有参数Func0<V> supplier的get方法注释也是一样有问题, 容易误导使用者不敢使用这些方法. 原码截图如下:
![1718087538848](https://github.com/dromara/hutool/assets/54059130/1111f706-f8e6-47df-8689-62704747e0fd)

**Comment by looly** [comment]
5.8.29修复注释，感谢~~
