### ISSUE TITLE
JsonUtil.toBean()泛型问题

### ISSUE THREAD

**Issue by 798284909** [looly/hutool#3616]
### 版本情况

JDK版本：    jdk1.8
hutool版本： 5.8.28

### 问题描述（包括截图）
我从接口拿来的json，然后想用toBean方法转成一个ResultInvokeWrapper<List<UserSelectDto>>>中。
ResultInvokeWrapper为http请求结果包装类，就是code，msg之类的字段
UserSelectDto是list里面每个对象的java类
`{
	"code": 0,
	"msg": "操作成功",
	"obj": [{
		"id": "1783051742205833217",
		"version": 9,
		"deleted": 0,
		"createDate": "2024-04-24 16:33:58",
		"updateDate": "2024-05-30 10:40:49",
		"creator": "",
		"updater": "",
		"username": "abc",
		"password": "",
		"email": "",
		"status": true,
		"mobile": "13012341234",
		"employeeNo": "",
		"headImg": null,
		"name": "钱",
		"manageUser": true,
		"leader": false,
		"displayOrgCode": "001",
		"displayOrgName": null,
		"roleName": null,
		"roleIdsStr": "",
		"roleIds": [],
		"subSystem": "RLZY",
		"subSystemName": "系统",
		"forceUpdatePwd": true,
		"userExpands": [],
		"position": "INVESTMENT",
		"positionText": null
	}],
	"success": true
}`

![image](https://github.com/dromara/hutool/assets/29478932/67fa6cbe-6aa8-485e-9615-6f4d64313ce9)
![image](https://github.com/dromara/hutool/assets/29478932/691bc38c-75fc-4fb7-82c5-966d2f7cebfc)
![image](https://github.com/dromara/hutool/assets/29478932/fba8eaca-da1d-49f8-8005-0129f00e4d1c)
toBean后拿到的是JsonArray嵌套JsonObject，请问这是为啥。
![image](https://github.com/dromara/hutool/assets/29478932/03c5e08f-e99a-46bb-84ea-41aed4a86abd)

**Comment by 798284909** [comment]
已发现问题，第一层的ResultInvokeWrapper继承了JsonResult。我把这个继承去掉就可以了。这是为啥呢？

**Comment by looly** [comment]
@798284909 应该是泛型类型获取错误导致的。

你继承`JsonResult`，我不知道这对象是什么样子，猜测可能实现了Map，导致被识别为Map而非Bean。

后续有补充请再打开此issue。

**Comment by 798284909** [comment]
![image](https://github.com/dromara/hutool/assets/29478932/8b63fff2-cea3-4823-960b-b2c237022eaf)
![image](https://github.com/dromara/hutool/assets/29478932/02be51a5-e052-4ad9-bdc8-b5a4dd915916)
不是map。就是单纯的实体类。

**Comment by looly** [comment]
@798284909 明白了，父类中的泛型没有识别成功。

obj的类型为泛型，但是定义在了父类中，识别时由于类型擦除，只识别到了当前类的泛型类型，父类泛型类型并未识别到，导致认定为Object类型。

要想正确识别类型，需要调用`toBean`时使用`TypeReference`指定泛型类型。

**Comment by 798284909** [comment]
好的吧，我也猜测是泛型擦除，但是套的太多了，我也看的晕。。。以后用的时候尽量注意吧~

**Comment by 798284909** [comment]
> @798284909 明白了，父类中的泛型没有识别成功。
> 
> obj的类型为泛型，但是定义在了父类中，识别时由于类型擦除，只识别到了当前类的泛型类型，父类泛型类型并未识别到，导致认定为Object类型。
> 
> 要想正确识别类型，需要调用`toBean`时使用`TypeReference`指定泛型类型。



> @798284909 明白了，父类中的泛型没有识别成功。
> 
> obj的类型为泛型，但是定义在了父类中，识别时由于类型擦除，只识别到了当前类的泛型类型，父类泛型类型并未识别到，导致认定为Object类型。
> 
> 要想正确识别类型，需要调用`toBean`时使用`TypeReference`指定泛型类型。

谢谢老板
