### ISSUE TITLE
DateUtil.offset空指针NullPointerException

### ISSUE THREAD

**Issue by wanghuizuo** [looly/hutool#3617]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.27（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
DateUtil.offsetDay(null, 1)
```

2. 堆栈信息
java.lang.NullPointerException: Cannot invoke "cn.hutool.core.date.DateTime.offset(cn.hutool.core.date.DateField, int)" because the return value of "cn.hutool.core.date.DateUtil.dateNew(java.util.Date)" is null
	at cn.hutool.core.date.DateUtil.offset(DateUtil.java:1451) ~[hutool-all-5.8.27.jar!/:5.8.27]
	at cn.hutool.core.date.DateUtil.offsetDay(DateUtil.java:1417) ~[hutool-all-5.8.27.jar!/:5.8.27]

4. 测试涉及到的文件（注意脱密）

5. 期望解决方案
```java
public static DateTime offset(Date date, DateField dateField, int offset) {
		if (date == null) {
			return null;
		}
		return dateNew(date).offset(dateField, offset);
	}
```

**Comment by looly** [comment]
5.8.29修复此问题，感谢。
