### ISSUE TITLE
ZipUtil 新增方法建议

### ISSUE THREAD

**Issue by gaoxs1985** [looly/hutool#3621]
### 版本情况

hutool版本： 5.8.27

### 问题描述（包括截图）
使用ZipUtil.unzip进行压缩包解压，遇到Zip bomb attack detected, invalid sizes: compressed 175, uncompressed 163328

源文件为doc文档

看源码发现只能在 ZipReader  setMaxSizeDiff中调整maxSizeDiff，是否可以在ZipUtil类中增加对应方法

**Comment by looly** [comment]
5.8.28修复了这个问题：

![image](https://github.com/dromara/hutool/assets/1432613/f29015be-98ef-4ca7-8427-5d07e807b274)


也可以使用`ZipReader.setMaxSizeDiff(-1)`关闭检查。

**Comment by poenel** [comment]
> 5.8.28修复了这个问题：
> 
> ![image](https://private-user-images.githubusercontent.com/1432613/340172449-f29015be-98ef-4ca7-8427-5d07e807b274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODg4MzUsIm5iZiI6MTcyNDk4ODUzNSwicGF0aCI6Ii8xNDMyNjEzLzM0MDE3MjQ0OS1mMjkwMTViZS05OGVmLTRjYTctODQyNy01ZDA3ZTgwN2IyNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDMyODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRkNDViNTM0YTZhYmEwYTg2N2Q5MjE3OTE0ZWIzMzIzMTQyMTg0YmNlOGQ4YmJmZDk5Mzc1MDM5NmJlYmQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.at5D3shxktXifJQo2Z5nfkOkw-7ual_kj1YZP2uz5D0)
> 
> 也可以使用`ZipReader.setMaxSizeDiff(-1)`关闭检查。

这个问题解决了吗？在5.8.25能静态设置参数了吗？

**Comment by looly** [comment]
@poenel 解决了

**Comment by poenel** [comment]
> @poenel 解决了

![1724988976277](https://github.com/user-attachments/assets/b1708f9b-55ed-4672-b0df-821c6d14ec96)
对不起，刚才我写的版本打错了，我这个是5.8.28，但是这个set是个成员方法，怎么自定义呢？

**Comment by looly** [comment]
@poenel 只能自行构建ZipReader
