### ISSUE TITLE
5.8.24  ClassNotFoundException: Unable to resolve class: cn.hutool.core.bean.BeanUtil

### ISSUE THREAD

**Issue by chenmeiye666** [looly/hutool#3623]
### 版本情况

JDK版本：    openjdk version "1.8.0_362"
hutool版本： 5.8.24

### 问题描述
我使用的BeanUtil的beanToMap 方法。但是会产生ClassNotFoundException的问题，我能确定我的代码中没有jar冲突，我通过arthas查看类加载，反编译都没有问题，但是执行那个方法就是会有异常ClassNotFoundException。
![image](https://github.com/dromara/hutool/assets/139849806/22378ed9-222f-4564-b5c7-70eb72631636)

1. 复现代码

```java
Map<String, Object> paramMap = BeanUtil.beanToMap(xxlJobInfo);
```

2. 堆栈信息
![image](https://github.com/dromara/hutool/assets/139849806/06595019-1345-43a9-a424-0ad53dab8f4f)

**Comment by looly** [comment]
目测应该是版本冲突。

请检查是否引入多个版本的Hutool，包括第三方关联引入的包，还有就是hutool-xxx和hutool-all如果版本不一致也不能共存。

**Comment by chenmeiye666** [comment]
![image](https://github.com/dromara/hutool/assets/139849806/c1108084-4f2e-4ff7-80b2-880e72b38664)
这种情况下不可能是jar包冲突吧？ 而且我看arthas 的类加载是正常的

**Comment by chenmeiye666** [comment]
![image](https://github.com/dromara/hutool/assets/139849806/ecda7e36-46ac-4c7e-92a1-af71daa540fa)
这种情况不可能是jar包冲突吧，而且我看arthas的加载时正常的。

**Comment by looly** [comment]
@chenmeiye666 还有一种可能，就是XxlJobInfoServiceImpl这个类在更新Hutool后没有重新编译，你尝试重新编译打包下这个类所在jar。

![image](https://github.com/dromara/hutool/assets/1432613/2681a5dd-c0a9-41e2-b9fd-b673c9506c69)


事实上有这个可变长参数的方法，确实没有只有一个单独参数的方法，所以我猜你更新hutool而没有重新编译你的代码。

**Comment by chenmeiye666** [comment]
为什么需要重新编译？

**Comment by looly** [comment]
@chenmeiye666 具体的话应该是方法签名变更了导致的
