### ISSUE TITLE
对于HttpRequst，在请求header的contentType=multipart/form-data的情况下，怎么设置单项值contentType=application/json？

### ISSUE THREAD

**Issue by Fxiao1** [looly/hutool#3626]
### 版本情况

JDK版本：    openjdk_1.8
hutool版本： 5.7.10

### 问题描述（包括截图）
我想发起如下请求
![image](https://github.com/dromara/hutool/assets/40653617/43ef54ea-0014-4b31-a423-04d46a371ac8)
![image](https://github.com/dromara/hutool/assets/40653617/78c0ed44-1f3e-4348-b48a-3661f9405237)

接收端controller端的方法签名是：

```java
    @PostMapping("api/saveUser")
    public AjaxResult apiSavePUser(@RequestPart("photoUser") PhotoUser photoUser,
                           @RequestPart("passport") MultipartFile passport,
                           @RequestPart("driver") MultipartFile driver,
                           @RequestPart("idCard") MultipartFile idCard,
                           @RequestPart("masterDrawing") MultipartFile masterDrawing
                           ){
```
请问我应该怎么设置其中一项的contentType=application/json？

**Comment by Fxiao1** [comment]
我调用的方法如下：

```java
        HttpRequest httpRequest = HttpRequest.post(idPhotoUploadApi);
        HttpResponse response=httpRequest.form("photoUser", JSONUtil.toJsonStr(photoUser))
            .form("passport", passport)
            .form("driver", driver)
            .form("idCard", idCard)
            .form("masterDrawing", masterDrawing).execute();
```
然后服务端就会报错：Content type 'application/octet-stream' not supported

**Comment by looly** [comment]
form的value需要使用`HttpResource`包装一下：

```java
.form("xxx", new HttpResource(new StringResource(jsonValue), "application/json"));
```

**Comment by Fxiao1** [comment]
> ```java
> .form("xxx", new HttpResource(new StringResource(jsonValue), "application/json"));
> ```

请问其中的`HttpResource`是哪个类？我的项目中只能找到一个`org.springframework.web.servlet.resource.HttpResource`，并且还是个接口

![image](https://github.com/dromara/hutool/assets/40653617/a01df907-1624-405f-8d72-c96b3728646a)

**Comment by looly** [comment]
@Fxiao1 我想你需要升级下Hutool版本了。

**Comment by Fxiao1** [comment]
我已经更新到5.8.28了，还是找不到这个类
![image](https://github.com/dromara/hutool/assets/40653617/d42d4d5e-e0b8-4774-8e97-a86393454370)
![image](https://github.com/dromara/hutool/assets/40653617/b79f4f32-8525-47d4-bdac-d860a20a5cdf)

**Comment by looly** [comment]
@Fxiao1 `cn.hutool.http.HttpResource`

**Comment by Fxiao1** [comment]
确实在github中看到这个类了[HttpResource.java](https://github.com/dromara/hutool/blob/v5-master/hutool-http/src/main/java/cn/hutool/http/HttpResource.java)，但奇怪的是我本地就是找不到这个类，我再找找到底什么原因，感谢指导。

**Comment by looly** [comment]
@Fxiao1 建议重新build一下项目，把旧版本的Hutool排除掉。

**Comment by Fxiao1** [comment]
我的锅，这张截图都已经能找到了，我眼拙没看到，以为还是spring的那个同名接口
![image](https://github.com/dromara/hutool/assets/40653617/2a93af3a-07b7-4d2c-b77b-3fb96620cf63)

至此问题已解决，需要更新到新版本（5.8.28）的hutool就有了，我旧版本用的是5.7.10
