### ISSUE TITLE
什么时候废弃com.jcraft.jsch，转而支持com.github.mwiede.jsch

### ISSUE THREAD

**Issue by yujianhua88** [looly/hutool#3627]
什么时候废弃com.jcraft.jsch，因为他2018年开始已经不更新，转而引入com.github.mwiede.jsch，旧版本的不支持openssh 的密钥文件

**Comment by looly** [comment]
这个是第三方维护版本吧？暂时不考虑更改，考虑可能在6.x中做支持。

这个issue暂时保留。

**Comment by binarywang** [comment]
楼主说的这个新的组件的github地址是什么？没找到

**Comment by looly** [comment]
https://github.com/mwiede/jsch

**Comment by looly** [comment]
@binarywang 看了下第三方维护库的情况，你在使用时只要把Maven坐标换一下即可，代码不用变动。

Hutool中对Jsch也是可选引入，用户自行更改Maven坐标即可。
