### ISSUE TITLE
请教下JschUtil里的exec 和 execByShell的区别是什么，能否在文档注释里描述清楚些？

### ISSUE THREAD

**Issue by binarywang** [looly/hutool#3628]
https://github.com/dromara/hutool/blob/38592915eb1e599fdd9a2ba66881b19dcdff7ee6/hutool-extra/src/main/java/cn/hutool/extra/ssh/JschUtil.java#L571

**Comment by looly** [comment]
![image](https://github.com/dromara/hutool/assets/1432613/4e645381-d7e5-4c9b-9722-8265e4047b33)


注释有说明。

**Comment by binarywang** [comment]
好吧，说的都是不会产生阻塞，但是我实际上使用两个都可能会产生阻塞

**Comment by looly** [comment]
@binarywang 可能是Jsch内部实现不同，我记得主要是是否读取环境变量的差别。

类似于直接执行和模拟打开shell终端的差别。
