### ISSUE TITLE
JSONUtil.toJsonStr 如何忽略别名@Alias()

### ISSUE THREAD

**Issue by 7757** [looly/hutool#3631]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 最新版（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
 
1、在使用ExcelReader解析excel的时候给实体类每个字段都加上了比如 name @Alias("姓名")
2、我想把读出来的每一行都转成json字符串存起来，JSONUtil.toJsonStr(rowData)，解析出来的是
{"姓名":value}而不是{"name":value}
3、如何才能让JSONUtil忽略别名，我看JSONUtil.toJsonStr(item, JSONConfig.create())JSONConfig中也没有可以设置忽略别名都配置

**Comment by looly** [comment]
@7757 你可以不加别名注解，而是使用`ExcelReader.addHeaderAlias`设置别名即可。
