### ISSUE TITLE
[Feature] Week添加ofChinese

### ISSUE THREAD

**Issue by loprx** [looly/hutool#3637]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： laster

### 问题描述（包括截图）

观察`Week Enum`里面没有`ofChinese`的转换，感觉可以添加一下

**Comment by looly** [comment]
5.8.29在Week.of中增加处理逻辑，可以识别星期日、周日之类名称。

**Comment by loprx** [comment]
Thank you~
