### ISSUE TITLE
[协议疑问]我可以在其他编程语言里移植Hutool吗？

### ISSUE THREAD

**Issue by xflcx1991** [looly/hutool#3638]
比如新招募预览的仓颉语言。我如果用Hutool的名字，用一样名字的API名字做一个库，这违反Hutool的协议吗？作者介意吗？

**Comment by xflcx1991** [comment]
在gitee提了，本issue关闭

**Comment by looly** [comment]
关联：https://gitee.com/dromara/hutool/issues/IA9D6E
