### ISSUE TITLE
Convert.toInt()设置默认值抛出异常

### ISSUE THREAD

**Issue by huixiangyang** [looly/hutool#364]
- 版本 4.5.10
- 代码
````

    public static void main(String[] args) {


        JSONArray array = new JSONArray();
        Integer aLong = Convert.toInt(array, -1);

        System.out.println(aLong);

    }
````

![image](https://user-images.githubusercontent.com/30469680/57772925-5b531400-7749-11e9-9fa3-a842f43cc2c3.png)

**Comment by looly** [comment]
新版中做了一些策略变更。

由于不抛异常无法排查潜在问题，因此默认抛异常。

4.5.11会增加convertQuietly方法。

感谢。
