### ISSUE TITLE
ClassUtil.scanPackageBySuper 偶发性报错，java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by Charles7c** [looly/hutool#3642]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.27

### 问题描述（包括截图）

生产中偶发性出现此问题。

1. 复现代码

```java
ClassUtil.scanPackageBySuper()
```

2. 堆栈信息
![1719890897691](https://github.com/dromara/hutool/assets/25446948/b3676d0c-6c92-4058-a130-22b68a19f9ff)

**Comment by looly** [comment]
考虑：不要并发调用此方法。

在多线程读取同一jar的时候，可能造成同时读被关闭问题。

如果还有报错，麻烦打开issue提供更多信息。

**Comment by Charles7c** [comment]
感谢
