### ISSUE TITLE
建议hutool-bom版本管理可以包含hutool-all

### ISSUE THREAD

**Issue by henry-hub** [looly/hutool#3643]
如题目前hutool-bom中版本管理不含hutool-all，引入hutool-bom版本管理后，如果需要使用hutool-all还需要单独管理或者指定版本

**Comment by looly** [comment]
https://doc.hutool.cn/pages/index/#%E5%BC%95%E5%85%A5

可以看下这里，既然使用了bom方式，就不需要使用all了，这两个是互斥的。
