### ISSUE TITLE
MailUtil附件应该不是必填参数

### ISSUE THREAD

**Issue by xqxyxchy** [looly/hutool#365]
邮件工具，附件应该可以传null，附件应该不是必填参数；

**Comment by xqxyxchy** [comment]
![TIM截图20190516134940](https://user-images.githubusercontent.com/21134578/57829464-9ef95c80-77e1-11e9-99b5-f6b22568eae4.png)

**Comment by looly** [comment]
4.5.11做改进。感谢。
