### ISSUE TITLE
byte[]和数值转换问题咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#3650]
NumberUtil.fromUnsignedByteArray这方法的入参是个byte[]，但是没有指定大端小端，意思是这种转换跟大端小端没关系吗？

还有ByteUtil.byteToUnsignedInt只支持byte，有没有那种数值转无符号位的？比方说负数short转成正数的int？

**Comment by looly** [comment]
1. 默认`big-endian`，默认包装了`BigInteger`的构造。

2. 这个没有。

**Comment by reixuemin** [comment]
这个有打算加上一些重载吗？支持大端小端？

**Comment by looly** [comment]
@reixuemin 欢迎提供参考的实现或PR。
