### ISSUE TITLE
csv字段分隔符只能设置单个字符

### ISSUE THREAD

**Issue by liyuu127** [looly/hutool#3652]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.16

### 问题描述（包括截图）

1. 复现代码

```java
	/**
	 * 字段分隔符，默认逗号','
	 */
	protected char fieldSeparator = CharUtil.COMMA;
```

工具提供的csv分隔符只能用于单个字符的场景，特殊情况下超过1个字符的分隔符石无法使用

**Comment by looly** [comment]
CSV工具确实只有单个字符的分隔符，不支持多个字符。否则会让整个CSV变得复杂。
