### ISSUE TITLE
HttpUtil工具get方法请求头Content-Type设置问题

### ISSUE THREAD

**Issue by a616766585** [looly/hutool#3658]
### 版本情况

JDK版本：    openjdk8-redhat 8u342-b07
hutool版本： 6.0.0-M6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

`org.dromara.hutool.http.HttpUtil#get(java.lang.String, java.util.Map<java.lang.String,java.lang.Object>)`
该方法请求头 Content-Type 设置有问题，charset重复，如截图所示
![image](https://github.com/user-attachments/assets/7dd062fe-408d-4cae-ae7d-7bdcbbcc8c8b)

原因在于
`org.dromara.hutool.http.client.body.HttpBody#getContentType(java.nio.charset.Charset)`
设置了一次
`org.dromara.hutool.http.meta.ContentType#build(java.lang.String, java.nio.charset.Charset)`
也设置了一次

1. 复现代码

```java
package cn.muzaijian.javajvm;

import org.dromara.hutool.http.HttpUtil;

import java.util.Collections;

public class testJava {
    public static void main(String[] args) {
        // 请注意这里一定使用带form参数的get方法，参数随便设什么都行，url也随便
        String resp = HttpUtil.get("https://timor.tech/api/holiday/year/2020-02", Collections.singletonMap("11", "22"));
        System.out.println(resp);
    }
}
```

2. 堆栈信息

无

3. 测试涉及到的文件（注意脱密）

无

**Comment by looly** [comment]
6.0.0-M15修复此问题~~
