### ISSUE TITLE
Convert.digitToChinese(0),按照标准读法应该返回“零元整”

### ISSUE THREAD

**Issue by he429134733** [looly/hutool#3662]
<dependency>
    <groupId>cn.hutool</groupId>
    <artifactId>hutool-all</artifactId>
    <version>5.8.16</version>
</dependency>

Convert.digitToChinese(0),按照标准读法应该返回“零元整”，现在返回的是“零”。这是不是一个问题？

**Comment by CherryRum** [comment]
@looly  路哥这个应该要修复下吧

**Comment by CherryRum** [comment]
**正确填写票据和结算凭证的基本规定** 

　　银行、单位和个人填写的各种票据和结算凭证是办理支付结算和现金收付的重要依据，直接关系到支付结算的准确、及时和安全。票据和结算凭证是银行、单位和个人凭以记载账务的会计凭证，是记载经济业务和明确经济责任的一种书面证明。因此，填写票据和结算凭证，必须做到标准化、规范化，要要素齐全、数字正确、字迹清晰、不错漏、不潦草，防止涂改。 

　　一、中文大写金额数字应用正楷或行书填写，如壹（壹）、贰（贰）、叁、肆（肆）、伍（伍）、陆（陆）、柒、捌、玖、拾、佰、仟、万（万）、亿、元、角、分、零、整（正）等字样。不得用一、二（两）、三、四、五、六、七、八、九、十、念、毛、另（或0）填写，不得自造简化字。如果金额数字书写中使用繁体字，如貳、陸、億、萬、圓的，也应受理。 

　　二、中文大写金额数字到“元”为止的，在“元”之后，应写“整”（或“正”）字，在“角”之后可以不写“整”（或“正”）字。大写金额数字有“分”的，“分”后面不写“整”（或“正”）字。 

　　三、中文大写金额数字前应标明“人民币”字样，大写金额数字应紧接“人民币”字样填写，不得留有空白。大写金额数字前未印“人民币”字样的，应加填“人民币”三字。在票据和结算凭证大写金额栏内不得预印固定的“仟、佰、拾、万、仟、伯、拾、元、角、分”字样。 

　　四、阿拉伯小写金额数字中有“0”时，中文大写应按照汉语语言规律、金额数字构成和防止涂改的要求进行书写。举例如下： 

　　（一）阿拉伯数字中间有“O”时，中文大写金额要写“零”字。如￥1，409．50，应写成人民币壹仟肆佰零玖元伍角。 

　　（二）阿拉伯数字中间连续有几个“0”时，中文大写金额中间可以只写一个“零”字。如￥6，007．14，应写成人民币陆仟零柒元壹角肆分。 

　　（三）阿拉伯金额数字万位或元位是“0”，或者数字中间连续有几个“0”，万位、元位也是“0’，但千位、角位不是“0”时，中文大写金额中可以只写一个零字，也可以不写“零”字。如￥1，680．32，应写成人民币壹仟陆佰捌拾元零叁角贰分，或者写成人民币壹仟陆佰捌拾元叁角贰分；又如￥107，000．53，应写成人民币壹拾万柒仟元零伍角叁分，或者写成人民币壹拾万零柒仟元伍角叁分。 

　　（四）阿拉伯金额数字角位是“0”，而分位不是“0”时，中文大写金额“元”后面应写“零”字。如￥16，409.02，应写成人民币壹万陆仟肆佰零玖元零贰分；又如￥325．04，应写成人民币叁佰贰拾伍元零肆分。 

　　五、阿拉伯小写金额数字前面，均应填写入民币符号“￥”（或草写：）。阿拉伯小写金额数字要认真填写，不得连写分辨不清。 

　　六、票据的出票日期必须使用中文大写。为防止变造票据的出禀日期，在填写月、日时，月为壹、贰和壹拾的，日为壹至玖和壹拾、贰拾和叁抬的，应在其前加“零”；日为抬壹至拾玖的，应在其前加“壹”。如1月15日，应写成零壹月壹拾伍日。再如10月20日，应写成零壹拾月零贰拾日。 

　　七、票据出票日期使用小写填写的，银行不予受理。大写日期未按要求规范填写的，银行可予受理，但由此造成损失的，由出票入自行承担。

**Comment by looly** [comment]
这个稍后处理。

**Comment by looly** [comment]
5.8.30修复此问题~~

**Comment by he429134733** [comment]
> 5.8.30修复此问题~~

还发现一个问题，0.75  标准读法应该是 零元柒角伍分，现在错误的读法是 柒角伍分

**Comment by looly** [comment]
@he429134733 按照票据规则，`零元`并不是必须的吧。

**Comment by he429134733** [comment]
> @he429134733 按照票据规则，`零元`并不是必须的吧。

网上到处看了下，有三种说法： 零元柒角伍分、圆柒角伍分、柒角伍分
都不知道哪个才是对的了
