### ISSUE TITLE
### 版本情况

### ISSUE THREAD

**Issue by yanye666** [looly/hutool#3667]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.29（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
旧版本 5.5.2 这个代码会返回[] list，但是最新版返回 ['']，这是个较大的语义改动？是否应该保留原语义，空串/null 都返回[] list

1. 复现代码

```java
        int sum = StrUtil.split("", ',').stream().mapToInt(Integer::parseInt).sum();  //预期无异常，实际异常 parseInt
        System.out.println(StrUtil.split("",',').size()); 预期返回0，实际返回1
```

__Originally posted by @yanye666 in https://github.com/dromara/hutool/issues/3660__

**Comment by looly** [comment]
重复：https://github.com/dromara/hutool/issues/3660

你打开原有issue即可。

原issue稍后回复。
