### ISSUE TITLE
hutool.cn首页无法打开

### ISSUE THREAD

**Issue by zaiyunduan** [looly/hutool#3668]
### 版本情况
无

### 问题描述（包括截图）

hutool.cn 使用了cdn，https://cdn.staticfile.org。该cdn因高安全风险，被防火墙禁止访问了，导致首页无法使用。

相关信息：
https://blog.feizhuqwq.com/86
https://juejin.cn/post/7385061036828917760

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
已经注意到相关情况，近期替换其它安全开放CDN，这个issue暂时保留。

**Comment by zonefile** [comment]
https://github.com/staticfile/static/issues/700#issuecomment-2245215079

看到这个 issue 了，建议不再使用 Staticfile，更换为 [zstatic](https://www.zstatic.net/docs/quick-start) 或者[南科大镜像](https://mirrors.sustech.edu.cn/help/cdnjs.html)，另外推荐加上 [sri integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)，cdnjs 上的库可以在 [cdnjs.com](https://cdnjs.com) 上找到，或者用 [srihash.org](https://srihash.org) 生成。

```diff
- https://cdn.staticfile.org
+ https://s4.zstatic.net/ajax/libs
+ https://mirrors.sustech.edu.cn/cdnjs/ajax/libs
```

**Comment by CherryRum** [comment]
@famousprince  非常感谢

**Comment by looly** [comment]
已经完成zstatic替换。
