### ISSUE TITLE
能否把CharSequenceUtil里的方法在StrUtil里重写以规避sonar检测

### ISSUE THREAD

**Issue by tianlongJ** [looly/hutool#3669]

**Comment by looly** [comment]
继承是为了代码管理规整。

sonar不允许继承么？

**Comment by tianlongJ** [comment]
> 继承是为了代码管理规整。
> 
> sonar不允许继承么？

允许继承，但是不允许使用派生类访问基类的方法，例如CharSequesceUtil.isBlank，如果使用StrUtil.isBlank就会出现警告"static" base class members should not be accessed via derived types，并且它是一个Critical问题，不能被忽略。StrUtil更符合使用习惯也更好敲。如果可能的话还是希望能在StrUtil里重写一个方法做一层调用，避免sonar检测

**Comment by looly** [comment]
@tianlongJ 我觉得工具类继承更像是别名作用，考虑给sonar提个issue？哈哈。

暂时没发现工具类继承调用父类方法有啥坏的后果。

**Comment by tianlongJ** [comment]
> "static" base class members should not be accessed via derived types

坏处是基本不会有，只是个代码维护性Maintainability的警告，只不过公司内部部署sonarqube时候会使用这些个sonar规则，就影响代码提交了。😁升级jar包做加法更方便一点嘛，即使sonar官方真的意外把这个规则去了，还得找公司负责维护的人battle把内部规则同步更麻烦一点😁，只是个建议，使用习惯罢了

**Comment by tianlongJ** [comment]
> @tianlongJ 我觉得工具类继承更像是别名作用，考虑给sonar提个issue？哈哈。
> 
> 暂时没发现工具类继承调用父类方法有啥坏的后果。

坏处是不会有，只不过sonar官方即使能去掉还要各个公司自己部署的sonarqube也跟着同步，感觉升级jar更方便一点嘛😁
