### ISSUE TITLE
6.0.0版本 BeanUtil会导致Metaspace溢出

### ISSUE THREAD

**Issue by test-bin-001** [looly/hutool#3671]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 6.0.0-M8

### 问题描述（包括截图）

1. 复现代码

![b03ef8a03a2e04de2987968b0b030664](https://github.com/user-attachments/assets/dc47265b-15d4-4a37-b9c8-4043ffce3f9a)

2. 堆栈信息

![1721877914353_3FA9ACE6-00B9-4820-B1EB-467414517A4A](https://github.com/user-attachments/assets/a5cb06de-9bfe-4c49-8b32-d09b9afb76cd)
![1721877931098_B13EEC11-8B4F-40cf-865C-8D2374B2D4C8](https://github.com/user-attachments/assets/4e310c56-43ff-4544-953e-9da0d8ac7107)
![lQLPJwskBfb2Rk_NAvDNB1-wmLz7ddADBswGi5lfIaNMAA_1887_752](https://github.com/user-attachments/assets/a0c8f219-9f6b-4f81-a9d8-844ee384250d)

**Comment by test-bin-001** [comment]
频繁GC会导致LambdaFactory产生的类在metaspace中堆积

**Comment by VampireAchao** [comment]
收到

**Comment by VampireAchao** [comment]
您好，麻烦能尝试最新版本还有这个问题吗，最好您方便的话帮忙给一个复现Demo供开发定位问题

**Comment by test-bin-001** [comment]
6.0.0-M8和M14都测试过了，复现就一直gc就行，每次gc之后执行BeanUtil的copyProperties方法LambdaFactory都会生成一批类，但是因为是弱引用，gc后就没了，但是类加载器中类不会被卸载，导致metaspace一直增长

**Comment by saberwangmi** [comment]
@VampireAchao  https://github.com/dromara/hutool/blob/v6-dev/hutool-core/src/main/java/org/dromara/hutool/core/func/LambdaFactory.java#L41 
这里使用的是WeakConcurrentMap，GC后就会移除生成的缓存，但是Metaspace中加载的class并不会被卸载而导致的内存泄漏

如图:这些Lambda的class在每次GC后生成都会生成
![image](https://github.com/user-attachments/assets/8b7c2832-fd70-4086-8d62-6b95327a7719)

**Comment by VampireAchao** [comment]
感谢！修复中

**Comment by VampireAchao** [comment]
https://gitee.com/dromara/hutool/issues/I99A2X

**Comment by looly** [comment]
@VampireAchao WeakCache中的对象被回收了，但是Lambda类加载器中的lambda对象没有回收。

**Comment by looly** [comment]
@test-bin-001 

来自 @CherryRum 的回答：

可以见：
https://github.com/openjdk/jdk/pull/12493

https://bugs.openjdk.org/browse/JDK-8302154

<img width="1240" alt="a9a50f5f5ba83917f1dc9ec29d7b5e3" src="https://github.com/user-attachments/assets/6ed51a63-a365-4f40-b784-395c3b43dc84">

jdk15改了 一个隐藏类，和 jdk8的lambda生成方式不同了

可能导致构建的lambda无法正常回收。

6.0.0-M15会改回使用MethodHandler反射方式。
