### ISSUE TITLE
HttpUtil post  响应结果乱码问题

### ISSUE THREAD

**Issue by shixiaoxianga** [looly/hutool#3672]
version：5.8.29

抓包工具响应结果

![image](https://github.com/user-attachments/assets/0dabb219-b180-4428-a4e9-0cc314723ddb)

代码如下

        HttpResponse httpResponse = HttpUtil.createPost(checkTicketUserCardApi)
                .body(bodyJson)
                .charset(StandardCharsets.UTF_8)
                .addResponseInterceptor(new HttpInterceptor<HttpResponse>() {
                    @Override
                    public void process(HttpResponse httpObj) {
                        System.out.println("1");
                    }
                })
                .headerMap(headerMap, true)
                .execute();
        int status = httpResponse.getStatus();
        String data = httpResponse.body();

接口响应头中的 Content-Type 也是 application/json;charset=UTF-8

打印data ：
F�֙���'�6&8�Jd[9�eA�Tĩ(�}'H$A8�a+Hވۍ@(b�;C!�\Vwȉ@����렼��%��oj���LH�d(�"(���9�$-���~��tf�kʣ������Ԍ��,ֵ���u��JNe n

我查看httpResponse.body字节长度为137实际应该不会这么少的（个人猜测作者可忽略）

**Comment by shixiaoxianga** [comment]
已解决

**Comment by friendbookok** [comment]
这个问题改了哪里？我遇到相同问题，但不能升级版本。看不到commit的代码

**Comment by looly** [comment]
@friendbookok 你需要自定义charset解析响应体。

**Comment by friendbookok** [comment]
对方响应内容里传了meta=gb2312过来，而且contentype里也没有传charset，所以进入这里做了特殊处理，导致解码失败。因此 httpResponse.charset(charsetStr).body()也是不行的,办法只能在外部处理，如下所示：
String responseBody = new String(httpResponse.bodyBytes(), charsetStr);

<img width="1335" height="693" alt="Image" src="https://github.com/user-attachments/assets/1dabf003-3046-4dd4-bde3-d94c3037d1b2" />
	public String body() throws HttpException {
		return HttpUtil.getString(bodyBytes(), this.charset, null == this.charsetFromResponse);
	}
