### ISSUE TITLE
是否可以提供简单点的AES加解密方法

### ISSUE THREAD

**Issue by liunancun** [looly/hutool#3678]
public static String encrypt(String data, String seed)
{
    if (StrUtil.isBlank(data))
    {
        return data;
    }

    KeyGenerator keyGenerator = KeyUtil.getKeyGenerator(SymmetricAlgorithm.AES.getValue());
    keyGenerator.init(128, RandomUtil.getSHA1PRNGRandom(seed.getBytes()));
    SecretKey secretKey = keyGenerator.generateKey();
    byte[] key = secretKey.getEncoded();
    return SecureUtil.aes(key).encryptBase64(data);
}

public static String decrypt(String data, String seed)
{
    if (StrUtil.isBlank(data))
    {
        return data;
    }

    KeyGenerator keyGenerator = KeyUtil.getKeyGenerator(SymmetricAlgorithm.AES.getValue());
    keyGenerator.init(128, RandomUtil.getSHA1PRNGRandom(seed.getBytes()));
    SecretKey secretKey = keyGenerator.generateKey();
    byte[] key = secretKey.getEncoded();
    return SecureUtil.aes(key).decryptStr(data);
}

当前要实现AES的加解密要写的代码比较多，能否提供简单一个方法就可以实现加解密的方法

**Comment by CherryRum** [comment]
```java
package org.example.test;

import cn.hutool.core.codec.Base64;
import cn.hutool.crypto.Mode;
import cn.hutool.crypto.Padding;
import cn.hutool.crypto.symmetric.AES;


/**
 * AES加密解密 demo
 * @author lin
 */
public class AESDemo {
    public static void main(String[] args) {
        // 待加密的原文
        String message = "hello world";
        // 密钥的 base64
        String key = "Pr0kS3abd8CYiIi6PDeU9g==";
        // 创建对称加密算法对象
        AES aes = new AES(Mode.ECB, Padding.PKCS5Padding, Base64.decode(key));
        String encrypted = aes.encryptBase64(message);
        System.out.println("加密：" + encrypted);

        String decrypted = aes.decryptStr(encrypted);
        System.out.println("解密：" + decrypted);
    }
}
```
这样呢，应该满足您需求吧
