### ISSUE TITLE
关于JSONUtil中字符串问题

### ISSUE THREAD

**Issue by he429134733** [looly/hutool#3679]
### 版本情况
 <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.16</version>
        </dependency>
JDK版本：    openjdk_8_201

### 问题描述（包括截图）
![image](https://github.com/user-attachments/assets/1252380f-88d8-4e52-a624-9de4673b279a)
使用的JSONUtil与jackson解析字符串结果不一致。不知道这算不算一个问题。

![image](https://github.com/user-attachments/assets/e7d71b4e-c73d-4a2e-aac6-207330698991)
hutool使用这种方法会报异常，无法直接转换
但是jackson是可以互相转换的
![image](https://github.com/user-attachments/assets/e4ad6942-ee7e-4a10-b3ac-129fda097b83)

使用的场景是，自己弄了一个redis工具，使用set方法存入数据，使用get取数据时，通过传入class类型来做反序列化。但是当使用的场景是普通字符串时，就报错了。

**Comment by looly** [comment]
这个并不算问题，而是5.x对于非标准的JSON字符串不支持。

比如"aaa"不是标准的JSON字符串，因此不被支持。

6.x此处会做一个兼容。
