### ISSUE TITLE
时间处理工具不支持 'rfc3339-date-time-string' 规范的格式

### ISSUE THREAD

**Issue by larrykoo711** [looly/hutool#368]
由于Hutool 时间处理中格式化使用的是 'SimpleDateFormat'，所有不能完整的支持各种时间字符串格式化；

例如：'rfc3339-date-time-string' : https://www.ietf.org/rfc/rfc3339.txt

发现这个问题，是我使用 Hutool 格式化 InfluxDB 返回的时间字符串时遇到的问题；
参考 InfluxDB 的时间格式：http://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#time-syntax

使用了'rfc3339-date-time-string' 如：''YYYY-MM-DDTHH:MM:SS.nnnnnnnnnZ'' 这样的格式；这种格式使用 SimpleDateFormat 无法正确的格式化。

建议：使用 JDK8 的 DateTimeFormatter 进行完整的时间格式化支持；

还有查了一下 google 有一个parseRfc3339(...) 的工具：
https://github.com/googleapis/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/util/DateTime.java

**Comment by looly** [comment]
这个可以解析，T加上单引号即可。

Hutool基于jdk7编译，因此jdk8新特性暂时无法单独支持。
