### ISSUE TITLE
关于JSONUtil序列化Optinal为空字典的问题，有办法可以获取到optional的值吗

### ISSUE THREAD

**Issue by fanqie03** [looly/hutool#3681]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.22（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public class GsonDemo {
    public static void main(String[] args) {

        Console.log(JSONUtil.toJsonStr(Optional.ofNullable("123")));
        Console.log(JSONUtil.toJsonStr(Optional.empty()));

    }
}

```
![image](https://github.com/user-attachments/assets/312a81c4-38fd-415f-9ddf-16bd2adfb825)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by CherryRum** [comment]
hutool的比较轻量，没做这个类型适配
![image](https://github.com/user-attachments/assets/6c0e39a9-b119-4b22-a6ee-0d4d8e15f183)
fastjson做了适配，暂时应该不会大动

**Comment by looly** [comment]
5.x不做变动，6.0.0-M15支持Optional
