### ISSUE TITLE
类似jackson的@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 的注解

### ISSUE THREAD

**Issue by wang12013** [looly/hutool#3683]
hutool会不会支持类似jackson的@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") 的注解，同一个项目因为要对应外部接口可能需要反序列化不同格式的json时间字符串

**Comment by looly** [comment]
如果你只对某个字段做注解，Hutool是不支持的。

此时考虑jackson这类库完成。
