### ISSUE TITLE
outlook 邮件发送是否支持 Oath2 认证方式

### ISSUE THREAD

**Issue by zq99299** [looly/hutool#3687]
### 版本情况

JDK版本：    openjdk_21
hutool版本： 5.8.29

### 问题描述

通过 smtp 协议使用 Mail  发送 [outlook 的邮件](https://support.microsoft.com/de-de/office/moderne-authentifizierungsmethoden-sind-jetzt-erforderlich-um-die-synchronisierung-von-outlook-e-mails-in-nicht-microsoft-e-mail-apps-fortzusetzen-c5d65390-9676-4763-b41f-d7986499a90d)，在 9 月份不再支持普通的用户名和密码认证了，要使用 Oath2 方式，不知 Mail 工具是否支持这种方式的认证
![a95281b9cc5f158294d9c02225053035](https://github.com/user-attachments/assets/21456d1d-c6a8-4412-aea0-eb706df6aaa6)

**Comment by looly** [comment]
我搜了几篇文章：

使用Gmail的Oauth2：https://kgiann78.github.io/java/gmail/2017/03/16/JavaMail-send-mail-at-Google-with-XOAUTH2/

使用Outlook的Oauth2：https://medium.com/@tempmailwithpassword/sending-emails-with-java-using-oauth2-and-office-365-b164d54f68fc

事实上，换成Oauth2登录后，你需要使用token方式而不是密码方式，但是微软的token生成貌似比较麻烦，你需要新建应用，然后借助`MSAL4J`这个库生成token。

```java
ConfidentialClientApplication app = ConfidentialClientApplication.builder("your-application-id", ClientCredentialFactory.createFromSecret("your-client-secret"))    .authority("https://login.microsoftonline.com/your-tenant-id")    .build();
IClientCredential credential = ClientCredentialFactory.createFromSecret("your-client-secret");
SilentParameters silentParameters = SilentParameters.builder(Collections.singleton("Mail.Send"))    .build();
IAuthenticationResult result = app.acquireTokenSilently(silentParameters).join();
String accessToken = result.accessToken();
```

然后使用Hutool：

```java
final MailAccount mailAccount = new MailAccount();
mailAccount.setHost("smtp.office365.com");
mailAccount.setPort(587);
mailAccount.setFrom("xxxx@outlook.com");
mailAccount.setUser("xxxx");
// 这里使用生成的token
mailAccount.setPass("token".toCharArray());
mailAccount.setAuth(true);
mailAccount.setStarttlsEnable(true);
// 这里关掉SSL
mailAccount.setSslEnable(false);
// 使用XOAUTH2
mailAccount.setCustomProperty("mail.smtp.auth.mechanisms", "XOAUTH2");
mailAccount.setCustomProperty("mail.smtp.auth.login.disable", "true");
mailAccount.setCustomProperty("mail.smtp.auth.plain.disable", "true");

final String id = Mail.of(mailAccount)
	.setTos("xxx@qq.com")
	.setContent("Mail test from Outlook!")
	.setTitle("测试Outlook邮件")
	.send();
```

我没测试过，你可以试下。

**Comment by zq99299** [comment]
嗯 好的，我看到也是通过自定义属性方式，以为hutool的工具没有自定义来着，我尝试成功再来回复具体方法

**Comment by zq99299** [comment]
已经尝试了：这是笔记，https://www.yuque.com/mrcode.cn/note-combat/iv6gmsr1qzsk4x06#CIkOg

结果如下： smtp 配置太繁琐，而且只能是租户内部账户才行
