### ISSUE TITLE
BeanUtil.copyProperties导致积压class不回收

### ISSUE THREAD

**Issue by taowater** [looly/hutool#3690]
### 版本情况

JDK版本：    openjdk_22
hutool版本： 5.8.29.（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
最近生产宕机，排查发现，使用BeanUtil.copyProperties，会产生Lambda相关class，并且无法回收，一直积压，最终compared class space oom

![06f5cb531df1d36e659d478a10b5107](https://github.com/user-attachments/assets/bac8ecc8-b454-4ba5-b6b2-ced1860bec68)
![e53540b7aff1b127df087f3513408c9](https://github.com/user-attachments/assets/1268482b-fa8e-4351-96b3-f9da9d261fa1)

1. 复现代码
```java
var user = new SysUser();
        Class clazz = SysUser.class;
        var user2 = new SysUser();
        var o = BeanUtil.copyProperties(user, user2, false);
        return ApiResponse.ok(o);
```

```java
Console.log("报错了");
```

不是运行时异常，而是应用累积class最终宕机。。使用Visualvm工具观测的内存情况
3. 堆栈信息

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
相关原因见：https://github.com/dromara/hutool/issues/3671

但是5.x只是使用了简单的反射方式调用setter方法注入，并没有动态创建lambda，也没有任何动态lambda的创建逻辑，且此问题也只存在于6.0的M14及版本以下。

麻烦检查下这些lambda是否在其他地方创建？

**Comment by ZZemptypoint** [comment]
我对这句代码有点疑问，hutool的`BeanUtil.copyProperties(Object,Object,boolean)`方法是没有返回值的
```java
 var o = BeanUtil.copyProperties(user, user2, false);
```

**Comment by CherryRum** [comment]
> ```java
> user
> ```

我还以为他用了
![image](https://github.com/user-attachments/assets/3864cd35-12ae-407d-a7ba-2c6f4ee4a22b)

**Comment by CherryRum** [comment]
> 我还以为他用了 ![image](https://private-user-images.githubusercontent.com/24296698/356439118-3864cd35-12ae-407d-a7ba-2c6f4ee4a22b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzAyNzMsIm5iZiI6MTcyMzE2OTk3MywicGF0aCI6Ii8yNDI5NjY5OC8zNTY0MzkxMTgtMzg2NGNkMzUtMTJhZS00MDdkLWE3YmEtMmM2ZjRlZTRhMjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAyMTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOGZiN2E2ZjhiOTU3YjhhZjRmZjY1ZTdhYTVkNTYzY2Q3ZDAxZDg0MmU4NGI1NzQ5ZTA0YmM2NGY5MGM0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9E4tSE_eIq-NJMI7ipbuBwInZgN9v5Xezqk8twbNL4Y)

**Comment by taowater** [comment]
> 我对这句话代码有点疑问，hutool的`BeanUtil.copyProperties(Object,Object,boolean)`方法是没有返回值的
> 
> ```java
>  var o = BeanUtil.copyProperties(user, user2, false);
> ```

有的，返回target

**Comment by CherryRum** [comment]
> > 我对这句话代码有点疑问，hutool的`BeanUtil.copyProperties(Object,Object,boolean)`方法是没有返回值的
> > ```java
> >  var o = BeanUtil.copyProperties(user, user2, false);
> > ```
> 
> 有的，返回target

能截个图吗？

**Comment by taowater** [comment]
> 相关原因见：#3671
> 
> 但是5.x只是使用了简单的反射方式调用setter方法注入，并没有动态创建lambda，也没有任何动态lambda的创建逻辑，且此问题也只存在于6.0的M14及版本以下。
> 
> 麻烦检查下这些lambda是否在其他地方创建？

对不起，我标错版本了，确实是6.0-M13,项目里面5.X和6.X都引入了

**Comment by CherryRum** [comment]
我就说嘛，5.x不会的，这个问题是jdk15修改lamda生成方式引起的

**Comment by taowater** [comment]
> > > 我对这句话代码有点疑问，hutool的`BeanUtil.copyProperties(Object,Object,boolean)`方法是没有返回值的
> > > ```java
> > >  var o = BeanUtil.copyProperties(user, user2, false);
> > > ```
> > 
> > 
> > 有的，返回target
> 
> 能截个图吗？

![image](https://github.com/user-attachments/assets/7485ed88-e8ad-4812-8986-0daaa93000bf)

**Comment by taowater** [comment]
> 我就说嘛，5.x不会的，这个问题是jdk15修改lamda生成方式引起的

抱歉抱歉，还好，升级版本就好了，不过为啥6.X版本不在github上有更新日志的？

**Comment by looly** [comment]
@taowater 好的。麻烦升级到6.0.0-M15测试，M15把Lambda动态生成去掉了。

**Comment by looly** [comment]
@taowater 现在M系列都是测试版本，测试版本变动极大，不会像正式版一样有changelog。等待release吧。
