### ISSUE TITLE
GraphicsUtil 接口变化，导致不兼容旧版本

### ISSUE THREAD

**Issue by cytihuntor** [looly/hutool#3694]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.30（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

最新的 5.8.30，这个修改，做了接口变化，强制增加了接口参数

![image](https://github.com/user-attachments/assets/23961316-f32d-453a-aaf3-4219b692af18)

**Comment by looly** [comment]
可能是我合并没有注意。

我检查下。

**Comment by looly** [comment]
![image](https://github.com/user-attachments/assets/cfb45425-7497-4a88-a1df-501b520e3243)

啊，合并PR确实没注意。

5.8.31加上。
