### ISSUE TITLE
升级5.8.30后ZipUtil压缩成流的方法报错、5.8.29没问题

### ISSUE THREAD

**Issue by Forevery1** [looly/hutool#3697]
### 版本情况

JDK版本：    jdk_21
hutool版本： 5.8.30（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        String ll = "/Downloads/test";
        File node = new File(ll);
        FileOutputStream fos = new FileOutputStream("/Downloads/test.zip");
        ZipUtil.zip(fos, CharsetUtil.CHARSET_UTF_8, false, null, node);
```

2. 堆栈信息
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/2098e8dc-96ac-4e11-96cf-569bf23f5d8c">

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Forevery1** [comment]
打断点发现是此次的问题、因为我是用的流、所以this.zipFile为null、所以报错了。如果zipFile是null应该跳过<img width="666" alt="image" src="https://github.com/user-attachments/assets/3ca85fcf-67a3-4e42-9813-804e70bd2b31">

**Comment by Forevery1** [comment]
@looly

**Comment by looly** [comment]
5.8.32修复此问题，感谢~~
