### ISSUE TITLE
[poi] [excel] ExcelReader调用read读取日期时，第一行数据类型是String，第二行开始是DateTime

### ISSUE THREAD

**Issue by pakchoily** [looly/hutool#3698]
### 版本情况

JDK版本：    openjdk_17.0.8
hutool版本： 5.8.31
poi-ooxml版本：5.3.0

### 问题描述
读取的list结果中，我期待日期始终保持一个格式，方便后续进行其他操作

1. 复现代码
```java
public class Test {
    public static void main(String[] args) {
        ExcelReader reader = ExcelUtil.getReader("C:\\Users\\Administrator\\Desktop\\测试样例.xlsx", 0);
        List<List<Object>> list = reader.read(0);
        int a = 0;
        reader.close();
    }
}
```

2. 图片
- 文件图片
![1723778084572](https://github.com/user-attachments/assets/0547ab7c-f81e-4dcc-90e1-8e148e3a6cb2)
- 断点结果
![1723777836221](https://github.com/user-attachments/assets/8d35853d-6ccf-4096-938a-88a00f3eaae2)

3. 测试涉及到的文件
[测试样例.xlsx](https://github.com/user-attachments/files/16632512/default.xlsx)

**Comment by looly** [comment]
原因是首行被作为标题行了，导致自动转换。

你可以使用：

```java
List<List<Object>> list = reader.read(0, Integer.MAX_VALUE, false);
```

这样就不自动处理标题行了。

**Comment by pakchoily** [comment]
> 原因是首行被作为标题行了，导致自动转换。
> 
> 你可以使用：
> 
> ```java
> List<List<Object>> list = reader.read(0, Integer.MAX_VALUE, false);
> ```
> 
> 这样就不自动处理标题行了。

收到，多谢啦。
