### ISSUE TITLE
FileUtils网络路径支持存在问题

### ISSUE THREAD

**Issue by LeeKasm** [looly/hutool#3699]
### 版本情况

hutool版本： 5.8.31

### 问题描述（包括截图）
无法得到正确的文件列表或文件是否存在的真实情况
![84002c6fa8072163fa89dd665b3b761d](https://github.com/user-attachments/assets/145b4040-c42b-49e7-868b-5ac08d65d0e9)

1. 复现代码

```java
FileUtil.exist(“\\\\192.168.10.143\\soft”);
FileUtil.ls(“\\\\192.168.10.143\\soft”);
```

**Comment by looly** [comment]
这是个samba服务地址，而非本地文件地址。不能使用FileUtil。

考虑协议相关的库。
