### ISSUE TITLE
5.8 之后的版本，空字符串替换失效；

### ISSUE THREAD

**Issue by rock-li-k** [looly/hutool#3702]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在5.7.22的版本情况下，使用下面的代码。复制后的map2种的a应该是不会覆盖的，返回的a应该是等于map2的 a1，而不是null；。升级到5.8 之后的版本，就不行了；直接a=null。应该是在copy之后再调用的；
![image](https://github.com/user-attachments/assets/00d7c302-3f94-40df-ab0b-4b1e0cc60fb1)

![image](https://github.com/user-attachments/assets/a4cff4bd-1ff0-4b95-8186-66a0f8a544de)

1. 复现代码

```java
public static void main(String[] args) {
        Map<String,String> map=new HashMap<String,String>();
        map.put("a","");
        map.put("b","b");
        map.put("c","c");
        map.put("d","d");

        Map<String,String> map2=new HashMap<String,String>();
        map2.put("a","a1");
        map2.put("b","b1");
        map2.put("c","c1");
        map2.put("d","d1");

        CopyOptions option=CopyOptions.create().setIgnoreNullValue(true).setIgnoreError(true).setFieldValueEditor((name, value)->{
            if(value.equals("")){
                value=null;
            }
            return value;
        });
        BeanUtil.copyProperties(map,map2,option);
        System.out.println(map2);
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

请问官方能否增加空字符串不复制的方法了。。。。

**Comment by rock-li-k** [comment]
![image](https://github.com/user-attachments/assets/e1d44c9d-acdc-4d55-a710-580a695b9743)

**Comment by looly** [comment]
看下`CopyOptions.setOverride`，你可以设置成false。

默认为true，覆盖模式，修改值为null肯定也会覆盖。

**Comment by rock-li-k** [comment]
> 看下`CopyOptions.setOverride`，你可以设置成false。
> 
> 默认为true，覆盖模式，修改值为null肯定也会覆盖。

这个还是有问题。加了flase。是有值的不覆盖。现在我的需求是，如果我的源是空字符串，我就不覆盖；；之前5.8之前的版本就是好的；将源的空字符串换成null。然后就不会覆盖了；。现在不行了；

**Comment by looly** [comment]
@rock-li-k 那就继续加上setFieldValueEditor，然后配合setOverride(false)不行么？

**Comment by rock-li-k** [comment]
> @rock-li-k 那就继续加上setFieldValueEditor，然后配合setOverride(false)不行么？

不行哦。我测试过了。就是在原来的基础上加了一个setOverride  false。结果是目标有值，就不覆盖了；。还是没有到达我之前的需求； 仅空字符串不替换；

**Comment by looly** [comment]
我看了下源码，现在的覆盖策略是：

1. 如果setOverride(false)，则目标有值（非null）直接赋值，否则忽略
2. 如果setOverride(true)，则无论目标值是啥，直接覆盖

按照这个策略，确实如果源对象无论是否为null，都不会影响覆盖策略。

你需要的策略是，如果源是null，则跳过，可以使用`CopyOptions.setIgnoreNullValue(true)`即可。

**Comment by rock-li-k** [comment]
> 我看了下源码，现在的覆盖策略是：
> 
> 1. 如果setOverride(false)，则目标有值（非null）直接赋值，否则忽略
> 2. 如果setOverride(true)，则无论目标值是啥，直接覆盖
> 
> 按照这个策略，确实如果源对象无论是否为null，都不会影响覆盖策略。
> 
> 你需要的策略是，如果源是null，则跳过，可以使用`CopyOptions.setIgnoreNullValue(true)`即可。


我的需求是空字符串则跳过。但是目前这个代码不支持空字符串跳过，看了api文档，意思是可以用setFieldValueEditor 先将源的空字符串换成null。然后再进行 copy；就是下面这个代码；这个代码在5.8之前还是好的。升级到5.8之后就没有效果了。

```
CopyOptions option=CopyOptions.create().setIgnoreNullValue(true).setIgnoreError(true).setFieldValueEditor((name, value)->{
            if(value.equals("")){
                value=null;
            }
            return value;
        });
        BeanUtil.copyProperties(map,map2,option);
```

**Comment by looly** [comment]
@rock-li-k 可能是先后顺序问题。

这个我稍后测试，测试后回复。

**Comment by rock-li-k** [comment]
> @rock-li-k 可能是先后顺序问题。
> 
> 这个我稍后测试，测试后回复。

好的。非诚感谢。这个影响到了我十几个项目了。

**Comment by looly** [comment]
@rock-li-k 按照逻辑确实有问题。

经过setFieldValueEditor后的值应该受`ignoreNullValue`控制，5.8.32修复此问题。

十分感谢耐心的交流。

**Comment by rock-li-k** [comment]
> @rock-li-k 按照逻辑确实有问题。
> 
> 经过setFieldValueEditor后的值应该受`ignoreNullValue`控制，5.8.32修复此问题。
> 
> 十分感谢耐心的交流。

好的，预计什么时候可以更新了？

**Comment by looly** [comment]
@rock-li-k 下个月吧，再积累一些bug修复。

**Comment by rock-li-k** [comment]
> @rock-li-k 下个月吧，再积累一些bug修复。
好的。下次更新能否直接提供方法支持 空字符串不覆盖的方法了？不然每次都要这样转一次感觉很没必要；

**Comment by looly** [comment]
@rock-li-k 空字符串是具体的值，不像null具有二义性。

**Comment by rock-li-k** [comment]
> @rock-li-k 空字符串是具体的值，不像null具有二义性。

加个类似的参数控制？是否设置空字符串覆盖等，应该也是能行的吧。

**Comment by rock-li-k** [comment]
> > @rock-li-k 空字符串是具体的值，不像null具有二义性。
> 
> 加个类似的参数控制？是否设置空字符串覆盖等，应该也是能行的吧。



> @rock-li-k 空字符串是具体的值，不像null具有二义性。

话说，最新的6.0.0.M3。有没有这种问题，刚好有个新项目了。想试试看；

**Comment by looly** [comment]
@rock-li-k 最新M15，你可以引入试试玩儿一下，还是测试版
