### ISSUE TITLE
BeanUtil 报错

### ISSUE THREAD

**Issue by zhou20001005** [looly/hutool#3704]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.25（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

> 
![image](https://github.com/user-attachments/assets/62307e04-4e65-4404-833f-d7cc32cd2bc6)

1. 复现代码
        BeanUtil.copyProperties(dto, Profile.class, CopyOptions.create().ignoreNullValue());

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
Profile是不是系统类？

JDK9+中对反射做了限制，可以增加启动参数方式放开限制：

https://blog.csdn.net/qq_27525611/article/details/108685030

**Comment by zhou20001005** [comment]
不是系统类哦

**Comment by zhou20001005** [comment]
业务实体

**Comment by looly** [comment]
麻烦完整堆栈贴一下，我搜一下。
