### ISSUE TITLE
DateUtil.parse 或者 DateUtil.parseUTC 方式处理带毫秒结果不对

### ISSUE THREAD

**Issue by charbus** [looly/hutool#3712]
### 版本情况

JDK版本：   oraclejdk8
hutool版本： 5.8.31
### 问题描述（包括截图）
"2024-08-28T08:43:59.5Z" 和 "2024-08-28T08:43:59.05Z" 和 "2024-08-28T08:43:59.005Z" 理论上毫秒数不一样。第一个是500ms，第二个是50ms，第三个是5ms。结果使用DateUtil.parse(time1)方法执行的结果都是5ms。

1. 复现代码

```java
      String time1 = "2024-08-28T08:43:59.5Z";
      System.out.println(time1.length());
      long time = DateUtil.offsetHour(DateUtil.parse(time1), 8).getTime();
      System.out.println(time);

      time1 = "2024-08-28T08:43:59.005Z";
      time = DateUtil.offsetHour(DateUtil.parse(time1), 8).getTime();
      System.out.println(time);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
这几个都是按照`yyyy-MM-dd HH:mm:ss.SSS`解析的。

如果对解析这种歧义有问题，考虑自行使用格式定义解析。
