### ISSUE TITLE
jdk版本不一样，tobean结果不同,jdk11正常，jdk21解析异常

### ISSUE THREAD

**Issue by stoneLee81** [looly/hutool#3713]
hutool: 5.8.29
 
测试json内容，对应的 :{"operDate":"Aug 22, 2024, 4:21:21 PM"}，CustomerCreateLog.operDate 是util.date类型

代码 JSONUtil.toBean(json内容, CustomerCreateLog.class)

jdk 11版本，解析正常，可以解析出

jdk 21版本，解析错误
Parse [Aug 22, 2024, 4:21:21 PM] with format [EEE, dd MMM yyyy HH:mm:ss z] error!

**Comment by looly** [comment]
5.8.33修复此问题。

需要：

```java
JSONUtil.toBean(jsonStr, JSONConfig.create().setDateFormat("MMM dd, yyyy, h:mm:ss a"), CustomerCreateLog.class)
```
