### ISSUE TITLE
Sonar扫描强迫症患者："static" base class members should not be accessed via derived types 

### ISSUE THREAD

**Issue by xzqqqcom** [looly/hutool#3716]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.27

### 问题描述（包括截图）

1. 复现代码

```java
StrUtil.isNotBlank(str);
```

2. sonar扫描一直提示：
"static" base class members should not be accessed via derived types 

有点强迫症，现在为了应付这个扫描问题，改用CharSequenceUtil.isNotBlank了，然后又跟StrUtil混用，感觉有点怪怪的

**Comment by looly** [comment]
额……工具继承吧。

我想的是`CharSequenceUtil`太长了，就把这个和`StrUtil`合并在一起了。但是为了区分管理，使用了两个工具类。

暂时这个没法变动，我不知道这么用有啥问题。……

**Comment by VampireAchao** [comment]
修改sonar规则即可，本身默认的规则是适配国外环境，在国内水土不服
