### ISSUE TITLE
权重随机类实现方式问题

### ISSUE THREAD

**Issue by wangyefeng** [looly/hutool#3718]
### 问题描述（包括截图）
优化建议:
WeightRandom采用ArrayList的时间和空间复杂度都优于TreeMap
新增:ArrayList只需要在数组后面插入，就是自动排好序的，时间复杂度为0(1)
随机:采用2分查找，时间复杂度也优于红黑树。

**Comment by looly** [comment]
没太看懂如何实现。

可否提供一个PR？

现有的`WeightRandom`是精确到double的。

补充后再打开此issue。

**Comment by wangyefeng** [comment]
PR-#3720

**Comment by wangyefeng** [comment]
![1726481264090](https://github.com/user-attachments/assets/66d9b617-4710-42fa-9c3a-5c8ec0e47bdf)
![1726481295515](https://github.com/user-attachments/assets/2546728e-9af3-4576-8912-6fd4b419e15d)
修改之后 随机效率提升了40%左右，增加元素的效率也变成O(1)级别了

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/3720

已合并，感谢~
