### ISSUE TITLE
httprequest, 希望可以控制content-type 是否传入

### ISSUE THREAD

**Issue by 981433814** [looly/hutool#3719]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
httpRequest 提交数据的时候，会默认给我塞个content-type 进去，但是上传接口，会因为传入了content-type 导致签名错误。希望能控制content-type 允许为空
![image](https://github.com/user-attachments/assets/72dd17d3-d71e-4a11-8b7a-dbc102633e4b)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.8.33更新：

HttpConfig增加`setUseDefaultContentTypeIfNull`方法，设置为false即可跳过自动默认Content-Type。

```java
HttpUtil.createGet(url).setConfig(HttpConfig.create().setUseDefaultContentTypeIfNull(false))
...
```
