### ISSUE TITLE
FileUtil.createTempFile设置isReCreat为true

### ISSUE THREAD

**Issue by yuf19-2022** [looly/hutool#3725]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
FileUtil.createTempFile设置isReCreat为true是不是没用啊，每次生成的临时文件名称都由一串随机的数字组成，基本不会和以前生成的的重复，那设置isReCreat为true就没用了吧

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你有没有想过`随机的数字`可能会重复？
