### ISSUE TITLE
Assert.notEmpty java.lang.NoSuchMethodError: cn.hutool.core.lang.Assert.notEmpty

### ISSUE THREAD

**Issue by yangyang122** [looly/hutool#3726]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.25（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
私有jar包A依赖 5.2.5，项目本身依赖jar包A ,依赖排除了低的hutool-all(5.2.5) ，引入5.8.25,调用jar包中的方法，方法调用,Assert.notEmpty方法，结果：
![图片](https://github.com/user-attachments/assets/7c33996f-38f4-4c26-9340-482eff55bd0e)
如果依赖jarA 和项目本身依赖的hutool-all的版本相同没问题，确认已经排除调低版本了。依然问题出现

**Comment by looly** [comment]
麻烦检查下是否其它关联引入了hutool-core包，core和all也是不能共存的。

**Comment by yangyang122** [comment]
我也检查了，没有core重复依赖，这个方法。测试没有问题，依赖的自己的jar中静态方法间接调用就不太行，依赖自己的jar中的hutool-all版本相同，调用没问题。不同的话，我排除低版本，就报错了

**Comment by looly** [comment]
@yangyang122 目测就是包冲突。

还有就是升级以来jar后，可能需要重新编译你的代码，因为可能方法签名变了。

**Comment by yangyang122** [comment]
好的，签名确实变了， 低版本的依赖是: notEmpty(Collection)  高版本是notEmpty(Iterable)
