### ISSUE TITLE
xls 文件解析异常

### ISSUE THREAD

**Issue by 7757** [looly/hutool#3727]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.2.6（请确保最新尝试是否还有问题）

#### IOException: Can't open workbook - unsupported file type: XML

1. 复现代码

```java
        <!-- 文件解析-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-poi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.3.0</version>
        </dependency>


        ExcelReader reader = ExcelUtil.getReader(stream); //这里报错了
        int startRowIndex = 2;
        BeanSheetReader<AlipayEnterpriseTransaction> beanReader = new BeanSheetReader<>(
                startRowIndex, startRowIndex, Integer.MAX_VALUE, AlipayEnterpriseTransaction.class
        );

        reader.setIgnoreEmptyRow(true);
        List<AlipayEnterpriseTransaction> read = reader.read(beanReader);
```

2. 堆栈信息
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/c3d0a0cf-9ae8-4ed7-8036-db34e9d7f0bd">

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
检查你的文件，是否是xls扩展名，但是实际是xlsx？或者只是简单的xml文本。

方便的话脱敏上传在，再打开此issue。

**Comment by 7757** [comment]
[11111.xls](https://github.com/user-attachments/files/16908667/11111.xls)

**Comment by 7757** [comment]
> 检查你的文件，是否是xls扩展名，但是实际是xlsx？或者只是简单的xml文本。
> 
> 方便的话脱敏上传在，再打开此issue。

上传了

**Comment by looly** [comment]
@7757 这是一个XML文件，并不是XLS或者XLSX。

![image](https://github.com/user-attachments/assets/bf88d809-250f-4d61-93ca-2f78c8b0d7b8)

我看文件涉及隐私信息，我删除了。
