### ISSUE TITLE
JWTUtil.createToken() 使用 HMAC-SHA256 签名时偶发 ArrayIndexOutOfBoundsException 异常

### ISSUE THREAD

**Issue by xiaogc123** [looly/hutool#3732]
### 版本情况

JDK版本：    jdk-8u301
hutool版本： 5.7.7
操作系统：Windows 10
### 问题描述（包括截图）

在使用 JWTUtil.createToken() 方法并结合 HMAC-SHA256 (hs256) 进行签名时，偶尔会抛出 ArrayIndexOutOfBoundsException。该问题并非每次调用都会发生，错误似乎出现在 HMAC 计算部分。

1. 复现代码

```java
public class JWTTest {
    final static JWTSigner SIGNER = JWTSignerUtil.hs256("6sf2f5j2a62a3s8f9032hsf".getBytes());

    public static void main(String[] args) {
        Map<String, Object> payload = new HashMap<>();
        payload.put("name", "test");
        payload.put("role", "admin");

        // 创建 JWT token
        String token = JWTUtil.createToken(payload, SIGNER);
        System.out.println("Generated Token: " + token);
    }
}
```

2. 堆栈信息
![image](https://github.com/user-attachments/assets/a5efaabb-c126-4d40-b8c8-4a509bc8034e)

![image](https://github.com/user-attachments/assets/9d27f680-ae54-4b57-b45c-a52a5fba00ae)

**Comment by looly** [comment]
没复现问题，猜测可能多线程并发调用导致的。

见：https://gitee.com/dromara/hutool/issues/I58LXJ
