### ISSUE TITLE
cn.hutool.core.collection.CollUtil.group(collection, hash)方法有歧义

### ISSUE THREAD

**Issue by happyyangyuan** [looly/hutool#3735]
### 版本情况

JDK版本：    openjdk 17.0.6
hutool版本： 5.8.27

### 问题描述（包括截图）
cn.hutool.core.collection.CollUtil.group(collection, hash)方法中的hash参数并不是字面意思的hash取值函数，而是分组index计算函数。
这么看来它并不具有普适性，它应当仅供cn.hutool.core.collection.CollUtil.groupByField方法使用。

建议：将这个group collection by index lamda方法置为@Deprecated，然后再搞一个适应hash值的分组方法出来？

1. 复现代码
```
public static void main(String[] args) {
        System.out.println(CollUtil.group(List.of("1","2","3"),str->str.hashCode()));
    }

输出：[null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, [1], [2], [3]]
```

**Comment by looly** [comment]
如果你看过一致性Hash算法，我想你应该直到这个方法的本意。

Hash32函数决定了分组的范围，列表数据分布于这个范围中，因此并不是只提供给groupByField使用。

在你的例子中，`str.hashCode()`提供的数字范围太大了，导致分组的”槽“太多。

严格俩说，你应该使用`str.hashCode() % n`

参考：https://zhuanlan.zhihu.com/p/129049724
