### ISSUE TITLE
6.0.0-M16，HttpUtils.post方法无法正确的发送json数据

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#3736]
6.0.0-M16，当使用httpclient4作为engine时，body是json的时候，会使用StringBody作为body，然后将StringBody写到outputStream中，在httpClient处理body写出的时候，获取了body的长度作为content-length，这时候StringBody最终获取的length是从CharSequenceResource#size里取的，对于http来说，应该需要先把data转成byte[]，再取byte[]的长度，而不是直接用data.length()

**Comment by looly** [comment]
这个之前有人提过了，确实有这个问题。

代码已改。6.0.0-M17修正
