### ISSUE TITLE
请问6.0什么时候可正式发布呢？

### ISSUE THREAD

**Issue by pakchoily** [looly/hutool#3737]
### 问题描述

1. 想请问一下，6.0什么时候可以正式发布呢？从23年5月到24年8月已持续发版一年多，我也想用6.0 M版，但是目前还没有文档，不太敢直接生产环境。太期待，JDK21+springboot3.2的虚拟线程啦。
2. 我个人是想这样，我知道您说很大工作量是在文档编写。如果6.0程序本身如果已经完备，是否可以尽早放出6.0的文档，可以方便大家一起看看有什么编写问题。

**Comment by looly** [comment]
@pakchoily 感谢关注。

现阶段除了文档外几个模块还存在较多问题

1. http模块的SPI实现中，Cookie管理、自动30X跳转才刚刚完成适配
2. json模块依旧存在API混乱和性能问题，在封装jackson、fastjson、gson等库的过程中在研究改善
3. test单元测试还不完善，覆盖率还是不足

5.x的经验是，一旦release，修改API的成本非常高，要考虑用户升级的兼容性，因此希望花更多的时间呈现一个”成熟“的库。
