### ISSUE TITLE
CronUtil.schedule问题咨询

### ISSUE THREAD

**Issue by reixuemin** [looly/hutool#3741]
### 版本情况

JDK版本：    jdk 1.8.0_181
hutool版本： 5.8.29

### 问题描述

1. 复现代码
CronUtil.setMatchSecond(true);
CronUtil.start();
CronUtil.schedule("0/1 * * * * *", (Task) () -> dualData(this.dualDataWith(), new byte[]{}));

我发现有好多hutool-cron-xxx的进程，xxx都已经到几十万了，状态是TIMED_WAITING，BLOCKED都有

这个是我用法有问题吗？图片里的Thread是我用ThreadUtil.getThreads();查询出来的

![image](https://github.com/user-attachments/assets/a120c42d-5526-4b42-ac31-adee72a3b434)

**Comment by looly** [comment]
忙猜是定时任务启动太多了，但是没有正常结束。

检查你的定时任务，是不是在任务中创建了新任务？

如需继续讨论，再打开此issue即可。

**Comment by wcxgit** [comment]
我也遇到了同样的问题
<img width="2426" height="1736" alt="Image" src="https://github.com/user-attachments/assets/9329a12e-b1b9-44f3-a88d-fd37d87441ca" />

> 忙猜是定时任务启动太多了，但是没有正常结束。
> 
> 检查你的定时任务，是不是在任务中创建了新任务？
> 
> 如需继续讨论，再打开此issue即可。
