### ISSUE TITLE
FTP默认情况下没有启用被动模式导致上传文件失败

### ISSUE THREAD

**Issue by VioletAyatan** [looly/hutool#3742]
### 版本情况

JDK版本：    graalvm-jdk-17.0.9
hutool版本： 5.8.32（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
try (Ftp ftp = new Ftp("192.168.1.21", 21, "root", "root")) {
            FTPClient client = ftp.getClient();
            File file = new File("D:\\Download\\123.zip");
            boolean success = ftp.upload("/soft", file);
            System.out.println("success = " + success);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

success返回false。

需要自己手动切换模式为被动模式才可正常上传。

```java
try (Ftp ftp = new Ftp("192.168.1.21", 21, "root", "root"))) {
            ftp.setMode(FtpMode.Passive);
            File file = new File("D:\\Download\\123.zip");
            boolean success = ftp.upload("/soft", file);
            System.out.println("success = " + success);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```
success返回true

**Comment by looly** [comment]
对啊，Ftp提供了`setMode`切换模式。

只是默认是主动模式。

**Comment by VioletAyatan** [comment]
emmm，我在文档里面看到的是默认被动模式，确实有点引起误会
![1](https://github.com/user-attachments/assets/12c6aa31-4892-4e85-a351-dda65bb2a36c)

**Comment by looly** [comment]
@VioletAyatan 文档有误。

这块应该是使用Commons-Net给的默认值：

![image](https://github.com/user-attachments/assets/05eaf175-ea63-4448-8a29-1bfe8c1cab4a)


![image](https://github.com/user-attachments/assets/3d177c42-0d7a-4aad-9143-852135aa33f5)
