### ISSUE TITLE
加密内容在其他在线解密网站有时可以解密有时不行

### ISSUE THREAD

**Issue by id2314** [looly/hutool#3743]
公钥：045ACB8DF1B4E4A75E2E35386E21425A7FD09362B3E3EA27BCE073AD0179E49B7AFA4859661EA16EB9FD22CDC2789BDAC291994B0D4858AFD4486135DE7534D4E8
私钥：59D8A0C69CF2CC669BEDD00DE34DE3E8DC8F532448F12F01EFB423909D7E12E3
![image](https://github.com/user-attachments/assets/9f657aa4-509a-458f-a688-b71204909cc9)
![image](https://github.com/user-attachments/assets/88408788-8449-4ef2-89d3-75dd9e08dfbe)

**Comment by looly** [comment]
加密内容BC库会带上04头，去掉试下。
