### ISSUE TITLE
UserAgentUtil.parse()无法正确解析出Win11操作系统参数

### ISSUE THREAD

**Issue by xiajunzhuang** [looly/hutool#3745]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.32

### 问题描述（包括截图）
通过User-Agent无法正确的解析Win11操作系统
![image](https://github.com/user-attachments/assets/7f6e160f-f500-4a97-bd49-89ee4a870584)
补充信息：
信息来源：https://learn.microsoft.com/zh-cn/microsoft-edge/web-platform/how-to-detect-win11
![image](https://github.com/user-attachments/assets/8671a387-72b7-438f-9ba2-07080ff11f02)
![image](https://github.com/user-attachments/assets/5ccfe674-19b8-42b4-b407-23b1ef17734c)
掘金有人提出的相同问题并尝试解决地址：
https://juejin.cn/post/7398511534744338447

**Comment by BingChunMoLi** [comment]
请求头的获取可以通过添加HttpServletRequest的构造方法或静态获取解决，可能需要开发者自行选择Accept-CH、Delegate-CH、Permissions-Policy去实现。 或者去提供一个filter以供用户注册(有点超出hutool小工具的范围了)。 还有更好的方案吗

**Comment by CherryRum** [comment]
@looly 我记得我以前说过
https://github.com/dromara/hutool/issues/2669

**Comment by looly** [comment]
@BingChunMoLi 看下 @CherryRum 的回答。

单纯从UA上，无法区分Win10还是Win11的，
你发的内容截图也做了说明：

![image](https://github.com/user-attachments/assets/93b1a04e-698a-4665-b26e-0214faff7149)

因此你需要根据header信息辅助判断，而这个工具类并不提供。
