### ISSUE TITLE
为二维码增加logo时圆角是否考虑配置成参数

### ISSUE THREAD

**Issue by fun-li** [looly/hutool#3746]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.32

### 现版本默认增加增加圆角，实际我的需求时不需要圆角，暂时通过修改源码本地编译解决了，是否考虑QrConfig配置中增加参数配置圆角？我可以提交PR

**Comment by looly** [comment]
来个pr吧。

round变成QrConfig中的配置即可。

**Comment by fun-li** [comment]
已经提交PR

**Comment by looly** [comment]
关联：https://github.com/dromara/hutool/pull/3747
