### ISSUE TITLE
Singleton#get 碰到个偶现的问题

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#3749]
jdk 21
hutool 6.0.0-M16
<img width="740" alt="image" src="https://github.com/user-attachments/assets/58ed63d7-0fca-402d-b13a-613b79ae9dbb">

https://blog.csdn.net/wu_weijie/article/details/129289929

**Comment by looly** [comment]
@refeccd JDK9+确实有这个问题。

就是hash碰撞了，见：https://bugs.openjdk.java.net/browse/JDK-8161372

JDK8一旦hash碰撞直接死循环，所以有了`SafeConcurrentHashMap`，JDK9+解决了死循环的bug，当然解决办法就是直接抛出异常。

**Comment by refeccd** [comment]
这个是hash冲突吗？
一个是 ClientEngine.class.getName()
一个是 LogEngine#getName() + clazz.getName()
应该冲突的可能性比较小吧
