### ISSUE TITLE
hutool 写出excel 排序不没有

### ISSUE THREAD

**Issue by zhizhi555555** [looly/hutool#375]
根据文档说excel写出如果按别名顺序加入会按别名排序，如果是2个sheet的话，第二个sheet没有按别名排序

**Comment by looly** [comment]
新建sheet会清空之前的别名，请重新写一遍别名即可。

**Comment by zhizhi555555** [comment]
> 新建sheet会清空之前的别名，请重新写一遍别名即可。
我这边是2个sheet分别是不同的表格，head别名是不一样的，

现在新建sheet没有清空之前的别名。debug后发现存在之前的别名是不是版本问题？
private Comparator<String> getInitedAliasComparator() {
		if (MapUtil.isEmpty(this.headerAlias)) {
			return null;
		}
		Comparator<String> aliasComparator = this.aliasComparator;
		if (null == aliasComparator) {
			Set<String> keySet = this.headerAlias.keySet();
			aliasComparator = new IndexedComparator<>(keySet.toArray(new String[keySet.size()]));
			this.aliasComparator = aliasComparator;
		}
		return aliasCompara

第二个sheet时候执行上面方法，其中this.aliasComparator还是存在前面的别名

**Comment by looly** [comment]
这原来是个bug，已经修复了。请升级到4.5.10

**Comment by zhizhi555555** [comment]
> 这原来是个bug，已经修复了。请升级到4.5.10

ok,看了新版本源码果然已经修复，谢谢
