### ISSUE TITLE
有没有可能增加一个算集合笛卡尔积的方法，这样就可以把多层循环变成一层

### ISSUE THREAD

**Issue by xiaoyv-haha** [looly/hutool#3750]
有没有可能在CollectionUtil中增加一个算集合笛卡尔积的方法，这样就可以把多层循环变成一层，缩进太多，不方便阅读，可以参照guava  Lists.cartesianProduct()

**Comment by looly** [comment]
不考虑，自行实现算法吧~~

**Comment by xiaoyv-haha** [comment]
其实我觉得可以把guava的Lists.cartesianProduct()抄过来，反正两个库的功能也差不多，避免为了用这一个方法还去引入guava...



---Original---
From: "Golden ***@***.***&gt;
Sent at: 2024年9月24日(Tue) Evening11:05
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dromara/hutool] 有没有可能增加一个算集合笛卡尔积的方法，这样就可以把多层循环变成一层 (Issue #3750)




 
不考虑，自行实现算法吧~~

**Comment by looly** [comment]
@mingyou-xiong 参考：

https://www.baeldung-cn.com/java-cartesian-product-sets

6.0.0增加一个方法在`CollStreamUtil`
