### ISSUE TITLE
cn.hutool.core.collection.CollUtil#disjunction的注释是不是可以改成 “两个集合的对称差集”

### ISSUE THREAD

**Issue by wzdlagrange** [looly/hutool#3753]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
cn.hutool.core.collection.CollUtil#disjunction
这个方法的注释 是 “两个集合的差集”
是不是可以改成 “两个集合的对称差集”

因为差集 我理解为 A-B，去网上查的差集定义 也是 A-B
disjunction实现的逻辑 应该是 对称差集 ==> (A-B)∪(B-A)  

从CollUtil里找差集方法 先搜到了 disjunction，
一看确实是差集方法，我就用了，到后面才发现subtract才是我需要的。
没仔细看方法实现，是我的问题，
注释 写为对称差集，会更好。以示不是常规的差集

**Comment by looly** [comment]
有道理~~

5.8.33修改注释。

**Comment by looly** [comment]
我想你需要的是：

![image](https://github.com/user-attachments/assets/143b6606-87c1-421d-ba7e-0711a80aa286)
