### ISSUE TITLE
Ftp的upload(String destPath, File file)方法上传的图片，打开后是马赛克，很多种色彩带

### ISSUE THREAD

**Issue by yuf19-2022** [looly/hutool#3758]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

这个方法是会原样上传文件吗，会受到其它因素影响吗，返回值为真
![IMG_20240929_110509.jpg](https://github.com/user-attachments/assets/a93644ec-cf76-47ce-ae5d-475dc6b014c8)

**Comment by looly** [comment]
你确定不是你的服务端做了加密？

**Comment by yuf19-2022** [comment]
> 你确定不是你的服务端做了加密？

大佬，ftp服务器做加密吗，如果是的话，应该怎么处理呢，服务器是别人的不清楚啊

**Comment by looly** [comment]
@yuf19-2022 这个就不清楚了。

尝试使用FTP客户端上传试下。
