### ISSUE TITLE
cn.hutool.json.JsonArray没有判断ignoreNullValue配置

### ISSUE THREAD

**Issue by sadmonsterr** [looly/hutool#3759]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.32

### 问题描述
![image](https://github.com/user-attachments/assets/32f1f169-c5b9-48bc-ba2f-ef8be64185a0)
将一个包含null值的数组序列化为cn.hutool.json.JsonArray时
cn.hutool.json.JsonArray类中的addRaw(Object object)方法没有判断ignoreNullValue配置，导出null最终被转换为了JSONNull对象
参考cn.hutool.json.JsonObject中的set(String key, Object value, Filter<MutablePair<String, Object>> filter, boolean checkDuplicate)方法，就判断了ignoreNullValue配置
![image](https://github.com/user-attachments/assets/cbd9e8e2-d9e2-4f7e-ac00-24a9acec11d3)

1. 复现代码

```java
// 默认的配置是true，应该转为null的
String jsonArrayStr = "[null]";
JSONArray jsonArray  = JSONUtil.toBean(jsonArrayStr, JSONArray.class, true);
assert jsonArray.get(0) == JSONNull.NULL;
```

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
无

**Comment by looly** [comment]
确认bug，5.8.33修复此问题。

修复见：https://github.com/dromara/hutool/commit/be98b46349c6649195e01b5ca39f281016d9f4e6
