### ISSUE TITLE
如何判断文件是否完整

### ISSUE THREAD

**Issue by yuf19-2022** [looly/hutool#3761]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

比如我要把本地的某个文件夹下的所有文件上传到ftp盘，这个文件夹中又在不断地增加新的文件，我读到的文件会有还没有完全生成的，比如压缩一个很大的文件，这样导致上传到ftp的文件也是不完整的

**Comment by looly** [comment]
只能根据文件长度判断。
