### ISSUE TITLE
ftp的upload方法会卡住

### ISSUE THREAD

**Issue by yuf19-2022** [looly/hutool#3762]
上传一些图片后就卡住了

**Comment by looly** [comment]
可能的原因：

1. 服务器处理卡死
2. 网络中断或等待

暂时不能确定具体原因。

**Comment by yuf19-2022** [comment]
> 可能的原因：
> 
> 1. 服务器处理卡死
> 2. 网络中断或等待
> 
> 暂时不能确定具体原因。

刚发现是调用的构造方法没有指定ftpmode为possive，默认为null，传一部分图片就卡住了
