### ISSUE TITLE
A possible parameter check to `md5HexTo16`

### ISSUE THREAD

**Issue by iscas-zac** [looly/hutool#3763]
The `md5HexTo16` https://github.com/dromara/hutool/blob/467d67e83ae5fc40364cda9e36e30a7283be2449/hutool-crypto/src/main/java/cn/hutool/crypto/digest/DigestUtil.java#L198-L200 is public, and its substring index is not checked. Should we write a check in it?

**Comment by looly** [comment]
Bad md5Hex will cause the exception, No need to check.

**Comment by iscas-zac** [comment]
Should we add a `throws IndexOutOfBoundException` in its signature?

**Comment by looly** [comment]
IndexOutOfBoundException is runtimeException and no need to add signature.

and this method also throw NullPointException
