### ISSUE TITLE
M17 HttpClient4Engine#initEngine 报错

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#3765]
<img width="850" alt="image" src="https://github.com/user-attachments/assets/025bca2d-bb51-4b8b-8256-570b6be6a591">

<img width="356" alt="image" src="https://github.com/user-attachments/assets/a3b288c8-2324-426e-9793-275f0bd60813">

<img width="570" alt="image" src="https://github.com/user-attachments/assets/f0ab6672-6b91-4824-b096-3b232ca9e1a5">

maxTotal 默认是0，导致报错了

**Comment by refeccd** [comment]
![image](https://github.com/user-attachments/assets/44e21901-4180-45ad-9dff-645ce3b4e4a2)

还有下载文件时，会出现这个错误，必现

**Comment by looly** [comment]
1. 没注意HttpClient的源码检查。

2. 问题出在使用了HttpClient的`HttpClientResponseHandler`，导致获取响应后关闭了连接，改用`executeOpen`。

以上两个问题会在M18修复，十分感谢~~
