### ISSUE TITLE
AES解密不报错

### ISSUE THREAD

**Issue by clvspk** [looly/hutool#3766]
### 版本情况

JDK版本：    openjdk_8_422
hutool版本： 5.8.16（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
AES解密不报错 
1. 复现代码

```java

 String a = SecureUtil.aes("8888888888888888".getBytes()).decryptStr("哈哈");
 System.out.println(a);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
JCE的AES确实没有报错。不明原因。

引入BC库可实现严格的报错。

![image](https://github.com/user-attachments/assets/39e7dfa9-14c2-486c-83bb-4c03adbddd31)

**Comment by changhr2013** [comment]
**`SunJCE` 和 `BouncyCastle` 在处理空输入的策略上有所不同，`SunJCE` 认为空是一个合法输入，`BouncyCastle` 认为空输入非法。**

回到这个问题上，这其实跟 `hutool` 本身的输入处理机制有一定关系，`hutool` 在处理解密输入时，认为输入一定是 `Hex` 或者 `Base64` 格式，在本例中输入的是中文，因此都无法解析，导致处理输入字符串后返回了一个空字节数组。

```java
/**
* 解密Hex（16进制）或Base64表示的字符串
*
* @param data 被解密的String，必须为16进制字符串或Base64表示形式
* @return 解密后的bytes
*/
default byte[] decrypt(String data) {
    return decrypt(SecureUtil.decode(data));
}
```

```java
/**
* 解码字符串密钥，可支持的编码如下：
*
* <pre>
* 1. Hex（16进制）编码
* 1. Base64编码
* </pre>
*
* @param key 被解码的密钥字符串
* @return 密钥
* @since 4.3.3
*/
public static byte[] decode(String key) {
    // issue#I90M9D
    // 某些特殊字符串会无法区分Hex还是Base64，此处使用系统属性强制关闭Hex解析
    final boolean decodeHex = SystemPropsUtil.getBoolean(HUTOOL_CRYPTO_DECODE_HEX, true);
    return (decodeHex && Validator.isHex(key)) ? HexUtil.decodeHex(key) : Base64.decode(key);
}
```

`hutool` 的 `Base64` 解码会忽略不可解析的字符返回空：
```java
System.out.println(cn.hutool.core.codec.Base64.decode("哈哈").length);
```

输出：

```txt
0
```

再将空字节数组传入到算法实现层，由于 `SunJCE` 和 `BouncyCastle` 对空输入的处理策略不一致，导致了当前的现象。

你可以将输入替换为 `Hex` 或者 `Base64` 格式，例如输入一个 "1234"，就会发现 `SunJCE` 也会报错了。

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/cec9844a-ed25-4bf7-9eb6-f800e26fec5d">

**Comment by looly** [comment]
@changhr2013 原来是这样。

看来输入数据要做一下检查了。

**Comment by looly** [comment]
@clvspk 

6.0.0-M18增加一些检查
