### ISSUE TITLE
MaskingUtil类是否可以新增方法重载支持自定义替换的字符

### ISSUE THREAD

**Issue by zhangdp** [looly/hutool#3767]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.32（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

目前固定是替换成'*'，有时候需求要替换成'#'😭，希望新增方法重载可自行传入要替换的字符，十分感谢🙏

**Comment by looly** [comment]
5.x不做变更。

6.0.0-M18增加支持：

```java
final MaskingManager manager = MaskingManager.ofDefault('#');
assertEquals("段##", manager.masking(MaskingType.CHINESE_NAME.name(), "段正淳"));
```
