### ISSUE TITLE
http上传文件，文件名是个路径

### ISSUE THREAD

**Issue by elliotliu** [looly/hutool#3768]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.31（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

http上传文件文件名是路径

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
很有可能是：

上传的文件没有指定文件名。
你需要指定特定头信息。

**Comment by elliotliu** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/f4c3d5fe-98cf-4c9e-8812-24e73c305a77">
这个怎么指定呢？

**Comment by looly** [comment]
这个打印的只是body，并不是实际传输的内容。

当有File时，使用`MultipartBody`，服务端读取即可。
