### ISSUE TITLE
sax读取excel时间格式错误

### ISSUE THREAD

**Issue by an9xyz** [looly/hutool#377]
excel中时间格式为**HH:mm**
![fOH9BITOJe](https://user-images.githubusercontent.com/28777740/58618644-b3674a00-82f5-11e9-9b3e-3d7ebf52961d.png)
解析结果如下图所示：
![DCNV9VQfgq](https://user-images.githubusercontent.com/28777740/58618643-b3674a00-82f5-11e9-93a6-9add2e716daa.png)

**Comment by an9xyz** [comment]
单元格格式为自定义
> h:mm

获取的时间变成**当前时间**了

**Comment by looly** [comment]
这是没有读取到时间格式导致的，解决方法如下：
1、读取字符串自行转时间
2、升级新版本Hutool看能否解决。

**Comment by looly** [comment]
如果不行，请提供Excel我本地测试。

**Comment by an9xyz** [comment]
这个本地测试确实没有问题，但是我的代码中是有问题的，原因还要进一步查找
SaxReader读取excel能提供获取所有总行数的方法？
目前是通过ExcelReader先获取总行数，再用SaxReader处理业务逻辑

**Comment by an9xyz** [comment]
@looly 如何中止导入呢？抛异常还是会处理下一行，如何彻底中止导入呢？
