### ISSUE TITLE
在YamlUtil 添加 yml 格式的字符串转为 json 对象

### ISSUE THREAD

**Issue by luoqiz** [looly/hutool#3771]

**Comment by luoqiz** [comment]
![image](https://github.com/user-attachments/assets/dae3e91e-3c5e-40b3-bf99-7be8bfa838ed)

**Comment by looly** [comment]
@luoqiz JSON和Setting是两个独立模块，封装这个方法必须将JSON模块作为依赖，不值得。

且用户可能使用第三方的JSON库完成转换，因此封装的意义不大。
