### ISSUE TITLE
关于DateUtil.parse的优化建议

### ISSUE THREAD

**Issue by stayWhite00** [looly/hutool#3774]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.11

### 问题描述
原因是一个需求Excel导入时间，日期格式是年月,因为是导入不好规范格式，所以想做适配 yyyy年MM月、yyyy-MM、yyyy/MM。
结果DateUtil.parse 最低程度直到yyyy-MM-dd这个日期格式；
![image](https://github.com/user-attachments/assets/74588c9e-58e4-4569-8eb3-1624892442de)

**Comment by looly** [comment]
DateUtil.parse只能支持正常的几种格式，并不是万能的。

如果对格式有自定义需求，可以使用：

```java
DateUtil.parse(str, "yyyy年MM");
```
