### ISSUE TITLE
信息脱敏工具-DesensitizedUtil是否可以添加微信号公共脱敏方法

### ISSUE THREAD

**Issue by 1228181394** [looly/hutool#3776]
### 版本情况

JDK版本：    1.8.0_333
hutool版本： 5.8.21

### 问题描述（包括截图）

1. 信息脱敏工具-DesensitizedUtil是否可以添加微信号公共脱敏方法

**Comment by looly** [comment]
来个PR？给个规则即可。

**Comment by 1228181394** [comment]
方案1：小于等于10位隐藏中间4位，大于10位隐藏中间6位；
方案2：类似死于DesensitizedUtil.idCardNum()改一下方法名

**Comment by looly** [comment]
@1228181394 我搜了下微信号的格式，似乎并没有一个固定的格式，可以完全自定义。

考虑直接用`StrUtil.hide`
