### ISSUE TITLE
springutil getbean 希望能对泛型类支持更友好

### ISSUE THREAD

**Issue by FULaBUla** [looly/hutool#3779]
目前手动注入泛型类的时候编译器会提示未指定的泛型转换，理论上 spring 自己的 getbean 是可以在后面参数声明泛型类型的，但是封装的静态方法不支持

**Comment by looly** [comment]
![image](https://github.com/user-attachments/assets/3e8e75f7-fd01-438d-8842-6e9bb2e950d7)

是这个么？如何更好的支持泛型？补充后打开此issue。

**Comment by FULaBUla** [comment]
> ![image](https://private-user-images.githubusercontent.com/1432613/382617767-3e8e75f7-fd01-438d-8842-6e9bb2e950d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc4MTEsIm5iZiI6MTczMTA3NzUxMSwicGF0aCI6Ii8xNDMyNjEzLzM4MjYxNzc2Ny0zZThlNzVmNy1mZDAxLTQzOGQtODg0Mi02ZTliYjJlOTUwZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTQ1MTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2RkMGFiMTBhYjdiYjZkMjNhNmRhYjNhZWM1NzY1NTk4M2VmMzA2YzQzM2NmODVmZGM1ZDAwMzgxY2YxZjc2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kZ2Rve9SJB7TdknbRsjYA44Mpvh0euDSS3YbJUtJKDY)
> 
> 是这个么？如何更好的支持泛型？补充后打开此issue。

需要封装提供对图中方法的支持
![image](https://github.com/user-attachments/assets/8280e861-e2f2-4b9f-bd16-e6fd67844df2)

**Comment by FULaBUla** [comment]
@looly

**Comment by looly** [comment]
@FULaBUla 5.8.34增加这个方法。
