### ISSUE TITLE
JDK21环境下，使用ClassUtil.loadClass方法出现有个别class无法找到的问题

### ISSUE THREAD

**Issue by LettyBoy** [looly/hutool#3780]
### 版本情况

JDK版本：    jdk21
hutool版本： 5.8.31

### 问题描述（包括截图）

1. 复现代码

```java
ClassUtil.loadClass(mapperName)
```

2. 堆栈信息
![image](https://github.com/user-attachments/assets/a7056775-41c2-47a1-bbe3-01590d4906a4)

**Comment by looly** [comment]
使用JDK的`Class.forName`试下。

盲猜几个原因：

1. 使用了自定义的ClassLoader，和当前上下文的不一致
2. 多模块，没有加载。

补充后再打开此issue。

**Comment by LettyBoy** [comment]
同一个模块下，只有这一个类不能被发现，而且换成java自带的class.forName后，是成功的

**Comment by looly** [comment]
@LettyBoy 那可能还是ClassLoader的问题。

尝试：

```java
Class.forName("xxxxx", true, ClassLoaderUtil.getClassLoader());
```

本质上是调用的这个方法。

而`Class.forName`使用`ClassLoader.getClassLoader(caller)`，使用调用者的ClassLoader，你可以打印对比下这两者是否有区别。

**Comment by LettyBoy** [comment]
我发现只是在生产环境出现这个问题，idea开发环境下，是正常的

**Comment by looly** [comment]
@LettyBoy 那就可能是ClassLoader的问题了。
