### ISSUE TITLE
Convert类的数据转换时间消耗过长

### ISSUE THREAD

**Issue by Wang-0122** [looly/hutool#3782]
### 版本情况

JDK版本：    jdk17
hutool版本： 5.8.25

### 问题描述（包括截图）
Convert类的数据转换
两万条左右的数据, 耗时5s起步

![image](https://github.com/user-attachments/assets/2129a3e9-6c63-4c08-8250-49fbc030ed36)
![image](https://github.com/user-attachments/assets/106a08b8-acd7-42ae-8bcf-396337feee70)
![image](https://github.com/user-attachments/assets/5476bef9-ab2e-4ef3-8dfc-9f5699aaff3f)

**Comment by looly** [comment]
Convert基于策略模式的类型转换，因此转换时需要查找对应的转换器，这个过程比较长。

对于已经明确转换规则的转换，考虑直接编码。
