### ISSUE TITLE
DateUtil.rangeToList 内存溢出问题

### ISSUE THREAD

**Issue by IFlyToMe** [looly/hutool#3783]
### 版本情况

JDK版本：    openjdk_8_202
hutool版本： 5.8.33

### 问题描述（包括截图）
使用DateUtil.rangeToList，传入步长为0时，出现无限循环，底层不断创建对象，最后OOM

![image](https://github.com/user-attachments/assets/580404ce-c499-4f28-bfec-3f65fceea5d1)

1. 复现代码
        Date start = DateUtil.date();
        Date end = DateUtil.date();
        System.out.println(DateUtil.rangeToList(start, end, DateField.DAY_OF_MONTH, 0));

2. 堆栈信息
无堆栈信息，本地运行发现许久没有响应发现的

**Comment by looly** [comment]
确实有这个问题。

0和负数都有这个问题。

5.8.34修复此问题。

见：https://github.com/dromara/hutool/commit/55bd8afcef0b6a5619d3db8bb34804e4e9fde0e2
