### ISSUE TITLE
关于DesensitizedUtil的脱敏实现方法设计

### ISSUE THREAD

**Issue by mikoto2464** [looly/hutool#3786]
### 版本情况

JDK版本：    openjdk_22_0_2
hutool版本： 5.8.33（请确保最新尝试是否还有问题）

### 建议目标及当前痛点

希望重构DesensitizedUtil，我希望添加的功能有两个
- **自定义Desensitized实现**
虽然自定义实现我个人暂时也没有（毕竟原本的实现还是较为完备的），但还是提出来做个参考
- **针对PO类脱敏逻辑的简化**
这个我个人来说还是较有痛点的。因为当前的实现只支持String -> String的脱敏，设想一个业务场景，使用RestController以JSON格式输出一个从持久层获取的PO对象，其中某一项需要进行脱敏。按照目前的实现，只能先将其转换为JSON对象，然后在Controller层（或者也可以在持久层返回对象之前）将其手动赋值为脱敏后的字符串。

### 设想的解决方案
- **自定义Desensitized实现**
1. 新增一个DesensitizedOperation接口，为了便于使用lambda表达式，此接口只有一个方法，方法签名如下`String operation(String str, Object... args)`
2. 使DesensitizedType实现此接口，并实现operation方法，这样最大的好处就是简化了desensitized中的一长串switch case
3. 使desensitized方法原来传入的DesensitizedType变为DesensitizedOperation，这样既可以直接向其中传入自己的实现，同时由于DesensitizedType实现了DesensitizedOperation方法，用户过去编写的代码也不用进行改动，仍然可以直接使用DesensitizedType这个枚举

- **针对PO类脱敏逻辑的简化**
1. 新增@Desensitized注解，value()返回的是DesensitizedType，用于标注此PO对象需要脱敏的字符串
2. 新增desensitized方法，传入PO对象，返回的是一个Map，其中key是字段名，value是脱敏后的值（脱敏传入的是此对象.toString()的值，没有@Desensitized注解则直接调用toString()）
3. 还有的小问题应该是反射相关的，三个方案，我个人认为最后一种实现比较好，但还是想参考下先前其他的实现，尽量统一
    - 在每一次调用desensitized方法的时候都通过反射查找，缺点是可能性能会差，优点是避免耦合
    - 在启动的时候使用扫描器扫描带有@Desensitized的注解，并缓存，缺点是启动时较慢，并且应该需要在启动类定义需要扫描的包，优点是所有可能需要脱敏的类的反射都被缓存了，性能较好
    - 在某个PO类首次传入时使用反射，而日后的调用使用先前通过反射获取的缓存，缺点是第一次调用比较慢，并且同样需要使用缓存，得考虑内存占用，优点是除了第一次外性能好并且尽量避免耦合

以上是我对修改DesensitizedUtil类的想法，如果认为没问题的话，我稍后会提交一个pr

**Comment by looly** [comment]
5.x不再变动了。`DesensitizedUtil`从灵活性角度来说确实很差，可以使用`StrUtil.hide`辅助。

6.0此类改为`MaskingUtil`，实现了自定义规则：

```java
final MaskingManager maskingManager = MaskingManager.ofDefault('#');
maskingManager.register("custom", (str)->"custom" + str);

// customhutool
final String masking = maskingManager.masking("custom", "hutool");
```

关于注解，Hutool作为工具一直不主张使用注解（除了`@Alias`等在json和excel中应用较为普遍的注解），因为注解侵入性太强了。因此建议使用上述防暑手动注册。
