### ISSUE TITLE
math. Calculator  计算数学公式计算错误

### ISSUE THREAD

**Issue by tanmouren66** [looly/hutool#3787]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.26（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

"0+50/100x(1/0.5)"
 计算上面这个表达式时，结果为0.0，实际应该是1.0

```java
 Calculator calculator1 = new Calculator();
 double calculate = calculator1.calculate("0+50/100x(1/0.5)")
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
![image](https://github.com/user-attachments/assets/b868de51-503a-4f22-aa01-222096345634)

**Comment by EightyOliveira** [comment]
乘法符号用*   
public static void main(String[] args) {
        Calculator calculator1 = new Calculator();
        double calculate = calculator1.calculate("0+50/100*(1/0.5)");
        System.out.println(calculate);
    }

**Comment by looly** [comment]
哈哈，使用`x`是我没想到的。我做个兼容吧。

**Comment by looly** [comment]
见：https://github.com/dromara/hutool/commit/62d31e4656eff1da464491d9c1a1b91c220690db
