### ISSUE TITLE
TemplateEngine无法找到模板

### ISSUE THREAD

**Issue by asusuka** [looly/hutool#3794]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： hutool-all-5.4.0

### 问题描述（包括截图）
TemplateEngine无法找到resources下的freemaker模板，检查过path和其他配置并没有发现问题，但就是找不到模板文件，编译后，target下也能看到对应的模板文件，但是代码就是找不到

1. 复现代码
```java
  @Bean
    public TemplateEngine templateEngine() {
        return TemplateUtil.createEngine(new TemplateConfig("classpath:templates", TemplateConfig.ResourceMode.CLASSPATH));
    }

    Template template = templateEngine.getTemplate("news_list.ftl"); // 直接是null
    System.out.println(template);
```

2. 堆栈信息
cn.hutool.core.io.IORuntimeException: TemplateNotFoundException: Template not found for name "news_list.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(classLoader="org.springframework.boot.devtools.restart.classloader.RestartClassLoader@3a8e8b14", basePackagePath="classpath:templates/").

3. 测试涉及到的文件（注意脱密）
![微信截图_20241122094526](https://github.com/user-atta
![Uploading 微信截图_20241122094555.png…]()
chments/assets/16e499f1-9add-4389-87f7-b34749545bfd)

比如报错的Excel文件，有问题的图片等。

**Comment by asusuka** [comment]
![微信截图_20241122094526](https://github.com/user-attachments/assets/991660f3-9a31-4816-8a1f-62984ecfcb73)
![微信截图_20241122094555](https://github.com/user-attachments/assets/b0ade97c-2651-4ea3-8dae-9e13b33ed45e)

**Comment by looly** [comment]
`classpath:templates`改成`templates`试下。如果不行使用`getTemplate(templates/news_list.ftl)`；

需要看下日志具体找到哪儿去了这个模板。

如果没解决麻烦再打开此issue。

**Comment by asusuka** [comment]
classpath:templates改成templates确实好了，这是咋回事呢

**Comment by looly** [comment]
不是Spring环境，不支持classpath前缀呗。

我记得我做过兼容，但是你要更新Hutool到最新试下。
