### ISSUE TITLE
无法发送QQ邮件

### ISSUE THREAD

**Issue by fenglex** [looly/hutool#3797]
### 版本情况

JDK版本：    openjdk 1.8.0_391
hutool版本： 5.8.16

### 问题描述（包括截图）

1. 复现代码

```java
 MailAccount account = new MailAccount();
        account.setDebug(true);
        account.setHost("smtp.qq.com");
        account.setPort(465);
        account.setAuth(true);
        account.setSslEnable(true);
        account.setStarttlsEnable(true);
        account.setFrom("xxxxx@qq.com");
        account.setUser("x");
        account.setPass("x");
        MailUtil.send(account, "xxx@126.com", "xxxx", "xxx", false);
 
```

2. 错误信息
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

**Comment by looly** [comment]
看下这个文档：

https://doc.hutool.cn/pages/MailUtil/#%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6

![image](https://github.com/user-attachments/assets/ff77a605-95f3-47c0-af2f-858265bfc097)


我这边测试没问题。你检查下mail版本是不太旧了。

```xml
<dependency>
	<groupId>com.sun.mail</groupId>
	<artifactId>javax.mail</artifactId>
	<version>1.6.2</version>
</dependency>
```
