### ISSUE TITLE
form方式上传文件，setFixedContentLength后报错.

### ISSUE THREAD

**Issue by BigPotato8** [looly/hutool#3799]
### 版本情况

JDK版本：    openjdk_8_422
hutool版本： 5.8.34（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
        HttpRequest httpRequestPost = HttpUtil.createPost(getFullUrl(url));
        FileResource resource = new FileResource(file);
        httpRequestPost.form("imgfile", resource);
        long len = file.length();
        httpRequestPost.setFixedContentLength(len);

2. 堆栈信息
  cn.hutool.core.io.IORuntimeException: IOException: too many bytes written
	  at cn.hutool.core.io.copy.StreamCopier.copy(StreamCopier.java:71)
	  at cn.hutool.core.io.IoUtil.copy(IoUtil.java:162)
	  at cn.hutool.core.io.IoUtil.copy(IoUtil.java:146)
	  at cn.hutool.core.io.IoUtil.copy(IoUtil.java:132)
	  at cn.hutool.core.io.IoUtil.copy(IoUtil.java:119)

**Comment by looly** [comment]
form方法转为body时是key=xxx的，或者multipart方式，长度远超`length`，因此setFixedContentLength肯定报错。

**Comment by BigPotato8** [comment]
这种情况有办法获取到准确的length吗？
设置setChunkedStreamingMode的模式，服务端报400，怀疑不支持

**Comment by looly** [comment]
@BigPotato8 这个客户端是自动计算body length，并加头信息的，你试下。

**Comment by looly** [comment]
@BigPotato8 不用设置setChunkedStreamingMode，你传body或者form的时候，客户端自动计算的。

**Comment by BigPotato8** [comment]
HttpRequest httpRequestPost = HttpUtil.createPost(getFullUrl(url));
FileResource resource = new FileResource(file);
httpRequestPost.form("imgfile", resource);

目前的主要问题是，这种方式上传文件70M，会上传到多个服务端，本地内存会增加很多，而且内存一直都不降下去，有什么方式处理吗？

**Comment by looly** [comment]
@BigPotato8 几个办法：

1. 自己构造body，通过stream方式写出
2. 考虑下HttpClient？
