### ISSUE TITLE
CollectionUtil类的修改建议

### ISSUE THREAD

**Issue by MaxSherry** [looly/hutool#38]
CollectionUtil这个类在使用过程中是经常使用的,尤其是newHashMap、newHashSet、newArrayList这几个方法; 在调用这几个方法的时候,需要写"CollectionUtil"这么长的类名,很不方便,如果像guava那样,只用写"Maps.xxx"这样是很方便的. 另外能不能加创建Map时有类似guava的ImmutableMap.of(key, value)方法直接创建键值对

**Comment by looly** [comment]
可以考虑。我在想一个简洁的名字。说实话，Maps这种名字并不适合在Hutool中，容易与JDK名字冲突。

**Comment by looly** [comment]
3.1.1中单独建立了MapUtil，加入of方法，同时加入别名工具类CollUtil，表示CollectionUtil的简短别名。

**Comment by looly** [comment]
更多欢迎加Hutool群讨论，群号在README中。（分不清你加没加~~sorry）
