### ISSUE TITLE
form方式上传文件，setFixedContentLength后报错.

### ISSUE THREAD

**Issue by BigPotato8** [looly/hutool#3801]
版本情况
JDK版本： openjdk_8_422
hutool版本： 5.8.34（请确保最新尝试是否还有问题）

问题描述（包括截图）
复现代码
HttpRequest httpRequestPost = HttpUtil.createPost(getFullUrl(url));
FileResource resource = new FileResource(file);
httpRequestPost.form("imgfile", resource);
long len = file.length();
httpRequestPost.setFixedContentLength(len);

这种情况有办法获取到准确的length吗？
设置setChunkedStreamingMode的模式，服务端报400，怀疑不支持

**Comment by looly** [comment]
重复：https://github.com/dromara/hutool/issues/3799

如果补充可以重新打开旧的issue。
