### ISSUE TITLE
POST进行Form文件上传，内存溢出

### ISSUE THREAD

**Issue by BigPotato8** [looly/hutool#3802]
JDK版本： openjdk_8_422
hutool版本： 5.8.34 

HttpRequest httpRequestPost = HttpUtil.createPost(getFullUrl(url));
FileResource resource = new FileResource(file);
httpRequestPost.form("imgfile", resource);

目前的主要问题是，这种方式上传文件70M，会上传到多个服务端，本地内存会增加很多，而且内存一直都不降下去，有什么方式处理吗？

另外弱弱问一下，close的issue怎么重新打开呢？

**Comment by looly** [comment]
上个issue回复了。

HttpUrlconnection功能有限，考虑自行拼装body，用流写出，及时关闭。

如果还是不行，就得使用HttpClient了。
