### ISSUE TITLE
找不到可用的SHA256withECDSA算法 no such algorithm: SHA256withECDSA for provider BC

### ISSUE THREAD

**Issue by bollus** [looly/hutool#3806]
### 版本情况

JDK版本：    oracle jdk17.0.13
hutool版本： 5.8.34（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
验证es256签名的jwt，找不到可用的SHA256withECDSA算法
![image](https://github.com/user-attachments/assets/78fa05e9-9688-4b47-bc57-945e20ecf489)
![image](https://github.com/user-attachments/assets/0c6108cd-4248-4fa1-943c-6c5089324f3e)

1. 复现代码

```java
public static void main(String[] args) {
        String token = AppleSubscribeCallback.signedPayload();
        JWT jwt = JWTUtil.parseToken(token);
        jwt.verify(jwt.getSigner());
        List<String> x5c = jwt.getHeaders().getBeanList("x5c", String.class);
        SecretKey es256 = KeyUtil.generateKey("ES256", x5c.get(0).getBytes(StandardCharsets.UTF_8));
        jwt.verify(JWTSignerUtil.es256(es256));
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
String token = "";

**Comment by looly** [comment]
问题出在`KeyUtil.generateKey`，这个方法不支持简写形式。

而且，`SHA256withECDSA`这种算法`ECDSA`是一种椭圆曲线算法，需要密钥对或公钥、私钥传入，不能直接使用`KeyUtil.generateKey`生成密钥。

具体x5c如何解析，你要看JWT提供方的文档。

> 注意，你的JWT有隐私信息，我给你删掉了，你自行测试。

**Comment by bollus** [comment]
> 问题出在`KeyUtil.generateKey`，这个方法不支持简写形式。
> 
> 而且，`SHA256withECDSA`这种算法`ECDSA`是一种椭圆曲线算法，需要密钥对或公钥、私钥传入，不能直接使用`KeyUtil.generateKey`生成密钥。
> 
> 具体x5c如何解析，你要看JWT提供方的文档。
> 
> > 注意，你的JWT有隐私信息，我给你删掉了，你自行测试。

好的，我去看看，多谢~
