### ISSUE TITLE
JSONUtil工具toJsonStr生成的JSON字符串出现ZERO WIDTH NON-JOINER

### ISSUE THREAD

**Issue by sppan24** [looly/hutool#3808]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.8.34（应该是目前已知版本都存在）

### 问题描述（包括截图）

1. 复现代码

```java
import cn.hutool.core.io.FileUtil;
import cn.hutool.json.JSONUtil;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;

public class Main {

    public static void main(String[] args) throws Exception {
        Gson gson = new Gson();
        ObjectMapper jackson = new ObjectMapper();
        String str = FileUtil.readString("/Users/xxx/Desktop/1.json", StandardCharsets.UTF_8);
        HashMap hutoolRead = JSONUtil.toBean(str, HashMap.class);
        HashMap gsonRead = gson.fromJson(str, HashMap.class);
        HashMap jacksonRead = jackson.readValue(str, HashMap.class);
        System.out.println("original:\t" + str);
        System.out.println("hutoolR   hutoolW:\t" + JSONUtil.toJsonStr(hutoolRead));
        System.out.println("gsonR     hutoolW:\t" + JSONUtil.toJsonStr(gsonRead));
        System.out.println("jackson   hutoolW:\t" + JSONUtil.toJsonStr(jacksonRead));
        System.out.println("hutoolR     gsonW:\t" + gson.toJson(hutoolRead));
        System.out.println("gsonR       gsonW:\t" + gson.toJson(gsonRead));
        System.out.println("jacksonR    gsonW:\t" + gson.toJson(jacksonRead));
        System.out.println("hutoolR  jacksonW:\t" + jackson.writeValueAsString(hutoolRead));
        System.out.println("gsonR    jacksonW:\t" + jackson.writeValueAsString(gsonRead));
        System.out.println("jacksonR jacksonW:\t" + jackson.writeValueAsString(jacksonRead));
    }
}
```
2. 原始JSON数据
```json
{"recommend_text":"✅宁波，‌一座历史悠久的文化名城，‌承载着丰富的文化遗产和深厚的文化底蕴。‌让我们一起来探索这座千年古城的历史文化底蕴！ n✅宁波名城文博游推荐景点： n📍天一阁博物院，感受千年藏书楼的古籍魅力； n📍宁波博物馆，了解历史文物的“生命”历程...... n✅已为您整理宁波名城文博游路线。"}
```

3. 输出结果
<img width="1634" alt="image" src="https://github.com/user-attachments/assets/f7f2b6b0-76bc-4d4d-8566-a50b850b40e6">

**Comment by CherryRum** [comment]
![image](https://github.com/user-attachments/assets/9a75f923-29f6-47ec-94c8-9cb567e70167)
应该是你的原始字符串就有.

**Comment by sppan24** [comment]
> ![image](https://private-user-images.githubusercontent.com/24296698/392620517-9a75f923-29f6-47ec-94c8-9cb567e70167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzAxMDUsIm5iZiI6MTczMzM2OTgwNSwicGF0aCI6Ii8yNDI5NjY5OC8zOTI2MjA1MTctOWE3NWY5MjMtMjlmNi00N2VjLTk0YzgtOWNiNTY3ZTcwMTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAzMzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMWU0MGNlY2M5MGE1OTBlMWE0ZGY0NmJjYWM4MDZiZmU5ZTAwYmQ2YjY5ZGU1MjQ5OGQ3YTJjZDQ2OTRkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uVXpcBybjCiKv69NkxK1WL9GMznJIgoywrVDCet19p0) 应该是你的原始字符串就有.

哦？那意思是只有hutool的行为是正确的，其他的库全都不对吗😄

**Comment by sppan24** [comment]
或者换句话来说，序列化以后直接把Unicode展示出来了，是否代表着已经改变了原来的数据呢？两位不用那么着急关单吧，都不觉得这个是个可以讨论的话题吗？ @looly @CherryRum

**Comment by looly** [comment]
@sppan24 Hutool回答风格，就是每次回复都关闭issue，表示这个问题已经回答了，如果有补充或问题，再重新打开即可。

按照JSON规范，你的JSON中不应该有这类不可见字符，都要转成Unicode表示形式的，Hutool中为了兼容，默认解析这个不可见字符，输出时自动给escape成unicode表现形式。

Jackson之类的库中，也可以配置是否宽松解析。

规范见：https://www.rfc-editor.org/rfc/rfc8259#section-7

**Comment by sppan24** [comment]
> @sppan24 Hutool回答风格，就是每次回复都关闭issue，表示这个问题已经回答了，如果有补充或问题，再重新打开即可。
> 
> 
> 
> 按照JSON规范，你的JSON中不应该有这类不可见字符，都要转成Unicode表示形式的，Hutool中为了兼容，默认解析这个不可见字符，输出时自动给escape成unicode表现形式。
> 
> 
> 
> Jackson之类的库中，也可以配置是否宽松解析。
> 
> 
> 
> 规范见：https://www.rfc-editor.org/rfc/rfc8259#section-7

首先感谢解答。我个人作为用户的角度来考虑这个事情的话，开启escape的行为默认关闭会更加合理一些。

**Comment by looly** [comment]
@sppan24 我先暂时打开此issue。

针对不可见字符，我写个对比测试和配置吧，每个库的默认行为不同，稍后补充用例。

**Comment by CherryRum** [comment]
我记得，gson是默认处理了这个字符。而这种配置类的问题，每个人都有自己的想法。



---原始邮件---
发件人: "Golden ***@***.***&gt;
发送时间: 2024年12月5日(周四) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/hutool] JSONUtil工具toJsonStr生成的JSON字符串出现ZERO WIDTH NON-JOINER (Issue #3808)




 
@sppan24 我先暂时打开此issue。
 
针对不可见字符，我写个对比测试和配置吧，每个库的默认行为不同，稍后补充用例。

**Comment by looly** [comment]
@sppan24 我觉得这里加个配置比较好。

6.0.0-M19会在`JSONConfig`中增加`setIgnoreZeroWithChar`方法，可选是对零宽字符做丢弃处理还是转义处理

```java
final String str = ResourceUtil.readStr("issue3808.json", CharsetUtil.UTF_8);
final JSON parse = JSONUtil.parse(str, JSONConfig.of().setIgnoreZeroWithChar(true));
```

**Comment by sppan24** [comment]
> @sppan24 我觉得这里加个配置比较好。
> 
> 
> 
> 6.0.0-M19会在`JSONConfig`中增加`setIgnoreZeroWithChar`方法，可选是对零宽字符做丢弃处理还是转义处理
> 
> 
> 
> ```java
> 
> final String str = ResourceUtil.readStr("issue3808.json", CharsetUtil.UTF_8);
> 
> final JSON parse = JSONUtil.parse(str, JSONConfig.of().setIgnoreZeroWithChar(true));
> 
> ```

赞
