### ISSUE TITLE
cn.hutool.core.util.NumberUtil#roundStr(java.lang.String, int) 保留小数值不正确

### ISSUE THREAD

**Issue by intjfyl** [looly/hutool#3809]
### 版本情况

JDK版本：    OpenJDK_1.8.0_411
hutool版本： 5.5.9

### 问题描述

1. 复现代码

```java
        System.out.println(NumberUtil.roundStr("9999999999999999.99", 2));  //输出结果不符合方法声明返回值规则
        System.out.println(NumberUtil.roundStr("11111111111111119.00", 2));
        System.out.println(NumberUtil.roundStr("7999999999999999.99", 2)); //输出结果不符合方法声明返回值规则
        System.out.println(NumberUtil.roundStr("699999999991999.92", 2)); //输出结果不符合方法声明返回值规则
        System.out.println(NumberUtil.roundStr("10.92", 2));
        System.out.println(NumberUtil.roundStr("10.99", 2));
```

输出结果：
10000000000000000.00
11111111111111119.00
8000000000000000.00
699999999991999.90
10.92
10.99

2. 堆栈信息
![image](https://github.com/user-attachments/assets/b58d6154-f5f0-46ad-8542-040807216199)

**Comment by looly** [comment]
旧版本bug吧。新版本没问题，请升级：

![image](https://github.com/user-attachments/assets/d55657e4-16ed-48df-b848-50201702f91e)
