### ISSUE TITLE
因安全问题，版本从5.6.7升级到5.8.25

### ISSUE THREAD

**Issue by wenbochang888** [looly/hutool#3810]
升级过程中，发现有些API内部逻辑变化，影响业务一些逻辑判断。
比如103500.00转中文
5.6.7版本：   壹拾万叁仟伍佰圆整
5.8.25版本：壹拾万**零**叁仟伍佰圆整

请问除此之外，是否还有其他内部逻辑变化，以后升级是否说明这种内部逻辑的改动。
虽然hutool这点看起来改动很小，但是上游业务量一大，hutool不知道业务是什么用法，会造成千奇百怪的影响

**Comment by CherryRum** [comment]
每次升级都有一个`https://github.com/dromara/hutool/releases`说明日志
你这个参考此处https://github.com/dromara/hutool/issues/3662
这不是逻辑变动,是bug修复,我们也没法做到怎么通知这种变更,因为日志不一定有人看,看的话不一定是每个人理解的那样,只能尽量完善.

**Comment by looly** [comment]
@wenbochang888 5.8.0开始与之前版本有一些可能的不兼容变化，见changelog中的不兼容变化部分：

https://hutool.cn/docs/#/CHANGELOG?id=_580m1-2022-03-28
