### ISSUE TITLE
安卓 WebView 默认用户代理字符串将被简化

### ISSUE THREAD

**Issue by CherryRum** [looly/hutool#3813]
The User-Agent string has been [reduced](https://developers.google.com/privacy-sandbox/protections/user-agent) in Chrome on Desktop and Chrome on Android platforms since Chrome 107. Beginning in Android 16, the default User-Agent string in Android WebView will be similarly reduced.
https://android-developers.googleblog.com/2024/12/user-agent-reduction-on-android-webview.html
影响:UA工具
版本:所有
需要使用新的正则
![image](https://github.com/user-attachments/assets/daaf6adf-7592-47f3-b5c3-3d76dfa0a335)

**Comment by looly** [comment]
![image](https://github.com/user-attachments/assets/477d74bf-f540-47a0-936a-a593c5a1d395)

我测试解析应该没啥问题，哪个部分解析有误？
