### ISSUE TITLE
Snowflake如何动态配置workerId

### ISSUE THREAD

**Issue by solano33** [looly/hutool#3815]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本：5.8.28（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
请问 分布式场景下如何动态设置workerId和dataCenterId。目前如下配置，但是起两个容器就很容易得到相同的workerId

1. 复现代码

```java
    private static final Snowflake snowflake;

    static {
        long dataCenterId = IdUtil.getDataCenterId(1);
        long workerId = IdUtil.getWorkerId(1, 12);
        snowflake = IdUtil.getSnowflake(workerId, dataCenterId);
        log.info("dataCenterId:{} workId:{}", dataCenterId, workerId);
    }

```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不同容器分配不同的workerId就行呗，不同的容器持有不同的`Snowflake`对象，workerId不重复即可。

**Comment by solano33** [comment]
> 不同容器分配不同的workerId就行呗，不同的容器持有不同的`Snowflake`对象，workerId不重复即可。

有动态配置的方式吗？我们这个场景打的镜像都是一样的，分配不同workerId得打不同镜像了

**Comment by looly** [comment]
IdUtil.getDataCenterId之类的方法依赖于网卡MAC地址，你打docker可能这个值是一样的。

好的办法是，通过打镜像根据镜像之间不同的部分生成ID（比如镜像Id）
