### ISSUE TITLE
JSON序列化字符串时，没有正常解析

### ISSUE THREAD

**Issue by curryhcy** [looly/hutool#3817]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.25（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
![image](https://github.com/user-attachments/assets/515996cb-7b88-449a-9fdb-754111b7a021)
如图，body的信息解析后丢失，对应的req是飞书的sdk中的CreateMessageReq对象，CreateMessageReqBody是由GSON注解。
对应飞书sdk版本
```
        <dependency>
            <groupId>com.larksuite.oapi</groupId>
            <artifactId>oapi-sdk</artifactId>
            <version>2.2.0</version>
        </dependency>
```
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
@curryhcy 我看了这个对象：

https://github.com/larksuite/oapi-sdk-java/blob/87ec3f6d2ca6f0090fbb40127fd715cadd8514c5/larksuite-oapi/src/main/java/com/lark/oapi/service/im/v1/model/CreateMessageReq.java#L66

![image](https://github.com/user-attachments/assets/b13492c9-67a8-4280-952e-c2247dd35af6)


参数名字叫`body`，getter方法名字叫做`getCreateMessageReqBody`，必然不匹配啊，所以这个字段没有解析。

**Comment by curryhcy** [comment]
OK，所以我们怎么能让他正常序列化出来呢？如截图，我们使用GSON和jackson都能序列化出来内容。

**Comment by looly** [comment]
@curryhcy 那你只能自定义序列化了。
