### ISSUE TITLE
HttpUtil 中 InputStreamResource 作为form字段时，无法正常上传文件。

### ISSUE THREAD

**Issue by tri5m** [looly/hutool#3819]
### 版本情况

JDK版本：    openjdk_17
hutool版本： 5.8.34

### 问题描述（包括截图）

![image](https://github.com/user-attachments/assets/fec4b08b-2ff7-4715-be5f-d128a40db455)

![image](https://github.com/user-attachments/assets/167b230e-dbf3-4fb3-a1fd-667f06160e81)

1. 复现代码
我从服务器上获取一个InputStream, 想上传到另一个服务器，当我构建表单使用new InputStreamResource(downloadRes.bodyStream())，作为文件file字段时，我的文件服务器获取不到file字段的信息，当我用File时就可以正常上传

**Comment by tri5m** [comment]
实际的另个InputStream是来自于其他的网络图片，
![image](https://github.com/user-attachments/assets/d2c70286-a396-4ee0-9d85-9e93f3cf91ae)

**Comment by tri5m** [comment]
通过测试，加入了Resource名称后就可以了
![image](https://github.com/user-attachments/assets/482b0304-9926-4d04-b554-dc773d702724)

**Comment by looly** [comment]
@trifolium-x 事实上，multipart中，Hutool根据`Resource.getName`获取文件名，根据扩展名判断类型，如果无法判断，则使用`application/octet-stream`。

如果需要自定义类型，自定义扩展名也可以，使用`HttpResource`，定义`contentType`也可以。
