### ISSUE TITLE
spring-boot devtool 使用Singleton报错

### ISSUE THREAD

**Issue by sunsulei** [looly/hutool#382]
springboot web项目,开启`devtool`.当检测到文件修改时会动态的重新加载文件.
使用`Singleton.get(X.class)`时会出现类型转换异常的错误.

[代码片段](https://gist.github.com/sunsulei/16ace8f308f8e2c51d5eb3d3fc12e967)

[报错片段](https://gist.github.com/sunsulei/b5baafbd3ffac85380ff9f9e153a7d6b)

**Comment by looly** [comment]
这个热部署确实会导致ClassLoader不同，可以调用destroy方法清理单例池。
