### ISSUE TITLE
cn.hutool.crypto.symmetric.AES.<init> 初始化阻塞整个java进程

### ISSUE THREAD

**Issue by bingxueai123456** [looly/hutool#3822]
### 版本情况

JDK版本：    java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
hutool版本：5.7.15

### 问题描述（包括截图）
当项目重启完成，第一次执行这个方法的时候，永远阻塞，30秒后，以后调用这个方法就没有问题。奇怪的是我在之前用的ECS centos7.8就没有问题，换了新机器就变成这样子了
1. 复现代码
![image](https://github.com/user-attachments/assets/057757c4-c721-49fd-9f6f-dacd1eb104c8)

```java
import cn.hutool.core.codec.Base64;
import cn.hutool.crypto.Mode;
import cn.hutool.crypto.Padding;
import cn.hutool.crypto.symmetric.AES;

import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

import com.jt.cupboard.constant.CupboardConstant;

import java.nio.charset.StandardCharsets;

/**
 * 解密前端传来的密码
 */
public class DecryptUtil {

    public static String decryptPassword(String encryptPassword) {
        AES aes = new AES(Mode.CBC, Padding.ZeroPadding, new SecretKeySpec(CupboardConstant.FRONT_PASSWORD.getBytes(), "AES"),
                new IvParameterSpec(CupboardConstant.FRONT_PASSWORD.getBytes()));

        return new String(aes.decrypt(Base64.decode(encryptPassword.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
    }
}

```

2. 堆栈信息
![image](https://github.com/user-attachments/assets/459dd053-bfd3-4226-a567-3d3851ef9955)

4. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
不排除旧版本中存在bug。

考虑升级到5.8.34试下。

后续补充再打开此issue。

**Comment by bingxueai123456** [comment]
<img width="771" alt="image" src="https://github.com/user-attachments/assets/9ff646a3-1405-4f04-9b35-75140a65f61a" />
![image](https://github.com/user-attachments/assets/057f337a-cb3c-4b37-a2ac-3cf0c8a2d388)

我用了5.8.34，还是不行，就是第一次使用的时候阻塞

**Comment by CherryRum** [comment]
您是用的`Oracle JDK`吗?
能换个`open jdk`试下吗

**Comment by looly** [comment]
我咋怀疑是jdk的bug

**Comment by CherryRum** [comment]
> 我咋怀疑是jdk的bug

应该是 Oracle JDK验证包的流程出的问题,哈哈,经典jce问题

**Comment by bingxueai123456** [comment]
> 您是用的`Oracle JDK`吗? 能换个`open jdk`试下吗

我试了下openJDk,的确解决了这个问题，但是我有个疑问，我之前在centos7上使用oracle jdk11是没有问题的，如图：
![image](https://github.com/user-attachments/assets/13ab4346-53b5-4618-a8bd-5108f678643d)
但是我现在把项目切换到了新的系统，用同样的oracle的jdk11就会卡住，如图：
<img width="792" alt="image" src="https://github.com/user-attachments/assets/9e23513e-c55f-4462-a60b-348c1338afdc" />

**Comment by CherryRum** [comment]
这个问题猜测很多的,首先网络这个机器阿里云的不知道和 Oracle那边是否是友好的,而且魔改的系统我怀疑有自己的限制.
