### ISSUE TITLE
请问HttpUtil如何完成流式请求

### ISSUE THREAD

**Issue by 15380831711** [looly/hutool#3824]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.34

**Comment by looly** [comment]
可以使用HttpRequest.create。

见：https://doc.hutool.cn/pages/HttpRequest/#%E4%BB%8B%E7%BB%8D

**Comment by 15380831711** [comment]
好的，谢谢

**Comment by 15380831711** [comment]
最新版本没有HttpRequest.create方法吗？

**Comment by looly** [comment]
@15380831711 哈哈，sorry，叫`HttpRequest.of`

**Comment by 15380831711** [comment]
@looly 好的，多谢
