### ISSUE TITLE
DateUtil#between返回值是否为负数-abs逻辑

### ISSUE THREAD

**Issue by sunsulei** [looly/hutool#3825]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.8.34（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
public static void main(String[] args) {
        DateTime start = DateUtil.parse("2024-11-11 00:00:00");
        DateTime end = DateUtil.offsetDay(start, 2);
        long between = DateUtil.between(start, end, DateUnit.DAY, false); 
        //between == 2   是否应该是 -2 更符合语义?  
        Console.log("当前时间：{}，两天后时间：{}，两天后与当前时间相差：{}天", start, end, between);
    }
```

**Comment by CherryRum** [comment]
```java
//-2 应该是这样吧,毕竟都是 end - start
long between = DateUtil.between(end,start,DateUnit.DAY, false); 
```

**Comment by sunsulei** [comment]
@CherryRum 
如果按照这样来说的话,  既然有了abs参数,  那么, 什么情况会返回负数呢?

**Comment by sunsulei** [comment]
```java
public static void main(String[] args) {
        //当前日期
        DateTime today = DateUtil.date();
        //某个合同到期时间
        DateTime someEndDay = DateUtil.parse("2024-01-01");
        
        //判断合同到期剩余天数. 
        //实际上: 合同老早就到期了.
        //那么,谁是start, 谁是end呢?
        long between = DateUtil.between(?, ?, DateUnit.DAY, false);
        //between == 2
        Console.log(between);
    }
```

**Comment by CherryRum** [comment]
> @CherryRum 如果按照这样来说的话, 既然有了abs参数, 那么, 什么情况会返回负数呢?
abs为true,会比较时间进行交换
```java
public static void main(String[] args) {
        DateTime start = DateUtil.parse("2024-11-11 00:00:00");
        DateTime end = DateUtil.offsetDay(start, 2);
        long between = DateUtil.between(end,start, DateUnit.DAY, false); 
        //between == -2
         long between1 = DateUtil.between(end,start, DateUnit.DAY, true); 
        //between == 2
    }
```

**Comment by CherryRum** [comment]
还有工具类不关心业务,比较的是语言 between

**Comment by sunsulei** [comment]
> 还有工具类不关心业务,比较的是语言 between

所以感觉歧义的地方就是, 入参上明确了start end.  但是使用上, 更好理解的应该是左边比较右边.

**Comment by CherryRum** [comment]
这个开关只是帮你获取一个差值,比如昨天和今天差一天,今天和昨天差一天,你既然已经明确了你需要**负数**.
你的业务上一定可以确定是两个值进行对比,这取决与产品属性的定义

**Comment by CherryRum** [comment]
> 这个开关只是帮你获取一个差值,比如昨天和今天差一天,今天和昨天差一天,你既然已经明确了你需要**负数**. 你的业务上一定可以确定是两个值进行对比,这取决与产品属性的定义

按照您的例子,业务上不应该判断下正负吗
```java
// 当前日期
DateTime today = DateUtil.today();
// 某个合同到期时间
DateTime someEndDay = DateUtil.parse("2024-01-01");
// 计算剩余天数，DateUtil.between() 返回的值取决于日期顺序
// 输出剩余天数，若合同已过期则返回负数，若合同还有剩余时间则返回正数
System.out.println("剩余天数: " + between);
```

**Comment by sunsulei** [comment]
我理解你的意思，并且我理解工具本身，就是比较的 start 和 end 的间隔。

我的问题是会不会带来一个使用上的歧义，如果我从某个地方拿到了两个日期，我得先判断谁大谁小，然后把小的，作为 start 参数传进去。反之作为 end 传进去。

如果变成类似 compare 的逻辑，但是返回的不是-1 0 1 ，而是实际的间隔。并且根据 abs 参数，决定是不是需要处理负数。
这样，不需要关注谁大谁小，谁作为 start。

**Comment by sunsulei** [comment]
或者, 换一个角度, 如果我前置做了一些处理(谁大谁小), 那么这个abs字段就显得鸡肋了.

**Comment by CherryRum** [comment]
> 我理解你的意思，并且我理解工具本身，就是比较的 start 和 end 的间隔。 我的问题是会不会带来一个使用上的歧义，如果我从某个地方拿到了两个日期，我得先判断谁大谁小，然后把小的，作为 start 参数传进去。反之作为 end 传进去。 如果变成类似 compare 的逻辑，但是返回的不是-1 0 1 ，而是实际的间隔。并且根据 abs 参数，决定是不是需要处理负数。 这样，不需要关注谁大谁小，谁作为 start。

那就不是abs参数,会让用户感觉好复杂,现在这个参数本来就是放出来这个构造,满足需要自己处理的人使用,每个人都有自己的想法,所以没有完善的,你要作的工具,不是业务,假如你处理了谁大谁小，那这边确实少一个if了,时间本来就是整数,其实简单来说,你直接相减都没问题.

**Comment by sunsulei** [comment]
<img width="898" alt="image" src="https://github.com/user-attachments/assets/45025c4b-5ef5-4a2b-aa9f-0f730fa95991" />
从这个方法, 也一定程度上可以佐证我的问题. 默认情况下, 是取正整数的间隔返回的. 意味着, 使用方可以忽略谁大谁小.

同样的方法,  这个参数不传,默认为true,  如果想传呢, 还得考虑start end谁大谁小的问题.

**Comment by CherryRum** [comment]
**也一定程度上可以佐证我的问题. 默认情况下, 是取正整数的间隔返回的. 意味着, 使用方可以忽略谁大谁小？**
这个你从哪得来的?
我记得这玩意写的时候因为的原因是防止用户传反得到负数,内部判断下大小方便用户知道天数,然后暴漏出来原始的构造方便用户自己判断大小,不过兄弟我不和你唠了,您感觉你说的有道理,但是用户不一定觉得这个是好用的.

**Comment by sunsulei** [comment]
ok  没事，只是讨论而已，也没说一定要做出什么改变。发自我的 iPhone在 2024年12月26日，11:22，lin ***@***.***> 写道：﻿
也一定程度上可以佐证我的问题. 默认情况下, 是取正整数的间隔返回的. 意味着, 使用方可以忽略谁大谁小？
这个你从哪得来的?
我记得这玩意写的时候因为的原因是防止用户传反得到负数,内部判断下大小方便用户知道天数,然后暴漏出来原始的构造方便用户自己判断大小,不过兄弟我不和你唠了,您感觉你说的有道理,但是用户不一定觉得这个是好用的.

**Comment by looly** [comment]
@sunsulei 这个方法在不设置abs的情况下有几个作用：

1. 如果用户明确了先后，那between理论上都应该是正数，但是某些情况下是负数（比如系统事件回拨），这个时候产生负数就应该报错或有独立的处理逻辑，如果强制取绝对值，那会造成错误误判
2. 大部分场景我只需知道两个日期的差即可，这样传abs为true就不用关心传入的日期参数，比如在SQL查询中（between A and B）。

因为hutool作为工具提供者，应该给用户更多选择以适应不同场景，对常用场景提供一个默认值，这样即做到灵活又做到简单。

**Comment by sunsulei** [comment]
> @sunsulei 这个方法在不设置abs的情况下有几个作用：
> 
> 
> 
> 1. 如果用户明确了先后，那between理论上都应该是正数，但是某些情况下是负数（比如系统事件回拨），这个时候产生负数就应该报错或有独立的处理逻辑，如果强制取绝对值，那会造成错误误判
> 
> 2. 大部分场景我只需知道两个日期的差即可，这样传abs为true就不用关心传入的日期参数，比如在SQL查询中（between A and B）。
> 
> 
> 
> 因为hutool作为工具提供者，应该给用户更多选择以适应不同场景，对常用场景提供一个默认值，这样即做到灵活又做到简单。

ok，理解意思了。
