### ISSUE TITLE
6.0.0-M19 SpringUtil 的问题

### ISSUE THREAD

**Issue by refeccd** [looly/hutool#3826]
### 版本情况

hutool版本： 6.0.0-M19

在这个[commit](https://github.com/dromara/hutool/commit/26ac8750789c68c3dc4ed6e515eefba5f7107efa)，修改了getBean(clazz) 方法，加了重载的方法。
对于正常容器里的bean的获取是没问题的，但是如果是获取spring内部的bean，比如environment，会报错
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/eb979958-447a-4611-9e60-eb0bf6b93f05" />

**Comment by CherryRum** [comment]
嗯,确实不应该直接删除,单参数的重载
您这边先指定下
```java
getBean(clazz, (Object[]) null);
```
应该可以吧

**Comment by looly** [comment]
![image](https://github.com/user-attachments/assets/3ed51274-3da4-4749-acc4-98965af52d3b)

M20这么改造。
