### ISSUE TITLE
sax读取excel03版本整数有误

### ISSUE THREAD

**Issue by qing0504** [looly/hutool#383]
Excel03SaxReader文件263行代码：
```
// 对于无小数部分的数字类型，转为Long，否则保留原数字
value = (longPart == numValue) ? longPart : numValue;
```
不管longPart == numValue是否是true，三目运算符都不起作用，value的类型永远是Double，这样就导致excel中的数据是3，存储的时候变成了3.0

**Comment by looly** [comment]
longPart == numValue成立时，Object类型为Long，否则为Double。用户通过instanceof判断即可吧。有啥问题？

**Comment by qing0504** [comment]
可能我描述的意思不够明白，我说的意思是这里用三元运算符有坑，反编译class文件就能很容易看到，value的类型永远是Double，这是编译的时候就一定确定了的，所以value永远不可能是Long类型，只会强转成Double类型

**Comment by looly** [comment]
明白了，这块欠缺了。感谢。

**Comment by looly** [comment]
4.5.12修复此问题，感谢。
