### ISSUE TITLE
文档有笔误

### ISSUE THREAD

**Issue by yuanjiahui** [looly/hutool#390]
https://www.hutool.cn/docs/#/core/%E8%AF%AD%E8%A8%80%E7%89%B9%E6%80%A7/%E5%8D%95%E4%BE%8B%E5%B7%A5%E5%85%B7-Singleton

![image](https://user-images.githubusercontent.com/5235098/59253792-8dc93180-8c61-11e9-8f94-6c2d8d56368e.png)

**Comment by looly** [comment]
已修复，感谢。
