### ISSUE TITLE
JSON序列化的时候,知否可以提供出注解指定json序列化名称

### ISSUE THREAD

**Issue by chenshiyun2011github** [looly/hutool#394]
在使用hutool的json工具包的时候,因为正常的驼峰命名,是没有问题的,但是现在有需求是,字段跟序列化的名字不一样,比如
![image](https://user-images.githubusercontent.com/21190868/59583054-b68f7200-910c-11e9-89fc-ca37fd53997e.png)
遇到这两个不规范的命名,或者遇到一些想做保护的命名,需要指定他的名字进行序列化,因为
hutool的概念是不引入第三方的包,这样的话,hutool是否可以提供出一个注解,然后贴了后,就达到我截图里的效果,序列化的时候,可以指定某个序列化到某个列里去,我用的是最新版本的hutool
![image](https://user-images.githubusercontent.com/21190868/59583155-066e3900-910d-11e9-8fa2-92d9c4dea4ce.png)
目前序列化不进去的,如果不按照标准

**Comment by looly** [comment]
考虑注解侵入性比较强，因此没有支持。

考虑FastJSON，这块支持比较好。
