### ISSUE TITLE
关于 hutool 核心包下的 ArrayUtil 代码冗余问题

### ISSUE THREAD

**Issue by yangfancoming** [looly/hutool#398]
hutool 核心包下的 ArrayUtil 类中 已经有了 public static <T> boolean isEmpty(final T... array)
为什么还要 将8种基本类型的方法 都要写一遍呢？  是代码冗余 还是另有用途 ？  跪求解答

**Comment by looly** [comment]
因为泛型不能覆盖8种基本类型，泛型只能覆盖包装类型。

比如你定义了 int[] a = xxx;，是不能用这个方法的。

你可以看JDK的Arrays，里面也是一大堆。

**Comment by yangfancoming** [comment]
> 因为泛型不能覆盖8种基本类型，泛型只能覆盖包装类型。
> 
> 比如你定义了 int[] a = xxx;，是不能用这个方法的。
> 
> 你可以看JDK的Arrays，里面也是一大堆。

这个我用代码测试了  是可以使用的呢 ，你使用的是 可变形参   ...  符号  ，基本类型和包装类型 都是可以使用的。

**Comment by looly** [comment]
不知道你怎么写的代码，不过确实没法匹配。是基本类型而不是包装类型。

包装类型有自动拆装箱，但是基本类型的数组不行。如果还有疑问请加我QQ具体探讨：914104645，验证Hutool即可。
