### ISSUE TITLE
使用ImageUtil.read读取图片时报错

### ISSUE THREAD

**Issue by mxj009** [looly/hutool#400]
No stream adaptor found for javax.imageio.stream.FileImageInputStream!

at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at cn.hutool.core.util.ImageUtil.read(ImageUtil.java:1435)

**Comment by looly** [comment]
贴下代码，怀疑你用错对象了。或者参数直接传文件即可。

**Comment by mxj009** [comment]
知道原因了，因为整个工程引用了dcm4che-imageio.jar 使用ImageUtil.read的时候，不知道怎么调用到dcm4cher reader了。这里的解决方案是指定imagereader即可Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("jpg");

**Comment by looly** [comment]
好的。
