### ISSUE TITLE
cn.hutool.extra.ssh.JschUtil#exec(com.jcraft.jsch.Session, java.lang.String, java.nio.charset.Charset, java.io.OutputStream)

### ISSUE THREAD

**Issue by julyking0** [looly/hutool#405]
![image](https://user-images.githubusercontent.com/33617310/60006807-b874aa80-96a3-11e9-9ce2-3eb77c9a2daf.png)

设置完command，不执行channel.connect()，不会执行命令，没有执行结果的

**Comment by looly** [comment]
感谢。4.5.15修复此问题。
