### ISSUE TITLE
SystemUtil.getosInfo方法在windows server下报错

### ISSUE THREAD

**Issue by hanjiuri** [looly/hutool#408]
unexpected alert open: {Alert text : ?????} (Session info: chrome=75.0.3770.100): Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'INSTANCE-CYCR0R', ip: '172.16.0.6', os.name: 'Windows NT (unknown)', os.arch: 'amd64

**Comment by looly** [comment]
无法确定问题。请贴下代码和堆栈信息。

**Comment by hanjiuri** [comment]
我查了一下,应该是chromedriver的问题,不好意思
