### ISSUE TITLE
使用BigExcelWriter导出后xlsx文件  无法再使用reader读取文件数据 

### ISSUE THREAD

**Issue by dongxiaoqiang** [looly/hutool#409]
使用BigExcelWriter导出后xlsx文件  无法再使用reader读取文件数据  
数据导出是成功的  无法再次读取

**Comment by zyhui98** [comment]
代码能粘贴出来吗，有异常？

**Comment by dongxiaoqiang** [comment]
`public class HuToolExcelTest {

    public static void main(String[] args) {
        Map<String, Object> row1 = new LinkedHashMap<>();
        row1.put("姓名", "张三");
        row1.put("年龄", 23);
        row1.put("成绩", 88.32);
        row1.put("是否合格", true);
        row1.put("考试日期", DateUtil.date());

        Map<String, Object> row2 = new LinkedHashMap<>();
        row2.put("姓名", "李四");
        row2.put("年龄", 33);
        row2.put("成绩", 59.50);
        row2.put("是否合格", false);
        row2.put("考试日期", DateUtil.date());

        ArrayList<Map<String, Object>> rows = CollUtil.newArrayList(row1, row2);

        String path = "C:\\Users\\DongXiaoQiang\\Desktop\\1\\test.xlsx";
        BigExcelWriter writer = ExcelUtil.getBigWriter(path, "test");

        writer.write(rows, true);
        writer.close();

        System.out.println("使用reader");
        // 使用reader.read可以读出数据
        ExcelReader reader = ExcelUtil.getReader(path);
        List<List<Object>> readAll = reader.read(0, 5);
        System.out.println(readAll);


        // 使用SAX无法读取数据文件  无异常抛出
        System.out.println("使用sax");
        ExcelUtil.readBySax(path, 0, createRowHandler());
    }

    private static RowHandler createRowHandler() {
        return new RowHandler() {
            @Override
            public void handle(int sheetIndex, int rowIndex, List<Object> rowlist) {
                System.out.println("sax读取内容：" + rowlist);
            }
        };
    }
}
`

感谢回复，遇到的问题是：使用sax无法读取出BigExcelWriter写出的xlsx文件  使用office打开保存后一次后可以读出数据  无异常抛出，测试代码如上~

**Comment by dongxiaoqiang** [comment]
感谢你的回复，代码贴GitHub上了




------------------ 原始邮件 ------------------
发件人: 云辉 <notifications@github.com>
发送时间: 2019年6月26日 21:05
收件人: looly/hutool <hutool@noreply.github.com>
抄送: dongxiaoqiang <823440027@qq.com>, Author <author@noreply.github.com>
主题: 回复：[looly/hutool] 使用BigExcelWriter导出后xlsx文件  无法再使用reader读取文件数据  (#409)




代码能粘贴出来吗，有异常？

**Comment by zyhui98** [comment]
ok，是不是读写模式问题，xls，是否可以，有空我测试下

**Comment by looly** [comment]
问题出在这一行：

```Java
ExcelUtil.readBySax(path, 0, createRowHandler());
```

这里的sheetIndex不是序号，而是rid，传2即可：

```java
ExcelUtil.readBySax(path, 2, createRowHandler());
```

**Comment by wenren0819** [comment]
这个2代表的是什么？
