### ISSUE TITLE
请求增加数据是否过期校验

### ISSUE THREAD

**Issue by guaguawa** [looly/hutool#41]
如：一条数据，包含创建时间、有效期长短，过期判断。

public static void main(String[] args) {

    Date startDate = DateUtil.parseDateTime("2017-09-04 11:52:00");

    Date now = DateUtil.parseDateTime("2017-09-04 12:51:00");

    System.out.println(isExpired(startDate, now, 1, DateField.HOUR));
}

static boolean isExpired(Date startDate, Date nowDate, Integer timeLength, DateField dateField){

    Date endDate = DateUtil.offsiteDate(startDate, dateField, timeLength);

    return endDate.before(nowDate);

}

**Comment by lohaoo1** [comment]
请问jdk最低要哪个版本

**Comment by guaguawa** [comment]
1.7

**Comment by looly** [comment]
感谢~~3.1.1会加入此方法

**Comment by looly** [comment]
但是有个问题……就是判断过期应该是endDate.after(nowDate)吧？
