### ISSUE TITLE
目前不支持SQL Server 2008及以下分页查询。

### ISSUE THREAD

**Issue by tmluwei** [looly/hutool#413]

**Comment by zyhui98** [comment]
附上分页查询的代码，api比较多不知道你说的具体哪个方法

**Comment by tmluwei** [comment]
使用的是：
Db.use().page(***);
Db.use().pageForEntityList(***)
以上两个试了，均不可行。我看cn/hutool/db/dialect/DialectFactory.java第96行中对于SQLServer只有SqlServer2012Dialect，而cn/hutool/db/dialect/impl/SqlServer2012Dialect.java中分页SQL写法只支持了SQL Server 2012及最新的，SQL Server 2008及以下分页SQL不太一样。
目前在政府部门2008还是用的比较广泛的，期待支持。谢谢。

**Comment by looly** [comment]
Gitee已提，我先关闭这个了，在Gitee回复。
