### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [looly/hutool#416]
Hi
The following lines have cryptographic API misuses. <br> File name => hutool-crypto/src/main/java/cn/hutool/crypto/digest/HMac.java: Line number => 82: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 402: API name => KeyPairGenerator:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/digest/Digester.java: Line number => 93: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 426: API name => KeyPairGenerator:Unexpected call to method generateKeyPair on object of type java.security.KeyPairGenerator. Expect a call to one of the following methods initialize<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/digest/Digester.java: Line number => 89: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/DESede.java: Line number => 174: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/SymmetricCrypto.java: Line number => 134: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to init<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/SymmetricCrypto.java: Line number => 131: API name => PBEParameterSpec:Second parameter (with value 100)Variable iterationCountmust be  at least 1000<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 127: API name => SecretKeySpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/DES.java: Line number => 173: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/digest/HMac.java: Line number => 70: API name => SecretKeySpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/asymmetric/Sign.java: Line number => 160: API name => Signature:Operation on object of type java.security.Signature object not completed. Expected call to initSign, initVerify<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/AES.java: Line number => 127: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 106: API name => KeyGenerator:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/asymmetric/AsymmetricCrypto.java: Line number => 173: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to init<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/DES.java: Line number => 127: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/DESede.java: Line number => 128: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 127: API name => SecretKeySpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/symmetric/AES.java: Line number => 173: API name => IvParameterSpec:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 422: API name => KeyPairGenerator:Unexpected call to method generateKeyPair on object of type java.security.KeyPairGenerator. Expect a call to one of the following methods initialize<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/KeyUtil.java: Line number => 98: API name => KeyGenerator:First parameter (with value "DES") should be any of {AES, Blowfish, DESede, HmacSHA224, HmacSHA256, HmacSHA384, HmacSHA512}<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/SecureUtil.java: Line number => 288: API name => Signature:<BR> File name => hutool-crypto/src/main/java/cn/hutool/crypto/digest/HMac.java: Line number => 70: API name => SecretKeySpec:<BR> File name => hutool-core/src/main/java/cn/hutool/core/lang/UUID.java: Line number => 143: API name => MessageDigest:<BR> File name => hutool-core/src/main/java/cn/hutool/core/lang/UUID.java: Line number => 139: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => hutool-core/src/main/java/cn/hutool/core/lang/UUID.java: Line number => 143: API name => MessageDigest:<BR>

**Comment by looly** [comment]
Sorry, I dont understand how misuses in this code?
