### ISSUE TITLE
请问是否有推荐与此项目配套的iOS SM2 加解密工具包

### ISSUE THREAD

**Issue by tuxuzhang-me** [looly/hutool#418]
现在在网上找了很多关于关于Gmssl SM2 加解密的工具包，与此工具包中提供的SM2加解密 都不能互通。请问是否有关于iOS 的工具包，或去他解决方案推荐。感谢！！！

**Comment by looly** [comment]
IOS没有测试过，Hutool的SM2使用的是bouncycastle库的实现。

尝试：

1、新版本的Hutool默认加密顺序是C1C3C2，如果IOS使用了旧模式，通过`setMode()`方法设置模式。

2、IOS加密或者Hutool加密可能开头多出`04`，去掉后尝试。
