### ISSUE TITLE
建议实现类似spring boot的profile功能

### ISSUE THREAD

**Issue by ltylty** [looly/hutool#419]
spring boot的profile功能，可以让一个jar包在不同的环境启用不同的配置。希望hutool也添加这个功能，方便打包部署。
我在源码里看到GlobalProfile这个类，但是这个类在初始化配置文件时没有用上。

**Comment by looly** [comment]
Setting中有Profile类，因为Hutool并不是框架，无法控制系统的启动和关闭，因此推荐：

1、使用框架的Profile机制
2、使用Maven的profile插件定义环境和配置文件。
