### ISSUE TITLE
生成图形验证码字符位置调整建议

### ISSUE THREAD

**Issue by gooree** [looly/hutool#421]
建议生成的图形验证码位置稍微靠下部进行微调，现在的位置太靠上了，有的字符显示不全。看了下源码现在是按照默认字体大小来计算的，建议可以改为按照图片高度进行调整。
目前的效果见下图：
![Jietu20190704-135829](https://user-images.githubusercontent.com/1580066/60642894-eefcb300-9e63-11e9-9c9a-0b6ca0a39349.jpg)

**Comment by gooree** [comment]
以下是hutool-captcha和jcaptcha的对比效果：

- hutool-captcha
![Jietu20190704-162156](https://user-images.githubusercontent.com/1580066/60651075-05ad0500-9e78-11e9-9aeb-63c195b66ed6.jpg)
- jcaptcha
![Jietu20190704-162057](https://user-images.githubusercontent.com/1580066/60651103-12315d80-9e78-11e9-98ac-796d1cf725c4.jpg)

可以看到hutool-captcha的验证码位置明显偏高一些

**Comment by looly** [comment]
4.5.17解决此问题，感谢。
