### ISSUE TITLE
JSONUtil.toJsonPrettyStr(Optional<T>)

### ISSUE THREAD

**Issue by ttt307307** [looly/hutool#426]
```
Optional<Integer> value = Optional.of(7);
System.ou.println(JSONUtil.toJsonPrettyStr(value));
```
result:
`{
}`
not: 7

**Comment by looly** [comment]
Optional并非一个bean对象，也非一个key value成对的值，无法转换为JSON。因此输出空。

**Comment by ViCrack** [comment]
json部分实现得比较简单只判断了有getter这些标准的javabean了吧
相比阿里的fastjson,google的gson却能输出来

**Comment by looly** [comment]
是滴，不过只输出一个7或者{7}并不是一个标准json，除非输出[7]。

稍后我会测试fastjson如何输出，感谢。

**Comment by ViCrack** [comment]
fastjson是特殊处理过了,com.alibaba.fastjson.parser.deserializer.OptionalCodec,对于Optional类就是直接提取出value来当成Integer.
而gson则是{"value":7}看起来比较常规点
而Jackson则是{"present":true},估计是跑远了把方法名来处理了
