### ISSUE TITLE
Visual studio error

### ISSUE THREAD

**Issue by mishraanmol** [looly/hutool#43]
When I try and follow the windows instructions in the readme I get the following error:

cl.exe /nologo /O2 /EHsc /D "_CRT_SECURE_NO_DEPRECATE" /D "USEOMP" /openmp tsne.obj sptree.obj -Fewindows\bh_tsne.exe
libcpmt.lib(xthrow.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1900' doesn't match value '1800' in tsne.obj
libucrt.lib(hypot.obj) : error LNK2005: hypot already defined in tsne.obj
windows\bh_tsne.exe : fatal error LNK1169: one or more multiply defined symbols found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe"' : return code '0x2'
Stop.

I'm not sure how I can edit the tsne.obj file to adjust this, any advice?

**Comment by mishraanmol** [comment]
I got this :)

**Comment by looly** [comment]
Sorry about this issue is not related to Hutool.

**Comment by mishraanmol** [comment]
I already closed the issue, By mistake, I opened an issue in the wrong repository.
I apologize for the same
