### ISSUE TITLE
设置excel样式时遇到的问题

### ISSUE THREAD

**Issue by VanMesure** [looly/hutool#432]
有两个excel， 我获取了第一个excel的StyleSet（reader.getWriter().getStyleSet()），然后设置给第二个excel（writer.setStyleSet(styleSet)），结果报错：
`
java.lang.IllegalArgumentException: This Style does not belong to the supplied Workbook Stlyes Source. Are you trying to assign a style from one workbook to the cell of a differnt workbook?
	at org.apache.poi.xssf.usermodel.XSSFCellStyle.verifyBelongsToStylesSource(XSSFCellStyle.java:119)
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellStyle(XSSFCell.java:651)
····
`

有什么办法能解决这个问题吗？  
我的本意是想将一个excel复制一份，然后更改里边部分单元格的内容， 但是写入完了第二个单元格后所有样式都丢失了，所以我才想用上面这种方法设置一下， 但是也不管用。

**Comment by looly** [comment]
不可以夸工作簿（workbook）共享样式，尝试重新创建，
