### ISSUE TITLE
TextSimilarity 对文本进行相似度匹配有bug。

### ISSUE THREAD

**Issue by VirensCn** [looly/hutool#435]
`String newStrA, newStrB;`在removeSign后这2个变量就全是 falsetruefalsetrue（由false/true组成的字符串）了。导致后面匹配的相似度根本不是文本相似度。

`	// --------------------------------------------------------------------------------------------------- Private method start
	/**
	 * 将字符串的所有数据依次写成一行，去除无意义字符串
	 * 
	 * @param str 字符串
	 * @return 处理后的字符串
	 */
	private static String removeSign(String str) {
		StringBuilder sb = StrUtil.builder(str.length());
		// 遍历字符串str,如果是汉字数字或字母，则追加到ab上面
		int length = str.length();
		for (int i = 0; i < length; i++) {
			sb.append(charReg(str.charAt(i)));
		}
		return sb.toString();
	}

	/**
	 * 判断字符是否为汉字，数字和字母， 因为对符号进行相似度比较没有实际意义，故符号不加入考虑范围。
	 * 
	 * @param charValue 字符
	 * @return 是否为汉字，数字和字母
	 */
	private static boolean charReg(char charValue) {
		return (charValue >= 0x4E00 && charValue <= 0XFFF) || //
				(charValue >= 'a' && charValue <= 'z') || //
				(charValue >= 'A' && charValue <= 'Z') || //
				(charValue >= '0' && charValue <= '9');
	}`

**Comment by looly** [comment]
4.5.18修复此问题，感谢。
