### ISSUE TITLE
建议DateUtil类可以传入一个Locale对象

### ISSUE THREAD

**Issue by GreenHatHG** [looly/hutool#437]
事情是这样
昨天我的日期格式化类还能运作，但是今天就报错了，如下
<img src="https://i.loli.net/2019/07/21/5d3438f939f3b26833.png">

然后我debug了一遍，发现它我输入的英文识别成中文了
<img src="https://i.loli.net/2019/07/21/5d3439a5d5b7447146.png">

所以我用如下代码定义语言，然后就可以了
<img src="https://i.loli.net/2019/07/21/5d343a0b3b36570583.png">
所以我建议DateUtil类可以传入一个Locale对象，以防出现这种情况

**Comment by looly** [comment]
感谢。

DateUtil.parse方法支持传入SimpleDateFormat对象。


4.5.18增加此方法：

![image](https://user-images.githubusercontent.com/1432613/61603762-6a869e80-ac71-11e9-86be-05d366f63f79.png)
