### ISSUE TITLE
建议新增一个自动生成HTML提交方法

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#439]
目前，大部分互联网都支持网关支付业务，网关支付对接的特点就是商户网站组织form表单数据，页面自动提交到银行的url。

建议增加这类方法到工具中。

如下这样的代码。

`

  public static String createAutoFormHtml(String reqUrl, Map<String, String> hiddens, String encoding) {
    StringBuffer sf = new StringBuffer();
    sf.append("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=" + encoding + "\"/></head><body>");
    sf.append("<form id = \"pay_form\" action=\"" + reqUrl
        + "\" method=\"post\">");
    if (null != hiddens && 0 != hiddens.size()) {
      Set<Map.Entry<String, String>> set = hiddens.entrySet();
      Iterator<Map.Entry<String, String>> it = set.iterator();
      while (it.hasNext()) {
        Map.Entry<String, String> ey = it.next();
        String key = ey.getKey();
        String value = (String) ey.getValue();
        sf.append("<input type=\"hidden\" name=\"" + key + "\" id=\""
            + key + "\" value=\"" + value + "\"/>");
      }
    }
    sf.append("</form>");
    sf.append("</body>");
    sf.append("<script type=\"text/javascript\">");
    sf.append("document.all.pay_form.submit();");
    sf.append("</script>");
    sf.append("</html>");
    return sf.toString();
  }

`

**Comment by looly** [comment]
因为每个form表单字段不一样，且都是模拟post请求，所以请使用HttpUtil.post即可。
