### ISSUE TITLE
ImageUtil.pressImage()添加图片水印方法，没有释放资源

### ISSUE THREAD

**Issue by DullSky** [looly/hutool#44]
![image](https://user-images.githubusercontent.com/15259698/30265820-f76e9484-970f-11e7-981b-2585c42b14cb.png)

调用 ImageUtil.pressImage() 方法后，执行delete无法删除，报如下错误
2017-09-11 16:40:16
[ERROR]-[Thread: qtp632249781-29]-[com.jfinal.core.ActionHandler.handle()]: /edu/teacher/getLearningCardImage
com.jfinal.render.RenderException: com.xiaoleilu.hutool.io.IORuntimeException: FileSystemException: E:\IdeaCode\AgentAPI\src\main\webapp\temp\fb1facb023054ef99c8a58c0c9733763.png: 另一个程序正在使用此文件，进程无法访问。

在这里qrcodeFile和destFile都是作为临时文件用的，用过之后要删除，但是发现删除不掉

**Comment by looly** [comment]
确认bug，感谢Issue~~
