### ISSUE TITLE
Monitoring multiple paths will create multiple threads

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#440]
比如Setting模块的autoload功能也是调用了WatchMonitor来实现的
每增加一个路径的监听都会导致WatchMonitor多创建一个线程出来

所以我想是否能保持系统只有一个监听线程的情况下,利用不同的Path来register,
cn.hutool.core.io.watch.WatchMonitor.watch(Watcher)  然后在这里take之后取出来WatchKey得到对应不同的Path进行转发通知watcher.做到一个Monitor就能同时监控多个文件夹的变动,无需创建多余的线程.

而且能通过WatchKey的cancel方法,取消掉某个path的监听

这种优化可行性如何?

下面的文件是我简单写的一个例子
[Watch.txt](https://github.com/looly/hutool/files/3422643/Watch.txt)

**Comment by looly** [comment]
这个需求暂时搁置。等有时间我研究下。感谢。

**Comment by looly** [comment]
5.1.0增加WatchServer类，后续再继续改造。
