### ISSUE TITLE
能否把poi的版本升级到最新版本

### ISSUE THREAD

**Issue by ylh23y** [looly/hutool#442]
我的项目的poi的版本和hutool的poi有冲突

**Comment by firekcc** [comment]
你可以排除掉统一一个你的版本，假如另外一个人用的是稳定版怎么办

**Comment by looly** [comment]
hutool要求poi大于等于3.17，且非关联依赖，都是你自行引入的。

**Comment by ylh23y** [comment]
> 你可以排除掉统一一个你的版本，假如另外一个人用的是稳定版怎么办
> […](#)
> 在 2019年7月24日，14:05，http-client ***@***.***> 写道： 我的项目的poi的版本和hutool的poi有冲突 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

那就都给升级一下了
