### ISSUE TITLE
源代码有问题

### ISSUE THREAD

**Issue by RamonZhao** [looly/hutool#449]
ImgUtil 中 hexToColor 中  调用 StrUtil.removePrefix 参数传反了，详情见图
![TIM图片20190725201233](https://user-images.githubusercontent.com/6092627/61873470-a5f6c680-af18-11e9-9099-719f45f871b4.png)
![TIM图片20190725201240](https://user-images.githubusercontent.com/6092627/61873474-a68f5d00-af18-11e9-992d-280fa782f14b.png)

**Comment by looly** [comment]
4.6.0修复此问题。感谢。
