### ISSUE TITLE
数组工具能否加上数组交换的方法swap()

### ISSUE THREAD

**Issue by th0o0** [looly/hutool#450]
数组可以加上
`private void swap (int[] nums, int a, int b){  
  int temp = nums[a];
  nums[a] = nums[b];
  nums[b] = temp;
}`

**Comment by looly** [comment]
ArrayUtil有这个方法啊：

![image](https://user-images.githubusercontent.com/1432613/61931411-223de800-afb3-11e9-8dcd-58072c0e2f8a.png)

**Comment by th0o0** [comment]
哦哦，不好意思
