### ISSUE TITLE
镂空的png 图片缩放后不镂空，显示黑色的

### ISSUE THREAD

**Issue by RamonZhao** [looly/hutool#452]
1，测试代码如下
![TIM图片20190726170238](https://user-images.githubusercontent.com/6092627/61940060-44416580-afc7-11e9-8eeb-f187b0b4cf6d.png)
新方法如下
![TIM图片20190726170257](https://user-images.githubusercontent.com/6092627/61940088-50c5be00-afc7-11e9-9f5f-f8ff739ad80d.png)
hutool.png图片如下：
![hutool](https://user-images.githubusercontent.com/6092627/61940153-689d4200-afc7-11e9-9ceb-6941b8161f95.png)
newMethod.png 图片如下：
![newMethod](https://user-images.githubusercontent.com/6092627/61940184-781c8b00-afc7-11e9-86b7-19e42d7ccbee.png)
测试用的图片如下
![source](https://user-images.githubusercontent.com/6092627/61940217-88cd0100-afc7-11e9-9e47-26df8834965f.png)

**Comment by looly** [comment]
Hutool是按照目标的文件扩展名判断是否需要透明的，因此：

```java
ImgUtil.scale(FileUtil.file("f:/test/test.png"), FileUtil.file("f:/test/test_result.png"), 0.5f);
```

这么用就没问题，只有传入目标文件才可以。

**Comment by RamonZhao** [comment]
thx
