### ISSUE TITLE
Convert.toList 时，列表里包含子列表，不能按照指定的类型去转换

### ISSUE THREAD

**Issue by lvhaiyan888** [looly/hutool#453]
Convert.toList 时，列表里包含子列表，不能按照指定的类型去转换，子类型。还是原来的类型，没有办法重新指定为新类型

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/61958203-7668bc80-aff3-11e9-8cf3-7f83336c3ab2.png)


需要这个方法，自定义TypeReference，以便定义子属性中的泛型对应类型。
