### ISSUE TITLE
enhancement cn.hutool.core.exceptions.ExceptionUtil

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#459]
希望能增强关于异常处理的功能

![图片](https://user-images.githubusercontent.com/18179821/62223480-90d1da00-b3e7-11e9-8abc-0b9848503cee.png)

> cn.hutool.core.exceptions.ExceptionUtil.wrapRuntime(Throwable)

不知道这里的代码为什么有些是throw,而有些却又只是return,如果确定是要全部自动throw,是不是我们应该void之后去掉return,否则就明确全部包装后return

相比 apache commons 缺少一些getRootxxxx等方法

比如

> org.apache.commons.lang3.exception.ExceptionUtils.getRootCauseMessage(Throwable)
> org.apache.commons.lang3.exception.ExceptionUtils.getRootCause(Throwable)

这好像挺好用的

**Comment by looly** [comment]
4.6.2修正并加入这些方法，并增加wrapAndThrow方法。感谢。
