### ISSUE TITLE
Excel工具类,希望能支持根据传入的列头自动,导出Excel

### ISSUE THREAD

**Issue by l745230** [looly/hutool#461]
比如查询数据源共4个字段,id,name,tel,remark
传入列头为
LinkedHashMap<String, String> rowMap = new LinkedHashMap();
        rowMap.put("name", "客户名称");
        rowMap.put("tel", "客户联系方式");
导出Excel只要2个字段. 目前是没在列头中的字段默认渲染在最前面.

**Comment by looly** [comment]
setOnlyAlias即可。
