### ISSUE TITLE
建议添加根据request获取访问ip与mac地址接口~~

### ISSUE THREAD

**Issue by l745230** [looly/hutool#462]

**Comment by looly** [comment]
有ServletUtil.getClient方法获取客户端ip，客户端mac没法获取。

**Comment by l745230** [comment]
/**
     * 通过IP地址获取MAC地址
     *
     * @param ip String,127.0.0.1格式
     * @return mac String
     * @throws Exception
     */
    public static String getMACAddress(String ip) {
        String line;
        BufferedReader br = null;
        String macAddress = null;
        final String macAddressPrefix = "MAC Address = ";
        final String loopBackAddress = "127.0.0.1";
        try {
            //如果为127.0.0.1,则获取本地MAC地址。
            if (loopBackAddress.equals(ip)) {
                InetAddress inetAddress = InetAddress.getLocalHost();
                //貌似此方法需要JDK1.6。
                byte[] mac = NetworkInterface.getByInetAddress(inetAddress).getHardwareAddress();
                //下面代码是把mac地址拼装成String
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < mac.length; i++) {
                    if (i != 0) {
                        sb.append("-");
                    }
                    //mac[i] & 0xFF 是为了把byte转化为正整数
                    String s = Integer.toHexString(mac[i] & 0xFF);
                    sb.append(s.length() == 1 ? 0 + s : s);
                }
                //把字符串所有小写字母改为大写成为正规的mac地址并返回
                macAddress = sb.toString().trim().toUpperCase();
            } else {
                //获取非本地IP的MAC地址
                Process p = Runtime.getRuntime().exec("nbtstat -A " + ip);
                InputStreamReader isr = new InputStreamReader(p.getInputStream());
                br = new BufferedReader(isr);
                while ((line = br.readLine()) != null) {
                    if (line != null) {
                        int index = line.indexOf(macAddressPrefix);
                        if (index != -1) {
                            macAddress = line.substring(index + macAddressPrefix.length()).trim().toUpperCase();
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (null != br) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        return macAddress;
    }

网络上找到的根据ip获取mac地址的代码~  大佬看看会不会靠谱~~

**Comment by looly** [comment]
这是获取本地的ip和mac地址吧。你就算获取了也是服务器的mac地址，这个不正确

**Comment by l745230** [comment]
/**
     * 通过IP地址获取MAC地址
     *
     * @param ip String,127.0.0.1格式
     * @return mac String
     * @throws Exception
     */
    public static String getMACAddress(String ip) {
        String line;
        BufferedReader br = null;
        String macAddress = null;
        final String macAddressPrefix = "MAC Address = ";
        final String loopBackAddress = "127.0.0.1";
        try {
            //如果为127.0.0.1,则获取本地MAC地址。
            if (loopBackAddress.equals(ip)) {
                InetAddress inetAddress = InetAddress.getLocalHost();
                //貌似此方法需要JDK1.6。
                byte[] mac = NetworkInterface.getByInetAddress(inetAddress).getHardwareAddress();
                //下面代码是把mac地址拼装成String
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < mac.length; i++) {
                    if (i != 0) {
                        sb.append("-");
                    }
                    //mac[i] & 0xFF 是为了把byte转化为正整数
                    String s = Integer.toHexString(mac[i] & 0xFF);
                    sb.append(s.length() == 1 ? 0 + s : s);
                }
                //把字符串所有小写字母改为大写成为正规的mac地址并返回
                macAddress = sb.toString().trim().toUpperCase();
            } else {
                //获取非本地IP的MAC地址
                Process p = Runtime.getRuntime().exec("nbtstat -A " + ip);
                InputStreamReader isr = new InputStreamReader(p.getInputStream());
                br = new BufferedReader(isr);
                while ((line = br.readLine()) != null) {
                    if (line != null) {
                        int index = line.indexOf(macAddressPrefix);
                        if (index != -1) {
                            macAddress = line.substring(index + macAddressPrefix.length()).trim().toUpperCase();
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (null != br) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        return macAddress;
    }

网上根据ip查找mac,看看会不会靠谱~~

**Comment by l745230** [comment]
有两个分支,获取本机mac跟非本地mac
Runtime.getRuntime().exec("nbtstat -A " + ip);

**Comment by looly** [comment]
这也是本机mac啊，linux命令
