### ISSUE TITLE
CacheUtil构建缓存时,获取缓存未命中时，关于missCount的计数问题

### ISSUE THREAD

**Issue by vayneluo** [looly/hutool#465]
如果AbstractCache中get缓存过期，remove方法移除当前cacheMap中的缓存对象，记录missCount
![image](https://user-images.githubusercontent.com/40878619/62282923-09d23f80-b483-11e9-9d3a-bd25a5ee47a9.png)
执行removeWithoutLock(K key, boolean withMissCount),如果缓存过期了，missCount--后值为-1
是否应该是记录每次命中丢失的次数？
![image](https://user-images.githubusercontent.com/40878619/62283055-4a31bd80-b483-11e9-8dc3-bf19fb1b6213.png)

**Comment by looly** [comment]
确认bug，remove时候与missCount无关。感谢。
