### ISSUE TITLE
HttpUtil在进行inflate处理未能解析出正确的数据

### ISSUE THREAD

**Issue by cj506817364** [looly/hutool#466]
用postman可以请求道正确数据,但是HttpUtil.get却不行
接口https://comment.bilibili.com/67573272.xml

![3245945B05F2C1C16C33F033009C67A8](https://user-images.githubusercontent.com/33059555/62332641-f65ebd00-b4f2-11e9-9709-d334f9c11823.jpg)

**Comment by looly** [comment]
此链接返回格式为：`Transfer-Encoding: chunked`，测试过很多方法没有成功。

此问题暂时搁置。

**Comment by looly** [comment]
5.0.2修复此问题：

感谢来自：https://github.com/looly/hutool/pull/593
