### ISSUE TITLE
FileTypeUtil中无法获取2007以后版本office文件类型。

### ISSUE THREAD

**Issue by WayneLee5991** [looly/hutool#471]
2007后office前n个byte值和zip格式有一部分是重复的，但是，后面是有不一样的！例如我们将office取值为‘504B030414000600080000002100’，这样就可以区分zip和office了。使用puyfileType方法也无法正确获取到，只能得到zip。

**Comment by looly** [comment]
恩，这个并不准确，因为xlsx也是zip，后边的不同的可能是内容不同。
