### ISSUE TITLE
关于httpUtil模块的返回结果集识别度不友好

### ISSUE THREAD

**Issue by xiaobaogeit** [looly/hutool#472]
Request Headers: 
    Accept=[text/html,application/xhtml+xml,application/xml,application/json;q=0.9,*/*;q=0.8]
    User-Agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Hutool]
    Accept-Encoding=[gzip]
    Accept-Language=[zh-CN,zh;q=0.8]
    Content-Type=[application/json;charset=utf8]

以上是我调试模式获取的，我没有强设置任何头部信息，全部用的默认，明显Accept与Content-Type匹配不高，必须我强行设置Accept的application/json权重，我觉得程序是可以做到此方面的优化的

**Comment by looly** [comment]
修改了默认的权重，json有限。
