### ISSUE TITLE
AES加密使用碰到问题

### ISSUE THREAD

**Issue by cj506817364** [looly/hutool#474]
python代码写的AES加密用hutool实现的时候发现无法实现:
python代码:
![0170BEE78E64C742DEAE95FB80CC2A55](https://user-images.githubusercontent.com/33059555/62539594-22c66080-b888-11e9-9dcf-01fbc4f18e68.jpg)

def pkcs7padding(text):
    """
    明文使用PKCS7填充
    最终调用AES加密方法时，传入的是一个byte数组，要求是16的整数倍，因此需要对明文进行处理
    :param text: 待加密内容(明文)
    :return:
    """
    bs = AES.block_size  # 16
    length = len(text)
    bytes_length = len(bytes(text, encoding='utf-8'))
    # tips：utf-8编码时，英文占1个byte，而中文占3个byte
    padding_size = length if (bytes_length == length) else bytes_length
    padding = bs - padding_size % bs
    # tips：chr(padding)看与其它语言的约定，有的会使用'\0'
    padding_text = chr(padding) * padding
    return text + padding_text

def encrypt(key, content, iv):
    """
    AES加密
    key,iv使用同一个
    模式cbc
    填充pkcs7
    :param key: 密钥
    :param content: 加密内容
    :return:
    """
    key_bytes = bytes(key, encoding='utf-8')
    # iv = key_bytes
    cipher = AES.new(key_bytes, AES.MODE_CBC, iv.encode('utf-8'))
    # 处理明文
    content_padding = pkcs7padding(content)
    # 加密
    encrypt_bytes = cipher.encrypt(bytes(content_padding, encoding='utf-8'))
    # 重新编码
    result = ''.join(['%02x' % b for b in encrypt_bytes])
    return result

以上是python代码的截图和源码

调用: encrypt_en = encrypt(d, c, b).lower()
参数值: 
d => 0123456789ABHAEQ
c => 4321c9a2db2e6b08987c3b903d8d11ff
b => DYgjCEIMVrj2W9xN
encrypt_en = > cd0e3a249eaf0ed80c330338508898c4bddcfd665a1b414622164a273ca5daf7b4ebd2c00aaa66b84dd0a237708dac8e

**Comment by looly** [comment]
```java
String content = "4321c9a2db2e6b08987c3b903d8d11ff";
AES aes = new AES(Mode.CBC, Padding.PKCS5Padding, "0123456789ABHAEQ".getBytes(), "DYgjCEIMVrj2W9xN".getBytes());
		
// 加密为16进制表示
String encryptHex = aes.encryptHex(content);

Assert.assertEquals("cd0e3a249eaf0ed80c330338508898c4bddcfd665a1b414622164a273ca5daf7b4ebd2c00aaa66b84dd0a237708dac8e", encryptHex);
```
