### ISSUE TITLE
Excel工具类希望添加下拉选择功能

### ISSUE THREAD

**Issue by yilers** [looly/hutool#476]

**Comment by yilers** [comment]
如题，希望老哥加上下拉选择，如果有级联更好哦。
网上案列：https://blog.csdn.net/enshiwaer/article/details/53466431?locationNum=13&fps=1
级联案列：https://www.jianshu.com/p/922f90ba7ae9

**Comment by looly** [comment]
4.6.2增加addSelect方法，感谢。

**Comment by looly** [comment]
级联太麻烦了
