### ISSUE TITLE
Setting类 建议改良

### ISSUE THREAD

**Issue by Bophie** [looly/hutool#480]
Setting类
使用空构造函数创建对象
使用store(String absolutePath)持久化数据，无法正常保存数据，原因是字符集为空

/** 本设置对象的字符集 */
	protected Charset charset;
	/** 是否使用变量 */
	protected boolean isUseVariable;
	/** 设定文件的URL */
	protected URL settingUrl;
这些没有提供set方法，那么空构造函数没有意义吧？
我想用空构造创建对象是因为在保存数据时才确定保存的路径，在store的时候去设置路径。

/** 本设置对象的字符集 */
	protected Charset charset;
	/** 是否使用变量 */
	protected boolean isUseVariable;
	/** 设定文件的URL */
	protected URL settingUrl;

这些最好提供setter getter方法，charset设置一下默认

现在只有清除指定组的方法
public Setting clear(String group) 
建议加个清除所有组的方法
public Setting clearAll

**Comment by looly** [comment]
4.6.2改进此类
