### ISSUE TITLE
HttpUtil.post有问题(4.6.1版本）

### ISSUE THREAD

**Issue by dzjfromChina** [looly/hutool#482]
参数没有传过去
这个是微信获取标签下粉丝列表  现在我传参获取100下面的粉丝 按理说应该只有一个  但是获取到了全部
我把参数去掉  也是获取到全部
所以我猜测是没传
我自己写了一个 http 的post  是可以获取到一个粉丝的

        String url = "https://api.weixin.qq.com/cgi-bin/user/tag/get?access_token="+AccessToken;
        Map<String,Object> param = new HashMap();
        param.put("tagid",100);
        param.put("next_openid","");
        //post 有问题!
        String post = HttpUtil.post(url, param);
        System.out.println(post);
        String s = null;
        try {
            s = HttpPost.https(url,param);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(s);

**Comment by HHHQiang** [comment]
mark一下，有尝试请求其他的接口吗？

**Comment by looly** [comment]
微信接口的参数传递是使用的json，你用form方法肯定不行，你要用body方法传json参数才可以

**Comment by dzjfromChina** [comment]
> 
> 
> mark一下，有尝试请求其他的接口吗？
要传json字符串
