### ISSUE TITLE
使用FTP时报错

### ISSUE THREAD

**Issue by lishengsen** [looly/hutool#484]
cn.hutool.extra.ftp.FtpException: MalformedServerReplyException: Could not parse response code.
Server Reply: SSH-2.0-OpenSSH_5.3

**Comment by lishengsen** [comment]
> cn.hutool.extra.ftp.FtpException: MalformedServerReplyException: Could not parse response code.
> Server Reply: SSH-2.0-OpenSSH_5.3

通过了解是因为连接协议的问题，我通过FileZilla连接到host上，是以sftp://开头的

**Comment by dxx123** [comment]
我也遇到了这个问题

**Comment by looly** [comment]
需要使用SFTP，而非FTP。
