### ISSUE TITLE
邮件发送 springSender发送成功 hutool-mail发送失败

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#487]
前置条件：用的是腾讯企业邮箱
hutool代码如下（xxx为敏感信息）
MailAccount account = new MailAccount();
        account.setHost("smtp.exmail.qq.com");
        account.setPort(465);
        account.setSslEnable(true);
        account.setFrom("xxxx");
        account.setPass("xxx");
        account.setStartttlsEnable(true);
        MailUtil.send(account, "xxx", "测试", "<h1>邮件来自Hutool测试</h1>", true);
结果报错：javax.mail.AuthenticationFailedException: 535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256

spring java发送邮件代码如下：
JavaMailSenderImpl javaMailSender = new JavaMailSenderImpl();
        javaMailSender.setHost("smtp.exmail.qq.com");
        javaMailSender.setUsername("x'x'x");
        javaMailSender.setPassword("x'x'x");
        javaMailSender.setDefaultEncoding(StandardCharsets.UTF_8.toString());
        javaMailSender.setProtocol("smtp");
        javaMailSender.setPort(465);

        Properties properties = new Properties();
        properties.setProperty("mail.smtp.auth", "true");
        properties.setProperty("mail.smtp.timeout", "3000");
        if (true) {
            MailSSLSocketFactory sf = null;
            try {
                sf = new MailSSLSocketFactory();
                sf.setTrustAllHosts(true);
                properties.put("mail.smtp.ssl.enable", "true");
                properties.put("mail.smtp.ssl.socketFactory", sf);
            } catch (GeneralSecurityException e) {
//                log.error("init mail Sender error", e);
            }
        }

        javaMailSender.setJavaMailProperties(properties);
        MimeMessage mailMessage = javaMailSender.createMimeMessage();
        MimeMessageHelper messageHelper = new MimeMessageHelper(mailMessage, true);
        messageHelper.setTo("xxx");
        messageHelper.setFrom("xxx");
        messageHelper.setSubject("测试");
        messageHelper.setText("test", true);
        javaMailSender.send(mailMessage);
结果：发送成功

**Comment by looly** [comment]
from是个邮箱地址，是你的发件人邮箱，setUser也要同时配置。
