### ISSUE TITLE
背景色设置没有效果

### ISSUE THREAD

**Issue by hanzhen2017** [looly/hutool#491]
我用write.getOrCreateCellStyle()方法拿到cellStyle，cellStyle设置背景颜色方法cellStyle.setFillBackGroundColor(HssfColor.Red.index)设置，writer.getCell(x,y).setCellStyle(cellStyle);来设置的背景颜色，我是在循环里面操作的，根据属性值不同，设置不同的背景颜色，设置的颜色没有生效

**Comment by looly** [comment]
貌似不能共享样式吧。这个我不知道，请查阅poi相关文档。

**Comment by hanzhen2017** [comment]
不知道什么共享样式，导出的时候要根据属性值来设置这一列在每一行显示不同的颜色，这个不能实现吗

**Comment by moxia** [comment]
我也遇到这个问题 题主解决了没？

**Comment by looly** [comment]
需要设置单独的单元格样式。

**Comment by moxia** [comment]
`
Map<String, Object> row1 = new LinkedHashMap<>();
row1.put("姓名", "张三");
row1.put("年龄", 23);
row1.put("成绩", 88.32);
row1.put("是否合格", true);
row1.put("考试日期", DateUtil.date());

Map<String, Object> row2 = new LinkedHashMap<>();
row2.put("姓名", "李四");
row2.put("年龄", 33);
row2.put("成绩", 59.50);
row2.put("是否合格", false);
row2.put("考试日期", DateUtil.date());

ArrayList<Map<String, Object>> rows = CollUtil.newArrayList(row1, row2);

// 通过工具类创建writer
ExcelWriter writer = ExcelUtil.getWriter("d:/writeMapTest.xlsx");
// 合并单元格后的标题行，使用默认标题样式
System.out.println(rows.size());
writer.merge(4, "一班成绩单");

// 一次性写出内容，使用默认样式，强制输出标题
writer.write(rows, true);

//覆写某个单元格的值和样式
Cell cell = writer.getCell(2, 2);
cell.setCellValue("90.50");
CellStyle cellStyle = writer.createCellStyle();
cellStyle.setFillForegroundColor(IndexedColors.GREEN.getIndex());
cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
cellStyle.setAlignment(HorizontalAlignment.CENTER);
cell.setCellStyle(cellStyle);

// 关闭writer，释放内存
writer.close();
`

哦了

**Comment by moxia** [comment]
```
Map<String, Object> row1 = new LinkedHashMap<>();
row1.put("姓名", "张三");
row1.put("年龄", 23);
row1.put("成绩", 88.32);
row1.put("是否合格", true);
row1.put("考试日期", DateUtil.date());

Map<String, Object> row2 = new LinkedHashMap<>();
row2.put("姓名", "李四");
row2.put("年龄", 33);
row2.put("成绩", 59.50);
row2.put("是否合格", false);
row2.put("考试日期", DateUtil.date());

ArrayList<Map<String, Object>> rows = CollUtil.newArrayList(row1, row2);

// 通过工具类创建writer
ExcelWriter writer = ExcelUtil.getWriter("d:/writeMapTest.xlsx");
// 合并单元格后的标题行，使用默认标题样式
System.out.println(rows.size());
writer.merge(4, "一班成绩单");

// 一次性写出内容，使用默认样式，强制输出标题
writer.write(rows, true);

//覆写某个单元格的值和样式
Cell cell = writer.getCell(2, 2);
cell.setCellValue("90.50");
CellStyle cellStyle = writer.createCellStyle();
cellStyle.setFillForegroundColor(IndexedColors.GREEN.getIndex());
cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
cellStyle.setAlignment(HorizontalAlignment.CENTER);
cell.setCellStyle(cellStyle);

// 关闭writer，释放内存
writer.close();
```
哦了
