### ISSUE TITLE
MetaUtil#getTableMeta 错误

### ISSUE THREAD

**Issue by xlongshu** [looly/hutool#498]
version 4.5.8+
```
java.lang.AbstractMethodError: com.xxx.xxx.jdbc.Connection.getSchema()Ljava/lang/String;

	at com.zaxxer.hikari.pool.HikariProxyConnection.getSchema(HikariProxyConnection.java)
	at cn.hutool.db.meta.MetaUtil.getTableMeta(MetaUtil.java:181)
......
```
JDBC 4.1 的API不一定所有的驱动和连接池都有实现
比如 setSchema 等方法, 建议处理异常

**Comment by looly** [comment]
4.6.2新版本已经修复此问题了。请升级。

**Comment by xlongshu** [comment]
[getSchema](https://github.com/looly/hutool/blob/d1a87a1fc47cbc7ae3fef9545891c553ea880812/hutool-db/src/main/java/cn/hutool/db/meta/MetaUtil.java#L243)  catch (SQLException e) try不住 AbstractMethodError 
`String getSchema() throws SQLException @since 1.7` 是JDBC 4.1的API 不一定都有实现
