### ISSUE TITLE
在使用过程我有一些请求建议/补充,关于DateTime/DesktopUtil/Dict/JschUtil

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#503]
**cn.hutool.core.date.DateTime.of()**
缺少对应的of(long date), 使用一个数字来转化成DateTime
```
public static DateTime of(Date date) {
		if (date instanceof DateTime) {
			return (DateTime) date;
		}
		return new DateTime(date);
	}
```

**cn.hutool.core.swing.DesktopUtil.browse(String)**
这个类里面的一些封装的方法,比如 java.awt.Desktop.browse(URI)本身也有一个传递URI类型的参数,希望能否增加一个URI参数这个也常用一点

**cn.hutool.core.lang.Dict.getObj(String)**
这个方法我觉得是不是设置返回值成强转泛型比较方便 <T> T,  这样调用取一些非基本对象时候就不用特别的去强制转化了,就像cn.hutool.core.lang.Dict.get(String, T)方法一样,只是更简单不用每次都传defaultValue
```
@Override
	public Object getObj(String key) {
		return super.get(key);
	}
```

**cn.hutool.extra.ssh.JschUtil.exec(Session, String, Charset, OutputStream)**
在这个方法中,我发现throw包装的应该是统一的JschRuntimeException
```
		try {
			channel.start();
			in = channel.getInputStream();
			return IoUtil.read(in, CharsetUtil.CHARSET_UTF_8);
		} catch (IOException e) {
			throw new IORuntimeException(e);
		} catch (JSchException e) {
			throw new IORuntimeException(e);
		}
```

thx

**Comment by looly** [comment]
4.6.3修复以上问题，感谢。
