### ISSUE TITLE
JSONUtil.tobean 无法解析七牛云的返回值

### ISSUE THREAD

**Issue by jiangbubai** [looly/hutool#505]
解析代码：
```
Response response = getUploadManager(getConfiguration(os.getZone())).put(inputStream, key, upToken, null, null);
DefaultPutRet putRet = JSONUtil.toBean(response.bodyString(), DefaultPutRet.class);
            
```
七牛文件上传返回值：
`{"hash":"FtsGLhjJPsMsOtu7Cy1qmXYPurOb","key":"19ebfd3e53b84bd598add025e88ec3fe.png"}
`
DefaultPutRet对象定义：

```
package com.qiniu.storage.model;

public final class DefaultPutRet {
    public String hash;
    public String key;
}
```
异常返回：
`cn.hutool.core.convert.ConvertException: No Converter for type [com.qiniu.storage.model.DefaultPutRet]`

**Comment by looly** [comment]
你的`DefaultPutRet ` 没有setXXX方法。

**Comment by jiangbubai** [comment]
DefaultPutRet 是七牛云SDK提供的，同样Gson可以转换成功，不依赖setter。是否可以优化？
