### ISSUE TITLE
FileTypeUtil.getType(Inputstream stream)会改变入参的流对象

### ISSUE THREAD

**Issue by ll789899** [looly/hutool#508]
应该是源码中使用了InputStream.read方法改变了流的位置
我也不知道说的对不对
发现的原因是：我将获得到的Mutipartfile图片文件转成流用FileTypeUtil.getType判断文件类型之后再用Thumbails压缩图片会报流异常

**Comment by looly** [comment]
是的，它读取了前几个字节，你可以调用reset方法复位
