### ISSUE TITLE
DbUtil 对mysql tinyint 类型解析问题

### ISSUE THREAD

**Issue by kecoo1** [looly/hutool#511]
> 查询tt_stay_process时， cos_start_type为tinyint(1)类型。使用DbUtil查出来之后，使用Entity打印时，拿不到准确的数值

> 查询的代码
```java
			List<Entity> entitys = DbUtil.use().query("select cos_start_type from tt_stay_process where cos_start_type = '2' limit 1");
			for(Entity entity : entitys){
				System.out.println("str-" + entity.getStr("cos_start_type"));
				System.out.println("int-" +entity.getInt("cos_start_type"));
			}
```

> 查询结果
str-true
int-1

**Comment by looly** [comment]
这里没有问题，关于字段类型的对应关系见：
https://blog.csdn.net/dujianxiong/article/details/60571395

其中：

>如果tinyInt1isBit =true(默认)，且tinyInt存储长度为1 ，则转为java.lang.Boolean，否则转为java.lang.Integer。

解决办法：

> 1、tinyInt(1) 只用来代表Boolean含义的字段，且0代表False，1代表True。如果要存储多个数值，则定义为tinyInt(N), N>1。例如 tinyInt(2)

> 2、JDBC的URL增加 tinyInt1isBit=false参数，注意参数名区分大小写，否则不生效
jdbc:mysql://${ucmha.proxy1_2.host}/${db.mysql.db}?tinyInt1isBit=false
