### ISSUE TITLE
中文分词组件

### ISSUE THREAD

**Issue by jimichan** [looly/hutool#519]
你好 looly：

注意到在您的项目中有使用到中文分词组件！

Mynlp是我的新推出开源NLP项目[https://github.com/mayabot/mynlp/](https://github.com/mayabot/mynlp/), 虽然开源时间不长，但是已经积累多年，有着良好的设计和高性能。

想邀请您来试用、并欢迎提出各种建议！

**Comment by looly** [comment]
好的，感谢。Hutool的extra模块中TokenizerUtil会加入封装。

4.6.5加入支持。

**Comment by jimichan** [comment]
👍
