### ISSUE TITLE
ExcelRead怎么获取多个sheet进行读取

### ISSUE THREAD

**Issue by xiangshang190823** [looly/hutool#520]
ExcelRead怎么获取多个sheet进行读取

**Comment by looly** [comment]
通过调用setSheet切换sheet即可。

**Comment by xiangshang190823** [comment]
您好，我是想请教下，用excelUtil,怎么去获取这个excel文件的sheet个数，但是考虑到


Workbook workbook = WorkbookUtil.createBook(new File(filePath));
Integer sheetCount = workbook.getNumberOfSheets();
这个方法，可能会内存溢出的问题，所以请教下您，您封装的这个Hutool的工具有啥能解决这个问题的吗




------------------ 原始邮件 ------------------
发件人: "Golden Looly"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午5:04
收件人: "looly/hutool"<hutool@noreply.github.com>;
抄送: "小魔头"<1041975591@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [looly/hutool] ExcelRead怎么获取多个sheet进行读取 (#520)




通过调用setSheet切换sheet即可。

**Comment by Eric30326** [comment]
> 您好，我是想请教下，用excelUtil,怎么去获取这个excel文件的sheet个数，但是考虑到 Workbook workbook = WorkbookUtil.createBook(new File(filePath)); Integer sheetCount = workbook.getNumberOfSheets(); 这个方法，可能会内存溢出的问题，所以请教下您，您封装的这个Hutool的工具有啥能解决这个问题的吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Golden Looly"<notifications@github.com>; 发送时间: 2019年9月3日(星期二) 下午5:04 收件人: "looly/hutool"<hutool@noreply.github.com>; 抄送: "小魔头"<1041975591@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [looly/hutool] ExcelRead怎么获取多个sheet进行读取 (#520) 通过调用setSheet切换sheet即可。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

ExcelReader reader = ExcelUtil.getReader(new File(filePath));
int sheetCount = reader.getSheetCount();
