### ISSUE TITLE
poi设置sheet行高不生效

### ISSUE THREAD

**Issue by jokenchen** [looly/hutool#522]
问题：ExcelWriter.setRowHeight(-1, 20)，设置sheet默认行高不生效（poi本身的问题），希望hutool能兼容下
解决方案：sheet创建row的时候，设置height。（sheet.setDefaultRowHeightInPoints无效）。
代码优化（仅供参考）：
1）完善RowUtil.writeRow，增加方法签名行高rowHeightInPoints。
    public static void writeRow(Row row, Iterable<?> rowData, StyleSet styleSet, boolean isHeader,Float rowHeightInPoints) {
        int i = 0;
        Cell cell;
        for (Object value : rowData) {
            cell = row.createCell(i);
            if (rowHeightInPoints!=null){
                row.setHeightInPoints(rowHeightInPoints);
            }
            CellUtil.setCellValue(cell, value, styleSet, isHeader);
            i++;
        }
    }
2）完善ExcelWriter.writeHeadRow(Iterable<?> rowData)和public ExcelWriter writeRow(Iterable<?> rowData)方法。  RowUtil.writeRow(this.sheet.createRow(this.currentRow.getAndIncrement()), rowData, this.styleSet, false,this.sheet.getDefaultRowHeightInPoints());

**Comment by looly** [comment]
经过测试，这个设置是有效的：

![image](https://user-images.githubusercontent.com/1432613/64537131-d2da2e00-d34c-11e9-885c-797a6756ace2.png)
![image](https://user-images.githubusercontent.com/1432613/64537144-d968a580-d34c-11e9-877c-a63adcc87e0a.png)
