### ISSUE TITLE
JschUtil的createSession方法

### ISSUE THREAD

**Issue by boronga** [looly/hutool#531]

**Comment by boronga** [comment]
![image](https://user-images.githubusercontent.com/44537798/64577091-f71a2700-d3ad-11e9-98b9-d815a1d90329.png)
 建议修改为
![image](https://user-images.githubusercontent.com/44537798/64577048-d05bf080-d3ad-11e9-89ea-11deb9a7fc4a.png)
或者传入Hashtable对象

**Comment by looly** [comment]
原来方法有何不可？报错？

**Comment by boronga** [comment]
对，报错



---原始邮件---
发件人: "Golden Looly"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 上午9:41
收件人: "looly/hutool"<hutool@noreply.github.com&gt;;
抄送: "boronga"<2553235247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [looly/hutool] JschUtil的createSession方法 (#531)



原来方法有何不可？报错？

**Comment by looly** [comment]
操什么错？我看实现方法一样啊。

**Comment by boronga** [comment]
没有这个方法

---原始邮件---
发件人: "Golden Looly"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 中午1:12
收件人: "looly/hutool"<hutool@noreply.github.com&gt;;
抄送: "boronga"<2553235247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [looly/hutool] JschUtil的createSession方法 (#531)



操什么错？我看实现方法一样啊。

**Comment by looly** [comment]
那是你引入jsch版本不对吧，使用最新版本。你用什么版本？

**Comment by boronga** [comment]
有道理，我引入的是你推荐的最低版本



---原始邮件---
发件人: "Golden Looly"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 中午1:18
收件人: "looly/hutool"<hutool@noreply.github.com&gt;;
抄送: "boronga"<2553235247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [looly/hutool] JschUtil的createSession方法 (#531)



那是你引入jsch版本不对吧，使用最新版本。你用什么版本？

**Comment by boronga** [comment]
发现原因了 打扰了 原来还有别版本的包 😂冲突了



---原始邮件---
发件人: "Golden Looly"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 中午1:18
收件人: "looly/hutool"<hutool@noreply.github.com&gt;;
抄送: "boronga"<2553235247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [looly/hutool] JschUtil的createSession方法 (#531)



那是你引入jsch版本不对吧，使用最新版本。你用什么版本？
