### ISSUE TITLE
some coding problems

### ISSUE THREAD

**Issue by xingguang2013** [looly/hutool#546]
1. `cn.hutool.db.ds.GlobalDSFactory` 的 `set` 方法和 `get` 方法的锁不是同一个对象，`set` 是 `GlobalDSFactory` 对象，而 `get` 方法是 `GlobalDSFactory` 对象的 `lock` 成员属性，是否需要修改成一致？
2. 如果一个类只覆盖 `equals` 和 `hashCode` 中的一个，则可能意味着 `equals` 和 `hashCode `不一致
* `cn.hutool.core.builder.HashCodeBuilder`
* `cn.hutool.core.comparator.VersionComparator`
3. `cn.hutool.core.convert.ConverterRegistry` 120行 Double-checked locking 不是线程安全的，建议添加 `volatile` 关键字修饰

**Comment by looly** [comment]
十分感谢，稍后处理

**Comment by looly** [comment]
4.6.7修复此问题，感谢。
