### ISSUE TITLE
CombinationAnnotationElement 源码问题

### ISSUE THREAD

**Issue by Relucent** [looly/hutool#547]
源码: 
类：cn.hutool.core.annotation.CombinationAnnotationElement 
87行：
Annotation[] declaredAnnotations = element.getDeclaredAnnotations();
Annotation[] annotations = element.getAnnotations();
if(declaredAnnotations == annotations) {  //<---※
  //1
}else {
 //2
}

对这个※位置的判断有些疑惑，因为 JDK(1.7/1.8) 中 getAnnotations 的实现方式为：
public Annotation[] getAnnotations() {
      return AnnotationParser.toArray(annotationData().annotations);
}
也就是除非 declaredAnnotations 和 annotations 均为NULL，否则 ※ 位置永远为 flase。

**Comment by looly** [comment]
这里检查注解是否有父类，既是否有继承关系。

getDeclaredAnnotations 获取本类的注解，getAnnotations获取包括父类的注解。

**Comment by Relucent** [comment]
:)  我不是问 declaredAnnotations 和 annotations  的区别

而是根据 JDK 源码的实现方式：
多次调用 element.getAnnotations() 返回的数组并不是同一个数组，使用==判断永远为false

也就是说，除非遇到NULL的情况
否则 declaredAnnotations == annotations 恒等于false

你可以打印一下 element.getAnnotations()  ==  element.getAnnotations()  的结果   (false)

那么这个 IF 判断其实没有意义的

**Comment by looly** [comment]
这个没有细研究过，回头我看下。

**Comment by looly** [comment]
感谢，确认bug，此处不应该用==，改用equals。

**Comment by Relucent** [comment]
JAVA 数组的比较是不能用 equals 的
因为数组的equals等同于 == 
Objects.equals 也不正确，因为Objects.equals的实现就是 a.equals(b)。
☆ 数组的比较的正确写法是，Arrays.equals  举例说明：

String[] a1 = {"A", "B"};
String[] a2 = {"A", "B"};
System.out.println(a1 == a2);    //false
System.out.println(a1.equals(a2));    //false
System.out.println(Objects.equals(a1, a2));    //false
System.out.println(Arrays.equals(a1, a2));    //true

=====
然后看看  cn.hutool.core.util.ObjectUtil.equal 的实现方式 ，我是不是又发现一个BUG  ^_^
