### ISSUE TITLE
not support windows share folder(cn.hutool.core.io.FileUtil)

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#549]
test code:
```
File file = new File("\\\\192.168.1.1\\Share\\");
File file2 = FileUtil.file("\\\\192.168.1.1\\Share\\");
```

output:
```
\\192.168.1.1\Share
\192.168.1.1\Share
```

cn.hutool.core.io.FileUtil.getAbsolutePath(String) / normalize
在这个方法中会简单的把原路径的分隔符进行处理，此时没有handle前缀\\的情况，导致共享文件夹下的路径将不能适用FileUtil.file等方法

**Comment by looly** [comment]
4.6.7修复此问题，转换结果为：`\/192.168.1.1/Share/`

JDK会做自动转换。
