### ISSUE TITLE
有几点工具类代码上疑问

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#550]
cn.hutool.system.SystemUtil.OS_NAME

在SystemUtil里面SystemUtil.USER_NAME /USER_HOME 这些命名很容易产生误解
就连注释写的也是

> 用户的账户名称

我看了下说明文档，用的时候还以为是输出用户名的，哪知道返回了一个user.name

我觉得是不是命名为USER_NAME _KEY之类的名称会更好点，或者补充下注释说明？
![无标题](https://user-images.githubusercontent.com/18179821/65158047-4aead700-da64-11e9-9645-f43f546fd27c.png)

RuntimeException replace  UtilException
简单搜索了一下工具有些地方混用了RuntimeException/UtilException等抛出的异常类型
![www](https://user-images.githubusercontent.com/18179821/65158448-eed48280-da64-11e9-8562-752aa084e0c7.png)
这样catch的时候就不好细分了

**Comment by looly** [comment]
4.6.7增加SystemPropsKeys类，常量key放这里。

名字暂时不能改，影响有点儿大，我加了文档注释。
