### ISSUE TITLE
Padding类模式疑问

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#551]
AES 加密的填充方式，我看在padding.java这个枚举中有罗列，其中的 NoPadding，指的是 zeropadding吗？

**Comment by looly** [comment]
应该是。zeroPadding是js里的概念吧？

**Comment by gpqhl0071** [comment]
不一样，

参考：https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.paddingmode?view=netframework-4.8

这种方式：无论缺多少就补多少个0。

请帮看下如何用hutool 引入这种补0的模式 。

**Comment by looly** [comment]
https://blog.csdn.net/OrangeJack/article/details/82913804

先mark，稍后我看如何解决。

**Comment by looly** [comment]
4.6.7增加对ZeroPadding的支持。感谢。
