### ISSUE TITLE
FileTypeUtil无法准确判断xlsx类型

### ISSUE THREAD

**Issue by BugSupplier** [looly/hutool#552]
FileTypeUtil将我上传的xlsx类型判断为zip类型，看了一下，zip文件的16进制开头为504B030414000000，xlsx为504B030414000600，两个很相似。

源码fileTypeMap.put("504B0304", "zip");

**Comment by looly** [comment]
其实是一样的，你换了xlsx内容这个头又变了。

xlsx本质上还是zip打包几个xml，所以识别出来一样，这个文件没法判断。
