### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by chenmoand** [looly/hutool#555]
### 可能是作者大大写的太赶工了,我这里找了一个错误
https://github.com/looly/hutool/blob/4d133f3d641957e39b6949272c245b59e4eac6e7/hutool-core/src/main/java/cn/hutool/core/util/ArrayUtil.java#L158
建议修改成
```java 
return !isEmpty(array);
```
https://github.com/looly/hutool/blob/4d133f3d641957e39b6949272c245b59e4eac6e7/hutool-core/src/main/java/cn/hutool/core/util/ArrayUtil.java#L168
我觉得底下的都可以改成,减少一下代码量
```java 
return !isEmpty(array);
```
还有我觉得 用 ```Object...```数组不如改成```Object[]```
因为假如我在调用这个方法的时候要吗传入一个数组,不可能还直接```isEmpty(参数1,参数2)```
这样都肉眼可见了,根本不需要比较了

**Comment by looly** [comment]
1、false == isEmpty(array);是故意而为之，更加清晰，感叹号容易看不清。

2、可变长参数已改成数组，此处确实用不到可变长参数。感谢。

4.6.8更新，感谢。
