### ISSUE TITLE
FTPUtil

### ISSUE THREAD

**Issue by catcallxw** [looly/hutool#565]
FTPUtil在不同环境中会出现返回成功，但文件没有上传成功的问题。
测试环境
1、windows
2、postman请求、文件上传成功，也可读取文件
正式环境
1、docker环境运行
2、跨域请求
没有任何异常、返回文件上传成功、FTP服务器没有对应文件

**Comment by looly** [comment]
请确定是否为最新的hutool，之前有未上传的bug。

如果是最新，请尝试commons-net原生上传，hutool基于此库封装。

**Comment by bigbeef** [comment]
ftp.getClient().enterLocalPassiveMode();

**Comment by bigbeef** [comment]
我也遇到问题了，开发环境是windows没有问题，测试环境是linux就上传失败，我是这样解决的：ftp.getClient().enterLocalPassiveMode();
