### ISSUE TITLE
验证码转化成base64返回给前端

### ISSUE THREAD

**Issue by malagebi** [looly/hutool#566]
验证码 转化成base64返回给前端 应该 怎么写代码

**Comment by 1369521908** [comment]
@GetMapping("/qrCode")
    public Object qrCode(String url, HttpServletResponse response) {
        QrConfig config = new QrConfig();
//        response.setContentType("application/octet-stream");
        //  logo
        config.setImg(new File(Constants.LOGO_PATH));
        //  错误级别 /** H = ~30% correction */ 至少30%
        config.setErrorCorrection(ErrorCorrectionLevel.H);
        //  暂时不用写流的方式
//        ServletOutputStream outputStream = response.getOutputStream();
//        QrCodeUtil.generate(url, config, ImgUtil.IMAGE_TYPE_PNG,outputStream);
        //  转base64返回前端,微信小程序最好是png格式
        return ImgUtil.toBase64(QrCodeUtil.generate(url, config), ImgUtil.IMAGE_TYPE_PNG);
    }

**Comment by 1369521908** [comment]
以上仅供参考

**Comment by malagebi** [comment]
老哥，我的意思是CaptchaUtil这个工具类生成的验证码，给前端， 你给的例子是二维码的，

**Comment by 1369521908** [comment]
思路一样的

**Comment by looly** [comment]
```java
LineCaptcha lineCaptcha = CaptchaUtil.createLineCaptcha(200, 100);
response.setContentType("application/octet-stream");
OutputStream out= response.getOutputStream();
lineCaptcha.write(out);
// 自己try
IoUtil.close(out);
```
