### ISSUE TITLE
sm4加密好慢啊

### ISSUE THREAD

**Issue by s1084796293** [looly/hutool#567]

**Comment by s1084796293** [comment]
![image](https://user-images.githubusercontent.com/17758223/65752584-accfce80-e13f-11e9-820b-ebccce9db000.png)

**Comment by looly** [comment]
基于bc库封装，性能没法控制哎。

**Comment by s1084796293** [comment]
我试了一下其他工具类，没有那么慢
![image](https://user-images.githubusercontent.com/17758223/65754316-5a90ac80-e143-11e9-9fda-fbf767cc8347.png)

**Comment by s1084796293** [comment]
https://github.com/ZZMarquis/gmhelper

**Comment by looly** [comment]
好的，稍后我做对比测试

**Comment by looly** [comment]
你的对比计算方式有问题：

```java
SmUtil.sm4();
```

这个方法是会生成随机密钥，这个过程需要足够的种子，所以慢。而你用那个库计算时间没有把生成密钥时间计算在内。

**Comment by chenjy952-droid** [comment]
> ![image](https://user-images.githubusercontent.com/17758223/65752584-accfce80-e13f-11e9-820b-ebccce9db000.png)

第一次加密要先初始化，比较耗时。可以在项目启动时先初始化或者先调用一次方法
