### ISSUE TITLE
希望增加CST时间格式转换

### ISSUE THREAD

**Issue by MakenChan** [looly/hutool#570]
springboot项目配置了StringToDateConverter如下的形式，希望在DateUtil.parse(dateString);方法中添加CST时间格式转换

    public class StringToDateConverter implements Converter<String, Date> {
        @Override
        public Date convert(String dateString) {
//因为工具没提供这种解析，所以单独判断了并重写了方法
            if (dateString.contains("CST")){
                Date time =new Date(dateString);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String timeFormat = sdf.format(time);
                return new DateTime(timeFormat, DatePattern.NORM_DATETIME_FORMAT);
            }
//hutools工具提供的方法
            return DateUtil.parse(dateString);
        }
    }

**Comment by looly** [comment]
最新版(4.6.8)已经可以解析了：

```java
String dateStr = "Wed Sep 16 11:26:23 CST 2009";
DateTime dateTime = DateUtil.parse(dateStr);
```
