### ISSUE TITLE
设置了禁用默认cookie，但是请求抓包还是会自动携带

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#572]
![Snipaste_2019-10-05_17-10-08](https://user-images.githubusercontent.com/41384519/66252894-5e4faf00-e793-11e9-9dfc-22ecbb5c033a.png)

**Comment by looly** [comment]
首先确认下是否为最新版本的Hutool，4.6.8。

**Comment by Andy095** [comment]
已经更新到最新的，问题依旧

**Comment by looly** [comment]
尝试使用closeCookie

**Comment by looly** [comment]
disableCookie确实存在问题，请使用closeCookie关闭Cookie管理器。

4.6.9修复此问题。

**Comment by Andy095** [comment]
![Snipaste_2019-10-05_17-10-08](https://user-images.githubusercontent.com/41384519/66252992-acb17d80-e794-11e9-8411-d39db363a49d.png)
还有Cookie键同名的不同网站之间取Cookie也有问题

**Comment by Andy095** [comment]
![Snipaste_2019-10-05_17-21-29](https://user-images.githubusercontent.com/41384519/66253010-d8346800-e794-11e9-8340-5f95672cea8c.png)

**Comment by Andy095** [comment]
还有Cookie键同名的不同网站之间取Cookie也有问题

**Comment by looly** [comment]
不同网站指域名不同么？全局管理的Cookie是按照url来区分的，不相同获取的Cookie也不同。

**Comment by Andy095** [comment]
你看我发的截图通过response取回的Cookie与抓包的不同。response取到的是别的域名的，我查看了内部方法的代码，并没有判断域名，而是解决用for遍历list数组，找到第一个就直接返回了。正确的cookie在更后面，还没有遍历到

**Comment by Andy095** [comment]
![Snipaste_2019-10-05_17-39-13](https://user-images.githubusercontent.com/41384519/66253201-15015e80-e797-11e9-9101-14ea2b3ace9d.png)

**Comment by looly** [comment]
这个问题也确实存在，4.6.9统一修复，十分感谢。
