### ISSUE TITLE
httpCookie

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#583]
新版本 默认Cookie行为失效。
所有的请求都不会带上服务器返回的Cookie怎么设置都无效	

/**
	 * 打开默认的Cookie行为（自动回填服务器传回的Cookie）
	 *
	 * @return this
	 */
	public HttpRequest enableDefaultCookie() {
		return cookie((String) null);
	}

**Comment by looly** [comment]
你的新版本指哪个版本？你自己不要设置cookie头即可，设置了自动cookie自动失效。

**Comment by Andy095** [comment]
hutool版本是4.6.9   
     HttpRequest httpRequest = HttpRequest.get("https://www.baidu.com").setProxy(proxy1).enableDefaultCookie();
        HttpResponse response1 = httpRequest.execute();
        System.out.println(response1.getCookies());
        System.out.println(response1.getCookie("route1plat"));
        HttpResponse response2 = httpRequest.execute();
        System.out.println(response1.getCookies());
        System.out.println(response2.getCookie("route1plat"));

这是我的代码，访问了两个百度的网站，但是第二次访问并没有携带第一次访问返回的Cookie，4.6.8是会携带的

**Comment by looly** [comment]
确实有这个问题。

**Comment by looly** [comment]
4.6.10修复此问题，感谢。

问题出在存储Cookie时host不匹配导致的问题，请于明天升级，下午我提交新版本。
