### ISSUE TITLE
反序列化问题

### ISSUE THREAD

**Issue by objectboy2016** [looly/hutool#60]
json数据如下:
{
    "statusCode": 200,
    "message": "OK",
    "skip": 0,
    "limit": 20,
    "total": 30,
    "data": [
        {
            "Price": {
                "ADT": [
                    [
                        {
                            "BookingCode": [
                                "N",
                                "N"
                            ]
                        }
                    ]
                ]
            }
        }
    ]
}

建立相应的bean
  
public class ADT {

    private List<String> BookingCode;
    public void setBookingCode(List<String> BookingCode) {
         this.BookingCode = BookingCode;
     }
     public List<String> getBookingCode() {
         return BookingCode;
     }

}

public class Data {

    private Price Price;
    public void setPrice(Price Price) {
         this.Price = Price;
     }
     public Price getPrice() {
         return Price;
     }

}

 
public class JsonRootBean {

	private int statusCode;
	private String message;
	private int skip;
	private int limit;
	private int total;
	private List<Data> data;

	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}

	public int getStatusCode() {
		return statusCode;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public void setSkip(int skip) {
		this.skip = skip;
	}

	public int getSkip() {
		return skip;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getLimit() {
		return limit;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public int getTotal() {
		return total;
	}

	public void setData(List<Data> data) {
		this.data = data;
	}

	public List<Data> getData() {
		return data;
	}

}

public class Price {

    private List<List<ADT>> ADT;
    public void setADT(List<List<ADT>> ADT) {
         this.ADT = ADT;
     }
     public List<List<ADT>> getADT() {
         return ADT;
     }

}

test:

public static void main(String[] args) {
		String json = "{\"statusCode\":200,\"message\":\"OK\",\"skip\":0,\"limit\":20,\"total\":30,\"data\":[{\"Price\":{\"ADT\":[[{\"BookingCode\":[\"N\",\"N\"]}]]}}]}";
		JsonRootBean objJsonRootBean = JSONUtil.toBean(json, JsonRootBean.class);
		ADT sObject = objJsonRootBean.getData().get(0).getPrice().getADT().get(0).get(0);
		System.out.println(sObject.getBookingCode());
	} 

error:

Exception in thread "main" java.lang.ClassCastException: com.xiaoleilu.hutool.json.JSONObject cannot be cast to sss.ADT
	at sss.test.main(test.java:12)

**Comment by looly** [comment]
我本地测试后回复，感谢issue

**Comment by looly** [comment]
确认bug，3.2.2修复此问题。

**Comment by objectboy2016** [comment]
CollectionUtil  是否可以增加分组(分组后每个组以列表形式返回),  交集,并集等公用方法

**Comment by looly** [comment]
我解释下此Bug：此Bug问题来源于获取集合元素类型失败导致的问题。Hutool原先设计是使用Class做为类型转换参数的目标类型标识，但是Class一旦是集合类型，会导致获取其元素类型为null，最终导致元素类型无法被转换。Hutool3.2.2中将Type做为类型转换的基础，Type会保留集合中元素泛型类型。至此问题解决。十分感谢提出这个bug~~
