### ISSUE TITLE
ExcelWriter生成文件出现历史数据的问题

### ISSUE THREAD

**Issue by littlewalnut2024** [looly/hutool#603]
运行第二次生成的文件会有第一次运行时的历史数据。版本为5.0.3
![1](https://user-images.githubusercontent.com/48768539/67619224-7616d200-f82b-11e9-8408-083ed75cee1e.jpg)
![2](https://user-images.githubusercontent.com/48768539/67619229-7c0cb300-f82b-11e9-9d23-819e7dcb1ab0.jpg)

```
public static void main(String[] args) {
        String filePath="D://test//test.xls";
        ExcelWriter writer= ExcelUtil.getWriter(filePath);
        if(FileUtil.exist(filePath)){
            if(FileUtil.del(filePath)){
                System.out.println("删除旧的test.xls成功");
            }else{
                System.out.println("删除旧的test.xls失败");
                return;
            }
        }
        List<String> list=new ArrayList<>();
        //第一次运行的代码  第二次运行请注释
        list.add("1111");
        list.add("1111");
        list.add("1111");
        list.add("1111");
        list.add("1111");
        list.add("1111");

        //第二次运行的代码
        //list.add("222");


        writer.write(list);
        writer.close();
    }
```

**Comment by looly** [comment]
`ExcelUtil.getWriter`的时候会读取已存在的文件，所以创建时请调用`FileUtil.del`先删掉这个已存在文件即可。

这样做的原因是：为了防止用户手误传入已存在的文件路径导致误删除。

**Comment by littlewalnut2024** [comment]
> `ExcelUtil.getWriter`的时候会读取已存在的文件，所以创建时请调用`FileUtil.del`先删掉这个已存在文件即可。
> 
> 这样做的原因是：为了防止用户手误传入已存在的文件路径导致误删除。

可是请您看下代码，我已经在方法开始时调用了`FileUtil.del`删除存在的文件了，可以依然有这个问题，要不请您运行下试试看？

**Comment by looly** [comment]
可能是没删除成功吧。
