### ISSUE TITLE
ZipUtil工具类 zip(File zipFile, String[] paths, InputStream[] ins, Charset charset) 这个方法ins没有关闭，需要在外面手动去关闭

### ISSUE THREAD

**Issue by xiaofuliang** [looly/hutool#604]
ZipUtil工具类 zip(File zipFile, String[] paths, InputStream[] ins, Charset charset) 这个方法ins没有关闭，需要在外面手动去关闭，能否改成在工具里面关闭

**Comment by looly** [comment]
5.0.4改进默认关闭流，感谢意见。
