### ISSUE TITLE
HikariPool problem

### ISSUE THREAD

**Issue by katty0924** [looly/hutool#613]
When I use HikariPool  to connect oralce, nomally, the first time to connect is very slow, and sometimes it will say "﻿﻿﻿﻿﻿﻿Io 异常: The Network Adapter could not establish the connection, and connect timeout", but when I tried to connect oralce again, it can be successful, so the database pool is not quit stable with oracle? or I ignored some configuration?

**Comment by looly** [comment]
try Driud？

Please see https://www.hutool.cn/docs/#/db/%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AEdb.setting%E6%A0%B7%E4%BE%8B
