### ISSUE TITLE
ProxyUtil工具问题

### ISSUE THREAD

**Issue by w5185552** [looly/hutool#615]
5.0.3 执行官网的列子发现TimeIntervalAspect.after方法不执行
4.5.12 可以正常执行TimeIntervalAspect.after方法

测试发现4.6.8之后包括4.6.8 都不行

**Comment by looly** [comment]
```java
Animal cat = ProxyUtil.proxy(new Cat(), TimeIntervalAspect.class);
String result = cat.eat();
Assert.assertEquals("猫吃鱼", result);
cat.seize();
```

这样可以么？

**Comment by looly** [comment]
我这边测试没问题。

**Comment by w5185552** [comment]
![图片](https://user-images.githubusercontent.com/24616689/68002639-bd2a1a80-fca4-11e9-9c9e-80fda5caeaba.png)
实现这个方法就正常了after(Object target, Method method, Object[] args, Object returnVal)
