### ISSUE TITLE
ExcelUtil 问题反馈

### ISSUE THREAD

**Issue by wuai1024** [looly/hutool#616]
目前项目中Excel操作都已改造为使用hutool 的 ExcelUtil

在使用过程中遇到一个很神奇的问题

1、ExcelUtil.readBySax(path, 0, new RowHandler() {} 
      优势：使用这个操作速度快，占用内存小
      缺点：网络上的excel（比如说使用unzip解压zip文件后，文件夹里面的excel），读取不了，需要先在本地打开保存一下，然后才可以顺利读取。

2、ExcelReader reader = ExcelUtil.getReader(path);
      List<List<Object>> list = reader.read();
      
      我后来改成用这个方法，就可以顺利读取了，但是这个是直接把读取到的所有数据一次性封装到list。 我们excel数据比较大，内存占用比较高。

希望ExcelUtil.readBySax 这个方法也可以直接打开

**Comment by qing0504** [comment]
你说的应该是07版本的excel，我也遇到了类似的现象，我遇到的问题是导出的文件，使用ExcelUtil.readBySax(path, 0, new RowHandler() {} 解析不了。原因我找到了，与你分享下：

可以先看下这篇文章：https://www.cnblogs.com/wangmingshun/p/6654143.html

Excel07SaxReader类中方法
`public Excel07SaxReader read(OPCPackage opcPackage, int sheetIndex) throws POIException` ，其中的一行代码
`sheetInputStream = xssfReader.getSheet(RID_PREFIX + (sheetIndex + 1));`，
sheet是根据rId读取的，如果是0，则rId是rId1，看下excel的xml源文件（ _rels/workbook.xml.rels）看看rId1对应的是哪个sheet就一目了然了。

**Comment by wuai1024** [comment]
这样的话，每个文件去改有点得不偿失啊。 都是平台上直接导出的文件，然后直接读取的。
你看我发的还一个方法，使用ExcelReader的就能正常读取




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qing0504"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 晚上6:17
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"杨康"<851161583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] ExcelUtil 问题反馈 (#616)




你说的应该是07版本的excel，我也遇到了类似的现象，我遇到的问题是导出的文件，使用ExcelUtil.readBySax(path, 0, new RowHandler() {} 解析不了。原因我找到了，与你分享下：
 
可以先看下这篇文章：https://www.cnblogs.com/wangmingshun/p/6654143.html
 
Excel07SaxReader类中方法
 public Excel07SaxReader read(OPCPackage opcPackage, int sheetIndex) throws POIException ，其中的一行代码
 sheetInputStream = xssfReader.getSheet(RID_PREFIX + (sheetIndex + 1));，
 sheet是根据rId读取的，如果是0，则rId是rId1，看下excel的xml源文件（ _rels/workbook.xml.rels）看看rId1对应的是哪个sheet就一目了然了。

**Comment by looly** [comment]
readBySax默认传入的是rid，而非index，一般工具导出的excel这个rid是2或者3，你可以修改这个值达到读取目的，或者使用-1读取所有sheet。
