### ISSUE TITLE
获取文件类型错误

### ISSUE THREAD

**Issue by aoyouxingkong** [looly/hutool#619]
JDK 1.8和 hutool-all 版本号是4.6.10
cn.hutool.core.io.FileTypeUtil#getType(java.io.File)，输入参数是F:\test.doc，返回值是xls
获取文件类型，返回不对

**Comment by looly** [comment]
此问题与https://gitee.com/loolly/hutool/issues/I14JBH?from=project-issue重复，先关闭。
