### ISSUE TITLE
hutool-core BeanUtil.isEmpty() 跟 hasNullField()考虑补充忽略检测字段的参数吗?

### ISSUE THREAD

**Issue by aStudyMachine** [looly/hutool#629]
版本 5.0.5 

如题 , 可以考虑补充一个重载方法 , 加入不纳入的检测的字段名字符串参数 . 
`public static boolean isEmpty(Object bean , String... ignoreFiledNames)`

同时可以考虑对 字段进行 notNull , notBlank , notEmpty 的判断 .

**Comment by looly** [comment]
感谢。5.0.7加入ignoreFiledNames参数和isNotEmpty。

notNull可以用`ObjectUtil.isNotNull`

notBlank对bean对象没意义

**Comment by aStudyMachine** [comment]
作者你理解错我第二部分的意思啦 , 我说的是对**bean内部的字段**的非空校验改为notNull , notBlank , notEmpty  , 例如你在`cn.hutool.core.util.ObjectUtil#isEmpty()`的判断方式 . 

`cn.hutool.core.bean.BeanUtil#isEmpty()` 目前的对空值的判断是 : 
```
if (null != ReflectUtil.getFieldValue(bean, field)) {
	return false;
}
```
可以改为直接用`cn.hutool.core.util.ObjectUtil#isEmpty()` 去做判断
