### ISSUE TITLE
NumberUtil下的max和min会出现ambiguous问题

### ISSUE THREAD

**Issue by w2c17lin** [looly/hutool#630]
![1](https://user-images.githubusercontent.com/29086596/69129369-2903e400-0ae9-11ea-8f08-1c9160978389.png)
是不是可以和ArrayUtil下的max和min一样定义，对泛型的方法使用数组做入参
![2](https://user-images.githubusercontent.com/29086596/69129378-2c976b00-0ae9-11ea-8901-dd03767e19df.png)
![3](https://user-images.githubusercontent.com/29086596/69129380-2ef9c500-0ae9-11ea-900d-7beccaeef8c8.png)

**Comment by looly** [comment]
感谢意见，5.0.7修改此处。
