### ISSUE TITLE
poi在服务端为linux，导出的excel文件会出现文件损坏问题

### ISSUE THREAD

**Issue by Chanshusband** [looly/hutool#631]
![image](https://user-images.githubusercontent.com/16173368/69201269-adea0e80-0b78-11ea-9317-5c38f9d73d09.png)
![image](https://user-images.githubusercontent.com/16173368/69201275-b5a9b300-0b78-11ea-903b-86364e0a9c5d.png)

**Comment by Chanshusband** [comment]
在windows下可以导出后可以正常打开

**Comment by looly** [comment]
尝试：
1、写出到文件看是否能打开
2、扩展名改为xlsx试下。
