### ISSUE TITLE
在参考文档里面点击API文档跳转 nginx报错 

### ISSUE THREAD

**Issue by yuanyonglin** [looly/hutool#633]
![image](https://user-images.githubusercontent.com/40201226/69322604-27205900-0c80-11ea-8eb0-984f0015d2fe.png)
![image](https://user-images.githubusercontent.com/40201226/69322640-356e7500-0c80-11ea-9c2b-eefbb6b41e2e.png)

**Comment by looly** [comment]
已修复，感谢。
