### ISSUE TITLE
关于CellUtil的扩展建议

### ISSUE THREAD

**Issue by xiongmingwu** [looly/hutool#637]
非常感谢作者提供如此精简的工具包，但在实际使用ExcelWriter过程中发现若同一个sheet中存在金额，又存在百分比的场景中无法个性化设置不同的CellStyle和Format，经查阅源码建议建议拓展CellUtil.setCellValue的方法，并在 cn.hu tool.poi.excel.cell.CellValue 中添加getFormat或者getCellStyle的方法，并在CellUtil.setCellValue中提供相关支持(类似FormulaCellValue的处理)，方便在不用的业务场景下支持自定义拓展，谢谢！期待您的答复。

**Comment by xiongmingwu** [comment]
CellUtil.setCellValue中的styleSet参数为null 则存在NPE的问题。

**Comment by xiongmingwu** [comment]
建议将ExcelWriter中部分private修饰的field修改成protected 或提供 protected 的方法进行获取，如：currentRow，这样可以方便继承ExcelWriter 重写部分方法已满足个性化需求。

**Comment by looly** [comment]
hutool-poi的本意时数据处理，对样式支持不好。这块没有想到好的处理方法，暂时不做变更。感谢意见。

**Comment by xiongmingwu** [comment]
若不介意，我可以近期提供相关PR。
