### ISSUE TITLE
hutool已弃用的PinyinUtil工具类，发现汉字转拼音的bug

### ISSUE THREAD

**Issue by evasnowind** [looly/hutool#640]
版本：hutool-all 4.6.2
![image](https://user-images.githubusercontent.com/2696709/69541563-64f4e880-0fc4-11ea-9672-dcf951e78a3f.png)

例如：中文汉字“馨”会被转成“zuo”
![image](https://user-images.githubusercontent.com/2696709/69541587-73db9b00-0fc4-11ea-9cde-7ff18f4f280a.png)

**Comment by looly** [comment]
被弃用也是这个原因。推荐pinyin4j。
