### ISSUE TITLE
建议加入经纬度转换工具类

### ISSUE THREAD

**Issue by GreatGarlic** [looly/hutool#643]

**Comment by looly** [comment]
之前有geoHash，后来去掉了。此处考虑专门的库。

**Comment by GreatGarlic** [comment]
@looly 想问下这个geoHash是转换WGS-84、GCJ-02、BD-09这种坐标系的吗？

**Comment by GreatGarlic** [comment]
@looly 就是这三种坐标系互相转换

**Comment by looly** [comment]
百度到的：https://www.cnblogs.com/helios-fz/p/11177080.html

留个flag，看看是否加入hutool中。

**Comment by looly** [comment]
考虑再三，这个工具类不考虑加入了，你可以使用我发的这个博客自行封装。原因如下：

1、坐标转换不熟悉，没法确定准确性
2、博客中的坐标涉及国家边界线，无法验证，有很大的风险

**Comment by GreatGarlic** [comment]
@looly 好的，感谢
