### ISSUE TITLE
CronUtil的setting中指定的定时方法,如果是带参方法,该如何调用呢?

### ISSUE THREAD

**Issue by jiayaoO3O** [looly/hutool#653]
例如我的setting配置文件里面有如下配置:

> [org.watch.dog.watcher]
FrpWatcher.watch = */3 * * * *

说明我想要定时调用这个watch()方法,但是如果这个watch()方法需要传一个参数,例如watch(string str),那么配置文件该如何填写?

**Comment by looly** [comment]
不行，这个参数没法传，你直接代码里调用CronUtil.schedule方法动态加入定时任务即可。
