### ISSUE TITLE
JschUtil.exec方法无法远程执行命令问题

### ISSUE THREAD

**Issue by yuzixuan0722** [looly/hutool#658]
JschUtil中exec(Session session, String cmd, Charset charset, OutputStream errStream)方法中第362行调用内部方法openChannel(session, ChannelType.EXEC);建立通道，由于openChannel方法中已经有了channel.connect()，导致exec方法后续的setCommand是不生效的。
![image](https://user-images.githubusercontent.com/39270971/70289406-9dd85d00-180f-11ea-89f6-4646f110a5ac.png)
![image](https://user-images.githubusercontent.com/39270971/70289418-acbf0f80-180f-11ea-9b4d-a40cd959849e.png)

**Comment by looly** [comment]
此问题已修复，请升级到5.0.7后测试。
