### ISSUE TITLE
enhance of cn.hutool.core.util.ReflectUtil.getFieldValue(Object, Field)

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#662]
public static Object getFieldValue(Object obj, Field field) {
Object result;
if (null == obj || null == field) {
return null;
}
ReflectUtil.setAccessible(field);
try {
result = field.get(obj);
}
catch (IllegalAccessException e) {
}
return result;
}

在这里null == obj我觉得可以不用加上obj为空判断,因为field.get(null)同样可以使用,可以通过反射取到静态变量的值,不需要有实例化的对象

使用的测试代码
Field field = ReflectUtil.getField(sun.misc.Unsafe.class, "theUnsafe");
ReflectUtil.setAccessible(field);
sun.misc.Unsafe unsafe = (Unsafe) field.get(null);

**Comment by looly** [comment]
感谢，5.1.0修改此部分。
