### ISSUE TITLE
在安装了VMware的电脑上不能正确获取Ip

### ISSUE THREAD

**Issue by AIex-Mercer** [looly/hutool#663]
NetUtil.localIpv4s() 获取的列表：
127.0.0.1
192.168.100.1
192.168.200.1
192.168.101.45
NetUtil.getLocalhostStr()获取的值：
192.168.100.1

cmd：ipconfig

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::bc80:25af:4552:65b%11
   IPv4 地址 . . . . . . . . . . . . : 192.168.200.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::4c0d:5aa1:858b:64ef%5
   IPv4 地址 . . . . . . . . . . . . : 192.168.100.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::74eb:f2e2:f30b:fd14%19
   IPv4 地址 . . . . . . . . . . . . : 192.168.101.45
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : fe80::8a11:96ff:fe1c:6861%19
                                       192.168.101.1

**Comment by looly** [comment]
getLocalhostStr职能获取到符合条件的第一个地址，无法区分vmware。请调用localIpv4s后自行区分。
