### ISSUE TITLE
参考文档中的网络工具-NetUtil页 404

### ISSUE THREAD

**Issue by DaiYuanchuan** [looly/hutool#664]
参考文档中的网络工具-NetUtil页 报错 404 - Not found
![image](https://user-images.githubusercontent.com/38415417/70369237-fcc1d300-18f0-11ea-964e-2fc0138c6671.png)

**Comment by looly** [comment]
地址可访问，不知道你指的哪个页面的链接？

https://www.hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E7%BD%91%E7%BB%9C%E5%B7%A5%E5%85%B7-NetUtil
