### ISSUE TITLE
JschUtil . IO阻塞

### ISSUE THREAD

**Issue by is-xianglei** [looly/hutool#665]
![image](https://user-images.githubusercontent.com/33053444/70491990-e2c90000-1b3d-11ea-9eef-f6f922f9d37f.png)
![image](https://user-images.githubusercontent.com/33053444/70492015-f5433980-1b3d-11ea-988a-1973f278211f.png)

他会一直阻塞在IOUtil这里...没有任何响应,程序也没有停止..

**Comment by looly** [comment]
gitee已回答。
