### ISSUE TITLE
HttpRequest 的 patch 方法疑问

### ISSUE THREAD

**Issue by ZhouQQQ** [looly/hutool#666]
看了源码 好像并不是真正的`patch` 方法 而是加入特定的请求头
```java
public HttpRequest method(Method method) {
		if (Method.PATCH == method) {
			this.method = Method.POST;
			this.header("X-HTTP-Method-Override", "PATCH");
		} else {
			this.method = method;
		}
		
		return this;
	}
```
但是 我要请求的URL就不认这种请求 报`405 method not allow`

有没有直接就是`patch`的方法 请问

**Comment by looly** [comment]
HttpUrlConnection 不支持patch方法，所以在这里折中。

**Comment by ViCrack** [comment]
真想加也是可以的，能用反射来改…

**Comment by looly** [comment]
确实……回头研究把。

**Comment by qq295190549** [comment]
现在 patch 请求如何解决？

**Comment by looly** [comment]
暂时没有解决。考虑HttpClient库吧。

**Comment by ViCrack** [comment]
> 
> 
> 现在 patch 请求如何解决？


> https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch

真要加就自己改改这个静态域变量吧, 可能改了会有些兼容问题也说不定
java.net.HttpURLConnection.methods

**Comment by looly** [comment]
太棒了，5.1.6增加支持！
