### ISSUE TITLE
关于ImgUtil缩放图片功能

### ISSUE THREAD

**Issue by yimi88** [looly/hutool#668]
使用ImgUtil进行图片缩放处理，缩放后图片出现了逆时针90度的反转。尝试了几张图，只有一张有上述问题，测试代码如下图，压缩文件里面有2张图片，（原图和处理后的图片），此问题比较特殊，望测试后予以解答。
[pic20191213.zip](https://github.com/looly/hutool/files/3959753/pic20191213.zip)

版本hutool-core5.0.7
`import java.io.File;

import cn.hutool.core.img.ImgUtil;

public class TestHutoo {
	
	public static void main(String[] args) {
		float scale = 0.5F;
		File srcImageFile = new File("G:\\data\\PICT_20191128_153020.jpg");
		File destImageFile = new File("G:\\data\\PICT_20191128_153020_dest.jpg");
		ImgUtil.scale(srcImageFile, destImageFile, scale);
	}
}
`

**Comment by looly** [comment]
终于找到原因了：

使用特殊设备（比如相机、ipad等）拍摄的照片，有EXIF方向信息，但是JDK中ImageIO无法读取这个信息，导致读取的照片长宽被互换了。暂时不借助第三方库无法搞定这个东西。

具体见：https://stackoverflow.com/questions/11310162/imageio-get-image-type-and-exif-data
