### ISSUE TITLE
关于使用RSA加密解密

### ISSUE THREAD

**Issue by WillVend** [looly/hutool#669]
使用糊涂版本：hutool-all-4.1.19

问题描述：数据在Server上使用Hutool RSA加密后通过Socket传输到Android Client上解密后，解密后数据有奇怪符号添加，不知如何去除多余的字符？

服务器打印：
{"data":{"publickey":"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCNS6V7gLhpYqsJYK3ksDpBqNelvtm4jCXvtBcfido25Gv4qnMEZKQBg6WtbnarG2E0JuuzTwhSx33u7rXNrQnI/83dnUy1CTgiYHphuCkjGzQYUbMwEZepEeLIYhFadELxUzM+IZuoYvs8gB11tz8BI88Yzcy9irHTYQXqyHecIwIDAQAB"},"status":"success"}

Android上解密后打印：
�gV�8���{"data":{"publickey":"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCNS6V7gLhpYqsJYK3ksDpBqNelvtm4jCXvtBcfido25Gv4qnMEZKQBg6W&1AxW$=��tbnarG2E0JuuzTwhSx33u7rXNrQnI/83dnUy1CTgiYHphuCkjGzQYUbMwEZepEeLIYhFadELxUzM+IZuoYvs8gB11tz8BI88Yzcy9irHTYQXqyHecIwID��Q����p�9����ua;\y��w��8	/Z"�3b[S26?.J�G�XZ���).K����z��3Ǳ}��e�ig4�%�|�"��XY<�vF��������AQAB"},"status":"success"}

服务器上使用的加密方法：
![image](https://user-images.githubusercontent.com/41274541/70787449-a1e51b80-1dc9-11ea-88fe-5009772f0991.png)

Android上解密方法：
![image](https://user-images.githubusercontent.com/41274541/70787197-284d2d80-1dc9-11ea-815c-530e46aa159d.png)

请大佬指教一二！！！

**Comment by pdxgg** [comment]
出现了同款问题，本地main 方法debug调用是没有问题的，API调用就出现了解密结果中带有乱码问题 hutool.version 5.3.8

**Comment by looly** [comment]
@pdxgg 忙猜是因为padding问题。不同的平台对RSA的默认实现不同，而且BC库和JCE的默认实现也不同。

你可以指定padding和mode，这样可以保持一致。
