### ISSUE TITLE
不知道能否加入银行卡校验工具类

### ISSUE THREAD

**Issue by youaodu** [looly/hutool#670]
不知道能否加入银行卡校验工具类

**Comment by looly** [comment]
银行卡规则太多了，还得维护，不考虑。

**Comment by ljynfo** [comment]
请求加入银行卡相关工具类
@looly

**Comment by looly** [comment]
@ljynfo 欢迎提供思路。这个不好加啊。你可以试试这个：https://github.com/nanchen2251/BankCardUtils

**Comment by ljynfo** [comment]
@looly 

我的思路就是：银行卡工具类不用支持所有的银行，银联类卡、大银行的卡规则都是遵循规范的，这类卡的数量几乎已经占了95%以上、其余小类型卡占量不足5%；工具类支持的场景达到95%已经完全足够了，不支持的只用在文档注释着重标明即可

**Comment by looly** [comment]
@ljynfo 银行的规则是不断变化的，这个还是不加了。而且没有一个规范来定义这个东西。
