### ISSUE TITLE
httprequest能配置HttpsURLConnection的doOutput吗

### ISSUE THREAD

**Issue by ChengangFeng** [looly/hutool#671]
httprequest的get方法不支持body里面传参，会报以下错误
```
cannot write to a URLConnection if doOutput=false - call setDoOutput(true)

```
暴露HttpsURLConnection的setDoOutput方法吗？

**Comment by looly** [comment]
其实暴露也没有意义的：

你可以看下`sun.net.www.protocol.http.HttpURLConnection`源码的getOutputStream0方法：

![image](https://user-images.githubusercontent.com/1432613/70956462-00064d00-20af-11ea-98d1-8b8e31d016d5.png)


JDK会自动将你的GET方法转换为POST方法。

所以这类请求考虑使用第三发库把，比如okhttp。

5.1.0会做一些修改，把这个设置打开。如果测试可用也可以用。
