### ISSUE TITLE
About log printing

### ISSUE THREAD

**Issue by zskHub** [looly/hutool#674]
Question: so far I've introduced it in maven style, 
HttpRequest.get (url).form(paramMap).execute().body();
The console does not see any log information.
Desired outcome: I want a log management method that can control log printing.For example, if I use the httpUtils module, do I see the url I actually sent when I sent the request?

**Comment by looly** [comment]
Hutool基于`HttpUrlConnection`封装，根据用户传入信息构建的Http请求，最后都在HttpUrlConnection中，不能打印完整的请求。
