### ISSUE TITLE
about  create temp file

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#676]
cn.hutool.core.io.FileUtil.createTempFile(File)

创建temp文件的时候内置的"hutool"字符串能否抽取出来定义成public static XXXX,方便全局修改

还有发现
cn.hutool.setting.Setting.autoLoad(boolean)
cn.hutool.setting.SettingLoader.load(UrlResource)
默认总会有一些多余的log.debug,StaticLog.debug方法在打log...这能不能去掉或者在setting类中动态设置下

**Comment by looly** [comment]
1、你可以调用：
```java
createTempFile(String prefix, String suffix, File dir, boolean isReCreat)
```

2、多余日志都是debug日志，你可以在日志框架中把hutoo的日志屏蔽。
