### ISSUE TITLE
StrUtil concat求新增 插入数组中间值 工具太好用不想自己再实现

### ISSUE THREAD

**Issue by wflyLeo** [looly/hutool#678]
不知道哪里留言 哈哈
```py
arr={'aa','bb'}
isNullToEmpty = true
joinStr = '&'
print(StrUtil.concatWithJoin(isNullToEmpty ,joinStr,arr))
# aa&bb

```

**Comment by wflyLeo** [comment]
ArrayUtil 的join方法 求新增isNullToEmpty

**Comment by looly** [comment]
默认就是nullToEmpty的啊
![image](https://user-images.githubusercontent.com/1432613/71238590-74571f80-233f-11ea-9fb8-b9c47e63fdef.png)

![Uploading image.png…]()
