### ISSUE TITLE
关于ImgUtil偏移量的原点设置

### ISSUE THREAD

**Issue by BreezeCool** [looly/hutool#680]
在使用ImgUtil工具类的添加水印方法，发现其偏移量的原点是以图片正中心为原点，期望新增个设置原点位置(左上,左下,右上,右下,正中央)的功能

再次感谢作者回复。

**Comment by looly** [comment]
可以使用`Img.from(srcImage).setPositionBaseCentre(false).pressImage(pressImg, x, y, alpha).getImg();`
