### ISSUE TITLE
ZipUtil 解压压缩包，在mac电脑上 提示File path is blank!

### ISSUE THREAD

**Issue by linc007** [looly/hutool#685]
问题我大概看了一下，是由于方法buildFile 在使用/拆分路径时，mac电脑的压缩包中有_MACOSX这个文件夹，
final String[] pathParts = StrUtil.splitToArray(fileName, CharUtil.SLASH);
			for (int i = 0; i < pathParts.length - 1; i++) {
				//由于路径拆分，slip不检查，在最后一步检查
				outFile = new File(outFile, pathParts[i]);
			}
			//noinspection ResultOfMethodCallIgnored
			outFile.mkdirs();
			// 最后一个部分作为文件名
			fileName = pathParts[pathParts.length -1];
这段代码去split这个文件夹后有数组有两个值，第二个值为空字符串，fileName = pathParts[pathParts.length -1];这个代码刚好就取了空值，导致报错，麻烦看到后核实一下， 使用版本 5.0.7--jdk1.8

**Comment by looly** [comment]
请升级到5.1.0尝试，此问题之前有人提过，已修复了。十分感谢。

详细见：https://gitee.com/loolly/dashboard/issues?id=I16PKP
