### ISSUE TITLE
国密SM2验签问题

### ISSUE THREAD

**Issue by dalaocu** [looly/hutool#686]
看了示例的代码，采用sm2验签的时候是从X.509格式加载公钥的。例如：

 KeyPair pair = SecureUtil.generateKeyPair("SM2");

 byte[] publicKey = pair.getPublic().getEncoded();

 SM2 s  = SmUtil.sm2(null, publicKey);

 s.verify(text.getBytes(), signData); 

在这里，publicKey必须为DER编码存储。

但是，在实际的使用场景中，我们会获得公钥，是以普通的十六进制存储的。请问需要如何转换成DER的编码？

**Comment by looly** [comment]
使用：
```java
String publicKey = 你的十六进制密钥字符串
SmUtil.sm2(null, publicKey);
```

**Comment by dalaocu** [comment]
> 使用：
> 
> ```java
> String publicKey = 你的十六进制密钥字符串
> SmUtil.sm2(null, publicKey);
> ```

不，这里的十六进制密钥是有编码要求的，必须是DER的才行。
但是，在有些场景下，拿到的密钥是普通的十六进制编码，并没有按照DER的格式编码的，所以无法使用。
由于bc库过于复杂，我还没找到十六进制转DER格式的方法。所以，我参考TASSL，自己实现了一个验签的功能。

**Comment by looly** [comment]
可否给我发一份示例的密钥么？我这边做个测试。

issue中不方便可邮箱：loolly@aliyun.com

发送后请重新打开此issue。感谢。

**Comment by dalaocu** [comment]
Hi，Looly


首先非常感谢Hutool，太棒了！


国密的测试信息如下：
公钥X:长度 32(0x20)
e8c670380cb220095268f40221fc748fa6ac39d6e930e63c30da68bad97f885d
| 公钥Y:长度 0(0x0) |
|
a6e8c9ad722c3683ab859393220d1431eb1818ed44a942efb07b261a0fc769e7
数据:长度 32(0x20)
434477813974bf58f94bcf760833c2b40f77a5fc360485b0b9ed1bd9682edb45
签名后数据:长度 128(0x80)
09628650676000c8d18bf43db68e7f66dfaed230d87e6391c29eb594b7b9cc3c8d370dbd29ce62bbcf3506adb57f041d8646ae4f70a26ea5179418e738fd4372e8c670380cb220095268f40221fc748fa6ac39d6e930e63c30da68bad97f885da6e8c9ad722c3683ab859393220d1431eb1818ed44a942efb07b261a0fc769e7


算法：  SM2公钥验签
数据  长度32(0x20)字节
43 44 77 81 39 74 BF 58 F9 4B CF 76 08 33 C2 B4 0F 77 A5 FC 36 04 85 B0 B9 ED 1B D9 68 2E DB 45 
签名结果  长度128(0x80)字节
09 62 86 50 67 60 00 C8 D1 8B F4 3D B6 8E 7F 66 DF AE D2 30 D8 7E 63 91 C2 9E B5 94 B7 B9 CC 3C 8D 37 0D BD 29 CE 62 BB CF 35 06 AD B5 7F 04 1D 86 46 AE 4F 70 A2 6E A5 17 94 18 E7 38 FD 43 72 E8 C6 70 38 0C B2 20 09 52 68 F4 02 21 FC 74 8F A6 AC 39 D6 E9 30 E6 3C 30 DA 68 BA D9 7F 88 5D A6 E8 C9 AD 72 2C 36 83 AB 85 93 93 22 0D 14 31 EB 18 18 ED 44 A9 42 EF B0 7B 26 1A 0F C7 69 E7 
ID：16(0x10)字节
31 32 33 34 35 36 37 38 31 32 33 34 35 36 37 38 
HASH：32(0x20)字节
19 97 DE 64 22 F5 AD 56 8A 79 7B C0 8C 91 C9 7C 09 66 99 C9 EC 20 29 0C 4C C9 F8 47 B3 53 E6 05 
验签 通过


参考你之前推荐的工具： https://i.goto327.top/CryptTools/SM2.aspx?tdsourcetag=s_pctim_aiomsg









在 2019-12-30 06:18:42，"Golden Looly" <notifications@github.com> 写道：

可否给我发一份示例的密钥么？我这边做个测试。

issue中不方便可邮箱：loolly@aliyun.com

**Comment by looly** [comment]
关于密钥格式的问题算是解决了，但是你给你的我始终验证为false，很是头疼。

```
String d = "FAB8BBE670FAE338C9E9382B9FB6485225C11A3ECB84C938F10F20A93B6215F0";
String x = "9EF573019D9A03B16B0BE44FC8A5B4E8E098F56034C97B312282DD0B4810AFC3";
String y = "CC759673ED0FC9B9DC7E6FA38F0E2B121E02654BF37EA6B63FAF2A0D6013EADF";

String data = "434477813974bf58f94bcf760833c2b40f77a5fc360485b0b9ed1bd9682edb45";
String id = "31323334353637383132333435363738";

final SM2 sm2 = new SM2(d, x, y);

final String sign = sm2.signHex(data, id);

Assert.assertTrue(sm2.verifyHex(data, sign));
```
