### ISSUE TITLE
HttpRequest get 有些请求获取的数据是xml格式

### ISSUE THREAD

**Issue by yifan2333** [looly/hutool#688]
`String str = HttpRequest.get(url).header("token", "token").execute().body();`
str 是xml格式的，使用PostMan 返回是json格式的。
修改为
`String str = HttpRequest.get(url).header("token", "token").header("Accept", "*").execute().body();`
即可返回正常的json格式。

**Comment by yifan2333** [comment]
java version "1.8.0_221"
`<dependency>
	<groupId>cn.hutool</groupId>
	<artifactId>hutool-http</artifactId>
	<version>4.3.2</version>
</dependency>`

**Comment by looly** [comment]
请升级Hutool到最新：5.1.0，新版本修改了优先级，json优先。

**Comment by yifan2333** [comment]
好的，谢谢～～
