### ISSUE TITLE
RSA加密 缺少依赖 是不是文档中没有添加说明

### ISSUE THREAD

**Issue by haust-lyb** [looly/hutool#689]
KeyPair pair = SecureUtil.generateKeyPair("RSA");
        System.out.println(pair.getPrivate());
        System.out.println("--------------------------------------");
        System.out.println(pair.getPublic());

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>

**Comment by looly** [comment]
这个依赖不是必须的，此处不需要。请升级Hutool到最新版本呢：5.1.0
