### ISSUE TITLE
关于文件缓存api，很吃内存问题

### ISSUE THREAD

**Issue by xiaobaogeit** [looly/hutool#697]
使用了new LRUFileCache(314572800)，进行缓存300M图片文件，运行结果是一下子使用了2G多。
![image](https://user-images.githubusercontent.com/19976188/71660488-2e11af80-2d86-11ea-99f1-ac4d3dd534f7.png)

**Comment by looly** [comment]
对啊，你缓存设置太大了，又没有设置超时。

LRU只有在快满的时候才清理。

**Comment by xiaobaogeit** [comment]
@looly  缓存300M的文件，个人觉得不应该吃这么大的内存，跟是否设置超时无关。

**Comment by looly** [comment]
> @looly 缓存300M的文件，个人觉得不应该吃这么大的内存，跟是否设置超时无关。

确实， 你可以设置每个键值对的超时事件
