### ISSUE TITLE
在Validator工具中，如果我的url两端带空格，则调用isUrl方法会返回false

### ISSUE THREAD

**Issue by felayman** [looly/hutool#7]
如下：t
rue
http://openapi.baidu.com/public/2.0/bmt/translate?client_id=xGzW7GhPIK3vLjnTeXZ1LOfG&q=today&from=auto&to=auto
 http://openapi.baidu.com/public/2.0/bmt/translate?client_id=xGzW7GhPIK3vLjnTeXZ1LOfG&q=today&from=auto&to=auto
false
如果是不小心复制的时候两侧多了个空格的话，作者最好加上trim验证。

**Comment by felayman** [comment]
改成如下最好，isByRegex(URL, value.trim());

**Comment by looly** [comment]
此问题已经在2.11.6中解决（我用了new URL方式来验证）
