### ISSUE TITLE
ZipUitl 解压Mac打的压缩包异常Exception in thread "main" java.lang.NullPointerException: File path is blank!

### ISSUE THREAD

**Issue by linc007** [looly/hutool#701]
ZipUitl 解压Mac打的压缩包异常Exception in thread "main" java.lang.NullPointerException: File path is blank!

**Comment by looly** [comment]
重复：https://gitee.com/loolly/hutool/issues/I17VU7?from=project-issue

**Comment by mirocolo** [comment]
4.6版本不修复么

**Comment by looly** [comment]
4.x稍后修复。
