### ISSUE TITLE
SM4解密问题

### ISSUE THREAD

**Issue by BeyondTheBlade** [looly/hutool#706]
问一下，SM4作为对称加密算法，为什么不能分开加密解密。
我在使用例子中的代码测试的时候是可以加密 以及 解密的。
但是我一旦在不同的线程中，将加密完的密文进行解密，会报错：javax.crypto.BadPaddingException: pad block corrupted
这个机制是因为SM4本身算法的原因吗？
SymmetricCrypto sm4 = SmUtil.sm4()，一旦sm4不同了，就没办法解密了。

**Comment by BeyondTheBlade** [comment]
抱歉，实际使用过了之后，发现是我用法不对。
官方文档没有给出正确的写法，例子给的是随机密钥，所以密钥变量线程不共享。
必须自己传入key到SM4（）中。

**Comment by looly** [comment]
是滴，文档稍后改进

**Comment by GuangjuY** [comment]
文档还没有改变啊，求一个正确的样例 @BeyondTheBlade

**Comment by hanguyu** [comment]
![image](https://user-images.githubusercontent.com/94884855/158503980-31bc134c-b2b7-4450-bdfc-beb23766a32f.png)

加密没问题，解密出现这种问题

**Comment by BeyondTheBlade** [comment]
> 文档还没有改变啊，求一个正确的样例 @BeyondTheBlade

解密的时候，那个key要带过去

**Comment by hanguyu** [comment]
![image](https://user-images.githubusercontent.com/94884855/158507629-14aa2aab-0fdf-475a-b4b5-0671e3c5906d.png)
![image](https://user-images.githubusercontent.com/94884855/158507675-a0d64766-4894-4775-9a41-ed0c3c76574f.png)
![image](https://user-images.githubusercontent.com/94884855/158507836-96e89cfa-a1c2-4e31-aaea-51a50b47033f.png)
加密完成直接解密，
![image](https://user-images.githubusercontent.com/94884855/158507892-a6bcd25b-8639-4f73-99d6-5d00e11e17e1.png)

**Comment by looly** [comment]
@hanguyu 我并没有复现你的问题：

```java
String content = "test中文";

SecretKey key = KeyUtil.generateKey(SM4.ALGORITHM_NAME);

SM4 sm4 = new SM4(Mode.ECB, Padding.PKCS5Padding, key);
Assert.assertEquals("SM4/ECB/PKCS5Padding", sm4.getCipher().getAlgorithm());

String encryptHex = sm4.encryptHex(content);
String decryptStr = sm4.decryptStr(encryptHex, CharsetUtil.CHARSET_UTF_8);
```

![image](https://user-images.githubusercontent.com/1432613/158805833-70e076cc-4aaa-4589-aae1-b26b067d1b67.png)

尝试改为：

```java
SM4 sm4 = new SM4(Mode.ECB, Padding.PKCS5Padding, key);
```

试下看可以不。

**Comment by GuangjuY** [comment]
是的，我已经解决了，原来我看文档，原来SM4需要传进一个key密钥值，如果没有的话会随机生成一个
需要这样
![image](https://user-images.githubusercontent.com/35771909/158918216-799ed87c-eefa-4e8e-b6ae-f9f7400df04e.png)

**Comment by wangjinliang1991** [comment]
文档还没改呢 @looly ，也踩坑了

**Comment by looly** [comment]
我修改下文档
