### ISSUE TITLE
在Db.use().query的方法中增加Map<String, Object>参数的接口

### ISSUE THREAD

**Issue by simonzfq** [looly/hutool#709]
`Map<String, Object> paramMap = MapUtil.builder("name1", (Object)"张三").put("age", 12).put("subName", "小豆豆").build();
Db.use().query("select * from table where id=@id and name = @name1 and nickName = @subName", paramMap);`
官网中的命名占位符的SQL执行总是报错，而直接使用SqlExecutor可以正确执行。
希望在Db.use().query的方法中增加Map<String, Object>参数的接口。

**Comment by looly** [comment]
确实没有传map的方法，5.1.1加入，感谢。

**Comment by waerly** [comment]
5.1.1 也是不能用的啊

**Comment by looly** [comment]
有的啊:

![image](https://user-images.githubusercontent.com/1432613/72230659-e5fa5480-35f1-11ea-9c98-90fd5a4d016b.png)
