### ISSUE TITLE
你好，JschUtil中执行sh命令能否新增，sh命令执行超时时间？

### ISSUE THREAD

**Issue by heroXin2019** [looly/hutool#718]
有些sh命令去掉脚本时间太长一直长连接着

**Comment by looly** [comment]
JschUtil.exec执行传入Session对象，此对象可以设置timeout属性。

**Comment by heroXin2019** [comment]
你好 ，Session设置timeout属性，这个timeout只是登陆超时，不是脚本执行超时。

**Comment by looly** [comment]
执行超时没法设置把?

**Comment by heroXin2019** [comment]
是的 ，看jsch 官方api也没有执行超时时间设置。看你们能不能在工具类读取socket流的时候，用个计时器来控制下

**Comment by looly** [comment]
> 是的 ，看jsch 官方api也没有执行超时时间设置。看你们能不能在工具类读取socket流的时候，用个计时器来控制下

暂时实现不了。Hutool对于Jsch封装仅仅局限于api封装。不打算深入改造。不过说实话，Jsch库比较老了，暂时没有找到更好的替代库。
