### ISSUE TITLE
Hutool-db模块，日期占位符总是出错

### ISSUE THREAD

**Issue by simonzfq** [looly/hutool#719]
使用T.IN_CY_TIME < TO_DATE(@startTime, 'YYYY-MM-DD HH24:MI:SS')方式来设置日期条件，命名占位符中设置为: MapUtil.builder().put("startTime", "2020-01-08 08:52:18")，执行后总是报ORA-01858:在要求输入数字处找到非数字字符。

**Comment by looly** [comment]
IN_CY_TIME 是不不是日期字段?

**Comment by simonzfq** [comment]
> IN_CY_TIME 是不不是日期字段?

确定是日期字段，表述里的数据库是Oracle

**Comment by looly** [comment]
直接传Date对象试下。
