### ISSUE TITLE
RSA算法中，BlockSize长度错误!

### ISSUE THREAD

**Issue by Relucent** [looly/hutool#721]
安全加密包
cn.hutool.crypto.asymmetric.RSA
分段加密，关于 BlockSize 的长度描述和计算方式是错误 (不严谨) 的。

“加密数据长度 <= 模长-11”这个只是针对于 RSA/ECB/PKCS1Padding 说的。

针对 RSA 的几种填充方式：
RSA/ECB/NoPadding  钥模长-1
RSA/ECB/PKCS1Padding    钥模长 -11
RSA/ECB/OAEPWithSHA1AndMGF1Padding  钥模长-41

举个例子，默认情况：
对 RSA/ECB/PKCS1Padding 长度限制是 117(加密)和128(解密)
而 RSA/None/NoPadding   长度限制是 127(加密)和128(解密)

**如果使用JDK自带的RSA算法，然后用钥模长 -11去分段加密/解密数据，得到的结果将是错误的。**

另外：如果是基础算法的话，BlockSize 也 可以通过cipher.getBlockSize() 来获取
只有获取不到的时候（返回0）的情况，才需要自己去判断计算。

**Comment by looly** [comment]
可以调用:
```java
setEncryptBlockSize

setDecryptBlockSize
```

自定义块大小。Integer.MAX表示不限制。

**Comment by Relucent** [comment]
如果不引入 bouncy castle 库，默认 new RSA()  某些环境会加密解密失败。

你提供的解决方案是自己设置 setEncryptBlockSize ，setDecryptBlockSize ！
这个方案实在太不友好，并且太隐晦了

**Comment by looly** [comment]
可否有更好的方案？因为不同的算法block方案不同，除了自定义，不知道如何自动识别。

**Comment by Relucent** [comment]
如果引入 bouncy castle 的情况 javax.crypto.Cipher类的 getBlockSize() 方法可以直接获取块大小。

但是不引入 bouncy castle的情况 , cipher.getBlockSize()  == 0

我想到的方法是，默认取 cipher.getBlockSize() ，如果等于 0 ，那么再自己根据算法名和KEY的大小去算。 

 --------------------
目前 觉得可以这样调整一下：
1、 setEncryptBlockSize，setDecryptBlockSize方法保留，默认值 -1
2、加密解密时，如果BlockSize不为-1 （用户自定义了），那么按照用户设置的来处理
3、否则通过  cipher.getBlockSize() 方法直接获取块大小 (引入 bouncy castle 的情况能正确获取，不用自己算)
4、如果 cipher.getBlockSize()  == 0 ，那么再根据KEY和算法名称去计算BlockSize，（算法写到子类里面，或者提供一个工具类专门处理这个）

 --------------------
**附：引入 BouncyCastle的情况，可以通过 getBlockSize 获取 BlockSize 大小**
```       
 Provider provider = new org.bouncycastle.jce.provider.BouncyCastleProvider();
  //算法名称     
  String algorithm = "RSA";
 //生成密钥
  KeyPairGenerator gen = KeyPairGenerator.getInstance(algorithm);
  KeyPair keyPair = gen.generateKeyPair();
  PublicKey key = keyPair.getPublic();

 //获得加解密器
  Cipher cipher = Cipher.getInstance(algorithm);

  cipher.init(Cipher.ENCRYPT_MODE, key);
  System.out.println(cipher.getBlockSize());

  cipher.init(Cipher.DECRYPT_MODE, key);
  System.out.println(cipher.getBlockSize());
```

**Comment by looly** [comment]
hutool中RSA确实对BC库的兼容性需要进一步增强（之前使用`cipher.getBlockSize()`获取的块大小一直是0就放弃使用了）

此issue我暂时打开，稍后做些修改。再次感谢提供如此详细的思路！

**Comment by looly** [comment]
5.1.6调整策略。
