### ISSUE TITLE
字段大小写敏感问题

### ISSUE THREAD

**Issue by crskyp** [looly/hutool#722]
1、执行代码：List<Entity> list = Db.use(ds).query(sql, new EntityListHandler(true));
2、entity.getStr("fpipenumber")可以获取值；
3、entity.getStr("fPipeNumber")获取值为null；
4、entity.getStr("FPIPENUMBER")获取值为null
期望：字段大小写不敏感

**Comment by looly** [comment]
5.1.1改进此问题，感谢。
