### ISSUE TITLE
正则工具的疑问

### ISSUE THREAD

**Issue by XSun771** [looly/hutool#723]
首先感谢作者的工作和付出。

https://www.hutool.club/docs/#/core/工具类/正则工具-ReUtil

文档举例说明是否有一些不完善？

比如

> ReUtil.extractMulti
> 抽取多个分组然后把它们拼接起来
> ```
> String resultExtractMulti = ReUtil.extractMulti("(\\w)aa(\\w)", content, "$1-$2");
> Assert.assertEquals("Z-a", resultExtractMulti);
> ```

可是如果不知道传入进来用来匹配的content的内容是什么，理解起来还是有点麻烦。

另外最简单的使用场景，获取匹配正则表达式中的第一个()中的内容，看文档在由来章节展现了代码，希望能够在使用章节补一个例子。

**Comment by looly** [comment]
缺了个content，稍后补上，感谢。
