### ISSUE TITLE
JSONUtil.readJSON不抛出异常么？

### ISSUE THREAD

**Issue by XSun771** [looly/hutool#724]
使用JSONUtil.readJSON时，传入的文件不存在，文件存在但打不开之类的常见错误，应该抛出对应的异常吧？若是在方法内部处理了，也应该在控制台输出一下信息。。目前看来好像没有相关措施？

**Comment by looly** [comment]
有抛出异常啊，你程序是不try掉了？

**Comment by XSun771** [comment]
> 有抛出异常啊，你程序是不try掉了？

确实是有，不过是runtimeexception的子类，所以不要求一定处理。最好在文档里声明一下吧。另外转为runtimeexception的异常，发生的时候不会产生任何输出么？

**Comment by looly** [comment]
runtime异常一般不会捕获，默认打印堆栈，除非你屏蔽了。
