### ISSUE TITLE
参考文档，错误描述

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#726]
[http://ww1.sinaimg.cn/large/0067qJAnly1gaxeud6cwlj30ne06wt9u.jpg](http://ww1.sinaimg.cn/large/0067qJAnly1gaxeud6cwlj30ne06wt9u.jpg)

详见上面截图，`feilong-core最在开源中国中发现的` 不通顺。

**Comment by looly** [comment]
哈哈，感谢。错别字。
