### ISSUE TITLE
数据库查询操作分页查询不支持OR

### ISSUE THREAD

**Issue by shininglxj** [looly/hutool#727]
例如查询SQL：SELECT * FROM Table WHERE (**A1 LIKE '%A%' OR B1 LIKE ‘B’**) AND STATUS = 1
以上SQL如何通过Db.use().page(entity, pageNo, pageSize)查询设置多个OR组合查询

**Comment by looly** [comment]
使用query方法手动传SQL语句吧，复杂SQL使用page方法太复杂了。
