### ISSUE TITLE
springboot使用db时，过一段时间出现超时

### ISSUE THREAD

**Issue by SY1123** [looly/hutool#729]
报错信息：
 com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 302,176 milliseconds ago. The last packet sent successfully to the server was 302,213 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

**Comment by looly** [comment]
连接池超时设置有不匹配吧。

**Comment by tangmingze7280** [comment]
我也出现这个问题 一周就 异常了
