### ISSUE TITLE
Season 里面有别字

### ISSUE THREAD

**Issue by aristotll** [looly/hutool#73]
https://github.com/looly/hutool/blob/0b3895f23aff268eaddb83f0d48e4d3d0daf4ce4/hutool-core/src/main/java/com/xiaoleilu/hutool/date/Season.java#L20-L21

这里有 typo 吧 秋天是 autumn 而不是 ANTUMN 是 u 不是 n

**Comment by looly** [comment]
感谢意见。3.2.3中修复此问题
