### ISSUE TITLE
请问json.org官方的JSON解析是什么?

### ISSUE THREAD

**Issue by XSun771** [looly/hutool#734]
https://hutool.cn/docs/#/json/概述

> Hutool开始也并不想自己写一个JSON，但是在各种工具的封装中，发现JSON已经不可或缺，因此将json.org官方的JSON解析纳入其中，

我有点担心是不是 json-lib  因为从网上的一些性能比较结果来看 json-lib 相当得菜..

https://www.xncoding.com/2018/01/09/java/jsons.html

https://mp.weixin.qq.com/s/wj106b9zdWQI1aRcAyJd1w

**Comment by looly** [comment]
确实比较菜，因此hutool也没有参与性能比较。

你可以测试下hutool的性能如何。

**Comment by XSun771** [comment]
> 确实比较菜，因此hutool也没有参与性能比较。
> 
> 你可以测试下hutool的性能如何。

不要说是免费的公益项目，就算是成熟的商业项目也可能百密一疏，就不能好好正面回答么？是就是呗。

**Comment by looly** [comment]
> > 确实比较菜，因此hutool也没有参与性能比较。
> > 你可以测试下hutool的性能如何。
> 
> 不要说是免费的公益项目，就算是成熟的商业项目也可能百密一疏，就不能好好正面回答么？是就是呗。

确实是正面回答啊，我说了hutool的json模块性能比较菜啊~~

性能菜的原因可能如下：

1、对于bean对象解析hutool使用了反射而非字节码解析
2、json字符串的parser部分并没有修改源码的逻辑，只是基于json-lib稍作修改和简化。

有时间我这边做个性能测试，不过个人能力有限，尽量优化，哈哈。

**Comment by XSun771** [comment]
> > > 确实比较菜，因此hutool也没有参与性能比较。
> > > 你可以测试下hutool的性能如何。
> > 
> > 
> > 不要说是免费的公益项目，就算是成熟的商业项目也可能百密一疏，就不能好好正面回答么？是就是呗。
> 
> 确实是正面回答啊，我说了hutool的json模块性能比较菜啊~~
> 
> 性能菜的原因可能如下：
> 
> 1、对于bean对象解析hutool使用了反射而非字节码解析
> 2、json字符串的parser部分并没有修改源码的逻辑，只是基于json-lib稍作修改和简化。
> 
> 有时间我这边做个性能测试，不过个人能力有限，尽量优化，哈哈。

谢谢解答，考虑一下用gson或者jackson之类的有名的库做底层？

**Comment by looly** [comment]
> > > > 确实比较菜，因此hutool也没有参与性能比较。
> > > > 你可以测试下hutool的性能如何。
> > > 
> > > 
> > > 不要说是免费的公益项目，就算是成熟的商业项目也可能百密一疏，就不能好好正面回答么？是就是呗。
> > 
> > 
> > 确实是正面回答啊，我说了hutool的json模块性能比较菜啊~~
> > 性能菜的原因可能如下：
> > 1、对于bean对象解析hutool使用了反射而非字节码解析
> > 2、json字符串的parser部分并没有修改源码的逻辑，只是基于json-lib稍作修改和简化。
> > 有时间我这边做个性能测试，不过个人能力有限，尽量优化，哈哈。
> 
> 谢谢解答，考虑一下用gson或者jackson之类的有名的库做底层？

这些库本身比较好用了，故不需要封装，hutool自己实现是考虑到一半场景使用及内部部分功能的协同。
