### ISSUE TITLE
DateUtil中yesterday，today，tomorrow返回类型不一样

### ISSUE THREAD

**Issue by Taskeren** [looly/hutool#739]
DateUtil.yesterday() -> DateTime  
DateUtil.tomorrow() -> DateTime  
**DateUtil.today() -> String**  
？？？

**Comment by looly** [comment]
这个是hutool版本更新遗留的不一致问题。

today方法最早想使用一种快捷的日期返回方式，故返回字符串，后来发现today这个名字应该返回datetime，但是考虑到兼容性，故保留。

与之对应的是date方法。
