### ISSUE TITLE
CronUtil.remove方法不是静态的，想用这个方法都用不了额

### ISSUE THREAD

**Issue by fqlee** [looly/hutool#74]
CronUtil.remove方法不是静态的，想用这个方法都用不了额

**Comment by looly** [comment]
确认bug。请暂时使用Scheduler scheduler = new Scheduler();自行创建使用。3.3.0会修复此问题。

**Comment by fqlee** [comment]
谢谢,我目前是自行copy了CronUtil代码至JobUtil，单独把remove方法变为静态的
