### ISSUE TITLE
StrUtil.splitToInt 拆分不支持根据长度为 0 的字符串进行拆分

### ISSUE THREAD

**Issue by galaxy-t** [looly/hutool#744]
发现 StrUtil 工具类中的拆分方法均不支持根据长度为 0 的字符串进行拆分，如标题想将字符串转换成 int 数组需要  
int[] intArr2 = Convert.convert(int[].class, StrUtil.split(str, 1)); 
缺少了作者说的“甜甜的”感觉，嘿嘿。
在下是你的忠实粉丝。

**Comment by looly** [comment]
没看懂你的意思。“根据长度为 0 的字符串进行拆分”这句话是什么意思呢？是被拆分的字符串长度为0？

还有你发的`Convert.convert(int[].class, StrUtil.split(str, 1));`中第二个参数1应该是个char，分隔符，不是数字长度。
