### ISSUE TITLE
CombinationAnnotationElement类中中init方法有个判断有误

### ISSUE THREAD

**Issue by hbys126878033** [looly/hutool#752]
private void init(AnnotatedElement element) {
        final Annotation[] declaredAnnotations = element.getDeclaredAnnotations();
        this.declaredAnnotationMap = new HashMap<>();
        parseDeclared(declaredAnnotations);

        final Annotation[] annotations = element.getAnnotations();
        if(ObjectUtil.equal(declaredAnnotations, annotations)) {
            this.annotationMap = this.declaredAnnotationMap;
        }else {
            this.annotationMap = new HashMap<>();
            parse(annotations);
        }
    }

ObjectUtil.equal(declaredAnnotations, annotations)) 这个地方的判断应该是有误的，
需要调整成Arrays.equals()方法

**Comment by looly** [comment]
感谢，5.1.4修复此问题。
