### ISSUE TITLE
ExecutorBuilder类的build方法在创建线程池的隐患

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#753]
ExecutorBuilder类的build方法在创建线程池时，方法参数没有给出列队参数，构造函数里面默认用了new LinkedBlockingQueue<Runnable>()，这样会导致无限存放任务，maxPoolSize就会无效，堆积的请求处理队列可能会耗费非常大的内存，甚至OOM，建议队列设置默认值1024。
并提供一个可传队列参数的方法，public static ThreadPoolExecutor newExecutor(int corePoolSize, int maximumPoolSize, BlockingQueue<Runnable> workQueue)，注释提示要指定列队大小。

**Comment by looly** [comment]
1. SynchronousQueue    它将任务直接提交给线程而不保持它们。当运行线程小于maxPoolSize时会创建新线程，否则触发异常策略

2. LinkedBlockingQueue 无界队列，当运行线程大于corePoolSize时始终放入此队列，此时maximumPoolSize无效

3. ArrayBlockingQueue  有界队列，相对无界队列有利于控制队列大小，队列满时，运行线程小于maxPoolSize时会创建新线程，否则触发异常策略

如注释所说，LinkedBlockingQueue本身为无界队列，此处限制队列大小反而会导致等待锁死。

此处需用ArrayBlockingQueue限制大小。

具体用`setWorkQueue`方法。
![image](https://user-images.githubusercontent.com/1432613/75005752-55454d00-54aa-11ea-8c6c-2f275bda95da.png)

**Comment by mvp31** [comment]
2、你好，在ThreadPoolExecutor源码里execute方法得知，列队workQueue都是调用offer插入任务，队列满了就直接返回false，然后会执行reject方法等于抛出异常。所以LinkedBlockingQueue限制大小后，超过maxPoolSize值不会等待锁死是返回false直接触发异常策略。请作者分析一下是否正确，非常感谢！
int c = ctl.get();
        if (workerCountOf(c) < corePoolSize) {
            if (addWorker(command, true))
                return;
            c = ctl.get();
        }
        if (isRunning(c) && workQueue.offer(command)) {
            int recheck = ctl.get();
            if (! isRunning(recheck) && remove(command))
                reject(command);
            else if (workerCountOf(recheck) == 0)
                addWorker(null, false);
        }
        else if (!addWorker(command, false))
            reject(command);

**Comment by looly** [comment]
确实，是我理解的问题。

不过如果LinkedBlockingQueue默认是无界队列，此处用户可以自定义传入的对象。


5.1.4修改默认值，感谢！
