### ISSUE TITLE
ThreadUtil类的newSingleExecutor创建单例线程池的隐患

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#754]
ThreadUtil类的
public static ExecutorService newSingleExecutor() {
return Executors.newSingleThreadExecutor();
}
方法。调用源码是
new ThreadPoolExecutor(1, 1,
                                    0L, TimeUnit.MILLISECONDS,
                                    new LinkedBlockingQueue<Runnable>())
创建了一个无界队列LinkedBlockingQueuesize，是一个最大值为Integer.MAX_VALUE的线程阻塞队列，当添加任务的速度大于线程池处理任务的速度，可能会在队列堆积大量的请求，消耗很大的内存，甚至导致OOM。
建议设置LinkedBlockingQueue<Runnable>(1024)默认值

**Comment by looly** [comment]
如果设置默认值，不会产生堆积，但是会产生阻塞。

此处不做修改。

**Comment by mvp31** [comment]
你好，设置了LinkedBlockingQueue的默认值，列队超过最大值会直接触发异常策略，不会产生阻塞，请作者分析一下是否正确，感谢！

**Comment by looly** [comment]
5.1.4修改默认容量，感谢。
