### ISSUE TITLE
ThreadUtil类的newExecutor()方法有可能误用

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#755]
你好，ThreadUtil类的newExecutor()方法会创建一个SynchronousQueue<Runnable>线程池，但int maxPoolSize = Integer.MAX_VALUE，为无限大，会一直添加新线程来执行，直到无限，有可能消耗很大的内存，建议是否可以控制下maxPoolSize初始值，避免初学者误用。

**Comment by looly** [comment]
这个是有意为之的。

maxPoolSize = Integer.MAX_VALUE表示无限创建下线程，此时线程池和普通的new Thread一致。
