### ISSUE TITLE
EscapeUtil类的escape转义方法出来的结果与文档描述不一样

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#758]
### 版本情况

JDK版本：    JDK8
hutool版本： 5.1.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

String escapeHtml4 = EscapeUtil.escape("*@-_+./(123你好)");

返回结果：%2a%40%2d%5f%2b%2e%2f%28123%u4f60%u597d%29

异常：没有保留这些字符 * @ - _ + . /

**Comment by looly** [comment]
5.1.5修复此方法，感谢。
