### ISSUE TITLE
BitSetBloomFilter类的构造函数，使用者比较难理解怎样控制错误率

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#759]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.1.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
BitSetBloomFilter类的构造函数，使用者比较难理解怎样控制错误率
/**
	 * 构造一个布隆过滤器，过滤器的容量为c * n 个bit.
	 * 
	 * @param c 当前过滤器预先开辟的最大包含记录,通常要比预计存入的记录多一倍.
	 * @param n 当前过滤器预计所要包含的记录.
	 * @param k 哈希函数的个数，等同每条记录要占用的bit数.
	 */
	public BitSetBloomFilter(int c, int n, int k) {
		this.hashFunctionNumber = k;
		this.bitSetSize = (int) Math.ceil(c * k);
		this.addedElements = n;
		this.bitSet = new BitSet(this.bitSetSize);
	}
好像Guava和Redis的第三个参数是小数，数值小（越接近0）就代表错误率越低，数据值越大（越接近1）代表错误率越高，这样使用者会更容易能推算设置参数。

**Comment by looly** [comment]
hutool使用多个hash函数来生成hash值，此值为使用的hash函数个数，此处并非错误率。
