### ISSUE TITLE
建议整合OWASP 的 java-html-sanitizer 的xss安全类库

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#762]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
OWASP 的 java-html-sanitizer 是google维护的xss安全库，性能比较antisamy的好，建议可以整合到工具里

**Comment by looly** [comment]
你可以直接使用这个库，extra模块暂时不考虑收录~~
