### ISSUE TITLE
升级到5.2.0后，模版引擎失效了。

### ISSUE THREAD

**Issue by ChambersChan** [looly/hutool#767]
### 版本情况
hutool版本： 5.2.0

### 问题描述
加载出来的是文件名称，回退版本就没问题。

![image](https://user-images.githubusercontent.com/32906036/76197116-80f46100-6226-11ea-9af2-2a55376b8201.png)

**Comment by looly** [comment]
升级后采用SPI机制，你是怎么使用的？图挂了……

**Comment by looly** [comment]
升级后采用SPI机制，你是怎么使用的？图挂了……

**Comment by ChambersChan** [comment]
图片是参考文档写的一个问题复现截图，代码：
TemplateEngine engine = TemplateUtil.createEngine(new TemplateConfig("", TemplateConfig.ResourceMode.CLASSPATH));
Template template = engine.getTemplate("test.btl");
String result = template.render(Dict.create().set("name", "Hutool"));
输出是：test.btl。
模版引擎是ibeetl，3.0.13.RELEASE

**Comment by yupaits** [comment]
> 图片是参考文档写的一个问题复现截图，代码：
> TemplateEngine engine = TemplateUtil.createEngine(new TemplateConfig("", TemplateConfig.ResourceMode.CLASSPATH));
> Template template = engine.getTemplate("test.btl");
> String result = template.render(Dict.create().set("name", "Hutool"));
> 输出是：test.btl。
> 模版引擎是ibeetl，3.0.13.RELEASE

Hutool 5.2.0版本，我使用freemarker模板引擎也是这样，回退到TemplateFactory.doCreate(TemplateCOnfig config)方法使用 `new FreemarkerEngine(config)`方式创建模板引擎的版本功能正常。

**Comment by looly** [comment]
5.2.1修复此问题，感谢。
