### ISSUE TITLE
建议json增加key命名风格，微信api的全是下划线风格的

### ISSUE THREAD

**Issue by hzdjulytech** [looly/hutool#768]
建议可自由切换命名风格  可将下划线风格的json直接与bean转换 转为json时也可直接转为 下划线风格 避免注释等其他全局配置

**Comment by yupaits** [comment]
> 建议可自由切换命名风格 可将下划线风格的json直接与bean转换 转为json时也可直接转为 下划线风格 避免注释等其他全局配置

微信开发可以用 [WxJava](https://github.com/Wechat-Group/WxJava) 工具，很方便

**Comment by looly** [comment]
在Bean中的字段上添加`@Alias("name")` 注解即可。

**Comment by hzdjulytech** [comment]
WxJava 目前不支持v3  就是不想写注释 我还是自己来吧

**Comment by binarywang** [comment]
> WxJava 目前不支持v3 就是不想写注释 我还是自己来吧

v3已经实现了部分接口，欢迎来参观指导
