### ISSUE TITLE
HttpRequest直接用IP地址访问一个网站，添加body参数去请求有BUG

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#769]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.6.14（请确保最新尝试是否还有问题）

HttpRequest直接用IP地址访问一个网站，添加body参数去请求有BUG，第一次正常返回结果，第二次请求什么也拿不到（必须要使用IP地址访问，还有添加Body参数，4.4.4版本无此问题）

1. 复现代码
见图片

**Comment by Andy095** [comment]
![Snipaste_2020-03-10_14-04-08](https://user-images.githubusercontent.com/41384519/76284693-f882c880-62d8-11ea-8dd8-fb9eaca7d6b3.jpg)

**Comment by Andy095** [comment]
![QQ图片20200310141421](https://user-images.githubusercontent.com/41384519/76284931-7f37a580-62d9-11ea-9861-a2904e47756e.png)

**Comment by Andy095** [comment]
影响项目进度了，麻烦能尽快解决

**Comment by Andy095** [comment]
![Snipaste_2020-03-10_14-20-35](https://user-images.githubusercontent.com/41384519/76285292-5f54b180-62da-11ea-8a65-b6409ba14453.jpg)

请求4次才打印出来两次

**Comment by Andy095** [comment]
根据抓包结果，第二次和第四次请求根本没有发出

**Comment by looly** [comment]
升级到5.2.1试下，并调用

```java
HttpRequest.get().disableCache().body().execute().body()
```

**Comment by Andy095** [comment]
试过了，一样不行。
项目需要使用

**Comment by Andy095** [comment]
1.7版本的

**Comment by looly** [comment]
麻烦加QQ具体沟通吧

**Comment by looly** [comment]
已找到问题，下个版本修复此问题，感谢。~~
