### ISSUE TITLE
ImageUtil.hexToColor()方法有bug

### ISSUE THREAD

**Issue by zhangyangze** [looly/hutool#771]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.3.0 最新的好像也是

### 问题描述（包括截图）
ImageUtil.hexToColor()中StrUtil.removePrefix("#", hex)的删除#字符参数传值错误 参数反了
1. 复现代码
`/**
	 * 16进制的颜色值转换为Color对象，例如#fcf6d6
	 * 
	 * @param hex 16进制的颜色值，例如#fcf6d6
	 * @return {@link Color}
	 * @since 4.1.14
	 */
	public static Color hexToColor(String hex) {
		return getColor(Integer.parseInt(StrUtil.removePrefix("#", hex), 16));
	}`

**Comment by looly** [comment]
最新版本已经没有这个问题了，请升级到5.2.1或者4.6.15
