### ISSUE TITLE
1、RandomUtil工具不支持设置seed种子，有些场景不满足需求

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#772]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
1、RandomUtil工具采本地线程继承Random，不支持设置seed种子，导致很多场景不满足需求，建议增加可设置种的Random工具类。

**Comment by looly** [comment]
RandomUtil.createSecureRandom即可。

**Comment by mvp31** [comment]
试了一下RandomUtil.createSecureRandom，好像性能比Random低一倍

**Comment by looly** [comment]
> 试了一下RandomUtil.createSecureRandom，好像性能比Random低一倍

必须啊，毕竟是安全随机类。其它随即类没有种子。
