### ISSUE TITLE
CharUtil建议增加中文字符判断，特殊字符判断

### ISSUE THREAD

**Issue by mvp31** [looly/hutool#773]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
有时需要区分开字母、数字、中文、符号、特殊字符等，建议增加这些都提供判断

**Comment by looly** [comment]
正则表达式不香么？

**Comment by mvp31** [comment]
JAVA本身有提供，Charcater.getType来判断字节类型，建议也可以丰富下工具类
