### ISSUE TITLE
执行以下代码报错

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#776]
Map<String, Object> paramMap = MapUtil.builder("name1", (Object)"张三").put("id", 12).put("subName", "小豆豆").build();
Db.use().query("select * from table where id=@id and name = @name1 and nickName = @subName", paramMap);

**Comment by Andy095** [comment]
![QQ图片20200312120517](https://user-images.githubusercontent.com/41384519/76486256-c2208700-6459-11ea-89c4-964464e1ec7a.png)

**Comment by Andy095** [comment]
![123123](https://user-images.githubusercontent.com/41384519/76486760-517a6a00-645b-11ea-98ac-9c0f7367c5af.png)

**Comment by Andy095** [comment]
![123123](https://user-images.githubusercontent.com/41384519/76486795-69ea8480-645b-11ea-9f95-1db31001d4a9.png)

**Comment by Andy095** [comment]
第二个错误，数据库保存
![Snipaste_2020-03-12_12-28-51](https://user-images.githubusercontent.com/41384519/76487350-1da04400-645d-11ea-8830-9d9bbc25bbfa.jpg)
的时间，导致程序报错
![QQ图片20200312122841](https://user-images.githubusercontent.com/41384519/76487338-15e09f80-645d-11ea-869e-9251d3978f73.png)

**Comment by Andy095** [comment]
![Snipaste_2020-03-12_14-24-34](https://user-images.githubusercontent.com/41384519/76493328-5b0ccd80-646d-11ea-8b4b-894fc441e340.jpg)

**Comment by looly** [comment]
正确的使用方法是：

```
Map<String, Object> paramMap = MapUtil.builder("name1", (Object)"张三").put("id", 12).put("subName", "小豆豆").build();

Db.use().query("select * from table where id=@id and name = @name1 and nickName = @subname", new EntityListHandler(), paramMap);
```

**Comment by looly** [comment]
这块确实存在使用上的歧义，5.2.2改进此处。

**Comment by Andy095** [comment]
![Snipaste_2020-03-12_16-41-18](https://user-images.githubusercontent.com/41384519/76503174-57367680-6480-11ea-9ab0-7bf7ce8ab88b.jpg)

**Comment by looly** [comment]
请升级到最新版本Hutool
