### ISSUE TITLE
关于5.2.2版本JSON工具的bug

### ISSUE THREAD

**Issue by zx965230** [looly/hutool#780]
### 版本情况

JDK版本：     jdk_8_201
hutool版本： 5.2.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
        JSONObject qJson = JSONUtil.parseObj(request);
        log.info(qJson.getStr("head"));
        log.info(qJson.getStr("body"));
```

2. 堆栈信息
    找不到符号，方法getStr()

![微信图片_20200313100911](https://user-images.githubusercontent.com/53927082/76583039-1471ae80-6513-11ea-93c3-df09d91f0b84.png)

**Comment by looly** [comment]
你项目编译的问题，重新编译下，或者看下包导入正常没。

**Comment by zx965230** [comment]
都试过了，换成4.5.9的版本是正常，5.2.2不行，jar包是正常导入

**Comment by looly** [comment]
这属于编译错误啊，不是包本身的问题。请检查你的项目，重新build
