### ISSUE TITLE
ServletUtil工具类中是否有判断当前request中的agent是android还是iOS的方法吗？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#781]
ServletUtil工具类中是否有判断当前request中的agent是android还是iOS的方法吗？

**Comment by looly** [comment]
UserAgentUtil.parse().getPlatform()

**Comment by joey-happy** [comment]
这个方法获取平台后 我还需要自己去判断具体是哪个平台的。
有没有类似：https://github.com/steveswinsburg/mobile-detect 这里的方法
        UAgentInfo agentInfo = new UAgentInfo(userAgent, null);

        if (agentInfo.detectIos()) {
            response.sendRedirect("http://www.baidu.com");
            return;
        }

        if (agentInfo.detectAndroid()) {
            response.sendRedirect("http://www.sogou.com");
            return;
        }

**Comment by looly** [comment]
5.2.3增加相关方法。感谢。
