### ISSUE TITLE
注释错误，还是代码错误？

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#782]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.2
![Snipaste_2020-03-13_15-14-49](https://user-images.githubusercontent.com/41384519/76598623-39c7e200-653e-11ea-9ae7-73fe569baeb8.jpg)

**Comment by looly** [comment]
确实有这个问题。5.2.3修复此问题。
