### ISSUE TITLE
集合工具能否增加初始化List和Map的方法

### ISSUE THREAD

**Issue by david1025** [looly/hutool#788]
Java在使用集合框架的时候，会涉及到扩容的问题，扩容是比较消耗性能的。比如我知道我要创建一个长度为100的map，但是我不能直接new HashMap（100），负载因子是0.75，到了75个就会扩容。所以能否提供一个这样的方法

**Comment by hallkk** [comment]
`new HashMap(133)` ?

自己计算一个值呢

**Comment by david1025** [comment]
自己每次计算就比较麻烦，所以说能不能提供一个自动计算的方法。google工具类就有那个方法，但是不想为了这一个方法再引入一个工具类。

**Comment by looly** [comment]
MapUtil.newHashMap()即可。
