### ISSUE TITLE
FileTypeUtil未关闭流导致文件占用无法删除

### ISSUE THREAD

**Issue by majianle** [looly/hutool#79]
今天使用了FileTypeUtil类判断文件类型后，执行删除文件操作，执行失败，原因是文件被占用，发现占用的是java.exe。本来怀疑是自己代码有问题，后来尝试将FileTypeUtil的使用去掉，文件正常删除。
初步判定是FileTypeUtil读取文件后未关闭。

FileTypeUtil文件中，此代码
public static String getType(File file) throws IORuntimeException {
		return getType(IoUtil.toStream(file));
}

没有对输入流关闭导致

尝试将代码改成

 public static String getType(File file) throws IORuntimeException {
        FileInputStream inputStream = IoUtil.toStream(file);
        String type = getType(inputStream);
        IoUtil.close(inputStream);
        return type;
 }
后执行，判断后文件不再提示被占用，能够正常删除。

再次感谢分享这么方便的工具。

**Comment by looly** [comment]
bug确认，感谢意见~~
