### ISSUE TITLE
BeanPath expression map取值问题

### ISSUE THREAD

**Issue by lhaopeng** [looly/hutool#790]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.2.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
BeanPathTest.java

@Test
public void getMapTest () {
	BeanPath pattern = BeanPath.create("userInfo[id, photoPath]");
	Map<String, Object> result = (Map<String, Object>)pattern.get(tempMap);
	Assert.assertEquals(1, result.get("id"));
	Assert.assertEquals("yx.mm.com", result.get("photoPath"));
}
```

2. 堆栈信息
java.lang.NullPointerException

3、问题原因：
![image](https://user-images.githubusercontent.com/35865779/77030216-e7247500-69d8-11ea-9bf4-cd608f77dfe6.png)

**Comment by looly** [comment]
5.2.4修复此问题，感谢。
