### ISSUE TITLE
ProxyUtil是否有生成某个类的代理类？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#791]
已存在接口如下：
	public static <T> T newProxyInstance(InvocationHandler invocationHandler, Class<?>... interfaces) {
		return newProxyInstance(ClassUtil.getClassLoader(), invocationHandler, interfaces);
	}

期望接口：
    	public static <T> T newProxyInstance(InvocationHandler invocationHandler, Class<?>... parentClass) {
		//parentClass是一个普通类 非接口
	}

**Comment by looly** [comment]
https://www.hutool.cn/docs/#/aop/%E5%88%87%E9%9D%A2%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7-ProxyUtil

需要引入cglib才行。

**Comment by joey-happy** [comment]
我想实现的功能入下：
//生成动态代理类
                Enhancer enhancer = new Enhancer();
                //设置代理目标
                enhancer.setSuperclass(JPlayModel.class);
                //设置单一回调对象，在调用中拦截对目标方法的调用

                //设置类加载器
                enhancer.setClassLoader(JPlayModel.class.getClassLoader());
                enhancer.setCallback(new InvocationHandler() {
                    @Override
                    public Object invoke(Object obj, Method method, Object[] objects) throws Throwable {
                        String methodName = method.getName();
                        if (methodName.equals("equals")) {
                            // Only consider equal when proxies are identical.
                            return (obj == objects[0]);
                        } else if (methodName.equals("hashCode")) {
                            // Use hashCode of proxy.
                            return System.identityHashCode(obj);
                        }
//                    else if (methodName.equals("toString")) {
//                        return this.objectFactory.toString();
//                    }

                        HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();

                        JPlayModel model = new JPlayModel();
                        model.setName(RandomUtil.randomString(10));

                        return method.invoke(model, objects);
                    }
                });

我不想传入aspect这个实现 因为我要在invoke的时候做一些操作

**Comment by joey-happy** [comment]
//生成动态代理类
                Enhancer enhancer = new Enhancer();
                //设置代理目标
                enhancer.setSuperclass(JPlayModel.class);
                //设置单一回调对象，在调用中拦截对目标方法的调用

                //设置类加载器
                enhancer.setClassLoader(JPlayModel.class.getClassLoader());
                enhancer.setCallback(new InvocationHandler() {
                    @Override
                    public Object invoke(Object obj, Method method, Object[] objects) throws Throwable {
                        String methodName = method.getName();
                        if (methodName.equals("equals")) {
                            // Only consider equal when proxies are identical.
                            return (obj == objects[0]);
                        } else if (methodName.equals("hashCode")) {
                            // Use hashCode of proxy.
                            return System.identityHashCode(obj);
                        }
                        return method.invoke(model, objects);
                    }
                });

工具类中需要传入aspect 我不想传入这个参数 我想在操作invoke的时候 做一些操作

**Comment by joey-happy** [comment]
public interface Aspect 这个接口定义了 before  after方法 不满足我的要求 我想在invoke的时候处理一些事情

**Comment by joey-happy** [comment]
public interface Aspect 这个接口定义了 before after方法 不满足我的要求 我想在invoke的时候处理一些事情

能否把 invoke方法放开 子类可以自己复写这个方法？？？

**Comment by joey-happy** [comment]
public static T newProxyInstance(InvocationHandler invocationHandler, Class<?>... parentClass) {
//parentClass是一个普通类 非接口
}

通过某个类 生成这个类的代理对象 而不是我传一个已经存在的对象当参数 

类似如下功能：
                Enhancer enhancer = new Enhancer();
                enhancer.setSuperclass(JPlayModel.class);
                enhancer.setClassLoader(JPlayModel.class.getClassLoader());
                enhancer.setCallback(new InvocationHandler() {
                    @Override
                    public Object invoke(Object obj, Method method, Object[] objects) throws Throwable {
                        String methodName = method.getName();
                        if (methodName.equals("equals")) {
                            return (obj == objects[0]);
                        } else if (methodName.equals("hashCode")) {
                            return System.identityHashCode(obj);
                        }

                        return method.invoke(model, objects);
                    }
                });

              return (JPlayModel)enhancer.create();

最后生成一个代理实例对象

**Comment by joey-happy** [comment]
public static T newProxyInstance(InvocationHandler invocationHandler, Class<?>... parentClass) {
//parentClass是一个普通类 非接口
}

通过某个类 生成这个类的代理对象 而不是我传一个已经存在的对象当参数

类似如下功能：
Enhancer enhancer = new Enhancer();
enhancer.setSuperclass(JPlayModel.class);
enhancer.setClassLoader(JPlayModel.class.getClassLoader());
enhancer.setCallback(new InvocationHandler() {
     @override
     public Object invoke(Object obj, Method method, Object[] objects) throws Throwable {
              String methodName = method.getName();
              if (methodName.equals("equals")) {
                  return (obj == objects[0]);
             } else if (methodName.equals("hashCode")) {
                  return System.identityHashCode(obj);
             }
                return method.invoke(model, objects);
             }
      });

return (JPlayModel)enhancer.create(); 
最后生成一个代理实例对象返回

**Comment by joey-happy** [comment]
我要的类似下面的接口：
public static T newProxyInstance(InvocationHandler invocationHandler, Class<?> parentClass) {
      Enhancer enhancer = new Enhancer();
      enhancer.setSuperclass(parentClass.class);
      enhancer.setClassLoader(parentClass.class.getClassLoader());
      enhancer.setCallback(new InvocationHandler() {
     @override
     public Object invoke(Object obj, Method method, Object[] objects) throws Throwable {
          String methodName = method.getName();
          if (methodName.equals("equals")) {
              return (obj == objects[0]);
           } else if (methodName.equals("hashCode")) {
               return System.identityHashCode(obj);
          }
              return method.invoke(model, objects);
        }
   });

   return (parentClass)enhancer.create();
}

代码只是例子 invoke方法可以暴露出来 方便复写或是回调 使用者可以自己控制invoke方法里的操作
