### ISSUE TITLE
BeanCopier 的valueProviderToBean 中field 为基本数据类型时,只匹配到set方法,没有匹配到get方法时,setterMethod.invoke(bean, value)方法设置值时会出现基本数据类型设置为null,出现错误

### ISSUE THREAD

**Issue by chengzichen** [looly/hutool#797]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.3（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
BeanCopier 的valueProviderToBean 中field 为基本数据类型时,只匹配到set方法,没有匹配到get方法时,setterMethod.invoke(bean, value)方法设置值时会出现基本数据类型设置为null,出现错误

1. 复现代码
  Page page1=new Page();
        Page page2=new Page();

        BeanUtil.toBean(page1, Page.class);

/**
 * 简单分页模型
 *
 * @author hubin
 * @since 2018-06-09
 */
public class Page<T>  {

    

  
    /**
     * 自动优化 COUNT SQL
     */
    private boolean optimizeCountSql = true;
    /**
     * 是否进行 count 查询
     */
    private boolean isSearchCount = true;

    public Page() {
    }

    @Override
    public boolean optimizeCountSql() {
        return optimizeCountSql;
    }

    @Override
    public boolean isSearchCount() {
        if (total < 0) {
            return false;
        }
        return isSearchCount;
    }

    public Page<T> setSearchCount(boolean isSearchCount) {
        this.isSearchCount = isSearchCount;
        return this;
    }

    public Page<T> setOptimizeCountSql(boolean optimizeCountSql) {
        this.optimizeCountSql = optimizeCountSql;
        return this;
    }
}

2. 堆栈信息
![image](https://user-images.githubusercontent.com/19171614/77170438-0238d700-6af6-11ea-9093-ec1c60e1c2d9.png)

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
嗯……也算问题也不算问题。

这个方法本质上调用了copyProperties方法，你可以：

```java
Page page2=new Page();
BeanUtil.copyPropertis(page1, page2, CopyOptions.create().setIgnoreNullValue(true));
```

5.2.4增加重载方法可以这么用:

```
BeanUtil.toBean(page1, Page.class, CopyOptions.create().setIgnoreNullValue(true));
```

**Comment by chengzichen** [comment]
我认为这是一个解决办法,但是我的思路是在其他人没踩坑之前是不知道,而单setterMethod.invoke(bean, value)方法不应该出现基本数据为null错误

**Comment by looly** [comment]
确实有道理，5.2.5吧，我在这里加个判断。

新的逻辑是：当用户未忽略null值，会给一个默认值，比如int默认值是0。

**Comment by chengzichen** [comment]
个人愚见,当用户未忽略null值,如果字段为基本数据类型,并且字段为空说明该字段获取是错误的或者没有设置get方法,这时候就应当放弃赋值可以直接跳过

**Comment by looly** [comment]
嗯，这样会有歧义：

如果目标对象已经有了一个值，源对象是null而没有选择忽略null，应该覆盖，否则保留原值会有歧义或者潜在问题。

**Comment by chengzichen** [comment]
还真是,保留原对象会有歧义,给默认值也存在类似的歧义
综合来讲
如果能在源对象获取值的这里做一些逻辑保证能获取正确的值,假如没有发现get方法时,是否考虑使用field.get(object)  (这样做不知道会影响性能,或者你有什么其他考虑),尽量避免setterMethod.invoke(bean, value)方法出现基本数据为null错误

**Comment by looly** [comment]
现在的逻辑是：如果用户没有提供getter方法，且字段是public的时候才去读字段的值。不然用户设置为private，且没有提供getter肯定是不想让外部读取，读了反而有问题。

现在逻辑较为合理：

1、用户没设置，给默认值，用户设置了CopyOptions.create().setIgnoreNullValue(true)跳过，这样兼具减少歧义和灵活性。
