### ISSUE TITLE
SqlRunner获取tableName为Null

### ISSUE THREAD

**Issue by huaijinwoyu** [looly/hutool#80]
RT,在使用DataSource的时候,用

` sqlRunner.find(
          Entity.create("表名").set("id", ">  30"));`

获取的List<Entity> 里面tableName=null, fieldNames=null 其他的字段有值.

**Comment by looly** [comment]
返回的Entity是无字段名列表和表名的。因为考虑到数据太大的话比较占空间，且没有实际意义。
