### ISSUE TITLE
redis 分组使用

### ISSUE THREAD

**Issue by zxccong** [looly/hutool#803]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
redis 分组怎么使用 RedisDS.create(group) ,group 应该填写什么参数，是group的名称还是
group名称应该在哪定义呢？

**Comment by looly** [comment]
https://www.hutool.cn/docs/#/db/NoSQL/Redis%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B0%81%E8%A3%85-RedisDS

group是redis.setting中的分组。

**Comment by zxccong** [comment]
group 是string类型的，应该填入什么呢，你的文档只有使用默认配置的例子，有没有使用group的案例

**Comment by looly** [comment]
```
[custom]
host = localhost
BlockWhenExhausted = true;
...
```

配置文件中custom就是分组名。
