### ISSUE TITLE
使用SqlRunner.FindAll转型失败

### ISSUE THREAD

**Issue by huaijinwoyu** [looly/hutool#81]
使用SqlRunner.FindAll转型失败

`List<T> findAll(Entity where, Class<T> beanClass)`

转型没报错,但是使用时会提示ClassCaseExcepiton 错误.

**Comment by huaijinwoyu** [comment]
`Cannot cast 'com.xiaoleilu.hutool.db.handler.BeanListHandler' to 'java.lang.String[]'`

**Comment by looly** [comment]
List<T> findAll(Entity where, Class<T> beanClass) 只是针对一条数据转为Bean设立的，因此并不支持java.lang.String[]。如果需要返回String[]或者Object[]，请自行实现RsHandler。
