### ISSUE TITLE
JSON设置了排序无效，使用的是maven最新版本的hutool

### ISSUE THREAD

**Issue by Andy095** [looly/hutool#813]
JSON设置了排序无效，使用的是maven最新版本的hutool
![Snipaste_2020-03-29_21-13-29](https://user-images.githubusercontent.com/41384519/77850018-55034480-7202-11ea-8d87-175aec9b8dcf.png)

**Comment by looly** [comment]
必须在构造时候设置是否排序：

```java
JSONObject(int capacity, boolean isOrder)
```
