### ISSUE TITLE
http get 不带参数请求报错（需设置参数编码）

### ISSUE THREAD

**Issue by King-Love** [looly/hutool#817]
### 版本情况

JDK版本：    java version "1.8.0_192"
hutool版本： 5.0.3（最新问题仍在）

### 问题描述（包括截图）
http get方法不带参数请求报错，需设置参数编码（encodeUrlParams=true）

图片无法上传
cn.hutool.http.HttpUtil.java文件encodeParams（）方法 460行
注释写的是无URL，错了。应该是无Params即无参数
所以应该是：urlPart = paramsStr;

**Comment by looly** [comment]
确实忽略了单独URL的情况，5.2.6修复此问题，感谢。
