### ISSUE TITLE
通过读取JSON文本串解析JSONObject对象，JSON顶层有序，其他层无序

### ISSUE THREAD

**Issue by tsye** [looly/hutool#818]
### 版本情况

JDK版本：    java version "1.8.0_51"
hutool版本： 5.2.5【包括4.4.0】

### 问题描述（包括截图）

1. 复现代码

```java
JSONObject jsonObject = new JSONObject("{'b':'1','a':{'b':'3','a':'4'}}",true);
```

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
![hutool_bug_顶层有序，其他无序](https://user-images.githubusercontent.com/16408279/78500477-357f9500-7789-11ea-82bb-fe4d9d710adf.png)

**Comment by looly** [comment]
5.3.0修复此问题。
