### ISSUE TITLE
建议为hutool.dfa加入白名单和敏感字替换功能

### ISSUE THREAD

**Issue by BoscoL** [looly/hutool#819]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
试用了一下hutool.dfa，发现这工具提供的API还不够全面，存在敏感字误判，缺少敏感字替换功能，希望能加上。

1. 复现代码

```java
	public static void main(String[] args) {
		WordTree tree = new WordTree();
		tree.addWord("口交");
		
		String match = tree.match("路口交通已恢复！");
		
		System.out.println(match);
	}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
使用String.replace替换关键字即可。没有替换功能。

白名单不知道如何加，比如这个词，那加哪个为白名单？
