### ISSUE TITLE
xmlUtil issue

### ISSUE THREAD

**Issue by hellosx** [looly/hutool#820]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
使用xmlUtil

Map<String, Object> map = MapBuilder.create(new HashMap<String, Object>())
                .put("Town",  CollUtil.newArrayList(town1, town2))
                .build();
Document doc = XmlUtil.mapToXml(map, "City");

输出：
<City>
    <Town>
        <name>jojo</name>
        <age>1991</age>
        <name>kiko</name>
        <age>1988</age>
    </Town>
</City>

期望：
<City>
    <Town>
        <name>jojo</name>
        <age>1991</age>
    </Town>
    <Town>
        <name>kiko</name>
        <age>1988</age>
    </Town>
</City>

**Comment by looly** [comment]
5.3.0修改如下：

```java
Map<String, Object> map = MapBuilder.create(new LinkedHashMap<String, Object>())
		.put("Town", CollUtil.newArrayList("town1", "town2"))
		.build();

Document doc = XmlUtil.mapToXml(map, "City");
Console.log(XmlUtil.toStr(doc, true));
```

结果：

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<City>
  <Town>town1</Town>
  <Town>town2</Town>
</City>
```
