### ISSUE TITLE
Do cn.hutool:hutool-core dependency support Java 11?

### ISSUE THREAD

**Issue by asdf913** [looly/hutool#826]
### 版本情况

JDK版本：   
`java 11.0.6 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)`

hutool版本： 5.2.5

### 问题描述（包括截图）

1. 复现代码

The below error message is found for `mvn clean package` command
`
package cn.hutool.core.swing.clipboard is not visible
`

Also, the */META-INF/MANIFEST.MF* file in *hutool-core-5.2.5.jar* does not define *Automatic-Module-Name*.
Are there any workaround to solve the problem?

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
JDK11没有适配兼容（jdk9及其以上都没兼容测试）

默认的unamed module应该是都加载才对，至于not visible问题，应该是缺包？
