### ISSUE TITLE
有多个表格时，列排序功能有bug

### ISSUE THREAD

**Issue by lf78204490** [looly/hutool#828]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

当一个excel中有多个表格时，即使每写一个表格后调用了writer.clearHeaderAlias(); 
在对后面的表格添加别名writer.addHeaderAlias();进行列排序就不会正常排序了。

看源码应该是在调用writer.clearHeaderAlias();时没有清除 aliasComparator 引起的。

**Comment by looly** [comment]
setSheet方法会自调用reset方法，清除aliasComparator，紧接着调用clearHeaderAlias即可清除别名。

标准你的写入应该是这样的：

```java
ExcelWriter writer = ExcelUtil.getWriter(path);
writer.addHeaderAlias(key1, value1);
writer.addHeaderAlias(key2, value2);
writer.write(rows, true);

//表2
writer.setSheet("表2");
writer.clearHeaderAlias();
writer.addHeaderAlias(key11, value11);
writer.addHeaderAlias(key12, value12);
writer.write(rows, true);

...
```
