### ISSUE TITLE
sm2 验签

### ISSUE THREAD

**Issue by youzhagui2006** [looly/hutool#829]
sm2 签名和验签 在 hutool （5.2.5 版本）

String d = "FAB8BBE670FAE338C9E9382B9FB6485225C11A3ECB84C938F10F20A93B6215F0";
String x = "9EF573019D9A03B16B0BE44FC8A5B4E8E098F56034C97B312282DD0B4810AFC3";
String y = "CC759673ED0FC9B9DC7E6FA38F0E2B121E02654BF37EA6B63FAF2A0D6013EADF";

String data = "434477813974bf58f94bcf760833c2b40f77a5fc360485b0b9ed1bd9682edb45";
String id = "31323334353637383132333435363738";

final SM2 sm2 = new SM2(d, x, y);

final String sign = sm2.signHex(data, id) （这边生成的长度是71字节）
而网页 https://i.goto327.top/CryptTools/SM2.aspx?tdsourcetag=s_pctim_aiomsg 签名生成长度是64字节。导致两边不能互为签名和验签。

**Comment by youzhagui2006** [comment]
昨天在 我们同事的帮忙下解决了 。
1. 使用基于 hutool 库的sm2  生成的签名是 70 多字节 
转化规则
长度=140   头减 4字节
长度=142   头减 5字节
长度=144   头减 5字节
然后取32字节  + 尾部 32字节   后 放到网页进行验签 

2. 网页生成签名的验签 ： 使用SM2SignHardToSoft 转成 70多字节 再验签
public static String SM2SignHardToSoft(String hardSign) {
byte[] bytes = HexUtil.decodeHex(hardSign);
byte[] r = new byte[bytes.length / 2];
byte[] s = new byte[bytes.length / 2];
System.arraycopy(bytes, 0, r, 0, bytes.length / 2);
System.arraycopy(bytes, bytes.length / 2, s, 0, bytes.length / 2);
ASN1Integer d_r = new ASN1Integer(byteConvertInteger(r));
ASN1Integer d_s = new ASN1Integer(byteConvertInteger(s));
ASN1EncodableVector v2 = new ASN1EncodableVector();
v2.add(d_r);
v2.add(d_s);
DERSequence sign = new DERSequence(v2);

String result = null;
try {
result = HexUtil.encodeHexStr(sign.getEncoded());
} catch (IOException e) {
logger.error(e.getMessage());
throw new RuntimeException(e);
}
//SM2加密机转软加密编码格式
//return SM2SignHardKeyHead+hardSign.substring(0, hardSign.length()/2)+SM2SignHardKeyMid+hardSign.substring(hardSign.length()/2);
return result;
}

public static BigInteger byteConvertInteger(byte[] b) {
if (b[0] < 0) {
byte[] temp = new byte[b.length + 1];
temp[0] = 0;
System.arraycopy(b, 0, temp, 1, b.length);
return new BigInteger(temp);
}
return new BigInteger(b);
}

**Comment by looly** [comment]
太感谢了，这个我一直没有搞定。

**Comment by looly** [comment]
其实不用这么麻烦，发现bc库的SM2Signer支持encoding的切换，下个版本5.3.1可以这么用：

```java
final SM2 sm2 = new SM2(d, x, y);
sm2.usePlainEncoding();
```

这样签名后的值就是64位的。
