### ISSUE TITLE
HttpUtil.get()是否应该从方法级别抛出异常

### ISSUE THREAD

**Issue by Git950715** [looly/hutool#834]
### 版本情况

hutool版本： 5.2.3

### 问题描述

使用HttpUtil.get()请求设置超时时间如果超时会使程序异常，中断线程处理。是否应该在方法增加throws Exception来提醒使用者做方法的异常处理。

![11111](https://user-images.githubusercontent.com/22900789/79522865-66b46b00-808f-11ea-992f-84775fcd7ab1.png)

**Comment by looly** [comment]
自行try catch即可。这是个Runtime异常。
