### ISSUE TITLE
json继承JSONDeserializer自定义配置不生效

### ISSUE THREAD

**Issue by kyxuas** [looly/hutool#836]
### 版本情况

JDK版本：   1.8
hutool版本： 5.2.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

`` @Test
    public void deserializeTest() {
        String jsonStr = "{\"customName\":\"testName\"}";
        CustomBean bean = JSONUtil.parseObj(jsonStr).toBean(CustomBean.class);
        System.out.println(bean);
    }

    @ToString
    public static class CustomBean implements JSONDeserializer<CustomBean> {
        public String name;
        public String b;
        public Date date;
        
        @Override
        public CustomBean deserialize(JSON json) {
            CustomBean customBean = new CustomBean();
            customBean.name = ((JSONObject)json).getStr("customName");
            return customBean;
        }
    }
```
2. 
CogradientAggregationServiceTest.CustomBean(name=null, b=null, date=null)

**Comment by looly** [comment]
需要调用：

```java
JSONUtil.putDeserializer(CustomBean.class, new CustomBean());
```
