### ISSUE TITLE
FileUtil.rename给文件重命名后通过file.getName()获取的文件名字符串尾多了一个点"."

### ISSUE THREAD

**Issue by nemowang** [looly/hutool#839]
### 版本情况

JDK版本：    1.8.0_102
hutool版本： 5.3.1

### 问题描述（包括截图）

1. 复现代码
```
File file = FileUtil.rename(uploadFile, System.currentTimeMillis() + fileName.toString(), true, true);
```
![image](https://user-images.githubusercontent.com/10138559/79744258-9d60de80-8338-11ea-9f3c-19460261aa4d.png)
原文件名：E:\pics\1587380213334
重命名后通过file.getName()获取的文件名：E:\pics\1587380217907微信图片airplane.jpg.
最后多了一个点"."
去到文件夹看这个文件名称正常，没有这个点。

**Comment by looly** [comment]
5.3.2修复此问题，感谢。

是由于你原来的文件没有扩展名，拼接错误导致的。
