### ISSUE TITLE
使用Setting读取配置文件没法获取配置内容

### ISSUE THREAD

**Issue by floydbaby** [looly/hutool#846]
### 版本情况

JDK版本：    openjdk_1.8
hutool版本： 5.2.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/42885710/79968556-daf17300-84c2-11ea-8af4-4f53cab06dba.png)

1. 复现代码

```java
public class SettingTest {

    public static void main(String[] args) {
        getSetting();
    }

    public static void getSetting(){
        Setting setting = new Setting("example.setting");
        System.out.println(setting.keySet().size());
    }

}

无法获取到文本内容
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
请确定example.setting在classcpath中存在。
