### ISSUE TITLE
HttpUtil工具，Url带参的问题

### ISSUE THREAD

**Issue by lsw1990** [looly/hutool#850]
### 版本情况
5.3.1
JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）
是的
### 问题描述（包括截图）
https://mp.weixin.qq.com/s?__biz=MzI5NjkyNTIxMg==&amp;mid=100000465&amp;idx=1&amp;sn=1044c0d19723f74f04f4c1da34eefa35&amp;chksm=6cbda3a25bca2ab4516410db6ce6e125badaac2f8c5548ea6e18eab6dc3c5422cb8cbe1095f7
类似上述请求参数，不能有效的正确得到解析，导致请求回来预期的结果不一致 (能正常请求)，暂未发现那地方问题，和jsoup请求的比对得出的结论

1. 复现代码

```java
HttpUtil.get(url)
```

2. 堆栈信息
无

**Comment by looly** [comment]
5.3.3修复此问题，感谢。

你可以先手动把`&amp;`替换为`&`即可。
