### ISSUE TITLE
ImgUtil.createImage无法设置透明色作为背景

### ISSUE THREAD

**Issue by shaoneng111** [looly/hutool#851]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
源代码：
Color backgroundColor = new Color(255,255, 255, 0);
ImgUtil.createImage(“abc”, new Font("Microsoft YaHei", Font.PLAIN, posterPosition.getNicknameFontHeight()), backgroundColor, Color.BLACK, imageOutputStream);
目的是想生成背景色为透明的，结果生成了背景色为黑色的！

2. 堆栈信息
通过追踪hutool源代码发现问题如下：
// 创建图片
BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_BGR);
此处使用TYPE_INT_BGR，忽略了alpha，请问是如何考虑的，导致无法使用透明背景色，
通过使用TYPE_INT_ARGB可以解决此问题。
请问此处使用TYPE_INT_BGR是bug还是有其他考虑？

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.3.3修改此方法，感谢。
