### ISSUE TITLE
字符串转JSON后将html的标签中的斜杠使用了反斜杠进行转义

### ISSUE THREAD

**Issue by AceCandy** [looly/hutool#852]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.2

### 问题描述（包括截图）
字符串转json之后，类似</div>这样的标签会变成<\\/div>，其它json包没有出现这样的情况，如果是为了防止注入，那是否可以设置一个开关，比如普通的是没有当前设定的，打开防注入开关之后再有这种标签转义。

1. 复现代码

```java
public static void main(String[] args) {
        String s = "{\"a\":\"<div></div>\"}";
        Console.log(s);
        Console.log(JSONUtil.parseObj(s));
        Console.log(com.alibaba.fastjson.JSONObject.parseObject(s));
        Console.log(new JsonParser().parse(s).getAsJsonObject());
    }
```

2. 堆栈信息
无
3. 测试涉及到的文件（注意脱密）
![image](https://user-images.githubusercontent.com/6278583/80270801-b88f6d80-86ed-11ea-9b90-954629151648.png)

**Comment by looly** [comment]
这是为了避免在HTML中script脚本注入而专门家的转义。

见：

https://www.thorntech.com/2012/07/4-things-you-must-do-when-putting-html-in-json/

https://stackoverflow.com/a/4180424

> 注意：
> 5.3.3 我会去掉这个校验。
