### ISSUE TITLE
5.0.4以后版本分页查询有问题。

### ISSUE THREAD

**Issue by zabzd999** [looly/hutool#855]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.2（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

Db.use().page(queryLimit.getFields(),entity, new Page(page,pageSize));
分页查询。最后打印的日志是这样的：
select * from table limit 20 offset 20
应该是这样的：select * from table limit 20 offset 0
分页查询默认应该从第0页开始，现在从第一页开始了。会漏掉前20行数据

**Comment by looly** [comment]
默认0表示第一页，你此处应该是：

page = 0，offset才是0。

```java
List<Entity> page0 = Db.use().page(Entity.create("user"), 0, 3);
```

![image](https://user-images.githubusercontent.com/1432613/80662339-9ae24f80-8ac3-11ea-8c98-4effeed4e85a.png)

**Comment by zabzd999** [comment]
好的。谢谢回复。我看之前低版本第一页是从1开始的。不知道什么时候改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Golden Looly"<notifications@github.com&gt;; 
发送时间: 2020年4月30日(星期四) 上午9:19
收件人: "looly/hutool"<hutool@noreply.github.com&gt;; 
抄送: "李金山"<985379560@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [looly/hutool] 5.0.4以后版本分页查询有问题。 (#855)





 
默认0表示第一页，你此处应该是：
 
page = 0，offset才是0。
 List<Entity&gt; page0 = Db.use().page(Entity.create("user"), 0, 3);

**Comment by looly** [comment]
新版本做了修改，不过可以设置。

```java
PageUtil.setFirstPageNo(1);
```

**Comment by LouisGuo** [comment]
> 新版本做了修改，不过可以设置。
> 
> ```java
> PageUtil.setFirstPageNo(1);
> ```

海勒姆定律：当一个API有足够多的用户时，在约定中你所承诺的已不重要：所有在你系统里被观察到的行为都会被一些用户所依赖。
