### ISSUE TITLE
提问，如果我只想读取定义好的Excel模板，往里面填数据怎么做到导出保留原格式？

### ISSUE THREAD

**Issue by kangqing** [looly/hutool#857]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
嗯……Hutool其实不支持模板导出的。

**Comment by kangqing** [comment]
ok，谢谢回答，已经查到不能模板导出了

**Comment by xwayway** [comment]
> 嗯……Hutool其实不支持模板导出的。

有考虑增加模板导出吗，其实感觉模板导出需求还是挺多的

**Comment by looly** [comment]
@xwayway 暂时不考虑，考虑EasyPOI
