### ISSUE TITLE
IDCardUtil工具类针对18位身份证号没有校验cityCode是否合法，15位有校验

### ISSUE THREAD

**Issue by fantasyzj** [looly/hutool#859]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： v5-master（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
IDCardUtil工具类针对18位身份证号没有校验cityCode是否合法，15位有校验。

**Comment by looly** [comment]
5.3.3加入，感谢。
