### ISSUE TITLE
xml 转换有问题

### ISSUE THREAD

**Issue by daivGithub** [looly/hutool#865]
### 版本情况

JDK版本：    jdk 1.8.0_144
hutool版本： 5.3.3
### 问题描述（包括截图）

1. 复现代码

AccountConfirmInfo info=new AccountConfirmInfo();
		info.setReqCode("1111");
		info.setAccountName("账户名称");
		info.setAccountNumber("1234");
		info.setBankCode("00001");
		info.setCreateTime("20200503102222");
		info.setOperator("cz");
		info.setProjectCode("123");
		info.setResult(0);
		info.setType(0);
		String xml= XmlUtil.format(XmlUtil.beanToXml(info,""));
		System.out.println(xml);
		//转bean 失败 null
		XmlUtil.xmlToBean(XmlUtil.parseXml(xml),AccountConfirmInfo.class);
图片是bean
![微信截图_20200509155310](https://user-images.githubusercontent.com/10653456/81467727-3898f580-920d-11ea-967f-73a3352deb16.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.3.4修复此问题，感谢。
