### ISSUE TITLE
ExcelWriter.autoSizeColumnAll列宽度自适应

### ISSUE THREAD

**Issue by moxia** [looly/hutool#866]
数字和英文字母的列自适应没问题，中文的列没有实现宽度自适应，查了下，应该是POI里就没处理中文列的宽度自适应，希望hutool可以优化下这块。
https://www.iambigboss.top/post/43718_1_1.html

**Comment by looly** [comment]
中文没法解决，博客中的方法没法判断单元格的中文长度。

**Comment by Jean-Jacques-Nuoan** [comment]
博客打不开
