### ISSUE TITLE
默认4位验证码？5位

### ISSUE THREAD

**Issue by bahuwang** [looly/hutool#87]
路径 : hutool/hutool-captcha/src/main/java/cn/hutool/captcha/LineCaptcha.java
// -------------------------------------------------------------------- Constructor start
	/**
	 * 构造，默认4位验证码，150条干扰线
	 * 
	 * @param width 图片宽
	 * @param height 图片高
	 */
	public LineCaptcha(int width, int height) {
		this(width, height, 5, 150);
	}

**Comment by looly** [comment]
感谢意见。下个版本修复注释
