### ISSUE TITLE
cn.hutool.core.date.DateTime 注释信息错误

### ISSUE THREAD

**Issue by anaer** [looly/hutool#877]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

cn.hutool.core.date.DateTime 注释信息错误

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

![image](https://user-images.githubusercontent.com/4637100/82215433-004e9100-994a-11ea-9b07-128bae76c34b.png)

**Comment by looly** [comment]
5.3.6修复注释，感谢。
