### ISSUE TITLE
Hutool Http工具类默认加的Header头导致请求接口无法正常响应400

### ISSUE THREAD

**Issue by xiaosTyy** [looly/hutool#879]
### 版本情况

JDK版本：    1.8
hutool版本： 5.3.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
请问下，作者当时为什么要默认加这些请求头？
Accept头导致400的请求响应，会返回404
![image](https://user-images.githubusercontent.com/39477475/82424886-5e998200-9ab8-11ea-812a-84387185b1d5.png)

1. 复现代码
![image](https://user-images.githubusercontent.com/39477475/82424947-71ac5200-9ab8-11ea-9f37-30e65f19493a.png)

```java
返回响应404
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
你可以手动指定header("Accept", "*/*")。

默认头是为了模拟浏览器的默认请求头。
