### ISSUE TITLE
关于[将Map形式的Form表单数据转换为Url参数形式，不做编码]疑问

### ISSUE THREAD

**Issue by serical** [looly/hutool#880]
### 版本情况

JDK版本：    java version "11.0.7" 2020-04-14 LTS
hutool版本： 5.3.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
cn.hutool.http.HttpUtil#toParams(java.util.Map<java.lang.String,?>) 这个方法注释说的是不做编码, 但是结果是进行了URL编码的, 不知道是不是我理解有误。

1. 复现代码

```java
    @Test
    public void testUrl() {
        Map<String, String> params = Maps.newHashMap();
        params.put("a", "a");
        params.put("b", " ");
        params.put("c", "你好");
        params.put("d", "");
        System.out.println(HttpUtil.toParams(params));
    }
```

2. 堆栈信息
输出:
```bash
a=a&b=+&c=%E4%BD%A0%E5%A5%BD&d=
```

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
注释错误。感谢。
