### ISSUE TITLE
BeanUtil.copyProperties执行速度问题

### ISSUE THREAD

**Issue by wuuJiawei** [looly/hutool#881]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.5

### 问题描述

1. 复现代码

[HutoolBeanUtilDemo.java](https://github.com/wuuJiawei/springboot-demos/blob/master/bean-copy-test/src/main/java/xyz/easyboot/demo/HutoolBeanUtilDemo.java)

2. 测试说明与报告
[https://www.easyboot.xyz/posts/14639/#测试报告](https://www.easyboot.xyz/posts/14639/#测试报告)

![测试报告](https://cdn.easyboot.xyz/bean-copy-record-2.png)

`Hutool BeanUtil`在执行次数较少的场景下比较快，但测试10000000次时出现了明显的速度问题

3. 正常使用过程中不会出现连续执行10000000次的情况，但觉得有必要告知

**Comment by looly** [comment]
十分感谢你的性能测试。

cglib修改字节码所以很快，Hutool依旧使用传统的反射完成，执行较多性能差也是一定的。

稍后我研究下其它几个源码，争取优化一下。
