### ISSUE TITLE
农历时间能不能返回时间格式

### ISSUE THREAD

**Issue by zqxsober** [looly/hutool#886]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
什么是时间格式?ChineseDate.toStringNormal不行？

**Comment by zqxsober** [comment]
哦~  抱歉没看到这个方法，多谢了
在 2020年5月26日 +0800 PM3:06，Golden Looly <notifications@github.com>，写道：
