### ISSUE TITLE
获得文件类型时出错

### ISSUE THREAD

**Issue by Rayonlar** [looly/hutool#888]
- #### 问题描述：docx文件获得扩展名为xls，这个文件是一个加密的docx文件，估计应该是加密的问题
- #### hutool版本：5.3.5
- #### jdk版本：1.8.0_241
- #### 操作系统：MacOS 10.15.4
- #### 问题复现：https://github.com/Disciplining/hutool-issue.git

**Comment by looly** [comment]
docx等获取不可参考。请使用扩展名判断把。
