### ISSUE TITLE
超时缓存使用的线程池大小强制为16且无法定义,大多数时间空载

### ISSUE THREAD

**Issue by Dustone-JavaWeb** [looly/hutool#890]
### 版本情况

JDK版本：    8u201
hutool版本： 5.2.3

### 问题描述（包括截图）

1. 复现代码
![image](https://user-images.githubusercontent.com/35624201/82970017-ce50c500-a002-11ea-988f-d812ee81841f.png)
![image](https://user-images.githubusercontent.com/35624201/82970517-0b1cbc00-a003-11ea-9fb6-382f39b20b90.png)
建议改为可以使用公共线程池或指定大小
2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by looly** [comment]
5.3.6改为1。感谢。
