### ISSUE TITLE
当查询条件携带中文时，返回结果集为空

### ISSUE THREAD

**Issue by AhHeadFloating** [looly/hutool#899]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.5

### 问题描述
当查询条件携带中文时，返回结果集为空
1. 复现代码

```java
String answerSql ="select * from user where name = '测试'";
List<Entity> answerResult = Db.use().query(answerSql);
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）
## db.setting文件

url = jdbc:mysql://localhost:3306/kong?useUnicode=true&characterEncoding=utf8&useSSL=false
user = root
pass =

showSql = true
formatSql = false
showParams = true
sqlLevel = debug

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
请检查mysql数据库编码是否为utf8，或者通过参数形式传入试下：

```java
Db.use().query("select * from user where name = ?", "测试");
```
