### ISSUE TITLE
验证码最后一个字符显示问题

### ISSUE THREAD

**Issue by Ikki-Dai** [looly/hutool#901]
### 版本情况

JDK版本：    openjdk_8_252
hutool版本： 5.3.6（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/16415439/83412560-df5b6500-a44c-11ea-8ae4-4de68f019a93.png)

验证码 最后一个字符有一定概率 显示不完全， 需要优化
1. 复现代码

```java
CaptchaUtil.createShearCaptcha(160,80,4,4)
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
字母是随机扭曲的，可能扭曲导致某些特殊字母看不清一部分。

这个不需要优化，也是一种防oci的方式之一。
