### ISSUE TITLE
DatePattern支持ISO8601_PATTERN:yyyy-MM-dd HH:mm:ss,SSS

### ISSUE THREAD

**Issue by sunsulei** [looly/hutool#904]
如题.
希望能扩充pattern.
![image](https://user-images.githubusercontent.com/19281052/83710998-a68ddc80-a654-11ea-8b2c-f071a4f43e15.png)
org.apache.log4j.pattern.DatePatternConverter

**Comment by looly** [comment]
5.3.8加入。
