### ISSUE TITLE
AES加密结果无法和网上工具加密匹配，请问我该如何设置

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#905]
您好，使用AES加密，代码如下

```java
  @Test
  public void test() {

    String k = "HEJUZKQhrS7ijRdN5wfq3A==";
    byte[] key = Base64.decode(k);
//    String k = "1c425464a421ad2ee28d174de707eadc";
//    byte[] key = HexUtil.decodeHex(k);

    // 构建
    SymmetricCrypto aes = new SymmetricCrypto("AES/CBC/PKCS5Padding", key);
    aes.setIv("1234567890123456".getBytes());

    String encryptHex = aes.encryptHex("123456");

    System.out.println(encryptHex);

  }
```

得出结果如下：
`aac44bf43028fa7a811625cd6821c425`

但是使用网上的AES机密工具，都无法匹配密文结果

使用AES/CBC/PKCS5Padding，设置偏移量，但是代码中运行的结果和网站工具加密的结果不一致，我想知道是哪个参数没配置对吗？感觉参数都是一样的，请帮忙解答，非常感谢。

工具网站：[http://tool.chacuo.net/cryptaes](http://tool.chacuo.net/cryptaes)

![image](https://user-images.githubusercontent.com/8787216/83822347-5457c480-a703-11ea-8d41-6a9b78862469.png)

**Comment by gpqhl0071** [comment]
![image](https://user-images.githubusercontent.com/8787216/83743089-ce009b80-a68c-11ea-952b-9537b976fa9f.png)

**Comment by gpqhl0071** [comment]
![image](https://user-images.githubusercontent.com/8787216/83743109-d658d680-a68c-11ea-91fe-291edb47bf27.png)

**Comment by looly** [comment]
```java
AES aes = new AES("CBC", "PKCS5Padding", "1234567890123456".getBytes(), "1234567890123456".getBytes());
String encryptHex = aes.encryptHex("123456");
System.out.println(encryptHex);
```

结果和你提供的网站一致。

![image](https://user-images.githubusercontent.com/1432613/83828946-6130e400-a714-11ea-9e85-106dc9b73c06.png)

![image](https://user-images.githubusercontent.com/1432613/83828952-668e2e80-a714-11ea-8dec-1d56831e7c5e.png)

你这里密码不能用base64直接传到网站去。

**Comment by gpqhl0071** [comment]
好用了，非常感谢
