### ISSUE TITLE
请问异常被底部代码捕获，我怎么正常trycatch自己处理呢？

### ISSUE THREAD

**Issue by Stefbing** [looly/hutool#907]
### 版本情况

JDK版本：    1.8.0_231
hutool版本：  5.3.2

### 问题描述（包括截图）

1. 复现代码

```
        /*此路径不存在此文件*/
        String path = System.getProperty("user.dir") + System.getProperty("file.separator") + "config.properties";
        try {
            Props props = new Props(path);
            Console.log("Properties: {}", props);
        }catch (Exception e){
            System.out.println("此路径下不存在此文件");
        }
```
2.问题描述
我想自己处理异常，可是被底层代码捕获了。请问有办法解决吗？
![catch不到](https://user-images.githubusercontent.com/49504435/83835500-8416c480-a723-11ea-8d6b-ea46ed5c22a3.png)

**Comment by looly** [comment]
这块打印成了日志，暂时无法捕获了，你可以自行判断File文件是否存在。

5.3.8修改此处逻辑，感谢。
