### ISSUE TITLE
hutool4.*版本是否持续更新和修复呢？

### ISSUE THREAD

**Issue by gpqhl0071** [looly/hutool#909]
您好，今天看到文档上说明，hutool5.*版本是不支持jdk1.7。

那么hutool4.*版本是否持续更新和修复呢？如果想用hutool新增的特性，是否支持呢？

![image](https://user-images.githubusercontent.com/8787216/84091610-8b8de480-aa27-11ea-9162-d35db357b784.png)

**Comment by looly** [comment]
4.x只是bug修复了，不再添加新特性。
