### ISSUE TITLE
FileTypeUtil.getType不能获取文件类型

### ISSUE THREAD

**Issue by gaowei7752003** [looly/hutool#91]
`FileTypeUtil获取文件类型的getType()方法为什么不能获取文件类型，一直返回null（windows使用的是4.0.6版本）：
`
File file = FileUtil.file("C:/Users/Administrator/Desktop/1.jpg");  

String type = FileTypeUtil.getType(file);   

Console.log(type);
`

**Comment by looly** [comment]
FileTypeUtil是根据文件流的前几个字符判定文件格式的。存在不准确的问题，后续会持续修复。十分感谢。
