### ISSUE TITLE
5.3.7版本提示：无法找到引入的 “poi-ooxml” 包

### ISSUE THREAD

**Issue by obiscr** [looly/hutool#912]
### 版本情况

JDK版本：    java version "1.8.0_211"
hutool版本： 5.3.7（目前是最新版本）

### 问题描述（包括截图）

目前我正在开发一款IDEA的插件，使用 DevKit 构建的环境，依赖是从 mvnrepository 下载的 jar 包 
放到了 lib 目录引入的，同时还引入了 `poi-ooxml-4.1.2.jar`。

![](https://ftp.bmp.ovh/imgs/2020/06/2b2738533738d288.jpg)

然后在项目开始使用

![](https://ftp.bmp.ovh/imgs/2020/06/86f4fb183e839c77.jpg)

但是出现了异常，信息如下

![](https://ftp.bmp.ovh/imgs/2020/06/aa82046b12767d6b.jpg)

 > 但是此时的 `poi-ooxml` 已经是 <b>4.1.2</b> 了

**Comment by looly** [comment]
是这样的：需要maven引入，有关联依赖的jar，都要放进去。
