### ISSUE TITLE
发现个bug

### ISSUE THREAD

**Issue by 531958737** [looly/hutool#913]
### 版本情况

JDK版本：    jdk 11.0.4
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1、方法写错了。
cn/hutool/core/collection/CollUtil.java   

if (isEmpty(coll2)) 
{
	return ListUtil.list(true, coll2); //issue 这里应该是coll1
}  

/**
	 * 计算集合的单差集，即只返回【集合1】中有，但是【集合2】中没有的元素，例如：
	 *
	 * <pre>
	 *     subtract([1,2,3,4],[2,3,4,5]) -》 [1]
	 * </pre>
	 *
	 * @param coll1 集合1
	 * @param coll2 集合2
	 * @param <T>   元素类型
	 * @return 单差集
	 */
public static <T> List<T> subtractToList(Collection<T> coll1, Collection<T> coll2) {

		if (isEmpty(coll1)) {
			return ListUtil.empty();
		}
		if (isEmpty(coll2)) {
			return ListUtil.list(true, coll2);
		}

		//将被交数用链表储存，防止因为频繁扩容影响性能
		final List<T> result = new LinkedList<>();
		Set<T> set = new HashSet<>(coll2);
		for (T t : coll1) {
			if (false == set.contains(t)) {
				result.add(t);
			}
		}
		return result;
	}

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
已合并:https://github.com/looly/hutool/pull/915
