### ISSUE TITLE
ResponseEntity转json少俩字段问题

### ISSUE THREAD

**Issue by anfree** [looly/hutool#916]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
org.springframework.http.ResponseEntity转json时，少了两个字段,"statusCode":"OK","statusCodeValue":200，用jackson转的时候有这两个字段。

1. 复现代码

```java
JSONUtil.parseObj(object, false, true).toStringPretty()

```

2. 堆栈信息
{
    "headers": {
    },
    "body": {
        
    }
}
3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by Andyfoo** [comment]
这应该不是bug，hutool只会处理有get/set方法的类，为了更安全

**Comment by looly** [comment]
jackson只是简单调用getXXX方法，hutool为了安全，双重判断getXXX和xxx字段是否统一且都存在，因此这里getStatusCode并没有解析。

**Comment by looly** [comment]
![Uploading image.png…]()
