### ISSUE TITLE
Validator类的isEmail返回值注释错误，应该是true为可用邮箱

### ISSUE THREAD

**Issue by spirit-unpredictable** [looly/hutool#918]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
注释错误

![image](https://user-images.githubusercontent.com/43667484/84368416-204f3880-ac08-11ea-909f-8ee96a3458c8.png)

**Comment by looly** [comment]
5.3.8修改，感谢。
