### ISSUE TITLE
似乎没有表单提交字节流的方式？

### ISSUE THREAD

**Issue by wudongyuan2017** [looly/hutool#92]
陷入既用hutool-http还要用httpclient的尴尬

**Comment by looly** [comment]
字节流提交使用
body方法，有byte[]参数的重载。

**Comment by wudongyuan2017** [comment]
public void postFile(FileChannel fc ,String url, long begin,long end) throws IOException {
		long bufferSize = end - begin + 1;
		MappedByteBuffer byteBuffer = fc.map(FileChannel.MapMode.READ_ONLY, begin, bufferSize);
		byte[] temp = new byte[(int) bufferSize];
		byteBuffer.get(temp);
		String reStr = "";
		try {
			HttpPost httppost = new HttpPost(url);
			MultipartEntityBuilder builder = MultipartEntityBuilder.create()
					.addBinaryBody("file", temp,ContentType.APPLICATION_OCTET_STREAM.withCharset("UTF-8"),"block")
					.addTextBody("bhash", DigestUtil.sha1Hex(temp),ContentType.TEXT_PLAIN.withCharset("UTF-8"));
			httppost.setEntity(builder.build());

			CloseableHttpResponse response = (CloseableHttpResponse) client.execute(httppost);

			int resStatu = response.getStatusLine().getStatusCode();

			if (resStatu == HttpStatus.SC_OK) {

				HttpEntity entity = response.getEntity();
				BufferedReader reader = new BufferedReader(new InputStreamReader(entity.getContent(), "UTF-8"));
				String line,tempStr = "";
				while ((line = reader.readLine()) != null) {
					tempStr += line;
				}
				JSONObject result = JSONUtil.parseObj(tempStr);
                                System.out.println(result);
				}
			}
			else {
				log.error(url + ": resStatu is " + resStatu);
			}
		}
		catch (Exception e) {
			log.error("http post throw Exception", e);
		}
	}

我说的是这样子的方式

**Comment by looly** [comment]
暂时没有很好的支持方法。sorry。
