### ISSUE TITLE
使用中文转拼音PinyinUtil.getFirstLetter("林海","") 首字母仅仅出来“l“

### ISSUE THREAD

**Issue by abs1285** [looly/hutool#921]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

使用中文转拼音PinyinUtil.getFirstLetter("林海","") 首字母仅仅出来“l“

**Comment by looly** [comment]
这个是Pinyin4j的一个bug导致的，分隔符失效导致首字母丢失。

**Comment by looly** [comment]
5.3.8我会加一些逻辑绕过这个bug，感谢。
