### ISSUE TITLE
提一个需求，关于Strutil.removeAll方法

### ISSUE THREAD

**Issue by xu1990119** [looly/hutool#923]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 最新版

### 问题描述（包括截图）

Strutil.removeAll方法只能删除一个字符串，我想要如下使用是没有对应方法的
比如，Strutil.removeAll("中国人民万岁"，“人民”，“万岁”)；//返回中国
是否可以加上此方法呢

**Comment by looly** [comment]
5.3.8加入，感谢。
