### ISSUE TITLE
MetaUtil.getTableMeta获取oracle元数据时comment 注释为null

### ISSUE THREAD

**Issue by mopoliujia** [looly/hutool#924]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.4（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
MetaUtil.getTableMeta获取oracle元数据时comment 注释为null

**Comment by vvizden** [comment]
oracle需要手动开启`comment`, `oracleConnection.setRemarksReporting(true)`.参考：[oracle docs](https://docs.oracle.com/database/121/JJDBC/oraperf.htm#JJDBC28785)

**Comment by looly** [comment]
这块的参数没有考虑。

5.3.8增加remarks参数支持，你可以在配置文件中增加：

```java
remarks = true
useInformationSchema = true
```

来激活Oracle对元数据的支持。
