### ISSUE TITLE
关于AOP功能的问题

### ISSUE THREAD

**Issue by lee723** [looly/hutool#928]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.8（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
1. aop是否考虑引入多Aspect的支持？目前只支持引入一个Aspect。
2. Aspect是否考虑支持方法级别的拦截？

**Comment by looly** [comment]
1、Aspect是个非常灵活的接口，你可以在before或者after中加入特定逻辑，完成多层拦截。
2、before和after方法中有Method对象，你可以通过判断方法名和参数，完成对特定方法的拦截。
