### ISSUE TITLE
public class Browser extends UserAgentInfo 是否有判断是微信扫码 还是 支付宝扫码的方法

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#934]
public class Browser extends UserAgentInfo 是否有判断是微信扫码 还是 支付宝扫码的方法

例如：boolean isWxPayScan  and boolean isAliPayScan

**Comment by looly** [comment]
这个没有判断，是使用头信息判断的么？

**Comment by joey-happy** [comment]
看其他代码判断 说是使用头信息判断的 
例如：https://blog.csdn.net/qq_25646191/article/details/80566425
![Uploading image.png…]()
