### ISSUE TITLE
关于雪花 终端ID 数据中心ID 生成的问题

### ISSUE THREAD

**Issue by maomao94** [looly/hutool#936]
您好，我们需要上到k8s当中去，pod 可变，雪花生成id 必须 指定终端ID 数据中心ID，能否提供一种自动计算这两个的方式，可以在k8s中运行

**Comment by looly** [comment]
这两个你得靠数据库或者相关分布式系统生成，hutool不能保证分布式下生成的这两个id不重复。

**Comment by maomao94** [comment]
> 这两个你得靠数据库或者相关分布式系统生成，hutool不能保证分布式下生成的这两个id不重复。

可以根据pod ip来计算吗，集群中的pod id 应该是不重复的

**Comment by looly** [comment]
> > 这两个你得靠数据库或者相关分布式系统生成，hutool不能保证分布式下生成的这两个id不重复。
> 
> 可以根据pod ip来计算吗，集群中的pod id 应该是不重复的

如果有内网公网区分这样很容易出问题。也容易重复。这个不应该工具来搞定，而应该是分布式调度来搞定。
