### ISSUE TITLE
使用bigWriter生成excel, 调用autoSizeColumnAll()方法无效

### ISSUE THREAD

**Issue by litown** [looly/hutool#939]
### 版本情况

JDK版本：    openjdk_8
hutool版本： 5.3.7

### 问题描述（包括截图）
使用bigWriter生成excel, 调用autoSizeColumnAll()方法无效

(bigWriter写完数据后再调用的autoSizeColumnAll(), excel数据全英文,无中文)

**Comment by looly** [comment]
考虑使用POI的WordToHtmlConverter，暂时没有封装。

**Comment by looly** [comment]
貌似和XSS机制有关，这个无能为力。
