### ISSUE TITLE
word 转成html 可以实现吗

### ISSUE THREAD

**Issue by sunhai1988** [looly/hutool#942]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
考虑使用POI的WordToHtmlConverter，暂时没有封装。
