### ISSUE TITLE
ZipUtil工具类 zip(OutputStream out, Charset charset, boolean withSrcDir, FileFilter filter, File... srcFiles) 方法里面 ZipOutputStream 没有 finish

### ISSUE THREAD

**Issue by xeyn** [looly/hutool#944]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.7

### 问题描述
   
ZipUtil工具类 的 zip(OutputStream out, Charset charset, boolean withSrcDir, FileFilter filter, File... srcFiles),  生成的zip文件无法打开, 提示"不可预料的压缩文件末端".  原因是该方法内生成的ZipOutputStream 没有调用 finish 方法.

1. 复现代码

            ```
            public static void main(String[] args) {
                String dir = "E:/workspaces/java/test";
                String zip = "E:/workspaces/java/test.zip";
                try (OutputStream out = new FileOutputStream(zip)){
                    //实际应用中, out 为 HttpServletResponse.getOutputStream
                    ZipUtil.zip(out, Charset.defaultCharset(), false, null, new File(dir));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            ```
2. 解决

          修改 zip(OutputStream out, Charset charset, boolean withSrcDir, FileFilter filter, File... srcFiles) 方法内

               zip(getZipOutputStream(out, charset), withSrcDir, filter, srcFiles);

               =>

               ZipOutputStream zout = getZipOutputStream(out, charset);
               zip(zout, withSrcDir, filter, srcFiles);
               zout.finish();  // 此处 zout 不能 close, 只能 finish

**Comment by looly** [comment]
5.3.9修复此问题。感谢。

**Comment by looly** [comment]
可能是压缩客户端的问题，我本地测试并没有遇到不可预料末端问题。不过以防万一，我会加上这个方法。
