### ISSUE TITLE
关于http请求的问题

### ISSUE THREAD

**Issue by kuaile1993** [looly/hutool#945]
### 版本情况

JDK版本：    jdk8
hutool版本： 5.3.5（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
![image](https://user-images.githubusercontent.com/52553619/86190805-f094b000-bb77-11ea-9b4f-5f59994438a7.png)
![image](https://user-images.githubusercontent.com/52553619/86190846-10c46f00-bb78-11ea-9e48-48e5c7242059.png)
httputil 掉用get方法的时候，时间长的话， 我这边的http调用会一直阻塞下去，不知道是什么原因，一开始是以为第三方系统不稳定，我这边没有设置超时，但是后来设置http的timeout后，运行几天后仍然阻塞了
1. 复现代码
请求时通过定时器调用 ，平均3秒调用一次，问题：在单线程里面调用，定时器阻塞。 在多线程里调用，线程全部阻塞后，停止调用，定时器在跑

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
我这边暂时无法确定问题：

1、看下是否为https请求
2、可否看下是否有死锁问题。
