### ISSUE TITLE
httpUtil post get 参数顺序问题

### ISSUE THREAD

**Issue by xchendeveloper** [looly/hutool#95]
有些场景需要使用前几个参数计算出签名后，将签名附在最后，用于服务端验证，这时对参数顺序有要求。
hutool现在的实现好像是hashmap。请问是否有支持？

**Comment by looly** [comment]
参数签名并非http的事情，参数是你自己控制，因此需要你自己写逻辑使用TreeMap排序后签名，你可以考虑使用`SecureUtil.signParams`方法对已有Map排序后签名。
