### ISSUE TITLE
JSONUtil.toJsonStr(obj)对非string类型有问题

### ISSUE THREAD

**Issue by DkAlsace** [looly/hutool#954]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）
5.2.4
### 问题描述（包括截图）
Long类型的toStr方法，结果是个空集合。“{}”
1. 复现代码
String str =JSONUtil.toJsonStr(1278529592130326531L)
sout("{}".equals(str));

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
是滴。此方法主要针对bean进行转换，你单独传一个Long，没有key，当然不行啊。

**Comment by DkAlsace** [comment]
ok，基本类型不支持是吧

**Comment by looly** [comment]
你基本类型怎么转换成JSON？期望转换后的内容是？

**Comment by DkAlsace** [comment]
获得toString结果。作为redis的key生成工具。


| |
戴博奇
|
|
daiboqi_bs@163.com
|
签名由网易邮箱大师定制
在2020年7月6日 11:48，Golden Looly<notifications@github.com> 写道：

你基本类型怎么转换成JSON？期望转换后的内容是？

**Comment by looly** [comment]
那你应该直接调用toString，否则JSONUtil.toJsonStr如果直接获取toString的结果，得到的是一个非法的JSON。
