### ISSUE TITLE
JsonUtil判断json有问题

### ISSUE THREAD

**Issue by bluesmi** [looly/hutool#955]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
    public void fromJSONObject() {
        String str = "{1231311}";
        System.out.println(JSONUtil.isJsonObj(str));
    }
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
此方法并不是严格的格式判定，只是简单的判断是否为JSON字符串，用于区分XML字符串等其他格式。

**Comment by bluesmi** [comment]
能否提供高性能JSON合法性校验API？现有的简单判定不满足那些有{}、[]符号，但是并不是正确json格式的情况，如：[张三]号码[183]

**Comment by looly** [comment]
这个需要靠JSONUtil.parse方法解析判断了。

完整格式校验比较影响性能，因此校验完再解析就有性能浪费，还不如直接解析。
