### ISSUE TITLE
UrlQuery里的parse方法导致参数丢失

### ISSUE THREAD

**Issue by lid1987** [looly/hutool#956]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.8

### 问题描述（包括截图）
如果查询参数的值包含==号，则该值会丢失
1. 复现代码

```java
String queryStr = "a=1&b=111==";
        UrlQuery q = new UrlQuery();
        UrlQuery parse = q.parse(queryStr, Charset.defaultCharset());
        System.out.println(parse.toString());
```
输出结果：a=1&b=
b的参数111== 丢掉了，Base64后的参数是有可能以==结尾的

期望的结果：
可以正常解析出b的参数：111==

**Comment by looly** [comment]
![image](https://user-images.githubusercontent.com/1432613/87035288-b2545c00-c21b-11ea-9a36-63aee8dd76cc.png)

我这边输出正常啊，请确认你使用的是最新版本的hutool
