### ISSUE TITLE
[建议] session 调用查询不会自动关闭连接 希望加入文档中说明

### ISSUE THREAD

**Issue by freshgeek** [looly/hutool#959]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.1.1
hikari pool
pgsql

### 问题描述（包括截图）
在springboot 应用中,原有mysql hikari 数据源 需要同步pg数据库数据 , 因此采用hutooldb 同步

在使用dbUtil 直接查询分页后 
DbUtil.newSession(ds).pageForEntityList(Entity.create("xxx").set("update_time", ">= " + dateFormat), page, size);

过一段时间就发现连接超时 ,然后排查各种设置 ,
 
最后在hikari 中设置 连接泄露监听 发现 全部连接未关闭导致连接泄露

查看源码发现  pageForEntityList 中的回调 关闭连接 session 中 是空实现

	/**
	 * Session中不关闭连接
	 * 
	 * @param conn {@link Connection}
	 */
	@Override
	public void closeConnection(Connection conn) {
		// Session中不关闭连接
	}

希望在文档中说明这点 避免后人踩坑

**Comment by looly** [comment]
可以使用Db.use()

session为了事务是不自动关闭连接的。
