### ISSUE TITLE
【询问】请问有python实现的打算吗

### ISSUE THREAD

**Issue by fish267** [looly/hutool#960]
这套工具非常好，点赞！
请问有发布python工具类的打算吗？

**Comment by looly** [comment]
Python那么好用，还需要工具么，哈哈。


Python我不熟，暂时不考虑哦。

**Comment by monyuan** [comment]
我也想问问，我发现此工具类的base64和aes python都解不了

**Comment by looly** [comment]
Base64都是通用的啊，AES定义好Mode和Padding保持一致即可。

**Comment by looly** [comment]
Base64:

```python
import base64

str = base64.b64decode(base64)
```

**Comment by monyuan** [comment]
System.out.println(Base64.decode("UITUld9wCpDmllNp3/MdGg=="));
打印：[B@33c7353a

import base64

str = base64.b64decode("UITUld9wCpDmllNp3/MdGg==")
转str打印：P�ԕ�p
��Si��

**Comment by looly** [comment]
你这解码之后的数据又不是字符串。

随便找个在线解码试下。
