### ISSUE TITLE
ZipUtil工具类 ZipOutputStream 不应该在循环中调用 finish

### ISSUE THREAD

**Issue by xeyn** [looly/hutool#961]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9

### 问题描述
ZipUtil 类的方法 zip (ZipOutputStream zipOutputStream, boolean withSrcDir, FileFilter filter, File... srcFiles),  代码第 231 行在 for 循环中调用了 finish 方法, 当 srcFiles 为数组时只有第一个文件被写入到zip流.  应当在所有文件写入完成后才调用 finish, 也就是在 for 循环外调用.

         ```
         try{
             for (File srcFile : srcFiles) {
                  ```
                 zipOutputStream.flush();
                 zipOutputStream.finish();  // Line 231: 此行代码应放在 for 循环外
              }
         } catch (IOException e) {
             throw new IORuntimeException(e);
         }

**Comment by looly** [comment]
确实，确认bug，感谢意见。
