### ISSUE TITLE
http工具在SSL情况下是否存在内存泄漏

### ISSUE THREAD

**Issue by mySamInZK** [looly/hutool#964]
### 版本情况

JDK版本：    1.8.0_201
hutool版本： 4.5.1

### 问题描述（包括截图）

1.使用hutool的http工具，内存中大量驻留SSLSocketImpl对象，无法被gc
2.使用场景。调用微信支付

**Comment by looly** [comment]
请升级到5.3.9，新版本这个对象使用了单例。
