### ISSUE TITLE
jsonobject序列化问题

### ISSUE THREAD

**Issue by Jayden-Rocky** [looly/hutool#965]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

List<Message> messageList  = ........
JSONObject result = new JSONObject();
result.put("messageList",messageList);
result.put("unReadCount",unReadCount);

class Message{
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;
}

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

不能正确进行日志序列化

**Comment by TrReMix** [comment]
JsonFormat注解应该是Jackson的注解 这边肯定不能识别啊

**Comment by Jayden-Rocky** [comment]
但是fastjson是可以识别的。
或者hutool有什么序列化的注解吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 下午4:21
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"风"<785923055@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] jsonobject序列化问题 (#965)





 
JsonFormat注解应该是Jackson的注解 这边肯定不能识别啊

**Comment by looly** [comment]
Hutool没有注解，可以用setDateFormat

**Comment by Jayden-Rocky** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 下午4:24
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"风"<785923055@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] jsonobject序列化问题 (#965)





 
Hutool没有注解，可以用setDateFormat

**Comment by Jayden-Rocky** [comment]
好的好的 谢谢！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 下午4:24
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"风"<785923055@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] jsonobject序列化问题 (#965)





 
Hutool没有注解，可以用setDateFormat
