### ISSUE TITLE
建议增加解析字符串表示的数据大小工具类

### ISSUE THREAD

**Issue by tonnyyi** [looly/hutool#967]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

项目中会有对文件或者数据大小进行限制的需求, 比如: 上传文件大小不超过`3M`, 一般我们是先将3M转成`3145728`(3\*1024\*1024)后, 保存到配置文件, 但这种写法很不直观. 而spring从5.1开始增加了一个`org.springframework.util.unit.DataSize`类, 可以直接调用`parse("3M")`得到实际字节长度.

因此建议参考该类, 增加一个`DataSizeUtil`工具.

**Comment by looly** [comment]
5.3.10加入DataSize，感谢。
