### ISSUE TITLE
邮件工具的说明文档https://hutool.cn/docs ，关于SSL部分，starttlsEnable 实际为startttlsEnable 。导致debug才找到。。按这文档怎么配都不对

### ISSUE THREAD

**Issue by li709854423** [looly/hutool#969]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
starttlsEnable是对的，`startttlsEnable`是拼写错误，后来修正了。

请升级Hutool到最新版本。

**Comment by li709854423** [comment]
哭了。。我上次才更了一次最新版。更新频率贼高





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 上午9:00
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"李思颖"<li709854423@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] 邮件工具的说明文档https://hutool.cn/docs ，关于SSL部分，starttlsEnable 实际为startttlsEnable 。导致debug才找到。。按这文档怎么配都不对 (#969)





 
starttlsEnable是对的，startttlsEnable是拼写错误，后来修正了。
 
请升级Hutool到最新版本。

**Comment by li709854423** [comment]
不好意思。。两个项目没想到这个项目用的版本太老了。不好意思了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "looly/hutool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 上午9:00
收件人:&nbsp;"looly/hutool"<hutool@noreply.github.com&gt;;
抄送:&nbsp;"李思颖"<li709854423@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [looly/hutool] 邮件工具的说明文档https://hutool.cn/docs ，关于SSL部分，starttlsEnable 实际为startttlsEnable 。导致debug才找到。。按这文档怎么配都不对 (#969)





 
starttlsEnable是对的，startttlsEnable是拼写错误，后来修正了。
 
请升级Hutool到最新版本。
