### ISSUE TITLE
文档有通假字

### ISSUE THREAD

**Issue by ly-chn** [looly/hutool#970]
https://www.hutool.cn/docs/#/core/%E5%B7%A5%E5%85%B7%E7%B1%BB/%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%B7%A5%E5%85%B7-StrUtil?id=_6-%e5%ae%9a%e4%b9%89%e7%9a%84%e4%b8%80%e4%ba%9b%e5%b8%b8%e9%87%8f

是转义字符吧

**Comment by looly** [comment]
稍后修改，感谢。
