### ISSUE TITLE
SoapClient 调用疑问

### ISSUE THREAD

**Issue by DreamsCat** [looly/hutool#972]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
我想知道这种怎么进行调用？

```xml
<soapenv:Envelope xmlns:bod="http://xxx1" xmlns:sch="xxx2">
   <soapenv:Header/>
   <soapenv:Body>
      <bod:InvokeBODATCON3ByRemote>
         <bod:mBOParaSchema>
            <sch:userName>xxx</sch:userName>
         </bod:mBOParaSchema>
      </bod:InvokeBODATCON3ByRemote>
   </soapenv:Body>
</soapenv:Envelope>
```

我现在想设置 sch:userName 的参数并且进行调用，我该怎么设置方法和命名空间，尝试了好几种方式都无法调用成功

**Comment by looly** [comment]
使用`public SoapClient setParam(String name, Object value, boolean useMethodPrefix) {`

其中useMethodPrefix传false即可。

**Comment by DreamsCat** [comment]
其实我主要疑问的点在于怎么设置方法，目前来说是有 bod:InvokeBODATCON3ByRemote 和 bod:mBOParaSchema 两个方法，那我该怎么设置，调用两次 setMethod 并设置命名空间吗？那 <sch:userName>xxx</sch:userName>，其中 sch 也有命名空间，那该怎么设置呢

**Comment by looly** [comment]
多层嵌套只能传XML文本了，或者调用getMethodEle方法获取XML节点，自行添加节点。

**Comment by DreamsCat** [comment]
我的调用代码：
`SoapClient client = SoapClient.create("http://xxx?wsdl")
                .setMethod("bod:InvokeBODATCON3ByRemote ", "http://xxx1")
                .setMethod("bod:mBOParaSchema", "http://xxx1)
                .setParam("userName", "1", false)；`

这样好像并不行
