### ISSUE TITLE
是否有Apache commons StringSubstitutor 替换占位符的方法？

### ISSUE THREAD

**Issue by joey-happy** [looly/hutool#973]
![image](https://user-images.githubusercontent.com/16012082/87894170-8a16f980-ca74-11ea-8080-7d7fce223ff7.png)

Map valuesMap = HashMap();
valuesMap.put("animal", "quick brown fox");
valuesMap.put("target", "lazy dog");
String templateString = "The ${animal} jumped over the ${target}.";
 
StrSubstitutor sub = new StrSubstitutor(valuesMap);
String resolvedString = sub.replace(templateString);

**Comment by joey-happy** [comment]
参考链接：https://blog.csdn.net/weixin_41888813/article/details/90481607

**Comment by joey-happy** [comment]
最好是可以传map 也可以 传任意对象

**Comment by looly** [comment]
可以使用`StrUtil.format`
