### ISSUE TITLE
ExcelWriter使用建议

### ISSUE THREAD

**Issue by daozhongliu** [looly/hutool#976]
### 版本情况

JDK版本：   jdk_1.8.0_112
hutool版本： 5.3.7（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

在使用ExcelWriter的时候，遇到一些问题，有点小建议：能否将isCLosed通过getter暴露出来，还有closeWithoutFlush能否修改为public。因为我的的业务逻辑，写出excel之后还要上传ftp，又不太方便写成2个try{}catch{}，这就导致，我的try里面有excelWriter.close()，为了避免后续操作产生的错误导致excelWriter不释放内存，我又必须在catch或者finally里面再进行一次excelWriter.close()，这个时候我无法得到excelWriter是否已经closed，在try里面已经执行过close方法的时候直接调用close方法会直接将之前的文件清空成0字节。。。。。。

**Comment by daozhongliu** [comment]
目前我是写了2个try{}catch{}来解决
       try {
            // 生成xls
            writer = ExcelUtil.getWriter(filePath);
            // 设置sheet名称
            writer.renameSheet("详情");
            writer.writeHeadRow(HEAD_TITLES);

            // 开始查询
            XxlJobLogger.log("start query OLT active alarms ...");
            List<EventModel.Msg> activeOLTAlarms = queryActiveOLTAlarms(startTime, stopTime);
            XxlJobLogger.log("OLT active alarms [{}]", activeOLTAlarms.size());
            writeToExcelFile(writer, activeOLTAlarms);
            XxlJobLogger.log("write OLT active alarms end");

            // 写出到文件，并关闭log
//            writer.close();
//            XxlJobLogger.log("write to file end");
        } catch (Exception e) {
            XxlJobLogger.log("出错，{}", e.getMessage(), e);
            return ReturnT.FAIL;
        } finally {
            if (writer != null) {
                // 不能放到finally里面，重复close会导致之前得到文件变成0字节。
                // 理论上应该使用 isClosed  closeWithoutFlush  但都是 protected
                try {
                    writer.close();
                    XxlJobLogger.log("write to file end");
                } catch (Exception ignore) {
                }
            }
        }

        try {
            // 上传
            XxlJobLogger.log("start upload ftp file ...");
            ftp = new Ftp(ftpConfigBean.getHost(), ftpConfigBean.getPort(), ftpConfigBean.getUsername(), ftpConfigBean.getPassword());
            ftp.upload(ftpConfigBean.getRemotePath(), fileName, new File(filePath));
            XxlJobLogger.log("upload ftp file end");

            XxlJobLogger.log("结束，耗时:" + (System.currentTimeMillis() - currMM) + "ms.");
            return ReturnT.SUCCESS;
        } catch (Exception e) {
            XxlJobLogger.log("出错，{}", e.getMessage(), e);
            return ReturnT.FAIL;
        } finally {
            if (ftp != null) {
                try {
                    ftp.close();
                } catch (Exception ignore) {
                }
            }
        }

**Comment by looly** [comment]
你可以调用getWriter(true)不指定路径，然后可以在try里手动调用flush(path)方法，即可完成写出，最后在finally里close掉即可
