### ISSUE TITLE
StrUtil.removeAny有bug

### ISSUE THREAD

**Issue by xu1990119** [looly/hutool#977]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.9（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

StrUtil.removeAny("aa-bb-cc-dd", "a", "b") 实际输出是aa--cc-dd 不是--cc-dd

![image](https://user-images.githubusercontent.com/15828159/88151373-3273bc00-cc35-11ea-979a-42787addabcb.png)
这里有bug

**Comment by looly** [comment]
确认bug，感谢。
