### ISSUE TITLE
BeanUtil.copyPropertiesNotNull

### ISSUE THREAD

**Issue by bigbeef** [looly/hutool#983]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

建议拓展一个方法BeanUtil.copyPropertiesNotNull

**Comment by looly** [comment]
BeanUtil.copyProperties提供了CopyOptions参数，可以设置是否忽略null
