### ISSUE TITLE
小小的困惑：关于hutool-all和hutool-bom

### ISSUE THREAD

**Issue by kanghouchao** [looly/hutool#987]
### 版本情况

JDK版本:
hutool版本：5.3.9

### 问题描述（包括截图）

从现在代码看，hutool-all和hutool-bom似乎没有区别

hutool-bom的依赖应该要加一层dependencyManagement:
```xml
<dependencyManagement>
   <dependencies...>
</dependencyManagement>
```

然后，就可以这样用了？
```xml
          <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
还是我理解错了？

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
all和bom区别如下：

all将所有模块打包成一个jar，因此在你的项目中只有一个hutool-all的jar包，你也无法选择去除哪些模块。

bom则是默认引入所有模块，你可以通过exclude标签排除不需要的模块，减少整个项目体积。

**Comment by hhw3KevinHou** [comment]
直接用all，省事
