### ISSUE TITLE
excel 合并单元格操作建议

### ISSUE THREAD

**Issue by GungnirLaevatain** [looly/hutool#989]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.2.2

### 问题描述（包括截图）
https://github.com/looly/hutool/blob/1f19a31c5ae205f10f807c97adadcc88ebceaa0c/hutool-poi/src/main/java/cn/hutool/poi/excel/cell/CellUtil.java#L316

POI 4.1.2 有提供addMergedRegionUnsafe这个不包含校验的方法以提供单元格合并性能

**Comment by looly** [comment]
考虑到3.x的POI用户，新的方法暂时不加入。
