### ISSUE TITLE
用了4.0.7以上版本后HttpUtil.post方法出现问题

### ISSUE THREAD

**Issue by CodinngLee** [looly/hutool#99]
使用4.0.7以上版本后，接口方返回错误提示"A JSONObject text must begin with '{' at character 0 of 
json请求体 {"head":{"sysname":"xx","flow":"32015efc-9394-49b5-ad06-d9e17a66cbd1"},"body":{"codeNumbers":[{"codeNumber":"xxxxxxx"}]}}
HttpUtil.post(api, json请求体); 

使用HttpUtil.createPost(apiFdNumber).body(requestBody, "application/json").execute().body();则正常

经测试过，4.0.7版本则不会有上面的问题。

**Comment by looly** [comment]
确认bug。是因为在自动判断Content-Type时加了已有Content-Type存在的判断。此问题在下个版本（4.0.11）中修复。十分感谢。
