### ISSUE TITLE
DateUtil可否增加传入自定义时间格式数组的方法

### ISSUE THREAD

**Issue by phoema** [looly/hutool#993]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.X.X（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
DateUtil可否增加传入自定义时间格式数组的方法
方便开发人员灵活使用。
类似
org.apache.commons.lang3.time
Date parseDate(final String str, final String... parsePatterns)

我们希望能够少引用一个公共包。

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
5.3.11增加DateUtil.parse重载方法。感谢。
