### ISSUE TITLE
关于封装字符串转义的功能询问

### ISSUE THREAD

**Issue by ViCrack** [looly/hutool#994]
### 版本情况

JDK版本：    jdk 8
hutool版本： 5.3.10

### 问题描述

找了一下Hutool似乎没有专门封装转义单引号双引号等的功能? 类似org.apache.commons.lang3.StringEscapeUtils中所做的事情.

如果没有的话, 考虑加上去吗

**Comment by looly** [comment]
Hutool里这些封装在EscapeUtil中。

**Comment by ViCrack** [comment]
> 
> 
> Hutool里这些封装在EscapeUtil中。


![图片](https://user-images.githubusercontent.com/18179821/89115747-53060680-d4be-11ea-9d7a-07d8d0b5c836.png)

可能是有点误解, 我EscapeUtil有找过, 看起来它的功能是转化成%xx格式的字符编码, 没有StringEscapeUtils escapeJava之类的功能


![图片](https://user-images.githubusercontent.com/18179821/89115813-2b636e00-d4bf-11ea-977e-7ed9b715c986.png)

**Comment by ViCrack** [comment]
![图片](https://user-images.githubusercontent.com/18179821/89300170-5fdf5180-d69a-11ea-80fc-12e67a989ab8.png)
@looly 不知道能不能看到

**Comment by looly** [comment]
EscapeJava没有封装。

**Comment by ViCrack** [comment]
作者有空有计划考虑封装下不？ 代替apache的EscapeJava、EscapeJavaScript、EscapeXXXX
