### ISSUE TITLE
合并单元格设置边框有问题

### ISSUE THREAD

**Issue by 306495389li** [looly/hutool#995]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 5.3.10（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
设置合并单元格1到4并设置单元格无边框，6到8列也被设置无边框
![image](https://user-images.githubusercontent.com/15187323/89145610-e81f0300-d583-11ea-8819-ae088b8d0cd9.png)

1. 复现代码
CellStyle cellStyle = writer.getCellStyle();
      cellStyle.setBorderLeft(BorderStyle.NONE);
      cellStyle.setBorderTop(BorderStyle.NONE);
      cellStyle.setBorderRight(BorderStyle.NONE);
      CellUtil.mergingCells(writer.getSheet(), 0, 0, 1, 4, cellStyle);

**Comment by looly** [comment]
writer.getCellStyle();是一个共享的style，因此你应该使用一个新建的style。

你应该这么创建style：
```java
writer.getWorkbook().createCellStyle();
```

**Comment by 306495389li** [comment]
![image](https://user-images.githubusercontent.com/15187323/89164694-fb44c980-d5a9-11ea-9ef4-b77f390cbb69.png)
这么chuang创建的没有效果的

**Comment by 306495389li** [comment]
CellStyle cellStyle = writer.getWorkbook().createCellStyle();
      cellStyle.setBorderLeft(BorderStyle.NONE);
      cellStyle.setBorderTop(BorderStyle.NONE);
      cellStyle.setBorderRight(BorderStyle.NONE);
      CellUtil.mergingCells(writer.getSheet(), rowNum, rowNum, 1, 4, cellStyle);
