### ISSUE TITLE
cn.hutool.core.io.FileUtil

### ISSUE THREAD

**Issue by MrChocol** [looly/hutool#997]
### 版本情况

JDK版本：    openjdk_8_201
hutool版本： 4.1.19

### 问题描述（包括截图）
- 如果是创建不存在的文件的话if (false == file.exists())这个方法会直接跳过导致文件没有创建成功，不清楚这个判断的意义是什么呢？
![ERTPDSQ2_}H7A9DWNQK%686](https://user-images.githubusercontent.com/39512573/89243002-71424280-d635-11ea-9305-ccec9c667128.png)

1. 复现代码

```java
Console.log("报错了");
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

比如报错的Excel文件，有问题的图片等。

**Comment by looly** [comment]
逻辑没问题啊：

false == file.exists()表示文件或者父目录不存在，然后执行if内的逻辑，创建父目录和文件。
